### ISSUE TITLE
Quest [Battling the Elements] 

### ISSUE THREAD

**Issue by Fixed7** [SunwellTracker/issues#1000]
Decription: 
During the quest, you are supposed to kill 10 Seething Revenants with an Ice Giant.

How it works: 
You wait around the anvil, they take upwards to 8 minutes to spawn, and you have to kill 10 of them. This results in a quest that takes almost half an hour which is not acceptable.

How it should work: 
Everything works fine except the spawn time. They should spawn a lot faster. I saw several people patiently waiting there, and all of them were complaining.

Source (you should point out proofs of your report, please give us some source): 
Talked to GM Tide about it. Did the quest myself today.

**Comment by Cwiercpasiec** [comment]
Duplicate #940
