### ISSUE TITLE
Quest [The Delicate Sound of Thunder]

### ISSUE THREAD

**Issue by V5killer** [SunwellTracker/issues#1001]
Decription: 
First you have to use Work Bench in the Explorers' League to become Iron Rune Construct, after that
you have to go inside a cave in the cliffside in the Howling Fjord and listen to a hologram message

How it works: 
When you enter the cave all npcs inside and around the entrance disapear, after few seconds you are teleported back in the place where elveator is changing back to your character, mostly dying from fall dmamage.

How it should work: 
You are supposed to go inside that cave and listen to hologram message

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/192
