### ISSUE TITLE
[Death Knight] [DK] Death Grip underwater bug

### ISSUE THREAD

**Issue by thanhtotti** [SunwellTracker/issues#1002]
Description: 
Using Death Grip underwater didn't pull the target to the Death Knight location but the bottom of the water medium (lake, sea, river)

How it works: 
Using Death Grip underwater didn't pull the target to the Death Knight location but the bottom of the water medium (lake, sea, river). This position is exactly below the death knight position. 

How it should work: 
Death Grip should pull the target toward the Death knight.

Source (you should point out proofs of your report, please give us some source): 
[Video](https://www.youtube.com/watch?v=HagwN6ZCdwc) of a Death Knight using Death Grip underwater (Cataclysm expansion, but how DG works remain the same)
Issue #101

**Comment by Rosenkrantz** [comment]
Probably a wider issue regarding height positioning, using Blink underwater also teleports the mage to the bottom.

**Comment by Avarishd** [comment]
https://www.youtube.com/watch?v=nqxCIWaQN20
