### ISSUE TITLE
NPC: Dreghood Brute

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1004]
Decription: They are not working as they are suposed to.

How it works: When you attack Illidare Taskmaster, they don't do anything, they just remain on same position.

How it should work: Once you attack the Taskmaster they should attack with him and obey his orders, also once you kill taskmaster they should runaway and become neutral to you.

Source (you should point out proofs of your report, please give us some source): 
![dreghood](https://user-images.githubusercontent.com/37425406/37647040-9a17592c-2c2b-11e8-8973-068e3ce98c7f.png)

**Comment by Dootz** [comment]
will be fixed with next server update
