### ISSUE TITLE
[warlock]  Curse of Agony

### ISSUE THREAD

**Issue by windrunner73** [SunwellTracker/issues#1005]
Decription: 
Must have something wrong with curse of agony's damage.

How it works: 
When you observe every dot's damage when using curse of agony under Affliction spec, you'll find each dot's damage does not always right. Sometimes latter dot's damage is less than former one.

How it should work: 
Curse of agony's next dot's damage should be higher than former dot's, **according to description.** 

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
