### ISSUE TITLE
[Warrior] [Ability] Slam doesn't suspend swingtimer

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#1006]
Decription: 
Currently your swingtimer keeps going while slamming

How it works: 
slam at 1.5 seconds left of swing and when slam finishes it will do slam AND the auto-attack at the same time as if it never paused

How it should work: 
Swingtimer should be paused when slamming, you can see this is built into quartz addon aswell

Source (you should point out proofs of your report, please give us some source): 
Wrath of the Lich King Patch 3.0.2 (2008-10-14): Slam now suspends the weapon swing timer rather than resetting it.
https://streamable.com/bwxcf
#582 continuation but you never re-opened it so i guess i have to make a new issue.

**Comment by set-theorist** [comment]
Can confirm, this is the original state the spell was in since launch of server. They fixed swing resetting but now the slam doesn't pause swing. 

Particularly helpful in some situations in pvp where you proc improved/glyphed hamstring and can time your slam to come off at same time as autoattack.
