### ISSUE TITLE
Crusader on heirloom weapon (venerable dal'rend's sacred charge)

### ISSUE THREAD

**Issue by Protectaur** [SunwellTracker/issues#1007]
Decription: 
When you apply cursader on this heriloom sword, it never proceed.
I did 2000+ hits and no any effect has occured (no heal, no stregth gain).
Can you please check if it is problem of just this weapon or just crusader do not work as it should (5-15% chance to get the effect).

How it works: 
it dont

How it should work: 
should proceed by formula (weapon speed * 1,8, or similar).

Source (you should point out proofs of your report, please give us some source): in game experience, leveling from 8-14 with applied crusader - no procs.. Ty ahead for solution!. BR

**Comment by ujellyx** [comment]
"At low levels (e.g. level 9) Crusader procs very rarely. Its not known at what level the standard proc rate takes effect."

http://wowwiki.wikia.com/wiki/Enchant_Weapon_-_Crusader
