### ISSUE TITLE
Bug with saronite vein.

### ISSUE THREAD

**Issue by amalirr** [SunwellTracker/issues#1009]
Decription: In Icecrown there is one saronite vein, which is under the textures and there is no possibility of digging it up.

How it works: You can not dig up the vein, since it is under the textures.

How it should work: The vein should be above the textures!

Source (you should point out proofs of your report, please give us some source): have screenshoot with the location of the problem vein
![bugged saronite vein](https://user-images.githubusercontent.com/37587393/37662942-c19e7674-2c8a-11e8-8bcd-8cfd5d622510.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
