### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by Kiaa19931224** [SunwellTracker/issues#1011]
Decription: 

When drink the Noggenfogger Elixir and you transformed Skeleton, you can't mount, "You are in Shapeshift Form" .
How it works: 

How it should work: 

You can ride on mount when you are drink Noggenfogger Elixir and you are a skeleton.

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
You posted no proof supporting your claim and besides, no, you shouldn't be able to mount while in skeleton form.
