### ISSUE TITLE
Detterence not reflecting if the spell is in the air

### ISSUE THREAD

**Issue by SiguDS** [SunwellTracker/issues#1012]
Decription: 

How it works: Detterence is not deflecting spells if they are in the air. Which makes it a lot worse than it should be

How it should work: Detterence should deflect spells EVEN if they are in the air.

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
Proof?

**Comment by SiguDS** [comment]
Will update post when i get the time to dig something up

**Comment by SiguDS** [comment]
I was wrong
