### ISSUE TITLE
Diremaul east impossible Whip Lasher's

### ISSUE THREAD

**Issue by Ehtaa** [SunwellTracker/issues#1013]
Decription: 
Diremaul east: Whip lasher named trash hits 300 - 600 dmg to prot warrior tank with full plate gear.

How it works: 
Im doing dungeon run in diremaul and we wipe to these whip Lasher's (they are plants in grp), they hit way too hard at this lvl. It have to be bug.. they are not even elites and they hit harder than diremaul bosses.. 

How it should work: 
Gid gud they have to hit less than 300dmg per hit... they are in 4 -6trash packs..
![wowscrnshot_032018_234215](https://user-images.githubusercontent.com/37599125/37684338-6398d6d8-2c98-11e8-8a89-d9353cd928bf.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
