### ISSUE TITLE
ADDON: Auctionator

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1015]
Decription: Auctionator addon  found from the Sunwell official addon site isn't working as intended.

How it works: Selling works fine, but "Buy" tab doesnt work atall, shows completly different and outdated data, also Full scan option doesnt work atall, so can't scan and colect proper data.

How it should work: Once you click on the "Full scan" option it should scan the Auction house and provide you with proper data, and for "Buy tab" it should sort things out and show proper items listed with their current prices.
![auctionator](https://user-images.githubusercontent.com/37425406/37689769-583c8b40-2ca7-11e8-9772-3b9d387dfae3.png)
![bug1](https://user-images.githubusercontent.com/37425406/37689770-58bb2414-2ca7-11e8-98bf-6868d8e31f1f.png)
![bug2](https://user-images.githubusercontent.com/37425406/37689771-58eb871c-2ca7-11e8-9190-9ce7d5e13d6d.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by knasen88** [comment]
i use auctionator and everything works except full scan, cos its disabled serverside

**Comment by Vessler** [comment]
Well dang. it doesnt provide proper data and it doesnt sort things out for me like it should since it cannot do full scan properly...

**Comment by Unbugable** [comment]
Browse tab isn't from auctionator addon.
