### ISSUE TITLE
[Pets] Combat issue

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#1017]
Decription: 
Player pets, upon performing a hostile action on an enemy player or NPC should put the owner of the pet in combat. All player pets should behave this way.

How it works: 
Currently, performing hostile actions with pets do not put the owner of the pet in combat.

How it should work: 
Performing any hostile action with a pet should put the owner in combat (be it a spell, ability or simply attacking).

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Seduction (Type: offensive, utility)
https://wow.gamepedia.com/Gnaw (Type: offensive)
https://wow.gamepedia.com/Bite (Type: offensive)

http://wowwiki.wikia.com/wiki/Combat (Actions that will get you into combat: casting an offensive spell)

**Comment by Shatterx** [comment]
"Source (you should point out proofs of your report, please give us some source):"

**Comment by Azathothh** [comment]
#134
