### ISSUE TITLE
[Nibelung] Random Target

### ISSUE THREAD

**Issue by siggall** [SunwellTracker/issues#1018]
**Decription:** 

> Equip: Your harmful spells have a chance to cause you to summon a Val'kyr to fight by your side for 30 sec.

Val'kyr's after summon, start attack random target and after kill that target don't change him.

> **How it works:** 

Nibelung summon val'kyr's and she start attack random target, after kill that target don't swap on any alive target in combat
> **How it should work:** 

Summoned Val'kyr's start attack target by target player and after kill that target swap target on any alive in combat.

> Val'kyr target the mob that caused the proc (not based on your aggro). If the target dies, they will wait and attack the next target you deal damage to, whether directly or indirectly. Thus, they will never randomly target mobs and break CC. If a Val'kyr appeared to break a CC, look to the master of the Val'kyr instead.

All fixes on Val'kyr's from Nibelung

> 2% proc rate with no internal CD. There is no limit on the number that can be out at one time.
Spawn with 12,600 health and no mana bar.
Heal themselves for 25% of the damage they deal.
Cast smite (holy damage) an average of 16.6 casts per summon or an instant cast every 1.81 seconds. The actual GCD of the val'kyr is probably 1.35 seconds and 0.45-0.5 additional seconds are added from server delay/lag. (It's the same affect that raises a water elemental's cast time from 2.5 up to 2.95-3.0 seconds.)
Deal 1591 - 1785 damage, 5% crit chance, 1.5 crit multiplier, and hit capped.
They do not scale with your stats.
Benefit from curse of elements, but not arcane empowerment, ferocious inspiration, or sanctified retribution.
Benefit from +5% spell crit debuff from imp. scorch, imp. shadowbolt, and winter's chill and all other boss debuffs.
Benefit from the spell haste buffs from wrath of air and imp. moonkin aura/swift retribution.
Val'kyr proc off living bomb dot ticks and those from locks and priests. They do not proc off pyroblast or fireball's dot or ignite or any other dot that are an after-effect of a spell.
Arcane is horrible with this staff because it does not proc off each arcane missile, only at the onset of the channel. It interacts the same way with mind flay.
Proc off each spellcast of arcane explosion, each wave of blizzard, and the detonation of living bomb. It does NOT proc off each target hit.
Do not proc off waterbolt or mirror image spells.
Proc off molten armor.
Val'kyr target the mob that caused the proc (not based on your aggro). If the target dies, they will wait and attack the next target you deal damage to, whether directly or indirectly. Thus, they will never randomly target mobs and break CC. If a Val'kyr appeared to break a CC, look to the master of the Val'kyr instead.
Visually, they're an exact mini-replica of the white Val'kyr of the Twin Val'kyr encounter in ToC. Blizzard could have added an additional rarity to each staff by making half spawn only white and half spawn only black Val'kyr. Oh well...
To get the most from the Val'kyr, stand between 10 and 30 yards. If outside that range, the Val'kyr will fly around a bit until in minimum/maximum range and eat away at the 30 seconds it's summoned. It's worth noting for pvp that once the Val'kyr is in minimum range, it won't need to readjust if the target moves closer than 10 yards until a new target is acquired.
Val'kyr obey the commands you give to your pets.
For a reason unknown (and it might very well be unintentional), talenting for fingers of frost and imp. blizzard is triggering this staff at an exceptional rate. If you're a mage, you will get a kick out of running with this staff at least once as frost for AoE jobs in raids because of the huge number of Val'kyr that will spawn, and you'll also be able to control them with your pet. Your raid will enjoy them as well.

Source (you should point out proofs of your report, please give us some source):

**Comment by bongobg** [comment]
From what I saw with my Nibelung the Valkyrs not only choose a random target but they also switch randomly targets mid-fight. It's hard to explain how they behave but it's all totally weird. I got ~100k dmg from them in 11 minute fight if you need some numbers for reference. And I can say the multi-spawning thing works because at some points I had 3 spawns. The smite damage seems correct too.

**Comment by aleksandr073** [comment]
I confirm it

**Comment by ludozyad** [comment]
Nice involvement from sunwell staff. This item was best in slot item for couple of classes before the bug. Now, from over a year (when this topic was created) nibelung is almost useless.
