### ISSUE TITLE
Argent Priestess.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1019]
Decription: http://myprintscreen.com/s/1521663737.05782098.png After getting mind control on tank i was unable to attack other priestesses.

How it works: Theres Invalid Target when im trying to attack her.

How it should work: I should be able to attack them.

Source (you should point out proofs of your report, please give us some source): 
http://myprintscreen.com/s/1521663737.05782098.png
http://www.wowhead.com/npc=35307/argent-priestess

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/437
