### ISSUE TITLE
[Q] Iron Rune Constructs and You: The Bluff.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1020]
Decription: Quest need some fixes with "catching" player stepping into Rug. In some cases Lebronski dont even try to cooperate. In other cases he start talking, but he dont want to complete our quest. Cant find why hes not always responding to us.
I finally made it after about 30minutes of trying. 30minutes for quest that should be finished in 30secs.

How it works: Up.

How it should work: That should be simple quest, got robo disguise, stand on rug, and use 1 to bluff Lebronski. He should start talking then complete the quest.

Source (you should point out proofs of your report, please give us some source): 

http://www.wowhead.com/quest=11491/iron-rune-constructs-and-you-the-bluff

**Comment by Dootz** [comment]
will be fixed with next server update.
