### ISSUE TITLE
Egg of mortal essence (40Heroism emblem trinket)

### ISSUE THREAD

**Issue by xblazze** [SunwellTracker/issues#1022]
Decription: Your Direct heals and heals over time have a chance to proc 505 haste for 10 seconds.

How it works: This trinket does not proc from direct heal from affliction warlocks when using Siphon Life, Health Funnel or Fel Armor procs as a warlock
Reproduce this bug by using an affliction warlock's Health funnel and have Fel Armor on for the heal ticks with the trinket equiped.

How it should work: When you use Siphon Life ,Health Funnel or Fel Armor heal ticks it should have a chance to proc but it never procs.

This used to be a trinket for those never lucky to get maexxna 10man trinket which is the same but it procs from damage abilties.

Source (you should point out proofs of your report, please give us some source):

https://i.imgur.com/CxqyGiP.jpg

**Comment by Semper-Numquam** [comment]
http://www.wowhead.com/forums&topic=114333/the-egg-of-mortal-essence

http://wowwiki.wikia.com/wiki/The_Egg_of_Mortal_Essence
" This item can no longer be triggered by Life Tap."

Drain Life, Fel Armor ticks, Siphon Life, Haunt and Life Tap, among the other lock spells are not considered healing spell or heal over time spells, they are considered drain/regen effects that while they give HP, do not count as healing spell casts and thus cannot proc this item.
