### ISSUE TITLE
[Fishing] Skill-up System is chance based (not blizzlike)

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1023]
Decription: 
The way you currently get fishing levels is completely random while blizzlike fishing system gives set amount of fishing XP per successful cast.

How it works: 
Getting skill ups from fishing seems to be **based on chance** right now. The higher level fishing skill is, the lower your chance to level up. This means that you can go on for a really long time without skilling up if you get unlucky, or skill up very fast if you get lucky:
https://i.imgur.com/NNQ3Abh.jpg

How it should work: 
Fishing should **NOT** work like other professions. There is a **fixed** amount of 'fishing XP' you get after every successful catch. First 75 levels of fishing skill, the XP is enough for 1 skill up per catch. Next 75 it's 2 catches for skill up, etc.

You are guaranteed to skill up if you have successfully caught items (even junk) X amount of times (decided by your fishing level) using this formula:

( {Current Skill Level} - 75 ) / 25 = Approximate number of fish you need to catch to gain one fishing skill point.

Source (you should point out proofs of your report, please give us some source): 
1) http://wowwiki.wikia.com/wiki/Fishing?oldid=2335620  <-- Scroll down to "Increasing fishing skill" section.

2) I have 1000 fish achievement + lot more fish caught, and my skill is not even 300. The table in the above link shows I should have **at least 310 skill with just 1000 fish caught**. This has a real impact on fishing and makes it a LOT more grindier.

**Comment by seriess** [comment]
I can confirm this. On every server I have played on and even retail, fishing has never been this grindy.

**Comment by TheBigBallsOfFury** [comment]
Actually most TC servers have it working like this (incorrectly) which is a real bummer.
