### ISSUE TITLE
[Quest]Frostmane Hold

### ISSUE THREAD

**Issue by gambit57** [SunwellTracker/issues#1025]
Decription: [Quest](http://db.darkwizard.pl/?quest=287) wymaga zabicia 5 [mobów](http://db.darkwizard.pl/?npc=1123) oraz odkrycia terenu.
How it works: Część z mobami działa poprawnie, nie działa część z odkryciem terenu. Wyczyściłam całą jaskinię, której odkrycie powinno się zaliczyć .
How it should work: Po dotarciu do największej komory jaskini powinno zaliczać odkrycie "Fully explore Frostmane Hold".

**Comment by Dootz** [comment]
will be fixed with next server update
