### ISSUE TITLE
RET paladins dps

### ISSUE THREAD

**Issue by somethingxx** [SunwellTracker/issues#1027]
Decription: sometime in the last week ret paladins dps has been reduced some how and i dont know why or how last week i was doing 7k dps on patchwork this week i did only 5k dps noone understands why because everything looks the same on the recount can u please look back any patch notes or something to get this fixed.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
We got a few reports about this issue. 
Were there any changes to Ret Pallys in the past week or so?

**Comment by somethingxx** [comment]
apparently its because changed something with seal of Vengeance/Corruption?

**Comment by somethingxx** [comment]
http://www.worldoflogs.com/reports/s0n4nrf0gbxp0fnz/details/25/?s=5449&e=5653
http://www.worldoflogs.com/reports/y8hd5wpra96bg4wf/details/18/?s=549&e=743
u can see the damage diff i have alot better gear this week aswell so there should be more damage on some actions but seal of vengeance/corruption is messed up whatever u changed with it u need to change it back please.

**Comment by Afgann** [comment]
Yeah, it was the time when there was an unexpected bug with new implementation of seal of vengeance and it was proccing too much, everything is fine right now... closing

**Comment by somethingxx** [comment]
no its not fine i legit raided yesterday and it was still terrible? u cant just change a class? without telling anyone

**Comment by Afgann** [comment]
Because it was bugged that one day, and you were making more dps than you should, make a proper report or stop wasting time.

**Comment by somethingxx** [comment]
so ur saying its been wrong for the past 2 months of naxx? this is a proper report im doing 2k burst dps now can we actually talk properly?

**Comment by somethingxx** [comment]
https://gyazo.com/8032993368c3e9ea4eadaac5098f1afc this was updated on the 12th that u changed ret paladins seal and my raid was on the 14th so it was after the nerf so u have nerfed it again since then why is that not in the change logs please look at the dates.

**Comment by Afgann** [comment]
It was reverted, there aren't any changes at all.

**Comment by somethingxx** [comment]
if it was reverted why is my damage so much lower i used to do this damage when i first entered nax?

**Comment by Afgann** [comment]
You're actually the only guy that reported this, so i suppose you just got worse.

**Comment by somethingxx** [comment]
no im not why dont u take a look at the replys nadiir replied and shes a game master and said we have had many reports about this. just noone has bothered to report it on here do u not read the comments?

**Comment by Afgann** [comment]
Yeah, many reports... Because you're spamming everywhere.

**Comment by somethingxx** [comment]
https://cdn.discordapp.com/attachments/403345538986147842/426565889488322562/image.png this is another ret that has reported it and has nothing to do with me so thats not true atall now can u please not change classes without telling people

**Comment by somethingxx** [comment]
like ill keep making tickets until u actually fixed the shit u have done

**Comment by Cwiercpasiec** [comment]
@somethingxx  seems like you may have a problem with reportink a bug properly. Here is how to do it the right way: 
1. Report should be named in a way that would identify the problem at the first sight. You have to write what’s the problem about in square brackets (which raid, class, etc.). For example: [Warrior] Bladestorm, [Ulduar - Thorim] Adds deal too much damage, [Warsong Gulch] wrong flag respawn timer. 
So basically your report should start with [Paladin] Name of the Skill that is Bugged.

2. Every bug has to be described thoroughly. “Quest X doesn’t work” is simply not enough. You have to write what exactly is happening and what should happen.
In this exact case this point means, that "Ret dps is too low" is simply not enough. You should report which exact spell hit too low and why (too low ap coeff, no spell power coeff, some buffs not improving damage of given spell etc.)

3.Every bug should be reported with the following pattern:

        Decription:
        How it works:
        How it should work:
Now, your report is missing 2 last points, there is no "How it works" and "How it should work". Without this, there simply no way to fix this, nor even do some research.

Here you can read more about reporting bugs:
https://sunwell.pl/page/bugtracker
