### ISSUE TITLE
Mission: leave-no-one-behind

### ISSUE THREAD

**Issue by mayumayux** [SunwellTracker/issues#103]
Decription: 

http://www.wowhead.com/quest=12512/leave-no-one-behind

How it works: 

mobs dont count over quest

How it should work: 

http://www.wowhead.com/quest=12512/leave-no-one-behind

Source (you should point out proofs of your report, please give us some source): 

http://www.wowhead.com/quest=12512/leave-no-one-behind

I've escorted all 3 mobs, but as a result they just follow me and dont count over quest completion.

**Comment by Kokaina** [comment]
Probably u can't get credit while u are escorting those mobs mounted. 
Mounted players should get credit as well.

**Comment by bongobg** [comment]
Confirm - this is a bug all over private servers scene. You can't get credit if you mount and also you can't get credit if the npc enters combat during the escort (i'm not sure if the combat part is for all of them but i know for the southern one).

**Comment by cuntdestroyer69fuckyou** [comment]
Confirm, does not work while mounted.. (you don't get the debuff) but then I tried to do it dismounted and it STILL doesn't work. I get the debuff 3m timer but no credit for running her back to the camp.

**Comment by artemmavrich** [comment]
1) DON’T mount
2) DON’T fight and avoid NPC fight

**Comment by Dootz** [comment]
will be fixed with next server update
