### ISSUE TITLE
Utgarde Pinnacle Normal reputation

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1030]
Decription:  Utgarde Pinnacle normal doesn't give reputation.

How it works: no reputation in normal mode. With or without tabard.

How it should work:   Should be Expedition rep w/o tabard and selected rep w/ tabard, like other l80 normals (CoS, HoL, Oculus).

Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/item=43154/tabard-of-the-argent-crusade#comments:id=879347
http://www.wowhead.com/utgarde-pinnacle#comments:id=478071

**Comment by Dootz** [comment]
same for UK

**Comment by Dootz** [comment]
k

**Comment by Dootz** [comment]
will be fixed with next server update
