### ISSUE TITLE
Quest "Establishing Superiority

### ISSUE THREAD

**Issue by Rorshak17** [SunwellTracker/issues#1034]
Decription: 
Quest w Icecrown

How it works: 
Zabijając moby: Hulking Horror nie zaliczają się do questa

How it should work: 
Po zabiciu 10 mobów Hulking Horror quest powinien być zaliczony. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Witaj,

nie byłeś może w czasie wykonywania quest w grupie rajdowej? Wtedy nie zalicza wykonywanych questów.
