### ISSUE TITLE
[Quest] Willix The Importer

### ISSUE THREAD

**Issue by jchiera** [SunwellTracker/issues#1035]
Decription: 
When someone else starts the escort quest "Willix the Importer" in RFK, it will only allow one person to turn it in once we reach the entrance. After that person turns in the quest Willix runs back to the end of the dungeon were you first accept it. This does not allow anyone else to turn that quest in.

How it works: 
When someone first talks to Willix to accept/start the escort, it will prompt all the party members if they would like to start the quest. We escort Willix to the beginning of RFK and then he talks some more about finally escaping. Once he is done talking our Quest is shown as Complete. When someone turns in the quest Willix will just run back to his original starting location at the end of RFK and this does not allow anyone else to turn in their quest.

How it should work: 
The quest should allow everyone to turn it in once we reach the entrance of RFK. Willix should not run back to his original starting location at the end.

Source (you should point out proofs of your report, please give us some source):
I have spoken with GM Tide and he also confirmed that it was a bug and suggested that I put this in the bug tracker.

**Comment by jchiera** [comment]
Another small note to add, but it showed that the experience awarded for this quest about about 99,580 as well. I don't have a screenshot of this, but it's showing the correct amount now (3650). This doesn't relate to the above bug, just something to mention.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/195
