### ISSUE TITLE
[Item] Orb of the Blackwhelp debuff isn't cancelled on right click

### ISSUE THREAD

**Issue by robertkg** [SunwellTracker/issues#1039]
Decription: 
The item [Orb of the Blackwhelp](https://wotlk.evowow.com/?item=31337) (Item ID: 31337) does not allow you to cancel the effect it applies on right click. When the item is used, it transforms you into a blackwhelp from the debuff [Transofrmation - Blackwhelp](https://wotlk.evowow.com/?spell=38318) (Spell ID 38318). 

How it works: 
The debuff is applied, but you are unable to cancel the effect.

How it should work: 
You should be able to cancel the debuff by right clicking on the debuff slot in your UI.

Source (you should point out proofs of your report, please give us some source): 
Bought the orb from a Wyrmcult Provisioner in Blade's Edge Mountains and used the orb on myself at level 80.

**Comment by Dootz** [comment]
will be fixed with next server update
