### ISSUE TITLE
QUEST-Two Wrongs

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#104]
Decription: Unable to reach target with a melee character

How it works: Everything work as intended except when the proto lands.
1. it hovers above ground
2. unattackable with melee MUST jump to hit

How it should work:  Pathing issue.

Source (you should point out proofs of your report, please give us some source):  just completed quest @ 1:35 server time

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
