### ISSUE TITLE
[Quest] A Bear of an Appetite @ Grizzly Hills

### ISSUE THREAD

**Issue by Zonzei** [SunwellTracker/issues#1041]
Decription:  No Northern Salmon pools spawns anywhere confirmed by GM Azathothh.
![img](https://puu.sh/zOKDU/a29671920f.jpg)

How it works: 

![img2](https://i.imgur.com/4NHTsjT.jpg)
![img3](https://i.imgur.com/0J2em31.jpg)

How it should work: 

Pools everywhere.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
