### ISSUE TITLE
[Quest] Going Bearback

### ISSUE THREAD

**Issue by purplehaze321** [SunwellTracker/issues#1042]
Decription: 
All the mobs are stuck in the walls or mountain surrounding the quest area

How it works: 
You sit on the bear and shoot mobs. the bear runs a premade route. After you hit a mob it runs in a straight direction for a few seconds and then stops. Pretty much every mob in the questarea got hit so often that they are all stuck in the walls or mountains now and you cant hit em anymore.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Hello yes i do a reset from time to time but its not enough

**Comment by Dootz** [comment]
will be fixed with next server update
