### ISSUE TITLE
[Warlock] Improved Corruption does not work 

### ISSUE THREAD

**Issue by gdziguashvili** [SunwellTracker/issues#1045]
Decription: 
[Warlock] Improved Corruption does not work 
![corruption](https://user-images.githubusercontent.com/37770612/37874152-7b0bd8ba-303a-11e8-9259-d230df15984f.png)

How it works: 
Once adding talent points to Improved Corruption, dots damage of Corruption spell does not increase.

How it should work: 
It should increase dots damage of Corruption spell by 2,4,12,16,20%.

Source (you should point out proofs of your report, please give us some source): PLs see screenshot

**Comment by Akha72** [comment]
4% of 40 dmg (you have 0 sp) is 1.6 so it won't be visible on a single tick. And the talent shouldn't increase dmg by 2,4,12,16,20 but by 2,4,6,8,10%.
