### ISSUE TITLE
A Bear of an Appetite aint spawning the salmon

### ISSUE THREAD

**Issue by Shuuman** [SunwellTracker/issues#1047]
Decription: I have been looking for the salmon for 45 min and not 1 has spawned

How it works: The salmon should spawn along side the mantas spawning in the water but they are not spawning

How it should work: They should spawn so you can catch them with the net from the quest

Source (you should point out proofs of your report, please give us some source): Im doing the quest now so im the source

**Comment by Dootz** [comment]
it'll be fixed with next server update
