### ISSUE TITLE
Return of the High Chief

### ISSUE THREAD

**Issue by Myst0gan** [SunwellTracker/issues#1049]
Decription: 
Quest w Dragonblight

How it works: 
Po uwolnieniu wodza taunki mob który powinien zeskoczyć na dół znika w połowie drogi i respi się z powrotem na skale.
How it should work: 
https://www.youtube.com/watch?v=m26PcoscSW8 -(grafika nie powala ale tu nie o to chodzi) mob powinien zejść na dół, żeby dało się go zabić i zlootować skorupe.
Source (you should point out proofs of your report, please give us some source):

**Comment by TheBigBallsOfFury** [comment]
This event works beatifully IF the event starts, many times it bugs out at the start.

1st attempt:
Prison shackles broken after activating purple crystal. Warchief stands in place and starts dialogue. Event gets stuck there.

I abandoned the quest and tried again:
2nd attempt:
Warchief started walking and event played out perfectly.

Hope this helps.

**Comment by MrTide** [comment]
@Dootz this happens when a enemy npc around him hits him and he bugs out and just stands there

**Comment by Dootz** [comment]
if that's the issue then it will be fixed with next server restart (aka tomorrow), because there was report about and i fixed it. But this report is about Anub disappering during fall, which i've never experienced.
