### ISSUE TITLE
[Quest] It Goes to 11...

### ISSUE THREAD

**Issue by theadrix33** [SunwellTracker/issues#105]
Decription: Couldn't complete - Dragonflayer Longhouse Destroyed 0/1.

How it works: was shooting harpoons at the correct house and nothing was triggering.

How it should work: harpoon hits on the house should give you credit for destroying it, and then summon flying adds in front of your harpoon.

Source (you should point out proofs of your report, please give us some source): I've done this quest a million times before, it should work like i mentioned.

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.

**Comment by sharkman800** [comment]
This still seems to be broken. There doesn't seem to be a good spot to hit the Longhouse.

**Comment by Exorcista** [comment]
was able to complete this on this date, the "spot" to hit the houses is on the roof right were the wood "Dragon" heads start showing. Hope this helps people doing this anoying quest.
