### ISSUE TITLE
(HUNTER) Pet resilience

### ISSUE THREAD

**Issue by UsulxD** [SunwellTracker/issues#1051]
Decription:  Resilience should affect pets more

How it works: I tested with my arena mate, with and without resillience gear, the difference is of about 3-4% (recount).  I have 600 resi, the damage reduction should be above 15% (crits/flat reduction).

How it should work: Resilience should affect pet in the same way it affects hunter.

Source (you should point out proofs of your report, please give us some source): You could try the same test. You can also compare with Warmane but iirc they buffed pet resilience gain in their 3.3.5b patch because even at retail value the pet just gets blasted.

**Comment by Akha72** [comment]
If you have 600 resilience then your pet has 240 and thus 2.50% reduced chance to be critted and 5% dmg reduction. You're saying that these numbers are wrong and as a consequence scalling is broken or what?

**Comment by ujellyx** [comment]
"1 point of resilience gives 1 point of resilience rating to your pet as of Patch 3.3.0. Previously, it was 0.4 points of resilience per 1 point."
https://wow.gamepedia.com/Hunter_pet#Pet_scaling

That's how it should be. So the damage-reduction should be the same amount as the hunter's right now, which according to op isn't the case.

**Comment by Akha72** [comment]
Wowwiki seems to confirm that. Are we safe to assume that both pet and its master need the same amount of resilience points to get 1% reduction?

**Comment by set-theorist** [comment]
^Yes. That's how it should be.

**Comment by Riztazz** [comment]
Did you test with melee attacks? If so remember that owner and pet have different armor values so differences might come from that and im pretty sure that's the case, i just did some tests and looked at the code and pet gets 100% resilience from owner, i'll get @Azathothh to recheck after me so we're dead sure about that

**Comment by Azathothh** [comment]
"How it should work: Resilience should affect pet in the same way it affects hunter."
And it's exactly how it's working. Tested with different amounts of resilience and it was always same damage reduction for both pet and it's owner.
Like Riztazz said probably you've tested it with melee and difference comes from different armor values (i'm 100% sure it got nothing to do with resilience)
