### ISSUE TITLE
(HUNTER) Scatter Shot

### ISSUE THREAD

**Issue by UsulxD** [SunwellTracker/issues#1052]
Decription:  Scatter shot glitches the target movement for a bit when applied

How it works:  Scatter shot makes the target have very weird/laggy movement pattern making it very difficult to land traps.

How it should work: Just normal scatter pattern.

Source (you should point out proofs of your report, please give us some source):  Use scatter in a pvp situation with an enemy moving

**Comment by ujellyx** [comment]
yeah, the target moves around way too much when scatter hits... makes it hard to trap.

**Comment by Nrocer** [comment]
UP

**Comment by lukaasm** [comment]
duplicate #948
