### ISSUE TITLE
[Q] Into the World of Spirits (Howling Fjord)

### ISSUE THREAD

**Issue by hairychestfan** [SunwellTracker/issues#1053]
**Decription:**  Respawn time is bugged (insanely long)

**How it works:**  I believe this server brags how it has dynamic respawn times or whatnut, but for this quest in particular the respawn time is bugged which means you are unable to loot it to complete the quest.

**How it should work:**  Simple quest, you dive in the water and loot the object to get your quest item..

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=11333
http://db.darkwizard.pl/?item=33635
**http://db.darkwizard.pl/?object=186662**  <--- the bugged object respawn time

**Comment by Dootz** [comment]
will be fixed with next server update
