### ISSUE TITLE
[Priest] Mind Flay tick being able to miss

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#1056]
Decription: 
Mind Flay ticks are able to miss individually even if the initial application landed on target if you aren't hit capped.

How it works: 
Mind Flay ticks can miss on a target even if the initial cast is sucessful and lands on the target, gimping shadow priest damage.

How it should work: 
Channeled spells ticks cannot miss once the initial application flag is on the target. The exception are channeled spells with proyectile or direct dmg component, such as Arcane Missiles.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Arcane_Missiles
"Unlike other channeled spells, each second (or "tick") is considered a separate direct damage missile which passes through the normal direct damage checks (crit, resistance)."

**Comment by ujellyx** [comment]
confirm

**Comment by Azathothh** [comment]
Fixed, will be updated soon.
