### ISSUE TITLE
[PvE][PvP] Projectiles ignore mitigation effects when they are mid-air

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#1058]
Decription: 
Ranged attacks and spells deal full damage on targets that use a defensive CD if the attack/spell was mid-air when they used it.

How it works: 
Spells and ranged attacks that are traveling deal full dmg on targets that get a defensive CD up before the spell hits, ignoring the mitigation

How it should work: 
The spells have two checks, one for damage done and another for damage taken (by the target). For the damage done calculation, the spells and attacks count the effects on the caster and add them to calculate how much damage it would do. This calculation is done by the time the spell cast is finished.

However, as for damage taken the calculation is made when the spell HITS. This applies for all damage, mitigation and avoidance checks (for example, hit/miss or resist) aswell as absorbs and inmunities.

Thus, spells can be mitigated by defensive CDs if they are mid-air, because the damage taken check hasn't taken place.

Source (you should point out proofs of your report, please give us some source): 
Base game mechanics, currently inmunities and absorbs work in this way but damage mitigations don't so you can get nuked even if you pop a defense CD.

**Comment by dathremar** [comment]
its supposed to work like that. Damage/parry/dodge/miss is calculated when you cast the spell. Only immunities/absorbs/(block?) and spells like vanish or shadowmeld can affect already casted ranged abilities.

**Comment by Akha72** [comment]
If according to your theory dmg is calculated when spell hits then it is possible to cast nukes and then Curse of Elements just before they hit to increase their dmg. And it certainly wasn't possible on retail TBC. And since when do absorbs affect mid-air effects?

**Comment by ujellyx** [comment]
False report - it's working as intended here.
Only thing I heard of is that you can't vanish/shadowmeld projectiles mid-air here, but maybe that's something for another report.
