### ISSUE TITLE
life tap health funnel bugs  (warlock)

### ISSUE THREAD

**Issue by krovic** [SunwellTracker/issues#106]
Decription: 
health funnel and life tap are working incorrectly

How it works: 
health funnel takes your life and grants it to the pet at a adjusted amount. however it will do so even if the result kills you.

life tap costs X amount of life to be conjured and grants you Y amount of mana
however, sometimes you have X amount of life plus 200 and you still cannot life tap.
curently, i find myself with 550 hp and cant cast a spell that costs 391 hp. as i spam life tap (meaning i cast it as soon as possible) i find myself with over 200 hp left over.. meaning i had more then enough to cast it before and it didnt let me

How it should work: 
health funnel should auto cancel before killing you 
life tap costs 300 hp to cast, if you have 301, it should cast and leave you with 1 (example)

Source (you should point out proofs of your report, please give us some source): 

source is my own playing experience. which can easily be reproduced real time should someone want to see me do it. just heath funnel till you die.. and same for life tap. contact me in game if u want.

**Comment by dredd-sunwell** [comment]
Provide the evidence that this is indeed a bug.

**Comment by krovic** [comment]
how? you would have to find videos from retail showig you that health
funnel dosent kill you. but since i dont play retail wow, any video i
provide for you could be from another private server and not the real
blizzard version.

its not working as its supposed to be, just like life tap. the evidence is
written on the spell.. you need 391 hp to cast it you have 500 and you
cannot cast it.. dont need more evidence right?

**Comment by Semper-Numquam** [comment]
http://wowwiki.wikia.com/wiki/Health_Funnel

"It is possible for warlocks to kill themselves using this spell."
