### ISSUE TITLE
[Q] He's Gone to Pieces [Quest ID: 13212] [Icecrown]

### ISSUE THREAD

**Issue by onyx215** [SunwellTracker/issues#1061]
Decription: 
You have to kill corpulent horrors to get the quest items.
The items are: 
[item=43526] [item=43527] [item=43528] [item=43529]

How it works: 
When you kill the corpulent horrors you get 2-3 of the quest items, but after that you cant loot the mobs any more.
When you kill them there is no loot, you can still loot other mobs in the area after you killed them.
I have killed around 50-60 corpulent horrors after i noticed that they did not drop anything anymore.

I abandoned the quest and tried again, got 2-3 pieces and then they stopped dropping loot.

I cleared cache and WTF folder, abandoned the quest again and tried but still the corpulent horrors still stop giving any loot after you get 2-3 pieces.

How it should work: 
When you kill the mobs you have a 12% chance of getting one of the quest items, it should not take 50-60 mobs to even complete this quest. 

Source (you should point out proofs of your report, please give us some source): 

Wowhead link to the quest: http://www.wowhead.com/quest=13212/hes-gone-to-pieces#videos

Link to the quest items: 
http://www.wowhead.com/item=43526/olakins-torso
http://www.wowhead.com/item=43527/olakins-legs
http://www.wowhead.com/item=43528/olakins-left-arm
http://www.wowhead.com/item=43529/olakins-right-arm#dropped-by

**Comment by Dootz** [comment]
will be fixed with next server update. Note that there are two types of abomination npc in this area. On of them, i belive called "Chained ..." do not drop quest item which is correct behaviour
