### ISSUE TITLE
[Quest]Runes of compulsion

### ISSUE THREAD

**Issue by Vasilenius** [SunwellTracker/issues#1062]
Decription: The quest is not working correctly.The overseers were not spawning when i killed the 4 dwarfes around the runes.A Game Master had to respawn the dwarves a several times before and overseer would spawn.

How it works: The overseers randomly spawn and don't spawn when you kill the 4 dwarves guarding the runes.I had the help of a Game Master respawning them so i could complete the quest.

How it should work: An overseer should spawn after you kill the 4 dwarves guarding the rune.

Game master that helped me was named Tide

**Comment by MrTide** [comment]
Hello
I had to reset the waypoints ( just like besieged quest ) and after that they spawned
seems like only two of these waypoints bug out

**Comment by Dootz** [comment]
will be fixed with next server update
