### ISSUE TITLE
Chilled Abomination Guts Drop Rate!

### ISSUE THREAD

**Issue by kasea** [SunwellTracker/issues#1063]
Decription: 
Chilled Abomination Guts is needed to do quest That's Abominable!

How it works: 
Drop rate should be about 53%, but after killing more than 20 Hulking Abomination it droped ones.

How it should work: 
Drop rate should be 53% so it means, that after killing 20 Hulking Abomination I should get more than 10 of that items.

Source (you should point out proofs of your report, please give us some source): 

http://www.wowhead.com/quest=13289/thats-abominable

**Comment by Dootz** [comment]
will be fixed with next server update
