### ISSUE TITLE
Moonglow increases mana use instead of decreasing

### ISSUE THREAD

**Issue by Lurvee** [SunwellTracker/issues#1065]
Decription: 
Moonglow talent increases how much mana used on Wrath spell instead of decreasing

How it works: 
3rd point in talent increased mana usage on Wrath spell from 26 mana to 28.

How it should work: 
Should decrease by 3% on last point

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
i just tested it on fresh lvl 80 druid without items and spells/other talents and cost goes like this:
no talent points :279
1 point: 270
2 points: 262
3 points: 253

Cost of some spells change while you level up, based on you "base mana" (http://www.wowhead.com/forums&topic=42632/mana-costs-in-percentages ). So what probably happened is you checked it after level-up. But that's just my guess, if that's not the case please let me know.

**Comment by Lurvee** [comment]
Really sorry… late evening for me and long time since I played wow, so I honestly did not think about mana cost increase upon lvling 😊

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Fra: Chris <notifications@github.com>
Sendt: Monday, March 26, 2018 9:13:34 PM
Til: SunwellTracker/issues
Kopi: Lurvee; Author
Emne: Re: [SunwellTracker/issues] Moonglow increases mana use instead of decreasing (#1065)


i just tested it on fresh lvl 80 druid without items and spells/other talents and cost goes like this:
no talent points :279
1 point: 270
2 points: 262
3 points: 253

Cost of some spells change while you level up, based on you "base mana" (http://www.wowhead.com/forums&topic=42632/mana-costs-in-percentages ). So what probably happened is you checked it after level-up. But that's just my guess, if that's not the case please let me know.
