### ISSUE TITLE
[Quest] [Fire Upon The Waters]

### ISSUE THREAD

**Issue by heniuus** [SunwellTracker/issues#1068]
Decription: 
Apothecary Vicky Levine at Venomspite has asked you to use her **Apothecary's Burning Water** to set the **sails** of the Sinner's Folly afire.
While the deckhands are busy attempting to put the fires out, head belowdecks and retrieve Captain Shely's Rutters from the captain.

How it works: 
Player can throw Burning Water at sails without effect.

How it should work: 
Quest item should set on fire sails, and nearby sailors should be distracted. 

> Once the sails are on fire, the deckhands will be busy putting them out, and you'll slip belowdecks to 'retrieve' the captain's rutters.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=4L_J0K5VJAU&t=35s

**Comment by Dootz** [comment]
will be fixed with next server update
