### ISSUE TITLE
[Warlock] Slow the warlock = you slow the pet

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#1070]
Decription: If you slow a warlock his pet will automatically be slowed.
PS: I also noticed if a rogue blinds you your pet is automatically slowed too.

How it works: Asked a mage friend to use frostbolt on me (warlock) and it slowed my pet (succubus)
https://www.youtube.com/watch?v=PklDlZoGvmU

How it should work: If you slow the warlock you shouldn't slow the pet. You would actually have to slow the pet which would give him a debuff.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=PklDlZoGvmU

**Comment by set-theorist** [comment]
Can confirm, 

In fact, if master gains beneficial speed boost which puts him above 100% speed, then pet should gain that speed as well (warsong gulch sped buff for instance).

If master gets snared below 100% speed his pet should NOT become affected by this speed debuff. Pet can only be snared below 100% speed by snaring the pet itself.

**Comment by dispelx** [comment]
up ^ fix this  It is not at all possible to play for a hunter

**Comment by Kokaina** [comment]
Fixed.
