### ISSUE TITLE
[Quest]A Bear of an Appetite

### ISSUE THREAD

**Issue by lax241** [SunwellTracker/issues#1071]
Decription: 
Not working quest "A Bear of an Appetite". 

How it works: 
There aren't any Northren Solmon schools of fish in the water. I can find only "Imperial manta Ray" schools of fish.

How it should work: 
This type of fish should spawn. 

Source (you should point out proofs of your report, please give us some source): 
https://github.com/TrinityCore/TrinityCore/issues/17598
https://www.youtube.com/watch?v=ZuXl8u0iOxY

**Comment by Dootz** [comment]
it will be fixed with next server update (tomorrow)
