### ISSUE TITLE
Utgarde Keep / Intercept / Feral Charge

### ISSUE THREAD

**Issue by adamzimnyy** [SunwellTracker/issues#1076]
Decription: 
Mobs swap position with player when charged.

How it works: 
When charged, some mobs teleport to player's origin position and are immobilized there.
https://youtu.be/GDOmg45ArGs
https://youtu.be/6iLME283HAU
https://youtu.be/Y6kyY2hltI8

Happens with warrior's intercept and druid's feral charge (bear)

How it should work: 
Mobs should not teleport and be immobilized in the position they got charged at.

**Comment by Sensza** [comment]
I can confirm this. It started to happen today and doesn't work properly regardless to player's location(not only in UK instance).
