### ISSUE TITLE
Reputation Gains at 80lvl dungeons

### ISSUE THREAD

**Issue by trexenoob** [SunwellTracker/issues#1078]
Decription: 
Bug at gaining reputation while doing a 80lvl normal dungeon in Angrathar Alliance.

How it works: 
Today while I was wearing  Wyrmcrest tabard (I am lvl 80 Human dk named Trexe) I entered the Utgarde Pinnacle dungeon and I fully completed it. I didn't get any reputation for any faction. I asked another guy in my party and he said he didn't get anything as well and didn't understand the reason. I opened a ticket and a gm told me to address my problem here so it can be resolved.

How it should work: 
I should have gotten reputation for the Wyrmcrest Accord and I lost it.

Source (you should point out proofs of your report, please give us some source):

**Comment by trexenoob** [comment]
Unfortunately I don't have a source because of this kind of problem. I hope you fix the reputation as intended. Thanks so much.

**Comment by trexenoob** [comment]
The gm I talked to is named Pixie.

**Comment by Dootz** [comment]
it'll be fixed with next week update. But it only happens in UP. So in every other dungeon it should be fine.
https://github.com/SunwellTracker/issues/issues/1030
