### ISSUE TITLE
[Shadowmoon Valley Quest] Dragonmaw Race: Wing Commander Ichmann (11069)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#1079]
Decription:
Problem dotyczy questa (https://db.darkwizard.pl/?quest=11069), a konkretnie npca (https://db.darkwizard.pl/?npc=23345) / the issue is related to the quest (1st link) and npc (2nd link)

How it works: 
Czasami podczas wykonywania questa npc wlatuje w tekstury i wraca na miejsce spawnu, przez co quest pozostaje niezaliczony. Dzieje się to na wysokości, na której znajduje się w 2:03 filmiku (https://www.youtube.com/watch?v=g4_GV-mpQFQ), dokładniej zaznaczone okręgiem na screenie (https://i.imgur.com/WE0JcTI.jpg). Questa udało mi się wykonać za 3cim razem, ten sam problem zgłaszany był na poprzednim BT / sometimes while completing this quest the followed npc flies right into textures and returns to his starting point, marking the quest as failed. It happens around place shown in 2:03 and it is circled in the linked screen. It does not occur always for he didn't do so on my 3rd run, making the quest completable. The same issue was reported on previous BT.

How it should work: 
Wing Commander Ichmann nie powinien wlatywać w tekstury tylko podążać trasą pokazaną w filmiku powyżej / WCI should not fly into textures but rather stick to the route shown in the video.

Source (you should point out proofs of your report, please give us some source):  j/w

**Comment by Dootz** [comment]
will be fixed with next server update
