### ISSUE TITLE
[Quest] Leave no one behind

### ISSUE THREAD

**Issue by Stikkychaos** [SunwellTracker/issues#1080]
Decription: 
Let No One Behind quest in Zul'Drak has a bug associated with crusaders you have to save.

How it works: 
After being bandaged, the crusaders will follow you, as per usual. If you enter combat with nearby ghouls they will still follow you and not turn in when reaching the outpost, forcing you to wait for respawn of those NPCs.

How it should work: 
Crusaders should follow you, engage in combat and turn in in the outpost EVEN if you engaged in combat with ghouls.

Source (you should point out proofs of your report, please give us some source): 
Personal experience. Additionally, when asking on Global chat, i was told the quest is indeed bugged.

**Comment by TheBigBallsOfFury** [comment]
This is very inconsistent. Even after enterning combat with ghouls sometimes I got credit.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/103
