### ISSUE TITLE
The cipher of Damnation

### ISSUE THREAD

**Issue by jockeboschko** [SunwellTracker/issues#1081]
Decription:  The last part of Cipher of Damnation quest chain is bugged. The big fire elemental is not attackable.

How it works: RP event is fine boss spawns fine but can not be attacked nor attacks anything.

How it should work: 
RP finish and boss become attackable.

Source (you should point out proofs of your report, please give us some source): 
GM tide tested it with me and noted it was bugged.

**Comment by Dootz** [comment]
Have you started event at Oronok NPC? https://youtu.be/vwC8MgX9Ip0?t=2m7s . After Boss is spawned you need to talk to NPC, small escort event will start and boss will attack.

**Comment by MrTide** [comment]
Hello checked again it works without an issue
seems like some weird problem happened last time
ty Dootz
