### ISSUE TITLE
(Quest)Rampage

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#1083]
Rampage seems to be buggy in zuldrak. When i got to the place for the quest event there was several copies of the akali/prophet of akali spawned in. GM azathothh killed all the mobs and it reset the event after five minutes. When I did the event I only needed to unlock one chain not all four like it should be to release akali. Seemed to work ok on despawning the mobs and resetting for my attempt, so I do not know the root cause of them staying spawned like that.

**Comment by Dootz** [comment]
hopefully fixed
