### ISSUE TITLE
[Death knight] Rune cooldowns

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#1084]
Decription: 
Death knights use runes as a resource for certain abilities. By default, runes have a 10 second cooldown (9 with 2/2 in improved unholy presence, while in unholy presence).

How it works: 
Runes have a varied and random cooldown when used, ranging from 5-10 seconds.

How it should work: 
Runes should always go on a 10 second cooldown unless in unholy presence with 2/2 points in improved unholy presence.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=U9np0rmvVOo&feature=youtu.be

The video shows the addon present different cooldowns. If you don't trust the addon, you can see that abilities are being used as soon as they are reported to have come off cooldown.

**Comment by set-theorist** [comment]
This is not a bug. See rune grace period:

https://github.com/TrinityCore/TrinityCore/issues/6122
