### ISSUE TITLE
Slow stealth + break cheap

### ISSUE THREAD

**Issue by pojkee** [SunwellTracker/issues#1085]
Decription:
If im used Fast Vanish> Cheap  cheap doesnt work. Istead cheap some reason pressed spells At unstealth bar.

How it works like:
My button 3 in unstealth - Eviscerate
My button 3 in stealth - cheap shot.
And if I press fast Vanish - Cheap shot (i dont have any macro for it) - its bugged :<
I made some movie - https://youtu.be/TidHROPyGp0
Movie 2 - https://youtu.be/l0Ds69urGME
P.s. yeah. my PC sucks and  lagged
Pp.s. U can check how i press button 3 (addon SnowFallKeyPress)
How it should work: 
Looks like between cast Stealth (stance 0 (unstealth) and stance 1 (stealth)) big delay or something. 
I made same movie but now at AT (blackrock).
Movie 1 - https://youtu.be/7Sb27XT-Iow
Movie 2 - https://youtu.be/9CQgSlmguDA
P.s. Sorry for AD x)
Pp.s. Even if u would say "Arena tournament its 3.3.5b", there some change than retail:
Movie RVR  - https://youtu.be/spH5R2pTBFU 0:35 s. Pls look at this and fix

Source (you should point out proofs of your report, please give us some source):

**Comment by pojkee** [comment]
Updated: testing this morning - works perfectly. Сonclusion - every evening big delay so play pvp impossible.

**Comment by ujellyx** [comment]
It's delayed because of the delayed switch of the action bars, which also occured on retail.
Just macro the spells with the conditions [stealth] and [nostealth] and the delay should be no problem anymore.

**Comment by pojkee** [comment]
@ujellyx even macro doesnt help :<

**Comment by Danieloses** [comment]
Yea macro like this
#show Backstab
/cast [stance:0] Backstab
/cast [stance:1/2] Cheap Shot

should speed up the process but I think it doesn't work on sunwell
