### ISSUE TITLE
Lord Marrowgar - pull

### ISSUE THREAD

**Issue by feralxgodx** [SunwellTracker/issues#1087]
Decription: 
Mechanika pullania Lorda jest nieprawidłowa.

How it works: 
Lord pulla się po przejsciu paru kroków za bramą.

How it should work: 
Lord powinien pullnąć się od dmg/taunta.

Source (you should point out proofs of your report, please give us some source): 
Jakikolwiek filmik z lorda.

**Comment by Elaatu** [comment]
To chociaz mogłbys wkleic ten jakikolwiek filmik...

**Comment by feralxgodx** [comment]
https://www.youtube.com/watch?v=zFTceGrZIVk
https://www.youtube.com/watch?v=gyy2YoQZXko
https://www.youtube.com/watch?v=xiFsg7DIQLc
