### ISSUE TITLE
[Quest] Sweet amber

### ISSUE THREAD

**Issue by Lexofein** [SunwellTracker/issues#1088]
Decription: 
Quest link
http://db.darkwizard.pl/?quest=48
Object for getting quest item http://db.darkwizard.pl/?object=759

How it works: 
Quest object http://db.darkwizard.pl/?object=759 doesn't exist

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
My own experience. Trying come to fountain 2 times in 2 different days, but fountain still inactive.

**Comment by Dootz** [comment]
Right now respawn of this fountain takes around 15 minutes. It'll be reduced with next server update.

**Comment by Dootz** [comment]
will be fixed with next server update
