### ISSUE TITLE
[RP Event] [Quest order] Something That Doesn't Melt (12047)

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1090]
1) Missing RP event at the end of this quest

2) The quest order in this hub (goblins) is completely F'd up. For example you get the harpy quest that becomes available in the video below straight away as you come to this quest hub.

I don't remember exactly what order it was so I cannot pinpoint what exactly is wrong, but it doesn't follow the questing structure of WotLK zones. Hopefully you guys will be in a better position to see that info :)

P.S - High quality fixes guys, keep em coming!

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/5LtHyDk4r8A?t=1m58s

**Comment by Dootz** [comment]
RP event will be added in next server update. As for quest order i'll link it to this issue : https://github.com/SunwellTracker/issues/issues/1090
