### ISSUE TITLE
Enchanting SP

### ISSUE THREAD

**Issue by Tsux3** [SunwellTracker/issues#1092]
Decription: 
When i trying to enchant, i got an error :o 

How it works: 
Dont enchant items. ;o

How it should work: 
Item should get +23 sp

![ench](https://user-images.githubusercontent.com/36333911/38058006-9bee5ffe-32e1-11e8-9791-87f3aa334165.png)

**Comment by Akha72** [comment]
You know you can enchant only your own rings?

**Comment by Tsux3** [comment]
I prolly think it was gloves. For 90%: o

czw., 29 mar 2018, 00:16 użytkownik Akha72 <notifications@github.com>
napisał:
