### ISSUE TITLE
[Quest]Death to the Necromagi

### ISSUE THREAD

**Issue by balazskvr** [SunwellTracker/issues#1093]
Decription: 
Quest is not obtainable after completing Rupert's task.

How it works: 
I assume it needs the whole http://www.wowhead.com/quest=12596/patroll to be unlocked.
To be confirmed...

How it should work: 
Completing Rupert's task should unlock the quest.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12552/death-to-the-necromagi#comments:id=464205
"To clarify, you don't need to complete Pa'Troll - Just Captain Rupert's criteria to unlock this quest hub."

**Comment by Dootz** [comment]
> I assume it needs the whole http://www.wowhead.com/quest=12596/patroll to be unlocked.
> To be confirmed...
Yup, that's how it works right now.

**Comment by Dootz** [comment]
will be fixed with next server update
