### ISSUE TITLE
Post-partum Aggression(griefing bug)

### ISSUE THREAD

**Issue by Stretpaket** [SunwellTracker/issues#1094]
Decription: When you get to controll the mammoth you can target players with its abilities resulting in you being able to perma stun people.

How it works: You can attack players with the "mammoth vehicle".

How it should work: You should only be able to attack NPCs with the abilities(i think. pretty game breaking if you can perma stun players)

Source (you should point out proofs of your report, please give us some source): I can't recreate the issue because I already completed the quest.

**Comment by Dootz** [comment]
will be fixed with next server update
