### ISSUE TITLE
Saronite bomb triggers indestructible potion cooldown

### ISSUE THREAD

**Issue by set-theorist** [SunwellTracker/issues#1095]
Decription: 
Using a saronite bomb and possibly any other explosive such as a grenade or sapper charge incorrectly triggers a 1 minute hidden cooldown on Indestructible Potions. Strangely this does not happen with speed potions.

How it works: 
Using a saronite bomb and possibly any other explosive such as a grenade or sapper charge triggers a 1 minute hidden cooldown on Indestructible Potions

How it should work: 
Explosives and pots cooldown should be completely independent

Source (you should point out proofs of your report, please give us some source): It's obvious from the armor pot tooltip, it doesn't even go on cooldown when you use grenades.

**Comment by Azathothh** [comment]
It's same for other explosives as well.
1. use any explosives from engineering
2. can't use 40093 - [Indestructible Potion]  for 1minute

If Indestructible Potion is used first, explosives can be used without problem, but still apply 1min hidden cd.
