### ISSUE TITLE
Speaking with the Wind's Voice extremely low Voice of the Wind droprate

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1096]
Decription: In quest "Speaking with the Wind's Voice" you need to kill stormrider (http://db.darkwizard.pl/?npc=29624) and collect Voice of the Wind (http://db.darkwizard.pl/?item=41514) in order to complete the quest. The droprate is stated as 22%, but after killing about 25 of them I only got 1, which is a bout 1 in 1000 chance of happening, I think the droprate is broken

How it works: 1% droprate

How it should work: 22% droprate

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
