### ISSUE TITLE
Emergency Measures extremely low droprate on Worg Fur

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1097]
Decription: In quest "Emergency Measures" you have to get 6 Worg Fur by killing Cavedweller Worg. The droprate is extremely low.

How it works: http://db.darkwizard.pl/?npc=30164 drops http://db.darkwizard.pl/?item=42510 about 1 in 20 kills. 

How it should work: Drops 20% of the time.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
