### ISSUE TITLE
[Warrior] Class quest The Rethban Gauntlet

### ISSUE THREAD

**Issue by LessRight** [SunwellTracker/issues#1099]
Description: I turned in the prerequisite quest Yorus Barleybrew to that NPC in Redridge. He doesn't offer me The Rethban Gauntlet or do anything when clicked.

How it works: Having turned in the prereq, he doesn't automatically offer me the quest. There is no yellow exclamation point above his head, the mouse icon does not turn to a yellow exclamation point when I mouse over him, and when I click on him nothing happens.

How it should work: Presumably he should offer the followup quest The Rethban Gauntlet automatically, but also the yellow exclamation points should appear over his head and on my cursor. He should definitely give the quest when I right-click him.

Source (you should point out proofs of your report, please give us some source): I could post a screenshot but I'm not sure how to prove I did the prereq and haven't yet done the quest itself.

EDIT- The warrior I am experiencing this on is named Sawgrass, if that matters. (second edit - on Angrathar.)

**Comment by Dootz** [comment]
will be fixed with next server update.
