### ISSUE TITLE
RDF

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#11]
Decription: After wipe and when one player leaves group i should leaves party without having a Dungeon Deserter debuff.

How it works: 
After few wipes  and some players going out from party Dungeon Deserter apply on my char after leaving party.

How it should work: 
After wipe and someone leaves party i should leave party without Dungeon Deserter.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
