### ISSUE TITLE
Vanish doesnt avoid hunter abilitis

### ISSUE THREAD

**Issue by pojkee** [SunwellTracker/issues#1100]
Decription: 
#fixvanish
How it works: 
If hunter used any spell (Viper Sting, explosive shot, aimed shot etc) and rogue insta vanish - hunter abilities broke vanish, and do damage.  (But vs another class vanish work fine)

How it should work: 
Vanish works - https://www.youtube.com/watch?v=TTDbFBbNgyw

Source (you should point out proofs of your report, please give us some source): pls fix it fast, impossible play and get so much angry cuz of this

**Comment by Hoodeee** [comment]
I have had a number of issues with vanish aswell. The improved stealth of vanish seems to immediately break with any damage. You are still able to be attacked while improved stealth is active, but it should not drop stealth until after its duration.

**Comment by Phobossus** [comment]
Bump. Vanish still doesn't work properly, breaks on missiles hitting rogue that were fired before vanish.
