### ISSUE TITLE
Lightning Reflexes

### ISSUE THREAD

**Issue by Yarzqt** [SunwellTracker/issues#1104]
Decription: Talent Lightning Reflexes 3/3 gives 9% haste instead of 10% which isn't right, because even the tooltip says it should give 10%. It was changed to 9% in 4.0.1 but we're playing on 3.3.5 :)

Proof: https://i.imgur.com/kSkByDo.jpg

**Comment by set-theorist** [comment]
Actually, your calculations are wrong. Haste does not reduce your swing speed by x%. It increases the amount of swings you can fire in a certain period of time by x%. To actually find your new weapon speed:

weapon speed = original wep speed/(1+haste%).

For example 100% haste means you would do 100% more attacks in t seconds, which means your weapon speed would be half of normal.

**Comment by Yarzqt** [comment]
Well, actually that makes sense. Problem solved itself.
