### ISSUE TITLE
Regarding Flight Speed on Time-Lost Proto Drake

### ISSUE THREAD

**Issue by Elefant0n** [SunwellTracker/issues#1106]
Decription: I haven't found any specific source of this because there is none atm. But i'm pretty sure Time-Lost Proto Drake is supposed to be 310%, Same as Plague Proto Drake, Black Proto Drake etc, Iron-Bound Proto Drake etc.

How it works: Currently 280% with Artisan Training Skill

How it should work: Same as other Proto Drakes.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
http://www.wowhead.com/forums&topic=83280.3/what-is-the-easiest-310-mount-to-get

> By Katalliaan on 2010/06/25 at 4:41 AM (Patch 3.3.5)
> Time-Lost is only a 280%, not a 310%.

https://www.reddit.com/r/wow/comments/4uzco6/time_lost_proto_drake_works_with_group_loot/

> You're correct, the TLPD was only 280% in Wrath. Source: I camped for/got one during that expansions.
