### ISSUE TITLE
Hunter Scaling with Agi(crit)

### ISSUE THREAD

**Issue by Vanggaard9300** [SunwellTracker/issues#1107]
Decription: 
scaling with agi is wrong
400/400 weapon skill

How it works:
1% is almost 90-91agi
I have 1327agi and thats 14,39%

How it should work: 
correct formula is 1327/83,33 = 15,92%

Source (you should point out proofs of your report, please give us some source): 
https://www.freakz.ro/forum/WOTLK-Hunter-marksmanship-PvE-t76269.html
http://www.warcrafthuntersunion.com/2008/12/hunter-stat-conversion-guide-level-80/

**Comment by xxxkowal** [comment]
XD Hunter make insane dmg and u want do moar :D?

**Comment by Soufly** [comment]
+1,can some GM test that.

**Comment by sonrakus** [comment]
It's called diminishing returns. The more crit you have, the more agility you will need for more crit %. So for example, if you have 0 crit, 90 agility would increase the crit chance by 1%. But if you already have 1% crit, you would need more than 90 to gain another 1% crit chance. This effect, of course, becomes more and more severe the higher your stats go.

https://en.wikipedia.org/wiki/Diminishing_returns

**Comment by Vanggaard9300** [comment]
never heard about DR interms of stats, better give me a real source for that.
btw rogues also need 83.33 seems to work for them.

**Comment by sonrakus** [comment]
Well, no, that's not what i'm saying, stamina is a number that translates to another number, not a percentage. Agility is a number that, among other things, does. In any case, i can't find any evidence of this i'll withdraw from the conversation.

**Comment by gabbat** [comment]
DR has never affected base stats, sonrakus you are wrong on this case. you will get the same % crit on low and on high agility, same with strength to ap conversion or any other stat for that matter.

**Comment by Azathothh** [comment]
83.33 Agility = 1% crit  applies to agility that you're getting from gear/buffs/etc. 
It doesn't apply to base agility.
At naked 80lvl orc hunter i've got 178 and it gives 0.60% crit rating.
1327-178 = 1149
1149/83.33 = 13.79
13.79 + 0.60 = 14.39  <-- your crit rating

So it's scaling as it should. If you think base stats should be scaled other way than it's done now - please write new report about it with proper proofs.
