### ISSUE TITLE
[Warlock] Demonic Pact double dips from itself

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#1108]
**Decription:** Demonic Pact buff has an increased effect of over 10% by double dipping from itself.

**How it works:** Demonic Pact after proccing for the **second** time takes into account the SP bonus warlock received from the **first** one. This way demonic pact gives around 11% of warlock SP instead of 10%.

**How it should work:** Demonic Pact should take into account all the SP warlock has **minus** the SP he received from the Demonic Pact buff.

**Sources**: 
[Screenshots from the DemoPact addon testing](https://imgur.com/a/gMPJv)
[DemoPact addon](https://wow.curseforge.com/projects/demopact) - Addon which measures the SP Demonic Pact should give. It calculates **second** proc as a 10% from the warlock SP minus SP from the Demonic Pact he had on himself so that the **first** and the **second** proc we see from the screenshots give about the same SP bonus just as they should. However when compare the SP from the character tooltip we can see that **second** proc gave 10% more SP than the **first** one because it took into account the SP from the Demonic Pact.

This mechanic is also noted in Warlock DPS Spreadsheet - however it should be noted that it is for 3.1.3: 
[Spreadsheet](https://web.archive.org/web/20090808165329/http://dmz-gaming.com:80/site/wiki/index.php?title=Warlock_DPS_Spreadsheet)
In a DemonicPact tab we can see a "CancelAura used" option which was a mechanic that warlock used to buff their Pacts by canceling the Demonic Pact aura they had on themselves so that they could benefit from the Totem of Wrath 280 SP bonus. They wouldn't do that if the Demonic Pact could benefit from itself. 
This interaction was also noted on the Elitist Jerks forums:
[Forum Post 1](https://web.archive.org/web/20110510123631/http://elitistjerks.com/f80/t45693-demonic_pact_rdps_vs_personal_dps/p5/)

> "Inspired by the report of Lrac (from the compendium thread), I did some testing with an elemental shaman, and my conclusion, same as Lrac, is that when the demon crits, the DP buff is calculated from your current spell power minus your current DP buff, rather than your current spell power bonus category buff (including totems). That is, totems boost DP, but (obviously) DP does not feed off itself. The only buff that does not contribute to DP is DP itself (excluding bugs)."

[Forum Post 2](https://web.archive.org/web/20110510123629/http://elitistjerks.com/f80/t45693-demonic_pact_rdps_vs_personal_dps/p6/)

> "The point about using /cancelAura though is to remove the DP buff from the lock only. It will not remove it from the rest of the raid.
> 
> If your lock has 3500 SP when buffed, including the buff from Totem of Wrath, then when DP procs everyone gets 350 SP bonus. However, this is only a gain of 70 SP as 280 is lost from ToW. Also, since the ToW buff has gone from the DP lock (replaced by DP) the amount of SP provided by DP if it is refreshed would be ((3500 - 280) / 10) = 322 (as DP can't buff itself). Therefore by removing the DP buff from themselves with /cancelAura the lock drops back to ToW and DP will refresh for 350 again. The loss in doing this is that the lock will be sitting at 3500 rather than 3570, he would be sacrificing 70 SP from himself to provide 28 SP to everyone else while DP is up. Depending on the raid setup this may or may not be worthwhile."

**Comment by Kokaina** [comment]
Quite critical issue.
