### ISSUE TITLE
Achiv.: Respect your elders

### ISSUE THREAD

**Issue by jeriks** [SunwellTracker/issues#1109]
Decription: we have burst boss without a kill any guardin and we dont have a achiv.

How it works:
 if you kill rhc boss without killing anyguardians you earrn a achiv 
and boss earn a berserk 500%

How it should work: 
https://www.youtube.com/watch?v=Y1XO6w2N6-Y

Source (you should point out proofs of your report, please give us some source): 
https://zapodaj.net/bf11695015285.jpg.html

**Comment by Dootz** [comment]
will be fixed with next server update
