### ISSUE TITLE
[Wintergrasp quests] Healing with Roses & Jinxing the Walls

### ISSUE THREAD

**Issue by a-krzysztofik** [SunwellTracker/issues#1112]
Decription: 
Both Water Revenant and Mature Lasher drop only one quest item or none.

How it works: 
Revenants visible only to players from faction which controls Wintergrasp Fortress drop one quest item.

How it should work: 
Every element Revenant should drop two quest items.

Source (you should point out proofs of your report, please give us some source): 
How it works: https://imgur.com/a/aUjCK
How it should work: http://wowwiki.wikia.com/wiki/Wintergrasp_quests
"...the different elementals will always drop one of the item. If you control Wintergrasp Keep, the elemental Revenants will drop two of the quest item instead."

**Comment by Dootz** [comment]
will be fixed with next server update
