### ISSUE TITLE
[Dungeon] Sunken Temple - Summoning avatar of Hakkar

### ISSUE THREAD

**Issue by Lexofein** [SunwellTracker/issues#1114]
Decription: 
Today I was trying summon avatar of Hakkar for quest http://db.darkwizard.pl/?quest=3528

How it works: 
I use egg http://db.darkwizard.pl/?item=10465
mobs start spawn, door closes. I kill one http://db.darkwizard.pl/?npc=8438. Get http://db.darkwizard.pl/?item=10460  Use it on fire. And nothing, Mobs just start dissapear.
I even try to use egg 4 times(5 min cd among other things), and each time kill bloodkeeper and use blood on other fire, until I used it on all 4 fires.
I find this video, trying to google what I did wrong https://www.youtube.com/watch?v=wQd8AVdqCOw
But it didn't work for me like that. Minions are just endless spawns in 1 second after being killed.
Maybe problem with I don't kill them all enough fast? I am doing this quest solo by 55 warrior because people in 99.999% interesting only in fast kill last boss and leave.
How it should work: 
Dosn't know how it should work, but I can't summon at all.

Source (you should point out proofs of your report, please give us some source):

**Comment by Towoku** [comment]
Hello,
just did it today. its passable but got some issues. in 5 man group it should be easy passable. or with 80 lvl helper. U need t do it in 4:30 or it ends. And there's only 4 npcts that drop blood so if you miss one ( or someparty member is afk that got it droped) i may end and you need too restart it. also those dragons that cancel ritual kinda spawn in wierd moments, but not sure if its bug or not. More like dev variation of a event. If you need help with this quest just pm me IG and ill help ya :)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1462
