### ISSUE TITLE
The Iron Thane and His Anvil & Blackout [quest] (ELEVATOR BUGS)

### ISSUE THREAD

**Issue by hairychestfan** [SunwellTracker/issues#1116]
**Decription:** 
So these 2 quests take you into a building where you need to use the elevator but the elevators are bugged and you get stuck in an elevator shaft forcing you to use Hearthstone to leave the place.

**How it works:** Elevators seem to be non existant its just a hole but occasionally you do see an elevator but when you step on it you just fall through and get stuck

**How it should work:** Elevators should work like any elevator works (example: thousand needles and thunder bluff, undercity... elevators work)

Source (you should point out proofs of your report, please give us some source):

**Comment by TSSchoof** [comment]
Can confirm. Same thing happened to me.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1494
