### ISSUE TITLE
The sons of Hodir

### ISSUE THREAD

**Issue by kentagent134** [SunwellTracker/issues#1117]
Decription: Reacently got friendly with The sons of hodir and whanted to countinue questing on them,
They are friendly to me but when i check my rep tab, its has a red background on it like i+m unfriendly with them

How it works: I cant take any quest insted i can only attack them

How it should work: that i cant attack them and i can take quest

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, do you have option "At war" checked? You should see it when you click on this faction in your rep tab.

**Comment by kentagent134** [comment]
OHH thanks, never would figur it out
