### ISSUE TITLE
[Battlegrounds] Flag capturing interrupted by dots & ground aoe

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#1118]
Decription: 
Currently AoE on ground, and most DoTs will interrupt your tries to cap a flag in battleground.

How it should work: 
Only direct damage should interrupt.

**Comment by Dootz** [comment]
And here's something to confirm it : https://us.battle.net/forums/en/wow/topic/2878770151

**Comment by Rosenkrantz** [comment]
Currently, Moonfire and Flame Shock **instant** damage doesn't interrupt capping; Devouring Plague **ticks** do interrupt. 

By your linked topic, these interactions should be reversed - as a general rule, instant damage should interrupt, remaining DoT shouldn't.

**Comment by ujellyx** [comment]
Can confirm OP's report.
