### ISSUE TITLE
[Warlock] Decimation talent.

### ISSUE THREAD

**Issue by razarah** [SunwellTracker/issues#1120]
Decription: 

If you shadow bolt or incinerate a target which is at or above 35% of its health, you gain Decimation which reduces the cast time of soul fire by 40% for 10s and doesn't consume a soul shard if cast under the effect of decimation.
How it works: 
If you finish your cast of soul fire after Decimation buff wore off (but started it when it still was on), it will consume a soul shard. Of course won't cast it if you have 0 soul shards.

How it should work: 
In my opinion it shouldn't consume a soul shard in such case, I don't really know how it worked on retail.

Source (you should point out proofs of your report, please give us some source): 
You can easily reproduce it ingame.

**Comment by Amarok-bt** [comment]
Not a bug
