### ISSUE TITLE
[Quest][Warlock] Devourer of Souls should be available w/o prequest

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1121]
Decription: 
Do not agree with closing this issue #754 . Quest with should be available after reaching 20 lvl in stormwind ( by logic why do humans need to go to ironforge and then go back to sw ). Anyway did research long time ago and im gonna link it below.
How it works: 
As human you need to go to ironforge and receive pre-quest from gnome warlock to start scubbus quest
How it should work: 
At lvl 20 its available in stormwin
Fix : 
If its my old good DB and its the same as it used to be here's fix ( i should probably link pastebin but not sure when s1 gonna look into it):
UPDATE `quest_template` SET `Nextquestid` = 0, `NextQuestIdChain` = 0, `ExclusiveGroup` = 1716 WHERE `id`=1717; 
UPDATE `quest_template` SET `PrevQuestid` = 0, `ExclusiveGroup` = 1716 WHERE `id` =1716;

Source (you should point out proofs of your report, please give us some source): 
1st one states that [20] Devourer of Souls (Stormwind) (Alliance) (Alternative start of Questline: Gakin's Summons (Succubus) in Ironforge)
2nd is just old vanilla guide how to obtain pet for human warlock and he don't need to go into IF
http://wowwiki.wikia.com/wiki/Warlock_quests
http://home.planet.nl/~pete0420/wow/warlockinfo/Succubus-AllianceSW.htm

**Comment by Dootz** [comment]
will be fixed with next server update
