### ISSUE TITLE
Deathgrip Flying mount glitch/bug

### ISSUE THREAD

**Issue by snafuLAD** [SunwellTracker/issues#1122]
Decription: 
Deathgrip Bug 

How it works: What happens is deathknight will chase you on flying mount , when he catches you he will use his death grip ability, Which forces you on your mount from way up in the sky all the way too the ground. Which where the DK and others will kill you.
Usually seen done with a priest so the DK takes no fall damage.

How it should work: 
Death grip whilst you're mounted 1000 FT in the air on your flying mount shouldn't send you flying too the ground , deathgrip should only send you to the deathknights location. Therefore clearly a bug

Source (you should point out proofs of your report, please give us some source):

**Comment by set-theorist** [comment]
Happens with underwater units as well. They get taken to the bottom of the map when gripped underwater.

**Comment by Azathothh** [comment]
https://www.wowhead.com/forums&topic=55164
