### ISSUE TITLE
Quest: Mr. Floppy's Perilous Adventure

### ISSUE THREAD

**Issue by TSSchoof** [SunwellTracker/issues#1126]
Decription: Escort quest found in Grizzly Hills. I however didn't find Emily on her usual spot(http://www.wowhead.com/npc=26588/emily). But in the middle of the woods. It's possibly somebody just completed the escort quest. I was able to accept the quests there though. 

How it works: Emily Floated back to her starting position.
![wowscrnshot_033018_192935](https://user-images.githubusercontent.com/2319986/38164801-1e3fda9e-350a-11e8-81e9-12151d306e96.jpg)
![wowscrnshot_033018_192958](https://user-images.githubusercontent.com/2319986/38164802-1e5cad5e-350a-11e8-8fa6-f07dc173700b.jpg)

Where she began going down the path (without Mr. Floppy). Her usual dialogue appears, the wolves appeared etc.

When the last wolf spawns he is not targetable (this is correct), but he doesn't take Mr. Floppy in his mouth.
![wowscrnshot_033018_193240](https://user-images.githubusercontent.com/2319986/38164823-906b7b96-350a-11e8-83b1-70d3de97085c.jpg)

How it should work: 
- You shouldn't be able to start the quest with Emily when she isn't in the tower.
- Mr. Floppy should follow Emily
- The Last Wolf should take Mr. Floppy in his mouth.

Source (you should point out proofs of your report, please give us some source): 
- https://www.youtube.com/watch?v=FnHXYNYKMjA 
- http://www.wowhead.com/quest=12027/mr-floppys-perilous-adventure

**Comment by Dootz** [comment]
will be fixed with next server update
