### ISSUE TITLE
Obsidian Sanctum - Emblem Distribution

### ISSUE THREAD

**Issue by Elegance12** [SunwellTracker/issues#1129]
How it works: 
If you kill any of the 3 drakes, you get an ID but no emblem.

How it should work: 
Each Drake gives you 1 emblem if you kill them outside Sartharion Encounter.
Sarharion should only drop extra emblems for drakes that are killed within the encounter.

Source (you should point out proofs of your report, please give us some source): 
Video is 
Here you can see that after they killed first drake, they loot the emblem.
https://youtu.be/0S5V8Z4ZiEs?t=1m59s
and another video (loot comes in the middle of the UI)
https://youtu.be/zI8ATa19puQ?t=3m14s

**Comment by Dootz** [comment]
will be fixed with next server update
