### ISSUE TITLE
[Mage Talent] Brain Freeze procs not showing on SCT

### ISSUE THREAD

**Issue by Ghettomagus** [SunwellTracker/issues#113]
Decription: When you get a Brain Freeze proc (Fireball!) there is no notification of that in the Scrolling Combat Text like there should be, other talents such as Fingers of Frost show the buff gained normally.

How it works: When you gain a Fireball! buff there is no scrolling combat text (or "Reactive spells & abilities) indicating that you got a proc.

How it should work: There should be a notification just like with Fingers of Frost.

Source (you should point out proofs of your report, please give us some source): Just go cast Blizzard on a pack of mobs with Brain Freeze talent picked for 2 seconds and you'll see it.

**Comment by dredd-sunwell** [comment]
Can you give the proof that it should work like you said?

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
