### ISSUE TITLE
Lord Marrowgar

### ISSUE THREAD

**Issue by Sunwellxd** [SunwellTracker/issues#1130]
Decription: 
Marro po Bone Storm nie resetuje threatu

How it works: 
po bone storm utrzymuje sie threat od poczatku walki

How it should work: 
Po bone storm threat powinien byc zresetowany

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=b7lGWk6V-74
1:15s widac w omenie threat 
1:34s therat zostal zresetowany (koniec bone storm)

https://www.youtube.com/watch?v=_2G7AExNyj8&t=67s
0:48s bone storm marrowgara
1:08s threat skasowany

**Comment by Elaatu** [comment]
Tylko czemu na filmiku Paragonow sie nie resetuje? https://m.youtube.com/watch?t=365s&v=o3zFud2T-5Y

**Comment by Sunwellxd** [comment]
i sa z wersji normal,mozliwe ze wersja hc sie roznila.
Jezeli ktos bedzie mial wiecej czasu moze poszperac i znalezc wersje norm nagrana poznym icc.
Do tego czasu,mysle ze mozna zgloszenie zamknac z powodu braku rozsadnych dowodow.

**Comment by Dootz** [comment]
obecne zachowanie marrowgara jest zamierzone i nie będzie zmieniane
