### ISSUE TITLE
[Quest order] A Spark of Hope

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1133]
Decription: 
Handed in [The Refiner's Fire](http://www.wowhead.com/quest=12922/the-refiners-fire) to the Anvil but did not get this quest afterwards.

How it should work: 
Should get this quest from [Fjorn's Anvil](http://www.wowhead.com/object=192060/fjorns-anvil) right after handing in The Refiner's Fire.

P.S - Tried deleting my cache to no avail.

**Comment by TheBigBallsOfFury** [comment]
I was able to get this quest only after turning in Mending Fences.

**Comment by Dootz** [comment]
That's indended behaviour. Because when you turn in A Spark of Hope phase in this area changes and players are no longer able to see giants for Mending Fences. Because of that many players were stuck on Sons of Hodir chain, so we changed it to make sure you turn in Mending Fences first.

**Comment by TheBigBallsOfFury** [comment]
Hopefully an alternative fix can be found to the situation because:

- The reputation this quest is the only way to making sure you are not hostile with Sons of Hodir after turning in Mending Fences and getting the subsequent quest Forging an Alliance which is mandatory to progress the story. Without turning in the quest you are stuck with nothing to do as Thorim does not give the quest, and Sons of Hodir is not friendly yet (because of the missing reputation).

- The player then has to fly back to the Anvil on the edge of the map (with no reason to do so) to accept A Spark of Hope and turn it in to continue the questing.

1. New players who do not know of this change have no reason to return to the Anvil unless they go to wowhead and suspect they missed that quest, or are told by someone that this change has been made.
2. Destroys continuity and immersion of an otherwise beautifully working main quest line of Storm Peaks.

I understand that this is not a top priority issue, but hopefully can be addressed in the future to further polish the already good questing experience.

**Comment by nimeral** [comment]
Can confirm it's still an issue. The lazy fix you've made is better than nothing though, thank you for it : )
