### ISSUE TITLE
Time Lost Proto Drake dies during route.

### ISSUE THREAD

**Issue by helofriend** [SunwellTracker/issues#1134]
Decription: Time Lost Proto Drake flies into a minefield on his route and dies. He also gets teleported down to the ground randomly.

How it works:  Time Lost Proto Drake flies into a minefield on his route and dies. He also gets teleported down to the ground randomly.

How it should work: Time Lost Proto Drake flies through The Storm Peaks until a player kills him. (Or he possibly despawns naturally, not dying to mines.)

Source (you should point out proofs of your report, please give us some source): https://cdn.discordapp.com/attachments/379373215694323715/429886633576366080/WoWScrnShot_040118_010913.jpg 

This is an image of where he died right outside K3 in the storm peaks. No player hit him.
april first 2018 8:08 realm time

As for more proof, you can spawn him yourself and watch his routing. I flew to TLPD spawn right after the server restarted.

**Comment by Dootz** [comment]
As for random teleport it's indended. It's one of his skills http://www.wowhead.com/npc=32491/time-lost-proto-drake#abilities - Time Shift.

However minefield thing shouldn't happen. I'll check that.

**Comment by Dootz** [comment]
will be fixed with next server update
