### ISSUE TITLE
[Quest][Cave Medicine]

### ISSUE THREAD

**Issue by heniuus** [SunwellTracker/issues#1135]
Decription: 
Tracker Val'zij, at Gimorak's Den, wants you to obtain 1 Jormungar Toxin Gland and 8 Cave Mushrooms.

How it works: 
Jormungar's Toxin won't drop. I've killed 82 mobs (82 Worm Meats in bag) or even more, and still nothing.

How it should work: 
With 5% drop rate kill max 20 mobs, collect toxin, complete quest.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=13055/cave-medicine

**Comment by Dootz** [comment]
drop chance is small, but it should eventually drop. Will be increased with next server update
