### ISSUE TITLE
[Drop] Rethban Ore (2798)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#1137]
Decription: 
Rethban Ore (https://db.darkwizard.pl/?item=2798#dropped-by) required to complete alliance-only quest of the same name (https://db.darkwizard.pl/?quest=347) seems to be mined not only from Copper and Tin Veins in Redridge Mountains but in other locations as well.

How it works: 
Currently one can get Rethban Ore off Gnolls, Copper and Tin Veins in Redridge Mountains and in other locations as well - the quest requires 5 ores to be completed - I mined 3 in Redridge, 1 in the Barrens and 1 in Thousand Needles (will provide pics if needed).

How it should work: 
Rethban Ore should only be mined from Copper and Tin Veins in Redridge Mountains and dropped off Gnolls in the same location.

Source (you should point out proofs of your report, please give us some source): 

Wowwiki
(http://wowwiki.wikia.com/wiki/Rethban_Ore)

Wowhead
(http://www.wowhead.com/quest=347/rethban-ore)
(http://www.wowhead.com/item=2798/rethban-ore)

**Comment by Dootz** [comment]
According to wowhead comments:

> By Xaemoon (1,491 – 7·20) on 2016/09/07 (Patch 7.0.1)
> This quest has been unavailable for years, but you can still mine Rethban Ore (which has no purpose outside this quest). I just got some today in Feralas and came to see if they re-instated the quest. Nope. Even though it's not a grey item, it IS vendor trash.

> By Taraezor (15,614 – 3·22·203) on 2016/01/11 (Patch 6.2.3)
> Incredibly, I got two of these in Thousand Needles, along with two solid stone. Never heard of it so came here. Looking at the obsolete quest I am thinking... did the gnolls or whatever get washed all the way over here from Redridge come the Cataclysm?

> ghostmaster123 on 2010/10/23 (Patch 4.0.1)
> No man, you're wrong. I just mined it in Westfall in a tin vein


Of course those comments are from later expansions, but still.

**Comment by Akha72** [comment]
Very well then.
