### ISSUE TITLE
Shadow Sight in arena does not work

### ISSUE THREAD

**Issue by sunwellfan** [SunwellTracker/issues#1138]
Decription: 
Shadow Sight in arena does not work, the nameplates of enemy player does not pop up so they can just LoS you and you will never find them.

How it works: 
Nameplates are not shown

How it should work: 
Nameplates should show

Source (you should point out proofs of your report, please give us some source): 
OBVIOUS (shadow sight is currently totally useless and rogues are abusing it)

**Comment by Danieloses** [comment]
https://youtu.be/bzZnll1ewis?t=2m9s

**Comment by ujellyx** [comment]
Stealthed targets never have nameplates if i recall correctly. Doesn't matter if you can see them or not.
