### ISSUE TITLE
[Mining Node] Underground in Icecrown. Cannot reach

### ISSUE THREAD

**Issue by bubblebobble111** [SunwellTracker/issues#1139]
Decription: 
There is a mining node location in icecrown that spawns underground. The location is 63,22. There are times when it spawns as titanium which causes me to become sad that i cannot reach it. 

How it works: 
The node is below the surface of the ground. Unable to reach

How it should work: 
Node should be above ground.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_040118_200933](https://user-images.githubusercontent.com/37989270/38179364-09bed0a0-35e8-11e8-8216-26990238607f.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
