### ISSUE TITLE
[Quest Order & Dialogue] Catching up with Brann 

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1140]
1) Quest [Catching up with Brann](http://www.wowhead.com/quest=12920/catching-up-with-brann) should not be available before completing quest [Speaking with the Wind's Voice](http://www.wowhead.com/quest=12917/speaking-with-the-winds-voice).
2) Dialogue between player and Brann after activating item is missing.

Source (you should point out proofs of your report, please give us some source): 
1) http://wowwiki.wikia.com/wiki/Storm_Peaks_quests
http://www.wowhead.com/quest=12917/speaking-with-the-winds-voice#comments:id=405701
2) https://wow.gamepedia.com/Quest:Catching_up_with_Brann#Notes

**Comment by Dootz** [comment]
will be fixed with next server update
