### ISSUE TITLE
[RP Event] The Damaged Journal & Deciphering the Journal

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1141]
NPCs should say few lines after these quests are handed in.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12026/the-damaged-journal#comments:id=1130355
http://www.wowhead.com/quest=12054/deciphering-the-journal#comments:id=1130369

**Comment by Dootz** [comment]
will be fixed with next server update
