### ISSUE TITLE
[NPC] Ricket (29428) - Dialogue

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1142]
Decription: 
1) Option to head further into Storm Peaks should not be available before accepting When All Else Fails.
2) Dialogue option should send you on a rocket to the next quest hub depending on Horde or Alliance.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29428/ricket

**Comment by Dootz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13298#issue-45453546

**Comment by Dootz** [comment]
will be fixed with next server update
