### ISSUE TITLE
Converted Hero Icecrown

### ISSUE THREAD

**Issue by Motaru1234** [SunwellTracker/issues#1143]
Decription: 
The mobs in Icecrown that are in  packs of 8-9 don't drop money and some of them have no loot. 

How it works: 
The mobs in Icecrown that are in  packs of 8-9 don't drop money and some of them have no loot. 

How it should work: 
They should drop money same as retail and other servers.Also if you look at the picture on wowhead they should have some chains on them.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=32255/converted-hero

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by Motaru1234** [comment]
When is next server update.thanks in advance.
