### ISSUE TITLE
[Priest] Vampiric Embrace keeps you in combat

### ISSUE THREAD

**Issue by janipeltonen** [SunwellTracker/issues#1148]
Decription: Healing party members with vampiric embrace puts you in pvp combat (takes longer to drop than pve combat) even when only fighting monsters. This is not game-breaking but annoying. This doesn't happen in solo-play.

How it works: Having vampiric embrace on and dealing damage (healing party members) keeps you in combat for 5-6s even after monsters die. Presumably when it heals your party it considers it pvp healing.

How it should work: After all monsters are dead, combat should drop immediately (it does for every other player in the party), even if you heal through vampiric embrace.

Source (you should point out proofs of your report, please give us some source): Leveled a priest to 80 and still playing shadow.  Couldn't use vampiric embrace when questing in a party because it slowed the process down too much. (not being able to mount after mobs)

**Comment by Riztazz** [comment]
@Shatterx @Azathothh @Kokaina Please test, i cannot reproduce this one locally

**Comment by ujellyx** [comment]
Kindly note, that this only happens when party members are healed with vamp embrace (PvE and PvP). Happens to me all the time while doing dungeons.

**Comment by Azathothh** [comment]
Ok, so i put shadow word:pain on a monster, wait till it ticks, so me+person in party gets heal from vampiric embrace, after that heal i kill monster and combat is gone right after his dead.
Need more info how to reproduce it.
