### ISSUE TITLE
Quest Fresh Remounts ID : 12214 - Not able to mount the horse

### ISSUE THREAD

**Issue by Trueliving** [SunwellTracker/issues#115]
Decription: 

Bugged quests in Dragonblight, Fresh Remounts, ID : 12214, tried all solutions possible and checked database comments, I am not doing something wrong.

How it works: 

You kill the knights, you get the crop, the horse turns friendly but you are not able to mount it. You cannot interact by clicking on the horse and using the crop will have no effect.

How it should work: 

You should be able to mount the horse without any issues as seen in wowhead screenshots and comments. The only issues with this quest is mounting the horse, everything else seems to be working as expected.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=12214/fresh-remounts#screenshots

**Comment by Vlnkaj** [comment]
I manage to jump on two horses yesterday. But just make ticket and GM will complete it for you. (did for me).

**Comment by Trueliving** [comment]
In that case maybe some of the horses are bugged? I tried 2 of them and none worked. Dreed already completed the quest for me but just so we have it reported. Not a big deal anyway.

**Comment by Riztazz** [comment]
Resolved
