### ISSUE TITLE
[Spell][Death Knight] Death Grip

### ISSUE THREAD

**Issue by Danieloses** [SunwellTracker/issues#1150]
Decription: Death grip should have minimum range to use (like warrior's charge), atm you can grip someone who stands literally on top of you.

NOTE: I'm not providing source because it worked correctly and some developer probably accidentaly bugged it (there is no information in changelog about death grip changes). Just bring back old version of death grip.

How it works:  ^

How it should work: It should have minimal range to use.

Source (you should point out proofs of your report, please give us some source):

**Comment by knasen88** [comment]
you can only deathgrip mobs at melee range, players i atleast can't "melee" grip

**Comment by set-theorist** [comment]
Can you actually provide some source? This is a very contested matter. Some people claim that Death Grip pvp minimum range was added in 3.3 but some say that a hotfix in 3.3.3 removed the death grip's minimum range in pvp. 

Can you provide any retail video from this exact patch (3.3.5a) where death grip has minimum range?

**Comment by set-theorist** [comment]
https://www.mmo-champion.com/threads/699309-Death-Grip-change-(minimum-8yrds)/page3

"http://blue.mmo-champion.com/26/2342...s-minimum.html

IT'S NOT GOING LIVE

(read the front page of this site ffs )"

This report is invalid
