### ISSUE TITLE
[RP Event] Memories of Stormhoof (13037)

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1154]
Decription: 
[Chieftain Swiftspear](http://www.wowhead.com/npc=30395/chieftain-swiftspear) is supposed to say a few lines when player talks to them while on this quest. Currently credits the quest without any dialogue.

How it should work: 
https://www.youtube.com/watch?v=RP4TyCvCxos&feature=youtu.be

**Comment by Dootz** [comment]
will be fixed with next server update
