### ISSUE TITLE
Quest: Wandering Shay

### ISSUE THREAD

**Issue by jockeboschko** [SunwellTracker/issues#1155]
Decription:  Ran to end point of the quest "Wandering Shay" but it didn't complete

How it works: 
There is no way to complete quest at the stone giant. I tried running in out around the camp and nothing happened.  Also Shay seem to start wandering off after around 20 seconds while the bells cd is 60 seconds making it annoying. Maybe her strolling around for long periods of time fails the quest somehow.

How it should work: 
Running to the stone giant with Shay should complete the quest

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
