### ISSUE TITLE
Elixir of Agony - Captured Farmers

### ISSUE THREAD

**Issue by beregas** [SunwellTracker/issues#1157]
Decription: 
At the end of Elixir of Agony chain (Hillsbrad), the keg is not poisoning and not killing the farmers inside the inn

How it should work: 
After turning the quest on the carpet, the farmers should drink it and die in sequence.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=Q6kra8QaQaE

**Comment by Dootz** [comment]
will be fixed with next server update
