### ISSUE TITLE
Zul'aman Hex Stick NPCS/Timed Chest

### ISSUE THREAD

**Issue by AshhWoW** [SunwellTracker/issues#1159]
Decription: The forest frogs you use the hex sticks on that drop from trash drop a box that can contain a few different items. The boxes say locked when trying to open / Same issue with the timed run chests. They are locked and do not allow you to get the extra loot.

How it works: You loot an Amani Hex Stick from trash & use the item on the forest frogs in the raid/kill the 4 animal bosses within the timer.

How it should work: When you use the stick and they turn into an NPC that drops a lootable chest the chest should be able to be opened. The timed event drops a chest if killed within the timer on each animal boss & gives an extra piece of loot. Only 1 box drops from the 1st boss and it is locked, unable to loot.

Source (you should point out proofs of your report, please give us some source): I ran it an hour ago. I will post links to Screenshots at a later time when I run again.

**Comment by davchichi4** [comment]
Confirmed, timed chest are lock. I don't think its necessary to link some proofs cause everyone know that we can get the mount amani war bear from the timed chest in zul aman. The question is : isn't it intentionall to force ppl to buy this mount from the shop ?

**Comment by davchichi4** [comment]
That's exactly how we can loot the mount : "Amani bear". Put it in game pls or put ALL the mounts in the shop..
