### ISSUE TITLE
[Quest] Tormenting the Softknuckles

### ISSUE THREAD

**Issue by Wyrafinowane** [SunwellTracker/issues#116]
Description: Hardknuckle Matriarch (http://db.darkwizard.pl/?npc=28213) don't spawn/spawn as invisible, untargetable after using quest item.

How it works: After using quest item (http://db.darkwizard.pl/?item=38467) on Softknuckle we see emote that sign us about spawning mob, but we can't even see him.

How it should work: After using quest item we should saw and kill mob.

Source (you should point out proofs of your report, please give us some source):
http://www.wowhead.com/quest=12530/tormenting-the-softknuckles

**Comment by gitghost** [comment]
Even though quest mob can still be killed by aoe.
