### ISSUE TITLE
Quest: Warsong Scout Update, Warsong Outrider Update are still in quest log after finishing them

### ISSUE THREAD

**Issue by Sveron1** [SunwellTracker/issues#1160]
Decription: Quest: Warsong Scout Update, Warsong Outrider Update are still in quest log after finishing them

How it works: After finishing them they are still in quest log

How it should work: After finished quest there should be no quest in quest log
![bez tytulu](https://user-images.githubusercontent.com/16925131/38254374-721730a8-3759-11e8-9345-771b40276de0.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
strange, have you tried to relog/clear cache?

**Comment by TheBigBallsOfFury** [comment]
can confirm exactly same thing happened to me in Ashenvale, didn't make a report though.

**Comment by Dootz** [comment]
will be fixed with next server update
