### ISSUE TITLE
Quests sharing

### ISSUE THREAD

**Issue by Sologrim** [SunwellTracker/issues#1161]
Decription: 
Quests can`t be shared when in 'complete' status

How it works: 
If a quest is completed. I can`t share it. When clicking 'share', nothing happens. Even no textual response or anything.

How it should work: 
Quests should be share-able in any status.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/806
