### ISSUE TITLE
[Quest] Trolls Is Gone Crazy! - NPC and chain have different spawn times

### ISSUE THREAD

**Issue by TSSchoof** [SunwellTracker/issues#1162]
Decription: Trolls Is Gone Crazy! is a quest where you have to free captured Rageclaw by removing their chains.

How it works: The "Captured Rageclaw" and their chains have a different spawn time. Thus there are a lot of "Captured Rageclaw" that you can't free.

How it should work: 
The "Captured Rageclaw" and their chains should have the same spawn time.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=12861/trolls-is-gone-crazy

**Comment by Dootz** [comment]
will be fixed with next server update
