### ISSUE TITLE
[RP Event] The Boon of A'dal (13082)

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1163]
Missing RP event at quest turn in. There is supposed to be a sequence where naaru appear and say a few lines.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=13082/the-boon-of-adal#comments

All videos I found cut off after turning in the quest but you can see the shadow of 3 naaru units spawn in the air.

Trivia - this entire quest line is a dedication to cancer patients and their struggle.

**Comment by Dootz** [comment]
https://youtu.be/Kfu8aB2yV-Y?t=3m6s
