### ISSUE TITLE
[Quest] Fuel For the Fire (12690)

### ISSUE THREAD

**Issue by mep0** [SunwellTracker/issues#1165]
**Decription:** Fuel For the Fire
[https://db.darkwizard.pl/?quest=12690](url)

**How it works:** 
While mobs respawn rate was fixed in other report [https://github.com/SunwellTracker/issues/issues/237](url) Drakkari Chieftain takes extremely long time to respawn so quest is still hard to do if someone already done it.  I waited 30+ mins and still no respawn on them.

**How it should work:** 
Drakkari Chieftain should also respawn sooner so quest could be done.

**Comment by TSSchoof** [comment]
They don't spawn normally. They spawn when you kill a bunch of the mobs. That's what the quest means by 'luring' them.

**Comment by mep0** [comment]
Hmm its posssible that is the thing but i killed more then 60 Drakkari Skullcrushers. I guess you have to continue killing them until they spawn.

**Comment by Dootz** [comment]
They spawn for every 20 drakkari skullcrushers you kill with abomination's ability http://www.wowhead.com/spell=59576/burst-at-the-seams
