### ISSUE TITLE
[Ingeneuer] Glove enchant has the same cd of the trinket

### ISSUE THREAD

**Issue by nabermert** [SunwellTracker/issues#1166]
Decription:  If you use the pyror enchant, your active trinket goes instantly in cooldown

How it works:  if you use your trinket or glove ench, one of the things goes 30sec in cooldown, and thats bugged

How it should work: the ingeneuer glove enchant hasn't the same cooldown and you should can use the glove ench and trinket at the same time.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
http://wowwiki.wikia.com/wiki/Hand-Mounted_Pyro_Rocket
"The on-use effect will trigger the 10-second burst DPS item shared cooldown, though the cooldown for the ability itself is 45 seconds." 
And that's how it works on sunwell (Hand-Mounted Pyro Rocket triggers 10 sec cooldown here as far as I remember)

**Comment by Semper-Numquam** [comment]
Yes. You can't shoot Lightning Generator AND rocket at the same time as when you use one, the other enters a 10s CD.

I have no issue using trinkets that aren't damage dealing on use before of after using Pyro Rocket

**Comment by Azathothh** [comment]
Not a bug.
