### ISSUE TITLE
Landro's Gift Box

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#1167]
Purchased 6 boxes and 1 of them was just empty.

https://i.imgur.com/cX5JBzE.png
https://i.imgur.com/VxBbyGO.png

Seems like a bug to me since it was never just empty in retail.

2x [Papa's Hummel's Old Fashioned Pet Biscuit]x50.
2x [Path of Cenarius]x50.
1x [Sandbox Tiger]x50.
1x Empty.

**Comment by Burritodog** [comment]
Same issue here. 
1 Box was just empty and it was never empty on retail.
https://gyazo.com/852418e2c57521ac53d142eec1f2c120
https://gyazo.com/e0b4660bf6026ff0fdcf59291749a185

When i add up your % 
Path of Cenarius (36.36%)
Papa Hummel's Old-Fashioned Pet Biscuit (36.36%)
Sandbox Tiger (27.28%)
= 100%

So you should always get 1 of the 3 items and mounts are a bonus.

**Comment by 0vertime** [comment]
Leaves me worried if it was a mount that was giving empty roll.
