### ISSUE TITLE
The Oculus: Mage-Lord Urom

### ISSUE THREAD

**Issue by seriess** [SunwellTracker/issues#1168]
Description: 
It is currently possible to skip killing the summons Mage-Lord Urom spawn. 

How it works:
You can begin summoning your dragon and then aggro Urom when he's on the platforms summoning his minions. Only one person does this and moves to the next platform repeating the same thing. This way none of his minions need to be killed and you can skip to just fighting him alone in the middle. 

How it should work: 
You should need to kill the minions he summons to progress in the dungeon.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/the-oculus#npcs
http://www.wowhead.com/npc=27655/mage-lord-urom#encounter

**Comment by iamaio** [comment]
can confirm this

**Comment by Dootz** [comment]
will be fixed with next server update
