### ISSUE TITLE
Bristleback Geomancers can't be LOS'd in the barrens 

### ISSUE THREAD

**Issue by magicdadi** [SunwellTracker/issues#1169]
Decription:  I was leveling my Tauren druid when I ran into this bug. I couldn't LOS the bristleback so that I won't take dmg from the fireball. This made the leveling experience painful since the game is not working how it should

How it works: 
When Birstleback Geomancer uses fireball on you, he doesn't get LOS'd by the vines.

How it should work: 
When Birstleback Geomancer uses fireball on you, he gets LOS'd and has to move in LOS

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=kDtO4g554zQ&feature=youtu.be

**Comment by Azathothh** [comment]
I'm pretty sure it was working like that on retail.
If you think otherwise - please find some proof.
