### ISSUE TITLE
Netherspite in kara - Beams don't trigger on your player and you can't block them

### ISSUE THREAD

**Issue by Anselm123** [SunwellTracker/issues#1170]
Decription: NS is bugged

How it works: You cannot block the beams on NS in kara.

How it should work: You block the beams to get the buffs to kill the boss

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=Tf-2iw_aK90

**Comment by Azathothh** [comment]
Works fine for me.
