### ISSUE TITLE
[Quest] Retest Now - Some mobs do not drop quest item

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1172]
How it works: 
Tainted Essence drops only from Damned Apothecary & Cult Alchemist.

How it should work: 
Should also drop from Dark Subjugator, Vile Torturer, Cult Blackguard.

Source (you should point out proofs of your report, please give us some source): 
Shows in client tooltip.
http://www.wowhead.com/quest=13357/retest-now#comments

**Comment by Dootz** [comment]
They drop it but chance is currently around 40%

**Comment by TheBigBallsOfFury** [comment]
I must have been very VERY unlucky then :(

Not sure what the true drop rate should be though. Feel free to close this, quest is definitely completable.

**Comment by Dootz** [comment]
will be fixed with next server update
