### ISSUE TITLE
[NPC - Cosmetic] Scout Nisstina - Missing dialogue

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1179]
She should be standing (instead of /sit) and have a 3 different dialogue interactions.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29778/scout-nisstina#comments:id=485247

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by TheBigBallsOfFury** [comment]
Update seems to be live but nothing's changed on my end after deleting cache.

**Comment by Afgann** [comment]
Angrathar will be updated tomorrow.
