### ISSUE TITLE
Using spell reflect while stunned.

### ISSUE THREAD

**Issue by anticlutch** [SunwellTracker/issues#1181]
Decription: 
A warrior can spell reflect while stunned. Which means he can change his weapon into a shield while stunned. This is obviously unintended as while you're stunned the intention is to be unable to do nearly anything.

How it works: 
Stun a warrior - for me with deep freeze.
Cast spell on warrior - for me it was frost bolt.
Warrior then applies shield and 1h weapon.
Frost bolt is cast and mid air.
Spell reflect is put up.
Spell gets reflected back to the mage.

How it should work: 
The warrior should stay and be stunned and should not be able to use spell reflection while stunned.

Source (you should point out proofs of your report, please give us some source):

**Comment by set-theorist** [comment]
Never experienced this

**Comment by gabbat** [comment]
this is a false bug report, as a mid-air spell can never be reflected anyway. please retry

**Comment by Azathothh** [comment]
Invalid report.
Missing proofs/sources.
