### ISSUE TITLE
[Quest] For Great Honor - Should be removed since marks of honor are unobtainable

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1182]
Patch 3.3.5 has no use for mark of Honor. This quest offered by Horde Warbringer and probably the Alliance counterpart is not completable and should be removed since there are no Marks of Honor in the game with any player at all (since the server was released on patch 3.3.5).

**Comment by Dootz** [comment]
Blizzard left those quest, so they won't be removed here aswell.
