### ISSUE TITLE
[Battleground] Eye of the Storm resurrecting

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#1183]
How it works: 
If you're dead and spirit waiting for resurrect, your base is being captured by enemy and it's already gone gray, you stay there as spirit until your team next time captures it. Making you have to run to the nearest graveyard or jumping down in the void.

How it should work: 
If you're dead and spirit waiting for resurrect and if your base is gray, you should get teleported to nearest controlled base.

Also capture zone's seem to be smaller than retail, by like 10-20% per base.

**Comment by TheBigBallsOfFury** [comment]
Also happens in Strand of Ancients

**Comment by Danieloses** [comment]
The teleport bug happens on AB and SoA too. Also when you die from falling on eots your corpse will be teleported to spawn and after releasing spirit you will respawn on spawn. After falling corpse should stay down and you should get teleported to the closest base after realeasing spirit, not to the spawn.

Also can confirm the capture zone being to small, it definitly was bigger on retail.

**Comment by Rosenkrantz** [comment]
Happens on Wintergrasp too, but only sometimes. On EotS it's 100% guaranteed.
