### ISSUE TITLE
Talonsworn Forest-Rager

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1186]
Decription: not enough spawns of this NPC

How it works: currently there's 3 spawns.

How it should work: there should be 4 spawns according to WoWhead, the comments there, and the Wowroad.info map (we're missing the northern spawn).

Source (you should point out proofs of your report, please give us some source):  http://wowroad.info/?npc=23029   http://www.wowhead.com/npc=23029/talonsworn-forest-rager#comments:id=166186     http://www.wowhead.com/npc=23029/talonsworn-forest-rager#comments:id=225375

**Comment by Dootz** [comment]
will be fixed with next server update
