### ISSUE TITLE
[Quest] Hot and Cold

### ISSUE THREAD

**Issue by hairychestfan** [SunwellTracker/issues#1187]
Decription:  So this quest works fine but the main problem is that due to **high population** this place is camped 24/7 therefore many of us cant even complete this quest and can't progress our sons of hodir rep falling behind other players and not getting invited into raids due to not having shoulder enchant.

How it works: Mobs take too long to respawn and maybe there is too few of them and they don't necessearily drop the quest item making it even harder to complete. (if you lucky enough to get to see one alive and kill it)

How it should work:  To fix the problem imo would be to increase their respawn rate to 1 minute.. make them 100% to drop a quest item, and incresae the number of quest mobs by 50%...

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=30160

**Comment by eloquence743** [comment]
Not blizzlike, and should not be done. Many people are already exalted, and ignoring the dailies. This will futher prove to happen in the coming months, so leaving everything as it is is a fine choice. Plus, you can always kill opposing faction.

We're not here for easy numbers, this should not be changed as it is working as intended.
