### ISSUE TITLE
Mal'Ganis gives no emblems

### ISSUE THREAD

**Issue by hairychestfan** [SunwellTracker/issues#1188]
Decription:  Killing boss Mal'Ganis in Caverns of Time: The Culling of Stratholme doesn't give any Emblem of Heroism

How it works: Killing final boss of the Culling of Stratholme doesnt reward players with any Emblem. Instead it displays "You don't have any space in your bags" message.

How it should work: Players should get Emblems of Heroism for killing the boss

Source (you should point out proofs of your report, please give us some source):

**Comment by Semper-Numquam** [comment]
Isn't the emblem provided when you open the spoils chest?
