### ISSUE TITLE
[AOE Bugg] to large, fail proccs etc..

### ISSUE THREAD

**Issue by nabermert** [SunwellTracker/issues#1189]
my englisch isnt good enough to explain it, so i will write it in germany.

Decription:  alle aoe effekte im spiel haben eine größere range als angezeigt, zudem wirken sie dauerhaft statt in intervalle.

How it works:  der aoe effekt ist wesentlich größer als angezeigt, zudem wirkt der zauber nicht in intervallen, sondern permanent was auch nicht richtig ist.

How it should work:  JEDES aoe, sei es tod und verfall(dk) oder vom paladin weihe, muss der schurke seine gegner (sap) auch wenn sie mitten in ihren effekt drin stehen AUßER vom jäger (Leuchtfeuer) !

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Invalid report.
Missing proofs/sources.
