### ISSUE TITLE
[Combat][Spell] Beacon of Light

### ISSUE THREAD

**Issue by Danieloses** [SunwellTracker/issues#119]
Decription:  Beacon of Light po ostatnich fixach nadal szczęśliwie nabija combat.

How it works: Gdy zostajemy wyleczeni przez Beacon of Light otrzymujemy combat, CO WIĘCEJ nawet będąc poza zasięgiem beacona i nie otrzymując leczenia też randomowo wchodzimy/wychodzimy z combatu więc nie wiem do końca w czym problem.

![wowscrnshot_020118_142110](https://user-images.githubusercontent.com/23665812/35682856-6c073040-0762-11e8-8fae-7a490b064ad5.jpg)
![wowscrnshot_020118_142119](https://user-images.githubusercontent.com/23665812/35682857-6c207384-0762-11e8-8bce-ac5885bdc58a.jpg)
![wowscrnshot_020118_142125](https://user-images.githubusercontent.com/23665812/35682858-6c3954ee-0762-11e8-9253-bdef0bfb779f.jpg)
![wowscrnshot_020118_142146](https://user-images.githubusercontent.com/23665812/35682859-6c52381a-0762-11e8-9a82-0c5c0461aae0.jpg)

How it should work: Zero ingerencji w combat.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
