### ISSUE TITLE
Loque'nahak Respawn Timer

### ISSUE THREAD

**Issue by Nadiirr** [SunwellTracker/issues#1191]
Decription: 
Reports of this mob being killed 10 times by 1 player within 8 hours.

How it works: 
Mob respawns too fast. 
.npc info shows it has 10 min respawn timer

How it should work: 
I believe it should have a 6-12 hour respawn. Can't find any solid source.

Source (you should point out proofs of your report, please give us some source): 

![screenshot_41](https://user-images.githubusercontent.com/36300104/38461259-0d2d45d6-3a80-11e8-8572-2e3c59734088.png)

**Comment by Dootz** [comment]
will be fixed with next server update
