### ISSUE TITLE
[Suggestion for enhancement] Quest: Free your mind

### ISSUE THREAD

**Issue by thanhtotti** [SunwellTracker/issues#1193]
Description: 
The respawn time of Vile, Lady Nightswood and the leaper was too slow, and they despawn too quickly. 

How it works: 
This quest is a bottleneck because too many people want to open shadow vault (knight of the ebon blade quartermaster). We have to do it individually since the credit doesn't count for party members.

How it should work: 
Suggest for enhancement: We can either:
- Significantly reduce respawn time of Vile, Lady Nightswood, and The Leaper
- Increase despawn time for them
- Or make the quest doable in party (1 person do, the others in the party have credit)

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12893/free-your-mind#comments

**Comment by MrTide** [comment]
Hello This is what happens @Dootz when you kill mobs at their spawn point sometimes they bug out and despawn and you can't use quest item on them thats the issue
but still doable you just need to pull mobs far back from their spawn point
