### ISSUE TITLE
[Quest] The Wayward Apprentice

### ISSUE THREAD

**Issue by Timeric** [SunwellTracker/issues#1194]
Decription: 
We can accept the quest from the questgiver and the other NPC is there, but doesn't have a quest mark.

How it works: 
http://www.wowhead.com/quest=9254/the-wayward-apprentice

How it should work: 
https://www.youtube.com/watch?v=cmAe_DIb9sU

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/38181349/38466898-114903c8-3b28-11e8-9e08-bf352a79de33.png)

**Comment by Akha72** [comment]
Abandoning the quest and doing it again made it possible to complete it for me. However, I did it after server restart (No idea if it's relevant but just yeah, fyi).

**Comment by MrTide** [comment]
@Dootz Hi i can confirm this sometimes it bugs out and only GM reset ( kill and respawn ) or server restart fixes it

**Comment by Dootz** [comment]
I figured it out. She sometimes bugs out. It will be fixed with next server update, which is sadly in next week.

**Comment by Dootz** [comment]
will be fixed with next server update
