### ISSUE TITLE
Gretta the Arbiter's daily quest unavailable after daily reset at 09:29 server time

### ISSUE THREAD

**Issue by Tonev** [SunwellTracker/issues#1195]
Decription: 
I was redirected here by a GM, because they do not reset quests. 
The NPC, Gretta the Arbiter, located at Brunnhildar Village in Storm Peaks, has no daily quest available after today's daily reset. Everything was all right yesterday, I personally completed the quest without any problems at all.

How it works: 
Gretta the Arbiter has no quest to offer, the reset successfully took place at 09:29 server time this morning.

How it should work: 
Gretta the Arbiter is supposed to offer one random daily quest a day. 

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Gretta_the_Arbiter

**Comment by Dootz** [comment]
Have you completed required prequests?

**Comment by Dootz** [comment]
ok, i'll check that

**Comment by Tonev** [comment]
Thank you, highly appreciated. My in-game characters on Angrathar are Xeas and Bto.

**Comment by Tonev** [comment]
Hello,

I'm able to pick up the daily quest after the daily reset that just happend. I'll report again after the daily reset tomorrow.

**Comment by Dootz** [comment]
ok. Thanks. I'm not sure what happened yet.

**Comment by Tonev** [comment]
I'm able to pick up the daily quest again. I believe the problem is gone now :)

**Comment by Tonev** [comment]
Unfortunately it happend again. I completed yesterday's daily, and she wouldn't give me another one after the reset.

**Comment by Tonev** [comment]
It happend again, unfortunately. Yesterday I completed http://wowwiki.wikia.com/wiki/Quest:Defending_Your_Title, and there's no quest for me after the reset today.

**Comment by Dootz** [comment]
ok, i'll check it.

**Comment by Dootz** [comment]
Meanwhile, do you by any chance remember if you were getting all four dailies? Here they are:
http://www.wowhead.com/quest=13422/maintaining-discipline
http://www.wowhead.com/quest=13425/the-aberrations-must-die
http://www.wowhead.com/quest=13424/back-to-the-pit
http://www.wowhead.com/quest=13423/defending-your-title

**Comment by Tonev** [comment]
From all of them, I've never done http://www.wowhead.com/quest=13425/the-aberrations-must-die.

**Comment by Tonev** [comment]
I've completed 3 of 4, never got to do http://www.wowhead.com/quest=13425/the-aberrations-must-die.

**Comment by Dootz** [comment]
thanks for the update. Do you recall completing quest: Aberrations? (http://www.wowhead.com/quest=12925/aberrations). Because that's the prequest required for this daily. Or you completed all quest in this area? I'll fix it with next server update.

**Comment by Tonev** [comment]
I just completed the quest you linked, but unfortunately, that didn't unlock any daily quest.

**Comment by Tonev** [comment]
Update **_after_** the daily reset: I successfully completed http://www.wowhead.com/quest=13425/the-aberrations-must-die. My previous post was **_before_** the daily reset.
