### ISSUE TITLE
Raven Stones Quest

### ISSUE THREAD

**Issue by banzerer** [SunwellTracker/issues#1196]
Decription: the Quest Raven Stones in the quest chain of fast flying form of druid

How it works: you use the cenarion sparrowhawk whistle in skettis and the hawk Shows up and stands and does nothing.

How it should work: you call the hawk with the canrion sparrowhawk whistle then he Comes out and searches for the raven Stones so u can loot them u Need 8

Source (you shoul
![wowscrnshot_040818_154153](https://user-images.githubusercontent.com/38184237/38468408-8aa6600e-3b45-11e8-8a93-f2d188a9d23b.jpg)
![wowscrnshot_040818_154333](https://user-images.githubusercontent.com/38184237/38468409-8ac2fe26-3b45-11e8-9d1f-3452d1b41d4a.jpg)
![wowscrnshot_040818_154447](https://user-images.githubusercontent.com/38184237/38468410-8adf2a38-3b45-11e8-9da9-e4d3ac933092.jpg)
![wowscrnshot_040818_154530](https://user-images.githubusercontent.com/38184237/38468411-8b0070f8-3b45-11e8-9ed6-7b06a07accee.jpg)
![wowscrnshot_040818_154537](https://user-images.githubusercontent.com/38184237/38468412-8b1e8502-3b45-11e8-8c1b-0146734a228f.jpg)

d point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Confirmed. But the quest is completable.

**Comment by Tyton89** [comment]
This was fixed and Implemented on Jun 21, but I'm encountering the same issue on 11/26/2019. Does this need to be resolved on Frosthold as well?
