### ISSUE TITLE
Obsidian Sanctum - Sartharion Tail Swipe Bug

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#1199]
Decription: After a player gets hit by Tail Swipe, later on in the fight they can be randomly interrupted during spell casting as if hit by Tail Swipe, just without the stun debuff.

How it works: During OS25 (not sure about 10m), if a spell caster is hit by Tail Swipe, any point after that the caster can be randomly interrupted during casting. It acts like  you are hit by Tail Swipe, but you don't get the stun debuff, just the interrupt.

How it should work: You should only be interrupted if hit by Tail Swipe.

Example of problem. I didn't hit Escape during these interrupts.
https://www.youtube.com/watch?v=O71MP6AL9uA

**Comment by gabbat** [comment]
isnt that one related to the not correctly scripted 3D portals when you dont kill all of the portal dudes?

**Comment by ihcTactics** [comment]
Interesting. I wouldn't know since we haven't bothered to go into the portals and kill the dragons.

I'm trying to remember if this interrupt has ever happened to me when I haven't been tailed whipped, but I can't be 100% sure.
