### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Doomwalkerr** [SunwellTracker/issues#120]
Decription: 
3 Issues here

How it works: 

How it should work: 

Kaw the Mammoth Destroyer doesn't drop his Halbard for the remaining party members, Winterfin Oracles often or always do not cast spells, they do not really interact as they should have worked, you can't complete quest ' Taking Wing ' in Borean Tundra, Amber Ledge, it's a part of the chain and somehow you can't complete it 
Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
