### ISSUE TITLE
[Quest] Gerenzo Wrenchwhistle - Gerenzo missing

### ISSUE THREAD

**Issue by LessRight** [SunwellTracker/issues#1200]
Decription: For the quest Gerenzo Wrenchwhistle, the NPC Gerenzo Wrenchwhistle does not appear up near the waterwheel in Stonetalon like he should. Therefore, I cannot kill him and complete the quest.

How it works: No Gerenzo up by the waterwheel.

How it should work: Gerenzo should spawn and be located up by the waterwheel.

Source (you should point out proofs of your report, please give us some source): Sorry, I don't want to try to figure out what his respawn timer is and figure out how to take a video and post it to Youtube long enough to prove that it's not just a respawn issue.

**Comment by LessRight** [comment]
I have since found him. I may have made a mistake.

**Comment by Dootz** [comment]
most likely someone killed him. His respawn time is around 5 minutes.
