### ISSUE TITLE
Main building in Dun Argol (Grizzly Hills) has a bugged elevator that glitches out and sends you through the floor

### ISSUE THREAD

**Issue by vitor210** [SunwellTracker/issues#1202]
**Decription:** 

For the quest "The Iron Thane and his Anvil" I should use my golem vehicle to kill a certain mob (Iron Thane on this case). He's on the bottom floor of the main building in Dun Argol and the only way to reach him is to use either of the 2 side elevators since my golem can't jump from the railing on the entrance floor to the bottom floor where the mob is. THe problem is that every time I use the elevator, when it reaches the bottom floor it glitches out and makes me fall down to a pit below the elevator where I can't get out from besides using hearthstone, as if the elevator despawns when I reach said bottom floor. This is really annoying

**Comment by TSSchoof** [comment]
Already logged: https://github.com/SunwellTracker/issues/issues/1116 

But you can complete it, just jump down when you are not in your golem and then activate it.
