### ISSUE TITLE
[Quest] Kill them with sleep depriviation

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1203]
Decription: pillow objects take too long to spawn (over 5 minutes), and there's only nine of them, making the quest doable alone in 15+ minutes (retail pillow spawn time is 1 minute).

Also, looting pillows doesn't trigger the script to spawn Pillaclencher's Ornate Pillow (should with 10% chance).

How it works: low amount of pillows, long respawn

How it should work: more pillows, faster spawn, and script to create a big one (extra quest item for a give-in)

Source (you should point out proofs of your report, please give us some source): https://db.darkwizard.pl/?object=179828 https://db.darkwizard.pl/?object=179832#summoned-by http://www.wowhead.com/item=18943/dark-iron-pillow#comments:id=913545 http://www.wowhead.com/object=179832/pillaclenchers-ornate-pillow#comments:id=988901(the group doesn't exist on our realm)

**Comment by Dootz** [comment]
will be fixed with next server update
