### ISSUE TITLE
[Warlock] Felhunter's Devour Magic not dispelling enemy buffs

### ISSUE THREAD

**Issue by prymex** [SunwellTracker/issues#1205]
Decription: 
Using Felhunter's Devour Magic does not dispel magic buffs present on an enemy.

How it works: 
Felhunter's Devour Magic doesn't dispel beneficial magic buffs from enemies.

How it should work: 
Felhunter's Devour Magic should dispel beneficial magic buffs from enemies. 

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?spell=48011 -- It's in the description
https://imgur.com/a/tV4Q8 -- screenshots.

**Comment by Azathothh** [comment]
18:01:02> Traatom casts Devour Magic at Cdmp.
18:01:02> Cdmp's Blessing of Might fades from Cdmp.
18:01:02> Cdmp's Blessing of Might is dispelled by Traatom's Devour Magic.

18:02:45> Traatom casts Devour Magic at Cdmp.
18:02:45> Cdmp's Tidal Waves fades from Cdmp.
18:02:45> Cdmp's Tidal Waves is dispelled by Traatom's Devour Magic.

Works fine for me.. 
Not enough proofs (like combat log showing what's happening)
