### ISSUE TITLE
Issue with Besieged! quest 

### ISSUE THREAD

**Issue by Siusaczkarz** [SunwellTracker/issues#1206]
Decription: There's an issue in Shadowmoon Valley, near Shadowmoon Village with Besieged! quest

How it works: There aren't any Infernall Attackers

How it should work: There should fight Infernal Attackers

Source (you should point out proofs of your report, please give us some source): 
![sunwell bug](https://user-images.githubusercontent.com/38226190/38516963-c499c690-3c38-11e8-9c0e-86c58f87a932.PNG) There aren't any fights, as it should be ;/

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/985
