### ISSUE TITLE
Healing and Absorbs Reduction on Arena/BG/Wintergrasp!

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#1207]
Decription: 
Healing/Absorb reduction on PvP instances.

How it works: 
There is no Healing/Absorb reduction on PvP instances.

How it should work: 
It should be 10% Healing and Absorbs reduction on Arena/BG/Wintergrasp.
I mean all Healing, DK percentage HP Healing like Death Strike, Rune Tap, Warrior percentage HP Healing like Second Wind, and all normal castable Heals and Absorbs.

I remember on Old Sunwell was bug only on DK and Warrior Heals has no reduction but naw there is no reducion at all on PvP instances.
Thats why PvP is so long and boring.

Source (you should point out proofs of your report, please give us some source): 
Its hard do find old article. But i think all know what I am talking about.
Discusion or Molten http://forum.warmane.com/showthread.php?t=307204.

**Comment by sonrakus** [comment]
http://wowwiki.wikia.com/wiki/Patch_3.3.2

"All healing abilities (including items such as potions) will be decreased in effectiveness by 10% when in Battlegrounds, Arenas, or Wintergrasp. "

**Comment by BialyADI** [comment]
Bump.

**Comment by Shatterx** [comment]
Feronis bug.
