### ISSUE TITLE
Brittle Revenant respawn time way too slow

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1208]
Decription: Brittle Revenants for Sons of Hodir quest Hot and Cold have an extremely slow respawn time that makes doing that daily a nightmare.

How it works: Brittle Revenant (npc=30160) for quest Hot and Cold (quest=12981) take an extremely long time to respawn, to the point where there is non-stop pvp battles and 4-5 people constantly circling the area hunting down respawns for what is supposed to be and was during retail a quick and painless daily.

How it should work: They should respawn much faster. I'm not sure how much faster but I know its at least 3 times slower than retail right now.

Source (you should point out proofs of your report, please give us some source): I don't have a specific source because it was never an issue during retail so nobody ever spoke about it, but if you google brittle revenants the only things you get are the wowhead page where respawn time is never brought up, and a report on the sunwell.pl forums complaining about the extremely slow respawn time, so obviously it isn't correct.

**Comment by Dootz** [comment]
it should be better today
