### ISSUE TITLE
[JEVELCRAFTING] Icy Prism consume x3 gems for craft

### ISSUE THREAD

**Issue by raddil** [SunwellTracker/issues#1209]
Decription: Icy Prism (http://www.wowhead.com/item=44943/icy-prism) should be crafted with: 
1 x Frozen Orb 
1 x Chalcedony 
1 x Shadow Crystal 
1 x Dark Jade
and we should receive 1xIcy Prism

How it works: 
It use to craft:
1 x Frozen Orb
3 x Chalcedony
3 x Shadow Crystal
3 x Dark Jade

How it should work: 
It should use to craft:
1 x Frozen Orb
1 x Chalcedony
1 x Shadow Crystal
1 x Dark Jade

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=44943/icy-prism (Wowhead definition)
https://i.imgur.com/HHbA0wn.jpg (Actual screenshot from my acount from Angrathar

**Comment by Azathothh** [comment]
Patch 3.3.3 (2010-03-23): Undocumented change
            The number of each gem necessary has been reduced from 3 to 1.
source : http://wowwiki.wikia.com/wiki/Icy_Prism

or comments from wowhead link you've provided:

By Razia (2,591 –  9·32)  on 2010/03/06 (Patch 3.3.2) |   |  
"Seems like it hasn't been mentioned yet, so I'll say it. Next patch (3.3.3), the mats will go from x3 of the gems to x1."

By drakoes (132 – 1) on 2010/03/24 (Patch 3.3.2)
As of 3.3.3 this no longer takes three of each of the gems. it now takes 1 orb and 1 each of Chalcedony, shadow Crystal, and Dark Jade


It will be changed to 1 of each gems needed with Icc content probably.

**Comment by raddil** [comment]
So here is still an issue with defected tooltip :)
