### ISSUE TITLE
Quest  The stagnanat oasis 

### ISSUE THREAD

**Issue by magick123** [SunwellTracker/issues#1210]
Decription: 

How it works:  quest works fine but the reward Experiance does not multiply  

How it should work:  quest give 1025 experiance at 1 times and at my 4 times rate instead of getting 4k experiance i was given the standard rate of 1025 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Checked and it works fine, maybe you didn't notice that you've earned correct exp or you've had .blizzlike enabled.
