### ISSUE TITLE
Voggah Deathgrip's Quests

### ISSUE THREAD

**Issue by Kokaina** [SunwellTracker/issues#1213]
Decription: Mentioned NPC (13817) should offer two quests for horde side: Hero of the Frostwolf (8272) and The Battle for Alterac (7142) afterwards.

How it works: He doesn't offer first quest after player reach 51 lvl (required lvl).

How it should work: Both quests should be obtainable at 51lvl.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=13817#starts

**Comment by Akha72** [comment]
https://github.com/SunwellTracker/issues/issues/469

**Comment by Dootz** [comment]
will be fixed with next server update
