### ISSUE TITLE
[Raid Looting] Containers in dungeons from bosses bound to current people in the dungeon

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1217]
Decription: wrong boss looting policies

How it works: Currently, only people that are in the dungeon at the moment of opening the container are eligible for the loot.

How it should work: only the people that participated in selected encounter and boss bound to the container should be eligible for the loot.

Source (you should point out proofs of your report, please give us some source): currently, the system can be abused and loot can be shared to people that didn't even participate in the encounter if not opened. This can be abused, and Blizzards' looting system disables this abuse, which is the proof that our current system is wrong, per se. Sadly, no other sources can be provided as it's not a problem encountered on retail where GM's could simply transfer loot in these situations, which on our server, sadly, can't happen.

Fixing this problem fixes 2 problem:

1) Loot can't be transfered to people eligible for it
2) Loot can't be transfered to twinks that get in after the boss is killed.

These encounters include Tribunal chest in HoL, Malygos core in EoE, Four Horseman chest in Naxxramas and Saurfang's chest in ICC. (probably more, top of my head).

**Comment by mpuryear** [comment]
After ~10 tickets with gm's after being ineligible for loot from eoe while still getting saved, I'm convinced they think this is how it should work. This is likely not limited to chest's in instances, but likely every boss drop, but people loot the bosses so fast you would likely never know. 

I could provide links to blue posts on how it should work, but after being jerked around by the staff refusing to correct the mistake of their system, I refuse to help them out. 

Don't expect this one to get fixed.

**Comment by eloquence743** [comment]
@mpuryear , please, post the links you've found. It's crucial to build a sustainable proof base in order for this bug to get fixed.

The reason the administration isn't allowing transfer through commands is because of the abuse people could, and will do. The only way to do it is to fix the bug, and having proofs is crucial. 


Thank you, and hope you will be able to post what you've found. :)

**Comment by eloquence743** [comment]
Making a lift to this bug, don't know if it's allowed by the rules, but it's needed with the upcoming raids and the fact that Game Masters doesn't have the right to help out in this complex situations.

**Comment by Riztazz** [comment]
This has been fixed at some point in 2019, just never closed properly.
