### ISSUE TITLE
Achievement, "Oh Novos!"

### ISSUE THREAD

**Issue by Panikx** [SunwellTracker/issues#1218]
Decription: After talking to GM "Tide" , i was told to open a ticket for the Achievement ["Oh Novos!"] in 5 player instance [Drak Tharon Keep] on heroic difficulty. The achievement isn´t working as intended.

How it works: You kill all undead minions without them leaving the stairs / touching the floor on the bossfight of Novos the Summoner. "Defeat Novos the Summoner in Drak Tharon Keep on Heroic Difficulty without allowing any undead minions to reach the floor." - You don´t get the achievement.

How it should work: After killing all undead minions properly and starting the boss fight, you should get the achievement when killing the boss.

Source (you should point out proofs of your report, please give us some source): GM Tide has reproduced the problem and wanted me to open a Bugtracker report for it. I´ve done the proper Achievement way 5 times and it didn´t work for me , as for several other players.
Thanks

**Comment by Dootz** [comment]
Currently achivement fails when you stun or root zombies.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/631
