### ISSUE TITLE
Quest: The Admiral Revealed

### ISSUE THREAD

**Issue by racuh** [SunwellTracker/issues#1219]
Decription: You kill a mob who turns into malganis alongside the fight

How it works: He hits incredibly hard, and after turning into Mal'ganis he hits for ~16k+ with melee swings

How it should work:  He shouldnt hit for ~16k+ with melee swings

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Malganis seems to hit for too much, however, Grand Admiral Westwind looks fine. Remember that this quest is suggested for a group of 5.

**Comment by Dootz** [comment]
will be fixed with next server update
