### ISSUE TITLE
You Don't Have An Eternity (10 player) achivement not triggering for all raid members.

### ISSUE THREAD

**Issue by jessemon** [SunwellTracker/issues#1220]
After killing Malygos 10man, killing him within 6minutes and triggering "You Don't Have An Eternity". The achivement was not triggered for everyone in the raid.
Out of 10 players, only 9 players got it.
Sadly, I was that one guy, I was not dead, nor released, I was alive and well throughout the whole fight.

How it works: "You Don't Have An Eternity (10 player)" achivement does for some reason not triggering or did not trigger for all raid participants.

How it should work: "You Don't Have An Eternity (10 player)" achivement, should trigger for all the raid participants when Malygos is defeated within the time limit.

VOD from the whole fight (timestamped ~5 seconds before the kill); 
https://www.youtube.com/watch?v=rOjxkxkDcLs#t=113m20s
Showing the achivements rolling out, however, I did not get one.

IGN: Jessex (I am the warrior tank)

**Comment by Gracku** [comment]
This happened to our raid as well.

**Comment by Voxarimus** [comment]
https://www.youtube.com/watch?v=-biMy76vOFc&feature=youtu.be

**Comment by Voxarimus** [comment]
So 5 of us got it and 5 of us did not. Proof we completed it, this has been bugged for over 2 weeks if you cannot figure out how to fix it, maybe reward those people who earned it with the achievement until u fix it.

**Comment by Dootz** [comment]
Will be fixed with next server update

**Comment by Dootz** [comment]
fixed
