### ISSUE TITLE
Faded Photograph

### ISSUE THREAD

**Issue by beregas** [SunwellTracker/issues#1221]
Decription:  item "A Small Pack" received in the quest It's a Secret to Everybody is not giving the Faded Photograph (cosmetic item)

How it should work: 
When earned, the bag should contain the quest items and the photo

Source (you should point out proofs of your report, please give us some source): 

http://db.darkwizard.pl/?item=11107

**Comment by MrTide** [comment]
Hello test it out myself 
No faded photograph

**Comment by Dootz** [comment]
will be fixed with next server update. If you want to have this item, please write an in-game ticket and we will add it. Mentioning my name might help.
