### ISSUE TITLE
JC recipe: Mystical Skyfire Diamond

### ISSUE THREAD

**Issue by Socloseagain** [SunwellTracker/issues#1222]
Decription: +Design: Mystical Skyfire Diamond does not seem to drop 

How it works: +Design: Mystical Skyfire Diamond does not seem to drop 

How it should work: +Design: Mystical Skyfire Diamond should drop

Source (you should point out proofs of your report, please give us some source): +I have farmed the trash in Shattered Halls instance both normal and heroic and it just won't drop
+If it's possilbe, please check if literally ANYONE else on the server has the recipe, becouse it seems bugged. If somebody has it please tell me who it is to contact them. :(

**Comment by Dootz** [comment]
The chance to get a recipe (for any profession) from these trash mobs is really small (wowhead says around 0%, but it's higher here). And if you consider that you can get only one recipe from a group of recipes that they drop, chance to get the particular recipe is even smaller. 

But to confirm that everything is working as intended:
- while you were farming mobs have you collected any other recipe (e.g. for blacksmithing)?

**Comment by Socloseagain** [comment]
Yea I was getting a few other recipes from BS, tailor, even some other JC. But it would really put my mind at ease if I knew the recipe is dropping for sure (regardless how hard it is), hence why I was asking if anyone else on this server has it? Please if you could check that it would be amazing!! Thanks! :)

**Comment by Socloseagain** [comment]
Okaaay I want to add more info into this issue. BS recipes seem to drop like 80-85% of the time compared to LW, tailor and JC ones. And I'm farming like crazy with those results, it's not just a few runs.

**Comment by Nadiirr** [comment]
![screenshot_82](https://user-images.githubusercontent.com/36300104/38767780-a969e9ba-3f9c-11e8-8ef1-92ffc536524d.png)

This can be closed @Dootz
