### ISSUE TITLE
Shutting Down manaforge B'naar - Alliance

### ISSUE THREAD

**Issue by xiaotofu** [SunwellTracker/issues#1223]
Decription: Quest: Shutting Down Manaforge B'naar from Anchorite Karja in Area 52

How it works: The quest objectives are marked as complete and it is marked as complete in the quest log but the questgiver is still grey and will not accept.

How it should work: The quest should be able to be turned in

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/pcRor

**Comment by Nadiirr** [comment]
Quest showed as "active" when I .lookup quest on him. 
Watched him try it again and still only "active" when it showed as complete for him.

**Comment by Dootz** [comment]
will be fixed with next server update. If you can't turn in quest right away, please abandon it and try to complete it.

**Comment by TheRealYasri** [comment]
This quest is still broken for me, Horde side.
