### ISSUE TITLE
[Q] The Bloodsail Buccaneers

### ISSUE THREAD

**Issue by hairychestfan** [SunwellTracker/issues#1226]
Decription: 
Lootable object respawn time is TOO LONG

How it works: 
Respawn time of objects is too long and people cant complete quest unless they got a couple of hours to camp the spawn point

How it should work: 
Respawn time should be shorter

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=3920/bloodsail-charts
http://www.wowhead.com/object=2086/bloodsail-charts
http://www.wowhead.com/object=2087/bloodsail-orders

**Comment by Dootz** [comment]
will be fixed with next server update
