### ISSUE TITLE
3 mining nodes spawned in one rock

### ISSUE THREAD

**Issue by Icyffire12** [SunwellTracker/issues#1228]
Decription: A gold, silver and iron rock spawned in one node. 

How it works:  Move your mouse around you can see the other rocks pop up. With the option to mine them. The silver is gone I mined it while training mining. 

How it should work:  Not all in the same node. 

Source (you should point out proofs of your report, please give us some source): The coordinates in stranglethorn vale are 30.5 7.6. 

https://imgur.com/a/vlanA   iron

https://imgur.com/a/7NGHC  gold

**Comment by Dootz** [comment]
will be fixed with next server update
