### ISSUE TITLE
Battle of the Crimson Watch broken

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1229]
Decription: Quest Battle of the Crimson Watch http://db.darkwizard.pl/?quest=10781 is not working even close to how it is supposed to.

How it works: After you accept the quest all the elite waves all spawn at once and charge at you no matter where you stand.

How it should work: The elite mobs are supposed to come one wave at a time, and they are not supposed to agro you unless you are in close range. It's not necessary to put the effort into fully scripting it, just stop it from autokilling anyone who starts the quest.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=10781/battle-of-the-crimson-watch#comments

**Comment by Dootz** [comment]
event reset was corrected, that might help.

**Comment by Dootz** [comment]
will be fixed with next server update
