### ISSUE TITLE
Problem z systemem RAF oraz grantowaniem poziomów.

### ISSUE THREAD

**Issue by anakondaqt** [SunwellTracker/issues#123]
Decription:  Występuje problem z systemem RAF, mianowicie z ilością otrzymywanego doświadczenia.
Nasze konta (moje "anakondaqt" oraz kolegi "kipkolm2") zostały połączone systemem RAF za pomocą linku rekrutacyjnego, i nazwa konta kolegi wyświetla się w moim panelu gracza, więc wszystko wydaje się być przeprowadzone prawidłowo.

How it works:  Dziala możliwość "summon a friend", natomiast ilość zdobywanego doświadczenia nie zgadza się z naszymi obliczeniami. Nie działa również możliwość grantowania poziomów.
![wowscrnshot_020118_192947](https://user-images.githubusercontent.com/36050066/35696777-a664b5a2-0788-11e8-95f7-4829c61019e4.jpg)

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
