### ISSUE TITLE
[Quest][Enhancement] Post-partum Aggression

### ISSUE THREAD

**Issue by TSSchoof** [SunwellTracker/issues#1230]
**Decription:** Kill Broodmother Slivina and return to Dorian Drakestalker at Dorian's Outpost.  
The quest works perfectly, it's only missing a small bit of dialogue after the quest is done.

**How it works:** You complete the quest and upon completing the quest it says: "Well, I had a whole speech prepared, but the old man himself has some words he wants to say to you. "

Hemet Nesingwary appears and nothing else happens. 

**How it should work:** Hemet Nesingwary should appear and have the following dialogue:

> [11:35]Hemet Nesingwary says: What a fight you missed, Dorian! It was one for the ages!
> [11:41]Hemet Nesingwary says: There we were, riding into battle at full speed on the back of Stampy...
> [11:47]Hemet Nesingwary says: Everything was shaking all over the place. I could hardly steady my gun.
> [11:52]Hemet Nesingwary says: And then we saw her, the fearsome beast!
> [11:58]Hemet Nesingwary says: It took all of <name>'s skill to maintain control of Stampy.
> [12:04]Hemet Nesingwary says: The battle was a haze of blood, lead, and sweat. The broodmother's attacks came faster and faster!
> [12:12]Hemet Nesingwary says: But, in the end, <name> and I prevailed through our wits and teamwork. And now we have this glorious trophy as a memento of our victory.
> [12:18]Hemet Nesingwary says: Do I detect a bit of jealousy, Dorian?
> [12:23]Dorian Drakestalker says: Well, I don't know. I was here tending the fire and discussing the drawbacks of cogs with Zootfizzle. That's pretty epic, too, in its own way.

**Source (you should point out proofs of your report, please give us some source):** http://www.wowhead.com/quest=12614/post-partum-aggression#comments
http://wowwiki.wikia.com/wiki/Quest:Post-partum_Aggression

**Comment by Dootz** [comment]
will be fixed with next server update
