### ISSUE TITLE
Calendar events are empty

### ISSUE THREAD

**Issue by Tonev** [SunwellTracker/issues#1231]
Decription: 
The calendar events, created before the server restart today, are empty now. The problem appeared after today's restart, the one to fix arena spectator issues.

How it works: 
When you open an old event, you don't see anything but the title and description (screenshot uploaded). 

![wowscrnshot_041318_093746](https://user-images.githubusercontent.com/20608253/38720357-a56bca02-3efe-11e8-9592-d11344d4b233.jpg)

How it should work: 
You should be able to see the status of all events.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Calendar

**Comment by Riztazz** [comment]
It was used to attack our server and i had to wipe entire calendar invite database, im so sorry for the inconvenience, but there was no other way to go about it.
