### ISSUE TITLE
Death Knight starting zone quest: An End to All Things... - Quest item causes game to crash

### ISSUE THREAD

**Issue by kevinmd88** [SunwellTracker/issues#1233]
Description: 
One of the quests in the Death Knight starting zone, [[An End to All Things...]](https://db.darkwizard.pl/?quest=12779) causes the game client to lock up and crash to the desktop when you click on the quest item to summon the drake.

How it works: 
Talk to the Lich King at Death's Breach, accept the quest, and click on the quest item, [[Horn of the Frostbrood]](https://db.darkwizard.pl/?item=39700). The game client immediately locks up, and Windows reports there is a problem and it needs to close.

How it should work: 
...It shouldn't crash lol

Source (you should point out proofs of your report, please give us some source):
I don't know what I could attach as documentation for this issue, so please let me know what I can provide. I can tell you my mate is right next to me and experienced the same thing, though it worked the second time she tried. It's happened to me at least 6 times currently.

**Comment by kevinmd88** [comment]
(QUICK UPDATE)
Apparently, somehow this quest works if you walk away from the Lich King down to the ground below and use the quest item there. The game client did still lock up for about 8 seconds, but then it resumed and I was on the drake. Strangely, got PvP flagged in the process...

**Comment by Azathothh** [comment]
Works fine for me, must be some client issue.
