### ISSUE TITLE
[Diminishing Returns] Spell Reflect

### ISSUE THREAD

**Issue by Patrulek** [SunwellTracker/issues#124]
Decription: 
CC odbite reflectem nie posiada dr

How it works: 
CC odbite reflectem nie posiada dr. Przykład:
1. Wrogi druid castuje cyklon - 6s
2. My castujemy cyklon na warriora i wrzuca reflecta - 6s (powinniśmy dostać na 3s)

How it should work: 
http://wowwiki.wikia.com/wiki/Diminishing_returns

"When a spell with diminishing returns is used against a target in PvP, the first effect has full duration. The effect then diminishes by 50%, then 75%, then the target becomes immune. Spells must be used on the same target within 15 seconds of the *end* of the duration in order to be diminished."

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by lukaasm** [comment]
duplicate #1240 & in progress
