### ISSUE TITLE
[Spell] [Warrior] Reflected CC doesn't trigger DR

### ISSUE THREAD

**Issue by exzetron** [SunwellTracker/issues#1240]
Decription: 
DR on reflected clone doesn't work.

How it works: First reflected clone goes on the casting druid, full duration. Next reflect clone doesnt DR with the one befor and is also full.

How it should work: 
If a cyclone get reflected there should be a full cyclone on the casting druid and a DR timer will start counting down.
If another reflect clone goes on the same druid it should be a DR clone (half) and the DR counter resets to full. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It does apply to other cc as well.

**Comment by Notmelody** [comment]
Bump, still bugged.
