### ISSUE TITLE
Autoattacking trough pillar los on all arenas

### ISSUE THREAD

**Issue by Danieloses** [SunwellTracker/issues#1241]
Decription:  ^ Title

How it works:  ^ Title

How it should work:  U shouldn't be able to attack trough los rofl.

Source (you should point out proofs of your report, please give us some source):

**Comment by prymex** [comment]
Possibly the case anywhere in the world, not just arenas: https://im5.ezgif.com/tmp/ezgif-5-1a24a072e6.gif

**Comment by Akha72** [comment]
I can partially confirm - successfully managed to attack mobs while los-ing their casts.

**Comment by Akha72** [comment]
Particularly annoying with pets attacking you through walls so you cannot target them or players meleeing you from below the floor.

**Comment by Lupe4js** [comment]
Hello, I was doing some tests on Frosthold skirmish arenas and here is my report :
You can melee hit through pillar with your AA (but can not use abilities) exactly as you can on the world.

In full honesty, this was the mechanic back on retail at the time.
PvP private servers changed it (mostly known Arena-tournament) so melee AA could not go through walls/pillars.

I think it is a good change that should be implemented, at least in Arena.

**Comment by Aridam** [comment]
That mechanic was indeed present back on Retail at the time.

It should be left as-is, _unless_ there's something about it which makes it behave not quite as Blizz-like, such as being able to hit through pillars from one side to the complete opposite (you probably know what place I'm talking about that actually has that bug).
