### ISSUE TITLE
kołczan na plecach

### ISSUE THREAD

**Issue by 0Web0** [SunwellTracker/issues#1243]
Decription: 
Witam ostatnio na mojej postaci Arystoteles na realmie Feronis pojawił się kołczan ze strzałami. Jestem orkiem szamanem więc nie rozumiem dla czego się to pojawiło.

How it works: 
na mojej postaci widzę kołczan na plecach

How it should work: 
Jestem szamanem, to nie powinno się pokazywać

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_041618_163024](https://user-images.githubusercontent.com/38432268/38815842-1e547b7e-4195-11e8-9433-db97ea5bf080.jpg)

**Comment by Dootz** [comment]
Witaj. Po przelogowaniu i usunięciu cache dalej jest widoczny?

**Comment by 0Web0** [comment]
Tak, usunołem cache i nic się nie zmieniło
