### ISSUE TITLE
The quest for Voidwalker

### ISSUE THREAD

**Issue by Falphia** [SunwellTracker/issues#1246]
Decription: 
Hey,

I have a warlock lvl 26 and I can not get the quest for Voidwalker. I went to see a trainer in 3 different cities. There is a gray exclamation point. I can not take the quest and I do not have it in my quest inventory. Help me please !

Bonjour,

J'ai un warlock lvl 26 et je n'arrive pas à avoir la question pour Voidwalker. J'ai été voir dans 3 différentes villes et il y a toujours un point d'exclamation gris et je ne peux pas prendre de quest. Je ne l'ai pas non plus dans mon inventaire de quest. Aidez moi svp !

**Comment by Dootz** [comment]
Hi, in which faction you play? Horde/Alliance? To get Voidwalker you need to go through the chain of quests. You can find them here (http://wowwiki.wikia.com/wiki/Warlock_quests) under  "Summoning of the Voidwalker". 

So if you're Horde you should go to http://www.wowhead.com/npc=5724/ageron-kargal
And for Alliance: http://www.wowhead.com/npc=6120/lago-blackwrench

**Comment by MrTide** [comment]
Hello make a ticket ingame we will help you out :) you can ask for me
