### ISSUE TITLE
New character restricted to answer GM

### ISSUE THREAD

**Issue by Zonzei** [SunwellTracker/issues#1247]
Decription: 

4h timer before whispering is fine in most cases but you should absolutely be able to whisper back to GM when one starts to chat with you about your ticket.

**Comment by MrTide** [comment]
Hello we usually check characters lvl and invite them to the party to talk
but sometimes we forget about it so its better if you mention it in your ticket

**Comment by Zonzei** [comment]
Wouldn't it still be easier to just fix the system once than make all GMs actively check character levels for every ticket? 
If fixing it is not feasible maybe remind GMs that getting DK to 60 takes like an hour.
Also never even thought I wouldn't be able to reply to GM so didn't even think to mention about fresh character (however I did mention that I was still at "starting zone"). :man_shrugging:

**Comment by MrTide** [comment]
You are right but i believe they have more important things to fix 
We will make sure to check lvls everytime :)
