### ISSUE TITLE
[Quest] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by GhostFinn** [SunwellTracker/issues#1248]
Decription: 
This is an escort mission with Homing Robot OOX-22/FE, it works all ok up until the NPC reaches the main road of Feralas where the quest is meant to get completed.

How it works/Steps to reproduce: 
We can escort the NPC out of the cave up to the main road but rather than having the objective completed, Homing Robot OOX-22/FE will carry on walking on the road on a walking pace.

How it should work: 
It might actually complete if you escort to it's final destination, wherever that is but the quest is meant to complete when the NPC reaches the main road. When the NPC reaches the road it will interact with the player saying: "Flight systems online! CLUCK! Engaging rockets for transport to Booty Bay!" it'll then use a rocket and fly away completing the objective

Source: 
https://www.youtube.com/watch?v=pnqhH5Ez2lM
https://www.youtube.com/watch?v=U23z47OVL80

**Comment by Dootz** [comment]
Will be fixed with next server update
