### ISSUE TITLE
[Quest][Ally][Hillsbrad Foothills] Assassin's Contract

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1252]
Decription: 
http://sunwell-community.com/index.php?/topic/1953-questallyhillsbrad-foothills-assassins-contract/
Tried to look for it several days. Looked around in scripts in sunwellcore and not found it. Did not look around sunwellcore DB.  In the end need to report it.
How it works: 
Its probably not implemented. If it is sorry for report.

How it should work: 
There should be condition for event to start. Like quest completion or time based start(like SV pvp arena chest spawn).

Source (you should point out proofs of your report, please give us some source): 
1st is TrinityCore problem + some kind of script so it would be nice to check if its implemented that way?  : https://github.com/TrinityCore/TrinityCore/issues/14880
2nd is is some other BT Issue with comments how it should look that was gathered by other ppl
https://vanilla-twinhead.twinstar.cz/?issue=5124

**Comment by Dootz** [comment]
Will be fixed with next server update. NPC will spawn from time to time (5-10 minutes)
