### ISSUE TITLE
[QUEST] The Lost Supplies - drop rate

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1253]
Decription: 
Drop rate for https://db.darkwizard.pl/?item=6172 is 0.02 ( at least according to your wiki). There are 4 spawns for like 5 min respawn. As we all know no one care in wotlk content about old vanillia stuff.

How it works: 
Well did loot around 40 but no luck. I'm not masochist. I'm a feminist. https://www.youtube.com/watch?v=0IW5x5w4Gco

How it should work: 
I cant care about 100% look rate for me 20 is fine 2. I just want do it 1 time. According to other sources it should be repetable quest, can carry 1 item at a time and award 25 rep to sw. 

Source (you should point out proofs of your report, please give us some source): 
http://web.archive.org/web/20060722044121/http://wow.allakhazam.com/db/quest.html?wquest=1423

**Comment by Dootz** [comment]
I'll increase it slightly so that it can be obtained after some time.

**Comment by Dootz** [comment]
Will be fixed with next server update
