### ISSUE TITLE
[Warlock] Conflagrate 

### ISSUE THREAD

**Issue by Larax323** [SunwellTracker/issues#1254]
Decription: The Warlock Conflagrate spell sometimes cannot chain properly with the Immolate/Shadowflame, although the target does have them on and the ability is off cooldown. There is a brief moment in which it is as if the game does not process the fact that the requirement for the casting of the spell is met and does not allow the Warlock to cast the spell, which is not only a big dps loss in end-game raiding to have an unintended additional Global Cooldown in your rotation, but also does not occur every time with the same delay, not allowing the player to get used to casting and learn his rotation to the perfection, which is required in raids. Problem is that it sometimes triggers pretty fast, and other times it takes almost a second to register the fact the spell's cast requirements have been met and it should be able to be cast, which basically means that when your fingers click the spell, knowing it SHOULD be able to be cast, sometimes it will not be cast but you wont know this until a few seconds later, when you notice Backdraft haste missing from your other spells, at which point you have already lost a couple seconds of not having important damage being dealt, then you cast it again, trigger global cd, and then go back to casting, resulting in 5-6 seconds of dealing sub-optimal damage. The bug is crippling my beloved class and cannot be allowed to keep plaguing us in such an impactful way.  

How it works: Conflagrate stays gray and cannot be cast on targets that have Immolate/Shadowflame debuffs for 0.1-1.0 seconds after the application of said debuffs, tricking the player into thinking the spell was cast when he pressed the button, when in reality it wasn't most of the time. It is DEFFINITELY a bug and was not intended to work as is. The Warlock combo flows perfectly and everything fits in its rightful place. The spell is locked ONLY under the requirement that either Immolate or Shadowflame debuff is present on the target and there is no sense nor indication that the spell was meant to not be cast-able immediately after the requirement for it was met.

How it should work: Conflagrate should be able to be cast immediately after Immolate/Shadowflame, most commonly in the case of the first, which links a casting spell (which has its global cd run during the cast time) link with an instant one resulting in only a single GCD that needs to be waited, giving the Warlock the ability to move during that second and reposition. It is also the only burst damage the Warlock has in cases where a non-boss add needs to be focused and killed or slowed ASAP and forms an integral, vital part of the rotation of the class, which if out of order messes up the entire combo of spells, which is unacceptable for bosses in which said spells need to be cast 30-40 times each before the kill. 

Source (you should point out proofs of your report, please give us some source): http://db.darkwizard.pl/?spell=17962
I play the class for more than 10 years and know how casting should flow. This bug does not belong in the rotation and throws it way off. Much less maintained servers had it right and on a realm as well-built as Angrathar major class-issues like this should not be allowed to cripple such a big percentage of the player-base. It sounds small but it results in an additional, unintended GCD, which is a big deal in high-end raiding, where milliseconds are the difference.

**Comment by Akha72** [comment]
Delay to Immolate - Conflagrate combo was added back in vanilla WoW.

**Comment by Larax323** [comment]
This would imply that the delay was intended, which would in turn imply the same delay every time. Instead, the spell seems to decide on its own when it can be casted and this prevents the player from having certainty about his rotation being cast or not. And here I'm afraid i need to repeat myself, i do not see the indication that this was intended anywhere in the spell description or in common sense as it is the only Wlock in-movement-burst combo. Other classes have powerful instant spells, we do not but we have learned to be ok with a quick cast one (Immolate) and an instant ( Conflagrate) as a combo, allowing us to still contribute in low health but important to die adds without casting like 3 seconds for a single spell hit.

**Comment by Akha72** [comment]
You claim to play this class for more than 10 years and yet think that introducing delay to Immolate - Conflagrate combo was an unintended change? If the time between Immolate being applied and Conflagrate being usable is not the same on every cast then I believe it is related to lag, but regarding that we'll need a dev's response.

**Comment by Cwiercpasiec** [comment]
#633 Duplicate and also invalid. Funny how such experienced warlock talks about destro PvE in "high-end raiding, where milliseconds are the difference."

**Comment by Akha72** [comment]
Maybe he meant high-end TBC raiding, but then neither Immolate nor Conflagrate take any part in it.

**Comment by Larax323** [comment]
I am sorry but all you do is cite blizzard servers that also had the same delay and nowhere do i see a reason why there should be one, only smirks about my experience as a warlock on 4 different servers only the last one of which (Sunwell) has had this delay. I have read official server forums these days where people also say there should not be one. You need to understand that Blizz-like does not mean perfection. This is a code frozen in time, taken from a particular point in Blizzard's patches which does not equal it being without flaws. Your comments clearly state that you do not see me as someone who is experienced in the class on a level you are so, please, explain to me WHY there needs to be a delay and do not include in your answer "because it was on official at one point" because I will just ask you why that was. Go down to the logical, reasonable root of the need for such a delay, or the reason why not having it would be unwanted.
https://eu.battle.net/forums/en/wow/topic/2723297471

**Comment by Akha72** [comment]
All you do is talk around to make a change that will buff a specific class. At the time of official WotLK (and the expansions before) one could dispell Warlock's Immolate to prevent the application of Conflagrate for Warlock not to get her/his Backdraft buff or solely for damage mitigation purposes. So now you want to change that mechanic completely because you do not believe this spell is working as intended and was not working as intended on retail. There are video guides from WotLK time specifically saying to cast Spell Lock at the time of applying Immolate in order for Warlock to get her/his combo rolling (like here https://youtu.be/TJQn1OVFCjw?t=8m4s ). On the other hand your only source is 'I believe, I think, I do not see how it was intended', and based on that you expect devs to make such an impactful change.

**Comment by Azathothh** [comment]
Invalid report.
Missing proofs/sources.

**Comment by lineagedr** [comment]
@Vagoom That's from a private server. 
This is from retail: https://www.youtube.com/watch?v=yq3N1fP3a24&feature=youtu.be&t=194

**Comment by Akha72** [comment]
Shouldn't ppl posting fake info purposely get banned from BT?
