### ISSUE TITLE
[Mage] Mana Sapphire (Mage created on use mana restore item) can not be used while flying on the hoverboard on malygos in p2 (25m)

### ISSUE THREAD

**Issue by gabbat** [SunwellTracker/issues#1255]
Decription: [Mage] Mana Sapphire (Mage created on use mana restore item) can not be used while flying on the hoverboard on malygos in p2 (25m)

How it works: you can not use your mana gem

How it should work: you should be able to use all consumes

**Comment by Azathothh** [comment]
Invalid report.
Missing proofs/sources.

**Comment by gabbat** [comment]
source: enter a hoverboard in the malygos encounter and you can experience it by yourself
