### ISSUE TITLE
Palladin buff tooltip bug

### ISSUE THREAD

**Issue by Maxaoe** [SunwellTracker/issues#1258]
Description: When you take the talent in the retribution tree "Improved blessing of might", the tool-tip in the top right hand corner of your UI doesn't display the correct amount of bonus attack power, it only shows the base amount (without the talent). All other tool-tips work correctly, and you still receive the bonus AP. I just think the bug is a bit misleading is all.

How it works: 

How it should work: should display the full amount of AP once you spec into "improved blessing of might", and not just the base amount.

Source (you should point out proofs of your report, please give us some source): 
![screenshot_33](https://user-images.githubusercontent.com/38483917/38910353-e5b5a718-4296-11e8-839b-20f8e7b0e852.png)
![screenshot_35](https://user-images.githubusercontent.com/38483917/38910361-f0397066-4296-11e8-92d3-b7725e84bf54.png)
![screenshot_34](https://user-images.githubusercontent.com/38483917/38910362-f555f204-4296-11e8-9bd1-6f409a850f4d.png)

**Comment by Akha72** [comment]
Isn't that a blizzlike bug? It was always the same with Demon and Fel Armor in Warlock's case.

**Comment by gabbat** [comment]
blizzlike behaviour. It is the same with any talented buff
