### ISSUE TITLE
[Quests] Kalu'ak dailies reputation gain

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1259]
Decription: they give too much reputation

How it works: 1000 rep per quest for humans

How it should work: only 500 rep for nonhumans, 550 for humans

Source (you should point out proofs of your report, please give us some source):  https://db.darkwizard.pl/?quest=11960 https://db.darkwizard.pl/?quest=11945 https://db.darkwizard.pl/?quest=11472 http://wowwiki.wikia.com/wiki/Kalu%27ak

**Comment by Dootz** [comment]
Will be fixed with next server update
