### ISSUE TITLE
Betrayal quest

### ISSUE THREAD

**Issue by Borthun111** [SunwellTracker/issues#126]
Decription: 
Quest item cant be looted

How it works: 
When u get on top of the Voltarus and start the combat everything works fine. After Drakuru is supposed to die and drop the skull, u cant loot the skull it just says interrupted at the end of cast and leaves u in combat aswell and Drakuru alive with 1hp

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Vlnkaj** [comment]
Completed that Q today, same as one guy who did Q with me. Working good.

**Comment by Semper-Numquam** [comment]
Can confirm. I completed it about an hour ago. Item doesn't give loot but as soon as event ends you can get the skull.

**Comment by Kokaina** [comment]
U have just wait till outro ends in order to loot skull.

**Comment by Kokaina** [comment]
Okey i probably recreated this bug. It happens (i think so) when u defeat Drakuru and send pet to attack him again during outro event. Boss will continue fight which bugs skull loot - to fix!

**Comment by TheRealYasri** [comment]
Had trouble with this one today,

1. You can only get one skull if you do it as a group, the skulls seem to stick around making you think your clicking the wrong one but it wont let you loot.

2.The amount of damage you take I dont see how a class without heals can do it. Was taking fog damage. I put on healing gear as a paladin and healed thru it.

3.When my pet died I had to go grab a new one and send it to attack, It took a long time for the new pet to regain agro, to stop the spell spam the mob was doing to me.

4. Multiple pets can spawn in same place, its possible to deagro the extra but can be hard and the extra damage will kill most people.

Had to use a mp pot and lay on hands.

**Comment by TheBigBallsOfFury** [comment]
Confirmed only 1 person in part can loot. The rest have to repeat the event individually to complete quest.
