### ISSUE TITLE
[Quest] Questioning Reethe

### ISSUE THREAD

**Issue by sardinecookies** [SunwellTracker/issues#1260]
Decription: Quest NPC Ogron is bugged, making the quest incompletable. 

How it works: 
Ogron is starting in the wrong place (he starts next to Reethe). 
Ogron freezes up after he starts talking to Reethe/when the ambush occurs.

How it should work: Ogron's starting location is supposed to be different. Ogron is also supposed to fight against the ambush. 

Source: 
![bug 3](https://user-images.githubusercontent.com/38502499/38942382-374d1afa-4361-11e8-80fe-702c7e1e250e.png)
![bug 1](https://user-images.githubusercontent.com/38502499/38941988-43ce00d8-4360-11e8-90bb-8ce6f07b8eab.png)
![bug 2](https://user-images.githubusercontent.com/38502499/38941990-45979712-4360-11e8-9b47-9573688bba4f.png)

https://www.youtube.com/watch?v=G89A9ITuTfs

**Comment by Dootz** [comment]
Will be fixed with next server update
