### ISSUE TITLE
[Quest] Deathblow to the Legion

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1262]
Decription: 
NPC not found to begin event.
Suspect the event is not resetting, and only works once after server restart.

How it works: 
NPC not found to begin event.

How it should work: 
•	Speak with Adyen the Lightwarden (coords: 30.7, 17.4), and select "I'm ready, Adyen."

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=10409/deathblow-to-the-legion

**Comment by Dootz** [comment]
Will be fixed with next server update
