### ISSUE TITLE
[Malygos 10] "You Don't Have An Eternity (10 player)" Achievement not working

### ISSUE THREAD

**Issue by UFJ** [SunwellTracker/issues#1263]
Decription: 
The "You Don't Have An Eternity (10 player)" achievement did not proc for everyone in the raid, only a couple of people in the raid got the achievement after killing Malygos 10 in 5:30ish.

How it works: Not everyone in the raid got the speed kill achievement for Malygos 10.

How it should work: Everyone in the raid should have gotten the achievement, not just a few.

Source (you should point out proofs of your report, please give us some source): 
Clip of the end of the fight: https://clips.twitch.tv/JoyousDepressedCougarItsBoshyTime
Total stream:https://www.twitch.tv/videos/251784145  The Malygos 10 fight starts around 5:19~ and ends around 5:25.

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/1220
