### ISSUE TITLE
[Quest Item Bug] Moodle's Stress Ball

### ISSUE THREAD

**Issue by Dudo12** [SunwellTracker/issues#1264]
Decription: My ingame character is an alliance hunter Noxo on Angrathar. I destroyed the Item http://www.wowhead.com/item=38624/moodles-stress-ball from my inventory while I was on the quest http://www.wowhead.com/quest=12581/a-heros-burden, which is a quest offered by the npc summoned from the ball, then I dropped the quest as well. The NPC http://www.wowhead.com/npc=28027/high-oracle-soo-say is supposed to give you a new ball. It is neither in my bank or in my inventory. I am still friendly with "The Oracles" but unable to obtain the ball to carry on questing with them.

How it works:  Item is missing from inventory and bank, speaks to High Oracle Soo-say , just a chat box without any interactive clicks to obtain another "Moodle's Stress Ball"

How it should work:  Item is missing from inventory and bank, speaks to High Oracle Soo-say, Chat box with interactive option to obtain another "Moodle's Stress Ball"

**Comment by Dootz** [comment]
Hi, please open an in-game ticket. GMs will help you.

**Comment by Dootz** [comment]
That probably happend because you were "At War" with Oracles. Please uncheck "At War" checkbox in "Reputation" tab, and he should give you next ball.
