### ISSUE TITLE
Unable to tame Spirit wolfs in Dustwallow Marsh

### ISSUE THREAD

**Issue by bright57** [SunwellTracker/issues#1266]
Decription: 
The Grimtotem Spirit-Shifter's are supposed to have wolf pets around them at all times, not just when they are aggrod and spawn for a few seconds. Also they are supposed to be tamable. 

How it works: 
When you hit them or get aggroed by them the spectral wolf spawns, and then despawns after about 10 or so seconds. Also untamable. https://i.imgur.com/50ZdIAO.jpg

How it should work: 
They are supposed to be sitting next to the mobs, i managed to find a video from retail with how it was back then. https://www.youtube.com/watch?v=eGLEpevco7g

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=eGLEpevco7g
https://i.imgur.com/50ZdIAO.jpg

Pls fix i need spectral wolf pet :)

**Comment by Dootz** [comment]
Grimtotem Spirit Wolf shouldn't be tameable.
TrinityCore/TrinityCore#13223

> , the ability to tame them was removed in a hotfix as of 1/14/2008.

**Comment by Dootz** [comment]
> , the ability to tame them was removed in a hotfix as of 1/14/2008.
