### ISSUE TITLE
[Quest] Stasis Chambers of Bash'ir

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1267]
Decription:
Object/NPC to use quest item missing

How it works: 
Object/NPC to use quest item missing

How it should work: 
https://www.youtube.com/watch?v=YBEdbuzRqUo

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=YBEdbuzRqUo

**Comment by Dootz** [comment]
Will be fixed with next server update
