### ISSUE TITLE
[SPELL] Blink: falling under map

### ISSUE THREAD

**Issue by purplehaze321** [SunwellTracker/issues#127]
Decription: in thousand needles I just blinked through a mountain and fell to death. 
location cirka 29/30

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by gitghost** [comment]
I just add that this is really common in caves of Eastern Kindoms and Kalimdor.
On outland and northend blink never failed me (whenever it was in cave or not).
