### ISSUE TITLE
[General] Possible wrong reaction from mobs

### ISSUE THREAD

**Issue by lmrech** [SunwellTracker/issues#1272]
Decription: When someone cast a spell, like 'Wrath' for instance, in a mob that is near other mobs, the other mobs dont get pulled, only the one who was targeted.

How it works: You cast a ranged spell on a enemy npc, it gets pulled by yout but no the others near them. This happened casting 'Wrath' on a mob near Hogger a few days ago.

How it should work: I think (?) the correct reaction is to all the mobs near him also get pulled when this happens.

Source (you should point out proofs of your report, please give us some source): Issue happened playing a low level druid, near Hogger area which have small groups of enemies.

Edit: No answer after 6 days. Really?

**Comment by sonrakus** [comment]
Finally, somebody reported this. After the elwynn wolf fix, almost no enemy in the entire world is linked, meaning you can do single pulls from a group. Obviously, it should not be like this, pull links are common knowledge.

**Comment by Akha72** [comment]
https://github.com/SunwellTracker/issues/issues/1378
