### ISSUE TITLE
Halls of stone

### ISSUE THREAD

**Issue by Pirattheamazing** [SunwellTracker/issues#1273]
Decription: Doors are closed

How it works: All doors are closed so we cant skip

How it should work: Doors should be open as the bosses are non-linear and can be done in any preferred order.

Source (you should point out proofs of your report, please give us some source): 
Retail and literally every other private server.
https://wow.gamepedia.com/Halls_of_Stone
-Bosses
The order of bosses is non-linear, so the order below doesn't necessarily represent the encounter order.

**Comment by Dootz** [comment]
Will be fixed with next server update
