### ISSUE TITLE
[Talent][Death Knight] Night of the Dead

### ISSUE THREAD

**Issue by Bordiran** [SunwellTracker/issues#1274]
**Decription:** 

Army of the Dead and Ghoul Pet in Unholy Spec for Death Knight should take 90% reduced damage from all AoE (example: Heigan the Unclean Eruptions + Platform AoE Damage) with the talent Night of the Dead in the Unholy Tree.

**How it works:** 

Army of the Dead and Ghoul Pet do not have 90% reduced damage from AoE. They get killed basically instantly from any big AoE mechanics like Heigan Eruption and Sapphiron AoE + Blizzards. This leads to a pretty significant DPS losses on those fights because the Army  Ghouls and the Raise Dead Pet Ghoul are dying within 10 seconds of the start of the fight with AoE and you have to wait 30s to Summon a new Ghoul just to have it die again when it gets hit by another Eruption on Heigan or any other AoE on other fights.

**How it should work:** 

Army of the Dead Ghouls and the Ghoul Pet while you are Unholy DK Spec with talent Night of the Dead should have 90% reduced damage from AoE abilities/mechanics.

**Source (you should point out proofs of your report, please give us some source):** 

https://db.rising-gods.de/?spell=55623
>**Also reduces the damage your pet takes from creature area of effect attacks by 90%.**

If you check that link and look at MODIFIES down below you see it affects Army of the Dead and Raise Dead (Ghoul) so it should affect both Army Ghouls and your Pet Ghoul.
https://i.gyazo.com/d8ba56b0096a7b9a9e9ef263084f0dfc.png

**Comment by Misery321** [comment]
Bump, the damage reduce does not lower the damage being output from Bladestorm. 
Which makes the pet dies instantly vs. a Warrior in PVP
