### ISSUE TITLE
[Zul'gurub -  edge of madness] rotacja bossów

### ISSUE THREAD

**Issue by faggbag** [SunwellTracker/issues#1275]
Decription: Brak rotacji bossów. 

How it works: 
Cały czas jest boss Gri'lek

How it should work: 
Do 16.04 powinenbyl byc gril'ek od 16.04 Wushoolay a od 30.04 Renataki.
Zbieranie matsów do ugaszenia pożaru jest frustrujące a musiałem zrobić to dwukrotnie ponieważ ciągle jest ten sam. Proszę nie każcie mic zekać kolejego ponad miesiąca żeby renataki był w rotacji bo na nim mi zależy

Source (you should point out proofs of your report, please give us some source): 4 tygodnie temu pisałem w tej sprawie ticket, dostałem odpowiedź, że bossy się rotują co 2 tygodnie i w jakiej kolejności, a po 4 tygodniach nadal jest ten sam boss - Gri'lek

**Comment by Dootz** [comment]
Powinno się naprawić po update.

**Comment by faggbag** [comment]
A kiedy będzie update?

**Comment by faggbag** [comment]
a o której godzinie mniej więcej? z góry dzięki za odpowiedź i serdeczne dzięki za zainteresowanie się i naprawę problemu. jestem mega wdzięczny :)

**Comment by Dootz** [comment]
nie jestem w 100% pewny, natomiast zwykle są to godziny poranne. Powinno być to widoczne na stronie gdy zresetuje się licznik czasu online serwera (nad liczbą graczy)

**Comment by faggbag** [comment]
rewelacja, dziękuję pięknie :)

**Comment by faggbag** [comment]
jeszcze ostatnia rzecz, 30.04 powinien pojawić się w takim razie renataki tak? z góry dzięki

**Comment by faggbag** [comment]
p.s. wushoolay już jest.

**Comment by Dootz** [comment]
tak 30.04 po 7 rano powinien być renataki
