### ISSUE TITLE
[EoE Malygos]EoE 10/25 object/container for neck quest item despawning

### ISSUE THREAD

**Issue by Fjara1** [SunwellTracker/issues#1276]
Decription: Heart of Malygos container despawning in EoE

How it works: After killing Malygos in EoE25 the quest item can be looted by only one player from container http://db.darkwizard.pl/?object=194159#contains / http://db.darkwizard.pl/?object=194159 , sometimes by none player. GM said the way it works is, you need to have all people who have quest inside for object to not disappear. However, we tried it today with everyone ressed and stacked inside EoE25, one person looted it, then the container despawned. It already happend twice for my guild denying me and guild mates neck but as far as I know a lot of players encountered this problem.

How it should work: Everyone who killed Malygos should be able to loot the object no matter if they died, no matter if someone is outside while looting, no matter if they were outside when someone looted. The object/container should simply be there able to be looted by anyone who turned in http://db.darkwizard.pl/?quest=13375 . If you perceive it as working properly as it is now then I suggest testing it again in different situations and if that won't change your opinion I suggest letting GMs give the quest item to players. If there is some time limit on how long container can exist, it should be longer.

Source (you should point out proofs of your report, please give us some source): No one captured it on VOD this time so I don't really know how to prove it, since you need chat to observe that only one person got it and then it disappeared and most streamers hide chat. Players report it every week to GMs, honestly I have no idea how it never got on bugtracker.

**Comment by MrTide** [comment]
Hello
Can confirm .. i can't tell if its bugged since blizzard build a weird mechanic for it but still
I believe needs improvements

**Comment by Dootz** [comment]
Will be fixed with next server update
