### ISSUE TITLE
The Dead Rise! Quest clickables not spawning.

### ISSUE THREAD

**Issue by Bulkathas** [SunwellTracker/issues#1277]
Description: The Dead Rise! quest items don't spawn (mounds of dirt).

How it works: 
You go to the graves where the clues should be and nothing is there.

How it should work: 
You go to the corresponding graves and there is a mound you can click on for clues.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11504/the-dead-rise

**Comment by Dootz** [comment]
Will be fixed with next server update
