### ISSUE TITLE
Highland Mixed School

### ISSUE THREAD

**Issue by eloquence743** [SunwellTracker/issues#1278]
Decription: Highland Mixed School spawn is too fast

How it works:  has 3 minute spawn

How it should work: the spawn time should be ~1 hour

Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/item=27388/mr-pinchy#comments:id=28738

**Comment by Dootz** [comment]
unfortunately, there isn't enough source to decide what's correct respawn time. There's only one wowhead comment with the approximate time. I checked few other websites and couldn't find anything.
