### ISSUE TITLE
The Fate of Bloodbane (Quest)

### ISSUE THREAD

**Issue by Myatz** [SunwellTracker/issues#1279]
Decription: 

Orbaz Bloodbane spawns below Icecrown Citadel for the quest "The Fate of Bloodbane".

How it works: 

The non-player character spawn should be at a specific rate, however, after a considerable amount of time this monster did not spawn. (Upwards of 20 minutes)

How it should work: 

Orbaz Bloodbane should be spawning at a set rate, an example of this rate would be 5 minutes after his last death.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/38625875/39097092-a485d9c4-4625-11e8-91d8-5bea23ad00eb.png)
Photo essentially just shows that he isn't currently spawned - not really sure what other source of information that I can provide. It looks like I just got logged in because Lightshot bug splatted the client.

**Comment by Dootz** [comment]
Will be fixed with next server update
