### ISSUE TITLE
Mekgineer Sicco Thermaplugg Resets Constantly

### ISSUE THREAD

**Issue by Sigma6o** [SunwellTracker/issues#128]
Final boss of Gnomeregan, Mekgineer Sicco Thermaplugg, resets over and over. Didn't record, but can confirm he reset at least 4 times while attempting to down him. I'll try and run again and record, will update if I get the chance.

**Comment by Riztazz** [comment]
Will look into it

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
