### ISSUE TITLE
Quest: Re-Cursive

### ISSUE THREAD

**Issue by kevinmd88** [SunwellTracker/issues#1281]
Description: 
Borean Tundra quest, [[Re-Cursive]](https://db.darkwizard.pl/?quest=11712) is giving double credit for each Fizzcrank Mechagnome the quest item is used on.

How it works: 
Kill a Fizzcrank Mechagnome and use the provided quest item on the corpse. Player receives credit for 2 toward their quest.

How it should work: 
Player should receive credit for 1 toward their quest.

**Comment by Dootz** [comment]
Will be fixed with next server update
