### ISSUE TITLE
[Tabard Vendor] - Will not let you retrive [Green Trophy Tabard of the Illidari] / [Purple Trophy Tabard of the Illidari]

### ISSUE THREAD

**Issue by Tahiku** [SunwellTracker/issues#1284]
Decription: 

Upon completing the quest http://www.wowhead.com/quest=10781/battle-of-the-crimson-watch you are rewarded with one of the two tabards (Green Trophy Tabard of the Illidari / Purple Trophy Tabard of the Illidari) - Once you have recieved said tabard, and you wish to change from X to Y, you are supposed to be able to delete the tabard, visit any tabard vendor and the vendor should give you an option to retrive your tabard, or give you the other colored tabard.
How it works: 
If you delete the tabard here, it is deleted and cannot be retrived from any tabard NPC.
How it should work: 
You are supposed to be able to delete the tabard, visit any tabard vendor and the vendor should give you an option to retrive your tabard, or give you the other colored tabard.

Source (you should point out proofs of your report, please give us some source):  Attatched file is the comment field from Wowhead. And here is a link to 
![tabard bug proof](https://user-images.githubusercontent.com/38655313/39121835-22f5b9c8-46f3-11e8-9956-9ce1fc385f61.png)
the comment(s) - http://www.wowhead.com/item=31404/green-trophy-tabard-of-the-illidari#comments - Link to the comments for further proof,

**Comment by Dootz** [comment]
Hi, currently 8 vendors should have this option. I tried in Ironforge and in Dalaran and it works fine. May I ask which vendor didn't have dialog option for you?

**Comment by Tahiku** [comment]
Hey! The Stormwind one

**Comment by Dootz** [comment]
ok, thanks. I'll check it.

**Comment by Dootz** [comment]
Fixed.
