### ISSUE TITLE
Recipe: Elixir of Brute Force [Drop Rate]

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1285]
Decription: 
Item's drop rate from https://db.darkwizard.pl/?item=13481#contained-in-item  is set slightly lower than it should be. It should be 1.7%(2%), not 0.7%.

Source (you should point out proofs of your report, please give us some source): 

http://wow.allakhazam.com/forum.html?forum=69&mid=110747237146411208 - (1.7%)
http://casualwow.blogspot.co.uk/2006_11_01_archive.html - (less than 2%)
http://www.wowwiki.com/Quest:Dadanga_is_Hungry! - (2%)

Drop rate should be either 1.7% or 2%. 2% seems to be its original drop rate, the 1.7% seems to be the info gathered from player reports with Thottbot/Wowhead.
0.7% (it's drop rate here), is the default drop rate for private servers.

**Comment by Dootz** [comment]
Fixed.
