### ISSUE TITLE
Shadow Embrace

### ISSUE THREAD

**Issue by bugabuser** [SunwellTracker/issues#1287]
Decription: 
Shadow embrace is sometimes not being applied.

How it works: 
Currently, if you cast Shadow Bolt and then move out of Line of Sight of the target, and Shadow Bolt does damage while you are out of LoS, it will not apply the debuff. This is important on fights like Sapphiron where you want to shoot a shadow bolt and immediately LoS the bomb.

How it should work: 
All successful Shadow Bolts/Haunts should apply Shadow Embrace.

Source (you should point out proofs of your report, please give us some source): 
Since it's a very vague bug, I can't find any documentation supporting my claim.

**Comment by lulzi** [comment]
First learn how to NOT drop shadow embrace,then do bug reports.
