### ISSUE TITLE
Froststeel Lockboxes

### ISSUE THREAD

**Issue by jealousmuch** [SunwellTracker/issues#1288]
Decription: Hello, opened today 3 Froststeel Lockboxes (unlocked them myself) and the were empty. Also had some Lockboxes in the past that were empty, i doubt its normal that like 75% of them are empty.

How it works: Not sure about how much % are empty on Retail, but i guess some are still empty?

How it should work: See above.

Source (you should point out proofs of your report, please give us some source): Well got no proof of opening, just opened em and poof no loot, also happens when i open some for other ppl in the trade window and they are empty for them aswell.

**Comment by Dootz** [comment]
Hmm.. according to this video ( https://www.youtube.com/watch?v=g2xznxwT-Ek ) they should always drop something.

**Comment by Dootz** [comment]
confirmed, 2 out of 10 were empty for me.

**Comment by Dootz** [comment]
Should be fine now.
