### ISSUE TITLE
[10 man] Malygos bug

### ISSUE THREAD

**Issue by djjurg1** [SunwellTracker/issues#1289]
Decription: Hello, we just did Malygos 10man on a speedrun for the achivement. Two of our raiders got the achievement, but the rest of us did not. The fight According to DBM took 5 mins & 57 seconds & by the fact that two of our raiders (Keggyan & Kamekue) got the achievement, there must be some kind of bug, prohibiting the rest of us getting it. 
The raid ID is: 23703 & a link to the VOD: https://www.twitch.tv/videos/253734249

How it works: Everyone did not get the achievement.

How it should work: Everyone should get the achievement.

Source (you should point out proofs of your report, please give us some source): https://www.twitch.tv/videos/253734249

**Comment by gabbat** [comment]
https://github.com/SunwellTracker/issues/issues/1220
