### ISSUE TITLE
[Quest - Howling Fjord] Gambling Debt

### ISSUE THREAD

**Issue by n4xu5** [SunwellTracker/issues#129]
Decription: 
The Quest Gambling Debt in Howling Fjord. Interaction with "Silvermoon" Harry

How it works: 
You go to Silvermoon Harry, ask him about the debt and he gets aggressive. Then you just kill him.

How it should work: 
After you beat him he should Surrender and give you his debt.

Source (you should point out proofs of your report, please give us some source): 
http://de.wowhead.com/npc=24539/silbermond-harry#english-comments

**Comment by Bel-WOW** [comment]
The quest is doable. Your goal is not to kill NPC, but to damage him until his health drops to certain amount after which you will be able to talk to him. So take off your weapon, start hitting him until his health drops to around 10%, wait a little and talk to him.


![wowscrnshot_020418_212006](https://user-images.githubusercontent.com/36129798/35781977-808da544-09f1-11e8-8ca8-8852c1a2d263.jpg)

**Comment by shadovvs** [comment]
Decription:
The Quest Gambling Debt (ID: 11464) in Howling Fjord is still buggy.

How it works:
1) "Silvermoon" Harry can be killed.
2) If you keep him at low health for some time, he will give you "Silvermoon" Harry's Debt, but as soon as he gives you the quest item he disappears and you have to wait 10-15min for him to appear again. 

How it should work:
1) You shouldn't be able to kill "Silvermoon" Harry. At 2036 hp he should become friendly and no longer attackable. (YouTube source) 
2) He should not disappear after giving you "Silvermoon" Harry's Debt.

Source (you should point out proofs of your report, please give us some source):
[https://www.youtube.com/watch?v=pYKZRDAQsiY](https://www.youtube.com/watch?v=pYKZRDAQsiY) - you can see "Silvermoon" Harry hp at 0:14
[https://www.youtube.com/watch?v=sz72ncjKNdc](https://www.youtube.com/watch?v=sz72ncjKNdc)
[http://www.wowhead.com/quest=11464/gambling-debt](http://www.wowhead.com/quest=11464/gambling-debt)
