### ISSUE TITLE
Blast the Gateway

### ISSUE THREAD

**Issue by ivanlink** [SunwellTracker/issues#1293]
Decription:  She gives you the item called Sizzling Embers, right click it to summon the quest pet. Then go kill the Fel Sparks in the surrounding area and as you do, the quest pet will continue to grow larger. 

Eventually the pet will turn into am Unstable Fel Spark which is the same color as the Fel Sparks. When you reach this point, go and stand in the gateway new Magistrix Seyla and the pet will slowly move to the gateway and blow up which will complete the quest

How it works:  The gateway should get destroyed and you should get the quest completed.

How it should work:  The Unstable Fel Spark doestn do anything, and you can't get the quest completed

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/geWRmJJ
https://imgur.com/bZdfcG4
As you can see the Unstable Living Flare doesn't do anything.

**Comment by Dootz** [comment]
Fixed.
