### ISSUE TITLE
Stormchops from coocking do too low damage

### ISSUE THREAD

**Issue by Motaru1234** [SunwellTracker/issues#1294]
Decription: After eating stormchops you get a buff that zaps nearby enemies. 
The damage it does is below 30. This it to low.

How it works: 

How it should work: The damage should be 660 to 670 acourding to wowhead.
http://www.wowhead.com/spell=43731/lightning-zap
Recipe: https://db.darkwizard.pl/?item=33871#teaches
https://db.darkwizard.pl/?spell=43730

Please check this
Many thanks in advance

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
No, it's not too low.

(http://www.wowhead.com/spell=43730/electrified#comments)

3.3.0
This also randomly zaps nearby mobs so not recommended if you're doing a stealth run as I found out :)

I doubt this scales with level but at 80 the effect caused about 30 damage to level 60 elite mobs.


(http://www.wowhead.com/item=33866/stormchops#comments)

2.3.0
does 19-31 damage with an average of 24

**Comment by Motaru1234** [comment]
Hello,

Here you can clearly see a 600 damage zap and also the low ones 
https://youtu.be/sRYnEsJ23WU?t=2m11s

**Comment by Akha72** [comment]
Yeah, that's precisely what posts in wowhead comment section describe. 30 dmg to regular mobs and 600 versus critters.

**Comment by Bel-WOW** [comment]
http://db.darkwizard.pl/?spell=43730

2 effects with different dmg values, check yourself.
