### ISSUE TITLE
[QUEST] Vahlarriel's Search - NPC incorrect faction flags

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1296]
Decription: 
https://db.darkwizard.pl/?quest=1438 
NPC: https://db.darkwizard.pl/?npc=5644 . 
 Burning Blade NPCs around her should not be hostile towards her. They keep killing her. Also not sure but worth checking for horde if flags are correct -> This NPC should not be friendly to Horde, but hostile instead. She should not attack Horde players when going near her though.

How it works: 
After spawn Npc's around her start attacking her and she die.
How it should work: 
She should just sit there doing nothing, npc should ignore her(but change flag on escort quest tho https://db.darkwizard.pl/?quest=1440).

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=OlnnPZbg3T0&t=163m19s

**Comment by Dootz** [comment]
It looks like issue with flag reset after escort quest. https://db.darkwizard.pl/?quest=1440 But i wasn't able to recreate it.

**Comment by Dootz** [comment]
Fixed.
