### ISSUE TITLE
[NPC]  Bloodmyst Isle NPCs

### ISSUE THREAD

**Issue by LookinGood** [SunwellTracker/issues#1297]
Decription: 
These NPC don't use their spells:
http://www.wowhead.com/npc=17610 -
http://www.wowhead.com/npc=17607 -
http://www.wowhead.com/npc=17609 - 
http://www.wowhead.com/npc=17604 - 
http://www.wowhead.com/npc=17715 -
http://www.wowhead.com/npc=17358 -
http://www.wowhead.com/npc=22060 -
http://www.wowhead.com/npc=17683 -
http://www.wowhead.com/npc=17661-
http://www.wowhead.com/npc=17527-
http://www.wowhead.com/npc=17494 -
http://www.wowhead.com/npc=17342 -
http://www.wowhead.com/npc=17339 -
http://www.wowhead.com/npc=17330 - 
http://www.wowhead.com/npc=17328 - 
http://www.wowhead.com/npc=17496 - 
http://www.wowhead.com/npc=17523 -
http://www.wowhead.com/npc=17522 -
http://www.wowhead.com/npc=17336 -
http://www.wowhead.com/npc=17334 -
http://www.wowhead.com/npc=17352 - 
http://www.wowhead.com/npc=17588 -
How it works: 

How it should work: 
They are should use all spells.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Fixed.
