### ISSUE TITLE
Zul'Gurub - Boss

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#13]
W raidzie Zul'Gurub a dokladniej Edge of Madness nie ma obiektu (braziera) ktory za uzyciem Gurubashi Mojo Madness powinien spawnowac jednego z 4 bossow:
Gri'lek (https://db.darkwizard.pl/?npc=15082)
Renataki (https://db.darkwizard.pl/?npc=15084)
Wushoolay (https://db.darkwizard.pl/?npc=15085)
Hazza'rah (https://db.darkwizard.pl/?npc=15083)
Gurubashi Mojo Madness (https://db.darkwizard.pl/?item=19931)
Brazier of Madness (https://db.darkwizard.pl/?object=180327)(https://wow.gamepedia.com/File:Edge_of_Madness.jpg)
Caly event (https://db.darkwizard.pl/?search=Edge+of+Madness)

Przeklejone z mantisa coby nie popadło w zapomnienie :p

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.

**Comment by Riztazz** [comment]
Otwieram, mialem przypisane na poprzednim bugtrackerze, tylko musze znalezc czas zeby to napisac

**Comment by Szelmon556** [comment]
to jak, mam szukac dowodu? ;d

**Comment by Riztazz** [comment]
Fixed on Feronis, Angrathar will be updated in following days
