### ISSUE TITLE
[Quest] Eyes Above, Grizzly Hills

### ISSUE THREAD

**Issue by Kittykatreporter** [SunwellTracker/issues#1300]
Decription: 
Quest requires you to bind sight of Imperial Eagles ( http://www.wowhead.com/npc=26369/imperial-eagle). You're supposed to use quest item on 6 different eagles, watching them fly away. You can complete the quest. As far as i know, quests from retail videos linked in Source did not get any changes since WotlK.

How it works: 

You can use quest item six times on single mob and complete quest,  eagle's dont dissapear and there is no "flying away" animation, but you get the "eagle vision" animation.

How it should work: 

Quest item should be used on six **different** mobs, each mob should despawn and fly away

Source (you should point out proofs of your report, please give us some source): 
Wowhead comments: http://www.wowhead.com/quest=12453/eyes-above
Youtube play through: WoD  https://www.youtube.com/watch?v=Mh73ie2gRg0
Legion: https://www.youtube.com/watch?v=P_5ua98mU1E

**Comment by Bel-WOW** [comment]
I confirm this.

**Comment by Dootz** [comment]
Fixed.
