### ISSUE TITLE
[Malygos 10man] Achievement missing

### ISSUE THREAD

**Issue by Dunderj** [SunwellTracker/issues#1301]
Description: 
We killed Malygos today under 6minutes for the achievement, and 2 of the raiders in the raid didn't receive the achievement, Foxy and Faldal. (InstanceID 15911).

How it works: 
Not everyone in the instance gets the achievement upon killing Malygos under 6minutes.

How it should work: 
Everyone that participated in the fight should be rewarded with the achievement

Source (you should point out proofs of your report, please give us some source):
https://imgur.com/VMsJqU5

**Comment by jesterlol** [comment]
Here is another Screenshot. :)

http://185.170.114.68/sharex/Wow_2018-04-25_23-04-26.png

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1220
