### ISSUE TITLE
[Icecrown Citadel] Val'kyr Shadowguard vs Threat

### ISSUE THREAD

**Issue by lachapelle** [SunwellTracker/issues#1303]
Decription: 
Obecnie Valkyrie bija sobie kogo chca z Life Siphona.

How it works: 
Po zbiciu Valkyrie do 50% leci sobie ona na srodeczek i castuje Life Siphona w randomowe cele (nie bierze w ogole pod uwage tabeli aggro). Psuje to Power Word: Shieldy Disco priestowi.
[https://www.youtube.com/watch?v=dkIUurnb6x8](url)

How it should work: 
Tabela aggro powinna byc uwzgledniana jako main target od Life Siphonow (glowny dmg valkyrie).
Guide Paragonow na LK HC:

> As the val’kyrs get dps’d down to 50% they drop the player they were carrying and fly up in the air and start shooting. They have aggro and we used a retribution paladin with righteous fury on to pull aggro from the val’kyrs. When they flew up our protection paladin taunted them off the retribution paladin to soak the damage they did. If the val’kyrs were allowed to shoot around freely they would have destroyed all the discipline priest shields which would have made infest healing impossible.
[http://www.paragon.fi/node/160.html](url)

[https://youtu.be/UJz6R18A5u8?t=7m31s](url) <--- caly dmg jest soakowany przez paladyna prot

Source (you should point out proofs of your report, please give us some source):

**Comment by lachapelle** [comment]
@Wojtyas Czesc nadal nie dziala, sprawdz discorda napisalem co i jak

**Comment by Wojtyas** [comment]
Siemano, okej dopilnuję aby zostało fixnięte!

**Comment by Riztazz** [comment]
re-test please

**Comment by lachapelle** [comment]
@Riztazz Napisalem Ci na Discordzie jak to obecnie dziala, sprawdzaj od nadawcy Bonka

**Comment by lachapelle** [comment]
@Riztazz dziala tylko jest problem z AOE tauntem paladyna, a dokladniej wyskakuje: Invalid Target, jak nie jestes zajety to obczaj baze, dzieki
