### ISSUE TITLE
[NPC] Desolace Caravan

### ISSUE THREAD

**Issue by fabienjinn** [SunwellTracker/issues#1305]
Decription: 

In Desolace, there is a caravan patrolling between 2 points, 2 intersections in desolace.

How it works: 

Actually, this caravan does not exist.

How it should work: 

The caravan travels between the 2 points. When she arrives at one of the 2 points of her patrol, she stops 10 minutes then resume the path in her inverses.

A very specific seller appears each time the caravan arrives at an end point of its patrol.

Vendor-tron 1000 appears when she arrives at the northernmost point of her patrol.
Super-Seller 680 appears when she arrives at the southernmost point of her patrol.

Source (you should point out proofs of your report, please give us some source): 

Super-Seller 680 : https://dbwotlk.com/?npc=12246
Vendor-tron 1000 : https://dbwotlk.com/?npc=12245
Caravan patrol path : http://www.wowhead.com/npc=11564/gizelton-caravan-kodo

**Comment by Towoku** [comment]
It works

**Comment by Towoku** [comment]
I wanted report 1 of 2 quests that you need 2 do with them but after 5 h and like 4-6 tried i managed to pass it.  In this quest https://db.darkwizard.pl/?quest=5821 its a way for kodos to block themself and just sit in 1 spot until 1st goblin die or reach end of escort quest( then fail it). My guess was that its cuz of centaur cyclone ability https://db.darkwizard.pl/?spell=6728 but it should be tested locally and its low prio cuz in the end with good tactic u can pass it (or ask high lvl for clear)
