### ISSUE TITLE
Molten Core Bugg

### ISSUE THREAD

**Issue by Tna1112** [SunwellTracker/issues#1306]
Decription: 
ME and 3 other players Were Doing Good old Molten core raid 60 for Achievement But Coming up to the Final Boss We got Stuck the NCP did not Spawn to call raggy Wel killed all bosses but the final We ticket for GM they useless and did not help us we Abandon the raid 

How it works: 
Kill all bosses with the Steal Plate to unlock Upper Level then Of to raggy But Dose not

How it should work: 

Same as Above 
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Can't reproduce. I killed all 8 bosses leading to Majordomo and he spawned in the same location as in video: https://www.youtube.com/watch?v=Nx14eu6kerA

**Comment by Tna1112** [comment]
i quit sunwell now
