### ISSUE TITLE
QUEST- Reconnaissance Flight (SCHO-BASIN)

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#131]
Decription:  Impossible to control vertical axis (fly) 

How it works: Currently impposible to fly and land wich is the whole point of the quest

How it should work: https://www.youtube.com/watch?v=bKDuH7VhXj4

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=bKDuH7VhXj4
https://wotlk-twinhead.twinstar.cz/?quest=12671

**Comment by Kokaina** [comment]
Duplicate report.
