### ISSUE TITLE
Lost 2X EXP (stuck in blizzlike)

### ISSUE THREAD

**Issue by Kadrian94** [SunwellTracker/issues#1310]
Decription:
 My rogue character (dirky in account: ****) on Angrathar, lost his 2* exp boost, tried to go to .blizzlike and then back, but didnt work.

How it works: 
I get 1x exp for everything 

How it should work: 
I should get 2x exp for everything (or more O.O)
 
Thank you in advance
Source (you should point out proofs of your report, please give us some source):

**Comment by eloquence743** [comment]
You get x1 xp starting from level 70, it's not a bug, but a feature. Sorry, and have fun. Plus, delete acc name and do not share it publicly. Have a pleasant day :)
