### ISSUE TITLE
Pounce not activating on stealthed people correctly

### ISSUE THREAD

**Issue by givemeausernameplease** [SunwellTracker/issues#1311]
Decription: 
Pounce ability is a stun / bleed spell that can be used only while prowling.
It bugs when using it on rogues that are also stealthed (presumably other stealthers)

How it works: 
When used on a stealthed rogue, there's a chance I get the pounce done, it does the sound and exits my stealth but doesn't stun nor bleed the rogue, and after they just turn around and sap me freely.

How it should work: 
Rogue should get normally stunned and bleeded if Pounce is cast, or if he is too invisible or for other reason Pounce was not able to land druid should remain in stealth.

Source (you should point out proofs of your report, please give us some source): 
Happened twice today. Didn't notice it before.

**Comment by givemeausernameplease** [comment]
Also I'd add I'm Pvp hitcapped and wasn't under effects of reduced miss chance, so it wasn't a miss either.
It's most likely the server lagging slightly letting my Pounce happen but then decide that "oh the rogue can't be seen any more so let's not pounce after all, but screw the druid and his stealth."

**Comment by givemeausernameplease** [comment]
Also recently happened on a druid that was going in prowl same time.

**Comment by ntt1** [comment]
Can confirm this is happening.

**Comment by akrom23** [comment]
Cannot reproduce.
