### ISSUE TITLE
[deviant delight transformation]

### ISSUE THREAD

**Issue by soserxd** [SunwellTracker/issues#1312]
Decription: 
this is small issue but when consumed after using iron boot flask deviant delights should turn you into a human male even if your character is female 

How it works: 
when consumed after using iron boot flask deviant delights still turn me into a human female

How it should work: 
when consumed after using iron boot flask deviant delights should turn me into a human male

Source (you should point out proofs of your report, please give us some source): 
![mgidk9h](https://user-images.githubusercontent.com/38785770/39361424-b0d45060-4a22-11e8-8085-b1162c11b940.png)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1370

**Comment by Dootz** [comment]
will be fixed with next server update
