### ISSUE TITLE
[Quest] Saragosa's End

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1313]
Decription: 
minor bug, that force us to kill ourselves. when we summon Keristrasza, we have quest complete and quote interaction. Naturally we complete quest first, because if we will teleport, we need to wait 2min for q item cooldown to summon Keri again. So, we finish quest, take next, and... we lose quote option to teleport us back. We are forced to jump from platform, fly 300metres down, and do a loud "splat" at ground.

How it works: After q finish, we cant teleport to base.

How it should work: When we finish q, teleport quote disappears.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11957/saragosas-end
btw even GitGut Video shows, that ppl choose fly mount instead of teleport, but its impossible, if you dont have fly mount. xD

**Comment by Dootz** [comment]
Fixed.
