### ISSUE TITLE
[Hunter] Glyph of Explosive Trap not scaling

### ISSUE THREAD

**Issue by Dunderj** [SunwellTracker/issues#1314]
Decription: Glyph of Explosive Trap https://db.darkwizard.pl/?item=45733 _The periodic damage from your Explosive Trap can now be critical strikes._  does not scale with the crit from the hunter.

How it works: It only seems to crit for ~20-22% of the time even when you are fully raidbuffed with over 60% crit.

How it should work: It should scale with the hunters crit.

Source (you should point out proofs of your report, please give us some source): data with over 2500 Explosive Trap ticks on level 80 target on Angrathar: https://imgur.com/HT7P8t0

Logs from retail WoTLK:
http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?s=8418&e=9169
http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?enc=trash

**Comment by Soufly** [comment]
The trap itself is using the SPELL crit chance(which is around 19-22%),instead of our RANGED crit chance(which it should be around 50-60%,with all raid buffs,and procs on average).

**Comment by Soufly** [comment]
Can someone check this ? It is important for the survival hunters.

**Comment by Dootz** [comment]
> The trap is using our SPELL crit chance

That's correct and from what I found that intended. There was a ticket on Feronis bugtracker about it (sadly in Polish and does not provide source/proof) https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/1021 . I'll keep looking for a proof of how it should work.

**Comment by Soufly** [comment]
@Dootz Check T9 2 set bonus for hunters.It should work in the same way.Both spells explosive trap and serpent sting are dots.

**Comment by Soufly** [comment]
Patch 3.3.0 ''[Explosive Trap], DoT now receives bonus damage equal to 100% of RAP (old - DoT did not scale with RAP)'' - http://wowwiki.wikia.com/wiki/Patch_3.3.0_(undocumented_changes) . If it scales with the RAP,then the critical strike should do the same.

**Comment by Soufly** [comment]
https://www.mmo-champion.com/threads/671755-Explosive-trap-on-PTR - Found this guy(the first comment),from the PTR of TOC(thats the end of 3.1.3 patch probably).

**Comment by Soufly** [comment]
https://db.rising-gods.de/?spell=63068 - School | Physical .

**Comment by CiriSunwell** [comment]
It is not bugged, i know you guys want to Top dps by just putting Explosive trap with bugged glyph, but sadly after this fix you need put more effort.

**Comment by CiriSunwell** [comment]
Proof my previous report was correct:

http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/xe/?s=8418&e=9169&x=spell+%3D+%22Explosive+Trap%22

[21:30:04.779] Bullseyes Explosive Trap  Val'kyr Shadowguard 559
[21:30:05.029] Bullseyes Explosive Trap  Val'kyr Shadowguard *863*

559 * 1,5 = 838 (base spell crit damage is 150%)
838 * 1,03 = 863 (meta gem gives 3% bonus crit damage)

I think it proof that on retail Explosive Trap was considered as spell, not ranged abilities. Otherwise it should crit for 230% (he was MM) + meta gem.

**Comment by Dunderj** [comment]
The bug is concerning the crit **chance**, not crit damage of Glyph of Explosive Trap. With the same source you provided you can clearly see how often his glyphed Explosive Trap crits: http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?s=8418&e=9169
6 normal ticks, 20 tick crits on LK fight, which suggests 76% crit chance which is realistic in ICC gear.

Trashmobs summary from same wol: http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?enc=trash 102 tick crits vs 51 normal ticks, which averages out at a 66.6% chance to crit on explosive trap ticks.

**Comment by CiriSunwell** [comment]
@Dootz quote my report from Feronis realm, so i wanted prove this report was correct. But in this report i only wanted nerf crit damage, devs nerf also crit chance, but i didn't ask for it in my report. I cant find 100% proof how crit chance should scale in this glyph, i would say it should scale with melee crit chance, but i cant proof it. You guys need find 100% proof for this report.

**Comment by Dunderj** [comment]
The proof is in the retail logs from WoL, please don't spread false information
