### ISSUE TITLE
When u send ur pet you can still get sapped here

### ISSUE THREAD

**Issue by buffdkplz** [SunwellTracker/issues#1315]
Decription: if a dk hunter warlock etc. sends his pet he still can get sapped

How it works: u Count as not in combat for sap when your pet is send but didnt allrdy hit something 

How it should work: u Count as in combat as soon as you send your pet for sap mechanism

Source (you should point out proofs of your report, please give us some source): on any other priv Server and back than on retail sending your pet did prevent u from getting sapped

**Comment by Dootz** [comment]
That issue was part of big debate that ended in change of this mechanic. https://github.com/SunwellTracker/issues/issues/553

> You're now able to sap a player whos not in combat even if he sent his pet on target, because we decided to resolve that bug that blizzard had in the past. Also resolved an issue where guardians would instantly set victim in combat rather than when they actually hit him, as far as sending pet on target behind LoS, ill write it down as ToDo after our movement rewrite. Closing for now

**Comment by Dootz** [comment]
> You're now able to sap a player whos not in combat even if he sent his pet on target, because we decided to resolve that bug that blizzard had in the past. Also resolved an issue where guardians would instantly set victim in combat rather than when they actually hit him, as far as sending pet on target behind LoS, ill write it down as ToDo after our movement rewrite. Closing for now
