### ISSUE TITLE
[Quest] Cold Hearted. 

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1317]
Decription:  A truly cold hearted quest. you can steal prisoners from other player's back xD https://youtu.be/rYliZIZmuFE

How it works: You can steal his bike... ummm prisoner! xd

How it should work: Prisoner placed on proto drake's back should be unable to steal :D 

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29639/brunnhildar-prisoner

**Comment by Dootz** [comment]
will be fixed with next server update
