### ISSUE TITLE
Beastmastery Pet damage bugged in Arena

### ISSUE THREAD

**Issue by lippincott25** [SunwellTracker/issues#1319]
Decription:  Beastmastery Pet damage bugged in Arena

How it works: Attackpower of pet drops by 150

How it should work: Attackpower of pet shouldn't change

Source (you should point out proofs of your report, please give us some source):  
![wowscrnshot_042718_205818](https://user-images.githubusercontent.com/36810222/39391812-a2057726-4a5e-11e8-8699-5f26e7f6ce74.jpg)
![wowscrnshot_042718_210003](https://user-images.githubusercontent.com/36810222/39391822-cd6fb9b2-4a5e-11e8-8bb3-06fc491f65a7.jpg)

**Comment by Cwiercpasiec** [comment]
#1270  Spamming about a bug won't make it fixed faster...
