### ISSUE TITLE
[Quest] The Stone That Started A Revolution

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1320]
Decription: Some Ancient Elven Masonry  in Ruins of Shandaral (Cystalsong Forest) has doubled spawn. 

How it works: Doubled spawn.

How it should work: They should spawn alone.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=13130/the-stone-that-started-a-revolution
http://www.wowhead.com/item=43218/ancient-elven-masonry

**Comment by Dootz** [comment]
Fixed.
