### ISSUE TITLE
[Quest] Shutting Down manaforge B'naar 

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#1322]
#1223 - Still broken

Decription: Quest: Shutting Down Manaforge B'naar from Anchorite Karja in Area 52

How it works: The quest objectives are marked as complete and it is marked as complete in the quest log but the questgiver is still grey and will not accept.

How it should work: The quest should be able to be turned in

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/pcRor

Just reposted the other issues info sense you cant reopen a closed one. This is still broken on the horde side. Tried to drop it and redo, no dice.

**Comment by Dootz** [comment]
Hi! 
Should be fixed now. If you have it in questlog, please abandon it and try again. Let me know if that helped.
