### ISSUE TITLE
Recipe: Transmute Primal Might wrongfully on CD

### ISSUE THREAD

**Issue by Justhype96** [SunwellTracker/issues#1323]
Decription: 
The Recipe: Transmute Primal Might is sold from Altaa in exodar, Melaris in Silvermoon City and Skreah in Shattrath.

How it works: 
It's currently on a buyout cooldown that according to a lot of searching on internet is 20 hours
source: hours.http://wowwiki.wikia.com/wiki/Recipe:_Transmute_Primal_Might

How it should work: 
It should as of patch 3.0.2, no longer be on a cooldown. 
source: http://wowwiki.wikia.com/wiki/Recipe:_Transmute_Primal_Might

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Recipe:_Transmute_Primal_Might

**Comment by eloquence743** [comment]
You're wrong, as it's stated that the craft cooldown is 20 hours, and was removed as of patch 3.0.2. It doesn't say anything about the buyout from the vendor cooldown. Cheers.
