### ISSUE TITLE
Ultrasafe Transporter : Gadgetzan unavailable

### ISSUE THREAD

**Issue by psychazia** [SunwellTracker/issues#1325]
Decription: 
This item https://db.darkwizard.pl/?item=18986 isn't available

How it works: 
The Npc https://db.darkwizard.pl/?npc=8736 engineer trainer at gadgetzan doesn't teach the spell https://db.darkwizard.pl/?spell=23489

How it should work: 
The engineer trainer just should learn us the spell if we have the level required..

Source (you should point out proofs of your report, please give us some source):
https://www.nostalgeek-serveur.com/db/?spell=23489

**Comment by Dootz** [comment]
You can learn it from http://www.wowhead.com/npc=14743/jhordy-lapforge 
Just talk to him. Only requirement is to have:
- Engineering at level 260
- Gnomish Engineer skill http://www.wowhead.com/spell=20219/gnomish-engineer
