### ISSUE TITLE
[Achievement] Bloody Rare

### ISSUE THREAD

**Issue by Bestijax** [SunwellTracker/issues#1328]
Decription: Do wykonania tego osiągnięcia należy zabić 20 rare mobów w outland jednak jeden z nich: "Hemathion" ma złe miejsce spawnu i zawsze gdy próbuje się do niego podejść to wypada za tekstury. Gram na Feronis.

How it works: Hemathion wypada za mapę i nie da się go zabić.

How it should work: Miejsce spawnu Hemathion zostanie poprawione i będzie dało się go zabić.

Source (you should point out proofs of your report, please give us some source): http://db.darkwizard.pl./?npc=18692
![111111111111111111111111111](https://user-images.githubusercontent.com/38879816/39468837-5e3b78a4-4d35-11e8-84f2-67b39fea8b8e.PNG)

**Comment by Dootz** [comment]
potwierdzam, dodam mu też ścieżkę bo nie powinien stać w miejscu
