### ISSUE TITLE
QUEST-Flight of the Wintergarde Defender (dragonblight)

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#133]
Decription: The gryphon spawns 25 yards in front of us and is unable to grab Helpless Villagers

How it works: 
1.When you right click the item the gryphon spawn 25 yards in front of you
2.The number 1 ability isnt working 

How it should work: https://www.youtube.com/watch?v=lF_OCW9WIHA

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=lF_OCW9WIHA
http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender

**Comment by Dootz** [comment]
I tested it and ability 1 works fine, but you're right with that gryphon spawn

**Comment by Dootz** [comment]
Please make sure you're targeting Helpless Villagers and not Trapped Villagers http://www.wowhead.com/npc=27359/trapped-wintergarde-villager

**Comment by sunwellkiwi** [comment]
All the lack of sleep during that period may have led to some confusion, but you taking the time to look into it is really preciated. <3
