### ISSUE TITLE
Rogue can restealth in hex

### ISSUE THREAD

**Issue by exzetron** [SunwellTracker/issues#1331]
Decription:  If a rogue get hexed and drop combat he can restealth, shouldnt be able to use spells in hex.

How it works: Hex rogue (hes in combat) after a while if you dont hit him he drops combat and he can restealth

How it should work: shouldnt be able to cast spells in hex, as soon as the hex drops and rogue still out of combat he should be able to restalth.

**Comment by kinglobster** [comment]
pain suppression with glyph is also castable while hexed

**Comment by Azathothh** [comment]
Will be fixed at next server update.
