### ISSUE TITLE
[Naxx 25] Bugged Gluth Loot - Only 2 epics, no tier tokens (and green shoulders?)

### ISSUE THREAD

**Issue by Smoogl** [SunwellTracker/issues#1333]
Decription: 
We killed Gluth on 25man, but much to everyone's surprise the boss only dropped 2 epics, no tier tokens and a random pair of green shoulders. 
Screenshot of the loot: 
https://i.imgur.com/0KWVtKY.jpg

Raid ID: 6551 (Naxx 25)
Date: 2/5/2018, ~00:15 GMT+1
Lootmaster: Ledge

How it works: 
There were only 2 epic drops from a boss on 25-man.

How it should work: 
There should be more loot. Tier tokens included. Also, there shouldn't be any green items.

Source: 
![naamloos](https://user-images.githubusercontent.com/38895596/39498097-940147cc-4da6-11e8-9d45-9a707bbba4c6.png)

**Comment by Dootz** [comment]
Should be fixed now, i'm sorry for any inconvenience caused

**Comment by Smoogl** [comment]
Any chance we can get our missing tier tokens?

**Comment by Dootz** [comment]
I asked GMs and unfortunately, we can't restore them. I'm really sorry. :(

**Comment by Smoogl** [comment]
Bad luck, I hope one day I will be able to overcome this blow.

Either way, thanks for your effort and quick responses.
