### ISSUE TITLE
[Children's Week] Can't get replacement Draenei/Blood Elf Orphan Whistle

### ISSUE THREAD

**Issue by Dawnre** [SunwellTracker/issues#1334]
Decription: 
Players cannot get replacement Draenei orphan whistles from Orphan Matron Mercy in Shattrath.

How it works: 
Currently Orphan Matron Mercy in Shattrath City gives the **human** whistle instead of the Draenei whistle (I assume the issue is similar for Horde).
![image](https://user-images.githubusercontent.com/5439312/39500003-285cfba8-4d77-11e8-96a6-a1b66846f3ae.png)

How it should work: 
"If a player loses their Orphan Whistle at any time during the in-game Children's Week event they can speak to a Matron in cities to receive a replacement. Players can now obtain another orphan whistle from an orphan matron, even if they have completed all the associated orphan's quests."
The Matron located in Shattrath should give the correct whistle for the BC Children's Week quests.

Source (you should point out proofs of your report, please give us some source): 
[Description of the Item and Hotfix describing this behavior](http://wowwiki.wikia.com/wiki/Draenei_Orphan_Whistle)

**Comment by Dootz** [comment]
Should be fixed now.
