### ISSUE TITLE
Arthas not working properly in CoS

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1337]
Decription: In Culling of Stratholme, after you kill the second boss you need to talk to arthas to get him to come to the inn and continue the dungeon. He is not supposed to kill any zombies on the way to the inn. This makes the achievement zombiefest extremely difficult because you are supposed to able to grab all 85 zombies from the beginning of the instance, but instead arthas kills half of them permanently.

How it works: He kills half the zombies permanently as he walks to the inn.

How it should work: He just walks straight to the inn without killing anything.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/achievement=1872/zombiefest#comments
in retail wowhead comments everyone recommends waiting for zombies to respawn and then talk to arthas, a strategy that could not work if arthas killed zombies in retail permanently.

**Comment by Dootz** [comment]
will be fixed with next server update
