### ISSUE TITLE
Activation crystals not working properly in violet hold

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1338]
Decription: In Violet Hold there is activation crystals that do a certain amount of burst damage to everything in the room. They do not work on Ichoron's blobs. This is a major problem for the achievement "dehydration" because for that achievement all you are supposed to do is hit a crystal and it kills them all, but this strategy does not work with broken crystals.

How it works: activation crystals do not kill ichor globules.

How it should work: they kill ichor globules. 

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/achievement=2041/dehydration#comments
everyone suggests to use crystals in original wowhead comments.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/509

Will be fixed with next server update
