### ISSUE TITLE
Mage T7 4 piece set bonus doesn't work

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1339]
Decription: Mage 4 piece tier 7 set bonus is supposed to give 5% bonus critical damage just like the meta gems. Not sure if that has been posted already but I see top end mages complaining about this.

How it works: Does not give any critical bonus at all.

How it should work: give's 5% bonus damage to crits.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1032
