### ISSUE TITLE
[Quest] Helcular's Revenge

### ISSUE THREAD

**Issue by LookinGood** [SunwellTracker/issues#1341]
Decription: 
https://db.darkwizard.pl/?quest=553
After the completion of the quest(https://db.darkwizard.pl/?object=1767) should appear Helcular
(https://db.darkwizard.pl/?npc=2433)

How it works: 
Helcular does not appear.

How it should work: 
Helcular should appear.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
