### ISSUE TITLE
[Rogue] Shadowstep

### ISSUE THREAD

**Issue by arielmarcinkowskir91** [SunwellTracker/issues#1342]
Description: Shadowstep (http://db.darkwizard.pl/?spell=36554) gives a bad bonus to offensive skill.

How it works: Shadowstep (http://db.darkwizard.pl/?spell=36554) gives a 10% (as you can see on print screen) bonus to offensive skill.

How it should work: Shadowstep (http://db.darkwizard.pl/?spell=36554) should give a 20% bonus to offensive skill.

Source (you should point out proofs of your report, please give us some source): 
![1](https://user-images.githubusercontent.com/38940032/39569022-e3bde82c-4ebb-11e8-934a-31a94bbb0e20.png)
![2](https://user-images.githubusercontent.com/38940032/39569023-e3f1e9b0-4ebb-11e8-825b-89c28b92dd60.png)

**Comment by Dootz** [comment]
I just tested it on training dummies in AT with Sinister Strike and it seems to work. Here are my results:
Sinister Strike

Without Shadowstep buff
119
121
116
115

on average: 117.75

20% Bonus would be 20% * 117.75 = 23.55
So it should deal around 117.75 + 23.55 =  141.3

With shadowstep's buff :
147
139
144
144
On average: 148

**Comment by arielmarcinkowskir91** [comment]
Ok, maybe i was to rush, and i will check this; but on garrote, whatever mob i hit, there is always 10% more damage on tick. Regards.

**Comment by arielmarcinkowskir91** [comment]
I confirm that on sinister strike it work well, but on dots like rapture or garrote it simple work strange (about 10% boost), or is it my, dont knowing something hidden mechanics of its damage. Anyway, thanks fo da response. ;)

**Comment by Dootz** [comment]
ok, I'll check it on other abilities then.
