### ISSUE TITLE
[Dire Maul : East ] No Rich Thorium veins  at the end

### ISSUE THREAD

**Issue by enkzz** [SunwellTracker/issues#1343]
Decription: 
Hello, and thank you for taking your time to solve this problem. As I was leveling my profession being on the Thorium level of Mining and Jewelcrafting I decided to use an old trick I did back on retail and on every other servers. It is to farm Dire Maul : East in order to get ores. At the end when you kill the last boss, several imps break through the wall and opens a cavern where you can exit the instance but also see 3 to 6 Rich Thorium Veins on your way out. This is very convenient as a level 80 to farm because only you can have those ores and you simply have to reset the instance & repeat.

How it works: 
There is no ores at all. Nothing.

How it should work: 
There should be Rich Thorium Veins on the way out of the instance( in the cavern)

Source (you should point out proofs of your report, please give us some source): https://youtu.be/lhViC_wJ6OI?t=86 Video proof with the timing of two people farming it.

**Comment by enkzz** [comment]
Hello, 

Do you need more proofs or is it fine ?

Regards,

Enkzz

**Comment by enkzz** [comment]
Can i be of any help ?

**Comment by Dootz** [comment]
they should be spawning there already.

**Comment by enkzz** [comment]
Yes they are thanks !
