### ISSUE TITLE
Jotunheim Cage Key

### ISSUE THREAD

**Issue by Yacopok** [SunwellTracker/issues#1345]
Decription: 
The drop rate for Jotunheim Cage Key ID42422 should be 10% according to the datebase, however after 40 minutes of griding only a single key has dropped.
Perhaps I am simply getting really unlucky, but would love a Dev to just look into the DB to double check if the correct % is applied.

How it works: 
Received 1 key after killing close to 50 mobs, which makes the drop rate 2% at best.

How it should work: 
Every 10th mob if not more should drop a key.

Source (you should point out proofs of your report, please give us some source): 

http://db.darkwizard.pl/?item=42422

**Comment by Dootz** [comment]
will be fixed with next server update
