### ISSUE TITLE
Block value bugged. Display. ? 

### ISSUE THREAD

**Issue by sagewarrior2** [SunwellTracker/issues#1347]
Decription: 
the block value brought on about items is not properly displayed nor calculated for the warrior's move shield slam, which is dependant on the the block value.

How it works: 
The the stats page of the character, the block value number does not increase depending on the equipment attached. also shields don't add the proper block value.

How it should work: 
under the strength portait number of the character where the block value is displayed. the number should go up. Also shield slam- a move dependant on the block value would comfirm it is working. as they share a direct correlation. if (BV) block value goes up then shield slam damage should go up also.

![Uploading BV with shield A.png…]()

![bv value of shiled a 5](https://user-images.githubusercontent.com/38982844/39631792-875256ea-4ff6-11e8-92ed-c3edb1e35c65.png)
![bv value with shield b](https://user-images.githubusercontent.com/38982844/39631791-87176dd2-4ff6-11e8-8ba0-820fed35ca51.png)
![Uploading BV value with shield B.5.png…]()

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
When you mouseover 'strength' stat it only display block value which you are gaining from that stat, not your total block value.
Total block value can be found in "defenses" tab after mousing over "block"
![obraz](https://user-images.githubusercontent.com/37483678/66854794-53aacc00-ef82-11e9-9b1e-e2160f5acbb0.png)
"your block stops X damage" X = block value from strength + block from shield +block from "block value" stat on tank gear + other sources like buffs, etc.
