### ISSUE TITLE
Quest thats allow you to fly didnt show

### ISSUE THREAD

**Issue by katsuia1** [SunwellTracker/issues#1350]
Decription:  i made all my quest without a single problem all the way to lv 9, after level 9 all my quest was gone, and the most important one the quest that allows me to fly to another town, so now every time i click on the shoes to find a location to fly, it says that i don't have any location to fly

How it works: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
There's not enough data in this report. Please add race and class of your character, and which flymaster you've tried to use.
