### ISSUE TITLE
Warlock spell Conflagrate not working propertly 

### ISSUE THREAD

**Issue by Komarac1234** [SunwellTracker/issues#1352]
Decription: Conflagrate spell is showing with 1-2 sec delay

How it works: When i use immolate the conflagrate spell does not show immediate.It is usable only after 1-2 sec

How it should work: Conflagrate should be able to be used instantly

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
No, it shouldn't work instantly after applying Immolate.
