### ISSUE TITLE
[Dungeon] Grand Magus Telestra (The Nexus)

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1355]
Decription: Grand Magus Telestra split and died in the same moments. Her clones did not dissappeared.
http://myprintscreen.com/s/t55z/4f379e2cf9 
http://myprintscreen.com/s/t562/58c8bdd80c

How it works: Grand Magus Telestra's clones did not dissappeared after her death.

How it should work: Whole encounter should be ended while she lies dead on the ground.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=26731/grand-magus-telestra
HC version.

**Comment by Dootz** [comment]
will be fixed with next server update
