### ISSUE TITLE
Reconnaissance Flight

### ISSUE THREAD

**Issue by Borthun111** [SunwellTracker/issues#136]
Decription: 

The plane doesnt work as intended
How it works: 

The controls of the plane are all over the place, You cant go up or down with it and it moves really slowly and u can't land it at all so this quest is impossible to be completed
How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Just press 'space' button in order to take full control of place :P

**Comment by Cwiercpasiec** [comment]
This quest is a bit bugged, sometimes you can't land and you have to abandon and take this quest again. Usually worked for me the first or second time, I'm not sure why it doesn't work sometimes.

**Comment by Bel-WOW** [comment]
Did it myself, and quest really is bugged.
- As said by Kokaina, you need to press "space" after NPC gives you control of the vehicle to actually control the vehicle. Minor but annoying bug.
- If you are mounted while taking the quest (shadowform may also give the same result, not sure) you won't be able to use vehicle-skill to land the machine in designated place, making it not possible to finish the quest. Not so minor but equally annoying.

**Comment by Azathothh** [comment]
Seems like it's not using https://db.darkwizard.pl/?spell=52255 when plane is on "global cooldown" at the moment when it should be set on fire (at least that's how i could reproduce it)

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2540
