### ISSUE TITLE
The way to his heart

### ISSUE THREAD

**Issue by veljko93** [SunwellTracker/issues#1360]
Decription: The quest in howling fjord. Daily I think. I got the reef bul over, nothing happened.

**Comment by Dootz** [comment]
might be related to pet movement issues that will be fixed with next server restart.

**Comment by veljko93** [comment]
Good. Thank you for the answer!

**Comment by Dootz** [comment]
should work now.

**Comment by veljko93** [comment]
Wow, thank you!
