### ISSUE TITLE
[Instance] Scarlet Monastery - Catedral Door

### ISSUE THREAD

**Issue by Towoku** [SunwellTracker/issues#1361]
Decription: 
When entering catedral and using leaver we can close door(well i missclicked when looting-.-). But using leaver again dont open the door. (OoC, most of the mobs there etc) If i recall even door stayed closed even after killing bosses, so we were stuck(but anyway its worth testing). Only way out was disbanding party or hsing out ( no rdf). [Well it may be some kind of hack when fixing boss encouter, still imo easiest solution would be just to remove leaver so door close at start of fight and open after killing boss(or reseting)]

How it works: 
Player pull a leaver, door closes. Use it agian door stay closed.

How it should work: 
After closing door, pulling again should open door.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
