### ISSUE TITLE
Quest 10507 bug

### ISSUE THREAD

**Issue by psychazia** [SunwellTracker/issues#1363]
Decription: 
Seems there is a problem with the quest turning point http://db.darkwizard.pl/?quest=10507

How it works: 
First you have this two items provided http://db.darkwizard.pl/?item=29796 & http://db.darkwizard.pl/?item=30259
You need to get to netherstom & use the teleportation stone, then use Vorenthal's presence, the second item, to make Socrethar (http://db.darkwizard.pl/?npc=20132) attackable 
But when I try to use the Vorenthal's Presence on Socrethar, it just says "invalid target" & I can't engage him..

How it should work: 
the item just should work & after using it, we should be able to engage Socrethar..

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
