### ISSUE TITLE
Daily quests "TheKalu'ak" does not take human racial Diplomacy into account.

### ISSUE THREAD

**Issue by lukasognelod** [SunwellTracker/issues#1365]
Decription: 
Planning for the Future and Preparing for the Worst in Draginblight and Borean Tundra respectively does not give the extra 10% reputation gained for humans on completion. 

How it works: 
After completion the quest gives gold and 500 reputation

How it should work: 
After completion the quest gives gold and 550 reputation

Source (you should point out proofs of your report, please give us some source):
![wowscrnshot_050718_174043](https://user-images.githubusercontent.com/16799746/39710769-0a3bcbe4-521e-11e8-8b16-103c2a93944c.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1291
