### ISSUE TITLE
[Quest] Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by davidswayze** [SunwellTracker/issues#1366]
Decription: 
The quest "Iron Rune Constructs and You: The Bluff" has an activation piece that is not working.

How it works: 
When stepping on Lebronski's rug the NPC does not react.

How it should work: 
While in the construct suit the NPC Lebronski is supposed to negatively react when you step on his rug, allowing you to use the constructs bluff ability on the NPC and complete the quest.  See the Youtube video here for how it should work:  https://www.youtube.com/watch?v=w84B28E_r_o

**Comment by Dootz** [comment]
Hi, GM tested it on Angrathar and was able to complete it. But something is not working properly as he had to move around Lebronski, rather than standing on the rug.

**Comment by Dootz** [comment]
you should be able to use golem's spell on him even when he doesn't spot you. There's probably an issue with event's reset.

**Comment by davidswayze** [comment]
Attempted to use the spell (Bluff) on Lebronski without the NPC reaction to no effect.  Many thanks for looking into the issue.

**Comment by Dootz** [comment]
should work right now. It's possible that sometimes he won't move/notice you but you should be able to get quest credit.
