### ISSUE TITLE
[Quest] Mending Fences 

### ISSUE THREAD

**Issue by lax241** [SunwellTracker/issues#1367]
Decription: 
Bad quest reward for that quest.

How it works: 
Recived 22k of reputation to The Sons of Hodir

How it should work: 
Should recive 28.6k of reputation to The Sons of Hodir

Source (you should point out proofs of your report, please give us some source): 
![bez tytulu](https://user-images.githubusercontent.com/6098897/39718831-ba471cb4-5237-11e8-8875-70c1e2aa623a.png)
http://wowwiki.wikia.com/wiki/Quest:Mending_Fences

**Comment by Dootz** [comment]
That won't be changed. It was increased with the release of Icecrown Citadel (Patch Notes at wowwiki).
