### ISSUE TITLE
Purple Smoke Flare

### ISSUE THREAD

**Issue by Hoodeee** [SunwellTracker/issues#1368]
Decription: 
The "Schematic: Purple Smoke Flare" seems to be unobtainable. 

How it works: 
My friends and I have killed thousands of Phase Hunters in Netherstorm. These mobs as well as numerous other mobs in Outland should have a low chance of dropping the flare pattern. We have yet to receive the schematic.

How it should work: 
I would like to confirm whether these mobs are properly dropping this schematic.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=25887/schematic-purple-smoke-flare
http://wowwiki.wikia.com/wiki/Schematic:_Purple_Smoke_Flare

**Comment by Dootz** [comment]
will be fixed with next server update
