### ISSUE TITLE
MAGE ABILITY- Flamestrike

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#137]
Decription: AoE spell Flamestrike

How it works: Upoin casting flamestrike the first tick and sometimes second of dmg only affect 1 target.

How it should work: Flamestrike should hit all target at all time

Source (you should point out proofs of your report, please give us some source): https://youtu.be/bBP2lFGRK4c?t=458

**Comment by lowbur** [comment]
there's definitely an issue with flamestrike as multiple people have complained about it.

**Comment by Praktikanten** [comment]
Any fix comming soon?

**Comment by akrom23** [comment]
Looks okay.
