### ISSUE TITLE
[World Boss] Doomwalker

### ISSUE THREAD

**Issue by Sensza** [SunwellTracker/issues#1372]
Decription: 
http://www.wowhead.com/npc=17711/doomwalker#abilities
"Enrage - At 20%, all physical damage is doubled."

How it works: 
There's no Frenzy/Enrage below 20% hp.
https://imgur.com/a/TsDRoQb

How it should work: 
There should be Frenzy/Enrage below 20% hp.
https://youtu.be/IDe0Jna0K3g?t=2m30s

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
