### ISSUE TITLE
Mailbox

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#1373]
Decription: Otoz, na feronisie jak i na angratarze wystepuje bug z mailboxem. Mianowicie, po uplywie czasu przeznaczonego na odebranie maila od innego gracza (30dni/90dni) mail powinien zdaje sie byc odsylany do nadawcy, a zamiast tego itemy znikaja w twisting netherze albo goblinscy kurierzy dorabiaja na tym nielegalnym procederze. 

How it works: Itemaski oraz gold znika w niewyjasnionych okolicznosciach.

How it should work: Itemaski/gold powinien byc odsylany do nadawcy po uplywie miesiaca.

Source: Dowodu nie znalazlem, lecz wydaje sie oczywistoscia, ze nie dziala tak jak powinno. Jesli sie myle, najmocniej przepraszam.

Tymze sposobem stracilem mala fortunke na feronisie(na szczescie).

**Comment by Szelmon556** [comment]
Jakies postepy w tym temacie? :D Aktualnie znalazlem sie w sytuacji gdzie moge stracic troche fajnych rzeczy na Angra, a wiec nie ukrywam iz milo by bylo jakby maile ktore powysylalem wrocilby na moja postac :D

**Comment by Szelmon556** [comment]
dowod: http://wowwiki.wikia.com/wiki/Mail 

Mail expiration:
"Mail received stays in your mailbox for 30 days. Prior to patch 2.1.3, any piece of mail you read would only last for 3 days from being read.
**After the expiry period, the mail is returned to the sender. If the mail comes from the Auction House, a quest NPC, or anything similar, it is simply discarded and any item or money attached to it is lost.**"

**Comment by Szelmon556** [comment]
Jakies postepy? Albo moze sie myle to niepotrzebnie sie produkuje tutaj xD Tak czy srak, o ile to mozliwe i o ile jeszcze moje fanciki nie wyladawaly w twisting netherze prosiłbym o odeslanie maili z postaci o nicku Szelmob, bo juz nie wiem gdzie moglbym liczyc na pomoc ;D

**Comment by coolbeanslol** [comment]
This happened to me recently on two different characters on Frosthold.

The mail was supposed to be returned to the sender after the 30 days limit, but they weren't and were instead deleted. I checked the mails that were supposed to be returned and they all had the "return" button. I thought that they would be automatically returned so I didn't return them manually.

I lost an absurd amount of herbs and other alch mats from this. Is there anyway that those materials can be recovered? They shouldn't have been deleted.

I can provide the character names upon request.
