### ISSUE TITLE
Quest 10564 bug

### ISSUE THREAD

**Issue by psychazia** [SunwellTracker/issues#1375]
Decription: 
The quest Blast the infernals seems impossible to complete

How it works: 
When you try to use http://db.darkwizard.pl/?item=30614 as explicated in the quest, nothing happens
you cast the spell, but nothing happens, no display event, no completing the quest, nothing...

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
This event resets every 5 minutes. A good indication to tell if it will work is to check if "army" of infernals is alive. I'll reduce reset time for next server update.

**Comment by psychazia** [comment]
the army is alive & still not working...

**Comment by Dootz** [comment]
will be fixed with next server update
