### ISSUE TITLE
[Warlock] Voidwalker (pets in general?) passive stance + taunt

### ISSUE THREAD

**Issue by MilosMisic** [SunwellTracker/issues#1377]
Decription: 
If the Voidwalker is on passive stance and you manually taunt a mob pet will go back to the caster as if you pressed - follow.

How it works: 
^

How it should work: 
Pet should stay on the target

Source (you should point out proofs of your report, please give us some source):

**Comment by Zarant** [comment]
I'm pretty sure that's blizzlike, I used to have my pet taunt bound since it was useful in pvp to snipe grounding totems, and the pet used to behave just the way you described. Maybe i'm mistaken, but in any case you should provide proper evidence.

**Comment by Akha72** [comment]
I believe that's blizzlike too. I remeber using spells like Seduction or Soothing Kiss on a target and having my Succubus on passive she always came back to my side after casting. I know it's different minion but mechanics should be similiar, shouldn't they?
