### ISSUE TITLE
Single mob aggro from pack of mobs

### ISSUE THREAD

**Issue by MilosMisic** [SunwellTracker/issues#1378]
Decription: 
You can freely pull one mob from a pack of same mobs.

How it works: 
^

How it should work: 
Other mobs with same "class" should be pulled too.

Source (you should point out proofs of your report, please give us some source):

**Comment by Sensza** [comment]
I guess Developers are not concerned about your feelings, neither they read your mind.
Can you describe the specific circumstances like at least zone or group of mobs? Otherwise your report is not helpful.

**Comment by MilosMisic** [comment]
@Sensza Any group of mobs, it's a server wide problem. I think it's called zone aggro where the pulled mob has a area from which he chains his aggro onto other mobs of the same type.

**Comment by lmrech** [comment]
Already reported multiple times. Devs seems to not care about it.
