### ISSUE TITLE
Aggro distance

### ISSUE THREAD

**Issue by MilosMisic** [SunwellTracker/issues#1379]
Decription: 
Aggro distance feels like it's double than normal. Around 50 yrds.

How it works: 
I pulled a mob that was outside of my spell range.

How it should work: 
Should be alot lower.

Source (you should point out proofs of your report, please give us some source):

**Comment by Sensza** [comment]
I guess Developers are not concerned about your feelings, neither they read your mind.
Can you describe the specific circumstances like at least zone or group of mobs? Otherwise your report is not helpful.

**Comment by MilosMisic** [comment]
@Sensza I didn't have the time to test it thoroughly since it's not my job to do so. And It's a well known issue. I just decided to report it so the devs have it as a reminder.

**Comment by MilosMisic** [comment]
> Seems like a cry for help from a newbie having problems with leveling
Not really but whatever.
It's possible that Sunwell has a blizzlike aggro system and that am used to all kinds different scripting from other servers.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/336
