### ISSUE TITLE
[Profession]Tailoring Lightweave Embroidery procs on Buffs

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#138]
Decription: Tailoring profession Lightweave Embroidery http://wowwiki.wikia.com/wiki/Lightweave_Embroidery
Lightweave Embroidery is proccing on buffs applied on yourself or a teammate.

How it works: 
Lightweave Embroidery is proccing of buffs applied such as (Detect Invisibility) http://wowwiki.wikia.com/wiki/Detect_Invisibility, Or simply applying Demon Armor or Fel Armor. 
In world of warcraft normally procs on your character dont proc from a buff.
1- Apply a buff
2-Get proc
3- Cry

How it should work:
It should not proc on silly buffs such as detect invisible or fel armor.

Source (you should point out proofs of your report, please give us some source): 
this lock buffs himself a lot does fel armor, demon armor detect invis other spells and Lightweave Embroidery doesnt proc, soullink and still doesnt proc and some other buffs.
https://youtu.be/ieGnHENE7JQ?t=78 
Just to show he does have the enchant and it didnt proc with simple buffing.
https://youtu.be/ieGnHENE7JQ?t=137

Less important clip but here:
here Viscus swaps armor and it doesnt proc : 
https://youtu.be/IQYrH72-oXI?t=173

**Comment by Semper-Numquam** [comment]
Embroiders can proc from ANY spell cast, although it's a chance with an internal cooldown. Even "small buffing can proc it" as it proc rate is really high.

However, it should not proc from passive auras such as the healing from Fel Armor (changing Lock armors can proc it tho). I repeat myself, any spell cast can proc it, as long as it is a spell cast.

**Comment by moonsado** [comment]
After reading some older forums post regarding lightweave embroidery for WOTLK. There is something quite important to notice and thats the fact that lightweave embroidery was pretty well regarded for casters specially in pve. Oh sure some players were a bit upset when it procced while casting a simple heal yet no complaints as to a simple buffing such as a Priest giving stamina to his raid group or a Mage giving arcane intellect. Surly if this was how it was a lot of players would of ranted as they did for so many other things and not say that lightweave embroidery was actually not bad.

----Here I am not trying to prove that tailoring is a better profession but I am trying to prove that logically speaking no one in their clear mind would say that tailoring is good in raids if it procced of simple buffs just imagine "GUILD LEADER MY BACK ENCHANT PROCCED BY BUFFING MY FRIENDS WAIT 45 SECS PLS!" People would of ranted. instead of saying it wasn't a bad profession----

"I recently dropped maxed out enchanting with all WOTLK recipes for Tailoring (Lightweave Embroidery). Definitely noticed a DPS increase after raiding Ulduar last night so it was worth trading off +38 SP (two +19 on rings) for +250 SP over 15 seconds (30 sec cooldown). " "Bouth are good. I have Tailoring and like it alot, the new back enchant is very nice (finealy!)""I have to agree with SpiritusVex. If you want to maximize your character then JC/Tailoring are the clear winners"
https://www.mmo-champion.com/threads/645451-Enchanting-or-Tailoring

https://www.mmo-champion.com/threads/632848-Spell-Piercing-vs-Lightweave-Embroidery-in-the-Arena

+the video evidence 
https://youtu.be/ieGnHENE7JQ?t=78 clearly shows the lock buffing himself a couple of times nearly 7x whereas if i just do demon armor ill probably randomly proc it.

Just to show he does have the enchant and it didnt proc with simple buffing.
https://youtu.be/ieGnHENE7JQ?t=137

Also note in other private servers I have been they were not proccing on simple buffs.

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
