### ISSUE TITLE
[NPC] King Bangalash respawn timer

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#1381]
Decription: King Bangalash respawn timer is too long

How it works: King Bangalash respawn timer is 30 minutes http://db.darkwizard.pl/?npc=731

How it should work: please make it 3 minutes, or well 5-10, but better 3 : )

Source (you should point out proofs of your report, please give us some source): I couldn't find a proof, but hope it's quite a common sense that a quest mob shouldn't have respawn timer of half an hour

**Comment by Dootz** [comment]
will be fixed with next server update
