### ISSUE TITLE
Game crashes every time I fly over Dragonblight when starting from Dalaran

### ISSUE THREAD

**Issue by kevinmd88** [SunwellTracker/issues#1382]
Description: 
Every time I start a flight from Dalaran's flightmaster and the path takes me anywhere over Dragonblight (even if my final destination is not there), my game crashes. Two friends of mine say they're experiencing the same thing. I've cleared my cache more times than I can count. I have no idea what's causing it, but I've never had the same problem on any other server to my knowledge...

How it works:
Go to Dalaran, talk to the flight master and fly anywhere that would take you over Dragonblight - even if your final destination is not in Dragonblight, just make sure you fly over one of Dragonblight's as a connection. Game crashes.

How it should work: 
...Not crash

Source (you should point out proofs of your report, please give us some source): 
Screenshot of crash:
https://s14.postimg.cc/w8cnzup1t/crash-report-wow-sunwell-screenshot.png

Crash log (from the same window as in the screenshot):
https://pastebin.com/3NrrWDCi

**Comment by kevinmd88** [comment]
I appreciate the link @TheRealYasri 

Before I attempt to make that modification, however, is there any merit to the other "alternate" solutions proposed by the blue poster in that thread?

It mentions that it is an "OS setting" - is this the one that the Large Address Aware thing sets? Or is it something else that can be changed to fix the issue?

Can DX11 be forced? I'm not aware of the WotLK client supporting it.

If those things are ruled out, I will happily give the large-address thing a try.

**Comment by TheRealYasri** [comment]
DirectX11 came with cata, so for wrath it is not possible, you can try lower your graphics setting to see if that helps at all by reducing memory usage. WoW is running out of memory it is able to use and that is why it crashes. There is probably a way using a windows commandline prompt to make a exe aware but this app just makes it easier. WoW fixed this in 4.1 from what I can gather.
