### ISSUE TITLE
[Warlock] Rolling Corruption Incorrect Snapshot Mechanics

### ISSUE THREAD

**Issue by chme3921** [SunwellTracker/issues#1384]
Decription: Warlock currently has an unintended interaction with the Affliction talent "Everlasting Corruption", which allows certain spells to refresh Corruption. This refresh of Corruption has some snapshot effects from when the original Corruption is cast, but some stats are not intended to snapshot. However, on Angrathar, it appears that Haste is snapshotting from the original cast, when it is not intended to.

How it works: Corruption snapshots critical strike chance, percentage damage modifiers, haste, and spell power when it is cast. When it is refreshed, all of the old values are used assuming they are higher than when the new ones are applied.

How it should work: Corruption snapshots critical strike chance, and percentage damage modifiers when it is cast. When refreshed, critical strike chance and percentage damage modifiers from the original cast are used if they are higher, but new haste values and spell power values are used every time Corruption is refreshed.

Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/forums&topic=162195/rolling-corruption-an-overview
https://web.archive.org/web/20100717061617/http://elitistjerks.com/f80/t37900-dots_you_affliction_warlock_thread/#Rolling_Corruption_Crits_and_Modifiers

**Comment by Amarok-bt** [comment]
i call bs

**Comment by Avarishd** [comment]
go test on dummy, the things you listed are incorrect, all works fine. bs report

**Comment by mpuryear** [comment]
It's very easy to test that it is not snapshotting our SP. 

SB x3 to get shadowy embrace stacked, Life tap, corruption, click off LT buff, SB.

My damage went from 1300 per tick to 1200 per tick after refreshing it. 

The same can be done with haste. Cast anything until haste trinket procs. cast corruption, then click off the buff and refresh corruption with SB.

My hasted corruption had a 13s duration, after refreshing with SB it went back up to 15s.

working as intended. QED

**Comment by bugabuser** [comment]
Haste and SP is currently being rerolled on every reapplication of corruption, recast or through the Everlasting Affliction talent, which is intended. No bugs here.
