### ISSUE TITLE
Undying title does not work at all

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1386]
Decription: If you have the achievement The Undying and had the title, you can no longer put the title on, it is just completely absent from the title list.

How it works: The Undying is absent from the title list

How it should work: It shows up.

Source (you should point out proofs of your report, please give us some source):

**Comment by kovaq** [comment]
Any screenshot? seems to be working.

**Comment by Azathothh** [comment]
Just use a slider next to your titles list:
https://imgur.com/a/LG1KMsn
