### ISSUE TITLE
Critical Error Crash

### ISSUE THREAD

**Issue by kentertainer** [SunwellTracker/issues#1387]
Decription: 
Flying from Dal to the Alliance side flight path, I hit a critical error:
Failed to read file WORLD\WMO\NORTHREND\BUILDINGS\TITAN\WG_TITANBUILDING06_000.wmo.

It crashes the game completely. When I try to relog it gives me the same error and crashes again. 

How it works: 
Completely locked out of game on just the one character, all other characters on that account and any other account is still functional (although I have not attempted the same trip on another character for fear of losing more)

How it should work: 
Land safely, continue playing!
![wow crash](https://user-images.githubusercontent.com/39179382/39906077-2a8f6916-54a6-11e8-8976-3b6f95cb1609.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
This used to happen to me all the time with another private server's WOD models.
