### ISSUE TITLE
Enginnering Skill Up Bug Mechs @ Stormpeak(maybe all mechs)

### ISSUE THREAD

**Issue by kiddy07** [SunwellTracker/issues#1388]
Decription:  Mechs in Stormpeak doesn´t give Skill Ups for the Profession

How it works:  as you can see down under at the screenshots, the mechs where i am doesn´t give skill ups for my Profession, First Screenshot show the color of Skill up by using my Profession and Second the bug after.

How it should work:  The Mechs should give Skill Ups for Engineering, but they doesn´t give any Point.
I had kill now over 100 Mechs there but no Skill up(maybe all Mechs gives no skill ups here?)
and thats a bug, even so that often the mobs don´t give loot after use engineering on them.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_051018_234817](https://user-images.githubusercontent.com/39195699/39931953-26a252b6-553f-11e8-9521-2fd3f1931c48.jpg) then i used engineering because its yellow(skill up) but 
![wowscrnshot_051018_234821](https://user-images.githubusercontent.com/39195699/39931993-3c5db10e-553f-11e8-924d-43aa198a1a63.jpg)

**Comment by Cwiercpasiec** [comment]
Any proof that mob salvaging should be able to give a skill up? I've never seen anyone saying you could grind engineering by salvaging mobs and I've read a lot of engi guides.

**Comment by Cwiercpasiec** [comment]
The only way to level up skinning is to skin the mobs, which is not the case for any other proffesion. For example you can't (or at least shouldn't) get a skill up for mining a mob.
http://wowwiki.wikia.com/wiki/Mob_mining
" Unfortunately, mining cannot be leveled in this fashion."

Of course, it's wowwiki, not 100% reliable source, but it really concerns me, that I've never seen anything about leveling engineering by salvaging mechanicals. To be honest I don't believe, that if it was possible, noone would mention it in any guide (and I read lots of them, the cheapest ways, the fastest ways etc.).

**Comment by Azathothh** [comment]
It's not a bug - you shouldn't be able to level up engineering by salvaging mobs
