### ISSUE TITLE
[Mount Hyjal] Archimonde kills the raid at the end.

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1390]
Decription: 
Archimonde kills the raid at the end.

How it works: 
Archimonde kills the raid at the end.

How it should work: 
Raid should get "Protection of Elune" at 9%

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=Zkw8qbEV9LM

**Comment by Afgann** [comment]
@ivanlink It means that the issue was fixed, you can stop with your rudeness.

**Comment by ivanlink** [comment]
I'm sorry if I sound rude, but that was not my intention.
