### ISSUE TITLE
Feral Season 5 gloves “Savage Gladiator's Dragonhide Gloves” are bugged

### ISSUE THREAD

**Issue by jimmyjazz139** [SunwellTracker/issues#1391]
Decription: equip bonus is not working

How it works: Maim still cost 42 energy after equip this gloves

How it should work: Maim should cost 27 energy if you have the gloves on

Source (you should point out proofs of your report, please give us some source):  
![bug](https://user-images.githubusercontent.com/39209001/39953576-745e9418-55e1-11e8-8128-bb8795be788b.png)

**Comment by Dootz** [comment]
Without:
![wowscrnshot_051218_105746](https://user-images.githubusercontent.com/25490436/39955680-9930db60-55d3-11e8-9040-6e3f71bfe5b1.jpg)

With item equipped
![wowscrnshot_051218_105755](https://user-images.githubusercontent.com/25490436/39955682-a870b55a-55d3-11e8-9022-3be61333beb4.jpg)
:
