### ISSUE TITLE
Regarding Netherwing Egg

### ISSUE THREAD

**Issue by Elefant0n** [SunwellTracker/issues#1394]
Decription: Lacking alot of spawns from Netherwing Egg.

How it works: Currently there is only 9 spawn points, Of my knowledge and 6h of farming them.

How it should work: According to Wowhead, http://www.wowhead.com/quest=11050/accepting-all-eggs#comments:id=790488
There should be atleast 24 of them.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11050/accepting-all-eggs#comments:id=790488
http://www.wowhead.com/quest=11050/accepting-all-eggs#comments:id=1056091

**Comment by Dootz** [comment]
some spawns where added in mine
