### ISSUE TITLE
[Shaman] Earth's Grasp don't have Diminishing returns in PvP

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#1395]
Decription: 
Root form Shaman Earth's Grasp dont have Diminishing returns.

How it works: 
Earth's Grasp Root have no DR at all.

How it should work: 
Earth's Grasp Root should have DR with Controlled Root.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by Dootz** [comment]
http://wowwiki.wikia.com/index.php?title=Diminishing_returns&diff=2341644&oldid=2341221
https://github.com/TrinityCore/TrinityCore/issues/2347

>  azuross commented on 10 Aug 2012 
> Proof that shows that the DR on earths grasp should not excist.
> 
> -The Addon to show deminishing returns ( DR tracker ) doesnt display the controlled root DR, since it shouldnt excist in the first place.
> -http://eu.battle.net/wow/en/forum/topic/2313884492
> -http://us.battle.net/wow/en/forum/topic/2743728664
> -On arena tournament it does not have DR either ( also private server, but still quite relyable )
> 
> Found a movie finally from some WoW warrrior geek from retail.
> 
> 4minute 33 seconds: Swifty gets rooted. 
> 4 minute 44 seconds: Swifty gets rooted again. Clearly visable that in the 4 minute 44 seconds screen that de root lasts for the entire duration.
> 
> There is 11 seconds inbetween both roots. This means that no DR of 15 seconds can excist on the shamans earths grasp


> 4minute 33 seconds: Swifty gets rooted.
> 4 minute 44 seconds: Swifty gets rooted again. Clearly visable that in the 4 minute 44 seconds screen that de root lasts for the entire duration.
> 
> There is 11 seconds inbetween both roots. This means that no DR of 15 seconds can excist on the shaman earths grasp.
> 
> http://www.youtube.com/watch?v=sgONe6VzeKM
