### ISSUE TITLE
Neyal - Druid - [Old Crafty] Achievement

### ISSUE THREAD

**Issue by Neyala** [SunwellTracker/issues#1396]
Decription: I fished up Old Crafty, but didnt loot it by accident.

How it works:  Shouldn't i still be able to get the achievement.

How it should work: Should be able to get achievement by fishing it up and not by looting it aswell?

**Comment by Dootz** [comment]
http://www.wowhead.com/achievement=1836/old-crafty#comments:id=435516
By Dimish (6,233 – 2·19·47) on 2008/11/08 (Patch 3.0.3)
> Step 3
> We're almost done. Now, go to your fishing spot (Ironforge or Orgimmar in case you're after these two lovely's), and bid your Fishing skill to some easy to press (F for example) button. Then turn on "Auto-loot" (Remember, **you still have to press "Yes i want to loot this BoP fish"** button when you do finally get this lovely piece of epicness) from WoW's options
