### ISSUE TITLE
[Paladin] Consecration

### ISSUE THREAD

**Issue by ddhfd** [SunwellTracker/issues#1397]
Decription: 
Spell Consecration http://db.darkwizard.pl/?spell=48819

How it works: 
When paladin puts it on the ground the player who steps into it doesn't trigger combat on the paladin who placed that consecration.

How it should work: 
As soon as someone steps into consecration it should trigger the combat on paladin. Also even if target is shielded (or has another kind of absorb) running over the consecration should trigger combat on consecration's owner.

**Comment by gabbat** [comment]
running on the consecration should not combat flag you - only if the consecration ticks at that exact same instant. between the pulses you can step on it without getting into combat
