### ISSUE TITLE
[Paladin] Hand of Reckoning doenst destroy totems

### ISSUE THREAD

**Issue by ddhfd** [SunwellTracker/issues#1399]
Decription: 
Spell Hand of Reckoning http://db.darkwizard.pl/?spell=62124

How it works: 
When you use Hand of Reckoning on a Grounding totem ( Earthbind totem, Tremor totem etc) it doent get destroyed. You just get the "Immune" message.

How it should work: 
You should be able to kill totems with Hand of Reckoning if there is no absorb totem being set (Stoneclaw totem http://db.darkwizard.pl/?spell=58582). Basically totems have no hp so they can be destroyed with paladin's taunt cos it does holy dmg.

**Comment by Cwiercpasiec** [comment]
You get immune message, cause totems are immune to taunts. Hand of reckoning does damage only on targets that are tauntable and are not currently targeting you.
