### ISSUE TITLE
[Profession] Jewelcrafting: Icy Prism

### ISSUE THREAD

**Issue by mondegoftw** [SunwellTracker/issues#140]
Decription: The Icy Prism recipe seems not to register Frozen Orbs.

How it works: Currently trying to make the Icy Prism recipe will return the message "Missing reagent: Frozen Orb" even when Frozen Orbs are present in inventory. Might be true for every Frozen Orb recipe - I don't know - but it definitely is for this recipe.

How it should work: The recipe should be posible to make.

Source (you should point out proofs of your report, please give us some source): N/A

**Comment by mondegoftw** [comment]
Any updates on this? Pretty annoying to race thruogh leveling JC to then discover that the arguably most important craft is broken.

Frozen orbs are confirmed to work with other recipes (a tailoring one at least), so this issue seems to be specific to Icy Prism.

**Comment by mondegoftw** [comment]
It only requires one of each gem, so that's fine.

It's possible that it currently requires 3 Frozen Orbs though, even though the tooltip says just 1. Either way, it still doesn't work.

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/140
