### ISSUE TITLE
[Hunter] Pet and mouseover macro

### ISSUE THREAD

**Issue by Homerjayx** [SunwellTracker/issues#1401]
Decription: 
Using mouseover or focus macros for a hunter's pet or its abilities doesn't work properly

How it works: 
Currently mouseover attack macros don't work when the pet is already on a specific target. In that case you can't tell it to attack a different target via mouseover macro. You first have to press petpassive so it gets off its current target and then you can use the mouseover macro again.

How it should work: 
The hunter shouldn't have to withdraw the pet from its current target for mouseover macros to work.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
https://youtu.be/9i4Ks-we198

Works just fine for me, could be your UIs messing stuff up, leaving this open for couple of more days unless some more information pops up ;p

**Comment by Akha72** [comment]
Seems as if there was some stealth-fix or it was connected with other issue because as for now it works fine.

**Comment by Riztazz** [comment]
alright, closing then
