### ISSUE TITLE
[Quest] The Soul Cannon of Reth'hedron (Netherwing reputation)

### ISSUE THREAD

**Issue by raddil** [SunwellTracker/issues#1402]
Decription: 
Quest [The Soul Cannon of Reth'hedron](http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron) is impossible to complete. Its impossible to get [Flawless Arcane Essence](http://www.wowhead.com/item=32822/flawless-arcane-essence). [Sar'this](http://www.wowhead.com/npc=23093/sarthis) should summon some elementals, but this NPC is unable to speak with us.

I tried do it after restarting server but it is still not working.

How it works: 
[Sar'this](http://www.wowhead.com/npc=23093/sarthis) is unspeakable NPC

How it should work: 
[Sar'this](http://www.wowhead.com/npc=23093/sarthis) should be able to speak with us.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron
http://www.wowhead.com/item=32822/flawless-arcane-essence
http://www.wowhead.com/npc=23093/sarthis
https://www.youtube.com/watch?v=OmVPTSE6eJ4

**Comment by raddil** [comment]
I don't know if you done somethink but already i done it so its working :)

**Comment by Dootz** [comment]
fixed, will reset correctly from now on.

**Comment by neverson42** [comment]
@Dootz I'm having this issue right now on Frosthold. Was this fix ever implemented on that realm?
