### ISSUE TITLE
[Quest]The Lost Pages

### ISSUE THREAD

**Issue by pre-man** [SunwellTracker/issues#1403]
Decription: grając postacią alliance w Ashenvale dorobiłem się chyba 4 różnych kartek z questu The Lost Pages

How it works: Elementy questu, czyli Shredder Operating Manual - Page X wypadają w locie dla Ally

How it should work: Quest wyłącznie dla Hordy więc raczej elementy nie powinny być dostępne dla graczy alliance, nie jestem znawcą więc mogę się mylić.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=6504/the-lost-pages

**Comment by Dootz** [comment]
http://www.wowhead.com/quest=6504/the-lost-pages#comments:id=995170
> By Bagrid (109 – 0) on 2010/03/11 (Patch 3.3.2)
> I got all the pages with Night Elf while exping in ashenvale, it is usually dropped by humanoids and it is really easy to get those. However i am afraid of it is only horde quest and well i really dunno why.
