### ISSUE TITLE
[Quest] Redemption

### ISSUE THREAD

**Issue by Porleo** [SunwellTracker/issues#1404]
Decription:  The Neutral Quest "Redemption" from Tirion Fordring in the Eastern Plaguelands, isn't working properly. I did multiple reloggs, disabled all Addons and abandoned / accepted the quest multiple times.

, How it works: 
After accepting the Quest, the Quest Interface of Tirion is not prompting the Speechbubble to advance in the Quest.

How it should work: 
After accepting the Quest, the Quest Interface of Tirion should prompt the Speechbubble " I am ready to hear your tale, Tirion." to advance in the Quest.

Source (you should point out proofs of your report, please give us some source):  
Sunwell Database: https://db.darkwizard.pl/?quest=5742
wowwika Database: http://wowwiki.wikia.com/wiki/Quest:Redemption_(Neutral) Exact discription on how you advance in this Quest with Tirion.

**Comment by Dootz** [comment]
> Sit and listen to my story, <race>. 

You need to "/sit" to listen to his story :D

**Comment by Porleo** [comment]
Oh wow, this is embarrassing. Thanks for the reply though.
