### ISSUE TITLE
Westfall - Duskwood Chest

### ISSUE THREAD

**Issue by Jaladre** [SunwellTracker/issues#1405]
Decription: Skill Pick Lock should be usable manually (not right click)  on Duskwood Chest even without quest.

How it works: It doesn't.

How it should work: Use Pick Lock skill, click on the chest, open it and level up lockpicking.

Source (you should point out proofs of your report, please give us some source): 

http://www.wow-pro.com/class_guides/lockpicking_guide
http://tarsitreiver.blogspot.com/2010/01/world-of-warcraft-lockpicking-guide-1.html
https://www.freakz.ro/forum/WOTLK-Lockpicking-Guide-t79721.html

My own experience.
All Lockpicking guides on the internet.

Regards,
IGN: Jaladre

**Comment by Dootz** [comment]
http://www.wowhead.com/object=123214/duskwood-chest#comments
> For Rogues still looking to level lockpicking with this chest:
> 
> It is a little more complicated but possible.
> 1. Make sure you pick up the first part of the quest
> 2. Then get the next part in the chain
> 3. Right click on the chest to lock pick it and loot the journal
> 4. You won't be able to re-pick the chest if you have the journal in your inventory, so destroy it
> 5. repeat steps 3 and 4 until 175 lock picking
> 
> Good luck!

And there are more comments saying that you need to be on a quest to open it.
