### ISSUE TITLE
[Death Knight] Glyph of the Ghoul is not working properly

### ISSUE THREAD

**Issue by Whompp** [SunwellTracker/issues#1406]
Decription: Glyph of the ghoul is not stacking with talents properly and not giving the ghoul the proper stats it should have when used.

How it works: Ghoul is not getting 100% of the str and stam of the Death Knight

How it should work:  Ghould should be getting 100% of str and stam of the Death Knight

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
No source attached.
