### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by sierota** [SunwellTracker/issues#1407]
Decription:  Bought pve mace for druil feral and can't equip

How it works: 
Bought pve mace for druid feral and cant equip, is it some kind of error or I'm mistaken?

How it should work: 
if in description of 
**"Repurposed Lava Dredger"**
States that's an item is dedicated for an feral druid, shouldn't i be able to equip an item for my character who is an feral druid?

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, you need to have Mace weapon skill to wield it. You can learn it from weapon trainers in major cities.
