### ISSUE TITLE
[Warrior] Charge

### ISSUE THREAD

**Issue by Terryfic1** [SunwellTracker/issues#1408]
Decription: 
Warrior charge stuns the enemy for 2 seconds also they can charge at people who are in loss. I was at dala arena and they charge at me even though i stand behind the boxes, they just charge run around every box and stun you for 2 sec

How it works: Warris charge you even though their target is at loss and charge stun lasts 2 sec

How it should work: 
They should not be able to charge around objects and charge stun should last 1 sec.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
https://db.darkwizard.pl/?spell=11578
Stun should last 1.5 second and that's how much exactly it lasts.

**Comment by Azathothh** [comment]
Not a bug/lack of proofs.
