### ISSUE TITLE
[item] Dragon's Call not working. Pet is not attacking

### ISSUE THREAD

**Issue by gabbat** [SunwellTracker/issues#1415]
Decription: The very rare weapon from the sunkel temple endboss does procc the dragon, but the dragon is just on idle and does not fight at all

How it works: Dragons spawns but does not fight

How it should work: Dragon should shoot green slime bolts at enemies

Source (you should point out proofs of your report, please give us some source): 

![image](https://user-images.githubusercontent.com/38278426/40136314-d6a89678-5947-11e8-9124-2bd3fd899501.png)
there are plenty of comments on wowhead on how the dragon should shoot bolts

**Comment by Dootz** [comment]
fixed
