### ISSUE TITLE
Caster mobs

### ISSUE THREAD

**Issue by 510Kyle** [SunwellTracker/issues#1417]
Decription: 
Blood elf casters aren't moving like they're supposed to in the dranei starter zone.

How it works: 
Wind shear the Sunhawk Reclaimer's while they are casting Fireball and they just stand there for 2 seconds and begin casting again. (edit) they will mele you if you are in range, but they are suppose to run towards you.

How it should work: 
When you kick a casting mob, it is suppose to run towards you and begin meleeing until it can cast again.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed
