### ISSUE TITLE
[Druid] Shred is dodged, parried, and blocked.

### ISSUE THREAD

**Issue by kittydruid** [SunwellTracker/issues#142]
Description: The druid spell that requires you to be behind the enemy, shred, is being dodged, parried, and blocked.

How it works: Shred is being dodged, parried, and blocked. 

How it should work: Shred has a positional requirement and obviously could not be dodged, parried, or blocked on live. It should only be able to hit, hit critically, and miss.

Source: Any video on youtube of druids around that time period will show you shred never is dodged, parried, or blocked. Only missed if not hit capped. https://www.youtube.com/watch?v=sZtLkchL178

Proof: https://i.imgur.com/PkfhE87.jpg

Spell: http://db.darkwizard.pl/?spell=48572

To reproduce it just shred some targets (most easily done in a dungeon where the mobs are facing away because of the tank and you can get behind easy) and it will occur. Thank you for your time, this spell is what the feral rotation revolves around.

**Comment by Semper-Numquam** [comment]
Attacks from behind can be dodged but not blocked or parried. The reason endgame druids aren't dodged as much is due to expertise.

**Comment by kittydruid** [comment]
@Semper-Numquam It was never like this on live, the arena tournament realm, and warmane. The wrathful pvp gear has no expertise on it and if you watch videos of full s8 gear their shreds are never dodged, parried, or blocked. Even with evasion and deterrence up, the entire point of the spell having a positional requirement is this reason. 
Unless NPC's can dodge and parry from behind and players cannot. Then this would make more sense. I assume this is the case, just want to confirm that then.

**Comment by Semper-Numquam** [comment]
http://wowwiki.wikia.com/wiki/Dodge

"Players can only dodge attacks if they are facing their opponent, however a mob can dodge attacks that are from behind."

I failed to include that I was refering to NPCs. Yes, players cannot dodge, block or parry from behind and NPCs can't parry or block, **but they can dodge.**

**Comment by kittydruid** [comment]
@Semper-Numquam How foolish of me to forget NPC and player dodge/parry is different. I will close this now. Thank you for pointing out my error.
