### ISSUE TITLE
[Item - Small Velvet Bag] Container Gives No Items / is Empty

### ISSUE THREAD

**Issue by KoaditheKingslayer** [SunwellTracker/issues#1420]
Decription: The Small Velvet Bag, awarded from the quest "Gem Perfection" as a reward for completion is supposed to contain a random "perfect cut" gem from a table of six. However, when I used the item, there was nothing in it. It disappeared from my inventory, but I didn't receive any of the gems that it's supposed to have within. 

How it works: I used the item, and it gave me nothing.

How it should work: You use the item, and it should award you one of 6 items, as listed below. 
Perfect Balanced Shadow Crystal (16.9%)
Perfect Glowing Shadow Crystal (16.9%)
Perfect Forceful Dark Jade (17.7%)
Perfect Jagged Dark Jade (16.3%)
Perfect Inscribed Huge Citrine (13%)
Perfect Reckless Huge Citrine (19.3%)

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?item=41888#contains lists what should come out of the item.

**Comment by Dootz** [comment]
will be fixed with next server update
