### ISSUE TITLE
[NPC] Some broken Npc

### ISSUE THREAD

**Issue by LookinGood** [SunwellTracker/issues#1421]
Decription: 
These NPC don't use their spells:
https://db.darkwizard.pl/?npc=1259
https://db.darkwizard.pl/?npc=15407
https://db.darkwizard.pl/?npc=15649
https://db.darkwizard.pl/?npc=15650
https://db.darkwizard.pl/?npc=15937
https://db.darkwizard.pl/?npc=16343
https://db.darkwizard.pl/?npc=3249
https://db.darkwizard.pl/?npc=712
https://db.darkwizard.pl/?npc=1038
https://db.darkwizard.pl/?npc=1057
https://db.darkwizard.pl/?npc=2434
https://db.darkwizard.pl/?npc=1037
https://db.darkwizard.pl/?npc=937
https://db.darkwizard.pl/?npc=3974
https://db.darkwizard.pl/?npc=9176
https://db.darkwizard.pl/?npc=12474
https://db.darkwizard.pl/?npc=12476
https://db.darkwizard.pl/?npc=12475
https://db.darkwizard.pl/?npc=3265
https://db.darkwizard.pl/?npc=4024
https://db.darkwizard.pl/?npc=4026
https://db.darkwizard.pl/?npc=4339
http://www.wowhead.com/npc=9037
http://www.wowhead.com/npc=23714
http://www.wowhead.com/npc=23592
http://www.wowhead.com/npc=23594
http://www.wowhead.com/npc=23881
How it works: 

How it should work: 
They are should use all spells.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Will be fixed at next server update.
