### ISSUE TITLE
[NPC]/[Loot] Karazhan, Attumen the Huntsman

### ISSUE THREAD

**Issue by ntjoking** [SunwellTracker/issues#1422]
Decription: 
Yeah, two times in a row this guy hasn't dropped any loot.

How it works:
You kill the boss and you don't get any loot.

How it should work: 
You kill the boss and it drops loot :))

Source (you should point out proofs of your report, please give us some source):  Well, i don't have a recording of it and the screenshot won't do much, but here it is: https://i.imgur.com/Cr9DoKx.jpg
I will record it next time if needed. Although it should be simple, the boss hasn't dropped ANY loot for the last 2 times i've done it. 

--EDIT, GM told me that apparently we're killing it "too fast". Nonetheless it should drop loot whether you spend 1 second or 1 hour doing the boss.

**Comment by Dootz** [comment]
fixed, I'm sorry for any inconvenience caused.
