### ISSUE TITLE
[Rogue][Spell] - Stealth

### ISSUE THREAD

**Issue by AJ7766** [SunwellTracker/issues#1428]
Decription: Stealth breaks from stepping on a AoE spell like [Death and Decay][Consecration] when the rogues has [Power Word: Shield] on.

How it works: Should'nt break stealth with AoE dmg like that with shield on, should just be entering combat. Only Direct AoE damage like [Rain of Fire] or [Blizzard] should break stealth even with shield on.

How it should work: Not break stealth when the rogue is shielded.

Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/spell=17/power-word-shield#screenshots , pretty much every shield should absorb a spell on the ground and not break stealth. http://www.arenajunkies.com/topic/163617-power-word-shield-and-stealth/ This bug is fixed on Warmane, wowcircle

**Comment by ujellyx** [comment]
confirm

**Comment by ujellyx** [comment]
Bump.
