### ISSUE TITLE
QUEST Fresh Remounts

### ISSUE THREAD

**Issue by Sjadovski** [SunwellTracker/issues#143]
Decription: 
You kill Onslaugh Knights, who will drop Onslaught Riding Crop, which normally allows you to mount their warhorses, but instead you get a buff for 3 minutes that does nothing, and you cannot get credit for returning horses.

How it works: 
You kill a knight, and their horses always turns "Friendly", but from there you cant do anything. If you use the Riding Crop the knights drop, it simply does nothing but put a useless buff on you.

How it should work: 
You kill a knight, you use the crop on the horse, you mount them and return them to the nearby city Venomspite where you get credit for the quest.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=6nBHsDmjKAM

**Comment by Kokaina** [comment]
Duplicate.
