### ISSUE TITLE
[item=42992][Discerning Eye of the Beast] Not Working At All

### ISSUE THREAD

**Issue by slopllama** [SunwellTracker/issues#1432]
Decription: [item=42992][Discerning Eye of the Beast]  % mana not working

How it works: Only gives spell power.

How it should work: Increase spell power based on level. On Kill of enemy giving Honor or experience the player should receive 2% mana back.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=42992/discerning-eye-of-the-beast

**Comment by Akha72** [comment]
Works fine for me.

**Comment by slopllama** [comment]
Yep, after I logged out for the night it works now.... Cool must have been a glitch. Sorry for the waste of time.
