### ISSUE TITLE
Xizzer Fizzbolt  doesn't sell engineering schematics

### ISSUE THREAD

**Issue by alexnxs** [SunwellTracker/issues#1434]
Decription: 
The NPC Xizzer Fizzbolt isn't properly spawning the engineering schematics he should be selling, even after killing him. The schematics he should be selling are: 

Schematic: Delicate Arcanite Converter
Schematic: Powerful Seaforium Charge
Schematic: Masterwork Target Dummy
Schematic: Gyrofreeze Ice Reflector

How it works: 

They don't spawn at all.

How it should work: 

They should respawn in his inventory occasionally or after killing him.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Hello i am pretty sure he is selling them but its not showing in there because they are out of stock :)
you need to wait for a respawn. maybe we can lower the timers 
dootz can decide

**Comment by Dootz** [comment]
Restock time on his limited items is around 2,5h.
