### ISSUE TITLE
Swimming display bug

### ISSUE THREAD

**Issue by psychazia** [SunwellTracker/issues#1435]
![wowscrnshot_052118_013551](https://user-images.githubusercontent.com/37190258/40285038-8a9e3aaa-5c97-11e8-84a5-28549944b34a.jpg)
![wowscrnshot_052118_013637](https://user-images.githubusercontent.com/37190258/40285039-8ad9e4ec-5c97-11e8-844a-559ea1ce5a89.jpg)
![wowscrnshot_052118_013642](https://user-images.githubusercontent.com/37190258/40285041-8afcef14-5c97-11e8-8314-88a78b182829.jpg)
![wowscrnshot_052118_013703](https://user-images.githubusercontent.com/37190258/40285042-8b21dd24-5c97-11e8-9b91-9af974162d21.jpg)

Decription: 
As you can see GM explaining to me, there is a display bug, when you jump in water mounted, you are drowning, your breathing bar is just downing whereas you are swiming at the surface..
If you dismount your breathing bar goes up, but it's displaying your character swimming underwater

How it works: 
look on screenshots for detail

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2422
