### ISSUE TITLE
Dragonmaw Race: Captain Skyshatter

### ISSUE THREAD

**Issue by skrroo** [SunwellTracker/issues#1437]

**Comment by Dootz** [comment]
> get the achieve but its not working i try it many time
Hi, what do you mean by that? You can't turn-in quest to quest giver? Or it's something else? I'm confused.

**Comment by skrroo** [comment]
i watch a  how the achieve work in the youtube  whan  the player finsh the quest   [70] [Dragonmaw Race: Captain Skyshatter] he got has achieve but i have finshed the quest 3 time so far and its not working and the

**Comment by Dootz** [comment]
will be fixed with next server update
