### ISSUE TITLE
Earthern power

### ISSUE THREAD

**Issue by Chestdaygodtier** [SunwellTracker/issues#1439]
Decription: 
Your earthbind Totem's Puleses have a 2/2 100% chance to also remove all snare effects from you and nearby friendly targets

How it works: DOESNT

How it should work: 
FREEDOM

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
On which spells it doesn't work for you? I've tested it with Chains of Ice and Piercing Howl and it works fine.
