### ISSUE TITLE
QUEST No Mercy for the Captured

### ISSUE THREAD

**Issue by Sjadovski** [SunwellTracker/issues#144]
Decription: 
You talk with NPCs in a cage which would normally allow you to kill them, but they get stuck.

How it works: 
You talk with them while they are in a cage, but they get stuck in their cage so they are not in line of sight of attacks/spells/aoe/etc.

How it should work: 
You talk with them while they are in a cage, and you can then kill them while they are inside the cage without any problem with line of sight.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=bq-p6ih3E2w

**Comment by Sjadovski** [comment]
Yes I saw some other guy complete it next to me aswell, but I couldnt seem to get them to work whatsoever. Even got a GM to come and help, but he couldnt get it to work either

**Comment by Dootz** [comment]
Will be fixed with next server update
