### ISSUE TITLE
[Totem of Wrath] & [Demonic Pact] Stacking

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1441]
Decription: 
[Totem of Wrath] & [Demonic Pact] buffs stack

How it works: 
If [Demonic Pact] is brought under 280 SP value it will stack with [Totem of Wrath]

How it should work: 
It should never stack and only pick the highest one.

Source (you should point out proofs of your report, please give us some source): 
Honestly don't have a concrete source, but it's basic WoW buff mechanics IMO.
Blessing of Might/Battle Shout don't stack, Blessing of Wisdom/Mana Spring don't stack, etc.

**Comment by Hahecz** [comment]
Discussion on wowhead states that those effects don't stack. 
http://www.wowhead.com/forums&topic=132387/demonic-pact-help-please-and-thank-you#p1611419
