### ISSUE TITLE
[Quest - The Refiner's Fire]

### ISSUE THREAD

**Issue by Lachyon** [SunwellTracker/issues#1442]
Decription: Furious Spark stops being collected when reaching 5, instead of the 10 needed for the quest.

How it works: When reaching a total of 5 Furious Sparks in your inventory, you will not be able to pick more, showing the message: You can't carry anymore of those items.

How it should work: You should be able to pick 10 Furious Sparks in order to finish the quest.

Source: 
[Pic 1](https://i.imgur.com/wjK7WTF.jpg?2)
[Pic 2](https://i.imgur.com/tkuHEG4.jpg?1)

**Comment by Dootz** [comment]
Hi, it's probably because you already have 5 of them in bank ( Pic 2 ). So you have 5 in inventory + 5 in bank = 10. That's why you can't pick up more.

**Comment by Lachyon** [comment]
You are absolutely right. Didn't crossed my mind that i could bank quest items.
