### ISSUE TITLE
[Alterac Valley Quests] Stormpike / Frostwolf Insignia Chain

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#1444]
Decription: Stormpike Insignia (https://db.darkwizard.pl/?item=17904) and (probably, have no way to check that) Frostwolf Insignia (https://db.darkwizard.pl/?item=17909) can be obtained without rising player's standing with Stormpike Guard or Frostwolf Clan respectively.

How it works: Right now player can obtain Stormpike Insignia Rank 1 (https://db.darkwizard.pl/?item=17691) from quest Proving Grounds (https://db.darkwizard.pl/?quest=7162) at neutral, which is fine but it can be immediately followed up with Rise and Be Recognized (https://db.darkwizard.pl/?quest=7168), Honored Amongst the Guard (https://db.darkwizard.pl/?quest=7169), Earned Reverence (https://db.darkwizard.pl/?quest=7170), Legendary Heroes (https://db.darkwizard.pl/?quest=7171) and The Eye of Command (https://db.darkwizard.pl/?quest=7172), all of them still at neutral which is wrong, because you are not supposed to complete this chain until you max your standing with AV faction.

How it should work: Rise and Be Recognized should be obtainable at Friendly, Honored Amongst the Guard at Honored, Earned Reverence at Revered, Legendary Heroes at Exalted and The Eye of Command at 999/1000 Exalted (links in a paragraph above).

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=17904/stormpike-insignia-rank-6

1.12.0
10 second cast that recalls you to Dun Baldar.

There are 6 Stormpike Insignias:

Rank 1: Quest - Can be done at Neutral
Rank 2: Friendly (3000 rep)
Rank 3: Honored (6000 rep)
Rank 4: Revered (9000 rep)
Rank 5: Exalted (21000 rep)
Rank 6: Full Exalted (1000 rep)

Horde equivalents of Alliance chain:
1. Neutral (works fine) - (https://db.darkwizard.pl/?quest=7161)
2. Friendly - (https://db.darkwizard.pl/?quest=7163)
3. Honored - (https://db.darkwizard.pl/?quest=7164)
4. Revered - (https://db.darkwizard.pl/?quest=7165)
5. Exalted - (https://db.darkwizard.pl/?quest=7166)
6. Exalted 999/1k - (https://db.darkwizard.pl/?quest=7167)

**Comment by Dootz** [comment]
will be fixed with next server update
