### ISSUE TITLE
Time-Lost Proto-Drake Phasing

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#1445]
This rare is phasing in and out of view as it pats around stormpeaks. It should be viewable by all in the zone no matter what stage of quests they are in. This is really bad if you camping a spawn point that you dont know is phased out.

https://db.darkwizard.pl/?npc=32153

**Comment by TheRealYasri** [comment]
Seems dirkee is another one, a guildy can see him but I can not over by thunderfall in stormpeak. Also the spawn point over the is wrong going by the wowhead one.
https://db.darkwizard.pl/?npc=32500

**Comment by TheRealYasri** [comment]
The few rares I got remaining are in stormpeaks and icecrown, both with heavy phasing, might want to give those rares a once over along with the other northrend ones.

**Comment by TheRealYasri** [comment]
On dirkee I got hold of a friends account to use his druid, with no quests started in stormpeak. I had my paladin who could not see the rare stand right by the rare as the druid dot'd and root spammed to kill it, my paladin got credit and could even roll on the blue that dropped.

**Comment by Dootz** [comment]
there's no source in this report. Please add some kind of proof that they should be visible in other than the basic phase.
