### ISSUE TITLE
Horde PvP Medallion of the Horde

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#1447]
Decription: The deadly vendors are not selling the original 84 resilience trinket. (Alliance dead;y vendor has the trinket).
https://wotlk.evowow.com/?item=42122

How it works: There is no Medallion of the Horde.

How it should work:  There should be the trinket for honor just like alliance vendors.

Source (you should point out proofs of your report, please give us some source): Check pvp vendors at orgrammar

**Comment by Dootz** [comment]
fixed
