### ISSUE TITLE
Tormenting The Softnuckles quest

### ISSUE THREAD

**Issue by Moistcookie** [SunwellTracker/issues#145]
Decription: There's a quest in Sholazar Basin called "Tormenting The Softknuckles". It requires you to kill a mob named "Hardknuckle Matriarch".

How it works: Currently, the mob that is needed for the quest is invisible at 67.7,74.3. If you stand there, you take damage, but there's nothing around you. He also does an emote saying he is enraged, but is still invisible. If you use the quest item (Softknuckle Poker) on the baby garillas, it does nothing to fix it.

How it should work: You use a quest item called "Softknuckle Poker" on the baby gorillas, and after a few pokes, he's supposed to come out and attack you. Then you kill him and it's over.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Duplicate.
