### ISSUE TITLE
pala's [hands of sacrifice] or [divine guardian] cant broken dk's hungering cold

### ISSUE THREAD

**Issue by uilosss** [SunwellTracker/issues#1450]
my english poor, who's good at pvp and english good plz help me explain this bug  ;/thanks a lot!

frost dk'【 hungering cold】, any damage other than diseases will break the ice,right ?

when i play 2v2 with a warr,we met 2teams,enemy  are both resto dru and frost dk.when i guess dk will use【 hungering cold】, i cast 【hands of sacrifice】to warr before he use hungering cold..,.but it didnt broken [hungering cold].,all the time.my warr's hp from 100% to 20%,i still in the 【 hungering cold】.

if enemy was priest or shaman,i can understand why sacrifice didnt work.but dru cant dispel enemy's buff.

anyway,i think maybe its a fortuitous bug.so next time i try to broken【 hungering cold】 again.

4times ,i have used 【hands of sacrifice】 or 【divine guardian】before dk use【 hungering cold】.all doenst work for break .everytime doesnt work,its clearly a bug.

i have print screen,my target isnt warr,but you can see from my sikll's cold down time.

plz test it.even i play bad,i still like play pvp,bugs makes me sad.plz help  ;/

![12345](https://user-images.githubusercontent.com/39649379/40576476-d982a6d8-6129-11e8-89b6-70dd5caae6de.png)

![12346](https://user-images.githubusercontent.com/39649379/40576484-ff34de5a-6129-11e8-8ac9-b604a29dc2cd.png)

**Comment by Azathothh** [comment]
Fixed, will be updated soon.

**Comment by Kokaina** [comment]
Fixed.
