### ISSUE TITLE
Blackrock Spire bug (eggs keep respawning)

### ISSUE THREAD

**Issue by Craoxsen** [SunwellTracker/issues#1452]
Decription: 
Hello, I was boosting some friends in blackrockspire and noticed a bug that the eggs (https://gyazo.com/345fdaf7d3b9aef63a568ba7eada8fc9) that spawn Rookery Whelp's kept on respawning after being popped and kept on yielding exp. So we could technically stay and grind in the room until my friends out leveled the Whelplings.

How it works: 
The eggs keep respawning after being popped.

How it should work: 
Eggs should not respawn after being popped.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
