### ISSUE TITLE
[Ulduar] Charged Sphere (Storm Tempered Keeper)

### ISSUE THREAD

**Issue by Kittykatreporter** [SunwellTracker/issues#1453]
Decription: 
The two twin adds Storm Tempered Keeper release charged sphere that is heading towards the other twin.

How it works: 
Once sphere reaches second adds, it does nothing.

How it should work: 

Once sphere reaches secon add, it should enrage him and deal aoe damage.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=33715/charged-sphere#comments

These spawn while fighting Storm Tempered Keeper's around the Observation Ring in UlduarThese Charged spheres need to be snared (if you want to) and killed before they reach the other Storm Keeper. or else its heavy raid damage on you and your raid.Add Reply
--
By Mike (25,357 – 6·38·182) on 2009/07/01 (Patch 3.1.3) |   |

**Comment by Kokaina** [comment]
Just checked. If sphere touches Storm Tempered Keeper he gains Supercharged buff increasing damage by 60% and adds nature damage to melee swing. Looks fine for me ;o

**Comment by Kittykatreporter** [comment]
Double checked, indeed it gains buff. My bad, sorry. I just remember that this trash was basically wiping raids once the sphere hit the twin, but it was long ago and perhaps thats just 3.3.5a thingy :P.  sphere didn't dissapear though, will double  check this on next raid and make sure.

 ""Increases the target's damage done by 60% and causes the target's attacks to cause powerful electrical surges, **sacrificing the caster in the process**
