### ISSUE TITLE
XT-002 Consuming Scrap Bots from a distance

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#1457]
Decription:  Scrap Bots VERY far out are being 'consumed' by XT before they are even in range of the range dps.

How it works: 
https://www.twitch.tv/videos/265941814?t=00h36m48s

How it should work: All scrap bots should be much closer to XT (5-10y?) before he can interact with them.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Yep we have it reported, probably movement issue. Will fix asap.
