### ISSUE TITLE
Heroic strike "out of range"

### ISSUE THREAD

**Issue by femdead** [SunwellTracker/issues#1458]
Decription: 
Heroic strike (presumably cleave as well, haven't unlocked it yet) is only able to be queue'd while currently in melee range of your target.

How it works: 
Can queue heroic strike while in melee range, queuing HS then kiting out of melee range does not de-queue it, can not queue heroic strike while out of melee range (ie. charge -> HS or hamstring kiting a mob)

How it should work: 
Heroic strike should not have a range check on it - the limiting factor is your swing timer only, of course your melee swing is limited to melee range but you should be able to queue heroic strike beforehand.

Source (you should point out proofs of your report, please give us some source): 
From playing WoW on other servers/retail and then on Sunwell, it's instantly noticably different. You can compare the tooltip of rend ([melee range] tag) and heroic strike (doesn't have [melee range] tag) to see that this is not a feature of the ability.

**Comment by Tsaav** [comment]
I had the same issues. Glad to hear it's not just me
