### ISSUE TITLE
Death Grip on Guardian of Yogg-Saron

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#1464]
Decription: Death Grip on Guardian of Yogg-saron makes Phase 1 much easier.

How it works: They are death grippable and fly in the air to the source of the death grip.

How it should work: They should NOT be death grippable. 

Source (you should point out proofs of your report, please give us some source): https://youtu.be/kAKIdW6feFQ?t=118 - As you can see on the Guardian of Yogg-Saron that spawns, it doesn't fly when death gripped. You can see the animation of the death grip. 

Edit: https://youtu.be/VWtJL-A81u0?t=77  Another Death Grip, you can clearly see that the mob turns to attack the Death Knight and does not get the "Death Grip fly animation"

Edit2: https://youtu.be/9cgY4lREwEw?t=115 Another Death Grip from a Dreanei Male, clearly can see that the mob turns but the Death Grip does NOT work.

**Comment by Kokaina** [comment]
ve seen this conversation on discord, will investigate that. I've seen posts where ppl said they were gripable, also ur link is from jun 2010 - it was cataclysm already so im not sure if its not some priv. As I said, will be checked

**Comment by Kokaina** [comment]
![image](https://user-images.githubusercontent.com/22802214/40611462-b0151864-6276-11e8-91e5-ff6a6262901d.png)

**Comment by Chryslol** [comment]
No, it's a DK called Nygrael from Twisting Nether doing it. 
Here is his Armory-link: https://worldofwarcraft.com/en-gb/character/twisting-nether/nygrael

**Comment by Chryslol** [comment]
I added 2 more sources, the last one is insanely good and shows it perfectly. Now fix it so we can get the real version of phase 1.

**Comment by jesterlol** [comment]
Simple question you can ask yourself.
If you search for it you can rarely find anything from the time when Ulduar was active. Also not a single guide mentions the possibility to dk grab the adds. Why is that?

Simple answer: Because it wasn't a thing. It was not possible so noboy mentioned it.

**Comment by ujellyx** [comment]
Yeah they couldn't be gripped. Otherwise one would find this in the Ulduar guides on the internet.
@Kokaina 3.3.5 was released on 06/22/2010, so the video was definately before Cataclysm.
