### ISSUE TITLE
DK Death Grip - minimum range in PvP

### ISSUE THREAD

**Issue by fbpeter** [SunwellTracker/issues#1465]
Description:
**Deathknight** Spell: **Death Grip** (spell=66017) is bugged in PvP. There should be **NO minimum range** on gripping other players. 

How it works: 
In PvE Death Grip works super fine. You can grip mobs while standing in them to interrupt a cast for example. In PvP you have to run away maybe 10 yards to actually grip a player to interrupt him. The tooltip does not show any minimum range and there shouldn't be any. 

How it should work: 
You should be able to grip other players while standing in them to prevent a cast or anything similar. I played DK on retail until Ruby Sanctum very last patch and you were always able to do it like that.

Source (you should point out proofs of your report, please give us some source): 
People say that Blizzard added minimum range on **Death Grip** in 3.3.3 but they did not! http://us.battle.net/wow/en/game/patch-notes/3-3-3 
You won't find any Death Grip changes. 

Another proof is here: https://www.mmo-champion.com/threads/699292-Heroic-Lich-King-Kill-PTR-3-3-3-Build-11623?p=7401081&viewfull=1
You will see the word **Unintended**! Blizzard tested minimum range on 3.3.3 PTR but it never went live. 

On retail state 3.3.5a Death Grip had NO minimum range in PvP. Please fix it.

**Comment by sphericalsilver** [comment]
There's a lot of confusion on this but it looks like there was a minimum range in pvp.

Have a look at this post on another server: http://forum.warmane.com/showthread.php?t=383561&p=2923397&viewfull=1#post2923397

**Comment by ujellyx** [comment]
Yeah the videos in the warmane-thread debunk the report. Works as intended.
