### ISSUE TITLE
[Hunter][Spell] - Freezing Arrow/Freezing Trap

### ISSUE THREAD

**Issue by roguebugs** [SunwellTracker/issues#1467]
Decription: It should hit the closest target

Place a frost trap that freezes the first enemy that approaches, preventing all action for up to 20 sec. Any damage caused will break the ice. Trap will exist for 30 sec. Only one trap can be active at a time. | Place a frost trap that freezes the first enemy that approaches, preventing all action for up to 20 sec. Any damage caused will break the ice. Trap will exist for 30 sec. Only one trap can be active at a time. |  

How it works: Hits a random target within the radius.

How it should work:  Should hit the closest target to the trap

Source (you should point out proofs of your report, please give us some source): https://wowgaming.altervista.org/aowow/?spell=14311

**Comment by Kwyzard** [comment]
Any update for live server ?

**Comment by Afgann** [comment]
Probably Tuesday.

**Comment by Azathothh** [comment]
Fixed, will be updated soon.

**Comment by szoks** [comment]
ITS STILL BUGGED. You can test for example on mobs before 2nd boss on ToCH5 man. Because of that playing hunter PVP is pointless here. FIX IT
