### ISSUE TITLE
Hot and Cold still bugged 

### ISSUE THREAD

**Issue by drambit** [SunwellTracker/issues#1469]
Decription: The Sons of Hodir Daily quest "Hot and Cold" requires you to kill brittle revenants for essence of ice. Essence is supposed to have a 67% drop rate, which means that if you kill every single one in the lake you should be done the quest, but it seems far lower, like 20%-33%. It's not uncommon to see the same 3 people circling the lake on flying mounts for an hour because the droprate is so low.

How it works: Extremely low droprate on essence of ice.

How it should work: 2/3 droprate.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=42246/essence-of-ice

**Comment by Dootz** [comment]
will be fixed with next server update
