### ISSUE TITLE
Searing totem bug

### ISSUE THREAD

**Issue by Sunite** [SunwellTracker/issues#147]
Decription: Searing totem attacking whatever is in a range.

How it works: When you are fighting a mob and you put down a searing totem it attacks a mob. However if a mob dies and there is another in a range, it starts attacking him too...

How it should work: Should attack mobs I'm attacking.

Source (you should point out proofs of your report, please give us some source): Does it need a proof? It is logical kinda like gargoyle which you have presented in a preview video.

**Comment by Kokaina** [comment]
Correctly it should attack target where ur threat is the highest, if u had any threat on second mob than totem will attack it too. Did second mob was in combat with u?

**Comment by Kokaina** [comment]
Ok, true. Totem should attack only target which has combat and threat with player.
