### ISSUE TITLE
[Ulduar] Faceless Horror trash

### ISSUE THREAD

**Issue by Kittykatreporter** [SunwellTracker/issues#1473]
Decription: 

Faceless Horror doesn't use midn control

How it works: 

Does not MC random players

How it should work: 

Should Mind control.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=33772/faceless-horror#abilities
http://www.wowhead.com/spell=63713/dominate-mind

**Comment by Kokaina** [comment]
Im pretty sure its not his spell. Dominate Mind is used by Guardian of Yogg-Saron ;o have any video?
