### ISSUE TITLE
[Quest Bugged?] Preying Upon the Weak 

### ISSUE THREAD

**Issue by deviantgamer** [SunwellTracker/issues#1475]
Description: The Howling Fjord the quest Preying Upon the Weak seems bugged because quest items that appear lootable cannot be interacted with.

How it works: The quest involves searching for trapped animals and opening the traps. Sometimes when opening a trap the player receives a quest item directly, but sometimes a hostile Prowling Worg spawns instead. After killing the worg the Trapped Animal appears lootable but it cannot be interacted with. This gives a false impression of how the quest works. I personally wasted time trying to figure out why I couldn't loot the trapped animals because the first several traps I opened spawned worgs.

How it should work: Either the Trapped Animal should not appear lootable, or the player should be able to pick it up after killing the worg.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
