### ISSUE TITLE
Execute randomly does not deal damage

### ISSUE THREAD

**Issue by Tsaav** [SunwellTracker/issues#1476]
Decription: 
I don't know what's causing this issue, but it seems like every so often (about 20-30% of the time) casting execute does the animation and triggers a global. It does **not** spend any rage, however. What ends up happening is the execute deals no damage.

How it works: 
Sometimes casting Execute produces no damage. I think it might be because it spends 0 rage. 0 rage = a 0 damage execute?

How it should work: 
I should be able to execute 100% of the time when a player/npc is below 20% hp, and it should be dealing damage.

Source (you should point out proofs of your report, please give us some source): 
https://clips.twitch.tv/BoredFantasticClamCharlietheUnicorn Here is a clip of it happening. At 14 seconds my execute goes off, and deals no damage.

**Comment by arifashaari** [comment]
This has happened too often. Sound played, rage spent (sometimes they don't), no misses, no dodge/parry/block, yet no damage even in combat log.

**Comment by rajoe** [comment]
@ujellyx - it doesn't miss, I've checked the combat log, it just doesn't appear there - no dodge/parry/miss/block etc.

**Comment by Riztazz** [comment]
https://github.com/SunwellTracker/issues/issues/2262
