### ISSUE TITLE
[Quest] Fields of Grief [#1]

### ISSUE THREAD

**Issue by Erotes** [SunwellTracker/issues#1477]
Decription: The pumpkins you're supposed to steal have a weird respawn rate, takes alot longer than blizzlike.

How it works: Steal 10 pumpkins on the field. Takes alot of time for them to respawn, should be fixed when there's new players joining.

How it should work: The respawn rate should be reduced to 1 minute.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=365/fields-of-grief

Very easy to reproduce.

**Comment by Dootz** [comment]
will be fixed with next server update
