### ISSUE TITLE
Heartbreaker 10 man - no Emblem of Conquest

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#1479]
Decription: You don't get the correct Emblem from Heartbreaker in 10man (XT-002 Hardmode)

How it works: It gives your raid 1x Emblem of Valor

How it should work: It should give your raid 1x Emblem of Conquest

Source (you should point out proofs of your report, please give us some source): https://www.twitch.tv/videos/265976691 (2 hours 48 minutes)

**Comment by Kokaina** [comment]
Fixed with next ID.
