### ISSUE TITLE
The Storm King's Vengeance phasing bug

### ISSUE THREAD

**Issue by blodigejens** [SunwellTracker/issues#148]
Decription: I was doing the quest The storm king's vengeance in Zul drak on my hunter. The quest has you riding Gymer to kill some undead. 

How it works: After about one minute my abilities on the npc stopped working.
I tried to solve this by using /reload and relogging,  this caused me to dismount from Gymer, but I stayed in the phased area. I could not see any npcs in the world except the quest ones, and a GM had to remove the buff from me.

How it should work: I guess the game should kick you out of the phase if you relogg so that you can restart the quest.

Source (you should point out proofs of your report, please give us some source): I did not take any screenshots sadly, but I talked to Dred and he was the one who removed the buff.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
