### ISSUE TITLE
[Ulduar] Freya Mushroom duration

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#1480]
Decription: 
Ulduar Freya Mushrooms duration is shortened

How it works: 
Freya Mushrooms last 12 seconds

How it should work: 
Freya Mushrooms last 25 seconds
Was this change intended and undocumented, or unintended?

Source (you should point out proofs of your report, please give us some source): 
Watch the area near Diamond mark. This Mushroom lasts 1:20-1:45
https://www.youtube.com/watch?v=w2w2973jfBo&feature=youtu.be&t=132
Another video for reference sake. 2:11-2:36
https://www.youtube.com/watch?v=mq_kkp4esCA

**Comment by Kokaina** [comment]
Actually it was intented as I seen two notes that it should last for 12 seconds. There are no recorded videos from that so I thouht it may be on retails ptr on February. In the end i think it wasn't correct change, and even w/o your report i think we would change it to 25s. Will be done soon ;)

**Comment by Kokaina** [comment]
Corrected with next ID.
