### ISSUE TITLE
[Thorn Hill] mobs common items drop rate is way too high

### ISSUE THREAD

**Issue by Buttnugget69** [SunwellTracker/issues#1481]
Decription: 
Every time I kill a Razormane mob, I get drops: common cloaks, common belts, common boots, etc.

How it works: 
Drop rate, even if they're only common quality items, seems way too high

How it should work: 
Those items should drop at a much lower rate, correct me if i'm wrong :p 

Source (you should point out proofs of your report, please give us some source): 
(https://user-images.githubusercontent.com/39878620/40886742-9e5a280a-670b-11e8-818f-fe563b7bc84c.png)

I've only killed maybe 10-15 mobs, and got 5 Disciple's Cloaks, 3 Warrior's Boots, Other cloaks and other boots.

Thanks !

**Comment by Buttnugget69** [comment]
Edit: Greater Plainstriders have this problem too:
Drops from 1 of them only:

(https://user-images.githubusercontent.com/39878620/40886787-5008bfb2-670c-11e8-8573-46cf31ae2157.png)

This happened a lot of times too :P

**Comment by Buttnugget69** [comment]
Edit 2:

From the second Greater Plainstrider I killed right after the last screenshot

(https://user-images.githubusercontent.com/39878620/40886806-9e9dd93c-670c-11e8-82bd-6efdda65f556.png)

**Comment by Dootz** [comment]
will be fixed with next server update
