### ISSUE TITLE
Saronite Vapors debuff

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#1482]
Decription: 

How it works: Saronite Vapors is a buff on the player.

How it should work: Saronite Vapors should be a debuff on the player.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Saronite_Vapors - **"Each tick of the debuff makes you take damage but also gain mana:"**

**Comment by Dootz** [comment]
will be fixed with next server update
