### ISSUE TITLE
Darkmoon, Mulgore

### ISSUE THREAD

**Issue by polygxn** [SunwellTracker/issues#1484]
Decription: 
There is Darkmoon Faire at Mulgore.

How it works: 
There is Darkmoon Faire at Mulgore.

How it should work: 
It should be there.

Source (you should point out proofs of your report, please give us some source): 
https://i.gyazo.com/aea157b8c0b33fc2cb32b732ab4c2cb2.jpg

**Comment by Dootz** [comment]
GM Tide : 

> its up in elwynn forest
