### ISSUE TITLE
VIOLET HOLD CRYSTAL 

### ISSUE THREAD

**Issue by nlittlenoda** [SunwellTracker/issues#1485]
Decription: 
the violet hold  crystal are not aviable and i cant do  glory of the hero ( dehydration ) 

How it works:  i see the crystal but i cant  use them 

How it should work:   the crystal should  be aviable 4 evry player at least 1 time 

pls fix it 

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
The last times I did the instance (e. g. yesterday) the crystals worked just fine.
