### ISSUE TITLE
Hunter/DK/Warlock pet bugs

### ISSUE THREAD

**Issue by dispelx** [SunwellTracker/issues#1488]
Decription: 
Will this ever be fixed?
it's been 4 months since the creation of these bug reports
not at all possible to play for a hunter

https://github.com/SunwellTracker/issues/issues/921

https://github.com/SunwellTracker/issues/issues/1070

https://github.com/SunwellTracker/issues/issues/168
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
I'll add (https://github.com/SunwellTracker/issues/issues/465) though idk if it's not a performance related issue - upon exiting vehicle, cannons or mounts like Oculus drakes pet ui disappears yet its keybinds remain active (reload + mount/dismount fix this issue).

**Comment by Kokaina** [comment]
Fixed.
