### ISSUE TITLE
Quest: The Captive Prospectors

### ISSUE THREAD

**Issue by Demite** [SunwellTracker/issues#1489]
Decription: 

When Using Key to Unlock cage with Prospector Gann, No credit is given- used 5 keys over 30 minutes
Grizzly Hills Captive Prospectors Rescue
Prospector Gann
Prospector Torgan
Prsospector Varana

You must collect Keys to unlock cages 

How it works: 
Using key on Prospector Gann cage Doesn't grant credit for objective

How it should work: 
Using key on Prospector Gann's Cage should give credit for Objective
Source (you should point out proofs of your report, please give us some source): 
Quest details in quest log

**Comment by Dootz** [comment]
fixed
