### ISSUE TITLE
[Quest] Return of the High Chief

### ISSUE THREAD

**Issue by Sasssyunicorn** [SunwellTracker/issues#149]
Decription: Cannot complete quest  [Return of the High Chief]. Stuck on NPC doing nothing.

How it works: After you free that tauren from prison he is just standing there doing nothing(happened 3 times to me).

How it should work: There's elite boss up the hill that should come down and be killable.

**Comment by MrTide** [comment]
if npc around him attacks him after engaging the event he bugs out
#extra information

**Comment by bongobg** [comment]
Did it couple of days ago - still the same.

After using the item and starting the encounters, if the NPC enters in combat before starts to walk, the encounter gets bugged.

**Comment by Dootz** [comment]
will be fixed with next server update
