### ISSUE TITLE
Quest: The Chain Gun and You

### ISSUE THREAD

**Issue by Demite** [SunwellTracker/issues#1490]
Decription: 
Use Chain gun, Call for 7th Legion soldier and shoot undead till they are in safe area. 

How it works: 
Currently you call the injured 7th legion soldier and a ton of undead spawn throughout the escort/guiding the Soldier to safety. I attempted 20 tries only managing to get 1 successful pass.

How it should work: 
I never done this mission, but it seems broken with how many undead spawn you cannot shoot the gun fast enough to kill them most of the time.

Source (you should point out proofs of your report, please give us some source): N/A

**Comment by Dootz** [comment]
I did it at the third attempt, but you're right. It's a bit irritating and requires key smashing. Respawn time of zombies will be slightly increased.

**Comment by Dootz** [comment]
will be fixed with next server update
