### ISSUE TITLE
[Store Mount] Black Qiraji Battle Tank (flying) doesn't work while in Wintergrasp

### ISSUE THREAD

**Issue by brlan10** [SunwellTracker/issues#1493]
Decription: 
The store mount Black Qiraji Battle Tank (the flying version) doesn't work in Wintergrasp

How it works: 
Using the mount in WG while battle is NOT occuring results in message "You can't do that in a Battleground"

How it should work: 
Using the mount in WG while battle is NOT occuring should be allowed.

Source (you should point out proofs of your report, please give us some source): 
screenshot: https://i.imgur.com/zzB4oaR.png

Steps to reproduce:
It happens every time, so just go to WG and try to use the mount.

**Comment by ujellyx** [comment]
Flying mounts can't be used in general during a WG battle.

**Comment by brlan10** [comment]
Did you read the issue or look at the screenshot? It's not during a battle.
It consistently never works no matter if there's a battle or not.

**Comment by feralxgodx** [comment]
It's shouldnt work on WG/arena/bg because this mount has instant cast.

**Comment by brlan10** [comment]
It actually doesn't. I wish it had an instant cast though.
