### ISSUE TITLE
[Quest] The Iron Thane and His Anvil/Lightning Infused Relics (elevator+vehicle)

### ISSUE THREAD

**Issue by Demite** [SunwellTracker/issues#1494]
How it works: 
When you use the Golem Control unit and take the elevator you fall through the floor of the Elevator and get stuck.

How it should work: 
shouldn't fall through elevator floor.
Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bug isn't only about that quest. Vehicles have problems with "seeing" elevators and stuff like that everywhere. Same thing happens on lifts in howling fjord https://db.darkwizard.pl/?quest=11495
