### ISSUE TITLE
[Ulduar] Caster thrash before Vezax casts while in CC/sheep

### ISSUE THREAD

**Issue by Smoogl** [SunwellTracker/issues#1495]
The caster thrash packs before General Vezax in Ulduar have mobs in there that continue to cast even tho they are hard CC'd. As visible in the clip below (watch the Moon).

https://clips.twitch.tv/ExuberantWimpyJalapenoAsianGlow

I'm quite certain this shouldn't be the case.

**Comment by Dootz** [comment]
will be fixed with next server update
