### ISSUE TITLE
[Resto Druid][Tier 8 4-Set Bonus]

### ISSUE THREAD

**Issue by Charless22** [SunwellTracker/issues#1497]
Decription: 
Druid T8 Restoration 4P Bonus — Your Rejuvenation spell also instantly heals your target for its periodic healing amount.

How it works: 

Your Rejuvenation spell also provides an instant heal for your target.
-Heals for about half of what a Rejuvenation tick does, flasked and selfbuffed. 
1145 Initial Ticks
2080 Ticks for rest of duration

How it should work: 
The difference between first tick of rejuvenation and the rest should not be this big.
The initial tick should not heal the same amount as a normal tick would, doesnt scale with the talents Genesis, Improved Rejuvenation, or Gift of Nature. It does scale with Empowered Rejuvenation, Master Shapeshifter, and Tree of Life.

In a later patch, after Trial of the Grand Crusader was release, the set bonus was nerfed because it was too strong compared to the new tier.
"Druid Tier-8 Healer 4-Piece Set Bonus: The amount of healing this set bonus grants on the initial cast of Rejuvenation has been reduced by 50%."

Im asking if its intended that this set bonus is using the nerfed value even during Ulduar.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Patch_3.2.2
http://www.wowhead.com/spell=64760/item-druid-t8-restoration-4p-bonus#comments

**Comment by ujellyx** [comment]
As we're on 3.3.5 mechanic wise the nerf from patch 3.2.2 is probably responsible for the low amount of healing from the initial tick. Devs probably won't change that.

**Comment by Afgann** [comment]
@ujellyx correct, it's intentional.
