### ISSUE TITLE
Shadow Priest Pain and Suffering 

### ISSUE THREAD

**Issue by Phubo** [SunwellTracker/issues#1499]
Decription: The talent "Pain and Suffering" does not work as intended with proccs

How it works: it reapplies the dot instead of refreshing the duration. Therefore the newly applied dot doesn't benefit from previous proccs such as "Now is the time!" from Sundial of the Exiled or "Lightweave" from the tailoring cloak enchant. havent had a chance to test haste potions or other proccs. 

It does seem to work with other talents and spells such as "Inner Fire (increased crit, 25%)" and "Shadow Weaving"

How it should work: it should refresh the dot with all the proccs it had been applied with in the first place 

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/pgn5l (test with The time is now!)
https://streamable.com/1ipxi (test with Lightweave)

**Comment by ujellyx** [comment]
Working as intended. The damage of the "refreshed" SWP is calculated on refresh, not only once on first application.
False report.
