### ISSUE TITLE
[Mob range] Frigid Abomination Attacker

### ISSUE THREAD

**Issue by Sasssyunicorn** [SunwellTracker/issues#150]
Decription:  Frigid Abomination Attacker in Ruby Dragonshrine (Dragonblight) won't leash.

How it works: SHouldn't it leave me alone after 30yards?

How it should work: It was following me no matter how far I ran,

Source (you should point out proofs of your report, please give us some source): No SS, luckily for me dungeon queue popped and I ran.

**Comment by Dootz** [comment]
Will be fixed with next update
