### ISSUE TITLE
Quest: Convocation at Zul'Heb

### ISSUE THREAD

**Issue by zilvinasj** [SunwellTracker/issues#1500]
Decription: Does not give credit sometimes

How it works: when Har'Koa does more than 50% of damage you do not complete the quest, even though according to the script Har'Koa says it is all done.

How it should work: Should give credit no matter how much damage Har'Koa does (wowhead has numerous cases where it is solo'd by people with no issues)

Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/quest=12730/convocation-at-zolheb#comments

**Comment by Dootz** [comment]
will be fixed with next server update
