### ISSUE TITLE
[Death Knight] Dancing Rune Weapon

### ISSUE THREAD

**Issue by Mietoszew** [SunwellTracker/issues#1501]
Decription: Dancing Rune Weapon hits does not count Might of Mograine critical strike bonus damage properly. 

How it works: 
When it comes to hits which are not affected by Might of Mograine, DRW damage is fine (about 50% DK's damage). But when Death Knight hits with Death strike, Heart Strike, Blood Strike and Blood Boil, DRW never hits for about 50% of damage, DRW damage is too low. In most cases, DK's DS damage without critical strike is higher than DRW's DS critical damage. Seems like DRW is affected by Might of Mograine, but it's base damage is far too low on these spells.

How it should work: 
DRW hits should be properly affected by Might of Mograine talents. DRW's DS, HS, BS, BB damage should be about 50% of Death Knight's damage.
![wowscrnshot_060918_162130](https://user-images.githubusercontent.com/40121382/41193444-1a377c70-6c0c-11e8-9883-d52e865e11e0.jpg)
![wowscrnshot_060918_162132](https://user-images.githubusercontent.com/40121382/41193445-1a54629a-6c0c-11e8-9d0a-4460918df762.jpg)
![wowscrnshot_060918_162402](https://user-images.githubusercontent.com/40121382/41193446-1a7005fe-6c0c-11e8-88a1-d3413727f916.jpg)
![wowscrnshot_060918_162408](https://user-images.githubusercontent.com/40121382/41193447-1a8ead6a-6c0c-11e8-8e55-438d7c6edda8.jpg)
![wowscrnshot_060918_163712](https://user-images.githubusercontent.com/40121382/41193448-1aaa240a-6c0c-11e8-90ec-a69a7257b086.jpg)
![wowscrnshot_060918_163715](https://user-images.githubusercontent.com/40121382/41193449-1ac6409a-6c0c-11e8-8aa3-cb98c68a0c05.jpg)
![wowscrnshot_060918_165027](https://user-images.githubusercontent.com/40121382/41193450-1ae3f964-6c0c-11e8-92ca-8a969a461420.jpg)
![wowscrnshot_060918_165029](https://user-images.githubusercontent.com/40121382/41193451-1b0358a4-6c0c-11e8-9d19-933f50a1c442.jpg)
![wowscrnshot_060918_165035](https://user-images.githubusercontent.com/40121382/41193452-1b1fa518-6c0c-11e8-8141-c2a2d7a22f86.jpg)
![wowscrnshot_060918_165036](https://user-images.githubusercontent.com/40121382/41193453-1b3aead0-6c0c-11e8-879b-a05f6d87ba90.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/5

**Comment by Mietoszew** [comment]
DRW's Rune Strike damage is not correct as well.
