### ISSUE TITLE
[Malygos] Scions target players on hover disk with arcane barrage

### ISSUE THREAD

**Issue by samercyn** [SunwellTracker/issues#1504]
Decription: Scions target players on hover disk with arcane barrage

How it works: During phase 2, when a player is riding on the hover disk they will get hit by the arcane barrages cast by the Scions of Eternity.

How it should work: Players on hover disks should not be eligible targets for the Scion of Eternity's arcane barrage.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/xYqJ-8FiXCI?t=4m50s - watch the rogue, DK, and feral druid, never gets hit by barrage after mounting the disks
https://youtu.be/HvPvWIEiUsk?t=4m30s - watch rogue and warrior, never gets hit by barrage after mounting the disks
https://youtu.be/BoQwGt6_SAI?t=4m - this video is admittedly cancer to see the health bars but, if you watch the melee closely, they never get hit by barrages after mounting the disks.

**Comment by Dootz** [comment]
will be fixed with next server update
