### ISSUE TITLE
[Spell Batch System] No Spell/CC delay - not possible to "cross-cc"

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#1506]
**Decription:** 
Many of you, who have watched PvP videos in the past, probably noticed that it was possible to e. g. switch places with two warriors charging each other, or two rogues sapping/blinding themselves at the same time. This also allowed for healers to cast a heal on a target and sit down and drink right after the cast if they were out of combat. Right now, this isn't possible on this server, as there's no spell delay.
One quick example-video: http://www.warcraftmovies.com/movieview.php?id=110241 (19:20 Min.)

**How it works:** 
As instant-spells/cc have basically no delay, cross-cc isn't possible.

**How it should work:** 
There should be a random delay of 0 - 400ms for instant casts and cc before "hitting" the target. This only applies when the targets are other players and not the casting player himself.

**Source (you should point out proofs of your report, please give us some source):** 
The "delay" was only changed as soon as Warlords of Draenor to be less than that, but still existed. This means that the delay existed from Vanilla all the way to MoP - see: http://blue.mmo-champion.com/topic/318876-warlords-of-draenor-theorycraft-discussion/#post114

A source and a discussion on this topic were on the TrinityCore Github - even a fix was included (although with a fixed 200ms amount):
https://github.com/TrinityCore/TrinityCore/issues/1195

Some other private server, where the issue was fixed:
https://github.com/ccshiro/cc-buglist/issues/1438

Reddit-Link about the topic:
https://www.reddit.com/r/wowservers/comments/6867mw/400ms_spell_batches_prewod/

They even discussed it on Nostalrius (vanilla) and provided some proof:
https://forum.nostalrius.org/viewtopic.php?f=30&t=43506&start=150

**Comment by Sunaqt** [comment]
also /confirm

**Comment by lukaasm** [comment]
Fake delay implemented for all PvP CC spells.
Current window: 200ms which may be tweaked later in the future

**Comment by ujellyx** [comment]
Quick question after the fix:
Did you set the delay to a fixed timer (if so, how many ms) or on a variable between 0 and 400 ms?
