### ISSUE TITLE
[PL]Fury stance Q line bug

### ISSUE THREAD

**Issue by tytus500** [SunwellTracker/issues#1508]
Decription: 
Its hard to explain in English for me.
Błąd polega na tym, że niemożliwe jest ponowne rozpoczęcie lini Questów dla warriora.
Próbowałem czyścić folder WTF ale z mizernym skutkiem.

How it works: 
Po rozpoczęciu lini Q dla Warriora jeden z Questów należy wykonać w określonym czasie, jeżeli się tego nie zrobi to Q jest oznaczony jako failed. Mimo niepowodzenia jest możliwość przyjęcia kolejnej lini q w celu zdobycia Fury Stance. Po udaniu się na wyspę w The Barrens i oddaniu q dla lini fury nie możliwe jest rozpoczęcie kolejnej części dla fury. Po tym fakcie spostrzegłem się że poprzednie zadania dla warriora jest, jak wyżej wspomniałem, failed. Po usunięciu tego Questa z mojego Quest logu, aby rozpocząć go ponownie po prostu Quest się nie pojawia u trenera. Jednocześnie nie jestem w stanie kontynuować q dla fury.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 

Jak widać na załączonym obrazku nie mam ani Q, ani możliwości ponownego rozpoczęcia linii, ani fury stance. Pozdrawiam.

![zrzut ekranu 2018-06-10 o 20 27 34](https://user-images.githubusercontent.com/40148555/41205019-bf445a7c-6cec-11e8-8a4c-8599fa1eba36.png)

**Comment by Dootz** [comment]
There's a hidden limit in timed quests. You can only have one quest with the time limit in your quest log. Removing all quests with time limit from quest log should resolve your issue.
