### ISSUE TITLE
[Quest - Howling Fjord] - Iron Rune Constructs and You The Bluff

### ISSUE THREAD

**Issue by IroniaSham** [SunwellTracker/issues#1509]
**Decription:** 
You always gotta have a contingency plan in case your main plan backfires! That's why I've built in some anti-intelligence systems into the construct.

Your shiny new ride might rouse some suspicion while you're at Baelgun's excavation site. That's what your bluff ability is for! Just use that any time you're confronted and you'll be safe from harm.

Test it out on Lebronski by walking on his rug. Once he starts huffin' and puffin', use the bluff!

Get on the work bench when you're ready to begin. 

(copy from https://db.darkwizard.pl/?quest=11491)

**How it works:** 
It is not working. I do it several times, now watched youtube video and do it same as in and NOT working. Small quest only 2000 xp.

**How it should work:** 
https://www.youtube.com/watch?v=w84B28E_r_o

**Source (you should point out proofs of your report, please give us some source):** 
I want to do as many quest i could. I would like to get Loremaster and Seeker title, maybe wont need only this but please watch it. :))

Thanks, Ironia.
_P.s. Thanks for Doremi fast answer on discord where should i report this._

**Comment by Dootz** [comment]
Hi, have you tried to stand near him and use golem's ability? It is possible that sometimes he'll bug and won't "notice you" (text won't appear and he'll keep moving), but still, quest event should start when you use golem's ability. Regardless of that, I'll check if it can be improved.

**Comment by Dootz** [comment]
will be fixed with next server update
