### ISSUE TITLE
 [Hard to Swallow]

### ISSUE THREAD

**Issue by Gudmon** [SunwellTracker/issues#151]
Decription:  [Hard to Swallow]

How it works: I have to use the quest item as long as the jormungar opens his mouth and is weakened. I can use the quest item but nothing happens.

How it should work: As long as it is weakened you can use your q item, and it explodes the jormungar into pieces that you are able to loot.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
![image](https://user-images.githubusercontent.com/22802214/35732871-6da5b020-081b-11e8-9f54-dcf3cbea2469.png)
