### ISSUE TITLE
[Quest][Vehicle][Dragonblight] Xink's Shredder

### ISSUE THREAD

**Issue by Azathothh** [SunwellTracker/issues#1512]
Decription: 
Xink's Shredder vehicle should be usable for two quests : Lumber Hack (12050) and Harp on This!(12052).
In first one it MUST be used, otherwise we won't be able to complete it, in second one it can be used(and should to help with elite mob), but isn't necessary 

How it works: 
Currently if we don't have Lumber Hack in our quest log we can use Xink's Shredder Control Device to summon Xink's Shredder but we can't enter this vehicle.
We can enter it only if we have Lumber Hack in quest log.

How it should work: 
We should be able to use Xink's Shredder when we have Harp on This! quest and don't have Lumber Hack

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?npc=27061  - vehicle
https://db.darkwizard.pl/?item=36734 - item to summon vehicle
https://db.darkwizard.pl/?quest=12052
https://db.darkwizard.pl/?quest=12050

**Comment by Dootz** [comment]
will be fixed with next server update
