### ISSUE TITLE
Badge of heroism

### ISSUE THREAD

**Issue by Lyalp** [SunwellTracker/issues#1513]
Decription: I did two heroics yesterday at a total of four bosses. I didn't get any badges from them, even though it said I did. I recall it telling me that my bags are full, even though they were nearly empty.

How it works: Kill a boss, get a badge.

How it should work: Kill a boss, get a.. badge...?

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Have you looked at the "Currency"-tab on your character sheet? Those badges don't appear in your inventory.

**Comment by Lyalp** [comment]
![wowscrnshot_061218_075230](https://user-images.githubusercontent.com/40208208/41298297-e5aef56c-6e15-11e8-9bf9-77dac059243a.jpg)

**Comment by Lyalp** [comment]
SHows the same number. Idk if it's a matter of not having it set to where it shows the currency under the bag or not.

**Comment by ujellyx** [comment]
Hm, can only speak for myself - never had any problems not receiving badges. It once happened, that I queued for NHC instead of HC though (this way you obviously wouldn't get any badges)

**Comment by Lyalp** [comment]
Yeah I just recently put it on tracking under my bags, so I don't know if it happened because of that. I did both as randoms, but I haven't done actual randoms in some time, so I don't know if this has been an issue for a while now or not. I'm kinda wanting to avoid doing raids if it leads me to have the same issue with raid bosses. Would kinda seem like a waste of time.
