### ISSUE TITLE
[Quest - Nekrum's Medallion] 

### ISSUE THREAD

**Issue by ETB1991** [SunwellTracker/issues#1516]
Decription: The quest [Nekrum's Medallion] is a chain from the hinterlands

How it works: Nekrum is suppose to drop the quest item

How it should work: Nekrum did not drop the quest item

Source (you should point out proofs of your report, please give us some source): His body disappeared before I could take a screenshot and I also didnt know you need to provide proof. My first Bug i am reporting

**Comment by Dootz** [comment]
Is it possible that he was killed by a pet? (warlock/ hunter). Or you killed him and quest item was not in loot.
