### ISSUE TITLE
[Priest] Dispersion

### ISSUE THREAD

**Issue by drekthral** [SunwellTracker/issues#1517]
Decription: 
Player become invisible when used correctly.

How it works: 
Mount up, apply Shadow Form, use Dispersion, immediately cancel Shadow Form. And you will became invisible and untargetable. Only your name will be shown.

How it should work: 
After cancelling Shadow Form, player shoud be visible in normal form.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_061318_173216](https://user-images.githubusercontent.com/14870273/41361714-03805a84-6f30-11e8-9284-df3fb2a047b1.jpg)
![wowscrnshot_061318_173222](https://user-images.githubusercontent.com/14870273/41361715-03a9da94-6f30-11e8-9f88-88e77976a216.jpg)
![wowscrnshot_061318_173225](https://user-images.githubusercontent.com/14870273/41361716-03c733e6-6f30-11e8-8abd-96f048d1e14b.jpg)
![wowscrnshot_061318_173230](https://user-images.githubusercontent.com/14870273/41361717-03e5ed36-6f30-11e8-8026-94a7947142a3.jpg)

**Comment by ujellyx** [comment]
Yeah I remember this "bug" from retail. Was fun. :D 
/confirm

**Comment by Riztazz** [comment]
Client bug, nothing i can do about it, its issue with wotlk shaders
