### ISSUE TITLE
 [Lumber Hack]

### ISSUE THREAD

**Issue by Gudmon** [SunwellTracker/issues#152]
Decription:  [Lumber Hack]

How it works: You are able to summon the shredder minion to chop trees, but even if they are marked, you can't use his ability to receive any lumber.

How it should work: Obviously you should get the lumber from the marked trees if you use his ability (Gather Lumber) (number 6 spell)

Source (you should point out proofs of your report, please give us some source): Maybe the respawn time is too long or I don't know. We tried to do this quest for ~45 minutes or so.

**Comment by Riztazz** [comment]
Resolved
