### ISSUE TITLE
Bugged Icethorn in storm peaks

### ISSUE THREAD

**Issue by kenniholm** [SunwellTracker/issues#1521]
Decription: 
Herb going invisible when you go close to it, so you can't pick it up.
The herb itself is located "71,6 64" close to fjorns anvil.

How it works: 
It dissapears when you go close to it, and reappears when you go more than 10 yards away from it or so.

How it should work: 
Well it should not dissapear and people should be able to pick it up.

Source (you should point out proofs of your report, please give us some source): I dont have any screen capture sofware atm but the herb is there.

**Comment by Dootz** [comment]
will be fixed with next server update
