### ISSUE TITLE
[Quest] The Challenge - Loot Issue

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#1526]
Decription: I did Boss on Blackrock Arena to that quest. Its dwarf as leader, trogg, centaur, gnome, quillback and one more that i dont remember. Ive got gnome knuckles, quillback back, centaur mantle and ive opened dwarf and ive got these 3 items again./

How it works: up

How it should work: decide you want to split loot between owners, or keep leader as loot giver.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=9015/the-challenge

**Comment by Dootz** [comment]
will be fixed with next server update
