### ISSUE TITLE
[Mage] T8 4p. proc chance definitely too low

### ISSUE THREAD

**Issue by darkpotterxd** [SunwellTracker/issues#1528]
**Description:** 
I recently got my 4th T8 piece and was very excited for the 4p bonus but I got really disappointed soon... 

**How it works:** 
On Angrathar it's an embarassing bad T8 bonus. I could never get 2 procs or more in a row which is definitely NOT blizzlike! Even after hours of testing! It really feels like a 2-3% chance at best. I talked about that topic with several mages on Angrathar and all of them said they never had two consecutive procs in a row. So the proc chance is no way near to retail WotlK. It procc's once every 5-10 minutes which is ridiculous compared to retail.

**How it should work:** 
From back in retail I remember mage with 4P bonus being absolutely broken with so many endless procs. On retail it was somewhere between 10-30%.

**Source:** 
I did some research and people talked about the T8 proc chance at wowhead back in retail. People at mmo-champion even complained the bonus being too mana draining due to high frequency of procs and high mana cost of Pyroblast which isn't an issue on Angrathar at all since we barely get any proc.

Screenshot of many wowhead comments from 2009 to confirm my thoughts: https://imgur.com/a/i6TqEVu

Please fix this issue and make mage great again!

**Comment by darkpotterxd** [comment]
I can make a dummy test later to show you how bad the proc rate actually is.

**Comment by Nadiirr** [comment]
It's difficult - because we don't know what the proc % should be. 

The wowhead comments are good to point us in a direction - but can't be taken word for word.

**Comment by Druuz** [comment]
@Nadiirr any chance you can give us insight to what the current procc chance is set to on sunwell? In my experience this procc also seem way to low, especailly when reading up on old forum posts from when wotlk was current, how this set  and 4setbonus was praised as one of the best bonuesses piled with the screenshots above. At sunwell the 4set procc seems mediocre at best.

**Comment by gabbat** [comment]
![image](https://user-images.githubusercontent.com/38278426/41745854-ad3edd6a-75a8-11e8-884b-988102edaf8f.png)

**Comment by gabbat** [comment]
that might be off help, values of 2pieces compared to 4piece

**Comment by gabbat** [comment]
but yes, the procc chance on sunwell is wayyyyy to low, 4piece is not worth using currently and it was bis up until 4pieces T9 back in the day

**Comment by gabbat** [comment]
what does "requires testing" mean btw? I am pretty sure you can check the data on sunwell within a few seconds - what do you need tested?@afgann

**Comment by Afgann** [comment]
Issue was fixed and it will be applied on realm after being tester.

**Comment by gabbat** [comment]
@Afgann  took me 4hours to dig throught the forums to find the correct time stamp but I found a legit source:
http://web.archive.org/web/20091108152029/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/

"4/5 T8 has a 20% proc rate, has no cooldown and can chain proc. It's a 2% boost for Fire/Frostfire, 1% for Arcane, 0.2% for Frost."

further information is on the following pages

**Comment by darkpotterxd** [comment]
gabbat = MVP !!!

**Comment by Kokaina** [comment]
Fixed, will be implemented with next update.
