### ISSUE TITLE
Nimar - rare mob

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#1529]
Decription: owy rare mobek, przywodca klanu Warband albo prowadzi swoich ludzi ze sporej odleglosci skitrany w jakiejs jaskini, albo lezy juz gdzies w 10m pod ziemia ;D da rade cos podzialac? bo ładne piorka leca :>

How it works: 
No nie ma 

How it should work: 
A powinien byc

Source (you should point out proofs of your report, please give us some source): https://db.darkwizard.pl/?npc=2606

**Comment by Dootz** [comment]
will be fixed with next server update
