### ISSUE TITLE
Silverleaf node in Mulgore is underground

### ISSUE THREAD

**Issue by Saben65** [SunwellTracker/issues#1530]
Decription: There is a silverleaf spawn just south of the elevators to Thunder Bluff that appears to be spawned underground. Coords are 37.46, 36.46

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_061618_093726](https://user-images.githubusercontent.com/1936487/41499641-eb86d082-7148-11e8-92b5-1554fb809056.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
