### ISSUE TITLE
Bug with Recruit a friend-feature

### ISSUE THREAD

**Issue by Kastakasta** [SunwellTracker/issues#1533]
Decription: 
The bonus experience you're supposed to get when you are recruiting a friend to level with you isn't working as it should, you get about 1/4 of the experience when in a group with your recruiter of what you would get when you are questing without having them in your party.

How it works: 
Personal example: When I was in a group with my recruiter in the starting zone we got about 33xp per mob each, when we left the group we got about 200 xp per mob. Wouldn't matter if it wasn't for the fact that you can't grant any levels you've gotten outside of the party, which is about 50% of the idea with RaF.

How it should work: 
Obviously, we should both be getting that bonus experience, aka 200xp per mob, when we are in a group rather than when we are solo-killing mobs.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
In party xp from monsters is shared between party members, so: 
If monster gives solo 50xp at x1 xp rate it would give 100xp solo at x2 xp rate. In RaF with x3 it would be 150xp, but it's shared between party members, so if there's 2 players AND they are equal levels they would get 75xp each. If players levels are different it won't be distributed equally also "rested" isn't shared through raf so it may be big difference if one player is rested while other isn't
