### ISSUE TITLE
[Rogue - PvP] Vanish Fear

### ISSUE THREAD

**Issue by Rogueqt** [SunwellTracker/issues#1536]
Description: Every spell can be immuned by vanishing at the right time, but on Sunwell I've never been able to get that to work.
Spells referenced: 
https://db.darkwizard.pl/?spell=26889 Vanish
https://db.darkwizard.pl/?spell=10890 Psychic Scream

How it works: Even if you vanish on the right millisecond you'll still get hit by that spell. For e.g. I can vanish right on the cast of priest's Psychic Scream, and I will get into vanish, but after about half a second I'll get hit by it.

How it should work: When vanishing on the exact cast of that spell vanish should immune it and the rogue should not be hit by the spell the rogue vanished.

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Did a more detailed report on it here:

https://github.com/SunwellTracker/issues/issues/1505

**Comment by Rogueqt** [comment]
Didn't see your thread when i was reporting this, but yea devs should look at ur post as it provides proof.

**Comment by lukaasm** [comment]
Closing due #1505 being the same issue.
