### ISSUE TITLE
One-handed Specialization talent in protection tree (warrior)

### ISSUE THREAD

**Issue by Cymoril** [SunwellTracker/issues#1537]
Decription: 
The talent is not working as it should

How it works: 
It only enhances white damage (adds a bonus to weapon damage in character sheet) and thus it doesn't affect non-weapon damage based skills. (like revenge or shield slam for example)

How it should work: 
This talent is a damage multiplier which means ALL physical damage is enhanced (there must appear the x110% multiplier when you mouse over the "damage" word in the character sheet and the word must be in green color). This is the same for one handed spec in paladins.
Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
No source attached.
