### ISSUE TITLE
Dmg while fear effects

### ISSUE THREAD

**Issue by splank96** [SunwellTracker/issues#1539]
Decription: 
Getting dmg while be feard while have an absorb shield.

How it works: 
If you are feared and have a absorbshield on you and get a fear (e.g 9sec) and your absorb shield absorbs (e.g 6k) the dps can give you 6kdmg and the fear doesnt break because the dmg got absorbed.

How it should work: 
If you get a 9sec fear and have a 6k absorb shield on you and you absorb incoming dmg the fear should break as same fast as if you wouldnt have a absorb shield ). So e.g after 2k absorbed dmg the fear should break. 

Source (you should point out proofs of your report, please give us some source): 
Edit: https://wow.gamepedia.com/Psychic_Scream

**Comment by ujellyx** [comment]
Just a snipped from a Wiki:
"Damage taken (or absorbed) while under the protection of shield or damage reduction spells will still count toward Psychic Scream's damage threshold in full, and such spells will not reduce the likelihood of Psychic Scream breaking."
https://wow.gamepedia.com/Psychic_Scream

/confirm

**Comment by Riztazz** [comment]
Please re-test, this was probably fixed when i fixed sacrifice and fear effects :P
