### ISSUE TITLE
Warrior: !Bladestorm resets auto attack timer!

### ISSUE THREAD

**Issue by Vertaz** [SunwellTracker/issues#1545]
Decription: Using bladestorm resets auto attack timer, 

How it works: 
Using Bladestorm will reset your melee swing to 0 = lot of loss rage and damage.

How it should work: 
Bladestorm should not affect auto attack timer, this is the most major bug I found on Warrior, please try to fix this one prio if you can :) Its big nerf for damage of Arms

Source (you should point out proofs of your report, please give us some source): 
Quartz with auto attack timer is great thing to prove, but you can see that even without it, that your auto attack will get delayed by a lot.

**Comment by ujellyx** [comment]
Where's the proof that it shouldn't be that way? Wiki, retail-forum, etc.?

**Comment by Vertaz** [comment]
Simply put: Nobody on retail will talk about something not working, that has worked ever since 3.0.2. This is the first time after me playing WotLK for 8 years including retail WotLK that I see Bladestorm reseting melee swing to the absolute start. (example: Give me proof from retail-forum that Death coil should not reset DK melee swing in patch 3.3.5b).

**Comment by ujellyx** [comment]
Thing is, in here we can't just rely on ones "experience". We need definite proof, either through some old forum posts or through some movies from retail WotLk.

**Comment by Vertaz** [comment]
It is in your own interest to have functional Classes. At least, not to have major class bugs. If one Gladiator is not enough to prove such a obvious game breaking bug I can gather more Gladiator rated players from Arena Tournament/Warmane.

Or simply just log on any server you compete with, doesnt matter if its Circle/Warmane/Blackrock/GD idk what else and you dont even need auto attack timer to see that auto attack doesnt reset when you use Bladestorm.

Same with Sweeping strikes bug, These two are so major hugely affecting Arms Warrior both in PvP and PvE that it should not be questioned.

Blackrock - Template gear NPC - Teleporter - training dummy area - Bladestorm 2 times max and you can clearly see the difference. Sweeping strike + thunder clap just once and you can see that it doesnt take away your Sweeping Strikes stacks. 

Its like if you ask me to send you photo that in 1928 grass was green...

**Comment by Vertaz** [comment]
I dont want to sound rude, but you get what I am trying to say, I hope

**Comment by ntt1** [comment]
Relax vertaz, trauma is still bugged and admins don't care to fix it even though its been on the bugtracker forever (confirmed bug), so overall warriors do more dmg.
