### ISSUE TITLE
Warrior: Heroic Throw resets auto attack timer

### ISSUE THREAD

**Issue by Vertaz** [SunwellTracker/issues#1546]
Decription: Heroic throw resets melee auto attack timer for 3,6/3,4 second depending on your weapon speed as if you used bow/gun, but with much longer delay to auto attack. 

How it works: 
Heroic Throw resets melee auto attack timer = rage and damage loss. Heroic throw should be usable as a filler for free gcd, which is not, as you loose 1 whole melee swing.

How it should work: 
Heroic throw should not affect melee auto attack timer, you are not switching weapon or using ranged weapon or casting, it is melee ability related to your main hand weapon.

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Proof?

**Comment by Vertaz** [comment]
Responded you in my Bladestorm thread.

**Comment by lukaasm** [comment]
Proof:
https://youtu.be/H_mtfdsF-8o?t=80

**Comment by lukaasm** [comment]
Proof:
https://www.youtube.com/watch?v=H_mtfdsF-8o
