### ISSUE TITLE
[Quest][Northend] The Yeti Next Door.

### ISSUE THREAD

**Issue by Exorcista** [SunwellTracker/issues#1548]
**Decription:** 
**Quest:** http://www.wowhead.com/quest=11284/the-yeti-next-door

Maybe if the sentries won't help me, you will? I'm the foreman of the mine just across the bridge. My men are mining ore for the weapons our expeditionary force will need to carve a path into the Grizzly Hills.

A giant yeti has invaded the mine, blocking the tunnel we need to expand! We've tried yelling at him and smoking him out, but nothing's worked.

Maybe you could rouse it from its sleep with a meal of meat from the frosthorn rams in the snowy areas around town? Please? We're desperate!

**How it works:** 
With a drop rate way lower that it should be (12%) it seems to be less than 1%

**How it should work:** 
Drop rate should be higher.

**Source (you should point out proofs of your report, please give us some source):** 

Killed arround 30+ in 1 hr and just got 1 drop on all the mountainside.

**Comment by Dootz** [comment]
will be fixed with next server update
