### ISSUE TITLE
[Quest][Northend] Bring Down Those Shields

### ISSUE THREAD

**Issue by Exorcista** [SunwellTracker/issues#1549]
**Decription:** 
**Quest:** http://www.wowhead.com/quest=11396/bring-down-those-shields

Look at the button on the side of the controller here. I bet if you got close enough to one of those scourging crystals, you could use the controller to bring its shield down. Then it would simply be a matter of destroying the thing before its shield goes back up.

What do you say, <name>? You up for it? I can guarantee a nice reward for you if you can bring down those shields and destroy the crystals.

It's the least we can do to keep the Scourge from making more of their own kind.

**How it works:** 
Upon using the item given to you near the crystal they don't get destroyed.

**_

> EDIT: You need to kill the crystal via melee attacking it, if your pet kills it you wont get credit.

_**

**How it should work:** 
crystals should be destroyed once you use the item

**Comment by Dootz** [comment]
http://www.wowhead.com/item=33960/scourging-crystal-controller
> Use: Deactivates the shield protecting a scourging crystal. You must target and get within 10 yards of the crystal to use the controller.

https://youtu.be/r0AAsi7K1fk?t=11s
As you can see in the video and from a quote above, what this item does is that it only removes a shield from the crystal. You need to destroy it yourself.
