### ISSUE TITLE
Quests Bug :(1) Mystery of the Infinite and (2) That which creates can also destroy

### ISSUE THREAD

**Issue by XBT31** [SunwellTracker/issues#155]
Decription: 
Two quests from dragonblight

How it works: 
(1) you defend an object against waves of enemies but the quest does not complete
(2) The wyrm part doesnt work, The wyrms are already in weakened state before using the object so they cannot be grounded
How it should work: 
(1)After the last wave + dialogue the quest is complete
(2) The Item should turn the wyrm in weakened state and ground it (like it works for the 2 other mobs of this quest.
Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
I just did Mystery of the Infinite and it completed for me just fine after finishing all waves including the Elite NPC.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
