### ISSUE TITLE
[Quest][Northrend] Ruby Dragonshrine attackers are not attacking automatically

### ISSUE THREAD

**Issue by nycheia** [SunwellTracker/issues#1551]
Description: 
Ruby Dragonshrine quests

How it works: 
The Frigid Abomination/Ghoul/Geist Attackers are not attacking npcs automatically, and spawn inside cliffs. Possibly too few geists as well, i could only spot two in the entire area.

How it should work: 
Should attack and move automatically, and not spawn inside cliffs. Possibly more geist spawns

Source (you should point out proofs of your report, please give us some source): 
https://prnt.sc/jwfyya
https://prnt.sc/jwfz62

**Comment by Dootz** [comment]
will be fixed with next server update
