### ISSUE TITLE
  [Bloody Breakout]

### ISSUE THREAD

**Issue by Gewber** [SunwellTracker/issues#1553]
Decription: 
The alarms have been sounded. The High Inquisitor and his acolytes will be here soon. I'm too badly injured to be of much use, but I'll do what little I can to help.

Slay the High Inquisitor and his cronies. Tear off his head and return with it to Thassarian. Vengeance will soothe his savage soul.

One more thing, <name>. If you do manage to survive and make it back to Thassarian, tell him that they're executing prisoners at the chapel. Perhaps he'll send you there to play the hero once more.
How it works: 
Adds should spawn coming down the starirs.

How it should work: 
No adds are spawning including the NPC that needs to be killed for quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
should be ok now.
