### ISSUE TITLE
Borean Tundra Oiled Wolves

### ISSUE THREAD

**Issue by Draxgard** [SunwellTracker/issues#1554]
Decription: 
Powerleveling for every players 

How it works: 
https://www.youtube.com/watch?v=j6FoT9rLVqQ&feature=youtu.be

How it should work: 
Wolves should attack without following you to eternity and bug your combat state.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
