### ISSUE TITLE
Death Grip animation bug

### ISSUE THREAD

**Issue by Flobberz** [SunwellTracker/issues#1555]
Decription: 
Death Grip sometimes bugs out, teleporting the gripped person to you after a delay.

How it works: 
https://clips.twitch.tv/LachrymoseOnerousJellyfishTBTacoRight
https://clips.twitch.tv/FitLovelyDillRickroll

How it should work: 
https://clips.twitch.tv/AmorphousObliviousCrocodileTheThing
https://youtu.be/BYK6OkFwbv8?t=3m58s Video from retail WOTLK

Source (you should point out proofs of your report, please give us some source):

**Comment by jedrekx92** [comment]
I's visual bug and appears very often with most gap closers.
