### ISSUE TITLE
[Rogue] Instant Poison Procrate not normalized for weapon speed

### ISSUE THREAD

**Issue by Swellzong** [SunwellTracker/issues#1556]
Decription: 
Instant poison procs are not normalized per minute. Instead a faster weapon yields more procs than a slower weapon.

How it works: 
For instance :a 1.4 speed weapon procs more instant poison procs per minute than a 2.6 speed weapon.

How it should work: 
A 1.4 speed weapon should proc the same amount of instant poison procs as a 2.6 speed weapon.
Instant poison should be normalized to procs per minute and not based on speed.

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
To add a source here:
http://wowwiki.wikia.com/wiki/Instant_Poison

Yes, the ppm should be the same, regardless of weapon speed.

Do you maybe have any screenshots (Recount) of the current situation?

**Comment by TheBigBallsOfFury** [comment]
Already been abused since day 1 double LPC build

**Comment by Swellzong** [comment]
![instant_poison_test_2 6](https://user-images.githubusercontent.com/40440902/41809636-4820bcd8-76f1-11e8-85f0-4563f833635a.png)
![instant_poison_test_1 4](https://user-images.githubusercontent.com/40440902/41809637-48389d8a-76f1-11e8-93a0-9eadba99b956.png)

After testing this does not seem to be bugged. This can be closed, sorry for wasting your time.
