### ISSUE TITLE
Wailing Caverns, last boss encounter spawns adds too fast

### ISSUE THREAD

**Issue by Johnnii** [SunwellTracker/issues#1557]
Decription: The last part of Wailing Caverns involve an NPC starting a RP event in which 2 waves of mobs spawn (first serpents and then slimes) and then a boss (Mutanus the Devourer).

How it works: The second wave of mobs (slimes) spawns almost immediately after the first (serpents), making it an unreasonably hard encounter for a party of appropiate level.

How it should work: The second wave should spawn a short time after the first wave has been defeated, giving a group at least a short time to recuperate.

Source (you should point out proofs of your report, please give us some source): 
Here is a video from 2009 on retail showing the fight:
https://youtu.be/lFLzpKnfv8A

**Comment by Dootz** [comment]
will be fixed with next server update
