### ISSUE TITLE
Shadowmeld

### ISSUE THREAD

**Issue by Zaurox** [SunwellTracker/issues#1560]
Decription: 
Shadowmeld doesn't repel attackers

How it works: 
You go into Shadowmeld but all the mobs keep attacking you, ranged mobs might stop attacking but melee always continue

How it should work: 
All mobs should stop attacking you and you should go out of combat when using Shadowmeld

Source (you should point out proofs of your report, please give us some source): ![wowscrnshot_062118_083026](https://user-images.githubusercontent.com/29898919/41701679-9a759dfc-752d-11e8-8189-85c3bf861437.jpg) Note on the combat log how I keep getting attacked after casting Shadowmeld

**Comment by Zerozorg** [comment]
Thats because they "spot" you immediatly, what you do is keep distance and then shadowmeld and lose combat
