### ISSUE TITLE
Double spanwed NPCs

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1562]
Decription: There are some npc that spawned multiple times 

How it works: You can see in the screenshot.

How it should work: There should be one of each.
![wowscrnshot_062118_100742](https://user-images.githubusercontent.com/37425406/41706159-5b55c134-753b-11e8-8f9a-efffa920b5af.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
