### ISSUE TITLE
Minor NPC animation bug

### ISSUE THREAD

**Issue by jagaren** [SunwellTracker/issues#1564]
Decription: 
The Emerald Lashers in Emerald Dragonshrine in Dragonblight stay underground even after being attacked.

How it works: 
They stay underground during combat except to attack, and dying.

How it should work: 
when aggroed they should sprout up and stay above ground while in combat.

https://youtu.be/Hv9FFJIUneE?t=64

**Comment by Dootz** [comment]
will be fixed with next server update
