### ISSUE TITLE
[Ulduar] [Mage] [Abilities] Yogg Saron Brain Room Blink not working

### ISSUE THREAD

**Issue by gabbat** [SunwellTracker/issues#1566]
Decription: 
You can not use Blink in the brain room of yogg saron. It gets cast, but it does not move you forward.

How it works: You can not use Blink in the brain room of yogg saron. It gets cast, but it does not move you forward.

How it should work: Blink should be working normally, it feelsl like the brainroom is not proper scripted as a movement terrain or something.

Source (you should point out proofs of your report, please give us some source): 
mages usually dont enter the brainroom as they suck in there, so finding a video as a source is quite impossible, but I think its clear, that blink should be working in there and not be in the current bugged state where it gets casts but doesnt do anything

**Comment by Kokaina** [comment]
Blink, Shadowstep and warlock's Teleport were working in Brain's Room after 3.2 patch.

"Wrath of the Lich King Patch 3.2.0 (2009-08-04): Players can now use  [Blink],  [Shadowstep], and Demonic Teleport while participating in the illusion events in the Yogg-Saron encounter."
