### ISSUE TITLE
Visual cart bug

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1568]
Decription: Quest is doable, but there's a minor visual bug.

How it works: Upon releasing the cart, cart stands still and doesn't start moving towards the entrance.

How it should work: When you release it with the key you pick up from Captian Jacobs, cart should start moving towards the entrance.
![wowscrnshot_062218_094003](https://user-images.githubusercontent.com/37425406/41764197-adfe2b4a-7600-11e8-9f8c-fc6d57787d56.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
