### ISSUE TITLE
Random Instance Completion

### ISSUE THREAD

**Issue by Adamosky** [SunwellTracker/issues#1569]
Decription: 
Upon completion of SM Armory, the bonus experience upon completion is not distributing the XP, nor is it saying complete.

How it works: 
Upon killing of final boss; No Random Instance completed XP gain

How it should work: 
Upon killing of final boss, random instance XP should be gain

Source (you should point out proofs of your report, please give us some source):

**Comment by nimeral** [comment]
It just happens time to time (very rarely, as it seems to me). I've reported it on https://github.com/SunwellTracker/issues/issues/55; 've no idea what triggers the bug.
