### ISSUE TITLE
Quest - Fervor of the Frostborn

### ISSUE THREAD

**Issue by Trsko** [SunwellTracker/issues#157]
Decription:  
Yorg Stormheart at Frosthold has requested that you speak to Fjorlin Frostbrow to secure a ride and face  your challenge.

How it works: 
You speak to Fjorlin and get a mount with a dwarf on it, but you cant jump on it but you can summon infinite birds.

How it should work: 
You should be able to jump on.

Source (you should point out proofs of your report, please give us some source):  Quest log is the source

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.

**Comment by Dootz** [comment]
Will be fixed with next server update
