### ISSUE TITLE
Missing loot from last boss of blood furnace heroic

### ISSUE THREAD

**Issue by metalbaneb** [SunwellTracker/issues#1570]
Decription: Ive been doing Keli´dan de Breaker heroic (npc 17377) for 2 months, trying to get the Leggings of the Unrepentant (id 27514) with no luck, that seemed strange to me, so checked with a gm and yes, seems that the item is missing on the table.

How it works: After more than 40kills the pants didnt drop.

How it should work: it should be in the loot table.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_062218_114242](https://user-images.githubusercontent.com/40489435/41770464-958985ac-7612-11e8-8143-07f1e29ea9f0.jpg)

**Comment by Dootz** [comment]
I got them on16th attempt. It's one of 12 blue items that can drop so you have around 8% to get them. I'll ask Nadir to check again.

![obraz](https://user-images.githubusercontent.com/25490436/41771198-9bc8162a-7614-11e8-92bd-1adbcbbf5a02.png)

**Comment by metalbaneb** [comment]
thank you for checking it again, seems a problem of bad luck xD anyway in atlas is showed 13,65% drop, maybe a bad data.

**Comment by metalbaneb** [comment]
ty for the check, hope for the drop in the coming days!
