### ISSUE TITLE
[Ashenvale] Mob Ikrud Magthrull and his Succubus Minion deal too much damage

### ISSUE THREAD

**Issue by cmhernandezdel** [SunwellTracker/issues#1571]
Decription: They have to be killed in orden to complete the quest "The Tower of Althalaxx", they are level 24 both, and them and the Felslayer near them (level 22) deal absurd amounts of damage (400 or so per hit at level 24). 

How it works: Succubus Minion and the nearest Felslayer deal too much damage, about 400 per hit which makes you dead at level 24 in three hits at most.

How it should work: They should deal much less damage.

Source (you should point out proofs of your report, please give us some source): Just the steps to reproduce: go to Ashenvale subzone Fire Scar Shrine, fight them, they deal too much damage.

Additional information:
The NPC: http://db.darkwizard.pl/?npc=3664
His minions aren't in the DB.

**Comment by Dootz** [comment]
will be fixed with next server update
