### ISSUE TITLE
[Borean Tundra] Lupus Pupus

### ISSUE THREAD

**Issue by lippincott25** [SunwellTracker/issues#1572]
Decription: Bug with the neutral/friendly interaction of the mobs in this quest.

How it works: The Oil-stained wolves stay friendly(green) when the Wolf Bait is thrown at them.

How it should work: The Oil-stained wolves in this quest are suppose to turn neutral (killable by horde or alliance) when you throw the Wolf Bait at them. 

Source (you should point out proofs of your report, please give us some source): 
http://youtu.be/BBt5omqHwgY

http://wowhelperz.blogspot.com/2013/07/lupus-pupus-wow-quest-in-borean-tundra.html

**Comment by Dootz** [comment]
will be fixed with next server update
