### ISSUE TITLE
[Arathi Basin Quests] Arathi Basin Resources! / Cut Arathor Supply Lines!

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#1573]
Decription: There are faction-specific Arathi Basin quests that should no longer be in game.
Alliance quest is Arathi Basin Resources! (there are different versions of this quest depending on player's lvl)
1) (https://db.darkwizard.pl/?quest=8155)
2) (https://db.darkwizard.pl/?quest=8156)
3) (https://db.darkwizard.pl/?quest=8154)
4) (https://db.darkwizard.pl/?quest=8080)
5) (https://db.darkwizard.pl/?quest=8297)

Horde equivalent is Cut Arathor Supply Lines!
1) (https://db.darkwizard.pl/?quest=8162)
2) (https://db.darkwizard.pl/?quest=8161)
3) (https://db.darkwizard.pl/?quest=8160)
4) (https://db.darkwizard.pl/?quest=8123)
5) (https://db.darkwizard.pl/?quest=8299)

How it works: Quests are obtainable, yet no Arathi Basin Mark of Honor (https://db.darkwizard.pl/?item=20559) is created upon winning AB (and should not be), hence it is impossible to be completed.

How it should work: These quest should not be obtainable.

Source (you should point out proofs of your report, please give us some source): 
1) Patch 2.4.0 (2008-03-25): Removed. (http://wowwiki.wikia.com/wiki/Quest:Arathi_Basin_Resources!_(level_60))
2) Patch 2.4.0 (25-Mar-2008): Removed. (http://wowwiki.wikia.com/wiki/Quest:Cut_Arathor_Supply_Lines_(level_60))

**Comment by Dootz** [comment]
will be fixed with next server update
