### ISSUE TITLE
Quest: Lightning Infused Relics - Not working as intended

### ISSUE THREAD

**Issue by Freazi** [SunwellTracker/issues#1574]
Decription: You are 'forced to get into a Iron Rune Construct and explore a cave and collect some data.
When i entered the cave and tryd to collect data from a crystall (2nd ability of the Construct) i flew through the area to the point where i started.

How it works: 

How it should work: This is a YouTube video of someone doing it. https://www.youtube.com/watch?v=cerT_kHn2xw

Source (you should point out proofs of your report, please give us some source): this is a video i made about that issue : https://streamable.com/n6rey

**Comment by Azathothh** [comment]
It will only happen if you've used lift while controlling vehicle (iron rune construct). You should be fine as long as you don't step on any elevators/lifts.
Already reported here : https://github.com/SunwellTracker/issues/issues/1494
