### ISSUE TITLE
Krecenie a disease'y

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#1576]
Decription: Wystepuje ciekawy bug, mainowicie podczas krecenia flagi czy to na ab czy eots(podejrzewam ze jesli chodzi o skrzynki oraz inne obiekty, to rowniez) jesli dostaniemy dp od preja lub innego hiva od dk to niemozliwoscia jest przekrecenie obiektu, nawet po smierci rzucajacego co niezwykle utrudnia rozgrywke, idk czemu jeszcze nikt tego nie zglosil :D Jesli chodzi o inne debuffy typu magic czy curse to rzecz niewystepuje. Ponadto zdaje sie ze dnd od dk tez przerywa. Nie mam dowodow, musicie mi uwierzyc na slowo :D Nie mam tez dowodow ze tak byc nie powinno, chociaz wydaje sie to oczywiste. Jesli sie myle mozna zamknac ;> Pozdroweczki.

**Comment by Akha72** [comment]
DP should interrupt flag capturing if specced into Improved DP, DnD should interrupt when it initially hits a player.

**Comment by Szelmon556** [comment]
okay so u can close the topic, but i think it really makes no sense ;d
