### ISSUE TITLE
[Item] Meteorite Crystal

### ISSUE THREAD

**Issue by lorderheller** [SunwellTracker/issues#1578]
**Description:** At the moment trinket procs do not work correctly.

**How it works:** You get procs from casts from your spells, if I use Beacon of Light on another target I still get 1 proc.

**How it should work:** Should get 2 procs with Beacon of Light.

**Source:** http://www.wowhead.com/item=46051/meteorite-crystal#comments

Lots of comments stating it should give 2 procs with each Beacon of Light cast.

**Comment by Kokaina** [comment]
High prio thing.

**Comment by baseswotlk** [comment]
It is BiS when working correctly. Plz fix :)

**Comment by Kokaina** [comment]
Fixed and implemented.
