### ISSUE TITLE
Meta gem ignoring Belt buckle

### ISSUE THREAD

**Issue by Platinumcoated** [SunwellTracker/issues#1579]
**Gem socketed into Eternal Belt Buckle doesn't contribute towards Meta gem.**

If the Meta gem requirement is fulfiled with regular sockets from items, then the Meta gem shows that it's active (text is white) and it works (it gives bonuses).

If the Meta gem requirement is fulfiled with the need of a gem from an Eternal Belt Buckle, then the Meta gem shows that it's active (text is gray), but it doesn't work. Player does neither receive +stats, nor the special effect (I use minor speed and I can tell the difference in running animation).

Actual items used:
**Tireless Skyflare Diamond** meta gem
https://db.darkwizard.pl/?item=41375
**Eternal Belt Buckle** +extra socket into waist
https://db.darkwizard.pl/?item=41611
**Quick Autumn's Glow** yellow gem
https://db.darkwizard.pl/?item=40017

pics:
https://imgur.com/a/CejixrD

**How it should work:** 
Gems socketed into Eternal Belt Buckles should count towards Meta gem requirements, as stated by several sources.

**Source:**
http://www.wowhead.com/item=41611/eternal-belt-buckle
several comments state that
http://wowwiki.wikia.com/wiki/Eternal_Belt_Buckle
"Gems added to the socket will not help you achieve the color match bonus of the item, however they do contribute towards activation of a Meta gem."

**Comment by Riztazz** [comment]
Whats your current waist, does it have any socket slots by default (without eternal buckle)

**Comment by nimeral** [comment]
It actually works well now, https://imgur.com/a/6MYaqm1

**Comment by Platinumcoated** [comment]
**Not working on Frosthold now**

personally I haven't tested the fix back on Angrathar, but now on Frosthold it doesn't work

pics:
https://imgur.com/a/sbx6eOw

btw a small typo in original post:
"then the Meta gem shows that it's active (text is **gray**)" should have written WHITE
