### ISSUE TITLE
Can't use Barkskin in Psychic Horror

### ISSUE THREAD

**Issue by buffdkplz** [SunwellTracker/issues#1580]
Decription: Can't use Barkskin in Psychic Horror

How it works: Can't use Barkskin in Psychic Horror it says can't do that while stunned.

How it should work: You should be able to use barkskin in every stun.

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
"This spell is usable while stunned, frozen, incapacitated, feared or asleep."

Psychic Horror is an Horror-effect. Do you have a source/video?

**Comment by buffdkplz** [comment]
please just don't talk if u have no clue @ujellyx psychic horror causes 2 debuffs 1 stun and 1  that mechanically horrifies which is a dissarm

**Comment by ujellyx** [comment]
![2018-06-23 19_05_00-window](https://user-images.githubusercontent.com/17804807/41811904-8812dd68-7718-11e8-9739-00267d2129dd.png)
The "Stun" is just the visual aura, as in you can't move or do anything. The Mechanic of the CC-part of the spell is the important part, which is obviously "Horrified" and not "Stunned". You can see this fact in several spell-databases.

The disarm-part of the spell has the "disarmed" mechanic.

The fact that you report something, that isn't even bugged without any proof and that it gets falsely fixed is just ridiculous...

**Comment by buffdkplz** [comment]
pls dont be that annoying you made me waste 15min of my time finding a video from retail wotlk for proof https://www.youtube.com/watch?v=ugWy53u1EVk

**Comment by buffdkplz** [comment]
btw you got you spellinfo from the wrong expansion @ujellyx . "cost: 30 insanity"
