### ISSUE TITLE
Warrior: Heroic Strike/Cleave gets canceled while Bladestorming

### ISSUE THREAD

**Issue by Vertaz** [SunwellTracker/issues#1581]
Decription: 
Heroic Strike/Cleave gets canceled while Bladestorming

How it works: 
Heroic Strike/Cleave gets canceled while Bladestorming

How it should work: 
Heroic Strike/Cleave should not get canceled while Bladestorming. Its key factor to managing rage while using Bladestorm...

Source (you should point out proofs of your report, please give us some source): 

I swear if someone writes link source again I will gather everyone from Old AT community who played on Sunwell to confirm here that most basic things that should be working and were working on AT 7+ years ago are and will be broken here because of your Bugtracker politics. So many mistakes lately that I see, Reddit people are not as stable players as Polish players. Lordaeron was far more proffesional server in terms of development and look what happened to them, and they were fixing stuff constantly. Its your job to confirm source/you should already know if its bug or no. There were people capable of making retail like client with close to zero bugs, finding almost everything themselves and testing any minor bug that was reported in matter of hours from topic start. I reported 6 just for Arms spec, 0 were fixed. I dont even want to report the other bugs, since it will get closed anyway.

**Comment by ujellyx** [comment]
Yeah, on retail you could "queue" heroic strike or cleave before using bladestorm in order to get off the hs/cleave during the bladestorm.

I'll help you out with a source:
http://www.arenajunkies.com/topic/102151-queuing-cleave-before-bladestorm/

What should not be possible is to use/queue hs/cleave while already in bladestorm. This one should be self-explanatory.

**Comment by lukaasm** [comment]
https://streamable.com/8g1p9
Seems to work fine, maybe issue was related to: #1458?

**Comment by ujellyx** [comment]
@lukaasm unfortunately OP meant something different. The heroic strike/cleave should deal damage during the bladestorm when it's queued before the bs.

**Comment by lukaasm** [comment]
For reference:
https://www.youtube.com/watch?v=a3eoR8l4ndc
