### ISSUE TITLE
[Shadowmoon Valley] Infernal Attacker spawns in air and is flying

### ISSUE THREAD

**Issue by Bombowiec** [SunwellTracker/issues#1582]
**Decription:** Infernal Attacker in Wildhammer Stronghold at (35,52) spawns in air and can't land.

**How it works:** Mobs spawn animation (falling meteor) stops in air and minion is spawned here and is bugged, so it is flying.

**How it should work:** Spawn animation should end hitting the ground and mob should be spawned there.

**Source** (you should point out proofs of your report, please give us some source): http://prntscr.com/jyfxdl

**Comment by Dootz** [comment]
will be fixed with next server update
