### ISSUE TITLE
[Item] Totem of Spirits (ID: 30094) following instead of being stationary

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#1584]
Decription: 
The above mentioned item should be stationary when you use it.

How it works: 
The with the quest item summoned Totem of Spirits is following the player like a companion/pet.

How it should work: 
The totem should be stationary and stay at where one has used it.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=LKFejOWZ_X8

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by ujellyx** [comment]
It's still moving.

**Comment by Dootz** [comment]
will be fixed with next server update
