### ISSUE TITLE
Doctor Weavil from Alcaz island

### ISSUE THREAD

**Issue by Bugadin** [SunwellTracker/issues#1585]
Decription:  Doctor Weavil doesn't use spells or loot

How it works:  Doctor Weavil just stands in front of you and he hits you, he doesn't use any spells and he doesn't drop anything.

How it should work:  He should use mind control and he should drop his diary I guess

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Doctor_Weavil

**Comment by Dootz** [comment]
will be fixed with next server update
