### ISSUE TITLE
[Angrathar] Torch Tossing Quests

### ISSUE THREAD

**Issue by Somethingideally** [SunwellTracker/issues#1587]
Description: 
You  can complete quests unlimited times (and get 7 gold per catching quest)
http://www.wowhead.com/quest=11731/torch-tossing
http://www.wowhead.com/quest=11657/torch-catching
How it works: 
Complete quests => Logout => Login => Complete quests

How it should work: 
Complete quest => And get only daily quests with less reward
Source (you should point out proofs of your report, please give us some source): 
Just try it in game)

**Comment by Dootz** [comment]
done
