### ISSUE TITLE
Elemental focus doesnt seem to proc

### ISSUE THREAD

**Issue by jockeboschko** [SunwellTracker/issues#1588]
Decription: 
Elemental focus the trinket does not seem to proc for my fire mage.

How it works: 
DOesnt proc

How it should work: 
On harmful spells it should proc the haste buff

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?item=45866

**Comment by Cwiercpasiec** [comment]
It proced for me after 3rd tick of living bomb:

![wowscrnshot_062518_165906](https://user-images.githubusercontent.com/26198742/41858203-8ddecb30-7899-11e8-8eef-a502a39024c6.jpg)

Tested on PTR.

**Comment by jockeboschko** [comment]
mby a visual glitch on the cd when it procs in character tab.
