### ISSUE TITLE
[quest corrupted sabers, Felwood]

### ISSUE THREAD

**Issue by Urghan** [SunwellTracker/issues#1589]
Decription: 
Quest nie zostaje zaliczony po wykoaniu

How it works: 
Po przyprowadzeniu kota do NPC quest dalej zostaje nie zaliczony

How it should work: 
Po Przyprowadzeniu kota do NPC quest powinien byc zaliczony

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
po podejściu do npc, należy porozmawiać z kotem którego się prowadzi. Jeśli znajdujemy się w zasięgu 5 y od npc do którego prowadzimy kota powinna pojawić się u kota opcja dialogowa która zaliczy quest.
