### ISSUE TITLE
Arena Group Q in Grizzly Hills

### ISSUE THREAD

**Issue by Vlnkaj** [SunwellTracker/issues#159]
Decription: 

All Q from this chain http://www.wowhead.com/quest=12431/the-conquest-pit-final-showdown .

How it works: 

Only guy who do killing blow on mob will complete Q, so you have to repeat it 3times.
How it should work: 

When you kill mob all party members should be able to get complete Q.

Source (you should point out proofs of your report, please give us some source): 

Dont have proof. Common sense.

**Comment by Afgann** [comment]
Will be fixed with next update.
