### ISSUE TITLE
[Midsummer event] Quests and bonfires refreshing/bugging out

### ISSUE THREAD

**Issue by RealKlayton** [SunwellTracker/issues#1592]
Description: 
flame warden quests and bonfire have rested at least twice now, which is breaking the event's quests. Stole Ogrimmar and Thunderbluff fires yesterday, came today to hear from guildies that like 70% of bonfires are usable again, and after I stole other 2 fires today (UC and Silvermoon) I didn't get the final quest that allows me to get the achievement [King of the fire festival]. Went back to Ogri to take the flame again, but now I can't use the Ogri flame (Flame of Orgrimmar), says 'you are already on that quest' (pic added)

How it works: 
If you didn't get all 4 flames between the resets - you can't obtain the last quest.

How it should work: 
You should be able to steal 4 flames, give them back via quest they give to NPC in Shattar and get the final quest -"a thief's reward"

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=9365

P.S.: also flames do refresh as shown in second screenshot, but can't be bothered to make another report =\

![wowscrnshot_062518_003743](https://user-images.githubusercontent.com/40548952/41824135-33f647c2-7814-11e8-9a3b-3aed734966f7.jpg)

![wowscrnshot_062518_012750](https://user-images.githubusercontent.com/40548952/41824458-d7edff88-7818-11e8-9b3c-ba2efbb93f98.jpg)

**Comment by Dootz** [comment]
should be fixed now.
