### ISSUE TITLE
Weapon Skill

### ISSUE THREAD

**Issue by Gewber** [SunwellTracker/issues#1594]
Decription: 
Currently I am trying to level my two handed mace weapon skill, but it will not level off any mobs.  I am trying to level my weapon on the target dummies at Ebon hold, but even then...I get one skill. then have to leave combat and swing again. Not working as intended.

How it works:  Gains weapon skill based off level of npc, level of character, and what you are using

How it should work: 
each swing has a chance to level weapon skill.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
To level up weapon skill you must attack mobs at similar level to your (it can't be gray, must be green at least - for lvl 80 minimum was mob lvl 73 or something near that). They must give experience as well, so you can't do that on target dummies.
Not a bug.
