### ISSUE TITLE
Mid summer event - Torch juggler's achievement

### ISSUE THREAD

**Issue by Bugadin** [SunwellTracker/issues#1595]
Decription: 
The juggling torch is bugged, you can throw it where ever place but you won't be able to catch it again so you can't complete the achievement.

How it works:  If you throw the torch it just looses from your bag.

How it should work: When you throw the juggling torch you should be able to retake it again.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?item=34599#reward-from-quest

**Comment by Dootz** [comment]
Should be fixed now. Please check if you can pick up again quest Torch Juggling at Midsummer camp. After you complete this quest, you'll be able to catch torches.
