### ISSUE TITLE
[Paladin Spell] Hand of Freedom

### ISSUE THREAD

**Issue by jedrekx92** [SunwellTracker/issues#1597]
Decription: 
http://db.darkwizard.pl/?spell=1044
http://db.darkwizard.pl/?spell=14311
HoF is paladin spell that grants immunity to slowing effects. Can be cast on friendly targets or self.
Should be able to cast while stuned or incapacated.

How it works: 
HoF can't be used in Freezing Trap

How it should work: 
HoF should work while being under Freezing Trap effect on self and friendly targets.
![hof trap](https://user-images.githubusercontent.com/40339532/41910460-000bd8a0-794a-11e8-955e-dc6055720350.png)

http://www.warcraftmovies.com/movieview.php?id=135033  - 20:55

Source (you should point out proofs of your report, please give us some source):

**Comment by jedrekx92** [comment]
works fine now

**Comment by Azathothh** [comment]
Duplicate #846
(+ it's already fixed)
