### ISSUE TITLE
[Paladin Spell] Hand of Freedom

### ISSUE THREAD

**Issue by jedrekx92** [SunwellTracker/issues#1598]
Decription:
http://db.darkwizard.pl/?spell=1044
http://db.darkwizard.pl/?spell=20066
HoF is paladin spell that grants immunity to slowing effects. Can be cast on friendly targets or self.
Should be able to cast while stuned or incapacated.

How it works:
HoF can't be used in Repentance

How it should work:
HoF should work while being under Repentance effect on self and friendly targets.
http://www.warcraftmovies.com/movieview.php?id=247086 - 7:45
![hof rep](https://user-images.githubusercontent.com/40339532/41911140-17e792dc-794c-11e8-84ac-f51417622a19.png)

**Comment by Azathothh** [comment]
Duplicate https://github.com/SunwellTracker/issues/issues/846
(+ it's already fixed)
