### ISSUE TITLE
Charge bug

### ISSUE THREAD

**Issue by HuMa69** [SunwellTracker/issues#160]
Decription: if you charge a moob or character above a mountain or a mound you fall throught to floor and die

How it works:  if you charge a moob or character above a mountain or a mound you fall throught to floor and die

How it should work: not falling through the floor

Source (you should point out proofs of your report, please give us some source):

**Comment by HuMa69** [comment]
im still falling throught the floor if i charge someone below a mound, are you going to fix this?

**Comment by sitowsky** [comment]
#46
