### ISSUE TITLE
[Core?] Swing timer internal CD when dual wielding working incorrectly

### ISSUE THREAD

**Issue by Voldraek** [SunwellTracker/issues#1601]
Decription: 
The delay inbetween autoattacks when dual wielding should only apply when opening on a target. However, it is instead applying on every swing.

How it works: 
When an autoattack is performed on a target, it stops any other autoattack from occuring in the next ~0,15-0,3 seconds.
See https://www.youtube.com/watch?v=6x-UyV5dLyc&list=UUiFGHxImcckC-6TghyFJ91Q (Apologies for the poor resolution).
In this particular case, what's being used is a 3,5 speed main hand and a 3,3 speed offhand.
As you can see from the swing timer, what happens is that:
1: The main hand hits
2: ~0,25 sec later, the offhand hits
3: When the attacks become ready again, what should occur is a main hand hit, followed by an offhand hit ~0,05 sec later.
4: What instead happens is that the main hand hits and triggers the ICD of 0,25 seconds. The offhand hits after the 0,25 seconds.
5: As such, the swings never "desync" from eachother, despite being different speeds. In practice, it acts as if the offhand has a 3,5 speed instead of a 3,3.

As can be seen in the combat log based on the damage dealt per melee, it's always the main hand followed by the offhand hitting.

How it should work: 
This is unfortunately rather unclear as I haven't managed to find a source of the correct mechanics.
From personal experience on other servers, the AA delay should only apply the very first time you start autoattacking an enemy, only - and always - resetting when you leave combat.
This also means that if you pause your melee by starting up and then cancelling e.g. a Slam or Lightning bolt before the melee hits, the melee hits will happen at the exact same time
An overly simplistic video example would be the autoattacks acting like they do on https://www.youtube.com/watch?v=rcnl0HiBdJQ, where they act independently.

Source (you should point out proofs of your report, please give us some source): 
See above, unfortunately not much hard evidence on how exactly it's supposed to work. I cannot imagine that it should work like it does as there definitely should be some discussion regarding it online then, however I'm not finding any of the such. Nor do I have access to a retail account but I'd imagine it should be possible to see how retail is working now - I doubt it will have changed very much over the years.

**Comment by mercred** [comment]
What is the addon are you using for showing dual-wielding swing timer? I would love to test it as well with it.

**Comment by Voldraek** [comment]
Attack Bar Timer
