### ISSUE TITLE
Hodir adds bugged, not frozen and doesnt cast buffs

### ISSUE THREAD

**Issue by Catrex** [SunwellTracker/issues#1602]
Decription: 
As tittle said, adds bugged and are not frozen, however they do not give the buffs they normally do

How it works: 
Cant break out adds, they just stand still

How it should work: 
Break out adds, get buffs get gut get HM hodir

Source (you should point out proofs of your report, please give us some source): 

https://gyazo.com/2a4729973d50637902a48b51cf38303f

**Comment by nimeral** [comment]
Can confirm, also can "vote for fixing", this bug is pretty gamebreaking for casual guilds.
