### ISSUE TITLE
The air strikes must continue - Shattered Sun Offensive

### ISSUE THREAD

**Issue by Bugadin** [SunwellTracker/issues#1603]
Decription: The quest requires to kill (with ''arcane charges'') 3 types of mobs mounted in a dragonhawk but it's nearly impossible to score a kill of an Wrath enforcer. I have realized that It would never count because of the way WoW was programmed or something: when you kill an add that is below certain %(which I guess it's 70% or something like that) because other adds are damaging him the death won't count.

How it works: You can score deaths easily on Eredar sorceres and, with some patient, overlord pits but I guess there isn't any much chances for the Wrath enforcers because they spawn and die too fast due to the other adds.

How it should work: I suppose it should count the death at any remaining % of the Wrath enforcer.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
