### ISSUE TITLE
Bugged daily battle ground quest

### ISSUE THREAD

**Issue by Plornt** [SunwellTracker/issues#1604]
Decription: 
I can't pick up quest from alliance brigadier general

How it works: 
When i talk to alliance brigadier general it shows me badge shop and i can't take daily BG quest :(

How it should work: 
It should allow me to show screen where i can choose go to shop for badges or take a quest.
![wowscrnshot_062718_113622](https://user-images.githubusercontent.com/30109102/41962729-6e923652-79fe-11e8-9442-6ef76434e02d.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Vessler** [comment]
I can confirm this. +1

**Comment by ujellyx** [comment]
If I recall correctly the dailies (at least the Call to Arms one) should only be available during CTA (Fr - Mo). The other dailies he offered (Mark of Warsong etc.) weren't possible to complete anymore anyways.

**Comment by Dootz** [comment]
will be fixed with next server update
