### ISSUE TITLE
[Rogue] Stealth - Cooldown Display Bugged If Stealth Activation Is Spammed

### ISSUE THREAD

**Issue by Max0r847** [SunwellTracker/issues#1605]
**Decription:** Stealth cooldown only displays correctly if stealth is activated via 1 clean click or keypress. Any spam whatsoever, invokes cooldown display as if unstealthing. This, of course, is a problem, because nobody doing any advanced play has any time to tenderly time a single keypress, when spam is required to minimize gaps between GCDs, and of course to activate abilities as quickly as possible while the GCD is coming off cooldown.
http://db.darkwizard.pl/?spell=1784

**How it works:** This works exactly the same whether clicking the spellbook, or using a macro. 1 clean activation attempt has no issues. Any spam of the ability whatsoever, whether clicked or keypressed, even if it is via the !Stealth command (impossible to unstealth with it), it will result in displaying the cooldown even while in stealth, which counts down while in stealth. As a result, when coming out of stealth, no cooldown is displayed, and the ability simply appears usable, even though it isn't for the proper cooldown duration.

Tested on Angrathar just now and fully demonstrated beyond any shadow of a doubt:
https://www.youtube.com/watch?v=VgxU1RkBZhM

**How it should work:** The stealth ability cooldown/usability should always properly display regardless of whether stealth was activated via spam or a single click/keypress.

Tested on another server just now where this function seems to work, I was spamming the crap out of it:
https://www.youtube.com/watch?v=PA61kl8FYFo

**Comment by Azathothh** [comment]
Couldn't reproduce it by spamming stealth macro, probably it happens while with high latency, maybe some addons "help" with that as well ( i had 20ms at that moment and all addons disabled).
Could reproduce it only with macro like that:
/cast stealth
/cast stealth

**Comment by Max0r847** [comment]
As requested I have repeated the test with all addons disabled using the spellbook clicking and /cast !Stealth macro method. The same results were obtained.

https://www.youtube.com/watch?v=XODmvm6WbV8

As far as latency goes, my latency is pretty normal in the Americas region it seems. It is true that on the other server it was only 113 ms instead of ~146-149 ms, however, on the other server, I was spamming it super super hard too (both key-up and key-down were activating it) and it was 100% reliable. As far as I know, I'm across the ocean from both realms.

I suspect that sending another stealth command before the original stealth is activated results in this bug. At 20ms, it is a lot more difficult to do that, as it would require sending the equivalent rate of 50 clicks/keystrokes per second.  At 113ms it would require 8.84 clicks per second. At 146ms it would require only 6.85 clicks per second. 7 clicks per second is very easy to achieve without even trying to be a spam hero.

**Comment by ujellyx** [comment]
When you have a non-macro-stealth button and you spam it, it can sometimes put you out of stealth, as the bar-switch is a little delayed and the second press is still recognized on the first (non-stealth) bar. And because it puts you out of stealth, the cooldown occurs of course.

**Comment by Max0r847** [comment]
A very pleasant gift found in my e-mail today indeed :) Works perfectly now
