### ISSUE TITLE
Auriaya - Sanctum Sentry: Rip Flesh stacking after wiping

### ISSUE THREAD

**Issue by Feorblade** [SunwellTracker/issues#1607]
Decription: 

The Sanctum Sentry stacks the rip flesh debuff much faster after wiping on the boss for the first time, making the crazy cat lady achievement annoying to get
if you happen to wipe on the boss.

How it works: 

Watch how slowly the debuff stacks on you during the first attempt of Auriaya (make sure you are only tanking one cat). Then wipe and try again, you will see
the debuff will stack much faster. It might even stack faster and faster the more you wipe.

How it should work: 

This is obviously not how its supposed to work, obviously some server side variables are not reset properly on a wipe.

**Comment by Dootz** [comment]
will be fixed with next server update
