### ISSUE TITLE
Re opening case #1528 because we have proof of how it must be done

### ISSUE THREAD

**Issue by darkpotterxd** [SunwellTracker/issues#1608]
Description: 
Refering to this post: https://github.com/SunwellTracker/issues/issues/1528

Since you said you fixed the issue and are about to test it. Screw it! We have the right numbers now:
http://web.archive.org/web/20091108152029/http://elitistjerks.com/f75/t30655-wotlk_complete_mage_compendium_3_3_ptr/

"4/5 T8 has a 20% proc rate, has no cooldown and can chain proc. It's a 2% boost for Fire/Frostfire, 1% for Arcane, 0.2% for Frost."

further information is on the following pages

I made a new issue in case you didn't catch the new comments from the old bug report (#1528 ) . If you did then I'm sorry. Just wanna get sure you see it. T8,5 4/5 procc chance is 20% confirmed.

**Comment by Azathothh** [comment]
There's no need to create same topics again. Old one is still opened, and even if it was closed you can still write in closed issues... It's fixed, but still needs testing, so it's not on Angrathar yet. When it's "live" you will find info about it in changelog https://sunwell.pl/changelog

**Comment by darkpotterxd** [comment]
Alright I wasn't aware of how it's going on here. By fixed I assume you mean you adjusted it correctly to 20% ?
