### ISSUE TITLE
Resto Druid 4 Pieces Set bonus - Healing too little

### ISSUE THREAD

**Issue by Oeybol** [SunwellTracker/issues#1609]
Decription: 
Resto Druid 4 Pieces Set bonus - Healing too little

How it works: 
I don't know

How it should work: 
4pT8 (as of 3.1.1a).
* Does not crit
* Does not benefit from Glyph of Rejuvenation
* Does not benefit from Genesis talent
* Does not benefit from Gift of Nature talent
* Does not benefit from Improved Rejuvenation talent

Formula: (338+Spellpower*0.37604*1.2)*1.06*1.04

At 3000 SP it will heal for 1865.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item-set=-78/conquerors-nightsong-regalia#comments -  more info can be found in the comments

https://urbad.net/blue/us/17615362654-Resto_Druid_4pc_T8_bugged_Blue_please

http://db.darkwizard.pl/?spell=64760

**Comment by ujellyx** [comment]
We're on 3.3.5 mechanic wise, so it's not bugged. Was already discussed in #1497

**Comment by Oeybol** [comment]
Ulduar state is not in 3.3.5 state mechanic wise (which i find good thing), however druids kinda depend on this to deal with the spikier damage :D so is it possible for it to be reconcidered?

**Comment by ujellyx** [comment]
Ulduar isn't 3.3.5 content-wise. And this realm is only progressive content-wise not mechanic-wise.

**Comment by Oeybol** [comment]
Ulduar
Ulduar will stay pre-nerf. However, some of the encounters are enhanced by our own boosts: Razorscale, XT, Steelbreaker, Mimiron, Freya, Thorim, Vezax, Yogg and Algalon. Every few weeks we’ll slowly revert some of the changes, so when 3.2 hits, Ulduar will be pre-nerf only, without any custom mechanics. A revert of every boss will be announced prior to that. ( http://sunwell-community.com/index.php?/topic/3352-post-ulduar-news/ )

I do think this realm is in a way regressive contente wise (harder as it was in 3.3.5 and even harder as it was in 3.1 prenerv) so maybe the the nerves done to the set bonuses should be regressed as well to be able to deal with it :D

**Comment by ujellyx** [comment]
When this mechanic is being regressed, every other class will complain and want their skills, set-bonusses or whatever regressed aswell. This'd be way too much ...
