### ISSUE TITLE
Flask of the north

### ISSUE THREAD

**Issue by Yikesman** [SunwellTracker/issues#1610]
Flask of the North doesn't prioritize the right stats

Gives me AP instead of SP 

Should prioritize your best stats - in my case SP

https://i.imgur.com/bVlBX8y.jpg

edit: seems to be fixed now

**Comment by Cwiercpasiec** [comment]
Actually it gives random stats on every use, so all you have to do is to drink it utill you get the buff you wanted. Also this seems to be blizzlike:
http://www.wowhead.com/item=47499/flask-of-the-north - here you can read some comments from patch3.x about it.

**Comment by Shaquiloheal** [comment]
I think this flask working wrong. Rolling random stat but i used this item about 50 times today and get only spell power or str (as feral druid with items for feral). I just cant get AP buff. If you want check it write to im in game (the same nick) and we can make test for proof.
