### ISSUE TITLE
Quest - Pushed too far

### ISSUE THREAD

**Issue by rewto** [SunwellTracker/issues#1611]
Decription: 
The quest Pushed too far in Frosthold, Storm peaks is unable to be completed.

When accepting the quest you are mounted on the eagle for the quest Fervor of the frostborn and taken to the Terrace of the makers instead of flown around Engine of the makers on the eagle with combat abilities.

**Comment by xNevan** [comment]
Here is a video of the quest:
https://www.youtube.com/watch?v=vFPZdTT9vZI

Please note that in current state it can be completed, you just have to kill the wyrms on your own.

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by nimeral** [comment]
I think it's bugged, you're getting parachuted off your eagle as soon as you leave the proximity of the questgiver.
