### ISSUE TITLE
[Item] Design: Defender's Twilight Opal - does not seem to drop

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1612]
Decription: 
[Design: Defender's Twilight Opal](https://db.darkwizard.pl/?item=41820) does not seem to drop at all from [Stormforged Artificer](https://db.darkwizard.pl/?npc=29376) and [Stormforged Champion](https://db.darkwizard.pl/?npc=29370).

Other similar recipes with 0.5-2% drop rates like [Design: Accurate Monarch Topaz](https://db.darkwizard.pl/?item=41818) and [Design: Radiant Forest Emerald](https://db.darkwizard.pl/?item=41819) have been dropping within 10-30 kills. But I have been farming hundreds of Stormforged Champion and Artificers and no gem recipe drop.

I have for instance sold over 250 [Relic of Ulduar](https://db.darkwizard.pl/?item=42780) over the course of farming these mobs so that's 400 mobs at least. I also checked auction house and find that it is the most expensive rare cut gem in the market, way above other storm peaks mob cuts.

Source (you should point out proofs of your report, please give us some source): 
I only have my personal anecdote since there is no way I can prove any points about such low drop rate RNG but I am just requesting a developer to check and perhaps confirm that the drop rates are working.

Thank you.

**Comment by Dootz** [comment]
http://www.wowhead.com/item=41820/design-defenders-twilight-opal#comments
> This is one of the four rare JC designs obtainable from certain mobs in Storm Peaks. **These recipes can only be seen by jewelcrafters,** are BoP.

To get it in loot you need to have Jewelcrafting skill on a character. Drop rate is quite low, but it's obtainable.

**Comment by TheBigBallsOfFury** [comment]
I do have JC skill and i HAVE got the other recipes listed in your link. This is the only one that has not dropped in hundreds of mobs killed.

I will continue farming and report if it drops. Don't think it's even possible to be this unlucky.

**Comment by TheBigBallsOfFury** [comment]
No drop yet. Farming Champions for days. Guess I'll just abandon it at this point.

**Comment by Dootz** [comment]
Ok, I'll check it again.

**Comment by Dootz** [comment]
drop chance will be slightly increased with next update

**Comment by TheBigBallsOfFury** [comment]
Thank you :)
