### ISSUE TITLE
[Hunter] Pet doesn't put you in combat

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#1614]
Decription: 
When the pet attacks an enemy it doesn't put you in combat.
This may also effect other pet classes (WL/DK/...)

How it works: 
See above.

How it should work: 
After the player's pet uses a spell on an enemy target or attacks it (even with auto attack) it should put the player in combat.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=40dTivHe4Ts (1:44 Min. mark)

**Comment by TheBigBallsOfFury** [comment]
i believe Sunwell team has expressed that this behavior is intended. They believe the way Blizzard had it working was because it was a bug they could not fix.

**Comment by ujellyx** [comment]
Okay then, guess this issue can be closed.
