### ISSUE TITLE
Rogue class-Blind sometimes makes the enemy walk in place/invulnerable

### ISSUE THREAD

**Issue by Gar4chy** [SunwellTracker/issues#1616]
Decription: The ability 'Blind' isnt working as it should be since the enemy is basically invulnerable while in its effect.

How it works: Rogue 'Blind' has a chance of making the enemy walk in place instead of making them 'wander disoriented' and they cant be targeted during the bug which is quite frustrating in situations where you are in a BG and you have to wait 10 seconds for your glitched blind to expire just so you could kill the enemy.

How it should work: The ability 'Blind' should make the enemy wander disoriented for up to 10 seconds,and with any damage dealt to the target after its usage, it should expire.

Source (you should point out proofs of your report, please give us some source): I really dont have any recorded proof of it actually not working as it should , and i've also never seen that glitch in my experience of playing this game(other then on this server).

**Comment by ujellyx** [comment]
Hm, never happened to me. Any way to reproduce?
