### ISSUE TITLE
Leeway - Melee and Spells

### ISSUE THREAD

**Issue by Triaku** [SunwellTracker/issues#1617]
Description: Currently there is no "moving range leeway" for ranged spells, melee spells & auto-attack.

How it works: There is no "moving range leeway" for ranged spells, melee spells & auto-attack.
https://youtu.be/OUzUFB2hqZo

How it should work: 
When you and your target(player) are moving, the server should allow +2.66 yards to your ranged spells, melee spells & auto-attack.

Source: 
How it's calculated in the 2.4.3 client: http://i.imgur.com/PxKWgdQ.png
Retail: https://youtu.be/_DgUcqXwtwk?t=2m
Corecraft(working): https://www.youtube.com/watch?v=L8WhIo1l8Aw

PS thanks Klimp I copied from your bug report from warmanes bugtracker. Please fix this soon it makes melees a lot worse in PVP.

**Comment by ujellyx** [comment]
Can confirm. As a melee it's even worse with targets, that are running away from you as you basically have to stand inside of them to use your abilities...

If it helps the devs, here's a link to the official trinity github on this issue:

https://github.com/TrinityCore/TrinityCore/issues/17818

**Comment by Triaku** [comment]
This also applies to instant Aoe spells, in a little different way though. For example, instead of it being player and target are running, It's only player running that adds a 2.66 yard range. This allows you to get Psychic Scream off in arena a LOT easier.

**Comment by Triaku** [comment]
Not fixed, Auto attack leeway is not working yet.

**Comment by Kokaina** [comment]
@Afgann check it for aa as well, please.
