### ISSUE TITLE
[Quest] The Mosswalker Savior

### ISSUE THREAD

**Issue by turkhero** [SunwellTracker/issues#1619]
Decription: 
 [The Mosswalker Savior] id:12580

How it works: 
Dont work cant speak with Mosswalker Victim

How it should work: 
https://www.youtube.com/watch?v=hd3BcCSDNr4
http://db.darkwizard.pl/?quest=12580

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, 
is there a chance that you were in a raid group or bg group when you were trying to interact with them?
Few people reported it before, but after second check it worked well:
https://github.com/SunwellTracker/issues/issues/1239
https://github.com/SunwellTracker/issues/issues/794

**Comment by turkhero** [comment]
Hi Dootz, Thanks for reply.
I solve my issue.
You cant talk with any of Mosswalker Victim when you are "At War" with "The Oracles" faction.
