### ISSUE TITLE
Quest - If he cannot be turned (Icecrown)

### ISSUE THREAD

**Issue by Trsko** [SunwellTracker/issues#162]
Decription: 
Defeat General Lightsbane and  then report your success back to Thassarian aboard the gunship, The Skybreaker. https://wotlk-twinhead.twinstar.cz/?quest=12896

How it works: 
He hits like a train, its not a group quest and the 3 helpers you get taunt him and should keep him aggroed the whole fight, but they die since hes all roided up

How it should work: 
The 3 undead helpers tank him while you nuke him down.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Saw bunch of movies and they do not taunt him nor generate massive amounts of threat but he does indeed hit way too much, i'll tweak it

**Comment by Riztazz** [comment]
Resolved
