### ISSUE TITLE
Not getting Draenei racial while in group with Draenei

### ISSUE THREAD

**Issue by Feorblade** [SunwellTracker/issues#1620]
Decription: 

On the Kologarn encounter, I am not getting the draenei racial even though I'm in group with a draenei. Only at specific parts of the enounter am I getting the buff.

How it works: 

How it should work: 

I should be under the effects of the Draenei racial at all points during the fight.

Source (you should point out proofs of your report, please give us some source): 

Here's a vod of me missing a Chimera Shot during the fight when I should be hit capped with the buff. 

https://www.twitch.tv/videos/278418205?t=20m40s

However, since I am not under the effect of the racial I'm not hit capped. If you watch later, when I get targeted by the eye beam and run to the right of the boss, I get the buff for a brief duration until it disappears again. It may be an issue with LoS in the room but I'm not sure.

**Comment by Cwiercpasiec** [comment]
I don't think it's a LoS issue. Heroic presence has 30 yards range (https://db.darkwizard.pl/?spell=6562), you seem to simply be too far away from your draenei.

**Comment by ihcTactics** [comment]
You're absolutely more than 30y away.
You're back left and your DR is the Tank DK who's front right.
![chrome_2018-07-11_04-39-18](https://user-images.githubusercontent.com/22337269/42563698-7b770656-84c4-11e8-8744-82a4a834f293.png)

It's only when you end up moving to the right side of the room that you get Heroic Presence.
