### ISSUE TITLE
Warlock: Quest of thistleheads and eggs tbc 

### ISSUE THREAD

**Issue by Clanggedon** [SunwellTracker/issues#1621]
Decription: 
obtain a rotten arakkoa egg and deliver to tobius the filth gorger in shatt

How it works: 
cannot click on any of the eggs in sketh'lon to obtain the rotten egg

How it should work: 

should be able to click on eggs and eventually get a rotten one
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Currently,  there is only one usable egg  at 42.5, 58.2  . I'll add few more.
![wowscrnshot_070118_014848](https://user-images.githubusercontent.com/25490436/42129828-ef81ccda-7cd0-11e8-9c4f-cc3f072ba978.jpg)
![wowscrnshot_070118_014728](https://user-images.githubusercontent.com/25490436/42129823-caf32c74-7cd0-11e8-9b85-75dbba87f3aa.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
