### ISSUE TITLE
[northshire abby] the occurance of sound of accpetion of quests in this area may be wrong

### ISSUE THREAD

**Issue by Myang583** [SunwellTracker/issues#1622]
Decription: 
[northshire abby] the occurance  sound of accpetion of quests in this area may be wrong

How it works: 
before i click the acception button of quests,the sound of acception already happen.

How it should work: 
after i click the acception button of quests,the sound of acception should happen.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
those quests are "Auto-accepted". If you check chat you'll see message "Quest accepted <Quest Name>" after you open NPC's window with quest description. So you don't need to confirm them.
