### ISSUE TITLE
Quest - City of Light

### ISSUE THREAD

**Issue by jaygee6891** [SunwellTracker/issues#1623]
Decription: The quest bugs when you pick it up on mount, but appears to work normally when unmounted. After testing this seemed to be the case but no real way to know for sure.

How it works: When you pick up the quest on mount the NPC that is Kargath's Servant(the elemental)follows you around anywhere you go like a pet or someone who has you on follow, does not do escort quest.

How it should work: NPC should spawn and take you on a tour of Shattrath, as an escort.

Source (you should point out proofs of your report, please give us some source):  https://www.youtube.com/watch?v=I8Kn7vUr_GQ

**Comment by Dootz** [comment]
It looks like it bugs out when you move before tour event start.

**Comment by Dootz** [comment]
will be fixed with next server update
