### ISSUE TITLE
Quest: Buzzbox 411 isn't available.

### ISSUE THREAD

**Issue by johnschatner** [SunwellTracker/issues#1625]
Decription: The former quest which leads up to this one is "Buzzbox 827" which was available to accept and complete, when turned in the mechanical box should give you the quest: Buzzbox 411 and yet it doesn't.

How it works: It doesn't offer the quest Buzzbox 411 after completing Buzzbox 827. That's it.

How it should work: The quest should be offered to the recipient per usual and yet in my case it didn't. Not much else I can provide other than that it's a quest given by a mechanical box sitting in the grass next to a wooden platform in Auberdine.

Source (you should point out proofs of your report, please give us some source): Imgur [Mirror](https://imgur.com/a/HLZB27Y)

**Comment by Dootz** [comment]
Hi, right now you can get this quest from Buzzbox 411.
![wowscrnshot_070318_124627](https://user-images.githubusercontent.com/25490436/42215594-3b5c4c9e-7ebf-11e8-94bb-e8dbb9618d36.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
