### ISSUE TITLE
Icecrown, The Bombardment - spawn too small

### ISSUE THREAD

**Issue by xNevan** [SunwellTracker/issues#1626]
**Description:** The amount of monsters spawning in The Bombardment (54.0, 43.0) in Icecrown is too small. 

**How it works:** When doing quests like [Leading the Charge](https://db.darkwizard.pl/?quest=13380#?ref=sunwell.pl) or [Static Shock Troops: the Bombardment](https://db.darkwizard.pl/?quest=13404), it's hard to complete them in one go, as there aren't enough monsters. I went through the flight twice, and only got 13/50 Infantries, and I was the only person doing the quest at that time.

**How it should work:** The spawn should be increased (tripled at least), so that it can be completed easily. You can see [here](https://www.youtube.com/watch?v=nnJMLBD4oHs) that a person kills over 30 Infantries within the first 60 seconds of the flight.

**Source (you should point out proofs of your report, please give us some source):** 
Screenshots of the zone from Sunwell - Angrathar:
[Screenshot #1](https://i.imgur.com/Vf56usA.jpg)
[Screenshot #2](https://i.imgur.com/rZ9mT5i.jpg)
[Screenshot #3](https://i.imgur.com/0Xe4LtD.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
