### ISSUE TITLE
Quest - If he cannot be turned (Icecrown) Thassarian

### ISSUE THREAD

**Issue by biscuits69** [SunwellTracker/issues#1627]
Decription: 
Quest - If he cannot be turned (Icecrown)  upon completion you have to turn it in to the ship and find the NPC "thassarian".

How it works: 
NPC Thassarian is not on the ship. he is directly on the ground, and when I fly to him on the ground, he phases out.

How it should work: 
Thassarian should be on the ship to allow the turn-in of "Quest- If He cannot be turned"

Source (you should point out proofs of your report, please give us some source):  Playing.  
![screenshot at 2018-07-01 16 17 09](https://user-images.githubusercontent.com/39687104/42139847-7baee05c-7d4a-11e8-8e8e-a997167fcd02.png)
![screenshot at 2018-07-01 16 17 26](https://user-images.githubusercontent.com/39687104/42139849-81d32006-7d4a-11e8-9eb8-4c90142d7ccf.png). GM told me to submit a ticket

**Comment by xNevan** [comment]
I don't think it has anything to do with any certain quest, just the fact that you can't reach the NPC. 

I have completed a quest called "Raise the Barricades" and have to talk to Thassarian, and can't do it as well.

**Comment by Dootz** [comment]
From what i've heard from GM team it works right now.
