### ISSUE TITLE
Mimiron hardmode bugs

### ISSUE THREAD

**Issue by Danuezzy** [SunwellTracker/issues#1628]
Decription: 
Flame mechanic is broken
Missile Barrage in Phase 4 is broken

How it works: 
Old flames is sometimes still active
When boss enters missile barrage mechanic in p4, he is still able to move around

How it should work: 
Only new fires should be able to expand
Boss should not move at all when Missile barrage is active

Source (you should point out proofs of your report, please give us some source): 
Decription:
https://www.youtube.com/watch?time_continue=661&v=D4X_zHyK6Fc
Original video from worlds first Mimiron hardmode kill on retail
As you can see in the video and many others, in barrage, he doesn't move AT ALL. When barrage is done, he instantly moves.
Old fires doesn't expand.

**Comment by lorderheller** [comment]
Boss moving during barrage is pre-nerf mechanic, and its working as intended. As you can see in the timestamped video, tank is creeping a bit with backpedaling and the boss is moving as well.

**Comment by Turanius** [comment]
missile barrage is w/e, biggest issue is the active [old] flame after new one spawns, 1 mistake from 1 player and everything gets messy after that, can recover but many times results into a wipe.
