### ISSUE TITLE
[Ankahet Web Winder]

### ISSUE THREAD

**Issue by Nasudaa** [SunwellTracker/issues#163]
Decription: 

They instantly web-grab a person without being able to counter it by los or groundign totem

Source (you should point out proofs of your report, please give us some source):

**Comment by Nasudaa** [comment]
The Ankahet Web Winder is the mob name.  They shouldnt instagrab you and pull you in like 3 groups. you could outrange them or los pull them. You are forced to fight 3 Mobgroups  in the beginning of Ankahet dungeon at the same time since the tank will be grabbed instantly. There is no way to avoid it

**Comment by Riztazz** [comment]
Ah alright, i will look into it

**Comment by Afgann** [comment]
Will be fixed with next update.
