### ISSUE TITLE
Inactive spec's glyphs interfere with active spec

### ISSUE THREAD

**Issue by Outis3** [SunwellTracker/issues#1630]
Description:
Got Glyph of Cleaving on Fury spec and when I try to apply it on the other spec (Protection) a message pops up: "That Glyph is already inscribed in your spellbook", refusing to let me use it.

How it works:
Somehow the inactive spec's glyph is counting towards the active spec one, not allowing the use of glyphs that are already on the other spec.

Tried a diferent glyph (Glyph of Whirlwind) which I also have on the inactive spec and it allows me to use it.

(Note that the Glyph of Cleaving is on the same slot in the "spellbook" on which I tested.)

How it should work:
Inactive specs shouldn't interfere in any way on the active spec, so glyphs shouldn't be an exception. It should allow you to apply the same glyph you used in your other spec, as long as you don't repeat it on the active spec.

**Comment by blackwife** [comment]
I had this same issue when applying glyphs to my second spec, I found that logging out and back in enabled me to add the glyphs.  It's definitely a bug, though.
