### ISSUE TITLE
Quest : The Runesmiths of Malykriss

### ISSUE THREAD

**Issue by Demite** [SunwellTracker/issues#1632]
Decription: 
Currently Tasked with collecting 5 | Runed Saronite Plate (5) 

How it works: 
Drop rate is way below what it should be.

How it should work: 
according to wowhead it should be 40-77% drop rate

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=43291/runed-saronite-plate

**Comment by Dootz** [comment]
will be fixed with next server update
