### ISSUE TITLE
Mage cannot cast mana gem

### ISSUE THREAD

**Issue by Finallytherock** [SunwellTracker/issues#1633]
It was working fine 4 hours ago. It keeps telling me I'm already holding. 

How it works: I press the button and it says I have them, I don't. GM couldn't help. 

How it should work: I press the button and it gives me a gem. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
If it keeps telling you that you already hold it then it means that you already hold it - maybe you've put it into your bank by accident or it's addons fault.
Please disable all your addons and check bags + bank again.
Send screenshots with all your bags + bank opened if you won't find it.
