### ISSUE TITLE
Mistcaller Soo-gan quest bug

### ISSUE THREAD

**Issue by JestePalom** [SunwellTracker/issues#1635]
Decription: After not being able to turn in "The Lost Mistwhisper Treasure" quest. I abandoned the quest and now I can't talk with the NPC.

How it works: I can't talk with the NPC 
![wowscrnshot_070318_122910](https://user-images.githubusercontent.com/40793053/42215074-a55c25b2-7ebd-11e8-86c3-3ca444e7aa3b.jpg)

How it should work: I should be able to talk with the NPC and continue the questline.

Source (you should point out proofs of your report, please give us some source): Original Blizzard servers

**Comment by Dootz** [comment]
Hi, could you try to do following:
1) Check your "reputation" tab. Maybe you're "At War" with Oracles - then uncheck it
![wowscrnshot_070318_125229](https://user-images.githubusercontent.com/25490436/42215836-0977b834-7ec0-11e8-955f-2d3dfedacfba.jpg)
2) Close Wow and delete Cache folder.
If none of the above helps, please write an in-game ticket. GM will try to help you.

**Comment by JestePalom** [comment]
Will try that, thx for the response.

**Comment by Dootz** [comment]
GM Piootrek was kind enough to check it on your character, and it looks like you're  "At War" with oracles. Just uncheck it and everything should be fine.
