### ISSUE TITLE
There are too few Thorium veins

### ISSUE THREAD

**Issue by lastnoob** [SunwellTracker/issues#1636]
Decription: 
The spawn density and ratio of mining deposits are not working correctly. The main issue is with thorium.

How it works: 
There are 10x more truesilver veins than thorium and mithril together. For example, in all silithus there's barely a thorium vein. The spawn locations are filled with truesilver and gold veins (uncommon quality). It's a major hassle to farm thorium, thus a stack goes for 100g in the AH. Also, gold veins spawn even in Silithus (they shouldnt).

How it should work: 
There should be significantly more thorium veins, and way less truesilver and gold veins.

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?object=175404
http://db.darkwizard.pl/?object=324

It's pretty obvious.

**Comment by xNevan** [comment]
Just wanted to add that it happens in Winterspring as well. Mithril/truesilver/gold nodes in a 55-60 zone...

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by Zackthecellist89** [comment]
This is happening currently on Frosthold, please apply whatever fix you applied to angrathar there as well.
