### ISSUE TITLE
Glyph of Rejuvenation

### ISSUE THREAD

**Issue by lba1986** [SunwellTracker/issues#1638]
**Decription:** Glyph of Rejuvenation(Major) - While your Rejuvenation targets are below _50%_ health, you will heal them for an additional _50%_ health. 

**How it works:** Current implementation - When a player drops below _35%_ health, they receive a second hot tick for _50%_ of original.

**How it should work:** When a player drops below _50%_ health, the rejuvenation should heal for _50%_ more. 

**The issue:** Extra healing should occur at _<50%_ hp, not _<35%_ hp.

**Source:** This is very easy to test. Simply equip the glyph and take damage below 50% hp and apply rejuvenate. It will not receive the extra 50% healing. Now take damage below 35% hp and apply rejuvenate, immediately you'll receive the extra 50% healing hot until your hp goes above 35%.

**Comment by Kokaina** [comment]
Fixed.
