### ISSUE TITLE
Warrior charge is broken in Thunder Ridge

### ISSUE THREAD

**Issue by Wowbughunter** [SunwellTracker/issues#1639]
Decription: 
So Basically While questing in thunder ridge I did a charge on a mob and i fall down and then died.

How it works: 
When I charge a mob it will not charge in a proper manner and path but here i fall down when i charge.

How it should work: 
It will charge according to correct path.
![wowscrnshot_070518_195927](https://user-images.githubusercontent.com/40863531/42329607-ae4c3946-808e-11e8-8fe9-1161e8ccb359.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/46
