### ISSUE TITLE
If valgarde falls. Too few mobs and not moving. 

### ISSUE THREAD

**Issue by Helligg** [SunwellTracker/issues#164]
Decription: 
If valgarde falls. Too few mobs and not moving. 

How it works: 
Mobs are too scarce, and just stand still. 

How it should work: 
Should be running towards the keep in waves, attacking the guards. 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=I3XfgyEjuSw

**Comment by Helligg** [comment]
As it is now there are like 6 mobs with a 5 min respawn timer. Making it take forever to complete the quest, even solo. WIll take ages if there are several players.

**Comment by Afgann** [comment]
Will be fixed with next update.
