### ISSUE TITLE
unkillable Plainstrider in Wailing Caverns 

### ISSUE THREAD

**Issue by SamLlamas** [SunwellTracker/issues#1642]
Description: There's a Fleeting Plainstrider in the WC, before the dungeon, that's can't be killed. melee says it's too far, spells gives NLOS (Not in Line Of Sight). 

How it works: just try to kill it

How it should work: it should probably die I'm guessing. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_070618_123012](https://user-images.githubusercontent.com/31750528/42392573-eb04dfb6-8118-11e8-9e85-9f99f3889a92.jpg)
![wowscrnshot_070618_123026](https://user-images.githubusercontent.com/31750528/42392574-eb19999c-8118-11e8-84dd-a7da9bb3bf16.jpg)
![wowscrnshot_070618_123030](https://user-images.githubusercontent.com/31750528/42392575-eb2ff8b8-8118-11e8-8411-c0a1bf83329a.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/171
