### ISSUE TITLE
High Miss/Dodge/Parry in Undead Strat

### ISSUE THREAD

**Issue by Runesinne** [SunwellTracker/issues#1643]
Decription:  Mobs and undead strathlome have an unusually high amount of ability to be missed, dodge, or parry level 80 attacks. As an 80 ret pally, with 6% hit, they almost 100% miss all my divine storms and my melee white swings are missed/dodged/parried nearly every time. Need to cast consecrate/exorcism to kill them. 

How it works: 

How it should work: They should be largely unable to avoid my attacks. 

Source (you should point out proofs of your report, please give us some source):  http://wowwiki.wikia.com/wiki/Hit

**Comment by Azathothh** [comment]
No proofs, not enough information, you didn't even give name of mobs on which it's happening.
My bet is that your weapon skill is low or they had some buff/you had some debuff which made it.
Checked some undeads in stratholme and had no problems with hitting them.
