### ISSUE TITLE
[Quest] Vilebranch Hooligans

### ISSUE THREAD

**Issue by Akio501** [SunwellTracker/issues#1646]
Decription:  There's missing quest item for quest http://www.wowhead.com/quest=7839/vilebranch-hooligans

How it works: There's no item to pick up.

How it should work: Well, have no clue :P

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
works fine for me. And respawn is really short. Have you check in location from screenshot?
![wowscrnshot_070818_183748](https://user-images.githubusercontent.com/25490436/42421937-16d861be-82de-11e8-8a45-5aad0861e87c.jpg)
