### ISSUE TITLE
[NPC] Barrens Gazelle - Pathing across zone missing

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#1648]
Decription: 
They stand around and do not run around in the wilds as they are supposed to.

How it works: 
https://i.imgur.com/sJjrlBl.jpg

How it should work: 
The herd should run around together in formation from point to point in the Barrens, resting a few minutes at certain points.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=4166/gazelle#comments:id=1044544

Vanilla realms like Light's Hope and Elysium have it working, it looks wonderful.

**Comment by Dootz** [comment]
will be fixed with next server update
