### ISSUE TITLE
Watts My Target (quest)

### ISSUE THREAD

**Issue by Dobleman** [SunwellTracker/issues#1652]
Decription:
One of the Icecrown bombing quests. You ride on a helicopter and bomb targets on the ground, as well as shoot gargoyles in the air.

How it works:
Many gargoyles spawn, so many that you have to get in a new helicopter 10+ times in order to finish part of the mission, even if you constantly shoot gargoyles. Also, there are no frostbrood spawns in sight to shoot, which is part of the quest, so it is not completable.

How it should work:
The quest should be able to be finished in 1 or 2 tries, like every other quest in wow.

Source (you should point out proofs of your report, please give us some source):
According to the comments here: http://www.wowhead.com/quest=13381/watts-my-target
the quest should not even be available.

I asked in world chat as well as my guild if anyone has completed it. Nobody has, everyone says it is broken. Apparently this issue was already opened months ago but closed for not having "proof." The proof is in the fact that everyone knows it is broken.

**Comment by Nadiirr** [comment]
If the quest should not be available then the "fix" is to remove it from the game.

**Comment by xNevan** [comment]
The gargoyles are fine, you just have to be shielded. There are too few Frostbrood Spawns though, that's for sure.

**Comment by TKD2U** [comment]
STOP CLOSING BUGS THAT PEOPLE ARE HELPING YOU FIND. Jesus... FIX THEM. This quest, along with TONS in Icecrown has bugs. Don't be lazy and just shut them down. play the fucking game and see whats wrong... Jesus... There are 3 people that made the effort to tell you something is WRONG with this quest and you guys just shut them for no reason. Terrible SOP...
