### ISSUE TITLE
[Quest] Dukes of the Council

### ISSUE THREAD

**Issue by lippincott25** [SunwellTracker/issues#1653]
Decription:  Dukes of the Council, quest in Silithus. Requires 3 Abyssal crests from Abyssal Templar's for completion. 

How it works: Abyssal crest doesn't drop. Been farming them for several hours.

How it should work: Abyssal crests are a 100% drop rate from all Abyssal Templar's

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Abyssal_Templar

**Comment by lippincott25** [comment]
ty dootz keep up the good work

**Comment by Dootz** [comment]
I followed instruction from wowhead comments ( http://www.wowhead.com/quest=8332/dukes-of-the-council#comments:id=284136 ), and it worked for me. Right now drop chance of Abyssal Crests is around 80%. I'll set it to 100% with next server update (Tuesday), let me know if that helped.
