### ISSUE TITLE
Bubbly Fissure bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#1654]
Decription: 
Bubbly Fissure bug.

How it works: 
Bubbly Fissure in Desolace (around Shadowprey Village) does not give the breathing buff to fill up your breath bar. Multiple locations.

How it should work: 
Bubbly Fissure should fill the breath bar.

Source (you should point out proofs of your report, please give us some source): 
https://github.com/dalaranwow/dalaran-wow/issues/4123 exactly the same issue on another server.
![wowscrnshot_071018_151008](https://user-images.githubusercontent.com/30598442/42509108-93cd3af2-8453-11e8-9861-f86b9318277a.jpg)
![wowscrnshot_071018_151010](https://user-images.githubusercontent.com/30598442/42509109-93fc8546-8453-11e8-965a-e2085129985a.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
