### ISSUE TITLE
Random Heroic

### ISSUE THREAD

**Issue by ZackForester** [SunwellTracker/issues#1659]
Decription: When queuing for a Specific Heroic Dungeons or Random Lich King Heroic, players should receive a lockout the first time a dungeon is completed each day. Once all lockouts for available heroic dungeons have been obtained, players should no longer be able to queue for Specific Heroic Dungeons but players should remain eligible to queue for Random Lich King Heroic.

How it works: Once all lockouts have been obtained, players are no longer able to queue for heroics, either by queuing for Specific Heroic Dungeons or Random Lich King Heroic.

How it should work: Players should still be able able to queue for Random Lich King Heroic.

Source (you should point out proofs of your report, please give us some source):
https://blue.mmo-champion.com/topic/68912-07-12-dungeon-finder-tool-mini-faq/ https://www.engadget.com/2009/12/07/dungeon-finder-tool-mini-faq/
https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide-page-2/
http://www.tentonhammer.com/guides/instance-guides

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/196
