### ISSUE TITLE
QUEST-Mounting up (Grizzly Hills)

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#166]
Decription: Quest works fine except some horses cant be rode back to camp

How it works: 
https://clips.twitch.tv/SecretiveSpicyChickenTebowing
https://clips.twitch.tv/AbstruseRockySnoodGrammarKing

How it should work: Mustang should not auto run back to its original pathing in the pack, u can see below a proof

Source (you should point out proofs of your report, please give us some source): https://youtu.be/2n8zmkp-nR4?t=126

**Comment by Riztazz** [comment]
lol :P I will fix that

**Comment by sunwellkiwi** [comment]
you tell me if im anoying :P

**Comment by Riztazz** [comment]
Nah its alright, this is what bugtracker is for :P

**Comment by Riztazz** [comment]
Resolved
