### ISSUE TITLE
Formula: Enchant Cloak - Superior Frost Resistance not dropping?

### ISSUE THREAD

**Issue by BestDKafrica** [SunwellTracker/issues#1660]
Decription: 
There are 3 Resistance Patterns for Enchanting dropping from NPCs in Icecrown.
Damned Apothecary are dropping Formula: Enchant Cloak - Superior Frost Resistance (https://db.darkwizard.pl/?item=37332)

How it works: 
Damned Apothecary are dropping Frost Resistance Pattern normally.
But it seems like Damned Apothecary are not dropping Frost or Nature Resistance Patterns If u learned the Arcane Resistance Pattern already. I learned the Arcane and since then I never got any other dropped. I farmed up to 20+ Hours.

How it should work: 
It should drop with a Droprate of 0.6% even If u already got another Resistance Formula learned. Source : https://db.darkwizard.pl/?item=37332

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?item=37332
https://db.darkwizard.pl/?npc=32289

**Comment by ihcTactics** [comment]
They all drop just fine. With the limited number of mob spawns and with the respawn timer, you should expect to spend quite a few hours farming for all the resistance enchants.

I've farmed all of them a few months ago.
