### ISSUE TITLE
Despawn bug

### ISSUE THREAD

**Issue by Dewour** [SunwellTracker/issues#1661]
Decription: Dustwallow Marsh - The Den of Flame, Stonemaul Ruins - bugged dragonkins 

How it works: 50% of dragonkins despawn while skinning em.. Found out only those 2 locations, but I suppose there are more locations with dragonkins who are bugged.
But that´s not such bug with despawning as with skinning, cuz found out this occurs only if I try to skinn em and at the end of process they literally fade out.

How it should work: They have to be despawned immediately after i skin em, or after certain time, not after loot

Source (you should point out proofs of your report, please give us some source): GM named Asureuz is witness, cuz he reacted on my in-game ticket.

**Comment by Dewour** [comment]
edit: traced that mobs doesn´t have leather... I mean they fade out automatically if I auto-loot em with SHIFT + click, but if I don´t auto-loot their inventory is empty... I´m not sure if I should consider this as bug, or basic mechanic of game, but never happend to me before...

Would appreciate opinion of others.

**Comment by Dootz** [comment]
does it happen with every single mob? By dragonkins you mean [Firemane Scout](http://www.wowhead.com/npc=4329/firemane-scout)  and [Firemane Ash Tail](http://www.wowhead.com/npc=4331/firemane-ash-tail) ?

**Comment by Dewour** [comment]
Even whelps does it,  and not with every single one that occurs like 50% of time..
