### ISSUE TITLE
Stratholme Vanilla Dungeon Blacksmithing Plans DO NOT DROP ANYTHING

### ISSUE THREAD

**Issue by Bocamafe** [SunwellTracker/issues#1665]
Decription:  The blacksmithing plans should drop items but it does not only the mob it spawns.

How it works:  doesnt give u anything

How it should work:  shoudl give u blacksmithing plans Corruption

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
