### ISSUE TITLE
[Professions] Failed attempts on gathering professions

### ISSUE THREAD

**Issue by imbactbulletz** [SunwellTracker/issues#1668]
**Decription:**
The issue is related to Mining, Herbing and Skinning in specific.

**How it works:** 
Whenever a player tries to gather an ore/herb/skin an animal their attempt can result in a failed attempt. (A 'Failed attempt' message is being displayed on the screen and you have to reattempt gathering again).

**How it should work:** 
Gathering resources from these professions should never fail as of 3.1.0.

**Source (you should point out proofs of your report, please give us some source):** 
"You can no longer fail when Mining, Herbing, and Skinning." - http://wowwiki.wikia.com/wiki/Patch_3.1.0

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by Dootz** [comment]
I need to check one more find and thus it'll be fixed in next week's update (aroun 07.08)

**Comment by Dootz** [comment]
will be fixed with next server update
