### ISSUE TITLE
[Escape from Silverbook]

### ISSUE THREAD

**Issue by Nasudaa** [SunwellTracker/issues#167]
Decription:  Escaping NPCS just rides

How it works: The NPC you have to rescue wont stop when mobs spawn and want to attack him, he just keeps riding

How it should work: He should stop so you could fight

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://www.youtube.com/watch?v=GTpItEKHUZw
Works correctly... closing
