### ISSUE TITLE
[Strand of the ancient] Bug with Teleport

### ISSUE THREAD

**Issue by sQuba12** [SunwellTracker/issues#1674]
Decription: 
When u play for defend team and if u will use teleport near broken gate u will hit behind the damaged wall, when u must to teleport behind to full hp gate in next defend line and protect it  from tanks.

How it works: 
When u defend gate and use teleport near broken gate u will hit behind same broken wall.

How it should work: 
When u defend gate and use teleport near broken gate u need to move behind a full hp gate in next defend line

Source (you should point out proofs of your report, please give us some source): If needed we cant make short video

**Comment by Aridam** [comment]
This is invalid.
https://worldofwarcraft.com/en-us/news/2166872/patch-4-0-6-official-notes
> The Teleporters on defense will now teleport players based on which line of gates have been destroyed, rather than directly behind that gate. For example, if a player clicks the Teleporter at the Blue gate when one of the beach gates has been destroyed, it will put the player behind the Red gate.

It was changed to work like that during the _Cataclysm_, v4.0.6 -- _before_ that, it's supposed to simply teleport you to the other side of the same Gate, **even if destroyed.**
