### ISSUE TITLE
[Warlock][Spell] Curse of Doom

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1677]
Decription: The spell casts a dot on the target and after 1 min if the dot kills the target and it yields experience or honor it has a chance to summon a doomguard.

How it works: It works fine except that at at level 80 this doomguard is lvl 64 and needs to be enslaved.

How it should work: The doomguard should be level 80.

Source (you should point out proofs of your report, please give us some source): https://db.darkwizard.pl/?spell=47867

**Comment by Akha72** [comment]
Yeah, I reported that on server previous bugtracker. Difficult to find proofs though - not much beside 320p videos where you can barely see anything.
