### ISSUE TITLE
[Ulduar] [Hodir] Freeze spell chains to people

### ISSUE THREAD

**Issue by samercyn** [SunwellTracker/issues#1679]
Decription: The damage from the freeze spell that Hodir casts chains to people nearby.
https://db.darkwizard.pl/?spell=62469 <-- spell ID

How it works: When Hodir casts Freeze, it will target a player's location and launch a bolt of ice. Any player struck will be rooted and take ~6k frost damage but also will deal ~6k frost damage to anyone nearby. E.g. if 4 people are close enough together and get hit by freeze, they will all take ~6k frost damage 4 times.

How it should work: The root and damage should be an AoE attack, but not chain the damage to nearby players. E.g. if the 4 people in the example above get hit, all 4 players will be rooted and take ~6k frost damage.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/d8Wqg5eP6V8?t=5m40s - around this time stamp you will see 5 people within close proximity to each other get hit by the freeze, they only receive damage once and the damage will not chain to each player.

**Comment by Azathothh** [comment]
Got any video or logs with this 4x~6k damage from freeze?
I've tried to reproduce it on test realm and couldn't - it was always ~6k dmg for everyone in range and no extra dmg from other ppl.

**Comment by samercyn** [comment]
If my guild goes back into Ulduar this weekend I will try to remember to record the fight and take screenshots of Skada death logs. This was happening on 10man if that helps. It was also happening most noticeably during/directly after the flash freeze (since everyone tends to be more clustered at that point).

**Comment by whabt** [comment]
I just had this happen to me last night, our raid kept falling over and we couldn't figure out why.  I no longer have the recount parse (going to see if someone else does and get them to screenshot some death reports for me - I'll add it to the thread if so), but Hodir's Freeze hit me and several other raid members at lease 4 times in a .3 second period, I went from 70% to dead in .3 sec.  This was in 10 man.  

It was immediately after a Flash Freeze, no players were hit by flash afaik.

**Comment by samercyn** [comment]
forgot I had this open issue still. thank you github for e-mail alerts.

https://youtu.be/YXXNa_hIMwk happens 20 seconds into that video.
after re-watching it, it looks like the freeze spell is cast 4 times in rapid succession. you can see the graphical animation on the ground under the players.

https://imgur.com/a/Zqsas08 skada death logs of the three players killed by this.

**Comment by whabt** [comment]
Samercyn, that is pretty much exactly what my recount death report looked like, right down to the spell timings.
