### ISSUE TITLE
deterrence huntera + pet commands

### ISSUE THREAD

**Issue by dathremar** [SunwellTracker/issues#168]
Decription: 
Bug dotyczy mozliwosci sterowania petem w czasie deterrence.   Ktos,kto to skryptowal zle zinterpretowal ". While Deterrence is active, you cannot attack. Lasts 5 sec.".

How it works: 
W czasie deterrenca nie mozna uzywac komendy pet attack (zmienic targetu, zaczac atakowac petem). Jezeli pet zostal wyslany do ataku przez wlaczeniem deterrenca, to bedzie atakowal wybrany target (akurat to dziala dobrze).

How it should work: 
Deterrence nie powinien miec absolutnie zadnego wplywu na sterowanie petem (rzucanie pulapek(w tym freezing arrow),uzywanie spelli nie zadajacych DMG powinno byc mozliwe,tylko kill command i shoty nie powinny byc uzywalne - co dziala dobrze).  Komendy peta powinny byc mozliwe do uzycia przez caly czas. Powinno sie moc zmieniac target peta z wlaczonym deterrencem. 

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?spell=19263   - dowodem jest sam tooltip spella, nie ma tam nic o niemoznosci sterowania petem.
http://wowwiki.wikia.com/wiki/Deterrence
http://www.wowhead.com/spell=19263/deterrence#comments coment Magnatross z patcha 5.0.1 (nie ma zadnych informacji, by ta mechanika zmenila sie miedzy wotlkiem a mopem/cata)

Prosze o szybka naprawe, bo bug ten znacznie oslabia huntera.

**Comment by dispelx** [comment]
up ^ fix this  It is not at all possible to play for a hunter

**Comment by Kokaina** [comment]
Fixed.
