### ISSUE TITLE
Npc miss place and mass spawn

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1682]
Decription: Infront of Hyal summit raid this thing happened

How it works: 
Look at picture

How it should work: 
Shouldnt be there
![wowscrnshot_072018_231719](https://user-images.githubusercontent.com/37425406/43027467-b2c1ea32-8c7a-11e8-9299-15b61f5e3542.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
