### ISSUE TITLE
Mob Issue:  Stonetalon Mountains

### ISSUE THREAD

**Issue by MisterSitar** [SunwellTracker/issues#1685]
Decription: 
at coord. 47,47 in Stonetalon Mountains there is a Pridewing that is unable to target nor initiate combat regardless if i use the macro /target for the specific mob

How it works:  Mob exists by tree, but is unable to aggro let alone target the said mob.

How it should work:   Mob should be capable of being targeted via TAB or running a macro for target recognition.   You should also be able to use a pull to the mob based among agrro range that seems non-existent with this specific mob.  All the rests in the area are pefectly fine and I have not been able to find any other mob in the area that respawns in the same fashion this specific mob did.

Source (you should point out proofs of your report, please give us some source): 
![screenshot 153](https://user-images.githubusercontent.com/40922169/43032139-bfaccc28-8c7d-11e8-80fa-0f0ad6047afc.png)

**Comment by Dootz** [comment]
will be fixed with next server update
