### ISSUE TITLE
[Quest Daily] Hot and Cold ID 12981

### ISSUE THREAD

**Issue by smyrtus** [SunwellTracker/issues#1686]
Quest http://db.darkwizard.pl/?quest=12981
Sometimes when you use quest item Essence of Ice http://db.darkwizard.pl/?item=42246 it dissapear and nothing happend.
When you use it near Smoldering Scraps, should appear  Frozen of Iron Scrap http://db.darkwizard.pl/?item=42252

**Comment by Dootz** [comment]
When it disappears what happens with Smoldering Scrap? Is it still visible? Were you able to see a missile animation when you used q item? Maybe it hit different Smoldering Scrap.

**Comment by Dootz** [comment]
will be fixed with next server update
