### ISSUE TITLE
Pet Macro

### ISSUE THREAD

**Issue by unknown41** [SunwellTracker/issues#1688]
Decription: 
#showtooltip Summon Water Elemental
/cast Summon Water Elemental
/petpassive
/petattack

How it works: 
it starts to attack a random target 
its only happening on the initial summon. its starting to attack something direct and wont attack with the first cast the right target since its casting already.

How it should work: 
its summoning your water elemental
pet switches into passive form 
(it follows you unless you have a target it will start to attack direct if you spam the button)

Source (you should point out proofs of your report, please give us some source): 
if you spam pet attack while the pet is already summoned it is not attacking random targets
the petpassive should prevent the pet from attacking unless you have a target

**Comment by Azathothh** [comment]
"How it should work: pet switches into passive form (it follows you"  
that's not correct if you want pet to stop current cast and to follow you use /petfollow instead of /petpassive
