### ISSUE TITLE
Argent Tournament Dailies Not unlocking

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#1689]
When you unlock the achievement  [Exalted Argent Champion of the Horde] and  [The Sunreavers] new dailies should open at the argent tournament.

http://www.tentonhammer.com/guides/wow-argent-tournament-guide
The quests under "Crusader's Charge" and "Someone Else Likes Me!" are the ones not unlocking.

**Comment by Dootz** [comment]
some quests (e.g. The Black Knight's Curse ) will be unlocked with patch 3.2 content update.
http://wowwiki.wikia.com/wiki/Argent_Tournament

**Comment by TheRealYasri** [comment]
yeah forgot they were added in 3.2, maybe put in a quest in saying more is coming if they unlock those achives.
