### ISSUE TITLE
Warrior Stance Bug

### ISSUE THREAD

**Issue by Xeroasd** [SunwellTracker/issues#169]
Decription: 
After dying or warping from an instance my Warrior acts like he is not in any kind of stance. I need to click on one of my stances to make it back

How it works:  Manually need to swap back to a stance after porting or dying

How it should work: Automatically enters the previous stance

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/114
