### ISSUE TITLE
[Naxxramas] Shocking Achievement (Thaddius)

### ISSUE THREAD

**Issue by Kowson** [SunwellTracker/issues#1690]
Decription: 
Wiping the encounter doesn't reset the criteria for doing an achievement. We did it on the 3rd pull, checked it with Fail addon and 3 different damage meters(Skada, Recount, Details!). And due to it not working as intended we lost our last chance to get the drake.

How it works: 
You can only get this achievement by doing in on the first pull.

How it should work: 
The criteria for an achievement should reset after wipe. (just add that one line to the source code pls)

Source (you should point out proofs of your report, please give us some source): 
"We were shocked - after few wipes on him (lags, freezes, etc) we've managed to kill him AND get this one on our first kill." (http://www.wowhead.com/achievement=2179/shocking-25-player#comments) from 3.0.9

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1302
