### ISSUE TITLE
Yeh'kinya's Scroll

### ISSUE THREAD

**Issue by sixele** [SunwellTracker/issues#1693]
Description: 
Yeh'kinya's Scroll is an item used instead of the  [Egg of Hakkar] to summon the Avatar of Hakkar in the Sanctum of the Fallen God of the Sunken Temple if the quest The God Hakkar had already been completed. Unlike the Egg of Hakkar it was not consumed after use. 

How it works: 
After completing the quest The God Hakkar you can not get Yeh'kinya's scroll.

How it should work: 

This item should be obtained by speaking to Yeh'kinya after completing the quest The God Hakkar.
The scroll was supposedly only removed in Cata patches, meaning it was available and still being in use in WotLK.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Yeh%27kinya%27s_Scroll
https://wow.gamepedia.com/Avatar_of_Hakkar
https://wow.gamepedia.com/Egg_of_Hakkar
http://www.wowhead.com/item=10818/yehkinyas-scroll#comments:id=166094
http://www.wowhead.com/npc=8443/avatar-of-hakkar#comments:id=211644
http://www.wowhead.com/npc=8443/avatar-of-hakkar#comments:id=737308 and other TBC/WotLK comments.

**Comment by Dootz** [comment]
will be fixed with next server update
