### ISSUE TITLE
World boss Taerar bugged. Angrathar.

### ISSUE THREAD

**Issue by Kypced** [SunwellTracker/issues#1694]
Decription: 
World boss Taerar bugged.

How it works: 
When he reaches 75% of hp he just banishes and becomes unavilable to hit and spawns nothing. So you can't touch him and he evades after couple minutes.

How it should work: 
Every 25% of his HP(75% 50% 25%) he must be banished and must spawn some little clones of himself.

Source (you should point out proofs of your report, please give us some source): 
Sorry, i can't point out proofs(screenshots) because noone wants to try kill him, if he bugged.
And also sorry for bad english.

**Comment by Dootz** [comment]
will be fixed with next server update
