### ISSUE TITLE
[Quest] We Have the Power

### ISSUE THREAD

**Issue by mdindoffer** [SunwellTracker/issues#1695]
Decription: 
NPC Kathorn does not drop the quest item [Kathorn's Power Cell](https://db.darkwizard.pl/?item=36858).

How it works: 
As stated in the description. I have killed him 3 times, but he didn't drop the item.

How it should work: 
Maybe the drop rate should be increased?

Source (you should point out proofs of your report, please give us some source):
The droprate should logically be the same as the droprate of [Durar's Power Cell](https://db.darkwizard.pl/?item=36857) which is the second quest objective.

**Comment by MrTide** [comment]
Hello
it surely drops but drop rate needs adjusting

**Comment by Dootz** [comment]
will be fixed with next server update

**Comment by Jonsse** [comment]
10.4.2020 - still not fixed
