### ISSUE TITLE
[Drop] Mantle of the Wayward Conqueror

### ISSUE THREAD

**Issue by devrak** [SunwellTracker/issues#1697]
Decription: 
Mantle of the Wayward Conqueror drop rate seems to be less than it should be

How it works: 
It appears that currently Mantle of the Wayward Conqueror is dropping less often than other two tokens in last 7 kills iv only seen 1 to drop and walking around Dalaran its rare to see some paly/priest/wl with t8 shoulders

How it should work: 
Mantle of the Wayward Conqueror should drop as often as other tier tokens

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?npc=33955

Additional information:
Asking some of my friends that raid in different guilds and they also confirmed that this token is rare and they have never seen double p/p/w token drop however they often see  double hunter/sham/war token drops

**Comment by Azathothh** [comment]
There's 33% chance for each type of token.
I've killed yogg 30 times to make sure, got 60tokens total and it was:
19x conqueror
20x vanquisher
21x protector
