### ISSUE TITLE
Mob Misplaced: Ridge Huntress

### ISSUE THREAD

**Issue by MisterSitar** [SunwellTracker/issues#1698]
Decription:  Ridge Huntress level 38 (ID:2732) Coord: 37,49 Badlands

Stuck upon a peak, but still can initiate aggro if entering within appropriate area of effect.  It caused a cmb bug once, but was fixed with login.  Was unable to reproduce the cmb bug on my other character aggroing the bugged mob.

How it works:  Huntress will initiate cmb, but cannot be engaged.  Requires you to vacate the area until you are passed the leash so the combat disengages

How it should work:  Huntress should be roaming and not fixated on top of a point that is inaccessible by any player utilizing legit methods.

Source (you should point out proofs of your report, please give us some source): 
![screenshot 158](https://user-images.githubusercontent.com/40922169/43278425-1a57950e-90d9-11e8-80ab-2a337f199d33.png)

**Comment by Dootz** [comment]
will be fixed with next server update
