### ISSUE TITLE
cannot change loot settings

### ISSUE THREAD

**Issue by mundon** [SunwellTracker/issues#170]
Decription: When in RDF with some friends we cannot seem to change the loot system to master looter.

How it works: Loot system defaults to need before greed

How it should work: It should default to Need before Greed but should be changeable, so when we group with random people we can prevent getting ninjad by setting master looter.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
