### ISSUE TITLE
[Quest] Swabbin' Soap

### ISSUE THREAD

**Issue by dhrakon** [SunwellTracker/issues#1702]
Decription: 
The goal of the quest ("Big Roy", a named reef bull) has too many spawns.

How it works: 
Big Roy has too many spawns at once.

How it should work: 
Big Roy is unique and only one should be alive at a time

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/19195764/43360399-cacedb5e-9282-11e8-9cbb-922df6fcb1d5.png)

**Comment by Dootz** [comment]
will be fixed with next server update
