### ISSUE TITLE
 No NPC in the city of SW

### ISSUE THREAD

**Issue by Lianna1** [SunwellTracker/issues#1703]
Decription: 

A few weeks ago, the capital city of Stormwind, the NPC disappeared. The city appears simply empty, and it is no use for me to relogar.This happens only in SW, in other maps, all is well. Já downloaded another customer, and the error persists! I checked my internet, and neither is this. My nickname in the game is Panndora.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_072818_190135](https://user-images.githubusercontent.com/41843221/43361616-9dc47cd2-92a9-11e8-96b1-4b1af7336b82.jpg)
![wowscrnshot_072818_190222](https://user-images.githubusercontent.com/41843221/43361621-d597afbc-92a9-11e8-97d5-ce6d95e14e80.jpg)

I do not know if the images will load, I apologize right away, if I do not load. But the situation is just this, the city is simply empty for me, no matter how many times I go to it, even with another player, I always appear alone.

**Comment by Dootz** [comment]
Hi, you probably started Battle For Undercity chain quest.  You just need to end it. If you'll have trouble finding the place from which you should continue, you can always use the in-game ticket system. GM will respond as soon as possible, and help to solve your issue.

Useful links:
http://wowwiki.wikia.com/wiki/Quest:The_Battle_For_The_Undercity_(Alliance)
https://wow.gamepedia.com/Battle_for_the_Undercity

**Comment by Lianna1** [comment]
Hi. I do not have any quest with that name ... And yet, if I had it, did all the NCPs really go away? To the flight NCP? There's simply no NPC or SW players for me ... I suppose this is not because of a mission ...

**Comment by Lianna1** [comment]
My problem is that there are no players or NCP's in the city of SW ... Not even the flight NPC appears anymore ... Every city is completely deserted for me ... even if my friends are in the city, I can not see them.

**Comment by Dootz** [comment]
i'm  pretty sure it's "battle of undercity related" issue. Have you done any quest in Dragonblight? You might want to look for quest near Wrathgate. **But to be sure please write in-game ticket**. GM will be able to check what's going on with your character. They respond quickly.

**Comment by Lianna1** [comment]
I went to the mission and did it, it worked. Sorry to have doubted!

**Comment by dhrakon** [comment]
I ran into this issue the other day, I hadn't started the battle for undercity chain. It seems to happen right be fore (or after) the wrathgate cinematic.
