### ISSUE TITLE
[Druid]Heart of The Wild doesn't give stamina and attack power

### ISSUE THREAD

**Issue by Darkhoof** [SunwellTracker/issues#1706]
Decription: The talent don't gives the second part for increasing Stamina in Bear form and Attack Power in Cat form

How it works: The talent gives only the first part for increasing Intellect by 20%

How it should work: The talent should increase stamina when druid is in Bear form and increase attack power while Cat form

Source (you should point out proofs of your report, please give us some source):  

![wowscrnshot_072918_223749](https://user-images.githubusercontent.com/41876092/43370070-1c036752-9381-11e8-8141-5ff1e9d8c35b.jpg)
![wowscrnshot_072918_223828](https://user-images.githubusercontent.com/41876092/43370075-2797c536-9381-11e8-830c-5f1b1740b31c.jpg)
![wowscrnshot_072918_223805](https://user-images.githubusercontent.com/41876092/43370076-2d1ccc4a-9381-11e8-8044-4d662197f92e.jpg)
![wowscrnshot_072918_223819](https://user-images.githubusercontent.com/41876092/43370079-31c435bc-9381-11e8-8148-ff5bb5a28b7b.jpg)

This is my druid without and with the talent in the both forms in bear form stamina stay the same.
In cat form attack power also stay same with and without the talent

**Comment by Koroflmao** [comment]
Hello, I just tested this and the talent does work, however you must shape-shift out and into form again for it to properly show in the character panel.

/roro
