### ISSUE TITLE
portal to wintersgrasp

### ISSUE THREAD

**Issue by Rinister** [SunwellTracker/issues#1708]
Decription: 
The que worked yesturday for wintersgrasp... Not for the pvp event n or the pve event, to day when im trying to que up nothing pappens... In i have seen a few other ppl experiens somting simmilar...

How it works: 
I cant use the portal propely it dose the animation for clicking the portal but i dont get transported to wintersgrasp

How it should work: 
well i shudde alteas be abel to go there afterwords when coz there shudde be no restriction on the player limit then...

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_073018_140259](https://user-images.githubusercontent.com/41904685/43396371-98a8d1cc-9401-11e8-90b6-c6a2eb58978a.jpg)
![wowscrnshot_073018_140301](https://user-images.githubusercontent.com/41904685/43396377-9c0c8d7c-9401-11e8-8018-e5276965e383.jpg)
n the battel is over
![wowscrnshot_073018_140935](https://user-images.githubusercontent.com/41904685/43396624-68c4a9a8-9402-11e8-8efa-2ed6c1145dea.jpg)

**Comment by Cwiercpasiec** [comment]
Portal to Wintergrasp works only for faction controlling Wintergrasp. To que for WG while your faction attacks it, simply speak with Wintergrasp Battle-Mage and click Queue for Wintergrasp.

**Comment by Rinister** [comment]
look at the buff
