### ISSUE TITLE
Galak Centaurs broken paths - Splithoof Hold cave - Thousand Needles

### ISSUE THREAD

**Issue by bongobg** [SunwellTracker/issues#171]
Decription: 
All the centaur NPCs in the cave in Splithoof Hold (entrance at 44.0-37.4) flee through the top/roof of the cave and get stuck in the 'walls'.

How it works: 
Enter the cave, engage a centaur, drop it on low HP, watch his fleeing path.

How it should work: 
They should flee following the terrain and aiming the nearest NPC.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020218_220549](https://user-images.githubusercontent.com/865756/35754859-aebd7776-086d-11e8-88a4-bfd13d9f334e.jpg)

**Comment by Azathothh** [comment]
It doesn't happen with all centaurs in that cave - it happens only in center of that cave : 
![obraz](https://user-images.githubusercontent.com/37483678/41715109-b164b528-7552-11e8-80b2-3451f745debc.png)
