### ISSUE TITLE
The Heart of the Mountain

### ISSUE THREAD

**Issue by Drakuxgodx** [SunwellTracker/issues#1710]
Decription: Quest item bug.

How it works: Can't pick up the quest item Hearth of the mountain first i didnt even saw him than the gm makes him visisble but still cant pick up.

How it should work:We should take key open safe and just pick up the q item.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/qr5DG8Z

**Comment by Dootz** [comment]
will be fixed with next server update
