### ISSUE TITLE
[Quest][Item] Tiki Hex Remover

### ISSUE THREAD

**Issue by mdindoffer** [SunwellTracker/issues#1711]
Decription: 
The [Tiki Hex Removers](http://www.wowhead.com/item=39305/tiki-hex-remover) from the quest [Hexed Caches](http://www.wowhead.com/quest=12709/hexed-caches) do nothing.  You should be able to dispel all the curses on your character by using the hex removers.

How it works: 
When you open a cache from the quest, a random curse is applied to your character. You click on the Hex Remover, but your curse does not get dispelled.

How it should work: 
You should be able to dispel all the curses on your character by using the hex removers.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=39305/tiki-hex-remover#comments
http://www.wowhead.com/quest=12709/hexed-caches

**Comment by Dootz** [comment]
will be fixed with next server update
