### ISSUE TITLE
[Npc] Gotura Fourwinds - no option to restore Totem of the Earthen Ring

### ISSUE THREAD

**Issue by Azathothh** [SunwellTracker/issues#1712]
Decription: 
Gotura Fourwinds should be able to restore our Totem of the Earthen Ring if we have lost it.
This totem is obtained in Relic of the Earthen quest (id 14100).

How it works: 
Currently if we delete Totem of the Earthen Ring there's no way to get new one.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=14100/relic-of-the-earthen-ring  - horde quest
http://www.wowhead.com/item=46978/totem-of-the-earthen-ring#comments
http://www.wowhead.com/npc=35068/gotura-fourwinds#comments

"If you, for any reason, destroy your totem, you can take it back from Gotura Fourwinds.
(tested it because i got surprised when i learned that it was destroyable)"
"on 2009/08/08 (Patch 3.1.3) Can be destroyed. Talk to the person who gave it to you for another."

**Comment by Dootz** [comment]
will be fixed with next server update
