### ISSUE TITLE
[Npc] Farseer Eannu - no option to restore Totem of the Earthen Ring 

### ISSUE THREAD

**Issue by Azathothh** [SunwellTracker/issues#1713]
Decription:
Farseer Eannu should be able to restore our Totem of the Earthen Ring if we have lost it.
This totem is obtained in Relic of the Earthen quest (id 14111).

How it works:
Currently if we delete Totem of the Earthen Ring there's no way to get new one.

Source (you should point out proofs of your report, please give us some source):
http://www.wowhead.com/quest=14111/relic-of-the-earthen-ring - alliance quest
http://www.wowhead.com/item=46978/totem-of-the-earthen-ring#comments
http://www.wowhead.com/npc=35073/farseer-eannu#comments

"on 2009/08/08 (Patch 3.1.3) Can be destroyed. Talk to the person who gave it to you for another."

**Comment by Dootz** [comment]
will be fixed with next server update
