### ISSUE TITLE
[NPC] Some broken Npc №3

### ISSUE THREAD

**Issue by LookinGood** [SunwellTracker/issues#1715]
Decription:  
These NPC don't use their spells:

- [x] http://www.wowhead.com/npc=28189
- [x] http://www.wowhead.com/npc=25383
- [x] http://www.wowhead.com/npc=24250
- [x] http://www.wowhead.com/npc=24249
- [x] http://www.wowhead.com/npc=23651
- [x] http://www.wowhead.com/npc=23932
- [x] http://www.wowhead.com/npc=23660
- [x] http://www.wowhead.com/npc=23658
- [ ] http://www.wowhead.com/npc=26170
- [x] http://www.wowhead.com/npc=24014
- [x] http://www.wowhead.com/npc=24018
- [x] http://www.wowhead.com/npc=24029
- [ ] http://www.wowhead.com/npc=23992
- [ ] http://www.wowhead.com/npc=24073
- [x] http://www.wowhead.com/npc=23993
- [x] http://www.wowhead.com/npc=23990
- [x] http://www.wowhead.com/npc=23989
- [x] http://www.wowhead.com/npc=23991
- [x] http://www.wowhead.com/npc=23665
- [x] http://www.wowhead.com/npc=24060
- [ ] http://www.wowhead.com/npc=23844
- [ ] http://www.wowhead.com/npc=26663
- [ ] http://www.wowhead.com/npc=24871
- [ ] http://www.wowhead.com/npc=24872
- [ ] http://www.wowhead.com/npc=24198
- [ ] http://www.wowhead.com/npc=24199
- [ ] http://www.wowhead.com/npc=23564
- [ ] http://www.wowhead.com/npc=24026
- [ ] http://www.wowhead.com/npc=24186
- [ ] http://www.wowhead.com/npc=23644
- [ ] http://www.wowhead.com/npc=24485
- [ ] http://www.wowhead.com/npc=24540
- [ ] http://www.wowhead.com/npc=27501
- [ ] http://www.wowhead.com/npc=23643
- [ ] http://www.wowhead.com/npc=24440
- [ ] http://www.wowhead.com/npc=23688
- [ ] http://www.wowhead.com/npc=23940
- [ ] http://www.wowhead.com/npc=23871
- [ ] http://www.wowhead.com/npc=23653
- [ ] http://www.wowhead.com/npc=23657
- [ ] http://www.wowhead.com/npc=23655
- [ ] http://www.wowhead.com/npc=23676
- [ ] http://www.wowhead.com/npc=23711
- [ ] http://www.wowhead.com/npc=23674
- [ ] http://www.wowhead.com/npc=24644
- [ ] http://www.wowhead.com/npc=23656
- [ ] http://www.wowhead.com/npc=24015
- [ ] http://www.wowhead.com/npc=23654
- [ ] http://www.wowhead.com/npc=24169
- [ ] http://www.wowhead.com/npc=24635
- [ ] http://www.wowhead.com/npc=24676
- [ ] http://www.wowhead.com/npc=24371
- [ ] http://www.wowhead.com/npc=24789
- [ ] http://www.wowhead.com/npc=23865
- [ ] http://www.wowhead.com/npc=23778
- [ ] http://www.wowhead.com/npc=23883
- [ ] http://www.wowhead.com/npc=24212
- [ ] http://www.wowhead.com/npc=23796
- [ ] http://www.wowhead.com/npc=24030
- [ ] http://www.wowhead.com/npc=24638
- [ ] http://www.wowhead.com/npc=23744
- [ ] http://www.wowhead.com/npc=23919
- [ ] http://www.wowhead.com/npc=23740
- [ ] http://www.wowhead.com/npc=24023
- [ ] http://www.wowhead.com/npc=24742
- [ ] http://www.wowhead.com/npc=24547
- [ ] http://www.wowhead.com/npc=24713
- [ ] http://www.wowhead.com/npc=23842
- [ ] http://www.wowhead.com/npc=24050
- [ ] http://www.wowhead.com/npc=23739
- [ ] http://www.wowhead.com/npc=25316
- [ ] http://www.wowhead.com/npc=25209
- [ ] http://www.wowhead.com/npc=25215
- [x] http://www.wowhead.com/npc=24957
- [x] http://www.wowhead.com/npc=25687
- [x] http://www.wowhead.com/npc=25444
- [x] http://www.wowhead.com/npc=25448
- [x] http://www.wowhead.com/npc=27008
- [x] http://www.wowhead.com/npc=27009
- [x] http://www.wowhead.com/npc=27330
- [ ] http://www.wowhead.com/npc=27826
- [x] http://www.wowhead.com/npc=30333
- [x] http://www.wowhead.com/npc=30205
- [x] http://www.wowhead.com/npc=30206
- [x] http://www.wowhead.com/npc=30544
- [x] http://www.wowhead.com/npc=26586
- [x] http://www.wowhead.com/npc=26920
- [x] http://www.wowhead.com/npc=27615
- [x] http://www.wowhead.com/npc=26820
- [x] http://www.wowhead.com/npc=26806
- [x] http://www.wowhead.com/npc=29449
- [x] http://www.wowhead.com/npc=29451
- [x] http://www.wowhead.com/npc=28034
- [x] http://www.wowhead.com/npc=28221
- [x] http://www.wowhead.com/npc=28257
- [x] http://www.wowhead.com/npc=28255
- [x] http://www.wowhead.com/npc=30037
- [x] http://www.wowhead.com/npc=32488
- [x] http://www.wowhead.com/npc=29738

How it works: 

How it should work: 
They are should use all spells

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
weird, so far most of them work for me. But i'll check the rest too
