### ISSUE TITLE
[Onslaught Harbor - NPC]

### ISSUE THREAD

**Issue by ViPERGaming247** [SunwellTracker/issues#1716]
Decription: In onslaught harbor (icecrown) there are Gryphon Riders "flying" under water (pretty deep also though)

How it works: just watch it, its hillarious :D

How it should work: grypons should get waterbreathing buffed ;p

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_080318_133548](https://user-images.githubusercontent.com/42065988/43641844-71db75dc-9725-11e8-8deb-b0e29b0642e0.jpg)
![wowscrnshot_080318_133554](https://user-images.githubusercontent.com/42065988/43641851-77c8f960-9725-11e8-8194-1869def458d9.jpg)

**Comment by Dootz** [comment]
fixed
