### ISSUE TITLE
DKs death coil healing

### ISSUE THREAD

**Issue by Rinister** [SunwellTracker/issues#1717]
Decription: 
DK death coil dont heal undead trargets (i dont know if u can heal the goul i havent tryed it...

How it works: 
Death coils DMG works as intended the healing cant be used what i have seen it just says invalid target!

How it should work: 
u shudde ba abel to heal any DK (thay are undead) as well as the UD hord race

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I found only information that you can use it if you have Lichborne effect. After simple test it works.
Source:
https://us.battle.net/forums/en/wow/topic/2016083013

Also there's a comment: "Undead players are treated as humanoids." so i don't think that you should be able to use it on Undead's

**Comment by Rinister** [comment]
![wowscrnshot_080618_021200](https://user-images.githubusercontent.com/41904685/43691538-5f28de2a-991e-11e8-85e3-eff904ad5ab2.jpg)

**Comment by Rinister** [comment]
this is not working

**Comment by Rinister** [comment]
![wowscrnshot_080618_021321](https://user-images.githubusercontent.com/41904685/43691552-822b69a6-991e-11e8-853b-715acfc1b604.jpg)
