### ISSUE TITLE
resto druid swiftmend

### ISSUE THREAD

**Issue by Spainboy** [SunwellTracker/issues#1719]
Decription: Glyph of Swiftmend not working

How it works: not working whitout rejuvenation or regrowth spell

How it should work: working without rejuvenation or regrowth spell

Source (you should point out proofs of your report, please give us some source): all resto druids on the server

**Comment by dhrakon** [comment]
Swiftmend:
Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.

That sounds to me like there has to be a rejuv or regrowth on the target for it to work. There's a glyph that makes it so it doesn't consume the rejuv / regrowth, but it still needs to be there.

**Comment by Spainboy** [comment]
You're right, works well, this not bug.
