### ISSUE TITLE
Cheap shot does not hit through hunters Detterance

### ISSUE THREAD

**Issue by Shinkied** [SunwellTracker/issues#172]
Decription: 
Title, rogue's skill Cheap Shot cannot be blocked, dodged, or parried, and is meant to hit through hunters skill Detterance.

How it works: 
Cheap shot gets dodged by the hunter

How it should work: 
Cheap shot hits the hunter

Source (you should point out proofs of your report, please give us some source): 
https://www.mmo-champion.com/threads/706464-Hitting-through-deterrence
http://www.arenajunkies.com/topic/117257-cheap-shotting-through-deterrence/

**Comment by Shinkied** [comment]
http://www.wowhead.com/spell=1833/cheap-shot
additional proof 'cannot be parried or dodged'

**Comment by Afgann** [comment]
Will be fixed with next update.
