### ISSUE TITLE
[Icecrown] Jotunheim Graveyard, glitching through

### ISSUE THREAD

**Issue by Voidbound** [SunwellTracker/issues#1724]
**Decription:** If you die nearby the Jotunheim Graveyard in Icecrown, you'll be teleported to that graveyard on a gryphon. That gryphon glitches you in the Graveyard and it's kinda hard to get out of it.

It's pretty easy to reproduce, just die near the graveyard.

**How it works:** You get glitched into the terrain of the Graveyard if you are mounted on the ghost gryphon.

**How it should work:** You should not get glitched into the terrain.

**Source (you should point out proofs of your report, please give us some source):**  https://imgur.com/a/AD0HFwM

Screenshot of being glitched into the graveyard.

**Comment by Dootz** [comment]
using space helps in many cases
