### ISSUE TITLE
Quest Reconnaissance flight doesn’t work

### ISSUE THREAD

**Issue by sgtTosteR** [SunwellTracker/issues#1726]
Decription: 

reconnaissance flight by helicopter

How it works: 

Flies by helicopter, After the engine breaks back to the place where the quest came from

How it should work: 

The helicopter should move much faster which would allow it to come back on time.

Source (you should point out proofs of your report, please give us some source): 

The helicopter should move like on the video here
https://www.youtube.com/watch?v=aw-Eugwg7eI 

And it moves much slower

**Comment by Dootz** [comment]
Hi, when you take control of the helicopter pressing spacebar should resolve your issue.
