### ISSUE TITLE
Quest: Leave No One Behind, doesn't work at all.

### ISSUE THREAD

**Issue by Ragemaniacc** [SunwellTracker/issues#173]
Decription: Quest: Leave No One Behind, doesn't work at all.

How it works: Right now when you bandage a crusader you can escort it back to base but don't get progress for the quest.

How it should work: When you escort one of the quest npc:s to the camp you should get progress.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Duplicated.
