### ISSUE TITLE
[Random Dungeon Finder] Random Wotlk Heroic incorrectly locks dungeons.

### ISSUE THREAD

**Issue by marc-gj** [SunwellTracker/issues#1730]
Description:

When queueing for Random Wotlk Heroics, characters are being locked from dungeons after completion.

How it works: 

1. Queue for Random Wotlk Heroic.
2. Get into dungeon.
3. Complete dungeon.
4. Dungeon is locked.
5. Dungeon is removed from Random Wotlk Heroic pool.
6. Random Dungeon Finder only queues you for dungeons you haven't completed for the day.

How it should work: 

1. Queue for Random Wotlk Heroic.
2. Get into dungeon.
3. Complete dungeon.
4. Dungeon is not locked.
5. All dungeons still part of the Random Wotlk Heroic pool.
6. Queuing for dungeons all day long.

 

Source (you should point out proofs of your report, please give us some source): 

I couldn't find any source but if you poll any players from Wotlk or even retail, you will find that using the Random Dungeon queue does not lock you out of dungeons after completing them. You are only supposed to be locked out of dungeons if you queue for them specifically or if you enter the dungeon through the entrance.

Edit***

Proof of the bug: 
![locked](https://user-images.githubusercontent.com/17578489/43937823-fc7261bc-9c2d-11e8-9914-ad6932204cd5.png)

Here is a screen shot of my locked dungeons. I haven't queued specifically for a single one. All are locked via queuing for Random Wotlk Heroics.

**Comment by marc-gj** [comment]
More proof. I just got into the Azjol Nerub that I was missing, I queued Random Wotlk Heroic and : ![locked](https://user-images.githubusercontent.com/17578489/43938282-bfedc10c-9c30-11e8-8649-46151915ef27.png)

**Comment by Dootz** [comment]
That's intended behavior and won't be changed right now.

https://github.com/SunwellTracker/issues/issues/196
https://github.com/SunwellTracker/issues/issues/1659
https://github.com/SunwellTracker/issues/issues/684

**Comment by marc-gj** [comment]
Okay. Disappointed but thanks.
