### ISSUE TITLE
[Dungeon Finder] Not rewarding Emblems or Frozen Orbs.

### ISSUE THREAD

**Issue by marc-gj** [SunwellTracker/issues#1731]
Decription: 
Using the dungeon finder for random wotlk heroics is supposed to reward high tier emblems for the first random of the day along with a frozen orb. All subsequent dungeons are supposed to reward emblems of heroism.

How it works: 
RDF rewards xp wotlk heroics.

How it should work: 
Using the dungeon finder for random wotlk heroics is supposed to reward high tier emblems for the first random of the day along with a frozen orb. All subsequent dungeons are supposed to reward emblems of heroism.

Source (you should point out proofs of your report, please give us some source): 
Here I am at level 80 and it wants to reward xp.
![locked](https://user-images.githubusercontent.com/17578489/43938497-ecc7604c-9c31-11e8-9f13-1a4c22e6cc54.png)

**Comment by Azathothh** [comment]
No proofs + that's no true.
Frozen orb is always found in last boss of each heroic instance, i don't think it was ever awarded through DF tool. On retail it was added in patch 3.3.0, before that patch you could get "daily emblems" that you're talking about from daily dungeon quests available in dalaran (Proof of Demise + Timear Foresees).
In 3.3.0 those quests will be removed and extra emblems will be awarded for random heroics done through DF tool.
