### ISSUE TITLE
[Stats, Gems, Belt Buckle, Gem Slot Bonus]

### ISSUE THREAD

**Issue by marc-gj** [SunwellTracker/issues#1732]
Description:  

I have a helmet with a Meta gem that requires 2 red gems and 1 blue gem.
I have a belt that has a red gem socketed in. (Not a Blacksmith Buckle)
I obtain a new belt with higher defence than my current belt.
I go buy a new red gem and a Blacksmith Buckle to put it in so that my Meta gem works.
I put on the new belt and my defence stat lowers from 535 to 533.
I will include screenshots below.

How it works: 
Stats go down.

How it should work: 
Stats go up.

Source (you should point out proofs of your report, please give us some source): 
Here you can see the Rare belt is equipped(with red gem) and has a lower defence rating than the Epic belt in my bag(with red gem).
You can also see that my Defence stat is at 535
![wowscrnshot_081018_002128](https://user-images.githubusercontent.com/17578489/43939024-1b699548-9c35-11e8-99f6-6e242be7714d.jpg)
Here you can see I put on the Epic belt and my Defence stat dropped to 533 when it should have increased to 536 - 537 
![wowscrnshot_081018_002135](https://user-images.githubusercontent.com/17578489/43939028-1fce0ae2-9c35-11e8-9a5b-5c5de534ef0c.jpg)
Here you can see my Meta gem while wearing the Epic belt looks fine but it seems as though even though it looks like it is working I'm not getting the stats. Or that is the only explanation I can come up with.
![wowscrnshot_081018_002144](https://user-images.githubusercontent.com/17578489/43939032-22ee75cc-9c35-11e8-8673-6544e64d2ec6.jpg)

**Comment by Azathothh** [comment]
#1579
