### ISSUE TITLE
AFK chat spam

### ISSUE THREAD

**Issue by ErasmusHereticus** [SunwellTracker/issues#1733]
Decription: 
AFK-ing for prolonged periods of time causes the chat to spam the messages "You are now AFK" and "You are no longer AFK". The name tag above the character does the same.

How it works: 
Stay AFK for 5 minutes or more.

How it should work: 
There should be no text or name tag spam.

Source (you should point out proofs of your report, please give us some source): 
Here's a screenshot; https://i.imgur.com/KMHswm8.jpg

**Comment by Nadiirr** [comment]
Were you in Wintergrasp when this happened?
( I ask because I had a similar issue while in WG)

**Comment by Darnek92** [comment]
its most likely and addon related issue, if you know how to trigger it you can try with addons turned off and see if its gone

**Comment by Riztazz** [comment]
@Darnek92 is right, most likely carbonite
