### ISSUE TITLE
[Shutting Down Manaforge Ara] Quest not working!

### ISSUE THREAD

**Issue by danysilva** [SunwellTracker/issues#1736]
Decription:  
1ºkill Overseer Azarad, then with the drop "Ara acess crystal" we can start the Shut Down ManaForge in the Console.

How it works: 
Everytime we try to Shut Down ManaForge, it says aborted, even when the NPC'S don't touch on it.

How it should work: 
Click in the console and start the shut down, NPC'S should start spawning and try to abort the mission, and we need to kill them so we can shut down the ManaForge. It should handle some damage from NPC's before aborted the mission, and after 2 mins we complete the mission.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_081218_002949](https://user-images.githubusercontent.com/20100435/43996619-0065e0c4-9dc7-11e8-9998-6f95286ea003.jpg)

**Comment by zexwildbacon2** [comment]
it works i done it few days ago.
