### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by 48477151** [SunwellTracker/issues#1737]
Decription: 
i can  see any NPC in stormwind city
and i am dk level 80

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,
you probably started chain quest Battle for the Undercity.
You should be able to pick up next quest near Wrathgate if i'm not mistaken.
https://wow.gamepedia.com/Battle_for_the_Undercity
