### ISSUE TITLE
[Meta Gem] Shield Block Value

### ISSUE THREAD

**Issue by Huberrtt** [SunwellTracker/issues#1739]
Decription: Meta gem nie dziala , nie dodaje prawidłowo statystyk które powinny być (+5% Shield Block Value)

How it works: Meta gem który powinien dawać +5% SBV ( shield block value) tego nie daje mimo spełniana warunków 

How it should work: Meta gem powinien zwiększyć SBV , jedynie str ktory jest w itemie ( goglach ) dodaje ten SBV , GEMU nie bieże pod uwage 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_081218_224322](https://user-images.githubusercontent.com/42325460/44006286-48cdb286-9e82-11e8-8e20-0fc5946a1818.jpg)
![wowscrnshot_081218_224317](https://user-images.githubusercontent.com/42325460/44006287-48e92322-9e82-11e8-8267-0b353a9f7e7b.jpg)
![wowscrnshot_081218_224327](https://user-images.githubusercontent.com/42325460/44006289-4f877878-9e82-11e8-8be0-db164e8d84f4.jpg)

**Comment by Azathothh** [comment]
#1579
