### ISSUE TITLE
Val'anyr Druid HoTs not working properly

### ISSUE THREAD

**Issue by Notmelody** [SunwellTracker/issues#1740]
Decription:  Druids hots not proccing Val'anyr 

How it works: 

- Only direct heals (Healing Touch / Swiftmend / Nourish / Regrowth / t8 4set) reliably procs the mace blessing buff, however druid Heal over Time does not.

How it should work: 

- HoTs should trigger the ICD blessing of val'anyr

Source (you should point out proofs of your report, please give us some source): 

- Original Ghostcrawler/Bornakk explanation blue post https://i.imgur.com/ggFcfYm.png

- Video proof on current sunwell angrathar server -

Hots not triggering mace - https://youtu.be/NwdJFPo38Ts
(In the end i show how reliably direct heal such as nourish easily trigger the blessing ICD)

**Comment by Notmelody** [comment]
Is this being looked at? or did i waste time collecting fragments 💯

**Comment by Kokaina** [comment]
High priority here.

**Comment by gabbat** [comment]
procc chance is wayy to low as well, it should be 10% and currently it is way below that

ghostcrawler quote:
https://www.mmo-champion.com/threads/647148-Val-anyr-Hammer-of-the-Ancient-Kings

**Comment by Notmelody** [comment]
Changelog update has been pushed, yet this was not.

I guess fixing majordomo spawning near ragnaros is slightly more important than a legendary item.

**Comment by Riztazz** [comment]
Gonna be live with next realm update
