### ISSUE TITLE
Kvaldir Raider Respawn Timer (incorrect?)

### ISSUE THREAD

**Issue by Mordecaii2018** [SunwellTracker/issues#1742]
Description: Hi all, just noticed that these enemies (Kvaldir Raider) respawn on an irregular basis, as opposed to what I remember.

How it works: 
![c139c850ebd19e3ee7f6fea1964fbf1f](https://user-images.githubusercontent.com/42352179/44046481-e5324548-9f2b-11e8-9525-f24a543bf12f.png)

How it should work: They used to respawn around 15-25 seconds after being killed, but now, as shown above, they take a lot longer. Please see screenshot attached below of proof. In the comment, cloth refers to Frostweave Cloth, as these mobs used to typically drop at least 1 cloth each, but having killed around 20 of them only netted me 12 pieces of cloth (maybe I'm just unlucky), compared to the image below.

Source (you should point out proofs of your report, please give us some source): 

![6aff5f3d3955c2a42e31b06b7382c357](https://user-images.githubusercontent.com/42352179/44046737-adfe94ae-9f2c-11e8-8e36-c2f6b207a816.png)

Many thanks for looking into this.

Kind Regards,

Mordecaii

**Comment by Dootz** [comment]
Hmm... their respawn time is consistent in different wotlk databases so i don't think that " They used to respawn around 15-25 seconds after being killed," is enought to change it. Also drop chance seems ok, as wowhead says it's around  24% to get 1-3 of cloth https://www.wowhead.com/npc=25760/kvaldir-raider
