### ISSUE TITLE
[mob][pickpoket] Greengill Slave

### ISSUE THREAD

**Issue by LittleAmnesia** [SunwellTracker/issues#1747]
Decription: 
missing drop

How it works: 
missing normal drop and pickpoket drop

How it should work: 
drop standard items

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=25084/greengill-slave#pickpocketing

**Comment by Dootz** [comment]
fixed

**Comment by Dootz** [comment]
ok, thank you for testing. I'll check again.

**Comment by Dootz** [comment]
yeaa sorry about that. Now they are drop thing but with really small drop chance. It will be fixed with next server update. Pickpocket loot should work aswell.
