### ISSUE TITLE
[Scarlet Monastery Graveyard - Fallen Champion]

### ISSUE THREAD

**Issue by dreamingdust** [SunwellTracker/issues#175]
Decription: 
NPC Fallen Champion (https://wotlk-twinhead.twinstar.cz/?npc=6488) gets stuck.

How it works: 
The path between the NPC and the player cannot be followed because of the NPC's position which leads to it getting stuck upon pull. Both times we encountered the NPC we pulled from in front of the tomb, so there might be a way to make the NPC go to the player if it is pulled from the sides.

How it should work: 
The NPC should not get stuck in the textures and should go to the player when aggroed.

Source (you should point out proofs of your report, please give us some source): 
http://i67.tinypic.com/izrg4m.jpg

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
