### ISSUE TITLE
Wailing caverns not reseting 

### ISSUE THREAD

**Issue by vengeance0011** [SunwellTracker/issues#1750]
Decription: 
When we have cleared the entire dungeon on horde side we wiped at the final boss when the murloc spawned and there was couple of adds left. The disciple of naralex was killed and we couldn't reset the fight he wasn't at the start of dungeon anymore or anywhere else he disappeared.

How it works: 
Wiping at the last boss in Wailing Caverns and getting the disciple of naralex killed will not let you complete the dungeon anymore because he won't respawn to reset the fight.

How it should work: 
The disciple of naralex should spawn at the beginning of the dungeon after a wipe or he gets killed so the fight can be restarted.

Source (you should point out proofs of your report, please give us some source):  I don't have any video or screenshots for this but if there is any instance logs it happened on august 16th around 3:30 to 4am server time.

**Comment by Akha72** [comment]
The final encounter does not reset in this patch. If you fail at the last boss, you need to reset the entire instance manually and start from scratch or just zone out in if you got there through rdf.

2.4.2
If he dies it's game over. You have to restart the whole instance to begin the escort again.

4.0.3
Does Muyoh respawn? >.>

Ouch, no respawns... Rough.

4.1.0
The no respawn thing really stinks when one of the dps starts a drama fight in the middle of everything, and the NPC walks off and gets himself killed before you notice him.

4.0.3
Yeah, no respawns. God, Blizz must be too lazy.

and 

5.0.3
I forget when they hotfixed it, but as of 5.3, Muyoh can no longer be killed - his health will never drop below 1%.
(It was hotfixed after 5.3 was released. I guess they got enough complaints about people getting placed into a dead and uncompletable WC with LFD. It only took 3 years!)

WH (https://www.wowhead.com/npc=3678/muyoh#comments)
