### ISSUE TITLE
Wintergrasp bug upon winning as attacker

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#1754]
Decription: After winning as attacker aka capturing WG the south towers and fortress doesnt update and still look like before the battle. Towers are still horde controlled and the fort is blue on map as if it would be ally controlled but the npcs and flags in fort are horde controlled, this also makes a problem with the quest Slay Them All cuz there are no alliance npcs south to kill since towers are still marked as horde which means you need to wait 2 hours and half till next battle when ally npcs spawn. 
http://prntscr.com/kjid4u you can see in screenshot on right corner that on minimap fortress is blue yet horde controls it and south towers are still marked as horde controlled.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by alexandru58** [comment]
Developers? Can you fix this please?? Thanks!
