### ISSUE TITLE
Can't accept Call to Arms quest at Alliance brigadier general

### ISSUE THREAD

**Issue by Thalydo** [SunwellTracker/issues#1755]
Decription: 
I can't pick up the daily Call to Arms quest from the alliance brigadier general

How it works: 
When I talk to the alliance brigadier general it shows me the badge shop and I can't take the daily BG quest.

How it should work: 
It should allow me to show a screen where I can choose to go to the shop for badges or take the Call to Arms quest.

Source (you should point out proofs of your report, please give us some source): 
All my friends got this issue.

**Comment by MrTide** [comment]
Hello as far as i know call to arms starts on Friday and ends on Monday .. you can't take that quest any other day also you can't take that quest again if you abandon it

**Comment by Thalydo** [comment]
Oh I thought it was a daily quest. The blue marker above the alliance brigadier general causes confusion tho.
