### ISSUE TITLE
[Mining] Too much Titanium

### ISSUE THREAD

**Issue by mondegoftw** [SunwellTracker/issues#176]
Decription: Titanium nodes spawn way too often. This kind of bug report is difficult, because it's hard (impossible?) to find a source that provides metrics on how often they should spawn; but its an important bug report since the current state of titanium spawns would sort of ruin the economy if it's still like this when the bulk of players hit level 80.

How it works:  Titanium nodes spawn way too often. Seems to occur in every zone. Most other mining node spawns seem OK (maybe saronite spawns a bit too much and cobalt is probably too scarce, but they are roughly normal).

How it should work: Titanium should be rare. Titanium should be expensive. Look at how many epic recipes have Titanium as their most expensive component - this is not compatible with a server where it's possible to farm 20 titanium in 10 minutes.

Source (you should point out proofs of your report, please give us some source):

**Comment by Trsko** [comment]
Been mining all day, seems ok to me, even cobalt and saronite.

**Comment by mondegoftw** [comment]
I find it far easier to find Titanium than Cobalt, for example. But yeah, time will tell. I think any responsible developer would reduce the Titanium nodes at least temporarily so the market doesn't get flooded with them, but that's just me.

**Comment by Trsko** [comment]
Market is gonna be flooded for 2 days then its gonna start to even out, trust me, titanium and saronite are ok, they're even more realistic than other wotlk projects, any responsible dev, if i even have the rights to utter that sentence, would wait and see in this case. there are tons of cobalt and rich cobalt in all zones pre sholazar. 
Dragonblight: https://gyazo.com/e4c172bcd6e81090842d6866b09dce90
Borean: https://gyazo.com/7b6c2fb7d1bae420c267e7d4645ee24e
Zul'Drak: https://gyazo.com/e75f3fb95d248f9bd3ea584cb531dc84
![image](https://user-images.githubusercontent.com/30490969/35771446-44b1ec70-092d-11e8-99d9-1120c211d1da.png)

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
