### ISSUE TITLE
[Quest-Outland] Banish the Demons & Banish More Demons

### ISSUE THREAD

**Issue by Sanders9352** [SunwellTracker/issues#1762]
Decription: 
Quest works perfectly normal, only that it awards more kill counts than normal.
http://db.darkwizard.pl/?quest=11026
http://db.darkwizard.pl/?quest=11051

How it works: 
1 demon killed awards 2 banished demons

How it should work: 
1 demon killed should award 1 banished demon

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=DgSVWLLlG_Y

**Comment by Dootz** [comment]
fixed
