### ISSUE TITLE
(Quest) Intercept the Reinforcements & Keeping the Enemy at Bay

### ISSUE THREAD

**Issue by Sanders9352** [SunwellTracker/issues#1765]
Decription: 
http://db.darkwizard.pl/?quest=11542
http://db.darkwizard.pl/?quest=11543

How it works: 
After burning the sails and killing 6 mobs, player cannot take Unrestrained Dragonhawk back to the shore
http://db.darkwizard.pl/?npc=25236

How it should work: 
After burning the sails and killing 6 mobs, quest completes and the player is able to use Unrestrained Dragonhawk to go back to the shore

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=hZuJSqWsyQM

**Comment by Dootz** [comment]
fixed
