### ISSUE TITLE
(Quest) Isle of Quel'Danas

### ISSUE THREAD

**Issue by Sanders9352** [SunwellTracker/issues#1767]
Decription: 

How it works: 
All of these daily quests are available each day
http://db.darkwizard.pl/?quest=11520
http://db.darkwizard.pl/?quest=11545
http://db.darkwizard.pl/?quest=11538
http://db.darkwizard.pl/?quest=11532
http://db.darkwizard.pl/?quest=11542
http://db.darkwizard.pl/?quest=11539
http://db.darkwizard.pl/?quest=11535
http://db.darkwizard.pl/?quest=11520
http://db.darkwizard.pl/?quest=11521
http://db.darkwizard.pl/?quest=11548
http://db.darkwizard.pl/?quest=11537
http://db.darkwizard.pl/?quest=11533
http://db.darkwizard.pl/?quest=11543
http://db.darkwizard.pl/?quest=11540
http://db.darkwizard.pl/?quest=11536
http://db.darkwizard.pl/?quest=11521

How it should work: 
Once first quest is completed, it's no longer available, second one becomes available and it's a daily quest.

http://db.darkwizard.pl/?quest=11520 -> http://db.darkwizard.pl/?quest=11521
http://db.darkwizard.pl/?quest=11545 -> http://db.darkwizard.pl/?quest=11548
http://db.darkwizard.pl/?quest=11538 -> http://db.darkwizard.pl/?quest=11537
http://db.darkwizard.pl/?quest=11532 -> http://db.darkwizard.pl/?quest=11533
http://db.darkwizard.pl/?quest=11542 -> http://db.darkwizard.pl/?quest=11543
http://db.darkwizard.pl/?quest=11539 -> http://db.darkwizard.pl/?quest=11540
http://db.darkwizard.pl/?quest=11535 -> http://db.darkwizard.pl/?quest=11536
http://db.darkwizard.pl/?quest=11520 -> http://db.darkwizard.pl/?quest=11521

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=11521/rediscovering-your-roots
https://www.wowhead.com/quest=11548/your-continued-support
https://www.wowhead.com/quest=11537/the-battle-must-go-on
https://www.wowhead.com/quest=11533/the-air-strikes-must-continue#comments
https://www.wowhead.com/quest=11540/crush-the-dawnblade
https://www.wowhead.com/quest=11536/dont-stop-now#comments
https://www.wowhead.com/quest=11543/keeping-the-enemy-at-bay
https://www.wowhead.com/faction=1077/shattered-sun-offensive#comments

**Comment by Dootz** [comment]
should be fine now
