### ISSUE TITLE
[Chain Heal] bounce on full HP targets

### ISSUE THREAD

**Issue by Brygga** [SunwellTracker/issues#177]
Decription: 
Chain heal bouncing on full health players, this is not correct it shouldnt jump on full health players. When you cast a chain heal and all players within range of the jump distance is full hp Chain heal stop jumping and only hit the player you cast on. 

How it works: 
Chain heal bouncing on full health players

How it should work: 
when you cast a chain heal and all players within range of the jump distance is full hp Chain heal should not jump. Chain heal shouldnt jump at all on full health players, no matter the situation.

Source (you should point out proofs of your report, please give us some source): 
Here you can see at 5:10 time stamp what i explained. 
This is from world first Lich King Heroic kill (retail patch 3.3)
https://youtu.be/RSeVCw3hVgQ?t=304 

Here alot more situations for example on 9:55. 
(retail patch 3.1 world first yogg saron normal mode) 
https://youtu.be/Pf4MAONG1vs?t=591 

And also here from patch 4.3 retail time stamp 2:56 as an example. 
https://youtu.be/EW4W21KMQWU?t=175
Here the shaman casted Chain heal on himself and all players around was full health, hence it did not jump.

I hope with this you see what i mean. Its not working correctly at the moment.

**Comment by Afgann** [comment]
Will be fixed with next update.
