### ISSUE TITLE
Noggenfogger Elixir Auto Attack Bug

### ISSUE THREAD

**Issue by sosleague** [SunwellTracker/issues#1771]
Decription: Cant auto attack after using Noggenfogger Elixir.

How it works: cant auto attack after using Noggenfogger Elixir. I m forced to log out of the game and log back in. Ive tried switching stances/weapons in warrior. Doing any ability that involves autoattacks and it just doesnt work until i log out of the game and back in.

How it should work: You should be able to use Noggenfogger Elixir and be able to auto attack.

**Comment by Akha72** [comment]
Duplicate https://github.com/SunwellTracker/issues/issues/1650
