### ISSUE TITLE
Escape From Durnholde 

### ISSUE THREAD

**Issue by TariqPrst** [SunwellTracker/issues#1775]
Decription: After you complete the first quest " Taretha's Diversion " you take the quest from Thrall but you don't have the option to chat and begin the actual scenario.

How it works: You can't start the quest so you get stuck in the middle of it.

How it should work: After you take the quest you should be able to talk to him and begin the quest

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/AR4xuLm

**Comment by MrTide** [comment]
Hello
Did you finish the first part of the event ? burning houses and killing the lieutenant drake ? first boss ? he spawns after setting the houses on fire
