### ISSUE TITLE
Twilight Corrupter Bug

### ISSUE THREAD

**Issue by ahmetcizmecioglu** [SunwellTracker/issues#1779]
Decription: 
I was watching the Twilight Corrupter in duskwood, he was alive and i was getting ready to call my friends to kill it but it disappeared for not any reason. I have to do quest but waiting it since 2 hours.

How it works:  The mob is stay near to pool in the middle of Duskwood. Near to Tearar boss.

How it should work:  It shouldnt disapear for nothing. Most people wants to do scarab lord title quest chain so you have to solve the problem please. Thank you...
![duskwood boss disapear](https://user-images.githubusercontent.com/42662019/44560761-ecb4cd00-a759-11e8-92b5-2b6bbb725ae5.png)
 for nothing. Probabbly there is a bug because first time i have seen it vanish

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
He disappers after 4 minutes out of combat, you can summon him again if you have quest in your questlog. Just walk/ride around for a bit to trigger his spawn.
