### ISSUE TITLE
[Hunter] - [Deadly Gladiator's Chain Spaulders]

### ISSUE THREAD

**Issue by Pirzmaker** [SunwellTracker/issues#1780]
Decription: 
Missing [Deadly Gladiator's Chain Spaulders]

How it works: 
I dont see [Deadly Gladiator's Chain Spaulders] ( http://db.darkwizard.pl/?item=41216 ) in Emblem of Conquest Vendor [Magister Sarien] in Dalaran, so i cant buy this item.

How it should work: 
i should be able to see and buy [Deadly Gladiator's Chain Spaulders] in [Magister Sarien] vendor.

Source (you should point out proofs of your report, please give us some source):

**Comment by Sanqell** [comment]
What is progres?

**Comment by Dootz** [comment]
fixed, should be able to buy them now.
