### ISSUE TITLE
Casting throguh wall

### ISSUE THREAD

**Issue by feralxgodx** [SunwellTracker/issues#1781]
Decription: 
Could you please fix casting through wall? its insane that when im hidding behind any object caster still can hit me...

How it works: Casters can cast through walls - 100% work on warsong gulch

How it should work: 
Stop casting??

**Comment by Akha72** [comment]
Where exactly? Most objects and terrain elements in WsG are patched. Btw melee can still hit through walls if in range.

**Comment by feralxgodx** [comment]
https://imgur.com/a/AH4UU7z 
Bugged places i remember, for sure there are more.

**Comment by feralxgodx** [comment]
can be close.
