### ISSUE TITLE
Investigate the blue Recluse

### ISSUE THREAD

**Issue by Lenivietz** [SunwellTracker/issues#1782]
Decription: 
It doesn't work at all.

How it works: 
There is no scripting. When you walk into a tavern there are supposed to be mob spawns and scripting in order to complete it yet there is none.
How it should work: 
As explained above.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=t0jFkP1k2ag
https://forum.sunwell.pl/index.php?/topic/5968-quest-investigate-the-blue-recluse-bug/

**Comment by Dootz** [comment]
How to complete it:
1. Pick up Chest of Containment Coffers and one of the scrolls (Cantation of Manifestation) from the table next to Jennea Cannon.
2. Go to tavern.
3. Go upstairs/ to the basement.
4.  use Cantation of Manifestation
5. Rift Spawns will appear
