### ISSUE TITLE
Mistress Nagmara won't open the door

### ISSUE THREAD

**Issue by joyboyz** [SunwellTracker/issues#1783]
Decription: 
She is an npc in the Grim Guzzler that should allows another option to leave the bar backdoor besides fighting the npc guarding it.

How it works: 
When you click to talk to Mistress Nagmara, she won't leave the room with Private Rocknot, no matter how many times you click

How it should work: 
After you finish the quest you should be able to talk to her, and get her along with Private Rocknot to open the bar door.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Mistress_Nagmara

**Comment by Dootz** [comment]
from next update (Tuesday/Wednesday) she'll open bar doors but there will be no RP event yet (she'll just disappear). I'll try to prepare something for next week, although there's not much data how it should look so it'll be a bit custom-ish.
