### ISSUE TITLE
Quest - The Hero's Arms 

### ISSUE THREAD

**Issue by Sanqell** [SunwellTracker/issues#1785]
Decription: 
I do 5 quest in chain and nothink to take now. Its should by The Hero's Arms

How it works: 
Nothink to take

How it should work: 
The Hero's Arms , then Changing the Wind's Course

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://www.wowhead.com/quest=13049/the-heros-arms#comments:id=656814
"You get this quest after handing in Memories of Stonehoof and Distortions in Time."
If you can't get this quest it means that you haven't done one or both quests mentioned above.
