### ISSUE TITLE
[Ulduar - Razorscale]

### ISSUE THREAD

**Issue by LocalFarmer** [SunwellTracker/issues#1786]
Decription: 
The flame breath attack performed in ulduar once the dragon lands is extremely downscaled to the retail version. Thus making it extremely difficult and time consuming to finnish one of the most annoying ulduar glory achievements to obtain the proto drake. The damage reduction might of scaled once the Razorscale nerf happened, potentially ruining the original flame breath mechanic.

How it works: 
The dragons breath in 10 man (phase 1) hits for approximately +/- 1-2k damage (test was performed in 10 man instance), which is insufficient in comparison to the retail damage. Knowing that the defenders are attacking the monsters too (which wasn't a thing in retail) it makes it extremely hard to complete this achievement.

How it should work: 
Dragons attack [Flame Breath] should hit anyone standing infront of the boss for aproximate damage of 12-15k.

Source (you should point out proofs of your report, please give us some source): 
'Razorscale can be brought to the ground by letting the friendly dwarves repair the Harpoon Guns. She will no longer fly up once her health is reduced to 50%. As long as Razorscale is on the ground, she will use Flame Breath, dealing 13125 to 16875 damage in a frontal cone. Bring Dark Rune Guardian dwarves to low health and drag them into this cone to kill them.' 
https://www.wowhead.com/achievement=2923/iron-dwarf-medium-rare-10-player#comments

**Comment by Soufly** [comment]
We even use the breath from berserk to complete the achievement.We stacked like 50 mobs,and we got credit for 1.

**Comment by Riztazz** [comment]
Fix will be live today after restart, closing
