### ISSUE TITLE
[mob] Venture Co. Evacuee (one more time)

### ISSUE THREAD

**Issue by LittleAmnesia** [SunwellTracker/issues#1787]
Decription: 
mob is currently giving rep, but wrong ammount. i noticed that all mobs gives 5 times more rep than they should
25/12 venture co. geologist/mechanic
125/62 foreman cozzle
resp time of evacuee is wrong and should be fixed

How it works: 
respawn time around 5 minutes
25/12 rep per mob

How it should work: 
fast respawn to keep 2 mobs (15-30 seconds according to some informations)
5/2 rep per mob

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Venture_Co._Evacuee
http://wowwiki.wikia.com/wiki/Venture_Co._Evacuee
https://us.battle.net/forums/en/wow/topic/8197862246

**Comment by Dootz** [comment]
should be fine now

**Comment by LittleAmnesia** [comment]
respawn still need fix.

source:
https://www.youtube.com/watch?v=b_9I1krglJA

Venture Co. Evacuee near stairs inside of ship killed at 1:22 next time killed 1:45
20 sec respawn time. 
"There must be at minimum two evacuees on the ship at all times, so they will respawn as quickly as needed to maintain their presence." - https://wow.gamepedia.com/Venture_Co._Evacuee

**Comment by Dootz** [comment]
I'll reduce their respawn time but due to corpse delay it won't be as fast. NPC on global servers respawn much faster nowadays.
