### ISSUE TITLE
Quest [Recover the Cargo!] impossible to complete.

### ISSUE THREAD

**Issue by Nadiirr** [SunwellTracker/issues#1789]
Decription: 
Impossible to complete - Can't get the Salvaged Strongbox. (Helmet is on and opened the bag that the quest gives you, still no luck.)

How it works: 
Should click quest item [Salvage Kit] near a Shipwreck Debris and it will give you credit. 
Currently there are shipwreck debris spawned, when I look them up with GM commands but ingame they show up as "Burning Wreckage" and don't work for this quest.

How it should work: 
Should give quest credit when using the item near the debris. 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=S28r-OIzHcc
https://db.darkwizard.pl/?quest=11140

**Comment by Dootz** [comment]
should work right now

**Comment by Girbelinha** [comment]
Still doesn't work :( , when i use the quest item [Salvage Kit] near the Shipwreck Debris it just spawns a murloc that gives no loot and the quest does not complete , tried about 20 times and still a murloc spawnd .
