### ISSUE TITLE
Quest: Kickin' Nass and Takin' Manes

### ISSUE THREAD

**Issue by tHLimperius** [SunwellTracker/issues#179]
Decription: 
Kickin' Nass and Takin' Manes a quest in Zul'Drak Ebonwatch isn't working properly

How it works: 
Nass only has 528 hp

How it should work: 
I think he should have more, he gets one shot by everything

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/36095183/35763176-bd23518e-086b-11e8-8772-390f11df07bf.png)

**Comment by Dootz** [comment]
Source: http://www.wowhead.com/npc=28521/nass#comments:id=372622:reply=87147

> Soldier45 on 2009/03/23 (Patch 3.0.9)
> This fellow here only has 529 health, so if you can't get aggro on your first attack, let's just say it'll be a while before you complete your quest.

Other comments also suggest that he dies quite quickly. That being said i think it's intentional and should remain as it is.
