### ISSUE TITLE
[Culling of Stratholme] Arthas Exorcism spam without cd

### ISSUE THREAD

**Issue by randomname159** [SunwellTracker/issues#1793]
Decription: 

How it works: 
Arthas in CoS dungeon doesn't have cd for his exorcism spell.

How it should work: 
Arthas Exorcism should has some sec of cooldown (probably 15 sec like default paladin Exorcism cooldown)
https://www.wowhead.com/npc=26499/arthas#abilities:mode=heroic
https://www.wowhead.com/npc=26499/arthas#abilities:mode=normal

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/PvtsLfBOwec?t=21m40s
https://www.youtube.com/watch?v=wmN3040a-aI

**Comment by Dootz** [comment]
fixed
