### ISSUE TITLE
[Halls of Lightning] Titanium Siegebreaker/Thunderer pull through the walls

### ISSUE THREAD

**Issue by randomname159** [SunwellTracker/issues#1794]
Decription: 

How it works:
https://db.darkwizard.pl/?npc=28961
https://db.darkwizard.pl/?npc=28965
pulls through the wall when You enter to the green area of The Terrestrial Watchtower
![wowscrnshot_082818_195952](https://user-images.githubusercontent.com/42775316/44741363-1a549a00-aafd-11e8-8033-01b63f15fff1.jpg)

How it should work: 
Mobs shouldn't pull.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
fixed
