### ISSUE TITLE
[Gundrak] Gal'darah Puncture debuff should dissappear after boss fight

### ISSUE THREAD

**Issue by randomname159** [SunwellTracker/issues#1795]
Decription: 

How it works: 
Gal'darah Puncture debuff don't dissappear after defeat boss.

How it should work: 
Gal'darah Puncture debuff should dissappear after defeat boss.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/fcj3mP-_rl8?t=1m59s
https://www.wowhead.com/npc=29306/galdarah#abilities:mode=heroic
https://www.wowhead.com/npc=29306/galdarah#abilities:mode=normal

**Comment by Dootz** [comment]
fixed
