### ISSUE TITLE
Quest [Recover the Cargo!] impossible to complete. 

### ISSUE THREAD

**Issue by Girbelinha** [SunwellTracker/issues#1796]
Decription: 
Impossible to complete - Can't get the Salvaged Strongbox.

How it works: 
When you open the bag [Renn's Supplies] it should give you two items , [Repaired Diving Gear] and [Salvage Kit] it does , when i put on the helmet and go underwater near the shipwreck debris and i use the item [Salvage Kit] it does not give you the quest but spawns a murloc , i did it twenty times and still murloc spawns and no quest.
How it should work: 
It should give me the quest item [Salvaged Strongbox] when i use the quest item [Salvage Kit] on the shipwreck debris but it doesnt.
Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=S28r-OIzHcc
https://db.darkwizard.pl/?quest=11140

**Comment by Dootz** [comment]
I'm really sorry about that, this time I made sure it works correctly and will award credit. Will be fixed with next server update.

**Comment by Dootz** [comment]
fixed
