### ISSUE TITLE
[A Guide to Northern Cloth Scavenging] Item drops if character doesn't have tailoring

### ISSUE THREAD

**Issue by randomname159** [SunwellTracker/issues#1797]
Decription: 

How it works: 
A Guide to Northern Cloth Scavenging https://www.wowhead.com/item=43876/a-guide-to-northern-cloth-scavenging drops if character doesn't have tailoring proffesion. My char has only mining and this book still drops from mobs on dungeons.

How it should work: 
This item has a chance to drop from any mob in Northrend. It only drops for tailors that do not already know Northern Cloth Scavenging.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/A_Guide_to_Northern_Cloth_Scavenging
https://www.wowhead.com/item=43876/a-guide-to-northern-cloth-scavenging
https://db.darkwizard.pl/?item=43876#?ref=sunwell.pl

**Comment by Dootz** [comment]
Hi, do you remember in which dungeon it dropped for you?

**Comment by randomname159** [comment]
Hello, It was while Drak'Tharon Keep dungeon if my memory is not wrong :)
