### ISSUE TITLE
Priest Talents, Shadow Weaving not procing for Devouring Plague

### ISSUE THREAD

**Issue by andreiacostinoaei** [SunwellTracker/issues#1798]
Decription: Devouring Plague is not adding stacks of Shadow Weaving

How it works: Shadow Weaving it is not procced when using Devouring Plague, I played on other server and it should proc, also lots of guides out there even from vanilla from official says that Devouring Plague should apply 1 stack of Shadow Weaving...

How it should work: Shadow Weaving should proc when a shadow spell is used, 1 tick for Mind Blast or for Shadow Word: Pain, Devouring Plague or 3 ticks for Mind Flay if fully casted...

Source (you should point out proofs of your report, please give us some source): Just try on a lvl 23+ shadow priest with 3 points in Shadow Weaving, use Devouring Plague you will get no stack of Shadow Weaving, use other shadow spells, it will stack...

**Comment by FolMing** [comment]
It applies 1 stack on my 65 lvl priest, working correctly

**Comment by wonszopaionk** [comment]
Read the description - it says about "damage spells". You won't get the instant stack of SW from DP unless you have impr. DP talent.

**Comment by andreiacostinoaei** [comment]
Then how come Shadow Word: Pain and Vampiric touch gives stacks? Explain that...
