### ISSUE TITLE
[Warlock] Haunt + last hit

### ISSUE THREAD

**Issue by Bjarzyna** [SunwellTracker/issues#18]
Decription: 
Problem w przypadku dobicia przeciwnika ze spella haunt, szczególnie przeszkadzający przy levelowaniu.

How it works: 
W przypadku gdy spell haunt zada ostatnie uderzenie (overkill damage) to leczy nas zawsze za równe 100 niezależnie od tego ile obrażeń zadał

How it should work: 
Haunt leczy za 100% obrażeń jakie zadał (minus overkill) podobnie do drain life (który działa pod tym względem dobrze)

Source (you should point out proofs of your report, please give us some source): 
https://wotlk.evowow.com/?spell=59164 Haunt

**Comment by mateuszwalczyna** [comment]
@up 
Skill fix not implemented yet.
