### ISSUE TITLE
[Enchanting] Abyssal Shatter does not grant +skill

### ISSUE THREAD

**Issue by mdindoffer** [SunwellTracker/issues#1800]
Decription: 
[Abyssal Shatter](http://db.darkwizard.pl/?spell=69412) is a 445 Enchanting skill taught by a trainer to convert Abyss Crystals into Infinite Dusts and Greater Cosmic Essences. 

How it works: 
When transforming the crystals, other lesser mats are created, but no skill is awarded for the process, although the skill is orange.

How it should work: 
It should follow the same rules as other trade recipes - i.e. grant +1 skill up each time an orange recipe is made.

Source (you should point out proofs of your report, please give us some source): 
Countless guides promoting the spell as a nice free enchanting skill up, e.g.: https://www.wowhead.com/spell=69412/abyssal-shatter#comments

Evidence:
I've performed the "Trade spell" three times, but did not receive any enchanting skill doing so. Captured on the screenshot:
![wowscrnshot_090118_205730](https://user-images.githubusercontent.com/12681399/44949090-894a2f80-ae2a-11e8-92be-f701f18fbaca.jpg)

**Comment by Dootz** [comment]
fixed
