### ISSUE TITLE
Huge pvp bug, druids shapeshifting out of poly.

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#1803]
Decription: So I've done so many arena games against resto druids on my mage, I get a focus deep into poly on him while he is human form, I do get poly cast off, and he just simply shapeshifts out of it without using a trinket or anything. (ofc he didnt have anyone dispelling or something like that because he's playing with a warrior)

How it works: Resto druids (not sure about other specs but probably same for them) can just simply shape shift out of mage's polymorphs without using a trinket. 

How it should work: If a druid gets polymorphed in his caster/human form he shouldn't be able to shapeshift out of it, only way for him to get out of it is to either get dispelled or trinket.

Source (you should point out proofs of your report, please give us some source): https://eu.battle.net/forums/en/wow/topic/16883848325
https://us.battle.net/forums/en/wow/topic/16491599508

**Comment by Akha72** [comment]
Tooltip (https://db.darkwizard.pl/?spell=783) ?

Shapeshift into travel form, increasing movement speed by 40%. Also protects the caster from Polymorph effects. Only useable outdoors.

The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.

**Comment by Vessler** [comment]
It protects you from polymorphs yeah, it means, you can't get poly'ed if you are already in a shapeshift form, but if you get polied during human/caster form, you can't just shapeshift out of it.
