### ISSUE TITLE
[Warrior]Berserker stance quest

### ISSUE THREAD

**Issue by molgus** [SunwellTracker/issues#1806]
Decription: 
I can't get quest "The Affray" (link below). I gave back fisrt quest from warrior trainer, but can't get next one.
Relog, alt+f4, deleting cache didn't help

How it works: 
Questgiver just saying Greetings.
![wowscrnshot_090418_130113](https://user-images.githubusercontent.com/42965676/45027954-575fe580-b043-11e8-8add-45592f9ac582.jpg)

How it should work: 
He should give me the quest [http://db.darkwizard.pl/?quest=1719](url)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, please check if you have any quests with time limit in your quest log. If you have one already removing it should help. Please let me know it that helped.

**Comment by molgus** [comment]
Hi, thank you for advice, deleted quest marked as failed (with timer) and it's working now 👍
