### ISSUE TITLE
[Druid] Aquatic form [Moonglade - dendrite] Can't take -Trial of the Lake and Aquatic Form- quests

### ISSUE THREAD

**Issue by bobrouketas** [SunwellTracker/issues#1807]
Decription: 
at level 16 i have a quest in mooglade as specific druid quests

How it works: 
dendrite starblaze has the ! above him but when i talk to him he just gives normal text and no quest giving

How it should work: 
should work normally 

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?npc=11802
http://db.darkwizard.pl/?quest=31#.
http://db.darkwizard.pl/?quest=29
![wowscrnshot_090418_150731](https://user-images.githubusercontent.com/42967258/45030384-4cfa1780-b054-11e8-9d4f-b497ed481362.jpg)

**Comment by Dootz** [comment]
Hi,
for Horde Tauren Druid quest you're looking for is 
http://db.darkwizard.pl/?quest=31#
To get this quest you need to complete quests:
1. http://db.darkwizard.pl/?quest=27
2. http://db.darkwizard.pl/?quest=28
3. http://db.darkwizard.pl/?quest=30

Have you completed  http://db.darkwizard.pl/?quest=30 ?
