### ISSUE TITLE
uther's strength 

### ISSUE THREAD

**Issue by KRYSTIANNWO** [SunwellTracker/issues#1808]
Decription: 
Hello, this is about the item Uther's strength does not work

How it works: 
Uther's strength gives shields which should give 14 s apsorbage for each dmg but after each attack the shield disappears

How it should work: 
Uther's strength has a 2% chance of shields that gives absorption for all dmg for a specific time and with each attack there was a chance that the shield will renew again

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
https://www.wowhead.com/item=11302/uthers-strength#comments

After 3 times of testing, I can confirm this absorbs 250 damage when it procs. I'm not sure if this changes with different stats, gear or level, but I was a level 51 Shaman while testing this.

This is during patch 3.1.1.





I remmember when I first saw it I expected proc to be like Divine Shield. Those item descriptions used to be quite fuzzy.
However, I suppose it could just read
Has a 2% chance when struck in combat of protecting you with a holy shield, absorbing 200 damage for 15 seconds.

**Comment by KRYSTIANNWO** [comment]
on the item, he does not write from absorbing only 200 but from absorbing dmg for a certain time I was on other servers and acted as before, i.e. after firing up the damage, even on the server feronis works the same as described, you can check

**Comment by Akha72** [comment]
So give devs a proof that it should work the way you describe it - some wowhead comment / post or a video, anything.

And here is the buff's tooltip:
![uth](https://user-images.githubusercontent.com/25017560/45040151-a1f25980-b065-11e8-8a6b-b895f2b48e85.jpg)

**Comment by KRYSTIANNWO** [comment]
so actually with this itemkiem it works sorki for wasting time you can close the topic
