### ISSUE TITLE
There Exists no Honor among birds. 

### ISSUE THREAD

**Issue by Helligg** [SunwellTracker/issues#181]
Decription: 
Quest There Exists no Honor among birds. Take controll of a small bird. 

How it works: 
The bird cannot fly on the server. Only fallls down to the eggs.

How it should work: 
Should fly

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=0_KdttuKsxE

**Comment by Afgann** [comment]
Will be fixed with next update.
