### ISSUE TITLE
[Quest] Know no Fear

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#1813]
Decription: the quest tells you to walk into teleporter, but it doesn't work

How it works: the quest tells you to walk into teleporter, but it doesn't work

How it should work: the teleporter behind the questgiver should move you to another teleporter in Garm's Rise (51, 82)

Source (you should point out proofs of your report, please give us some source): playthroughts on https://www.wowhead.com/quest=12822/know-no-fear#comments

**Comment by Dootz** [comment]
fixed, live on angrathar.
