### ISSUE TITLE
[Zangarmarsh] [Fen Strider Mob]

### ISSUE THREAD

**Issue by zexwildbacon2** [SunwellTracker/issues#1814]
Decription: fen striders in zangarmarsh drops quest item but I but dont have that quest

How it works: fen striders drop quest item without having the quest

How it should work: fen striders should drop quest item only if you have the quest called Gathering the Reagents

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/CfqKpCg

**Comment by Dootz** [comment]
fixed, live on angrathar.
