### ISSUE TITLE
[Nagrand] [Kill'Sorrow Mobs]

### ISSUE THREAD

**Issue by zexwildbacon2** [SunwellTracker/issues#1817]
Description: Mobs in Nagrand(Kil'Sorrow Fortress) seems like stucked and when trying to attack them it s ays target is not in line of sight so you have to go inside the mom to be able to attack it and if you run away mob doesnt move at all its bad for casters and hunters because they need to go inside the mob to aggro it and need to kill it on melee range.

How it works: Mobs in Nagrand(Kil'Sorrow Fortress) seems like stucked and when trying to attack them it s ays target is not in line of sight so you have to go inside the mom to be able to attack it and if you run away mob doesnt move at all its bad for casters and hunters because they need to go inside the mob to aggro it and need to kill it on melee range.

How it should work: Mobs have to attack you when you get close to them like every other mob does.

Source (you should point out proofs of your report, please give us some source): on last two pictures im showing you the 2 main gates where the bugged mobs are - https://imgur.com/a/Dp96AL0

**Comment by Dootz** [comment]
fixed, live on angrathar.
