### ISSUE TITLE
Item drop chance wrong

### ISSUE THREAD

**Issue by rodier** [SunwellTracker/issues#1819]
Decription: 
Wrong item drop chance. 

This item https://db.darkwizard.pl/?item=6690  should have 60% chance to drop.
Its written in darkwizard and also many other databases,  but it does not have it.

We tried kill this boss on his level (not by level 80 characters, but level 30) more than 15 times and that item dropped only 1 time. 
Instead all other times boss dropped this item  https://db.darkwizard.pl/?item=6691  which should have less drop chance. 

Another case:
https://db.darkwizard.pl/?npc=3974#drops
Again - we killed him at least 15 times, and in 14x he dropped "dog training gloves" which have 60%, only 1 time he dropped that "Dog whistler" which have 30% chance. 

Can you look into  it please.

Thanks

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
chance updated, fix live on angrathar
