### ISSUE TITLE
Ahn'kahet the old kingdon

### ISSUE THREAD

**Issue by Helligg** [SunwellTracker/issues#182]
Decription: 
First two mobs are lvl 79 for some reason. Also a party of lvl 71 should not be put in this instance i think (might be wrong)
How it works: 
lvl 79 mobs in an 73 mob instance

How it should work: 
I assume they should be lvl 73 and not 79. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Will be fixed with next update.
