### ISSUE TITLE
Obsidian Sanctum - Getting Saved when no bosses have been killed

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#1821]
Description:  Obsidian Sanctum has 4 bosses - 3 Drakes and Sartharion. If you kill any of the drakes individually outside of the main fight, or you kill Sartharion, then you will receive both loot (gold and/or items) and emblems.

How it works: Currently, killing ANY Drake during a 3D attempt (meaning non of the drakes have been killed), but wiping on Sartharion still results in the entire raid getting locked. No loot or emblems has been received at this point from any of the named drakes or Sarth. When running back in, all 3 drakes are up and so is Sarth.

How it should work: You should ONLY be saved after directly killing a named Drake outside of the main encounter OR killing Sartharion (and subsequently any drake left up). 

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=wW_ct096Lk0

You'll notice that at no point does it say in the chat box that the player is saved to Obsidian Sanctum prior to Sartharions death.

https://youtu.be/iJJ4hhL9DU0?t=9m10s

In this one, at the linked timestamp, you can see the "You are now saved to this instance" in the bottom right chat box.

**Comment by nimeral** [comment]
Encountered this, can confirm.
