### ISSUE TITLE
[Item][Priest] PVP Gladiator setpieces incorrectly acting unique.

### ISSUE THREAD

**Issue by kafka4president** [SunwellTracker/issues#1822]
Decription: 
Unable to equip two pieces of gear simultaneously for no reason. One is a chest, the other a shoulder slot:
**Hateful Gladiator's Satin Mantle**
http://db.darkwizard.pl/?item=41931
**Hateful Gladiator's Mooncloth Robe**
http://db.darkwizard.pl/?item=41857

Evidence is the red error text displayed mid-screen. Gear is not unique. 
https://imgur.com/a/ECqzRjs

How it works: 
Gear pieces cannot be simultaneously equipped, and provides the unique error effect.

How it should work: 
Gear pieces should be able to be worn simultaneously. 

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?item=41931
http://db.darkwizard.pl/?item=41857
https://imgur.com/a/ECqzRjs
Gear doesn't have the same name, is not unique, disabled all addons and reset cache. Tried on different computer, same result.

**Comment by Azathothh** [comment]
It got nothing to do with Hateful Gladiator gear.
You've put [Kharmaa's Grace](https://db.darkwizard.pl/?item=44066) in both Robe and Mantle, and this gem is unique-equipped (you can only use one in the gear that you're wearing).
