### ISSUE TITLE
Autoattack bug

### ISSUE THREAD

**Issue by Szajba** [SunwellTracker/issues#1824]
Decription: 
Bugi w walce wręcz i używaniu potionów.
Na innej postaci wszystko działa, tylko nie na rogue

How it works: 
Postać w trakcie ataku nie wykorzystuje autoataku, bije tylko skillami. Ponadto nie da się użyć potionów.

How it should work: 
Postać powinna atakować, a potiony powinny się użyć ;)

![bug](https://user-images.githubusercontent.com/43309909/45593619-5fe0e600-b98a-11e8-9a93-94b41003a6e6.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Witaj, napisz proszę Ticket w grze. GM powinien dość szybko odpowiedzieć. Jako sugestię możesz podać sprawdzenie i usunięcie aur z Twojej postaci.
