### ISSUE TITLE
[Warlock] Conflagrate, Can't be cast immediately after Immolate/Shadowflame.

### ISSUE THREAD

**Issue by Merivoid** [SunwellTracker/issues#1826]
Description: 
Conflagrate is an instant cast destruction spell that can only be cast on the target if an Immolate or Shadowflame Damage-over-time effect is present. There is almost always a delay (my guess would be around 1/2 a second) between which immolate finishes and Conflagrate can be cast. Note that this is not a result of the Global Cooldown.

How it works: 
Immolate is cast, and finishes casting around the same time that the global cooldown refreshes (depending on haste). Conflagrate can't be cast as it seems the game doesn't properly immediately register the fact that the immolate/shadowflame debuff is present - at least until a short time later.

How it should work: 
Immolate is cast, and conflagrate should be available to be immediately cast upon immolate finishing, with no delay. The problem here is that in PvP, if Immolate is dispelled then conflagrate can't be cast at all, and since there's a substantial delay, it's much easier than usual for people to dispel, and dodge the damage and slow effect of conflagrate.

Source:
This image below shows that:
https://prnt.sc/kvwc53
1) Immolate has just been cast (debuff is on the addon on the right).
2) Global cooldown has finished, as all the spells are lit up.
3) Conflagrate can't be cast despite all conditions being met.

Steps to reproduce:
1) Find an attackable mob with a decent amount of health so it survives immolate.
2) Cast immolate.
3) Cast conflagrate as soon as you would expect to be able to.
4) Realise you can't until a half-second later.
5) Cry and don't do battlegrounds.

**Comment by Merivoid** [comment]
https://prnt.sc/kvwc53 
Here is the image for proof. For some reason I couldn't link it in the main body.

**Comment by Dootz** [comment]
Probably related to requested "Fake delay" implementation. 
https://github.com/SunwellTracker/issues/issues/1506
https://github.com/SunwellTracker/issues/issues/1505

**Comment by Merivoid** [comment]
> 
> 
> Probably related to requested "Fake delay" implementation.
> #1506
> #1505

What is fake delay? Why does it exist? And can/will it be resolved?

**Comment by Cwiercpasiec** [comment]
This report is invalid, this topic has been talked over a lot of times here, some examples: #633, #1254. In the first link you can read and watch some proofs.
