### ISSUE TITLE
[warrior] quest: the affray from chain quest to get berserker stance 

### ISSUE THREAD

**Issue by simelek95** [SunwellTracker/issues#1829]
Decription: 
I cant get quest: the affray

How it works: 
there is a quest mark at npc  Klannoc Macleod, but i cant get it

How it should work: 
![wow bug](https://user-images.githubusercontent.com/43521025/45930539-d8830c00-bf61-11e8-88ec-4a45f18035f1.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It means that probably you have already quest with a time limit in your quest log.
Please abandon all quests with a timer that you've got and try again.
