### ISSUE TITLE
[Dragonblight - Return to Angrathar] Completing quest did not phase the zone.

### ISSUE THREAD

**Issue by mjhendell** [SunwellTracker/issues#183]
Description: 

After completing the Horde side quest "Return to Angrathar", there's the cinematic for Wrathgate.  Once the cinematic finished nothing in the zone changed.  This made it impossible to continue the quest line as the next part requires the player to talk to Alexstrasza in the new phase post-cinematic area.  Unsure what caused this to happen.  I was mounted if that is relevant at all.

I was able to fix the issue for myself thanks to GM Directions's advice of going to Orgrimmar, which when I arrived was already phased, then going back to the Wrathgate area, which was now phased.  The rest of the quest line worked perfectly and I completed the Battle for Undercity.

How it works: 

I turn in the quest Return to Angrathar and once the cinematic ends I am exactly where I was before and there is no change in the Wrathgate area.

How it should work: 

After the quest is turned in the Wrathgate area is changed and I am next to Alexstrasza who offers a quest "Darkness Stirs."

Source (you should point out proofs of your report, please give us some source):

**Comment by bongobg** [comment]
I did it yesterday and it was all perfect. The whole chain is flawless. Few cosmetic Sylvanna's movement bugs during Battle for Undercity, nothing important.
