### ISSUE TITLE
Glyph of Backstab

### ISSUE THREAD

**Issue by lolilover009** [SunwellTracker/issues#1831]
Decription:  This glyph isn't working as it's supposed to.

How it works:  It procs off of sinister strike as well as backstab.

How it should work:  It should only proc from backstab and not from sinister strike.

Source (you should point out proofs of your report, please give us some source):  Found it out after checking combat rogue armories from high-end guilds. Then, I've tested it on a twink to see what it actually does and it basically extends rupture duration from '16' to '22' seconds.

**Comment by lolilover009** [comment]
This bug is being abused by top guilds. Could you pay more attention to it please?

**Comment by Dootz** [comment]
will be fixed with next server update
