### ISSUE TITLE
[Item]Empty Brew Bottles are missing the GlassBreaking sound effect

### ISSUE THREAD

**Issue by McBlane** [SunwellTracker/issues#1835]
**Description:** 
The Brew of the Month Club drinks produce [Empty Brew Bottle](https://wotlk.evowow.com/?item=38626) which when thrown aren't producing the correct sound effect [BOTM - Empty Bottle Throw - Impact Creature](https://wotlk.evowow.com/?spell=51695) + [GlassBreaking](https://wotlk.evowow.com/?sound=12334)

**How it works:** 
The bottle throwing sound effect can be heard, but no sound is produced when either the bottle strikes a creature or the ground.

**How it should work:** 
Upon striking a creature or the ground, the bottle should produce the GlassBreaking sound effect.

**Source :**

1) It's inherent in the name [BOTM - Empty Bottle Throw - Impact Creature](https://wotlk.evowow.com/?spell=51695) (BOTM = Brew of the Month) which is listed as having the glass breaking sound effect.
2) [this video from a later expansion, but still includes the sound effect at 1:48](https://youtu.be/HYHBMxMPsYE?t=1m48s) 

I know this isn't super important but I love throwing those bottles

thanks guys

**Comment by Dootz** [comment]
should work now.
