### ISSUE TITLE
Warrior Recklessness bug

### ISSUE THREAD

**Issue by Linguster** [SunwellTracker/issues#1840]
Decription: So at current stats Warriors can use Recklessness to be immune to Priest Psychic Scream

How it works: As belove warrior can use Recklessness to be immune for Priest Psychic Scream

How it should work: Warrior shouldn't be immune for fears on Recklessnes, only on Berserk Rage, i didnt test it for others fears cuz i only play rog shadow in arenas and its crucial bug. Becuase after getting berserk rage he still can avoid ccs from priest with using Recklessnes its so dumb

Source (you should point out proofs of your report, please give us some source): I dont have proff couldn't find any video but i played on retail wotlk and it was never like that.

**Comment by zenots** [comment]
Recklessness and Death Wish make you immune to fear, just like Berserker Rage.

**Comment by Linguster** [comment]
Have ever played retail wotlk or any privs, never saw that bug. It is only bugged here like that

**Comment by Anachrony** [comment]
I believe this is exact spell version accompanied with warrior ability, https://www.wowhead.com/spell=13847/recklessness

I dont have retail wotlk experience, but that spell is used on other private servers as well, and it exists since classic version of the game and I cant find any significant changes done to it over the years that imply no fear immunity during wotlk.

**Comment by elasdmehico** [comment]
You believe wrong that's a cataclysm effect according to the link you provided Anachrony

**Comment by Anachrony** [comment]
Yes, but changelog is also there. 
I think this issue can be closed; 

Revision as of 12:35, December 30, 2008.
"The Fear protection is of limited value in itself; it is generally better to rely on the immunity from Berserker Rage and Death Wish instead, as this refreshes much faster."
> http://wowwiki.wikia.com/wiki/Recklessness?diff=1723733&oldid=1722331
