### ISSUE TITLE
Crucial Combat BUG 

### ISSUE THREAD

**Issue by Linguster** [SunwellTracker/issues#1841]
Decription: So at current state combat just appearing from nowhere, sometimes i have comabt for over 20 secs in arena while staying behind pillar doing clearly nothing waiting to get stealth up. Rogue is like worst class for pvp at current combat bug state. I can't sap off full 10 secs blind sometimes, imagine being rogue and player moving with combat for over 20 secs not doing anyhting, and you just wait for sap him but you can't. It happent to me many times in arenas and bgs.

How it works: Well it works like it is exaplined in description, i dont actually know what cause this problem, my friend who play rogue told me that he got same issue and he think that when he drop target, comabt going off faster, but anyway it shouldn't work like that.  

How it should work:  Player should drop combat after like 5 secs without interacting
This bug was on Feronis, and is here from the beging of server. I didnt report it before cuz im not kind of person that reporting bugs and i though gms will fix it if its so crucail to stealth classes. I dont know what is the problem that none of gms or devs can't change it. It makes rogue unplayable on high arena ratings, when you acully need to get restealth and saps.

Source (you should point out proofs of your report, please give us some source):  Play 1 bg with rogue. Try attack someone and without killing him try to go for reastlh or try to go for restealth in team fight with many buffs.

**Comment by nimeral** [comment]
"Source (you should point out proofs of your report, please give us some source)"

They meant a video from 2008-2010 where someone leaves combat after 5 seconds of not attacking/not being attacked.

**Comment by Vatoakavato** [comment]
I can confirm that such a bug exists.
From what i have seen it has to do with healers and hots/shields. If i get a shield from a priest and i try to get a restealth i can't get out of combat unless the priester is out of combat aswell. I tested this in a battleground and it worked with Heal over Time and Power word: SHield from priest. Also if you run behind a pillar/wall and remove the hot/shield you go out of combat after the normal amount of time.
