### ISSUE TITLE
[priest] Borrowed time discipline talent not granting increased absorbed damage

### ISSUE THREAD

**Issue by tekarsis** [SunwellTracker/issues#1843]
Description: At level 74, and possibly beyond, the spell Power Word: shield (ID 48066) rank 12 doesn't benefit from increased damage absorption granted by Borrowed Time talent, which should be an amount of 40% of spell power.
In the link below it is shown that the discipline specialization with Borrowed Time 5/5 and a shadow specialization grant the same absorption power.
Both specs tested have improved power word: shield 3/3, so that does not affect the validity of this report.

How it works: the issue is either descriptive or substantial, meaning there is no difference in declared absorbed damage in shadow or discipline specialization, thus Borrowed Time is probably not working.

How it should work: Borrowed Time should provide a 40% absorbed damage bonus depending on spell power.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/EXDVu02
Absorbed damage amount can be read in the right-bottom screen tooltip.

Thank you for your work

**Comment by Anachrony** [comment]
Hello, was the other spec completely empty? 
Other talents also increase the size of PW:Shield, tooltip is most likely not correct here.

You can check actual absorb amount in your combat log, or with an addon like skada.

**Comment by tekarsis** [comment]
I verified it's like this even on other servers and tooltip description doesn't affect shield absorption power
