### ISSUE TITLE
Trial of the Champion Bug 

### ISSUE THREAD

**Issue by Dramesh24** [SunwellTracker/issues#1844]
Decription: 
After defeating The Black Knight on Heroic difficulty instance Trial of the Champion, there wasn't any loot from last boss

How it works: 
Zero loot from last boss

How it should work: 
There should be loot from last boss

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, I tried to recreate it but it seems fine. Was Black Knight in his final "Ghost" Stage when you killed him and there was no loot? Or he bugged out and died earlier?

**Comment by Fikoblin** [comment]
It happen when last party member dies and kill boss at the same time. Instance goes for the next boss but loot chest doesn't spawn.
