### ISSUE TITLE
No sellers, mailboxes, auctioneers in Stormwind city

### ISSUE THREAD

**Issue by Szarkiz** [SunwellTracker/issues#1845]
Decription: 
I died in the instance and two other persons left the party. I couldnt enter the instance so decided to leave the party and get into the inst solo. I've returned to the body and heartstoned to Stormwind. Here i cant see any auctioneers, nor other player, nor sellers, nor mailboxes. Entering another instance doesnt fix the problem. Still i cant see anyone besides gards. Reloading, reloging, re-running the game doesnt work.

**Comment by Anachrony** [comment]
Try drowning yourself and using the spirit guide, or, write a ticket in game and wait for a help from GMs.

**Comment by Akha72** [comment]
Finish The Battle for the Undercity quest chain.

**Comment by Dootz** [comment]
Hi, as @Akha72 said it's probably related to Battle for Undercity Quest Chain.
You can find all quest from this chain under "Quest progression" here -> http://wowwiki.wikia.com/wiki/Quest:The_Battle_For_The_Undercity_(Alliance) 

If you'll still have this problem please use the in-game ticket. Someone from GM team should be able to help you.
