### ISSUE TITLE
[Warlock] [Spell] Conflagrate

### ISSUE THREAD

**Issue by iesbrutal** [SunwellTracker/issues#1847]
Decription: 
Warlocks spell Conflagrate has delay of close to 0.5 sec or more. After casting Immolate on a target, Conflagrate spell is not becoming active for cast for about 0.5 sec more or less.

How it works: 
Currently it has a delay and is not being activated for 0.5 sec more or less...

How it should work: 
After casting Immolate on a target, Conflagrate should become ready to cast instantly and is not supposed to have delay.

Source (you should point out proofs of your report, please give us some source): 
Can't make video to show it. If you want proof, make warlock and test it yourself.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1826

> 
This report is invalid, this topic has been talked over a lot of times here, some examples: #633, #1254. In the first link you can read and watch some proofs.

**Comment by Dootz** [comment]
> This report is invalid, this topic has been talked over a lot of times here, some examples: #633, #1254. In the first link you can read and watch some proofs.
