### ISSUE TITLE
No achivement after 10 man TOC normal completion.

### ISSUE THREAD

**Issue by rangobob** [SunwellTracker/issues#1848]
Decription: 
Completed TOC normal 10 man mode, killed all bosses. Didn't get achivement.

Completed TOC normal 25 man mode, killed all bosses. Did get achivement.

How it works: 
you kill the bosses and don't get achivement.

How it should work: 
You kill the bosses and do get achivement.

Source (you should point out proofs of your report, please give us some source): 

Wrong: 10 man: https://imgur.com/Q1qBaEX

Correct: 25 man: https://imgur.com/eiz4QKr

**Comment by Dootz** [comment]
Hi, I tested it a few times and it seems to work fine. To better understand what happened in your case, could you take some time to answer the following questions? 
1. Where you present near Anub'arak when he was killed by your group?
2. Did someone in your group have a similar issue?
3. What specialization are you playing in? (Tank, dps, healer)
4. Was it your first attempt at Anub'arak or you had already few wipes.
5. Where you dead/ released your corpse when Anubarak was killed by your group.
