### ISSUE TITLE
[Daily Quests] Daily quests don't give experience

### ISSUE THREAD

**Issue by Revarion** [SunwellTracker/issues#1849]
Decription: Notticed that few days ago and problem persists. Every daily quest won't give me any experience points upon completion, excluding first time ever doing those quests (when they are still yellow "!'s", not blue). I'm level 77 and decided to farm wyrmrest accord reputation from dailies early, but not getting exp while doing that doesn't seem right. Did 5 different daily quests for different factions, no exp from any of them.

How it works: By completing quest I get reputation and gold, but no experience

How it should work: By completing quest I should get experience (~20k), reputation and gold, as stated in every quest description.

Source: 
![s2](https://user-images.githubusercontent.com/43816833/46431015-fe22c900-c74a-11e8-9be3-f8bda714c0cf.png)
![s3](https://user-images.githubusercontent.com/43816833/46431017-fe22c900-c74a-11e8-83a0-b1fc2507f934.png)
![s4](https://user-images.githubusercontent.com/43816833/46431019-febb5f80-c74a-11e8-96a3-3b32d40be2c0.png)

**Comment by Dootz** [comment]
Hi, I was trying to find some evidence to back it up, but the only thing I found is this issue at Trinity Core's bug tracker. https://github.com/TrinityCore/TrinityCore/issues/6818#issuecomment-97499261
As you can read it's working correctly the way it is. I tested it on our server and it works the same.

**Comment by Revarion** [comment]
I first reported bug ingame and gm told me that they should give xp and send me here to report it, it's stated in all quests descriptions that they give xp :/
