### ISSUE TITLE
Fetish of Volatile Power[heroic] trinket bug

### ISSUE THREAD

**Issue by Fatskuyammy** [SunwellTracker/issues#1850]
**Decription:** 

I got the trinket from ToC10hc. The buff doesn't seem to work, but the critical strike rating it gives does work. I made a ticket to a GM but they told me to post here.

**How it works:** 

The trinket give no buff for me, even after casting any spell (I'm a mage). Not on target dummy, not on npc, not on player.

**How it should work:** 

The trinket should give you 64 haste rating after each harmful spell, stacking up to 8 times. 
https://db.darkwizard.pl/?item=48018

Source (you should point out proofs of your report, please give us some source): 
![ezgif-2-1727a6da9d82](https://user-images.githubusercontent.com/43817641/46417060-81cfbc00-c731-11e8-8314-08183faff8d8.gif)

**Comment by Dootz** [comment]
Hi,
it's "On Use" effect. That means you need to "Use" it (Right click, put in cast bar, via macro etc) for it to work. Works fine for me.
![obraz](https://user-images.githubusercontent.com/25490436/46439176-2e289700-c760-11e8-9078-a455b86ac852.png)
