### ISSUE TITLE
Glyph of Explosive trap scale

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#1853]
Decription: The scaling is not working correctly.

How it works: The glyph is working,but the trap is using our spell crit chance,instead of our range crit scale(same as serpent sting t9 2 set).

How it should work: The crit should be based on our average range crit chance.Hunters are not casters,every range ability scales with our range attack power and crit(for example),so our dots abilities should also scales with the range crit(like t9 2 set for serpent sting). 

Source (you should point out proofs of your report, please give us some source): http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?enc=trash  -  51 hits + 102 crits = 75% crit with ICC gear.

**Comment by Dunderj** [comment]
bump, please fix this bug already
