### ISSUE TITLE
[Wintergrasp] Workshops not working perfectly

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#1858]
Decription: Horde has all Workshops on the start and Alliance has 0. Same when Alliance control Fortress.

How it works: Horde has all Workshops on the start and Alliance has 0. Same when Alliance control Fortress.

How it should work: 
1. When Horde control the Fortress they need to have Broken Temple and The Sunken Ring workshops, and Alliance Eastpark and Westpark.
2. When Alliance control the Fortress they need to have Broken Temple and The Sunken Ring workshops, and Horde Eastpark and Westpark.

Source (you should point out proofs of your report, please give us some source): 
https://postimg.cc/8jV19sS6
https://postimg.cc/dhsJQXDQ

**Comment by Akha72** [comment]
Any blizzlike proof for how should it work?

**Comment by alexandru58** [comment]
I think it should be like on Angrathar server.. :)

**Comment by alexandru58** [comment]
https://www.youtube.com/watch?v=QrHjqrEBjpw

Look how Workshops should work.
Sunken Ring and Broken Temple on Alliance Side (if Alliance control it)
Eastpark Workshop and Westpark Workshops on Horde side (if Alliance control it)

Sunken Ring and Broken Temple on Horde Side (when Horde take Wintergrasp)
Eastpark Workshop and Westpark Workshops on Alliance Side (When Horde control the keep).
