### ISSUE TITLE
[NPC - Guvan] Not teaching spells

### ISSUE THREAD

**Issue by thsl97** [SunwellTracker/issues#1862]
Description: 
The npc Guvan(https://db.darkwizard.pl/?npc=17482) won't teach spells past level 6.

How it works: 
The npc only teaches spells up to level 6.

How it should work: 
The npc should teach all available spells past level 6, like all trainers are supposed to (E.g: the paladin trainer Tullas(https://db.darkwizard.pl/?npc=17483) teaches all available spells).

Source (you should point out proofs of your report, please give us some source): 

![wowscrnshot_100918_023742](https://user-images.githubusercontent.com/12467452/46644147-775c5a80-cb55-11e8-9f4e-79cab236970f.jpg)

**Comment by Akha72** [comment]
Any proof that class trainers in starting zones should have full roster of spells?

**Comment by thsl97** [comment]
The Npc Tullas(https://db.darkwizard.pl/?npc=17483), the paladin trainer, is next to the Priest trainer reported and has all spells available for training. I think just this one npc does not have spells past level 6 to train.

**Comment by Akha72** [comment]
Ah, I thought it was 1-5 area mate, my bad.
