### ISSUE TITLE
Several tier 2 arena weapons are missing

### ISSUE THREAD

**Issue by Voldraek** [SunwellTracker/issues#1864]
Decription: 
See title.

How it works: 
See title.

How it should work: 
The following items should also be at the vendor:
Relentless Gladiator's Fleshslicer
Relentless Gladiator's Halberd
Relentless Gladiator's Blade of Celerity
Relentless Gladiator's Salvation
Relentless Gladiator's Swiftblade
Relentless Gladiator's Longblade
Relentless Gladiator's Grasp
Relentless Gladiator's Eviscerator
Relentless Gladiator's Spike
Relentless Gladiator's Handaxe

And may be more than that. Info taken from wowhead but I believe all of the above should be t2 versions. 

Source (you should point out proofs of your report, please give us some source): 
See wowhead for items above, they definitely existed during the relentless season. E.g. https://www.wowhead.com/item=48507/relentless-gladiators-handaxe#comments

**Comment by Dootz** [comment]
fixed, live on Angrathar. Thanks for report.
