### ISSUE TITLE
Wintergrasp honor points reward

### ISSUE THREAD

**Issue by pakon3** [SunwellTracker/issues#1865]
Decription: : Destroying towers in Wintergrasp doesn't award honor points like it's supposed to. 

How it works: read description

How it should work: 
Wintergrasp Defeat now rewards 1250 Honor.
Tower Damaged now grants up to 750 Honor.
Tower Destroyed now grants up to 750 Honor.
Damaged Building Reward now grants up to 750 Honor.
Intact Building Defender now grants up to 1500 Honor. 

It should also award honor for each standing tower after WG ends. - I couldnt google any proof of it :(

Source http://wowwiki.wikia.com/wiki/Wintergrasp
Patch 3.1.2 (2009-05-19): Honor gains in Wintergrasp has been slightly nerfed:
Wintergrasp Victory now rewards 3000 Honor. (Down from 5000 Honor)
Wintergrasp Defeat now rewards 1250 Honor. (Down from 3000 Honor)
Tower Damaged now grants up to 750 Honor. (Down from 1250 Honor)
Tower Destroyed now grants up to 750 Honor. (Down from 1250 Honor)
Damaged Building Reward now grants up to 750 Honor. (Down from 1250 Honor)
Intact Building Defender now grants up to 1500 Honor. (Down from 2500 Honor)

 Proof from retail: https://youtu.be/9QIvXaPR61Y?t=1m23s As you can see in combat log, player gets 75 honor points as soon as ''The western tower has been destroyed text appers'' This is a typo and he gets 750 honor points.
https://youtu.be/eWAdVixPyrc?t=4m0s Same WG it shows he got awarded 300 honor points for WG win when in reality it is 3000 honor points.

https://youtu.be/e4s5HVt26pI?t=4m39s He gets awarded with ''75'' honor points for each tower damage/destruction text. This is actually 750 honor points same typo as at the end of the video only showing 300 honor points gain for winning WG.

Here are the auras which are supposed to trigger for everybody in WG battleground:

Retaining control of a damaged building (probably on defense): http://wotlk.cavernoftime.com/spell=59201
Damaging tower: http://wotlk.cavernoftime.com/spell=59135
Destroying tower: http://wotlk.cavernoftime.com/spell=59136
Retaining control of a damaged building : http://wotlk.cavernoftime.com/spell=59203

**Comment by Dootz** [comment]
Honor for Towers is granted at the end of Battleground
