### ISSUE TITLE
Edge of madness event boss in Zul'Gurub bugged "again"

### ISSUE THREAD

**Issue by Turanius** [SunwellTracker/issues#1867]
Decription: 
i made a report on that bug a couple of months ago, it was fixed but now it's bugged again

How it works: 
every 2 weeks (ID resets) there should be a new boss, there is only Gri'lek, its been like that for 1+ months, i need that one boss and it never came forth for me to slay, and it's frustrating cause this bugged again.

How it should work: 
every 2 weeks there should be a new boss, either reset the script to fix it or idk

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=_BymsuB9VG4

**Comment by Dootz** [comment]
Gm checked it few hours ago and right now Wushoolay is active. Next change will occur on 27.10.2018, but if you'll still get Gri'lek please let me know maybe there's something else broken. I'll keep looking regardless.

**Comment by Turanius** [comment]
i should be able to go today, i'll write a comment here and/or request a chat with a GM, thank you for your time!

**Comment by Dootz** [comment]
I'll close it for now, please let me know if you'll encounter this issue again and I'll reopen it.
