### ISSUE TITLE
Shaman Totems in Azjol Nerub

### ISSUE THREAD

**Issue by Adrestiah** [SunwellTracker/issues#1868]
Description: Shaman totems cause reset of first boss in Azjol Nerub (Normal)

How it works: If a totem is placed during the encounter and the adds target and kill the totem ( easily done, and repeatable) then all the adds  and the boss despawn. They respawn about 10 seconds later and can be killed/ endlessly farmed. 
_The bug is probably a result of the encounter being triggered by something and then that object "dying" causing the game to believe the player/party has died._ 

How it should work:  Obviously the Shaman totems dying shouldn't cause boss despawn ¯\_(ツ)_/¯

**Comment by Dootz** [comment]
fixed, live on Angrathar. Thanks for report.
