### ISSUE TITLE
Ressurected after level-up

### ISSUE THREAD

**Issue by Kapel** [SunwellTracker/issues#187]
Decription: 
If you die in a party and get enough exp to level-up you're beeing ressurected. You can't move or use any skill. You are seen as alive by party members but cannot be hit or killed by any mob. Cannot ressurect at spirit healer. Cannot die falling or in any other way. Cannot use any skill - you get an info "You're dead" or "Cannot use while dead". The only solution is to "teleport" on the website or ask a GM to ressurect. Leaving an instance or entering it does not help.

How it works: 
As in description.

How it should work: 
Die. Even after leveling up get an option to "ressurect" or beeing ressurected. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Resolved
