### ISSUE TITLE
doomguard is broken

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1870]
Decription: ritual of doom doesnt do enough damage

How it works: does low damage

How it should work: should do more

Source (you should point out proofs of your report, please give us some source): how do i proof that doomguard should do more dmg

**Comment by Akha72** [comment]
https://github.com/SunwellTracker/issues/issues/1075

https://github.com/SunwellTracker/issues/issues/1073

**Comment by elasdmehico** [comment]
yeah i saw them but i dont understand that language.. im guessing the damage is being reported

**Comment by Akha72** [comment]
They're both in Polish and English. Look after slashes or in brackets in every paragraph.

**Comment by elasdmehico** [comment]
ty
