### ISSUE TITLE
disenchanting JC items 

### ISSUE THREAD

**Issue by Alenka1234** [SunwellTracker/issues#1873]
Decription: 
When disenchanting JC items: Bloodstone Band (Item ID: 42336)  Sun Rock Ring (item ID: 42337) Crystal Citrine Necklace (item ID: 43244) I only get between 1 and 2 Infinite Dust.

How it works: 
When disenchanting JC items: Bloodstone Band (Item ID: 42336)  Sun Rock Ring (item ID: 42337) Crystal Citrine Necklace (item ID: 43244) I only get between 1 and 2 Infinite Dust.

How it should work: 
As echnatrix and wowhead database says you have 75% to receive 2.5x Infinite Dust -- which means either 2 or 3 dust from 1 item.
https://wotlk.evowow.com/?item=42336#disenchanting
https://wotlk.evowow.com/?item=42337#disenchanting
https://wotlk.evowow.com/?item=43244#disenchanting

Source (you should point out proofs of your report, please give us some source): 
https://wotlk.evowow.com/?item=42336#disenchanting
https://wotlk.evowow.com/?item=42337#disenchanting
https://wotlk.evowow.com/?item=43244#disenchanting

**Comment by Dootz** [comment]
fixed, live on Angrathar. Thanks for report.

**Comment by Alenka1234** [comment]
Still not fixed even after being closed/reopend

**Comment by Trajor** [comment]
This is part of the larger issue reported here https://github.com/SunwellTracker/issues/issues/2074
