### ISSUE TITLE
Colour text

### ISSUE THREAD

**Issue by idogaystuff** [SunwellTracker/issues#1874]
Decription:  /run if (not scm) then scm = SendChatMessage; end; function SendChatMessage(msg, type, lang, chan) scm("\124cffff8000\124Hitem:49623:3789:3525:3525:3525:0:0:0:80\124h["..msg.."]\124h\124r ", type, lang, chan); end;

How it works: i cant talk

How it should work: i should be able to talk with smourne colour in any chat

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
It was blocked intentionally and won't be restored anytime soon.
