### ISSUE TITLE
Conflagrate not working correctly

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1877]
Decription: on retail there was server-wise lag so it was difficult for blizzard to fix it but it's been a bug since forever

How it works: it takes some time before you can conflag after immolate

How it should work: should be able to conflag immediately after immolate

Source (you should point out proofs of your report, please give us some source): https://eu.battle.net/forums/en/wow/topic/2723297471
^This is a thread from early cata i think where they say it's been like this all the time which is true but you guys seem to fix bugs that blizzard didn't get to fix and i wanted to see if you guys could do the same with warlocks conflagrate like when you made /petattack no longer made you get into combat to favour rogues or changing how vanish works to favour rogues aswell
https://github.com/SunwellTracker/issues/issues/1615
^Here's a link where /petattack is being changed so you can get sapped and vanish being rewritten

**Comment by Dootz** [comment]
Hi, it's intentional. You can read more about it here: 
https://github.com/SunwellTracker/issues/issues/1352
https://github.com/SunwellTracker/issues/issues/1847
https://github.com/SunwellTracker/issues/issues/1826

**Comment by elasdmehico** [comment]
Hello. I know it was was bugged on retail because of server lag but I understand that you tend to fix things that were bugged on retail. This is just one of them, only this is a warlock spell and not a rogue spell. Can you reopen? @Dootz

**Comment by elasdmehico** [comment]
so its not being taken into consideration because more players play rogue than warlocks? aww thats a bummer
