### ISSUE TITLE
preparation before bg starts is bugged

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1878]
Decription:  reduces the power cost of spells and abilities by 100%

How it works: it reduces the mana cost of spells by 100%

How it should work: its supposed to reduce soul shards cost and even if it wasn't, do you think you guys could give us this? like in arenas?

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
https://www.wowhead.com/spell=44521/preparation#comments - Wrong
