### ISSUE TITLE
Horde grave on WSG textures bugged

### ISSUE THREAD

**Issue by s00lar** [SunwellTracker/issues#1879]
Decription: Really annoying bug with textures on WSG

How it works: Alliance players that are standing under our grave "hill" (for now I mean Priests and Hunters) are easily healing (or shooting) through textures their players that are fighting at our grave, I mean place under our hill when we're looking straight from our grave at Alliance base. Their grave hill works just fine, only our is broken...

How it should work: Textures are textures they shouldn't shoot or hill through them

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It's not a bug - it's blizzlike behaviour: https://youtu.be/TblqOwqmB0M?t=54
Also "Their grave hill works just fine, only our is broken..." is not true - it's working exactly same way everywhere.
Like Akha72 said - you can hide behind stones or fence.
![obraz](https://user-images.githubusercontent.com/37483678/47045217-93ce4780-d192-11e8-9e1c-78d7fc50094f.png)
