### ISSUE TITLE
[QUEST - Return of the High Chief]

### ISSUE THREAD

**Issue by Corazzin** [SunwellTracker/issues#188]
Decription: Quest in Icemist village, you get given a key by quest giver, to use on crystal to spawn a friendly chief mob who you defend against a boss mob named : Anub'et'kan.

How it works: When you use the key on the crystal, nothing happens or spawns, you can see in the chat window, the boss mob yells, however the chief mob you need to defend  as well as the actual boss mob you need to kill for quest item, dont spawn.

How it should work: Chief mob should spawn after crystal usage, and then boss mob should spawn, and you can kill him for q  item

Source (you should point out proofs of your report, please give us some source): Reported to GM via ticket, then recommended me here.

**Comment by Dootz** [comment]
NPCs (Roanauk & Anub) respawn every 2-3 minutes, and if they are alive event seems to work perfectly. To improve player's experience respawn time of those particular NPCs will be shortened.
