### ISSUE TITLE
Hunter flare is buggy

### ISSUE THREAD

**Issue by s00lar** [SunwellTracker/issues#1880]
Decription: Hunter's flare spell is broken

How it works: When Hunter is using this spell it reveals immediately players in Stealth even before the flare falls on the ground, he's just using it and BOOM.

How it should work: This spell should reveal players in Stealth only after it fall on the ground not before.

Source (you should point out proofs of your report, please give us some source):  Flare https://db.darkwizard.pl/?spell=1543

**Comment by komsomol5460** [comment]
https://www.warcraftmovies.com/movieview.php?id=125181       15:55
