### ISSUE TITLE
Engraved Breastplate. Animation of item

### ISSUE THREAD

**Issue by komsomol5460** [SunwellTracker/issues#1881]
Decription: 
Incorrect animation of item

How it works: 
![wowscrnshot_101618_170741](https://user-images.githubusercontent.com/44202973/47029994-717a0100-d175-11e8-8bc9-bf54e15b0244.jpg)

How it should work: 
https://www.wowhead.com/item=10232/engraved-gauntlets

Source (you should point out proofs of your report, please give us some source):

**Comment by komsomol5460** [comment]
sorry, 
How it should work:
https://www.wowhead.com/item=10230/engraved-breastplate

**Comment by Azathothh** [comment]
Your character is wearing some shirt and i guess that you're thinking it's a part of Engraved Breastplate.
