### ISSUE TITLE
spell pen and hit doesnt work in pvp

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1882]
Decription:  spell pen and hit should extend to warlocks pets meaning that if u get spell pen hard cap then you shouldn't EVER miss or resist spell lock on any players regardless of mage armor/pala aura etc.

How it works: doesnt work

How it should work: pet should get 100% spell pen from master

Source (you should point out proofs of your report, please give us some source): i'll find proof if you will take it into consideration.. i know theres not many players playing warlock but this is an actual bug lol

**Comment by Akha72** [comment]
What is your spn/hit and what class avoided your pet's skills?

**Comment by elasdmehico** [comment]
6% hit and 130 spell pen. Miss and resist on mages with mage armor. With 130 spell pen you should only resist spells cast on felhunters iirc

**Comment by elasdmehico** [comment]
bump

**Comment by akrom23** [comment]
Works okay.
