### ISSUE TITLE
[Trial of the Grand Crusade] Lord Jaraxxus

### ISSUE THREAD

**Issue by maserion** [SunwellTracker/issues#1888]
Decription: according to changelog, rev 1234 - " Touch of Jaraxxus spell added. He will use cast it time to time on random player (not tank)."

How it works:  Tank can get Touch of Jaraxxus spell

How it should work:  Tank won't be target of Touch of Jaraxxus spell

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/j504cCL.jpg - im MT, and I got Touch of Jaraxxus debuff

Other:
Maybe you should improve ecounter by giving him any sound when he cast that debuff, for example his berserk laugh?
Additionaly check Legion Flame, because I got that debuff on earleir fight, but I don't have screen about that (only DBM whisp)

**Comment by Dootz** [comment]
touch of
