### ISSUE TITLE
Jack-o'-Lantern (18 slot TBC bag) Incorrect drop values

### ISSUE THREAD

**Issue by SpectraQWERTY** [SunwellTracker/issues#1889]
Decription:  
Jack-o'-Lantern, a bag that was implemented in TBC and is supposed to drop of TBC level mobs (56 -72) doesnt drop, and it's stated as a 0.05% drop of only a single mob in Northrend(Wrath content) on the sunwell database page.

How it works: 
 Currently it's at a 0.05% drop from only 1 specific mob in Northrend, Magmoth Shaman (Level 69 - 72)

How it should work:
 It was implemented in TBC, Patch 2.2.3, and it dropped from all outland level mobs (56 - 72) with about the same drop rate as the 16 slot pumpkin bag in vanilla (0.5% - 2% drop rate, depending from mob)

Source (you should point out proofs of your report, please give us some source): 
Here are some sources i found :
http://wowwiki.wikia.com/wiki/Jack-o%27-Lantern
http://wowwiki.wikia.com/wiki/Hallow%27s_End
https://classicdb.ch/?item=20400
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/436038-get-free-20-slot-bags-no-charge-your-wallet-no-ah-begging.html
https://www.wowhead.com/item=33117/jack-o-lantern

**Comment by iliqiliev** [comment]
It dropped today from a netherwing npc, here is a screenshot(Hallowen isn't up now) 
![image](https://user-images.githubusercontent.com/25604760/50993017-4eb37a80-1521-11e9-89ed-c35d7872a5d2.png)
