### ISSUE TITLE
On the ruby wings 

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#189]
Decription: 
Grand necrolord antiok 
npc entry ID : 28006

How it works: 
Npc two shots you his shadow bolt damage is too high for none group quest ( players got like 6k hp and he hits for 3.5k )

How it should work: 
he should hit for 900 to 1000
https://youtu.be/QFxNsGNWldc?t=124

Source (you should point out proofs of your report, please give us some source): https://youtu.be/QFxNsGNWldc?t=124

**Comment by Riztazz** [comment]
Resolved
