### ISSUE TITLE
[QUEST] There's something about the Squire

### ISSUE THREAD

**Issue by Masuki90** [SunwellTracker/issues#1890]
Decription: 
Hello. I've trying to drop item "Large Fermur" for next step in quest. I had about 100 kills on Skieletal Woodcutters in Crystalsong Forest and 0% drop.

How it works: 
Mobs Skieletal Woodcutter dont drop quest item

How it should work: 
Skieletal Wood cutter should drop quest item

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_102118_113517](https://user-images.githubusercontent.com/44336132/47265255-72b87e80-d525-11e8-8126-3587bdd31cef.jpg)

**Comment by Azathothh** [comment]
Just checked it and looks like it's 100% droprate if you have that quest.
If it didn't drop for you it means that either you were in a raid group or you already have that item.
Please disable all your addons and check bags again (also bags in bank, maybe you've put it there and forgot about it).

**Comment by Masuki90** [comment]
Hello, 
after disable all addons and "retake" quest item was in first bag. Strange.  Anyway thx for help,
