### ISSUE TITLE
https://db.darkwizard.pl/?quest=5211

### ISSUE THREAD

**Issue by rodier** [SunwellTracker/issues#1891]
How it should work:
Quest "Defenders of Darrowshire". 
In description is to kill cannibal ghouls, gibering ghouls, diseased flayers. 
You find them in Plaguewood and Corins Crossing. 

How it work:
I tried all of these npcs on all places and they are not marked - when I hover over them I dont see they are for quest. When I kill them it does not fill my quest. 

Source (you should point out proofs of your report, please give us some source): 

https://db.darkwizard.pl/?quest=5211

**Comment by rodier** [comment]
Ok now I found one location (21.43 28.55) where kiling cannibal ghouls  works - it release spirit.  But still  no info that npc is for quest.. and in other quest locations same mobs do nothing

**Comment by Azathothh** [comment]
You're not supposed to get credit for this quest by killing cannibal ghouls, gibbering ghouls, diseased flayers but by speaking with Darrowshire spirits which appears after killing cannibal ghouls, gibering ghouls or diseased flayers.
Just checked this quest and haven't seen any problem with it
