### ISSUE TITLE
Headless Horseman mount bug

### ISSUE THREAD

**Issue by Artekd** [SunwellTracker/issues#1894]
Decription: The mount obtainable from Hallow's End event has two critic bugs

How it works: When jumping while on ground riding, the mount slightly sinks in the ground and has a strange jumping animation. Sometimes it jumps like it should but mostly not. When flying, its legs intermittently move way too fast

How it should work: It should behave like a normal horse mount. Its legs should move slowly in the air and it should not sink into the ground

Source (you should point out proofs of your report, please give us some source): I uploaded a couple of videos to show the problem https://www.youtube.com/watch?v=Oqtr3C0zTBg&feature=youtu.be
https://www.youtube.com/watch?v=Z847NchxAwQ&feature=youtu.be
https://www.youtube.com/watch?v=BEIczmDh_0s

Thank you for your attention

**Comment by Artekd** [comment]
Update:
I've made some testing about the excessive leg speed while flying, and i may have found the mechanism of this bug and consequently a simple way to fix it.
In fact, i have noticed that to predict if the mount will fly normally or in a buggy way it is sufficient to look at the first movement it does.

context: flying area (northrend or outlands)
case 1: the mount is summoned; when pressing space (jump) or space+direction, the mount makes an initial long jump, which is its intended way to start flying. When this jump occurs, its leg speed will be buggy, being too fast.
case 2: when pressing space or space+direction, the jump doesn't occur and after legs are being still for an instant (not like the long jump motion), they slowly move as intended.

My suggestion to fix this annoying bug is to remove the jumping motion or alternatively to correct it in some way. It can be speculated that the jumping motion causes the ground mount texture sinking as well.
here i uploaded the testing video
https://youtu.be/bW784UUDM3E

Hope it helps

**Comment by dranavz** [comment]
Is anybody going to fix this issue soon? Whole server is running with this silly mount..

(Also sometimes legs get stuck and don't move in the air)
The mount is pretty bad at following terrain also

**Comment by zexwildbacon2** [comment]
please fix it its so annyoing and gross i lose the joy of having this mount.

**Comment by zexwildbacon2** [comment]
Seems lime nobody from sunwell staff gives a fk about this mount to fix it

**Comment by Dootz** [comment]
part with fast flying animation will be fixed with next update. Part with sinking in ground probably won't be worked on.
