### ISSUE TITLE
Cloth scavenging perk

### ISSUE THREAD

**Issue by Spark2411** [SunwellTracker/issues#1895]
Decription: 
Dropped tailoring for jewelcrafting, still have the tailoring perk

How it works: 

Dropped tailoring for jewelcrafting, still have the tailoring perk
How it should work: 
Not having the tailoring perk.
![wowscrnshot_102618_144751](https://user-images.githubusercontent.com/44500147/47567189-26f34400-d92e-11e8-9b57-3786638aa596.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
If I'm not mistaken it should disappear on next login. Can you still use it?

**Comment by Spark2411** [comment]
Not in this case. I've dropped tailoring last night and relogged atleast 5 times on multiple occasions today, and i still have it.
