### ISSUE TITLE
Sending pet/ghoul doesn't trigget combat

### ISSUE THREAD

**Issue by Artekd** [SunwellTracker/issues#1897]
Decription: Expliciting the reasons why this behaviour should really be reverted to blizzlike status, as it appears from previous Devs answers' that Sunwell WoW has voluntarily decided to change the original blizzlike mechanic, thus buffing rogues and nerfing all classes provided with a pet, especially in arena settings. I politely ask Sunwell's developing team to kindly consider my positions, which are shared by other players as well.

How it works: Sending pet/ghoul doesn't instantly trigger combat as it always have been either in WOTLK retail and in all private servers.

How it should work: Sending controlled creatures to attack the opponent should instantly put the master in a status of combat, preventing being sapped by rogues.

Source (you should point out proofs of your report, please give us some source): 

History: Even if maybe this mechanic wasn't originally intended to work like this, it was mantained for a very long time in retail wow, which means that after all it has never been considered an issue. 
Ranking: No other pvp server have ever changed this blizzlike behaviour, and still 2v2 rogue-based teams have had no problem reaching the highest arena rankings. Indeed, in a today 3.3.5 end-game famous pvp server (originated from previous AT/molten), the 10 top arena positions are populated by 3 rogue teams, and just 1 pet class, which shows there hasn't been any disadvantage being done to rogues by this blizzlike mechanic. Actually, rogues are overrepresented in all arena brackets. This is why the ""fix"" Sunwell WoW is mantaining  is giving rogues an unfair advantage. Also in retail wotlk the class balancing have been done considering rogue's strenghts and weaknesses, thus taking in account even this never changed/always mantained blizzlike mechanic, so changing it would remove a weakness creating a situation of class unbalancing.

For example some classes can remove/prevent sap like warrior's or druid's enrage, others cancel snares and stuns like mages et cetera. It's very likely that preventing sap for pet classes has been seen as a balancing mechanic, especially for 2v2 arena pvp, as it is the ability to command pet while the master is stunned/cced. Conversely, it is extremely unlikely that this blizzlike mechanic has been mantained for **years** due to an oversight.
https://eu.battle.net/forums/en/wow/topic/17616522235
https://eu.battle.net/forums/en/wow/topic/17615081446
https://eu.battle.net/forums/en/wow/topic/17616973657

I see the point of creating a better version of wow, and i totally appreciate it, but pvp-wise, in my opinion, is better to keep things like they were. There is space for "never implemented fixes", and i think that should mainly involve quality of life improvements and pve. Pvp, though, is a much more sensitive setting, where even a simple mechanic change can create imbalances hard to correct at a later time. Reverting this setting asap would be the safest way to mantain class balancing.

I thank you for your work, attention and availability to consider player's feedbacks

**Comment by Lupe4js** [comment]
Same thing with Treants as moonkin :
Send treants on target, they hit target, i'm not in combat

**Comment by Aridam** [comment]
https://forum.gamer-district.org/topic/27924-stuff-that-looks-like-its-bugged-but-its-not/
https://truewow.org/bugs/view.php?id=1861
http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/
https://github.com/TrinityCore/TrinityCore/issues/2601

https://github.com/TrinityCore/TrinityCore/pull/19816
https://github.com/TrinityCore/TrinityCore/pull/12084#issuecomment-44102205

**Comment by Tellmeitsover** [comment]
@Wojtyas @Riztazz still bugged
