### ISSUE TITLE
[Quest] What Is Going On?

### ISSUE THREAD

**Issue by kbatko** [SunwellTracker/issues#190]
Decription: 
Jest to druga część chaina questowego który rozpoczynamy questem Commander Gor'shak [http://classicdb.ch/?quest=3981](url)

How it works: 
Gor'shak mówi nam że przeciwnicy nadejdą, ale po nich ani widu ani słychy :((( . Nie zalicza questa bo te moby najzwyczajniej się nie pojawiają/nie przychodzą. Wybicie wszystkich mobów w pobliżu też go nie zalicza.

How it should work: 
Moby z tej części instancji powinny falami przychodzić do celi Gor'shaka żeby spróbować go zabić/przechwycić. Po zabiciu wszystkich przychodzących fal quest powinien się zakończyć.

Source (you should point out proofs of your report, please give us some source): 
Link go questa: [http://classicdb.ch/?quest=3982](url)

**Comment by Riztazz** [comment]
Resolved
