### ISSUE TITLE
[Icecrown] [Quest - That's Abominable!] 

### ISSUE THREAD

**Issue by zexwildbacon2** [SunwellTracker/issues#1901]
Decription: Thassarian on the Skybreaker wants you to use the Abomination Reanimation Kit to create a Reanimated Abomination, which you are to use to kill 15 Icy Ghouls, 15 Vicious Geists, and 15 Risen Alliance Soldiers. 

P.S: This quest leads to 2 new quests please fix it.

How it works: Quest is bugged and can't be obtained from Thassarian

How it should work: Before taking the qeust there are pre-quests - ...All the Help We Can Get. , Poke and Prod and after you compleate these 2 you should be able to get That's Abominable! quest.

Source (you should point out proofs of your report, please give us some source): just done the quest i didn't know i ts bugged so didn't take pictures but i spoke with GM he told me i should be able to get that quest from Thassarian but im not and he said to report it here please somebody check it.

**Comment by Dootz** [comment]
Hi,
thank you for report, it ll be fixed with next server restart.

**Comment by zexwildbacon2** [comment]
And yet quest is still bugged at least dont say its fixed when its not

**Comment by Dootz** [comment]
hmm.. weird. I'll check again then. Thanks.

**Comment by zexwildbacon2** [comment]
done all the quests from thassarian and have only daily quest and this quest i was never able to get sadly its pre-quest of a chain that has nice item.
