### ISSUE TITLE
Hearthstone

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#1904]
Decription: Otóż, po wyrzuceniu kamienia będąc shamanem niemożliwością jest otrzymanie kolejnego u innkepeera poprzez 'bindowanie' nowego lub tego samego miejsca. Myślę, iż ma to związek ze spellem 'Astral Recall', który działa identycznie jak hs, z tym że ma krótszy cd oraz skalowanie z haste =)

How it works:
nie daje kamyka

How it should work: 
https://www.youtube.com/watch?v=kyoOPy4_GPs

**Comment by Dootz** [comment]
Sprawdź być może masz hearthstone w banku. Jeśli jesteś pewny że nie daj znać jaką wiadomość błędu otrzymujesz gdy próbujesz pobrać kamień.

Poradnik:
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by Szelmon556** [comment]
W istocie, osiol ze mnie :D Wybacz stracony czas na takie głupotki d;

https://www.youtube.com/watch?v=V8XTpCwicwE
