### ISSUE TITLE
Power word: shield is bugged and currently working like divine shield while capping bases

### ISSUE THREAD

**Issue by elasdmehico** [SunwellTracker/issues#1907]
Decription: When having shield up and capping a base in arathi basin or any other bg, you won't get interrupted because the damage is absorbed. Doing any dmage to anybody capping bases should interrupt it regardless of absorb.

How it works: It works like divine shield atm

How it should work: Should interrupt capping any base in any battleground regardless of damage taken.

Source (you should point out proofs of your report, please give us some source): like hello

**Comment by Azathothh** [comment]
"How it should work: Should interrupt capping any base in any battleground regardless of damage taken."
That's exactly how it's working:
https://www.youtube.com/watch?v=MA5Xv1u4stk
