### ISSUE TITLE
BUG Quest after "Speak with Ruga"

### ISSUE THREAD

**Issue by Vardel** [SunwellTracker/issues#1908]
Decription: I have a problem with my character "Voyti". I completed the quest "Speak with ruga" and next Ruga Ragetotem can not give a new quest

How it works: Ruga Ragetotem say to me: "Greetings, Voyti."

How it should work: Ruga Garetotem should give me next quest.

Source (you should point out proofs of your report, please give us some source): 
![45030004_538610753232092_9171767957548695552_n](https://user-images.githubusercontent.com/44613924/47729661-e0208980-dc60-11e8-9754-b07b08f1a731.jpg)
![45005918_698654980508091_7885729469225238528_n](https://user-images.githubusercontent.com/44613924/47729663-e0b92000-dc60-11e8-81c1-2496ccbe8823.jpg)

**Comment by Azathothh** [comment]
Next quest http://wowwiki.wikia.com/wiki/Quest:Trial_at_the_Field_of_Giants  have a timer.
You can't have 2 quests with a timer at same time, so if you can't take this quest it means that you already have one with a timer in your questlog (it doesn't matter if timer is still running/quest is failed/completed).
If you won't find a quest with timer in your quest log try deleting all quests, and speak with Ruga again.
If quest still won't be there open in-game ticket.
