### ISSUE TITLE
Quest - A Righteous Sermon

### ISSUE THREAD

**Issue by brakez** [SunwellTracker/issues#191]
Decription: 
The Dragonblight quest "A Righteous Sermon" does not complete after listening to the sermon.

How it works: 
Inquisitor Hallard goes through his RP event with Mayor Godfrey, then nothing happens

How it should work: 
The quest auto-completes at the end of the RP

Source (you should point out proofs of your report, please give us some source):

**Comment by brakez** [comment]
Correction to the above issue:

This only happens if you do the quest as a part of two or more players. The player who accepts the quest will get credit, but all other players in the party will not.

**Comment by Afgann** [comment]
Will be fixed with next update.
