### ISSUE TITLE
JC icy prism bug

### ISSUE THREAD

**Issue by Shasilim** [SunwellTracker/issues#1911]
Decription: 
it tells me that I am missing reagents when I craft icy prism even if I have them in my bag as you can see from the screenshot
[BUG.docx](https://github.com/SunwellTracker/issues/files/2531628/BUG.docx)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1392
https://github.com/SunwellTracker/issues/issues/1209
https://github.com/SunwellTracker/issues/issues/952
https://github.com/SunwellTracker/issues/issues/784
https://github.com/SunwellTracker/issues/issues/472
https://github.com/SunwellTracker/issues/issues/451
https://github.com/SunwellTracker/issues/issues/212
https://github.com/SunwellTracker/issues/issues/204
https://github.com/SunwellTracker/issues/issues/140

**Comment by Shasilim** [comment]
Yeah but I have all the gems, yet it does not work, I get you changed them from 3 to 1. But even if I have the gems I can't craft

**Comment by Azathothh** [comment]
"I get you changed them from 3 to 1" It's changed from 1 to 3, not from 3 to 1.
On the screenshot that you've posted you had only 2xDark Jade, so no, you don't have all gems

You need : 
3xDark Jade, 3xChalcedony, 3xShadow Crystal, 1xFrozen Orb
It's explained with more details in previous reports (links are posted above) so if you need more explanations please check them.
