### ISSUE TITLE
Leaving Arena before the match starts [PvP]

### ISSUE THREAD

**Issue by Testerqtxd** [SunwellTracker/issues#1918]
Description: At the moment, when the enemy team leaves the arena match before the gates open, or the other team can actually get to the enemy team the arena match ends, the team that left loses the same amount of rating as they would if they lost the match, but the team that is left inside the match does not win any rating. This is not blizzlike and it should be changed to the team that stays in the match wins rating as if it were a normal win.

How it works: The opposing team leaves the arena at the start, the arena match ends and the frame displays the team that did not leave the arena and "won" the match, but the team does not win any rating.

How it should work: The team that does not leave and wins the match should win rating.

Source (you should point out proofs of your report, please give us some source): 
![proof1](https://user-images.githubusercontent.com/38841336/47924885-2114da00-debd-11e8-8c04-2d1e08f727b1.png)

**Comment by elasdmehico** [comment]
I noticed this happen a few days ago when a team tried to dodge us. They would just leave before gates started and not lose rating or get a loss in their arena team. Confirming is all.

**Comment by MrTide** [comment]
Hello as far as i know its just visual they still lose points 
Need confirmation

**Comment by Testerqtxd** [comment]
You didn't get what I meant, the team that left loses rating, the team that is shown on the screenshot is the team that stayed in and should've won rating. Not win 0 rating.

**Comment by akrom23** [comment]
Nope.
If enemy team leaves arena on prep time, their members lose rating.
Your team should not get any credit for this match.
