### ISSUE TITLE
Molten Core loot from Majordomo

### ISSUE THREAD

**Issue by vixisenpai** [SunwellTracker/issues#1924]
Decription: After defeating Majordomo the chest with loot doesen't apear

How it works: chest doesen't apear

How it should work: chest should apear after defeating Majordomo and give loot to players

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Hello
Can confirm

**Comment by Dootz** [comment]
will be fixed with next server update
