### ISSUE TITLE
Handknucke Charger's charge doesn't stun

### ISSUE THREAD

**Issue by Viasilvas1** [SunwellTracker/issues#1926]
Decription: 
When Handkuckle Charger charges, the charge doesn't stun players

How it works: 
When it charges, the players aren't stunned and they can still cast spells even when slammed into the ground

How it should work: 
The charge should give at least a 2 to 5 seconds stun

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/44933786/48307349-ca557300-e542-11e8-8f9b-9d877f27a94d.png)

![image](https://user-images.githubusercontent.com/44933786/48307355-f2dd6d00-e542-11e8-9ddc-f4110d4c6927.png)

**Comment by Dootz** [comment]
https://www.wowhead.com/npc=28096/hardknuckle-charger#comments:id=610237
"While their charge includes a knockdown animation, you will notice that it does not interrupt your spellcasting nor does it prevent you from performing more attacks while you're "on the ground." So this attack is little more than a quick movement to close in the distance to you with a mild damage component to it."
