### ISSUE TITLE
[QUEST - Wanted: Ragemane's Flipper]

### ISSUE THREAD

**Issue by Corazzin** [SunwellTracker/issues#193]
Decription: Ragemane's spawn time is absolutely cancer.

How it works: Mob hasnt respawned for about 15minutes

How it should work: Mob should respawn sooner, so more people can complete quest instead of bottle necking people to one quest.

Source (you should point out proofs of your report, please give us some source): Spoke to GM, recommended me to make a ticket here

**Comment by Afgann** [comment]
Will be fixed with next update (reduced to 5 min).
