### ISSUE TITLE
[paladin] righteous vengeance

### ISSUE THREAD

**Issue by Tigerbonzoo** [SunwellTracker/issues#1936]
"Decription:
Righteouse Vengeance is a Retribution Paladin talent that does 30% of Crusader Strike / Divine Storm / Judgement critical strike damage as additional damage over time ( 8 sec ) ticks every 2 sec

How it works:
It does the 30% damage over time however it gains no benefit from bonuses that affect all damage

How it should work:
It should benefit from talents like Crusade talent 3-6% / 3% damage aura / Vengeance stacks 9% / avenging wrath 20% so upon a critical strike from J/CS/DS the damage calculation would be base 30% of crit damage * damage multiplayers + undelivered damage from existing RV ( if any )

Source (you should point out proofs of your report, please give us some source):
Bug is related to an ability not gaining benefits mechanics that affects all damage so i doubt source is needed however if needed i could look up some video."

**Comment by wonszopaionk** [comment]
You get that increase in the ability dmg. If you increased RV dmg further more, it would get double the benefit from those talents. Let's say CS cits for 1000 without talents - it would be 300 additional damage over 8 seconds. If you have talents/auras/meta let's say it hits for 1000*1,03*1,03*1,09*1,2 =~1387 crit which should make RV do ~416 dmg over 8 seconds. If you increased that dmg again you would get additional ~0,38*416= 158 dmg (sums up to 574) and that situation doubles the benefit from increased %dmg.
