### ISSUE TITLE
[Paladin] Seal of command

### ISSUE THREAD

**Issue by Tigerbonzoo** [SunwellTracker/issues#1939]
Decription: 
The seal of command spell does not work properly.

How it works: 
The seal of command's area of effect is based on the position of the player's target.

How it should work: 
The "area of effect" of seal of command should work within range of the caster (the player) so it should hit targets even behind the paladin.
 
Proof: 
this retail video https://www.youtube.com/watch?v=KTzEOa1tt4c 

Source (you should point out proofs of your report, please give us some source):

**Comment by akrom23** [comment]
https://wow.gamepedia.com/index.php?title=Area_of_Effect

> Cleave effects (epicenter: target; angle: 70°)
Heart Strike, Seals of Command, Blade Flurry, Cleave, Sweeping Strikes
