### ISSUE TITLE
Object - Dalaran Forge

### ISSUE THREAD

**Issue by Trsko** [SunwellTracker/issues#194]
Decription: 
Forge in dalaran blacksmith on the wall and next door in the forge / anvil area

How it works: 
It does not work, there is no "forge" tooltip when mouse over and you can not smelt.

How it should work: 
They should be recognized as forges.

Source (you should point out proofs of your report, please give us some source):  experience, also got this from google http://i.imgur.com/4N8Bi9R.jpg

**Comment by RandomDudoo** [comment]
@Trsko sorry for offtopic. But what glorious UI is that?

**Comment by Trsko** [comment]
Have no idea, thats legion retail on a demon hunter, i have respect for myself and would never play that.
But it looks like modified ELVUI
https://github.com/ElvUI/ElvUI/archive/master.zip

**Comment by knasen88** [comment]
++++++++++ need
