### ISSUE TITLE
[Warrior][Prot] - Tier 9 set bonus - mark to close

### ISSUE THREAD

**Issue by AnonymousWarrior** [SunwellTracker/issues#1940]
Decription: 
Set bonus for 4/5 parts of warrior [t9](https://db.darkwizard.pl/?itemset=-225) (Decreases the cool-down on your Shield Block ability by 10 sec.)
 not working. Tested on 245ilvl items.

How it works: 
With talents: 
[Shield Mastery rank 1](https://db.darkwizard.pl/?spell=29598) and [Shield Mastery rank 2](https://db.darkwizard.pl/?spell=29599).
[Shield Block](https://db.darkwizard.pl/?spell=2565) cd should be 30 sec and this is ok but with 4/5 parts of warrior t9 this should be reduced by additional 10 sec but it still is 30.

How it should work: 
I think with 4/5 parts of [t9](https://db.darkwizard.pl/?itemset=-225) armor [Shield Block](https://db.darkwizard.pl/?spell=2565)  ability should have 20sec cd because bonus say reduction by 10 sec. With talents this is 30 sec - 10 sec from set should be 20.
Am I right?

Source (you should point out proofs of your report, please give us some source): 
[Item - Warrior T9 Tank 4P Bonus (Shield Block)Instant](https://db.darkwizard.pl/?spell=67273)

Additional:

[Items](https://db.darkwizard.pl/?itemset=-225)

[Shield Block](https://db.darkwizard.pl/?spell=2565)

**Comment by kinglobster** [comment]
shield mastery from prot talents reduces the 1min block cd by 20sec, to 40s, t9 drops it to 30.

**Comment by erghar** [comment]
Holy cow this is true, my bad. Then this topic should be closed.
Sorry for misunderstanding.

**Comment by AnonymousWarrior** [comment]
Holy cow! Fact. Then this topic should be closed.
My bad.

Sorry for waste of your time.
