### ISSUE TITLE
Can´t send heirloom on character, which returned from Black market.

### ISSUE THREAD

**Issue by Burgeras** [SunwellTracker/issues#1944]
Decription:  I putted my character on Black market, after few days I taken it back and wanted to send heirloom on this character. But it is not possible.

How it works: When i trying to send heirloom on this character on same account, I get message:
Artifacts can only be mailed to your own characters. And canť send it. 
BTW: I have to put this character to friend list to send him other stuff, so system thinks, that character which returned from Black market is at another account (or somethink like that).

How it should work: 
When i send heirloom on character which is at the same account, heirloom could be sent.
It works at another characters, but not at char, which returned from Black market.

Source (you should point out proofs of your report, please give us some source): 
It is goal of heirloom, that can be sent through all characters on account.

**Comment by SunwellTracker** [comment]
fixed
