### ISSUE TITLE
Elwynn Lamb non-combat pet summoning Elwynn Forest Wolves in arena

### ISSUE THREAD

**Issue by snaplemouton** [SunwellTracker/issues#1946]
Description: The non-combat pet Elwynn Lamb can be used in arenas and will summon attackable Elwynn Forest Wolves in the arena. Those wolves can then be used for multiple things such as generating rage or staying in combat longer.

How it works: Elwynn Lamb is summoned, a random Elwynn Forest Wolf spawn after a short while.

How it should work: I do not know the correct behavior of interactive non-combat pet in arenas, but I can only assume that Elwynn Forest Wolves shouldn't appear in arena.

Source (you should point out proofs of your report, please give us some source): Cannot find any source of people using Elwynn Forest Wolf in arena, it would make sense that such a mechanic would have been mentioned on forums or boards considering how it can easily be abused.

**Comment by kinglobster** [comment]
they also spawn in dalaran sewers if owner has the pet out
