### ISSUE TITLE
Bleeding Hollow Tormentor's fear is a buff and can be right clcked

### ISSUE THREAD

**Issue by iliqiliev** [SunwellTracker/issues#1949]
Decription: 
Bleeding Hollow Tormentor's fear is a buff and can be right clcked and removed.
Source:
![wowscrnshot_112118_113937](https://user-images.githubusercontent.com/25604760/48833708-a7b62c00-ed84-11e8-96d3-ebd377e203aa.jpg)

**Comment by sicknot1** [comment]
![wowscrnshot_011919_123143](https://user-images.githubusercontent.com/35937937/51428776-7a4ff800-1be6-11e9-9d56-e60b38cfac8b.jpg)

Still broken
