### ISSUE TITLE
[QUEST] Willix The Importer

### ISSUE THREAD

**Issue by kikuhawki** [SunwellTracker/issues#195]
Decription: Escort quest in razorfen kraul

How it works: He flies to a random location after the escort is done, only 1 player can return it at the entrance

How it should work: He shouldnt fly out of there like that..

Source (you should point out proofs of your report, please give us some source):  https://i.imgur.com/TaeSJmm.jpg

**Comment by Dootz** [comment]
I wasn't able to recreate it. It might be more general bug, because it occurs with other escorts aswell.https://github.com/SunwellTracker/issues/issues/356

**Comment by Dootz** [comment]
most likely that happend because someone started this quest when he was at the end. Will be fixed.

**Comment by Dootz** [comment]
will be fixed with next server update
