### ISSUE TITLE
Gem requirements

### ISSUE THREAD

**Issue by Xaximbo** [SunwellTracker/issues#1954]
Decription: You can equip gems not suitable for the slot but you don't get the bonus of the piece for equiping all gem slots

How it works: you can equip wrong gems.

How it should work: : it should appear a warn of unappropiate gem and you shouldn't be able to insert the wrong gem.

Source (you should point out proofs of your report, please give us some source):  experience from retail server.

**Comment by Azathothh** [comment]
That's not how it's working. You should be able to put for example: red gem into blue socket (it would just give you no socket bonus)
