### ISSUE TITLE
EXP Bug 

### ISSUE THREAD

**Issue by travandus02** [SunwellTracker/issues#1959]
Decription: after buying a exp boost out of dungeons in the world I don’t receive any exp for killing mobs ? Please help ! Thank you. 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
I'm sorry but i don't understand what you're trying to say - please open ticket in-game and we will try to find out what's the problem and help you.
