### ISSUE TITLE
[Quest] Threat from Above

### ISSUE THREAD

**Issue by Ashkondrius** [SunwellTracker/issues#1961]
**Description:** 

The "Threat from Above" quest in Outland, which asks to kill 20 Gordunni Ogres gives 2 kills per ogre slain.

E.g:  1 ogre dead > 2 kills
        2 ogres dead > 4 kills

Link quest: https://www.wowhead.com/quest=11096/threat-from-above
Screenshot:
![capture](https://user-images.githubusercontent.com/45501395/49320906-fabe7a80-f50c-11e8-9783-4a502ae22d83.PNG)

**Comment by iliqiliev** [comment]
same for me
