### ISSUE TITLE
[Quest] The Caverns of Time

### ISSUE THREAD

**Issue by iliqiliev** [SunwellTracker/issues#1964]
Decription: Custodian of Time didn't say anything the whole run, she was just walking.
Source: 
![wowscrnshot_120118_162215](https://user-images.githubusercontent.com/25604760/49329323-8378fd00-f585-11e8-809d-6d4155cad32c.jpg)

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/49330146-0badd100-f58b-11e8-9a64-60341d3caac2.png)
Looks fine for me - please check your chat settings
![obraz](https://user-images.githubusercontent.com/37483678/49330156-2bdd9000-f58b-11e8-803a-68d5956e7056.png)
Probably your "creature whisper" is off
