### ISSUE TITLE
Pack of bugs.enjoy

### ISSUE THREAD

**Issue by DudeRick** [SunwellTracker/issues#1965]
Decription: 
1.SotA(bg),walls bug
2.Male orc with Female voice
3.IoC(bg)turret bug
How it works: 
1.After breaking wall (tested at hunter) I couldn't shoot while staying in place where wall was,also pet often stops attack beacuse of smthing like invisible wall at middle of beach.
2.Caverns of Time,there is vendor-male orc with female voice.kinda weird.
3.sometimes after repairing turret and then entering it ,you cant exit,happens without repairing too.

How it should work: 
1.You should shoot normally at those spots and pet shouldnt stop attacking by invisible wall.
2.Male orc=Male voice.
3.After entering turret(repaired or not)you should be able to leave it any time.

Source (you should point out proofs of your report, please give us some source):

**Comment by iliqiliev** [comment]
2 isn't a bug; if you speak with him/her he/she will tell you, you should wowhead these

**Comment by Akha72** [comment]
1 was already reported, enjoy.

**Comment by DudeRick** [comment]
Well 2 is actually in other realms too,nvm then
