### ISSUE TITLE
Parachute and possibly other fall speed reduction effects

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#1966]
Decription: 
Parachute cloak reduces your falling speed preventing any fall damage.

How it works: 
It is possible to die to fall damage even with the parachute cloak (and possibly other fall speed reducing effects) on.

How it should work: 
It should be impossible to die to fall damage with any fall speed reducing effect.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/FCL0La7.png

Here you can clearly see me gaining the parachute buff, falling and dying and losing the buff after death. I was falling slowly for a good 5-10 seconds.

**Comment by Wojtyas** [comment]
We can only see that you lost parachute buff before your death. It may be caused that you lost ur parachute just before landing.
