### ISSUE TITLE
[Warlock Quest] The Binding killsteal

### ISSUE THREAD

**Issue by theormore** [SunwellTracker/issues#1969]
Decription: 
Someone stole my kill on warlock summoning quest The Binding.

How it works: 
I started summoning a voidwalker and a guy showed up to do the same, he literally started 0.5-1.5s after me. Voidwalker showed for me and I naturally attacked him - the guy finished casting and nothing happened so he started to attack my voidwalker. Idk if the mob turned "grey" for me but i am sure he got last hit and most probably completed quest. I didnt complete it, I had to wait 3 minutes to do the quest again. 

How it should work: 
I summoned the voidwalker so I should have got that kill.

**Comment by Akha72** [comment]
Any proof be summoned already tapped?
