### ISSUE TITLE
[Achivement] Flirt With Disaster (Horde)

### ISSUE THREAD

**Issue by Gjende** [SunwellTracker/issues#197]
Decription: 
Get completely smashed, put on your best perfume, throw a handful of rose petals on Jeremiah Payson
and then kiss him. 

How it works: 
After doing all the following steps: getting smashed, putting on perfume, throwing the petals and then giving him a kiss. Nothing seems to be registered in the achievement tracker.
Even after following all the steps by looking at youtube or getting another player to try it out.

How it should work: 
Should work by simply following the achievement description.

Source (you should point out proofs of your report, please give us some source):

**Comment by dreamingdust** [comment]
Currently Flirt With Disaster (Alliance) is broken as well. Nothing is registered when attempting to follow what the achievement says.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
