### ISSUE TITLE
Ghost Dying at Graveyard Then Cant Move at All (game-breaking)

### ISSUE THREAD

**Issue by Lacheezy** [SunwellTracker/issues#1978]
Decription: 
When I die and release my ghost cannot leave the are of the graveyard or it dies.  I then cannot move at all.  Relogging does not fix.

How it works: 
When I die and release my ghost cannot leave the are of the graveyard or it dies.  I then cannot move at all.  Relogging does not fix.

How it should work: 
You should be able to run back to your body.

Source (you should point out proofs of your report, please give us some source): 

![image](https://user-images.githubusercontent.com/45579130/49410129-51e46b00-f718-11e8-9969-271fa0ee615b.png)

**Comment by Lacheezy** [comment]
Tried disabling all addons and reinstalling a different client but bug still persists.

**Comment by Dootz** [comment]
Hi, please use in-game ticket system to contact our  GMs. They will help you. We try to have always someone available in-game so it shouldn't take long
