### ISSUE TITLE
Njormeld in Dun Niffelem

### ISSUE THREAD

**Issue by Doomwalkerr** [SunwellTracker/issues#198]
Decription: 
Njormeld, one of the most important npcs in Sons of Hodir quest chain is gone, he is not at his place and you can't really find him, he is just not there

How it works: 

How it should work: 
I have 2 quests to complete to him, please fix it 🗡 
![wowscrnshot_020318_212539](https://user-images.githubusercontent.com/35903205/35771209-f4a385ee-0928-11e8-8bf4-e51c0bfa8f60.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Arthi93** [comment]
Works for me. You should compare Your questes with some guide, cause the is a moment, when you have to speak with Thorim at the top of the temple, and unless you complete quest he gives you, you wont be able to enther the phase, where njormeld is.

**Comment by Doomwalkerr** [comment]
I wasn't online for 12h so it might have been fixed and I do not have to talk with Thorin anymore, it was an obvious bug, even 3 GMs were there to investigate the problem but they couldn't fix it
