### ISSUE TITLE
Warrior Protection Mobs Keep chasing me forever

### ISSUE THREAD

**Issue by killtox** [SunwellTracker/issues#1982]
DecriptI am warrior protection, and if I attack 1 mob he will chasing me forever...he got no limit like it should have.....for example..If I attack 1 mob in Borean Tundra and I want to get away from him....he will follow me until Dragonblight.

How it works: 
Mobs keep chasing me forever

How it should work: 
Mobs should have a limit and go back to their place.

Source (you should point out proofs of your report, please give us some source): 
![1](https://user-images.githubusercontent.com/25190290/49439943-0fc83180-f7cb-11e8-8489-a4c32748f7f5.jpg)
![2](https://user-images.githubusercontent.com/25190290/49439957-16ef3f80-f7cb-11e8-86c5-d1d6adbe1914.jpg)
![4](https://user-images.githubusercontent.com/25190290/49439965-1ce52080-f7cb-11e8-8337-2baef7b052eb.jpg)
![5](https://user-images.githubusercontent.com/25190290/49439975-21113e00-f7cb-11e8-951c-512843c35fe9.jpg)

**Comment by Helliox** [comment]
It's because u keep hitting him with Damage Shield (https://db.darkwizard.pl/?spell=58874), which results in refreshing aggro. It's not a bug.
