### ISSUE TITLE
Shamanistic focus

### ISSUE THREAD

**Issue by Hecama12** [SunwellTracker/issues#1983]
Decription: 
The talent Shamanistic focus is being consumed by other abilities than earth/flame/frost shock

How it works: 
When I get a melee crit, I get shamanistic focus but if I use any spell it gets removed even my searing totem attack removes it.

How it should work: 
The proc of Shamanistic focus should only be consumed when using a shock ability

Source (you should point out proofs of your report, please give us some source):

**Comment by FallenAngel80** [comment]
Healing wave also uses this proc up.
