### ISSUE TITLE
Trading enchants

### ISSUE THREAD

**Issue by Spudez** [SunwellTracker/issues#1984]
Decription: 

When trading an enchant the materials required will be used even if the trade is not succesful

How it works: 

When trading an enchant the materials required will be used even if the trade is not succesful

How it should work: 

When both parties of the trade accept the trade it then should finalize the enchant and consume the materials

Source (you should point out proofs of your report, please give us some source): 

Trading+Enchanting many times

**Comment by akrom23** [comment]
Works okay.
