### ISSUE TITLE
High Inquisitor Whitemane Bug

### ISSUE THREAD

**Issue by Daubeny** [SunwellTracker/issues#1988]
Decription: 
High Inquisitor Whitemane won't die

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
ok this is in sm cath 1 or 2 days ago
i think its self explanatory
https://www.youtube.com/watch?v=QKPgTkdG8bc

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
