### ISSUE TITLE
Creatures are sometimes twice in the same place

### ISSUE THREAD

**Issue by Doomwalkerr** [SunwellTracker/issues#199]
Decription: 
Look at the screenshot, it's kinda odd
![wowscrnshot_020318_174205](https://user-images.githubusercontent.com/35903205/35771244-abe94392-0929-11e8-8629-7ee638ca06d9.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
