### ISSUE TITLE
Maraudon - The Scepter of Celebras dosent give scepter

### ISSUE THREAD

**Issue by Daubeny** [SunwellTracker/issues#1990]
Decription: 
we accepted the quest and when we read from the book or whatever the script doesnt go thru i guess and he didnt create the scepter or anything, he was stuck like that
![maradun scepter](https://user-images.githubusercontent.com/45588955/49558586-d9de9680-f90b-11e8-8f92-21abeaa97e15.jpg)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
