### ISSUE TITLE
[Jewelcrafting] Thorium Setting

### ISSUE THREAD

**Issue by ZhengSim** [SunwellTracker/issues#1992]
Decription: Design - Thorium Setting [21752] uses more material than it's supposed to.

How it works: Crafting Thorium Setting [21752] requires 3 Thorium Bar [12359] despite it showing only 1 (even after closing the game and deleting the cache). Having less than 3 reults in the error message "This item isn't ready yet".

How it should work: Crafting Thorium Setting [21752] should require only 1 Thorium Bar [12359].

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
