### ISSUE TITLE
Death coil breaks early from damage

### ISSUE THREAD

**Issue by wombo2u** [SunwellTracker/issues#1994]
Decription: 
Death coil spell breaks early from damage

How it works: 
Breaks before full duration

How it should work: 
Should always last full 3 sec

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
Proof?

**Comment by wombo2u** [comment]
This is on Nightbane mind you, and it is Horrify effect = Doesen't break

**Comment by foxxhound** [comment]
Death Coil shouldn't break early unless dispelled. Nor should it break from damage.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
