### ISSUE TITLE
Runed Copper Belt can't be disenchanted

### ISSUE THREAD

**Issue by Fatosefa** [SunwellTracker/issues#1995]
Decription: 
Runed Copper Belt can't be disenchanted. Tooltip said that it request 65535 skill in enchanting. 

How it works: 
if i click disenchant on this belt i get red message "Skill not high enough"

How it should work: 
normal disenchanted

Source (you should point out proofs of your report, please give us some source): 
tested on my mage Urukhai

**Comment by Fatosefa** [comment]
ahh and the belts was made by blacksmith named Anihilator if i good remember

**Comment by Fatosefa** [comment]
Anihilation

**Comment by maciejkock** [comment]
Same as Runed Copper Gauntlets  Made By Grubby

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
