### ISSUE TITLE
Cannot stealth even out of combat

### ISSUE THREAD

**Issue by ItsFilko** [SunwellTracker/issues#1996]
Decription: I do not know how to replicate the bug, but it happened today when fighting in PvP in STV, I used Vanish to open on a priest with a Cheap Shot, but my stealth broke immediately after vanish, maybe due to a DOT or some other damage, but after leaving combat I was completely unable to stealth again and could only restealth after waiting for vanish to cooldown and using it, then cancelled & then stealth was available again.

This has happened to me already once before.

How it works: Cannot stealth even out of combat in some occassions

How it should work: Stealth should be available upon leaving combat

Source (you should point out proofs of your report, please give us some source): https://youtu.be/s8YxRmoCdSw

**Comment by ItsFilko** [comment]
4 additional sauces: https://images-na.ssl-images-amazon.com/images/I/8143BTFiw8L._SL1488_.jpg

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
