### ISSUE TITLE
[Quest] Fresh Remounts

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#20]
Decription:  Nie mozna ukonczyc questu ze wzgledu na bug konia.

How it works: 
Po zabiciu jeźdźca i zlootowaniu lancy używając jej na koniu zmienia go tylko na friendly po czym znika.

How it should work: 
Po zabiuciu jeźdzca powinniśmy użyć lancy na koniu i wyjechać koniem z obszaru wroga do miasta. Tak 3 razy.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Duplicate.
