### ISSUE TITLE
[Boss] Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Sasssyunicorn** [SunwellTracker/issues#200]
Decription: She is supposed to start phase 2 and summon 1 add from crowd that walks towards her, if not killed she enrages. If killed she just lands and p1 starts again.

How it works: Adds won't come. She won't land.

How it should work: Go to description

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Will be fixed with next update.
