### ISSUE TITLE
Arcanite Bar Cooldown

### ISSUE THREAD

**Issue by Warlockdaddy** [SunwellTracker/issues#2005]
Decription: Arcane Bar Cooldown period was removed in 2.4.0.

How it works: Currently, it has a 24 hour cooldown when using transmute arcanite bar.

How it should work: Since we are playing on 2.4.3, the cooldown for transmute arcanite was removed in 2.4. Therefore, it should have no cooldown whatsoever.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Transmute:_Arcanite

**Comment by Delfury** [comment]
2nd Source: http://wowwiki.wikia.com/wiki/Patch_2.4.0 Confirms this.  
Please remove the cool-down.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
