### ISSUE TITLE
Elemental Mastery not giving 100% Crit

### ISSUE THREAD

**Issue by Bysse893** [SunwellTracker/issues#2008]
Decription: 
The talent Elemental mastery in the shaman Elemental tree does not give the promised 100% Crit chance of the spell every time.

How it works: 
I use the spell, then cast either Lightningbolt or Chain Lightning but do not always get 100% crit on the ability. It can be either the lightningbolt not criting or the chain lightning only criting the firts target and not the additional jumps.

How it should work: 
It should always make the abiltity crti 100% of the time, and all the jumps of the chain lightning should crit.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_120818_031028](https://user-images.githubusercontent.com/45702856/49680626-ef33fc00-fa96-11e8-8f31-a62aeb21e6a4.jpg)

**Comment by CHAIn220** [comment]
if you cast a lightning bolt and then use elemental mastery, elemental mastery will be consumed and the mid air lightning bolt will not crit. its also consumed by searing totem shots

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
