### ISSUE TITLE
[Quest] Dreadwood Ritual Totem doesn't work.

### ISSUE THREAD

**Issue by Warlockdaddy** [SunwellTracker/issues#2009]
Decription: Quest in Felwood by the name of Dreadwood Ritual Totem. It is a drop from the fulborg shamans in the area.

How it works: You bring the item to Kernda, but right clicking on Kernda does nothing. No window pops up at all.

How it should work: You click on Kernda and turn the quest in.

Source (you should point out proofs of your report, please give us some source):

**Comment by AlgalonEnd** [comment]
If you relog and take at war off, should be able to turn it in.
