### ISSUE TITLE
Any ground based lootable quest items in Northrend

### ISSUE THREAD

**Issue by theadrix33** [SunwellTracker/issues#201]
Decription: Every ground based lootable quest item (ex. Imprints on the Past quest in Dragonblight) that i've encountered in Northrend have had 5-15 minute respawn timers. Making questing with a friend extremely aggravating. 

How it works: named quest mobs, individual ground based quest items and multi-lootable ground based quest items are taking 5-15min to respawn.

How it should work: They should be closer be closer to 30second - 1min respawn (especially for named quest mob respawns, or individual quest item respawns

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
I will tweak our dynamic spawns for higher content a little bit with next update

**Comment by Bel-WOW** [comment]
Further examples, great for testing: 
- "Need an Engine, take an Engine" ID: 12522 in Sholazar Basin, respawn time of an engine (object on ground) is very long. Around 5min I guess (at the time I didn't count).
- "Post-partum Aggression" ID: 12614 in Sholazar Basin, respawn time of Broodmother Slivina is very long.

**Comment by Riztazz** [comment]
Gameobjects without valueable loot should have decreased spawn now
