### ISSUE TITLE
Herbs/veins in outland

### ISSUE THREAD

**Issue by dadolencebre** [SunwellTracker/issues#2010]
Decription: Herbs/veins in Outland

How it works: There is literally no to very few outland herbs and mostly felweed, respawn rates are very very low aswell, on the other hand there are far too much mining veins and the respawn rates are too high you basically almost cannot catch up because they respawn so fast.

How it should work: There should be a reasonable amount of herbs around over outland aswell as reasonable respawn rates, and same goes for mining veins.

Source (you should point out proofs of your report, please give us some source):

**Comment by Heftyarms** [comment]
I agree with this as well, it took me awhile to lvl herbalism. But in outlands I've made circles in multiple zones and there is literally 0 spawns. I went sometimes over 1 hour without getting a single node. This is actually really bad. Where as there are mines everywhere. Fix spawns, more nodes, faster respawns for Herbs.
