### ISSUE TITLE
Increased damage from crocodils in loch modan

### ISSUE THREAD

**Issue by lak14wto** [SunwellTracker/issues#2014]
Decription: crocodils located on the isle of loch modan has chance on hit of multiple attacks on hit. Often, they proc 3 hits at a time. 

How it works: increased damage with a mechanism like windfury, with 3 hits at a time and a High % chance of proccing

How it should work: this damage is significantly increased from other crocodils and from the same crocodils compared to retail

Source (you should point out proofs of your report, please give us some source): this can be verified from batteling a few crocodils on isle of loch modan

**Comment by foxxhound** [comment]
To 2nd this. This isn't just in Loch Modan, this happens with various mobs, such as gnolls in Elwynn as well. This is also present on multiple 2.4.3 servers.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
