### ISSUE TITLE
Fear not breaking from damage in pvp combat

### ISSUE THREAD

**Issue by lak14wto** [SunwellTracker/issues#2015]
Decription: fear foes not have chance to break from damage in pvp combat

How it works: then damage is applied on a feared target, fear had same duration as when damage is not applied

How it should work: fear should have chance on damage to break

Source (you should point out proofs of your report, please give us some source): pvp combat on nightbane server

**Comment by Akha72** [comment]
Works fine for me.

**Comment by foxxhound** [comment]
If I remember correctly, there was a damage cap that was added to the spell Fear, for when a player / mob was feared and had "Apply Aura #7: Mod Fear" applied in WOTLK. In TBC it has a chance to break upon being damaged from any outside source of dmg as opposed to a capped threshold.
