### ISSUE TITLE
[Searing Gorge] Mob Placement

### ISSUE THREAD

**Issue by revenant001** [SunwellTracker/issues#202]
Decription: 
Some mob spawns are in a place they definitely shouldn't be

How it works: 
The example I screen-shotted shows a golem walking in the middle of a lava lake inside a cave (but I know I've seen at least one other weird spawn point for a mob that I didn't screen shot)

How it should work: 
Most likely spawn would be the same spot but above the cave
![wowscrnshot_020218_202825](https://user-images.githubusercontent.com/36019407/35771837-46a7d306-08f0-11e8-970b-a6492b8c785b.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed.
