### ISSUE TITLE
Item Old Blanchy's Feed Pouch [NIGHTBANE]

### ISSUE THREAD

**Issue by foxxhound** [SunwellTracker/issues#2021]
Decription: Old Blanchy's Feed Pouch (item ID: 1537) Displays as an 8 slot bag, yet acts like a 4 slot bag.
[NIGHTBANE SERVER]

How it works:  Acts as a 4 slot bag.

How it should work: Should be an 8 slot bag.

Source (you should point out proofs of your report, please give us some source): 

![image](https://user-images.githubusercontent.com/45742349/49705487-734bc800-fbec-11e8-9724-21043f874bd8.png)

**Comment by Azathothh** [comment]
Patch 2.4.0 (25-Mar-2008): Increased the slots on Old Blanchy's Feed Pouch from 4 to 8
Please clear your cache and/or disable all addons - it should display "4 slot bag"
Also please report Nightbane related bugs on TBC bugtracker here : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
This one is Wotlk bugtracker ;)
