### ISSUE TITLE
[Alterac Mountains] Signpost placement

### ISSUE THREAD

**Issue by revenant001** [SunwellTracker/issues#203]
Decription: 
In Alterac Mountains, at the fork in the road that splits between the ruins of alterac and strahnbrad, the signpost there has a floating sign that reads "Andorhal" (screenshot attached)

How it works: 
Floating sign away from the post

How it should work: 
The sign should be attached to the post
![wowscrnshot_020318_143707](https://user-images.githubusercontent.com/36019407/35771892-39fd650c-08f1-11e8-8073-7631387de246.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
