### ISSUE TITLE
[NPC] Missing NPC in Stormwind Keep

### ISSUE THREAD

**Issue by Domo0696** [SunwellTracker/issues#2037]
Decription: 
NPC(Lady Katrana Prestor) is missing.

How it works: 
She is not in Stormwing Keep.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
Removed in 3.0.2

**Comment by Domo0696** [comment]
Isnt this the tbc bugtracker?
