### ISSUE TITLE
[Jewelcrafting] Icy Prism consumes 3 Frozen Orbs instead of 1

### ISSUE THREAD

**Issue by Trolltilla** [SunwellTracker/issues#204]
Decription: 

Icy Prism consumes 3 Frozen Orbs instead of 1

How it works: 

You need 3 Frozen Orbs 3 Chalcedony's 3 Shadow Crystals and 3 Dark Jades

How it should work: 

It should require 1 Frozen Orb 3 Chalcedony's 3 Shadow Crystals and 3 Dark Jades

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Icy_Prism

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/140
