### ISSUE TITLE
Drop rate of greens in outlands off mobs

### ISSUE THREAD

**Issue by Lacheezy** [SunwellTracker/issues#2040]
Decription: Outland mobs seem to not be dropping greens as often as they should be...especially in instances.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
