### ISSUE TITLE
Goldthorn floating in the air in Badlands

### ISSUE THREAD

**Issue by TechnoMulen** [SunwellTracker/issues#2041]
Decription:  Goldthorn floating in the air in Badlands

How it works: 
Goldthorns cant fly

How it should work: 
Should be on the ground

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/a/Pqt3LeL

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
