### ISSUE TITLE
stonevault cave hunter´s range attack does not damage

### ISSUE THREAD

**Issue by TechnoMulen** [SunwellTracker/issues#2044]
Decription: 
stonevault cave hunter outside uldaman -  range attack does not damage

How it works:  they just do ranged attack but with no damage. 

How it should work: 
ranged attack should do damage

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
