### ISSUE TITLE
[Quest] A Necessary Distraction

### ISSUE THREAD

**Issue by nuppster** [SunwellTracker/issues#2045]
Decription: 
You should kill Sunfury Warlocks and Summoners to get the "Scroll of Demonic Unbanishing" so you can free Azaloth

How it works: 
The Droprate of the Scroll of Demonic Unbanishing seems to be under 3% on Summoners and Warlocks (I spent over an hour killing 40-50 each of these)

How it should work: 
The drop rate should be some where between (according to wowhead) 20% for warlocks and 6% from summoners and up to 35% for both (according to various wow tbc databases)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
