### ISSUE TITLE
Mage Spell Casting Noise not Playing

### ISSUE THREAD

**Issue by wayneprim90** [SunwellTracker/issues#2046]
Decription:  

I am playing my mage and the spell casting noise of firebolt and frostbolt isn't playing. The sound plays when I successfully let a firebolt go but not during casting.

How it should work: 

I believe it should play a sound when you are casting firebolt and frost bolt.

**Comment by Azathothh** [comment]
Please check your sound settings - maybe you've disabled it somehow - works fine for me.
