### ISSUE TITLE
[Warlock] [Ability] Deathcoil breaks

### ISSUE THREAD

**Issue by hoborg87** [SunwellTracker/issues#2047]
Description:
Deathcoil breaks

How it works:
It is currently working as a 'fear' effect - % chance to break on damage, rarely lasting 50% of full duration

How it should work:
As a "horror' effect - unbreakable for the full 3 seconds

Source (you should point out proofs of your report, please give us some source):
Casting deathcoil with dots and a pet on target will break it every single time

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
