### ISSUE TITLE
Autoshoot with wands stops while organizing bag

### ISSUE THREAD

**Issue by plsfixthese** [SunwellTracker/issues#2049]
Decription: 

Autoshoot with wands stops while organizing bag
How it works: 

When you organize (drag and drop to other slots) your bag the autoshoot for wands stops
How it should work: 

Organizing bag should not affect autoshoot with wands. 
Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Can't reproduce.
