### ISSUE TITLE
[Quest] Wandering Shay

### ISSUE THREAD

**Issue by DarthPimpalot** [SunwellTracker/issues#205]
Decription: 
This Feralas quest requires you to loot [Shay's Bell] from a lootbox next to Shay Leafrunner (quest-giver), and to proceed to escort her to Rockbiter's camp (coordinates 42.5, 22) within a time limit.

How it works: 
While the item given works properly, the npc does not stray occasionally (rendering the bell useless) and the quest fails to detect the npc's arrival at the specified location. Additionally, if the quest is failed through the time limit the npc fails to despawn, procceding to follow the player until her death, even if the quest is abandoned. 

How it should work: 
The npc should wander off from time to time. The quest should also be marked completed when the npc is in range of the camp. Finally, the npc should despawn when the quest is abandoned, failed, or completed.

Source (you should point out proofs of your report, please give us some source): Attended by GM Tide. http://www.wowhead.com/quest=2845/wandering-shay for quest info/coordinates verification.

**Comment by Riztazz** [comment]
Resolved
