### ISSUE TITLE
[Stranglethorn Vale] Tasty Fish Schools for the Fishing Extravaganza

### ISSUE THREAD

**Issue by Oreodog** [SunwellTracker/issues#2051]
Description: Tasty Fish schools from the Stranglethorn Fishing Extravaganza spawned at the wrong time.

How it works: I don't know at what time the schools spawned, but I see that you can find several tasty fish schools at least 15 minutes before the tournament is actually supposed to start (14 ST)

How it should work: Tasty fish schools should spawn immediately upon the hour, and despawn after 2 hours (16 ST). The NPC's themselves should be available to talk to only when the tournament starts, and 3 hours after (17 ST).

Source (you should point out proofs of your report, please give us some source): https://wow.gamepedia.com/Stranglethorn_Fishing_Extravaganza

**Comment by Akha72** [comment]
The event works fine but since the time change it is rescheduled to last from 1pm till 3pm. So it starts an hour before it should and ends after 2hs.

**Comment by Oreodog** [comment]
Alright, thanks for the heads up
