### ISSUE TITLE
Jewelcrafting. Thorium setting

### ISSUE THREAD

**Issue by Peeters1978** [SunwellTracker/issues#2052]
Decription: Thorium Setting uses more material than it's supposed to.

How it works: Crafting Thorium Setting requires 3 Thorium Bar despite it showing only 1 

How it should work: Crafting Thorium Setting should require only 1 Thorium Bar

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues

**Comment by Nirazy** [comment]
Same! Ruins my profession now(((
![wowscrnshot_121918_005044](https://user-images.githubusercontent.com/45981772/50190353-f9c57f80-0339-11e9-8bc3-294a4e59a40b.jpg)
