### ISSUE TITLE
Hearthstone to Orgrimmar.

### ISSUE THREAD

**Issue by rafanito** [SunwellTracker/issues#2053]
Decription: 
I used the stone to orgrimmar. When he arrived in Orgrimmar, he gave an error. Whenever I try to log in my character who used the stone to orgrimmar the error keeps, the mistake is happening to a friend too.
My character nickname is "Natokaknik".

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
