### ISSUE TITLE
Quest: Bring me the egg! Can't remove slowfall debuff.

### ISSUE THREAD

**Issue by Bysse893** [SunwellTracker/issues#2055]
Decription: 
In The Nagrand quest Bring me the egg! you are supposed to land in the treetop and grab the egg to make the matriarch spawn, and then get the rewards for slaying it. The problem is that you cant remove the 3 min slowfall buff that you get, thus you cant land in the nest by any means.

How it works: 
Cant right-click away the slowfall buff.

How it should work: 
You should be able to just remove the buff to land your jump inside of the nest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Already reported here https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/1589

This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
