### ISSUE TITLE
Paralytic Poison Debuff

### ISSUE THREAD

**Issue by Hornflakes** [SunwellTracker/issues#206]
Decription: Daggerfen Muckdwellers at Daggerfen Village in Zangarmarsh apply a debuff called "Paralytic Poison" that should stun after 30 seconds of being on the target.

How it works: It does not stun after 30 seconds.

How it should work: It should stun after 30 seconds.

**Comment by knasen88** [comment]
there is a similar one in duskwood, the green spiders at raven hill, the poison should stun after X seconds, or rather it applies one poison first and if it's uncleansed it paralyzes you for 5 secs. 

now it just instastuns at application

**Comment by Afgann** [comment]
@Knasen88 make a new report please

**Comment by Afgann** [comment]
Will be fixed with next update.
