### ISSUE TITLE
Glyph of Disease

### ISSUE THREAD

**Issue by SamVerburg** [SunwellTracker/issues#2068]
Decription: 
Glyph of Disease is supposed to **refresh** the duration of the diseases instead of **reapplying** it.
![image](https://user-images.githubusercontent.com/7700592/50201948-7f5a2700-035c-11e9-86ec-3fcd160a7b98.png)

How it works: 
After using Pestillence to **refresh** the duration on your diseases. The DoT damage resets to match your current attack power.

How it should work: 
Diseases frost fever and blood plague work like a warlock's corruption.
It snapshots the stats you have when applying them.
This means it should keep the attack power value from first application.

Source (you should point out proofs of your report, please give us some source): 
https://www.twitch.tv/videos/351165931

https://runeforgegossip.wordpress.com/2009/10/18/rolling-diseases-how-to-effectively-spread-the-plague/

**Comment by kimaara22** [comment]
"After using Pestillence to refresh the duration on your diseases. The DoT damage resets to match your current attack power." 

Thats exactly how it should work and it shouldnt roll ap values, it was changed through expansion.
https://www.wowhead.com/forums&topic=134129
