### ISSUE TITLE
[QUEST - Tormenting the Softknuckles]

### ISSUE THREAD

**Issue by Corazzin** [SunwellTracker/issues#207]
Decription: The Mob 'Softknuckle' is merged into the surrounding tree, and isn't in line of sight to use the quest item on.

How it works: Monkey patrols inside a un-line of sightable piece of tree, and therefore you cant use quest item on him.

How it should work: Monkey should patrol in the open area around the tree, so quest item can be used on him without saying ' not in line of sight'

Source (you should point out proofs of your report, please give us some source): https://i.imgur.com/bdcRO2k.jpg

**Comment by Corazzin** [comment]
Still remains not in line of sight, still pathing through the tree

**Comment by Afgann** [comment]
Works locally, well, you can figure it out by yourself.

**Comment by Corazzin** [comment]
https://i.imgur.com/HCN4xbb.jpg 

Not working for either me or others on same quest :)

**Comment by Afgann** [comment]
Works locally means that issue is resolved, but it will be implemented on next update because it only works LOCALLY on my LOCAL server.

**Comment by Corazzin** [comment]
Could've explained that instead of the sarcastic comment to 'figure it out myself'

**Comment by Afgann** [comment]
I think that label says everything.

**Comment by Afgann** [comment]
Will be fixed with next update.
