### ISSUE TITLE
Hunter Pet not gaining experience(Exp bar is missing)

### ISSUE THREAD

**Issue by AshiyrHunter** [SunwellTracker/issues#2073]
Description: I've tested this thoroughly, every pet I tame at level 70 - regardless of their level. They don't have an experience bar. I've tried gaining loyalty levels hoping that would make it show up. I've tried stabling the pet, swapping with other pets. It doesn't matter what I do - the exp bar does not show up.

How it works: Freshly tamed hunter pets are not gaining experience.

How it should work: Hunters tame a pet and proceed to kill mobs within 10 levels of themselves or their pet and the pet gains experience per kill.

Source as follows in a screenshot: https://gyazo.com/e6ba08b6e2f5af74024bf5a48ef4bf7e This is a pet without an experience bar.
https://gyazo.com/e519e136ddf382356a442dd1951eea63
This is the pet that I trained at level 16, it still has an experience bar - he is level 69.

I have tamed multiple pets from level 1-70 to make sure it wasn't this specific beast.

Also to verify, I have grinded on the pet without the exp bar for 2 hours on mobs that would normally level it to make sure it wasn't a visual glitch. It is not gaining experience.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
