### ISSUE TITLE
[Instance] Vault of Archavon - Toravon the Ice watcher

### ISSUE THREAD

**Issue by Sorrow5** [SunwellTracker/issues#2079]
Decription: Frozen orbs can target totems, which makes them no threat for the players if they just move away from the totems.

How it works: Frozen orbs can target totems

How it should work: Frozen orbs should target only players

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Possible fix went live, please let me know if that happens again

**Comment by Sorrow5** [comment]
I did voa today and it still can happen, frozen orbs sometimes target totems and just stay there
