### ISSUE TITLE
[Professions] Titanium Ore isn't prospectable

### ISSUE THREAD

**Issue by mondegoftw** [SunwellTracker/issues#208]
Decription: Titanium Ore isn't prospectable

How it works: Trying to prospect Titanium Ore gives the error message "There are no gems in this."

How it should work: Titanium Ore should be prospectable, and should give both gems and Titanium Powder. 

Source (you should point out proofs of your report, please give us some source): The Jewelcrafting vendor in Dalaran lets you buy Jewelcrafting Tokens with Titanium Powder, so yeah, it's clearly intended to be in the game.

Also: Wrath-Logo-Small Patch 3.2.0 (04-Aug-2009): Titanium Ore can be prospected. Prospecting titanium yields Titanium Powder. Source: http://wowwiki.wikia.com/wiki/Prospecting

**Comment by Trsko** [comment]
This is patch 3.0, there is no epic gems before Argent tournament, and titanium wasnt prospectable until that patch. which is hopefull and probably what they intended.

**Comment by Afgann** [comment]
Exactly that @Trsko.
