### ISSUE TITLE
Glyph of Vigor

### ISSUE THREAD

**Issue by Toymachinex** [SunwellTracker/issues#2080]
Decription: 

Glyph of vigor dont grant me 10 energy
How it works: 

not works 
How it should work: 
Should give me 10 energy
Source (you should point out proofs of your report, please give us some source):

**Comment by Toymachinex** [comment]
Give me 10 energy im not fat :(((

**Comment by Sorrow5** [comment]
u sure u have vigor talent

**Comment by Toymachinex** [comment]
yea i can screenshot

**Comment by wonszopaionk** [comment]
So show us the screenshot with glyph of vigor, vigor talent and 110 energy.
