### ISSUE TITLE
[Druid TBC] Crit chance is not equal to max weapon skill in bear/cat form

### ISSUE THREAD

**Issue by tojothethief** [SunwellTracker/issues#2081]
Decription: 
** Sorry, I didn't know this is the Wrath-only tracker. I found that this issue has been already reported on the BC tracker: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2039 **

Currently your crit chance in bear/cat form is the same as your crit chance with your current equipped weapon.

How it works: 
Your crit chance is affected by your current weapon's skill level.

How it should work: 
Your crit chance is supposed to be equal to maxed weapon skill (base 5%). Hit chance seems to function at the intended way, however.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/forums&topic=7214
From 2008/01/04
"You have a separate weapon skill for cat form and bear form called Feral Combat Skill. FCS is nowhere on your character sheet, but it is automatically maxed for your level. So no, you never have to level weapon skill for your cat form. It has 0 effect on your DPS, or your crit chance, or anything else, in cat form or bear form. Caster form, of course, you are subject to the weapon skill rules just like everybody else."

**Comment by SunwellTracker** [comment]
It's not TBC BT.
