### ISSUE TITLE
Aggro issue in party

### ISSUE THREAD

**Issue by MrEvilToilet** [SunwellTracker/issues#2083]
Decription: 
When im in a party with a friend and he runs and pulls mobs (he is protection paladin) i get aggro even tho im not even close. i dont have any buffs or anything that really should take aggro from the tank when he got the same buffs even more buffs since he is the tank.

How it works: 
i can sit and drink water, eat food or not really doing anything i get aggro from mobs he runs and pulls

How it should work: 
i shouldnt get aggro from mobs when i dont do anything

Source (you should point out proofs of your report, please give us some source):

**Comment by wonszopaionk** [comment]
Buffing and healing also do threat aganist mobs, can you give us some evidence it is not working properly?

**Comment by MrEvilToilet** [comment]
not really any proof (i dont have anything that can capture video or
anything like that), i could stand a far bit from my friend and he ran to
the mobs and i got the aggro without doing anything (no healing or any
buffing). it might be the vengeance buff that retri have through talents
but i cant see anything else since he plays paladin aswell and had all
other buffs that i had exept for that one.

Den fre 11 jan. 2019 kl 08:09 skrev wonszopaionk <notifications@github.com>:
