### ISSUE TITLE
Quest: Thrusting Hodir's Spear

### ISSUE THREAD

**Issue by Zdzblotrawy** [SunwellTracker/issues#2085]
Decription: 
You are to use Hodir's Spear to challenge Wild Wyrm in the Valley of Ancient Winters. Once in its grip, you are to fight to the death.

How it works: 
Use quest item on Wild Wyrm, then you jump on him using new pop up skills to defeat him, when he is less than 20k hp then the second phase should start but your character drop's from Wild Wyrm before it happens.

How it should work: 
Use quest item on Wild Wyrm, then you jump on him using new pop up skills to defeat him, when he is less than 20k hp then the second phase should start and you execute him.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_122218_212856](https://user-images.githubusercontent.com/46075239/50378446-b8cbb480-0632-11e9-9b8b-a5646bc74c80.jpg)
![wowscrnshot_122218_212907](https://user-images.githubusercontent.com/46075239/50378454-e0228180-0632-11e9-90c5-1e25c937af03.jpg)
![wowscrnshot_122218_213000](https://user-images.githubusercontent.com/46075239/50378456-e9abe980-0632-11e9-80f1-2de3a7c55cc5.jpg)
![wowscrnshot_122218_213005](https://user-images.githubusercontent.com/46075239/50378458-f4ff1500-0632-11e9-8eea-85bacf3b6022.jpg)

**Comment by DragunovUA** [comment]
guys, pls fix it!

**Comment by nimeral** [comment]
It is bugged at the moment indeed. Was ok few months ago.

**Comment by lordhelmchench** [comment]
As soon as the second phase of the quest starts you will fall down. Even with 98 "Grip"-Points
