### ISSUE TITLE
Seed of Corruption not working properly

### ISSUE THREAD

**Issue by Doublespoons** [SunwellTracker/issues#209]
Decription: Seed of Corruption isnt exploding on death of an enemy.

How it works: 
Imbeds a demon seed into an enemy dealing X to X damage over time. When the target takes X damage or dies the seed will inflict X to X damage to all enemies within 15 yards of the target.

How it should work: 
After a certain amount of damage dealt or dies the target should explode.

Source (you should point out proofs of your report, please give us some source):

**Comment by Doublespoons** [comment]
Leaving a comment to check the status of this bugreport? Hinders aoe farming for cloth and what not so it's a bit annoying. Not rushing by any means i was just curious about the status.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by Doublespoons** [comment]
Thank you!

**Comment by Lameoxx** [comment]
its still bugged, the seed does not gets activated, if the target dies... tested it now on few single mobs.... there is no explosion on death how it should be... please fix this massive AoE bugg quickly
