### ISSUE TITLE
Freezing trap is useeless

### ISSUE THREAD

**Issue by Asherdoom** [SunwellTracker/issues#2091]
Decription: 
Everytime i trap someone (enemy player) they act normally like they are not rtapped at all amny times i got killed by a rogue in sprint under freezing  trap effect

How it works: 
read above and be ashamed

How it should work: freezing trap SHOULD block all actions in pvp for 12 sec maximum which does not work here at all. rogues feral druids and locks just dont give shit in netherstorm pvp world and simply when trigget freeze trap effect they keep attacking/casting as ususal

Source (you should point out proofs of your report, please give us some source): just asjk anybody to duel and rty and youn will see it. is fuckign broken

**Comment by Sorrow5** [comment]
this is a wotlk bugtracker, can u guys pls learn to read and stop reporting tbc bugs here

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
