### ISSUE TITLE
[warlock] [Talent] Demonic Knowledge

### ISSUE THREAD

**Issue by Sorrow5** [SunwellTracker/issues#2095]
Decription: Spell power gained from the talent is not matched by the tooltip. 
This is my spellpower without pet summoned and without any other buffs (2270)
![3 no pet my pannel](https://user-images.githubusercontent.com/39959624/50423094-1b020080-0851-11e9-8c74-6dacb589ab00.jpg)

Here is my pet panel without any buffs on him.  As u can see he has 1415 stamina and 556 intelect which in total gives us 1971. 12% of 1971 is 236,52 so i should gain that much spellpower.
![1 no buffs pet panel](https://user-images.githubusercontent.com/39959624/50423056-8bf4e880-0850-11e9-934e-e1435b1b457c.jpg)
Below is my character panel with pet summoned without any other buffs. My spellpower is 2486 which is a 216sp increase over base value of 2270. So i gained only 10,9589041% of 1971 (total pet's stamina and intellect).
![2 no buffs my panel](https://user-images.githubusercontent.com/39959624/50423117-792ee380-0851-11e9-8c24-7340baa4bbff.jpg) 

Here is an example with my pet having 1892 stamina and 752 intellect which in total gives 2644. 12% of that is 317,28 and this is the spellpower bonus i should gain.
![4 full buffed pet panel](https://user-images.githubusercontent.com/39959624/50423178-86000700-0852-11e9-8bed-0bcf4e3eebe1.jpg)
Instead of that i gained only 290 spell power as u can see on the screenshot. (2560spell power - 2270 base spellpower = 290) 290 equals to 10,96823% of 2644.
![5 full buffed my panel](https://user-images.githubusercontent.com/39959624/50423217-eb53f800-0852-11e9-9660-5703685b365a.jpg)

How it works: Spell power gained is to low.

How it should work: With 3 points spent in this talent it should increase spell damage by an amount equal to 12% of the total of active demon's Stamina plus Intellect.

Source (you should point out proofs of your report, please give us some source):

**Comment by Sorrow5** [comment]
any chance for a fix?

**Comment by Bjarzyna** [comment]
In addition, lower level ranks of this talent seems to give much lower values than intended. Rank 1 gave me around 2-3% instead of 4% when I was leveling.
