### ISSUE TITLE
[Death Knight] Starting area, fields

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#210]
Decription: 
Other deathknight on fields are not fighting with Scarlet mobs. DK horses and Scarlet NPC weapons!

How it works: 
Other deathknights NPC on fields are not fighting with Scarlet mobs, it's unlogical, also there are death knight horses standing on the field - they shouldn't be there at all. ALSO, there are a lot of Scarlet npc's that are fighting without weapons, just using their fists.

How it should work: 
All DK NPC must fight with another Scarlet NPC, and there shouldn't be DK horses on the field at all. Also there should be weapons.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020418_104222](https://user-images.githubusercontent.com/35955516/35775852-c47df31a-0999-11e8-92fd-cccc6f49e7a6.jpg)
![wowscrnshot_020418_104209](https://user-images.githubusercontent.com/35955516/35775853-c49ec5ae-0999-11e8-9cbe-abc1bdb662eb.jpg)
![wowscrnshot_020418_110044](https://user-images.githubusercontent.com/35955516/35775900-ca07eaba-099a-11e8-9b2d-1458f3eec93c.jpg)
![wowscrnshot_020418_105618](https://user-images.githubusercontent.com/35955516/35775884-7be7b7ac-099a-11e8-9016-9f080437ebc0.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
