### ISSUE TITLE
My belt disappeared

### ISSUE THREAD

**Issue by supposelol** [SunwellTracker/issues#2105]
Decription: 
Yesterday I got a belt from Arcatraz (N): https://db.excalibur.ws/?item=28375 Rubium War-Girdle. But It disappeared this morning for no reason! I wrote a ticket ingame and I was told to submit this here...

My char name is: Neverlucky

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
