### ISSUE TITLE
Quest: Defiling Uther's Tomb

### ISSUE THREAD

**Issue by luketti** [SunwellTracker/issues#2108]
Decription: 
The quest can't be completed, since everytime you try to use the item "Corrupted Mark of the Lightbringer" near the statue it sends the message "Requires Uther's Tomb Statue".
It only starts casting when used exactly behind the statue but it says "Target not in line of sight" at the end of the cast.
This quest worked perfectly before.

How it works: 
It gives you the item but doesn't let you use it to do the quest.

How it should work: 
You should use the item next to the statue, making Uther appear, he gives a speech and that completes the quest.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=lDynaDtPw6k

**Comment by Asureuz** [comment]
Hello,
Equip [Corrupted Mark of the Lightbringer] item and use it near Uther's Statue.
Quest should works correct.
![WoWScrnShot_030919_142524](https://user-images.githubusercontent.com/47954411/54072175-579d9f80-4277-11e9-9186-d28ce2b30e4d.jpg)
