### ISSUE TITLE
Combat via pets warlock

### ISSUE THREAD

**Issue by Micmenek** [SunwellTracker/issues#2109]
Decription: Warlock pets seem to have separate combat from their owner. Which means that when they are in combat, the warlock is not and can be sapped

How it works:  You send a pet to a target, your pet is attacking the target, you stay in combat, you get sapped. Here, even when the pet is literally hitting the enemy, you get sapped

How it should work: Once you send your pet to a target, you get automatically combat and cannot be sapped. 

Source (you should point out proofs of your report, please give us some source): Don´t really think ow to prove something that´s just an universal truth, but just to be sure  - https://eu.battle.net/forums/en/wow/topic/2226267523

**Comment by Akha72** [comment]
Unfortunately, that's a conscious decision from sunwell dev team.
