### ISSUE TITLE
Cant enter wstern plagelands

### ISSUE THREAD

**Issue by Deszka1111** [SunwellTracker/issues#211]
Decription: when im aboutto enter i simply cant,like an inviisble wall keeping me from it,but not just at the gates even when i tried to enter from the lake

How it works: i cant enter like there isnt a zone to enter

How it should work: i should just walk right trough the gate 

Source (you should point out proofs of your report, please give us some source): well i cant provide proof,because on pictrue it doesent show it,and i cant record

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
