### ISSUE TITLE
[Paladin] Judgement of Justice and Judgements of the Wise talent

### ISSUE THREAD

**Issue by thatsmee1996** [SunwellTracker/issues#2112]
Decription: 

How it works: 
Judgements of the Wise talent doesn't work while using Judgement of Justice ability. 

How it should work: 
Judgement of Justice should proc mana regen and replenishment buff from this talent as well as Judgement of Light and Wisdom.

Source (you should point out proofs of your report, please give us some source): 
https://wotlk.evowow.com/?spell=31876
https://wotlk.evowow.com/?spell=31877
https://wotlk.evowow.com/?spell=31878
https://wotlk.evowow.com/?spell=53407

**Comment by Riztazz** [comment]
Works fine for me, can you please re-test?
![image](https://user-images.githubusercontent.com/16348711/54281172-6ea30100-4599-11e9-936b-1cfc541cc97e.png)

**Comment by Azathothh** [comment]
Works fine - i've tried with every seal. Maybe you've hit someone with an absorb and your judgement was fully absorbed (in such case JotW shouldn't work).
