### ISSUE TITLE
Auto attack dont work anymore ! 

### ISSUE THREAD

**Issue by ma2mounbik** [SunwellTracker/issues#2113]
Decription: i w as in stv and auto attacked stopped to work and i cant anymore auto attack , by mouse or clicking on ability on my bar , its fixed by the way after relogging but this bug should be fixed , its really stupid to stop melee attacking as a melee class :v i dont know the cause by the way , its up to devs to discover in events of mouse auto attack to see the thing and thx ! 

How it works: melee attack buged 

How it should work: melee attack 

Source (you should point out proofs of your report, please give us some source):

**Comment by wonszopaionk** [comment]
Not enough proof, report to close I guess.
