### ISSUE TITLE
Pets hp is bugged

### ISSUE THREAD

**Issue by wapomani** [SunwellTracker/issues#2116]
Decription: pets hp is overtuned in retail pets hp was 3-4k less then they are here

How it works: 
way to much armor / resist / hp on pets (even dmg)

How it should work: 
they are overtuned by 30-50%

Source (you should point out proofs of your report, please give us some source): 
when i played in retail pets was killed fast and bm was given up relatively fast most hunters played mm or survival not bm but this server has bugged stats i have over 700 days played in tbc 500-600 on retail

**Comment by darklord88** [comment]
Dont think pets kill so hard i kill bm pets in 5sec.Main problem is the pet speeds too fast and the follow range too long.

**Comment by Azathothh** [comment]
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
