### ISSUE TITLE
[Jewelcrafting] Icy Prism reagents

### ISSUE THREAD

**Issue by Arthi93** [SunwellTracker/issues#212]
**Decription:** 
The Icy Prism recipe cosnumes too many reagents

**How it works:** 
Icy Prism requires 3 Frozen orbs and 3 of all other required gems to create. The recipe description says it needs only one. If you have one in the bag, creating icy prism will consume it, but if you have 3 or more it will consume up to three of all gems and frozen orbs. Wasn't sure yesterday, but today i've lost 3 orbs and gems again instead of one of each type. 

**How it should work:** 
Icy Prism recispe should only consume one of each required reagents, as recipe description says.

**Source:** I wont waste any more of my frozen orbs just to make a video. Please try to reprodyce it by yourself, it happens every time, so it shouldn't be hard.

**Comment by krauza666** [comment]
http://wowwiki.wikia.com/wiki/Icy_Prism
Patch 3.3.3 (2010-03-23): Undocumented change
The number of each gem necessary has been reduced from 3 to 1.

Now we have 3.2 content on Feronis, and 3.0 on Angrathar.

**Comment by Arthi93** [comment]
Recipe description should be changed than, since path 3.3.3 is not yet deployed on the server

**Comment by Arthi93** [comment]
Can I know why is this closed but still doesnt work?

**Comment by Arthi93** [comment]
I guess i cant....
