### ISSUE TITLE
[XT-002 Deconstructor][Warrior] Spellreflecting debuffs

### ISSUE THREAD

**Issue by wonszopaionk** [SunwellTracker/issues#2121]
Decription: 
As a warrior, after using Spell Reflection, it may reflect the debuffs (Light bomb or Gravity bomb) onto the boss.

How it works: 
When you use spell reflection and the boss chooses you as a target for a debuff, the debuff is reflected onto the boss, which suffers it.
It was tested on u10 normal mode encounter as a protection warrior without the glyph or improved spell reflection talent - I reflected Light bomb onto the boss.

How it should work: 
Spell reflect should only make you not suffer the debuff without redirecting it onto the boss.

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Spell_Reflection

"_Some "boss" mobs in general and a lot of mobs in raids are immune to their own spell, but reflecting it means you don't suffer its effects_"

**Comment by Riztazz** [comment]
You shouldn't be able to reflect those alltogether, something is wonky and i will look into it
