### ISSUE TITLE
[Icecrown Citadel - Lady Deathwhisper] Target choosing of the ghosts spawned during the encounter

### ISSUE THREAD

**Issue by wonszopaionk** [SunwellTracker/issues#2122]
Decription: 
During lady encounter, P2, the lady summons the ghosts every x seconds. The ghosts always chase 1 person from the raid, every wave of ghosts is focused on the person chosen at the beginning.

How it works: 
Each waves' summoned Vengeful Shades focus on one random person chosen withing 1st wave of ghosts. On 10 man each ghost, on 25 man each 2 ghosts are chasing one person entire fight.

How it should work: 
Each wave, the ghosts' are supposed to choose targets randomly (each ghost separatedly). Chasing one player with 2 ghosts is possible, but it is just a matter of maths [(1/25)^2 * 100% =~ 0,16% chance].

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/npc=36855/lady-deathwhisper#article

"_Summon Vengeful Shade - Summons a Vengeful Shade from the body of a dead Adherent or Fanatic._

 _Vengeful Shade - Pursues a **random** target._"

**Comment by Sorrow5** [comment]
any video proof? I dont remember all ghosts chasing one target when i did lady

**Comment by wonszopaionk** [comment]
well we did it yesterday, and on both 10 man and 25 man ghosts were definitely chasing only 1 person.

**Comment by Wojtyas** [comment]
Thanks for report, will take care of that asap

**Comment by wonszopaionk** [comment]
Bump. The fix is not live yet, it still happened on yesterday's Lady Deathwhisper 25n.

**Comment by Wojtyas** [comment]
Fix is ready, will be up with next update :)
