### ISSUE TITLE
[Icecrown Citadel] Professor Putricide - Tear Gas duration on DK(all?) pets

### ISSUE THREAD

**Issue by avarishd** [SunwellTracker/issues#2123]
Decription:  Currently the duration of Tear Gas (normal difficulty) is 3-4 seconds longer on controlled pets.

How it works: Tear gas lasts longer on pets for unknown reason.

How it should work: Tear gas should act the same way (same duration) on pets as acts on players.

Source (you should point out proofs of your report, please give us some source): 
https://www.twitch.tv/videos/358320254?t=52m02s Look at my mouseover on tear gas at the pet debuffs bar (bottom right, next to the chat covering image)

**Comment by wonszopaionk** [comment]
That's true, pets are stunned for few seconds longer than players.

**Comment by Wojtyas** [comment]
Tear Gas lasts longer on pets.
https://www.twitch.tv/videos/358320254?t=52m02s
