### ISSUE TITLE
I can't take dual spec

### ISSUE THREAD

**Issue by Mihardq** [SunwellTracker/issues#2124]
Decription: 
I can't take dual spec on my paladyn (first champion 61 lvl)

How it works: 
I go to pal trainer, take option --> accept to take dual spec (I have 61 lvl and over 1000 gold) --> and happens nothing.

How it should work: After accept that option I should have dual spec and lost 1000 gold.

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
Try to turn off all addons and buy dual spec from Your class trainer. If You will have still issues please create an ingame ticket.
Regards
