### ISSUE TITLE
[3.3 patch notes] Tailoring

### ISSUE THREAD

**Issue by Hahecz** [SunwellTracker/issues#2128]
Decription:
Patch note "Cooldown and location requirements removal of Moonshroud, Spellweave and Ebonweave.  " was not implemented completely with Fall of the Lich King content.

How it works:
All three crafts still require player to stand in their respective dragon shrines. Cooldown was properly removed.

How it should work:
Location requirement should be removed from all three crafts.

Source (you should point out proofs of your report, please give us some source):

Note: there is a changelog entry dated 19.12.2018 with: "- Cooldown and location requirements removal of Moonshroud, Spellweave and Ebonweave."

**Comment by Hahecz** [comment]
Screenshot:
https://imgur.com/a/vLwjQId

**Comment by Riztazz** [comment]
Fixed, will be live with realm update
