### ISSUE TITLE
[Death Knight][Quest] Important bug with DK main quests!

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#213]
Decription: 
[Bloody Breakout](https://db.darkwizard.pl/?quest=12727) first of all this quest is hard to complete and i will tell you why. 

How it works: 
[Bloody Breakout](https://db.darkwizard.pl/?quest=12727) first of all this quest is hard to complete and i will tell you why. Once player took and complete this quest (picture 1), player just leave this location(picture 2) and leave Koltira in this castle...But what's wrong with Koltira? After player leave this location Koltira won't disapear TILL HE FINISH FIGHTING, BUT he is not fighting at all, and NPC can't kill him beacuse he has a lot of health.(picture 3).
So what's the problem you ask me? You completed quest and left this place..
He won't disaper till he finish fight, SO HE WON'T respawn TILL he finish figh. That caused the problem(picture 4). A lot of players JUST WAITED for taking Koltira quest and noone knew that Koltira was just standing upstairs and "fighting" with NPC after previous player fcompleted his quest. 
The problem can be seemed local problem, BUT it's happening EVERYTIME previous player finished quest and leave Koltira alone upstairs just standing there. And everytime there are a lot of players just waiting for him for hours...
P.S. Also after releasing him from jail during quest he must wear his gear and sword but he doesn't. (picture 5).

How it should work: 
1) Koltira must NOT be hostile to Scarlet NPC and after completeing quest ignore them and RUN AWAY FROM THE CASTLE and shouldn't stop at all. **OR** as he says: "I'll **DRAW THEIR FIRE**, you make your escape behind me." so he must be strong enough to kill Scarlet NPC and escape from the castle by his own. (but now he is not fighting at all, just standing there while mobs hitting him)
2) He must wear his gear and sword, as he says : " I'll need to get my **RUNEBLADE AND ARMOR**... Just need a little more time."

Source (you should point out proofs of your report, please give us some source): 
![1](https://user-images.githubusercontent.com/35955516/35776982-c25bda6a-09ae-11e8-84c2-d52ba6f2bed9.jpg)
![2](https://user-images.githubusercontent.com/35955516/35776983-c499b78e-09ae-11e8-8d76-5f48a469742b.jpg)
![3](https://user-images.githubusercontent.com/35955516/35776984-c6abf8c0-09ae-11e8-8619-29e65e47f394.jpg)
![4](https://user-images.githubusercontent.com/35955516/35776987-c9320206-09ae-11e8-9f07-3d2f9b9ad1f4.jpg)
![5](https://user-images.githubusercontent.com/35955516/35776988-caf3f3ce-09ae-11e8-9d97-82eaf456a174.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
