### ISSUE TITLE
Sigil swap doesnt work help i cant nuke 

### ISSUE THREAD

**Issue by enriu** [SunwellTracker/issues#2134]
Decription: Sigil swapping doesnt work properly

How it works: IF u have Sigil of  Virulence and u swap it in combat with Sigil of the hanged Man and u already have the buff, it removes the buff of virulence(correct) BUT when u use  lets say obli after the swap it doesnt start the stacking  instantly.

How it should work: When u swap sigil it should waste 1 gcd and remove the buff of the sigil that u swapped but it should start instantly stacking the other sigil and not have a cd.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Like said above, i need some proof before i do any changes

**Comment by Riztazz** [comment]
No answer for 5 days, closing
