### ISSUE TITLE
Quests in Hellfire peninsula

### ISSUE THREAD

**Issue by AzenGaming** [SunwellTracker/issues#2139]
Decription: 
i go around and kill quests in the areas im supposed to and i make sure that is is the same creatures but my quest shows no tracking or indication that i have completed said quest this is only occurring on my Death Knight

How it works: 
The quests dont track

How it should work: 
The Quest should track my progress when killing or aquiring the proper items

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
Please describe this issue more precisely.
Regards

**Comment by AzenGaming** [comment]
It since fixed after a pc restart but for a while my quests in hellfire
peninsula and in the entire game were not tracking such as item collection
quests or enemy slaying quests
