### ISSUE TITLE
[Death Knight] Army of the dead ghoul taunt

### ISSUE THREAD

**Issue by maryxxxjane** [SunwellTracker/issues#214]
Decription: 
Army of the dead ghouls taunt is working on bosses.
How it works: 
Aotd ghouls taunt is working on BOSSES

How it should work: 
Boses are inmune to Aotd ghouls taunt

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
http://www.wowhead.com/spell=42650/army-of-the-dead#comments

"This is not true against raid bosses. The Ghouls won't taunt mobs that are flagged as "Boss" in-game (level ?)."

On our server only dungeon bosses can be taunted (they have 82 lvl, so they aren't flagged as "Boss").
