### ISSUE TITLE
Felguard Degrader doesn't spawn

### ISSUE THREAD

**Issue by iliqiliev** [SunwellTracker/issues#2140]
Decription: The title is self explanatory, i've been looking for some hours but he doesn't seem to spawn at all. His location is unknown in the sunwell database too - [https://db.darkwizard.pl/?npc=23055](url). This makes you unable to complete the Shartuul's Transporter Event.
Source:
![wowscrnshot_010919_095548](https://user-images.githubusercontent.com/25604760/50885192-b2d92000-13f5-11e9-9a27-41714f7b8c91.jpg)

**Comment by Dootz** [comment]
Hi, the event currently is not scripted.
