### ISSUE TITLE
Lord Marrowgar Bone slice

### ISSUE THREAD

**Issue by lkrocek** [SunwellTracker/issues#2142]
Decription: 
As a tank I feel the bone slice is doing plenty of dmg then it should do.

How it works: 
I was off tank as a druid on Lord Marrowgar 25m, and Bone slice hit me about 20k per hit, we did but 20k dmg with 65+% reduction and 12% from talents is kinda plenty.

How it should work: 
Boss has up to 27464 physical dmg, bone slice should split of 200% into 2 targets so each target should got up to 27464dmg - physical dmg reduction. That mean OT 27464*(1-0,65) = 9612

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?spell=69055
https://wow.gamepedia.com/Lord_Marrowgar

This reset I will check it out in details what it does and put here full log

**Comment by wonszopaionk** [comment]
Where did you find that damage? It seems really low-ish cause MT would take ~8-9k from swings from 25man raidboss...
Also:
You linked 10man ability - It's 200% dmg to MT and OT on 10man (2 targets).
On 25 man its 300% dmg between MT + 2x OT (3 targets).
https://www.wowhead.com/npc=36612/lord-marrowgar#abilities-normal-25-player
Just do it 3 tanks.
It's split correctly along 3 targets - done that on some PUG with 3 tanks (I was one of the OT's) and three of us got hit.

**Comment by lkrocek** [comment]
my source is https://wow.gamepedia.com/Lord_Marrowgar
and even on your link I see 200% of dmg even on 25m heroic...

![image](https://user-images.githubusercontent.com/376860/50957636-05324380-14bf-11e9-9d68-2b95afbd0ef5.png)

**Comment by wonszopaionk** [comment]
You are wrong, the tooltip is incorrect as comment says.

![obraz](https://user-images.githubusercontent.com/28888570/50958093-2e9f9f00-14c0-11e9-8d7e-dd22a573b19e.png)

![obraz](https://user-images.githubusercontent.com/28888570/50958121-41b26f00-14c0-11e9-9326-906cdf5b3c41.png)

**Comment by lkrocek** [comment]
ah well, but find good and true description of this so hard.
