### ISSUE TITLE
loggin bugged

### ISSUE THREAD

**Issue by Aswax** [SunwellTracker/issues#2143]
Decription: 
wczoraj dołączylem do ruskiej gildii COBET TITAHOB, od tamtego momentu mam problemy z logowaniem, gdy zaloguje, zacina mi gre i mam brak odpowiedzi, moglibyście usunąć mnie z gildii i przetransportował moja postac np do orgi  

How it works: 
gra sie zacina po 20 sek

How it should work: 
powinna logowac normalnie

Source (you should point out proofs of your report, please give us some source):

**Comment by wonszopaionk** [comment]
Reports should be done in english laungage.
You should resolve the issue with clearing cache and making ingame ticket.

**Comment by Asureuz** [comment]
Hello,
Write an ingame ticket from the another character.
Regards
