### ISSUE TITLE
[Achievement] Trial of the Champion Heroic

### ISSUE THREAD

**Issue by nemer116** [SunwellTracker/issues#2146]
Decription: 
In Trial of the Chapmion heroic 5-man there is achievement where you have to kill all bosses 
![obraz](https://user-images.githubusercontent.com/25852158/50919142-49cbc980-1442-11e9-85b3-3c2663982991.png)
Today I killed Runok Wildmane but achievement is still uncomplete.
Few days ago same. Killed tauren boss and achievement still uncomplete.

Screenshots:
![4](https://user-images.githubusercontent.com/25852158/50919354-dbd3d200-1442-11e9-95dc-f1e66b74f8b3.png)
![obraz](https://user-images.githubusercontent.com/25852158/50919420-10e02480-1443-11e9-808e-758e782bfcb4.png)

How it works: 

I killed boss and didn't get achie.

How it should work: 

If you kill all bosses you should get achie.

**Comment by jabukarium** [comment]
That is why you should switch to Horde.
