### ISSUE TITLE
Temporary Weapon Enchant not working on heirloom?

### ISSUE THREAD

**Issue by Blackezt** [SunwellTracker/issues#2147]
Decription: Unable to use Minor Wizard Oil on Dignified Headmaster's Charge

How it works: When I attempt to use Minor Wizard Oil on the heirloom staff, a message pops up "Target is too low level".

How it should work: Minor Wizard Oil should increase the Spellpower on a weapon by 8 for 60 minutes. It cannot be applied to a wepon with a level of greater than 165

Source (you should point out proofs of your report, please give us some source): I have been unable to find any references to this.

**Comment by wonszopaionk** [comment]
It works as on retail - you cannot do this on heirlooms:
https://www.wowhead.com/item=20744/minor-wizard-oil#comments
"By Dejoblue (950 –  3·6)  on 2009/02/20 (Patch 3.0.9) |   |  
As of Patch 3.0.9 this **does not apply to Heirloom weapons**, specifically Dignified Headmasters Charge.
Error message says "Item is too low level.""
and
"By lltomohikoll (758 – 11) on 2009/07/24 (Patch 3.1.3)
**Target weapon should have Item lvl 5 or greater**."
Report can be closed.

**Comment by Akha72** [comment]
wonszopaionk is right, moreover level requirements listed in descriptions of temporary enhancements apply both to level of player using them and item level of weapon they are used on.
