### ISSUE TITLE
DK melee haste talons stacking

### ISSUE THREAD

**Issue by jabukarium** [SunwellTracker/issues#2148]
Decription: DK's Icy Talons (mdps haste) stacks.

How it works: 

So, if you take enough DKs as dps in any raid, the melee haste talons stack, thus increasing mdps attack speed ridiculously.

How it should work: 

Only 1 Icy Talon, no matter how many DKs.

Source (you should point out proofs of your report, please give us some source): [IMG]http://i66.tinypic.com/2zog93b.jpg[/IMG]

**Comment by wonszopaionk** [comment]
It's only visual, you get only one 20% haste buff from those DK's. It doesn't stack.
Report to delete in my eyes.
