### ISSUE TITLE
The ephemeral snowflake item does not work well

### ISSUE THREAD

**Issue by Monels** [SunwellTracker/issues#2149]
Decription: The ephemeral snowflake item does not work well the regeneration of mana that gives per second to have active healings in objectives.

How it works: I as a heal duida to have full periodic healings throughout the raid the regeneration of 11 mana per second is limited regeneration that gives the item

How it should work: having full periodic healings the item for each active healing should give 11 mana points each time it heals something that is not happening, because many healings do not count and therefore does not give the mana regeneration that says. In a raid taking full healings throughout the raid in most of these the item does not give the mana although the dot is active and healing
![wowscrnshot_011119_105038](https://user-images.githubusercontent.com/46604591/51048728-6591b580-1591-11e9-884d-9ed1576e9115.jpg) https://youtu.be/Wa8o2j8LZT8 if you like I could make a video of a raid using the item so you can see that mana regeneration does not work well

**Comment by Asureuz** [comment]
Hello,
I see that every druid's heal over time is triggering this effect. Please check mana regeneration in combat log. It will be best proof.
![image](https://user-images.githubusercontent.com/47954411/53342916-639c6f80-390f-11e9-848b-5f340755cd2a.png)
![image](https://user-images.githubusercontent.com/47954411/53342970-8038a780-390f-11e9-8391-aed6e1f354e0.png)
![image](https://user-images.githubusercontent.com/47954411/53342998-8d559680-390f-11e9-80a5-9a91c0c5016b.png)
![image](https://user-images.githubusercontent.com/47954411/53343026-9f373980-390f-11e9-8eef-8c389f524637.png)

**Comment by Monels** [comment]
Good, I did the test in the register and by sending some healing skills the trinket is activated normally but as seen in the following pictures does not give the mana regeneration when some ticks of the skills heal, and it is much higher in some raid.
![wowscrnshot_022619_170140](https://user-images.githubusercontent.com/46604591/53453141-fe1cb180-39e8-11e9-9c97-89fe2c58b12f.jpg)
![wowscrnshot_022619_170151](https://user-images.githubusercontent.com/46604591/53453142-fe1cb180-39e8-11e9-804a-a7044c140f76.jpg)
![wowscrnshot_022619_170204](https://user-images.githubusercontent.com/46604591/53453143-feb54800-39e8-11e9-80de-581f72ffa1eb.jpg)

**Comment by Monels** [comment]
As seen in the last image, he skips up to 3 healings to give only 11 points of mana when in reality he had to have given the triple
