### ISSUE TITLE
[Death Knight] Starting area trash NPC's

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#215]
Decription: 
Some trash NPC in DK's starting zone tavern.

How it works: 
Some trash NPC in DK's starting zone tavern. Dead Scarlet NPC's that are standing like they are alive. It's not my client problem, every player see them. They are not despawning, just staying there permanently. Disable them, delete or make them invisible please.

How it should work: 
Just delete them please

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020418_135520](https://user-images.githubusercontent.com/35955516/35777273-b5c718b4-09b3-11e8-973e-be2f64ef4dbd.jpg)

**Comment by Dootz** [comment]
will be fixed with next update
