### ISSUE TITLE
Warbringer O'mrogg drops

### ISSUE THREAD

**Issue by Fiaskoomg** [SunwellTracker/issues#2151]
Decription: 
Warbringer O'mrogg drop chances seems to be off when compared to atlas loot addon

How it works: 
Skyfire Hawk-bow have 100% drop chance on a base of my 8 runs in this dungeon.
How it should work: 

should have 17.31% drop chance

Source (you should point out proofs of your report, please give us some source): 
well its no proof but just called it, check chat ;_;
Iknow i said 10th time in chat but this was like my 8th run "only"
![drop 1](https://user-images.githubusercontent.com/46278224/51075171-68bb9d00-1688-11e9-93be-f6d1606b31d8.PNG)
![drop 2](https://user-images.githubusercontent.com/46278224/51075172-68bb9d00-1688-11e9-9934-e0c1ecb9c842.PNG)

Please chceck if droprates are correct

**Comment by Dootz** [comment]
you must have been really unlucky :( everything seems fine. I've killed him couple times and received different items
