### ISSUE TITLE
[Druid] Rake initial dmg doesn't ignore armor of a target

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#2152]
**Decription:** Rake initial dmg doesn't ignore armor of a target

**How it works**: This spell consists of 2 parts: **initial bleed dmg part** and the **bleed damage over time part**. Bleeding over time works correctly which means that it already ignores the armor of a target so that any additional armor penetration value we get doesn't change the damage. However the initial dmg part is bugged and even though its dmg gets increased via Mangle debuff (30% more bleed dmg) it doesn't ignore the armor of a target.

**How it should work:** Initial dmg component of Rake should ignore armor of the target.

**Source (you should point out proofs of your report, please give us some source):** 

Link to album showing incorrect scaling with armor penetration and DrDamage addon tooltip value which tells us that the damage number shouldn't change (4943 dmg value) https://imgur.com/a/VS01j2M

> 2009-06-12
> https://www.mmo-champion.com/threads/652287-DPE-whit-ArP
> 
> "Since Armor Penetration basicly increases the dmg done by Shred, Magle, FB
> but it has 0 effect on the rip / rake bleed effect"
> 
> 2009-04-16
> https://www.mmo-champion.com/threads/644012-Kitty-Discussion-Armor-pen-gt-Agi
> 
> "RIP: 32%
> Shred: 30.%,
> White: 20%
> Rake: 12%
> Ferocious Bite: 6.0%
> 44% of the damage doesn't benifit from ARP. With the Idol of Worship will be even more."

**Comment by avarishd** [comment]
Can confirm, just tested it. (tested on prot paladin, he had no buffs also nor aura)
No items with procs/ buffs/trinkets

97 initial hit without mangle
126 with mangle
Ticks 724 without mangle
Ticks 914 with mangle 

Logs proof http://www.worldoflogs.com/reports/fkm5164wd336yozn/log/

No arp trinket
[17:24:40.009] Avarishd Rake Solas 97 - Initial hit  (non crit)
[17:24:42.891] Avarishd Rake Solas 724 tick

With arp trinket proc
[17:26:02.122] Avarishd gains Mjolnir Runestone from Avarishd (arp proc trinket )
[17:26:02.939] Avarishd hits Solas 157 initial hit (non crit)
[17:26:04.739] Avarishd hits Solas 159 intial hit (non crit)

**Comment by avarishd** [comment]
bump, since it's taking so long for a fix.

**Comment by avarishd** [comment]
bump, more than a month since the report @Amarok-bt

**Comment by Asureuz** [comment]
Hello,
@Amarok-bt @avarishd I tested rake in our PTR.
My values:
Normal initial dmg - 132
Normal initial dmg + Mangle - 172
Normal initial dmg + Mjolnir proc - 159
Normal initial dmg + Mangle + Mjolnir proc - 206
