### ISSUE TITLE
Blood draining enchant not working

### ISSUE THREAD

**Issue by darklord88** [SunwellTracker/issues#2153]
Decription: 
Blood draining enchant dont work nothing healing proc as u can see on skada total healing done...

How it works: The enchant not proccing atm

How it should work: Below 35% hp the enchant need heal u depend on stacks (1 Stacks: 360 to 440 heal.
2 Stacks: 720 to 880 heal.
3 Stacks: 1080 to 1320 heal.
4 Stacks: 1440 to 1760 heal.
5 Stacks: 1800 to 2200 heal.)

https://www.wowhead.com/spell=64579/blood-draining#comments

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_011219_214643](https://user-images.githubusercontent.com/10784910/51078339-ec3eb380-16b3-11e9-82c3-a269e2a667c3.jpg)

**Comment by Asureuz** [comment]
Hello,
I checked this in our PTR and works correct, try to enable Your % HP Value on Your character and check once again that enchant works or not.
![image](https://user-images.githubusercontent.com/47954411/53728987-4702b900-3e74-11e9-9041-9ca36f20e960.png)
![image](https://user-images.githubusercontent.com/47954411/53729022-5da91000-3e74-11e9-92a9-7b5c7ece3b2e.png)
