### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by juiceboxchronicles** [SunwellTracker/issues#2154]
Decription: 
the installation client for windows isn't working

How it works: 
goes to an error 404 page

How it should work: 
install the game

Source (you should point out proofs of your report, please give us some source): 
![aaaaaa](https://user-images.githubusercontent.com/46636679/51079669-d8e71480-16c2-11e9-8f66-0c782ae8c004.PNG)

**Comment by Asureuz** [comment]
Hello,
Try to use guide which You can find in our forum
http://sunwell-community.com/index.php?/topic/6448-how-to-connect-tutorial/
Regards
