### ISSUE TITLE
Lockpicking bug

### ISSUE THREAD

**Issue by turbowolke** [SunwellTracker/issues#2155]
Decription: 
I can't open a lockbox which requires a skill of 25 while my progress is 100. Specifically it's an item called [Heavy Bronze Lockbox]. 

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/ITM7c4Y.jpg

**Comment by Azathothh** [comment]
Looking at this screenshot i'm pretty sure that your CTRL key was stuck and that's why you couldn't open it (and probably do couple of other things)
