### ISSUE TITLE
Gnomish Death Ray

### ISSUE THREAD

**Issue by hyxgod** [SunwellTracker/issues#2156]
Decription: 
When you channel it, it gives u the debuff and removes hp from you. but it doesnt "Direct a burst of energy at your opponent"

How it works: 
^

How it should work: 
it should burst him after the channel.
Video proof (There's plenty) https://www.youtube.com/watch?v=leoK-k0AP2g

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Tested on the PTR and works correctly.
https://streamable.com/bkdv5
Regards
