### ISSUE TITLE
[Death Knight] The Scarlet Apocalypse quest

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#216]
Decription: 
After starting  [The Scarlet Apocalypse](https://db.darkwizard.pl/?quest=12778#?ref=sunwell.pl) and landing from the Acherus to the ground you agroo elite mobs that are shooting arrows and kill you almost instantly if you don't doge them

How it works: 
After starting  [The Scarlet Apocalypse](https://db.darkwizard.pl/?quest=12778#?ref=sunwell.pl) and landing from the Acherus to the ground you agroo elite mobs that are shooting arrows and kill you almost instantly if you don't doge them.
They are pulling and killing you BEFORE you complete this quest and taking [An End To All Things...](https://db.darkwizard.pl/?quest=12779)

How it should work: 
There shouldn't be  this npc  so close to your landing area. Or decrease their agro range please

Source (you should point out proofs of your report, please give us some source): 
![1](https://user-images.githubusercontent.com/35955516/35777616-d7eea6fe-09b9-11e8-9ec9-7c802e322b00.jpg)
![2](https://user-images.githubusercontent.com/35955516/35777619-da863c88-09b9-11e8-903a-a11470842196.jpg)
![3](https://user-images.githubusercontent.com/35955516/35777621-dc7a5d26-09b9-11e8-90d7-6d1e6109044d.jpg)
![4](https://user-images.githubusercontent.com/35955516/35777622-de1a7f3a-09b9-11e8-9fea-d063a0c384a6.jpg)

**Comment by Riztazz** [comment]
Resolved
