### ISSUE TITLE
Ethereum Prison Key has low drop chance.

### ISSUE THREAD

**Issue by ekunboy** [SunwellTracker/issues#2161]
Description: I've been farming Ethereals in The Heap in Netherstorm for several hours. They're supposed to drop Ethereum Prison Keys with a drop rate of 3%. I've killed 1200 so far, but have only looted 5 keys. With this amount of kills, I should've received ~36 keys on average. As you can see from the screenshots, I've looted almost 400 Zaxxis Insignias and many, many stacks of Netherweave Cloth from the mobs, which confirms the amount of kills. 

How it works: 

Simple drop item has too low chance to drop.

How it should work: 

Drop rate should be 6 times higher.

Source (you should point out proofs of your report, please give us some source): 

https://www.wowhead.com/item=29460/ethereum-prison-key#dropped-by

https://wotlk-twinhead.twinstar.cz/?item=29460

![image](https://user-images.githubusercontent.com/40549290/51278248-66d04180-19da-11e9-8c33-bddcac4bc0c3.png)

**Comment by darklord88** [comment]
Keys have 100% drop chance from jailors so drop is fine but there isnt so many jailors.Only 5-6 with 15min respawn time what is too long.

**Comment by Akha72** [comment]
FYI you need to complete q chain to make jailors visible.
