### ISSUE TITLE
[Priest] [ICC] Valithria Dreamwalker - Can't buff boss with Guardian Spirit

### ISSUE THREAD

**Issue by presstmoded** [SunwellTracker/issues#2162]
Decription: Guardian Spirit is an extremely useful cooldown you should be able to put on the boss to increase the healing taken boss recieves. 

How it works: Tried it out yesterday, can't use it on boss for some reason - says "target is invalid".

How it should work: You should be able to cast this buff on boss, and it should work just as it would work on player (preventing death, increasing healing taken). 

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=LEipp3dDR9I  Holy priest's PoV from TankSpot 2010's guide, at 2:08 she casts this exact buff on Dreamwalker.

- PLEASE FIX THIS BEFORE HC -

**Comment by Morphed123** [comment]
Will this get fixed soon?

**Comment by smokeandnoob** [comment]
Still without any respond nice 👍

**Comment by Asureuz** [comment]
Hello,
Guardian Spirit should works on Valithria Dreamwalker correctly now.
Regards
