### ISSUE TITLE
Sindragosa 

### ISSUE THREAD

**Issue by Velaurius** [SunwellTracker/issues#2164]
Decription: 
Sindragosa 10N 2 bugs, that make the encounter harder than it was meant to be.

How it works: 
Bug 1)Tail Swipe kick away people from the belly of Sindragosa as well , this should not happen.

Sindra also tail swiped a TOMB target in PH2 who was not nearly the tail of the boss, that resulted in a wipe.

Bug 2)  Chilled to the Bone  - Sometimes you get from 0 to 5 stacks in one second, I think that only happens after a blistering cold but I'm not sure about this last part.

How it should work: 
Bug 1) [Tail Swipe] I —Inflicts 11250 to 18750 damage on enemies within 20 yards of the tail's impact point, knocking them back. 1 sec cast

Bug 2) Chilled to the Bone - Causes those who attack Sindragosa with physical attacks to be chilled to the bone, dealing 1000 Frost damage per 2 sec for each application.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Sindragosa_(tactics)

**Comment by avarishd** [comment]
You have literally 1 yard of space in between getting to her front (getting parried, not being able to shred) and being tile swept away. And on top of that the moment you enter her hitbox you are almost guaranteed to get tail swept. Please fix.

**Comment by lorderheller** [comment]
Getting tail swiped inside Tomb in last phase. Really annoying, and ppl were way outside of tail swipe radious.

**Comment by shadownib** [comment]
When someone will fix this that's so basic ( let the fight be enjoyable ) Some ppl joining the server , to learn the mechanics , not to feel the Custom " challenge " :Dx

**Comment by Asureuz** [comment]
#2207
