### ISSUE TITLE
Nibelung

### ISSUE THREAD

**Issue by kameleon19851** [SunwellTracker/issues#2165]
Decription: 

Nibelung is not work good because is bugget anyone target
How it works: 

Valkiries not damage to target
How it should work: 
Valkiries they should beat all the targets

Source (you should point out proofs of your report, please give us some source):

**Comment by wonszopaionk** [comment]
Valkyrie attack only the target they initially spawn on. You cannot control them, and if the target which caused valkyrie to spawn dies - valkyries do nothing.

**Comment by Asureuz** [comment]
Hello,
Tested on the PTR - Valkiries attack currently player's target. Weapon's effect works correctly.
Val'kyr target the mob that caused the proc (not based on your aggro). If the target dies, they will wait and attack the next target you deal damage to, whether directly or indirectly. Thus, they will never randomly target mobs and break CC.
Regards
