### ISSUE TITLE
[Quest] Grizzly Hills, "An Intriguing Plan" ID: 12165

### ISSUE THREAD

**Issue by Bel-WOW** [SunwellTracker/issues#217]
Decription: 
Quest "An Intriguing Plan" ID: 12165 jest drugim questem w łańcuchu składającym się z 6 questów. Quest jest pomijany przez NPC (po wykonaniu pierwszego questa, przechodzi od razu do trzeciego questa). 

How it works: 
Jak wyżej, quest jest pomijany, a NPC przechodzi do kolejnego "etapu".

How it should work: 
Quest nie powinien zostać pominięty.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020418_134828](https://user-images.githubusercontent.com/36129798/35777797-5e812616-09b4-11e8-8e28-401b655cdf47.jpg)

**Comment by Bel-WOW** [comment]
Tymczasowe rozwiązanie to dodanie questa ręcznie przez administratora.

**Comment by Riztazz** [comment]
Resolved
