### ISSUE TITLE
Battered Q Bugged

### ISSUE THREAD

**Issue by Kubek2** [SunwellTracker/issues#2171]
Decription: 
When I finish q : [The Purification of Quel'Talar] i must pick up blade to my bag and when i open it, I show nothing

How it works: I dont see blade inside the questobject.

How it should work: I must pick this blade form questobject.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kubek2** [comment]
Character nicname is Huxar.

**Comment by Cwiercpasiec** [comment]
Isn't this thepart of the chain where you enter Sunwell Plateau? If so, you should enter solo, not in raid group, quest isn't marked as raid q and that's why you don't see the blade.

**Comment by Asureuz** [comment]
Hello,
How Cwiercpasiec said, You have to complete this quest without raid group. You have to enter to the SWP in party group or solo, but not in raid.
Regards
