### ISSUE TITLE
Lich King P4 - only 3 adds

### ISSUE THREAD

**Issue by NewFlyingDutch** [SunwellTracker/issues#2173]
Decription: 
In phase 4 (or 2.5) only 3 raging spirits spawn. It should be 4.

How it works: 
Even though DBM shows that in the **second** , better known as phase 2.5 or phase 4, remorseless winter phase there will be a 4th add, only 3 adds spawn.

How it should work: 
It should be 3 adds in the first remorseless winter phase and 4 in the second remorseless winter phase.

This is THE time you will have to use bloodlust/heroism as long as you are not totally overgeared, so you nuke down the third add and priorize the 4th add when you enter the platform again.
Source (you should point out proofs of your report, please give us some source):

**Comment by baseswotlk** [comment]
please fix

**Comment by Chryslol** [comment]
Some source: 

https://www.youtube.com/watch?v=UbbBsV5Tdqc

**Comment by Wojtyas** [comment]
Done, will be implemented with next update.
