### ISSUE TITLE
The Dusk Blade proc bug

### ISSUE THREAD

**Issue by Spotterman** [SunwellTracker/issues#2176]
**Decription:**  <a href="https://www.wowhead.com/item=43613/the-dusk-blade">The Dusk Blade</a> obtainable from reinforced lockboxes is supposed to give you <a href="https://www.wowhead.com/spell=59043/the-darkest-night">The Darkest Night</a> buff that gives 155 ArP, stackable 3 times. I'm dual-wielding this daggers and proc RARELY procs only once, let alone 3 times. 

**How it works:** (Keep in mind I'm dual-wielding these) Test included:
100 auto-attacks 
10 Mutilates (muti hits with both weapons = 20 hits)
120 hits = 3 inconsecutive <a href="https://www.wowhead.com/spell=59043/the-darkest-night">The Darkest Night</a> procs.

**How it should work:** <a href="https://www.wowhead.com/spell=59043/the-darkest-night">The Darkest Night</a> should proc A LOT more than this! This way, it never has a chance to stack even 2 buffs, let alone if players are using only 1 dagger and not 2 like I am.

**Source:** Couldn't find official note but this is common sense stuff.

**Comment by Dootz** [comment]
https://www.wowhead.com/item=43613/the-dusk-blade#comments

> rambaral on 2008/11/10 (Patch 3.0.3)
> I never asked what the ArPen would be, I was commenting on the proc rate compared to the Night Blade. The Night Blade had a proc rate that would proc itself (and sometimes proc again) meaning it was essentially at the full 3 stack the whole time, making it so overpowered that it was better than epic BoPs and was selling for 3000+g. **Blizz nerfed it so bad with a hidden cooldown it became useless** and some folks who spent thousands of gold on one were (understandably) $%^&ed-off. Making a new version of it got me wondering if they were going to throw a bone to people and make it a little more
