### ISSUE TITLE
Sylvanas Lament and Sunsorrow reaction

### ISSUE THREAD

**Issue by Volarei** [SunwellTracker/issues#2177]
Decription: 
After giving amulet to Sylvanas and when she's starting to sing her lament, Ambassador Sunsorrow whispers to player to come to him. Interacting with him results with him giving to player the book "Lament of the Highborne" which contains lyrics for Sylvanas' lament.

How it works: 
The book should've lyrics and it has but with all the code language

How it should work: 
Probably book shouldn't have the code, I guess

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_012419_144216](https://user-images.githubusercontent.com/46999859/51682356-8291a400-1fe7-11e9-9ed4-472a456f030f.jpg)
![wowscrnshot_012419_144217](https://user-images.githubusercontent.com/46999859/51682357-8291a400-1fe7-11e9-87d7-550e1e45707d.jpg)
![wowscrnshot_012419_144219](https://user-images.githubusercontent.com/46999859/51682358-8291a400-1fe7-11e9-9620-03dac9ff80f9.jpg)

**Comment by Asureuz** [comment]
Works correctly on the PTR, but on the live server this book is little bit bugged.
![image](https://user-images.githubusercontent.com/47954411/53340891-6a74b380-390a-11e9-95ec-eb9e1594b068.png) @Dootz

**Comment by Volarei** [comment]
Oh really? xD
