### ISSUE TITLE
Questline/Achievment - guru of drakuru (Betrayer)

### ISSUE THREAD

**Issue by SpectraQWERTY** [SunwellTracker/issues#218]
Decription: The quest is undoable in the current state and is beyond bugged with mutliple issues. 
How it works : 
Issue number 1 - the pet is uncontrollable (doesnt auto attack,doesnt move like a pet, can only use abilities if u physically move it to the boss)  : 
http://prntscr.com/i9y0f3

2 - Drakuru spams shadowbolts uncontrollably at some poiint

3- Quest is not doable in party / if someone is trying to do it upstairs sometimes, the boss teleports u up for a brief moment,than u get tped back down

4- even if u manage to kill it,the skull isnt lootable

How it should work: The pet should be perfectly controllable, the boss should nt spam shadowbolts, The quest should be completable in party without teleport bug, the skull should be lootable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
resolved
