### ISSUE TITLE
DK Can't pick up items when ghoul kill the monster

### ISSUE THREAD

**Issue by guud91** [SunwellTracker/issues#2181]
Decription: 
When ghoul kills a monster without DK attacking it, it can't be looted.

How it works: 
DK can't pick up loot from a monster killed by his pet

How it should work: 
DK should be able to pick up loot from a monster killed by his pet

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
That's how it works with all the pets.

**Comment by Akha72** [comment]
Yeah, if your pet is the sole damage dealer and slays a monster you get no credit for that.

**Comment by Azathothh** [comment]
Not a bug, player MUST do any dmg in order to be eligible for loot/xp.
For example if hunter will use Hunter's Mark on a mob and his pet will deal 100% of dmg to it - it won't be counted as if it was killed by pet owner.
