### ISSUE TITLE
[DALARAN] wow keeps crashing when using mount/fly

### ISSUE THREAD

**Issue by knullskallen** [SunwellTracker/issues#2183]
Decription: 
when ride mounts or fly with flights around dalaran, it crashes, sometimes several times within a minute

How it works: 
i dont do anything, maybe running or checking my inventory

How it should work: 
without crashing
[crash report.txt](https://github.com/SunwellTracker/issues/files/2800313/crash.report.txt)

Source (you should point out proofs of your report, please give us some source): i attached the crash report in a notepad here

**Comment by knullskallen** [comment]
another report
[crash report_1.txt](https://github.com/SunwellTracker/issues/files/2800337/crash.report_1.txt)

**Comment by Asureuz** [comment]
Hello,
If You're using Legion Model client version You can use LAA software. You can try solution in our forum
http://sunwell-community.com/index.php?/topic/5944-dalaran-crashes-solution-guide/&tab=comments#comment-16213
