### ISSUE TITLE
Master Elemental Shaper Krixix-NOT SPAWNS

### ISSUE THREAD

**Issue by Holydoomicus** [SunwellTracker/issues#2184]
Decription: 
In vanilla raid BWL after boss Firemaw must be a goblin called "Master Elemental Shaper Krixix"(https://www.wowhead.com/npc=14401)  with loot "Goblins guide to elementium" (https://www.wowhead.com/item=44956). But there isn't any mob!

How it works: 
In BWL you cant find and kill that mob in order to obtain mining book.His guards(3x dragons) are there,but he isn't.

How it should work: 
IMHO,he should stand there as it mentioned on Wowhead and other resources.
https://wowwiki.fandom.com/wiki/Master_Elemental_Shaper_Krixix
https://www.wowhead.com/npc=14401

Source (you should point out proofs of your report, please give us some source): 
As it SHOULD be: https://wow.zamimg.com/uploads/screenshots/normal/417950-master-elemental-shaper-krixix.jpg

- [ ]

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/51997865-e15b8f80-24b7-11e9-86e1-d2f2f65e461f.png)
He's there - maybe someone on your ID killed him before you were able to get there.
