### ISSUE TITLE
OLD HILSBRAD FOTHILS HEROIC

### ISSUE THREAD

**Issue by sensithc2** [SunwellTracker/issues#2188]
Decription: Hello, I did the Old Hilsbrad heroic yesterday, and it turned out that the first two barefoot gave me things from normal. I made a hero, today it was similar, I'm stuck on heroic 1 boss gave items from hero, 2 boss again gave item from normal, please fix it and unlock my id which I nabbed for a wasted, player of Sensithcc

How it works: Hello, I did the Old Hilsbrad heroic yesterday, and it turned out that the first two barefoot gave me things from normal. I made a hero, today it was similar, I'm stuck on heroic 1 boss gave items from hero, 2 boss again gave item from normal, please fix it and unlock my id which I nabbed for a wasted, player of Sensithcc

How it should work: Hello, I did the Old Hilsbrad heroic yesterday, and it turned out that the first two barefoot gave me things from normal. I made a hero, today it was similar, I'm stuck on heroic 1 boss gave items from hero, 2 boss again gave item from normal, please fix it and unlock my id which I nabbed for a wasted, player of Sensithcc

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, I belive this report refers to TBC. This bugtracker is for Wotlk. This issue has been resolved some time ago.
