### ISSUE TITLE
[Icecrown Citadel] Lord Marrowgar spikes 25 heroic

### ISSUE THREAD

**Issue by flappidyflap** [SunwellTracker/issues#2191]
Decription:   [Bone Spike Graveyard] (Heroic mode)—Hurls a massive bone spike which impales any enemies in the way. Deals 10% health per sec for 5 minutes or until killed. 3 sec cast. 5 min duration Puts the Impaled debuff on the affected player.

How it works: Summons 5 spikes.

How it should work: 
Must summpon 3 spikes.

Source (you should point out proofs of your report, please give us some source): https://youtu.be/fyl62Eg4P2g?t=52
You can clearly see he impales only  3 people. Same goes for every lord Marrowgar 25 heroic kill video on retail from 9 years ago.

**Comment by Cwiercpasiec** [comment]
It is custom buff, not a bug.
http://sunwell-community.com/index.php?/topic/6230-icecrown-citadel-25hc-boost/
