### ISSUE TITLE
Zul'Gurub boss "High Priest Thekal"

### ISSUE THREAD

**Issue by p6hmme55** [SunwellTracker/issues#2192]
Decription: High priest thekal doesn't phase.

How it works: 
You kill the boss and the NPC(Adds) at the same time and nothing happens, doesn't go to phase 2 where he respawns, this making him unkillable.

How it should work: 
When you kill both adds and boss at the same time, it phases into phase 2 where the boss respawns, when you kill him in his "final form" he the encounter ends, then you gain access to his loot-table.

Source (you should point out proofs of your report, please give us some source):

**Comment by Helliox** [comment]
If u kill the adds before the boss it should proceed to the second phase. When you get to that, the adds will respawn, which is also a bug.
