### ISSUE TITLE
[warrior][spell]Heroic Fury used shortly after casting Intercept

### ISSUE THREAD

**Issue by peanutcheese** [SunwellTracker/issues#2195]
Decription: 
I use this macro:
#showtooltip
/castsequence reset=2 Intercept, Heroic Fury
>I press it at an interval of 25ms
>It casts Intercept, then Heroic Fury
>I end up with Heroic Fury AND Intercept on cooldown, after having gone through the Intercept animation towards my target.

VIDEO: https://i.gyazo.com/d22919c802dccf67a03d9aa3a84eeb9c.mp4

How it should work: 
If I start to Intercept, it should go on cooldown the moment I start casting it. I should not be able to use Heroic Fury AFTER Intercept without resetting the Intercept cooldown.

Source (you should point out proofs of your report, please give us some source): 
common sense casting one spell after another

**Comment by peanutcheese** [comment]
Tried it at 50, 100ms too. Same effect.

**Comment by Asureuz** [comment]
Tested on PTR and I cannot reproduce this
https://streamable.com/vc8a1
Try to turn off all addons and check it once again. Make sure that You're using correct macro. 
Let me know when You will verify this.

**Comment by Asureuz** [comment]
Issue solved. If You're between 8-25y You can use intercept once again. 
Regards
