### ISSUE TITLE
Nightbane tbc, steamvault nagas has no abilities when mc'd

### ISSUE THREAD

**Issue by fidde9202** [SunwellTracker/issues#2197]
Decription: The coilfang engineer is supposed to have "bomb and net ability" the siren should have "fear, arcane flare and lightning bolt" the coilfang oracle "frost shock, heal and sonic burst" and coilfang warrior "battle shout, mortal blow and defensive stance"

How it works:  now when you mc they got no abilities and can only auto-attack making mindcontrol useless. It works in slave pens but not in steamvaults.

How it should work: The nagas should have their respective skills and be able to use them also when mc'd. I am linking wowhead proof below, and every other tbc database says the same, and the monsters are even using the abilities themselves. 

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/npc=17802/coilfang-warrior#abilities
https://www.wowhead.com/npc=17803/coilfang-oracle#abilities
https://www.wowhead.com/npc=17721/coilfang-engineer
https://www.wowhead.com/npc=17802/coilfang-warrior

**Comment by fidde9202** [comment]
On normal difficulty

**Comment by Asureuz** [comment]
Please report Your issue in the proper bugtracker. It's Angrathar realm bugtracker 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
Regards
