### ISSUE TITLE
Marrowgar - Coldflame damage taken while spiked

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#2198]
Decription: Coldflame damage while spiked

How it works: You take Coldflame damage while being spiked

How it should work: You shouldn't take damage from flames when on top of spike.

Source (you should point out proofs of your report, please give us some source): https://youtu.be/QzzXOAGYN3c?t=408

Pretty clear here. It's pretty insane how much of a RNG fiesta that boss becomes. I enjoy challenges but surely stacking 7-9 healers on an encounter isn't good tuning. Fix this bug and it might be somewhat less RNG tho.

**Comment by Asureuz** [comment]
Issue fixed.
Lord Marrowgar's Coldflame shouldn't hit targets that are currently on Bone Spike.
