### ISSUE TITLE
Can't learn tailoring/enchanting 240+ 

### ISSUE THREAD

**Issue by Nstyleds** [SunwellTracker/issues#2199]
![wowscrnshot_020719_054632](https://user-images.githubusercontent.com/47408970/52391084-deeecc00-2a9b-11e9-9645-75482e5f6c7b.jpg)
![wowscrnshot_020719_054649](https://user-images.githubusercontent.com/47408970/52391087-e1512600-2a9b-11e9-8d96-89fda0a76cde.jpg)

Decription: 
Was leveling my professions and suddenly realized that after 240 profession level the new recipes at NPS disappear

How it works: 
I check to buy new profession recipe and its disappearing 

How it should work: 
 I check it - I buy it

Source (you should point out proofs of your report, please give us some source):

**Comment by Nstyleds** [comment]
The same I would like to add about learning skills at Class Master, fix this please can't play.

**Comment by Asureuz** [comment]
Hello,
If You want to learn Enchanting proffesion on Master level You have to go the Outland locations (Hellfire Peninsula or Shattrath City). Additionaly level of Your character has to be at least 50.
Regards
