### ISSUE TITLE
Nagminne DC

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#22]
Witam od dłuższego czasu rozłącza mnie jak i innych graczy. DC z 2 razy na godzinę, podczas próby podnownego połączenia nie wpuszcza mnie na Feronisa ... 5 min musze czekac .  na nowy realm nie ma problemu . mozecie cos z tym zrobic bo na prawde jest to frustrujące ...

**Comment by Riztazz** [comment]
Rozwiazane
