### ISSUE TITLE
Bryntroll's Drain Soul proc 

### ISSUE THREAD

**Issue by Zerozorg** [SunwellTracker/issues#2200]
How it works: 
Doesnt proc off:
Pestilence
Both Icy Touch and Plague Strike disease apllication (pestilence too)

How it should work: 
Should proc off abilities i listed above or disease application to be exact

Source (you should point out proofs of your report, please give us some source): 
AJ 2010 forum posts discussing post nerf bryntroll
http://www.arenajunkies.com/topic/120683-bryntroll-vs-new-2200-weapon/page-3

wowhead comments
https://www.wowhead.com/item=50709/bryntroll-the-bone-arbiter#comments (literally first)
" The drain can proc off of the refreshing of some DoTs or debuffs so long as the character is within melee range of and facing the target for the drain. Specific to the deathknight class, the drain can proc off of the disease application of Icy Touch (assuming you are in melee range), can double-proc off Plague Strike (the strike and the disease application), and on each target that is in melee range and in front of you from Pestilence."

**Comment by Riztazz** [comment]
Sadly the way blizzard nerfed the weapon - it doesn't allow us to re-create pre-nerf state with current client files so this one cannot be fixed, closing
