### ISSUE TITLE
[Spell][Racial][Gnome] Escape Artist consistently not working under certain conditions.

### ISSUE THREAD

**Issue by peanutcheese** [SunwellTracker/issues#2202]
Decription: 
If the root is not the first debuff on the character, it cannot be dispelled by escape artist.

How it works: 
-druid use faerie fire, THEN entangling roots = it doesn't get dispelled by gnome racial
-druid use entangling roots without other debuffs = it gets dispelled
>this goes for ALL SPELLS AND EFFECTS DISPELLED BY ESCAPE ARTIST

How it should work: 
it should always dispell root effects, even if it's not the first in the line of debuffs

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
I tested this issue with different Entangling Roots ranks, but always Escape Artist removed Entangling Roots.
I casted Faerie Fire, then Entangling Roots.
https://streamable.com/4tk1y
