### ISSUE TITLE
Chilled to the Bones - sindragosa melee stacks 

### ISSUE THREAD

**Issue by smokeandnoob** [SunwellTracker/issues#2207]
Decription: So these stacks can get only melee characters,that works
https://imgur.com/qdeb6kr

How it works: There is problem with stacking because u can get immediately 6 stacks of this debuff from 1 divine storm and etc. spells

How it should work: It should work like you can get one stack and another stack not immediately next 5 or 6 

Source (you should point out proofs of your report, please give us some source): https://youtu.be/Cjx2A04OfCc?t=47s in the top right corner he has debuff meter or something like that and i dont see he gets immediately 6 stacks but one stack by one

**Comment by Chryslol** [comment]
Believe it's a paladin Seal problem.

**Comment by smokeandnoob** [comment]
But other melee classes has same problem for example like warrior one WW and gets 3 stacks,because there is some problem with % chance on getting stack.There should be only 20% chance to get stacks but it seems on this server there is like 40% chance on stack i guess 🤷‍♂️

**Comment by Riztazz** [comment]
Closing as it has been fixed, please re-report if there is any further issues (or write in this ticket even tho its closed)
