### ISSUE TITLE
[Quest] Zuluhed the whacked

### ISSUE THREAD

**Issue by tordhe** [SunwellTracker/issues#2208]
Decription: 
Zuluhed dont spawn right,

How it works: 
 I can /target Zuluhed for a sec before he disapears but cant see him. 

How it should work: 
should spawn where you get the Quest

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2038

I'll repeat myself:
This bugtracker is a place for Wotlk related bugs. In order to report bug found on Nightbane TBC realm please use our TBC Bugtracker : https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues
