### ISSUE TITLE
QUEST: "The Captive Prospectors"

### ISSUE THREAD

**Issue by Krallify** [SunwellTracker/issues#2209]
Description: You need to find a key and open cages to free NPCs. Its a quest in Grizzly Hills.

How it works: You get the key (the drop rate is pretty low, so its hard to find one), you open the cage, but the NPC is not moving out, so the quest can not be completed.

How it should work: https://www.youtube.com/watch?v=2hbsGrb65z0

Source (you should point out proofs of your report, please give us some source):

**Comment by Trauer1** [comment]
the quest is working. i finished it like 2 weeks ago or something.
