### ISSUE TITLE
Warrior: Intervene

### ISSUE THREAD

**Issue by FijayKing** [SunwellTracker/issues#221]
Decription: 
Intervene does not work on friendly players. Gives cooldown and no effect.

How it works: 
Currently it tosses skill on cooldown, and shows up as target is "Immune" when using it on a friendly player, no charge or anything. Player does not get the intervene buff either. Works as it should on Pets and Totems.

How it should work: 
Skill should make the warrior charge the friendly player targeted, and give the intervene buff grating 1 damage swing on the target to the warrior. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
What kind of auras did the target have? bop/bubble? No matter what i do, it always go thru - need more data

**Comment by FijayKing** [comment]
Tested on druid now without buffs it works as it should. When trying on a DK it does not

**Comment by FijayKing** [comment]
After another run in instance, it was possible to intervene the other players in the group that was not a DK. And I tested on frost and a blood DK , same problem it is not possible to intervene them because they are "immune".

**Comment by FijayKing** [comment]
here is a picture aswell of the problem

https://i.imgur.com/8TRjazK.jpg

**Comment by vedude** [comment]
Update.

You also can't intervene totems. Intervene goes off, however, nothing happens and you still stay the same position.

**Comment by Riztazz** [comment]
Yeah i know, this is quite hard to fix because it involves a lot of systems but i will look into it when i can find some time

**Comment by krolik115** [comment]
Same on #315 
This is Logs 
http://www.worldoflogs.com/reports/tema4nm9jn8bbkin/log/

**Comment by akrom23** [comment]
Look okay.
