### ISSUE TITLE
DK 4/5 T10 didn't work

### ISSUE THREAD

**Issue by Ketsuruis** [SunwellTracker/issues#2211]
Decription: When I use the "Rune Tap" skill I don'tt get a buff.
I don't know if he has any relationship but I also noticed that a few times the buff appeared, but it was random, I don't have a set head, but my friend dk has a set head and the buff always appears with him

How it works: I don'tt get a buff

How it should work: i should get a buff "Blood Tap" 

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
I checked this. I check set combination with and without tier head and always buff appeared. 
Probably You're using some UI addons and buff could not appear sometimes.
![wowscrnshot_022519_135409](https://user-images.githubusercontent.com/47954411/53338862-11565100-3905-11e9-9104-a63623dd6755.jpg)
![wowscrnshot_022519_135536](https://user-images.githubusercontent.com/47954411/53338874-161b0500-3905-11e9-9c22-ff678fa46bf7.jpg)
