### ISSUE TITLE
Still in combat while in dungeon

### ISSUE THREAD

**Issue by osmith93** [SunwellTracker/issues#2212]
Decription: 
Often, when in a dungeon after killing all mobs that had been pulled, you are still in combat and cannot drink/eat or stealth. This can be fixed by leaving the dungeon and rejoining.

How it works: 
Still in combat, although there are no mobs which are attacking.

How it should work: 
Once all pulled mobs are dead, combat mode should end.

**Comment by Asureuz** [comment]
Hello,
This problem appears in every dungeon or in the specified ones? 
Please tell details.

**Comment by osmith93** [comment]
I can only confirm the error in the Wailing Caverns and The Deadmines.

**Comment by Asureuz** [comment]
When You will be in combat all the time next time please create an ingame ticket. We'll check that.
