### ISSUE TITLE
I am stuck in pvp no matter what in Sunwell Angrathar

### ISSUE THREAD

**Issue by katya35** [SunwellTracker/issues#2215]
Decription: For the past 2 weeks, I have been stuck in pvp. No matter how long I have been toggled out, or how long I have been in Stormwind or any other capitol city. It is quite inconvenient because when we take the portal to sw from Dalaran, we are attacked by incoming and invading horde without the choice. 

How it works: Read the above. 

How it should work: I should be able to toggle out of pvp after 5 minutes of being in Stormwind. I should be able to take a portal and flight and be out of pvp. 

Source (you should point out proofs of your report, please give us some source): I submitted a ticket to a gm and was told to come here and tell you all about it.  Come to sw and see Prieta in full pvp all the time. It is a blast

**Comment by Akha72** [comment]
Are you sure you don't have any daily pvp quest in your log?

**Comment by katya35** [comment]
Even with no pvp quests. I finish them, leave Wintergrasp. Portal to SW and I can be there an hour and I am still in it. The same for my husband's toon
