### ISSUE TITLE
Intimidation

### ISSUE THREAD

**Issue by lulzi** [SunwellTracker/issues#2218]
Decription: The spell http://db.darkwizard.pl/?spell=19577 is not working as intented.

How it works: 
If u use the spell when the pet is not in range of the target,he will cast it on himself.

How it should work: 
U should be able to use the spell without stunning the pet(LOL).
Source (you should point out proofs of your report, please give us some source): From last Year https://www.youtube.com/watch?v=nP7gymCrx9I .

**Comment by Azathothh** [comment]
Couldn't reproduce - please record new video or add screenshot that show's how exactly it's bugging (with combatlog + timestamps in combatlog)

**Comment by Asureuz** [comment]
Hello,
This Youtube video is very old. Please give us some fresh proofs about this bug. 
I checked this in PTR and spell works correctly.
Regards
