### ISSUE TITLE
Issue with a quest in Dragonblight

### ISSUE THREAD

**Issue by Depressiapista** [SunwellTracker/issues#2219]
Hi! While levelling in Dragonblight I guess that I noticed a bug with a quest called "The focus on the beach".Whenever I get close to the destiny of that quest I get kicked from the server. I'm not sure if this happens because of my computer but I think that this shouldn't be the reason. 
 
Here is the video showing what happens:
https://youtu.be/8zi1ESHKjdw

**Comment by Dootz** [comment]
Hi, have you tried to disable your addons first? Please let me know if that helped.
