### ISSUE TITLE
Battle at Valhalas

### ISSUE THREAD

**Issue by Helligg** [SunwellTracker/issues#222]
Decription: 
Battle at Valhalas arena in icecrown. all the mobs should be immune to stun/fear cc. Makes it very easy such as it is now. 

How it works: 
Can stun, fear, slow etc. So kiting the mobs is possible, 

How it should work: 
Should have immunities. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Will be fixed with next update.
