### ISSUE TITLE
Priest cannot levitate over water

### ISSUE THREAD

**Issue by osmith93** [SunwellTracker/issues#2220]
Decription: 
When a priest uses levitate he cannot levitate over water.

How it works: 
When running into water while Levitate is activated the priest just starts swimming.

How it should work: 
The priest should levitate above the surface of the water.

**Comment by Asureuz** [comment]
Hello,
I tested Levitate spell in our PTR and works correctly. If You're in water You have to cast Levitate, then jump. 
https://streamable.com/przgk
https://streamable.com/logoq
