### ISSUE TITLE
Ephemeral snowflake bug

### ISSUE THREAD

**Issue by Monels** [SunwellTracker/issues#2221]
hi, I did the test in the register and by sending some healing skills the trinket is activated normally but as seen in the following pictures does not give the mana regeneration when some ticks of the skills heal, and it is much higher in some raid.
![wowscrnshot_022619_170140](https://user-images.githubusercontent.com/46604591/53453141-fe1cb180-39e8-11e9-9c97-89fe2c58b12f.jpg)
![wowscrnshot_022619_170151](https://user-images.githubusercontent.com/46604591/53453142-fe1cb180-39e8-11e9-804a-a7044c140f76.jpg)
![wowscrnshot_022619_170204](https://user-images.githubusercontent.com/46604591/53453143-feb54800-39e8-11e9-80de-581f72ffa1eb.jpg)

_Originally posted by @Monels in https://github.com/SunwellTracker/issues/issues/2149#issuecomment-467652751_

**Comment by Asureuz** [comment]
Hello,
After deeper research I can say that trinket works correctly. This trinket has ~0.4 sec internal cd (0.33 sec) between mana regen ticks. You can find some informations in wowhead comments.
