### ISSUE TITLE
Deathbringers will on feral druids

### ISSUE THREAD

**Issue by Chure3** [SunwellTracker/issues#2223]
Decription: 
I noticed that deathbringers will gives only 3 buffs to druid and one is wrong

How it works: 
it gives str/agi/haste

How it should work: 
it should give atp/agi/crit/haste

Source (you should point out proofs of your report, please give us some source):

**Comment by avarishd** [comment]
ahahahahahahhaahahahahahahahahahahahahahahhaahahahahahahahahahhaahahahahahahahah
I feel bad for the pug you stole the trinket from, what a waste ahahahahahahahahahahahahahahahah

**Comment by Soufly** [comment]
10 iq N word.

**Comment by Asureuz** [comment]
Hello, works correctly.
Regards
![image](https://user-images.githubusercontent.com/47954411/53684362-84e4cd80-3d0c-11e9-8d26-8996269e4af3.png)
