### ISSUE TITLE
Toc5 [ph] Generic Bunny appeared.

### ISSUE THREAD

**Issue by Warglaive** [SunwellTracker/issues#2226]
Decription: 
Toc5 [ph] Generic Bunny appeared.

How it works: 
--

How it should work: 
--

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/sUM82tM

**Comment by Warglaive** [comment]
That happened in TOC 5 Heroic via Random Dungeon Finder.

**Comment by Trauer1** [comment]
ur interface tho
