### ISSUE TITLE
The Hero's Brand 

### ISSUE THREAD

**Issue by Trauer1** [SunwellTracker/issues#2227]
Decription:  cant get the quest even after reaching Exalted with the Zandalari Tribe.

How it works:  hit exalted > cant get the last quest for the epic necklace

How it should work: hit exalted > get a quest from a dude > get the set item

Source (you should point out proofs of your report, please give us some source): 
https://classicdb.ch/?quest=8048
https://www.wowhead.com/quest=8048/the-heros-brand
https://wowwiki.fandom.com/wiki/Quest:The_Hero%27s_Brand

**Comment by Asureuz** [comment]
Fixed, for next server update quest will be available for all paladin's races.
