### ISSUE TITLE
Hunter's Pet scale

### ISSUE THREAD

**Issue by sildori** [SunwellTracker/issues#2228]
Decription:  Hunter's Pet attack Power doesn't scale with hunter's attack power

How it works:  When changing aspect: viper to hawk for example. My attack power change, pet's attack power stays same.

How it should work:  Pet should scale with hunter's attack power regardless of source that changes it.

Source (you should point out proofs of your report, please give us some source):

**Comment by peterjot** [comment]
With aspect:
![image](https://user-images.githubusercontent.com/28165544/58125524-0fa0de80-7c11-11e9-8165-0c057b6345f9.png)

Without aspect (pet has less AP):
![image](https://user-images.githubusercontent.com/28165544/58125555-1b8ca080-7c11-11e9-887e-df2818a06262.png)

**Comment by peterjot** [comment]
I think that scaling working properly

Pet`s AP with Aspect of the Viper:
![image](https://user-images.githubusercontent.com/28165544/58125756-9d7cc980-7c11-11e9-96e1-cfc7f8231024.png)

Pet`s AP with Aspect of the Hawk:
![image](https://user-images.githubusercontent.com/28165544/58125784-b4232080-7c11-11e9-9d87-938a1eae0e0d.png)
