### ISSUE TITLE
missing character from the market

### ISSUE THREAD

**Issue by angel190789** [SunwellTracker/issues#2229]
Decription: 
Missing character

How it works: 

How it should work: 

Hello . I put my character on the black market. level forgot either 64 or 65.class druid game nick Feralkitty for 120 coins. confirmed that sell and the character disappeared from the account. on the black market, he did not appear and disappeared from the account. when I go to account it shows that there are 1 character , but it is not. please help me with this problem
Source (you should point out proofs of your report, please give us some source):

**Comment by angel190789** [comment]
Hello . I put my character on the black market. level forgot either 64 or 65.class druid game nick Feralkitty for 120 coins. confirmed that sell and the character disappeared from the account. on the black market, he did not appear and disappeared from the account. when I go to account it shows that there are 1 character , but it is not. please help me with this problem

**Comment by Asureuz** [comment]
Hello,
Please write a DM to Raphael in our Discord channel.
https://discord.gg/KN8TmfS
Regards
