### ISSUE TITLE
LIGHTWELL UNCLICKABLE *IMPORTANT NOTICE/UPDATE ADDED"

### ISSUE THREAD

**Issue by Hyesunee** [SunwellTracker/issues#223]
IMPORTANT NOTICE/UPDATE: I'VE LEARNED RANK 1 LIGHTWELL AND RANK 2 LIGHTWELL SO FAR, RANK 1 SEEMS 100% FINE WHICH IS VERY STRANGE WHY I'VE HAD TO MAKE THIS BUG REPORT BUT IT'S ATM SPECIFICALLY FOR LIGHTWELL RANK 2, IF SUNWELL STAFF TAKES THIS ABILITY UNDER TESTING PLEASE TEST ALL RANKS OF LIGHTWELL THEREFORE.

Decription: 
As the title states, since today Isuddenly couldn't spam click Lightwell anymore and I was limited to only taking 1 charge or 2 charges at times for a full duration of Lightwell's uptime, like fellow party members who were also able to spam click it the day before, and you should be able to, you should be able to use up all 10 charges (rank2 atm) individually but now we can't anymore. This can be a great key ability to Holy priests in PvE content and therefore I hope this issue gets solved with great urgency.

How it works: 
Can only take 1 or 2 charges individually while there should be 10 available. Becomes unclickable at random times.

How it should work: 
Should ALWAYS be clickable and everyone should be able to take charges till Lightwell is gone.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=8AFW80sgB0g

**Comment by Hyesunee** [comment]
IMPORTANT NOTICE/UPDATE: I'VE LEARNED RANK 1 LIGHTWELL AND RANK 2 LIGHTWELL SO FAR, RANK 1 SEEMS 100% FINE WHICH IS VERY STRANGE WHY I'VE HAD TO MAKE THIS BUG REPORT BUT IT'S ATM SPECIFICALLY FOR LIGHTWELL RANK 2, IF SUNWELL STAFF TAKES THIS ABILITY UNDER TESTING PLEASE TEST ALL RANKS OF LIGHTWELL THEREFORE.

**Comment by Hyesunee** [comment]
Rank 3 Lightwell also not working accordingly.

**Comment by kacak0** [comment]
Rank 6 can't be clicked twice by same person in a row.
