### ISSUE TITLE
Blackmarket no Char

### ISSUE THREAD

**Issue by mr0donald** [SunwellTracker/issues#2230]
Decription: I bought 2 days ago a warrior called Gurke lvl 20 Dreanei. He disapeared on the previous account but is not on the new one. Help

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello, please write a DM to Raphael in our Discord. 
https://discord.gg/KN8TmfS
Regards
