### ISSUE TITLE
Seal of Vengeance/Corruption with Crusader Strike 

### ISSUE THREAD

**Issue by smokeandnoob** [SunwellTracker/issues#2231]
Decription: 
So there is problem with stacking seal of vengeance or corruption with crusader strike

How it works: 
Now it works like crusader strike isn't counted like instant weapon attack. So if you want to have fast 5 stacks you have to switch to fastest one hand in game  https://www.youtube.com/watch?v=oL_bT70xJcs&feature=youtu.be

How it should work: 
Crusader strike is counted like instant melee attack with weapon and should stacks another dot of SoV/C

Source (you should point out proofs of your report, please give us some source): https://wotlk-twinhead.twinstar.cz/?spell=71549

**Comment by Asureuz** [comment]
Tested on PTR and works correctly.
Proof:
![image](https://user-images.githubusercontent.com/47954411/53792948-2f3b3b80-3f2d-11e9-88ca-8a53a58befec.png)
I used simple macro:
/cast Crusader Strike
/stopattack
Because I didn't want to attack by using auto-attack.

**Comment by Asureuz** [comment]
![image](https://user-images.githubusercontent.com/47954411/53793287-d6b86e00-3f2d-11e9-8f7b-97345bc48c92.png)
