### ISSUE TITLE
Incorrect stats numbers

### ISSUE THREAD

**Issue by KuroiMatoO** [SunwellTracker/issues#2233]
Well, it's almost not worth mentioning but I got loot from random dungeon bag and noticed that numbers are wrong. In the item description it says it gives +6 to stamina but in fact it gives +10. That's it.
![image](https://user-images.githubusercontent.com/2721793/53921965-98cd5e00-4083-11e9-8420-427f0ed49f4a.png)
![image](https://user-images.githubusercontent.com/2721793/53921975-9ec33f00-4083-11e9-8145-835dbebac90b.png)

edit: another one??? Why damage decreasing???
![image](https://user-images.githubusercontent.com/2721793/54127818-bef45480-441b-11e9-919d-2416b1c2643a.png)
![image](https://user-images.githubusercontent.com/2721793/54127840-c582cc00-441b-11e9-9e2f-c780bdd15f22.png)

**Comment by KuroiMatoO** [comment]
Hmmmmm, next item too
![image](https://user-images.githubusercontent.com/2721793/53922528-cadfbf80-4085-11e9-82ae-d3542d03cd63.png)
![image](https://user-images.githubusercontent.com/2721793/53922535-d337fa80-4085-11e9-94e1-48570adf1e87.png)

**Comment by Asureuz** [comment]
Hello, try to turn off all addons and check once again.
Regards

**Comment by KuroiMatoO** [comment]
Oh, damn, sorry I'm already sold these items, I'll report here if I find another
