### ISSUE TITLE
[Q] Rescue from Town Square

### ISSUE THREAD

**Issue by TrueNargin** [SunwellTracker/issues#2234]
Decription: This quests requires you to rescue 6 NPCs from the town square next to Wintergarde Keep.
How it works: Every rescue counts as 2.
How it should work: Every rescue should count as 1.
Source (you should point out proofs of your report, please give us some source):  http://www.wowhead.com/quest=12253/rescue-from-town-square

**Comment by Asureuz** [comment]
*Additionally, killing npc Vengeful Geist (id 27370) provides quest credits.
Player should get quest credit only while killing Vengeful Geist which is NEAREST to the Trapped Wintergarde Villager

**Comment by Asureuz** [comment]
Proof:
https://www.youtube.com/watch?v=d6-MbLka1wg
