### ISSUE TITLE
RDF Satchel is empty

### ISSUE THREAD

**Issue by michael1358** [SunwellTracker/issues#2238]
Decription: 

Affected levels: 66-67
Inventory status was NOT full.

How it works: 

Opening the satchel rewarded nothing.

How it should work: 

There should be a rare item inside.

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
I opened 100 [Satchel of Helpful Goods] on PTR and every had 1 item inside. Make sure that You didn't sell item or delete. Additionaly, turn off all addons and check Your bags.
Regards

**Comment by Azathothh** [comment]
Actually there is a bug - 52005 - [Satchel of Helpful Goods] are sometimes empty. 
Other satchels are probably fine, this one isn't - players on level 65 and above can receive it by completing Random Dungeon in Dungeon Finder tool.
Checked on rogue and mage.
