### ISSUE TITLE
Blizzard doesnt slow

### ISSUE THREAD

**Issue by hyxgod** [SunwellTracker/issues#2240]
Decription: 
Blizzard doesnt slow on first tick

How it works: 
When blizzard hits a target he gets the debuff but no slow. first tick of the blizzard doesnt make slow debuff which causes me crazy, if some1 is running with sprint etc u cant hit them with the slow but it hits the out of stealth and they get debuff its fkn retarded please fix it

How it should work: 
^^^^^^^ ^^^^^^

Source (you should point out proofs of your report, please give us some source):

**Comment by Asureuz** [comment]
Hello,
I tested on the PTR and Blizzard works correct, make sure that You have [Improved Blizzard] https://wotlk.evowow.com/?spell=12488 in Your talen tree. Slow debuff was applied while frist damage tick of Blizzard spell.
Regards
