### ISSUE TITLE
[REOPEN] Shadowmourne proc doesn't work on arenas

### ISSUE THREAD

**Issue by Vanquis** [SunwellTracker/issues#2241]
Decription: 
I'm a ret paladin with SM. Problem as in the title. There is no shadowmourne proc while playing arenas (no sould shards, no chaos bane).

How it works: 
No SM proc on arena.

How it should work: 
According to forum information (http://sunwell-community.com/index.php?/topic/5891-arena-season-8-season-7-rewards/&tab=comments#comment-16052) shadowmourne should work on arenas during this first wrathful season. 

Source (you should point out proofs of your report, please give us some source):

**Comment by fak3frame** [comment]
"In the first Wrathful Season, Shadowmourne will be useable in arenas. "
~sry we disabled it now, our mistake, we'll fix this 1 day before next season and disable again, cheers!
-GMs playin arenas

**Comment by Vanquis** [comment]
Shadowmourne still doesn't work on arenas (date when tested - 13.03.2019, 19:15) . Please reopen the issue.

**Comment by Dootz** [comment]
Hi, it seems that realm was not updated yet. Sorry for confusion.

**Comment by fak3frame** [comment]
when it will be fixed?

**Comment by Asureuz** [comment]
@fak3frame Shadowmourne was enabled and should works correct on all arenas. 
Fixed was applied to the live server 12/03/2019 please check it while arena battle.
