### ISSUE TITLE
Intervene and Blink on Lich King (or in general)

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#2246]
Decription: Currently there's an issue with Blink / Intercept where you do not need a "path" to actually do the move. 

How it works: You shouldn't be able to use Blink / Intercept if there is no path available. Currently you can get dragged by the Val'kyr to the outside of the Platform and then Blink or Intervene back onto it. Will make Lich King Heroic easier if abused (which it will be). 

How it should work: Blink should be useable but it shouldn't make you go onto the platform. Intervene shouldn't work when you are falling down from the sky. 
 

Source (you should point out proofs of your report, please give us some source): If this was the case you would see videos of it in wotlk.

**Comment by XDDDDDDDDDDDDDD11121121211** [comment]
https://www.youtube.com/watch?v=SVqP2iUi1-8

me seeing mage blinking idk about u

**Comment by lkrocek** [comment]
agree with @XDDDDDDDDDDDDDD11121121211  It works but you are turned about 180deg you should turn around before blink/intervene.

**Comment by Chryslol** [comment]
@XDDDDDDDDDDDDDD11121121211 that guy blinked ~max 5 yards. On this server you can blink full range of the blink and hit the platform if it's infront of you.

**Comment by XDDDDDDDDDDDDDD11121121211** [comment]
in your opinion it shouldn't work at all soooooooooooo

**Comment by Zerf** [comment]
Charge, Intercept, Intervene have always worked without a path, as long as there's nothing in-between you and the target (easiest example - jump off a cliff and charge a mob while falling - there is no path, yet you can still charge).
As for blink, it doesn't require a path either, but idk how far in air you are supposed to teleport. "If this was the case you would see videos of it in wotlk" is not proof on **how exactly** it should work.

**Comment by Chryslol** [comment]
Should apparently work! Thanks for feedback.
