### ISSUE TITLE
[Q] [It Rolls Downhill]

### ISSUE THREAD

**Issue by WeedCatX** [SunwellTracker/issues#2248]
Decription: 
They just won't collect the crystals after scepter is used.

How it works: 

How it should work: 
https://www.wowhead.com/quest=12673/it-rolls-downhill

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
They doesn't collect them on their own - you have to use skill on pet bar to collect the crystals. Did you try to use this skill and nothing happened? (If you're playing warlock or hunter dismiss your pet before controlling Geist)

**Comment by WeedCatX** [comment]
There was no pet bar, -as a priest. First time posting stuffs here sorry.

**Comment by Azathothh** [comment]
Please try disabling all your addons and check again - maybe one of them disabled pet bar for you.
I'm closing this issue because quest is working - if you'll still have problem with doing it - please open in-game ticket and GMs will help you.
