### ISSUE TITLE
[Quest] Howling Fjord, "Help for Camp Winterhoof" ID: 12566

### ISSUE THREAD

**Issue by Bel-WOW** [SunwellTracker/issues#225]
Decription: 
Brak możliwości otrzymania quest "Help for Camp Winterhoof" ID: 12566 w Howling Fjord od NPC "Longrunner Nanik" x: 71,5; y: 39.2, mimo spełnienia wymagań. Raczej nie jest to chain quest, ale nawet jeżeli to wykonałem wszystkie inne questy w tej lokacji i wciąż jest zablokowany. Jeden z komentarzy na WoWHead, twierdzi, że rzekomo wykonanie innego questa w tej lokacji blokuje możliwość otrzymania tego (nie wybór, bug), jednak czy tak faktycznie jest - nie mam jak potwierdzić, chociaż sytuacja w jakiej jestem skłania mnie ku temu, że tak może być faktycznie. Ten komentarz, mimo że stary to jedyna informacja w sprawie problemów z tym questem jaką udało mi się znaleźć.

How it works: 
NPC nie daje questa.

How it should work: 
NPC powinien oferować questa.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12566/help-for-camp-winterhoof (wspomniany komentarz)

![wowscrnshot_020418_141348](https://user-images.githubusercontent.com/36129798/35781474-d24ec748-09ea-11e8-9c9a-b89e1ef396d0.jpg)
![wowscrnshot_020418_141410](https://user-images.githubusercontent.com/36129798/35781477-d8cbbd6a-09ea-11e8-88c2-47d842e818ad.jpg)

**Comment by Dootz** [comment]
Wykonanie questa http://www.wowhead.com/quest=11411/camp-winterhoof blokuje możliwość otrzymania http://www.wowhead.com/quest=12566/help-for-camp-winterhoof .
Oba questy są początkowo dostępne bez żadnych specjalnych wymagań
