### ISSUE TITLE
Crusader Strike and Divine Storm vs Anti Magic Shell

### ISSUE THREAD

**Issue by Vanquis** [SunwellTracker/issues#2251]
**Decription:** 
DK spell "Anti magic shell" blocks Ret Paladins Crusader Strike and Divine Storm damage. The damage shouldn't be blocked.

**How it works:** 
DK spell "Anti magic shell" blocks Ret Paladins Crusader Strike and Divine Storm damage. 

**How it should work:** 
The damage shouldn't be blocked. Both Divine Storm and Crusader Strike have physical damage and are affected by armor. AMS shouldn't block physical damage.

**Source (you should point out proofs of your report, please give us some source):**

Crusader strike wowwiki page from wotlk time:
https://wowwiki.fandom.com/wiki/Crusader_Strike?oldid=2410760
Pure physical, AMS should not absorb the damage.

Divine storm wowwiki page from wotlk time:
https://wowwiki.fandom.com/wiki/Divine_Storm?oldid=2366081

**Quote:** "The original skill dealt holy damage, but shortly after patch 3.0.2 went live, the PvP community called for Retribution Paladin's burst to be toned down, as a result, this spell was changed to deal physical damage, along with other changes, such as the removal of all critical strike damage increasing talents from the talent tree. "
Hence before patch 3.0.2 it WAS absorbed by AMS, but NOT affected by armor. After patch 3.0.2 it was affected by armor but AMS should not absorb the damage.

AMS wowwiki page from wotlk time:
https://wowwiki.fandom.com/wiki/Anti-Magic_Shell?oldid=2412407
It should absorb magic only.

**Comment by Asureuz** [comment]
Hello,
Tested on the PTR and seems to work correct. Make sure that Holy DMG from Your Seal buff isn't reduce by AMS.
![image](https://user-images.githubusercontent.com/47954411/54611198-cab4cc00-4a56-11e9-921a-dc076fa0cab6.png)
![image](https://user-images.githubusercontent.com/47954411/54611269-e7e99a80-4a56-11e9-8753-e8a5722bd564.png)
