### ISSUE TITLE
Death Gate Spell Missing

### ISSUE THREAD

**Issue by vipozel** [SunwellTracker/issues#2253]
Decription: 

Death Gate Spell Missing
How it works: 

İ cant find Death Gate Spell.
How it should work: 
it is in unholly spell.

Source (you should point out proofs of your report, please give us some source): 
 I am 60 level DK player name is "Urasto" . I cant my unholly spell " Death Gate" Is it a bug? I tried
![WoWScrnShot_031919_110558](https://user-images.githubusercontent.com/48711104/54589602-22dbd600-4a37-11e9-9519-544b6915293d.jpg)
 disable all Add-ons. I cant fix the problem. Please help me.

**Comment by Asureuz** [comment]
Hello,
Death Gate spell is reward from the https://db.darkwizard.pl/?quest=12801 [The Light of Dawn] quest, if You didn't get this spell You probably didn't complete final quest in DK chain.
Regards
