### ISSUE TITLE
water elemental vs mirror image

### ISSUE THREAD

**Issue by tourisover** [SunwellTracker/issues#2255]
Decription: summoning mirror image when water elemental is active

How it works: when i summon mirror image with already active water elemental, the elemental dissapears and i summon only 2 images instead of 3. This doesnt happend in the opposite summon order.

How it should work: mirror image shouldnt dissmis my water elemental

Source (you should point out proofs of your report, please give us some source):

**Comment by FilipiBrabo** [comment]
Also happening to me. As he said the inverse order is fine.
Proofs:
Before water elly cast:
![1](https://user-images.githubusercontent.com/33284760/57957649-5de17500-78d3-11e9-9356-b83732d011f3.jpg)

After water elly cast:
![2](https://user-images.githubusercontent.com/33284760/57957650-5de17500-78d3-11e9-9e95-1ef9628051d0.jpg)

Before MI cast:
![3](https://user-images.githubusercontent.com/33284760/57957651-5e7a0b80-78d3-11e9-9cd2-d985cd93e0c5.jpg)

After MI cast (As you can see, the pet is fading out and only 2 MI are summoned):
![4](https://user-images.githubusercontent.com/33284760/57957652-5e7a0b80-78d3-11e9-9867-99a805553568.jpg)

**Comment by Azathothh** [comment]
Like mentioned above - happens only when Water Elemental is summoned first also it does happen only when Water Elemental is temp summon - if we have perm Water Elemental (with Glyph of Eternal Water) everything works fine, no matter if we summon elemental>mirrors  or mirrors>elemental.
