### ISSUE TITLE
[Quest] Frankly, It Makes No Sense...

### ISSUE THREAD

**Issue by ethuath** [SunwellTracker/issues#2258]
Decription: The quest requires a player to use an device called an Arcano Control Unit (Shadowmoon Valley 62,40), to take control over Arcano-Scorp so a player can use it to "tag" 8 Diemetradons walking in the lava.

How it works: When you click on the device, it shows that you took control of the Arcano-Scorp, but actually you didn't because your character just dances around and none of the bars which should show the Arcano-Scorp skill show.

How it should work: When a player uses the Arcano Control Unit, he should take control of the Arcano-Scorp and be able to tag the Diemetradons with one of the Scorp's skill.

https://youtu.be/JbiBXev9YGk?t=121 <- this is how the quest should be done and how should it work.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/quest=10672/frankly-it-makes-no-sense

**Comment by Azathothh** [comment]
Looks like it's bugging out when someone abandon Arcano-Scorp far from Arcano Control Unit - Arcano-scorps have problem with resetting properly. You can write a ticket and GM will reset it, but yeah, it shouldn't be like that.

**Comment by ethuath** [comment]
I did that. GMs told me to write about it on the BugTracker, so I did.
