### ISSUE TITLE
leveling up while dead in dungeons bugs your character

### ISSUE THREAD

**Issue by pullovesi** [SunwellTracker/issues#226]
Description: leveling up while dead in dungeons bugs your character

How it works: Not entirely sure if it does this all the time, but my friend and I were doing SFK and my friend died on Arugal. We managed to kill the boss and my friend got enough xp for him to level up. He leveled up while being dead, got all his HP back up and he stood up as if he was alive but he couldn't move. He left the dungeon group and teleported back to SW where he could move and appeared to be fine but he couldnt do certain actions and the error msg said "You can't do that when you're dead" so he had to relog for everything to be fine. 

How it should work: you shouldn't magically come back to life all bugged af by leveling up when you're dead. :D

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
#187
