### ISSUE TITLE
Sudden Death Talent (Warrior)

### ISSUE THREAD

**Issue by Styffler** [SunwellTracker/issues#2262]
Decription: 
Sudden Death Talent (Warrior), Using Execution for 10 seconds no matter target's life.

How it works: 
When it procs u can use Execute but some of the hits doesnt do any damage and doesnt miss as well when u check combat log and players lose Global Cooldown which is a huge problem.

How it should work: 
It should hit the target every time u use it

Source (you should point out proofs of your report, please give us some source): I hit some mobs when it procs and sometimes when i use Execute nothing happens..looked and my log and I havent misses or do any damage like i didnt use it but actually i did and had Global Cooldown for nothing...

**Comment by Azathothh** [comment]
I've done some tests and it appears that Execute is working properly.
Problem is in combat log - for some reason it can show successful Execute attacks, but doesn't show any info about Executes which missed/dodged/parried.

If you've used Execute and it didn't do any damage + there's no info in combat log about it - it means that it missed or was dodged/parried.

**Comment by Riztazz** [comment]
Should be fixed with next realm update
