### ISSUE TITLE
Touch of zanzil

### ISSUE THREAD

**Issue by syk7** [SunwellTracker/issues#2263]
Description: Touch of zanzil doesn't prevent stealth

How it works: Can stealth while it's active
![zxcbxxd](https://user-images.githubusercontent.com/46019956/55220456-9f28a300-5207-11e9-88c5-666bb4b68e0b.png)

How it should work: The debuff shouldn't let you stealth

Source (you should point out proofs of your report, please give us some source): https://db.darkwizard.pl/?spell=9991#reward-from-quest

**Comment by Riztazz** [comment]
Fixed, will be live with next realm update
