### ISSUE TITLE
Wintergrasp Cannons (It gives you rank)

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#2266]
Decription: 
Hello! First of all i reported this bug because i have to, i hate when Wintergrasp it's bugged.
When you going to kill 1 cannon and you have rank 1 (Recruit) and cannon are down, you will have Recruit but it gives you 1 kill at rank 1 (Recruit) "4 more untill you get Corporal, not 5". Apparently cannons are giving you 1 kill. It should give you only on NPC, members of Alliance/Horde. You get rank 3 (First Lieutenant) in 1-2 mins..

How it works: 
I have Rank 1 (Recruit), and i'm going to destroy 1 cannon, i will get 1 kill. What's that suppose to mean? Well, you have to kill 5 Members of Horde/Alliance to get Rank 2 (Corporal), but if you kill 1 cannon you need to kill only 4 Members of Horde/Alliance, so it gives you 1 kill.
Here is a screenshot:
https://imgur.com/a/ZZCl76r (The 2nd screenshot, look at it, i have Corporal and 5 stack. When i kill cannon "first screenshot" i am on First Lieutenant, how?? It should not give you 1 stack, only Members/NPC of Alliance or Horde..

How it should work: 
It should not give stack, only Members/NPC of Alliance/Horde you need to kill to gain Rank, not cannons..

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Wintergrasp#cite_note-2

**Comment by Azathothh** [comment]
"After killing five enemy players, **defensive cannons** or NPC guards during a Wintergrasp match, you are given the rank of Corporal." that's from the source link that you've posted.

Please provide some proofs that it should work like you're saying.

**Comment by Riztazz** [comment]
No data for over a week, closing. Please open another issue with proofs
