### ISSUE TITLE
Wintergrasp Workshops not working perfectly

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#2268]
Decription: 
Hello! Workshops are bugged and it still remain when the next battle starts again. Let me explain a little bit.
If Alliance or Horde has all Workshops (Eastpark, Westpark, Sunken and Broken) and when the battle starts, Horde or Alliance starts with 0/0 vehicles, and they need to capture the workshops, but it's not suppose to be like that (it's not fair), it should be like this:

When Alliance Control the Keep! : 
1. Sunken Ring and Broken Temple should be on Alliance side.
2. Eastpark and Westpark Workshops should be on Horde side.

When Horde Control the Keep! : 
1. Sunken Ring and Broken Temple should be on Horde side.
2. Eastpark and Westpark Workshop should be on Alliance side.

How it works: 
Workshops are bugged and it still remain when the next battle starts again. Let me explain a little bit.
If Alliance or Horde has all Workshops (Eastpark, Westpark, Sunken and Broken) and the battle starts, Horde or Alliance starts with 0/0 vehicles, and they need to capture the workshops. (which is not fair for the opposite side "Horde or Alliance side".

How it should work:

When Alliance Control the Keep! : 
1. Sunken Ring and Broken Temple should be on Alliance side.
2. Eastpark and Westpark Workshops should be on Horde side.

When Horde Control the Keep! : 
1. Sunken Ring and Broken Temple should be on Horde side.
2. Eastpark and Westpark Workshop should be on Alliance side.

Source (you should point out proofs of your report, please give us some source):
https://www.youtube.com/watch?v=QrHjqrEBjpw  (this is on official server, i hope it's a good one). If not, i will make a video about that, and you will see. :)

Make Wintergrasp great again.

**Comment by alexandruu58** [comment]
https://www.youtube.com/watch?v=TWs4RPNtJHg&feature=share

Here as you can see when battle starts workshops resets, for example
When Alliance control it, Broken Temple, Sunken Ring on Horde side!
Eastpark and Westpark workshop on Alliance side. When almost the battle start he just looked on the map, dont forget to pause the video to see who control Workshops.. :)
It should work like this video! ;)
