### ISSUE TITLE
Mograine Bug In Scarlet Cathedral dungeon

### ISSUE THREAD

**Issue by Anik23** [SunwellTracker/issues#227]
Decription: After troll mograine a little with polymorph and mind control and kill him,let the other boss ress him and try to kill him again he became unkillable with 1 HP left. You can get the achivment and end the dungeon since is the girl who gives it but this is a little buggy.

How it works: You have to spam polys and mind controls on Mograine during the fight i think that caused the bug making him unkillable like a orgrimmar dummy.

How it should work: Mograine should die.

Source (you should point out proofs of your report, please give us some source): 

Several screnshots of mograine being kited after some people left the dungeon.

![wowscrnshot_020418_203546](https://user-images.githubusercontent.com/36137943/35781767-c4356d2a-09ee-11e8-8c0a-089125907d85.jpg)
![wowscrnshot_020418_203536](https://user-images.githubusercontent.com/36137943/35781768-c44e1d66-09ee-11e8-9f44-da8a524869e6.jpg)
![wowscrnshot_020418_203535](https://user-images.githubusercontent.com/36137943/35781769-c467048e-09ee-11e8-8471-f214df227f49.jpg)
![wowscrnshot_020418_203533](https://user-images.githubusercontent.com/36137943/35781770-c48063b6-09ee-11e8-81b6-abb7b6b42d66.jpg)
![wowscrnshot_020418_203531](https://user-images.githubusercontent.com/36137943/35781771-c499268a-09ee-11e8-988f-2e448d0b7a00.jpg)
![wowscrnshot_020418_203516](https://user-images.githubusercontent.com/36137943/35781772-c4b19062-09ee-11e8-8292-db6900832d71.jpg)
![wowscrnshot_020418_203226](https://user-images.githubusercontent.com/36137943/35781774-c4ca38e2-09ee-11e8-898f-b5361b67e6bb.jpg)
![wowscrnshot_020418_203219](https://user-images.githubusercontent.com/36137943/35781775-c4e2f4cc-09ee-11e8-9bea-b8ba3247dd07.jpg)
![wowscrnshot_020418_203213](https://user-images.githubusercontent.com/36137943/35781776-c4fcbb82-09ee-11e8-881f-63b4c90e82e3.jpg)
![wowscrnshot_020418_203208](https://user-images.githubusercontent.com/36137943/35781777-c515dde2-09ee-11e8-9716-de0593db2d7c.jpg)

**Comment by Anik23** [comment]
?

**Comment by Dootz** [comment]
will be fixed with next server update
