### ISSUE TITLE
Wintergrasp Workshops should be Grey (Message attack)

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#2270]
Decription: 
Hello there! This is the last bug in Wintergrasp. Actually if you want to capture a workshop, for example Sunken Ring. The message will say in chat:
"The Sunken Ring has been attacked by the Horde"
Alliance can still revive on Sunken Ring untill Horde will capture it. The Workshop should be grey, not blue. Same as Alliance, if they want to capture it the workshop will be red untill Alliance capture it, so Horde will revive there, when Workshop is on Alliance, Horde doesn't revive there anymore, but the workshop should be grey when the message appeared on the chat.

How it works: 
Actually if you want to capture a workshop, for example Sunken Ring. The message will say in chat:
"The Sunken Ring has been attacked by the Horde"
Alliance can still revive on Sunken Ring untill Horde will capture it. The Workshop should be grey, not blue. Same as Alliance, if they want to capture it the workshop will be red untill Alliance capture it, so Horde will revive there, when Workshop is on Alliance, Horde doesn't revive there anymore, but the workshop should be grey when the message appeared on the chat.

How it should work: 
Me (Alliance) i'm going to Sunken Ring workshop the message will appear on chat "The Sunken Ring has been attacked by the Alliance", when the message will appear the workshop should be grey because Horde can still revive on Sunken Ring, this is not fair at all. If im going to kill a horde on that workshop he is not allowed to revive on Sunken Ring, he should revive on the other Workshop (the other workshop controlled).
If that player wants to take the Workshop back and i didn't captured it, the base will be on Horde (which means it should be red color).
Viceversa Horde/Alliance.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/LEVkJwd

I don't have any Source, but i think this screenshot will be enough for you, anywaym you can actually come in Wintergrasp (you, Developer) to see how is it going on.

I hope you will fix all bugs in Wintergrasp, i hope...

Make Wintergrasp great again! ;)

**Comment by Piootrek** [comment]
According to this video it's blizzlike
https://youtu.be/1rtuG7ZeZ3Y?t=80

**Comment by Piootrek** [comment]
According to this video https://youtu.be/d3UclH6BAdw?t=166 it's blizzlike. Video is from patch 8.1.5, but I believe it worked in same way on WotLK.
