### ISSUE TITLE
Wintergrasp Quests Daily

### ISSUE THREAD

**Issue by alexandru58** [SunwellTracker/issues#2272]
Decription: 
Hello! Quests should be daily, but are weekly..

How it works: 
The quests resets every Friday as i remember, but those quests are weekly, it should be daily.

How it should work: 
All quests should be daily, not weekly quests.

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Wintergrasp_quests

Patch 3.2.2 (2009-09-22): No longer resets every five days and becomes daily again.

Make WG great again. Thanks!

**Comment by Rastlinek** [comment]
Its fake, wowwiki any1 can edit, look what i edit in patch notes https://wowwiki.fandom.com/wiki/Patch_3.2.2 before was "All quests should be daily, not weekly quests" here u got orginal patch notes http://us.battle.net/wow/en/game/patch-notes/3-2-2 and is no way that WG quest are daily and i played on global to cata and im sure was weekly.
