### ISSUE TITLE
Black Battlestrider

### ISSUE THREAD

**Issue by Matoj** [SunwellTracker/issues#2274]
Decription: 
Can't mount it properly

How it works: 
Mounted for a frame or 2 and then dismounted

How it should work: 
Mount it and ride away to the sunset

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Hello. I don't think it's a server side bug - source of this issue is client with legion models. If you will use standard wotlk client it works just fine.
You can also try using this patch - https://www.dropbox.com/s/su8an6tvephexde/Patch-K.MPQ?dl=0
Probably it will fix your problem.
