### ISSUE TITLE
Undead legs 

### ISSUE THREAD

**Issue by FL3SHU** [SunwellTracker/issues#2278]
Decription: 
I haven't my legs on my death knight undead,

How it works: 
My legs is invisible becouse of boots 

How it should work: 
i want to see my legs and boots

Source (you should point out proofs of your report, please give us some source): 
![undead](https://user-images.githubusercontent.com/49323259/55653502-0db0c680-57ef-11e9-9ea2-d3769382bcf2.png)
![boots](https://user-images.githubusercontent.com/49323259/55653562-40f35580-57ef-11e9-89e0-f4363508b59e.png)

**Comment by Riztazz** [comment]
This is not a server-side issue, this is client-side issue and i cannot do anything about it. Re-downloading proper will fix those visuals
