### ISSUE TITLE
Pet bug

### ISSUE THREAD

**Issue by damian1710** [SunwellTracker/issues#2279]
Decription:  i have a problem becouse , i died with my pet , and when i got returned for the living cant revive my pet , i dont have spell like revive , when i try to tame another pet , they say that i got one , i cant dismiss it couse i dont have one , when i use spell call pet it says your target is dead , 

How it works: cant revive my pet 

How it should work: i should have spell revive and revived my pet , 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_040719_203705](https://user-images.githubusercontent.com/49374127/55688097-264ae900-5975-11e9-8f48-557ba5fdf9a3.jpg)

**Comment by peterjot** [comment]
You have to end this quest: https://wowwiki.fandom.com/wiki/Quest:Training_the_Beast_(Dwarf)
