### ISSUE TITLE
Kil'sorrow Banners

### ISSUE THREAD

**Issue by LiquidRyce** [SunwellTracker/issues#228]
Decription: While doing the quest "Returning the Favor" and its associated chain, the act of planting the banners is off and only sometimes will work. 

How it works: Sometimes the banners can be planted within seconds of the Warmaul Ogre's death, other times they can be planted while the ogre is still alive, and others it does not work at all.

How it should work: The banners should be able to be planted on corpses of Warmaul ogres, one per mob.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed.
