### ISSUE TITLE
[Mage] Flamestrike cannot be cast while engineering explosives & other devices on cooldown

### ISSUE THREAD

**Issue by Max0r847** [SunwellTracker/issues#2281]
Description: Flamestrike cannot be cast while devices such as engineering explosives (dynamite/bombs) are on cooldown.

How it works: Use dynamite, big bronze bomb, discombobulator ray, magic dust, etc. Any device that shares the 60 second cooldown with explosives. So long as this cooldown is in effect, flamestrike will not be able to be cast.

How it should work: The cooldown of these devices should have no effect on flamestrike. Flamestrike should be able to be cast freely during such cooldowns.

Source (you should point out proofs of your report, please give us some source): 

Video demonstrating the problem on Angrather with all addons disabled
https://www.youtube.com/watch?v=PsqRQHP8F8A

Video demonstrating the problem with combat log view
https://www.youtube.com/watch?v=jkk9HM7dky4

**Comment by Riztazz** [comment]
Only happens with flamestrike rank 1, weird. I will look into it

**Comment by Max0r847** [comment]
Wow only rank1? RIP lol

**Comment by Riztazz** [comment]
Alright, figured out what's up. Will be fixed with next update
