### ISSUE TITLE
Missing quest Take Five Bases

### ISSUE THREAD

**Issue by Cursecobain** [SunwellTracker/issues#2284]
Decription: Deathmaster Dwire in Hammerfall doesnt offer the Quest : Take Five Bases

How it works: the NPC doesnt start the quest

How it should work: obviously the NPC should have the quest and reward Battle Tabard of the Defilers at completion

Source (you should point out proofs of your report, please give us some source): 
https://dbwotlk.com/?quest=8122

**Comment by Azathothh** [comment]
You need to be exalted with The Defilers in order to be able to start this quest.
Just checked it and it's working.
