### ISSUE TITLE
[Warrior] - Switching to 1hand+shield in order to use Shield Bash removes your crit chance

### ISSUE THREAD

**Issue by Nemanja99** [SunwellTracker/issues#2287]
Decription: If you are using a Two-Hand weapon as a Warrior, you will need to switch to a 1-hand + shield if you want to be able to use an interrupt called Shield Bash. ( you can do all this with a macro pretty quick ), however, it removes your critical chance by a lot.

How it works: I have around 10% crit, when i switch to 1hand+shield and use Shield Bash to Interrupt a mob/player casting, then I switch back to my 2hand weapon, my crit chance goes to 2%. And it will stay 2% until I switch stances ( for example from Battle Stance to any other stance )

How it should work: You should just use Shield Bash and go back to your 2hand without any critical chance loss, i don't understand why am i losing so much crit with this.

Source (you should point out proofs of your report, please give us some source): If you have a warrior, feel free to do this if you want a solid proof.

**Comment by kinglobster** [comment]
you dont have weapon skill you want to bash with. weapon skill affects your crit rate. 
2hander : https://gyazo.com/6742ab4e46c9a588e4951164a8b46aab
1h+shield: https://gyazo.com/1f8e62b21653e70f0b1a2b66610dfe8e
actually i have more crit with shield than with 1hander thats cause i have agility 1hand

**Comment by Nemanja99** [comment]
I got that after further testing. However..
When I switch back to my 2hand weapon, I should get my old crit chance back, instead it stays low, as if I am still using the 1hand weapon for which I don't have weapon skill for

**Comment by Riztazz** [comment]
Could you please write down steps to reproduce that issue?
I am in combat, switching to non-skilled 1hander and my crit goes to low % and then switching back to my 2hander while still in combat and my crit chance goes back to previous values

**Comment by Azathothh** [comment]
Tested with:
50737 - [Havoc's Call, Blade of Lordaeron Kings] 
12282 - [Worn Battleaxe] 

44 - Axes 1/400 
172 - Two-Handed Axes 400/400

It appears that when not skilled weapon is equipped crit is reduced properly, but when weapon with 400/400 skill is equipped back crit is not being updated (only if this weapon doesn't add crit rating!). Crit is updated to proper value after getting crit rating modified by any source (item/respec/relog/any kind of auras - spells/talents etc)
