### ISSUE TITLE
Zul'Drak quest

### ISSUE THREAD

**Issue by Coolmankenny** [SunwellTracker/issues#2288]
Decription: 
I was doing the quest where you mount the big guy and you have to stomp 100 scourges and some bosses but when i took the spark near, my bar went to normal spells instead of the special ones and I couldnt even get off, so I logouted and came back with no "mount" just a buff called Gymer's Buddy and I cannot see any mobs or NPC's around me... Tried to even go out of Zul'Drak to get the buff gone but nothing happens, even tried to Hearthstone to Dalaran and I cannot see sh*t... I'm kind of stuck here now. Hit me up in game on Zabulon or Holyfinger, thanks for your time and looking forward to any respond !

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Please open in-game ticket and gm will remove this aura from you (or kill your character by getting fall damage - it will remove it as well)
Problem is that if you'll logout/close game while controlling Gymer - he will disappear but his aura won't.
