### ISSUE TITLE
Flak cannons at ogrila

### ISSUE THREAD

**Issue by ganth** [SunwellTracker/issues#2289]
![WoWScrnShot_041519_202845](https://user-images.githubusercontent.com/49654560/56152788-4ace4300-5fbd-11e9-86a5-12e71542e7a4.jpg)
![WoWScrnShot_041519_202935](https://user-images.githubusercontent.com/49654560/56152790-4b66d980-5fbd-11e9-8184-50ea402ab62c.jpg)

Decription: multiple, numerous [PH]Knockdown Fel Cannon Dummy inside each flak Cannon at ogrila wrath camps. They are visible, and there's big bad fps drop near the cannons

How it works: Visible imps in each cannon, around 5 to 10 of them, bad fps drops nearby
Ye cannn shoots now but the lag((( and the imps inside(((

How it should work: Make imps invisible, put 1 of them not like 5-10 in a circle, fix fps issues mb cause 5 imps at once

Source (you should point out proofs of your report, please give us some source): Screens, Notice 11-14 fps, imp in my target, and nultiple of them in the cannon base

**Comment by Azathothh** [comment]
Hello. It's Angrathar - wotlk bugtracker - please report Nightbane related bugs on tbc bugtracker - https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues

Seems like these imps are summoned whenever Cannon does shoot and doesn't disappear afterwards ;/  I've removed these cannons for now - i'm sure developers will fix it soon.
