### ISSUE TITLE
[Quest] Flight of the Wintergarde Defender

### ISSUE THREAD

**Issue by Matt-One** [SunwellTracker/issues#2290]
Decription: When u mount up the gryphon near the Gryphon Master, nothing happen

How it works: Nothing happens.

How it should work: You must be able to ride the Gryphon, anyway if u use the  [Wintergarde Gryphon Whistle] you are able to do the quest.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
That's not true actually, those gryphons you're talking about are related to this quest:
https://www.wowhead.com/quest=12325/into-hostile-territory
