### ISSUE TITLE
Zul farrak prisoners are bugged

### ISSUE THREAD

**Issue by Pundalf** [SunwellTracker/issues#2293]
Decription: 
When you kill all previous bosses there is a moment when you have free prisoners from their cages to proceed further

How it works: 
When you climb on top of the temple and kill the boss with the key all npcs are automatically getting out of cage and bosses are already down the temple and there is no need to defend yourself from waves from the enemies. Also if you open cage by yourself it works as it should be and you dupe the bosses

How it should work: When you climb on top of the temple, you kill the boss and loot the key. None of the npc should spawn and then you free them out of the cage and start defending from waves of enemies which ends up killing bosses

Source (you should point out proofs of your report, please give us some source:

**Comment by Piootrek** [comment]
Works fine for me. Can you record a video?

**Comment by cpypcy** [comment]
If you ring gahzrilla gong before going up the stairs they do this.

**Comment by Piootrek** [comment]
Should be fixed after update.
