### ISSUE TITLE
[Druid] Rake initial dmg doesn't ignore armor of a target #2

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#2295]
Reopened because "ghost" didn't understand the issue.

> "Hello,
> @Amarok-bt @avarishd I tested rake in our PTR.
> My values:
> Normal initial dmg - 132
> Normal initial dmg + Mangle - 172
> Normal initial dmg + Mjolnir proc - 159
> Normal initial dmg + Mangle + Mjolnir proc - 206"

It shouldn't scale with armor penetration. Bleed damage type should ignore armor.

Decription: Rake initial dmg doesn't ignore armor of a target

How it works: This spell consists of 2 parts: initial bleed dmg part and the bleed damage over time part. Bleeding over time works correctly which means that it already ignores the armor of a target so that any additional armor penetration value we get doesn't change the damage. However the initial dmg part is bugged and even though its dmg gets increased via Mangle debuff (30% more bleed dmg) it doesn't ignore the armor of a target.

How it should work: Initial dmg component of Rake should ignore armor of the target.

Source (you should point out proofs of your report, please give us some source):

Link to album showing incorrect scaling with armor penetration and DrDamage addon tooltip value which tells us that the damage number shouldn't change (4943 dmg value) `https://imgur.com/a/VS01j2M`

    2009-06-12
`    https://www.mmo-champion.com/threads/652287-DPE-whit-ArP`

>     "Since Armor Penetration basicly increases the dmg done by Shred, Magle, FB
>     but it has 0 effect on the rip / rake bleed effect"
> 

    2009-04-16
`    https://www.mmo-champion.com/threads/644012-Kitty-Discussion-Armor-pen-gt-Agi`

>     "RIP: 32%
>     Shred: 30.%,
>     White: 20%
>     Rake: 12%
>     Ferocious Bite: 6.0%
>     44% of the damage doesn't benifit from ARP. With the Idol of Worship will be even more."

**Comment by Riztazz** [comment]
Fixed, will be live with next update
