### ISSUE TITLE
Azure Watch Priest Trainer won't let you train spells.

### ISSUE THREAD

**Issue by Deathrift991** [SunwellTracker/issues#23]
Decription: 
Priest Trainer in Azure Watch wont let you learn spells.

How it works: 
Can't learn spells from priest trainer

How it should work: 
You should be able to learn spells from this trainer.
Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
![wowscrnshot_020218_010613](https://user-images.githubusercontent.com/35101706/35709965-4fd92326-07b5-11e8-8373-fba9db6d0b34.jpg)

I checked your report and unfortunately I wasn't able to repeat reported bug, because it worked fine.
