### ISSUE TITLE
Besieged!

### ISSUE THREAD

**Issue by LiquidRyce** [SunwellTracker/issues#230]
Decription: There are no Infernal Attackers outside Wildhammer Stronghold for the "Besieged!" quest.

How it works: There are no required mobs to kill, so it does not work at all.

How it should work: The infernals should be falling from the sky and the dwarf NPCs should be killing them.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
@Dootz Hello after server restart or a crash the way points that summon infernal just don't work at both side hord and ally camp .. i am able to force them to work by killing the invis waypoint and respawning them....

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/654
