### ISSUE TITLE
[Hunter] Sending pet into combat doesn't prevent Sap

### ISSUE THREAD

**Issue by Huntender** [SunwellTracker/issues#2302]
Decription: Sending pet into attack doesn't make the master invunerable to sap like it happened on Retail, AT and other renowned PVP servers. Nor does the pet actual attacks (physical/magical) to the target.

How it works: Pet running to the target or attacking it doesn't trigger combat and/or prevention to saps, almost like the pet is fighting on his own...

How it should work: As soon as your pet/ghoul/demon is sent onto the target, you should get invulnerable to Sap. This is how it worked back then and how it works on serious PVP servers.

Source (you should point out proofs of your report, please give us some source):  It has been reported already and even put on debate but the server is tired of waiting, because this is damaging PVP, as for example rogs already have many (legit) "tricks" for hunters, like stunning them from stealth when they have deterrence and then being able to attack them normally. Frankly adding so many bugs and vulnerabilities (some of which I have just reported, e.g. scatter shot bug) can easily make a class unplayable for PVP.
Think about it.

**Comment by Riztazz** [comment]
https://github.com/SunwellTracker/issues/issues/1158

Already discussed multiple times, it has been like that back in the day. Closing
