### ISSUE TITLE
[Armory] - English Language

### ISSUE THREAD

**Issue by Noob1e** [SunwellTracker/issues#2303]
Decription: Talent descriptions on the armory aren't English.

How it works: They're written in Polish language.

How it should work: If you choose website language as English, talent descriptions should be translated to English.

Source (you should point out proofs of your report, please give us some source): 
![SS](https://user-images.githubusercontent.com/27544010/56846076-128b0680-68d3-11e9-93d3-e57581c251b6.JPG)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1962
