### ISSUE TITLE
Big Combat Problems and Pets - broken unfair pvp

### ISSUE THREAD

**Issue by afflictive** [SunwellTracker/issues#2305]
**Decription:** 

Combat system is broken at this server. PVP is broken and unfair. People here using bugs to win.
Rogues here are Overpower. At this server rogue+priest dont have any counter setups in arena if they using bugs. Most of rogues here using those bugs like wow mechanic. It is bug abusing.

Hunters, dk, warlocks are unplayable here. You can have hard counter setup and you can playing much more better then enemy rogue but you will lose again and again. They can sap you 24/7. You cant playing your normal gameplay vs rogues becouse you have be constantly focused to keep combat. Spam aoe all time and tryharding buff arena mate. But rogues can just gouge or kidney you, going to loss and sap you 1 sec after. Its impossible to avoid sap if they know how to using bugs.

**How it works:** 
- Rogue can sap me when my pet attacking enemy by meele or by using abilities.
- Rogue can sap me when I using health funnel to my pet (when pet has combat)
- Rogue can resap me after blind or fear when my pet currently attack enemy or using abilities (for example: silence enemy priest 1 sec before resap)
- Rogue can shadowstep + sap me (on shadowdance) when he attack my pet and I staying and using healthfunnel to pet
- Rogue can sap my arena mate when he using healing spell to my pet (when pet has combat)
Lock lossing combat when channeling Health Funnel is Active.
- Rogue sometimes can sap my arena mate 1sec after he used buffs or heals to my pet (when pet has combat)
- All of pets owners can drink when pet have combat. For example: lock / frost mage can go to the loss, use freeze / seduction to enemys and start drink 1 sec later)

**How it should work:** 

1. Pet owner should get combat at the same time when pet gets combat by attacking enemy (when pet meele attack anyone or using defensive or ofensive ability to target with combat)

For example: 
- When my pet using abilities to enemy I should get combat with my pet. 
- When my pet atacking enemys by meele atacks I shoud get combat with my pet.
- When my pet dispel my arena mate (if he have combat) I shoud get combat with my pet.

2. Everyone should get combat by using buff or healing spells to friendly pet for next 5,5sec.

3. Warlock should not losing combat when Healthfunnel is active(when pet have combat) and combat should be refresh to 5,5sec after last tick (when pet have combat)

**LET ME CLEAR!**
I dont care about blizzard bug - invisibility combat when anyone call pet to enemys (before pet hit target). I'm not talking about this bug. I talking about basic wow mechanics.

**Source (you should point out proofs of your report, please give us some source):** 

https://www.warcraftmovies.com/movieview.php?id=116999

**4:43** - Lock used health funnel to pet and hpal flash heal and they got combat for 5,5sec (lock still have combat - 5sec after last tick healthfunnel)
**5:35** - Lock used petfollow to avoid fear
**5:38** - Lock got fear, and he used atack pet to priest. After 6 sec fear he still have combat (pet atacking priest)

https://www.warcraftmovies.com/movieview.php?id=127563

**5:28** - Lock got 10sec Turn Evil. After 10 sec turn evil he still have combat(pet attacking druid).

https://www.warcraftmovies.com/movieview.php?id=130939

**5:26** - Lock got Blind. After 9sec he still have combat (pet attacking druid).

- In 2019 its realy hard to find good proofs how combat system should works. You can find two videos in which a certain issue works differently. Some mechanics or bugs lasted few days or few weeks becouse Blizzard introduces changes on a regular basis. 
- But all of biggest pvp private servers like Arena Tournament, Warmane have this combat system. Those servers have rly big pvp community. They fixed those combat bugs few years ago, when finding evidence was easier.

I will probably find some more evidence videos in a short time, but now I am tired.

**Comment by Huntender** [comment]
Very nicely documented report, sir. I see from previous answers from direction that their intention was to "fix blizzard bugs", but they don't seem to realize they are altering the arena brackets and providing an unfair pvp experience, because they are damaging 3 classes at once. 

I personally play Hunter with another pet class at a high tr and we are severely affected from the custom decisions applied here. Dev's opinions do not even seem aligned because some of them have closed some reports immediately, while others have put a status of "debate" over them.

Luckily a fresh WOTLK server has just been released.

**Comment by Huntender** [comment]
Devs should read this too
https://github.com/TrinityCore/TrinityCore/pull/12084
It is easy for everybody to understand that - if pet is chasing the enemy - the owner should be unsappable, **even if the player has no combat icon**
Therefore, former "evidences" from Riztazz have to be rejected, because he has never shown a pet class getting sapped while the pet was attacking!

Fix - this - bug.

**Comment by peterjot** [comment]
https://github.com/SunwellTracker/issues/issues/134
