### ISSUE TITLE
[Dreamscythe - Sunken Temple Dungeon] - Wrong yell quote in a wrong moment (minor bug)

### ISSUE THREAD

**Issue by Nikvet** [SunwellTracker/issues#231]
Decription: The dragon - Dreamscythe is yelling wrong quotes in the wrong moment

How it works: After killing Jammal'an the Prophet, when you approach the centre where of the instance (where the hole is), you hear Dreamscythe - Turn back! Do not wake the dreamer! 
But when you look in the chat, you see that he yells: You know not what you do! We must destroy you for your own good - as an intro quote. This is the aggro quote. When you aggro him, he yells the intro quote: Turn back! Do not wake the dreamer! 

How it should work: He should yell the intro quote, when you approach him and the aggro quote, when you aggro him.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/npc=5721/dreamscythe

How to reproduce: Kill Jammal'an the Prophet, then go to the centre of the instance. Approach and then aggro the dragon called Dreamscythe.

**Comment by Dootz** [comment]
will be fixed with next server update
