### ISSUE TITLE
Can't que for Wintergrasp

### ISSUE THREAD

**Issue by Zeptux** [SunwellTracker/issues#2312]
Decription: Unable to que for Wintergrasp 15 minutes or less before the battle. Only after the battle starts im able to que up, but i get kicked and teleported seconds after joining. 

How it works: Whenever i go to Arcanist Braedin to que up for wintergrasp, nothing happens. Same if i take the portal or fly there, i never end up in the que and i dont know why. 

How it should work: Whenever i press "Queue for Wintergrasp" at Arcanist Braedin, i should get in the queue. Same if i fly to the zone or take a portal.

Source (you should point out proofs of your report, please give us some source):

**Comment by Huntender** [comment]
I'd want to report this as well. As said, you can talk with WG battlemaster and get your queue for WG battle,  and often (or maybe always) you get the invite to get into WG. If you accept the invite, you get in, then you get kicked after less than a minute, even if you went into the raid group.

How it should work: it would make sense that you either get the invite and you are able to get into WG (and not be kicked) or you don't get the invite at all.
Thank you

**Comment by Zeptux** [comment]
I never successfully joined WG when i had this problem. I just wanted to add a comment to this saying that it has solved itself somehow. When i talk to the battle mage 15 minutes or less before a fight, i get a request to join the queue, i press the accept button and voillah, im in queue! And later i accept the request to join the fight, works 100%
