### ISSUE TITLE
Darkmoon Faire ending early

### ISSUE THREAD

**Issue by white0rabbit** [SunwellTracker/issues#2317]
Decription: Darkmoon faire not endind when it should.

How it works: Currently ends earlier (probably 11:59 am?)

How it should work: It should end 11:59 pm ST.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Darkmoon lasts full 7 days and ends at the same hour it starts. https://www.wowhead.com/darkmoon-faire
