### ISSUE TITLE
[Item] Toy Train Set & Wind-Up Train Wrecker

### ISSUE THREAD

**Issue by lachtanek** [SunwellTracker/issues#2319]
Toy Train Set http://db.darkwizard.pl/?item=44606 doesn't make everyone around it do /train emote.
Wind-Up Train Wrecker https://db.darkwizard.pl/?item=45057 doesn't destroy train sets on the ground.
Both very important items, please consider fixing!

Source:
Toy Train Set
https://wowwiki.fandom.com/wiki/Toy_Train_Set
https://www.wowhead.com/item=44606/toy-train-set#comments:id=388590
https://www.wowhead.com/item=44606/toy-train-set#comments:id=390047
Wind-Up Train Wrecker
https://wowwiki.fandom.com/wiki/Wind-Up_Train_Wrecker
https://www.wowhead.com/item=45057/wind-up-train-wrecker#comments:id=685435

**Comment by Piootrek** [comment]
Both items work correctly
https://streamable.com/n9wib

**Comment by lachtanek** [comment]
Well the "makes everyone do /train emote with sound repeatedly" part of toy train set does not, sorry that I did not check train wrecker before creating the report, confused that one with another server.
https://youtu.be/vEUwkRF4nhQ?t=13
https://youtu.be/8hwgMUa56Ig?t=14

**Comment by Piootrek** [comment]
Only sound effect doesn't work. I'll fix it.

**Comment by lachtanek** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16218 this looks like a valid fix, even tho it's got some ugly hacks

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/899
