### ISSUE TITLE
Dalaran rings

### ISSUE THREAD

**Issue by Flamed1212** [SunwellTracker/issues#232]
Decription: 
There are no dalaran rings above 213ilvl at Harold winston at Dalaran.
How it works: 
You go to Harold Winston and you cant upgrade the ring above 213 ilvl

How it should work: 
You go to Harold Winston and you can buy ring up to ilvl 226.

Source (you should point out proofs of your report, please give us some source): 
Checked with ingame GM JAMAG who confirmed it is an issue. 
heres a link to armory https://beta.sunwell.pl/armory/Feronis/Okiedokie.
This person has bought the ring over a week ago.
![wowscrnshot_020418_200549](https://user-images.githubusercontent.com/36140202/35783167-db30598e-09fa-11e8-9139-2c18ce33c060.jpg)
![wowscrnshot_020418_200552](https://user-images.githubusercontent.com/36140202/35783168-db456e78-09fa-11e8-9281-f6ed89544018.jpg)
Attached photos are showing that this ring is not there to buy.

**Comment by knasen88** [comment]
These were not in the game at launch, but were later added almost as ulduar was released, and that was the ilvl 200 ring
http://www.wowhead.com/item=44935/ring-of-the-kirin-tor#comments
then with 3.1 = 213
3.2 = 226
3.3 = 251

DO NOT ADD THESE

**Comment by Cwiercpasiec** [comment]
Realms share the bugtracker. As far as i know, reason is quite simple. Angrathar is just a copy of Feronis with blocked content, if there is an issue on Feronis, then probably there is the same issue on Angrathar, no need to have 2 sepparate bugtrackers.

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
