### ISSUE TITLE
[Paladin] Buff giving less AP

### ISSUE THREAD

**Issue by cisiur** [SunwellTracker/issues#2320]
Decription: Paladin buff Blessing of Might giving less attack power then it should

How it works: On rank 2 and with talent it should give 39 AP

How it should work: But actuality it giving just 35

![Screenshot_1](https://user-images.githubusercontent.com/24439426/58170989-34d73080-7c95-11e9-9b4e-100e0187c60d.png)
![Screenshot_2](https://user-images.githubusercontent.com/24439426/58170990-34d73080-7c95-11e9-82b7-299b3800ef5e.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Please check how much ap you have without BoM and with BoM - you will notice that you're getting correct amount - 39ap  it's not bugged.
The problem is tooltips in buffs not showing correct values - but it's client side problem and it was like that on retail as well.
