### ISSUE TITLE
Orgrimmar and Undercity problem

### ISSUE THREAD

**Issue by Szajba** [SunwellTracker/issues#2322]
I have weird scene. In orgrimmar was be few NPC and a Overlord speaking somethink to them. And in there is a lot Forsaken Refugees in the gate. 
Undercity was burning and is controlled by Varimathras and Grand Apothecary Putress. In front of Undercity is Lady Salvanas, Thrall and Vol'jin and I can do nothing. What the hell is that?

**Comment by Dootz** [comment]
Hi, that's part of Battle for Undercity questchain:
Horde: https://wowwiki.fandom.com/wiki/Quest:The_Battle_For_The_Undercity_(Horde)
Alliance: https://wowwiki.fandom.com/wiki/Quest:The_Battle_For_The_Undercity_(Alliance)

**Comment by Azathothh** [comment]
Most likely https://wowwiki.fandom.com/wiki/Quest:Return_To_Angrathar_(Horde) is the last quest that you've done, next one is https://wowwiki.fandom.com/wiki/Quest:Darkness_Stirs  and you have to complete whole chain in order to return to "normal" phase in orgrimmar/undercity/stormwind
