### ISSUE TITLE
[Quest] The Storm King's Vengeance

### ISSUE THREAD

**Issue by cavani776** [SunwellTracker/issues#2323]
Decription: 
During the quest [The Storm King's Vengeance](http://db.darkwizard.pl/?quest=12919), [Thrym](http://db.darkwizard.pl/?npc=29895) isn't visible while riding [Gymer](http://db.darkwizard.pl/?npc=29647)

How it works: 
Thrym should be present while riding Gymer, as he's one of the quest's kill objectives. He needs to be killed while riding on Gymer's back.

How it should work: 
Thrym should be visible while riding Gymer.

Source (you should point out proofs of your report, please give us some source):
![WoWScrnShot_052819_142149](https://user-images.githubusercontent.com/50214258/58480885-91d25b00-815b-11e9-8001-4845aa6e2f43.jpg)
![WoWScrnShot_052819_142207](https://user-images.githubusercontent.com/50214258/58480886-926af180-815b-11e9-9c80-d23a53768be1.jpg)
![WoWScrnShot_052819_142219](https://user-images.githubusercontent.com/50214258/58480887-926af180-815b-11e9-99f6-10e2849a6565.jpg)
![WoWScrnShot_052819_142300](https://user-images.githubusercontent.com/50214258/58480888-926af180-815b-11e9-9ae4-2fa85d0f32bc.jpg)
![WoWScrnShot_052819_142510](https://user-images.githubusercontent.com/50214258/58480889-926af180-815b-11e9-9d2b-dc2c3fe553b5.jpg)
![WoWScrnShot_052819_142552](https://user-images.githubusercontent.com/50214258/58480890-93038800-815b-11e9-8b9a-fffe03281efe.jpg)
![WoWScrnShot_052819_142608](https://user-images.githubusercontent.com/50214258/58480892-93038800-815b-11e9-92ba-d2e86251e64b.jpg)

**Comment by Azathothh** [comment]
Thrym on your screen is not related to this quest - Thrym which you have to kill in quest is spawning after Prince Navarius is dead :  https://youtu.be/nxwliC-Dn84?t=155

**Comment by cavani776** [comment]
Oh, silly me. Sorry for bothering you. :/
