### ISSUE TITLE
Saragosa's End

### ISSUE THREAD

**Issue by Cammeron1** [SunwellTracker/issues#2324]
Decription: Can't complete quest because Saragosa doesn't show up on the platform. Instead she is somehow "dismounted" and just falls down. 
![WoWScrnShot_060119_132117](https://user-images.githubusercontent.com/51262819/58747788-40361300-8470-11e9-9446-175fe512c1e6.jpg)
![WoWScrnShot_060119_132125](https://user-images.githubusercontent.com/51262819/58747790-43c99a00-8470-11e9-9fc2-5b032f9fcb4b.jpg)

How it works: Saragosa doesn't show up

How it should work: There should be at least possibility to kill her.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/quest=11957/saragosas-end

**Comment by Azathothh** [comment]
Quest can be completed just fine - you have to use quest item Arcane Power Focus near center of that platform and Saragosa will appear - it doesn't look 100% same as on retail but works 100% same (only cosmetic stuff to be corrected + Saragosa from your screen probably shouldn't be there)
https://www.youtube.com/watch?v=su6D3QXih18

**Comment by Cammeron1** [comment]
Oh, okay.. Sorry to bother you
