### ISSUE TITLE
<Heart of the Phoenix> Hunter pet spell bug

### ISSUE THREAD

**Issue by m2rahman** [SunwellTracker/issues#2325]
Description: 
Greeting GM, 

Since a week or two, i noticed that Pet instant revive spell [Heart of the Phoenix] is not working.
I tried to respec pet talent but its still same. please fix this. I attached a video link to proof.

proof link:

https://youtu.be/labQ5tEzEM4

Thanks

How it works: 
its just don't work.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It appears that currently it's not working if hunters have any companion (non-combat pet) active. After dismissing companion it worked.
