### ISSUE TITLE
[Quest] Word of power

### ISSUE THREAD

**Issue by adkonison** [SunwellTracker/issues#2328]
Decription: 
![WoWScrnShot_061419_203402](https://user-images.githubusercontent.com/51621756/59530406-caa45b00-8ee3-11e9-93c4-cac77dfc2b87.jpg)

How it works: Mob is immune even I kill mobs around

How it should work: Mob should be to kill after kill mobs

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Can confirm.
Happens rarely, GMs can fix it by killing/respawning it.

**Comment by stanq87** [comment]
worket for me just now
