### ISSUE TITLE
Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Lsnickels** [SunwellTracker/issues#233]
Decription: Jedoga became untargetable after she went up into the air for the fourth time, because she did not spawn a cultist to walk to the center of the circle. Also, she received the enrage buff each time even if the add didn't make it to the center of the circle, since we killed the add prior to it reaching that point. Lastly, when she came down and was enraged, she would not move from the center of the room and follow the tank.

How it works: Cultist did not spawn the 4th time she went immune. She received the enrage even if the cultist died. She stays in one place when enraged after coming down from cultist phase.

How it should work: She should spawn a single cultist from a random location around the circle, and if that cultist dies she does not get enrage. Each time she goes up into the air she should spawn one cultist to kill. She should follow the tank around the room like normal when she comes down from the cultist phase.

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
#200
