### ISSUE TITLE
I can't pick up quest to alchemy mastery

### ISSUE THREAD

**Issue by Mlecznykrul** [SunwellTracker/issues#2331]
Description: Today I tried to get quest for transmutation mastery. For some reason Quest giver didn't want to give me quest. The same problem with elixir master. I have 450/450 alchemy. Quest log is almost empty.

How it works: I m unable to get any alchemy mastery because of bugged npc.

How it should work: They should give quest to anyone with 325+ alchemy

Source (you should point out proofs of your report, please give us some source): 
https://user-images.githubusercontent.com/51995361/59760111-d1d7ba00-9291-11e9-9b82-f85da0d1bd51.png

**Comment by Azathothh** [comment]
Not a bug.
You have to do other quest first, before you will be able to start quest from Zarevhi.
https://wowwiki.fandom.com/wiki/Quest:Master_of_Transmutation_(1)
For alliance it does start at Alchemist Gribble in Honor Hold
