### ISSUE TITLE
painfull mages bug with pet

### ISSUE THREAD

**Issue by pojkee** [SunwellTracker/issues#2336]
Decription: 
Just watch video here - https://youtu.be/-6MRNbIIw_s
How it works: 
When i summ my Water Elemental and then mirrors - Water elemental - just disappears
How it should work: 

shouldn't disappear
Source (you should point out proofs of your report, please give us some source): 
proof -  https://youtu.be/-6MRNbIIw_s

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2255
