### ISSUE TITLE
Admiral's Orders

### ISSUE THREAD

**Issue by stanq87** [SunwellTracker/issues#2337]
Decription: 
npc for quest completion not present in origimar

How it works: 
no npc to give item to

How it should work: 
give item to npc

Source (you should point out proofs of your report, please give us some source): 

quest from https://classicdb.ch/?npc=3139
quest https://classicdb.ch/?quest=831
missing npc https://classicdb.ch/?npc=10540

**Comment by Dootz** [comment]
Hi, it is possible that he was killed by opposite faction. From what I can see he's alive now. In case of further please let us know and we'll reopen.
