### ISSUE TITLE
[Uncommon Scents] is daily

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#234]
Decription: [Uncommon Scents] is daily while it's supposed to be a one-time chain

How it works: I did Uncommon Scents-Crushing the Crown chain yesterday, was going to pick up Crushing the Crown (daily) today again, but picked up Uncommon Scents first, and now I can't take Crushing the Crown as if I never did the chain

How it should work: do Uncommon Scents chain to be eligible for Crushing the Crown daily

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=24660/crushing-the-crown#comments:id=1626616

**Comment by Dootz** [comment]
problem is not related to quest itself. More likely it reseted during server crash.
