### ISSUE TITLE
Lady Deathwhisper 25 Heroic Ghosts bug + Parry Haste

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2340]
Decription: Lady Deathwshiper should spawn 3 spirits on 25 Heroic and/or 25 Normal.

How it works: At the moment Lady Deathwhisper spawns only 1 spirit on 25 Heroic and/or 25 Normal. Currently Lady Deathwhisper doesn't have any Parry Haste.

How it should work: Lady Deathwhisper should spawn 3 spirits in phase#2 on 25 Heroic and/or 25 Normal.. Lady Deathshiwpser should have Parry haste - same as Sindragosa + Halion.

Source (you should point out proofs of your report, please give us some source): 

I'll put a link from the Exodus (World 2nd kill) Lady 25 Heroic - https://youtu.be/YMaNM3FQ7TM?t=326

If you need a more information, please let me know

**Comment by Piootrek** [comment]
Bug with shades have been fixed. Pary haste works correctly.
