### ISSUE TITLE
Sindragosa's Tail Smash Bug + Parry Haste

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2342]
Decription: Sindragosa's Tail Smash range is bugged.

How it works: At the moment, it works kinda weirdly. No matter where you stay, there is still a chance to trigger a tail smash. We've did many tries with my guild and even if there is no one behind the boss, she still casts a Smash and kicks people away. 

P.S - Sindragosa should have a "Parry-Haste" which doesn't work here as well. The main point is to DPS the boss at the back leg, so you don't parry the boss and you don't kill the tank. Unfortunately, the parry haste here is not working and everyone is DPS-ing in the middle of the boss or even at the front leg. I've noticed that if someone place a tomb under the boss (in the hit boss), she casts a smash. If you stay outside of the hitbox, she won't cast it.

How it should work: Sindragosa should cast Tail Smash only if someone stays behind her (near the tail). She shouldn't kick anyone who says in the middle of the boss.
Sindragosa should have parry haste.

Source (you should point out proofs of your report, please give us some source): 

I'll attach a video of our guild stream Sindragosa 10 heroic again.

Please, check how the paladin stays in middle(even front leg) and there is only him and the warlock pet. The boss still casts a Smash and kicks him away with the beacon causing a wipe. VIDEO: https://youtu.be/z2AWlxGfz3I?t=14812

**Comment by Azathothh** [comment]
She does have a parry-haste mechanic currently

**Comment by Philliipe** [comment]
@Azathothh Thank you for your reply.

The main report is about the Tail Smash range. All of the MDPS should stay at the back leg of the boss which is kinda impossible at the moment because Sindragosa kicks you away. The range of the smash is incorrect. Check it out please.

**Comment by Philliipe** [comment]
This was already fixed after the last update
