### ISSUE TITLE
Lich King Shambling Horrors + Wicked Spirits + Defile

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2343]
Decription: Shambling Horrors + Wicked Spirits on Lich KIng are immune to slow. Defile casted on the main tank.

How it works: The Shambling Horrors + Wicked Spirits are currently immune to slow. They're immuning, root/stun/shackle/turn evil etc. The defile is casted on the main tank.

How it should work:  The Shambling Horrors + Wicked Spirits shouldn't be immune to slow effects. The defile should not be casted on the main tank, never.

Source (you should point out proofs of your report, please give us some source): 

Unfortunately, not able to provide any evidences for this. Will try to look for it and update later on.

Providing a video link from our stream on Sunwell, how the main tank gets a defile. VIDEO: https://youtu.be/dB-_Na6kDSo?t=393

**Comment by Piootrek** [comment]
Any proofs?

**Comment by Philliipe** [comment]
@Piootrek All of the mobs on Lich KIng are elites. 
It doesn't make any sense "Vile Spirits" to be slowable but Wicked spirits to be immune. Same goes for the Shambling Horror.

The other really annoying thing is that most of the "Wicked Spirits" in the frostmourne are "evading" your spells/attacks.

**Comment by Philliipe** [comment]
@piootrek Please, disregard the post. We have already checked in retail and it works fine.

I'm sorry for any inconvenience.
