### ISSUE TITLE
Ruby Sanctum Combustion/Consumption/Meteor Strike

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2344]
Decription: Consumption/Combustion and Meteor Strike casted on the Main Tank.

How it works: Currently the Main Tank in Ruby Sanctum can get Combustion/Consumption and even Meteor Strike.

How it should work:  The Main Tank should never get Consumption/Combustion and/or Meteor Strike.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
1. Consumption/Combustion - he never cast it on a player with most aggro - if he used it on tank it means that tank wasn't first in aggro.

2. Meteor Strike - have you seen anywhere any informations that it should never be used on a tank? If yes, please add some links or other proofs

**Comment by Philliipe** [comment]
@azathott Please, disregard the post. We have already checked in retail and it works fine.

I'm sorry for any inconvenience.
