### ISSUE TITLE
[Quest Bug] When This Mine's a-Rockin'

### ISSUE THREAD

**Issue by BluddyGutz** [SunwellTracker/issues#2351]
Description: 
The mine's been overrun by a plague of gan'arg misfits! Not only did they run all my workers out of the tunnels, but they're pounding away in there night and day! To make things worse, now I've got Danath on me back! He says he's going to take away me ale ration if I don't get this taken care of soon! None of the miners'll go in there, and the guards are busy drinking themselves silly. I'm begging you, <name>, help me here. Danath can take me dignity, but he'll never take me ale! 

How it should work: Accept the quest from Foreman Biggums at the mouth to the mine (no quest item is given). Enter the mine and kill 12 Gan'arg Sappers. Return to Foreman Biggums to turn in quest. 

How it does work: I can kill the Gan'arg Sappers in the mine (they correctly label as the quest mobs), but their deaths do not 'tick-down' the quest log, nor am I able to progress the quest by killing 12 sappers. I've tried logging off the character, abandoning and then retaking the quest, and restarting the game... all to no avail.

Source (you should point out proofs of your report, please give us some source):  62 Dark Elf Hunter Kynnia tried completing quest on 15 July, 2019..

**Comment by Azathothh** [comment]
They are using "Power Burn" spell too quick now. You can do this quest by interrupting this spell or doing more than 50% dmg to them, before they detonate themselves. 
Will be fixed in next update.

**Comment by BluddyGutz** [comment]
I did as you suggested (interrupted sappers spell)... worked like melted butter. Thanks for the information and the response.
