### ISSUE TITLE
Not receiving Honor from a player 5+ levels higher

### ISSUE THREAD

**Issue by Fushigi1** [SunwellTracker/issues#2356]
Decription: I do a lot of pvp in Stranglethorn Vale because I am a 39 Twink Rogue, but when I kill players that are +5 levels higher I do not receive honor.
It's extremely frustrating as well since no battlegrounds happen at that bracket making the only way of pvp duels or world pvp so it should give the appropriate honor points.

How it works: 

Me as a lvl 39 kills a lvl 46 and receives no honor likewise for them I am green level meaning they should also receive honor for killing me but they do not.
How it should work: 
The player should receive honor for killing anyone within their 9 level bracket.
Source (you should point out proofs of your report, please give us some source): https://gyazo.com/709ceb8806f2607ddd6d455cd4405832

**Comment by Fushigi1** [comment]
The horde I was killing was my friend upstairs and I tested it with my brothers character and it seems you don't get any honor for killing someone playing on the same IP or WiFi? whats up with that

**Comment by Dootz** [comment]
Hi,

as you have noticed in comment which you deleted it does not grant honor points if both players share IP. It's to prevent honor farming on multiple accounts :)
