### ISSUE TITLE
Ahn'Kahet boss bugged out: Jedoga shadowseeker

### ISSUE THREAD

**Issue by matejchi** [SunwellTracker/issues#236]
Decription: 
She was supposed to do something when she flouted up, but we stood there, went to kill the mobs that maybe had to come, still nothing happened.

How it works: 
I'm sorry i don't know i'm a noob to wotlk lol. but she did bug out.

How it should work: 
I'm sorry i don't know i'm a noob to wotlk lol. but she did bug out.

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/a/rs315

**Comment by Cwiercpasiec** [comment]
How it works:
Jedoga sometimes bugs out and does not fall after flying up. I'm not sure if she spawns the add tho, @matejchi did she spawn the add after she flew away, or not? If yes, did you kill it?
By the way, if you're not sure how something should work, try googling it. There are plenty of records on youtube for example, simply enter the name of the boss/quest etc. and look for clips uploaded in 2010.

How it should work:
She should fly up, spawn the add and get down after the add is killed.

Source:
https://www.youtube.com/watch?v=u0nDvCXZVJ0

**Comment by Piootrek** [comment]
Fixed

**Comment by matejchi** [comment]
Hello, she flew up, said the text (audio) she needed for someone to come and no one came, then we went on killed those adds you see dead on the screen cus we thought they are the ones. Then nothing happened aswel, so we left for the last boss.

Thanks a lot for the fix, great server regardless, i love it.
