### ISSUE TITLE
[Quest Filling the Cages

### ISSUE THREAD

**Issue by adkonison** [SunwellTracker/issues#2360]
Decription: 
Budd doesn't have pet action bar to complete this quest 

How it works: 
Budd doesn't have pet action bar to complete this quest 

How it should work: 
Budd should have pet action bar to complete this quest 
https://www.youtube.com/watch?v=-9Jzo0zImAU

![WoWScrnShot_072819_173316](https://user-images.githubusercontent.com/51621756/62009321-44279e00-b15e-11e9-8020-e917d3cae2a7.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/141
