### ISSUE TITLE
[Trauma] doesn't work as it should

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2361]
Decription: The [Trauma] weapon (one of the most imporatnt weapon for Resto Shamans, Holy Priests and/or Restoration Druids is bugged.

How it works: At the moment the chance of the [Trauma] proc is literally 0.00001% - Almost impossible to get a proc from the weapon. This is the main reason why most of the healers on Sunwell doesn't it it.

How it should work: The [Trauma] healing effect proc should be 1% itself. (I'll attach a screenshot from "Rawr" to prove that the chance has to be 1%) I'll also attach many videos with many tests of the [Trauma] weapon proc, where you can clearly see that it procs quite often.

Source (you should point out proofs of your report, please give us some source): 

1st video of Trauma test - https://www.youtube.com/watch?v=B_qxHPDqUMU HPriest Test
2nd video of Trauma test - https://www.youtube.com/watch?v=RtAG5qRlQpo Rdruid Test-  It procs on the 8th Rejuvenation casted ( you can see the rejuvenation counts on the left of the video, sorry for the quality, that's an old video from retail but still visible)
3rd video of Trauma test - https://www.youtube.com/watch?v=lNGrmm6BD1o Restoration Shaman Test
4th video of Trauma test - https://www.youtube.com/watch?v=oMdQ4BlsNB4 Again Restoration Druid Test
5th video - https://www.youtube.com/watch?v=SGgDd-hpUWg STREAM TOC 25 hc from our guildie Resto Shaman on Sunwell where you can see that the proc chance is really low.
Rawr evidence for the proc chance of the weapon - https://cdn.discordapp.com/attachments/590971962470432778/605141374454464533/TraumaHC.jpg

P.S - I think all of these evidences are more than enough to resolve the issue as soon as possible. If you need more information, do not hesitate to ask. 

Looking forward,
Cheers

**Comment by Eaglesring** [comment]
Also u can check this https://www.youtube.com/watch?v=D01-AUnRijA. Whole PP fight with rdudu POV

**Comment by Cwiercpasiec** [comment]
Here are logs from my guild run:
http://worldoflogs.com/reports/78kctup36rxrviqd/details/17/?s=1169&e=1589
1406 trauma ticks, wouldn't say "[Trauma] proc is literally 0.00001%", seems a bit more.

**Comment by Philliipe** [comment]
Why did you close the topic??

**Comment by Cwiercpasiec** [comment]
Because Trauma procs quite often (u can check the logs)

**Comment by Afgann** [comment]
http://www.worldoflogs.com/reports/b2k9jsgjwxc5urmd/details/24/?s=1225&e=1742 - Method logs
http://worldoflogs.com/reports/78kctup36rxrviqd/details/17/?s=1169&e=1589 - Sunwell logs
Tell me what's off here, looks similar @Philliipe.
