### ISSUE TITLE
Sindragosa's Blistering Cold hits through the Ice Tombs. Frost Breath range is incorrect.

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2362]
Decription: Sindragosa's blistering cold hits throuhg the Ice Tombs and Sindragosa's Frost Breath range is incorrect.

How it works: At the moment, the Blistering Cold hits throuhg the Ice Tombs and it shouldn't. The Frost breath will hit you if you stay on the side of the boss. This is really annoying if you're doing Sindragosa 25 Heroic where you have healers spread on the tank side and sometimes the breath hits them. It's more like an angle ( > ) rahter than going straight.

How it should work: The Ice Tombs should prevent the damage from Blistering Cold. The Frost Breath shouldn't kill people who're going on the sides to explode, unless they're going literally infront.

Source (you should point out proofs of your report, please give us some source): 

You can easily check the video from Exodus World 2nd vs Sindragosa 25 Heroic.
The Shadow Priest places the tomb on the left side a bit close to the boss and everyone is los-ing there, no one dies from blistering. Attaching a video link :  https://youtu.be/O8NDBlSpM4g

Regarding Frost Breath: Paragon Video, where you can clearly see how the tomb is positioned even a bit infront of the head and everyone is resetting stacks there. The holy paladin is going on the left side of the tomb (that's even a bit infront) and the tank is going to swap, the boss is casting Frost Breath and none of them is taking damage from it. If it was Sunwell raid, they would die. - https://youtu.be/LVcWZ5hfhis?t=459

**Comment by Philliipe** [comment]
P.S - sorry for the typo, I'm reporting this from my phone ;[

**Comment by Azathothh** [comment]
https://youtu.be/O8NDBlSpM4g - not a single tomb was in range of blistering cold in this video
https://youtu.be/LVcWZ5hfhis?t=459 - "The holy paladin is going on the left side of the tomb (that's even a bit infront) and the tank is going to swap, the boss is casting Frost Breath ~~and none of them is taking damage from it~~" and said holy paladin nick Ilonie is dying from it, few seconds later you can see his exact position where he died...

**Comment by Philliipe** [comment]
Hey Azathothh, here is a video link with the exact second where you can see the shadow priest placing tomb on the left and everyone's hiding behind - 0 damage taken from the blistering. 

https://youtu.be/O8NDBlSpM4g?t=465

P.S - If you keep such range on Sunwell, you'll definitely die from Blistering Cold

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/64075345-6c537100-ccb7-11e9-969f-146949181fe8.png)
resto druid wasn't behind tomb at the moment of blistering and he didn't die - tomb wasn't in range of blistering...

"P.S - If you keep such range on Sunwell, you'll definitely die from Blistering Cold"
![obraz](https://user-images.githubusercontent.com/37483678/64075524-bdfcfb00-ccb9-11e9-9dd8-71a2a8f67bed.png)
i've done it like on video and that's ~31yd range, while blistering cold does have 25yd range - ofc i didn't get any damage from it
