### ISSUE TITLE
[Quest] You, Robot

### ISSUE THREAD

**Issue by adkonison** [SunwellTracker/issues#2366]
Decription: 
![WoWScrnShot_080419_221925](https://user-images.githubusercontent.com/51621756/62428814-52e5f600-b706-11e9-8ecd-64879d0bef5c.jpg)
![WoWScrnShot_080419_221930](https://user-images.githubusercontent.com/51621756/62428815-537e8c80-b706-11e9-8189-4df7eaf555b8.jpg)

How it works: I have comlete the quest but I can't give back

How it should work: I should give back it

Source (you should point out proofs of your report, please give us some source):

**Comment by adkonison** [comment]
![WoWScrnShot_080419_223128](https://user-images.githubusercontent.com/51621756/62428907-a9076900-b707-11e9-85b3-36feea26b120.jpg)

**Comment by Dootz** [comment]
Seems to be working correctly now.
