### ISSUE TITLE
Fuel For the Fire 

### ISSUE THREAD

**Issue by tank1194** [SunwellTracker/issues#237]
Decription: Fuel for the Fire 

How it works: Mobs take way to long to respawn been here 30 mins waiting for them to respawn cause if there is more then one person doing quest takes ages

How it should work: just increase the Spawn rates of the Drakkare Skullcrushers to meet atleast 2 people doing the quest at once

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealYasri** [comment]
Just did this quest, the hole camp of mobs was picked clean, did it with four other people and there were stretches of 5+mins with no mobs out. Can get it down "decently" if all grouped together buy if both a alliance and horde player are trying to do at same time, and cant group up, it would be a nightmare quest.

Few extra spawns and/or a two min respawn timer would fix it up well.

**Comment by Kokaina** [comment]
Fixed.
