### ISSUE TITLE
Raging spirits are healing themself during harvest soul (HC)

### ISSUE THREAD

**Issue by Eaglesring** [SunwellTracker/issues#2370]
How it works: 

Raging spirits are healing themself during harvest soul

How it should work: 

They shouldnt be able to do this

Source (you should point out proofs of your report, please give us some source): 

https://www.youtube.com/watch?v=pBfK5doQifY&feature=youtu.be

So as u can see on this vid. RS was on 10% of his HP and when we cameback from harvest his HP were fully regen
https://www.youtube.com/watch?v=RSeVCw3hVgQ&t=637s
Paragon vid- they cameback from harvest at 11:49 and Raging spirit had same amount of HP as before

PS: This bug appear becuase of the last server restart

**Comment by Philliipe** [comment]
Please, fix this, as it's really annoying for the guilds which are progressing heroics ..

**Comment by Lukabxjx** [comment]
With this being bugged its pain doing ph3 if you have 1 or 2 raging spirits being next to LK.Both tanks being busy over raging spirits and Lich King in ph3 doesnt let them have time to soak vile spirits which in most cases is wipe.
This fix is must.

**Comment by Riztazz** [comment]
We know, gonna update in an hour or so with a fix

**Comment by Philliipe** [comment]
Thank you so much for putting effort into this!

**Comment by Riztazz** [comment]
Always :)
