### ISSUE TITLE
[Core - Spell] On-next-attack Abilities causing Auto Attack skipping due to missing Resource check upon trigger

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2391]
Decription:
Repost of https://github.com/SunwellTracker/issues/issues/1111 -- original issue tagged as "Duplicate" and was closed, but couldn't find any other issue it could've been a duplicate of.
On-next-attack Abilities (f.ex. Heroic Strike, Cleave) are missing the Resource check for when they're triggered, causing skipping of Auto Attack if the Resource is below the minimum required at the time.

How it works: 
Triggering on-next-attack Abilities with sub-required Resource skips Auto Attack.

How it should work: 
Attempting to trigger an on-next-attack Ability with sub-required Resource should auto-cancel the queued on-next-attack Ability and instead hit with Auto Attack.

Source (you should point out proofs of your report, please give us some source): 
As found in the above-referenced issue: https://truewow.org/forum/viewtopic.php?f=49&t=13005&p=177188&hilit=next+attack#p177188
Furthermore, found the original link of the bugreport there: https://truewow.org/bugs/view.php?id=685

Steps to reproduce (example: Warrior):
1. Acquire enough Rage for a Heroic Strike (15R by default);
2. Queue up HS for your current Auto Attack;
3. Use any Ability that can drop you below 15R before HS gets triggered;
4. Attempt to trigger HS with sub-required Rage.

**Comment by Azathothh** [comment]
https://streamable.com/xh0iw
Auto attack isn't skipping now, but queued HS isn't 'canceled' when there's not enough rage, it stays in queue and is used next time when we do have enough rage.
Should we get "Heroic Strike failed.(Not enough rage)" info + Heroic Strike removed from queue or should it stay in queue like it does now?

**Comment by Aridam** [comment]
It should auto-unqueue as you do AA and give the "Not enough rage" error.
