### ISSUE TITLE
Fatal Crash: QUEST-Flight of the Wintergarde Defender (dragonblight)

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#240]
Decription:  During the use of the summoned gryphon in "Flight of the Wintergarde", my game fatally crashed. I had a Helpless Villager on my mount and was using the boost feature.

After relaunching, I was stuck on the summoned gryphon. Couldn't move, dismount or use abilities. I alt-f4'd, deleted Cache and relaunched. I was off the mount, but couldn't use any abilities and mobs only spawned within the view spawn distance of my summoned gryphons position. The gryphon was still spawned in the air and showed as a my pet, but I couldn't use Dismiss pet to remove it.

I used hostile NPCs to kill my character, which fixed the issue..

**Comment by ihcTactics** [comment]
Update, the issue is apparently caused by a memory overload of M2Shared.cpp. I'm looking into the cause of this.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
