### ISSUE TITLE
[Misc - Visual, Interface] Several Abilities not updating use conditions on Action Bars with Focus/Mouseover

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2404]
Decription:
Several Abilities are missing feedback on conditions for usage on the Action Bars with Focus/Mouseover.

How it works: 
There are several Abilities which are missing usage conditions updates on your Action Bars if you have Focus/Mouseover macros for them.
Same exact bug reported elsewhere, describing this in detail:
https://github.com/dalaranwow/dalaran-wow/issues/5768
Video source as well (applies to this server):
https://www.youtube.com/watch?v=P1CZi0Abw6o
Watch and see how several Warrior Abilities -- Rend, Overpower, Execute etc. -- don't update on the fact that your Focus/Mouseover is too far from you for them to be used, as they show as lit-up the whole time, misleading into believing that you can use them, when you actually cannot.

This also applies to Reactive Abilities -- f.ex. Overpower from Dodge is usable only on the Target that Dodged you. If you use Focus/Mouseover while having that same Target selected, you are being led to believe that OP is usable on any other Target that's a Focus or a Mouseover. The same also happens backwards -- if a non-selected Target Dodges you, and you have a Target that didn't Dodge you selected, using Focus/Mouseover will make you think you can't use Overpower on any Target.

How it should work: 
The Action Bars should update all Ability icons properly based on conditions for use if using Focus/Mouseover macros for them -- if you're out of Range, they should update correspondingly, if it's a Reactive Ability, it should update correspondingly on which Target it can be used on (in both above-explained situations), and so on.

Steps to reproduce:
Either watch and replicate https://www.youtube.com/watch?v=P1CZi0Abw6o or:
1. Roll a Warrior;
2. Make a Focus/Mouseover macro for the shown affected Abilities (f.ex. Rend);
3. Target something in Melee Range;
4. Attempt to use Focus Rend on something not in Melee Range -- icon is lit-up but unable to use due to Range;
5. Repeat steps 3-4 but with Mouseover instead;
6. Make a Focus/Mouseover macro for a Reactive Ability (f.ex. Overpower);
7. Target something in Melee Range;
8. Hit it until it Dodges;
9. Attempt to use Focus Overpower on something that hasn't Dodged you -- icon is lit-up but unable to use due to that other Target not having Dodged you first;
10. Repeat steps 7-9 but with Mouseover instead.
11. Repeat steps 7-9 but backwards for both Focus and Mouseover -- i.e. have a Target Dodge you, then select a different one that hasn't, attempt to use Focus/Mouseover OP; icon isn't lit for anything, but the first Target Dodged you and should show as usable, which it doesn't here (if you use it, it actually does it successfully).

**Comment by Piootrek** [comment]
I'm 99% sure it's clientside issue and can't be fixed by us.
