### ISSUE TITLE
[Misc - Visual] Auto Attack sometimes doesn't visually display

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2406]
Decription:
Auto Attack sometimes doesn't visually display.

How it works:
While using Auto Attack, there will sometimes be an occurrence where it is "missing" -- it's a visual bug that causes it not to display until another Auto Attack or another action that will cause it to display (like on-next-attack Abilities). It is random, so there's no clear pattern or solid way of forcing reproduction.
Same bug as here:
https://github.com/dalaranwow/dalaran-wow/issues/5764
Video here (applies to this server as well -- same exact bug, same principle):
https://www.youtube.com/watch?v=3aJ_bzOjyiM

How it should work: 
Auto Attack should always display as it happens.

Steps to reproduce:
1. Target something;
2. Use Auto Attack;
3. Keep watch on the Combat Text, your Character's animation (should be swinging but either doesn't or just stops mid-animation, as well as using a Damage Meter addon to note down when a registered AA doesn't visually show) -- you should see "two" AAs happening next time 'round.
DISCLAIMER: As said, this is random, so have patience if it doesn't happen off the bat -- it will, sooner or later.

Additional information:
Auto Attack Spell ID: https://db.darkwizard.pl/?spell=6603#?ref=sunwell.pl

**Comment by Riztazz** [comment]
Server doesn't handle animations, it's done by the client. I will take a look if something can be done, but pretty sure it was like that during wotlk times

**Comment by Aridam** [comment]
Seems correct.
https://youtu.be/OP63cb5cHf0?t=177
"Two" Auto Attacks. No Sword Spec present in this one. Looks to be as you said.

Issue can be closed for being invalid.
