### ISSUE TITLE
[Quest] Proof Of Demise: Ley-Guardian Eregos [The Oculus Heroic] Chest does not respawn

### ISSUE THREAD

**Issue by Vulas** [SunwellTracker/issues#241]
Decription: 
Chest does not respawn causing the quest to be incompletable.

How it works: 
Chest fails to respawn to give the item [Ley Line Turner]

How it should work: 
Chest should always respawn making [Ley Line Turner] lootable for all.

Have reported the issue to community manager Dredd and he is aware of this issue.

**Comment by Dootz** [comment]
Will be fixed with next server update
