### ISSUE TITLE
[Encouter] Rotface

### ISSUE THREAD

**Issue by adkonison** [SunwellTracker/issues#2411]
Decription: With this situation Ooze always explode

How it works: When big Oozes merges ooze with higher stack take another stack

How it should work: Two Big Oozes merge into a Big Ooze with size one larger than the smaller of the two initial ones.
https://wow.gamepedia.com/Rotface

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://www.youtube.com/watch?v=MehIjmUx2_8
3:12 - Big Ooze with 1 stack is merged with Big Ooze with 2 stacks = in result we get Big Ooze with 3stacks
3:39 - Big Ooze with 4 stacks is merged with Big Ooze with 2 stacks = in result we get Unstable Ooze Explosion
~4:30 - Big Ooze with 4 stacks is merged with Big Ooze with 1 stack = in result we get Unstable Ooze Explosion
~7:09 - Big Ooze with 2 stacks is merged with Big Ooze with 3stacks = in result we get Unstable Ooze Explosion

If it was like you're saying we would never get Unstable Ooze Explosion in any of these cases. 
If you have any proofs that it should be like you're saying please share them.
