### ISSUE TITLE
LK - Defile/Val'kyr overlap timer

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2412]
Decription:  LK - Defile/Val'kyr overlap timer

How it works: Spell timer overlaps

How it should work: 

If defile and val'kyrs should be cast at the "same" time. It should be picked random which one to be 1st

If it's Summon Val'kyr defile should be delayed for about 3 sec after the 3rd valk is summoned.
https://youtu.be/Fh7kQkQkLik?t=6m22s

If it's defile 1st then, Summon Val'kyr should be delayed for around 4-6 sec. Soul reaper and Infest may be cast during that time.
https://youtu.be/f2rywsW2H2A?t=4m52s

Lich king can cast Soul Reaper and Infest during Summon val'kyr spawns.
If defile, soul reaper and infest get same timer. They should prio dis way: Defile --> Infest -> Soul Reaper
https://youtu.be/f2rywsW2H2A?t=5m24s

Additional info:
Val'kyr 1st

http://www.worldoflogs.com/reports/k9lp4yw68u6s1asl/xe/?x=sourceName+%3D+%22The+Lich+King%22%0D%0Aand+type+%3D+6+and+spell+%3D+%22Soul+Reaper%22+%0D%0Aor+spell+%3D+%22Defile%22+and+type+%3D+6%0D%0Aor+spell+%3D+%22Summon+Val%27kyr%22%0D%0Aor+spell+%3D+%22Quake%22+%0D%0Aor+spell+%3D+%22Infest%22+and+type+%3D+6%0D%0Aor+spell+%3D+%22Harvest+Souls%22+and+type+%3D+6%0D%0Aor+spell+%3D+%22Vile+Spirits%22

Defile 1st

http://www.worldoflogs.com/reports/81eia26l3k2b6xku/xe/?s=6509&e=7401&x=sourceName+%3D+%22The+Lich+King%22%0D%0Aand+type+%3D+6+and+spell+%3D+%22Soul+Reaper%22+%0D%0Aor+spell+%3D+%22Defile%22+and+type+%3D+6%0D%0Aor+spell+%3D+%22Summon+Val%27kyr%22%0D%0Aor+spell+%3D+%22Quake%22+%0D%0Aor+spell+%3D+%22Infest%22+and+type+%3D+6

http://www.worldoflogs.com/reports/l8q2n8j5edqaioyi/xe/?s=8055&e=8997&x=sourceName+%3D+%22The+Lich+King%22%0D%0Aand+type+%3D+6+and+spell+%3D+%22Soul+Reaper%22+%0D%0Aor+spell+%3D+%22Defile%22+and+type+%3D+6%0D%0Aor+spell+%3D+%22Summon+Val%27kyr%22%0D%0Aor+spell+%3D+%22Quake%22+%0D%0Aor+spell+%3D+%22Infest%22+and+type+%3D+6

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
https://github.com/SunwellTracker/issues/issues/2350

**Comment by Philliipe** [comment]
@Wojtyas I'm gonna add this information to #2350

**Comment by Wojtyas** [comment]
Great <3
