### ISSUE TITLE
Necrotic Plague Jump Priorities

### ISSUE THREAD

**Issue by Philliipe** [SunwellTracker/issues#2415]
Decription: Necrotic Plague Jump Priorities

How it works: http://www.wowhead.com/spell=70337/necrotic-plague

How it should work: I believe when jumping, it should favour targets that are nearest to it.

 

 

I'm not convinced as to the random thing.

 

https://www.youtube.com/watch?v=2yS_fC9ti9w&feature=youtu.be&t=1m32s

 

Watch the Necrotic Plague at 1:35, and at 2:05. For a strategy like that to have any realistic hope of working without having the plague bounce between raid members constantly, the plague would need to have some kind of favored priority target. This could either be enemies, or simply targets that are nearest to it.

 

https://www.youtube.com/watch?v=UJz6R18A5u8

 

0:54, the Priest called Jhazrun has the plague dispelled while clearly being in range of the MT, ghouls, and probably some other melee DPS, yet the plague seems to preferentially jump to the Shambling Horror (because it's closest?). Jhazrun seems to anticipate this behavior, else they wouldn't have been so close to the Bear.

 

At 1:53, the Hunter called Kruf gets the Necrotic Plague. Just like the priest, he gets close enough to the Shambling Horrors such that they're closest before he has it dispelled.

 

The entire off-tank PoV in p1, the Necrotic Plague never jumped to the off-tank (until the very end once there was only 1 Shambling left). This seems to suggest either favouring enemies, or favouring nearest targets (enemies are usually closer to each other due to be being clustered around the OT).

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Yep, it should go to the nearest eligible target.
And that's exactly how it's working right now...https://streamable.com/igr5f (checked on LK with ghouls and shamblings as well - it was always going for nearest target)

**Comment by Philliipe** [comment]
Hello,


Looks like you misunderstood the topic.

The report was about prioritizing enemy targets over friendly ones. Try to have a friendly target around ya and enemy as well. ( party member + enemy(ghoul or shambling). Dispel the plague and check if it prioritizes the enemy over friendly. This is how it should work

**Comment by Azathothh** [comment]
> How it should work: I believe when jumping, it should favour targets that are nearest to it.

> Looks like you misunderstood the topic.

I'm pretty sure what does "it should favour targets THAT ARE NEAREST to it" mean, so how could i misunderstood it? In both videos plague is jumping to nearest target, that's how it should work, and that's how it's working (like i've already said)
