### ISSUE TITLE
npc / vendor miising idems

### ISSUE THREAD

**Issue by stanq87** [SunwellTracker/issues#2425]
Decription: 
npc Dealer Najeeb missing some stuff
How it works: 
its not there

How it should work: 
it shoukld be there

Source (you should point out proofs of your report, please give us some source): 

https://db.darkwizard.pl/?npc=20981#?ref=sunwell.pl

**Comment by Wojtyas** [comment]
He sells all of items from that list. What's exactly the issue? What is he missing?

**Comment by stanq87** [comment]
he sells 8 items he should sell 17 items, 

https://ibb.co/NpPpHmJ

**Comment by Azathothh** [comment]
He's selling all 17 items from that list - but 11 of them are available in limited supply. You can see only 8 cause other were sold out at that time.
