### ISSUE TITLE
[Gathering] Gathering attempts can fail. Should not fail as of 3.1.0

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#243]
Decription: 
While gathering herbs it is possible to "fail attempt".

How it works: 
Right-click to gather herb, there is a chance to fail attempt at the start of your cast.

How it should work: 
You should not be able to fail gathering attempts as of patch 3.1.0.

Source (you should point out proofs of your report, please give us some source):
http://wowwiki.wikia.com/wiki/Patch_3.1.0#Gathering_Skills

**Comment by TheRealestMcCoy** [comment]
I have this issue with mining as well.

**Comment by Dootz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/21039/files

**Comment by Dootz** [comment]
will be fixed with next server update
