### ISSUE TITLE
[Warrior, Talent] Sudden Death not spent when hitting successfully with Execute

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2435]
Decription:
Sudden Death doesn't fade when you land a hit with Execute.

How it works:
If you get a Sudden Death proc, it stays on even after an Execute hit that connects, allowing you spam it for as long as the Buff stays.

How it should work:
Sudden Death's Buff should fade when you land a hit with Execute.

Steps to reproduce:
1. Take the Sudden Death Talent;
2. Use Execute and land a hit with it;
3. Observe the Buff -- it's still there and you can keep using Execute.

Additional information:
Execute IDs: https://db.darkwizard.pl/?search=Execute#abilities
Sudden Death IDs: https://db.darkwizard.pl/?search=Sudden+Death

**Comment by Aridam** [comment]
To note, I didn't really notice this with Ranks 1 and 2, but it was straight-up in my face ever since I got Rank 3 (I've a Power Aura tracker for SD in general so I can't miss it) -- might be just R3 that's like this.

**Comment by Azathothh** [comment]
Are you sure that it's happening with Rank 3 Execute? (https://db.darkwizard.pl/?spell=20660)
For me it's happening only with Rank 5 (https://db.darkwizard.pl/?spell=20662). Looks like it's missing the part which is responsible for removing Sudden Death buff.

**Comment by Aridam** [comment]
Rank 3 Sudden Death not Execute.
