### ISSUE TITLE
Quest Mob/Quest Node/Item respawn time needs to be fixed for Northrend

### ISSUE THREAD

**Issue by redbrox** [SunwellTracker/issues#244]
Description: 
Mobs respawn at an extremely slow rate for Northrend. Same with the nodes for quests. Everyone is hitting around 70 by now and multitudes of people are waiting for nodes to respawn. This isn't how the launch was, they were respawning at an abysmal rate.

How it works: 
I have waited over 15 minutes now for a Nerub'ar Egg Sac to be respawned for my quest chain.

How it should work: 
It should take no more than 1 minute for them to respawn, given it's a fresh server. I think the spawn rates are affixed to the 3.3.5 ones, where most people aren't leveling to 80 and are doing ICC/waiting for Cata pre patch.

Source (you should point out proofs of your report, please give us some source): 

Anyone who played during retail Wrath launch or on any properly scripted private server that has spawn rates affixed to a fresh server / expansion release.

**Comment by Riztazz** [comment]
Issue will be resolved with next update.
