### ISSUE TITLE
[Warrior] Commanding Shout adds its Maximum Health increase to Current Health as well; doesn't keep Current Health proportionate

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#2440]
Decription:
An issue with Commanding Shout which makes it add the Max HP increase to Current HP as well, while also not keeping Current Health proportionate.

How it works:
Commanding Shout currently adds as much Maximum Health to Current Health as well.
Gaining/Losing Commanding Shout doesn't keep Current Health proportionate to this change.

Example: you're at 1 HP out of 1000, use Commanding Shout Rank 1 (+1080 Max HP) -- Max HP is at 2080 but your Current HP also goes up to 1081, essentially saving you in a tough situation.

How it should work:
Commanding Shout should not add the +Max HP to your Cur HP.
Cur HP should be kept proportionate anytime you gain or lose C. Shout.

Example: you're at 50% HP and gain Commanding Shout -- your Max HP increases by however much the C. Shout is supposed to give you, while your Cur HP scales proportionately to the shift, staying at 50% HP.

Source (you should point out proofs of your report, please give us some source):
https://www.mmo-champion.com/threads/717628-health-increase-based-on-blizzard-own-information?p=7874721&viewfull=1#post7874721
"The bug with Commanding Shout back in BC was (if we are talking about the same thing) where Commanding Shout was basically a potion. Before the hotfix, Commanding Shout added X health. Now, it adds a percentage based on your health percentage. If you are at 50%, it will only increase your health by 50% of the effect of commanding shout. (However max health is increased by the full effect of Commanding Shot)"

Steps to reproduce:
1. Get yourself to low HP (enabling showing of % HP is preferable);
2. Use Commanding Shout;
3. Observe the difference in Cur HP both in raw values and % before and after.

Additional information:
Commanding Shout Spell IDs:
https://db.darkwizard.pl/?search=Commanding+Shout#?ref=sunwell.pl

**Comment by Aridam** [comment]
Issue isn't fixed despite being marked as fixed _and_ implemented.
It's bugged in the opposite way now -- it increases _only_ Max HP, leaving Cur HP untouched and Cur % HP _severely_-disproportionate as a result.

Read provided source with quote again:
Source (you should point out proofs of your report, please give us some source):
https://www.mmo-champion.com/threads/717628-health-increase-based-on-blizzard-own-information?p=7874721&viewfull=1#post7874721
**"The bug with Commanding Shout back in BC was (if we are talking about the same thing) where Commanding Shout was basically a potion. Before the hotfix, Commanding Shout added X health. Now, it adds a percentage based on your health percentage. If you are at 50%, it will only increase your health by 50% of the effect of commanding shout. (However max health is increased by the full effect of Commanding Shot)"**

Read example _intended_ Commanding Shout corresponding to the above, again:
How it should work:
Commanding Shout should not add the +Max HP to your Cur HP.
Cur HP should be kept proportionate anytime you gain or lose C. Shout.

**Example: you're at 50% HP and gain Commanding Shout -- your Max HP increases by however much the C. Shout is supposed to give you, while your Cur HP scales proportionately to the shift, staying at 50% HP.**

**Comment by BialyADI** [comment]
bump

**Comment by Aridam** [comment]
Bump. Huge issue. Basically makes Commanding Shout worthless unless used pre-Combat with full HP.

**Comment by Aridam** [comment]
https://gfycat.com/honorableajarcollardlizard
Still nope.
