### ISSUE TITLE
[Core - Mechanic] First attack received while sitting isn't a Crit

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2441]
Decription:
Issue which prevents taking Crits on first attack received while sitting before being stood up.

How it works:
Sitting doesn't guarantee the first attack you receive that stands you up becoming a Crit.

How it should work:
The first attack you receive while still sitting is supposed to be a Crit.
This has always been a feature.

Source (you should point out proofs of your report, please give us some source):
https://wowwiki.fandom.com/wiki/Sit
https://forum.nostalrius.org/viewtopic.php?f=24&t=2917
https://www.reddit.com/r/wow/comments/4g4ycj/question_warcraft_logs_tank_sitting/
https://us.battle.net/forums/en/wow/topic/20767637953?page=1
https://www.reddit.com/r/classicwow/comments/9gmcfm/sit_for_combat_benefits/

Steps to reproduce:
1. Take any enemy;
2. Sit down;
3. Make the enemy attack you while sitting;
4. Note that none of the attacks received each time you've stat down are Crits.

Notes:
This is supposed to work even if you're immune to Crits from Resilience and/or Defense -- this is why Tanks are supposed to avoid accidental sits, unless you're specced in defensive Crit Talents (like Blood Craze, Enrage etc.) and want to force a proc knowing the risks (provided any received non-Crit Damage proccing them from % chance equal to Resil/Def doesn't happen first anyway) -- some of this is mentioned in some of the provided links above.

**Comment by Aridam** [comment]
Issue isn't fixed.

Just re-tested with Mobs out in Icecrown to try to proc Blood Craze by sitting -- turns out I still don't get their Melee hits on me to be guaranteed Crits in the first place.

**Comment by Piootrek** [comment]
Afgann fixed this only for sitting players. Now should be fine with creatures too.
