### ISSUE TITLE
Spell CONFLAGRATE Warlock

### ISSUE THREAD

**Issue by Marek723** [SunwellTracker/issues#245]
Decription: 
Class: Warlock
Spell: Conflagrate

How it works: 

After i use immolate, i need still waiting 1 sec. before i use conflagrate.
(Why this spell is so important for me? 
In arena is impossible to use conflagrate against hight players,becouse they still have a lot of time to dispell that immolate.)

How it should work: 
That spell Conflagrate should be use instantly when that dot immolate or shadowflame are on target.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=01fY5re7l8g 1:09

**Comment by Sunite** [comment]
Conflagrate should be out of GCD

**Comment by Elaatu** [comment]
Video 2012, server Tauri... That's the proof?

**Comment by Marek723** [comment]
Yes

**Comment by Afgann** [comment]
Any proof from retail?

**Comment by Marek723** [comment]
Why you need even proof i do not understand.
Or this is normal to waiting for conflagrate 1 sec. after that immolate was used ?

**Comment by Afgann** [comment]
https://eu.battle.net/forums/en/wow/topic/7527663253

**Comment by Sunite** [comment]
http://www.warcraftmovies.com/movieview.php?id=130861 Wotlk warlock season 7

**Comment by Kokaina** [comment]
Works correctly.
