### ISSUE TITLE
npc stuck in ground

### ISSUE THREAD

**Issue by stanq87** [SunwellTracker/issues#2450]
Decription: 

some mobs in outland > netherstorme > stormspire   are stuck inside or under the area ,  and no, there are no caves or basements,

How it works: 
npc's  Asarnan and Dealer Senzik  are not where there supose to be

How it should work: 
they should be where they usualy are ? 

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Can you provide some ss?

**Comment by stanq87** [comment]
https://i.ibb.co/VJn4x8V/werwer.jpg

however now these mobs are in the correct plases, so propably a server restart corrected the issue
