### ISSUE TITLE
[Northrend, Object, Item, Quest, Mechanic, Visual] Bombard the Ballistae - missing knockback, visual animation and despawn

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2455]
Decription: 
Issues with the ballistae for the Quest in question missing their animation and despawn on bombing them. There is also no knockback if you're too close.

How it works: 
The ballistae for the "Bombard the Ballistae" given by Deathguard Molder at Venomspite in Dragonblight are missing their visual animation of being blown up when hit with the bomb Quest Item, alongside missing their despawn. Also if you're close enough to them when you blow them up, you don't get knocked back.

How it should work: 
The ballistae are supposed to animate when blown up and despawn. If you're too close, you're supposed to get knocked back too.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/eOLY8NsCII4?t=198

Steps to reproduce:
1. Take https://db.darkwizard.pl/?quest=12232;
2. Stand close to a ballista;
3. Blow it up;
4. You will notice the following:
4a) no knockback for standing too close;
4b) no visual animation of the ballista being blown up;
4c) ballista doesn't despawn.

Additional information:
https://db.darkwizard.pl/?quest=12232 is the Quest's ID.
https://db.darkwizard.pl/?item=37259 is the Quest Item's ID.
https://db.darkwizard.pl/?object=188673 is the Ballista's Object ID.
https://db.darkwizard.pl/?search=Ballista#npc-abilities for the Ballista effects when blown up (search filter "Bombard").

**Comment by Azathothh** [comment]
"4a) no knockback for standing too close;" is working now, still missing: 
"4b) no visual animation of the ballista being blown up;
4c) ballista doesn't despawn."
