### ISSUE TITLE
[Warrior] Battle Shout and Commanding Shout are affected by Line of Sight

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2457]
Decription: 
An issue causing both Battle _and_ Commanding Shout to be affected by Line of Sight, not buffing anyone not in LoS up.

How it works: 
Both Battle and Commanding Shout are affected by Line of Sight -- people not within your LoS aren't buffed.

How it should work: 
Battle and Commanding Shout should both ignore Line of Sight and buff anyone up within their radius. It's supposed to act as a castable Aura Buff (similar to Rampage, Paladin Auras etc.).

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?spell=6673
Range is 0 (self), but with an added Radius, as seen here:
"Effect #1 | Apply Aura: Mod Attack PowerValue: 15, plus 0.5 per levelRadius: 30 yards
-- | --
Apply Aura: Mod Ranged Attack PowerValue: 15, plus 0.5 per levelRadius: 30 yards"
However here the Radius abides by LoS rules.

Take Blessing of Might: https://db.darkwizard.pl/?spell=19740
Only Range (30yd), no Radius. You can only directly-affect people with this.
However, take its Greater variant: https://db.darkwizard.pl/?spell=25782
Apart from the Range (40yd), any same-Class Group Members within a Radius of 100yd are also buffed by this, ignoring LoS, compared to the original Target of the Buff that requires LoS.

Take Rampage as well: https://db.darkwizard.pl/?spell=29801
0yd Range (self), but with a 100yd Radius that affects everyone, even not in LoS.

Steps to reproduce:
1. Take a Group Member;
2. Get out of their Line of Sight;
3. Use Battle/Commanding Shout;
4. Note the Shout missing from them.

Additional information:
https://db.darkwizard.pl/?search=Battle+Shout#abilities Battle Shout Spell IDs.
https://db.darkwizard.pl/?search=Commanding+Shout Commanding Shout Spell IDs.

**Comment by Riztazz** [comment]
Any more evidence supporting this? None of the aoe buffing spells have ignore line of sight attribute by default (from official client files).
There could be a scenario where consolidated raid buff automatically gains said flag, but that's just guess, kinda need more information

**Comment by Aridam** [comment]
Had to work with TBC Retail footage, considering that with WotLK came Glyphs, making it possible to have six-minute Shouts, which nobody bothers to refresh.

Despite being rather low-quality, they're still decent-enough to study, especially thanks to these people having let Buffs on their Group Members' Party Unit Frames be seen.
Check the people and how far they are, as well as when they are in LoS and when not. Apart from obvious pointers like Buff icon and timer refreshes, watch for visuals such as the Character animation and effects on casting a Shout, and correlate that when timing seems iffy, like in the first one:
https://www.youtube.com/watch?v=-41Dgo6auCA&feature=youtu.be&t=533
These two are much better due to their quality and the fact everyone's got a Raid Marker.
https://www.youtube.com/watch?v=pXUVYsr1DCM&feature=youtu.be&t=232
https://www.youtube.com/watch?v=pXUVYsr1DCM&feature=youtu.be&t=1529

**Comment by Riztazz** [comment]
Alright. thank you :)
