### ISSUE TITLE
Warrior - Charge/Intercept stun delay

### ISSUE THREAD

**Issue by vedude** [SunwellTracker/issues#246]
How it works: 

When you charge someone, there's a slight delay before the stun goes off. In some cases, this can make other players's spells go off right before the stun goes off, or they can jump even further, kiting the charge and catching up to him much harder.

How it should work: 

When you charge someone, it should stun the player charged instantly. There should not be any delay what so ever.

Source (you should point out proofs of your report, please give us some source): 

No source really needed here. This stun effect and how it should work is generally known. The tooltip does not mention of any delay before stunning the target.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
