### ISSUE TITLE
Glyph Seal of Vengeance re-apply

### ISSUE THREAD

**Issue by lioredri** [SunwellTracker/issues#2460]
Decription: 
If you relog to a character that is under the effect of Seal of Vengeance, and you have the Glyph activated, you'd have to re-apply the seal in order to have the Glyph effect again.

How it works: 
I suppose theres a Glyph condition check when applying the seal

How it should work: 
I assume there should be a check-for-glyph 
executed when logging in.
Source (you should point out proofs of your report, please give us some source): Personal experience in Angrathar, best available private realm.

**Comment by Azathothh** [comment]
Looks like it's same with all glyphs working in similar way (doing something when some other spell is active), for example Glyph of Seal of Wisdom or Glyph of Unending Breath - Seal of Wisdom/Unending Breath have to be re-applied after relog in order to gain effect from glyph.
