### ISSUE TITLE
Sons of Hodir: Honored but I can only attack

### ISSUE THREAD

**Issue by Farulon** [SunwellTracker/issues#2464]
Decription: 
I did the quests for the "Sons of Hodir" in the Storm Peaks. Including the ines for Thorim where you get honored with the Sons. I started the quests "Forging a Head" and "Raising Hodir's Spear" and logged out. When started the game again I finished the quests. Now I want to talk to the giants to finish them, but I can't talk to the giants, only attack them. Their names are green and they only attack me when I hit them.

How it works: 
Honored with "Sons of Hodir" but instead of talkin I can only attack them.

How it should work: 
I should be able to talk to them like normal questgivers/vendors.

Source (you should point out proofs of your report, please give us some source): 
![Njormeld](https://user-images.githubusercontent.com/55207229/67410752-dc49ed80-f5bc-11e9-8c24-375b332b11a2.PNG)

**Comment by Wojtyas** [comment]
You have to remove "At war" option with them in your reputation panel.
Anyway I will leave this issue as open, we shall change this by default.

**Comment by Farulon** [comment]
Oh good to know, thank you!
I was confused, because it worked at first.
