### ISSUE TITLE
[MECHANIC]Stuck in combat when mobs evade

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#2467]
Decription: Stuck in combat when at least one mob evades after big pull.

How it works: When you pull plenty of mobs at once but at least one of them runs away and you kill the rest of the mobs you are stuck in combat state until you pull that particular mob again and kill it or let it evade again.

How it should work: You shouldn't be stuck in combat when mob runs away.

Source (you should point out proofs of your report, please give us some source): -

**Comment by Aridam** [comment]
I've had this happen to me once while leveling recently (1-2 weeks) -- mass-pull situation, one Mob went into Evade right as I was attacking it, and ran back to pre-pull position. After clearing out all the rest, I was stuck in Combat and at the time, didn't know why. Went around to pull more Mobs and found out the Mob that had Evaded back was the cause of the Combat bug. After pulling that specific one, my Combat subsided.

**Comment by Aridam** [comment]
Still broken.

Fresh proof: https://youtu.be/TQ26JyGffvw

**Comment by Piootrek** [comment]
Today I found another source of this problem and fixed it too. Please recheck after next update.
