### ISSUE TITLE
Seared Scourge in Grizzly hills not behaving correctly.

### ISSUE THREAD

**Issue by magnusrambech** [SunwellTracker/issues#247]
Decription: 
Seared Scourge in Grizzly hills not behaving correctly. 

How it works: 
Bombs are having a very small aoe radius, making the quest close to impossible to complete. Also, You have very limited range in order to get credit.

How it should work: 
More radius ( i think), more range

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=eSNnRRTNV5k

**Comment by Netherfrost** [comment]
Although its a sloppy workaround, you can get credit from it if your party members use the quest item

**Comment by magnusrambech** [comment]
Yes, that will be a smart way to do it. Getting 30/30 was pain in the ass solo.

**Comment by Bel-WOW** [comment]
Done it myself few times, not so hard to be honest. While you stand in front of DTK, look to your right, more quest monsters gather there then the left side. After that it's timing your shots for the best results.

Reducing the cooldown on quest item would be welcome tho.
