### ISSUE TITLE
[Quest, Mechanic] Phasing out of "The Last Line Of Defense" gets Character stuck

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2472]
Decription: 
An issue which causes phasing out after "The Last Line Of Defense" to get your Character stuck.

How it works: 
After completing "The Last Line Of Defense" and phasing back out, your Character gets stuck -- cannot move, apart from being able to jump once, which gets you further-stuck in mid-air.

How it should work: 
Character shouldn't get stuck after phasing out following completing the Quest.

Steps to reproduce:
1. Take "The Last Line Of Defense";
2. Complete it;
3. Hand it in;
4. Attempt to move your Character after getting phased back out.

Additional information:
Quest ID: https://db.darkwizard.pl/?quest=13086#?ref=sunwell.pl

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/1232
