### ISSUE TITLE
[Black Rock Depth] Room whith trash before last boss.

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#248]
Decription: 
There is no need in [Shadowforge Torch](https://db.darkwizard.pl/?item=11885#dropped-by) by killing [Shadowforge Flame Keeper](https://db.darkwizard.pl/?npc=9956) because the door is already opened. 

How it works: 
There is no need in [Shadowforge Torch](https://db.darkwizard.pl/?item=11885#dropped-by) by killing [Shadowforge Flame Keeper](https://db.darkwizard.pl/?npc=9956) because the door is already opened. 

How it should work: 
You must kill  2 [Shadowforge Flame Keeper](https://db.darkwizard.pl/?npc=9956) to loot 2   [Shadowforge Torch](https://db.darkwizard.pl/?item=11885#dropped-by) and fire 2 [Shadowforge Brazier](https://db.darkwizard.pl/?object=174744) and only then doors must open.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
After some testing/ code behind check:
- doors are initially closed
- using Shadowforge Torch on each Brazier will open specific doors (left brazier - left doors, right -right)

However it should work as described in issue.

**Comment by kovaq** [comment]
As you said Dootz, each torch opens one doors.
Its bug:
_"To enter the Iron hall, you must loot two torches from two flamekeepers (one torch per dwarf), and use it to light the two braziers. These are five minute duration, unique, BoP items, that are consumed on use. **Once both braziers are lit,** the doors open, and the NPCs of the Lyceum stop respawning."_

http://wowwiki.wikia.com/wiki/Lyceum

**Comment by Dootz** [comment]
Will be fixed with next update
