### ISSUE TITLE
[NPC, Mechanic] Mobs are missing Co-Aggro mechanic

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2485]
Decription: 
An issue with Mobs and their Aggro, causing them to be missing an entire sub-mechanic.

How it works: 
Mobs do not have the Co-Aggro mechanic.

How it should work: 
https://wow.gamepedia.com/Aggro_radius#Co-aggro
Basically, Mobs should be able to pull other Mobs if they go within others' Aggro Radii. It's intended to make handling pulled Mobs more difficult and demand more awareness of one's surroundings -- taking a Mob that's following you into another Mob's Aggro Radius _despite_ not going into it yourself, should _still_ pull that Mob too. Same applies to if a Mob gets Feared and its random pathing takes them close enough to another Mob. Again the same applies to Mobs fleeing for their life when brought low-enough (this specifically works only after they've stopped at the nearest Mob for a few seconds -- if it's killed before those few seconds, the other Mob won't actually be pulled).

Source (you should point out proofs of your report, please give us some source):
See provided link above.

Steps to reproduce:
1. Pull any Mob;
2. Do the following:
2a) Make it follow you into another Mob's Aggro Radius. _Do not get **yourself** into the other Mob's Aggro Radius, else **you** will pull it;_
2b) Fear it until the Fear's random pathing takes it into another Mob's Aggro Radius;
2c) Bring its HP down to critical levels, causing it to flee -- if a Mob is close enough, it will try to run to it for help. The other Mob is supposed to be pulled upon the first one entering its Aggro Radius and Co-Aggroing it to you, however it only Co-Aggros after it has it stand next to it for a few seconds -- if it's killed before the last moments pass, the other Mob ends up not being pulled, which is not intended.

**Comment by Wojtyas** [comment]
Where you have detected that issue mate? We have implemented that on Angrathar time ago, it may not work on PTR.

**Comment by Wojtyas** [comment]
In addition, only mobs from same fraction will pull other mobs on you.

**Comment by Aridam** [comment]
One example location is at The Broken Front in Icecrown, example Mobs are Undying Minions.
https://imgur.com/a/5Ajh3N2
Taunted the farther one while not being in the closer one's Aggro Radius. Farther one was basically in kissing distance of the closer, but no Co-Aggro occurred.

Another example:
https://imgur.com/a/iELUPSw
Shadow Adepts, same location.
Got up on the tank to pull the targeted one while LoS-ing the other one you see, then I had to jump down and force it to pass by the other one while following me ('cause it wouldn't follow me until I jumped down due to another bug) -- no Co-Aggro again.

**Comment by Azathothh** [comment]
These examples are not related to co-aggro but rather to small issue with vmaps. Undying Minion from https://imgur.com/a/5Ajh3N2 won't attack you even if you'll run next to him, cause he can't see you in his LoS

**Comment by Aridam** [comment]
Seems correct -- went back and reconfirmed, then I went to some lower-Level Mobs for better and easier testing. The mechanic seems to work, as I pulled Mobs and made them pass by others of the same kind while out in open sight, without aggroing them myself, and it worked.

Looks like this report's invalid.
