### ISSUE TITLE
[Warrior, Spell, Talent, Mechanic] Sword Specialization doesn't proc from non-damaging Special Attacks with a Sword

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#2494]
Decription: 
An issue which causes non-damaging Special Attacks done with a Sword equipped to not proc the Sword Specialization Warrior Talent.

How it works: 
Non-damaging Special Attacks (the application of Rend, Hamstring, Sunder Armor etc.) don't proc Sword Specialization if using a Sword.

How it should work: 
Special Attacks which do no Damage (examples being _applying_ Rend, Hamstring, Sunder Armor, etc.) are supposed to proc Sword Spec if a Sword is used. They should _still_ be considered as attacking your Target with a Sword in spite of not doing any Damage -- they even play the weapon-swinging animations and also proc various Enchantments (f.ex. Berserking), Talents (Sudden Death) etc.

Source (you should point out proofs of your report, please give us some source):
This specific mechanic seems to have existed since Vanilla, persisted through TBC, and still worked in WotLK.
https://www.reddit.com/r/classicwow/comments/d5ga9p/leveling_arms_with_sunder_armor_instead_of_heroic/f0ltu6c/
http://www.arenajunkies.com/topic/3638-sword-spec-not-proccing-off-mshamstringww/#entry25391
http://www.arenajunkies.com/topic/3638-sword-spec-not-proccing-off-mshamstringww/page-2#entry25420
https://www.mmo-champion.com/threads/603849-sword-spec-and-windfury
https://www.wowhead.com/forums&topic=137622#p1720424

Steps to reproduce:
1. Take the Sword Spec Talent;
2. Equip a Sword;
3. Spam non-damaging Abilities at something (Rend, Hamstring, Sunder Armor).

Additional information:
Sword Spec IDs: https://db.darkwizard.pl/?search=Sword+Spec#talents

**Comment by Aridam** [comment]
Bump. Limits the Talent severely, alongside the other issues with it already.

**Comment by Aridam** [comment]
https://gfycat.com/whiteenergeticgardensnake
Still no procs.
