### ISSUE TITLE
[Warrior, Talent, Mechanic] Sword Specialization - off-Target procs hit current Target

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2497]
Decription: 
An issue with the Warrior Talent Sword Specialization, which is based on which Target takes the proc's hit if you're attacking one without having it selected, but instead another one.

How it works: 
Sword Spec's procs triggered by attacks done on a non-selected Target can hit a currently-selected _different_ Target which wasn't attacked in a manner that triggers the Talent on it.

Video showcase of the bug: https://youtu.be/TQSsCJwAs4E
Used Mouseover macro attacks with Mortal Strike/Overpower etc., on a non-selected Target. One of them procced SS off it, but the hit itself went onto the currently-selected _other_ Target, as shown. This does not follow the mechanic of the proc to be anchored to the same Target which the original attack triggered the Talent on it.

How it should work: 
Sword Spec's procs are supposed to be anchored to the Target of the original attack that procced the Talent. For example if an Execute hit procs Sword Spec, the proc is supposed to go on the _same_ Target that was subjected to the Execute which triggered SS -- _even if you aren't targeting it_. See here:
https://db.darkwizard.pl/?search=Sword+Specialization#?ref=sunwell.pl
"extra attack on the **same** target"

Steps to reproduce:
1. Take Sword Spec;
2. Equip a Sword;
3. Have one victim as a selected Target, with another (within Melee Range) as a non-selected Target to attack;
4. Attack the non-selected Target while targeting the other;
5. Watch procs triggered off the non-Target hit the selected Target -- unintended, should be anchored to non-Target as it was triggered.

Additional information:
Sword Specialization IDs: https://db.darkwizard.pl/?search=Sword+Specialization#?ref=sunwell.pl

**Comment by Aridam** [comment]
Bump.

**Comment by Aridam** [comment]
https://gfycat.com/poiseddistantacornbarnacle
Still doing it.

**Comment by Riztazz** [comment]
I disagree and we will need more proof, sword specialization works this way: it procs and you're energized with additional attacks, it doesn't actually cast anything at proc target, it just sets player data and lets him know - hey, you've got X additional attacks to fire and it will get handled during players update hence you're using your proc attacks on your current victim and it is intended.

```
ID - 16459 Sword Specialization
=================================================
Description: Gives you a chance to get an extra attack on the same target after hitting your target with your Sword.
Category = 0, SpellIconID = 1462, activeIconID = 0, SpellVisual = (6560,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0.00

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 19 (SPELL_EFFECT_ADD_EXTRA_ATTACKS)
BasePoints = 1 Bonus = 1.00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```
Output of the spell that gets triggered when aura procs

**Comment by Aridam** [comment]
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

Ah, I see - - self-applied. So it was made that way. Bad wording by Blizz strikes again it seems. Sigh.

Alright, I stand corrected.

**Comment by Riztazz** [comment]
It's alright, closing then :)
