### ISSUE TITLE
[Druid, Spell, Talent] Omen of clarity not activating correctly dps loss pvp problems pls fix asap

### ISSUE THREAD

**Issue by styxel** [SunwellTracker/issues#2500]
Decription: 
Omen clarity proc doesnt seem normal its not proccing from all the abilities it used To proc on retail and other servers

How it works: 
Procs only from attacks and heals, Spell dmg

How it should work: 
Omen of clarity used to proc on retail from for example from; nature's grasp, gift of the wild, faerie fire feral (cat and bear) and even from barkskin so its should proc atleast from those abilities not sure if theres more. It was a thing to use those abilities like gotw before a pull to get free ooc before the boss fight, i am ofc not able to test if its procs from gotw since im not high enough level on angra. Omen of clarity worked fine on other private servers like on dragonblight so i dont know whats different on here? 

Earlier there was a problem with maul not proccing it so was something wierd done to it? 

Virtually any spell cast can trigger the Clearcasting, including ones with no mana cost, though not all spells will benefit from it. 
Some abilities may cause Clearcasting to trigger, but will not benefit from it or consume the buff when cast. This includes spells such as Mark of the Wild and Nature's Grasp. Thorns is considered a damage spell for this purpose, and as such will benefit from (and consume) the Clearcasting state when cast.

Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.
Curiously, characters with Dual Talent Specialization will sometimes trigger Clearcasting by activating their other talent tree.

- https://wowwiki.fandom.com/wiki/Omen_of_Clarity

How To reproduce? 
Spec In To Omen of clarity use faerie fire feral, barksin, gotw, motw, nature's grasp atleast those abilities should proc clearcasting but its not happening proc chance is about 6%

Source (you should point out proofs of your report, please give us some source): *
theres very little i could find online but i could try to search some videos if i can find any since not many people used those tricks back in wotlk.
https://vanilla-wow.fandom.com/wiki/Omen_of_Clarity
https://ptr.wowhead.com/spell=16864/omen-of-clarity?classicRedirect&fromClassic&name=omen-of-clarity#comments some people commenting about it proccing from some wierd stuff and stuff not too wierd from patch 3.0.2 to 3.3.5 etc
https://www.youtube.com/watch?v=4gyy3GSokm0 this guy uses gotw before the pull to get ooc proc then again im not sure if gotw works on your server because i cant test it atm
https://www.youtube.com/watch?v=KFMPEECCAP0 i believe this is from retail wow here he uses gotw before the pull too to get ooc proc
https://wowwiki.fandom.com/wiki/Feral_DPS_guide here one post about natures grasp usage if you search the page with ctrl+f and type in nature's grasp u should find the part "you have less than 35 Energy, use [Tiger's Fury] (or [Nature's Grasp] - which can proc [Omen of Clarity])."

https://youtu.be/WuWOFtk6JS4?t=122 video showing barkskin proccing omen of clarity while hes stunned there.

https://youtu.be/y0NI3hDZyjs?t=38 ooc proccing from cyclone just a example that the ability that makes it proc doesnt have to be a 'damagin ability" 

https://youtu.be/iCBb4fSuako?t=308  heres a clip of faerie fire feral proccing omen of clarity.

Tested on max level on Frosthold still not proccing from faerie fire feral, natures grasp or gotw, motw nor barkskin its pretty big deal for pvp and even for pve To get Those extra damages or heals. Why those abilities proc ooc If u check https://wotlk-twinhead.twinstar.cz/?spell=16810 it says physical there and same thing on faerie fire https://wotlk-twinhead.twinstar.cz/?spell=16857 no idea why barkskin procced it.

Updating with some wol reports about gotw atleast
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/x=spell+%3D+"Gift+of+the+Wild"%0D%0AAND+type+%3D+TYPE_CAST%0D%0AAND+sourceName+%3D+"Hoofarted"%0D%0Aor+spell+%3D+"Clearcasting"+AND+sourceName+%3D+"Hoofarted"

Faerie fire feral 
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+"Clearcasting"%0D%0AAND+sourceName+%3D+"Oranoss"%0D%0AOR+spell+%3D+"Faerie+Fire+(Feral)"%0D%0AAND+sourceName+%3D+"Oranoss"+&page=1

[18:05:42.211] Oranoss's Faerie Fire (Feral) fades from Volatile Ooze
[18:05:44.934] Professor Putricide's Faerie Fire (Feral) is refreshed by Oranoss
[18:05:45.067] Oranoss gains Clearcasting from Oranoss
[18:05:47.980] Oranoss casts Faerie Fire (Feral) on Volatile Ooze
[18:05:48.263] Volatile Ooze afflicted by Faerie Fire (Feral) from Oranoss

18:36:01.079] Oranoss casts Faerie Fire (Feral) on  Blazing Skeleton
[18:36:01.153]  Blazing Skeleton afflicted by Faerie Fire (Feral) from Oranoss
[18:36:01.494] Oranoss gains Clearcasting from Oranoss
[18:36:02.103] Oranoss's Clearcasting fades from Oranoss

Spell ids
https://wotlk-twinhead.twinstar.cz/?spell=16810  Nature's Grasp buffing Yourself with it should be able to proc ooc
https://wotlk-twinhead.twinstar.cz/?spell=16857 faerie fire feral cat and bear
https://wotlk-twinhead.twinstar.cz/?spell=65860 barkskin
https://wotlk-twinhead.twinstar.cz/?spell=26991 gotw almost 100% chance since it goes to many People not sure how it works does it multiply the chance of the proc like x25 etc? 
Mark of the wild should Do it too.

**So In short how it should work** 

-No ICD works correctly here
-Proc rate ~6% 3.5ppm haste affect this

-It **shouldn't** proc off HoT-/DoT-ticks unless u have tier 8 set bonus, but off spellcasts. It should also trigger from things like crafting, changing specialization, etc. - since these are considered spell casts not that important imo If its hard to code.
-It **shouldn't** proc off feral abilities **(excluding "Maul", since Maul is an auto attack with added damage)**, but off auto attacks and other spells.
-It **should** proc from MoTW/GoTW, Fearie Fire all forms so faerie fire cat, bear and human form, Nature's Grasp, innervate and barkskin, dash (thorns dmg ticks? Someone commented about this i didnt ever know about this was a thing or i didnt notice it and i have no proof about this). 
It **shouldnt** proc from shapeshifting which its not doing atm so its ok.

So pretty much anything can proc it except for feral abilities (shred, mangle etc and shapeshifting. 

Seems that most of the spells that should proc it are from nature school maybe thats a solution To something?

**Comment by ganderxx** [comment]
Can confirm this to be true not that it matters. Played on many private servers and in retail icc and in all of them i used natures grasp and faerie fire feral for ooc procs it was something that only 1/100 ferals knew and did hopefully it works on frosthold 2 days left!!!

**Comment by Lupe4js** [comment]
ooc proc is too low in general on frosthold

**Comment by Aridam** [comment]
We get it. There are many old bugs of which some rather important, which haven't been fixed yet. You can stop editing now.

**Comment by tii86** [comment]
Also thorns, application of buff and from the thorns proc. (Smart ferals would put thorns on tank for more procs)

**Comment by ganderxx** [comment]
Please fixerino should be just couple lines its annyoing bug

**Comment by Zeorgbugfinder** [comment]
when fix? its BIG problem maybe stop making custom pve raids and fix this

**Comment by enterthevoidbro** [comment]
Id like to add that this issue is VERY real and makes Balance spec with low gear in pve literally unplayable.
OOC procrate is low but i cannot confirm its ever been higher. What i 100% can confirm tho is the fact that OCC used to be able to proc off of every single hurricane hit individually, Right not it does not proc off of hurricane at all. Zero. 

PLEASE fix asap. 
thank you ♥

**Comment by styxel** [comment]
> Id like to add that this issue is VERY real and makes Balance spec with low gear in pve literally unplayable.
> OOC procrate is low but i cannot confirm its ever been higher. What i 100% can confirm tho is the fact that OCC used to be able to proc off of every single hurricane hit individually, Right not it does not proc off of hurricane at all. Zero.
> 
> PLEASE fix asap.
> thank you ♥

https://github.com/SunwellTracker/issues/issues/2641 about hurricane here cant say anything about the proc rate it should be around 6% tho propably is correct. If u played on dragonblight u might have had a better time there ooc was proccing like crazy there from hurricane.

**Comment by ganderxx** [comment]
High priority pog is it finally going to be fixed :D? Been so long feels like :(

**Comment by ganderxx** [comment]
Bump.

**Comment by Zeorgbugfinder** [comment]
its not only pvp problem but also pve
coz hurricane typhoon stafall doesnt proc clearcasting and it SHOULD
i remember having permanent clearcasting on other servers when i use starfall on more than 10mobs and here on this server im out of mana as balance druid even on OS wheres xxxxx mobs
also very big problem when spaming hurricane coz it cost too much mana and hurricane allways procs clearcasting on other servers but here it doesnt!

**Comment by styxel** [comment]
> its not only pvp problem but also pve
> coz hurricane typhoon stafall doesnt proc clearcasting and it SHOULD
> i remember having permanent clearcasting on other servers when i use starfall on more than 10mobs and here on this server im out of mana as balance druid even on OS wheres xxxxx mobs
> also very big problem when spaming hurricane coz it cost too much mana and hurricane allways procs clearcasting on other servers but here it doesnt!
> and playing pvp as balance druid its disgusting i have glyph of innervate and still oom after 3min
> 
> pls fix asap

different servers work differently hurricane procs ooc atm only from the initial cast of the spell atleast when i cast it in feral spec so it should proc atleast from that but im sure they will fix it how it should be ive heard from other servers developers that this bug is guite common and sometimes hard to fix or something like that. but hopefully it will work soon as it should.

**Comment by ganderxx** [comment]
@Riztazz u better assign this next its tough one to fix i know u can do it

**Comment by ganderxx** [comment]
Bump.

**Comment by Leenakko** [comment]
Also a bug for us Healers missing some key tricks for ooc progs and mana return with lifeblooms some1 should work on this soon been a while now no one even saying anything about fixing this?

**Comment by ganderxx** [comment]
feelbadman

**Comment by ganderxx** [comment]
bumpity bumb

**Comment by Zeorgbugfinder** [comment]
PLZ FIX

**Comment by styxel** [comment]
bump.

**Comment by Zeorgbugfinder** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEe

**Comment by Riztazz** [comment]
Cleaned up useless comments a little bit. I will take a look at the issue soon ( keep in mind it's christmas time rn :P )

**Comment by styxel** [comment]
> Cleaned up useless comments a little bit. I will take a look at the issue soon ( keep in mind it's christmas time rn :P )

Yea thats what i said but nice of you to look at still during these holiday times

**Comment by styxel** [comment]
http://www.worldoflogs.com/reports/5pDfQR0g2ZNEbKYn/details/1/?s=11582&e=11907 some log from retail? sapp he got 18ooc procs In a 5min fight nothing close to what u get on Frosthold 50+ so i believe strongly that resto ooc is proccing too much. Im not gonna spend more time searching for more proof about the resto issue tho If some1 wants to u can If its needed could probably see it also from some vids..

**Comment by Riztazz** [comment]
```
-It shouldn't proc off feral abilities (excluding "Maul", since Maul is an auto attack with added damage), but off auto attacks and other spells.
```

How come?

**Comment by styxel** [comment]
> Thorns (not aura application, thorns dealing damage to someone) proccing OOC sounds bogus as well, i'll need proof on that one

I highly believe u wont find any i have never heard about this like i said but If someone finds something then cool :O.

**Comment by styxel** [comment]
> Also thorns, application of buff and from the thorns proc. (Smart ferals would put thorns on tank for more procs)

Do u have anything more about this?

**Comment by Riztazz** [comment]
I'm not adding that part to my fix, that sounds very stupid. If it did work like that, please do show proof and ill adjust

**Comment by styxel** [comment]
> I'm not adding that part to my fix, that sounds very stupid. If it did work like that, please do show proof and ill adjust

Yeah it sound way too op since thorns tick quite often. Was there something wrong with hots btw?

**Comment by ganderxx** [comment]
Nice thanks you Riztazz its finally fixed :) any clue when its goin live?

**Comment by Riztazz** [comment]
Probably monday

**Comment by Riztazz** [comment]
@styxel I am not sure to be honest, i just scrapped entire implementation and wrote my own

**Comment by styxel** [comment]
> Probably monday

If its live monday i will be able to test it in raid In resto and feral and see If its working properly.

**Comment by styxel** [comment]
@Riztazz if the changelogs are live atm, the fix did not work.
