### ISSUE TITLE
[NPC, Buffs, Mechanic] NPCs lose Buffs/Debuffs on Evade/reset after Combat end

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#2504]
Decription: 
An issue with Training Dummies, causing them to reset Buffs and Debuffs present on them when Combat with them ends.

How it works: 
Training Dummies reset applied Buffs and Debuffs on every Combat suspension.

How it should work: 
Training Dummies are supposed to keep applied Buffs and Debuffs after Combat with them has ended.

Source (you should point out proofs of your report, please give us some source):
https://youtu.be/x5bc1viclWo?t=218
See the Warrior leaving Combat with the Dummy (new Recount log with last DW tick + Warrior losing Rage indicating loss of Combat) -- the Dummy keeps the Trauma Debuff.

Steps to reproduce:
1. Fight a Training Dummy;
2. Apply Buffs/Debuffs to it;
3. Leave Combat;
4. Note the Dummy has lost any and all Buffs/Debuffs from during the just-suspended Combat.

**Comment by Aridam** [comment]
Update: This seems to affect NPCs in general, _not just_ Training Dummies.
https://imgur.com/a/mbmeWiQ
I used First Aid on one of the Guards here, applying the Debuff that disallows them to have First Aid be used on that particular one again. After getting into Combat with a nearby Mob and killing it and removing Combat, the same Guard lost the Debuff.
Related issue from the TC bugtracker about this issue: https://github.com/TrinityCore/TrinityCore/issues/23890

**Comment by Riztazz** [comment]
There are auras that should be removed upon evade and there are auras that shouldn't be removed on evade, as of now - everything is removed because said logic of when and what happens is unknown, probably not researched attribute for a spell
