### ISSUE TITLE
[NPC Missing] Reanimated Corpse in in Zul'Drak

### ISSUE THREAD

**Issue by kmkmkm0** [SunwellTracker/issues#2506]
Decription: I usualy aoe these guy but they ain't here .

How it works: There is no mobs .
Angrathar : https://plays.tv/video/5dceb5078d2bafcb46/desert-

How it should work: Swarming area .
Trinity core (couldnt find retail on this) : https://plays.tv/video/5dceb34c7945d32e31/reanimated-corpse-

Source (you should point out proofs of your report, please give us some source): 
https://wotlk-twinhead.twinstar.cz/?npc=29897
https://wotlk.evowow.com/?npc=29897

EDIT: these fucker are great for this quest : https://wotlk-twinhead.twinstar.cz/?quest=12919

**Comment by Dootz** [comment]
mobs are there, but they are visible only in specific phase. You can see them on Trinity core because you are running with GameMaster mode on :)
