### ISSUE TITLE
[Warrior, Talent, Spell] Two-Handed Weapon Specialization and Execute

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2507]
Decription: 
Talent Two-Handed Weapon Specialization don't give bonus Dmg to Execute Damage. 

How it works: 
Talent Two-Handed Weapon Specialization 3/3 don't give 6% bonus Dmg to Execute Damage.

How it should work: 
Talent Two-Handed Weapon Specialization should work for Execute when you have 2h Weapon equiped.

Source (you should point out proofs of your report, please give us some source):
https://wotlk.evowow.com/?spell=12712
https://wotlk.evowow.com/?spell=47471

**Comment by Aridam** [comment]
Confirmed. Just tested with and without the Talent -- Damage is the same.

**Comment by BialyADI** [comment]
The same problem is on Victory Rush.

**Comment by Aridam** [comment]
What, really? The hell?
Huh, that also happens to be another Attack-Power-based Ability (exponentially scales with AP) -- like Execute.
That makes me wonder, what about the rest -- Revenge, Heroic Throw, etc.?
I can't test at the moment.

**Comment by Aridam** [comment]
<details>
<summary>Video evidence:</summary>

Execute:
https://gfycat.com/selfishnaturalhawk
https://gfycat.com/anguishedcomfortableaustraliancattledog

Victory Rush:
https://gfycat.com/hospitablecourteousangelwingmussel
https://gfycat.com/grimyoddallensbigearedbat
</details>

**Comment by Riztazz** [comment]
Execute will search for highest damage mod auras on player and applie them to Execute dmg, as far as other spells go - this is done on spell by spell basis, so please report those as well. (custom handling for specific spells, not quite sure why blizzard has done it this way, in case of execute it's due to how rage affects the damage)

**Comment by BialyADI** [comment]
The same problem again.
