### ISSUE TITLE
[Scourge Invasion]

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#251]
Decription: 
Why some elements of Scourge Invasion are enabled and some not?
[Scorn](https://db.darkwizard.pl/?npc=14693) is active in Scarlett Monastery and [Tabard of the Argent Dawn](https://db.darkwizard.pl/?quest=9341) - disabled.
And maybe it will be a good idea befor Naxx opening to make a Scourge Invasion ?

How it works: 
Why some elements of Scourge Invasion are enabled and some not?
[Scorn](https://db.darkwizard.pl/?npc=14693) is active in Scarlett Monastery and [Tabard of the Argent Dawn](https://db.darkwizard.pl/?quest=9341) - disabled.
And maybe it will be a good idea befor Naxx opening to make a Scourge Invasion ?

How it should work: 
Disable [Scorn](https://db.darkwizard.pl/?npc=14693) is active in Scarlett Monastery if it's not Scourge Invasion.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Scorn will be removed with next server update
