### ISSUE TITLE
Eating and drinking animation doesn't loop

### ISSUE THREAD

**Issue by randomuser69** [SunwellTracker/issues#2511]
Decription: 
When eating and drinking, the player character sits down and takes one bite of food or one swig of water and then just sits there.

How it should work: 
Player character should sit down and the eating and drinking animation should play on a loop until food/water aura runs out

Source (you should point out proofs of your report, please give us some source): 

Eating and drinking animation loop is blizzlike, see example below from Classic:
https://youtu.be/BQOptBBFC5A?t=1638

**Comment by randomuser69** [comment]
Oh, and this is not a client issue. This is definitely a fault serverside

**Comment by Aridam** [comment]
Confirmed. Always been a bug. Looping of animations isn't there. I've been on very-few servers with this working, so it's definite that it's not merely from the client.
