### ISSUE TITLE
[Sunstrider Isle, Texture] Fountain Water Texture Bug (on Frosthold)

### ISSUE THREAD

**Issue by biirds** [SunwellTracker/issues#2512]
**Description**: The fountain water texture on Sunstrider Isle (located near the quest item Scroll of Scourge Magic) is bugged and flickers.

**How it works**: When panning the camera around, the water texture will flicker from slightly brighter to nearly black.

**Comment by Azathothh** [comment]
It's client related issue, it's not server side.
