### ISSUE TITLE
Spirit Tap (Talent Priest) pls fast fix

### ISSUE THREAD

**Issue by Sunwellxd** [SunwellTracker/issues#2513]
Decription: 
https://wowwiki.fandom.com/wiki/Spirit_Tap
How it works: 
sometimes gives a bonus in rank 3 after killing a target that yields experience or honor.

How it should work: 
always gives a bonus in rank 3 after killing a target that yields experience or honor.  it is 100% chance.

Source (you should point out proofs of your report, please give us some source): 
as in the description of the talent

kill the mob and check if you get the buff

**Comment by Azathothh** [comment]
I've killed 50 mobs granting experience and it was refreshed every time.

"This requires the priest to get the killing blow, which will rarely happen if the priest is in a group as healer unless the priest has impeccable timing. This becomes somewhat easier after level 62 with the advent of Shadow Word: Death. " Maybe problem is that you're not dealing killing blow?

**Comment by Sunwellxd** [comment]
Please for a movie, because for me nothing works. 
ps.I can record a movie if you need
