### ISSUE TITLE
Kurenai reputation issues

### ISSUE THREAD

**Issue by Wheelbur** [SunwellTracker/issues#2516]
Decription: 
The prequests for kurenai in zangarmarsh are not awarding enough reputation.

How it works: 
The quests in Orebor Harborage that are prequests to get friendly with Kurenai are only awarding 250 reputation. Plus killing the ogres in nagrand only awards 5 reputation.

How it should work: 
The quests should give 500 reputation each and killing ogres should give 10 reputation each. Right now the quests are not enough to get friendly, you need to farm some ogres as well. For some reason the reputation gain is halved.

Source (you should point out proofs of your report, please give us some source): 
As you can see in the screenshots provided I received 5 reputation for ogre kills and 275 rep for quest since I am human with 10% rep bonus. This is too low to get friendly from the quests alone which should be possible.
![WoWScrnShot_111819_093851](https://user-images.githubusercontent.com/57897064/69045220-badef480-09f6-11ea-98a7-c335963fe23f.jpg)
![WoWScrnShot_111819_093909](https://user-images.githubusercontent.com/57897064/69045224-bdd9e500-09f6-11ea-95ac-0260a5289394.jpg)

**Comment by Jonsse** [comment]
Though such a small issue, the effect is quite jarring. You're left 100(400) repuation short in Orebor Harborage to continue the quests there and without means of getting more other than moving to Nagrand.
