### ISSUE TITLE
Polymorph on polymorphed targets behaviour

### ISSUE THREAD

**Issue by tii86** [SunwellTracker/issues#2517]
**Decription:** 
Polymorph should be castable on targets that are under the effects of a polymorph spell. Under certain conditions, it is not castable.

full duration polymorph = 10 seconds
1/2 dr polymorph = 1/2 duration polymorph = 5 seconds
1/4 dr polymorph = 1/4 duration polymorph = 2.5 seconds

**Importance:** Being able to essentially spam cast polymorph on pvp targets is important since it gives more control ability to the mage. If a second polymorph is cast immediately following the first, the mage is rewarded for their prediction by immediately punishing the opponent with a 1/2 dr polymorph.  

**How it works:** 
Currently, on a pvp target, if a target is polymorphed, you can cast polymorph under certain conditions. If there is 5 seconds or less left on full duration poly, you can cast polymorph and 1/2 dr will be applied. If there is less than 2.5 seconds left on 1/2 dr polymorph, then 1/4 duration polymorph is applied.

**How it should work:** 
Should be able to cast polymorph on targets that are under the effect, regardless of duration remaining on current debuff.

**Pve behaviour**: refreshes to max duration. (functions correctly on frosthold)
**Pvp behaviour**: this is more complex, depends on duration of polymorph effect currently applied to target. 
Essentially you should be able to polymorph a target, then if a second polymorph is cast right after the first cast (ie current debuff >5 seconds), nothing should happen (but the cast should go off!). (Unless the player under effect uses pvp trinket, then 1/2 dr poly is applied) 

However, if the cast is done after 5 seconds, the polymorph will be refreshed at 1/2 dr. On a 1/2 dr polymorph, casting poly on a target with less than 2,.5 or less seconds left on current poly will result in 1/4 dr polymorph being applied. I believe warlock fear has the correct implementation of this mechanic, for comparison. 

**Source:** 
Blackrock (warmane) has the right functionality. If a historical source is required, please let me know and I will look.

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/1519
It was working correctly on Angrathar, probably broke with some recent changes.

**Comment by tii86** [comment]
It was slightly different on angrathar then the behaviour I described, where casting a second polymorph into a full duration poly would result in a 1/2 dr poly being applied, regardless of the duration on the initial polymorph. 
I suspected  this was also incorrect since warlock fear did not behave like this on angrathar, as well as the difference of scripting on warmane. I’ll try to find a source for this.

**Comment by buugss** [comment]
Yes please fix this annoying bug

**Comment by Riztazz** [comment]
Got a little bug with a fix so it has been postponed till tomorrow, gotta fix it first

**Comment by Riztazz** [comment]
Alright, fix is going live in 30 minutes from now - please test and if there is any issues left, let me know in this issue and i'll reopen
