### ISSUE TITLE
[Mage][Talent] Fingers of Frost

### ISSUE THREAD

**Issue by alycai** [SunwellTracker/issues#2518]
Decription: 
The talent is not blizzlike 

How it works: 
right now if you have only 1 remaining fof proc you are not able to ''shatter'', ie frostbolt-brainfreeze, frostbolt-icelance, or frostbolt-deepfreeze and both spells benefit from the single fof proc.

this is well known among mages that played during wotlk

'' Since Frostfire Bolt benefits from Ice Shards and Shatter, it is ideal to use its instant-castability immediately after the second Frostbolt during a Fingers of Frost proc.  Since the last Fingers of Frost charge is not consumed until the second spell hits the target, both the Frostbolt and the Frostfire Bolt will benefit from Fingers of Frost, resulting in what is commonly known as a Shatter Combo. ''

How it should work: 
The final FoF proc should still allow for any instant cast spell chained with a frostbolt to both benefit from the last FoF proc

Source (you should point out proofs of your report, please give us some source): 
https://frostisthenewblack.wordpress.com/2010/01/19/3-3-frost-mage-raiding-cheat-sheet/

I will edit for videos once i find them

**Comment by alycai** [comment]
sorry for my bad spelling; i tried to correct it,

note that this is similar to this report:
https://github.com/SunwellTracker/issues/issues/2469

''FoF stacks get consumed too fast so you can't do Frostbolt>DF combo with just one FoF stack what's not correct.''

''Proof that FoF stacks should NOT get instantly consumed on cast - https://youtu.be/8ET2Ct9_Ma8?t=1m6s ; https://www.youtube.com/watch?v=4X-GB9GB7Ic. In these videos you can see mage doing Frostbolt > DF with just one FoF stack. Watch in slow motion.''

**Comment by Taximan** [comment]
this is a very game breaking issue for frost mage pvp

**Comment by Sunaqt** [comment]
up!
huge bug for frost pvp

**Comment by keelash123** [comment]
I was so tilted ingame by this bug that i even register here to report it but then i notice some pple make work for me thanx god. This bug is so damn gamebreaking i stil dont understand why this is not fixed yet, it absolutly kiled frostmage pve and rly hurt him pvp. If they dont fix it till nax cames out ill quit, i dont understand why this is not prioritize to fix.

**Comment by keelash123** [comment]
I think stacks should be consumed after spell cast is finished but after spell lands on target.

**Comment by Piootrek** [comment]
Fixed, will be live after next update.
