### ISSUE TITLE
Gift for the warchief

### ISSUE THREAD

**Issue by fmxrider** [SunwellTracker/issues#252]
![wowscrnshot_020518_125259](https://user-images.githubusercontent.com/36165936/35816426-f8a1e2ee-0a9a-11e8-9514-540cfa6df003.jpg)
Decription: 
Gift for the warchief event daily quest doesn't give any experience points.

How it works: 
no exp

How it should work: 
![wowscrnshot_020518_125254](https://user-images.githubusercontent.com/36165936/35816420-f3eea4f8-0a9a-11e8-8d04-4be24cb12d25.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
#219
