### ISSUE TITLE
[NPC, Quest] Basic Chemistry/Neutralizing the Plague - summoned Mobs don't despawn

### ISSUE THREAD

**Issue by Aridam** [SunwellTracker/issues#2521]
Decription: 
An issue with every summoned Mob from the Plague Cauldrons while doing the "Basic Chemistry" and/or "Neutralizing the Plague" Quests, leading to said Mobs not despawning if not engaged and killed.

How it works: 
Mobs summoned by the Plague Cauldrons while doing the "Basic Chemistry" and/or "Neutralizing the Plague" Quests don't despawn if not engaged and killed. This allows for hundreds of them to be kept spawned every time the "Something emerges from the cauldron" message pops up, and potentially cause server instability over time. Furthermore, if this is present, this can make clearing the chamber of said abandoned Mobs impossible, disallowing Players the ability to do the Quests.

How it should work: 
Those Mobs should despawn after a while if left alone for a long period of time.
The amount of time needed for them to be left alone for their despawn to kick in is unknown to me as of right now -- cannot seem to find information on it.

Steps to reproduce:
1. Take up "Basic Chemistry" and/or "Neutralizing the Plague";
2. Have a Pustulant Spinal Fluid in your Inventory;
3. Go to the top of Mord'rethar -- where the Plague Cauldrons are inside the chamber there;
4. Use the Spinal Fluid;
5. Wait for the "Something emerges from the cauldron" message -- Mobs will be spawned;
6. Do not engage any of the Mobs, _especially do **not** kill them_;
7. Keep waiting for the "Something emerges from the cauldron" message (repeat the process with the Spinal Fluid when necessary, _but do not complete the Quest else it'll stop doing it_);
8. You should now have an ever-increasing number of summoned Mobs -- being left alone for any amount of time doesn't result in them being despawned. Possible eventual server instability if this is repeated too many times.

Additional information:
<details>
<summary>Affected NPCs:</summary>

Living Plague NPC ID: https://db.darkwizard.pl/?npc=32181
Rampaging Ghoul NPC ID: https://db.darkwizard.pl/?npc=32178
Plague Drenched Ghoul NPC ID: https://db.darkwizard.pl/?npc=32176
</details>

Basic Chemistry Quest IDs:
- Horde: https://db.darkwizard.pl/?quest=13279
- Alliance: https://db.darkwizard.pl/?quest=13295

Neutralizing the Plague Quest IDs:
- Horde: https://db.darkwizard.pl/?quest=13281
- Alliance: https://db.darkwizard.pl/?quest=13297

**Comment by Riztazz** [comment]
Could you move this issue to previous issue ticket about that quest? I'll fully rewrite that quest

**Comment by Aridam** [comment]
[This one?](https://github.com/SunwellTracker/issues/issues/2488)

**Comment by Riztazz** [comment]
Thanks, gonna close this one then
