### ISSUE TITLE
Tauren Herb Racial works incorrectly

### ISSUE THREAD

**Issue by mannewdan** [SunwellTracker/issues#2522]
How it works: 
Tauren herb racial currently increases herb level by 15. This part is correct. It does NOT increase the skill cap per herb like it should.

How it should work: 
A non-tauren gathering peacebloom sees peacebloom turn yellow at level 25. A tauren is supposed to see it turn yellow at level 40.

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Cultivation

**Comment by Aridam** [comment]
"Your chance to gain a skill point while picking a herb is based on your base (without Cultivation) Herbalism skill, while the minimum skill required to pick a herb takes Cultivation into account. This means that a tauren player needs the same total Herbalism skill as other players to pick a particular herb, but will continue to gain skill from picking it longer than other players would. For example, if a herb normally requires 100 Herbalism skill to pick and gives skill up to 150 skill, a tauren player would need 100 skill (including Cultivation) to pick it and would continue to gain skill from picking it up to 165 skill."

https://www.reddit.com/r/classicwow/comments/b74r82/what_is_the_purpose_of_the_tauren_racial/ejp8v0a/
https://www.reddit.com/r/classicwow/comments/b74r82/what_is_the_purpose_of_the_tauren_racial/ejp8snj/

Seems on-point.

**Comment by Riztazz** [comment]
This is actually not an issue, client handles displaying herb state (gray, green, yellow etc). Server-side we pick a skill value without bonuses (cultivation) when skill-up chance is calculated.
What it means is you still have a chance for a skill-up even tho it shows gray for you
