### ISSUE TITLE
[hunter] pet abilitites wont enable pet autoattack

### ISSUE THREAD

**Issue by blazetrooper** [SunwellTracker/issues#2523]
How it works: using pet skills manually wont start pet autoattacking and pet returning back to hunter after ability was used.

How it should work: Any offensive pet ability should enable pet autoattacking on targeted mob.

**Comment by Azathothh** [comment]
That's how it should work if your pet stance is set to Passive - what you're writing is correct for aggresive/defensive stances, and that's how it works.

**Comment by blazetrooper** [comment]
> That's how it should work if your pet stance is set to Passive - what you're writing is correct for aggresive/defensive stances, and that's how it works.

Can i ask for source of this info? Sunwell is the only place where pet movement working like that. What i am writing working on every wow server/client, including retail bfa and wow classic. I can't imagine situation when you want use offensive pet ability (like bite, ravage, growl) without enabling pet autoattacking. Pets have two different types of skills: physical and magic, physical attacks should enable autoattacking (like scourge strike) and magical skills shouldn't (like chains of ice).
