### ISSUE TITLE
[Shaman][Spell] Ghost wolf speed is the same as basic mount speed

### ISSUE THREAD

**Issue by Megraxon** [SunwellTracker/issues#2526]
Decription: When i use ghost wolf, i run at the same speed as on basic 60% mount

How it works: When i use ghost wolf, i run at the same speed as on basic 60% mount

How it should work: Ghost wolf should run at 40% speed, mount on 60%

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Are you sure about this?
Use this:

/run print(GetUnitSpeed("player") / 7 * 100);

Do it once while _running straight_ in Ghost Wolf Form, and then _again_ on a 60% Mount. Report back with what the prints in the chat say.

Script while running in Ghost Wolf Form should print 140.00000272478, and while on a 60% Mount, it should be 159.99999727522.

**Comment by Riztazz** [comment]
There are items as well that increase ghostwolf speed, so please do check those

**Comment by Megraxon** [comment]
it prints correct values, so it was probably just optical illusion, sorry
