### ISSUE TITLE
Quest [Kaw the Mammoth Destroyer] ID 11879

### ISSUE THREAD

**Issue by Lunasoll** [SunwellTracker/issues#2528]
Decription: 
One of the chain quests in Borean Tundra for D.E.H.T.A where  you need to kill Kaw the Mammoth Destroyer and loot an item

How it works: 
If you're in a group with 2 or more players, when the NPC is killed, only one player can loot the item. 

How it should work: 
The NPC should be lootable by all players in the group. 

Source (you should point out proofs of your report, please give us some source): 
I don't have a source but in these kind of quests where you kill one 'elite' NPC with long respawn time, usually all players loot the item.

**Comment by Aridam** [comment]
Actually, he's supposed to drop Kaw's War Halberd as a World Object next to himself, upon dying, for a short period of time -- looting _that_ is supposed to give you the Quest Item to be able to complete the Quest.
https://youtu.be/S9Amt8EJ8ZU?t=98
https://youtu.be/mnyhwHHth00?t=109

This is triggered when he dies:
https://db.darkwizard.pl/?spell=46310
which spawns the Object:
https://db.darkwizard.pl/?object=188066
which contains the actual Quest Item:
https://db.darkwizard.pl/?item=35234#contained-in-object
