### ISSUE TITLE
[Mage / Self buffing] Dampen Magic does not replace current Amplify Magic self buff 

### ISSUE THREAD

**Issue by vitasse** [SunwellTracker/issues#253]
Decription: 
When mage (player) has self casted [Amplify Magic](https://db.darkwizard.pl?spell=1008) buff, his own spell [Dampen Magic](https://db.darkwizard.pl?spell=604) can't be casted on himself. The game reports an error: "There is more powerful spell already active.". It's tested for Dampen Magic and Amplify Magic rank 1 on a player casting a spell on himself. 

Race / gender / level combo if it matters .... Undead female 20,21lvl.

P.S. Mage's spell Amplify Magic can override current and existing Dampen Magic self buff (as it should / works properly).
P.P.S. The issue is not tested if the bug occurs for other's players buffs (for e.g. mage tries to buff Dampen Magic with existing Amplify Magic buff (of the same rank) on another player.

How it works: 
Prereq. #1: Mage has self casted Amplify Magic buff (tested for rank1 spell)
1. Mage attempts to cast Dampen Magic buff on himself (tested for rank1 spell)
2. Game reports error massage: "There is more powerful spell already active."
3. The spell fails to apply as self buff
(4.) Amplify Magic remains as current and existing buff with the same duration.

How it should work: 
Prereq. #1: Mage has self casted Amplify Magic buff (presumably rank1 spell)
1. Mage attempts to cast Dampen Magic buff on himself (presumably rank1 spell)
2. Mage's existing Amplify Magic self casted buff is replaced by mage's Dampen Magic buff with full duration
(3.) Mage has a new Dampen Magic buff (instead of Amplify Magic -> only one of the two can be active on a player)

Source (you should point out proofs of your report, please give us some source): 
1. I will add screenshots later.
2. You can test it yourself.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
