### ISSUE TITLE
Auto shot when changing targets

### ISSUE THREAD

**Issue by sifiuocz** [SunwellTracker/issues#2536]
Decription: 
A huge issue for all the hunters.

How it works: 
When changing targets via tab-targeting and target clicking your character is still shooting the previously targeted NPC/player.

How it should work: 
When you have your auto shot turned on you always attack your currently targeted NPC/player.

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Related issue off the Sunwell TBC bugtracker -- same issue, but fixed there:
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2211
