### ISSUE TITLE
Quest: Ebon Blade Prisoners

### ISSUE THREAD

**Issue by Jonsse** [SunwellTracker/issues#2537]
Decription: A quest in Icecrown: Ebon Blade Prisoners. You gather keys from the mobs in the area and release Ebon Blade Knights.

How it works: Everything about the quest works except the Knights that join as your guardians after release. If you do combat with them they lock you in to combat. I was stuck in combat even after I let them get killed the combat still remained.

How it should work: Obviously the combat should drop. The area is only accessible by flying, so being stuck in combat maroons you to that area.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/rdelZSN

Addendum: It might be linked with the Proto-Drake rider daily quest in the same area.

**Comment by Azathothh** [comment]
Haven't noticed anything weird about them. 
I'm pretty sure that your combat bug was related to Jotunheim Proto-Drake from quest [Shoot 'em Up]

**Comment by Jonsse** [comment]
I think that's highly likely too. I was put in combat and stuck in it without being in combat with the proto-drake riders at the time. I had shot at them earlier while doing the quest and having dropped combat from them for the time being. Then afterwards fighting vrykul mobs with the death knights  in tow put me in combat for quite a long time.
