### ISSUE TITLE
Intercept is Parry-able

### ISSUE THREAD

**Issue by Vaxsysl** [SunwellTracker/issues#2538]
Decription: 
Doing a battleground I realized that Intercept got parried, and I remained where I was. I checked recount and indeed it was so. I guess that this is a result of recent changes made to the ability?

How it works: 
Intercept can be parried... probably dodged and blocked as well, when it should only be able to miss. Further testings are required with both it and Charge.

How it should work: 
Intercept cannot be dodged, blocked or parried - it can only miss on target if player lacks hit; or receive immune message if the target is immune to stuns, while damage is still applied and we still move towards our target.

Source (you should point out proofs of your report, please give us some source): 
No proof, but I'm 100% convinced that Charge and Intercept should not be working like that, I can't  ever recall "avoiding" it on my tank during WotLK retail era nor have I EVER seen it happening in my career. It's like saying you can dodge backstab while not being an NPC.
![WoWScrnShot_112019_214814](https://user-images.githubusercontent.com/5100071/69278138-0275a400-0be2-11ea-93a2-008abe986fef.jpg)

**Comment by Aridam** [comment]
Hmmm. Interesting.
Gonna have to test a bunch, but I'm pretty sure it's the same as it's been.

However, there _is_ one doubt: did you use Intercept on a Hunter using Deterrence?

**Comment by Aridam** [comment]
Confirmed the bug Intercept can be Avoided.
Fought [these](https://db.darkwizard.pl/?npc=27117) for their [weaker](https://db.darkwizard.pl/?spell=31567) Deterrence (it's not the real deal) -- I got a Dodge, with the Stun and Damage failing, _but_ I still rushed into it.

I need a test VS the _actual_ Hunter Deterrence that's supposed to Parry/Deflect stuff for further diagnosis.

**Comment by Vaxsysl** [comment]
@Aridam No, it was on rogue in this case.

**Comment by Aridam** [comment]
Erm, odd. Maybe it's more specific to just Parry/Deflect. I'll have to go back to test more until I get a Parry then.

**Comment by Aridam** [comment]
So I just came back with results.
I dueled a Hunter, told them to use Deterrence, then I used Intercept.
Intercept got fully-Parried -- both Stun _and_ Damage. **That's intended.** Although, unlike what you said, _I still rushed into the Hunter_. **So that also works.**

Unless it's something that _forces_ specific attacks to get Avoided just like Deterrence does against most, you're still right that it shouldn't be Avoided under normal circumstances -- that's already been confirmed as previously-stated here. However, I cannot reproduce the other issue.

Were you perhaps struck with a movement-altering CC (Root, Disorient, Fear etc.) at the time of that happening on your end? If so, then it's related to [this](https://github.com/SunwellTracker/issues/issues/2529).

**Comment by Vaxsysl** [comment]
Yes, I'm quite sure that I was not affected by any effect on the start of my ability. I was fighting another warrior and an enhancement shaman; the rogue revealed himself on healer so I intercepted with intention to Disarm and give some space. The healer was facing my direction so rogue was facing me; I saw "Parry" and I didn't move an inch. I took screenshot right after the fight.

**Comment by Aridam** [comment]
Gonna need video evidence next time it happens or the next-best thing to prove it accurately. I can't reproduce this.

**Comment by Vaxsysl** [comment]
I don't tend to record, but I'll see what I can do. Meanwhile screenshot of seeing "parried" under recount is the best I can do. Hunters don't have deterrence this early ;).

**Comment by Aridam** [comment]
Yeah they can get it starting from L60.

**Comment by Vaxsysl** [comment]
![WoWScrnShot_112219_230051](https://user-images.githubusercontent.com/5100071/69463489-ffaeb680-0d7b-11ea-9e1c-d0e99f16eff5.jpg)
Intercept got Dodged in the middle of combat in Scarlet Monastery.

**Comment by Aridam** [comment]
Did it still move you to the Target nonetheless?

**Comment by Vaxsysl** [comment]
Think it did this time.

**Comment by Aridam** [comment]
Okay, but keep in touch. So far at least normal-circumstance Parry/Dodge is confirmed bugged.

**Comment by BialyADI** [comment]
Bump!

**Comment by BialyADI** [comment]
![WoWScrnShot_112719_070003](https://user-images.githubusercontent.com/5780624/69697776-cc558a00-10e3-11ea-911e-55426bc92f90.jpg)
