### ISSUE TITLE
Post-partum Aggression

### ISSUE THREAD

**Issue by Woodyxd** [SunwellTracker/issues#254]
Decription: 
On the quest Post-partum Aggression in Sholazar Basin (42,28)  you are to mount a mammoth and kill Broodmother Slivina then turn in.

How it works: 
You mount the mammoth and kill her yet you don't get kill credit due to the npc with you doing over 50% of her hp.

How it should work: 
Npc with you should have his dmg scaled down and the mammoths scaled up so you can get kill credit.

Source (you should point out proofs of your report, please give us some source): Spoke to GM Tide and he informed me on the problem and how to quick fix it by dismounting the mammoth and soloing it normally, but for the purpose of the quest this should be fix
![wowscrnshot_020518_103808](https://user-images.githubusercontent.com/36167792/35819689-b40a87ce-0a60-11e8-9e77-d44577662fd4.jpg)
ed.

**Comment by Riztazz** [comment]
Issue will be resolved with next update.
