### ISSUE TITLE
[Quest] Reconnaissance Flight

### ISSUE THREAD

**Issue by syk7** [SunwellTracker/issues#2540]
Decription: 
The vehicle doesn't take damage nor does the the landing button work.

How it works: 
The plane doesn't take damage and can be taken anywhere in Northrend

How it should work: 
Should be timed via the plane taking damage and the landing button should allow you to end the quest once at the appropriate location

Source (you should point out proofs of your report, please give us some source): Verified by a GM in-game

**Comment by Azathothh** [comment]
Seems like it's not using https://db.darkwizard.pl/?spell=52255 when plane is on "global cooldown" at the moment when it should be set on fire (at least that's how i could reproduce it)

**Comment by Dootz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/92ac6ca0fee08d22fb6d49adb231250920d2043a
