### ISSUE TITLE
Mob aggro in the world

### ISSUE THREAD

**Issue by MonsterDooty** [SunwellTracker/issues#2542]
Description:  Regarding mobs outside of instanced zones - Enemies do not come as a group when doing single target pulls, but rather the mob targeted comes by itself.  This is seen on 95% of the mobs I've come across in the world.  Even when the enemies themselves are all in the same category.  

How it works:  When pulling a group of enemies, individually targeting a single mob will pull just that enemy without the rest coming.

How it should work: When pulling a group of enemies, individually targeting one single mob to pull should bring the whole group together

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Chain pulling is currently disabled, as we are reworking it

**Comment by MonsterDooty** [comment]
Any ETA on when it will be implemented?  Kind of wild to remove a mechanic like that?
