### ISSUE TITLE
Shaman totems can receive heal

### ISSUE THREAD

**Issue by sefamurat** [SunwellTracker/issues#2548]
Decription: Failure of self cast when targeting a totem and healing

How it works: When the player targets their own totem and casts heal, it tries to heal the totem which then says "immune"

How it should work: It should consider totem an invalid target for heal and instead heal the user

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
Can you attach any proof please.

**Comment by nueschts** [comment]
Maybe this this will can be used as proof?

https://wowwiki.fandom.com/wiki/Patch_3.0.8
 Shaman
  "Chain Heal: This spell will now give an invalid target error message if the primary target is a totem."
