### ISSUE TITLE
Hunter pet aggro [growl] underpowered

### ISSUE THREAD

**Issue by Stokes2015** [SunwellTracker/issues#2549]
Decription: 

I have played several different specs and chosen different pets with hunter and my pet can't hold aggro at all. Every mob instantly changes to attack me. 
How it works: 
The growl isnt strong enough with serpent, ravager, cat

How it should work: 
It should hold aggro until you are MM or Surv lvl 80 and geared doing massive damage with your shots. I never had this issue on 3 hunters on Angrathar / Dragonblight.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Lack of informations/proofs/any data.

Growl (pet) | +1234 base (rank 9) to pet, scales with pet attack power and level
https://wowwiki.fandom.com/wiki/Threat
