### ISSUE TITLE
Rogue: Envenom buff doesn't work when you overkill mobs

### ISSUE THREAD

**Issue by pawelox01** [SunwellTracker/issues#2553]
Decription: 
Normally this skill gives you buff for 1 second, but each combo points increase this time by 1 sec. Normally when I fight mobs and use this skill with 5 CP it gives me +5 second buff, but everytime when I overkill mob with this skill, no matter how many combo points I build it always goes down to 1 second
and I think it should gives me +5 second time with 5 CP no matter if I overkill mobs or just hit them

How it works: 
When you kill mobs with Envenom skill with combo points, it gives only a basic buff time which is 1 second, no matter how many combo points you had

How it should work: 
When you overkill mobs with envenom skill with let's say 5 combo points it should give total 6 second buff (1 sec basic and +5 sec from 5 combo points)

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2543
