### ISSUE TITLE
Quest: Battling the Elements (Frosthold)

### ISSUE THREAD

**Issue by Jonsse** [SunwellTracker/issues#2554]
Decription: 
Quest: Battling the Elements (Storm Peaks) 
The quest mobs: Seething Revenants, have a significant spawn time which is unconventional for a special vehicle quest event, and for this particular quest is just plain incorrect. There also seems to be only 5 spawns, for a quest that requires you to kill 10.

How it works: There are only 5 spawns and they take a significant amount of time to respawn.

How it should work: There should be more spawns, around 12, in the area around the anvil and they should respawn quite quickly. A singular player should not be able to kill all the spawns before the first one is back up.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/XkGrvuj (The area is clear of mobs as a horde player is attempting to do it)

**Comment by Aridam** [comment]
Retail Wrath video: https://www.youtube.com/watch?v=aRwHz4r3NdQ

**Comment by Jonsse** [comment]
> Retail Wrath video: https://www.youtube.com/watch?v=aRwHz4r3NdQ

Notice how the date is before Wrath launch date, meaning that video is from the beta. The UI is wrong as well, achievement tracking has a bar instead of just numbers.

**Comment by Aridam** [comment]
Check post-Wrath videos top if you want. Pretty much the same.
