### ISSUE TITLE
[Priest] Unable to use Shadowform while Wintergrasp battle is in progress

### ISSUE THREAD

**Issue by lkrocek** [SunwellTracker/issues#2562]
Description: 
This bug happened to me just once, so not sure if it's 100% if I will mention all points to reproduce it.

Steps to reproduce: 

1. queue RDF Northrend heroics 
2. travel to Wintergrasp shortly before the start I did like 10mins before
3. hit "Yes" to add into the queue
4. RDF popped up shortly and accept it and get in (there was DrakTharon Keep HC)
5. since WG started hit decline to stay in heroic dungeon
6. since you get out from Shadowform you cannot go turn it on again, /reload didn't help, didn't try relog, because wasn't sure if I will lose the RDF bonus reward and it was saying you can't use it at the moment. I tried to respec to discipline and back to shadow on place (dual-spec) but didn't help as well.

we few times wiped and when I get back into WG it started working again so no relog at all.

**Comment by Riztazz** [comment]
When did you encounter that issue? We rolled a fix for that case today morning

**Comment by lkrocek** [comment]
not today for sure, but not sure if it was yesterday or the previous day.

**Comment by Riztazz** [comment]
Alright then, i'm pretty sure that issue has been fixed before you made a report :P If it occurs again, please open another ticket and just copy this issue in new ticket and i'll take care of the rest.

Closing for now since i'm 99% sure it won't occur again
