### ISSUE TITLE
Crit healing while sitting

### ISSUE THREAD

**Issue by Zylienlol** [SunwellTracker/issues#2563]
Decription: 
You get 100% crit on heals while a person is sat down. This work on aoe healing and singel target.

How it works: 
A person sits down and you heal them. 100% Crit chance on them

How it should work: 
Not 100% crit chance on a person that is sitting

Source (you should point out proofs of your report, please give us some source): 
On classic wow and retail wow you don't have 100% Crit chance on person that sits down.

**Comment by Aridam** [comment]
Must've become a thing following the fixes on receiving attacks while sitting. Confirmed.
