### ISSUE TITLE
Envenom consuming deadly poison in spite of having 3/3 Master Poisoner

### ISSUE THREAD

**Issue by alxmke** [SunwellTracker/issues#2568]
Decription: 
Envenom consuming deadly poison in spite of having 3/3 Master Poisoner

How it works: 
Envenom consumes deadly poison stacks in spite of having 3/3 Master Poisoner.

How it should work: 
Envenom should not consume deadly poison while having 3/3 Master Poisoner,

Source (you should point out proofs of your report, please give us some source): 
https://wotlk-twinhead.twinstar.cz/?spell=58410
and your in-game tootlip for Master Poisoner indicates it as well

**Comment by Riztazz** [comment]
That's weird, could you try again after relogging?

**Comment by Azathothh** [comment]
Couldn't reproduce it - please add more informations / proofs if you're sure that it's happening to you and i'll reopen.
