### ISSUE TITLE
Earthbind Totem - no Diminishing Returns in PvP

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2569]
Decription: 
Earthbind Totem Root from Ele shaman dont have Diminishing Returns.

How it works: 
Ele can Root for 5s every 10s

How it should work: 
Earthbind Totem Root shoud have normal Diminishing Returns like Frost Nova.

Source (you should point out proofs of your report, please give us some source): 
http://www.skill-capped.com/guides/shared_drs.php

**Comment by BialyADI** [comment]
https://wow.gamepedia.com/Earth%27s_Grasp

**Comment by Azathothh** [comment]
Any proofs that it had DR during wotlk?
According to http://www.arenajunkies.com/topic/170817-earthbind-root-dr/  there were no DR for it during wotlk.

**Comment by BialyADI** [comment]
On that SkillCapped page is everything. How is it possible that Earth's Grasp totally has no DR, its make no sense.

**Comment by Azathothh** [comment]
On that SkillCapped page it doesn't say anywhere that it's data from wotlk. It can be data from Cataclysm (in Cataclysm DR on Earthbind Totem worked) or other expansions.
Some video from wotlk would be cool

**Comment by Aridam** [comment]
http://www.arenajunkies.com/topic/170817-earthbind-root-dr/
The mentions pre-4.0 say that there was no DR. When 4.0 (Cata) came, Earthgrab was changed to have DR. Before that (WotLK and prior), it didn't have DR.
https://github.com/TrinityCore/TrinityCore/issues/7037

From a previous report: https://github.com/SunwellTracker/issues/issues/1395

https://github.com/TrinityCore/TrinityCore/pull/11072
