### ISSUE TITLE
Warlock ability interactions with hand of protection

### ISSUE THREAD

**Issue by KimmoKM** [SunwellTracker/issues#257]
Decription: 
While doing dungeons, I've noticed several oddities while having been buffed with Hand of Protection (I'm afraid I haven't tested this with systematically in controlled environment, but I am fairly confident there's no mistake here). Firstly, I can't seem to order minions (felguard to be specific) to attack through pet commands, although aggressive stance works. Secondly, HoP appears to make the warlock immune to gaining Decimation effect. Suffice to say, this shouldn't be the case.

Other abilities and classes may be similarly affected.

Source (you should point out proofs of your report, please give us some source): 

According to Hand of Protection description, the spell causes the target to be "protected from all physical attacks for 6 sec, but during that time they cannot attack or use physical abilities". Neither pet attack command or spell procs fit the description.

**Comment by Kokaina** [comment]
Probably affects not only lock proc spells but wholes classes.

**Comment by sicknot1** [comment]
Use HoP on a hunter and see if pet can be commanded

**Comment by set-theorist** [comment]
I can confirm not being able to petattack, also happens with hunters.

**Comment by Akha72** [comment]
Was not able to use a Healthstone while under the effect of HoP.

**Comment by akrom23** [comment]
Looks okay.

**Comment by danniellos94** [comment]
Opening since I still dont get decimation on hop.
