### ISSUE TITLE
Swipe Cat Form in Frosthold

### ISSUE THREAD

**Issue by vinera30** [SunwellTracker/issues#2571]
Decription: 
I can't learn "Swipe (cat)" from a trainer.

How it works: 
This skill is not available to the trainer. It should be available from level 22.

[https://wowwiki.fandom.com/wiki/Swipe_(Cat)](url)

**Comment by tii86** [comment]
This isn’t true. Swipe cat was introduced in wotlk and is learned at lvl 71 I believe.
