### ISSUE TITLE
Bugged Warlock spells

### ISSUE THREAD

**Issue by Rizitrix** [SunwellTracker/issues#2573]
Decription: 
 [Backlash]
 [Soul Link]

How it works: 
So [Backlash] dont proc from spells
[Soul Link] Transfear to much damage to pet and ones hot it
How it should work: 
[Backlash] Should proc atleast ervrey 8 sec from spells/melee
[Soul Link] should trasnfear 20% and not more, which it does
Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
"So [Backlash] dont proc from spells"
![obraz](https://user-images.githubusercontent.com/37483678/70474481-fab76a00-1ad2-11ea-989d-07b98a852286.png) ![obraz](https://user-images.githubusercontent.com/37483678/70474724-6994c300-1ad3-11ea-9844-5d5d425ca17c.png)
Looks fine.

"[Soul Link] should trasnfear 20% and not more, which it does"
![obraz](https://user-images.githubusercontent.com/37483678/70474944-ce501d80-1ad3-11ea-86bd-273a5d946570.png)
tested with spell which does always same amount of dmg - in this case it was 550  and 20% of 550 is 110 and that's exactly how much dmg Soul Link was transferring.
