### ISSUE TITLE
Auction house extra mail

### ISSUE THREAD

**Issue by tii86** [SunwellTracker/issues#2574]
Description: 
When your auctions sell you receive two pieces of mail instead of 1.

How it works: 
You first receive a payment pending letter when your auction sells, then some time later you receive a second piece of mail with the gold. 

How it should work: 
Once the second piece of mail with the gold is received, the payment pending letter should be deleted automatically. Additionally, once the gold has been collected from the second letter, the message carrying it should be removed from your mailbox.

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2426
