### ISSUE TITLE
[Paladin] Shield of Righteouness ---> Scaling with spell power!

### ISSUE THREAD

**Issue by Arclitee** [SunwellTracker/issues#2575]
Decription: [Shield of Righteousness] its hitting for 3k+ on prot paladins and holy paladins.

How it works: Just get spell power and use the skill on your your victim.

How it should work: The correct formula doesnt include spell power at all. 0%
https://wowwiki.fandom.com/wiki/Spell_power_coefficient

![WoWScrnShot_112719_060431](https://user-images.githubusercontent.com/56983774/69705258-ef783d80-10d3-11ea-9bc4-f6b7a45b5728.jpg)

**Comment by Aridam** [comment]
https://wotlk.evowow.com/?search=Shield+of+righteousness#abilities
Block Value coefficient + fixed value Damage only. No AP/AP coefficients etc. 

Confirmed.

**Comment by Azathothh** [comment]
634 AP / 259 SP   = 785dmg
![obraz](https://user-images.githubusercontent.com/37483678/70476103-50d9dc80-1ad6-11ea-9b52-3f24e136e456.png)

2234 AP / 2739 SP   = 785dmg
![obraz](https://user-images.githubusercontent.com/37483678/70476363-d3fb3280-1ad6-11ea-9edd-9b5e910b1266.png)

"How it should work: The correct formula doesnt include spell power at all. 0%"
That's exactly how it works.
