### ISSUE TITLE
Egg of Mortal Essence Bug (after recent fix)

### ISSUE THREAD

**Issue by Mavock** [SunwellTracker/issues#2578]
Decription: The Emblem of Heroism trinket [Egg of Mortal Essence] procs off Life Tap now for Warlocks, but not off of Fel Synergy or Fel Armor.

How it works: The [Egg of Mortal Essence] trinket only procs off Life Tap for Warlocks, making it unviable.

How it should work: The [Egg of Mortal Essence] should proc off of Life Tap, Fel Synergy (talent) and Fel Armor.

Source (you should point out proofs of your report, please give us some source):

![image](https://user-images.githubusercontent.com/39953678/69764288-184e1080-1170-11ea-913d-516a73d91eb3.png)

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2552
