### ISSUE TITLE
[Shaman] Feral Spirit

### ISSUE THREAD

**Issue by Thaxhuz** [SunwellTracker/issues#2579]
Decription: Enhancement Shaman tree, last talent. The Feral Spirit, which is the ability that summons two wolves.

How it works: They always spawn as aggressive just jumping on everything, even if I put them to defensive, next time they spawn, they are automatically aggressive. It causes alot of ninja pulls.

How it should work: They should remain the same the next time you summon, for example. Are they put as defensive, next time they spawn, they should be in defensive mode.

Source (you should point out proofs of your report, please give us some source): Try it in-game.

**Comment by Aridam** [comment]
Seems remembering of set state from last summon isn't present for Spirit Wolves every time Feral Spirit is used.
