### ISSUE TITLE
Warlock [Immolate] ---> [Conflagrate]

### ISSUE THREAD

**Issue by Talonixa** [SunwellTracker/issues#258]
Decription: 
Warlocks cant use Conflagrate right away after casting Immolate on a target.

How it works: 
After casting Immolate the tooltip of Conflagrat remains grey (not castable) for like 1s.

How it should work: 
It should be castable right away. What i think happend is, that the spell Immolate is somehow treated like a missile (a cast that needs to reach the target after being cast) , when really it should not. For the Immolate itself it does not matter (i think), but its a annoying bug when you play destruction-warlock.

Sorry if this was already adressed but i could not find it

Thanks in advance.

Source (you should point out proofs of your report, please give us some source):

**Comment by Talonixa** [comment]
maybe it actually is blizzlike. (i just never worked like this on many other private servers) :)

**Comment by Afgann** [comment]
It is.
