### ISSUE TITLE
Morph items interaction with Druid forms

### ISSUE THREAD

**Issue by DiversionRoute** [SunwellTracker/issues#2581]
Decription: 
Some morph items overwriting bear/cat/tree forms and some dose not.

How it works: 
Out of the three items I've tried so far two of them currently overwrites bear/cat/tree form.

Items in question are:

- [Savory Deviate Delight](https://db.darkwizard.pl/?item=6657)

- [Noggenfogger Elixir](https://db.darkwizard.pl/?item=8529)
        (Skeleton part)

- [Iron Boot Flask](https://db.darkwizard.pl/?item=43499)

_**Noggenfogger Elixir**_ and _**Iron Boot Flask**_ overwrites bear/cat/tree form, while the _**Savory Deviate Delight**_ dose not.

How it should work: 
This is the tricky part, see I'm not sure what is right or wrong here. But in my opinion I think the _**Savory Deviate Delight**_ also should overwrite bear/cat/tree forms since the other two already dose it.

I've played on a 3.3.5 build in the past where they all did overwrite the forms, but don't have any screenshots or access to that realm anymore sadly.

I'll link some screenshots from **Frosthold** down below.

I'm aware that this might not be an actual bug, but maybe we can do this change anyway? I mean who doesn't want to run around as a pirate or ninja bear? :)

Source (you should point out proofs of your report, please give us some source): 

**Screenshots**:
https://imgur.com/a/LnfSqwL

**Comment by Aridam** [comment]
This was present back in _Vanilla_ -- it got patched out starting TBC as early as v2.0.1.
https://wowwiki.fandom.com/wiki/Patch_2.0.1
> Shapeshifting will now break "Nogginfogger Elixir" effect.

https://wowwiki.fandom.com/wiki/Savory_Deviate_Delight
> Druids, Shamans, and Warlocks lose the effect when they change forms.

https://eu.battle.net/forums/en/wow/topic/1622894397

**Comment by DiversionRoute** [comment]
Well nothing is working as the link you provided states.

Noggenfogger Elixir **dose not break** on Shapeshifting.

Savory Deviate Delight **is not lost** upon Shapeshifting.

Also I don't see any reason to actually have it like it was in 3.3.5 since there was several request from Druids and Shamans to make the morphs not disappear on Shapeshift.
It was even later changed in some later expansion.

Again this is more of a request I guess, then an actually bug fix.

**Comment by Aridam** [comment]
It was more as a PvP balancing measurement, as mentioned on the BattleNET WoW topic -- for example, people couldn't actually visually see the Form changes of a Druid with that.

If you think this should be allowed, then it would be fair to allow similar bugs/fixes to not be present in this server too, including mounting up with DBW procs.
