### ISSUE TITLE
Patch 3.0.8 mob tagging

### ISSUE THREAD

**Issue by PolarCookie** [SunwellTracker/issues#2582]
**Description:**
http://wowwiki.wikia.com/wiki/Patch_3.0.8

> Tapping: All player spells which cause a creature to become aggressive to you will now also immediately cause the creature to be tapped.

https://kotaku.com/5135695/wow-patch-308-brings-important-changes-to-clams

> and the fact that damage over time spells that don't immediately damage monsters now tag the critters as yours anyway is a great boon for several casting classes,

**TC solution:**
https://github.com/TrinityCore/TrinityCore/pull/22759

**Comment by Aridam** [comment]
Confirmed -- currently you tag creatures by doing any form of Damage to them _immediately_, as doing any non-damaging or Damage-delayed hostile actions (Taunts, CC, applying DoTs etc.) won't tap them as yours.
