### ISSUE TITLE
Pet passive and pet spell casting

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#2583]
Decription: 
Using /petpassive does not cancel the pet's cast in progress.

How it works: 
The pet will finish its current spell and then stop attacking.

How it should work: 
The pet should cancel its cast when /petpassive is used.

Source (you should point out proofs of your report, please give us some source): 
Tested on mage Water Elemental.

**Comment by Aridam** [comment]
"/petpassive" should only change the reaction to Passive, not _also_ stop the current cast. If you want to do that as well, you'll have to add something to the effect of "/petfollow".
Reference [here](https://github.com/TrinityCore/TrinityCore/issues/18264#issuecomment-261458359).

**Comment by Soufly** [comment]
defensive = auto attack while in combat
passive = wont attack in combat without target and /petattack
Thats how it works in other private servers at least.

**Comment by Aridam** [comment]
Private servers normally can't be used as reliable examples.

Putting in Passive does as said, but it doesn't stop _ongoing_ casts -- for that you need to force it to do so in some other way, like commanding it to follow you using "/petfollow". So for that, you do:
```
/petpassive
/petfollow
```
