### ISSUE TITLE
[Spell] Serpent Sting ID: 13550

### ISSUE THREAD

**Issue by Drostthehunter** [SunwellTracker/issues#2585]
Decription: 
https://classic.wowhead.com/spell=13550/serpent-sting#see-also-ability

How it works: 
You can apply Serpent Sting on multiple targets at the same time.

How it should work: 
The Serpent Sting should be only applied to 1 target per hunter on any one target, as explained in spell description.

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
Wrong report.

**Comment by Aridam** [comment]
Poor wording by Blizzard -- what it means to say is that you're unable to have more than one Sting as a single Hunter on a single Target (i.e., no Serpent _and_ Scorpid from _one_ Hunter on _one_ Target), but you can still multi-Sting.

Not valid.
