### ISSUE TITLE
[Warlock] Voidwalker's Consume Shadows doesn't work most of the time

### ISSUE THREAD

**Issue by FuZ38** [SunwellTracker/issues#2588]
Decription:  
Voidwalker's Consume Shadows will most of the time only cast for a split second and use mana without giving health to the Voidwalker

How it works: 
When using Consume Shadows, seems to happen more often when it's done after moving your character

How it should work: 
Channeling should not break

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/n0s1s

**Comment by jeyjeylol** [comment]
workaround before its fixed: press "follow", wait pet to stop by you and then cast consume shadows, its doesnt work when he is already standing next to you and after pressing "follow" he doesnt move an inch, so u have to move a little and then press "follow" again

**Comment by Baelek** [comment]
This issue still continue to persists, and we have to have the voidwalker stay so that he can consume shadows. Also he periodically looks like he's having a seizure when he's casting this.
