### ISSUE TITLE
Beasts in dungeons

### ISSUE THREAD

**Issue by xmachinex87** [SunwellTracker/issues#2591]
Decription: 
1: Non elite beasts despawn way too quickly - 1 or 2 minutes.

2: Some beasts in old dungeons drop only light leather and ruined leather scalps.

**Comment by Aridam** [comment]
> 1: Non elite beasts despawn way too quickly - 1 or 2 minutes.

I believe this relates to [this](https://github.com/SunwellTracker/issues/issues/2468) report.

> 2: Some beasts in old dungeons drop only light leather and ruined leather scalps.

You do realize you need to provide actual proof of which ones drop the supposed bad Leather and also show evidence of what they _are_ supposed to drop instead.

Report does not follow proper format.

**Comment by xmachinex87** [comment]
I wrote ticket yday with Craftys response explaining why I need to talk directly to developer in private about this fix. I do realise I cant just say some mobs drop bad leather.

**Comment by xmachinex87** [comment]
already talked to gms about this, n1 issue already reported
