### ISSUE TITLE
[Warlock] Voidwalker pet

### ISSUE THREAD

**Issue by fabuh** [SunwellTracker/issues#2593]
Decription:
http://db.darkwizard.pl/?spell=20387 Consume Shadows
The Voidwalker pet interupts his Consume Shadows if he's on follow and you're staying still.
How it works:
The first time you cast the spell it is intereupted and the 2nd time the spell is cast normally.
How it should work:
If I'm not moving the pet should be able to channel the spell.
Source (you should point out proofs of your report, please give us some source):
Steps to reproduce:
1)put voidwalker pet on follow
2)move
3)stop
4)cast Consume Shadows when the pet stops moving

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2588
