### ISSUE TITLE
Jet'ze's Bell not in the game

### ISSUE THREAD

**Issue by Drafter5523** [SunwellTracker/issues#2595]
Decription: 
It's a trinket

How it works: 
Highly doubt it's in the game atm, have never seen one equipped or on the AH, asked around alot and no one have seen one.

How it should work: 
It should be in the game 

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
As per [this](https://db.darkwizard.pl/?item=37835#dropped-by), it should have 0.1 - 0.13% chance (mostly 0.13%) to drop from the listed Mobs.
Either people are just _that_ unlucky, or maybe the shown percentages aren't actually reflected on live.

**Comment by Dootz** [comment]
Hi, I can confirm it's added to loottable and it's possible to get it, but it has low drop chance.
