### ISSUE TITLE
Charge animation

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#2597]
Decription: 
When a warrior charges or intercepts you, you only see the warrior teleporting instantly to you.

How it works: 
There is no animation on Charge or Intercept, just a teleport.

How it should work: 
Charge and Intercept should show the warrior moving towards you at a high speed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Are you sure? Provide a video snippet or something. Make sure it also doesn't involve CC-ing them mid-Charge -- just have someone Charge you completely and without any form of interruption, and watch how it goes.

**Comment by buugss** [comment]
It appears to only happen when the warrior gets a Frostbite on him from the charge.

**Comment by Aridam** [comment]
Then it's intended - - see given examples in https://github.com/SunwellTracker/issues/issues/2529.
