### ISSUE TITLE
[DRUID(balance)] Force of Nature treant health is not scaling with lvl

### ISSUE THREAD

**Issue by Zeorgbugfinder** [SunwellTracker/issues#2598]
Decription: 
title

How it works: 
The treants don't scale with levels. Treants have the same amount of health at level 50 as at level 80. (6296)

How it should work: 
Treants health should scale. (from 6296health to 14314health - each lvl should give some health to treant)
Treants should have health = to a normal mob for that level.

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Seems they're just straight-up missing the HP scale per Level matched with the Druid caster.
If you relearn Talents at 80 and then take it, does that change anything?

**Comment by Zeorgbugfinder** [comment]
> If you relearn Talents at 80 and then take it, does that change anything?
i asked a druid he rerolled balance later and he has same treant health as me

**Comment by Aridam** [comment]
So it's completely missing that then. Makes Treants rather puny, for a good CD.

**Comment by Zeorgbugfinder** [comment]
plz FIX it needs to be fixed

**Comment by dominotrix** [comment]
Still not fixed?
