### ISSUE TITLE
[Mining] Rough Stones doesn't seem to drop from copper veins.

### ISSUE THREAD

**Issue by Velthos** [SunwellTracker/issues#26]
Decription: 
Mining copper veins should dropd rough stones.

How it works: 
I have mined 15+ copper veins at this moment, and haven't got a single rough stone.

How it should work: 
Should drop rough stones.

Source (you should point out proofs of your report, please give us some source):

**Comment by Velthos** [comment]
EDIT: Have only mined veins in Westfall. Doesn't know if it changes anything, but thought you should know.

**Comment by pullovesi** [comment]
Yeah i've mined around 30+ veins in Elwynn Forest and didn't get a single rough stone.

**Comment by Velthos** [comment]
Update: Just mined some more veins and still not getting any rough stone. I literally cannot compete in Realm first engineer 450 due  to this (bug?"

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
