### ISSUE TITLE
[DK] Can't runeforge heirloom weapon

### ISSUE THREAD

**Issue by FrostSunwell** [SunwellTracker/issues#260]
Decription: 
Went to the runeforge to put something on my heirloom arcanite reaper and says it is too low level.

How it works: 
It doesn't.

How it should work: 
Runeforging should be able to be used on heirloom weapons.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
http://et.worldofwarcraft.wikia.com/wiki/Death_knight_abilities/Runeforging

"Runeforging requires that the weapon have an item level of 45 or higher." Heirlooms are ilvl 1.
