### ISSUE TITLE
[Sundial of the Exiled] not procing off Power Word: Shield

### ISSUE THREAD

**Issue by siskokid21** [SunwellTracker/issues#2606]
Decription: Sundial of the Exiled not procing when using Power Word: Shield.

How it works: It currently doesn't proc when using Power Word: Shield, which should proc it.

How it should work: Power Word: Shield should proc this trinket when used.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/24421583/69911242-9d425f80-13e6-11ea-8bc3-47a7cedb006d.png)
https://www.wowhead.com/item=40682/sundial-of-the-exiled#comments
![image](https://user-images.githubusercontent.com/24421583/69911275-104bd600-13e7-11ea-9ae2-279dd37c7e3a.png)
https://www.wowhead.com/spell=60063/now-is-the-time#comments

**Comment by Kenosz** [comment]
to add to this: it should also proc off of Penance (even when it's only used to heal)

Source: https://i.imgur.com/wZ7YPDZ.png
https://ptr.wowhead.com/forums&topic=85103/talk-me-out-of-my-druid-healer

https://i.imgur.com/xbDIeOS.png
https://www.wowhead.com/forums&topic=87317
