### ISSUE TITLE
Typhoon doesn't dismount players mounted flying

### ISSUE THREAD

**Issue by hellomotow** [SunwellTracker/issues#2609]
Decription: covered below

How it works: Just dazes

How it should work: Players should fall and give honor if killed by fall

Source (you should point out proofs of your report, please give us some source): 

Can remember doing this fondly
https://us.battle.net/forums/en/wow/topic/3123038138 - Late 2011 player mentions it always has
https://www.youtube.com/watch?v=pWlBr_fT6bI - TBC
https://www.mmo-champion.com/threads/854459-Typhoon-And-Flight-Form - MMO thread from early 2011

I am unable to find any WOTLK videos even though one of the people above mentioned there should be several out there.

**Comment by Aridam** [comment]
Not valid anymore -- it used to work until v3.3 in WotLK which made Blast Wave, Typhoon and anything similar no longer dismount people.

https://www.wowhead.com/forums&topic=153060
Referencing Patch 3.3:
https://wow.gamepedia.com/Patch_3.3.0
Ctrl-F search "Knockback" and find:
> - Knockbacks no longer dismount players. If on a flying mount, you will be knocked back a short distance before being able to resume flying.

**Comment by Riztazz** [comment]
Aridam explained it perfectly, closing
