### ISSUE TITLE
Flying Points - Outland

### ISSUE THREAD

**Issue by Sildo** [SunwellTracker/issues#261]
Decription: 
It happens randomly.

How it works: 
Sometimes clickable icon which makes you fly to point is missing 

How it should work: 
They shouldn't disappear randomly 

Source (you should point out proofs of your report, please give us some source): https://i.imgur.com/zttlkj3.png

**Comment by Afgann** [comment]
Try to remove cache, and reproduce the bug without addons, looks like UI bug.
