### ISSUE TITLE
Giant Darkwater Clam

### ISSUE THREAD

**Issue by lulzi** [SunwellTracker/issues#2620]
Decription: U can fish giant darkwater clam,which droppes siren's tear
How it works: U can fish them
How it should work: U should not be able to fish them before patch 3.1
Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/item=45909/giant-darkwater-clam

**Comment by Dootz** [comment]
Hi, upon review we decided to leave it in-game because siren's tear can be found also in other clams which were added in 3.0.2 : https://www.wowhead.com/item=36781/darkwater-clam and https://www.wowhead.com/item=44700/brooding-darkwater-clam
