### ISSUE TITLE
[Priest] - Cannot cast Guardian Spirit on friendly targets with Weakened Soul debuff

### ISSUE THREAD

**Issue by kinpie** [SunwellTracker/issues#2625]
Decription: 
You cannot cast **Guardian Spirit** on friendly targets with **Weakened Soul** debuff.  Casting **Guardian Spirit** also applies **Weakened Soul** debuff.

How it works: 
When you attempt to cast **Guardian Spirit** on a friendly target suffering from **Weakened Soul** debuff, an error message says "You can't do that right now."  Casting **Guardian Spirit** on a friendly target causes **Weakened Soul** debuff.

How it should work: 
**Guardian Spirit** can be cast on any friendly target in range + in line of sight.  **Guardian Spirit** should **NOT** apply **Weakened Soul Debuff**.  

Source (you should point out proofs of your report, please give us some source): 
![GSbug](https://user-images.githubusercontent.com/36087298/70109182-1a551b00-1619-11ea-8de6-a5fee164d476.jpg)

**Comment by Aridam** [comment]
https://youtu.be/LCAIejKhVyw?t=207
Casts GS, no Weakened Soul application. Confirmed.

Pretty sure it should also be castable through WS as said, as WS only restricts PW:S -- no mentions or video examples of this ever being a thing after a few searches of my own. Honestly this sounds like some bug making it like [Weakened Spirit](https://www.wowhead.com/spell=72232/weakened-spirit) on Valithria to prevent GS stacking there.

**Comment by quortonn** [comment]
I can confirm this bug too and is creating alot of problems in my guild for naxxramas progress, this should be fixed as soon as possible, or holy priests will be very useless in raid. As you can see here too https://wowwiki.fandom.com/wiki/Guardian_Spirit   this interation is totally non existent in the wotlk patchnotes, so is clearly a server bug.
