### ISSUE TITLE
[Warrior, Spell] Recklessness Bladestorm/Whirlwind/Cleave consumes all stacks.

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2627]
Decription: 
Whirlwind/Cleave consumes 3 stacks of Rec if hit 3 targets or more.
or 2 stacks if hit 2 targets.

How it works: 
Whirlwind/Cleave consumes 3 stacks of Rec if hit 3 targets or more.
or 2 stacks if hit 2 targets.

How it should work: 
Whirlwind/Cleave should consume 1 stack of Reck per Whirlwind Spin/Cleave Use

Source (you should point out proofs of your report, please give us some source):
https://www.wowhead.com/forums&topic=43160
https://youtu.be/DmwUI5-lDWo?t=26

I don't even know why no one report it earlier, so basic stuff.

Look on this too, warriors are the most bugged class at the moment.
It will be nice if Devs repair something in classes finally.
https://github.com/SunwellTracker/issues/issues/2539
https://github.com/SunwellTracker/issues/issues/2507

**Comment by Aridam** [comment]
Not true -- both Abilities are _supposed_ to expend Recklessness for _each hit_ that gets converted.

Watch the same video you linked, but at the lowest speed. I just watched it multiple times to be sure and I can tell you how it goes. Do the same and you'll see that this is what happens:

1. He activates Recklessness;
2. He uses Bloodthirst -- gains Bloodthirst Buff and expends a Recklessness charge;
3. He uses Cleave -- it hits both Dummies, expending two Charges in very-quick fashion;
4. He uses Whirlwind _**BARELY**_ after that (can see it more clearly in slow motion). One of the hits it did wasn't a Crit -- if he had used WW _with_ Reck, all hits would've been Crit (even if Reck was at 1 charge left).

**He was using literally nothing else _just before_ that Whirlwind, so there wasn't anything that could've expended Reck after Cleave expended two charges a moment before WW-ing. It seems the Cleave DMG on the left one wasn't displayed, _but there was still the blood effect and extra sound on it_.**

There is also this:
https://www.youtube.com/watch?v=D9yKdTQ6AVY&feature=youtu.be&t=5
Uses Reck, then:
1. Bloodthirst - two charges left;
2. Whirlwind -- all charges spent, but all hits are Crits.

I understand if you would doubt the above source considering it's 2009.

This:
https://www.youtube.com/watch?v=-tm9-1PatKg&feature=youtu.be&t=307
while low-quality, shows him:
1. Using Reck;
2. Using WW -- two hits (Crits), from three charges down to one left.

There is also this (best up-to-date example for WW):
https://www.youtube.com/watch?v=MOyfG-s3Gj0
which shows him:
1. Using Reck;
2. Using Heroic Strike -- Crit, one charge down;
3. Using Whirlwind -- eight Crits, both remaining charges expended

Furthermore, here's another example with Bladestorm (lowest speed is recommended again):
https://www.youtube.com/watch?v=IijlbG7yrlc&feature=youtu.be&t=3m10s
Pops Reck and the first Bladestorm spin instantly expends all Reck charges.
**Bladestorm has the same Recklessness/Sweeping Strikes and similar mechanics as Whirlwind does by 3.3.5a.**
