### ISSUE TITLE
Escape from the Winterfin Caverns

### ISSUE THREAD

**Issue by Zavvek** [SunwellTracker/issues#2628]
Decription: 
Didnt get credit for finishing escort

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, were you in raid group or in party with other players? Where you staying close to Lurgglbr? You need to escort him to the village, until he will stay in place and say "Thank you for rescuing me". Can someone confirm if it's working as intended. It worked for me when tested.
