### ISSUE TITLE
Obsidian Sanctuary can be entered during a running fight against Sartharion

### ISSUE THREAD

**Issue by frostholdte** [SunwellTracker/issues#2629]
Decription: 
As the title states the Obsidian Sanctuary can be entered during a running fight against Sartharion.

How it works: 
Start the fight against Sartharion and let people of your raid enter through the portal.

How it should work: 
The portal should be locked with a message stating that
 a bossfight has been started.

Source (you should point out proofs of your report, please give us some source): 
Official servers and common sense.

**Comment by Aridam** [comment]
Errr, wow okay. That's, odd. Should definitely be an error stating "Unable to zone in while an encounter in progress" there and disallowing people from entering while Sarth is in Combat -- obviously.
