### ISSUE TITLE
Quest Veranus Egg bugged

### ISSUE THREAD

**Issue by strictmage** [SunwellTracker/issues#263]
Description: 
Quest in stormpeaks called Veranus for sons of hodir chain

How it works: 
Currently unable to loot any of the eggs, not sure if its due to phasing or bug.

How it should work: 
You should be able to loot the eggs in the nest. 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020518_162836](https://user-images.githubusercontent.com/35983402/35835826-d1ec09c6-0a91-11e8-81ab-ea3da31f423b.jpg)
![wowscrnshot_020518_162852](https://user-images.githubusercontent.com/35983402/35835827-d20bd616-0a91-11e8-9634-1b85fbdc3df7.jpg)

http://www.wowhead.com/quest=13050/veranus   quest from wowhead

**Comment by Nadiirr** [comment]
Had a ticket about this today.
Eggs are spawning at the green arrow spot
Eggs are not spawning at the red arrow spot

![screenshot_146](https://user-images.githubusercontent.com/36300104/42130303-8af889d8-7c95-11e8-856b-1f818e21878e.png)

**Comment by Dootz** [comment]
will be fixed with next server update
