### ISSUE TITLE
Kel'thuzad fissure/void zone hit box is way too big.

### ISSUE THREAD

**Issue by Swiplington** [SunwellTracker/issues#2631]
Decription: 
KT's fissure hits from like 2-3 lenghts away

How it works: 
U stand far away from the fissure and still get 1 shot.

How it should work: 
Fissure should be closer to the actual size that it shows on screen

Source (you should point out proofs of your report, please give us some source): 
We tested it in yesterdays 10 man raid, ppl died 10-15-20 yards away from the fissure/void zone

**Comment by Aridam** [comment]
[TankSpot](https://youtu.be/nM0NFpmi9X0?t=165) video timestamp for reference, which shows the mechanic -- relatively close, might be possible to be just a little bit closer before you're able to die from it. Radius seems about 5yd (Melee Range), **purely from a visual perspective**.

[Void Blast](https://db.darkwizard.pl/?spell=27812) link here, which is the actual damaging Spell of the Shadow Fissure itself -- looking below the Damage values on the table, you see "Radius: 4 yards", so I guess I wasn't too far off.

**Comment by Swiplington** [comment]
it's way bigger on 10 man though, not sure on 25 cuz haven't tested that yet.
