### ISSUE TITLE
Drop on mobs

### ISSUE THREAD

**Issue by Gydvin123** [SunwellTracker/issues#2634]
Decription: 
Wrong drop of things on Theramore guards

How it works: 
They drops Elder's Moonstone and Heavyjunk box

How it should work: 
it's dosn't drop on this mobs

Source (you should point out proofs of your report, please give us some source): 
gm send me on github

**Comment by Aridam** [comment]
https://db.darkwizard.pl/?npc=4979
Seems they're not supposed to drop anything?

However, Heavy Junkboxes are still lootable (low chance for them to have one), _if you use **Pickpocket**_.

Elder's Moonstone is for the Lunar Festival -- obviously they shouldn't have it on them. They come from [these](https://db.darkwizard.pl/?item=21746#contains) instead, during the Lunar Festival itself.
