### ISSUE TITLE
[Mage] Permafrost Talent

### ISSUE THREAD

**Issue by emil92b** [SunwellTracker/issues#264]
How it works: 
target speed for slowing spells is not correct

How it should work: 
http://wowwiki.wikia.com/wiki/Permafrost

**Comment by Cwiercpasiec** [comment]
Permafrost 3/3 + Chilled to the Bone 5/5 should give +20% slow effect. Frostbolt slow is 40% without talents, so with these above it should give 60% and it does.
https://imgur.com/a/zxWn6 You can see the speed of my character on the right minimap. One screen shows speed without debuffs (+0% - normal running speed). Another one shows my rogue being slowed by mage's frostbolt and walking with -60% speed. (Mage had both talents, as you can see on the screenshots). I'm guessing that the only problem is, that the tooltips of buffs/debuffs are always the same, no matter if the skill is modified by talent/glyph etc or not (in other words, your permafrost works correctly, just the tooltip lied to you).

**Comment by emil92b** [comment]
ok
