### ISSUE TITLE
[Rogue] Glyph of Hunger for Blood

### ISSUE THREAD

**Issue by aylo-bugtrack** [SunwellTracker/issues#2640]
Decription: The glyph seems to not be working or at least there's a visual bug on buff description. Glyph should increase damage delt with Hunger for Blood by 3% (from 5% to 8%). On the skill tooltip everything seems fine - it says 8% damage increase, but when you move mouse cursor over the buff itself - it says 5%.

How it works: Glyphed Hunger for Blood still increases damage by 5% (or at least buff description says so)

How it should work: Buff description should say 8% when glyphed

Glyph:
![glyph](https://user-images.githubusercontent.com/58629828/70375551-38639980-18ff-11ea-91bf-d60f6cc24a5f.jpg)

Skill tooltip:
![tooltip](https://user-images.githubusercontent.com/58629828/70375557-4fa28700-18ff-11ea-8dec-7ff8da3faba1.jpg)

Buff description:
![buff](https://user-images.githubusercontent.com/58629828/70375561-592bef00-18ff-11ea-9b7f-caa22767d443.jpg)

**Comment by Rosenkrantz** [comment]
I'll check actual damage - buff tooltips are never updated with Glyphs or Talents and you shouldn't pay much attention to them (ex. talented Blessing of Might, Power Word: Fortitude or something like that)
