### ISSUE TITLE
Glyph of Frost Nova (isnt working)

### ISSUE THREAD

**Issue by AdlerRabelo** [SunwellTracker/issues#2642]
Decription: the glyph says that your Frost Nova targets can take an additional 20% damage before the Frost Nova effect automatically breaks. The glyph is lvl 15 so a lvl 15 frost nova should work just fine not just high spell ranks and we dont need be a lvl 80 to glyph start to work.

How it works: 
Any hit by any spell schools breaks the frost nova, we cant do shatter combo or any combo with frost nova on target because at the 1st hit frost nova breaks. This impact direcly on mages gameplay.

How it should work: 
for example: if we have Glyph of the Frost Nova equiped
and we frost nova an enemy and i hit 100 by any spell school, it means frost nova should not break and will continue till the end or after i hit more 20 damage by any school spells (it means 20% more from 1st hit by spells)

i have been testing this since lvl 20 when i use the glyph and never works, please fix it.

Source (you should point out proofs of your report, please give us some source): 
see my combat log print screeen, my frost nova dissipates after fire blast
![combat log](https://user-images.githubusercontent.com/58469362/70380733-72906380-191e-11ea-8a6b-2ceb7f135e79.png)

plz fix it

**Comment by Aridam** [comment]
You've just remade the same report which got closed earlier. Don't think that'll do much for you.

**Comment by AdlerRabelo** [comment]
I just remade because its not working normally and add some information

**Comment by AdlerRabelo** [comment]
> You've just remade the same report which got closed earlier. Don't think that'll do much for you.

Be free to test in a low lvl char with low frost nova rank.
I just remade because its not working normally and add some information
