### ISSUE TITLE
Masterlooter threshold bug. 

### ISSUE THREAD

**Issue by Swiplington** [SunwellTracker/issues#2646]
Decription: 
Set masterloot threshold to epic, yet raid members can't loot any greys/greens/blues only the masterlooter can.

How it should work: 
Loot should be working as group loot unless its epic items (if set to epic)

Source (you should point out proofs of your report, please give us some source): 
Happened in both our raids so far.

**Comment by Aridam** [comment]
Makes it annoying to sort out through loot while clearing, especially if trying to be quick about it. Nobody likes wasting time on trivial stuff that's actually important on its own (Gold/Enchanting Mats etc.).

**Comment by Riztazz** [comment]
Weird, i remember we fixed that, i'll take a look again.
closing as duplicate and assigning other one to myself
