### ISSUE TITLE
(Buged Quest) I work...For the Horde

### ISSUE THREAD

**Issue by RafaelCrocetti** [SunwellTracker/issues#2648]
Decription: 

The quest "I work.. For the Horde" ist bugged, in this quest you should pick up salvageable materials from the path of glory and deliver them to a goblim in thrallmar, the materials are wood and metal, both of them are liying around in the previously mention area. The problem is that i can't pick them up.

How it works: 

The materials glow in the usual (lootable) way but they are not interactuable, i can't click on any of  them , and when i hover the mouse over one of them the Gear icon (the one that signifies interactivity) does not appear.

How it should work: 

The materials sould glow in the usual (lootable) way and when i hover the mouse over one of them the Gear icon (the one that signifies interactivity) should  appear, and them when rigth clicking it after a short cast time, you will be able to loot it, it's the same for both materials, after getting enough of both you should return to the gobling to finish the quest.
In
Source (you should point out proofs of your report, please give us some source): 

Its hard to notice on the screen shot cause the mouse pointer does not show and the glow it's just a pixel.
![WoWScrnShot_120819_143412](https://user-images.githubusercontent.com/53916949/70393373-d1f67e00-19c7-11ea-9518-03bb8990d9c3.jpg)

This is a location where you can experiment.

![WoWScrnShot_120819_143116](https://user-images.githubusercontent.com/53916949/70393343-9d82c200-19c7-11ea-9c10-6022d08de282.jpg)

**Comment by RafaelCrocetti** [comment]
I add to this, the quest works on this location, its funny, it only works on one side of the path of glory
![WoWScrnShot_120819_144559](https://user-images.githubusercontent.com/53916949/70393516-98bf0d80-19c9-11ea-8678-f0bdeabc01a3.jpg)

**Comment by Aridam** [comment]
Okay so, by chance, are all the ones above The Path of Glory (ergo, Horde side) lootable by you, while none of the ones below it (Alliance) are?

**Comment by RafaelCrocetti** [comment]
Pretty much

**Comment by Aridam** [comment]
Hmmm, seems as per the [comments here](https://www.wowhead.com/quest=10086/i-work-for-the-horde#comments), it's actually intended?

**Comment by Dootz** [comment]
Hi. I can confirm this is intended. There are different gameobjects for Alliance and Horde.
