### ISSUE TITLE
Core/Entities: Interrupted creatures should move towards victim unless they can cast current spell school

### ISSUE THREAD

**Issue by emil92b** [SunwellTracker/issues#265]
How it works: 
interupting a spellcast from caster mob,  will result in it just standing still

tested on 'Twillight Aquamancer', 'Twilight Shadowmage' in bfd and many more caster mobs in various dungeons.

How it should work: 
it should follow the player and go melee?, not stand still

**Comment by Inbreaded** [comment]
This is an important bug concerning dungeons and raids. Makes positioning for tanks very difficult and sometimes impossible when caster enemies are involved.

One thing to note is that some enemies, once interrupted/silenced, will move towards the target with the highest threat, but others may not.

**Comment by Riztazz** [comment]
Issue will be resolved with next update.
