### ISSUE TITLE
[Death Knight, Spell] Rune of the Fallen Crusader - proc too often.

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2652]
Decription:
Rune of the Fallen Crusader proc too often.

How it works: 
Rune of the Fallen Crusader has like 3-5PPM or more.

How it should work: 
Rune of the Fallen Crusader should have 1PPM = 5,(66)% to proc on my 3,4 speed weapon no internal CD.
But it proc like crazy...

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/spell=53344/rune-of-the-fallen-crusader#comments
https://wowwiki.fandom.com/wiki/Procs_per_minute

**Comment by BialyADI** [comment]
Someone commented how it works on naxx on that wowhead link, on our server you will have 100% up time this enchant:

"I'm pasting the same comment I wrote to the buff section here:

This procced 70 times during 11 bosses in my last 10man Naxx run. That's ~7 times/boss.. which means nearly 2 minutes/boss, while average boss kill duration is maybe 4 minutes. Not too shabby.

Doesn't have internal CD so it can proc many times in a row.

Edit: Oh.. and the proc healed me for more than Blood Aura ;-)

Unholy Strength 155 815 16 %
Blood Aura 107 985 11 %"

**Comment by BialyADI** [comment]
Comparison to other enchants for a character with 1500 strength:
Rune of the Fallen Crusader - Increases attack power by 450 for 15 seconds at ~1 ppm
- 463.5 with Ravenous Dead
- 477 with Veteran of the Third War
- 490.5 with both
- (Also heals you for 3% of your maximum health)
Enchant Weapon - Berserking - Increases attack power by 400 for 15 seconds at ~1.698 ppm
- (Also decreases armor by 5%)
Enchant 2H Weapon - Massacre - Increases attack power by 110 all the time
Enchant 2H Weapon - Scourgebane - Increases attack power by 140 all the time against undead

**Comment by BialyADI** [comment]
In old Sunwell it worked well too.

**Comment by BialyADI** [comment]
Bump.

**Comment by BialyADI** [comment]
Bump!

**Comment by BialyADI** [comment]
Bump!

**Comment by BialyADI** [comment]
Ile czasu moze zając naprawienia takiego buga ;x?

**Comment by Misery321** [comment]
1 PPM is wrong.

Fallen Crusader is 2 PPM.
https://www.mmo-champion.com/threads/1345790-Rune-of-the-fallen-crusader-and-it-s-procs-uptime?highlight=Rune+of+the+Fallen+crusader

"So if your 2H weapon has a 3.6s base swing speed it has a 12% chance to proc on every hit. Melee attack speed buffs like Icy Talons, Unholy Aura, Bloodlust, etc, do not impact the base swing speed, so they will give additional procs."

"Take the number of procs and divide it by the total number of successful attacks. This will give you a probability per hit, from which you can find the pre-haste PPM:

Probability = Base_PPM * Tooltip_Swing_Speed / 60
Solving for Base_PPM,
Base_PPM = 60 * Probability / Tooltip_Swing_Speed"

"Uptime is approx 75/90/80% for DW frost, 2H frost, and Unholy respectively"

Uptime now is 16% and makes the enchant totally fucking useless.

Fix this

**Comment by Misery321** [comment]
If we use retail wow as sources you can also check this out.
https://www.wowhead.com/spell=166441/fallen-crusader

**Comment by LevanSturua** [comment]
this change is such a major fuckup, it barely procs now... 

heres some proofs of it having near 100% uptime on retail wotlk 

https://www.youtube.com/watch?v=VSs17aqQpA0

https://www.youtube.com/watch?v=-nzTzCUoROA

literally watch any dps dk video from retail wotlk and u will see fallen crusader is almost always up
it was working correctly, please revert it as it was as soon as possible.

**Comment by Valais** [comment]
This have to be a fucking joke. Theres another DKs pov from DBS:
https://www.youtube.com/watch?v=c4mIHZHd050 Its basically never falling off. 
Keep in mind that the post stating proc chance is ~1PPM post was on patch 3.0.3!!!! Even patch notes from 3.1.0 says the proc chance is doubled. 
Wrath of the Lich King Patch 3.1.0 (2009-04-14): Strength bonus reduced to 15%. Chance to proc doubled.
And then who knows how many silent fixes occured? 
Check out just 1 link from this thread and then try to convince us it was 1PPM LOL

**Comment by aceman85turbo** [comment]
Even if we use Rawr, which has been unchanged since 2011, it shows 2ppm.

I went 17 autos with Betrayer fully raid buffed before it procced last week, thats insane.
![fallencrusader](https://user-images.githubusercontent.com/54301171/76392545-c5bfeb00-633f-11ea-9ffb-671bf749c7f7.jpg)
