### ISSUE TITLE
Spellstealed Sacred Shield

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#2659]
Decription: 
Spellstealed Sacred Shields arent proccing the absorb

How it should work: 
They should proc the absorb like normal.

Source (you should point out proofs of your report, please give us some source): 
Tested ingame

**Comment by buugss** [comment]
Proof: https://www.warcraftmovies.com/movieview.php?id=114127 @ 15:29

**Comment by Aridam** [comment]
He took a Mortal Strike hit -- which didn't proc the Sacred Shield he had on himself via Spellsteal.

He Spellsteals the Sacred Shield proc himself -- check Target and its Buffs, see no Damage going on Mage, he casts Spellsteal and removes it from the Target's Buff list, adds it to his own.

Check 14:49 in the same video -- Spellsteals Sacred Shield, gets opened on with a buncha Damage -- no proc.

**Comment by buugss** [comment]
The absorb has a Chance to proc on taking damage. Here is another clip to demonstrate:
https://www.warcraftmovies.com/movieview.php?id=167507 @ 17:55

**Comment by Rosenkrantz** [comment]
Some clarification - the absorb doesn't have a chance, just a 6s cooldown. It probably doesn't reset cooldown on a steal, so assuming you should get procs, you'd have to wait 6seconds since last proc to get your own Sacred Shield, so a single hit not proccing absorb doesn't disprove it yet.

**Comment by Aridam** [comment]
>The absorb has a Chance to proc on taking damage. Here is another clip to demonstrate:
https://www.warcraftmovies.com/movieview.php?id=167507 @ 17:55
The warrior has no Sacred shield on him, and he hits the mage with mortal strike which procs the absorb.

Yeah, noticed that.

>Some clarification - the absorb doesn't have a chance, just a 6s cooldown. It probably doesn't reset cooldown on a steal, so assuming you should get procs, you'd have to wait 6seconds since last proc to get your own Sacred Shield, so a single hit not proccing absorb doesn't disprove it yet.

https://db.darkwizard.pl/?spell=53601

Pfff, I'm dumb -- forgot about the 6s ICD on the proc. Christ.

Point taken -- confirmed.
