### ISSUE TITLE
[Quest] Items of Power

### ISSUE THREAD

**Issue by Bennenator** [SunwellTracker/issues#266]
Description:  After I joined a dungeon, I can no longer interact with the center stone of the outer binding circle in the Arathi Highlands thereby not allowing me to complete the quest: Items of Power.

How it works: The Items of Power quest states to collect 10 Witherbark Totem Sticks and proceed with them to the outer binding circle, click on the center stone to deposit the totem sticks, "wait for a thunderbolt to strike the stone", and then collect the bolt charged bramble. Also, I have searched it and when it is stuck by lightning, elementals are supposed to spawn and attack.

How it should work: In the Items of Power quest, when I went to click on the center stone of the outer binding circle in Arathi Highlands after collecting 10 Witherbark Totem Sticks, Nothing happened for a few seconds and then I accepted a dungeon queue and was transported in. After returning, I find that I still have my Witherbark Totem Sticks and that the center stone is no longer intractable.

After talking with Dredd, he sent me here to fill out this report. I hope I was specific enough.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
