### ISSUE TITLE
Zul'aman Bugged

### ISSUE THREAD

**Issue by Enskauning** [SunwellTracker/issues#2665]
Decription: When you wipe in Zul'aman you cant enter the raid again it keep saying An encounter is still ongoing, even though none is inside, i was there with 2 mates we wiped and we couldnt enter it happend twice..Also couldnt mount in the raid which was wierd

How it works: When you wipe in Zul'aman you cant enter the raid again it keep saying An encounter is still ongoing, even though none is inside, i was there with 2 mates we wiped and we couldnt enter it happend twice..Also couldnt mount in the raid which was wierd, it said we were in combat even though we werent

How it should work: Let us enter the raid

Source (you should point out proofs of your report, please give us some source): I dont, didnt take any screenshot im afraid

**Comment by Piootrek** [comment]
On which boss you exactly wiped?

**Comment by Piootrek** [comment]
On which boss you wiped?

**Comment by Enskauning** [comment]
Nalorakk and akilzon, but when we enterd the raid we couldnt even mount after you opened the door with the gong so we were in combat already then.
