### ISSUE TITLE
[Quest] Dragonmaw race: Captain Skyshatter

### ISSUE THREAD

**Issue by Azathothh** [SunwellTracker/issues#2666]
Decription: When we start this quest, npc 23348 Captain Skyshatter should start moving

How it works:  Currently when we start it he does only say:  
"Captain Skyshatter says: I weep for you, <nickname>. You really have no idea what you've gotten yourself into..."  but he stays in one place, script is not advancing. Quest can't be completed because of that.

How it should work:  https://www.youtube.com/watch?v=MoL8Af3yxh8
Once quest is started he should start to move, like on this video. He does yell different text as well, but i'm not sure if that was changed after wotlk or if current text is wrong.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=MoL8Af3yxh8
https://db.darkwizard.pl/?npc=23348

**Comment by Mikov1899** [comment]
@Azathothh @Dootz I would like to inform you, that he does start moving, but he is not flying like he is supposed to, I mean, he flies at like 30% mount speed, he just starts from that runway, flies one circle, comes back to airstrip, and then he flies forward and backward SLOWLY as hell, those meteors work correclty, they hit, and its okay, but i've been at him for like 5 min, and then(i was 10 yards away and wasnt hit by any meteor) the quest failed... i wasnt to far away from him or neither was hit by those meteors. Its uncompletable... tried it like 10 times to confirm that it wasnt my retardness :P

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2714
