### ISSUE TITLE
Wraithtail Nagas in Ashenvale cannot be looted

### ISSUE THREAD

**Issue by fferko704** [SunwellTracker/issues#2669]
Decription: mobs in ashenvale= wraithtail nagas cannot be looted from any distance

How it works: mobs are unlootable

How it should work: they should be lootable when you are in close distance to corpse 

Source (you should point out proofs of your report, please give us some source):
my cursor here is not shown but the loot icon here is grey
![WoWScrnShot_121119_214909](https://user-images.githubusercontent.com/58790946/70659505-83afdc00-1c60-11ea-8c16-355bb408d360.jpg)

**Comment by Dootz** [comment]
Hi, can someone please verify? It seems to be working correctly for me. Can you see cursor change when you mouse over corpse?
