### ISSUE TITLE
Kirin Tor rep doesnt reduce epic flying training

### ISSUE THREAD

**Issue by proplays** [SunwellTracker/issues#267]
Decription: 

Kirin tor rep doesnt lower rep of epic flying training
How it works: 

Epic flying costs 5k at exalted
How it should work: 
Epic flying should be 4k at exalted

Source (you should point out proofs of your report, please give us some source):  https://gyazo.com/e31a7bc84b053967d586dddc9f2a696e

**Comment by Netherfrost** [comment]
This is not a source, you need to prove why it doesn't happen and why it should

**Comment by Cwiercpasiec** [comment]
http://www.wowhead.com/npc=31238/hira-snowdawn#comments

"By Xdoom (4,242 –  7·38)  on 2009/08/18 (Patch 3.2.0)
As said before she is not member of any faction, so no discount from here. DO NOT MAKE THIS MISTAKE! If you want to get discount on Artisan Riding, please read on my post below."

"By shaktier (299 – 1·15) on 2010/11/29 (Patch 4.0.3)
As of patch 4.0.3 she is now part of the kirin tor faction and is eligible for faction discounts"

Clearly not a bug, took me about 2 minutes to google it. That's the reason for source, so morons like you have to get to know something about the game before shitposting...
