### ISSUE TITLE
[Shaman][Earthbind]

### ISSUE THREAD

**Issue by herewegoaganebugs** [SunwellTracker/issues#2674]
Decription: Shamans earthbind's root effect works incorrectly.

How it works:  Currently on Frosthold shamans earthbind totem doesnt root reveal and root invis people near the totem.

How it should work:  Earthbinds root (with the talent) should reveal stealthed targets and root them if they are in the range of the root https://youtu.be/RNDVg8VsXAg?t=57

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
Earthbind totem shouldn't break stealth since 2.2.0 patch.
https://wow.gamepedia.com/Patch_2.2.0
 [Earthbind Totem]: This totem will no longer break Rogue stealth.

**Comment by Aridam** [comment]
@Piootrek he means the Root effect of Earthbind with the Elemental Talent "Storm, Earth and Fire", adding the Earthgrab Root to it. That's the revealing component.

The Earthbind change you linked was to remove the Snare's ability to reveal Stealth.
