### ISSUE TITLE
Mobs in Ashenvale cannot be looted

### ISSUE THREAD

**Issue by fferko704** [SunwellTracker/issues#2676]
Decription: mobs in ashenvale= Thistlefur Avengers, Shamans and Dal Bloodclaw, cannot be looted from any distance
Same with Foulweald Warriors, Ursas and others

How it works: mobs are unlootable

How it should work: they should be lootable when you are in close distance to corpse

Source (you should point out proofs of your report, please give us some source):
my cursor here is not shown but the loot icon here is grey
![WoWScrnShot_121319_182714](https://user-images.githubusercontent.com/58790946/70819538-c98eb080-1dd6-11ea-834b-834b11378ea3.jpg)

**Comment by Dootz** [comment]
Hi, I know it's irritating answer but have you tried to remove "Cache" folder from your /wow and restart the game? I tried many mobs in this area and all of them were working correctly. Apologies for the delayed answer.
