### ISSUE TITLE
Totem Targeting

### ISSUE THREAD

**Issue by Kupcakez** [SunwellTracker/issues#2677]
Decription: 
The targeting system was changed in 3.2.0 to remove scripts or macros from targeting totems (totem stomping macro)

How it works: 
Currently you can /target totems and have pets or whatever instantly kill totems

How it should work: 
Macros should be unable to perform such actions

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Patch_3.2.0
"Macros and scripts will no longer be able to target totems by name."
"Ghostcrawlers take on it in 2009:

If you command your pet to kill a totem, we don't have a problem with that. That is no different than a player deciding to use an attack to kill a totem. But note the key word there: "deciding." When you are able to kill a totem solely by virtue of the fact that you are a pet class, you have made no decision. You have made no commitment of resources. Your pet is just going and doing its own thing. That crosses a line for us. Your pet is not a totem. It is not nearly as easy to kill. Thus we require that you spend some amount of your bandwidth telling it what to do."

**Comment by Riztazz** [comment]
I am not quite sure that's something we can meddle with to be honest, i'm pretty sure all macro related stuff is handled client-side, but i will take a look later just to make sure. 99% sure it's all client-side so nothing,we - a server, can do

**Comment by Aridam** [comment]
So that would actually require editing the client to reflect the v3.2 change of, f.ex. not being able to macro `/tar Magma Totem` or running a script doing the same by name anymore?

**Comment by Riztazz** [comment]
Yeah, seems like blizzard reverted that change or something happened along the patches that they did not specify

**Comment by Riztazz** [comment]
Yup, it's client-side, nothing we can do about that, closing
