### ISSUE TITLE
Jedoga Shadowseeker in Ahn'Kahet The Old Kingdom- Cannot be looted if killed in air

### ISSUE THREAD

**Issue by Sykosic** [SunwellTracker/issues#268]
Decription: If Jedoga shadowseeker dies in the air her body falls to the ground unlootable

How it works: 
Dies in air to dots or other effects, body falls to the ground unlootable

How it should work: 
Should still be lootable after dieing in the air.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed.
