### ISSUE TITLE
Cooking chain does not work

### ISSUE THREAD

**Issue by Queldorei** [SunwellTracker/issues#2681]
Decription: 
I did the "Clamlette Surprise" quest on Horde side before taking the previous quest in the Orgrimmar "Go to Gadgetzan !". in the end, when I did both of these quests my Artisan Skill Cooking did not open until 300

How it works: 
Both of quests is open. i come to Gadgetzan and complete first "Clamlette Surprise", this quest gave me skill to cooking "clamette surprise, but not open skill to 300.

How it should work: 
Guess first should opening quest "Go to Gadgetzan !" and after this "Clamlette Surprise, when complete both quests you take Artisan skill of cooking(225-300).

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_121619_015341](https://user-images.githubusercontent.com/45577825/70870648-e679de00-1fa6-11ea-8655-21e8a96ad742.jpg)

**Comment by Queldorei** [comment]
name ingame - _Nebaken_.

**Comment by Aridam** [comment]
This is not valid anymore, as that was a Vanilla requirement (maybe TBC as well)?

You are able to straight-up train to the next Cooking proficiency without the need for Quests anymore -- the same thing applies to others, like First Aid (i.e. "Triage" or whatever it was called becoming obsolete).
