### ISSUE TITLE
Same loot drops from Hellfire Ramparts Heroic

### ISSUE THREAD

**Issue by Hellhammer90** [SunwellTracker/issues#2682]
Decription: 
Had been farming Vazruden in Hellfire Ramparts Heroic for xmog for about 4 days and has been dropping the same loot everytime. 

How it works: 
Drops the following everytime:
-Vambraces of Daring
-Lion's Heart Girdle
-Chestguard of the Prowler

How it should work: 
Different items should drop. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
It must have been really bad luck. Vazruden's chest can drop up to four items:
1. Steady Chrysoprase or Iridescent Fire Opal or Effulgent Chrysoprase
2. Wrath Infused Gauntlets or Feltooth Eviscerator or Tree-Mender's Belt or Lion's Heart Girdle
3. 1 or 2 items from following list:
Lion\'s Heart Girdle
Tree-Mender\'s Belt
Feltooth Eviscerator
Wrath Infused Gauntlets
Light Scribe Bands
Averinn\'s Ring of Slay
Volcanic Pauldrons
Irondrake Faceguard
Raiments of Nature\'s Breath
Life Bearer\'s Gauntlets
Oceansong Kilt
Vambraces of Daring
Reavers\' Ring
Chestguard of the Prowler
Steady Chrysoprase
Iridescent Fire Opal
Effulgent Chrysoprase

I tried couple times and it was dropping different items. Where you able to run this instance again? Can someone else confirm if this is an issue?

**Comment by Kulix** [comment]
the loot tables are bugged overall, last 4 weeks of naxx i was keeping track of the loot and its mostly the same rings/necks and caster loot
