### ISSUE TITLE
Active tracking abilities

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#2684]
Active tracking drops after every server crash even if player was not online.

**Comment by Aridam** [comment]
Seems similar to #2459 by the way it sounds?
Normal (non-Hunter) Tracking methods (low-Level Quests f.ex.) work and get remembered between sessions. Should work with special methods (Hunter) too.

**Comment by Rosenkrantz** [comment]
Normal tracking does work, but ability-related tracking does not. Track Humanoids is a spell, and is removed; Find Herbs is also technically (probably) a spell, and it does get removed.

**Comment by Aridam** [comment]
By that logic, it might be worth to check Sense Undead (Paladin).

**Comment by blazetrooper** [comment]
Confirming, active tracking drops after every server crash even if player was not online.

**Comment by Soufly** [comment]
Its getting REALLY annoying already ...

**Comment by Soufly** [comment]
Still not fixed : ) .

**Comment by Soufly** [comment]
Still not fixed(just happen after the crash) @Afgann

**Comment by Soufly** [comment]
Still not fixed,the server just crashed and i lost my tracking...
