### ISSUE TITLE
[Mage] Glyph of eternal water incorrectly works with dual spec

### ISSUE THREAD

**Issue by lpodlodowski** [SunwellTracker/issues#2689]
Decription: 
Glyph of eternal water works incorrectly with dual spec. Effects are active on both specs even if glyph is active only on one of them.

How it works: 
Glyph of eternal water removes skill from pet. Skill is removed in both spec of dual specialization.

How it should work: 
Glyph should work only if is active in spec.

Source (you should point out proofs of your report, please give us some source): 
It works right now on my character. Easy to check. 

EDIT: Behaviour is undeterministic. Dont know what exactly conditions should be done to trigger this bug.

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2596
