### ISSUE TITLE
Lock Pick Trading Visual Bug

### ISSUE THREAD

**Issue by shadzenn** [SunwellTracker/issues#269]
Description: 
Hello, ever since I got [Glyph of Pick Lock] I have encountered a visual bug when doing lock picking while trading.

How it works: Currently if you do not have [Glyph of Pick Lock] and pick a lock for someone in the trade window, where their locked box is in the "Will not be traded" section, it will say something along the lines that the box will be unlocked after the trade. But once you get the [Glyph of Pick Lock] to make it an instant cast, when you go to trade the lock picking and use the skill, it won't say it'll be unlocked. But the box does unlock, so it seems to just be a visual bug.

How it should work: With and without [Glyph of Pick Lock] the box should say it'll be unlocked after the trade when being Pick Locked in the "Will not be traded" section of the trade menu.

Source (you should point out proofs of your report, please give us some source): Not at the moment.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
