### ISSUE TITLE
Call of Fire- seek out prophet velen in exodar

### ISSUE THREAD

**Issue by LIttleashes** [SunwellTracker/issues#2691]
Decription: NPC is not at his designated area been waiting an hour for spawn.  Cannot complete quest for Shaman

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Maybe Velen had been killed during your visit?
https://db.darkwizard.pl/?npc=17468
Respawn timer is supposedly 2h. You said you waited an hour -- perhaps it wasn't enough?

**Comment by Dootz** [comment]
![obraz](https://user-images.githubusercontent.com/25490436/71123609-54124e00-21e3-11ea-9587-6d395e4b0061.png)

Like Aridam said Velen has 2h spawn time. Right now he's well and alive :)
