### ISSUE TITLE
Sapphiron extra damage from blizzard

### ISSUE THREAD

**Issue by lkrocek** [SunwellTracker/issues#2696]
Decription: 
Announced: Chill - 6k frost damage.

How it works: 
around 8,5k non-resist-able and 0 resist from all those damages in all tries visible in logs.

> [21:43:59.999] Blizzard (1) Chill \<Player> 8472
[21:43:59.999] Blizzard (1) Chill \<Player> 8484

How it should work: 
as frost dmg resist should work and should do 6k as was announced

Source (you should point out proofs of your report, please give us some source): 
https://sunwell-community.com/index.php?/topic/13826-frosthold-naxxramas-4122019/
http://www.worldoflogs.com/reports/q0t9b5eqblm4eaag/survivability/?s=6434&e=6695

**Comment by Riztazz** [comment]
summoning @Wojtyas

**Comment by smog49** [comment]
To add to the Chill Issues; Chill doesn't follow a player here, instead stays static on the position it spawned leading to no kite being necessary

**Comment by lkrocek** [comment]
Does closed mean deployed on the live?

**Comment by Aridam** [comment]
>Does closed mean deployed on the live?

"Fixed - not live yet" means a fix that's not current on live Realms (f.ex. Frosthold), waiting to be pushed for implementation soon.

"Fixed & Implemented" means a fix that's already on live Realms.

Being closed _should_ mean that it's indeed confirmed resolved (at least by devs).

Should go check it out next time you raid Naxx, or maybe check someone else's logs following the date of the here-noted implementation.
