### ISSUE TITLE
[Eversong Woods] Amani Berserker deals too much damage while enraged

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#27]
Decription: 
Amani Berserker monster deals too much damage while enraged. Got hit for non-crit 48-50 damage with 450 armour and 250 HP at level 11.

Source (you should point out proofs of your report, please give us some source): 
Eversong Woods, Tor'Watha

**Comment by Afgann** [comment]
http://www.wowhead.com/npc=15643/amani-berserker#comments
Comments suggest that he should actually hit really hard, got any proof from retail that he deals too much damage?.
