### ISSUE TITLE
A Gift, Love event

### ISSUE THREAD

**Issue by Katanya06** [SunwellTracker/issues#270]
Decription: 

The text in the quest to give a lovely charm bracelet says it gives a certain amount of experience.
How it works: 
When turning in quest, there is no experience gained.

How it should work: 
Suppose to give the certain experience at levels.

Source (you should point out proofs of your report, please give us some source):

**Comment by dpingel1** [comment]
I can confirm this issue. 
![xp issue](https://user-images.githubusercontent.com/12388775/35894844-4fcf2c4a-0b7a-11e8-912e-120ef170c233.png)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/219
