### ISSUE TITLE
[Warrior] Execute does not proc Sudden Death talent

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#2707]
Decription: Execute skill does not proc Sudden Death talent. 

Execute Spell ID's = {5308, 20658, 20660, 20661, 20662, 25234, 25236, 47470, 47471} maybe 20647 - this one is strange
Sudden Death Talent ID's = {29723, 29725, 29724}

How it works: Hitting an Execute skill from Sudden Death Talent or regular one when the target has less than 20% hp will never proc a Sudden Death Talent on Frosthold.

How it should work: Execute skill should proc Sudden Death talent. This should apply to all Executes: those used below 20% hp and those used via Sudden Death talent so that a back-to-back proc can occur.

Source (you should point out proofs of your report, please give us some source): 

Sources for procing Sudden Death talent back-to-back from Executes used via Sudden Death talent:

1# [Elitist Jerks Forum](https://web.archive.org/web/20100626024854/http://elitistjerks.com/f81/t52872-simulationcraft_s_t_imulating_your_inner_rage/p2/)

"That said, I'm not certain it is. Looking at WWS from last night, I'm seeing things like:

> 0:39'12.563 Jayde melee swing hits Molten Colossus #1 for 3154 Physical. (Critical) #84595
0:39'13.625 Jayde **Execute hits** Molten Colossus #1 for 6871 Physical. (Critical) #84773
0:39'13.625 Jayde **Sudden Death was removed** from Jayde. #84774
0:39'13.984 Jayde **gains Sudden Death**. #84825
0:39'14.391 Molten Colossus #1's Deep Wounds is refreshed. #84874
0:39'14.828 Jayde Overpower hits Molten Colossus #1 for 4903 Physical. (Critical) #84955
0:39'14.969 Jayde melee swing hits Molten Colossus #1 for 1385 Physical. (Glancing) #84977 

> 0:42'54.547 Jayde Heroic Strike hits Magma Rager #2 for 5488 Physical. (Critical) #103819
0:42'54.938 Jayde Mortal Strike hits Magma Rager #2 for 6092 Physical. (Critical) #103869
0:42'55.719 Magma Rager #2's Deep Wounds is refreshed. #103949
0:42'56.531 Jayde **Sudden Death was removed** from Jayde. #104066
0:42'56.547 Jayde **Execute hits Magma Rager** #2 for 8148 Physical. (Critical) #104086
0:42'56.969 Jayde **gains Sudden Death.** #104140

Seems to make it clear that **Execute can proc Sudden Death as well**."

Further into that thread the developer of Simulation craft tool changed the code to accommodate that.

2# [Youtube Link](https://youtu.be/r0YHch8Zq_w?t=61)
**I suggest watching every youtube link in this bug report with 0.25 speed.** 
In this one we see that it was the Execute skill that procced the Sudden Death talent as there is no melee swing or other skill seen in MSBT addon after the Execute.

3# [Youtube Link](https://youtu.be/PeIZDLAtKs0?t=26) Again we see via MSBT addon in the top right that it was the Execute that procced the Sudden Death

4# [Youtube Link](https://youtu.be/PeIZDLAtKs0?t=106) This time Heroic Throw was used before the Execute that procced Sudden Death so we can be extra sure that it was not melee swing that procced it as Heroic Throw resets the swing timer.

5# [World of Logs](http://www.worldoflogs.com/reports/84qyzuzzf39lt9gn/log/?s=13009&e=13251)
Snippet from Arms Warrior named Baltog:

> [21:06:55.414] Baltog Execute General Vezax *9843*
[21:06:55.414] Baltog's Sudden Death fades from Baltog
[21:06:55.414] Baltog Deep Wounds General Vezax 3042
[21:06:55.791] Baltog's Enrage is refreshed by Baltog
[21:06:55.791] Baltog's Enrage is refreshed by Baltog
[21:06:55.791] Baltog gains Sudden Death from Baltog

Notice no skills or swings in between of losing and gaining another Sudden Death proc

Sources for procing Sudden Death talent when using Execute below on target with below 20% hp:

1# [Youtube Link](https://youtu.be/Pr9mmwV5Tgw?t=295) Execute used when target is below 20% hp procs Sudden Death

**Comment by Aridam** [comment]
Gonna test this myself when I'm able. Nice report.

**Comment by Aridam** [comment]
Confirmed. SD doesn't proc from Execute.

**Comment by Riztazz** [comment]
Spent good 10 hours on this one, this one is dumb.. :| Gonna take a break for a day or two before i proceed with this
