### ISSUE TITLE
[MAGE][SKILL] Ice Block delay

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#2710]
Decription: Ice Block sometimes won't save mage even if Ice Block was used. You will have Ice Block on CD but you will still be dead. 

How it works: Ice Block delay kills mage even if Ice Block was used in time.

How it should work: Mage shouldn't be dead when Ice Block was used and is on CD. This COULD be connected with the fact that HP update isn't delayed on Sunwell while abilities are.

You can see how delayed HP update should work here - https://youtu.be/r7CSJqQOypc?t=140

Source (you should point out proofs of your report, please give us some source): https://i.imgur.com/e9Go5pN.jpg

**Comment by Aridam** [comment]
Very good find.

**Comment by Rosenkrantz** [comment]
There is a lot of delay around on the server in general - I can't count how many times I got Psychic Screamed by a stunned Priest (or the Priest got stunned by a feared Rogue? Who can tell the difference :D ), or had other instances of double CC happening. Yes, this stuff all should be possible to do, but not nearly as consistently as it can happen now. I think* that this is all one issue.

* - only an opinion of a single player that has no real authority.

**Comment by Riztazz** [comment]
We won't implement spell batching and we've already said why multiple times, closing.

Rosenkrantz, your issue is something else and it's intended in most cases but that reminds me that i had to tweak a few things around that system

**Comment by Riztazz** [comment]
Spell batching won't be implemented and we've already said why multiple times.

As far as being dead in iceblock, there are spells that can go through iceblock and divine shields, how exactly did you die?

**Comment by Nuy** [comment]
@Riztazz It happened to me few times in PvP so it's not that. It wasn't Mass Dispel and quick execute nor me instantly cancelling IB.
