### ISSUE TITLE
Vengeful Gladiator's Greatsword Missing from Meminnie in Blade's edge mountain

### ISSUE THREAD

**Issue by Enskauning** [SunwellTracker/issues#2712]
Decription: You cant buy Vengeful Gladiator's Greatsword from meminnie also the char from area 52 which  you are suppose to be able to buy it from are not there.

How it works:  You are suppose to be able to buy Vengeful Gladiator's Greatsword but you can't its not showing up.

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2695
