### ISSUE TITLE
Grobbulus Naxxramas 25 berserk time

### ISSUE THREAD

**Issue by 717adi717** [SunwellTracker/issues#2716]
Decription: 
Last night when we raiding Naxxramas 25, Grobbulus casted Berserk after 7 mins of combat.

How it works: 
Berserk after 7 mins of combat

How it should work: 
Berserk after 8 mins od combat

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/42300786/71364135-951bb100-259b-11ea-9a24-50107deb1240.png)

**Comment by Aridam** [comment]
For reference:
https://sunwell-community.com/index.php?/topic/13826-frosthold-naxxramas-4122019/

>Grobbulus
19,1 mln HP vs 9,55 mln HP
Melee Damage - 18k physical damage on well geared tank.
Poison Cloud - 8k nature damage, casts every 15 seconds vs ~4k nature damage
Slime Spray - 20k nature damage every 15 seconds, also spawns Fallout Slime (1hit = 1spawned add) vs ~13k nature damage
Mutating Injection - 8.5k nature damage after debuff fades or being dispelled.
># Berserk - 8 minutes vs 10 minutes

**Comment by Wojtyas** [comment]
https://github.com/SunwellTracker/issues/issues/2655
