### ISSUE TITLE
Incorrect gold values for old raid bosses (e.g. Karazhan)

### ISSUE THREAD

**Issue by DomenikIrrgang** [SunwellTracker/issues#2717]
Decription:  Gold values that drop in old raid (especially Karazhan are wrong). From what I've seen the gold values of the bosses in Karazhan are about 2gold with some exceptions. Also the trash after the opera event should drop about 70s each mob, some more. This is not the case. The gold drops got adjusted during cataclysm in patch 4.2 back then, not during wrath of the lichking.

How it works:  See above.

How it should work:  I don't know the exact values, but bosses should drop about 25gold, trash after opera event about 70s with some mobs droping like 5g.

Source (you should point out proofs of your report, please give us some source):  Example: https://wowwiki.fandom.com/wiki/The_Curator even supposed to drop almost 39 gold

**Comment by DomenikIrrgang** [comment]
Extra: https://www.youtube.com/watch?v=j2FVk8KbOC0 you can see here that the boss drops 38 gold 30 silver and 74 copper during wotlk

**Comment by Aridam** [comment]
> Extra: https://www.youtube.com/watch?v=j2FVk8KbOC0 at 2:17 you can see here that the boss drops 38 gold 30 silver and 74 copper during wotlk

https://wow.gamepedia.com/index.php?title=Attumen_the_Huntsman&oldid=2501881 -- last revision of Attumen on WoWPedia before Cataclysm dates. WoWWiki shows the same money amount.
https://youtu.be/CZYWG01VUMI?t=195 -- WotLK, showing 35g, 85s, 18c.

> Example: https://wowwiki.fandom.com/wiki/The_Curator even supposed to drop almost 39 gold

https://wow.gamepedia.com/index.php?title=The_Curator&oldid=2489246 -- last pre-Cata entry for the the Curator, showing 38g 94s 26c.
https://youtu.be/bFhMB21INdQ?t=298 -- WotLK video timestamp of 40g, 45s, 83c.
https://youtu.be/ZX7o_RS9xL8?t=185 -- also WotLK, showing 35g, 47s, 98c.
https://youtu.be/UttZLcySuic?t=181 -- Cataclysm (use frame-by-frame with `.` and `,`), showing 3g, 65s, 63c
https://youtu.be/WPgmHuPMJ9Q?t=27 -- MoP, showing 3g, 54s, 36c(?).
