### ISSUE TITLE
[Quest][Sons of Hodir][The Storm Peaks]Forging An Alliance

### ISSUE THREAD

**Issue by Blef-pal** [SunwellTracker/issues#2718]
Decription: I'm not able to complete the quest "Forging An Alliance" because i completed quest "Battling The Elements" and Fjorn's Anvil is already in Dun Niffelem.

How it works: 
When i'm in location where should be NPC "Njormeld", "Snori" and "Fjorn's Anvil" all i can see is "Seething Revenant". I can't talk with Njormeld in Dun Niffelem  or King Jokkum. In location near (77, 63) coords i'm not able to see any NPC, probably Njormeld should be there.

How it should work: 
Probably i should't have possibilty to take and complete "Battling The Elements" quest before i start "Forging An Alliance" quest.

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_122419_063030](https://user-images.githubusercontent.com/59190888/71396122-2b41ec80-2619-11ea-8764-782dd0671410.jpg)
![WoWScrnShot_122419_063045](https://user-images.githubusercontent.com/59190888/71396123-2b41ec80-2619-11ea-9f64-6f4353f10c8b.jpg)
![WoWScrnShot_122419_063143](https://user-images.githubusercontent.com/59190888/71396124-2b41ec80-2619-11ea-95fd-6d2702ded83c.jpg)

**Comment by styxel** [comment]
I didnt even read what u said but i made a ticket about something similar and then realized that i had to 'speak' To that anvil In that burning place In your last picture

**Comment by Dootz** [comment]
Hi,

apologies for the late answer. Could you please check if there is any quest you can pick up from Thorin in Temple of Storms? https://wow.gamepedia.com/Temple_of_Storms 
If he won't have anything for you please write an in-game ticket.
