### ISSUE TITLE
Hunter's Piercing Shot

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#2719]
Decription: Hunter's piercing shot that procs from Chimera/Aimed/Steady does not accumulate.
How it works:The dot applied by the piercing shots refreshes itself but the damage does not acummulate.

How it should work: Further critical strikes should refresh the piercing shot debuff AND add to the new, refreshed debuff any damage that didn't go off in the previous application.

Source (you should point out proofs of your report, please give us some source): 
https://web.archive.org/web/20130318032352/http://www.warcrafthuntersunion.com/2010/11/how-piercing-shots-works/

https://github.com/TrinityCore/TrinityCore/issues/19881

TrinityCore/TrinityCore#3256 - the way how should work.

**Comment by Soufly** [comment]
Should piercing shots work just like ignite(from fire mage) or no i wonder ? Because ignite does a lot of damage compared to piercing shots.

**Comment by Aridam** [comment]
Further info from an archived BlueTracker topic, back when Piercing Shots had a bug:
https://web.archive.org/web/20090310030104/http://blue.mmo-champion.com/28/15443410287-mm-hunters-bugs-with-piercing-shots-on-ptr.html

**Comment by keepokappalul** [comment]
https://www.wowhead.com/spell=53238/careful-aim#comments
Second comment:
1) You can't "waste" crits
2) your DPS will ramp up and up and up the longer these crits keep getting refreshed

**Comment by keepokappalul** [comment]
Right now on Sunwell the damage is based on your average steady shot crits(most usable ability out of the 3),instead of bumping up from Chimera and Aimed.

**Comment by keepokappalul** [comment]
Right now on Sunwell the damage is based on your average steady shot crits(most usable ability out of the 3),instead of ramping up from Chimera and Aimed.
Also here the guy from the second comment explained it verry well:
https://www.wowhead.com/spell=53238/careful-aim#comments

You can't "waste" crits
your DPS will ramp up and up and up the longer these crits keep getting refreshed

**Comment by keepokappalul** [comment]
My guess is that the damage is based on your average steady shot crits(most usable ability out of the 3),instead of ramping up from Chimera and Aimed.
Also here the guy from the second comment(eagleeye1975) explains it very well:
https://www.wowhead.com/spell=53238/careful-aim#comments

1.You can't "waste" crits
2.your DPS will ramp up and up and up the longer these crits keep getting refreshed

**Comment by keepokappalul** [comment]
https://www.mmo-champion.com/threads/704411-Piercing-Shotz-and-Serpent-Stang?highlight=piercing+shot
Lysah's comments from 2010-03-25 (patch 3.3.3).

**Comment by keepokappalul** [comment]
My guess is that the damage is based on your average steady shot crits(most usable ability out of the 3),without ramping up from Chimera and Aimed.
Also here the guy from the second comment(eagleeye1975) explains it very well:
https://www.wowhead.com/spell=53238/careful-aim#comments

1.You can't "waste" crits
2.your DPS will ramp up and up and up the longer these crits keep getting refreshed

**Comment by keepokappalul** [comment]
https://us.battle.net/forums/en/wow/topic/2059057006 - 4th comment
''This was not the way it worked when I was actively raiding as MM in Wrath of the Lich King. Back then each critical hit that caused a Piercing Shot added to the existing DoT as well as refreshed it, the value of each tic went up and down as damage was added or expired.''

**Comment by keepokappalul** [comment]
https://www.wowhead.com/forums&topic=120530 - u might check aswell this,its a similar effect.

**Comment by keepokappalul** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3256

**Comment by keepokappalul** [comment]
Still waiting >)))

**Comment by keepokappalul** [comment]
http://worldoflogs.com/reports/2deyfw3tuusjsb8c/details/33/?s=3099&e=3287 - Retail logs
https://www.mmo-champion.com/threads/701494-Piercing-Shots-question - patch 3.3.2

**Comment by Riztazz** [comment]
Looked at the code and it handles accumulating damage from previous aura. Did in-game tests as well and it works just fine, please re-test.

Before refreshing piercing shots, leftover damage (so damage that has been already dealt is not included) from current PS is taken and applied to new PS dmg

**Comment by keepokappalul** [comment]
> Looked at the code and it handles accumulating damage from previous aura. Did in-game tests as well and it works just fine, please re-test.
> 
> Before refreshing piercing shots, leftover damage (so damage that has been already dealt is not included) from current PS is taken and applied to new PS dmg.
> 
> Please provide proof if it's supposed to work differently

Is it adding the damage from Chimera/Aimed crits,or just refreshing Steady's crits,thats the question ? If the answer is yes,u can close the report.

**Comment by Riztazz** [comment]
It adds damage from chimera/aimed.

Let's say your dot overall damage (over entire duration of DoT) deals 8000 damage (which is 1000 dmg per tick) - there is 2 ticks left and now you crit once again, those two ticks - in this case its 2000 damage - gets added to new PS damage and then it's divided per tick :P closing then
