### ISSUE TITLE
hunter pets dissapear

### ISSUE THREAD

**Issue by lucario201** [SunwellTracker/issues#2722]
Decription: Decription:
I am 80lvl hutner with dual spec. I have 5 slots in my Stable. When i switch pet, sometimes it dissapears. yesterday i was lost my spider 80 lvl, and today i lost my Wolf 80lvl and spider again. I just switch pet, and it's gone. In stable i recieve empty slot instead of stabled pet. Also i have rare pets like spirit beast in my stable and im scared . 

How it works:
Pet sometimes dissapears when switching from stables. Problem starts to occur when i bought dual-spec.

How it should work:
Pet should not dissapear.

Source (you should point out proofs of your report, please give us some source): Desmond, Frosthold, hunter lvl 80.

U should fix it cuz to many ppl got the same problem with pets..

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2698
