### ISSUE TITLE
CHARGE on CC

### ISSUE THREAD

**Issue by Diocane94** [SunwellTracker/issues#2724]
Decription: When a warrior charge a druid whit nature grasp or a mage whit icearmor and proc the froze, the warrior will be froze / rooted on starting position and not under the enemy

How it works: When a warrior charge a druid whit nature grasp or a mage whit icearmor and proc the froze, the warrior will be froze / rooted on starting position and not under the enemy

How it should work: When a warrior charge a druid whit nature grasp or a mage whit icearmor and proc the froze, the warrior will be froze / rooted on starting position and not under the enemy

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
https://github.com/SunwellTracker/issues/issues/2529
