### ISSUE TITLE
[Priest] Holy Talent - Inspiration - Prayer of Mending does not proc the buff

### ISSUE THREAD

**Issue by Eksekk** [SunwellTracker/issues#2726]
Description:
According to the tooltip of the Holy Talent Inspiration, Critical Heals of Prayer of Mending should proc the Inspiration buff on the target. Currently, this does not seem to work.

How it works:

Cast Prayer of Mending on target
Target gets damaged.
Prayer of Mending heals and crits the target.
Target does NOT get the Inspiration buff.
How it should work:
4. Target does get the Inspiration buff (after a critical heal from Prayer of Mending).

Source (you should point out proofs of your report, please give us some source):
I have tested this in party and raid environment with my main priest multiple times. Also confirmed by Azathothh after a short conversation.

Kind regards,
Bandyto

**Copy of #1701, because nobody seems to notice my comments that it is still not working.**

**Comment by Riztazz** [comment]
Please do test after restart

**Comment by Eksekk** [comment]
Working! Thanks for the fix :)
