### ISSUE TITLE
Lightning Overload issue

### ISSUE THREAD

**Issue by Shootthepopo** [SunwellTracker/issues#2727]
Decription: 
Lightning Overload gives you X% chance to proc Lightning Bolt or Chain Lightning the second time, for half a damage, with no cost or cast time.

How it works: 
I recently found out it doesn't work properly. Instead of casting another Lightning Bolt after the first one, it casts multiple ones at once.

How it should work: 
It should only cast 1 additional Lightning Bolt/Chain Lightning after hitting the proc.

Proof: 
![WoWScrnShot_122419_212354](https://user-images.githubusercontent.com/59256359/71478868-0d7baf80-27f2-11ea-8378-7968ed22c804.jpg)

As you can see on the screenshot, 4 Lightning Bolts were casted at the same time but the animation showed only 2.

**Comment by Aridam** [comment]
Ouch, that's a doozie -- practically allows Eles to be overpowered, given favorable RNG, looks like. This is sorta like how it was way before WotLK, before changes to LO (was a bug on Retail that got patched out eventually -- someone correct me here on that tidbit if necessary), so you wouldn't get 29867298627698 back-to-back LO procs proccing off LOs so you could LO while you would LO, 'cause people liked LO-ing. 

Links for reference:
https://www.wowhead.com/forums&topic=155262
https://web.archive.org/web/20101122053506/http://elitistjerks.com/f47/t82625-shaman_elemental/

https://www.youtube.com/watch?v=3RW4FSm5zXY
https://www.youtube.com/watch?v=jGCP-1H_Arg
https://www.youtube.com/watch?v=So8OCpXDGN8

**Comment by Aridam** [comment]
So, _why_ was this closed as "invalid"?
