### ISSUE TITLE
Quest Lifeblood of the Mosswalker shrine

### ISSUE THREAD

**Issue by Rayan532908** [SunwellTracker/issues#2729]
Decription: I cant complited this quest because injured mosswalkers dont drop shrines . 

How it works: when i completed quest Mosswalker Savior during collected shrines to quest Lifeblood of the mosswalker shrine i cant completed this .

How it should work: when i complete quest mosswalker Savior i can collect shrines from injured mosswalkers but they are disabled . i speak with someone from injured mosswalkers and i dont have any choice .

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
No source/proofs.
