### ISSUE TITLE
blazing hippogryph runs at player speed

### ISSUE THREAD

**Issue by scruffer** [SunwellTracker/issues#273]
Decription: 

slow ass bird when in battlegrounds or 'old world' content
How it works: 
mount runs at normal player speed instead of 60% or even 100% bonus movement while in non-flying areas

How it should work: 
it should probably be a fast bird

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
Blazing Hippogryph shouldn't even be usable in non-flying areas.

http://www.wowhead.com/item=54069/blazing-hippogryph#comments
"By rowanr (6,008 – 1·14·37) on 2011/06/29 (Patch 4.1.0)
Mount is now usable as a ground mount as of 4.2. Thank you for finally listening Blizzard!"
