### ISSUE TITLE
[ROGUE][TALENT] Heightened Senses

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#2730]
Decription: This talent is really broken in PvP right now.

How it works: Gives way more than 4% miss chance. In reality you miss around 30% of your spells on rogue that uses this talent.

How it should work: Should reduce hit chance by 4%, not more.

Source (you should point out proofs of your report, please give us some source): -

**Comment by Wojtyas** [comment]
No source/proofs.
