### ISSUE TITLE
Quest The Ghostfish

### ISSUE THREAD

**Issue by koishi-666** [SunwellTracker/issues#2731]
Decription: 
You are supposed to fish a quest item fish in Sholazar basin

How it works: 
The drop rate is too low, makes people fish for a very long time in Sholazar, compared to the other fishing dailies which are completed in 2 to 5 minutes

How it should work: 
Higher drop rate

Source (you should point out proofs of your report, please give us some source):

**Comment by Wojtyas** [comment]
No source/proofs.
