### ISSUE TITLE
The Stones That Bind Us Quest Bugged

### ISSUE THREAD

**Issue by vorhix** [SunwellTracker/issues#2732]
Decription: 'The Stones That Bind Us' quest in the Blasted Lands is bugged as the mobs required are invincible and can't be killed.

How it works: The mobs that require to be killed can't be killed.
https://www.youtube.com/watch?v=ZyfrZ_6cyNI

How it should work: See source.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=xMXNXWS3kxY

**Comment by Dootz** [comment]
Hi, you must use stones which are nearby to "free" servants. See an example: https://youtu.be/AgoK-XGn0H0
