### ISSUE TITLE
DB/Creature: Dustwallow marsh beasts and invalid loot templates

### ISSUE THREAD

**Issue by wrekonizegamer** [SunwellTracker/issues#2734]
Decription: 
Skinning Dragonkins in Dustwallow Marsh barely drops Leather,instead the corpse just disappears.
How it works: 
Mob gets killed, skinned dropping any of the mentioned in Wowhead.

How it should work: 
Skinning these mobs must drop at least a single leather

Source (you should point out proofs of your report, please give us some source): 
https://classic.wowhead.com/npc=4334/firemane-flamecaller#skinning

**Comment by Riztazz** [comment]
@Dootz Could you take a look when you're around?
