### ISSUE TITLE
Wind Shear Resist 

### ISSUE THREAD

**Issue by tiszka** [SunwellTracker/issues#2735]
Decription: 
Wind Shear spell could resist at bosses/trashes. Bosses and creatures haven't any resistance so this spell shouldn't resist. Screenshots below.

How it works: 
Wind Shear colud resist at bosses/trash.

How it should work: 
Wind Shear souldn't resist.

Source (you should point out proofs of your report, please give us some source): 
![resist1](https://user-images.githubusercontent.com/59346321/71563897-c1519900-2a97-11ea-9251-0d299dd4bd69.jpg)
![resist2](https://user-images.githubusercontent.com/59346321/71563898-c1519900-2a97-11ea-8750-2b5aab1eac28.jpg)

**Comment by Piootrek** [comment]
Please provide a proofs from Blizzard's servers.

**Comment by tiszka** [comment]
Below are links from 2id guild Method form blizz server. This is from ICC, cuz i cant find logs from Naxx content. This is query for Wind Shear [{"spellNames": ["Wind Shear"]}] and boss like Lady where shamans uses Wind Shear to interupt Frostbolt have 0 resist.

http://www.worldoflogs.com/reports/rnyhwb053jp6bxqn/log/?s=1384&e=1799
http://www.worldoflogs.com/reports/b2k9jsgjwxc5urmd/log/?s=1225&e=1742

**Comment by Kwyzard** [comment]
have you checked all spell because, faerie fire (nature same as wind shear i guess) application sometimes resist on some naxxramas boss
