### ISSUE TITLE
Omen of clarity bug after recent fix

### ISSUE THREAD

**Issue by excentric21** [SunwellTracker/issues#2738]
Decription: Omen of clarity proc is happening pretty much every 4 seconds when beacon is on a druid 

How it works: Just beacon a druid and watch clearcasting.

How it should work: Beacon should not affect clearcasting procs in anyway whatsoever

Source (you should point out proofs of your report, please give us some source): https://streamable.com/24w37

**Comment by styxel** [comment]
Skill used To proc from the wierdest stuff on retail but procs like this should def be fixed or i better start asking for beacons instead of tricks lul @Riztazz

**Comment by Riztazz** [comment]
This spell is stupid... i'm working on it

**Comment by Riztazz** [comment]
OOC has been updated with new script.. again :(
By the way, i've noticed your chat during that streamable vid.
I had to enable all procs for that stupid spell and then disable everything that doesn't make sense, i didn't realize beacon will behave the way it did, hopefully this iteration covers everything

**Comment by Riztazz** [comment]
Realm updated, please do test when you have a few minutes.
I'll leave this topic open for a few days, if anything is wrong please post it here

**Comment by styxel** [comment]
@Riztazz spell seems To work properly now atleast from my experienced and havent seen complaints. But u missed one fix which was gift of the wild, see it used To have increased proc chance depending on how many People it buffs something that ferals would always Do before pulls but then again If this is something that might break the spell then u should propably leave it as it is. But thats one thing that came in mind.
