### ISSUE TITLE
[Item] Flask of the North (Alchemists only)

### ISSUE THREAD

**Issue by theadrix33** [SunwellTracker/issues#274]
Decription: When using Flask of the North, it cycles between giving the +40 strength buff or the +47 spell power buff. It's missing the chance to get +80 attack power. I've used the item 100+ times and have yet to receive the attack power buff.

How it works: Item is only giving 2 out of the 3 buffs it can give.

How it should work: Item should have a 33.33% chance to give 1 of 3 buffs fairly.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
What class are you playing?

**Comment by Piootrek** [comment]
Flask of the North works correctly.
"If you are a Druid, Death Knight, Warrior or Paladin you CANNOT get the attack power buff from this item."
Source: http://www.wowhead.com/item=47499/flask-of-the-north#comments:id=1001401
