### ISSUE TITLE
[PRIEST] Levitate spell

### ISSUE THREAD

**Issue by sbholy** [SunwellTracker/issues#2741]
Decription: 
levitate spell doesnt work correctly

How it works: 
it makes me run in the air, few feets above the ground

How it should work: 
it should make me leviate, float above the surface. rather than run in the air.

Source (you should point out proofs of your report, please give us some source): 
in-game experience

**Comment by Riztazz** [comment]
https://youtu.be/ktz83l1Q_Mc

**Comment by Riztazz** [comment]
Not really
https://youtu.be/ktz83l1Q_Mc
