### ISSUE TITLE
Devour magic - friendly targets case

### ISSUE THREAD

**Issue by felmad** [SunwellTracker/issues#2743]
Decription: 
Devour magic (felhunter dispell) does not dispell enemy magical effects from friendly targets behind LoS and targets that are OoR + gets stuck in place after that.

How it works: 
When we try to use Devour magic on friendly target that is behind LoS of the pet or is OoR of the pet, Felhunter cannnot use it at all. In addition to that, pet stops moving and will not move again until commanded to move with follow function - this also happens when pet has set follow as deafult.

How it should work: 
It should work just like it works with unfriendly targets - when Devour magic is used against the target that is behind LoS of the pet or is OoR of the pet, Felhunter runs to the target, and when it gets required range or has LoS, it uses the ability. Also, after the dispell, pet comes back to the position when the Devour magic was used - if on passive, Felhunter returns to the place where it has stayed before the ability was used, and if on follow, it returns to the side of its master.

Source (you should point out proofs of your report, please give us some source): At the moment I can't provide any sources, hovewer I can point out that this behaviour (the correct (?) one) could be found on the older alteration of Sunwell (before Angrathar) or can be found in quite-well-know other WotLK PvP server.
P.S. I know that does not count as source, but right now I'm out of sources. Would be also glad if anyone that is interested in this topic could provide some sources under this report.

**Comment by Riztazz** [comment]
Closing due to duplicate
