### ISSUE TITLE
MOBs Above Water

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2744]
Decription: This goes for MOBs throughout the game. You're going to have to check every single MOB that's supposed to have its place under water.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010120_034005](https://user-images.githubusercontent.com/58756521/71644252-5b316580-2c93-11ea-9666-16ffb5d8287c.jpg)

**Comment by Riztazz** [comment]
Duplicate, somewhere on the issuetracker - i know about that issue and is something im actively tracking to figure out best solution for that issue
