### ISSUE TITLE
MOBs Are Too Fast

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2747]
Decription: This MOB can keep up with a 100% mount.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010120_035229](https://user-images.githubusercontent.com/58756521/71644275-d135cc80-2c93-11ea-85c6-7415b70469ab.jpg)

**Comment by Riztazz** [comment]
Thank you for reporting stuff but could you please make per npc titles? Most of the issues are related to specific NPCs - not all of them and sadly you do not post much data about which NPC it is besides screenshot

**Comment by Knewklear** [comment]
The MOB's name is clearly shown within the picture. Can the picture not be enlarged?

**Comment by Dootz** [comment]
https://www.wowhead.com/npc=24871/risen-vrykul-ancestor#comments:id=498540
"Don't try running by these guys on a regular land mount. They can run nearly 100%. If not 100%."
