### ISSUE TITLE
Improper MOB Placement

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2748]
Decription: MOB doesn't belong here and won't move.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010120_042049](https://user-images.githubusercontent.com/58756521/71644283-ea3e7d80-2c93-11ea-91ce-3837090fd8fe.jpg)

**Comment by Dootz** [comment]
Hi, that's where he starts his march to dark portal. He should move after some time. Last time I checked he was at dark portal. I'll visit him from time to time to see if he's stuck. Thanks for report :)
