### ISSUE TITLE
No Combat

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2751]
Decription: Aren't these MOBs and NPCs supposed to be in combat and not just staring each other down?

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_123119_230151](https://user-images.githubusercontent.com/58756521/71644296-38ec1780-2c94-11ea-8ac5-06a44aa9eff8.jpg)

**Comment by Piootrek** [comment]
Is it a question or bug report? Please provide proofs.

**Comment by Knewklear** [comment]
Perhaps you could have waited 24 hours after your reply before closing the issue. People can't answer replies as immediately as you'd like. This was a question. I looked through some videos myself and unfortunately, I couldn't find what I needed. I thought that a devloper, someone who was more experience in knowing what's supposed to be going on would know if these two MOBs are supposed to be in combat or just standing there
