### ISSUE TITLE
Player Animation

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2757]
Decription: After completing the quest "going bearback", you get off of icefang with a shooting animation until you move

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010120_225445](https://user-images.githubusercontent.com/58756521/71656268-b8b3c980-2d08-11ea-9779-807a4501c487.jpg)

**Comment by Riztazz** [comment]
Client issue, not server-side issue
