### ISSUE TITLE
Thunderstorm and Spell Reflect

### ISSUE THREAD

**Issue by ahilison** [SunwellTracker/issues#276]
Decription: 
I was able to reflect the thunderstorm.

How it works: 
So I've reflected the thunderstorm and the shaman got knocked back and he received the damage.

How it should work: 
The thunderstorm spell should bypass the spell reflect (ignore it)

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
Any proof (that's what "source" is for btw)? I didn't find anything from 3.3.5a exactly, but here are some links, where people say, that thunderstorm actually was reflected during wotlk:

http://www.wowhead.com/forums&topic=106044/list-of-spells-that-can-be-reflected
"By DaCyclops on 2009/07/06 at 4:31 AM (Patch 3.1.3)
As mentioned, there are some exceptions. Some mobs in the Opening the Dark Portal apparently use a reflectable cone attack. You can apparently reflect Death Grip and the DK will be pulled to you. If you have reflect up when a Shaman uses Thunderstorm without the glyph, it throws THEM backwards."

https://www.mmo-champion.com/threads/624196-Thunderstorm-amp-Spell-Reflection
Thread where someone reports that thunderstorm is reflectable, although he thinks it's a bug (no further report that it was changed).

http://www.arenajunkies.com/topic/41625-warriors-can-reflect-thunderstorm-video/
Same as above.

https://eu.battle.net/forums/en/wow/topic/3888479045
Thread from official blizzard forums, it's from cata but some people mention that thunderstorm was reflectable during wotlk.
"Why doesn't it work?
It worked in wotlk."

**Comment by Kokaina** [comment]
More info needed, atm I found split opinions in web. Any video?

**Comment by ujellyx** [comment]
Any AoE-spell can't be reflected by spellreflect - and Thunderstorm is such AoE-spell. So it shouldn't be reflected.

**Comment by set-theorist** [comment]
The evidence from Cwiercpasiec seems enough for me. This is working as intended and bug report is invalid.
