### ISSUE TITLE
[Druid, Item]Illustration Of The Dragon Soul

### ISSUE THREAD

**Issue by Fixyourshit156** [SunwellTracker/issues#2761]
Decription: Item: Illustration Of The Dragon Soul

How it works: Rejuv, Life bloom, and Wild Growth casts dont give stacks

How it should work: They should.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/forums&topic=117574/healing-and-tanking-trinket-questions
Pretty obvious that one of the best resto druid trinkets should actually work on resto druids.

**Comment by Fixyourshit156** [comment]
Also pretty sure it worked like a week ago

**Comment by styxel** [comment]
@Riztazz related To Omen of clarity fix somehow?

**Comment by Fixyourshit156** [comment]
Might also be related to this fix as well https://github.com/SunwellTracker/issues/issues/2704

**Comment by Riztazz** [comment]
Not related to OOC fix

**Comment by Fixyourshit156** [comment]
Im not hostile, sir. Just kinda peeved that a best in slot item is literally unusable when it worked flawlessly a week ago.

**Comment by pipe-z** [comment]
@Riztazz there's also a 30sec cd on the trinket procc when equipping the item. 
Same with Majestic Dragon Figurine (https://wotlk-twinhead.twinstar.cz/?item=40430).
Dno if this is intended or not, since there's no "on-use" effect.

**Comment by Riztazz** [comment]
30 second cooldown is intended, even for on-action trinkets.

@Fixyourshit156 
Well, your name kinda is and that's called regress and that happens a lot when you fix stuff.. WoW is extremely tangled and touching one system might affect another
