### ISSUE TITLE
[Quest] Dragonblight

### ISSUE THREAD

**Issue by ciuruici2k5** [SunwellTracker/issues#2764]
Decription: [Hard to Swallow] Battle a Hulking Jormungar east of Nozzlerust Post until it opens its mouth, then throw a Potent Explosive Charge into its throat. After it explodes, collect 6 slabs of Seared Jormungar Meat off of the ground and bring them back to Xink.

How it works: 
After attacking a Hulking Jormungar for 15-20 seconds, a message should appear and his mouth should open wide, and be able to throw a bomb in it. This does not happen and i end up killing the worm.

How it should work: 
the Worm should open his mouth.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/71767094-94bed680-2f08-11ea-9c57-7660819cfef1.png)
![obraz](https://user-images.githubusercontent.com/37483678/71767099-a0aa9880-2f08-11ea-8aea-50aabd9f9b11.png)
Looks fine for me - maybe you've somehow disabled such messages through addons.
Tried to do it with stunned mob as well and been still getting message and could use bomb. 
Only thing that could be wrong is Jormungar Meat not being spawned if mob was stunned during explosion (not sure if that's blizzlike or not)

More detailed info is required
