### ISSUE TITLE
Locked in game for raid

### ISSUE THREAD

**Issue by dopersad** [SunwellTracker/issues#2766]
Decription: Im currently Lock for OS25 on my Death knight (Spicc) when it was reseted and i just did it on my paladin not my death knight.

so can you guys unlock it so i can do it with my Death knight also

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
There is literally no way for you to get a bind on death knight while playing on a paladin, closing. Stuff like that is dealt by GMs
