### ISSUE TITLE
[Rogue] Hack and Slash + Rupture

### ISSUE THREAD

**Issue by Elaatu** [SunwellTracker/issues#277]
**Opis:**
Jeśli w momencie użycia Rupture procnie nam talent Hack and Slash to dmg z Hack and Slash idzie w gracza. 

**Jak działa na sunwellu:**
Dmg z Hack and Slash który proca w momencie nałożenia Rupture zadaje dmg graczowi

**Jak powinno działać:**
Dmg z Hack and Slash który proca w momencie nałożenie Rupture powinien zadać dmg targetowi.

**Dowód:**
Logi: http://worldoflogs.com/reports/npeuzrgq92qy6p01/log/?s=1838&e=1994
Query: [{"eventTypes": [1], "targetNames": ["Kiro"], "actorNames": ["Kiro"]}, {"spellNames": ["Rupture"], "eventTypes": [6], "actorNames": ["Kiro"]}]

[19:47:03.769] Kiro crits Eydis Darkbane *3132*
[19:47:04.327] Kiro casts Rupture on Eydis Darkbane
[19:47:04.327] Kiro crits Kiro *3604*

**Comment by Azathothh** [comment]
Fixed already.
