### ISSUE TITLE
Ghost form doesn't get flying mount to reach inaccessible places of Northrend (low level zones)

### ISSUE THREAD

**Issue by Huntender** [SunwellTracker/issues#2774]
Decription: places elevated from the ground are impossible to reach during ghost form after coprse release

How it works: if you die on a tree or on a mountain you can't reach the place by yourself as you don't get offered a flying mount. this happens _at least_ in Sholazar Basin and Dragonblight.

How it should work: when the character dies in places above the ground, say higher than the corpse spawn range, you should get the flying form ghost so you can reach the place.

Source (you should point out proofs of your report, please give us some source): 
I'm pretty sure it should work like this but i haven't been able to find any source. hopefully someone else will be able to provide them to progress with this issue.

**Comment by Azathothh** [comment]
"In general, you can run much faster and walk on water in spirit form.

Some special cases:

    In Wrath of the Lich King, when dying in Icecrown, Storm Peaks, or Crystalsong Forest, players will have access to a spectral gryphon upon death to retrieve their corpse because you cannot always climb the mountainous regions. However, since Night Elves are wisps they don't have the gryphon, they can simply fly. "
https://wowwiki.fandom.com/wiki/Death
