### ISSUE TITLE
Quest: I Sense A Disturbance

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2775]
Decription: On the way back to Kar'koa, the kitten that you ride on suddenly speeds up to beyond normal ride speed and then stops, and then floats along the path it's supposed to take

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, kitten is supposed to speed up when coming back. See https://youtu.be/sDYVoDT5MDo?t=110 for reference. We'll make some adjustments when it comes to floating :) Thank you for report.
