### ISSUE TITLE
MOB Pathing

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2776]
Decription: MOBs around this area (refer to minimap and coordinates) seem to go around invisible objects instead of linear, towards you.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010420_173038](https://user-images.githubusercontent.com/58756521/71775542-82688b00-2f50-11ea-901e-9e461788823b.jpg)

**Comment by Dootz** [comment]
23/11/2020 - tested, creatures spawned in the same phase as object go around it. Creatures spawned in phase other than object - go through it.
