### ISSUE TITLE
MOB Pathing

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2778]
Decription: MOBs are running in place instead of walking around.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010420_184743](https://user-images.githubusercontent.com/58756521/71775572-ff940000-2f50-11ea-83ac-123cc363300b.jpg)

**Comment by Dootz** [comment]
23/11/2020 tested, cannot reproduce
