### ISSUE TITLE
Quest: The Last Line Of Defense

### ISSUE THREAD

**Issue by Knewklear** [SunwellTracker/issues#2781]
Decription: After completion, character is stuck and can't move. I was stuck in running and couldn't log out or hearth or mount.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_010420_213309](https://user-images.githubusercontent.com/58756521/71775595-441f9b80-2f51-11ea-9970-6e7601820f05.jpg)

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/1232
