### ISSUE TITLE
Hunter's Auto Attack

### ISSUE THREAD

**Issue by wrekonizegamer** [SunwellTracker/issues#2788]
Decription: 
If targetting a mob for auto attack, hunter draws Main Hand Weapon instead of bow..

How it works: 
Right Clicking a mob in the range of hunter forces the hunter to draw his main hand weapon, only pet attacks.

How it should work: 
should make the hunter auto attack with bow if within the applicable range & any ammo exists in bag, otherwise should attack with axe only if in melee range.

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/forums&topic=134921
https://classic.wowhead.com/spell=75/auto-shot#comments

**Comment by Aridam** [comment]
There should be an option somewhere in Interface that does that automatically for you.

**Comment by Riztazz** [comment]
This is all handled client-side, nothing i can do about that, closing

**Comment by wrekonizegamer** [comment]
i've downloaded a new client after checking my autoshot option enabled on old one yet not working, now its working , Thank you <3
