### ISSUE TITLE
Klaven's Tower

### ISSUE THREAD

**Issue by Thunderlordking** [SunwellTracker/issues#2789]
Decription: 
Class question. He does not drop the key needed to do the quest

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Nothing wrong with this quest - you have to PICKPOCKET key from Malformed Defias Drone.
Also keep in mind that this key SHOULDN'T open chest inside tower, you have to use lock picking in order to open it.
