### ISSUE TITLE
Vanish ( rogue ) 

### ISSUE THREAD

**Issue by Volas10** [SunwellTracker/issues#2790]
Description: Vanish does not remove combat during boss fights ( it should make potions go on cd )

How it works: Use potion during boss encounter, cast vanish - potions doesnt start filling  cool down - should be instant effect

How it should work: Cast vanish and leave combat briefly - potions go on cd
Its common knowledge it doesnt work on this server.

**Comment by Soufly** [comment]
Its on purpose i think.

**Comment by Azathothh** [comment]
That's blizzlike behaviour - combat shouldn't be removed during boss fights.
