### ISSUE TITLE
PVP flag indicator

### ISSUE THREAD

**Issue by Milenski10** [SunwellTracker/issues#2795]
Decription: I have several characters on Frosthold server alliance side. I have an issue with only 1 of the characters. When i go through the portal from Dalaran to Stormwing or Ironforge, i get flagged to PVP with this character and this status stays forever or until i teleport back to Dalaran, when pvp flag sets back to "disabled". This character has "pvp disabled" status. Then, when i am in Stormwind or Ironforge, if i want to log off or exit, the 20sec appears. This does not happening with other characters i have.

How it works: 

How it should work: 1.When i port through Dalaran portal to Stormwind or Ironforge, i should not get flagged for pvp. I dont know how this work exactly, but even if getting flagged is normal in this case, then still 5 minute timer should starting to count to get player to non flagged status. 2.When you are in non-contested territory, logging off or exition should be instant - no 20 seconds time should appear.

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment]
Do you happen to have a Quest which is intended to mark you for PvP? An example is [this one](https://wow.gamepedia.com/Make_Them_Pay!), because it's a PvP Quest, and as per [this link](https://wowwiki.fandom.com/wiki/PvP_flag), you get marked for PvP while such a Quest is in your Log.

**Comment by Milenski10** [comment]
Yes, now my problem is solved. I had this pvp quest in my quest log indeed. I abandoned it and now i dont get flag for pvp when i pass trough these portals to SW and IF. Thank you very much.
