### ISSUE TITLE
Quest: Supplies to Auberdine

### ISSUE THREAD

**Issue by AbraKabastard** [SunwellTracker/issues#2798]
**_Decription:_** 
Feero Ironhand should engage in combat with the hostile NPCs that spawn along the way to Auberdine.

**_How it works:_** 
He do not, with majority of the spawns except for the final 3 satyrs. In fact, I engaged in combat with one set of mobs.. out ran them and they lost aggro and they ran home and despawned. He doesn't engage in combat when the player does, like other escorts do.

![WoWScrnShot_011020_153938](https://user-images.githubusercontent.com/35535856/72208066-f507c800-3474-11ea-88b9-60d733287a6f.jpg)
https://classic.wowhead.com/quest=976/supplies-to-auberdine

**Comment by Dootz** [comment]
Hi, for me he engaged very first group and died to them :D Can someone please confirm if you experienced similar behavior to one described by Abrakabastard?
