### ISSUE TITLE
Deadmines Dungeon

### ISSUE THREAD

**Issue by SpectraQWERTY** [SunwellTracker/issues#28]
Decription: 
Current version of deadmines is litteraly just stock core and is completely not scripted like i noticed on most other servers aswell. Here are some issues:

1. After a boss has been slain, the door opens and the group just progresses. 

2. Mr. Smite doesnt pull when u pull the stealthed defias blackguards. Instead he pulls when u do a ranged ability and also brings the adds on the upper platform.

3. Captain Greenskin patrols without additional mobs patrolling with him

4. Noticed weird mob behaviour when mobs try to escape combat at low HP.  ( If they are on a lower platform they will bug out and run through the platform to the upper one etc.) 

How it should work:
1. After a boss has been successfully slain a wave of "Mini mobs" should appear from the entrance of the lair (randomized between 1 melee and 2 ranged casters or 2 melee and 1 ranged caster)

2.  Mr. Smite should pull when u destealth the defias blackguards. He also shouldnt pull the trash that is on the platform with him.

3. Captain Greenskin should have about 3 Defias  mobs patrolling with him.

4. Work on mob pathing a little bit more to make it perfect.

Source (you should point out proofs of your report, please give us some source):  I'll update the post when i find some,

**Comment by Dootz** [comment]
will be fixed with next server update
