### ISSUE TITLE
Item: The Dusk Blade

### ISSUE THREAD

**Issue by ShinsuRogue** [SunwellTracker/issues#2800]
Decription: 
We have a The Dusk Blade (https://db.darkwizard.pl/?item=43613). He have a proc with 155 ArP in 10 sec, 3 stack.

How it works: 
If i damage with dagger in main hand with SnD, and i can't stack 2 proc. For example, i have a 1 proc per ~50-90 sec. Randomly.

How it should work: 
I think it should work, you have fix proc chance like a 10-20%, now it's look like 1-3%.

Source (you should point out proofs of your report, please give us some source): 
It's rare dagger for rogues only, i can't find video proof.

**Comment by Piootrek** [comment]
Hello. Proc rate indeed seems to be too low. I changed it to 10%.
