### ISSUE TITLE
Frosthold Warlock/Voidwalker

### ISSUE THREAD

**Issue by Etnice** [SunwellTracker/issues#2801]
Decription: Its About Voidwalker spells called "Consume Shadows"

How it works: You need use it like 3 sometimes 5 times to spell start working, and you only loosing mana , becouse this it's hard to play, your summon can't be healed. Its channeling spell.

How it should work:  When you use it ,after combat, your voidwalker should channel that spell and should be healed.

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
I pushed possible fix for this issue. Please let me know if problem still occurs after update.

**Comment by vangop** [comment]
Hi,
thanks for the fix, will it be live anytime soon? leveling a lock is much harder without it working.
