### ISSUE TITLE
Arcturis(Spirit Beast) Not Spawning

### ISSUE THREAD

**Issue by wrekonizegamer** [SunwellTracker/issues#2802]
Decription: 
I have been camping the spot of Arcturis in hope to tame that pet, i have been camping the spot for 10 days now and Legit it never spawned (Even after server starts)

How it should work: 
Arcturis should spawn on server reset or at least within 12 hours of its death

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=38453
https://www.wowhead.com/npc=38453/arcturis#comments

**Comment by Dootz** [comment]
Hi,

he's spawning like any other regular mob near place mentioned on wowhead ( by near I mean you should be able to see him when you stand in place mentioned in comments. He has should spawn every 11hours. From what I can see on Frosthold he was killed few hours ago, so it seems that it is working correctly.
