### ISSUE TITLE
Helm of the Grave

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#2803]
Decription: https://db.darkwizard.pl/?item=40344 has lower than 10% chance to drop.

How it works: 
Doesnt drop at all(I did Naxx 25 on every trinity core based server(DB Rising,Molten,Warmane,Sunwell Angrathar,Tauri)

How it should work: It should drop.

Source (you should point out proofs of your report, please give us some source): 
Can u confirm that the % is 10 ,or i just have reaaaaaaaally bad luck...

**Comment by Dootz** [comment]
Hi,
I can confirm that there is 10% chance to get it from 25-man four horsemen chest.
