### ISSUE TITLE
Pet priority

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#2805]
Decription: Hunter's Pet priority system doesnt work sometimes(if there is any)

How it works: Sometimes the pet ignores https://db.darkwizard.pl/?spell=55495 ,even when i have it first on my pet action bar.(like this - https://imgur.com/a/IJMUVOC ).My pet had over 20 focus during the test.

How it should work: 
My guess is that the pet should prioritize his abilities by their order in the action bar.

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
Hello.
I never heard about such system. Please post proofs.
