### ISSUE TITLE
Warlock desctruction talents bugged

### ISSUE THREAD

**Issue by BIaireau** [SunwellTracker/issues#2806]
Decription: the talents backdraft that reduce the next 3 destruction is bugged for rain fire. making his aoe less important, im in love with this spec since i dont love affliction. i dont want to stop playing just because my aoe is less better :(

How it works: its not reduce 30%  rain of fire casting speed

How it should work: suppose to be reduce rain of fire  30% casting speed 

![WoWScrnShot_011420_025632](https://user-images.githubusercontent.com/29809137/72324798-c27aec80-3679-11ea-9ca1-7ed16ba6b1da.jpg)

the base casting speed of rain of fire is 8 sec , on the screenshot we see its not affected by the backdraft
Source (you should point out proofs of your report, please give us some source):

**Comment by Rosenkrantz** [comment]
Rain of Fire has no **cast** time, only c**hanneling** time. Therefore Backdraft apparently never reduced **channeling** time of Rain of Fire (or for Hellfire if anyone wondered). First google result for "backdraft rain of fire", a thread from 2009, so WotLK time.
https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire

**Comment by BIaireau** [comment]
no its suppose to work on rain of fire https://wotlk.evowow.com/?spell=47820, its modify by backdraft. on any others server its work well
