### ISSUE TITLE
[Warlock]Succubus vs Seduction

### ISSUE THREAD

**Issue by cleanaccmmr** [SunwellTracker/issues#2807]
Decription: right now in sunwell frosthold the succubus dosent cast Seduction correctly and make the crowd control in some cases impossible

How it works: 
If the succubus is on /follow and you want to Seduce a target it dosent cast until it stops walking then it cast the Seduction spell 

How it should work: 
Whenever you want to cast seduction the pet automaticly stops walking and start casting which is not the case in sunwell at the moment.

Source (you should point out proofs of your report, please give us some source): this is basics and you cant test it anywhere you want its how it works

**Comment by wonszopaionk** [comment]
I can confirm, succubus is neither stopping walking to cast nor following the target if it's out of range or out of vision.

**Comment by Piootrek** [comment]
Did you check this today after update?

**Comment by cleanaccmmr** [comment]
its Fixed already working correctly
