### ISSUE TITLE
[Professions] Skinning with no loot

### ISSUE THREAD

**Issue by frizzon** [SunwellTracker/issues#281]
Description: Skinning a mob provides no loot.

How it works: In certain ocassions when skinning a mob you get no loot. It seems to be random as I can't reproduce it consistently, however in some mobs apparently happens more often than in others.

How it should work: Skinning should always reward at least some loot.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020618_134150](https://user-images.githubusercontent.com/630031/35871915-390f8c42-0b44-11e8-9426-3d3ceb691bf9.jpg)

As you can see I skinned a mob at 13:41:39, the loot window is open and with nothing in it and it wasn't  looted as my last item looted was 4 seconds before the skinning was performed.

**Comment by Riztazz** [comment]
Issue will be resolved with next update.
