### ISSUE TITLE
[MAGE][SPELL] Polymorph

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#2812]
Decription: There's a game-breaking visual bug that makes it hard for a mage to "re-poly" target (especially in PvP). Basically polymorphed target visually is in a different location than it really is.

How it works: Polymorphed target's visual location is broken. Doesn't happen every single time but pretty often.

How it should work: Polymorphed target's visual location should match its real one.

Source (you should point out proofs of your report, please give us some source): Don't have anything recorded.

**Comment by Aridam** [comment]
Related to/Same as https://github.com/SunwellTracker/issues/issues/2645.

Try to Poly something not moving and see what happens, then try to Poly something that's movement and compare.
