### ISSUE TITLE
Ghost Howl pet Talent tree

### ISSUE THREAD

**Issue by Arixiusanlo** [SunwellTracker/issues#2813]
Decription: Once ghost howl is tamed there is the option to check for talent tree however there's no talents to put the points into at all.

How it works: Talent tree option is there but there's no talents to put points into

How it should work: Talent tree should be visible so you can insert points.

Source (you should point out proofs of your report, please give us some source): 
https://cdn.discordapp.com/attachments/604393900454707200/667385052505571329/WoWScrnShot_011620_180933.jpg

**Comment by Piootrek** [comment]
Hello. 
Please delete your cache. It should help.
