### ISSUE TITLE
Problem with Everlasting Affliction Talent.

### ISSUE THREAD

**Issue by Eradicatepls** [SunwellTracker/issues#2816]
Decription: 
Ever Lasting Affliction is supposed to proc from casting Drain Life / Drain Soul, and at the moment on Frosthold, the Corruption is refreshed on 1st Tick on each of those channeled spells.

How it works: 
On a blizz like content, at the moment you press your drain soul, corruption's duration should be reactualised to it's full duration.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/MHYRjHUcGI8?t=276
Here is a drain soul moment on Retail 3.3.5, showing the way things should do.
It's actually the same for drain life.

**Comment by Aridam** [comment]
Seems your report is the same as https://github.com/SunwellTracker/issues/issues/1903.
