### ISSUE TITLE
Beacon of Light

### ISSUE THREAD

**Issue by Ananisikimoruspu** [SunwellTracker/issues#2818]
Decription: https://db.darkwizard.pl/?spell=53563

How it works: Sometimes when i use Flash of light/ Holy shock on my mate i don't get healing through my Beacon of Light. I take a step to the pillar and Beacon of Light don't work. Just look that video 
https://www.youtube.com/watch?v=qwxELi8X308&feature=youtu.be

How it should work: I should get healed 100% of the time.

Source (you should point out proofs of your report, please give us some source): You don't need proof here, just watch the video.

**Comment by Piootrek** [comment]
It's blizzlike. Your target must be in line of sight.
https://www.wowhead.com/forums&topic=145887

**Comment by Ananisikimoruspu** [comment]
I'm talking about beacon of light on the paladin, not a random target behind pillar. If you can heal your target, you should receive the heal, that's logical. This doesn't  work only on Sunwell...

**Comment by Piootrek** [comment]
Sorry, my bad. I will check this.
