### ISSUE TITLE
Website Talents Page Buggy for 2 Years(Fix please)

### ISSUE THREAD

**Issue by Warglaive** [SunwellTracker/issues#2819]
Decription: 
The problem is Not in-game, it is a problem with the website's talents showing section.
I am reporting it here because reporting on tickets does not work.
http://prntscr.com/qpridm

How it works: 
http://prntscr.com/qpridm

How it should work: 
It should show talents correctly.

Source (you should point out proofs of your report, please give us some source): 
http://prntscr.com/qpridm

**Comment by Raphtrack** [comment]
fixed
