### ISSUE TITLE
[Achievement] Hadronox: Denied

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#282]
Decription: 
There is a bug where it is possible to get a heroic achievement in a normal dungeon.

How it works: 
I don't exactly know the specifics of how to replicate it, but my entire group got the heroic achievement "Hadronox Denied" in Azjol-Nerub upon defeating Hadronox. Another bug here is that Hadronox doesn't move up the tunnel at all.

How it should work: 
Obviously, it should not be possible to get a heroic achievement in a normal dungeon.

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/G8t0jd8.jpg
You can see in the screenshot that i am level 72.

**Comment by Kokaina** [comment]
at the beginning he's just below players - just as he should be
![image](https://user-images.githubusercontent.com/22802214/35877736-7c985c1e-0b76-11e8-9bbd-f5329c276329.png)

when i killed first anub'ar crusher he walked 1/3 of his path correctly
![image](https://user-images.githubusercontent.com/22802214/35877786-a4a18d34-0b76-11e8-85ef-0f7e896d86f2.png)
![image](https://user-images.githubusercontent.com/22802214/35877802-af095eb4-0b76-11e8-9ef4-32a5692dc979.png)
and 2 more anub'ar crusher arrived:
![image](https://user-images.githubusercontent.com/22802214/35877884-e6f262c6-0b76-11e8-9de2-9b6365f8a3b9.png)

When i killed them both, hadronox reached top of tunnel, each kill anub'ar moves him 1/3 of his road giving total path walked by killing 3 crushers. Everything looks fine on normal.
Hadronox is scripted fine, exception is achi u mentioned - should be to recieve only on heroic.

**Comment by sonrakus** [comment]
We kept killing anub'ar crushers but hadronox was nowhere to be seen, we couldn't see him below us. After a few waves we decided to just move down the tunnel and there she was. Upon killing her, my entire group received the heroic achievement. So maybe it was a special condition someone triggers, i'm afraid i don't know what exactly happened, but that is how it happened.

**Comment by Riztazz** [comment]
Resolved issue of second part of the issue, as far as hadronox not moving goes, we need more data, i cannot reprocude it right now locally :/
