### ISSUE TITLE
[RAID EOE 10MAN]

### ISSUE THREAD

**Issue by tiaan925** [SunwellTracker/issues#2820]
Decription: 
today i was part of raid team I died on phase 3 bu the raid was succesfull i couldnt roll for items and i didnt get badges. Player [Podest] was raid leader and he has screen shot

How it works: when you die you fall down and you are instanty kicked from instance and when its still succesful its like you didnt took part in it

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Kwyzard** [comment]
don't press release next time

**Comment by tiaan925** [comment]
As i wrote before i didnt Press release

pon., 24 lut 2020, 02:06 użytkownik Kwyzard <notifications@github.com>
napisał:
