### ISSUE TITLE
Stabled pet disappearing (multiple times)

### ISSUE THREAD

**Issue by Chrixie** [SunwellTracker/issues#2823]
So this has happened a couple of times now. It seems to always be in the last slot it goes away. I've lost Ravager and Wolf, 3 wolves and 1 ravager so far. I've only noticed it when I have logged in from being logged out and the pet being gone. I have no idea that is causing it. It happened yesterday aswell (5th slot wolf) so I lvld up a new one, today I lost my PvP ravager in the 5th slot as I logged in and wanted to swap over.

All of my pets when they've gone into the "Call Stable Pet" has been on 125% happy. Never been dead, just they do disappear and I have no idea why...

**Comment by Aridam** [comment]
This has already been reported - - use the search engine here.

**Comment by AbraKabastard** [comment]
Do you have dual spec?

**Comment by Chrixie** [comment]
I do, yes. I've only had 4 pets for now and it hasn't happened yet. I think it's the last pet slot that gets bugged because of something, could be dual spec or something else.

**Comment by Wojtyas** [comment]
#2698
Will try to make increase prio of this.
