### ISSUE TITLE
Proper values for spell coefficients and formulas [question]

### ISSUE THREAD

**Issue by Dominiklas** [SunwellTracker/issues#2824]
Hey, i'd like to ask if there's existing database with info how spell power coefficients is calculated?

I am looking for info about items internal cooldowns, proc rate chance (ppm, %) etc as these are sometimes missing on https://db.darkwizard.pl/ and other wotlk based online databases.

thx for help

**Comment by Semper-Numquam** [comment]
https://wowwiki.fandom.com/wiki/Spell_power_coefficient
