### ISSUE TITLE
[Broke] All Hail Roanauk!

### ISSUE THREAD

**Issue by andersleet** [SunwellTracker/issues#2827]
Decription: After quest line should be able to talk to Roanauk Icemist in Agmar's Hammer to complete the objective.

How it works: Do quests in Dragonblight, get the quest in the town, talk to Roanauk to complete. Roanauk does not offer any additional dialogue as he should.

How it should work: Should be able to "initiate" this NPC then return to Agmar to complete quest.

Source (you should point out proofs of your report, please give us some source): Screenshots showing quest is in my log and not able to get extra dialogue from the NPC -- https://imgur.com/a/QzjBH4W

PS -- I did also try disabling all addons...same result.

**Comment by felmad** [comment]
I was able to do this quest by using quest item on Roanauk. I did that quest week or two weeks earlier.

**Comment by Dootz** [comment]
Hi,
when you accept this quest "Overlord Agmar" will walk with you to Roanauk, once he reaches him you should be able to speak with him and complete quest. We'll remove this limitation to allow completion of this quest at any time with next update
