### ISSUE TITLE
Grand theft Palmino Not working

### ISSUE THREAD

**Issue by Unsakred** [SunwellTracker/issues#283]
Decription: 
Grand theft palomino : steal a horse from the stable below and return it and the quest giver make it into a deathcharger instead he just keeps killing it and walking away

How it works: 
you steal a horse from a horse stable and return it to make it into a death charger instead he keeps killing my horse and walking away from me 

How it should work:

you steal a horse from a horse stable and return it to make it into a death charger 

Source (you should point out proofs of your report, please give us some source): In game

**Comment by Dootz** [comment]
Did you use horse's spell "Deliver Stolen Horse" near Salanar? I can confirm that he kills horse but only if you dismount. If you're mounted and use mentioned spell everything seems to work fine.

**Comment by Unsakred** [comment]
There was no spell showing up on my screen it took multiple tries at the following quest before the spell showed up on that one too the area seems a bit buggy I just had an elite death charger chase me down and kill me also when agroing a scarlet on a horse they won’t move
