### ISSUE TITLE
High priest Thekal zul gurub

### ISSUE THREAD

**Issue by Krishma2137** [SunwellTracker/issues#2831]
Decription: 
After killing High priest Thekal, i could not pick up loot from him. I could not even target his corpse. I saw that his corpse is shining like there is some loot in here, but couldn't do anything about it.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![Bez tytułu](https://user-images.githubusercontent.com/51697227/73138578-79a53980-4064-11ea-97ab-9d7db1767b95.png)

**Comment by Dootz** [comment]
23/11/2020 - tested multiple times, cannot reproduce. There were some changes released some time ago so it's possible this was fixed too.
