### ISSUE TITLE
roots

### ISSUE THREAD

**Issue by Naxtter** [SunwellTracker/issues#2846]
Decription: 
if somebody roots me i can see anything

How it works: 
roots take the whole screen, they are enormous

How it should work: 
should be smaller animation

Source (you should point out proofs of your report, please give us some source):

**Comment by AbraKabastard** [comment]
Wanna post a screen shot?

**Comment by Naxtter** [comment]
https://user-images.githubusercontent.com/60472699/73526974-8b932d80-4412-11ea-9ac8-054fa6e01d3d.png

**Comment by AbraKabastard** [comment]
Woah, those are huge. Could you please clear your cache and see if the
issue persists?

**Comment by Naxtter** [comment]
unfortunatelly it didnt work at all

**Comment by Dootz** [comment]
21/11/2020 - tested, cannot reproduce. Did you have any event-related auras on you?
