### ISSUE TITLE
Isle of Conquest is open!

### ISSUE THREAD

**Issue by lkrocek** [SunwellTracker/issues#2849]
Decription: 
Battleground called Isle of Conquest is open.

How it works: 
Start/join or Call to arms is working and be able to do.

How it should work: 
It was announced to be with ToC 

Source (you should point out proofs of your report, please give us some source): 
https://sunwell.pl/page/fresh-wotlk-frosthold

**Comment by Azathothh** [comment]
It's available since start, because there was really no point in blocking that on purpose. You don't get any items from future patch or any other kind of advantage because that bg is opened.
