### ISSUE TITLE
Intercept (stun) goes straight through Deterrence - this is a bug

### ISSUE THREAD

**Issue by dariuzsdk** [SunwellTracker/issues#2851]
Decription: 
Intercept (stun) goes straight through Deterrence - this is a bug

How it works: 
Intercept stun goes through hunter deterrence

How it should work: 
It shouldnt

Source (you should point out proofs of your report, please give us some source):

**Comment by Grozorez** [comment]
https://github.com/SunwellTracker/issues/issues/2701
