### ISSUE TITLE
[Icecrown mobs] Weird NPC's that should be objects

### ISSUE THREAD

**Issue by SpectraQWERTY** [SunwellTracker/issues#286]
Decription:  There exists a group of NPC in ICC that shouldnt exist. They are pretty tough and make solo questing inthat area incredibly hard, also their respawn time is short.

How it works:  The NPC "Scourge War Machine" is behaving like a regular NPC instead of as an object. They aggro the player and attack without animations,
http://prntscr.com/ib1hqj

How it should work: These Mobs should be objects and shouldnt act like regular NPC
http://prntscr.com/ib1lju

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Resolved
