### ISSUE TITLE
Death Coil movement Bug

### ISSUE THREAD

**Issue by IKamajk** [SunwellTracker/issues#2868]
Description: Death Coil spell sometimes get a bug

How it works: When I am running towards a target and i lunch the spell Death Coil sometimes, it will not be landed. You can see the lunch animation but you will not see any graphic effect, nor the damage on the target.

How it should work: When I lunch it a green-ish bolt should land from me and reach the target after a short lunch animation (instant spell, no casting time).

Source (you should point out proofs of your report, please give us some source):  I will try to prepare a video of the bug

**Comment by Wojtyas** [comment]
Duplicate
https://github.com/SunwellTracker/issues/issues/2451
