### ISSUE TITLE
[Hunter] Chimera Shot - Serpent

### ISSUE THREAD

**Issue by Elaatu** [SunwellTracker/issues#287]
**Opis:**
Crit z Chimera Shot - Serpent powinien posiadać większy przelicznik z critów
Hit = Thick Serpent Stinga * 7 ( 7 to jest liczba thicków serpenta ) *40% ( to działa poprawnie )
Crit = Hit  *  %  -> u nas prawdopodobnie jest coś w granicy 200%-206%, na globie było w granicy 230-236%. (te 6% wychodzi prawdopodobnie od meta gema)

**Jak działa na sunwellu:**
Chimera Shot - Serpent posiada za mały przelicznik dmg z crita

**Jak powinno działać:**
Chimera Shot - Serpent powinien posiadać większy przelicznik dmg z crita

**Dowód:**

**Logi sunwell:**
http://worldoflogs.com/reports/spat9scgd5v2kda9/log/?s=874&e=1042
[{"spellNames": ["Serpent Sting"], "sourceNames": ["Valcy"]}, {"spellNames": ["Chimera Shot - Serpent"], "sourceNames": ["Valcy"]}]

[20:55:54.958] Valcy Serpent Sting Lord Jaraxxus 1070
[20:55:57.957] Valcy Serpent Sting Lord Jaraxxus 1070
[20:56:00.943] Valcy Serpent Sting Lord Jaraxxus *2290* (R: 254)
[20:56:04.081] Valcy Serpent Sting Lord Jaraxxus *2290* (R: 254)
[20:56:06.112] Lord Jaraxxus's Serpent Sting is refreshed by Valcy
[20:56:06.758] Valcy Chimera Shot - Serpent Lord Jaraxxus *6169*

1070 * 7 * 40%= 2996
2996 * 206% = **6171** (Chimera Shot - Serpent Lord Jaraxxus **6169**)

**Logi Global:**
http://worldoflogs.com/reports/FilwHGRNhtZOqWuX/log/?s=2630&e=2901
[{"spellNames": ["Serpent Sting"], "sourceNames": ["Niksaktus"]}, {"spellNames": ["Chimera Shot - Serpent"], "sourceNames": ["Niksaktus"]}]

[19:42:25.398] Niksaktus Serpent Sting Ignis the Furnace Master 923
[19:42:25.535] Niksaktus Chimera Shot - Serpent Ignis the Furnace Master *6114*
[19:42:28.195] Niksaktus Serpent Sting Ignis the Furnace Master 923
[19:42:31.471] Niksaktus Serpent Sting Ignis the Furnace Master 923

923 * 7 * 40% = 2584,4
2584,4 * 236% = **6099,184** (Chimera Shot - Serpent Ignis the Furnace Master **6114**)

**Comment by CiriSunwell** [comment]
"923 * 7 * 40% = 2584,4
2584,4 * 236% = 6099,184 (Chimera Shot - Serpent Ignis the Furnace Master 6114)"

To nie jest prawidłowe obliczenie, powinno być:
923 * 7 * 40% = 2584,4
2584,4 * 230% * 103% = 6122 (Chimera Shot - Serpent Ignis the Furnace Master 6114)

W kwestii samego buga niewiele to zmienia.

**Comment by Riztazz** [comment]
Postaram sie naprawic, ale widze, ze duzo mylnych informacji jest na stronie jak i w grze (gadalem z kilkoma hunterami). Ten talent zwieksza bonus damage nie calego spella, a tylko czesci krytycznej

**Comment by Kokaina** [comment]
Will be fixed with next updated.
