### ISSUE TITLE
[Paladin] Broken: Glyph of Divinity

### ISSUE THREAD

**Issue by Kennyslaboratory** [SunwellTracker/issues#288]
**Description:** 
I'm using Glyph of Divintiy to grant me mana when I use Lay on Hands.  The Glyph does not work as intended.  When I was out of mana and used Lay on Hands in a critical moment, hoping to get 500 mana back, it did not grant the mana!

**How it works:** 
Should give both me and the tank (or person) I cast Lay on Hands to the mana in the tooltip x2 along with me. 500 mana should've been given to both of us.

I used it on a Druid in Bear Form when I noticed what happened.

**Comment by Kokaina** [comment]
Mana regen doesn't work on player if player has glyph. On target works properly.

**Comment by Kokaina** [comment]
Fixed.
