### ISSUE TITLE
[Shaman class mechanics] Fire / Earth Elementals and Feral Spirits not benefitting from Bloodlust/Heroism

### ISSUE THREAD

**Issue by DollpartsFTP** [SunwellTracker/issues#2887]
Decription: 
Shaman summon pets (Fire Elemental, Earth Elemental, Feral Spirits), are not gaining Bloodlust effects.

How it works: 
They continue to hit at the same speed. The visual of receiving Bloodlust isn't even active for Elementals.
Feral Spirits receive the animation, but continue to hit at the same speed.

How it should work: 
They should benefit from Bloodlust at the standard attack speed increase.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/yJfPs5K - How it currently is

https://youtu.be/RAt3mNa-N7U?t=22 
Shows Fire Ele and Feral Spirits gain both effect and visually faster attacks (Left side of boss)

https://www.youtube.com/watch?v=C-yM2BvdP3U&feature=youtu.be&t=116
Another video showing Fire Eles gaining bloodlust.

**Comment by Nikrotip** [comment]
1) Bloodlust affects neither Fire Elemental nor the Earth one and that's how it should be. 
2) Bloodlust affects Feral Spirits and it does work currently on Sunwell.
