### ISSUE TITLE
An Unusual Patron

### ISSUE THREAD

**Issue by Avarishd** [SunwellTracker/issues#289]
Decription: The NPC does not spawn after completion of the cast.

How it works:  After you finish the cast nothing happens.

How it should work: After the cast the NPC - "Naias" should spawn and then you proceed to kill it.

Source (you should point out proofs of your report, please give us some source): 
I attempted to spawn the NPC 3 times (5-8min interval) and it never worked it.

**Comment by Kokaina** [comment]
Done.
