### ISSUE TITLE
Cloak of shadows doesn't disjoint spells

### ISSUE THREAD

**Issue by suhnu** [SunwellTracker/issues#2891]
Decription: CoS is not not working on spells that have finished casting.

How it works: if spells has finished casting, it always goes through cloak.

How it should work: Cos should make you 90% resist on spells, finished casting or not.

Source (you should point out proofs of your report, please give us some source):  tested with frostbolt, chaos bolt, death coil

**Comment by Rosenkrantz** [comment]
Is this live now? Suddenly Cloak of Shadows resists physical stuns (in particular Cheap Shot and Kidney Shot, just found out in Arena)

**Comment by Azathothh** [comment]
@Rosenkrantz yep, change related to this report caused this issue. Fix was applied after your comment - does it work properly now or there's still something not right?

**Comment by Rosenkrantz** [comment]
"Resist"-ed a charge stun right now. It doesn't even register in rogue's combat log, only in floating combat text.
