### ISSUE TITLE
Presence of Mind combined with Invisibility (Mage spell)

### ISSUE THREAD

**Issue by Bananwszyscy** [SunwellTracker/issues#2892]
Decription: It did worked on previous Sunwell sezons and it works also on different servers, but not here anymore so im reporting the issue.

How it works: 
Presence of Mind suppose to give an instant mage spell if its cast time is less than 10 secounds and it does not work combined with invisibility to have an instant invisibility state. 

How it should work: 
It should give every spell instant if its cast time is less then 10 secs so in this case I should go into invisibility state straight after using Presence of Mind but the timer for invisibility is still 3 secs before you go into invisibility state.

Source (you should point out proofs of your report, please give us some source):

**Comment by Vaxsysl** [comment]
Presence of Mind tooltip:
Instant cast, 1.4 min cooldown
"When activated, your next Mage spell with a casting time less than 10 sec becomes an instant cast spell."

Invisibility tooltip:
491 Mana
Instant cast, 2.1min cooldown
"Fades the caster to invisibility over 3 sec, reducing threat each second. The effect is cancelled if you perform any actions. While invisible, you can only see other invisible targets and those who can see invisible. Lasts 20 sec."


Presence of Mind affects casting spells. It can't affect channeling and has no effect on instant spells. Invisibility is an instant spell. When you use it, you fade away each second until you're completely invisible.


Nothing wrong there @Bananwszyscy . Works as intended.
...unless you find legit proof other wise.


Prismatic Cloak 3/3
"Reduces all damage taken by 6% and reduces the fade time of your Invisibility spell by 1 sec."
_^ That talent makes your Invisibility be instant._

**Comment by Bananwszyscy** [comment]
So why is it working differently on other wotlk servers? And even on sunwell previous sezons it was working as I described? You pressed presence of mind that was giving an instant invisibility, I know tho there is a talent to get that but thats not how it was before, I can send some material with proof that on previous sunwell sezon it was different. 
Ps; and also what about the other issue with the presence of mind bug? Theres also a topic open by me here on that forum.

**Comment by Vaxsysl** [comment]
> So why is it working differently on other wotlk servers? And even on sunwell previous sezons it was working as I described?

Because of bad scripting? Invisibility is an **instant spell**. It has **no** casting time. Nothing. _Using_ the spell **gives you a buff** which ticks off and then makes you invisible when the counter reaches 0. 

**Presence of Mind reduces casting time to zero.** Invisibility is an **instant** cast. Presence of Mind has nothing to affect here because there's no casting time to reduce.

**Comment by Bananwszyscy** [comment]
Oh okay then maybe I was just living on a bad scripted world at that time, because it was like that since I remember - well no worries than cheers for help alot. Just double check the other issue with that spell aswell in my topics.
