### ISSUE TITLE
Another Presence of Mind bug (Mage spell)

### ISSUE THREAD

**Issue by Bananwszyscy** [SunwellTracker/issues#2893]
Decription: 

How it works: 
After using Presence of Mind sometimes it shows the cooldown on the bars but sometimes it doesn't. It is very confusing especially during pvp.

How it should work: 
You should be able to see that after using it theres an cooldown on it for 59sec and onwords...

Source (you should point out proofs of your report, please give us some source):

**Comment by Bananwszyscy** [comment]
Ps: and its nothing to do with addons because I can see the cooldown timers on other spells :)

**Comment by Chumanoyasha** [comment]
Same as here https://github.com/SunwellTracker/issues/issues/2810
It's so easy to reproduce, and you can use it to double sheep twice in a duel / arena,
just read in thread that i linked.
