### ISSUE TITLE
Omen of clarity/leader of the pack heal bug. 

### ISSUE THREAD

**Issue by styxel** [SunwellTracker/issues#2897]
Decription: 

How it works: 
Omen of clarity has chance to proc from each invidual heal of leader of the pack(improved leader of the pack) , making it somewhat strong In 25mans with +10 melees, pets etc. Almost doubles ooc procs. This is something i have missed because ive ran raids mostly with feral tanks and i was specd 1/2 into the Talent so the game would only use our tanks aura. 

Gift of the wild too low proc chance in raids 

How it should work: 
_**_Improved leader of the pack_**_ Shouldnt proc from every lotp heal, should only proc from **selfheals** of it. Currently In a 3min fight u can get 35+ procs because of it should only be close to 20ish. Also makes running 2 ferals wierd, since the heals dont share this would make the other feral Who has lotp Active in the grp stronger. 

**_Gift of the wild_** when buffing it should have increased chance to proc ooc when buffed for example In 25mans (when it buffs 25people it should roll the 6% chance 25times making it close to 100% proc chance this is how it was In retail people would start fights with gotw before pulls for ooc doesnt sound a big deal but it actually makes the feral opener work better. 

Source (you should point out proofs of your report, please give us some source):
No proofs atm but obviously shouldnt proc like this. I can dig up some retail logs If u want but this is not how it should work. And gotw part never got fixed guess it was too complicated or u just forgot i had proof about it on my initial report think it was #2500

**Comment by styxel** [comment]
@Riztazz are u still here

**Comment by Piootrek** [comment]
Please post proofs

**Comment by styxel** [comment]
i think i know why its behaving like this may i sent u some logs in private on discord?

**Comment by styxel** [comment]
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/sum/healingDone/?s=510&e=627

http://www.worldoflogs.com/reports/wrwrj4rxi7mbotzl/sum/healingDone/

check the healings on those. On retail the druid would only heal himself not other players u can see that all the other melees have healing done with lotp but on sunwell the healing is only done by the druid

**Comment by Piootrek** [comment]
Please retest leader of the pack after update

**Comment by styxel** [comment]
Okey thanks, were u able to Do anything about gotw?

**Comment by Piootrek** [comment]
I don't exactly understand where is the issue with gotw. If you cast it on 25ppl, it doesn't mean you have 25 * 6% = 150% proc chance. It's still separate 25 chances with 6% success chance.

**Comment by styxel** [comment]
Ye thats what ive thoght because sometimes rarely it didnt proc ooc so its not 100% but instead it should be like u said but its not working In Frosthold atm.

**Comment by Piootrek** [comment]
Gift of the Wild will be fixed after next update.
