### ISSUE TITLE
Visual bug with Defias Trapper/Smuggler attack

### ISSUE THREAD

**Issue by Talimar** [SunwellTracker/issues#29]
Decription: 
When they throw knives at you, you get a blue and white square on your chest.
I'm not 100% sure if it is Smuggler or Trapper that does it, or even both as I was rarely attacked myself being in a group.

I use regular wotlk client from sunwell.pl

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://is03.ezphotoshare.com/2018/01/28/0oDc4s.jpg

**Comment by Riztazz** [comment]
Resolved already
