### ISSUE TITLE
Siltslither Eel duplicate [Critical]!

### ISSUE THREAD

**Issue by jstdm** [SunwellTracker/issues#290]
Decription: 
I belive mud pods are supposed to disappear for short duration after looted? 

How it works: 
You can open mud pod about every 3-5 seconds again and there will always spawn another Siltslither Eel withou pod disappearing.

How it should work: 
Pod should disappear for short duration (99% sure based on ban :D)

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
gob entry 190779 respawn time need to be increased
