### ISSUE TITLE
Immolate+Conflagrate combo = not immediately castable (global cooldown issue )

### ISSUE THREAD

**Issue by grokker1** [SunwellTracker/issues#2901]
Decription: 
Immolate+Conflagrate combo = not immediately castable (global cooldown issue )

How it works: 
After you cast an Immolate spell, you can't cast Conflagrate immediately (takes approximately global cooldown length to "register" immolate on the target, after which you can cast Conflagrate).

How it should work: 
After you cast an Immolate spell, you can cast Conflagrate immediately.

Source (you should point out proofs of your report, please give us some source): 
I don't have any as it can only be shown in a video.
On the other hand I have several confirmations from other fellow warlocks who confirmed mentioned issue above.

**Comment by Warglaive** [comment]
I can confirm it.

**Comment by Rosenkrantz** [comment]
Working as intended.

https://github.com/SunwellTracker/issues/issues/1877

**Comment by Riztazz** [comment]
What @Rosenkrantz said, this is by design and we won't be changing it
