### ISSUE TITLE
Heirlooms problem

### ISSUE THREAD

**Issue by ibqpdl** [SunwellTracker/issues#2903]
**Description:** Does not apply [Minor Wizard Oil] to Heirloom staf [Grand Staff of Jordan]
**How it works:** When you apply [Minor Wizard Oil] to [Grand Staff of Jordan], it displays the message: Target is too low level
**How it should work:** Item should be applied as usual and add 8 spellpower.
**Source (you should point out the evidence of your report, mention some source):** All the servers I have played so far, if I am not afraid it should work.

https://imgur.com/a/9KZxWL5

**Comment by Wojtyas** [comment]
Please provide retail proof it works like you suggest.

**Comment by ibqpdl** [comment]
left up on buffs

https://www.youtube.com/watch?v=EVYaaMJWdJM&t=9s

**Comment by ibqpdl** [comment]
this server is not oficial but privat ....
