### ISSUE TITLE
Immortal Guardians on Yog (Important)

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#2916]
**Decription:** Immortal Guardians on Yog 

**How it works:** Immortal Guardians during Yog p3 literally ignores any threat when they spawn. They seem to not have a threat-table first seconds. They pick a target and don't change until certain time. They also seem to change target randomly but hard to tell from our VOD. You should prob go and take a closer look what's happening with them. 

**How it should work:** Immortal Guardians should not ignore any threat first seconds. 

Source (you should point out proofs of your report, please give us some source): 
https://clips.twitch.tv/AgitatedAggressiveOrcaJKanStyle - You can see on new Guardian that it's taunted but still goes for a healer. You can see threat down right where tank is 9k above second player on threat. 

https://clips.twitch.tv/HomelyGoldenEggSeemsGood - random clip where a Guardian goes on a frost dk from doing nothing on the target

**Comment by Riztazz** [comment]
Immortal guardians have a 3s period where they do not do anything after spawn and this is by design, but they still should follow threat tables, i'll fix that
