### ISSUE TITLE
Xp bug when killing high lvl mobs

### ISSUE THREAD

**Issue by Altarincze** [SunwellTracker/issues#2923]
Decription: 
When you kill any mob with "skull" as its lvl, that means 10+lvl from yourself, it wil l not give any XP.

How it works: 
When you kill any mob with "skull" as its lvl, that means 10+lvl from yourself, it wil l not give any XP.

How it should work: 
it should give xp

Source (you should point out proofs of your report, please give us some source): 
i have no idea why high lvl mobs shouldnt give xp, i never even heard about that and have no idea where to even find that.

**Comment by Azathothh** [comment]
It's disabled to avoid mob tagging by low level characters and killing them with 80lvls. No, lvling up since lvl 1 in borean tundra isn't normal.
