### ISSUE TITLE
Arena Points Missing

### ISSUE THREAD

**Issue by moreabout** [SunwellTracker/issues#2927]
Decription: 
I didnt get the arena points from last sunday beside having 100% games played in my team and like 40 games played. I have currently 200 AP while playing almost every random bg every day which gives 50 AP
![WoWScrnShot_030720_100013](https://user-images.githubusercontent.com/61902454/76140410-7c7b4d00-605a-11ea-9910-6d75782a33c8.jpg)
![WoWScrnShot_030720_100013](https://user-images.githubusercontent.com/61902454/76140416-8b61ff80-605a-11ea-859a-2f888e584a5c.jpg)

How it works: 
I didnt get AP

How it should work: 
I was supposed to get like 280 AP

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
you wrote this report on saturday, while arena flush is on sunday 23:00 realm time...

**Comment by moreabout** [comment]
yes, because i just noticed that Im missing the points from previous flush.

pon., 9 mar 2020 o 21:09 Azathothh <notifications@github.com> napisał(a):

**Comment by Azathothh** [comment]
For previous flush you had to play between 18:00 29.02 and 23:00 01.03.  If you didn't receive your AP then either you haven't played at that time or one of the requirements to receive AP wasn't met, which are:
1. your **TEAM** played at least 10 battles 
2. **YOU** participated in at least 30% of all battles of your team between 18:00 29.02 and 23:00 01.03
