### ISSUE TITLE
Missing Skinning Skill

### ISSUE THREAD

**Issue by Mrlutek** [SunwellTracker/issues#2928]
Decription: I log in today and want to feed my skin and it turns out that my skinning 450/450 has been reset to 1/75 where yesterday it was at maximum
![Screenshot_1](https://user-images.githubusercontent.com/61904463/76141574-07157980-6066-11ea-9288-8a3ab8ff5263.png)

How it works: I didnt get my skinning 450/450

How it should work: 
I was supposed to get like 450/450

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It's not a bug. Either you or someone else who logged on your account unlearned it and learned again.
