### ISSUE TITLE
[Ulduar] Divine Plea shouldn't work on General Vezax

### ISSUE THREAD

**Issue by GhostFinn** [SunwellTracker/issues#2932]
Decription: 
A lot of people will hate me for this but Divine Plea shouldn't regenerate any mana during General Vezax's fight

How it works: 
Divine Plea regenerates as normal.

How it should work: 
Aura of Dispair should block any source of mana recovery (except for the normal Spirit). The description of the aura clearly says:

"Prevents mana regeneration from nearly all natural sources.  Aspect of the Viper, Judgements of the Wise, Shamanistic Rage, and Spiritual Attunement remain at least partially effective."

Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/spell=64848/aura-of-despair
https://www.mmo-champion.com/threads/649075-General-Vezax

**Comment by Piootrek** [comment]
Hello.
Divine Plea works only with protection talent Guarded by the Light.
According to Wowwiki description it's blizzlike.
https://wowwiki.fandom.com/wiki/General_Vezax
[Aura of Despair] - Prevents mana regeneration from nearly all natural sources. Aspect of the Viper, Judgements of the Wise, Shamanistic Rage, and Spiritual Attunement remain at least partially effective. **Divine Plea for protection paladins also apears to work too**. Also reduces melee attack speed by 20%.

**Comment by Azathothh** [comment]
adding source: 
26/07/2009 : http://www.worldoflogs.com/reports/5qrlX3uOL4eIaaxN/details/69/?s=11362&e=11921#tab-auras
