### ISSUE TITLE
[Shaman] [Spell] Wind Shear resist mechanics

### ISSUE THREAD

**Issue by Selot1234** [SunwellTracker/issues#2936]
Decription: 
Wind Shear interrupts casting.

How it works: 
Current implementation of wind shear allows trash + bosses in Ulduar (10 and 25 man) to fully resist [Wind Shear](https://db.darkwizard.pl/?spell=57994)

How it should work: 
Bosses and trash in ulduar can't resist Wind Shear

Source (you should point out proofs of your report, please give us some source): 
As Shamans from retail on Uldu seemed to not use Shears i am providing logs from ICC
[link](http://www.worldoflogs.com/reports/vweyx535vlctx49l/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/r990jgnfr802ixrw/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/tdfrimj45tnt0vjn/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/a28vcl4cx8qhioxm/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
amount of ~40 wind shears which none got resisted

Current state from Frosthold:
[link](http://www.worldoflogs.com/reports/rt-jvpeirc7vu5xh1cw/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22General+Vezax%22)
~80 wind shears which 6 got resisted

**Comment by Platinumcoated** [comment]
Enemies of higher level have innate resistances towards the player
https://wowwiki.fandom.com/wiki/Resistance

And this report seems to have come to the conclusion that Wind Shear should be resistable
https://github.com/SunwellTracker/issues/issues/1675

**Comment by Selot1234** [comment]
@Platinumcoated 
to be clear:
[link](http://www.worldoflogs.com/reports/vweyx535vlctx49l/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/r990jgnfr802ixrw/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/a28vcl4cx8qhioxm/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/c6ql9qrug06m8yy7/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/tdfrimj45tnt0vjn/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/eye60iq5l6c9zxih/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/pt6hgjymsmjqt24s/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/l2wwq65toclxdpja/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/48fjqhj76x23fpbp/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)
[link](http://www.worldoflogs.com/reports/b2k9jsgjwxc5urmd/xe/?x=spell+%3D+%22Wind+Shear%22+and+targetName+%3D+%22Lady+Deathwhisper%22)

these are 2 and a half months raiding on retail, with total of 162 wind shear interrupts on ICC boss.
And 0 resists.
