### ISSUE TITLE
The Fate of Bloodbane (quest)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#294]
Decription: 
Tried to do this quest in Icecrown but I'm phased and can't reach Orbaz, relog/retaking quest didnt help I had to make ticket and GM managed to get me in same phase with Orbaz. Some chain quest most likely changes your phase but I have no idea which one for sure since I almost finished all the quests in Icecrown.
Quest giver name: Vereth the Cunning

How it works: 

How it should work:
Once you take the quest from the quest giver and you go to the location Orbaz is you should be able to see and fight him.
http://www.wowhead.com/quest=13164/the-fate-of-bloodbane
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, here's list of quests that can affect phasing of Orbaz. Could you check if you're not currently on one of them? If you find quest from this list in your questlog (not completed or completed), please complete it and let me now which one was it - that should fix it for now. I'll investigate further to find out if he should be visible while on those quests.

www.wowhead.com/quest=13864
www.wowhead.com/quest=13863
www.wowhead.com/quest=13862
www.wowhead.com/quest=13861
www.wowhead.com/quest=13860
www.wowhead.com/quest=13859
www.wowhead.com/quest=13858
www.wowhead.com/quest=13857
www.wowhead.com/quest=13856
www.wowhead.com/quest=13855
www.wowhead.com/quest=13854
www.wowhead.com/quest=13852
www.wowhead.com/quest=13851
www.wowhead.com/quest=13847
www.wowhead.com/quest=13258

**Comment by RandomXD** [comment]
I've done all the quests in icecrown and left orbaz one at the end since i couldn't complete it, i managed to complete it when gm tide somehow fixed my phasing issue and i could group with other ppl to kill it, i didn't had any quest in questlog when i tried to do it but im sure some ebon blade chain caused the phasing issue.

**Comment by Dootz** [comment]
that's probably fixed now. I just forgot to close it.
