### ISSUE TITLE
death knight pet not returning when passive is hit

### ISSUE THREAD

**Issue by rtsands45** [SunwellTracker/issues#2943]
Decription: you can send your pet to attack something but if u passive it the pet does not return it continues to attack.

How it works: hit passive button after you send pet to attack it doesnt return to master

How it should work: hit passive button and it returns and stops attacking

Source (you should point out proofs of your report, please give us some source):  every wow server.  This is a major bug

**Comment by Piootrek** [comment]
Hello.
Please provide more information, it works correctly for me.
https://streamable.com/l98xl
