### ISSUE TITLE
strand of the ancients teleporters working incorrectly

### ISSUE THREAD

**Issue by rtsands45** [SunwellTracker/issues#2945]
Decription: teleporters in sota are working incorrectly by not teleporting players to the correct location

How it works: click the teleporter get tp'd behind current gate no matter the status of the gate/gates

How it should work: you should get teleported back from green to purple or blue to red if green or blue is down. Or if the front green/blue and red/purple are down then you should be teleported to yellow

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=xA7D6ICkPDU      time stamp : 6:55

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/1674
