### ISSUE TITLE
Death Knight Adept (npc)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#295]
Decription: 
Currently these npcs are stacked on top of each other like 3-4 and also once you kill them they respawn in around 10-20 secs back.
http://prntscr.com/ib55z0
How it works: 

How it should work: 
They shouldn't be spawned on top of each other and their respawn time should be slower.
http://www.wowhead.com/npc=31325/death-knight-adept#comments
Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Done.
