### ISSUE TITLE
Mob aggro issues

### ISSUE THREAD

**Issue by Whoopsiexd** [SunwellTracker/issues#2951]
Decription: 
Mobs don't aggro when they should, aggro range is very low, sometimes you can even stand on them and they don't attack you until a few seconds have passed.
Also, I feel like the range when you run away from the mob and lose aggro is very low as well and should be a bit higher than it is now.

How it works: 
![WoWScrnShot_031620_131653](https://user-images.githubusercontent.com/62246048/76759763-a2a49980-678c-11ea-91fa-2a71c1321b78.jpg)

How it should work:

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,
you're higher level than mob from screenshot, once you have higher level mobs shouldn't aggro that easily. In fact there were many complaints in the past that aggro range should be shortened, so I think it would be the best to not increase it :)

https://github.com/SunwellTracker/issues/issues/336
https://github.com/SunwellTracker/issues/issues/1379
https://github.com/SunwellTracker/issues/issues/2002
