### ISSUE TITLE
[Hunter] [Pet] /petfollow command no longer recalls an attacking pet

### ISSUE THREAD

**Issue by DonJuangler** [SunwellTracker/issues#2952]
Decription:  If a pet is attacking or commanded to attack an enemy using the /petfollow command no longer recalls the pet to the owner.

How it works:  When the pet is in the stay stance /petfollow and clicking follow recall the pet to follow the owner, however in combat and after using /petattack /petfollow no longer seems to stop the pet from attacking and recall it to the owner.

How it should work:  When a pet is in combat or charging/moving towards a target /petfollow should recall the pet back to the owner and stop it's attack until a new attack command is issued or until the pet reacts to a new defensive stance call to action.

Source (you should point out proofs of your report, please give us some source): Every hunter I've spoken to who uses petfollow macro seems to have the same experience since about a day or two.

**Comment by Restoxd** [comment]
I have exactly the same problem + Devour Magic macros wont work aswell, spell lock does work tho

**Comment by rtsands45** [comment]
Same goes for dk pet.  it wont passive back to owner
