### ISSUE TITLE
Tree of life talent

### ISSUE THREAD

**Issue by Naturligt** [SunwellTracker/issues#2958]
Decription: 
Tree of Life, Mana reduction on Healing over time spells

How it works: 
It doesn't reduce the mana cost on my healing over time spell in tree of life form. My spells cost the same with and without tree of life form. 
![Lifebloom with Tree of Life form](https://user-images.githubusercontent.com/62388853/77077663-d20a0f00-69f5-11ea-8576-e757f968fd69.jpg)
![Lifebloom without Tree of life form](https://user-images.githubusercontent.com/62388853/77077941-3927c380-69f6-11ea-8f91-203b08277df4.jpg)

How it should work: 
It should reduce the mana cost of your healing over time spells by 20% in tree of life form

Source (you should point out proofs of your report, please give us some source):

**Comment by Shragenator** [comment]
Have you confirmed this isn't just a tooltip bug?  (Actually watched mana pool)

**Comment by Naturligt** [comment]
I just checked it and i lose the same amount of mana with tree of life form as I do without it.

**Comment by styxel** [comment]
Theres nothing that says that tree of life should reduce mana cost by 20% its just a talent that reduces mana cost of hots by 20% by default.
