### ISSUE TITLE
Dungeon Finder Glitch

### ISSUE THREAD

**Issue by FreshGarlic** [SunwellTracker/issues#2959]
Description: When I'm in a dungeon group made by the finder, twice now after 2 or more people have left, the icon seems to have disappeared in the top right + the game no longer considers us a dungeon. The ramifications being that we no longer hypothetically receive our daily RDF reward, and that we can't queue back in the dungeon finder to find more players to help us complete the dungeon (annoying if we've almost finished the dungeon). Because it has only happened twice, I'm not sure of the exact triggers, but I do know the second one occurred because of inviting a non RDF member to the group to try help us replace a member who left. I believe it should have either denied player entry, or given the player RDF status too. The first time it occurred, I don't believe this happened, so I currently don't believe it's the only cause (an avoidable cause if it were to be the only one). The first time seemed to happen when our party dropped to 3 players

How it works: After an arbitrary event described above happens, RDF group no longer consider an RDF group despite role tags, RDF buff, etc. remaining. Can't re-enter instance upon death, queue for more players, receive RDF completion reward, etc.

How it should work: Should be able to queue for more players, add more people to the group, re enter dungeon, tele in and out of dungeon, and be considered an RDF group still/recieve completion reward

Source (you should point out proofs of your report, please give us some source): Didn't think to take screenshots, but hopefully based on the description it's pretty self explanatory

**Comment by Rosenkrantz** [comment]
I just lost my Dungeon Finder "status":
- healer left group
- queued as 4 with tank + 3 dps
- I wanted to requeue as heal/dps so I left queue
- couldn't requeue and DF broke (no icon, spawn points lost - upon leaving pt we were still in instance)
