### ISSUE TITLE
Venture Co. Ruffian (npc)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#296]
Decription: 
Currently these npcs are using the ability Backhand to stun themself instead of using it on enemies.
http://prntscr.com/ib56ee
How it works: 

How it should work: 
They should use the ability Backhand on enemies not on himself.
http://www.wowhead.com/npc=28124/venture-co-ruffian#drops
Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Done.
