### ISSUE TITLE
"Dragonmaw Race: The Ballad of Oldie McOld" Bugged Quest

### ISSUE THREAD

**Issue by badtiming220** [SunwellTracker/issues#2964]
**Description:** 
Quest fails when it should've progressed to a challenge. Please confirm if bug or I'm just doing it wrong.

**How it works:** 
1.) Follow flying orc around.
2.) Don't get dismounted.
3.) **Quest fails.**
4.) Hear the orc say "Well, you won...I guess"
![WoWScrnShot_032120_212144](https://user-images.githubusercontent.com/62471161/77227521-dda73280-6bbb-11ea-8c4f-b322d3da85aa.jpg)

**How it should work:** 
1.) Follow flying orc around.
2.) Don't get dismounted.
3.) Quest success!
4.) Hear the orc say "Well, you won...I guess"

**Source (you should point out proofs of your report, please give us some source):** 
Wowhead [https://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold#comments](url)
Youtube video of a guy completing the quest [https://www.youtube.com/watch?v=pqT9ulCIHr8](url)

**Comment by Dootz** [comment]
Hi,
I was able to complete it fairly easily. You need to stay close to him and it should be fine. Anyone else having this issue? Please up vote/ open new tickets. Thanks
