### ISSUE TITLE
Level requirement for joining Wintergrasp

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#297]
Decription: 
Currently you need to be lvl 77 to join Wintergrasp but it should be 75.

How it works: 

How it should work: 
In order to join Wintergrasp you must be at least level 75.
http://wowwiki.wikia.com/wiki/Wintergrasp
Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed.
