### ISSUE TITLE
Triage quest

### ISSUE THREAD

**Issue by koobis** [SunwellTracker/issues#2972]
Decription: 
I did the quest  Triage for Doctor GustafVanHowzen - i needed to heal 15 patients , to and the quest but Doctor Gustaf dont aknowledge the end of the quest

How it works: 
 i needed to heal 15 patients  to end the quest but Doctor Gustaf dont aknowledge the  (the question mark is still greyed out )

How it should work: 
DOctor gustaf should take the quest and give the reward

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/62515159/77255615-089b9000-6c69-11ea-9543-407208ce9efc.png)

**Comment by Dootz** [comment]
Hi,

are you sure you healed 15 and none of them died? I just tested it and it seems to be working without issue. When you let to many of them die, the quest should fail.

**Comment by koobis** [comment]
Yea i cured all of them. Well i did abandon q and restared it recently and
it worked. It seemed to be one time thing.
Sorry for the time and thanks for respond.


śr., 25 mar 2020, 22:31 użytkownik Chris <notifications@github.com> napisał:
