### ISSUE TITLE
mob kiting

### ISSUE THREAD

**Issue by bojidaryovchev** [SunwellTracker/issues#2974]
when I fight with a mele mob I can literally run around it without doing anything else and it wont hit me - it cant reach me - it should always hit me, I shouldnt be able to kite it like that

**Comment by SunwellTracker** [comment]
Could you provide as more details e.g which creatures behave like this? Maybe a short video

**Comment by bojidaryovchev** [comment]
I can do that tonite as I am working atm, but the example I saw was Hogger, Ill try tonite tho

**Comment by Nitroidt** [comment]
This issue of mobs not having proper pathing was the first thing that got my attention on this server.

I made a small vid of it.
Link: https://youtu.be/9lOMVWPNm5k

**Comment by Nitroidt** [comment]
I went ahead a made a video of the issue the OP encountered.
https://www.youtube.com/watch?v=A7r4ZfQbgio
