### ISSUE TITLE
(Druid) Tree of Life dont reduce manacost of heal over time spells.

### ISSUE THREAD

**Issue by suhnu** [SunwellTracker/issues#2981]
Decription: Tree of Life should reduce mana cost of heal over time spells by 20%. Doesnt work.

How it works: Same mana cost on all hots in tree form or normal. Not just a tooltip bug, tested watching actual mana bar.

How it should work: Should give 20% off mana cost of heal over time spells.

Source (you should point out proofs of your report, please give us some source):

**Comment by styxel** [comment]
https://github.com/SunwellTracker/issues/issues/2958

**Comment by Rosenkrantz** [comment]
Read the whole talent, Tree of Life reduces HoT cost passively even outside of Tree form. Reset your talents and check costs again.

**Comment by Afgann** [comment]
Works correctly, talent applies -20%, not tree of life form.
