### ISSUE TITLE
Death Gate not available to me

### ISSUE THREAD

**Issue by Tarouck** [SunwellTracker/issues#2985]
Decription: After I cast Death Gate and then try to click on it gives me an error "The spell is not available to me". I have been able to go to Ebon Hold in the past as this is a recent occurrence. Last time I was able to use it was level 68. 

How it works: Nothing happens, just an error message. Not even any error speech.
![DeathGateUnavailable](https://user-images.githubusercontent.com/50720560/77384369-da8e7c80-6d4a-11ea-9e33-2e8749d491cf.png)

How it should work: I should be instantly ported to Ebon Hold after clicking on the Death Gate doodad. 

Something of note: I was not able to accept the quest Taking Back Acherus as Highlord Darion Mograine despawned a short time after the siege event ended.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, please write an in-game ticket and we will get that fixed for you.
