### ISSUE TITLE
Hand of freedom

### ISSUE THREAD

**Issue by dinovs** [SunwellTracker/issues#2986]
Decription: 
While hand of freedom is active you can still get dazed.

How it works: 
While hand of freedom is active you can still get dazed.

How it should work: 
immunity to all moving impairments 

Source (you should point out proofs of your report, please give us some source):

**Comment by Rosenkrantz** [comment]
If you're talking about creature-applied daze when a mob hits you from behind and dismounts you, then it's working as intended. It doesn't count as a movement-impairing effect, but as a physical debuff, so Hand of Protection or Divine Shield can remove it (IIRC the same goes for Daze from Aspect of the Cheetah/Pack, but here I'm not certain).

If you're talking about player-applied Daze like from Concussive Shot, then it's a bug, so please clarify.
