### ISSUE TITLE
Graveyards in isle of conquest

### ISSUE THREAD

**Issue by rtsands45** [SunwellTracker/issues#2998]
Decription: porting to nearest graveyard is wrong for isle of conquest.  I die right outsde of ally base as an ally then get ported to the hangar.  Die at docks when we control hangar and our base and ressurect in the grave where you should res if ally control no bases.

How it works: die in isle of conquest and you are most likely ported to the wrong grave.

How it should work: each zone has certain limits to where you should get ported to in case of death.  If you are trying to defend your base and you die you shouldnt get ported to an outside gy of hangar, docks or workshop.  

Source (you should point out proofs of your report, please give us some source): Any properly working pvp classed server.  I was told by GMs that this is a pvp server and these simple things are not working. https://wow.gamepedia.com/Isle_of_Conquest.  says in the graveyards section

**Comment by rtsands45** [comment]
can confirm horde as well doing the same thing

**Comment by felmad** [comment]
I can confirm on this - died near the Docks while having it and got teleported to the deafult respawn point which is in NE direction (Horde(this respawn is not in the Horde keep)

**Comment by mustbeaguy0** [comment]
I will add to this - I am not sure if it should be considered a separate issue. If so I will make one.

The situation is even worse as Horde (cannot confirm as ally). Sometimes, you get ported to the middle (Workshop) graveyard even if you do not own the base. 

That means you have to run back to your corpse or the closest graveyard. If you died inside the keep and you don't have any other bases, there's no way to ressurect. I want to add, this is nowhere near a rare issue - I've had it happen to me multiple times in the same BG even.

How it works: when you die, you spawn at a graveyard you don't own.
How it should work: when you die, you spawn at a graveyard you own.
Source: this one is pretty common sense imo.

Hopefully this gets bumped and fixed quickly, as it literally is gamebreaking. If it only affects Horde, then it also screws with the faction balance insanely much.

**Comment by Soufly** [comment]
@Afgann something is wrong,i died inside in their base(horde one),and i got ported here. https://imgur.com/a/1vRj4dW
