### ISSUE TITLE
Mounting Issue

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#300]
Decription: 
Almost everytime I get out of a building I get this message "Can only use outside" and I see the animation of my character trying to mount but doesn't let him. It happens when you are close to any entrance, if I do few steps it will allow me to mount.
http://prntscr.com/ib5nuo
http://prntscr.com/ib5pfv
http://prntscr.com/ib5qf8
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
