### ISSUE TITLE
Statistic Page

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#301]
Decription: 
When you inspect someone's statistic page in game it's completly empty on all tabs. Also on your statistic page at Largest hit dealt there is no number displayed.
http://prntscr.com/ib5szz
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
