### ISSUE TITLE
Betrayal quest- Zul'Drak Ebon Watch chain quest issue

### ISSUE THREAD

**Issue by grashyn1** [SunwellTracker/issues#3015]
Decription: 
Almost whole chain of this quests works how it should be- altough the last one- "Betrayal" have some problem, which makes it immpossible to complete. Whole fighting with the final boss works fine. There is an issue with the not appearing the skull of Drakuru, after he dies from the Lich King's blow.

How it works: 
Same as earlier. He dies, Lich King talks. There is no skull to pick up- quest requires to pick up his skull and deliver it to the quest giver. There is an animation of how it falls from him.

How it should work: 
After he dies, there should be laying something. I've put the link to the gameplay of that quest- works same- the only difference is that ther is no skull

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=opArnZy6Go8

**Comment by Azathothh** [comment]
The skull does spawn but in different place than it's on this video - it's closer to the one of platforms with trolls - please watch at which direction skull animation is "flying". I'm not 100% sure about it, but i think that if you won't pick it up after some time, it would despawn, and you have to do the fight again.
