### ISSUE TITLE
Been Banned

### ISSUE THREAD

**Issue by Seufseuf** [SunwellTracker/issues#3022]
Decription: 
please help, i found my account banned bc of cheat but i didn't use any cheats

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): my internet is not at his best this days

**Comment by Azathothh** [comment]
In player's panel (https://sunwell.pl/ucp) you can find date, reason, and who banned you.
Write an appeal on our forums: https://sunwell-community.com/index.php?/forum/159-appeals/
Bugtracker isn't place for that.
Regards
