### ISSUE TITLE
Quest : "New Recruit" Bugged

### ISSUE THREAD

**Issue by Mu-ffi** [SunwellTracker/issues#3026]
Decription: The Quest in Icecrown "New Recruit" Where you need to Subdue a Lithe Stalker and bring it to the Questgiver.

How it works: Mind controlling Lithe Stalker works as it should but after bringing him back to Vereth the Cunning nothing happens. I tried it several times with different spawns of Lithe Stalkers, nothing helped.

How it should work: 
After mind controlling Lithe Stalker with Sigil of the Ebon Blade you should just bring him back to quest giver and quest should complete.

Source (you should point out proofs of your report, please give us some source): 
![WoWScrnShot_040320_213441](https://user-images.githubusercontent.com/57496310/78398337-3979ae80-75f3-11ea-8ce9-369bc96e3a58.jpg)

**Comment by felmad** [comment]
"Lead it back to the top of the rocks northeast of here and it will find its way to me.
Completion"
https://www.wowhead.com/quest=13143/new-recruit
There is nowhere stated in the quest that you must bring it to the NPC. Quest is not bugged, only the point of finishing it may be a little bit confusing to find (and that point may be bugged but I have nor the proof neither the study to provide anything to the case)
