### ISSUE TITLE
Totem of wrath (Elemental shaman)

### ISSUE THREAD

**Issue by Keyblade76** [SunwellTracker/issues#3027]
Decription:  Hello, I have seen that my "Totem of wrath" doesn't giving me the 3% critical chance buff. It is important for me to have this work, otherwise I am not a good support DD on Raids.

Hope this helps :)

How it works: normally without 3% critical chance.

How it should work: with +3% critical chance.

Source (you should point out proofs of your report, please give us some source): 

![WoWScrnShot_040320_232504](https://user-images.githubusercontent.com/63127636/78406227-7e591180-7602-11ea-887e-62355306784e.jpg)
![WoWScrnShot_040320_232513](https://user-images.githubusercontent.com/63127636/78406229-7f8a3e80-7602-11ea-896d-89b3cf27ac45.jpg)

best regards Wutz

**Comment by Soufly** [comment]
Its a critical strike DEBUFF on your target,not buff on you.
