### ISSUE TITLE
Alchemy Quest Bug!

### ISSUE THREAD

**Issue by tetesham** [SunwellTracker/issues#3028]
Decription: After I accepted the alchemy quest - Transmutation Master - i shortly abandoned it thinking I should've picked the Elixir Master one. But, after abandoning the initial quest, I could not take the Elixir Master quest from the gnome in Honor Hold. Now, I can't do any of the three alchemy quests. Can anyone help on this situation?

Cheers.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It's not a bug.
If you've completed ANY of initial quests from honor hold, then you can start ANY 2nd part of mastery quest - in your case, you should go to Lorokeem in Shattrath.
