### ISSUE TITLE
View Distance

### ISSUE THREAD

**Issue by yuript** [SunwellTracker/issues#3033]
Hi,

The View Distance its reduce for some reason and this make the game unplayeable for pvp or some other thinks i guess it affects over all game. You should correct that because the game like that its unplayeable and for sure you will have players lossing the feelling to play for that reason.

I can understand that maybe your server or servers are not good anoth for this its working correctly but you should find a solution and give prio for this feacture its working correctly.

Best Regard's,

**Comment by Soufly** [comment]
Its on purpose.

**Comment by yuript** [comment]
But why its on purpose? it doesnt make any sense can you explaind me what sense makes ?

**Comment by Soufly** [comment]
''Viewing distance is currently temporarily reduced in order to reduce time diff during peak times. We are releasing optimizations each day and will soon revert the viewing distance.''

**Comment by lkrocek** [comment]
Patchwerk in Naxxramas is not coming automatically due to this and other features in PVE in instances are reducing usability and experiences as well, can it be set on world only(without instances)? or changes in some middle value?
