### ISSUE TITLE
Medallion trinkets does not remove any Silence effect

### ISSUE THREAD

**Issue by enginasan** [SunwellTracker/issues#3037]
Decription: 

How it works: Human's 'every man for himself' racial skill and medallion of alliance trinkets and other movement impairing effect remover trinkets does not remove any silence effect

How it should work: 
im not talking about counterspell on casting and close that spell scool for 4 secs, its ok but the silence effect must remove with medallion trinkets or 'everyman for himself' spell

Source (you should point out proofs of your report, please give us some source):

**Comment by exzetron** [comment]
It shouldnt, came in later expansions.

**Comment by cleanaccmmr** [comment]
You are not supposed to be able to trinket silence in WOTLK it comes in later expansions...

**Comment by Bestsp** [comment]
Wtf it works correctly its obvious that u are a new player in wrath of the lich king trinket dosen't dispel silence in WOTLK I'm playing wotlk since 11 years and u can ask any pvp player I'm shocked that i was confirmed GM correct this wrong report before they apply false update

**Comment by Bestsp** [comment]
If u want more info let me know thx
