### ISSUE TITLE
Shadowfiend problem

### ISSUE THREAD

**Issue by Filipxz** [SunwellTracker/issues#3039]
Decription: 
Shadowfiend isnt working 

How it works: 

Shadowfiend attacks like 3 times. 

How it should work: 

Shadowfiend follow/attacks the target like 9 times on his duration and gives mana everyattack. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2965
