### ISSUE TITLE
High Priest Talet-Kha spawn bug.

### ISSUE THREAD

**Issue by Doublespoons** [SunwellTracker/issues#304]
Decription:  The boss is located in Temple City of En'Kilah and is one of 3 bosses needed for a quest to obtain his scroll. 

How it works: The boss should spawn with two web wrapped mobs to the left and right of the boss. Also the boss should be tethered by webs by the nearest two pillars. The boss was spawned with both web wrapped mobs, but when the mobs were killed he was untargetabble. I tried this around 5 times before a GM assisted me and had to .kill the boss to reset him. When he would spawn he'd spawn without the web tethers, once he was .killed he was respawned with the correct tethers. My assumption is the boss bugged when a player killed his two wraps who then respawned after leashing the boss to de-agro.

How it should work: 
The boss should spawn with two web wrapped mobs to his left and right.

Source (you should point out proofs of your report, please give us some source):  no source to note, but evidence was there. GM Vnu assisted me with the ticket.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by SpacefulSpecies** [comment]
I am having the same issue, and I have proof: In the provided screenshot you can see the error message "You cannot attack that target".

![proof](https://user-images.githubusercontent.com/5250815/84174945-89577480-aa7f-11ea-9bab-808364089b08.jpg)
