### ISSUE TITLE
[Quest] Sacrifices Must be Made

### ISSUE THREAD

**Issue by mgrisole** [SunwellTracker/issues#3041]
Decription: 
Clicking on the "Seer of Zeb'Halak" statue does not prompt the dialog from which we can get the [Eye of the Prophets](https://wotlkdb.com/?item=35806) needed for the quest [Sacrifices Must be Made](https://wotlkdb.com/?quest=12007)

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/78565189-d3bd3a80-781d-11ea-950f-c83614fd8060.png)
Nothing wrong with this quest.
1. make sure that you're not in a raid group
2. make sure that you've got empty bag slots when using the statue.
