### ISSUE TITLE
Shatterhorn Bugged

### ISSUE THREAD

**Issue by odelljp8** [SunwellTracker/issues#3047]
Decription: 
The mob Shatterhorn for the quest "The Yeti Next Door" is currently bugged.

How it works:  Shatterhorn is giving the error invalid target when I try to attack him.

How it should work: Shatterhorn should be able to be attacked.

Source (you should point out proofs of your report, please give us some source): 
Did not take a screenshot, but I just tried to complete the quest and

**Comment by Dootz** [comment]
https://www.wowhead.com/quest=11284/the-yeti-next-door
> Description
> Maybe if the sentries won't help me, you will? I'm the foreman of the mine just across the bridge. My men are mining ore for the weapons our expeditionary force will need to carve a path into the Grizzly Hills.
> 
> A giant yeti has invaded the mine, blocking the tunnel we need to expand! We've tried yelling at him and smoking him out, but nothing's worked.
> 
> **Maybe you could rouse it from its sleep with a meal of meat from the frosthorn rams** in the snowy areas around town? Please? We're desperate! 

Gather 4x https://www.wowhead.com/item=33352/tough-ram-meat 
Combine them into https://www.wowhead.com/item=33477/giant-yeti-meal
and then use near Shatterhorn - he'll attack you.
