### ISSUE TITLE
[DK] Noggenfogger Elixirs and Killing Machine Proc

### ISSUE THREAD

**Issue by FrostSunwell** [SunwellTracker/issues#305]
Decription: 
Whenever I used noggenfogger elixirs and went into combat, killing machine wouldn't proc at all.

How it works: 
I drink noggenfogger elixirs and killing machine doesn't work in combat

How it should work: 
Killing machine should proc when on noggenfogger

Source (you should point out proofs of your report, please give us some source): 
I couldn't attach it to the post so I'm just going to link my playstv where I recorded.
https://plays.tv/video/5a7aa60d81a8b8b866/bug

**Comment by Cwiercpasiec** [comment]
Killing Machine procs from auto attacks, after you drank elixir I didn't notice even one white hit. I heard that on old sunwell noggenfogger elixir buged auto attack, i think that's why your KM couldn't proc.
