### ISSUE TITLE
melee auto attacks go through walls

### ISSUE THREAD

**Issue by unknovvwn** [SunwellTracker/issues#3050]
Decription: 
In arena (and possibly elsewhere) melee auto attacks hit through the corners of pillars. This allows melee damage, poisons and other on hit spells (like seal of vengeance dot) be applied even when target is out of line of sight, also prolongs combat.

How it works: 
When 1 players stands near the corner of a pillar and other players stands around the same corner but on other side of the pillar, they can still hit eachother with melee autoattacks, even though they are not in each others line of sight and melee abilities cannot be cast anymore (it says not in line of sight for those abilities) 

How it should work: 
Melee autoattacks should not go around/through the corner and should stop, same as melee abilities are stopped by a corner.

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/1241#issuecomment-561178311
