### ISSUE TITLE
[Alchemy] Dalaran Alchemy trainer doesn not teach all development skills 

### ISSUE THREAD

**Issue by Doliven** [SunwellTracker/issues#3055]
Decription: 
In Dalaran NPC Linzy Blackbolt does not teach all development skills only Grand Master Alchemist. All other Grand Master Profession Trainers in Dalaran teach all development skills.

How it works: 
Alchemist trainer in Dalaran does not have option to learn basic development skills (see attachment) 

How it should work: 

It should work as every other profession trainer in Dalaran  (see attachment) 
![Alchemy trainer](https://user-images.githubusercontent.com/63343203/78767687-34b65100-798b-11ea-9714-cf2cb79a84f1.png)
![example blacksmithing trainer](https://user-images.githubusercontent.com/63343203/78767693-35e77e00-798b-11ea-8fbb-c1847fb33e30.PNG)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://www.wowhead.com/npc=28703/linzy-blackbolt#comments:id=1102052
> By Macilles (6,392 –  1·13·38)  on 2010/08/17 (Patch 3.3.5) |   |  
> Seems this trainer will only train the experienced Alchemists starting at skill 350.
> 
> Not sure why Alchemy was skipped when they made lower lvl crafting skills available from Dalaran trainers :/
>
