### ISSUE TITLE
Kidney Shot issue

### ISSUE THREAD

**Issue by zetikov** [SunwellTracker/issues#3059]
Decription: 
If you use Kidneyshot with a Sub Rogue on a target which is not stunned, the Model often turn around 180° and you cant attack the Model from behind 

Update: Its a general problem with stuns (same issue with cheap shot)

How it works: 
If you use Kidneyshot with a Sub Rogue on a target which is not stunned, the Model often turn around 180° and you cant attack the Model from behind 
How it should work: 
Kidneyshot shouldnt do that 180° turn around of the model.

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/2572
