### ISSUE TITLE
[Quest] Missing quest: "See to the Operations"

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#306]
Decription: There is missing quest in Howling Fjord. And with the missing quest also missing whole quest chain which contains 3 quests. The quest chain starts at the NPC named Overseer Irena Stonemantle with the name "See to the Operations" at the Steel Gate in Howling Fjord. This quest is just turn in to Steel Gate Chief Archaeologist which continues the quest line with 2 more quests named "I've Got a Flying Machine!" and "Steel Gate Patrol".

How it works: 
The NPC Overseer Irena Stonemanle doesn't give the quest.

How it should work: 
Because there is no prequest required for the quest to appear at the questgiver, only level requirement, the NPC Overseer Irena Stonemanle should give the quest.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=11176/see-to-the-operations

**Comment by Burnz2** [comment]
I can pick this quest up, but I have a guy on Discord that can't, it seems.

**Comment by Dootz** [comment]
right now to get this quest you need to complete http://www.wowhead.com/quest=11240/leader-of-the-deranged . It'll be changed so that anyone can pick it without any previous quest requirements.

**Comment by Danielmkd21** [comment]
Just did it, i discovered that myself. I did the quest http://www.wowhead.com/quest=11240/leader-of-the-deranged  and I got the qust chain. But also as for Burnz2 the machine on the 3d q when you killing gargoyles cant be moved up or down, nor even using space. Thanks for everything.

**Comment by Kokaina** [comment]
Done.
