### ISSUE TITLE
Eye of Eternity (25 players) [Heart of Magic]

### ISSUE THREAD

**Issue by Olcivks** [SunwellTracker/issues#3060]
Decription: 
I did **Eye of Eternity** (25players) and I wanted to complete quest with [Heroic Key to the Focusing Iris] but when I was about to click the heart-shaped chest after we killed boss Malygos, it dissapered. I still have the quest item and also I have ID for this instance. I did ticket to GM but they sent me here.

How it works: 
After killing Malygos, the heart dissapeared after one person clicked it.

How it should work: 
Heart shouldn't dissapear after one person click it. It should be available for all players in instance.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, I belive currently there is only one Heart of Magic per raid group. Which according to sources is a bug.

Duplicate:
https://github.com/SunwellTracker/issues/issues/1640
https://github.com/SunwellTracker/issues/issues/2675
