### ISSUE TITLE
Bugged DMG at mele stats with sword

### ISSUE THREAD

**Issue by Hicane** [SunwellTracker/issues#3061]
Decription: 
Bug is simple. Item: Sword of justice ( 200 itlvl blue ) have more dmg at axe Death's Bite ( 213 itlvl epic)

How it works: 
Sword dmg >> Axe dmg 

How it should work: 
Axe should have more dmg than sword
![WoWScrnShot_040920_234406](https://user-images.githubusercontent.com/63428565/78944528-67149b00-7abe-11ea-8f9b-332a65e92db8.jpg)
![WoWScrnShot_040920_234612](https://user-images.githubusercontent.com/63428565/78944532-6845c800-7abe-11ea-8d64-d476c15f87e3.jpg)
![WoWScrnShot_040920_234616](https://user-images.githubusercontent.com/63428565/78944533-68de5e80-7abe-11ea-9665-a3dae957220b.jpg)
![WoWScrnShot_040920_234401](https://user-images.githubusercontent.com/63428565/78944535-68de5e80-7abe-11ea-91a8-222344bf0c5a.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Platinumcoated** [comment]
Before you post a bug report you should research the issue and provide sources that prove that it's broken on sunwell.
Auto attack damage (which is shown on char tab) is calculated using the weapon's damage, the weapon's speed and your attack power

**Comment by Shragenator** [comment]
No evidence is shown here.
