### ISSUE TITLE
[Quest] We Have the Power

### ISSUE THREAD

**Issue by Jonsse** [SunwellTracker/issues#3065]
Decription:
NPC Kathorn does not drop the quest item Kathorn's Power Cell.

How it works:
As stated in the description. I had to kill him twice to get the item.

How it should work:
Maybe the drop rate should be increased?

Source (you should point out proofs of your report, please give us some source):
The droprate should logically be the same as the droprate of Durar's Power Cell which is the second quest objective.

**Comment by Dootz** [comment]
Hi,
drop chance for both quest items is 70% so you may have been unlucky.

**Comment by Jonsse** [comment]
What? You're serious? It's a drop, for a quest, from a quest npc, of which there are only a singular one in the world? How can that be 70%? That doesn't make any sense.
