### ISSUE TITLE
[Mobs/Pathing] When silenced, mobs that are primarily casters will not close the gap between their target. 

### ISSUE THREAD

**Issue by JamesIsAwkward** [SunwellTracker/issues#3069]
Description: When silenced, mobs that are primarily casters will not close the gap between their target and begin attacking them with melee. This makes silencing and backing mobs out of a dense area impossible. So far every caster-type mob does this in the Ghostlands from my experience. I haven't been to other areas yet to find out, but I suspect they all use the same underlying mechanic when silenced.

How it works: For example, if there is a Shaman-type mob and I Kick to interrupt their Lightning Bolt and silence them, and then back up a few feet the mob will NOT follow me and attack with melee. It will just stand there until the silence debuff fades.

How it should work: When silenced, most casters will run up to their target and attack them with their melee weapon until the silence debuff fades.

Source (you should point out proofs of your report, please give us some source): It's a known bug, I've been asking around and a lot of people have confirmed this to be the case.

**Comment by JamesIsAwkward** [comment]
Just tested this in the barrens with Bristleback Geomancers and they performed just as they should but they did have a bit of delay in switching to melee attacks.

**Comment by Shragenator** [comment]
I noticed this incorrect behavior exists for this mob https://db.darkwizard.pl/?npc=27639.   You can silence or kick this NPC from range and it will not move to you.

**Comment by Shragenator** [comment]
Can confirm this incorrect behavior also exists for the NPC "Druid of the Fang"  in the Wailing Caverns dungeon.

**Comment by JamesIsAwkward** [comment]
Interesting that only certain mobs are affected, I assumed they all used the same underlying mechanic.


Something I've also noticed is some mobs that do perform melee after being silenced have a pretty large delay, up to 2-3 seconds sometimes, before they begin melee attacks.

**Comment by Afgann** [comment]
Issue will be fixed for most casters with next update. Some mobs will still behave incorrectly because of old scripts, they need to be fixed individually.

**Comment by JamesIsAwkward** [comment]
Thanks @Afgann !
