### ISSUE TITLE
[Quest] Missing quest: "Everything Must Be Ready"

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#307]
Decription: There is quest missing in Westguard Keep in Howling Fjord. The quest starts at the NPC named Quartermaster Brevin. According to wowhead the quest has prequest named "Mission: Plague This!". I already finished this quest, and yet the NPC doesn't want to give any quest. The quest that is missing is only turn in quest to NPC Gil Grisert in Fort Wildervar and I assume it opens some new quests there. 

How it works: 
The NPC Quartermaster Brevin doesn't give the quest.

How it should work: 
The quest should be implemented in the game.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11406/everything-must-be-ready

**Comment by Danielmkd21** [comment]
What about this one? Is there some prequest I should do, to be able to pick it. All required prequests I have done. I dont care much about this quest, as about the quests it opens up in Fort Wildevar. Please give me some info. Thanks

**Comment by Dootz** [comment]
For this one right now you need to complete : http://www.wowhead.com/quest=11250/all-hail-the-conqueror-of-skorn

I'll be changed probably in next update to : "Mission: Plague This!"

**Comment by Danielmkd21** [comment]
Ok and when its the next update? thanks for the info

**Comment by Afgann** [comment]
Next Monday probably.

**Comment by Kokaina** [comment]
Done.
