### ISSUE TITLE
Ulduar: XT-002 Searing light and gravity bomb not affected by pet avoidance.

### ISSUE THREAD

**Issue by Subrias** [SunwellTracker/issues#3071]
Decription: 
Searing light and gravity bomb damage is not being reduced by pet avoidance (90% reduction).

How it works: 
pets taking 3.3k dmg per tick from searing light on hard mode XT. 15k from gravity bomb.

How it should work: 
Pets should take only 10% of the damage from aoe so 330 dmg per tick. and only 1500 from gravity bomb.

Source (you should point out proofs of your report, please give us some source): 
your database says searing light is 3000 per tick. 
https://db.darkwizard.pl/?spell=65120

Avoidance is 90% reduction 
https://db.darkwizard.pl/?spell=65220

My pet is Anasazi, this is a log from our hard mode ulduar.
http://www.worldoflogs.com/reports/7rc5d4m89b78wdp4/details/10/

**Comment by Soufly** [comment]
True,thats the reason why the pets are dying on that fight.

**Comment by Chryslol** [comment]
Pretty toxic also after pet-fix (of them always being behind target)- cant put them anywhere else.
