### ISSUE TITLE
Website Armory

### ISSUE THREAD

**Issue by Pearlsss** [SunwellTracker/issues#3074]
Decription: Wrong talents on website, they're not for 3.3.5a for classes: priest, paladin, warlock. Also wrong scaling unless having a higher resolution on desktop pc. Some classes have polish language on talent info.

How it works:  Talents: i think for those classes the talents are for 3.0.1 (? not sure) Scaling: for any class it looks like they got a liposuction -unless browser scale is reduced from 100% to 80% or 67% -for people that have a lower resolution, like me, personally have 1680x1050. Works fine for who has a bigger display. On android phones it looks bad as well. Polish language on some classes talents while website being used in english, for example hunter. Proof pics included bellow

How it should work: All classes talents showing the correct scale -for the people who have lower resolution and monitor/lcds, some android phones., the right talents for all 3.3.5a classes., english language while website being used in english.

Source (you should point out proofs of your report, please give us some source):  Was reported before few times, like here since 6 november 2019 (?) Will included pics withe the wrong and right values bellow. Think that Admins Raphael and Aza. already have some in their discord dms from a while ago as well. Thank you
![Screenshot_5](https://user-images.githubusercontent.com/58818462/79235768-b66b1a80-7e74-11ea-8d24-c6ea7c676112.png)
![Screenshot_6](https://user-images.githubusercontent.com/58818462/79235770-b834de00-7e74-11ea-9668-100cb11e060c.png)
![Screenshot_7](https://user-images.githubusercontent.com/58818462/79235773-b8cd7480-7e74-11ea-8bdb-10366d373096.png)
![Screenshot_10](https://user-images.githubusercontent.com/58818462/79235777-b9660b00-7e74-11ea-954d-a889a99dc975.png)
![Screenshot_11](https://user-images.githubusercontent.com/58818462/79235779-b9660b00-7e74-11ea-91ce-142c85d38530.png)

**Comment by Raphtrack** [comment]
old www
