### ISSUE TITLE
quest bury those cockroaches

### ISSUE THREAD

**Issue by fruvel** [SunwellTracker/issues#3078]
Decription: use q item on sinkholes near warsong hold

How it works:  when u use q item on sinkholes it explode, but does not pass, or have small pass rating on sinkholes 

How it should work: when u place q item near sinkholes it should pass on any place near and in sinkhole 

Source (you should point out proofs of your report, please give us some source):  take q and try it on west and north sinkhole

**Comment by Dootz** [comment]
Hi,
I was not able to recreate this issue so far. Completion was granted to my character even when I was far away. Were you able to get a credit for any of them by for example standing closer? Can you see a message in chat "Seaforium Depth Charge armed.
Detonation in 5...
4...
3...
2...
1..."
?

**Comment by Azathothh** [comment]
I've found what's the cause of it (just not sure why it matters).
It's not possible to get it done if our character is in combat at the moment when charge explodes.
Without combat everything is fine.
