### ISSUE TITLE
Aoe damage cap

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3079]
Decription: Aoe damage cap
How it works: Might not exist for specific abilities(need more researching)
How it should work: Versus 10 or fewer targets the aoe damage should stay the same(per target),but with 11 or more should be divided.
Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Area_damage_caps

**Comment by Afgann** [comment]
It should work for most cases, could you tell me where it fails to do so?

**Comment by Soufly** [comment]
Well i did my test on Freya's adds and Volley/Explosive trap had no cap.I did another test in icecrown with 11+ mobs and still those abilities had no cap.U should do a test with pestilence/howling blast on 11+ targets.

**Comment by Afgann** [comment]
Changed a few things, lemme know if it works after next update.

**Comment by exzetron** [comment]
"These have been put on to most Area of Effect spells as of Patch 2.2."

Not all classes, paladins concecration shouldnt be affected

**Comment by Zynical** [comment]
This should not be put on Paladin Consecration, this will really mess with Paladin/Druid AoE threat and clearing. Swipe(Bear) and Consecration has always been unaffected by this Diminishing Returns for Threat purposes

**Comment by Zynical** [comment]
I also notice someone mentioning "Pestilence" as an issue, pestilence puts a disease on all targets and then that disease is a single target dot, there should not be a cap on this spell either (haven't tested but I figued I'd comment on it anyway)

**Comment by Soufly** [comment]
https://blue.mmo-champion.com/topic/1524-why-a-nerf-on-all-aoe/ , https://www.mmo-champion.com/threads/673534-Onyxia-Whelp-AOE-Damage , a bit more info.There should be a cap for most of the aoe spells,but i'm not sure which should not be affected.

**Comment by Soufly** [comment]
http://web.archive.org/web/20090107184759/http://forums.worldofwarcraft.com/thread.html?topicId=443123919&sid=1 , http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/ , http://web.archive.org/web/20080811092840/http://elitistjerks.com/f31/t17008-warlock_pve_raiding_compendium/ , http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/

**Comment by Soufly** [comment]
https://web.archive.org/web/20130810144837/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/ @Afgann

**Comment by Zynical** [comment]
That list is incomplete and wrong? There's no DK spells, also I see swipe and cons still on it... It should not be. 
Also if you scroll down to one of the comments there's people confirming this.

**Comment by Soufly** [comment]
I found this mangos report https://github.com/cmangos/issues/issues/2054 - in the report u can see more links through oldwebpages

**Comment by Zynical** [comment]
Ok I just wanted it to be stated so they don't look at that 10 year old forum post and start programming. :)
Holy wrath has been affected by the cap since I started the server and has been diminshed properly, while cons has not (as it should be). Until 7 days ago.

**Comment by Soufly** [comment]
TBC version http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/
http://web.archive.org/web/20081020192602/http://elitistjerks.com/f31/t17008-warlock_pve_raiding_compendium/ http://web.archive.org/web/20090107184759/http://forums.worldofwarcraft.com/thread.html?topicId=443123919&sid=1

**Comment by Soufly** [comment]
A bit more info: This cap ignores critical strikes. In other words, the damage cap is calculated based on the non-critical damage per target, the spells is capped before critical strikes are taken into account, and critical strikes from the AoE can boost the damage past the AoE cap. Most AoE spells that deal damage from a debuff placed on the target (example:  [Shadowflame]), rather than direct damage or a debuff from a ground-effect damage over time AoE, will not have an AoE damage cap.

**Comment by Soufly** [comment]
https://wow.gamepedia.com/Area_of_Effect - This cap ignores critical strikes. In other words, the damage cap is calculated based on the non-critical damage per target, the spells is capped before critical strikes are taken into account, and critical strikes from the AoE can boost the damage past the AoE cap. Most AoE spells that deal damage from a debuff placed on the target (example: [Shadowflame]), rather than direct damage or a debuff from a ground-effect damage over time AoE, will not have an AoE damage cap.
