### ISSUE TITLE
[Quest] Mobs despawning

### ISSUE THREAD

**Issue by DatPotato** [SunwellTracker/issues#308]
Decription: 
Trying to do the quest "Free your mind" in Icecrown, the quest mobs despawn before I am able to use the item on their corpse.

How it works: 
Mobs despawn within a couple seconds.

How it should work: 
Increased time to be able to use item on corpse.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
#238

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/308
