### ISSUE TITLE
quest Valduran the Stormborn

### ISSUE THREAD

**Issue by Vojtyla** [SunwellTracker/issues#3082]
Decription: 
Can't interact with NPC

How it works: 
upon using Bouldercrag War Horn nothing happens, allies dont spawn, Valduran the Stormborn is untargetable

How it should work: upon using horn i should get 2 allies and my Valduran should turn hostile.

Source (you should point out proofs of your report, please give us some source):

**Comment by Vojtyla** [comment]
next day it was working fine

**Comment by Dootz** [comment]
Hi,

I was not able to recreate this. Was he spinning in air before you used the item?

**Comment by Dootz** [comment]
just after I wrote it happened :D Will be fixed with next update.

**Comment by Vojtyla** [comment]
<3

pon., 20 kwi 2020, 22:05 użytkownik Chris <notifications@github.com>
napisał:
