### ISSUE TITLE
Warlock Conflagrate Issue

### ISSUE THREAD

**Issue by Smizkarn** [SunwellTracker/issues#3083]
Decription: After applying immolate, conflagrate is not available the same global making my rotation change completely

How it works: In order to use conflagrate I need to apply immolate debuff first. What happens is that it takes about 0,5 after the debuff have been applied until I can use conflagrate which is super annoying because the rotation needs to change instead of casting conflagrate out of the global cooldown.

How it should work: Cast immolate and immediately use conflagrate efter the cast of immolate is complete (because the immolate debuff applies immediately after the cast)

Source (you should point out proofs of your report, please give us some source): I've attached a screenshot of a pig suffering the immolate debuff while the conflagrate icon still shows dark unable to use;

https://imgur.com/a/LJBNz7s

![WoWScrnShot_041520_075655](https://user-images.githubusercontent.com/63699801/79303794-0dfa9c00-7ef0-11ea-9f28-288dff250f17.jpg)

**Comment by Soufly** [comment]
https://github.com/SunwellTracker/issues/issues/2901 - WONT BE FIXED :) .
