### ISSUE TITLE
Rich Thorium Veins in Dire Maul East

### ISSUE THREAD

**Issue by tols400** [SunwellTracker/issues#3084]
Decription: 4 Rich Thorium Veins has been spawning in Dire Maul East, but from 14/4-2020 There has only been spawning 1 Rich Thorium vein, How come this has been change? Is it a bug?

How it works: 

In the Tunnel behind last boss in Dire Maul East, it happens to only spawn 1 Rich Thorium down from 4

How it should work: 

When i started on the server there has been spawning 4 Veins every time you reset the dungeon

Source (you should point out proofs of your report, please give us some source): 
![2020-04-15](https://user-images.githubusercontent.com/63719252/79333888-93e20b80-7f1f-11ea-9621-30ea9b408c73.png)

**Comment by Dootz** [comment]
4 spawns were unintentional. It will be increased to max 2 spawns with next update.
