### ISSUE TITLE
Can't prospect titanium ore

### ISSUE THREAD

**Issue by mutopek** [SunwellTracker/issues#3085]
Decription: 
Titanium ore isn't prospectable

How it works: 
When I try to prospect titanium ore I get the message "There are no gems in this" and instead of "Prospectable" there is "Requires Jewelcrafting (450)". I have 451.

How it should work: 
It should give random gems for 5 ore

Source (you should point out proofs of your report, please give us 
![prospecting](https://user-images.githubusercontent.com/42170898/79396761-e56cb380-7f7c-11ea-82de-c3cdd395a4cf.jpg)
some source):

**Comment by Soufly** [comment]
Patch 3.2.0 (04-Aug-2009): Titanium Ore can be prospected. Prospecting titanium yields Titanium Powder. - Wait for TOC.
