### ISSUE TITLE
Gundrak Raptors Leather count

### ISSUE THREAD

**Issue by Helleia** [SunwellTracker/issues#3089]
Decription: 
Gundrak Raptors drop 1-3 Borean leathers.

How it works: 
They drop between 1 and 3 borean leathers.

How it should work: 
They should drop 1-8 borean leather according to wowhead. 

Same wowhead link is provided in this issue:
https://github.com/SunwellTracker/issues/issues/1265
Source (you should point out proofs of your report, please give us some source): 
https://www.wowhead.com/npc=29334/gundrak-raptor#skinning

Here is a quick run in angrathar:
![image](https://user-images.githubusercontent.com/63871037/79616879-caca4400-810e-11ea-86f5-f43f6d33042b.png)

**Comment by Azathothh** [comment]
It's correct now, it was either changed in future expansions, or just displayed incorrecty on wowhead.
Please check comments/forum posts written during wotlk on retail - they all provide info about 1-3leathers dropping, not a single mention about 8.
