### ISSUE TITLE
[Mage] Deep Freeze

### ISSUE THREAD

**Issue by davidb9310** [SunwellTracker/issues#309]
Decription: 
Mage skill/talent "Deep Freeze" do not deal dmg only stun the target

How it works: 
only stuns the target

How it should work: 
it should deal dmg and stun frozen targets

Source (you should point out proofs of your report, please give us some source): 
https://scr.hu/vP5GAX
https://scr.hu/re52gV

**Comment by Cwiercpasiec** [comment]
Deep Freeze should deal damage only to targets PERMANENTLY immune to stun (like most of ride bosses, demolishers etc.). This also means that Deep Freeze shouldn't deal damage to Death Knights under Icebound Fortitude effect (they are immune to stun during the buff, not permanently).

Source:
https://www.youtube.com/watch?v=ItJV_IApfPs about 3:40 mage casts Deep Freeze and frostbolt, only frostbolt damages the target, Deep Freeze just stuns it.
