### ISSUE TITLE
sons of hodir reputation

### ISSUE THREAD

**Issue by dopamine1** [SunwellTracker/issues#3090]
Decription: 
hello i finished all the chain quests for sons of hodir but I'm still hated I got no reputation from the chain quest 

How it works: 
I got nothing

How it should work: 
I'm supposed to receive reputation after finishing the chain quest

Source (you should point out proofs of your report, please give us some source): 
check the character with the name 'Xdopamine' on frosthold server

**Comment by Azathothh** [comment]
If you're still hated, then it means you haven't finished all quests: https://wowwiki.fandom.com/wiki/The_Sons_of_Hodir_quest_chain
most likely you've done [80] Mending Fences (+28,600 The Sons of Hodir) , but haven't done [80] A Spark of Hope (+28,600 The Sons of Hodir) 
You should find it at Fjorn's Anvil, east from Dun Niffelem
