### ISSUE TITLE
Freya's Ground tremor dmg seems to be not reduced by armor

### ISSUE THREAD

**Issue by Soldarian** [SunwellTracker/issues#3095]
Decription:  Freya's Ground Tremor deals physcial damage and as such it should be reduced by the amount of armor that given player has in the moment when tremor happens.

How it works: Damage on clothies and platers (even tanks) is very similar.

How it should work: Damage should be reduced accordingly to physical dmg reduction from armor.

Source (you should point out proofs of your report, please give us some source):  http://www.worldoflogs.com/reports/wsj94y9lwoitetzn/log/?enc=bosses&boss=32906

**Comment by Chryslol** [comment]
Indended, was the same on Angrathar.
