### ISSUE TITLE
Players get stuck in a falling loop after completing a quest in Icecrown.

### ISSUE THREAD

**Issue by CristenPerret** [SunwellTracker/issues#3097]
Description: 
Once completing a quest in Icecrown: The Argent Vanguard (85.6, 76) the player transitions into a different world state/layer and in doing so they get stuck into a state of falling that stops players from '/camp', or hearthing even forced movements like fear, MC, and Deathgrip dont fix this issue. The only way to resolve it, and regain control of a player again is to Die or close the client and reconnect.

How it _doesn't_ work: 
If a player is by themselves and gets stuck, it can be frustrating.
There really isnt a way for another player to help out one that is struggling, because it must be in between differing layers, so unless you're specifically at that point in the chain its not possible. 
Fear allows players to break the game in a lot of fun and interesting ways, yet fear or other forced movements dont help, so its pretty hard to help unless you kill the opposing, or instruct allied factions to disconnect and reconnect. 

How it should work: 
Turn in quest, and walk through new layer so they can pickup and continue the cycle.

Source (you should point out proofs of your report, please give us some source): Im still in the layer in the spot of the bug, helping many other stuck players out while typing this up.

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/1232
