### ISSUE TITLE
[Rogue] Blade Flurry - Incorrect armor calculation.

### ISSUE THREAD

**Issue by Netherfrost** [SunwellTracker/issues#31]
Decription: 
Blade Flurry is incorrectly calculating armor reduction of damage twice, once when it hits, and once when it reflects.

How it works: 
Currently hit 1 is mitigated by armor (correct) this is then directed to 2nd target where it AGAIN is mitigated by armor (not correct) 

How it should work: 
The redirected attack should be counted seperately / directly depending on what sources you want to trust

Source (you should point out proofs of your report, please give us some source): 
https://github.com/Looking4Group/L4G_Core/issues/1636
https://github.com/dalaranwow/dalaran-wow/issues/1383

"Also if u watch this video of LK 25hc world 1st https://www.youtube.com/watch?v=RSeVCw3hVgQ , from a rogue perspective on 5:37 he pops BF+KS, and u can see that BF duplicates exact same hits of other abilities and melee.
That being said, i doubt he has 100% armor pen, because he uses Herkumi War Token, and they were trying for worlds 1st, so no one had best gear. And now on Beta ICC test, rogue struggles to get 100% arp without STS, and he was using Rupture (which full rogues dont use) but yet again they had Expose Armor on LK.
Considering all your previous comments about armor of secondary target, they most certainly didnt have armor reduction on adds, and rogue didnt have 100% armor reduction on adds, so how did BF hit exact same numbers on adds as it hit on boss?
Fukk, he was hiting Raging Spirit. Still i think it was usefull observations. Usefull rogue moments are 5:37 , 8:05, 13:41, 19:54
13:41 shows that melee hits while in Killing Spree is active, so those melee hits can generate Combat Potency while in KS."

EDIT: 

**How to confirm the issue:** 
_Assumption:_ 2 NPCs with identical values, including armor, meaning, a 50% reduction.

**How it functions:** I do 1k damage and it will hit my target for 500, but it will do 250 on the second, because it will be affected by both targets armor. [Currently how it functions on line (NOT INTENDED)] 
**Source:** **https://imgur.com/a/gk8R6**

**How to fix:** All of the gained attacks from Blade Flurry (Spell ID:13877) should go past the generic attack checks, since it is supposed to be a calculation of its own, not based on the initial value, AKA; it needs its own armor calculation based on the targets which it affect.

**Comment by Netherfrost** [comment]
https://imgur.com/a/gk8R6

#Save the Rogues

**Comment by Senex91** [comment]
Can confirm bug, please fix.
#RoguesAlreadyGotShitEnoughAoEDamage

**Comment by Netherfrost** [comment]
HELP

**Comment by Netherfrost** [comment]
**How to confirm the issue:** 
_Assumption:_ 2 NPCs with identical values, including armor, meaning, a 50% reduction.

**How it functions:** I do 1k damage and it will hit my target for 500, but it will do 250 on the second, because it will be affected by both targets armor. [Currently how it functions on line (NOT INTENDED)]

**How to fix:** All of the gained attacks from Blade Flurry (Spell ID:13877) should go past the generic attack checks, since it is supposed to be a calculation of its own, not based on the initial value, AKA; it needs its own armor calculation based on the targets which it affect.

**Comment by Netherfrost** [comment]
Is the report missing anything?

**Comment by Riztazz** [comment]
Nope, thanks @Netherfrost for the help with testing, fix should be live on monday

**Comment by Riztazz** [comment]
Resolved with next realm update
