### ISSUE TITLE
[Quest] HELP!

### ISSUE THREAD

**Issue by sunstriderko** [SunwellTracker/issues#310]
Decription: 
Key required for completing Nagrand's "HELP!" quest has a weird drop rate from ogres.

How it works: 
I literally spend 30minutes killing ogres which was like 40+ ogres and nothing dropped so I guess its not 20% like some old wowwiki pages say.

How it should work: 
It should definitely drop more.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Done.
