### ISSUE TITLE
Ethereal Portal - Item

### ISSUE THREAD

**Issue by okurosama** [SunwellTracker/issues#3102]
Decription: Ethereal Portal is too big (its for giants right now)

How it works: 
http://prntscr.com/s34j8z

How it should work: 
https://www.youtube.com/watch?v=JtRlC4E2W0c

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=3klEFahlKEE
https://www.youtube.com/watch?v=9DW1YQ7XvXM

**Comment by Piootrek** [comment]
It's a problem with your modified client. It works correctly.

**Comment by okurosama** [comment]
I downloaded wow client from your web side...
