### ISSUE TITLE
Ammo for Rumbleshot Quest

### ISSUE THREAD

**Issue by Meridius93** [SunwellTracker/issues#3107]
Decription:  Ammo for Rumbleshot Quest 

How it works:  Crate doesn't spawn

How it should work:  Crate should spawn with ammo and other junk shits

Source (you should point out proofs of your report, please give us some source):   waited almost 30 minutes for this crate

**Comment by Dootz** [comment]
Hi currently it respawns after 15 minutes it will be reduced after next update.
