### ISSUE TITLE
Argent Tournament NPC's not spawned

### ISSUE THREAD

**Issue by Revlys** [SunwellTracker/issues#3108]
Decription: The following npc's are not spawned in Argent Tournament:
- Dame Evniki Kapsalis <Crusader's Quartermaster>
- Narasi Snowdawn <The Silver Covenant>
- High Crusader Adelard
- Crusader Silverdawn
- Savinia Loresong <The Silver Covenant>

How it works:  They all should be spawned in order to take quests and buy items with Champion's Seals.
How it should work: Please check and spawn this npc's.

Source (you should point out proofs of your report, please give us some source):  https://db.darkwizard.pl/?npc=34885
https://db.darkwizard.pl/?npc=34880
https://db.darkwizard.pl/?npc=34882
https://db.darkwizard.pl/?npc=35094
https://db.darkwizard.pl/?npc=34912

**Comment by Azathothh** [comment]
These npc's were added in patch 3.2.0 - they would be added with ToC content.
