### ISSUE TITLE
Wintergrasp Vehicle and atleast 1 portal

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#311]
Decription: 
Wintergrasp issues
~~1. Vehicles in general, #185 touched on this. Obv different numbers here but it should scale with itemlevel i believe. (muh gearscore)~~

2. this portal is a traitor https://i.imgur.com/9CyWIcd.png https://streamable.com/d9r0i

How it should work: 
~~Vehicles should scale~~ this seems to be fixed
Portals should not sell you out to the enemy when trying to grab it

**Comment by Kokaina** [comment]
Done.
