### ISSUE TITLE
Figurine - Emerald Boar - low damage

### ISSUE THREAD

**Issue by Majkelogic** [SunwellTracker/issues#3112]
Decription: Phantom Boar which is summoned to fight, deal only 24 damage at 80 level

How it works: Phantom Boar should deal more damage i couldn't find information about damage for wotlk

Source (you should point out proofs of your report, please give us some source): https://wotlkdb.com/?item=42418

**Comment by Dootz** [comment]
https://www.wowhead.com/spell=56203/figurine-emerald-boar#comments
https://www.wowhead.com/item=42418/figurine-emerald-boar#comments
![obraz](https://user-images.githubusercontent.com/25490436/80412121-a0764480-88cd-11ea-8ef0-9e59a38fa08f.png)
![obraz](https://user-images.githubusercontent.com/25490436/80412135-a8ce7f80-88cd-11ea-9dba-0b5f4a4a8394.png)

Hi,
according to comments below it's supposed to have low damage, but I can agree that it's even lower then comments describe. It will be slightly increased but nothing spectacular.
