### ISSUE TITLE
Algalon missing speech/quote after wipe

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#3115]
Decription: Algalon is missing a quote

How it works: Algalon is missing his first line; 
"See your world through my eyes: A universe so vast as to be immeasurable - incomprehensible even to your greatest minds."

He does it for first pull only. This messes up DBM-combat-timer
How it should work: 
Algalon should do this line at every pull. 

Source (you should point out proofs of your report, please give us some source): 
checked DBM file: localization.en which has this line to trigger Pull-timer:
YellPull 				= "See your world through my eyes: A universe so vast as to be immeasurable - incomprehensible even to your greatest minds."

**Comment by Swiplington** [comment]
piggybacking of this.

Yogg says "Your will is no longer you own." after you reach 0 sanity. It's a typo and supposed to be:

"Your will is no longer your own."

:)

**Comment by Dootz** [comment]
Hi,
I belive he (Algalon) should say this only on first pulland there is a lot of evidence to support this.
See below wowwiki, and recording from world first Algalon where he does not say it. 
https://www.youtube.com/watch?v=uv_b1-bsN5o
https://wowwiki.fandom.com/wiki/Algalon_the_Observer
![obraz](https://user-images.githubusercontent.com/25490436/80410014-23959b80-88ca-11ea-8fc4-98f1a8acd71a.png)

@Swiplington thanks, I'll correct this.

**Comment by Chryslol** [comment]
There is a missing quote tho from what you just linked. It's just a different one, can edit DBM myself to make it work.

I was just going from how it was on Angrathar. But yeah, second wipe = no speech which is incorrect.

"Your actions are illogical. All possible results for this encounter have been calculated. The Pantheon will receive the Observer's message regardless of outcome."
