### ISSUE TITLE
Profession , Alchemy [Alchemy: Northrend Alchemy Research]

### ISSUE THREAD

**Issue by Moonhoof** [SunwellTracker/issues#3118]
Decription: [Alchemy: Northrend Alchemy Research] recipe for [Potion of Wild Magic]

How it works: You create [Alchemy: Northrend Alchemy Research] you get Potion and it say's you get the recipe (but you do not get it) , (you cant find it in your Profession menu)

How it should work:  You create [Alchemy: Northrend Alchemy Research] get Potion and Recipe and you are able to find it in your Profession menu .

Source Proof is that i have 3 day's CD of [Alchemy: Northrend Alchemy Research] and its the first time i ever made this because i just leveled up my profession and i don't have single of those rare Recipes you take from [Alchemy: Northrend Alchemy Research] i get only Potions not the Recipe
![Moonhoof](https://user-images.githubusercontent.com/64314888/80281416-a6282a80-8713-11ea-845c-31b7e32b664c.png)

**Comment by Moonhoof** [comment]
I got only potions from [Alchemy: Northrend Alchemy Research] i did not get the Recipe .
If you are able to help me please do it .
On the picture i upload you can see that i have CD on [Alchemy: Northrend Alchemy Research] , i do not have the Recipe of the potions i get and you can see the potions i get in my Auction House .

**Comment by deathstreal** [comment]
You get random potions and a random recipe. So, you can discover Potion of Speed recipe and get Potion of Wild Magic items.

**Comment by Dootz** [comment]
18/11/2020 - tested works correctly
