### ISSUE TITLE
Sunhawk not casting spells

### ISSUE THREAD

**Issue by Lenivietz** [SunwellTracker/issues#312]
Decription: 
Sunhawk Pyromancers, when attacked, use their baisc attacks, instead of casting Fireball.
How it works: 
Sunhawk Pyromancers attack the target by running close to him and attacking the target with a sword in meele range.

How it should work: 
The Sunhawk Pyromancers begin casting Fireball onto the aggroed target.

Source (you should point out proofs of your report, please give us some source): 
Try to go to Bloodmyst Isle and watch how they react.

**Comment by Lenivietz** [comment]
Idk if i am allowed to bump, but still not working for me.

**Comment by Kokaina** [comment]
Fixed.

**Comment by Afgann** [comment]
@Lenivietz Just for clarification, Works locally | Requires testing label means that the issue is already fixed, but it isn't present on main realm.

**Comment by Lenivietz** [comment]
@Afgann So when the issue is fixed on main realm they will change the thread tag to fidex?
