### ISSUE TITLE
Isle of Conquest Graveyards not working as intended

### ISSUE THREAD

**Issue by ZombieFreak115** [SunwellTracker/issues#3128]
Decription: 

In the "Isle of Conquest" BG graveyards don't work as intended. You get sent to a seemingly random graveyard when you die (even if the enemy has it, at that point you cannot ress and have to manually walk to another GY)

How it works: 
When you die, you spawn at a seemingly random graveyard (Which can arleady be under the controll of the enemy).

How it should work: ¨
When you die, you spawn at the closest graveyard relative from where you died, so if you died in the keep and your team has controll of said graveyard, you should spawn there.

Source (you should point out proofs of your report, please give us some source): 
How it worked on Angarthar, and in any other server that has IoC, and even in retail as nearly all GY's work this way (exception being SOTA)

**Comment by Dootz** [comment]
18/11/2020 - tested, respawned at nearest controlled graveyard.
