### ISSUE TITLE
[PvP Critical] Arena Rating

### ISSUE THREAD

**Issue by hablahabla21** [SunwellTracker/issues#3129]
Decription:
Sunwell arena ELO system doesn't work. 

How it works:
U can't lose more than -12 or -13 rating (im not sure) on sunwell and its ridiculous. People can play 20 arenas vs 1 team with 50/50 ratio + same rating and still both of them will gain +200 rating. 

How it should work:
Example of a match rating calculation:

Team A's Current Score: 1500pt
Team B's Current Score: 1580pt
Team A's Chance of Winning: 1 / (1+10(1580 - 1500)/400) = 0.38686
Team B's Chance of Winning: 1 / (1+10(1500 - 1580)/400) = 0.61314
Now Let's say Team A won the battle then
Team A's New Score: 1500 + 32*(1 - 0.38686) = 1500 + 19.62 = 1519.62
Team B's New Score: 1580 + 32*(0 - 0.61314) = 1580 + (-19.62) = 1560.38
Now Let's say Team B won the battle then
Team A's New Score: 1500 + 32*(0 - 0.38686) = 1500 + (-12.38) = 1487.62
Team B's New Score: 1580 + 32*(1 - 0.61314) = 1580 + 12.38 = 1592.38

Source (you should point out proofs of your report, please give us some source):
https://wowwiki.fandom.com/wiki/Arena_PvP_system
https://www.warcraftmovies.com/movieview.php?id=98583 1:28

**Comment by hablahabla21** [comment]
@Piootrek @Riztazz @lukaasm @Afgann

**Comment by hablahabla21** [comment]
bump
@Piootrek @Riztazz @lukaasm @Afgann

**Comment by hablahabla21** [comment]
@Piootrek @Riztazz @lukaasm @Afgann @Dootz

**Comment by hablahabla21** [comment]
@Piootrek @Riztazz @lukaasm @Afgann @Dootz cmon its easy to fix...

**Comment by Piootrek** [comment]
Fixed
