### ISSUE TITLE
Epic items drop too frequently

### ISSUE THREAD

**Issue by rookra** [SunwellTracker/issues#313]
Decription: rare and epic items drop way too frequently. I have been running instances while leveling today and have seen 5-6  Epics between level 30 and 40. 

How it works: epics drop too often

How it should work: drop less often. 

Source (you should point out proofs of your report, please give us some source):

**Comment by inscaped** [comment]
Shush, s'all fixed lul

**Comment by inscaped** [comment]
But seriously they said something like "it won't affect economy", so my guess it's intended. Which is a no-go for some people.

**Comment by inscaped** [comment]
Got some information that it's actually a bug related to the tables related to the core which is kinda hard to fix. Not sure how legit this information is, but it's all I got.
