### ISSUE TITLE
[Bugged quest] Terokkar Forest  – Can't finish the content

### ISSUE THREAD

**Issue by Maldamba** [SunwellTracker/issues#3131]
**Decription:** 

NPC Soolaveen may be bugged. He should give. "Recorev the bones" quest, which is a 1st part of a minor questchain. Therefore, we can make only 67/68 quest in Terrokar Forrest, which is unable to complete the content. 

https://wow.gamepedia.com/Recover_the_Bones

**How it works:** 
NPC is inactive (do not have "?" mark), and can't start the questchain

**How it should work:** 
Should give the Recover the Bones Q 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://www.wowhead.com/quest=10030/recover-the-bones#comments:id=25886

> By maracle (1,711 –  3·17)  on 2007/01/28 (Patch 2.0.6) |   |  
> This quest is not available until you complete "The Tomb of Lights" from High Priest Orglum. Thats a really weird prereq, probably not intended, but you must complete it first.

![obraz](https://user-images.githubusercontent.com/25490436/80526297-d29daa00-8992-11ea-86d8-23385e0ff7ab.png)

Hi,
you need to complete https://www.wowhead.com/quest=10840/the-tomb-of-lights first. Then he'll give you "Recover the Bones"
