### ISSUE TITLE
Bugged escort quest: [Escape from Coilskar Cistern]

### ISSUE THREAD

**Issue by zacke101** [SunwellTracker/issues#3132]
Decription: 
Escort quest. Works fine while accepting the quest, but when you complete the escort player do not get credit. Player is refered to "%N" during the roleplay so it does not recognise the players name. 

How it works: 
See above description.

How it should work: 
Should refer to the player by real name and give credit in the end.

Source (you should point out proofs of your report, please give us some source): 
Try out the quest on a toon. It wont give credit

**Comment by Dootz** [comment]
Hi,
where you the player who started quest? Or someone else started it?

**Comment by zacke101** [comment]
I started the quest. It was on my warlock Zaubolt.

tis 5 maj 2020 kl. 21:39 skrev Chris <notifications@github.com>:

**Comment by zacke101** [comment]
I see that the quest is fixed! Nice! When does this go live? Thanks
