### ISSUE TITLE
Stormchops occurs too many clearcasts

### ISSUE THREAD

**Issue by antiferal** [SunwellTracker/issues#3136]
Decription: 
Stormchops and Dragonbreath Chili occurs too many clearcasts on feral druid and ppl abuse that to dps increase.

How it works: 
Clearcasting is being procced by spell hits (ex. stormchops), while it should be spell casts only.
How it should work: 
Clearcasts should procc from spell casts not for spell hits. 

Source (you should point out proofs of your report, please give us some source): 
![cc](https://user-images.githubusercontent.com/64554017/80661556-46bd7800-8a8f-11ea-9788-c2c73591b2f1.png) with food
![bez stormow](https://user-images.githubusercontent.com/64554017/80662172-ea5b5800-8a90-11ea-9f37-bbb48f7d83d7.png) without food
Both screens are from following ID's encounter is the same with almost the same kill timer

**Comment by ganderxx** [comment]
As far as i know it does some stuff for other classes too not sure what, wowhead says something about stormchops proccing deepwounds on crits and maybe lightning shield on enh shaman? Another problem is that stormchops has no cd it should have a cd of 8 seconds https://www.wowhead.com/item=33866/stormchops#comments

**Comment by styxel** [comment]
Ive been doing alot of searching and shit when i was making my earlier bug/fix reports about ooc proccings, surely there was alot of wierd stuff that i found procs it but im clueless about this one, but im pretty sure there was a trinket for example that did damage on hit and it had a chance to proc ooc but im not 100% sure, surely stormchops is broken as its proccing its damage thingie without any cd so id say atleast fix that.  Dragonbreath chili seems very minor when i tested it (doesnt do damage often).

**Comment by darnias2** [comment]
This isssue doesn't come from Stormchops, but how Clearcasting itself works on this server. If you use Gift of the Wild and buff 25 players you will always get a clearcasting, because it checks how many targets you hit and not the 1 spell you casted so it's wrong in the first place on this server.

**Comment by ganderxx** [comment]
Thats actually how its supposed to be, got tons of sources To back it up

**Comment by styxel** [comment]
Omen of clarity does by the way proc form spell hit not cast? as it only procs when the spell has actually landed on the target? can be tested for example with wrath or something.

**Comment by eraghon98** [comment]
Hello, Omen of Clarity works like it should works. Stormchops should have GCD but not like 8 sec it was like 4, can't find source. AND PLEASE DO NOT TOUCH OOC please don't spoil/mess this talent, if u screw up this, feral spec would be useless. Tbh i was looking for reliable source about Stormchops and i can't find any info about GCD between tick's. And again don't screw up feral's dps,Thanks :)

**Comment by styxel** [comment]
theres a wowhead link https://www.wowhead.com/item=33866/stormchops#comments
most sources say its 8seconds and most videos ive seen show it proccing every 8 seconds so id say its 8seconds.

**Comment by Soufly** [comment]
https://www.wowhead.com/spell=43730/electrified / https://www.wowdb.com/spells/43730-electrified?itemLevel=55&itemSlot=0&playerLevel=120 .

**Comment by Soufly** [comment]
https://classic.wowhead.com/spell=15852/dragonbreath-chili , https://www.wowdb.com/spells/15852-dragonbreath-chili?itemLevel=35&itemSlot=0&playerLevel=120 , https://www.wowdb.com/spells/15851-dragonbreath-chili

**Comment by eraghon98** [comment]
Then fix CD to 8 sec on Stormchops and we are free to go :)

**Comment by Belpheris** [comment]
Please do not touch OCC at all. You will break it and I will have to reroll boomer.
I have a proposal how to deal with these bug abuses.
REMOVE Dragonbreath Chilli, Stormchops, and Immolation Oil from the game completely.
There is NO REASON to be using these in first place.
Remove them and everything will be fine.
Goodluck.

**Comment by Dkayzz** [comment]
@Belpheris that's an extremely poor solution. Also, no one is suggesting a change in OOC. They are simply suggesting to implement the missing ICD of Stormchops. OOC wouldn't be affected in any way.

**Comment by Belpheris** [comment]
Even if stormchops get's 8 sec cooldown it will still be > any other consumable as long as it procs Clearcasting. And how about Dragonbreath Chilli or Immolation Oil? Both proc CC aswell... 
Nerfing proc rate by giving it GCD isn't fixing the problem....

**Comment by Dkayzz** [comment]
The only relevant thing is whether the current state of said items is retail-like. Whether they are superior, useful, or  anything else is not really relevant.

**Comment by eraghon98** [comment]
> Even if stormchops get's 8 sec cooldown it will still be > any other consumable as long as it procs Clearcasting. And how about Dragonbreath Chilli or Immolation Oil? Both proc CC aswell...
> Nerfing proc rate by giving it GCD isn't fixing the problem....

it should be like  it was on retail, thats all :)

**Comment by styxel** [comment]
Just fix these items proccing Omen of clarity and then revert them If someone can actually find solid proof from logs etc, of them proccing it on retail. I played whole wotlk on retail never saw anyone using these, im sure there would be atleast some mention about this If it was a thing.

**Comment by antiferal** [comment]
just delete ferals dps they are useless anyway)))

**Comment by Chryslol** [comment]
Proccs Deep Wounds for warriors aswell. Make it 8 sec ICD would fix this but dno if it should procc clearcasting / deep wounds- seem weird.
