### ISSUE TITLE
21 DEF RATING GEM NOT WORKS - solved

### ISSUE THREAD

**Issue by nezblock** [SunwellTracker/issues#3139]
Decription: 
As title said.

How it works:  Its need to give 21 DEF rating. But not gives!

How it should work: Its need to give 21 DEF rating.

Source (you should point out proofs of your report, please give us some source): 
As u see in this video i dont get the 21 Def rating!
https://www.youtube.com/watch?v=aso9wDa3yno
As u see i change meta gem to 32 stamina and i get 32 stam and my def rating still at 542! Then i change back to 21 def rating and that i not get!
Pls reparir it!

**Comment by Platinumcoated** [comment]
https://github.com/SunwellTracker/issues/issues/2900

**Comment by nezblock** [comment]
> #2900

Ty
