### ISSUE TITLE
Chain Heal 

### ISSUE THREAD

**Issue by slav94** [SunwellTracker/issues#3142]
Decription: 
When i try to heal in raid with Chain Heal the spell is not jumping w

How it works: 
When Chein Heal is casted on targeth that is on max health not jump to other targeth 

How it should work: 
When u cast Chain Heal on target no matter the % health that it is spell jump on 3 (4 targets with gliph)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
18/11/2020 - tested, works correctly
