### ISSUE TITLE
[Isle of Conquest] - Dying as Alliance around the Hangar sends you to horde spirit healer

### ISSUE THREAD

**Issue by jpvd13** [SunwellTracker/issues#3150]
Decription: 
Dying at Hangar as Alliance sends you to horde spirit healer making you unable to ress and having to run to your faction's nearest spirit healer

How it works: 
When dying as Alliance around the Hangar you're sent to a HORDE spirit healer in the north eastern area of the map, forcing you to run to the nearest alliance spirit healer. If your team currently holds no bases, this is the spirit healer inside your home base which is unaccesible (cuz you can't use the telports as a ghost) unless your gates are down. 
You're doomed to roam the isle as a ghost... forever.

How it should work: 
When dying you should be sent to your faction's nearest spirit healer. 

Source (you should point out proofs of your report, please give us some source): 
Not sure how to prove this without recording it happen. If I end up in IoC again, I'll be sure to try and replicate this bug while recording it and edit post with a link to it

**Comment by Dootz** [comment]
Hi,
so far I was not able to reproduce this. Could you take a look at screenshot below. Was there anything different on map when this happened for you?
![obraz](https://user-images.githubusercontent.com/25490436/81113523-a8af2f00-8f20-11ea-94c0-ca0bf41a08cd.png)

**Comment by jpvd13** [comment]
From what I can remember, none of the assault points had yet been claimed by any faction. They were all "gray" or in the process of being captured. I, and 3 others, died on the top of the slope leading up to the Hangar from the Horde base and were sent to the north eastern horde spirit healer
