### ISSUE TITLE
view distance is a lot lower than what it should be

### ISSUE THREAD

**Issue by maikatiboklik** [SunwellTracker/issues#3154]
Decription: 
the range where u see players, npcs and stuff infront of u is way lower than original and other private servers. kinda ruins the whole gameplay... imagine not see the ppl fighting on the map in wsg or other bgs because of this. ive seen other servers INCREASE IT so u can see far far away, not lower it...

**Comment by Afgann** [comment]
It's currently needed because of high diff.
