### ISSUE TITLE
mobs in groups

### ISSUE THREAD

**Issue by maikatiboklik** [SunwellTracker/issues#3155]
Decription: 
when there are lets say 4-5 mobs in a group and when u attack 1 of them the others dont react. also when a low hp mob starts running away in fear he doesnt pull other mobs to help him.

How it should work: 
when u pull 1 mob of a group of few mobs, all of them should come. also low hp running away in fear mobs should be pulling other mobs to help them.

**Comment by Soufly** [comment]
Azathothh commented on Nov 26, 2019
''Chain pulling is currently disabled, as we are reworking it''

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/2978
