### ISSUE TITLE
[Hunter] Freezing Trap [PVP][PVE]

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#3159]
Bump for #993

This is not working in PVP at all, totally random with freezing trap who gets the trap.

**Comment by Soufly** [comment]
https://www.wowdb.com/spells/187650-freezing-trap - Should be 3 yards.

**Comment by Misery321** [comment]
Explosive trap is broken after the fix, can't be procced on Kologarn, can't be procced in melee range on ALL the other bosses in Ulduar. You need to stand on the tank to be able to get it to activate, Surv hunters got their biggest nerf yet.

**Comment by Misery321** [comment]
Same thing goes for Frost trap, the trigger range is too small, thought this fix was for a bigger radius of triggering trap not a smaller one. This is absurd.

**Comment by Chryslol** [comment]
Revert this change because there's no source that this is a bug. Explosive Trap range is broken right now. @Afgann @Azathothh 

Close the bug-report please.

**Comment by Afgann** [comment]
Fix was reverted yesterday, you really don't need to spam everywhere u can, it will work properly after update.
