### ISSUE TITLE
Warlock, conflagrate 

### ISSUE THREAD

**Issue by Thebigboy666** [SunwellTracker/issues#3164]
Decription: i cant immolation and i have 1-2 sec delay to my conflagrate is active and i can use just after this, normaly its work i can cast instant my conf 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/3083

**Comment by Thebigboy666** [comment]
Won't Fix?xD so i need play pvp with bug? wtfXD

**Comment by Afgann** [comment]
That's not my decision, i'm just being consistent with previous replies to this issue.

**Comment by Thebigboy666** [comment]
and what is this issue? why i get this 1-2 sec delay to can use? need creating video or what?D:

**Comment by Afgann** [comment]
Read previous report if you want to know more.
