### ISSUE TITLE
[Combat drop issues] In PvP, You can drop combat when you're healing or buffing.

### ISSUE THREAD

**Issue by Nekzington** [SunwellTracker/issues#3166]
Decription: 

So, when your mate is doing dmg on another player, u heal him and if u keep healing you'll drop combat. (5.5secondes)
How it works: 

Combat timer not reseting on every spells
How it should work: 

everytime u buff or heal someone in combat, the combat timer should be reset (it means u should stay in combat 5.5 sec everytime u buff or heal someone in combat)

Source (you should point out proofs of your report, please give us some source): 
every single pvp video from healer pov : 
https://www.warcraftmovies.com/fr/movieview.php?id=183377
(look first game 50sec, you can see hes not droping combat by just healing his rogue after cs)

**Comment by Azathothh** [comment]
Confirmed, easy to reproduce:
0:00 - cast heal on target in pvp combat
0:04 - cast another heal
0:06 - combat from healer drops, while it should stay until ~0:10
