### ISSUE TITLE
[Vanish] Rogue

### ISSUE THREAD

**Issue by Nekzington** [SunwellTracker/issues#3168]
Decription: 
When you vanish, people cant see you etc

How it works: 
The problem is : When you slow or root a rogue JUST after a vanish he's not slow or root, he can just keep running.

How it should work: 
When you use nova or slow on a rogue just after vanish, it should just work. If you use nova after his vanish, he is root and thats all.

Source (you should point out proofs of your report, please give us some source): 
https://www.warcraftmovies.com/movieview.php?id=157699 at 2:25 u can see rogue using vanish, then the mage use Cone of Cold and the rogue is SLOW

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/3146
