### ISSUE TITLE
suka warlocka

### ISSUE THREAD

**Issue by groszkowa** [SunwellTracker/issues#317]
Decription: no nie wiem co tu napisać, mojemu koledze z którym gram areny suka raz działa raz nie, nie mamy pojęcia czym to może być spowodowane.

Tutaj są macra z których korzysta mój kolega warlock. Zaznaczam jeszcze raz że ona raz działa a raz nie. Więc wykluczamy błędne macro.

#showtooltip
/cast [target=focus] Spell Lock
/cast [target=focus] Seduction
/cast [target=focus] Intercept(Rank 4)

-------------------------------------------

#showtooltip
/cast Seduction
/cast Spell Lock

How it works:  suka zamiast dać seduction to się kręci 180 stopni raz w lewo raz w prawo xD

How it should work: powinna dać seduction priestowi zamiast się kręcić

Source (you should point out proofs of your report, please give us some source): 
dowodem jest tu mój filmik 
https://youtu.be/zapEJmzb7gE?t=41m14s 
tak jak w linku od 41minuty 14sekundy, stoje obok suki i widać to perfekcyjnie. Jak ktoś ma wątpliwości proszę spowolnić film.

**Comment by sitowsky** [comment]
Źródło nie zawiera konkretnych informacji. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
