### ISSUE TITLE
[Inner Focus] spell display does not show it goes on CD

### ISSUE THREAD

**Issue by nalgenelol** [SunwellTracker/issues#3172]
Decription:  After casting Inner Focus and then cast priest spell , I noticed that the spell went on CD as expected, but the icon display does not say so. It will still display it as though it is already off CD but not usable.

How it works: 

How it should work: Icon should show that it is on CD after the buff has been consumed.

Source (you should point out proofs of your report, please give us some source):

**Comment by nalgenelol** [comment]
also noticed that it is only an issue when i bind Inner Focus to "shift - mouse scroll down" . It is working properly if I manually click the spell.

**Comment by LeDivinBueno** [comment]
Hello, I got the same bug with Nature's Swiftness, and now thay you say this, it's also bind on "shift - mouse scroll (up)"

**Comment by Semper-Numquam** [comment]
Same bug with Elemental Mastery, usually when you use another spell too fast after use EM.
