### ISSUE TITLE
Items unequiped by server on login, can't equip them again.

### ISSUE THREAD

**Issue by tubefrede** [SunwellTracker/issues#3174]
Decription: 
So i logged on my paladin the other day and got a mail saying that the following items had a problem being equiped  [Gauntlets of Dragon Wrath] & [Bands of the Stoneforge] and so they had been sent via mail to me. Be aware that before logging out previuosly the items were indeed equiped. Now however when i try to equip them it says that i can't equip more than 1 of those items even though nothing or something else is equiped (Yes i can still equip other gear in the hands and wrist slots, just not the gear that was unequiped by the server and sent to me via mail)

Image for  [Gauntlets of Dragon Wrath]
![image](https://user-images.githubusercontent.com/65162652/81548787-212d4a00-937e-11ea-8b1d-179802fe9420.png)

Image for [Bands of the Stoneforge]
![image](https://user-images.githubusercontent.com/65162652/81548939-520d7f00-937e-11ea-98fc-7e6381b09b19.png)

As you can see my Paladins name is Kisser and i play on frosthold. 

I hope you can help me or at least prevent other people from "losing" their items.

All the best

Kisser

**Comment by Rosenkrantz** [comment]
Is this +4 all stats gem "unique" or "unique-equipped"? If yes, then make sure you have only one between all sockets.

**Comment by tubefrede** [comment]
I feel like an idiot now. Thanks a bunch Rosenkrantz you are a lovely person.
