### ISSUE TITLE
[Krytyczny] Food, a combat

### ISSUE THREAD

**Issue by Danieloses** [SunwellTracker/issues#318]
Decription: ? https://www.youtube.com/watch?v=ZFiT8tpWSVs&t=104s 1:25

How it works:  Food przestaje regać hp, gdy gracz jest w combacie.

How it should work: Nie powinien przestawać regać hp w combacie.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
Źródło nie zawiera konkretnych informacji. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
