### ISSUE TITLE
Cenarion Beacon

### ISSUE THREAD

**Issue by eraghon98** [SunwellTracker/issues#3182]
Decription: 

After finished quest Cleansing Felwood (https://classic.wowhead.com/quest=4101/cleansing-felwood) you should get item called: Cenarion Beacon from NPC after talk with him.
How it works: 
I can't get item called: Cenarion Beacon.

How it should work: 
I should get item called: Cenarion Beacon.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=WOGEBhujjAo  SKIP TO 3:05 
https://classic.wowhead.com/npc=9528/arathandris-silversky

**Comment by Dootz** [comment]
Hi, are you sure you don't have it already in bags or in bank? Seems to be working correctly, at least for me.

**Comment by eraghon98** [comment]
Hello yes im sure i dont have it in bag/bank i was talking with GM right after found this bug.
