### ISSUE TITLE
Gnomish Death Ray

### ISSUE THREAD

**Issue by danniellos94** [SunwellTracker/issues#3184]
Decription: 
https://imgur.com/a/P6Bevqh

How it works: 

https://imgur.com/a/P6Bevqh
How it should work: 
https://imgur.com/a/P6Bevqh

Source (you should point out proofs of your report, please give us some source):

**Comment by Chaoslord69** [comment]
can't see anything on the pics

**Comment by danniellos94** [comment]
1. It does 569 damage to non armor lvl 1 critter GM can easily test that
2. On the pic you have link to retaol wow video where player is hitting ppl with armor for 3k crit.
