### ISSUE TITLE
Frostbrood Sentry - Icecrown hitting too hard

### ISSUE THREAD

**Issue by Scorpz91** [SunwellTracker/issues#3185]
Description: Frostbrood Sentry  -  Flying creature in Icecrown currently casts Bitter Blast and it hits for around 13k, i resist around 3k.

How it works: Creature casts Bitter blast and hits for 13k

How it should work: https://db.darkwizard.pl/?spell=46406 - Bitter Blast is meant to hit for around 800 damage not 8000

Source (you should point out proofs of your report, please give us some source): 

Bitter Blast - 45 yd range 1 sec cast 

Deals 829 to 871 Frost damage to the target.

**Comment by Soufly** [comment]
True,they 2 shot u.

**Comment by Azathothh** [comment]
You've linked spell from some other npc.
They are using this one https://db.darkwizard.pl/?spell=60542 and afaik they should hit that much.
