### ISSUE TITLE
BootyBay Buisers

### ISSUE THREAD

**Issue by rzabaa** [SunwellTracker/issues#3196]
Decription: BB Bruisers  are not  attackable after ticking "At war", sometimes cant attack them even if i kill player in BB and they aggro on me. They nameplates are always green. When trying to attack them, game says "Invalid Target"

How it works: Cant attack BB Bruisers after ticking at war, cant always attack them when they aggro on me

How it should work: Bruisers should be attackable after ticking "At war", Bruisers should be attackable when they attack player, even if "At war" is NOT ticked.

Source (you should point out proofs of your report, please give us some source): I spotted it when i was trying to grind rep for Bloodsails 
https://imgur.com/a/SmOz4Oo

**Comment by neverson42** [comment]
Clear your cache. I had the same problem. That fixed it.

**Comment by rzabaa** [comment]
Doesent help.

**Comment by Dootz** [comment]
This should be fixed after https://github.com/SunwellTracker/issues/issues/3265
