### ISSUE TITLE
Quest Reclaimed Treasures

### ISSUE THREAD

**Issue by MarekFish93** [SunwellTracker/issues#3199]
Decription: 
In this quest i should take some treasured from chest. I cannot open that chest, cannot even click on it.

How it works: 
Cannot click on a chest, there is no response. 

How it should work: 
I should just open it.
![screenBugWow](https://user-images.githubusercontent.com/23642948/82239999-f3c23c80-9939-11ea-8a25-0bee666b0ed3.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,

that's a wrong chest :) See this one https://youtu.be/GesXATj6-lg?t=161 from what I can see it works without issue.

**Comment by MarekFish93** [comment]
Yeap, u are right. I am sorry :(
