### ISSUE TITLE
[Hunter][Quest][Azymuth Isle] Complete class quests with tamed beast died

### ISSUE THREAD

**Issue by malins2000** [SunwellTracker/issues#32]
Decription: 
One can complte hunter class quest chain with target beast tamed and died afterwards 

How it works: 
When one start class quest, player is asked to tame beast and return it to NPC. After taming done OK, my pets died in battle. I could complete quest despite that. I don't have to have tamed beast following me.

How it should work: 
Quest should be completable only when tamed beast is near NPC. 

Source (you should point out proofs of your report, please give us some source): Self expiriance. didn't took screenshots though..

**Comment by Kokaina** [comment]
https://www.youtube.com/watch?v=ug6fMDyy-mI
5:50 looks like he got credit after tame spell finished, not when he arrived with pet to NPC
