### ISSUE TITLE
The Oculus Heroic Dungeon Loot [Cache of the Ley-Guardian]

### ISSUE THREAD

**Issue by sth666** [SunwellTracker/issues#3200]
Decription: THE OCULUS HEROIC 5man.

How it works: After Kill Last Boss on Oculus Heroic, will spawn there **Cache of Eregos**, it's work fine, but Inside of Cache didn't drop **Cache of the Ley-Guardian.**
For example : 
I join queue Random Dungeons (hopefully 1st of Random gonna be Oculus), All people on Party didn't leave or We didn't kicked any person from Party. After killed Last Boss, Chest Spawn Fine, but when We opened, Bag with Gems still not there, I try to do it lots of Times, by I never see Bag with Gems. 

How it should work: After kill last Boss on Oculus Heroic, will also drop **Cache of the Ley-Guardian.** 

**Of course just if you join queue on Random Heroics, when You use "Specific Dungeon" it's didn't never dropped.**

Source (you should point out proofs of your report, please give us some source): 

I asking GMs at Ticket on Game few month's ago, before Ulduar Release, and them answer Me : 
 Bag with Gems gonna be drop from **Cache of Eregos** after Ulduar Release, but still not dropped.

![PhotoGrid_1589882290869](https://user-images.githubusercontent.com/45474717/82315115-bce43900-99c2-11ea-917d-486836e9c65b.jpg)

**Comment by Chryslol** [comment]
3.2 my friend, we are on 3.1 atm.

**Comment by Azathothh** [comment]
It's not this content - will be added in future
