### ISSUE TITLE
Combat bug rogues abuse it in arena

### ISSUE THREAD

**Issue by syfe34** [SunwellTracker/issues#3203]
Decription: 
Healing/buffing/dispeling on a player who is in combat doesnt give you combat.

How it works: 
In arenas i dont get combat when im spam healing my partner, who is killing the enemy. Rogues abuse this bug and sap midgame while im casting heals/dispeling/buffing my partner who is in combat. The only way i can get combat is dispel/dmg the enemy, or if they kill me. but for example with holypaladin if i judgement and then just healing/rebuffing/dispeling my partner who still has combat my character just leave combat after 8 sec.

How it should work: 
If u heal/buff/dispel someone who is in combat, you should get combat too.

Source (you should point out proofs of your report, please give us some source): 
I dont think this needs any proofs... just watch a 3.3.5 pvp video vs rogues...

**Comment by Nekzington** [comment]
already reported, gm said "fixed"

in pvp u cant get in combat from healing or buffing.
