### ISSUE TITLE
[Death Knight] Ebon Gargoyle

### ISSUE THREAD

**Issue by elbastardonegro** [SunwellTracker/issues#3206]
Decription: Ebon Gargoyle prioritizes melee over casting Gargoyle Strike when summoned in melee range.

How it works: Gargoyle melees disrupting it's Gargoyle Strike casts. See: https://imgur.com/a/pJsJzx7 , upper screenshot. It has a disproportionate amount of melee swings vs gargoyle strike casts. Lower screenshot depicts the amount of gargoyle strikes for a gargoyle summoned outside of melee range.

How it should work: The Gargoyle should prioritise using Gargoyle Strike over melee, and should have a noticeably smaller amount of melee swings per summon even if summoned in melee range. 

Source (you should point out proofs of your report, please give us some source): This is difficult, but there's this https://www.wowhead.com/forums&topic=133584 discussion from 2009 about gargoyle haste scaling in which performed tests point to a much lower amount of melee swings per casts (1 melee swing, 12 casts). There is also examples such as http://www.worldoflogs.com/reports/llBbOtAfG9NDeIFo/details/42/?s=2596&e=2832 where you can see a gargoyle summoned by a death knight with higher haste (possibly including bloodlust and unholy presence and a haste potion?) having 16 gargoyle strike casts and 3 melee swings. The gargoyle was cast only once, as it's active time is 26.7s (the gargoyle stays up for 30s, so including arrival and departure and possible movement that's roughly the active time you'd expect).

**Comment by KrolServera** [comment]
When can we expect this to be fixed?

**Comment by KrolServera** [comment]
@Afgann can u make it into live server please?
