### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by Hawkxnight** [SunwellTracker/issues#3208]
Decription: 
The Quest "NO REST FOR THE WICKED" in IC - WOTLK bugs

How it works: 
normally you have to loot 4 chest. But only 3 chest can be looted atm. The 4th chest (when u enter the roam the rear left one) can't be looted. You can't interact with this chest.

How it should work: 
normally this chest should be lootable and give you the 4th quest item

Source (you should point out proofs of your report, please give us some source): 
Quest discription

**Comment by Dootz** [comment]
Hi. Are you sure you are using correct chest? On screenshot below you should use chest on the left. https://youtu.be/UhVzJWwnGIs?t=92
![obraz](https://user-images.githubusercontent.com/25490436/82840358-83d02b00-9ed2-11ea-89cb-983119869798.png)
