### ISSUE TITLE
NPC hitting way too much bug. 

### ISSUE THREAD

**Issue by 1amabove** [SunwellTracker/issues#3210]
Decription: The NPC's named Gargoyle Ambusher in WoW hit for around 7.8k with Gargoyle Ambusher Strike which is a very fast cast.

How it works: The npc's hit too much with that spell.

How it should work: They shouldn't hit that much? D:

Source (you should point out proofs of your report, please give us some source): 
I've attached a pic with my combat log and also one with the map to show the location of the npc's.

Also, I managed to find this: http://wotlk.cavernoftime.com/npc=32188

![Bug1](https://user-images.githubusercontent.com/65826984/82737600-6fedc300-9d32-11ea-82af-9056b1c377d2.png)
![Bug2](https://user-images.githubusercontent.com/65826984/82737606-74b27700-9d32-11ea-9cba-3815509765f3.png)

**Comment by Soufly** [comment]
https://www.wowhead.com/npc=32769/gargoyle-ambusher#comments

1 | ziddy1232 on 2009/08/18 (Patch 3.2.0)I did, got hit twice, 7k and 6k. That hurts on 15k HP.
-- | --

**Comment by Dootz** [comment]
Hi, yeah it should :) Thanks Soufly.
