### ISSUE TITLE
Swift Flight Form not getting the 310% fly speed.

### ISSUE THREAD

**Issue by DiversionRoute** [SunwellTracker/issues#3215]
**Decription**:  Swift Flight Form for Druids should change once you acquire a 310% mount to the same speed.

**How it works**: 
Currently it dose not "upgrade" the Flight Form speed once you acquire a 310% mount.

**How it should work**: 
It **SHOULD** "upgrade" your speed once you have a 310% mount.

"_Patch 3.2.0 (04-Aug-2009): The level requirement for this skill has been increased to level 71. Flight Form and Swift Flight Form now benefit from a paladin's Crusader Aura. Druids who have acquired a mount able to go 310% flight speed will now also go that speed while in this form._"

**Note**: Currently Crusader aura works with flight form, so that leads me to believe that the 310% "upgrade" should be implemented as well.

**Source (you should point out proofs of your report, please give us some source)**: 

https://wowwiki.fandom.com/wiki/Swift_Flight_Form

- See patch changes

**Comment by Azathothh** [comment]
That's exactly how it works, right now
![obraz](https://user-images.githubusercontent.com/37483678/82933842-dd942c00-9f8a-11ea-9138-eb3716ed8701.png)
If it doesn't work for you then probably you don't have 310% mount or you're checking it incorrectly

**Comment by DiversionRoute** [comment]
![20200526194439734](https://user-images.githubusercontent.com/24257578/82943802-767e7380-9f9a-11ea-8bf4-746842a60427.png)
![20200526194514145](https://user-images.githubusercontent.com/24257578/82943809-77afa080-9f9a-11ea-8491-cd60e56080d7.png)

The Rusted Proto-Drake's tooltip say 310% speed, but my Flight Form tooltip still say 280%, so something is wrong then.

Also what addon do you use to track the speed?

**Comment by Azathothh** [comment]
Addon is carbonite, but you don't need any addon, you can just use macro like: 
/run print((GetUnitSpeed("target")/0.07).."%")    (in this one you must have yourself on target)

Tooltip will always show 280% - it's same with buffs that have increased values for example by talents (like BoM with talent) - their tooltips will always show base value, because that's how wotlk client is made
