### ISSUE TITLE
1 DK per realm??? GM from Frosthold sent me here

### ISSUE THREAD

**Issue by kizito17** [SunwellTracker/issues#3216]
Decription: 
I wanted to create second DK on my acc, and game says that i can have only 1 dk per realm?
How it works: 
1 dk per realm
How it should work: 
As many as player want dk's per realm 

![Bug](https://user-images.githubusercontent.com/65923548/82842447-d4975200-9ed9-11ea-9348-22305c939d6d.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
If gm sent you here, i'm sure he also asked you to provide some proofs that it should be like you're writing.

https://wowwiki.fandom.com/wiki/Death_Knight
"Before Patch 5.3.0, players could only create one death knight per realm, so long as they had a level 55 character already"
