### ISSUE TITLE
[Black rock - jenkins] - powtarzalne DC

### ISSUE THREAD

**Issue by leman1991** [SunwellTracker/issues#322]
Decription: 
Podczas boostowania na smoczkach od tytułu "Jenkins" można przypadkiem powodować DC osób w instancji.
W celu powtórzenia problemu należy: pullnąć całą salę smoczków -> Mage Frost rzuca blizzard, DK rzuca D&D -> w ciągu 5 sec mamy oboje DC. Dzieje się tak tylko w połączeniu Imp. Blizzardu z Death and Decay'em. Flamestrike i inne skille dc nie wywołują.

How it works: 
Rozłącza i wyrzuca na cmentarz

How it should work: 
Nie wyrzucać?

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Skontaktuj się ze mną na discordzie/forum, potrzeba więcej informacji.
