### ISSUE TITLE
Auriaya - "Crazy cat lady" achievement.

### ISSUE THREAD

**Issue by Fixetza** [SunwellTracker/issues#3236]
Decription:  Currently it is possible to use a Blue Crashin' Thrashin' Racer Controller [https://wotlk.evowow.com/?item=54343](url) or any other of those for that matter, to pull Auriaya without pulling the cats that accompany her, resulting in people getting the "Crazy cat lady" achievement. It has been going on for 2 weeks now.

How it works: Summon a Blue Crashin' Trashin' Racer and just go up to Auriaya - the boss comes to the raid group without the cats.

How it should work: Pulling Auriaya should pull her cats as well.

Source (you should point out proofs of your report, please give us some source):

**Comment by Nostaglicdude** [comment]
I recall that it did work back in retail WOTLK as well. And blizzard did nothing about it. But maybe I am wrong as it was so long time ago. Just letting you know what I thought
