### ISSUE TITLE
drums of forgotten kings

### ISSUE THREAD

**Issue by matkes48** [SunwellTracker/issues#3237]
Decription: 
when you use drums of forgotten gings from LW (8% to all stats) it wont give you any stats if blessing of sanctuary is present on you. 

How it works: 
blessing of sanctuary = drums are totally useless

How it should work: 
blessing of sanctuary pressent, the drums still should give you 8% intellect and agi and spirit

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,

they shoud not stack. Do you have any sources to confirm that they should? See some examples below.

https://www.wowhead.com/item=49633/drums-of-forgotten-kings#comments:id=848830
https://wowwiki.fandom.com/wiki/Drums_of_Forgotten_Kings
https://github.com/TrinityCore/TrinityCore/issues/768
https://wowwiki.fandom.com/wiki/Greater_Blessing_of_Kings

Thanks
