### ISSUE TITLE
[Instance][Halls of Stone] Unable to Resurrect players

### ISSUE THREAD

**Issue by whitestar87** [SunwellTracker/issues#324]
Decription: 
Players who die in halls of stone are not resurrectable.

How it works: 
Players attempting to resurrect a dead target get the message "Target cannot be resurrected"

How it should work: 
Should be able to rez players when out of combat

Source (you should point out proofs of your report, please give us some source):

**Comment by Netherfrost** [comment]
Can confirm

**Comment by Riztazz** [comment]
Issue will be resolved with next update.
