### ISSUE TITLE
Mimiron 25 Hard Mode [Ulduar] not nerfed properly

### ISSUE THREAD

**Issue by ClassicMage** [SunwellTracker/issues#3240]
Hello,
it's been almost 2 weeks after Ulduar nerf, but Mimiron 25 HM is still on its pre-nerf state.
- Boss Parts still got +30% Health bonus instead of 25%
- Assault Bots still got around 820k HP instead of around 630k HP
- I think Defeaning Siren ability (cast by Emergency Fire Bot at phase 3) still got too much range (it should be 10 yards after nerf, now it propably got 20 yards)
- Propably some hit values from boss/assault bots should be nerfed too, but cannot confirm if it was or was not nerfed in May.

Hope to see a nerfed ecounter next ID, cheers.

**Comment by Nostaglicdude** [comment]
Did Mimiron 25 HM again and again and it is in post-nerf state. It has been fixed already.
