### ISSUE TITLE
Quest "Trial of the sea lion" - inactive container with half pendant

### ISSUE THREAD

**Issue by heracro** [SunwellTracker/issues#3245]
Decription: 
Container with Half pendant of Aquatic Agility is inactive, thus object can't be looted and quest completed.

How it works: 
Container is inactive

How it should work: 
As on this video:
https://classic.wowhead.com/item=15883/half-pendant-of-aquatic-agility#videos:id=166534

Source (you should point out proofs of your report, please give us some source): Repro steps:
1. Enter game with Druid on at least level 16
2. Follow quests in chain starting with A Lesson To Learn https://classic.wowhead.com/quest=27/a-lesson-to-learn
3. When Trial of the Sea Lion is triggered, go to 56,8 (Sludge Fen) in the Barrens and try to pick quest item from container laying on the bottom of the pond.

Other information: this usually means the other half pendant is also inactive. Please check both.
https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance

**Comment by Dootz** [comment]
Hi, it will be interactable after +/- 15 minutes. Fix will be applied so that it's interactable when object spawns. Thanks.
