### ISSUE TITLE
drums of forgotten kings stacks with kings

### ISSUE THREAD

**Issue by herbhenk** [SunwellTracker/issues#3246]
Decription: 
the buff from the drums of forgotten kings seems to stack with the paladin buff blessing of kings

How it works: 
when u have the paladin buff blessing of kings it stacks with the drums of the forgotten kings buff

How it should work: 
the buff from the drums of forgotten kings should not be able to stack with the paladin buff blessing of kings

Source (you should point out proofs of your report, please give us some source): 
<img width="467" alt="kingss" src="https://user-images.githubusercontent.com/64539747/84426076-edff0480-ac22-11ea-992d-c960a28e6791.png">

**Comment by Soufly** [comment]
Visual bug only.
