### ISSUE TITLE
Game telling you to type in /afk to stay in the game even if you are not afk

### ISSUE THREAD

**Issue by badlypayedgoon** [SunwellTracker/issues#3247]
Decription: 
Players can mark other players as afk which triggers a message to type in /afk to stay in the battleground. If you follow that order when you are not even afk, it instantly kicks you out of the bg and you get the deserter debuff

How it should work: 

Replace the "type /afk to stay in the battleground" to something more akin to "participate in the battleground to avoid getting kicked out" so that people don't get tricked into kicking themselves out by other players.

Source (you should point out proofs of your report, please give us some source): 
![zjtzjzkkuk](https://user-images.githubusercontent.com/51803986/84588475-0429e200-ae28-11ea-996e-cb0928280fa1.PNG)

**Comment by Cwiercpasiec** [comment]
Well, apparently Dessita trolled you. He simply typed "/e has marked you as AFK. Type /afk to stay in the battleground." and you fell for that. Guess you didn't know you can write in orange this way, did you?
