### ISSUE TITLE
Titanium Ore can't be prospected

### ISSUE THREAD

**Issue by Krusty47** [SunwellTracker/issues#325]
Decription: Titanium Ore currently cannot be prospected, despite being labeled "Prospectable" on mouseover.

How it works: When attempting to prospect Titanium Ore, you get a "There are no gems in this" message.

How it should work: Titanium Ore should most certainly be prospectable, as it is the only way to obtain Titanium Powder, used to purchase Jewelcrafting tokens in Dalaran.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=46849/titanium-powder#comments

**Comment by Kokaina** [comment]
It's because be have 3.0 content and Prospecting worked on Titanium Ore since 3.2 content.
