### ISSUE TITLE
[Icebound fortitude] dont work right +  hit through wall

### ISSUE THREAD

**Issue by XMATER** [SunwellTracker/issues#3253]
Decription:  Icebound Fortitude dont work properly, also we can hit another throught wall

How it works: actully i can gouge a dk who have the Icebound fortitude popped, also i can hit some1 thought the wall

How it should work:  Dk should be inmune to ALL stuns, and gouge is a stun, and u should't be ablo to hit another trought wall

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/66057698/84605846-ecdb0b00-aea0-11ea-8651-3cb7ed35d238.png) 
![image](https://user-images.githubusercontent.com/66057698/84605864-0a0fd980-aea1-11ea-92b6-8b8e559af746.png)
 
Video about this https://youtu.be/iYobUWwmF8o

**Comment by Cwiercpasiec** [comment]
https://wowwiki.fandom.com/wiki/Gouge
https://wowwiki.fandom.com/wiki/Incapacitate
Gouge is not a stun, it is Incapacitate, which diifers a bit from a stun (for example, you do not become immune to Incapacitate while under the effect of Icebound Fortitude).

**Comment by Azathothh** [comment]
Like mentioned above, Gouge is NOT a stun, and Icebound Fortitude shouldn't grant immunity for it
