### ISSUE TITLE
Ulduar 10 - keepers activating themselves

### ISSUE THREAD

**Issue by Boitab** [SunwellTracker/issues#3256]
Description: 

Hello I did Ulduar 10 today and we tried to do Yogg 1 keeper. I only activated Thorim and when we pulled we noticed that all keepers were present. We wiped so I came back to Shattered  Walkway to check if someone else did activated all keepers but to my surprise all 4 keepers were still up, even  Thorim that I manually activated few minutes ago. So I went back to Thorim again and talked to him to activate him (it seemed to worked because one more time he dissapeared from the Walkway). On second pull, all keepers were still activated.

How it should work: 

Keepers should show up during Yogg only if you activated them, which wasn't the case.

**Comment by Dootz** [comment]
Hi,

if ever encounter such issue again please open an in-game ticket. We may be able to help you there.

Thanks.
