### ISSUE TITLE
cc break absorb

### ISSUE THREAD

**Issue by Nekzington** [SunwellTracker/issues#3258]
Decription: if someone is sap or blind, if you hit him EVEN if he have a shield, cc should break.

How it works:  sap with shield, hit the sap, sap doesnt break.

How it should work: sap with shield, hit the sap, sap is break.

Source (you should point out proofs of your report, please give us some source): everywhere every videos

**Comment by Soufly** [comment]
https://github.com/SunwellTracker/issues/issues/2997

**Comment by Rosenkrantz** [comment]
Also, as for today, prowl doesn't break from blizzard if druid has an absorb.
