### ISSUE TITLE
Holy Wrath [paladin spell]

### ISSUE THREAD

**Issue by misteee** [SunwellTracker/issues#326]
Decription: 
The paladin spell "Holy Wrath" is not working as intended.

How it works: 
The spell reads: *Sends bolts of holy power in all directions, causing X Holy damage and stunning all Undead and Demon targets within 10 yds for 3 sec.*
Right now the spell doesn't damage any mobs that aren't Undead or Demon.

How it should work: 
It should damage all mobs, but stun only Undead and Demon mobs.

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2857
