### ISSUE TITLE
Shutting Down Manaforge B'naar [10329] - Unable to Complete

### ISSUE THREAD

**Issue by Baelek** [SunwellTracker/issues#3260]
Description: I am unable to have the emergency shutdown successfully complete.

How it works: Sunfury Technicians run into the room. Even if killed before they touch the mana forge, the shutdown is aborted, and the quest cannot be completed. Since only one should spawn at a time, this isn't an issue of another sneaking in to shut it down.

How it should work: Sunfury Technicians should run in to stop the sequence. If left undisturbed for a bit of time, the emergency sequence will abort. If killed, then the emergency shutdown sequence continues until it's shut down.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/quest=10329/shutting-down-manaforge-bnaar#comments

**Comment by Dootz** [comment]
Hi,

I just tested in and it seems to be working correctly. Technicians will spawn, run to manaforge and after few seconds they will start casting spell to interruptus "shutting down" procedure.  How did it look from your perspective? It just stopped and you were able to start it again?

Thanks
