### ISSUE TITLE
Heroism emblem's trincket (The egg of mortal essence) not working for disco priest

### ISSUE THREAD

**Issue by Delania** [SunwellTracker/issues#3262]
Decription: 
this trincket never prcs even after testing all my healing spells and when i say all it's all even holly nova and Divine hymn i've tried it many times and not working

How it works: 
not working, never procs for me

How it should work: 
using direct healing and heal over time grants 505 haste rating for 10 sec

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
It procs on HoT ticks!
It procs on direct heals.
It will proc regardless of who the heal is on.
It does NOT proc on HoT ticks that were 100% overheal, but direct heal overheals can still proc it.
As an exception to the above, the bloom from Lifebloom cannot proc it on an overheal, despite the overheal appearing in the combat log like a direct heal (unlike HoT ticks).

**Comment by Delania** [comment]
I'll let u see by urself : 
My priest : https://www.transfernow.net/4NTPzu062020 
My friend's priest : https://www.transfernow.net/qjJedw062020 
as u can see in his toon it was overhealing and on mine i used all healing spells without overhealing and no procs...

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/3259
