### ISSUE TITLE
Booty Bay Bruisers #2

### ISSUE THREAD

**Issue by rzabaa** [SunwellTracker/issues#3265]
Decription: Farming Bloodsail rep is pain in ass. BB NPCs work really wierd, definitly not how they should. Checked it out from 3 accounts and different PC's so its not issue with my client. Clearing cache and WTF as You reccomended on last report doesnt work. Hard to describe, check it on Your own or I can stream on discord.

How it works: 
Pulling one NPC: easy pull, easy kill and rep but evey other NPCs become unattackable, have to /reload or untick and tick "at war"to continue grinding. Painful.
Pulling more than one NPC: easy pull, after killing one of pulled NPC's other lose threat and become unattackable, have to /reload or untick and tick "at war"to continue grinding. Painful.
Pulling guards by killing player in BB: bruisers dont lose threat after killing one of them, they just become unattackable. Have to die to continue grinding. 

How it should work: NPC's should always be attackable after ticking "at war" without these wierd effects.

Source (you should point out proofs of your report, please give us some source): I spotted it when i was trying to grind rep for Bloodsails
https://imgur.com/a/SmOz4Oo
i can stream it on discord

**Comment by Dootz** [comment]
> Pulling more than one NPC: easy pull, after killing one of pulled NPC's other lose threat and become unattackable, have to /reload or untick and tick "at war"to continue grinding. Painful.

This part should be fixed after next update.
