### ISSUE TITLE
Tears of Bitter Anguish

### ISSUE THREAD

**Issue by Klakocik** [SunwellTracker/issues#3267]
Decription: 
At the moment it is impossible to have 2 Tears of Bitter Anguish (Binds when Equipped item)
I have dropped two within five minutes. I could not pick up second one, while still having one in backpack. Corspe with loot disappeared before i could pass one i already had to another person. Corpse disappeared after about 30 seconds, while i was still looting it (as shown in screenshot).

How it works: 
It is "Unique", you can't have two at the time.

How it should work: 
It should be "Unique-Equipped".

Source (you should point out proofs of your report, please give us some source): 
Here You can see that I already have one in equipment and can't pick up second one: 
https://i.imgur.com/UBYEIZV.jpg

https://i.imgur.com/0C2Y0mX.png

**Comment by Soufly** [comment]
https://wowwiki.fandom.com/wiki/Unique - nope
