### ISSUE TITLE
[The Occulus] Bug when dying when falling off of platforms

### ISSUE THREAD

**Issue by UFJ** [SunwellTracker/issues#327]
Decription:  When I died from falling off a platform, I was not sent to the proper graveyard. I was sent to the gravyard in Dalaran(the place where I queued RDF from) instead of the graveyard nearest to the Occulus instance.

How it works:  I was sent to the wrong graveyard while dying in the occulus.

How it should work: I should have been sent to the graveyard nearest to the instance.

**Comment by Kokaina** [comment]
Fixed.

**Comment by Riztazz** [comment]
Not yet

**Comment by Riztazz** [comment]
Resolved
