### ISSUE TITLE
[PvP] WG First Lieutenant Ally BUG

### ISSUE THREAD

**Issue by ntwrksx** [SunwellTracker/issues#3270]
Decription: --

How it works: 
1. Alliance can earn First Lieutenant after kill 1 horde player and able to create Sieges. 
2. Horde players defeating 10 players in total to earn First Lieutenant

How it should work: 
Both horde and ally players should be able to earn first Corporal rank after 5 kills, then Fist Lieutenant after 10 kills - 15 in total.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/olq9aFdSafg?t=109 - wg in bfa

**Comment by ntwrksx** [comment]
@lukaasm @Piootrek @Riztazz @Afgann @Dootz

**Comment by Azathothh** [comment]
https://www.wowhead.com/news=145516/patch-3-3-3-upcoming-wintergrasp-balance-changes
It's not a bug - that's blizzlike feature.

"The following advantages are provided at the beginning of the battle for Wintergrasp whenever these corresponding ranges on the scale have been reached:

    0-300: No advantages granted.
    400: Faction starts with the Sunken Ring Factory under their control.
    500: Faction starts with the Sunken Ring and Broken Temple Factories under their control.
    600: Faction starts with the Sunken Ring and Broken Temple Factories under their control and gains access to Catapults after earning 1 kill in battle.
    700: Faction starts with the Sunken Ring and Broken Temple Factories under their control and gains access to Catapults, Siege Engines, and Demolishers after earning 1 kill in battle."
