### ISSUE TITLE
Daily heroic quest: text bug

### ISSUE THREAD

**Issue by nosselil** [SunwellTracker/issues#3272]
Decription: 
when you complete the daily heroic quest you are rewarded 2 emblems of triumph

How it works: 
the emblems of triumph are added to your inventory but the system chat says you have been awarded emblems of valor

How it should work: 
the system chat should say that 

you have been awarded emblems of triumph 

Source (you should point out proofs of your report, please give us some source): 

![bug](https://user-images.githubusercontent.com/22297288/85866432-a900d380-b7c7-11ea-8b08-7b5451f61db9.PNG)

**Comment by Azathothh** [comment]
It's cache related issue - your game client is using old info, because that old info is saved in your cache folder.
Just delete cache folder and it will "fix" it for you.
