### ISSUE TITLE
Frostlord Ahune

### ISSUE THREAD

**Issue by Creedpt** [SunwellTracker/issues#3273]
Decription: The loot table from the boss is incorrect

How it works: The loot that his giving right now is level 70 cloacks.

How it should work: The loot from boss should be according to expansion max level

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/85948298-73d3bd00-b950-11ea-9f03-4dfa9c91e51f.png)
https://wowwiki.fandom.com/wiki/Patches/3.x
https://www.wowhead.com/object=187892/ice-chest#comments
