### ISSUE TITLE
T8 Mage 2pc not working

### ISSUE THREAD

**Issue by Oide1337** [SunwellTracker/issues#3276]
Decription: 
My 2 set for T8(Uld25) Mage says is gives 350 spellpower chance on hit for certain spells. Using those spells I have noticed that it never procs. I do have an on hit spellpower proc trinket Abyssal Rune so i believe that is overwriting my 2pc from proccing. 

How it works: 
Only my trinket is currently proccing no matter how long i dps for.

How it should work: 
Should stack with trinket proc as it is a separate entity and was like that on live, so SHOULD get 590 from trinket and 350 from 2pc

Source (you should point out proofs of your report, please give us some source): 
I have been paying close attention to all buffs as i go through heroics an it does not proc.

**Comment by wonszopaionk** [comment]
It works just fine. Provide sufficent proofs when posting a bug.
![obraz](https://user-images.githubusercontent.com/28888570/86140821-96510c00-baf1-11ea-9a0c-29a47495a8d0.png)

**Comment by Oide1337** [comment]
And you had an on proc spellpower trinket on too? That’s why I think it wasn’t, sorry for the no logs, my fault.

Sent from my iPhone

On Jun 30, 2020, at 7:49 AM, wonszopaionk <notifications@github.com<mailto:notifications@github.com>> wrote:


It works just fine. Provide sufficent proofs when posting a bug.
[obraz]<https://user-images.githubusercontent.com/28888570/86140821-96510c00-baf1-11ea-9a0c-29a47495a8d0.png>

**Comment by wonszopaionk** [comment]
Yes, it works just fine as I said. You just didn't check your combatlog carefully enough:
![obraz](https://user-images.githubusercontent.com/28888570/86243373-919a5f80-bba6-11ea-80af-70e2a92b2ba3.png)
