### ISSUE TITLE
Hunter Range Attack Speed

### ISSUE THREAD

**Issue by Ruur1** [SunwellTracker/issues#3277]
Decription: Hello i just saw that my Range Attack Speed is way faster then my bow on my Hunter. Bow Speed is 2.70s and Range Attack Speed is 2.35s - My Hunter is lvl 50 and has 0%haste gear on. Also ich checked without the Hawk buff or any haste improving buffs.

How it works: Range Attack Speed is faster than Weapon Speed 

How it should work: Range attack speed improves with %haste on  gear or buffs. if %haste is 0, the attack speed should match weapon speed

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
https://db.darkwizard.pl/?spell=75 - 15% bonus.

**Comment by Ruur1** [comment]
Thank you i didnt was that :)
