### ISSUE TITLE
[Quest] I've got a flying machine. (Can't complete it.)

### ISSUE THREAD

**Issue by Burnz2** [SunwellTracker/issues#328]
Decription: 
So I was trying to complete this quest, but when I try to put the sack of relics on the marked positions it will not drop. Also, the flying machines gets bugged. One of them I can't fly up or down with, and the same happened to the other one just now.

How it works: 
The bag of relics that you pick up while flying the machine will not drop on the designated areas.

How it should work: 
Somehow be able to drop the bags of relics onto the designated areas.

Source (you should point out proofs of your report, please give us some source):

**Comment by Burnz2** [comment]
Now both of the flying machines are bugged from the start. They can't be flown upwards or downwards.

**Comment by Dootz** [comment]
strange worked fine for me yesterday, i'll test it again :( . Also if your machine refuses to go up or down try to hit jump button (spacebar by default)

**Comment by AshElysium** [comment]
Hi,
If you hit the spacebar, while trying to control it, it will work. For some reason you just have to press space once.

**Comment by Kokaina** [comment]
Just did it w/o any troubles on Dootz's ptr :o

**Comment by Burnz2** [comment]
Yeah I tried hitting space and X, nothing happened. Managed to complete it by getting sack that I could pick up because of previous tries haha.
