### ISSUE TITLE
Faction Champions are immune to seduction

### ISSUE THREAD

**Issue by kollariss** [SunwellTracker/issues#3281]
Decription:  Seduction does not seem to be  working on Faction Champs

How it works: 
Currently, it appears that the Champs are immune to seduc (all attempts were at the start of the combat, if larger sample is needed, i can provide it)
https://imgur.com/ZaNpVgd

How it should work: 
According to Wowwiki: The NPCs are immune to mind control. All other forms of crowd control work. Hence the seduction should work (i have a feint memory of using it on retail + i did not see any changes to this aspect of the fight mentioned in the togc25 post).

Source (you should point out proofs of your report, please give us some source): 
https://sunwell-community.com/index.php?/topic/17959-frosthold-call-of-the-crusade-and-relentless-gladiator-season-patch-320-info/&__cf_chl_jschl_tk__=2d42fa49d09af15aa06378405f9488735157bc48-1593678412-0-ASh1DXmM03zN7ppKTTkGEkEy0_49oc_U8tfoSaXxYq06av-xhSVKc4HIpfVSIZ5R381VSExKhnaEOApCYp6UFOS87t3wduAx9eJv8qMkz8Px16RGWdY2MVZV4oVk0YrsO0qeph_ytKK_ygmQHYtnV-3lsbRUC5p4MU1S2ajbPKEZYxTydm4TaX2QUCGbY0WoNNCbPN4OX6v2cy3RjF8-b72-0IVAflTXlSfJWRWyd_98DTvFavAus7JBPzotUCVpfMg2YlUS4r3HHz1JDQIh7RTaSHM3LISE72Gl0jucaTcutIR9t8Ii6Te1KZjTdGEmcqCiQleMrYUUqlNJCdcppHm929mBqMcfVuGL2YIag83cX79fXwzOkMmJRkKtrlsn-CVt96GE3MIXCsQhuRuK05g

https://wowwiki.fandom.com/wiki/Faction_Champions

**Comment by Azathothh** [comment]
Proof needed - video/logs/info saying specifically that seduction should work there. I'm pretty sure it shouldn't.
