### ISSUE TITLE
T9 ROGUE SET 2P Bonus set not working

### ISSUE THREAD

**Issue by rayanmahanna** [SunwellTracker/issues#3282]
Description: Hi, I'm playing on Sunwell Frosthold and I got the 2 pieces gear for T9 rogue from Trial of the Champion, which is supposed to give me this bonus : 'Your rupture ability has a chance each time it deals damage to reduce the cost of your next ability by 40 energy'. But I ran a lot of tests, and it seems like it doesn't happen.

How it works: It is supposed to have a chance to make my next ability cost 40 energy less, but it seems like it never happens.

How it should work: I don't ever get the proc of this T9 2 pieces set bonus. If it was working, it would mean that at least one of my sinister strike after rupture deals damage should cost 0 energy, since sinister strike costs 40 energy itself. But I don't get any UI hint, or never see my energy back win 40 energy after casting an ability after rupture deals damage.

Source (you should point out proofs of your report, please give us some source):  I recorded 1 minute 30 and you can have access to the video at this adress : https://streamable.com/z4lhm8

**Comment by Soufly** [comment]
https://db.darkwizard.pl/?spell=67209 - its 2%.

**Comment by rayanmahanna** [comment]
> https://db.darkwizard.pl/?spell=67209 - its 2%.

alright I just seen it proc in the logs, it's just a very low chance. thanks for the quick answer
