### ISSUE TITLE
[Quest] Redemption (Tirion Fordring Dream Quest Chain from Vanilla)

### ISSUE THREAD

**Issue by mike-ers** [SunwellTracker/issues#3283]
**Decription:** 
The quest "Redemption" from the Vanilla WoW Tirion Fordring "Dream" quest chain is impossible to complete due to Tirion not doing what he's supposed to in order for the quest to be able to be turned in. Tried on two different characters, and attempted abandoning and re-taking the quest several times to no avail.

**How it works:** 
When accepting the quest, Tirion gives no dialogue nor does he have any "talking to" options when you click on him.

**How it should work:** 
When you accept the quest, Tirion is supposed to have dialogue options you manually select through to hear his "story", similarly to many other quests where you have to "listen to an NPC's story" by clicking through the dialogue window.

**Source (you should point out proofs of your report, please give us some source):** 
Trying to do it on my main and an alt, would not work for either character. I can take a video of it not working if it's really needed though.

Quest info:
https://classic.wowhead.com/quest=5742/redemption#comments

**Comment by Dootz** [comment]
Hi,
https://classic.wowhead.com/quest=5742/redemption#comments:id=2743175
you need to **sit** ( /sit ) and then option to hear his story will be available :)
