### ISSUE TITLE
Twin valkyrs orb soaking

### ISSUE THREAD

**Issue by styxel** [SunwellTracker/issues#3287]
Decription: 
Some classes/specs gain less stacks compared to others

How it works: 
Seems that as for example as feral dps u are always behind In stacks even when u stack directly above every1 else, talked to other ferals too seems to be like that for every1? I dont know If this problem excists for other classes/specs.. 
Apparently the number of hits are kinda even for every1 in the stacked grp but for some reason u dont get stacks often as a feral atleast??
Like the numbers of "powering up" buffs is the same for me as feral as our dks but our dks get the 100% dmg thingie twice during fight while i only get it once when boss hits 4%health its like im getting the powering ups but im not getting stacks.

How it should work: 
Should stack more evenly for every1 when u are stacked? Some problem with hitboxes or smthing 

Source (you should point out proofs of your report, please give us some source):

**Comment by wonszopaionk** [comment]
It works fine because you gain stacks form damage taken from orb explosion. Ferals take 30% less damage from explosions compared to other classes due to talent "Predatory Instincts" which reduces AoE damage taken by 30%:
![obraz](https://user-images.githubusercontent.com/28888570/86584567-5ec8e080-bf85-11ea-800d-57df750343c2.png)

**Comment by styxel** [comment]
Okey. I dont neccessary agree with this but If it is really like that and its blizzlike sure. Doesnt feel like 30% cuz sometimes u get the same amount sometimes 0. Sometimes when u kind move closer To the explosions u get same stacks with others but when u stand exactly where every1 else is u just dont i dont know feels wierd To me atm.
