### ISSUE TITLE
HAND OF SACRIFICE CAN'T USE AFTER DIVINE SACRIFICE

### ISSUE THREAD

**Issue by snaplife** [SunwellTracker/issues#3289]
Decription: 
after using the divine sacrifice the hand of sacrifice cannot be used but only before the divine sacrifice, this is a bug because the hand of sacrifice can also be used after the divine sacrifice. Furthermore I have tried the divine sacrifice with the other HAND skills and it works correctly both if I use them before and if I use them after the divine sacrifice

How it works: 
after using any skill, including divine sacrifice, another paladin can use the hand of sacrifice on the paladin who used divine sacrifice, at any time

How it should work: 

after using the divine sacrifice you can use the hand of sacrifice on the paladin who used the divine sacrifice

Source (you should point out proofs of your report, please give us some source): 
after the divine sacrifice:
https://prnt.sc/te6fue
https://prnt.sc/te6fad
https://prnt.sc/te6gbv
https://prnt.sc/te6hff
https://prnt.sc/te6iju

before the divine sacrifice 
https://prnt.sc/te6jqw
https://prnt.sc/te6jy4
https://prnt.sc/te6k58
https://prnt.sc/te6j1j

try with 2 paladins one uses divine sacrifice and the other the hand of sacrifice, both before and after

**Comment by Soufly** [comment]
Wrath of the Lich King Patch 3.2.0 (2009-08-04): Casting this spell on a target with Divine Sacrifice active will now generate an error message instead of wasting the cooldown.

**Comment by Soufly** [comment]
https://wow.gamepedia.com/Hand_of_Sacrifice

**Comment by snaplife** [comment]
is patch 3.2.0 on this server?

**Comment by Soufly** [comment]
yes
