### ISSUE TITLE
Stoneclaw totem not working properly!

### ISSUE THREAD

**Issue by Lithile** [SunwellTracker/issues#3293]
Decription: 
Stoneclaw totem is not working properly.

How it works: 
If Stoneclaw totem is used + any of the other 3 totems in a 4 set, in Call of Elements/Spirits/Ancestors, it is not giving protection to all totems, **it gives protection to fire totem**, **only**. 

If group of 3 totems is placed in Call of Elements/Spirits/Ancestors, and Stoneclaw is placed the last, it will apply shield to all totems.

How it should work: 
When Stoneclaw totem is placed in a 4 set, it should apply shield to all totems. 

Source (you should point out proofs of your report, please give us some source):  
https://wotlkdb.com/?spell=5730

**Comment by ArthurFkingShelby** [comment]
This is so annyoing in pvp especually when you cant protect your mana tide totem and anyone can just one shot it with basic attack
