### ISSUE TITLE
Spell queue system

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3296]
Decription: The spell queue system is not enabled on this server.
How it works: The retail spell queue system(the ability to link up 2 abilities,not spell batching window) does not exist here.
How it should work: U should be able to link up 2 abilities in order to reduce the difference in the latency(higher latency,bad gameplay etc).
Source (you should point out proofs of your report, please give us some source): 
https://www.twitch.tv/scribblejam/clip/AmusedLachrymoseAxeNomNom?filter=clips&range=all&sort=time

Edit: Even the worst server(paymane) has this system enabled,why cant we have it here ?

**Comment by markidjani** [comment]
This is the worst idea ive heared. 95%of ppl hate spell que and i dont see a single l reason why it should oul be used. Im the one whobleft warmane couse of this as many other and would do the same

**Comment by Soufly** [comment]
''an unfair advantage'' - clickers crying.

**Comment by Soufly** [comment]
Also ''blizzard implemented what can be thought of as an internal queue system''  and ''can be seen by noticing you can hit a spell a half second b4 the cast ends but that the spell doesn't go off for until the cast is actually finished, this is beyond what is due to lag'' - which doesnt exist on sunwell.

**Comment by Soufly** [comment]
''Blizzard implemented what can be thought of as an internal queue system'' and ''can be seen by noticing you can hit a spell a half second b4 the cast ends but that the spell doesn't go off for until the cast is actually finished, this is beyond what is due to lag'' - which doesnt exist on sunwell.

**Comment by Soufly** [comment]
https://i.imgur.com/vkOjrfQ.png

**Comment by Soufly** [comment]
[https://imgur.com/a/8qkcvt5](url)

**Comment by Soufly** [comment]
[https://i.imgur.com/yAhEjLg.png](url)

**Comment by Soufly** [comment]
Read the last comment in that thread. ;)
