### ISSUE TITLE
[PVP] SWD dont break scatter shot when player have power word shield 

### ISSUE THREAD

**Issue by lastrowy** [SunwellTracker/issues#3297]
Decription: SWD dont break scatter shot when dmg from it is absorbed

How it works:   SWD dont break scatter shot when dmg from it is absorbed, hunter can dmg on scatter too when player have absorb

How it should work: dmg for swd should break scatter shot does not matter player have absorb or not, any dmg shoud break scatter shot(like poly blind repetance)

Source (you should point out proofs of your report, please give us some source):

**Comment by lastrowy** [comment]
its same like #2997

**Comment by sunwellforumacc** [comment]
This!! so annoying! Makes hunter comps much much harder.
I see there is a note saying it is corrected, but still not. I hope this gets picked up fast!
