### ISSUE TITLE
[Hunter][UI]

### ISSUE THREAD

**Issue by malins2000** [SunwellTracker/issues#33]
Decription: 
There's no Pet ActionBar after login.

How it works: 
When I logout with pet active, and then log back in, ActionBar of pet disappear while Pet still there. Dismising and recalling pet brings ActionBar back.

How it should work: 
ActonBar should be present, when Pet is Active.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/35896695/35484491-b76fe7a8-0450-11e8-86ef-46d0107f98be.png)

**Comment by Sunwellxd** [comment]
jw. na dk unh jest to samo
bump

**Comment by ujellyx** [comment]
Still happening to me aswell. A "/reload" fixes it though.
