### ISSUE TITLE
hunter's Explosive Trap:crit damage is abnormal

### ISSUE THREAD

**Issue by wang3hui25** [SunwellTracker/issues#3301]
Decription: 
i am a new player from china,and i want to Report a bug about [Explosive Trap]
now [Explosive Trap]`s crit damage is 150% of the base damage,it should be 200% of the base damage

How it works: 
in chinese [Explosive Trap] is [爆炸陷阱]，as shown in the  picture
![WoWScrnShot_071920_203747](https://user-images.githubusercontent.com/68503264/87875136-a6c61980-ca01-11ea-883a-dc0909988832.jpg)
and [Explosive Trap] `s crit damage is this
![WoWScrnShot_071920_203552](https://user-images.githubusercontent.com/68503264/87875012-d294cf80-ca00-11ea-83ec-f010dc774814.jpg)
106/74=1.43,about 150%

How it should work: 
i found a post(chinese post) from year 2011 ,that showed [Explosive Trap] `s crit damage should be 200% of the base damage
post address：http://bbs.nga.cn/read.php?tid=4137382&fav=380775d8
and damage constitute:
![e769ceda68f9833a2f0b99bd832c4679](https://user-images.githubusercontent.com/68503264/87875120-957d0d00-ca01-11ea-9ce5-caf18f7611d0.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
it should crit for x1.53 (including meta) ignoring mortal shot and out normal x2 modifer

**Comment by wang3hui25** [comment]
> 它应该为x1.53（包括元数据）暴击而忽略致命一击并淘汰普通的x2修改器

sorry ,i don`t think so,in 2011 [Explosive Trap]`s crit damage is 2542/1279=1.98749,about 200%,it`s an attack power bonus skill,should be physical  crit damage.

**Comment by Soufly** [comment]
http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?s=8418&e=9169 - ICC logs from Method.
598 hit damage on valkyrs
910 crit damage on valkyrs
x1.52 multiplier

**Comment by wang3hui25** [comment]
> http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?s=8418&e=9169 - ICC logs from Method.
> 598 hit damage on valkyrs
> 910 crit damage on valkyrs
> x1.52 multiplier

but this log is inaccurate,We can analyze the damage component of his other skills,and found that [Steady Shot]'s crit damage is 5192/2550 = 203% ,and [Chimera Shot]'s crit damage is 13057.2/6192.3= 210%,and so on and so forth,it's inaccurate,Hunter's shoot skills to critical strike damage should be 230% by Talent bonus.
i found other log to show the Normal phenomenon,
http://www.worldoflogs.com/reports/ex034xw77ix917e5/details/19/?s=11354&e=12139
looking this guy's [Steady Shot] and [Chimera Shot],crit damage is more then 230%,and his [Explosive Trap] has no crit,because [Explosive Trap] can be crit until you used a Glyph of Explosive Trap,in fact,in WLK,Almost no one uses this glyph because it's a big glyph,and no one thought it would increase the damage to the BOSS.
so the log of Method's hunter is inaccurate,he used a big glyph whick is Glyph of Explosive Trap,but he just used less than three explosive traps,It doesn't make any sense.
i think,the log of Method's hunter should be version 4.0(CTM Eve),in CTM,hunter's  shoot skills crit damage  has been adjusted to 200% and Explosive Trap Effect can be crited and crit damage is 150%.
so,I think the data I provided is correct. Please reconsider.

**Comment by Soufly** [comment]
AS MM u have damage modifiers (Tier 10, 2 set / Improved Steady Shot / Rapid Killing etc...) u cant really compare the damage.

**Comment by wang3hui25** [comment]
> AS MM u have damage modifiers on proc (Tier 10, 2 set / Improved Steady Shot / Rapid Killing etc...) u cant really compare the damage.

i found so many log to prove it ,not just only one

**Comment by wang3hui25** [comment]
> AS MM u have damage modifiers on proc (Tier 10, 2 set / Improved Steady Shot / Rapid Killing etc...) u cant really compare the damage.

and in Bullseyes's log,he has use the [Aimed Shot],if he hasn't chose five Talent points to [Mortal Shots],he can't use the [Aimed Shot], if he chose five Talent points to [Mortal Shots,then his shoot skills  crit damage should be About 230%,so his log is inaccurate or his log is the version 4.0(CTM Eve)'s log

**Comment by wang3hui25** [comment]
> AS MM u have damage modifiers on proc (Tier 10, 2 set / Improved Steady Shot / Rapid Killing etc...) u cant really compare the damage.

the Critical damage of his all shooting skill  are all about 200%,not just [Steady Shot] and [Chimera Shot],but also [Arcane Shot] and [Kill Shot] and [Multi-Shot] and so so.
and The most irrational is [Serpent Sting],it's Critical damage is 2346.1/1556.1 = 150%,but from version,it has been fixed
https://wowwiki.fandom.com/wiki/Patch_3.2.2
Hunter Tier-9 2-Piece Set Bonus: Critical damage from Serpent Sting will now work properly with the [Mortal Shots] and [Expose Weakness] talents.
Bullseyes can use [Aimed Shot],so he must put five points in [Mortal Shots],so his [Serpent Sting]'s Critical damage must not be 150%.

**Comment by wang3hui25** [comment]
> AS MM u have damage modifiers on proc (Tier 10, 2 set / Improved Steady Shot / Rapid Killing etc...) u cant really compare the damage.

and i found then wiki of  [Glyph of Explosive Trap],it's been Added in  Patch 3.1.0, and Removed in Patch 4.0.1 and Recipe and existing glyphs converted to  [Glyph of Master's Call].
now,in this game,the [Glyph of Explosive Trap] is called  [Glyph of Master's Call].
so,this game's data is a mixture of the version 4.0's data, and in version 4.0,the [Explosive Trap] can be Crited and  doesn't need to use any glyph,and in version 4.0,the [Explosive Trap] 's  Critical damage has been adjusted to 150%
so, this game used the wrong data from version 4.0?.Please reconsider.

**Comment by wang3hui25** [comment]
> http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/spell/13812/?s=8418&e=9169 - ICC logs from Method.
> 598 hit damage on valkyrs
> 910 crit damage on valkyrs
> x1.52 multiplier

in this log,please check his [Buffs gained],and his [Power gains]

he get 978 focus from his [Steady Shot],
in WLK,hunter have mana but not focus,from CTM,hunter's DPS source becomes focus and no longer has mana.
so this log is a CTM'log,but not WLK's log,it can't be used to prove that [Explosive Trap]`s crit damage is 150%!!!

**Comment by Soufly** [comment]
@Afgann can help maybe.He is right about the focus part with steady(pre cata i guess,4.0 patch).

**Comment by Soufly** [comment]
My guess is that the explosive trap crit should work as Serpent Sting does with T9 2 set,but without valid proof ... well it will stay like this.

**Comment by wang3hui25** [comment]
But I have provided evidence, although it is from China,For special reasons, in 2011, China's version of world of Warcraft lagged behind other countries. At that time, China's version of world of Warcraft was 3.35 WLK,so i think it can be provided

在 2020-07-23 00:00:56，Soufly <notifications@github.com> 写道：


My guess is that the explosive trap crit should work as Serpent Sting does with T9 2 set,but without valid proof ... well it will stay like this.

**Comment by wang3hui25** [comment]
> My guess is that the explosive trap crit damage should work as Serpent Sting does with T9 2 set,but without valid proof ... well it will stay like this.

at first ,i have provided evidence
![image](https://user-images.githubusercontent.com/68503264/88294881-53203c80-cd2f-11ea-962f-f795e68048b1.png)

post(chinese post) from 2011-03-27:http://bbs.nga.cn/read.php?tid=4137382&fav=380775d8
![image](https://user-images.githubusercontent.com/68503264/88295011-74812880-cd2f-11ea-900b-986eab2f64ad.png)

as i said, for special reasons, The World of Warcraft: The Burning Crusade  in China lasted three years(2007-09-06~2010-8-30),the WotLK in China started on 2010-8-31 ,and in 2011-03-27 China's version of world of Warcraft was 3.35 WotLK,So I think it can prove that [Explosive Trap] `s crit damage should be 200% in 3.35 WotLK.

**Comment by Soufly** [comment]
@Afgann @Piootrek @Wojtyas

**Comment by wonszopaionk** [comment]
We are playing on enGB patches, why we should implement cn-related things here?

**Comment by wang3hui25** [comment]
> We are playing on enGB patches, why we should implement cn-related things here?

apart from language differences,is there any other difference between en and  cn settings?

**Comment by wang3hui25** [comment]
> @Afgann @Piootrek @Wojtyas

i finally found a log that could prove:http://www.worldoflogs.com/reports/4uc29jhb109l52yn/details/3/
in this log ,the Explosive Trap Effect Ticks damage is 1816.4 and Tick Crits is 3674.8
3674.8/1816.4 = 202.31%,Receive a 3% bonus on multi-colored gems,about 203%

**Comment by Soufly** [comment]
The log is from 2020,how is that retail log from wrath of the lich king ?

**Comment by Soufly** [comment]
The log is from 2020,how is that retail log from wrath of the lich king ?

Edit: I found this comment from the 3.3 PTR, https://www.mmo-champion.com/threads/679490-Explosive-trap 
''Just checked out ptr and a single explosive trap does on avarage 11K dmg to a single target for its full duration.
Tryed glyphing it for fun and its did as much as 23K dmg :P''

**Comment by wang3hui25** [comment]
> The log is from 2020,how is that retail log from wrath of the lich king ?
> Edit: I found this comment from patch 3.3 PTR, https://www.mmo-champion.com/threads/679490-Explosive-trap
> ''Just checked out ptr and a single explosive trap does on avarage 11K dmg to a single target for its full duration.
> Tryed glyphing it for fun and its did as much as 23K dmg :P''

oh my god,I hadn't noticed. Looks like the data from the unofficial servers will be uploaded, too?

**Comment by wang3hui25** [comment]
> The log is from 2020,how is that retail log from wrath of the lich king ?
> 
> Edit: I found this comment from the 3.3 PTR, https://www.mmo-champion.com/threads/679490-Explosive-trap
> ''Just checked out ptr and a single explosive trap does on avarage 11K dmg to a single target for its full duration.
> Tryed glyphing it for fun and its did as much as 23K dmg :P''

so it means that can prove it?

**Comment by Soufly** [comment]
The MMO champion link might prove it,but your log - no.

**Comment by wang3hui25** [comment]
> The MMO champion link might prove it,but your log - no.

ok,thinks for searching the evidence

**Comment by wang3hui25** [comment]
> The MMO champion link might prove it,but your log - no.

when it can be fixed?

**Comment by Soufly** [comment]
Its enabled ;)
