### ISSUE TITLE
30+ spellpower not working as intended

### ISSUE THREAD

**Issue by Emulersod** [SunwellTracker/issues#3303]
Decription: 30+ spellpower enchant on Heirloom staff

How it works: It doesn't work. I do not gain 30+ spellpower when I damage - only in stats when I press "C".

How it should work: It should give me 30+ spellpower and increase my damage which it does not. I only gain the spellpower from the heirloom staff itself and not the enchant.

Source (you should point out proofs of your report, please give us some source): I don't know what to put here. 
My character is located on Frosthold and it's called "Koreanjesus".

**Comment by wonszopaionk** [comment]
Do you know how spellpower works? Its UP to 30 sp - modified by coefficients. 
eg. Priests Mind blast gains only 42,8% which means spell damage is increased by 42,8/100*30~= 13 dmg.
