### ISSUE TITLE
DRUID school lock

### ISSUE THREAD

**Issue by wszaq** [SunwellTracker/issues#3316]
Decription: 
druid getting kicked = all schools locked
How it works: 
druid getting kicked = all schools locked

How it should work: 
only 1 school of magic should be blocked

Source (you should point out proofs of your report, please give us some source):

**Comment by Rosenkrantz** [comment]
Just for clarification - school isn't Balance or Restoration, but, in druid's case, Nature or Arcane spells. After a kick in Starfire, you should be able to cast basically anything except Moonfire, and after a kick in any Nature spell, you should be able to only use Star/Moon-fire.
