### ISSUE TITLE
Replenishment doesn't work in arenas

### ISSUE THREAD

**Issue by boskeys9** [SunwellTracker/issues#3320]
Description: 
While playing 3v3 arenas as a priest, I have noticed my ret pala partner doesn't apply Replenishment on me via Judgements of the Wise.

How it works: Pala judges enemies, his arena partner doesn't recieve Replenishment

How it should work: Pala judges enemies, his arena partner recieves Replenishment (provided the damage isn't fully absorbed, priest isnt cycloned etc. etc.)

Source (you should point out proofs of your report, please give us some source): While playing 10+ arenas, I haven't recieved a single instance of Replenishment across all of them. 
![repl](https://user-images.githubusercontent.com/69328124/89593413-58ad7480-d84f-11ea-9a7e-86e1bfe868f7.png)

**Comment by Rosenkrantz** [comment]
Replenishment talents on Arena only grant them as self-buff by a hotfix, as written on this report from 2009-04-25:

https://n4g.com/news/317767/wow

Working as intended.
