### ISSUE TITLE
DK arena: Ghoul despawns when entering arena, leaving it on a 30 sec CD.

### ISSUE THREAD

**Issue by MadsVSChristensen** [SunwellTracker/issues#3321]
Decription: 
As title says. When my ghoul is alive and i enter an arena, it despawns (no problem) but the CD is still 30 seconds. Hopefully this can be hotfixed as a QoL change .

How it works: 
Ghoul depspawns and goes on 30 sec cd.

How it should work: 
Ghoul's buffs should be removed and the ghoul not despawn OR the ghoul despawns but the cd is reset.

**Comment by Rosenkrantz** [comment]
Can confirm. Funnily enough, if I enter mounted, with my ghoul "hidden", I still lose him but do _not_ get cooldown.
