### ISSUE TITLE
[Giant Sewer Rat] can't pick up

### ISSUE THREAD

**Issue by Soilet** [SunwellTracker/issues#3324]
Decription: 
I was fishing in Dalaran Underbelly for that companion. I catch it 2-times so far, and i can not pick it. First time i catch it on my DK on 04.08.2020 and today on my shaman and there was the same problem.

How it works: After catch you can not pick it up.

How it should work: After catch it should appeared in inventory.

Source : https://wotlkdb.com/?item=43698

**Comment by Dootz** [comment]
Hi,

was there any error displayed when you tried to pick it up? ( red text at the center of the screen ). I assume you had space in bags. Did it happen for any other item? Was auto loot on?
Any additional information you can provide would be appreciated.
