### ISSUE TITLE
Bugged drop rate from Eye of Culuthas and Hound of Culuthas

### ISSUE THREAD

**Issue by Soldarian** [SunwellTracker/issues#3328]
Decription:  Eyes and Hounds of Culuthas have a high (85,9%) drop rate of mote of shadows and a small chance to (below 0,16%) to drop some other stuff, I've killed dozens of them (stopped counting after 40th) and I didn't get a single mote of shadow. 2 of them dropped some grey items, all other didn't have any loot at all - seems like dropping of motes got bugged and if any loot appears at all its from the pool of those low chance to drop items.

How it works: 
NPCs don't drop motes of shadow at all, or actual drop rate is very small

How it should work: 
Those mobs should drop motes accordingly to the drop rate

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?npc=20394#drops:0-14+1
https://db.darkwizard.pl/?npc=20141#drops

**Comment by Azathothh** [comment]
Looks like drop rate for these was corrected, but db.darkwizard.pl is still showing wrong values (db.darkwizard.pl isn't updated when changes are made)
![obraz](https://user-images.githubusercontent.com/37483678/91204976-1ddb8580-e705-11ea-8b58-b6efbb899498.png)
https://www.wowhead.com/npc=20394/eye-of-culuthas#comments
they shouldn't drop Motes of Shadow, so it's working correctly
