### ISSUE TITLE
Thunderstorming mobs under texture

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#334]
Decription: 
Everytime I thunderstorm a mob or more in the direction of a cliff/mountain or any surface that isn't flat mobs are getting into it. Most of the time they come back instantly but like in this screenshot they are stuck there untill I go far away to leave combat with them, then they just go back to their position.
http://prntscr.com/ic2vkp
How it works: 

How it should work: 
mobs should never end up under textures when they are thunderstormed.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
