### ISSUE TITLE
Chaos bolt

### ISSUE THREAD

**Issue by Aliftw** [SunwellTracker/issues#3346]
Decription: Chaos bolt isnt damagin cloak of shadows from rogue.

How it works: Chaos bolt is resesiting against cloak of shadows from rogue

How it should work: chaos bolt damaging through all absorbation and it cannot be resisted, check this out
https://cdn.discordapp.com/attachments/592382532209737749/750330622932942978/unknown.png

Source (you should point out proofs of your report, please give us some source): https://cdn.discordapp.com/attachments/592382532209737749/750330622932942978/unknown.png

**Comment by Platinumcoated** [comment]
Find proof that Chaos bolt ignored Cloak of Shadows during retail WotLK.

Internally Cloak of Shadows gives 90% miss, that's why Chaos bolt isn't hitting

**Comment by Soufly** [comment]
''Chaos Bolt pierces through resist effects (i.e. Cloak of Shadows)''
https://vanilla-wow.fandom.com/wiki/Chaos_Bolt

**Comment by Aliftw** [comment]
Unholy DK Anti magic sheel is absorbing every magic damage in the game, but
it's chaos bolt is hitting him with all the damage so you can't say cloak
has 90% chance and it should resist a spell like chaos bolt.
