### ISSUE TITLE
Brewfest issue

### ISSUE THREAD

**Issue by Esvelle** [SunwellTracker/issues#3356]
Decription: 
Hello,
I contacted GM over ticket and got redirected here. After we finished event rdf we got "Keg-Shaped Treasure Chest", opened it and didn't get anything from that. 

How it works: 
Didn't get anything from event reward bag.

How it should work
Not sure if there is 100% chance to drop item.

**Comment by Azathothh** [comment]
There was nothing wrong with that - only emblems does have 100% drop rate, and before ICC was opened there were not supposed to be emblems inside.
