### ISSUE TITLE
Pestilence on Lich King HC

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#3357]
Decription: Pestilence and Valks on Lich King HC

How it works: Valks that are flying in the air are in pestilence range during Lich King Heroic. 

How it should work: Pestilence and Chain Lightning should not be in range. 

Source (you should point out proofs of your report, please give us some source): https://youtu.be/UJz6R18A5u8?t=327

Here you can see pestilence being used from a random DK, LK is just below the valks and it does not spread. 

It's a pretty major bug of p2.

**Comment by wonszopaionk** [comment]
It works fine. even your "proof" says so:
![obraz](https://user-images.githubusercontent.com/28888570/93860002-a62a5780-fcbe-11ea-8013-2b5354782115.png)


Method Logs (http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/xe/?s=8418&e=9169&x=spell%3D%22Pestilence%22+or+spell%3D%22Frost+Fever%22):

![obraz](https://user-images.githubusercontent.com/28888570/93858321-416dfd80-fcbc-11ea-9e28-af8cae6bc118.png)

also here (http://www.worldoflogs.com/reports/7fdsejhs8e0ud38p/xe/?s=6684&e=8493&x=spell%3D%22Pestilence%22+or+spell%3D%22Frost+Fever%22&page=1):

![obraz](https://user-images.githubusercontent.com/28888570/93859640-28664c00-fcbe-11ea-9930-30074ea6d0d2.png)

Well nice "bug testing" sunced :)

**Comment by Misery321** [comment]
He's talking about the Val'kyrs that is airbourne after they've been dps'd down to 55% not the ones that spawn grabbing players.
@wonszopaionk

**Comment by Chryslol** [comment]
@wonszopaionk That Valk isn't even in the air? It's landing on a warlock next to the group, looks like that Pesilence range is weird. It's also weird how it goes to that valk but not the ones in the air don't you think? 

You link logs of Valks that have a mark, that means that they are on the ground. You don't see DKs having 20k DPS on any LK video because they can't spread diseases to Valks up in the air.
