### ISSUE TITLE
[Tirion's Gambit]

### ISSUE THREAD

**Issue by stanq87** [SunwellTracker/issues#3358]
Decription: 
npc is mising fin the starting location for[Tirion's Gambit] https://www.wowhead.com/quest=13364/tirions-gambit

How it works: 
Highlord Tirion Fordring is  lying dead at the  place where the event for [Tirion's Gambit] ends

How it should work: 
Highlord Tirion Fordring should stand near a  bonfire to the right of the entrance to the caterdal of darknesss, where the evet for the q starts
https://www.youtube.com/watch?v=-OVz8CXtI6w
https://www.youtube.com/watch?v=6BHru82udQw&feature=emb_logo

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi,

so from what I understand you can't take quest "Tirion's Gambit" because npc is not in start location. Do you see any other npcs at this camp? Have you completed previous quests? Please raise an in-game ticket if you still have this issue.
