### ISSUE TITLE
Ramp to Gunship not spawning for people

### ISSUE THREAD

**Issue by Mitchw1989** [SunwellTracker/issues#3362]
Decription: 
The ramp leading up to gunship isn't visible to some people. They just walk off the cliff.  Tried re-logging, rejoining raid group. It looks like a client issue since I was able to run it & the other 8 were able to, just 1 person didn't. He was able to TP to saurfang after we 9manned it.

How it works: 
Should be visible to walk up

How it should work: 
Left foot right foot on ship!

Source (you should point out proofs of your report, please give us some source):  I don't have any sources as it wasn't me in the raid who ran into the bug.

**Comment by Azathothh** [comment]
It's client related issue. Relog won't help, but restarting client may help. If not, then it's probably faulty client (some files are modified while they shouldn't).
It's not server side, so we can't do anything about it.
