### ISSUE TITLE
Brewfest items

### ISSUE THREAD

**Issue by lamatron** [SunwellTracker/issues#3364]
Decription: hello I Wright an issue regarding the 3set items needed for the dance achevent. They are pointed as Refundable in every guide and wowhead site.

How it works: I bought 3 items for 350tokens total and they aren't refundable for 2h duration.

How it should work: they should work like every other refundable item having 2h window to return them for full price 
https://www.wowhead.com/item=33967/green-brewfest-hat

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/94347874-4f16e080-0038-11eb-9fd5-dd7839f35a2a.png)
comment from your link
