### ISSUE TITLE
[ICC][Professor Putricide] Green Ooze - Ice block

### ISSUE THREAD

**Issue by mrnuggets** [SunwellTracker/issues#3366]
Decription: 

The green ooze isn't scripted as it should be.

How it works: 

When the green ooze targets a mage, the mage can ice block and the green ooze will just afk until the ice block runs out.
Shown here: https://www.twitch.tv/videos/749782061?t=2h8m36s

How it should work: 

When the mage uses ice block the green ooze should start targeting a new player, just like when you bubble or feign death.

Source (you should point out proofs of your report, please give us some source): 

https://gyazo.com/e981f8de68aa7d9872666575143306d1
Picture is taken from a comment on https://www.wowhead.com/npc=36678/professor-putricide#comments;mode:n10 if you want to read it yourself

**Comment by Soufly** [comment]
True.
