### ISSUE TITLE
[Quest]  An Invitation, of Sorts... or  Darkness Calling

### ISSUE THREAD

**Issue by Mysoopa** [SunwellTracker/issues#337]
Decription:
Unliving Choker or  Writhing Choker

How it works:
Unliving Choker or  Writhing Choker not dropping

How it should work:
During the quest Kickin' Nass and Takin' Manes, while killing the Whitered Trolls a quest item should drop  Unliving Choker or  Writhing Choker  to start a chains of quest leading op to Voltarus. the quest item won't drop

**Comment by kovaq** [comment]
@Dootz Its known issue.
https://github.com/RaphaelSunwell/Sunwell-BugTracker-SCv2/issues/1145
It happens only if you have Cleansing Drak'Tharon quest. You can complete it or Abandon it, should drop anyway. Checked right now.

**Comment by Dootz** [comment]
ohh thanks a lot. I wasn't aware of that.  I'll look into this again today.

**Comment by Dootz** [comment]
will be fixed with next update
