### ISSUE TITLE
[Warrior, Spell] Heroic Strike and bonus Dmg to Dazed targets

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#3370]
Decription:
Heroic Strike dont do bonus Dmg to Dazed targets.

How it works:
Heroic Strike dont do bonus Dmg to Dazed targets.

How it should work:
Heroic Strike Should do bonus Dmg to Dazed targets.

Source (you should point out proofs of your report, please give us some source):
https://www.wowhead.com/forums&topic=156304

old thread: https://github.com/SunwellTracker/issues/issues/2509

**Comment by Soufly** [comment]
Might be worth to check Steady Shot as well @Afgann (since the effect is similar)
