### ISSUE TITLE
Death Strike - Healing reduction on BG/Arena/WG

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#3372]
Decription: 
Death Strike Healing is not reduced by 10% on BG/Arena/WG like all other Healings.

How it works: 
Death Strike Healing is not reduced by 10% on BG/Arena/WG like all other Healings,

How it should work: 
Death Strike Healing should be reduced by 10% on BG/Arena/WG like all other Healings,

**Comment by Platinumcoated** [comment]
but why
