### ISSUE TITLE
Bugged ID's for weekly raids. (VOA25 in this case)

### ISSUE THREAD

**Issue by klafen** [SunwellTracker/issues#3374]
Description: Wednesday, no raid locks, perfect. This Wednesday was different, my VOA25 lock was still there.

How it works: Raid ID's not reseted this Wednesday.

How it should work: Raid ID's resets every Wednesdays.

Source (you should point out proofs of your report, please give us some source): No special source, logged online for the first time today (Wednesday), every raid reseted except VOA25.

**Comment by Azathothh** [comment]
It means that you've used "Extend Raid Lockout" feature. Or someone else in your group did and you've accepted that
