### ISSUE TITLE
Jewelcrafting yesterday's daily is undoable today 

### ISSUE THREAD

**Issue by Warglaive** [SunwellTracker/issues#3375]
Description: 
I have noticed that if I try to complete JC's daily from yesterday, today - the quest item will NOT drop.

How it works: 
...

How it should work: 
It should be doable anytime.

Source (you should point out proofs of your report, please give us some source): 
I am unable, what I can say is that I did try to complete the quest for ~15 minutes and I could NOT do it, had to abandon the quest and complete the current daily(for today, not from yesterday) and it worked as expected, while the normal completion time is just 1-2 minutes, it should definitely drop in this time period.

**Comment by Dootz** [comment]
Hi, could you please provide name/link to quest which you are not able to complete?

**Comment by Azathothh** [comment]
If you couldn't loot quest item, it does mean that either you were in raid group or that you already does have this quest item in your bags or bank.

**Comment by Warglaive** [comment]
Maybe my explanation was unclear, the idea is that **if you accept the Jewelcrafter daily quest (any quest) yesterday and try to complete it today, you won't be able**. And no I was not in a raid group and no I did not have the quest item in the bank :D 

Off question: I really wonder if you have reliable people to test the reported issues or you try to understand it from the description mainly because if you send someone to test it, you will see for yourself, it is just unusual to farm JC quest item for longer than 15 minutes and it won't drop.

**Comment by Azathothh** [comment]
It was clear, but it's simply not true. Just grab JC daily today, keep it and you will see that you can do it tomorrow just fine.
When i do my JC daily it's always at least one day old :P

**Comment by Warglaive** [comment]
> It was clear, but it's simply not true. Just grab JC daily today, keep it and you will see that you can do it tomorrow just fine.
> When i do my JC daily it's always at least one day old :P
> Like i've said - you can't get quest item to drop only in cases when you already have it (it's unique) or when you're in raid group (quests can't be done in raid groups). Well, other option is killing wrong mobs

Sure it may be just that I have been unlucky, but anyway, I play since 2010, been working on a wow 3.3.5a project for ~3 years so no chance I was killing wrong mobs, being in raid or w/e :D , lets not waste Dev's time with this minor report, it just seemed unusual the thing I reported.
