### ISSUE TITLE
Boss Health Bar Bugg

### ISSUE THREAD

**Issue by H4zard0us** [SunwellTracker/issues#3379]
Decription: 
Boss Health Bars were bugged in Blood Council , Icecrown Citadel 10

How it works: 
3 bosses in Blood Council all had HP bar

How it should work: 
2 of those bosses have 1 HP and the other 1 has the HP bar called "Invocation of Blood" and the boss which has the buff can be damaged

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
We had the same issue on 25 man 3 days ago,visually they had all full HP(except the attacked target).
