### ISSUE TITLE
Warbringer Arix'Amal does not drop Burning Legion Missive

### ISSUE THREAD

**Issue by chme3921** [SunwellTracker/issues#338]
Description: Warbringer Arix'Amal does not drop the Burning Legion Missive

How it works: he doesn't drop it

How it should work: he should

Source (you should point out proofs of your report, please give us some source): https://wotlk.evowow.com/?item=29588

dropped by Warbringer Arix'Amal at 100% rate

**Comment by Dootz** [comment]
There is 50% chance that Warbringer Arix'Amal will drop http://www.wowhead.com/item=29590/burning-legion-missive for Alliance player's. Horde version is droped by http://www.wowhead.com/npc=20798/razorsaw . So it works as intended.

**Comment by set-theorist** [comment]
The chance should be 100%. It's only 42% on wowhead because people who have already done the quest have killed the mob and looted him.
