### ISSUE TITLE
Feral rip bleed damage

### ISSUE THREAD

**Issue by Ripperino23** [SunwellTracker/issues#3387]
Decription: 
I feel like feral druid damage from bleeds atleast rip has been the same since naxx. Is the scaling of bleeds somehow off or does it always stay at same dmg no matter the gear??  Can someone Who knows better tell if im wrong. 

How it works: 
Still averages around 4.5-5.5k ticks 

How it should work: 
Should Do More damage maybe? I feel like even when u get big ap procs it still does very little more damage. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Platinumcoated** [comment]
So you did 5k dmg per tick during Naxx? That's 20k on one single dot which could literally one-shot people in pvp. Even with 1400 resilience that's 15k damage which ignores armour.

Rip should probably have an Attack Power coefficient which you can easily lookup online.

You can also test this really easily on a dummy by comparing damage with less AP by unequipping gear

**Comment by Ripperino23** [comment]
i see well idk just thought it was low increase i tested with no ap buff and with 1250ap trinket proc
rip ticks 2908 unbuffed
rip ticks 3127 with +1250ap proc trinket 
just wondering if this is correct or should it be more :))
