### ISSUE TITLE
Mage Tier 10, 2set Bonus Proc Bug for Arcane

### ISSUE THREAD

**Issue by LifebloomX** [SunwellTracker/issues#3388]
Decription: 
Mage's tier 10 - 2set bonus proc doesn't work properly for arcane mages.

How it works: 
"Pushing the Limit" haste proc occurs at the **START** of Arcane Missiles.

How it should work: 
"Pushing the Limit" haste proc must proc **AFTER** Arcane Missiles finishes channeling.

Steps to Reproduce:
1. Have an arcane mage with "Missile Barrage" talent ready.
2. Put on 2 pieces of Tier 10 gear.
3. Spam Arcane Blast until you get "Missile Barrage" proc.
4. Cast Arcane Missiles.

Source (you should point out proofs of your report, please give us some source): 
1. Proof of Bug: 
    - Image: https://imgur.com/a/gIcXEQa
2. Proof of how it worked in retail: 
    - T10 - 2 Set Proc: https://imgur.com/a/WHKds7E
    - Video: https://youtu.be/jD4Ds6f_6wo?t=273 
      (Pay attention to when the "Pushing the Limit" icon appears. It's after Arcane Missiles)
    - Wowhead: https://www.wowhead.com/spell=70752/item-mage-t10-2p-bonus#comments

**Comment by Soufly** [comment]
@Afgann Is not only that ability,all types of procs do proc before they even HIT the target...
