### ISSUE TITLE
[Patch] Dismount bug patch messes up textures

### ISSUE THREAD

**Issue by maliciousrabbit** [SunwellTracker/issues#339]
![wowscrnshot_020818_222224](https://user-images.githubusercontent.com/28464810/36011676-952f542c-0d1e-11e8-9651-b594914f5656.jpg)
![wowscrnshot_020818_222201](https://user-images.githubusercontent.com/28464810/36011677-966bbdee-0d1e-11e8-877d-75c7eb269235.jpg)
![wowscrnshot_020818_222143](https://user-images.githubusercontent.com/28464810/36011679-98554c4c-0d1e-11e8-98b9-d69da376e66e.jpg)

![wowscrnshot_020818_220015](https://user-images.githubusercontent.com/28464810/36011235-8a4a0352-0d1b-11e8-80da-9ff84fffd523.jpg)
Decription: 
Not too long ago you guys released a patch that fixed the problem where players would get dismounted as soon as they mounted up. This part of the patch works perfectly. However, while I have this patch in my data folder, my texture get extremely messed up. Instead of NPC's looking normal, their skin texture is just faces. I also see players run around as small blue/white checkered cubes. As well as a bunch of enemy NPC's in dungeons just being solid green. I know for sure it is the patch because when I take the patch out of my data folder, all my textures go back to normal but then I have to deal with the mount glitch again.

How it works: 
Textures are messed up

How it should work: 
Textures should be normal

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
