### ISSUE TITLE
Lich King: Soul Reaper debuff causing damage instantly

### ISSUE THREAD

**Issue by Windcubbz** [SunwellTracker/issues#3390]
Decription: 
In Phase 2 of the Lich King encounter (on 25N), he periodically uses Soul Reaper, which both applies a debuff on the active tank with a few second duration, and buffs the Lich King's damage done for a few more seconds.  Soul Reaper seems to sometimes expire immediately upon application, causing the shadow damage to go out as soon as it applies.

How it works: 
The Lich King applies Soul Reaper to the active tank.  The debuff appears to expire immediately.  The active tank takes the shadow damage up front without the intended Soul Reaper debuff duration beforehand.

How it should work: 
The Lich King applies Soul Reaper to the active tank.  The debuff appears on the active tank, ticks down for a few seconds, and causes shadow damage upon expiring.

Source (you should point out proofs of your report, please give us some source): 

Clip from stream:
https://clips.twitch.tv/IronicHealthyGarbageDAESuppy
MSBT scrolling on the left side of the screen shows all boss damage occurring to the tank throughout.

Thanks,
Wind

**Comment by wonszopaionk** [comment]
It does damage twice. Once upon application (50% meele) and then after 5 seconds 70k shadow dmg.
https://wotlk-twinhead.twinstar.cz/?spell=73799
