### ISSUE TITLE
[Hunter] [Pet] [Focus Regen]

### ISSUE THREAD

**Issue by leakages** [SunwellTracker/issues#34]
Description: 
Hunter pet focus regen is currently working incorrectly.

How it works: 
Focus is returning in large chunks of 25-50 focus every few seconds

How it should work: 
Focus should be regenerating at 5 focus/second and be smooth.

Source (you should point out proofs of your report, please give us some source): 

https://wow.gamepedia.com/Focus

**Comment by Azathothh** [comment]
Missing proofs/not enough data.
