### ISSUE TITLE
TOCH HC Eadric crits defense capped tank

### ISSUE THREAD

**Issue by rudeesk** [SunwellTracker/issues#3400]
Decription: 
i got critically hit by eadric the pure in toch5 hc mode while defense capped
Eadric the Pure's melee swing hits Rudeezw for 7092 Physical.(Critical)
![image](https://user-images.githubusercontent.com/18498406/96048619-22a3f680-0e77-11eb-9955-677e7ef7dffd.png)

How it works: 
i got crit

How it should work: 
defense capped tank should not get hit by crit 

Source (you should point out proofs of your report, please give us some source):

**Comment by Soufly** [comment]
https://www.wowhead.com/spell=66889/vengeance - nope
