### ISSUE TITLE
Thyrm becomes invisible in mini-instance after getting on to Gymer

### ISSUE THREAD

**Issue by heracro** [SunwellTracker/issues#3403]
Decription: Quest "The Storm King's Vengeance" - ride Gymer (giant) and kill 100 scourge, Alghar and Navarius - in the end there' giant Thyrm to defeat, but even though it's wandering around in Zul'drak, whenever you hop on Gymer, it's not visible and quest can't be completed.

How it works: ride Gymer, ill 100 scourge, prince, Alghar and Thyrm. Thrym not possible to kill - not visible while riding Gymer

How it should work: While riding Gymer Thyrm should be visible and kill-able

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/quest=12919/the-storm-kings-vengeance#

**Comment by Hahecz** [comment]
Incorrect, quest is perfectly doable, Thyrm (quest version of him) spawns after you kill Prince Navarius.

**Comment by Azathothh** [comment]
Quest works fine, Thrym walking on the road while you're not on this quest is NOT related to it.
Like Hahecz wrote, he appears after Prince Navarius death.
