### ISSUE TITLE
Pet follow speed 

### ISSUE THREAD

**Issue by Vidia2** [SunwellTracker/issues#341]
Decription: 
When a pet remains behind big time, it just continues to move at normal speed, instead accelerating to get back to master. Pet follow up speed should be faster, if/when the pet is severely behind, in order to keep up.

How it works: 
see above

How it should work: 
 Pet follow up speed should be faster, if/when the pet is severely behind, in order to keep up with the master.

Source (you should point out proofs of your report, please give us some source): 
it was like this from vanilla time, everyone knows this.

**Comment by Azathothh** [comment]
Pet movement rewritten, should be working now.
