### ISSUE TITLE
Sindragosa unchained magic/instability proc on spell hit and not on cast

### ISSUE THREAD

**Issue by Damnlife** [SunwellTracker/issues#3411]
Decription: Sindragosa's debuff she gives - Unchained magic [Inflicts an arcane malediction on the target, causing any spells cast to result in a backlash of Arcane power after 5 sec.  Multiple spellcasts by the afflicted target will intensify the backlash.] applies its aura called Instability[Using magic while afflicted with Unchained Magic will build up unstable energy, dealing 862 Arcane damage to the caster per spell cast, 5 sec after spellcasting ends.] on instant cast spells but when you cast a non instant spell(for example Shadow bolt) the Instability stack is procced on hit and not on release. I have seen this bug on other private servers and I have done the same report already(will not mention any names here).
Proof: I will post the stream of my friend, because I personally fighted sindragosa once since Im on the server so I dont have a proof of my own.
https://youtu.be/60a7s9JQlQc?t=3531 - the video is from a current time stream - 58:50
He is getting the unchained magic then he starts casting Shadow bolt and you clearly see it, play the video as many timeas as you want, I dont think there is a need of posting screenshots here, it is not even hard to notice that he is taking instability stacks on hits from shadow bolt and haunt and not on casts. After 3 shadow bolts and 1 Haunt, he casts Drain soul and instantly receives 1 instability stack, that means it's okay with drain soul and not with shadow bolt and the rest casting spells. I thought there is another bug connected to the instability stacks which is taking stacks on tics from spells like drain soul, drain life[channeling spells] but that works fine, I am not sure about discipline priest's penance spell though, I think it gives you 3 stacks which is incorrect. 

How it should work: Instability stacks should be procced only from casted spells and not on hits or channeling spells such as penance. This is literaly what the spell description says - [Inflicts an arcane malediction on the target, (CAUSING ANY SPELLS CAST) to result in a backlash of Arcane power after 5 sec.  Multiple spellcasts by the afflicted target will intensify the backlash.]

Source (you should point out proofs of your report, please give us some source): Here is my source. The video is from 2010 march 3(it is in the description of the video although the video is posted 2012 it's from retail. There are plenty of videos on youtube showing how unchained magic is supposed to work and since the video shows it clearly I decided not to post any more videos. 
Here it is: https://www.youtube.com/watch?v=B_HZPgLVBGE - Affliction warlock taking instability stacks from casted dots and from casted Shadow bolt and haunt.
Thanks for the attention!

**Comment by shadownib** [comment]
New FRESH Naxxramans wen ( why should they fix anything in icc , when they are closing the realm after few Halion 25 HC kills and opening Fresh 3.0.1 patch again ? ) 
Also note that , they are not wiling to provide the most blizzlike scripts , they are aiming for their own custom scripts & futures like Mythic+ etc, saying that ... idk what's the future of those reports in sunwell ( the community doesn't care , so the goal of the server is anything else based on the casual level of that new players generation )

**Comment by shadownib** [comment]
RIP WOTLK 3.3.5a GD 2019 ,and congrats to the Glitchmane monopoly , nice business.

**Comment by Damnlife** [comment]
I'm trying, I will just give up if no one cares about reports and stuff anymore.

**Comment by mrnuggets** [comment]
I'm not sure if it's because of the way you're explaining it.

But shadow bolt seems to be working as it should. He is taking stacks when the cast is finished, just like in the retail video.

**Comment by Damnlife** [comment]
No, he is not, I am sorry, I will add screenshots later then, if you have hard time not noticing when he is taking stacks.

**Comment by mrnuggets** [comment]
I don't think i am wrong.

I am watching both videos in the slowest speed that you can, and they're both taking stacks when Shadow Bolt is finished casting.

If you can prove me wrong, gladly do so.

Shadow Bolt - Frosthold: https://youtu.be/60a7s9JQlQc?t=3555
Shadow Bolt - Retail Video: https://youtu.be/B_HZPgLVBGE?t=56

**Comment by Damnlife** [comment]
I will, I am busy at the moment, in an hour will prove you wrong

**Comment by Damnlife** [comment]
Before he casts haunt, he casts 2 shadow bolts. the first shadow bolts hits for 16142 this is his first ins stack. He doesnt have UM yet when he casts it. the second SB before casting haunt hits for 14291<1587 resisted>, this is his second ins stack and it appears while he is casting SB after he finished casting haunt. so far he has casted 2 shadow bolts,1 haunt and is already casting another SB. the third stack is from Haunt which hits for 8468 damage and right after haunt hits, he starts casting drain soul which gives him another ins stack. So far 4 but while he is casting drain soul, he receives another instabiliy stack which is from the SB hit for 7586 that he casted between haunt and drain soul. Thats all. He takes ins stacks on hit and not on casts(except for drain soul) tell me if I have to provide you screenshots, it will take time that is why i decided to try and explain it differently this time and see if you could understand it now

**Comment by Damnlife** [comment]
Later oh, he gets UM again, he casts unstable affliction-1 stack, then haunt, finishes cast, no stack, then SB, finishes cast - ins stack from haunt, sb again, then sb again(finishes cast-stack from first sb and 1 ins stack he gets from curse of agony because he recasts it) so far 4 ins stacks. he starts casting another SB and right before his cast ended, he gets another ins stack from the last SB he casted, the one he casted before casting Curse of agony. Play the video on 0.50 speed and see for yourself, if you still cant, I will provide screenshots then

**Comment by mrnuggets** [comment]
Disregard what i've said.

He is right. After further looking into it, i have to agree with him.
