### ISSUE TITLE
Horseman's Reins

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3421]
How it works: Horseman's Reins has a chance(1% based on your database) to drop from the boss itself currently.
How it should work: It should drop ONLY from the pumpkin.
Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/The_Horseman%27s_Reins
''Wrath of the Lich King Patch 3.3.3 (2010-03-23): No longer drops from The Headless Horseman. Instead, you can get this mount from  [Loot-Filled Pumpkin].''
@Dootz

**Comment by Dootz** [comment]
Hi, I can confirm it has 1% chance to drop from both Headless Horseman and Loot-Filled Pumpkin.

**Comment by Soufly** [comment]
The point is that it should drop ONLY from the pumpkin .. @Dootz but ok ..
