### ISSUE TITLE
Frost Emblems Refund not working with Marks

### ISSUE THREAD

**Issue by sunwellbuggers** [SunwellTracker/issues#3423]
Decription: 
Bought wrong T-Part from Vendor. Upgraded it and then realized it wasn't the one i wanted to buy. Refunded 264 item w/o issue 251 item wasnt refundable.
See Screenshots attached.

How it works: 
Upgrading a T-Part with a Mark from 10HC or 25normal quarter Bosses and refunding will give you the 251iLVL item + the mark back. After that process 251iLVL item is not refundable although only 2 minutes "old"

How it should work: 
Upgrading a T-Part with a Mark from 10HC or 25normal quarter Bosses and refunding will give you the 251iLVL item + the mark back. 251iLVL item should be refundable after
![ticket](https://user-images.githubusercontent.com/73752642/97784416-c17e6180-1b9e-11eb-996e-1c60abbb510c.jpg)
![error](https://user-images.githubusercontent.com/73752642/97784418-c216f800-1b9e-11eb-96f1-8140c3246c1a.jpg)
![refund](https://user-images.githubusercontent.com/73752642/97784419-c3482500-1b9e-11eb-889f-4862ec960fda.jpg)
![refundable](https://user-images.githubusercontent.com/73752642/97784420-c4795200-1b9e-11eb-99f5-65b3a18526b0.jpg)

![refundable2](https://user-images.githubusercontent.com/73752642/97784415-c04d3480-1b9e-11eb-93f0-9dd6d3ad1a37.jpg)

Source (you should point out proofs of your report, please give us some source): Items attached. Please see if this can be fixed or introduce loot logs to the server.

**Comment by Azathothh** [comment]
I don't think that item which you've received from refunding 264ilvl should be refundable, because it's NOT the same 251ilvl which was refundable before you've used it to bought 264ilvl.
If you have any proofs/sources showing that it should work like you're claiming, please attach them and issue will be re-opened

**Comment by sunwellbuggers** [comment]
obviously i did the screenshots afterwards because i didnt expect this issue to occur. Nor did i expect the item i bought to be the wrong one. yes the 251iLVL item is not with "bluetext" anymore but i swear it was when i bought it. Fix your server and introduce lootlogs. thank you
