### ISSUE TITLE
Icehowl charge

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3424]
How it works: Icehowl charge animation between the stun and the crash itself lasts 5 seconds currently on frosthold.
How it should work: It should last 10 seconds.
Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/yBKO567s33k?t=387 (frosthold realm first)
https://youtu.be/po9k71NjnE4?t=404 (tankspot guide from retail)

**Comment by Hahecz** [comment]
I had my doubts about video speed and i check it with stopwatch.
I can confirm that in both videos one minute of  game time corresponds with 1 minute of real time.

Difference between charge timers is noticeable.

**Comment by Soufly** [comment]
Edit: The point if this report is to give a chance to the players to avoid the charge,by using aspect of the pack just before the crash,which will give a daze effect for 4 seconds,but since the whole charge animation lasts 10,they will have chance to run out from him.
