### ISSUE TITLE
Pestilance Frosthold 

### ISSUE THREAD

**Issue by kizito17** [SunwellTracker/issues#3426]
Decription: My pestilance spell doesnt work properly, with or without glyphs (glyph of disease, glyph of pestilance)

How it works:  When i cast pestilance, seems like nothing happends, doesnt spread diseases on other close targets, and doesnt restart duration on my main target at all

How it should work:  It should spread diseases on other close targets, and also to restart duration on main target

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
It works completely fine 
![obraz](https://user-images.githubusercontent.com/37483678/98467109-eb093f80-21d3-11eb-9b19-b5b559cfb0b3.png)

If you have some issues, you have to provide some data, like video, or combat log, otherwise we've got no idea what exactly are you doing.

**Comment by kizito17** [comment]
Look, it only hit all nearby targets, but doesnt spread any diesies... 
btw i have dk character on horde too, and all works perfectly, but on this not...

![pesti](https://user-images.githubusercontent.com/65923548/98486642-d43c0a80-221e-11eb-9938-d0a796bb670f.png)

**Comment by kizito17** [comment]
You market this report as closed, which is not, thats why i opened new one, sorry..
down here is data, so tell me can it be fixed?

![98486706-5af0e780-221f-11eb-89d9-5690231b66d1](https://user-images.githubusercontent.com/65923548/98531494-b3a49c80-2280-11eb-881f-2ef3707e7c2f.png)

**Comment by Azathothh** [comment]
Please just open ticket in-game explaining your issue, you will have to show GM this situation
