### ISSUE TITLE
Pestilance bug

### ISSUE THREAD

**Issue by kizito17** [SunwellTracker/issues#3429]
Decription: My pestilance spell doesnt work properly, with or without glyphs (glyph of disease, glyph of pestilance)

How it works: When i cast pestilance, seems like nothing happends, it only hit all nearby targets but doesnt spread diseases, and doesnt restart duration on my main target at all

How it should work: It should spread diseases on nearby targets, and also to restart duration on main target

btw i have dk character on horde too, and on him pestilance works perfectly, which is not case on my main char...

![pesti](https://user-images.githubusercontent.com/65923548/98486706-5af0e780-221f-11eb-89d9-5690231b66d1.png)

**Comment by Azathothh** [comment]
Please write in previous report, there's no need to create new one
