### ISSUE TITLE
[Quest]  The Assassination of Harold Lane

### ISSUE THREAD

**Issue by Avarishd** [SunwellTracker/issues#343]
Decription: The NPC(Harold Lane) an elite, is doing 1 to 3 damage.He is also missing his abilities. Quest item also does nothing.
Quest currently is a joke. The normal mobs around him do 200-300 and the elite(Harold Lane) is doing 1 to 3.

How it works: The NPC does nothing, melees for 1 to 3 damage. He doesn't use any special abilities. Quest item also does nothing.

How it should work: Harold Lane should hit for way more with basic attacks. He has 2 abilities (From wowhead 3.1 patch comment):

Throw Bear Pelt:
Harold will throw a bear pelt at the player doing 1000 - 1200 physical dmg (on leather) approximately every 3 seconds while at range.

Bear Trap:
Harold will place a trap on the ground, typically next to the player, which will root the player in place and do 315 damage every 2 seconds for 10 seconds. While player is rooted, Harold will run to ranged distance and use the Throw Bear Pelt ability.

Cenarion Horn(the item you are provided with) will summon a stampede and do approximately 50% damage to Harold. The item should only affect the NPC only once per encounter.
The stampede - a bunch of mammoths that spawn, run him over and then despawn.

Source (you should point out proofs of your report, please give us some source): 
Cenarion Horn - http://db.darkwizard.pl/?item=35293
Harold Lane -  http://db.darkwizard.pl/?npc=25804
Quest ID - http://db.darkwizard.pl/?quest=11892

**Comment by Dootz** [comment]
will be fixed with next update
