### ISSUE TITLE
PP,Regurgitate Ooze

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3437]
How it works: Regurgitate Ooze from the abomination at PP encounter can slow PP last phase.
How it should work: I never seen any ability that can slow a boss npc.
Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/eBzQYo9fHzE?t=421 frosthold / https://youtu.be/jv93ko3WeK8?t=447 retail

**Comment by mrnuggets** [comment]
I wouldn't say that this proves that it shouldn't be possible to slow the boss.

The abom in paragons kill used the slow on the green ooze at the end cause slow on it ran out. You'll also see that he didn't have time to slow the boss, since p3 started after slowing the green ooze once again.

**Comment by Soufly** [comment]
Still,there is no prove that it should.

**Comment by Soufly** [comment]
This might help: https://www.wowdb.com/spells/70539-regurgitated-ooze (i know its patch 7.0.1,but still the effect information is correct).

**Comment by Soufly** [comment]
This might help: https://www.wowdb.com/spells/70539-regurgitated-ooze (i know its patch 7.0.1,but still the effect and flag information are correct).

**Comment by Soufly** [comment]
This might help: https://www.wowdb.com/spells/70539-regurgitated-ooze (i know its patch 7.0.1,but still the effect and flag information are correct,except the damage part ofc).
