### ISSUE TITLE
Mindless Servant (npc)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#344]
Decription: 
When you enter Utgarde Pinnacle there are some skeletons on the left side that will aggro but won't move unless you get near them, most ppl don't notice them and just clear the dungeon thinking they are in combat bug.
http://prntscr.com/iccrmy
How it works: 

How it should work: 
mobs that aggro you shouldn't just stand still.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
