### ISSUE TITLE
Quest: Adversarial Blood

### ISSUE THREAD

**Issue by brekko** [SunwellTracker/issues#3440]
Decription: Even if I have the item Time-Lost Scroll in my bag when I try to summon the boss the client shows me an error like "Missing reagent: Time-Lost Scroll".

How it works: You need to use the "Elixir of shadows" obtained from skyguards in the Skettis area (Terokkar Forest), killing the ghosts you can obtain the Time-Lost Scroll and with that you can summon 4 bosses clicking the bones in that area, but it seems the server doesn't recognize the item in the bag.

How it should work: 4 Bosses should spawns when you use the Time-Lost Scroll with that bones in the ground.

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
Please keep in mind that you need 10 scrolls for each of npcs. Are you sure that you have 10 scrolls not only 1?

**Comment by Dootz** [comment]
4/1/2020 works correctly. You need 10 scrolls https://www.wowhead.com/quest=11885/adversarial-blood#comments
