### ISSUE TITLE
Buffs and scrolls not stacking

### ISSUE THREAD

**Issue by apunar** [SunwellTracker/issues#3444]
Decription: Buffs are not stacking.

How it works: If you try to cast blessing of might on someone that has battle shout on, it will get removed. If you try to cast scroll of stamina on someone that has power word: fortitude on it will say a more powerful spell is already active.

How it should work: All the buffs should stack except for the same kind, you should not be able to cast multiple power word: fortitudes on people but different buffs should stack. for example you should be able to have blessing of might, battle shout and scroll of strength on at the same time.

Source (you should point out proofs of your report, please give us some source):

**Comment by styxel** [comment]
Kappa

**Comment by Azathothh** [comment]
Blessing of might IS same buff type as battle shout - you shouldn't be able to get benefit from both of them at same time.

**Comment by apunar** [comment]
I know it is the same buff type, that is exactly the issue, on retail you could stack them, you couldn't have more than one of the exact same buff on at a time but you could have for example, power word fortitude and commanding shout on at the same time or blessing of might and battle shout... AND scrolls. If this server is intending this difference then so be it, I am just reporting a "bug" compared to retail, which what I thought this bug tracker thing was for.

Here's proof of it in a icc raid on retail, if you look at the player at timestamp 0:40, he had power word fortitude AND commanding shout on. This video was posted 11 years ago, meaning before any private servers existed so it had to be retail. 
https://www.youtube.com/watch?v=GQsZb77iptM

**Comment by Azathothh** [comment]
Power word: fortitude and commanding shout are not the same type of buffs, PW:F gives stamina, CS gives hp, they should be stacking and they are stacking on Sunwell.

Armor Debuff (Major): Acid Spit (exotic Hunter pet), Expose Armor, Sunder Armor
Armor Debuff (Minor): Faerie Fire, Sting (Hunter pet), Curse of Recklessness
Physical Vulnerability Debuff: Blood Frenzy, (2nd Talent Spec TBA)
Melee Haste Buff: Improved Icy Talons, Windfury Totem
Melee Critical Strike Chance Buff: Leader of the Pack, Rampage
Attack Power Buff (Flat Add): Battle Shout, Blessing of Might
Attack Power Buff (Multiplier): Abomination's Might, Trueshot Aura, Unleashed Rage
Ranged Attack Power Buff: Hunter's Mark (only Hunters benefit, so no need to exclude against other class abilities)
Bleed Damage Increase Debuff: Mangle, Trauma
Spell Haste Buff: Wrath of Air Totem
Spell Critical Strike Chance Buff: Moonkin Aura, Elemental Oath
Spell Critical Strike Chance Debuff: Improved Scorch, Winter's Chill
Increased Spell Damage Taken Debuff: Ebon Plaguebringer, Earth and Moon, Curse of the Elements
Increased Spell Power Buff: Focus Magic, Improved Divine Spirit, Flametongue Totem, Totem of Wrath, Demonic Pact
Increased Spell Hit Chance Taken Debuff: Improved Faerie Fire, Misery
Percentage Haste Increase (All Types): Improved Moonkin Aura, Swift Retribution
Percentage Damage Increase: Ferocious Inspiration, Sanctified Retribution
Critical Strike Chance Taken Debuff (All types): Heart of the Crusader, Totem of Wrath
Melee Attack Speed Slow Debuff: Icy Touch, Infected Wounds, Judgements of the Just, Thunderclap
Melee Hit Chance Reduction Debuff: Insect Swarm, Scorpid Sting
Healing Debuff: Wound Poison, Aimed Shot, Mortal Strike, Furious Attacks
Attack Power Debuff: Demoralizing Roar, Curse of Weakness, Demoralizing Shout
Stat Multiplier Buff: Blessing of Kings
Stat Add Buff: Mark of the Wild
Agility and Strength Buff: Strength of Earth Totem, Horn of Winter
Stamina Buff: Power Word: Fortitude
Health Buff: Commanding Shout, Blood Pact
Intellect Buff: Arcane Intellect, Fel Intelligence
Spirit Buff: Divine Spirit, Fel Intelligence
Damage Reduction Percentage Buff: Grace, Blessing of Sanctuary
Percentage Increase Healing Received Buff: Tree of Life, Improved Devotion Aura
Armor Increase Percentage Buff: Inspiration, Ancestral Healing
Cast Speed Slow: Curse of Tongues, Slow, Mind-numbing Poison. 

If 2 spells are in same "category" it means they won't stack, for example Health Buff: Commanding Shout, Blood Pact - you can't have Commanding Shout and Blood Pact working at same time, you can gain HP only from one of them at a time.
