### ISSUE TITLE
macbook pro tearing graphic problem

### ISSUE THREAD

**Issue by hurysek** [SunwellTracker/issues#3445]
hello, 

since i updated my macbook to BIG Sur OS i have a big problems with tearing in the game. In the Cities everything is OK but in areas or dungeons is not even playable. 

would you help me with this situation? is it question of settings or is something wrong on the server? based on information from other forum(other free server) it must be solved by new patch (fix in code). 

thank you
Hurys

![IMG_4639](https://user-images.githubusercontent.com/76399792/102723573-2c2f5c00-4309-11eb-94ea-1dbcdba28099.JPG)
![IMG_4640](https://user-images.githubusercontent.com/76399792/102723579-35202d80-4309-11eb-9682-d5268eb347bf.JPG)
![IMG_4641](https://user-images.githubusercontent.com/76399792/102723581-3a7d7800-4309-11eb-9deb-623e4965304c.JPG)

**Comment by Azathothh** [comment]
This got nothing to do with the server - it's issue often happening on macbooks - if you're running it through Wine, you may want to try bootcamping Windows or running it in a virtual machine.
