### ISSUE TITLE
[Transmogrification] Npc cannot see an Item.

### ISSUE THREAD

**Issue by Highovsky** [SunwellTracker/issues#3446]
Hello

Decription: A Transmogrification NPC cannot see an Item [Claw of the Phoenix] . I would like to transmog my axes into [Claw of the Phoenix]. Unfortunately the NPC after I clicked option Main hand or Off hand is not showing the [Claw of the Phoenix] as available option for Transmogrification. The NPC still can transmog other fists weapons on my axes.

How it works: It's doesnt as I explained above. It's just the problem with [Claw of the Phoenix]. I checked already with few different ones weapons.

How it should work: If the [Claw of the Phoenix] is in my backpack/bank and I have [Weapon Transmog Token] the NPC suppose to see the [Claw of the Phoenix] as a available option for Transmogrification.

Source (you should point out proofs of your report, please give us some source): This is a screenshot from a game today 13:47 https://zapodaj.net/e5764fb373513.jpg.html
All weapons all available dagger,fist,axe. Just not the [Claw of the Phoenix]. :( Could you fix it please. I will be much appreaciate

**Comment by Azathothh** [comment]
How weapon transmogs works for different weapon types:
main hand - can be changed into "main hand" or "one-hand" (or "off hand" of same weapon type fist->fist, dagger->dagger etc.)
one-hand - can be changed into "main hand" or "one-hand" (or "off hand" of same weapon type fist->fist, dagger->dagger etc.)
off hand - can be changed into "off hand" (or "main hand" of same weapon type fist->fist, dagger->dagger etc.)

Claw of the Phoenix is "off hand" weapon type therefore it can be used as a transmog only for other fist weapons or "off hand" weapons.
Sorry but there are currently no plans in changing the way that it's working.
