### ISSUE TITLE
Cage wont open

### ISSUE THREAD

**Issue by Lilmollyog** [SunwellTracker/issues#3447]
Decription: During questline to get Master's Key (Karazhan). Quest "Escape from Durnholde" in The Old Hillsbrad Foothills, Caverns of Time.

During the quest I should be able to open the cage and then follow Thrall. But for some reason the cage will not open. The mouse doesnt show anything that I could interact with.

As seen in this video at 15:20
https://youtu.be/jiTHFKo4CKU

**Comment by Azathothh** [comment]
Everything is fine there, you have to kill first boss (Lieutenant Drake) in order to be able to start event with Thrall.
