### ISSUE TITLE
Divine Sacrifice and Blessing of Sacrifice cause pushback

### ISSUE THREAD

**Issue by mondegoftw** [SunwellTracker/issues#345]
Decription: The referred damage from Divine Sacrifice and Blessing of Sacrifice cause spell pushback.

How it works: If you cast a spell while damage is being referred from you having buffed a friendly target with Divine Sacrifice or Blessing of Sacrifice, the spell gets pushed back from the referred damage.

How it should work: Damage transfered through these spells should not cause pushback. It should register as damage taken (and should break CC-effects), 

Source (you should point out proofs of your report, please give us some source): Shouldn't really be needed, but just for good measure: https://youtu.be/erCP8ZyCbkc?t=723

**Comment by ujellyx** [comment]
confirmed.

**Comment by mondegoftw** [comment]
Bump. This is a pretty big error with a pretty easy fix. Let's go.

**Comment by mondegoftw** [comment]
Bug report up for 10 days, in progress for 6. Any updates?

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
