### ISSUE TITLE
Quest - The Disruption Ends 

### ISSUE THREAD

**Issue by Chryslol** [SunwellTracker/issues#3454]
The quest "The Disruption Ends" ( https://db.darkwizard.pl/?quest=872 ) is unlocked after completing "Supplies for the Crossroads" ( https://db.darkwizard.pl/?quest=5041 ) 
instead of after completing "Disrupt the Attacks" ( https://db.darkwizard.pl/?quest=871 ).

How it works:
"The Disruption Ends" ( https://db.darkwizard.pl/?quest=872 ) is unlocked after completing "Supplies for the Crossroads" ( https://db.darkwizard.pl/?quest=5041 ).

How it should work:
"The Disruption Ends" ( https://db.darkwizard.pl/?quest=872 ) should be unlocked after completing "Disrupt the Attacks" ( https://db.darkwizard.pl/?quest=871 ) 
just like "Supplies for the Crossroads" ( https://db.darkwizard.pl/?quest=5041 ).

Source (you should point out proofs of your report, please give us some source):
https://classic.wowhead.com/quest=872/the-disruption-ends
https://i.imgur.com/sKP1NBw.png
This link shows that "The Disruption Ends" requires only the completion of "Disrupt the Attacks" to be unlocked.

https://classic.wowhead.com/quest=871/disrupt-the-attacks
This link shows that "Disrupt the Attacks" unlocks both "The Disruption Ends" and "Supplies for the Crossroads".

**Comment by Veryapeman** [comment]
Yep true, this is bugged!

**Comment by joguel** [comment]
Bump :)
