### ISSUE TITLE
Feral druid omen of clarity

### ISSUE THREAD

**Issue by gandalkk** [SunwellTracker/issues#3459]
Decription: 
Omen of clarity procs on this server ( well known bug by now)

How it works: 
Omen of clarity procs from every consumable that does damage which is wrong. U can get massive amounts of ooc procs with : flame cap, stormchops, dragonbreath chili, fiery weapon etc basically anything that procs damage. 

Also tier 8 2set bonus is giving a 6% should chance on ooc proc which should be 2%.

How it should work: 
shouldnt proc from consumables

Source (you should point out proofs of your report, please give us some source):

**Comment by avarishd** [comment]
Bump, fix before season is out.

**Comment by NatsumeLily** [comment]
A bug like this was reported and it was fixed. The current behavior is correct but there was no ICD on the consumables. 
https://github.com/SunwellTracker/issues/issues/3136

**Comment by gandalkk** [comment]
Sunwell is the only private server where consumables Proc omen of clarity it was made possible after rizztaz or something like that rewrote omen of clarity so no, its not blizz like if thats what u want from this server.

Can u find any proof saying that those consumables should Proc ooc? Also true that theres no proof that they shouldnt but ud think that there was at least some info if it was blizzlike.

**Comment by avarishd** [comment]
@Riztazz Your favourite spell is back on the menu. Fix before season, ty
**LINKED WITH:** https://github.com/SunwellTracker/issues/issues/3539

**Comment by Riztazz** [comment]
Im gonna close this issue and keep the other one up since it's a bit better written
