### ISSUE TITLE
Webpage news bug?

### ISSUE THREAD

**Issue by Bartekkur1** [SunwellTracker/issues#3467]
Decription: After reading one of the news articles I noticed the id number in url. So the first thing I did was to change it into random number, mess around with it.

How it works: After passing to url a invalid article id webpage gives me a http 500 error.

How it should work: Idk. redirect me somewhere or say that this article doesn't exists, also I suggest to check if its not a security breach of any kind.

Source (you should point out proofs of your report, please give us some source): 
proper url: https://sunwell.pl/news/read/85
invalid url: https://sunwell.pl/news/read/213
![image](https://user-images.githubusercontent.com/15158339/109845813-d30b6f00-7c4d-11eb-9553-c9ffe6a6afc3.png)

**Comment by Raphtrack** [comment]
fixed
