### ISSUE TITLE
Website RAF link id bug

### ISSUE THREAD

**Issue by Bartekkur1** [SunwellTracker/issues#3469]
Decription:  I saw a reflink with id in it so the first thing I did was change it to whatever first came into my mind.

How it works: 

1. Copy RAF link from your ucp. https://sunwell.pl/register/<xxxx>
2. Instead of <xxxx >insert what ever you want.
3. Try to create account with it.
4. Get a http 500 from server.

How it should work: basically the same steps as above but It would be great if the <xxxx> was checked before submiting the form and notify user that his link is broken.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/15158339/109847167-2df19600-7c4f-11eb-8ee2-487028931f19.png)
![image](https://user-images.githubusercontent.com/15158339/109847193-35b13a80-7c4f-11eb-9847-aae2d995cc73.png)

**Comment by Raphtrack** [comment]
fixed
