### ISSUE TITLE
[WEBSITE] Change Password length bug

### ISSUE THREAD

**Issue by Krrl** [SunwellTracker/issues#3470]
**Decription:**
 Change password function does not allow passwords with length of 16. Receive error saying passwords can only be 16 characters long. I had to change my password to 15 characters to be able to change it.

**How it works:** 
Enter password of length 16, get error saying passwords can only be 16 characters long

**How it should work:** 
Enter password of length 16, allow password to be changed to a password of length 16.

**Comment by Raphtrack** [comment]
fixed
