### ISSUE TITLE
Website donation complain text size

### ISSUE THREAD

**Issue by Bartekkur1** [SunwellTracker/issues#3471]
Decription: I saw that I made a donation hour ago (which I did not, wtf more on that later) so I wanted to create complain. After I saw that sad textarea without styles I knew its gona be intresting.
The first thing I did was to send empty complain which I expected won't and then I went all in.
(Im sorry for that) I sent a whole "Pan Tadeusz" (436188 characters long) book as complain just to check if there is a character limit.
(https://wolnelektury.pl/media/book/txt/pan-tadeusz.txt)

How it works:

1. Go to https://sunwell.pl/donation/getComplain/- complain id here
2. Insert whatever you want in textarea
3. Send, get http 500

How it should work: 

1. Go to https://sunwell.pl/donation/getComplain/- complain id here
2. Insert whatever you want in textarea
3. Before or even after application (backend && frontend) should check the complain message length so that some 2iq boi from internet won't send you the whole book.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/15158339/109850848-42379200-7c53-11eb-9736-81e101ed194b.png)
![image](https://user-images.githubusercontent.com/15158339/109850905-524f7180-7c53-11eb-9310-8cae141f5fc5.png)

**Comment by Raphtrack** [comment]
fixed.
