### ISSUE TITLE
Website cart server error

### ISSUE THREAD

**Issue by Bartekkur1** [SunwellTracker/issues#3474]
Decription: Http 500 outta nowhere, after clicking "Exchange Coins for Services" I get a error.

How it works: 

1. Login in.
2. Go to shop.
3. Click on cart.
4. On popup click on "Exchange Coins for Services"
5. You see a http 500 error.

How it should work: 

1. Login in.
2. Go to shop.
3. Click on cart.
4. On popup click on "Exchange Coins for Services"
5. Idk maybe show something "Exchange Coins for Services" related. 
    Or is it a feature where I spent Voltarus Coins for a backend 500 error?

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/15158339/109852872-8f1c6800-7c55-11eb-9784-00652240c287.png)
![image](https://user-images.githubusercontent.com/15158339/109852922-9e9bb100-7c55-11eb-9493-d5bbfe6b8ca1.png)
![image](https://user-images.githubusercontent.com/15158339/109852945-a3f8fb80-7c55-11eb-98de-b84c543b086f.png)

**Comment by Raphtrack** [comment]
fixed
