### ISSUE TITLE
Main Page NavBar

### ISSUE THREAD

**Issue by wawel37** [SunwellTracker/issues#3477]
Decription: Navigation bar doesn't stick to the top panel which makes it (at least in my opinion) not look good.

![image](https://user-images.githubusercontent.com/17952406/109853627-63e64880-7c56-11eb-8633-27833fa1f6d6.png)

How it works: It doesn't stick to top panel

How it should work: It should stick to it

![image](https://user-images.githubusercontent.com/17952406/109854126-f5ee5100-7c56-11eb-8468-8fc96adbc475.png)

Fix: just delete the "top: 80px;" style from "nav_main" css class and "top: 115px;" to "top: 80px;" in "status-online" css class so the status box stick to the nav bar

**Comment by Raphtrack** [comment]
stylistic theme.
