### ISSUE TITLE
[Culling of Stratholme - Daily Quest] Adds despawning

### ISSUE THREAD

**Issue by Aizenscar** [SunwellTracker/issues#348]
Decription: 
http://wotlk.cavernoftime.com/quest=13243 - Need to kill 4 infinite agents, which spawn in 4 seperate packs, to complete the daily.

How it works: 
The first pack of adds(as you enter the town hall) that you need to kill for the quest randomly despawns(have had it happen twice but unable to reproduce 100%). 

How it should work: 
Mobs shouldn't despawn and the mobs should be killable.

Source (you should point out proofs of your report, please give us some source): 
Didn't manage to take any screenshots of the mobs despawning as it wasn't something we were expecting.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/574
