### ISSUE TITLE
Satchel of Helpful Goods

### ISSUE THREAD

**Issue by Vishiswaz** [SunwellTracker/issues#3484]
Decription: 
It's supposed to give gold and crafting mats. Currently it only gives the mats.

Source (you should point out proofs of your report, please give us some source): 
https://sunwell-community.com/topic/23694-voltarus-new-progressive-335-wotlk-realm/
![image](https://user-images.githubusercontent.com/78314117/109878577-735b9680-7c42-11eb-97cd-2d5f79dd8833.png)

**Comment by Azathothh** [comment]
Actually it was description for both satchels together, it wasn't supposed to mean that both satchels will drop both gold AND mats. Satchel of Leadership does provide small amount of gold+materials, this one was supposed to give only small amount of materials, as small bonus.

**Comment by Vishiswaz** [comment]
Okay, good to know!
