### ISSUE TITLE
Arcane barrage bug

### ISSUE THREAD

**Issue by jockeboschko** [SunwellTracker/issues#349]
Decription: 
You cant use Arcane missiles with missile barrage proc during arcane power when oom. 

How it works: 
You cant use Arcane missiles with misslie barrage proc during arcane power when oom. 

How it should work: 
Missile barrage should make arcane missiles free, So if you go oom during arcane blast spam you can throw out one last arcane missile. 

Source (you should point out proofs of your report, please give us some source): 
Tooltip

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
