### ISSUE TITLE
[Armory - Website] Naked characters

### ISSUE THREAD

**Issue by Turvek** [SunwellTracker/issues#3492]
Decription: 
Some chararacter appears naked with only weapons/helms on them

How it works: 
Look at random people and some of them are naked

How it should work: 
Gear should display properly

Source (you should point out proofs of your report, please give us some source): 
Example : 
https://sunwell.pl/armory/Voltarus/Nostorme
https://sunwell.pl/armory/Voltarus/Ohiv
![image](https://user-images.githubusercontent.com/66416151/109971501-9fd0ea80-7cf6-11eb-9ef3-6cc0ec65ca76.png)
![image](https://user-images.githubusercontent.com/66416151/109971517-a52e3500-7cf6-11eb-9ab3-048b578a1a83.png)

**Comment by Raphtrack** [comment]
fixed.
