### ISSUE TITLE
Quest : Gol'Dir

### ISSUE THREAD

**Issue by Whiterosee** [SunwellTracker/issues#35]
Decription: 
The quest is bugged.

How it works: 
You can't complete the quest after you obtain the key.

How it should work: 
You complete the quest by giving the orc the key.
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_012818_191642](https://user-images.githubusercontent.com/35897891/35484898-d324d062-045f-11e8-9276-212d7758a8a5.jpg)

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
