### ISSUE TITLE
[Armory - Website] Translation problem

### ISSUE THREAD

**Issue by Turvek** [SunwellTracker/issues#3508]
Description: 
When you click on armory and you search anyone you end up with a part in english and a part in another langage (polish I assume).

How it works: 
Display 2 differents langages.

How it should work: 
Either fully display in english or in this other langage.

Source (you should point out proofs of your report, please give us some source): 
https://sunwell.pl/armory/  + searching for anyone, you can try with my character : Lindzei
![image](https://user-images.githubusercontent.com/66416151/110101359-b7b27800-7da3-11eb-9eb0-b5a2964ed76f.png)

**Comment by Raphtrack** [comment]
fixed.
