### ISSUE TITLE
[Armory - Website] Highlighted problem

### ISSUE THREAD

**Issue by Turvek** [SunwellTracker/issues#3509]
Description: 
When you're on a profile on the armory, there is an highlighted problem except for "Character"

How it works: 
When you click for example on "talents", Character is the one that remains highlighted

How it should work: 
"talents" "achievements" "collections" "reputations" should be highlighted properly

Source (you should point out proofs of your report, please give us some source): 
https://sunwell.pl/armory/Voltarus/Lindzei/talents
https://sunwell.pl/armory/Voltarus/Lindzei/achievements
https://sunwell.pl/armory/Voltarus/Lindzei/reputations
![image](https://user-images.githubusercontent.com/66416151/110101909-6ce53000-7da4-11eb-8a84-c260b75e5d2d.png)

**Comment by Raphtrack** [comment]
fixed.
