### ISSUE TITLE
Bringing Down Heb'Jin not working

### ISSUE THREAD

**Issue by matthewhenke** [SunwellTracker/issues#351]
Decription: 
Striking Heb'Jin's Drum does not cause Heb'Jin to mount his bat atop the temple and fly down. Flying up and netting the bat does not cause Heb'Jin to be killable. Quest is currently not completable. 

How it works: 
Striking the drum doesn't cause Heb'Jin to fly down on his bat.

How it should work: 
Opposite of above.

Source (you should point out proofs of your report, please give us some source): 
![heb jin bug](https://user-images.githubusercontent.com/36052513/36046147-944b8f9c-0d9d-11e8-9149-20a02b9b8142.png)

**Comment by Avarishd** [comment]
bump, doesnt work

**Comment by Nadiirr** [comment]
Confirmed does not work.

**Comment by yak232001** [comment]
This is still not operational as of 2/15/2018

**Comment by asaphede** [comment]
still an issue of 2/26/2018. Made a new ticket also

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by Trsko** [comment]
If you still want to do this quest even if its bugged, wait until bat and heb'jin is alive, bang the drum wait until he comes down, dont use your net, just wait until he starts to attack you, takes like 5-7 seconds, then kill him. done.

**Comment by asaphede** [comment]
I thought about this, but never saw Heb'Jin alive. Always only the bat.
