### ISSUE TITLE
[Armory - Website] Second professions bars

### ISSUE THREAD

**Issue by Turvek** [SunwellTracker/issues#3516]
Description: 
When you're on the armory on a profile you can check the completion of a profession. Sadly secondary bars aren't working properly and only show them full

How it works: 
Bars doensn't fill properly

How it should work: 
Bars related to the profession should fill correctly

Source (you should point out proofs of your report, please give us some source): 
https://sunwell.pl/armory/Voltarus/Mefala
![image](https://user-images.githubusercontent.com/66416151/110122870-7e3c3580-7dc0-11eb-9f39-5aa3b91b4d32.png)

**Comment by Raphtrack** [comment]
fixed.
