### ISSUE TITLE
[Armory - Website] First aid icon not working

### ISSUE THREAD

**Issue by Turvek** [SunwellTracker/issues#3517]
Description: 
When you're on a profile on the armory if the player have first aid as a secondary profession it doesn't display properly.

How it works: 
First aid icon is not displayed at all

How it should work: 
First aid icon should be displayed properly

Source (you should point out proofs of your report, please give us some source): 
https://sunwell.pl/armory/Voltarus/Mefala
![image](https://user-images.githubusercontent.com/66416151/110123416-24883b00-7dc1-11eb-93cd-7c3a65b1d089.png)
https://sunwell.pl/armory/Voltarus/Healing
![image](https://user-images.githubusercontent.com/66416151/110123445-2f42d000-7dc1-11eb-878a-9021d77fab2a.png)

**Comment by Raphtrack** [comment]
fixed.
