### ISSUE TITLE
[Instance] The Culling of Stratholme - Wrong wave orders

### ISSUE THREAD

**Issue by avarishd** [SunwellTracker/issues#3518]
**This is on HC, but I assume its the same on normal** 

Decription:  Sometimes (In about 1 in 4) certain waves in CoS spawn at once, in essence sometimes you fight a boss with the previous wave. 

How it works: Wave order is wrong (sometimes)

How it should work: Waves should be linear, no skipping.

Source (you should point out proofs of your report, please give us some source): 
Do the dungeon few times and you'll see how they spawn 2 at once.
![1110](https://user-images.githubusercontent.com/46330494/110139988-4ba03600-7ddc-11eb-9d30-38fe2e0e9b8d.png)

Fighting boss with additional wave
![385b79dfd8de3551fe151e51af40aa2b](https://user-images.githubusercontent.com/46330494/110140644-f9134980-7ddc-11eb-99c9-088412fe9223.png)

**Comment by Vishiswaz** [comment]
I reported this already

**Comment by avarishd** [comment]
> I reported this already
Woops @Dootz duplicate with #3482

**Comment by avarishd** [comment]
> I reported this already

Woops, duplicate with #3482 @Dootz I'm closing it as it is the same report.
