### ISSUE TITLE
Children are stuck on the Stormwind bridge (Valley of Heroes)

### ISSUE THREAD

**Issue by Adso777** [SunwellTracker/issues#3528]
Description: Children are stuck on the Stormwind bridge (Valley of Heroes).

How it works: They are just standing there, as if waiting to be executed or something. Honestly it looks quite creepy.

How it should work: Following the matron around the city iirc.
![WoWScrnShot_030721_233845](https://user-images.githubusercontent.com/80226332/110257546-b0a38980-7f9e-11eb-8fd4-28d53cc28abc.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Azathothh** [comment]
https://wowwiki-archive.fandom.com/wiki/Children_of_Goldshire
These are not the children which are running around the Stormwind. I'm pretty sure that when they reach Stormwind gates, they will be there for ~10min and then move on.
