### ISSUE TITLE
Destruction Warlock: Conflagrate lag

### ISSUE THREAD

**Issue by mario8000** [SunwellTracker/issues#3529]
Decription: When putting up Immolate to then make Conflagrate available, you must wait 1 full GCD AFTER putting up Immolate for it to become available.

How it works: 
Finish applying Immolate

Wait 1 full GCD, cant cast conflag

Conflag then becomes available.

How it should work: 

Should be able to cast Conflagrate as soon as Immolate is applied to the target, no lag no waiting 1 GCD.

Source (you should point out proofs of your report, please give us some source): 

https://youtu.be/tjDkiNMAYlY?t=86 Video of someone testing this spell on a target dummy back in 2009 wotlk live.

**Comment by avarishd** [comment]
#2901 
https://github.com/SunwellTracker/issues/issues?q=warlock+Conflagrate+

**Comment by mario8000** [comment]
going to go ahead and close this due to other multiple youtube videos confirming that this appears to be actually correct. All videos ranging from 2009-2010

https://youtu.be/RsEgbFnAcBE?t=46
https://youtu.be/nhy2lYG8rto?t=32
https://youtu.be/6lWgDuUVwxE?t=165
