### ISSUE TITLE
Valiance Keep flying trainer not linked with rep correctly

### ISSUE THREAD

**Issue by exal99** [SunwellTracker/issues#3532]
Decription: 

According to [this](https://wowwiki-archive.fandom.com/wiki/Riding) WoWWiki article, if you are exalted with the Valiance Expedition Artisan Riding should only cost 4000g. However I'm exalted and still the cost is 4250g (see screenshot)
![bild](https://user-images.githubusercontent.com/20404499/110323818-6a3d4180-8015-11eb-83ae-e5da388ef0bc.png)

How it works: 
At exalted with Valiance Expedition artisan riding cost 4250g.

How it should work: 
At exalted with Valiance Expedition artisan riding should cost 4000g.

Source (you should point out proofs of your report, please give us some source):
[https://wowwiki-archive.fandom.com/wiki/Riding](https://wowwiki-archive.fandom.com/wiki/Riding)

**Comment by avarishd** [comment]
You're halfway through revered with Valiance Expedition on the picture you've posted.

**Comment by exal99** [comment]
Im dumb. Mixed Alliance Vanguard and Expedition.
