### ISSUE TITLE
Hall of Lightning Ionar damage immunity

### ISSUE THREAD

**Issue by NatsumeLily** [SunwellTracker/issues#3535]
Decription: Ionar is the 3rd boss in Halls of lightning. He should not be immune to any damage.

How it works: Ionar is currently immune to nature damage.

How it should work: He shouldn't be immune to any damage types.

Source (you should point out proofs of your report, please give us some source): https://www.wowhead.com/npc=28546/ionar#comments

> While the smaller air elementals before Ionar are immune to nature damage, Ionar himself is not immune to nature damage.

**Comment by Dootz** [comment]
Hi,
I looked around and WoWwiki has "Ionar is immune to nature based spell damage." in "Abilities" section https://wowwiki-archive.fandom.com/wiki/Ionar.  I tried to look in other places but no luck. So for now I don't think we should change it. But I'll leave this one open for some time.
