### ISSUE TITLE
[Quest] [11728] Wolf defecates too quickly

### ISSUE THREAD

**Issue by vanguardbug** [SunwellTracker/issues#354]
Decription: This is a quest that requires you to throw drugged meat to a wolf. The meat makes the wolf poop, you loot the poop to get Microfilm item.

How it works:  When you throw Wolf Bait (35121) at Oil-stained Wolf (25791), object Wolf Droppings (187981) appears immediately. Also, wolf's poop appears in the air, not at the ground.

How it should work: After using Wolf Bait at the Wolf, he should run a little bit, perform an emote and then defecate. 

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=BBt5omqHwgY

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
