### ISSUE TITLE
[Quest][Coldarra] Springing the Trap

### ISSUE THREAD

**Issue by Whodabaws** [SunwellTracker/issues#3543]
Decription: 
The quest "Springing the Trap" is not completing when it's supposed to.

How it works: 
After you summon Keristrasza, there is a short RP going on and then you get to fly with her, followed by Malygos coming for another short RP.The quest never completes though.

How it should work: 
When you start flying with Keristrasza, the quest should complete, while you continue watching some RP.

Source (you should point out proofs of your report, please give us some source):  https://www.youtube.com/watch?v=n_fVmqFpG1o you can see exactly when the quest completes

**Comment by Dootz** [comment]
Hi,

please make sure you're not in raid group, stay close to Keristrasza before Malygos is summoned, and it should work correctly.
