### ISSUE TITLE
Epic world BOE

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3544]
How it works: https://db.darkwizard.pl/?item=43573 has way higher chance to drop than 0.0.1%
How it should work: Make it like at most 1% ,just like https://db.darkwizard.pl/?item=37835 .

**Comment by Vishiswaz** [comment]
A guildie of mine was able to farm that item, yes. Shouldn't be possible.

Also worth noting, it's pretty clear that the numbers on the database do not reflect what we're seeing on Voltarus. Is the site not updated or something? Would be good to get clarification from the devs.
