### ISSUE TITLE
[Warlock][Spell][Talent] Soul Leech -  Does not heal

### ISSUE THREAD

**Issue by Jajcercovidzgon** [SunwellTracker/issues#3545]
Soul Leech does not heal

How it works: 

Gives your Shadow Bolt, Shadowburn, Chaos Bolt, Soul Fire, Incinerate, Searing Pain and Conflagrate spells a 30% chance to return health equal to 20% of the damage caused.

**Comment by Azathothh** [comment]
![obraz](https://user-images.githubusercontent.com/37483678/111658493-af7b2380-880c-11eb-94b2-abac6aa57294.png)

not sure how you tested it, but looks fine for me
