### ISSUE TITLE
Kreeg's Stout Beatdown doesnt stack with Well Fed buff

### ISSUE THREAD

**Issue by Basxd** [SunwellTracker/issues#3546]
Decription: 
Kreeg's Stout Beatdown doesn't stack with Well Fed buff. 

How it works: 
Currently, on Voltarus, the debuff from Kreeg's Stout Beatdown doesn't stack with the Well Fed buff from Fish Feast (or any other source for that matter)

How it should work: 
It should stack.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?item=18284

**Comment by avarishd** [comment]
Patch 3.3.0 (08-Dec-2009): The Spirit buff no longer stacks with other food and spirit buffs.
https://wowwiki-archive.fandom.com/wiki/Kreeg%27s_Stout_Beatdown
