### ISSUE TITLE
Rejuvenation - Idol of Awakening

### ISSUE THREAD

**Issue by 7Zup** [SunwellTracker/issues#3547]
Decription: 
The "Idol of Awakening" is an item that reduces the mana cost of the spell "rejuvenation".
On the description of the item it clearly says "Equip: Reduces the mana cost of Rejuvenation by 106".
But when I put it on, my Rejuvenation cost goes from 446 to 371, which is 75 mana, not 106 (so roughly the idol is 26% less interesting than it should be)

How it works: 
The item only reduces the spell cost for 75 mana.

How it should work: 
The item should reduces the spell cost for 106 mana.

Source (you should point out proofs of your report, please give us some source): 
![2021-03-17 10_00_18-World of Warcraft](https://user-images.githubusercontent.com/7067576/111441473-a6ecf500-8707-11eb-8751-f59b7887af5b.png)
![2021-03-17 10_00_03-World of Warcraft](https://user-images.githubusercontent.com/7067576/111441486-a9e7e580-8707-11eb-82e5-efb123285d4d.png)
![2021-03-17 10_00_57-World of Warcraft](https://user-images.githubusercontent.com/7067576/111441527-b1a78a00-8707-11eb-82a1-c9b58108c090.png)

We can see on those screenshots the mana cost printed at the bottom right corner with the Blizzard tooltip

**Comment by 7Zup** [comment]
Also, I saw that a similar post was closed on 2018 where you said it was working correctly even though that person provided clear screenshots just like I did.
I'm pretty sure I've encountered the same issue on Frosthold. Today i've decided to help community and share this to github, I hope you'll manage to correct this quickly since it is a major issue in the resto druid healing (rejuvenation is the spell we're using the most).

**Comment by NatsumeLily** [comment]
The idol reduces base cost, not current cost. The idol is working correctly.
(629-106) * (1-(0.2+0.09)) = 371.33

**Comment by 7Zup** [comment]
From where does that calcul come from ?
The idol says "Reduces the mana cost of Rejuvenation by 106", it does not says base mana cost. Therefore, the calcul should be "COST - 106" and not "COST - 106 * RANDOM_THING"

**Comment by NatsumeLily** [comment]
> 
> 
> From where does that calcul come from ?
> The idol says "Reduces the mana cost of Rejuvenation by 106", it does not says base mana cost. Therefore, the calcul should be "COST - 106" and not "COST - 106 * RANDOM_THING"

All items that reduce mana costs are base cost. That also isn't some random thing calc...

0.2 is 20% mana cost tree form talent
0.09 is 9% moonglow talent

**Comment by 7Zup** [comment]
Okay, I get that 20% & 9% mana come from now, thank you.
But at least the text should be changed from "mana cost" to "base mana cost" because its really confusing and you will get some others posts for that item.

Thank you for taking the time to explain it!
