### ISSUE TITLE
Tel'athion the Impure (multiple bugs)

### ISSUE THREAD

**Issue by Lenivietz** [SunwellTracker/issues#355]
Decription: 
Tel'athion just like Sunhawk Pyromancer does not cast his spells, also the Water elementals spawned by Call of Water shaman quest on Bloodmyst, that are meant to help out with the guy are set as yellow mobs and might aggro you when fighting him. Also triggering the barrel twice can spawn multiple instances of this boss and proportional amount of Water Elementals.
How it works: 
No spells are cast by Blood Elf NPCs on Bloodmyst. The Water Elementals spawned to help fight Tel'athion can be hostile

How it should work: 
Tel'athion can cast his spells. The elementals help you out with the fight instead of attacking. Triggering the barrel that summons him renders it unclickable.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
done
