### ISSUE TITLE
Quest: Deciphering the Journal

### ISSUE THREAD

**Issue by Kanchuu** [SunwellTracker/issues#3560]
Decription: Quest item isn't dropping off the quest mob at all. I'm not in a raid group, I've attempted it several times and have looked up a video to make sure I'm not just dumb. Linked in "Source" shows a video of how its supposed to work its pretty self explanatory. 

How it works: I've killed Grumbald One-Eye several different times with no luck of the item dropping, i've also abandoned the quest and picked it up, it seems as if it isn't working at all.

How it should work: The Spiritsbreath is supposed to drop off of Grumbald One-Eye.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=b8sUw2MOBJE

**Comment by Dootz** [comment]
Hi,

it took me three kills to get that item, we'll update the drop change slightly.

Thanks!

**Comment by Dootz** [comment]
should be fixed now
