### ISSUE TITLE
1handed "Savage Gladiator's" caster weapons do not give spellpower

### ISSUE THREAD

**Issue by Crushhymn** [SunwellTracker/issues#3561]
Decription: 
Savage gladiator weapons have been introduced through a custom vendor "Brom Gayserstick" in Underbelly Dalaran.
These items never made it into the game, and were only present on the betatest of WOTLK, as such their scaling is completely off.

How it works: 
Deadly Gladiator's Redoubt has the following stats at ilevel 213:
66 stam
29 int
66 spell power
19 mp5
37 resi

Compared Savage Gladiator's Redoubt, which at ilevel 200 has:
49 stam
21 int
28 resi

Which means the rare ilevel 200 equivalent stats are missing in the budget.

How it should work: 
It is hard to say, but could you atleast bring them into line? right now physicals get a huge boost, while casters are left with poor choices.
The other stats are increasing by an average of 34.9%, which means that 14 mp5 and 49 spellpower would be in the right alley.

Source (you should point out proofs of your report, please give us some source): 
https://wotlkdb.com/?item=42568 Stats are 100% equal to what is shown here.
The examply here is one of many, several offhands and even some mainhands for casters are like this.
Items:
Spellblade
Redoubt
Touch of Defeat
Piercing Touch
Barrier
Gavel

**Comment by Dootz** [comment]
Hi,

spell power was added couple days ago. If you can't see it in UI please clear "Cache" in your WoW directory.
