### ISSUE TITLE
Krol Cleaver not dropping from Reinforced Junkboxes

### ISSUE THREAD

**Issue by Browser8** [SunwellTracker/issues#3562]
Decription: Krol Cleaver not dropping from Reinforced Junkboxes and marked as unobtainable

How it works: Currently unobtainable

How it should work: Should be a drop from opening Reinforced Junkboxes as reported in https://github.com/TrinityCore/TrinityCore/issues/19776

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/56970567/112304616-99021b80-8c95-11eb-8c67-5f350c3baee0.png)
From sunwell database it says unavailable to players but the item was dropping in wotlk from Reinforced Junkboxes

**Comment by Dootz** [comment]
Hi,
actually it can drop, but the drop chance is lower than in attached TrinityCore link, so we'll update it.
Thanks

**Comment by Dootz** [comment]
should be fixed now.
