### ISSUE TITLE
Savage staff druid attack power 

### ISSUE THREAD

**Issue by Lunalobo** [SunwellTracker/issues#3567]
Decription:  Savage Gladiator's Staff has incorrect feral attack power bonus. 

How it works:  currently the savage gladiator staff has around 800-900 attack power bonus in druid forms. 

How it should work:  the savage gladiator staff should have the same attack power bonus for druid forms as the savage gladiator's pike, which is around 1600 attack power bonus in druid forms. 

Source (you should point out proofs of your report, please give us some source):  you can see in the vendors, for the deadly gladiator versions, the "deadly gladiator's staff" has the same exact attack power for druid forms as the Deadly gladiator's pike, so the savage versions should mirror that, and the savage glad. staff should have the same attack power for druid forms as the savage pike. i believe this to be a mistake and needs to be fixed, thank you!

**Comment by Dootz** [comment]
Hi,
bonus AP for ferals depends on weapons damage and speed. Current values look correctly, and on top of that Staff gives  you Agility. 
https://wotlkdb.com/?item=42388
