### ISSUE TITLE
Power Word: Shield

### ISSUE THREAD

**Issue by bubbleprocs** [SunwellTracker/issues#3571]
Decription: 
Trinket Sundial of the Exiled states "Your harmfull spells have a chance to increase your spell power" But 
priests spell Power Word: Shield activates it. That is not an offensive spell its just a absorb bubble for priest.
There are talents in discipline tree that make your bubble reflect damage, but trinket proccs when im in shadow 
spec.

How it works: 

If you cast spell power word: shield your trinket procs sometimes (often)

How it should work: 

I believe it should not activate the trinket because power word: shield is not an harmfull spell. It is in discipline school.

Source (you should point out proofs of your report, please give us some source): 

I'm playing shadow priest and it happens to me a lot when i use bubble. 
https://imgur.com/a/XaP22Oz
screenshot evidence here. I used bubble with no combat and trinket procs. (this was first try too.)

**Comment by Azathothh** [comment]
https://github.com/SunwellTracker/issues/issues/2606
that's blizzlike behaviour
