### ISSUE TITLE
Je'tze Bell

### ISSUE THREAD

**Issue by Soufly** [SunwellTracker/issues#3574]
How it works: I killed over 1000 vrykuls,and still 0 drops of Je'tze Bell with 0.1% drop chance based on your database.
How it should work: It should drop once per 1000 kills(at least with really bad rng).
@Dootz Can u confirm that the drop chance is 0.1% from the vrykuls ?
https://db.darkwizard.pl/?item=37835#dropped-by:0+8+1 
Edit: Damaged Necklaces indeed dropes once around 100 vrykuls with 1% drop chance.

**Comment by Dootz** [comment]
Hi,
 I can confirm it's set to 0.1%. I'll test it for some time and see if it drops. If it will be really bad we'll set drop chance a bit higher.

**Comment by longereaven** [comment]
What even is this logic? 0.1% doesn't guarantee a drop every 1000 kill. It can take you 1 kill or 1000000 kills, probability is probability. If the drop rate is set to 0.1%, as it should be, then there is nothing to be done. Stop grinding for world BoEs, lol.

**Comment by Dootz** [comment]
![obraz](https://user-images.githubusercontent.com/25490436/113335249-f5fc7200-9324-11eb-820c-32da72b0fc7f.png)
yup.. it's low chance but can be done. took me ~400 mobs for first drop. Closing for now
