### ISSUE TITLE
Prayer of Healing does not work with @mouseover

### ISSUE THREAD

**Issue by jlindamood** [SunwellTracker/issues#3575]
Decription: Prayer of Healing will always simply cast on self if attempting to `@mouseover `macro

How it works: 

How it should work: It should cast at the mouseover.

Source (you should point out proofs of your report, please give us some source):

**Comment by longereaven** [comment]
This is simply not true. I use a mouseover macro for it and it works.
This one will cast on yourself if you do not have a mouseover. If you have mouseover it will cast on that person.
#showtooltip Prayer of Healing
/cast [@mouseover, exists][@player] Prayer of Healing

**Comment by jlindamood** [comment]
I use the same macro for all raid heal spells, and I swear it did not work for the past 2 days, and checked the macro 20 times for typos. I guess some whitespace char or something was screwing it. Completely rewrote it yet another time and is working.
