### ISSUE TITLE
Savage Gladiator's totem of Indomitability not counted as a totem

### ISSUE THREAD

**Issue by exal99** [SunwellTracker/issues#3576]
Description: 
When [Savage Gladiator's totem of Indomitability](https://db.darkwizard.pl/?item=42593) is equipped and no other totem is present in my inventory I cannot use my totem spells because it says I'm missing the totems, see picture:
![bild](https://user-images.githubusercontent.com/20404499/113316473-ab6ffb00-930e-11eb-8641-65a21d7f5c14.png)

How it works: 
Savage Gladiator's totem of Indomitability is not counted as a earth, fire, wind and water totem.

How it should work: 
Savage Gladiator's totem of Indomitability should be counted as a totem of each type

Source (you should point out proofs of your report, please give us some source): 
Just look at the tooltip.

**Comment by Dootz** [comment]
should be fixed now. If you still see this issue please remove "Cache" from "wow" directory
