### ISSUE TITLE
Lava Burst Issue

### ISSUE THREAD

**Issue by Akodafest** [SunwellTracker/issues#3583]
Decription: I observed that when I canst Lava Burst on my shaman and then apply Flame Shock on target before the burst hits the target it doesn't count as being affected by Flame Shock and it doesn't crit...

How it works: Lava Burst doesn't crit when u cast eat before u put the Flame Shock on the target.

How it should work: Lava Burst should crit even if you apply Flame Shock after you cast Lava Burst

Source (you should point out proofs of your report, please give us some source): I don't have any video ;/

**Comment by Soufly** [comment]
![Capture](https://user-images.githubusercontent.com/36957911/113567176-c72d1700-9616-11eb-8321-52be553ae30b.PNG)
