### ISSUE TITLE
Escape from Durnhold

### ISSUE THREAD

**Issue by kmcnary** [SunwellTracker/issues#359]
Decription: 
You enter combat once thrall is released and it does not ever leave combat till last encounter. The last encounter we have seen the dragon desummon randomly. If you wiped on last boss which is easy because being stuck in combat our healers never got more mana you cannot re engage the final boss through conversation with thrall.

How it works: 
Stuck in combat through instance. Last boss wipe you cannot re initiate the fight.

How it should work: 
Combat should not persist throughout the event after thrall is released. The last boss should be able to be reset after speaking to thrall in hillsbrad town center.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Update:
lieutenant drake x3 first boss in the dung
thrall bugs out after a wipe or sudden unknown action and also npc quest giver at the end of the dung bugs out i need to kill it and respawn it .. then it works
