### ISSUE TITLE
Runemaster Molgeim bug in Ulduar Iron council

### ISSUE THREAD

**Issue by NatsumeLily** [SunwellTracker/issues#3594]
Decription: When Runemaster Molgeim is the last one alive he should get the ability Rune of Summoning.

How it works: Runemaster is casting Rune of Summoning when one of the other bosses is still alive. We only killed steelbreaker.

How it should work: Runemaster should only get/cast Rune of Summoning when he's the last one alive.

Source (you should point out proofs of your report, please give us some source): https://wowpedia.fandom.com/wiki/Assembly_of_Iron

> Rune of Summoning — Creates a Rune of Summoning near a random enemy. This rune will periodically summon Lightning Elementals, which will rush towards random enemies and explode. Only available with 2 stacks of Supercharge.

**Comment by Azathothh** [comment]
"Hard Mode Boost  Once Stormcaller Brundir is dead, Runemaster Molgeim will start to use Rune of Summoning as well. "
 https://sunwell-community.com/topic/24178-voltarus-ulduar-information/?tab=comments#comment-42543
It's part of the hard mode boost, so he will use it after Brundir death.

He will no longer use it when Steelbreaker dies but Brundir is still alive

**Comment by NatsumeLily** [comment]
Ok...Kinda stupid since that's not hardmode but nice to know it's not a bug.
