### ISSUE TITLE
[TBC Dungeons] Bosses Corpses despawn after kill

### ISSUE THREAD

**Issue by sicknot1** [SunwellTracker/issues#360]
![wowscrnshot_020918_213948](https://user-images.githubusercontent.com/35937937/36056855-cfb9b06a-0de6-11e8-91bf-bcb8ac4ee162.jpg)

![wowscrnshot_020918_213924](https://user-images.githubusercontent.com/35937937/36056834-ab0607fa-0de6-11e8-8dbc-56f367e83515.jpg)

![wowscrnshot_020918_213917](https://user-images.githubusercontent.com/35937937/36056833-a5768c06-0de6-11e8-9df1-8b6474111974.jpg)
Decription: The corpses of bosses simply dissapear

How it works: Bosses corpses dissapear, in my case i couldn't loot galgommar hand

How it should work: Bosses corpses should not dissapear

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_020918_213915](https://user-images.githubusercontent.com/35937937/36056831-9e76e306-0de6-11e8-8f59-16bbf2a90573.jpg)

![wowscrnshot_020918_213915](https://user-images.githubusercontent.com/35937937/36056861-e163bf40-0de6-11e8-9e35-90c2b8d3b057.jpg)
![wowscrnshot_020918_213917](https://user-images.githubusercontent.com/35937937/36056862-e1860be0-0de6-11e8-8adb-019d469133a1.jpg)
![wowscrnshot_020918_213924](https://user-images.githubusercontent.com/35937937/36056863-e1a94844-0de6-11e8-9047-1008ff53092c.jpg)
![wowscrnshot_020918_213928](https://user-images.githubusercontent.com/35937937/36056864-e1c9f17a-0de6-11e8-89a6-00be2fd90fac.jpg)
![wowscrnshot_020918_213948](https://user-images.githubusercontent.com/35937937/36056865-e1ef8ff2-0de6-11e8-968b-26fdfc1513f1.jpg)

**Comment by sicknot1** [comment]
bump

**Comment by Dootz** [comment]
Closing due to inactivty. Seems like this issue was fixed as part of different report. Tested it locally seems to be working alright.
