### ISSUE TITLE
[Parting Gifts quest] Available after completion.

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#361]
Decription: 
[Parting Gifts quest] Available after completion.

How it works: 
Quest is available (though doesn't complete a 2nd time) after already completing it and the rest of the chain through to the end (Bloodbane).

How it should work: 
Shouldn't have quest available after completion.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by smkrus** [comment]
I did this whole chain... yet the first part is still available to take...
http://wowwiki.wikia.com/wiki/Quest:Parting_Gifts
