### ISSUE TITLE
[Quest Missing] Of Keys and Cages

### ISSUE THREAD

**Issue by Jickk** [SunwellTracker/issues#362]
Decription: Quest unavailable at Camp Winterhoof from quest giver

How it works: No quest available for pick up at camp winterhoof. 

How it should work: Quest should unlock after "The Conquerer of Skorn" is completed

Source (you should point out proofs of your report, please give us some source): http://db.darkwizard.pl/?quest=11265

**Comment by Dootz** [comment]
Right now this quest is available after completing http://www.wowhead.com/quest=11260/stop-the-ascension . It'll be fixed so that http://www.wowhead.com/quest=11261/the-conqueror-of-skorn is prequest of http://www.wowhead.com/quest=11265/of-keys-and-cages

**Comment by Kokaina** [comment]
Fixed.
