### ISSUE TITLE
[Quest] It's All Fun and Games

### ISSUE THREAD

**Issue by Valmere** [SunwellTracker/issues#364]
Decription: 
This is the opening quest for The Ebon Blade from Thassarian that eventually grants access to The Shadow Vault. You're given a laser to shoot the big eyeball above the vault.

Apparently The Ocular, upon respawn, has a high chance of falling down from its spawn point and either landing on top of the Shadow Vault or dropping into it entirely, which gives the illusion of it not spawning.

~~After further testing it seems to be more client side than server - if someone is camping The Ocular for the respawn, it may appear to fall down from its post on their screen, but someone just entering the area may see the NPC in it's intended spot.~~

Not a (fully) client side issue, when The Ocular falls through you can leave and reenter the area but the NPC will still be in the vault instead of above it. You can still use the quest item on it though.

How it works: 
Fly up to The Ocular and kill it with the given quest item while mounted. NPC may or may not be present. After 5 minutes from being killed (personally timed) The Ocular will despawn and respawn ~3 minutes further, giving it an 8 minute respawn.

How it should work: 
Should work the same, preferably with a shorter respawn according to wowhead comments since it's a required quest to open up the Ebon Blade rep vendor.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29747/the-ocular#comments

another edit after the (most) recent server crash:

The Ocular fell through the vault again.
![image](https://user-images.githubusercontent.com/2462756/36060284-81bf0e18-0e14-11e8-8883-b2f7428fbb53.png)

**Comment by Dootz** [comment]
fixed, but someone forgot to close this issue.
