### ISSUE TITLE
ITEM QUEST MISSING

### ISSUE THREAD

**Issue by scv901025** [SunwellTracker/issues#365]
Decription:  Whitered Trolls in Zul'drak should drop one of these items  (Unliving Choker) or (Writhing Choker) to start a chain quest.

How it works:  trolls just dont drop the item

How it should work:  should have 100% drop after finished this quest (Kickin' Nass and Takin' Manes) in Ebon Watch.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=38660/unliving-choker#comments

**Comment by Avarishd** [comment]
Bump, killed about 30 of the Withered Trolls still no quest item.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/337
