### ISSUE TITLE
Looking for More/Many/Multitudes (achievement)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#369]
Decription: 
Completing 1 rhc counts as completing 4 on the achievement Looking for More/Many/Multitudes instead of doing 100 rhcs for the last achiev you need to do 4 times less

How it works: 

How it should work: 
1 random heroic completed should award 1/100 for achiev not 4/100

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
https://db.darkwizard.pl/?achievement=4476
https://db.darkwizard.pl/?achievement=4477
https://db.darkwizard.pl/?achievement=4478
These achievements are awarded for gruping up with 10/50/100 people using Dungeon Finder. You should get credit only on Random Heroics and for people thast you didn't group up while joining the que. So when you join que for Random Heroic  solo, you should get credit for 4 people.
