### ISSUE TITLE
[Durotar] Razormane Scout bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#37]
Decription: 
Razormane Scout's throwing weapon appears as a grid box.
Also this monster runs away too fast.

Edit: Might be client sided, but got confirmation from other sources too. Fleeing is too fast anyway.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_012818_204511](https://user-images.githubusercontent.com/30598442/35485207-38e59708-046d-11e8-8f94-31db045d1b07.jpg)
![wowscrnshot_012818_204514](https://user-images.githubusercontent.com/30598442/35485210-4111df68-046d-11e8-83ca-897267eef1ab.jpg)

**Comment by Riztazz** [comment]
I will look into it

**Comment by Riztazz** [comment]
Issue resolved, thanks for the report
