### ISSUE TITLE
Trinket Pendulum of Telluric Currents does not work at all

### ISSUE THREAD

**Issue by xyNNNNNNNNN** [SunwellTracker/issues#373]
Description: 
I've acquired the trinket "Trinket Pendulum of Telluric Currents" out of the Oculus on the 10th February.
After equipping and using it in a dungeon, I noticed there was no shadow damage applied by it in any way. I tried it on a Dummy with spells and normal melee attacks to check if I am not wrong later on. No effect occurred.

How it works: 
No shadow damaged applied at all.

How it should work: 
It should have a chance to apply 1168 - 1752 shadow damage.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
![wowscrnshot_021018_231002](https://user-images.githubusercontent.com/26198742/36067141-9f36555c-0eb7-11e8-8cbf-ddb511353d19.jpg)

It procs for me.
