### ISSUE TITLE
Vanish does not reset threat

### ISSUE THREAD

**Issue by Senex91** [SunwellTracker/issues#374]
Decription: 
Vanish does not reset threat.

How it works: 
After vanishing you still have threat/get attacked even if another party member has higher threat.

How it should work: 
Vanish should clear threat.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Vanish

**Comment by RoyaxCH** [comment]
Vanish can get resisted.
If a Boss resists your Vanish you won't drop from his Threattable. With multiple Mobs in the Room its possible that some drop you from their table and some resist your Vanish.

In this Case it would be important to see a Screenshot with Combatlog and a Threatmeter open.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
