### ISSUE TITLE
[NPC] Ironhand Guardian (Blackrock Depths)

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#375]
Decription: Theres a hall, where Ironhand Guardians stays on left and right, using their cannons to make flame all champions inside. They are untargetable, so players must run quickly through hall, dealing with boss at end.

How it works: Guardians flames onto players, but dont do damage. After boss kill ive got doubled one tick (left and right flame) for 500total.

How it should work: Players should burn while running into that hall.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=8982/ironhand-guardian Their one and onl;y spell "Gout of Flame"

**Comment by kovaq** [comment]
Gout of flame leaves a combat bug inside instance. Only last 2 guardians work.

**Comment by Dootz** [comment]
should be fixed now
