### ISSUE TITLE
[Dungeon Boss] The seven - Vile'rel (Blackrock Depths)

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#376]
Decription: 
I have low skilled skinning, and after boss kill i was able to use skinning on it. Its dwarf, humanoid, so its disgusting and it shouldnt be possible to do that.

How it works: Vile'rel is skinnable.

How it should work: You cant skin dwarf, its humanoid.

Source (you should point out proofs of your report, please give us some source): 
http://myprintscreen.com/s/1518299565.2799149.png

**Comment by Kokaina** [comment]
Fixed.
