### ISSUE TITLE
Sorlof's Booty

### ISSUE THREAD

**Issue by softlilkitten** [SunwellTracker/issues#377]
Decription: 
Sorlof seems to walk around his little stretch of land at high speeds, and 'The Big Gun' required for the quest seems to do no damage to him.

How it works: 
Sorlof seems to walk around his little stretch of land at high speeds, and 'The Big Gun' required for the 
quest seems to do no damage to him.

How it should work: 
Sorlof should be shootable with 'The Big Gun' and the sailors of the ship to get his Bounty which drops nearby

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/96
