### ISSUE TITLE
(Missing Quest)  Sub-Lieutenant Jax (Zul'drak- The Argent Stand)

### ISSUE THREAD

**Issue by scv901025** [SunwellTracker/issues#378]
Decription: he should give the quest (The Drakkari Do Not Need Water Elementals) after complete ( Strange Mojo) .

How it works: he doesnt give the quest.

How it should work: he should give the quest after complete Strange Mojo.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12562/the-drakkari-do-not-need-water-elementals

**Comment by Dootz** [comment]
After few local tests: currently he's offering this quest without any requirements.
