### ISSUE TITLE
[Outlands] - [Blade's Edge Mountain] - [Shard-Hide Boar]

### ISSUE THREAD

**Issue by Chpop** [SunwellTracker/issues#379]
Decription: 
No Shard-Hide Boars are spawning around Ogri'li line intended. These are a great source for LW mats and makes it tough to progress easily without the Ogri'li Spawns.

How it works: 
Does not spawn mobs.

How it should work: 
spawns mobs in these locations (see image)

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/npc=22180/shard-hide-boar
https://imgur.com/a/cYgyd

**Comment by Dootz** [comment]
will be fixed with next update
