### ISSUE TITLE
[Quest] Returning the Favor

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#380]
Decription: 
Quest [Returning the Favor](https://db.darkwizard.pl/?quest=9931#?ref=sunwell.pl) is not working properly. You can't use banners to all Warmaul ogres. 

How it works: 
Quest [Returning the Favor](https://db.darkwizard.pl/?quest=9931#?ref=sunwell.pl) is not working properly. You can't use banners to all Warmaul ogres corpses.  You only can use [Kil'sorrow Banner](https://db.darkwizard.pl/?item=25555) to [Warmaul Reaver](https://db.darkwizard.pl/?npc=17138#?ref=sunwell.pl) but you cant use banner to [Warmaul Shaman](https://db.darkwizard.pl/?npc=18064#?ref=sunwell.pl) corpses.

How it should work: 
[Kil'sorrow Banner](https://db.darkwizard.pl/?item=25555) should be usable to [Warmaul Reaver](https://db.darkwizard.pl/?npc=17138#?ref=sunwell.pl) and [Warmaul Shaman](https://db.darkwizard.pl/?npc=18064#?ref=sunwell.pl) corpses aswell

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed.
