### ISSUE TITLE
[Dungeon] - [Halls of Reflection] - [Lich King's Walls]

### ISSUE THREAD

**Issue by Artanis02** [SunwellTracker/issues#381]
Decription: 
The first frozen wall that The Lich King  (Third boss of the instance) created couldn't be destroyed by Sylvanas, even though the voicelines indicated that the dungeon progresses properly and she run forward through the wall. We couldn't move further and got caught by The Lich King.
After reentering the dungeon, the wall was still there, but Sylvanas didn't destrot it during second run, I think that The Lich King created a second one (stacked on the first one) and she destroyed only that one.

How it works: 
As described above, not sure if it's repeatable, but that's what we got today.

How it should work: 
After killing the thrash that The Lich King spawns, Sylvanas should destroy the frozen wall and We should be able to run forward.

Source (you should point out proofs of your report, please give us some source): 
Just now, me and 4 other people got that bug, didn't record any screenshots though.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.

**Comment by Artanis02** [comment]
It's OK. The bug didn't happen any other time after that day.
