### ISSUE TITLE
Ahn Kahet - Prince Taldaram

### ISSUE THREAD

**Issue by SpectraQWERTY** [SunwellTracker/issues#382]
Decription:  Prince Taldaram is overtuned and his Fire ball casts deals unreasonable amount of damage atm

How it works:  Prince Taldaram begins a cast, after it finishes, 3 balls of lava spawn, wich seem to have a really fast "attack speed". The laser wich they cast applies at an unreasonable speed and deals unreasonable amount of damage per each ball (approx 4.5k dmg per  0.5~1 second per ball(3 of them) = 12 ~ 24k DMG PER SECOND if u dont move out). Prince is basicly undoable with melee groups, and even hard with some ranged comps.

How it should work:  Prince taldaram fire ball cast should definately deal less damage, or apply in bigger intervals. It is impossible that this kind of bug went through the PTR phase of the server. I found some data and it states that the balls apply their 500 ~ 800 Resistable fire DMG laser every 0.5 ~1 seconds  (3 oft them) = 3k ~ 5.4k DMG (video shows spriest taking aroun 450 with some being resisted at times) 

Source (you should point out proofs of your report, please give us some source):  https://www.youtube.com/watch?v=huee-HZk7OI

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
