### ISSUE TITLE
[Quest] The Mosswalker Savior

### ISSUE THREAD

**Issue by Aizenscar** [SunwellTracker/issues#383]
Description: 
Quest requires you to interact with and save 6 Mosswalker victims.

How it works: 
Was able to interact and save the Mosswalker victims initially, however after I joined a bg and returned I couldn't interact with any of the victims and as such wasn't able to rescue them.

How it should work: 
Should be able to interact and rescue the victims as long as I have the quest.

Source (you should point out proofs of your report, please give us some source): http://wotlk.cavernoftime.com/quest=12580
http://www.wowhead.com/quest=12580/the-mosswalker-savior

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
