### ISSUE TITLE
[Quests] - [Orc/Troll staring location]

### ISSUE THREAD

**Issue by Artanis02** [SunwellTracker/issues#384]
Decription: 
I created two new characters to see how different classes play and I started doing quests as an orc and then as a troll. When doing a quest for sting of scorpions (LINK: https://wotlk-twinhead.twinstar.cz/?quest=789) I've noticed that even after completing it, the quest item (LINK: https://wotlk-twinhead.twinstar.cz/?item=4862) was still droping from the quest mob (LINK: https://wotlk-twinhead.twinstar.cz/?npc=3124). It was still dropping after I turned the quest in that was on 2 characters a few days ago.

How it works: 
Scorpid Worker mob drops Scorpid Worker Tail even after completing the quest or even after obtaining the total amount for the quest.

How it should work: 
The item should stop droping Scorpid Worker after obtaining 8 of them

Source (you should point out proofs of your report, please give us some source): 
No SS, sorry :(

**Comment by Artanis02** [comment]
Just checked, items still keep droping :)

**Comment by Dootz** [comment]
it will until fix goes live :D

**Comment by Kokaina** [comment]
Fixed.

**Comment by Artanis02** [comment]
Thank you! :)
