### ISSUE TITLE
[Dungeon] [Oculus] [Final boss chest]

### ISSUE THREAD

**Issue by Charless22** [SunwellTracker/issues#385]
Decription: 
Cache of the Ley-Guardian unable to loot the bag containing rare gems after the final boss. Died corpseran could roll for loot and loot the quest item for Daily Heroic but not the bag containing gems.

How it works: 
Cant loot the bag.

How it should work: 
Should be possible to loot the bag even after corpserun.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
