### ISSUE TITLE
Ferocious Bite

### ISSUE THREAD

**Issue by Catcore** [SunwellTracker/issues#387]
Decription: Ferocious Bite the Feral Cat Finisher doesnt deal damage based on energy spend

How it works: It deals the same amount of damage doesnt matter if you spend 65 or 35 energy

How it should work: Should deal more damage based on energy spent (up to a maximum of 30 extra energy)

Source (you should point out proofs of your report, please give us some source): 
 
Patch 3.0.9 (2009-02-10): This ability now only uses up to 30 energy in addition to its base cost. 
Patch 1.7.0 (2005-09-22): Damage per combo point has been increased. In addition, extra energy now converts to damage at a higher rate. 
https://gyazo.com/ed756c44536d7a8d3f9806e8a50c26be

**Comment by adamzimnyy** [comment]
Here's a 100 Bites done at 100 energy: https://i.imgur.com/yduYBqD.jpg
and here's a 100 Bites done at 35 energy: https://i.imgur.com/4bc5U8r.jpg

The average damage at 100 energy is about 16% higher. If you think these results are incorrect feel free to do your own testing and provide some actual statistical proof to support your claim.
