### ISSUE TITLE
[Core issue][Quests] Lootable quest object spawns 

### ISSUE THREAD

**Issue by DisMisaL** [SunwellTracker/issues#390]
Decription: Many quests in Wow upon completion spawn containers with quest objects that should be looted. However, looting of these is incorectly handled curently. (to note: I am making general bug report because doing particular for every quest like this would be tedious)

How it works: Curently, upon quest completion and container spawn, only one item could be looted form it, doesn't mater if completed in party  or even if someone else do it (not in your group, opposite faction). After first person loots his quest item it is not available for others.

How it should work:  Every person in party that is on that quest should be able to loot quest item from containers. For some quests even not grouped/opposite faction should be also, given that they were present at time of quest completion/container spawn.

Source (you should point out proofs of your report, please give us some source): Giving examples for some of quests I stumbled upon till now, will try to include more later:
- Betrayal (http://www.wowhead.com/quest=12713/betrayal) ZD quest: only one Drakuru's Skull lootable, where in wowhead commen ts from WOTLK era we can read (http://www.wowhead.com/quest=12713/betrayal#comments:id=372677:reply=439581) _'You can loot the skull if someone else (doesn't have to be in your party) kills him, while you are also there.'_ also for other person(s) involved: (http://www.wowhead.com/quest=12713/betrayal#comments:id=372677:reply=445989) _'Its not "ninja'ing", you can still get it.'_
- A Race Against Time (http://www.wowhead.com/quest=11671/a-race-against-time) BT quest: same as above, only one Salrand's Broken Key lootable, when reading through comments from WoTLK era: (http://www.wowhead.com/quest=11671/a-race-against-time#comments:id=442798:reply=360716) _'After you or someone else defeat Salrand the box will appear, then anyone can loot it.'_
...

I believe this issue is present in numerous other quests, will try to add more examples as I find them, but  my opinion it may be general fault in how are quest objects spawns handled.

**Comment by bongobg** [comment]
All over Northrend... :(

The most annoying ones with general "line" of people forcing PVP and clusters:
https://db.darkwizard.pl/?quest=11671
https://db.darkwizard.pl/?quest=11879
https://db.darkwizard.pl/?quest=12069

I get that object can be "ninjaed" but at least should be shared by party members. It's absolute hell on those quests now. Of course, there are many more out there.

**Comment by Dootz** [comment]
>     Betrayal 
>     A Race Against Time 

objects from those quest from next update will be lootable by all party members
