### ISSUE TITLE
Note from the Grand Admiral (Drop chance bugged)

### ISSUE THREAD

**Issue by Doublespoons** [SunwellTracker/issues#391]
Decription: The drop rate on this item is lower than normal. It's a low chance as is, but so far i've dumped the quest items in order to get keys to open chests 4 times.

How it works: On the quest Intelligence Gathering you have to kill Scarlet mobs in the Onslaught Harbor to Obtain keys which will unlock chests for the quest. Doing so will have a chance to drop an item that starts a chain quest starting with Note from the Grand Admiral.

How it should work: You should get keys on Intelligence Gathering and open the chests to recieve the item. It's noted to have between a 10% drop chance, but it's less than that on this realm. Not sure the actual %, but it's definitely not 10%. I've done this quest recently on Live servers within the last year and cant recall the having this much difficulty with the quest either on Live or on another private server using Trinity Core. I know this is Sunwell Core, but i had this issue on Feenix's Realm of Shadows aswell which was also Sunwell Core. 

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/item=40666/note-from-the-grand-admiral#contained-in-object
all the correct information should be in the comments, from my experience it's checked out over the years of doing this quest. If you need more Sources I can attempt to dig up videos, but most likely none will talk about the drop chance.

**Comment by Doublespoons** [comment]
Also once the quest is completed you can no longer recieve keys. I deleted the quest items after completing the quest to get more keys and keep trying to get the drop. Right after this post I kept at it waiting for a GM ticket to be answered and got it on my 1st chest. To anyone curious it does drop, but it took me 5 attempts at the quest.

**Comment by Dootz** [comment]
Keys only drop if you're on quest, that's intended behaviour described in comments (http://www.wowhead.com/item=40652/scarlet-onslaught-trunk-key#comments). About drop rate: it will be slightly increased.

**Comment by Doublespoons** [comment]
Right the Key comment was for anyone who came to look at the bugtracker by chance. Also thanks you.

**Comment by Kokaina** [comment]
Fixed.
