### ISSUE TITLE
[Class] Rogue - Kick issue.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#392]
Decription: It seems that Fireball cant be kicked by rogue, but for example Warrior interrupt without problems.

How it works: Fireguard Destroyer's Fireball cant be kicked by rogue. 

How it should work: Fireball should be interrupted by kick.

Source (you should point out proofs of your report, please give us some source):

**Comment by kovaq** [comment]
The same for Mistress of Doom's Rain of Choas. Kick lands, no interrupt.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
