### ISSUE TITLE
QUEST  The Tome of Divinity

### ISSUE THREAD

**Issue by Cpburk** [SunwellTracker/issues#393]
Decription: 
Paladin Quest for the spell  Redemption

How it works: 
You take quest and dont get the item you need to finnish quest

How it should work: 
You take the quest and the quest giver should give you "Symbol of life" and it does not.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
This quest chain consist of many parts all of which are called "The Tome of Divinity (Part X of 8)". So i'm not sure at which stage you have problem. I was able to complete this chain. I got my Symbol of life from this guy: http://www.wowhead.com/npc=6171/duthorian-rall

**Comment by Dootz** [comment]
It'll be fixed so that when you lose Symbol of Life you can talk to http://www.wowhead.com/npc=6171/duthorian-rall for quest http://www.wowhead.com/quest=1790/the-symbol-of-life that will give you new quest item without requirement.
