### ISSUE TITLE
The Hunter and the Prince (

### ISSUE THREAD

**Issue by Doublespoons** [SunwellTracker/issues#394]
Description:  Someone failed the quest previously and once I started the quests there were 2 Illidans. After I failed the quest and retook it to start again there were 3 Illidans.

How it works: Once you fail the quest the previous Illidan doesn't despawn.

How it should work: There should be one Illidan in the fight.

Source (you should point out proofs of your report, please give us some source):  
https://www.youtube.com/watch?v=FjrLouOl_aI

**Comment by Doublespoons** [comment]
Had another test it out that was here with me and was told there was 1 Illidan, so it was on my end for failing the 1st quest that lead to multiple spawns. 1 spawn for everytime i failed. I'm very good at this game.

**Comment by Dootz** [comment]
will be fixed with next server update
