### ISSUE TITLE
Cloak of Bloodied Waters

### ISSUE THREAD

**Issue by Kaliram** [SunwellTracker/issues#395]
Decription: 
This item is currently unobtainable according to your database.

How it works: 
It does not drop from Gun'drak heroic, or anywhere else

How it should work: 
It should drop from all trash mobs in heroic Gun'drak trash mobs.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=37647/cloak-of-bloodied-waters&bonus=4117#comments

**Comment by Dootz** [comment]
Hi, there's small chance to get it from gundrak mobs  (http://www.wowhead.com/item=37647/cloak-of-bloodied-waters&bonus=4117#dropped-by). Website db is not 100% accurate
