### ISSUE TITLE
Bone Shield charges have no internal cooldown and loses charges to dots

### ISSUE THREAD

**Issue by Vidia2** [SunwellTracker/issues#396]
Description: 
Issue 1 - As you know, Boneshield charges can be consumed at a 1 per 2 second rate, no matter the number of attacks. Sadly, here either the cooldown is missing or is under 2 seconds. 
Issue 2 - Charges should never be consumed by auras or dots.

Make no mistake, these issues are BIG. Boneshield is a core spell for both pvp and unholy tanks.

How it works: 
1- When you are hit very fast, the charges dropped down like there is no 2 seconds internal CD or the internal CD is like 0.5 seconds or something like this. 

2 - Boneshield loses charges to dots and it shouldn't.

How it should work: 
No matter how fast you are hit, or how many times, the charges should not drop more than 1 per 2 seconds. Also, charges should never be consumed by auras or dots.

Source (you should point out proofs of your report, please give us some source): 
**See patch 6.0.2 changes, the internal cooldown was increased to 1 second. You can understand that the internal cooldown was indeed 2 seconds beforehand, and since it was released there were no mentions of the internal cooldown changed during wrath.**
http://wowwiki.wikia.com/wiki/Bone_Shield 
https://wow.gamepedia.com/Bone_Shield 

https://github.com/DoctorCookie/WoWIL-Issues/issues/2
You can see here other players reporting same issues in other githubs 

**Archived old posts from wowhead
https://web.archive.org/web/20150318041115/http://www.wowhead.com/spell=49222/bone-shield#comments**
"Bone Shield has a 2 second hidden cooldown for the charges. If you get hit twice in 2 seconds it will only consume one bone.
"all damage taken while you have at least 1 charge up is reduced, so if you had 4 mobs on you and all 4 hit you within 1 sec, you would lose only 1 charge, but reduce the damage of all of the incoming attacks during the cooldown time s well With 4 Charges this gives you ~6 seconds of 20% reduced damage intake"

Regarding dots, you can see everywhere that this spell SHOULD NOT consume charges if you are hit by a dot or aoe or auras. Here is the archived version of wowhead from 2008:
https://web.archive.org/web/20150318041115/http://www.wowhead.com/spell=49222/bone-shield#comments

**FYI, it seems that DoT effects don't use charges, but still have their damage reduced.** 

https://firestorm-servers.com/en/report/see_report/38439

**Comment by Sunwellxd** [comment]
BUMP!

**Comment by Riztazz** [comment]
Just tested with warlock corruption and it does reduce its damage and doesnt take charges. Also tested with casts which have around 0.8 cast time and im losing one stack on 3rd cast received so overall looks okay to me, i will more data. 

https://youtu.be/YUg4wUnDpdQ
