### ISSUE TITLE
[Flight Path][Wintergrasp] Player on FP automatically booted to Icecrown

### ISSUE THREAD

**Issue by whitestar87** [SunwellTracker/issues#397]
Decription: 
If a player is flying from Dalaran to Sholazar basin on a flight path, their gryphon passes over wintergrasp.  If wintergrasp is currently in progress and FULL, the player is booted to the spot in icecrown.  

How it works: 
If a player is flying from Dalaran to Sholazar basin on a flight path, their gryphon passes over wintergrasp.  If wintergrasp is currently in progress and FULL, the player is booted to the spot in icecrown.  

How it should work: 
Players on flight paths should be ineligible to que for wintergrasp.  Even if qued, players on flight paths passing over wintergrasp on flight paths should be unaffected by it.

Source (you should point out proofs of your report, please give us some source):

**Comment by whitestar87** [comment]
Also works going the opposite way, from Sholazar to Dalaran.

**Comment by Riztazz** [comment]
Fixed
