### ISSUE TITLE
Grant a level & Slave market

### ISSUE THREAD

**Issue by gitghost** [SunwellTracker/issues#4]
Decription: 
Postacie kupione na Slave Markecie nie mają możliwości oddawania leveli po wyexpieniu na nowym koncie za pomocą "grant a level". Są zarejestrowane jako postacie w rafie ponieważ działa exp i działa summon a friend.

How it works: 
Kupujesz postać na poziomie poniżej 78. Expisz. Po dwóch wbitych poziomach na postaci powinna istnieć możliwość oddania zarobionego poziomu na konto w RAFie. Niestety teraz opcja grant a level jest 
cały czas na szaro.

How it should work: 
Po kupieniu postaci powinny się naliczać poziomy do oddania. Jeden za każde dwa poziomy wbite na nowym koncie. Po wystawieniu na slave market liczba poziomów do oddania powinna być zerowana, niezależnie czy ktoś kupi postać czy nie.

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
