### ISSUE TITLE
Visual bug after leaving party

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#400]
Decription: 
After leaving party sometimes I get some visual bug which looks like my party members would be disconnected, relog fixes this.
http://prntscr.com/id8nsv
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
