### ISSUE TITLE
[Bossy ICC-TOC-ULDU][parry-haste]

### ISSUE THREAD

**Issue by Sensza** [SunwellTracker/issues#401]
Decription: 
"After a successful parry, the defender's "swing timer" is reduced by 40% of your weapon speed (or even reset), unless this would result in a reduction to less than 20% of your swing time remaining. "
http://wowwiki.wikia.com/wiki/Parry

How it works: 
Na tę chwilę prawie wszystkie raidowe bossy na wotlku mają aktywną mechanikę parry-haste.

ICC: 
The Lich King: https://imgur.com/a/UFeNa  22.49.37.984 - 22.49.38.235 = 0.749s melee swing.
Blood queen lana'thel: https://imgur.com/a/88HbU   21.28.12.422 - 21.28.11.191 = 1.231s melee swing.
Prince Valanar: https://imgur.com/a/0MCje   21.20.52.553 - 21.20.51.253 = 1.3s melee swing.
Professor Purtricide: https://imgur.com/a/iVOST  21.07.04.261 - 21.07.03.486 = 0.775s melee swing.
Festergut: https://imgur.com/a/ui1Tl  20.43.39.376 - 20.43.38.510 = 0.866s melee swing.
Rotface: https://imgur.com/a/hrdls  20.51.44.170 - 20.51.42.625 = 1.545s melee swing.
Deathbringer Saurfang: https://imgur.com/a/Tou6J  20.32.24.002 - 20.32.23.706 = 0.296s melee swing.
Lord Marrowgar: https://imgur.com/a/ivu5z  20.10.09.286 - 20.10.08.417 = 0.869s melee swing. Ponadto umiejętność Bone Slice(cleave) również nie powinna reagować na mechanikę parry-haste(obecnie reaguje).

TOC:
Anub'arak: https://imgur.com/a/1qpRf  21.05.46.490 - 21.05.45.386 = 1.104s melee swing.
Lord Jaraxxus: https://imgur.com/a/tG3N3  21.00.46.584 - 21.00.44.930 = 1.654s melee swing.
Gormok The Impaler: https://imgur.com/a/iedC2  20.52.59.091 - 20.52.58.168 = 0.923s melee swing.

ULDUAR:
General Vezax: https://imgur.com/a/bC1OU  21.57.54.261 - 21.57.53.169 = 1.092s melee swing.
Mimiron(Leviathan MK II): https://imgur.com/a/hMwK3  21.42.45.236 - 21.42.43.605 = 1.631s melee swing.
Freya: https://imgur.com/a/MpQHh  21.28.39.736 - 21.28.38.174 = 1.562s melee swing.
Hodir: https://imgur.com/a/b8Jpa  21.08.48.775 - 21.08.47.582 = 1.193s melee swing.
XT-002 Deconstructor : https://imgur.com/a/3rbfg  20.27.56.861 - 20.27.55.703 = 1.158s melee swing.
Ignis The Furnace Master: https://imgur.com/a/xQADo  20.18.19.986 - 20.18.19.309 = 0.677s melee swing.

NAXX:
Niesprawdzany.

How it should work: 
Mechanika parry-haste została prawie całkowicie zablokowana na wotlku https://www.mmo-champion.com/threads/1018040-Is-Parry-Haste-still-active-on-bosses, poza paroma wyjątkami m.in. Halion, Sindragosa, Onyxia itp(głównie smoki). 

http://web.archive.org/web/20100520020046/https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/
W tym miejscu, gdy mechanika jeszcze występowała na oficjalnych serwerach  - dzielono się spostrzeżeniami dotyczącymi parry-haste i wg badań tylko 2 encountery na ICC i 1 na TOCU(robaki+icehowl) posiadają tę mechanikę aktywną. Można to w prosty sposób potwierdzić przeglądając liczne logi z http://www.worldoflogs.com/ranking/eu-us/icecrown-citadel/dps/ , http://www.worldoflogs.com/ranking/eu-us/crusaders-coliseum/dps/ , http://www.worldoflogs.com/ranking/eu-us/ulduar/dps/.

Tutaj kilka zdjęć potwierdzających wyniki z powyższej strony:
ICC - https://imgur.com/a/16TQ8
TOC - https://imgur.com/a/7qd4L
ULDU - https://imgur.com/a/Lyqbi
Wszystkie przypadki parry'owania uderzeń przez bossy zostały wyszukane w taki sposób, aby występowały w jak najkrótszym odstępie czasu od poprzedniego melee swinga, żeby sprowokować maksymalne skrócenie czasu do następnego melee swinga bossa(tym samym ułatwiając rozpoznanie parry-haste).
Jedynymi przypadkami występowania parry-haste w Ulduarze, które udało mi się znaleźć to Thorim(http://www.worldoflogs.com/reports/rt-4qWFkgCZqKfJ76lQ/log/?s=3720&e=3907) i Aurayia(http://www.worldoflogs.com/reports/rt-s1koytmkouttibt0/log/?s=3142&e=3297).
Należy zwrócić uwagę, że czasy pomiędzy melee swingami poszczególnych bossów były ustawione inne niż na Sunwellu(dlatego nie należy porównywać zdjęć z logów z oficjalnych serwerów z tymi wykonanymi na Feronisie). Najprawdopodobniej u większości bossów ustawiono u nas melee swing timer na 2s-2.5s, gdyż nie znano prawidłowych wartości.

Na Naxxramas należy przeprowadzić podobne badania, lecz najprawdopodobniej jedynym bossem, który  powinien korzystać z parry-haste to Sapphiron i ewentualnie Grobbulus/Kel'Thuzad(do sprawdzenia).

Source (you should point out proofs of your report, please give us some source): 
http://www.worldoflogs.com/reports/rt-l3gzmcjx6nx2uenv/log/?s=403&e=608
http://www.worldoflogs.com/reports/1vpkqy7a07j9mwoa/log/?s=2247&e=2367
http://www.worldoflogs.com/reports/vweyx535vlctx49l/dashboard/?s=10007&e=10168

**Comment by Kokaina** [comment]
Mnie z kolei interesowałby w luj ten post:
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/
Temat z 15.01.10r czyli data dobra - sporym minusem są jednak linki, które dawno powygasały gdzie gościu pozamieszczał niby dowody oraz sam addon parry-haste, który napisał :/ W jednym z Twoich linków znalazłem też wpis "Like others mentioned it started to get removed in ICC besides Deathwhisper & Sindragosa. But also Halion had it when RS was released."

Sugerując się po datach wypowiedzi ludzi, mam wrażenie że parry-haste było obecne na progressie zarówno na Tocu, jak i na ICC, a dopiero z patchem 3.3.3+ (czyli jakoś w marcu gdy wszedł Halion a LK był ubity) to go zdejmowano (+boostowano aure na ICC) żeby ułatwić pugom raidowanie, i ograniczono się z tą mechaniką wyłącznie do paru bossów, w tym Lady, Sindry czy Haliona. Imo potrzeba jeszcze więcej danych choć nie powiem, że jak teraz poczytałem to pozostawienie samej mechaniki p-h na progress ICC niebywale mnie kusi ;d

**Comment by Kokaina** [comment]
Mnie z kolei interesowałby w luj ten post:
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/
Temat z 15.01.10r czyli data dobra - sporym minusem są jednak linki, które dawno powygasały gdzie gościu pozamieszczał niby dowody oraz sam addon parry-haste, który napisał :/ W jednym z Twoich linków znalazłem też wpis "Like others mentioned it started to get removed in ICC besides Deathwhisper & Sindragosa. But also Halion had it when RS was released."

Sugerując się po datach wypowiedzi ludzi, mam wrażenie że parry-haste MOGŁO być obecne na progressie zarówno na Tocu, jak i na ICC, a z czasem było ściągane, finlanie zostawiając to tylko kilku bossom. Imo potrzeba jeszcze więcej danych, wertuje sobie teraz logi z uldu 2k09 i dobrnąłem już do Hodira gdzie nie spotkałem się jeszcze z p-h mimo ze parry wchodziło srogo. Skończę research to ogarniemy do końca

**Comment by Sensza** [comment]
Do dowodów można się dostać poprzez web.archive.org (np. poprzez link, który podałem, albo ten poniżej). http://web.archive.org/web/20100521042451/http://maintankadin.failsafedesign.com:80/forum/index.php?p=540182&rb_v=viewtopic#p540182
Addonu niestety żadnego nie znalazłem, ale zwracałem uwagę, żeby wszystkie moje zdjęcia pochodziły właśnie z logów wykonanych w 2009(w przypadku uldu) niestety na screenach pokazana jest tylko data dd-mm.

Co do samego komentarza na mmo-champion to najprawdopodobniej icc było tylko najbardziej znanym przypadkiem ze względu na ten solidnie wykonany artykuł z Avenging Wrathy. Wcześniejsze contenty mogły być tak mało istotne pod względem P-H(ignorowano tę mechanikę lub wszyscy zakładali jej obecność na każdym bossie), albo wszystkie artykuły na ich temat dawno już przepadły w czeluściach internetu. Takie gadanie, że niby P-H było wszędzie aktywne można znaleźć w kilku miejscach, lecz nigdzie nie podają żadnych dowodów, zatem musi to wynikać jedynie z przezorności graczy i ich doświadczeń z tą mechaniką na TBC. 
Np. http://web.archive.org/web/20090308024039/http://blue.mmo-champion.com/12/13129903275-parry-hasting--was-it-removed.html trudno było to odkopać, ale w tym temacie oficjalnie przyznają, że mają możliwość wyłączania parry-haste i z niej korzystają, lecz jak na złość nie podano oficjalnej listy tych bossów poza Patchwerkiem :(

**Comment by Sensza** [comment]
A skoro już mowa o srogim parry'owaniu to u nas tak wygląda Kologarn: https://imgur.com/a/Dhzqi, natomiast na oficjalnym serwerze parry było u niego wyłączone(http://www.worldoflogs.com/reports/idElxGkScZqU6ogG/log/?s=12153&e=12386). Na szczęście jest to jedyny boss, z którym się zetknąłem na contentach T8+ mający wyłączone parry-haste.
