### ISSUE TITLE
Watts My Target / Static Shock Troops: The Bombardment

### ISSUE THREAD

**Issue by Nexao** [SunwellTracker/issues#402]
Decription: 
The two quests "Watts My Target / Static Shock Troops: The Bombardment" in Icecrown for alliance at least

How it works: 
It does not allow the player to repair the airplane and therefore causes you to be shotdown / plane burns up eventually

How it should work: 
It should be possible to repair the airplane / use the green shield

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
