### ISSUE TITLE
[NPC] Wooly Mammoth Bull

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#403]
Decription: 
This bull works up to hp regen.

How it works: 
If you dimount the bull he runs back to its spawn location. However he does not reset his HP.

How it should work: 
If dismounted should run back to spawn and hp should reset

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/c08f31b182ba15a1796138c5fd7c75f4

https://db.darkwizard.pl/?npc=25743

**Comment by TheRealestMcCoy** [comment]
Adding more to this after you kill kaw they become hostile again they should reamin friendly the rest of the time and never go back hostile after kaw is dead. You did save them.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
