### ISSUE TITLE
Mage Tier 7 - 2 Set Bonus Not Working With Macro

### ISSUE THREAD

**Issue by Clubhead** [SunwellTracker/issues#404]
Decription: When Using a Macro to trigger all Mage Cooldowns, the Tier 7 2Set Bonus of consuming a Mana Gem for increased SP does not work.

How it works: Using the Cd Macro does not trigger Mana Surge (SP bonus from set bonus), but the gem is consumed. But if the gem is consumed outside of the macro Mana Surge does trigger.
Example:
/Cast Arcane Power
/Cast Icy Veins 
/Use 13 (trinket) 
/Use Mana Sapphire
When using this Macro does not trigger the Spell Power from consuming the Mana Sapphire. Changing the order of spells trigger makes no difference.

How it should work: Using the Macro above should trigger the set bonus on consumption of the Mana Gem. 

Source (you should point out proofs of your report, please give us some source): Mages - Synthetic (me) and Selphie have both tried and have achieved the same result, even with a different Macro setup. Feel free to contact me in-game for further questions. Synthetic Alliance Mage.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
