### ISSUE TITLE
CTA BG (angrathar only)

### ISSUE THREAD

**Issue by feralxgodx** [SunwellTracker/issues#405]
Decription: 
W tym miesiącu zbugowało się cta na bg- w piątek było eots, w sobotę ioc- czyli właściwe, a w niedzielę wsg.

How it should work: 

Call to arms powinno być przez weekend na 1 bg- w tym tygodniu na isle of conquest
Source (you should point out proofs of your report, please give us some source): 

Dodam, że na feronisie działa poprawnie.

**Comment by sitowsky** [comment]
Problem był związany z wyłączonym sezonem, już rozwiązane.
