### ISSUE TITLE
Quest:Monitoring the Rift: Sundered Chasm

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#406]
Decription: 
I'll cast a spell that will enable you to breathe underwater. If it wears off before you find it, come let me know and I'll renew its effects.

How it works: 
Librarian Garren does not grant the water breathing buff. Nor does she have the gossip text to give it again.

How it should work: 
Once you accept the quest you should get the buff to breath under water. He should also offer a gossip option to be re granted the buff it it falls off.

Spell ID
http://www.wowhead.com/spell=52909/water-breathing
Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/c31f282c6e394a2b0e253e2c6cbdb680

**Comment by Kokaina** [comment]
Fixed.
