### ISSUE TITLE
[Violet hold] Not all levers are accounted for

### ISSUE THREAD

**Issue by Sweet-lou** [SunwellTracker/issues#407]
Decription: 
Levers on the wall that are used to help groups clear the dungeon are not all clickable

How it works: 
There's 3 on the ground floor, and 2 on higher levels. We noticed this when we were going for an achievement but were unable to click 4 of the 5 levers. This has been the case in the last two days, they used to work.

How it should work: 
All 5 levers should be clickable.

Source (you should point out proofs of your report, please give us some source): Two days ago I attempted the Defenseless achievement in H VH to get closer to my red proto drake, unfortunately it was a failed attempt. This puzzled me since the prison integrity was at 100% and no levers went off. Upon attempting Dehydration the next day, my group and I realized not all levers were clickable and that must be interfering with obtaining some of these crucial achievements

**Comment by Afgann** [comment]
Fixed
