### ISSUE TITLE
Unfit For Death (Borean Tundra Quest)

### ISSUE THREAD

**Issue by Deltrii** [SunwellTracker/issues#408]
Decription:   Trappers not being trapped when fake fur is placed.

How it works: Placing fur on traps does nothing.

How it should work: NPCs are supposed to become trapped.

Source (you should point out proofs of your report, please give us some source):

**Comment by TheRealestMcCoy** [comment]
The issue is the traps are not despawning after some one uses it like they should.

**Comment by Riztazz** [comment]
duplicate https://github.com/SunwellTracker/issues/issues/275
