### ISSUE TITLE
Ingvar the Plunderer Bug

### ISSUE THREAD

**Issue by xethra89** [SunwellTracker/issues#409]
Decription:  Last boss role-play bug happens when pet is attacking still during transition.

How it works: 
DK Pet attacking a dead NPC. Causes the RP to re-start over and over and over.

How it should work: 
Only start once. 

Source (you should point out proofs of your report, please give us some source): 

https://clips.twitch.tv/TenderVastSharkMingLee - Clip of the bug.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
