### ISSUE TITLE
[ITEM] The Black Heart

### ISSUE THREAD

**Issue by Aqua1234** [SunwellTracker/issues#41]
Decription: 
[The Black Heart](https://wotlk.evowow.com/?item=47216) działa w sposob niepoprawny.

How it works: 
Trinket ma proc w momencie gdy gracz **zada obrazenia**.

How it should work: 
Trinket powinien dzialac w momencie **otrzymania obrazen** przez gracza.

Source (you should point out proofs of your report, please give us some source): 
[The Black Heart](https://wotlk.evowow.com/?item=47216)

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
