### ISSUE TITLE
Quest:Last Rites-Minor

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#410]
Decription: 
Voices missing from RP.

How it works: 
The quest it self works but the voice over for the talking RO is missing

How it should work: 
They should actually speak words when they talk not just chat or chat bubbles.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12019/last-rites

Video with voice over from 2008 
https://www.youtube.com/watch?v=wx4XEnUkGhk

**Comment by Dootz** [comment]
will be fixed with next update
