### ISSUE TITLE
Quest:The High Commander Halford Wyrmbane 

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#411]
Decription: 
You are to deliver the MIssive to Wintergarde Keep. 

How it works: 
You accept the quest nothing happens but you accept the quest.

How it should work: 
Upon accepting the quest it should place you on a gryphon to fly you to Wintergarde Keep. 

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12174/high-commander-halford-wyrmbane

2008 Video
https://www.youtube.com/watch?v=qyfhdocFEi0

**Comment by Dootz** [comment]
will be fixed with next update
