### ISSUE TITLE
NPC: Blighted Elk

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#412]
Decription: 
Spawn Issues

How it works: 
There are double and triple spawns. Stacked spawns and tight spawns

How it should work: 
Spawns should be more spread and less stacked.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=26616/blighted-elk

https://gyazo.com/05cdf47d723ac7f51886159618d35888

**Comment by TheRealestMcCoy** [comment]
See if this will work?



`DELETE FROM `creature` WHERE `id`=26616;
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 4703.28, -1091.26, 166.104, 0.392838, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 4568.49, -1205.54, 158.215, 5.83221, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3325.29, -1375.41, 100.069, 2.32917, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3401.97, -1342.63, 111.059, 1.07044, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3453.7, -1293.49, 117.711, 6.09862, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3687.4, 2523.55, 105.774, 1.67799, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3333.11, -1511.01, 91.1843, 0.317737, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3432.76, -1481.03, 105.647, 5.92442, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3420.66, -1405.59, 104.178, 4.18403, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3650.16, 2694.04, 93.0145, 3.90979, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3776.81, -1494.91, 145.086, 4.22778, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3711.27, -1486.57, 136.187, 0.637468, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3355.91, -1445.69, 99.9143, 3.76413, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3657.13, 2461.63, 100.719, 4.23128, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3623.42, 2708.84, 85.8237, 2.06854, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 4535.77, -1237.42, 156.673, 6.22344, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 4554.45, -1141.69, 166.21, 1.47447, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3676.26, 1942.34, 81.9083, 3.79478, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3787.14, 1919.85, 95.5226, 4.58021, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3661.34, 2054.15, 80.7318, 2.77774, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3783.33, 2129.4, 91.174, 2.81697, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3790.64, 2020.64, 92.1446, 1.9371, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3671.85, 1995.67, 82.3485, 2.96183, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3686.97, 1992.51, 84.1838, 1.33032, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3778.38, 1894.68, 97.6998, 2.83263, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3796.52, 2000.48, 92.7097, 5.10853, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3620.1, 2723.46, 82.6987, 1.71371, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3645.3, 2680.39, 94.2473, 5.85676, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3681.55, 2772.65, 93.0234, 2.33, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3687.78, 2215.51, 86.6158, 3.23328, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3745.76, 2233.6, 93.1961, 2.76991, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3687.66, 1917.99, 83.5604, 1.08516, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3771.96, 2083.14, 92.8602, 4.85507, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3666.73, 2450.92, 104.069, 5.57032, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3712.64, 2730.54, 107.848, 1.94515, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3686.85, 2313.24, 92.3132, 0.804839, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3689.4, 2281.94, 90.0056, 4.50177, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3802.27, 1897.2, 100.196, 5.56195, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3789.73, 1990.23, 92.4449, 1.34041, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3745.36, 1920.18, 92.5819, 1.21657, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3734.03, 2048, 90.0601, 2.91911, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3705.05, 1946.01, 85.2816, 0.963423, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3637.83, 2165.7, 81.2966, 2.224, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3627.64, 2126.14, 78.5819, 4.95405, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3657.28, 2126.45, 81.9555, 1.44257, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26616, 571, 0, 0, 1, 1, 23952, 0, 3628.52, 2687.63, 89.6433, 4.98396, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
`

**Comment by Dootz** [comment]
will be fixed with next update
