### ISSUE TITLE
NPC:Rabid Grizzly

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#413]
Decription: 
same as elk

How it works: 
same as elk

How it should work: 
same as elk

Source (you should point out proofs of your report, please give us some source): 
https://github.com/SunwellTracker/issues/issues/412
http://www.wowhead.com/npc=26643/rabid-grizzly

**Comment by TheRealestMcCoy** [comment]
`DELETE FROM `creature` WHERE `id`=26643;
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4775.35, -1108.63, 171.967, 6.00281, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4773.4, -1023.23, 179.201, 0.640571, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4581.62, -1198.65, 160.002, 2.37001, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3317.53, -1443.27, 99.4378, 0.622847, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3363.57, -1343.25, 104.804, -2.92204, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4580.25, -1256.73, 156.208, 5.99594, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3370.11, -1420.21, 100.755, 3.20803, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3429.11, -1348.26, 107.019, 3.2886, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3736.9, -1504.18, 138.429, 3.19433, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3384.09, -1489.22, 100.377, 1.58413, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3826.17, -1495.93, 144.924, 3.06646, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4738.65, -1146.04, 168.441, 1.5132, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 4538.59, -1153.93, 162.503, 0.139135, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3699.17, 2061.01, 86.52, 0.771047, 90, 0, 0, 9291, 0, 0, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3738.48, 2102.7, 89.5162, 3.98328, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3636.68, 2105.3, 82.1167, 3.95977, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3652.86, 2184.98, 83.5728, 2.16121, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3720.78, 2270.92, 95.0649, 0.633557, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3707.31, 2232.98, 89.6201, 4.88263, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3822.77, 1878.3, 104.886, 4.5999, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3710.54, 1907.92, 87.0284, 4.39954, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3685.01, 2031.42, 84.609, 0.401864, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3722.03, 2077.1, 89.6397, 3.08788, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3681.39, 2253.82, 88.6157, 3.09585, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3881.92, 1849.58, 120.573, 1.24525, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3791.22, 1864.72, 105.05, 2.42534, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3717.08, 2082.21, 89.5943, 3.39585, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3727.76, 1965.59, 88.016, 4.49685, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3723.91, 2017.22, 88.7692, 4.92693, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3655.75, 2155.04, 80.2051, 2.45961, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3760.39, 2254.2, 97.8124, 2.82096, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);
INSERT INTO `creature` (`id`, `map`, `zone`, `area`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `walkmode`) VALUES (26643, 571, 0, 0, 1, 1, 23966, 0, 3772.63, 1939.72, 93.697, 1.8627, 90, 5, 0, 9291, 0, 1, 0, 0, 0, 0);`

**Comment by Dootz** [comment]
will be fixed with next update
