### ISSUE TITLE
QUEST:To Stars' Rest!

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#414]
Decription: 
When you are ready I will place you on my fastest gryphon to Stars' Rest. Once you get there, find and speak with Archmage Modera.

How it works: 
You accept the quest that is it you are forced to basically run.

How it should work: 
Upon accepting the quest you should be put on a gryphon and fly back to stars rest

Source (you should point out proofs of your report, please give us some source): 

http://www.wowhead.com/quest=12440/to-stars-rest

2008 Video Proof
https://www.youtube.com/watch?v=Ihefwpe6H_g

**Comment by Dootz** [comment]
will be fixed with next update
