### ISSUE TITLE
Verog the Dervish mob spawn apparently bugged

### ISSUE THREAD

**Issue by whyhallothar** [SunwellTracker/issues#415]
Decription: While attempting to complete the quest [Verog the Dervish] I circled the command hut for 30minutes killing kolkar and the quest mob never spawned.

How it works: You kill all the kolkar in the world and nothing happens.

How it should work: Verog spawns and emotes something after 5-10 kolkar kills in the area.

Source (you should point out proofs of your report, please give us some source):

**Comment by aglarcz** [comment]
Verog (https://db.darkwizard.pl/?npc=3395) should spawn after killing few kolkar mobs in Stagnant oasis, but he doesnt spawn at all. Mobs needed to be killed are https://db.darkwizard.pl/?npc=3274 and https://db.darkwizard.pl/?npc=3397.

**Comment by Dootz** [comment]
he spawns, but chance for it is small - as it should be, according to wowhead comments..
