### ISSUE TITLE
[Dungeon] Shadowfang Keep lever bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#417]
Decription: 
Lever didn't work for us, so we weren't able to proceed after the 1st boss.

How it works: 
Lever wasn't clickable this time.

How it should work: 
It should trigger the cage to open.

Source (you should point out proofs of your report, please give us some source): 
Can't attach screens due to party left.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/978
