### ISSUE TITLE
[NPC] Southsea Cannoneer doesn't shoot

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#418]
Decription: 
Southsea Cannoneer in The Barrens doesn't shoot, it goes straight melee combat even when pulled from far distance.

How it works: 
NPC doesn't shoot.

How it should work: 
NPC should shoot if pulled from the distance before going melee. Was like that since vanilla.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=3382/southsea-cannoneer#abilities

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
