### ISSUE TITLE
[Dungeon] Dire maul north scarab skinning

### ISSUE THREAD

**Issue by ghertruda** [SunwellTracker/issues#419]
Decription: Dire maul north is a popular location to farm rugged leather, nonetheless here the scarabs (and spiders and scorpids??) drop a wrong type of leather

How it works: those mobs are level 54-56 and drop a light leather, light hide and a ruined leather scraps which is leather level around 1-15

How it should work: those mobs should have the same loot table for leathers as a mob that has level 55 - 58, also on top of it they should all be scarabs, no scorpids no spiders

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021218_093231](https://user-images.githubusercontent.com/36400119/36088524-e6dcb9b6-0fd7-11e8-8e23-4a3b0ba878e2.jpg)
look in chat for the loot table, was lucky to catch all three of those, added a dot in chat to confirm timestamp

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
