### ISSUE TITLE
Razorfen Beastmaster Shoot animation

### ISSUE THREAD

**Issue by PowerKeeper666** [SunwellTracker/issues#42]
![wowscrnshot_012818_204512](https://user-images.githubusercontent.com/24966676/35486291-44be5bce-046c-11e8-8226-89ecec4e59b1.jpg)
Decription: http://db.darkwizard.pl/?npc=4532 Razorfen Beastmaster is a mob in Razorfen Kraul instance, before the bat caves

How it works: Razorfen Beastmaster shoots people with a cube instead of a normal arrow

How it should work: attack animation should be updated to use one of the arrow

Source (you should point out proofs of your report, please give us some source):

**Comment by inscaped** [comment]
Same thing with Razormane Scouts in Durotar.

**Comment by Riztazz** [comment]
Alright, i have fixed a few and implemented logs to detect others that have issues and will fix them on the fly :P

**Comment by Kokaina** [comment]
Already fixed.
