### ISSUE TITLE
[Scarlet Monastery Cathedral] Final boss disappear

### ISSUE THREAD

**Issue by Beheri** [SunwellTracker/issues#420]
Decription: 
When party killed Scarlet Commander Mograine and High Inquisitor Whitemane wanted to ressurect him, she ran straight past the wall and disappear.

How it works: 
High Inquisitor Whitemane doesn't ressurected Scarlet Commander Mograine. Just ran to the wall and past this wall and start to losing health. In some time she disappear or probably she died past the wall.
After this in some time High Inquisitor Whitemane ressurected himself but with low hp (maybe 1hp) because he was easy to kill, and this isn't end this dungeon. High Inquisitor Whitemane still didnt show herself after this.

How it should work: 
Inquisitor Whitemane wanted wouldn't run to past the wall,  she would always ressurect Scarlet Commander Mograine and be in boss room.

Source (you should point out proofs of your report, please give us some source):  Don't have

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
