### ISSUE TITLE
[NPC] Scourge War Machine

### ISSUE THREAD

**Issue by Valmere** [SunwellTracker/issues#421]
Decription: 
NPC in Icecrown needed for a bomber quest. They are currently spawning at southern Aldur'thar for some reason (54, 46) making questing in the area more difficult than it should be.

How it works: 
They're spawned in a place they shouldn't be.

How it should work: 
They're not supposed to be spawned here. I don't think they're supposed to be able to attack or be attackable either, which they currently are. That's what makes them such a pain in the ass at the moment.

Source (you should point out proofs of your report, please give us some source): 
It doesn't seem like many people recorded themselves doing random quests in this area, the best I could find are WoD+ videos of people coming back and doing old content. That said, this area hasn't changed from when it was current content so I believe these videos are accurate as far as NPC placement goes.

https://www.youtube.com/watch?v=EcfPVpz-c_4
https://www.youtube.com/watch?v=6ys9ZYrnOYs

There are no war machines spawned in either of those videos in the Aldur'thar area.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
