### ISSUE TITLE
 [The Storm King's Vengeance] - Quest bug

### ISSUE THREAD

**Issue by aquafina2222** [SunwellTracker/issues#424]
Decription: 
 [The Storm King's Vengeance] - ZulDrak quest is bugged after Gymer is hit with mobs several times. Abilities are not being used and the tooltip does not show up when mousing over the abilities.

How it works: 
Begin quest by riding on Gymer. Using abilities for roughly 60 seconds before he just stops and bugs out. Still be able to move and be attacked, but not able to use abilities.

How it should work: 
Uses the 4 abilities when riding Gymer to destroy the scurge and the 3 bosses surrounding the area. 

Source (you should point out proofs of your report, please give us some source): I had 2 different GM's reset the quest for me with in a matter of 10 minutes @ 3:15PM Server time on Alliance.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
