### ISSUE TITLE
Shaman Talent [Ancestral healing]

### ISSUE THREAD

**Issue by Popeno99** [SunwellTracker/issues#426]
Decription: 
This tallent not working

How it works: 
its not working

How it should work: 
After crit heal proc Passive 

My nick Greenstory
Source (you should point out proofs of your report, please give us some source):

**Comment by Crackaw** [comment]
Works fine. Any proof or something?

**Comment by Cwiercpasiec** [comment]
http://www.worldoflogs.com/reports/5oguxwbmxga69jf0/details/18/?s=1845&e=1999 Logs from my guild's ToGC 25. One of Buffs cast by our resto shaman: 
Ancestral Fortitude | 84 | 147.3 | 95.0 %
