### ISSUE TITLE
Quest: The Caverns of Time

### ISSUE THREAD

**Issue by vanguardbug** [SunwellTracker/issues#427]
Decription: Custodian of Time doesn't work correctly

How it works: Custodian of Time stays for 1 minute, then walks to 1 spot and stays. Has no dialogues.

How it should work: https://www.youtube.com/watch?v=-O2gL8LJM1g

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=-O2gL8LJM1g

**Comment by vanguardbug** [comment]
Also they should have random models - belf female, human female and draenei fmelae, they are on Sunwell (Custodian of Time) already near Culling of Stratholme entrance. But ones that spawn from quest are always blood elf.

**Comment by Dootz** [comment]
that one is a bit broken. If you stay close to her she'll move around caverns and you can complete quest. Dialogues only appear in chat

**Comment by TSSchoof** [comment]
Dialogues doesn't appear anywhere for me. My chat settings are default, I don't see anything appear. 
![wowscrnshot_030318_114620](https://user-images.githubusercontent.com/2319986/36933422-9adea83e-1ed8-11e8-893c-688e43178cd5.jpg)

**Comment by Dootz** [comment]
Will be fixed with next server update
