### ISSUE TITLE
[Hellfire peninsula - FPS DROP] Zeth'gor Cauldron

### ISSUE THREAD

**Issue by sicknot1** [SunwellTracker/issues#428]
Decription: If your visual range reachs the cauldron for the boling blood quest, your fps drops significantly, might be related to the spawning neutral mobs.

How it works: FPS drops significantly when close to the Cauldron

How it should work: FPS shouldn't drop

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021218_155233](https://user-images.githubusercontent.com/35937937/36114076-af6af638-100d-11e8-9a6a-58cbe19e1b8d.jpg)
![wowscrnshot_021218_155237](https://user-images.githubusercontent.com/35937937/36114126-d489329a-100d-11e8-8feb-e0c478a17654.jpg)

SPECS: 
gtx 1060 3gb
AMD fx 6300 6core
8gb ram

**Comment by isaacm1** [comment]
It's definitely a thing, i dropped from 200 fps to like 40-80.

i7 7700k 4.2ghz
gtx evga 1080 sc
16gb ddr4 ram
windows 10
