### ISSUE TITLE
Quest ''In Dreams'' is not working properly

### ISSUE THREAD

**Issue by sedamjegera** [SunwellTracker/issues#430]
Decription: While escorting Highlord Taelan Fordring through Hearthglen and out of it, at a point he stops and doesn't want to run anymore he stays there and he should call out for High Inquisitor Issilien and die there fighting againts him.

How it works: After running from Hearthglen , Highlord Taelan Fordring stops at the scarlet crusades watchtower and stays there unmovable.

How it should work:  Highlord Taelan Fordring should when he stops at the Scarlet's watchtower yell for Isillien and fight with him, after that, Highlord Taelan should die from Isillien and Tirion Fordring should spawn at our location near the Scarlet Watchtower, mourn the death of Highlord Taelan Fordring and fight with High Inquisitor Isillien.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=-stssicOz0M
![in dreams bug](https://user-images.githubusercontent.com/36422598/36118708-47d37ab4-103e-11e8-9b63-82f11f76c442.png)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
