### ISSUE TITLE
Sharptalon, Ashenvale hunt

### ISSUE THREAD

**Issue by rajy89** [SunwellTracker/issues#431]
Decription: Sharptalon, Ashenvale hunt

How it works:  When grouped up and killing sharptalon for the ashenvale hunt quest he only dropped a talon for one person.

How it should work: The talon should drop for everyone in the group that tagged him. Regardless of previous quest history.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
