### ISSUE TITLE
[Quest Tracker] Quest tracker not working properly

### ISSUE THREAD

**Issue by Runare** [SunwellTracker/issues#432]
Decription: 
When I open world map more than once in a game session, quest objectives aren't located properly or aren't in world map anymore. Reloading game will help only for one world map opening.

How it works: 
Quest objectives are not located properly after opening world map more than once.

How it should work: 
Quest objectives should be located at correct places at any given time.

Source (you should point out proofs of your report, please give us some source): 
1st opening
![sunwell quest objectives before](https://user-images.githubusercontent.com/36425790/36124653-8532315a-1059-11e8-9bdf-cf65d9bbd30e.jpg)
2nd one
![sunwell quest objectives after](https://user-images.githubusercontent.com/36425790/36124646-7f4cfe82-1059-11e8-9894-09907913e3fd.jpg)

**Comment by Runare** [comment]
Note: Upper one is the 1st opening and lower one is the 2nd one.

**Comment by Runare** [comment]
Note: Lower one is 1st opening and upper one is 2nd one.

**Comment by Azathothh** [comment]
Client issue - same thing was happening on retail : https://us.battle.net/forums/en/wow/topic/1127123822#post-13
In order to "fix" that you have to abandon all quests
