### ISSUE TITLE
[General] Can't land by logging out

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#433]
Decription: if you log out while flying, you continue to fly, but you're supposed to land

How it works: if you log out while flying, you continue to fly

How it should work: if you log out while flying, you should land on the nearest stop

Source (you should point out proofs of your report, please give us some source): https://gaming.stackexchange.com/questions/59746/is-it-possible-to-cancel-flight-ride

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
