### ISSUE TITLE
[NPC] Skinning Trainer in Silvermoon City

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#434]
Decription: 
Skinning Trainer in Silvermoon City stands in the wrong place.

How it works: 
Stands behind the wagon and looking at it.
![wowscrnshot_021318_033729](https://user-images.githubusercontent.com/30598442/36127592-5f0afa14-106f-11e8-98fb-874079590124.jpg)
![wowscrnshot_021318_033735](https://user-images.githubusercontent.com/30598442/36127594-5f318d32-106f-11e8-8967-a31dfaf6af7d.jpg)

How it should work: 
Should stand closer to the armour stands and look somewhere at the main street.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=16692/tyn#screenshots:id=609290

**Comment by Dootz** [comment]
![wowscrnshot_021318_183447](https://user-images.githubusercontent.com/25490436/36164464-b059d11a-10ec-11e8-8034-00ca6b2a4b0b.jpg)

I just checked on official server and that's exactly where she stands :D

**Comment by inscaped** [comment]
My bad then. :>
