### ISSUE TITLE
[NPC] Elder Mottled Boar doesn't use charge

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#435]
Decription: 
Elder Mottled Boar in Durotar doesn't use charge
Edit: same thing with Dire Mottled Boar

How it works: 
Boar uses some sort of self buff that doesn't seem to affect him in any way.

How it should work: 
The boar should charge to the player after being aggroed.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=3100/elder-mottled-boar#abilities

**Comment by Dootz** [comment]
will be fixed with next update
