### ISSUE TITLE
Execute 

### ISSUE THREAD

**Issue by isaacm1** [SunwellTracker/issues#436]
Decription: I find it that quite often execute does quite literally nothing. It does miss, does not get parried,dodged,evaded,blocked etc. I hear the sound and i see the animation but no damage is dealt and nothing occurs. I've monitored Recount to check the amount of times I used Execute during the encounter and that alone has confirmed this bug. I have also checked the combat log.

How it works: Cast execute on a target, it happens very frequently, sometimes multiple times.

How it should work: 

Source (you should point out proofs of your report, please give us some source): Recount and combat log, reproduction should be easy

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
