### ISSUE TITLE
Cannot Auto attack after MC 

### ISSUE THREAD

**Issue by Szusterx** [SunwellTracker/issues#437]
Decription: Cannot Auto attack after MC - Angrathar server

How it works:  After mind control cannot auto attack any target. 
I tryed 5 times , logout and login helps only.

How it should work: 
After mc auto attack should work every time.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Was it players MC or some kind of monster MC? It works just fine locally, i need more data

**Comment by Szusterx** [comment]
hi ,

I did mc on horde 50+ in tanaris.
Jumped couple of times and left mc , after i couldnt auto attack any mob and  this pally.
Relog help me , did  it once again after relog, result was the same like before.

**Comment by Szusterx** [comment]
I just couldnt hit any player and mob by auto attack staff and mace

**Comment by Riztazz** [comment]
Oh, the priest couldnt auto attack, thought the mind controled player couldnt ;p i will look into it

**Comment by akrom23** [comment]
Looks okay.

**Comment by Riztazz** [comment]
We've tried reproducing it multiple times and we couldn't. If it happens again, please write to me on discord or write a comment in here and i'll reopen
