### ISSUE TITLE
 [Mage] Arcane Focus,  

### ISSUE THREAD

**Issue by lostamigos** [SunwellTracker/issues#439]
!
Decription: Increases your chance to hit and reduces the mana cost of your arcane spells by 1%-3%

How it works: it does not increase hit rating from (Arcane Focus) talent. Without items have 3 points (0,22%) With items 16 points (1,18%). 

How it should work: 3/3 (Arcane Focus)=3% hit now 0,22
![wowscrnshot_021318_100251](https://user-images.githubusercontent.com/36440326/36144179-2f648f92-10a5-11e8-8eda-2d072e0dd9b8.jpg)
![wowscrnshot_021318_100527](https://user-images.githubusercontent.com/36440326/36144270-764b1cbe-10a5-11e8-8976-deecffb759a4.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Well... it works but it never was displayed :P

**Comment by lostamigos** [comment]
nope. I befor play in sunwell 3 years and no see this 'visual bug'  so ... ? Look if you see ' oh i no have hit rating, i need buy gem with this' . he sees that he is missing but everything is really good. It is not necessary for someone to dress a little more hit rating

> Preview
