### ISSUE TITLE
[ RDF ] Player invite 

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#44]
Decription:  For example when we have 4 ppl in party on RDF because someone leave the party and we want to invite friend (from guild exmp.) that person cant teleport into instance, and we can't leave or find someone from RDF. Instance ID not found. please try to sort it out

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
