### ISSUE TITLE
Flask of the North

### ISSUE THREAD

**Issue by Biomet** [SunwellTracker/issues#440]
Decription:  http://db.darkwizard.pl/?item=47499 not applying the correct buff as [Shaman] [elemental spec]

How it works: Applying a random enhancement, either 80AP or 47 sp

How it should work: I think I remember it should apply the buff either based on your highest stat or highest stat priority. I'm currently having to re-take the flask multiple times to get spellpower as AP/str are useless to me.

Source (you should point out proofs of your report, please give us some source): Sorry I have no source just memory

**Comment by Afgann** [comment]
http://www.wowhead.com/item=47499/flask-of-the-north

You can easily find evidence against your statement there, for example: "It will alternate between STR and spell power. Just keep using the flask until you get the thing you want."
