### ISSUE TITLE
Death knight resurrect bug

### ISSUE THREAD

**Issue by Acupofyogurt** [SunwellTracker/issues#441]
Decription: Sometimes when you resurrect, by player or by graveyard in bgs/wintergrasp, all of your runes act as if they are on cooldown.

How it works: The spirit healer will resurrect you in a battleground, or a teammate might resurrect you in a dungeon, and all of your runes act as if they're on cooldown. Visually on your UI you will see the runes as being off cooldown. Until you cast a spell that doesn't require runes, like horn of winter, the bug seems to persist.

How it should work: Your runes should be off cooldown and available to use when you resurrect.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
