### ISSUE TITLE
Gundrak raptors

### ISSUE THREAD

**Issue by Ebeebe123** [SunwellTracker/issues#442]
Decription: 
Gundrak raptors after skinning drop nerubian chitin 

How it works: 
Gundrak raptors after skinning drop nerubian chitin 

How it should work: 
They should drop from skinning borean leather and arctic furs

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29334/gundrak-raptor#skinning

**Comment by Ebeebe123** [comment]
In 166 borean leathers i got 20 nerubian chitins they shouldn't drop it at all.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
