### ISSUE TITLE
Giant Sewer Rat

### ISSUE THREAD

**Issue by sunwellkiwi** [SunwellTracker/issues#443]
Decription: Loot doesnt go into inventory

How it works: You fish Giant sewer rat but it doesnt go in your inventory (its a pet)

How it should work: I should be able to right click the object in my inventory like this
https://www.youtube.com/watch?v=1aCny0-pcjA

Source (you should point out proofs of your report, please give us some source):  the only proof I have right now is my own eyes that saw the icon in the lootbox (was on auto loot btw) and this screenshot of my fishing buddy addon that tells me I did indeed fish one. https://imgur.com/a/Q1gmn (thats my addon screenshot that proves I caught it)

**Comment by Cwiercpasiec** [comment]
My guess is that you got a dialog box telling you that it will bind it to you and asking if you want to loot it. You could missclick it and close loot window.

**Comment by RandomDudoo** [comment]
ye fish bots can't click yes gg and you CAN'T miss that dialog windows."yes or no" unless you using fishbot that just automatically click fishing skill
