### ISSUE TITLE
Quest:Leave Nothing to Chance-Minor

### ISSUE THREAD

**Issue by TheRealestMcCoy** [SunwellTracker/issues#445]
Decription: 
Retrieve a Wintergarde Mine Bomb and use it to blow up the Upper Wintergarde Mine Shaft and the Lower Wintergarde Mine Shaft. Report back to Siege Engineer Quarterflash at Wintergarde Keep in Dragonblight when you have completed this task.

How it works: 
The rocks are always in place requiring you to have to jump over them. You place the mine and dont even get the count down timer.

How it should work: 
Once the mine is placed your chat panel should start showing a count down to explosion:
Wintergarde Mine Bomb armed.
Detonation 5...
4...
3...
2...
1...

Then the bomb explodes rocks fall into the opening.  And after some time they should despawn.

Source (you should point out proofs of your report, please give us some source): 

Video https://youtu.be/q5T7QzWE4Ek?t=44
http://www.wowhead.com/quest=12277/leave-nothing-to-chance

**Comment by Dootz** [comment]
will be fixed with next update
