### ISSUE TITLE
[Hunter][Drop]Hunetr can't "need" items on party drop after getting mail armor skill

### ISSUE THREAD

**Issue by malins2000** [SunwellTracker/issues#447]
Decription: 
I'm playing as a hunter and after reaching 40lv I can't "need" leather armor items dropped by party. I have mail armor skill purchased. I have no problem in needing Mail items, though. Cloths are not tested yet.

How it works: 
After drop, on pop-up window I can't select "need" option on leather armor items

How it should work: 
I should be able to need all item I can actually use.

Source (you should point out proofs of your report, please give us some source): 
![image](https://user-images.githubusercontent.com/35896695/36166251-2b2d043e-10f2-11e8-83bb-86443fd741d2.png)

**Comment by Afgann** [comment]
http://www.wowhead.com/forums&topic=154285/cant-roll-need-on-leather. Took me 10 seconds of searching...
