### ISSUE TITLE
[NPC] Infinite Corruptors "Corrupting Blight" (CoT: The Culling of Stratholme)

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#448]
Decription: 
Currently the debuff "Corrupting Blight" stays on you after the boss dies.
https://i.imgur.com/Rd3NyCe.jpg

How it should work: 
The debuff should remove upon boss death.

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/UpPbHtSk6D0?t=210 Healer has the debuff and it disappears when boss dies.
https://youtu.be/P1jgdfbWz0w?t=341 Tank has the debuff and it disappears when boss dies.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by 0vertime** [comment]
Bug still present.
