### ISSUE TITLE
Arena-Teams starting at 1500 rating

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#449]
Decription: 
New arena teams start at 1500 Teamrating instead of 0.

How it works: 
See above.

How it should work: 
Arena-Teams should start at the same rating as the personal rating (0).

Source (you should point out proofs of your report, please give us some source): 
https://www.engadget.com/2010/06/21/blood-sport-an-overview-of-wotlk-arena-systems/

**Comment by 0vertime** [comment]
As of season 6 (Patch 3.1) newly formed teams have their Team Rating set to 0 that you must raise by fighting against other groups. Before patch 3.1 the first time the Arena Team is created, it starts with 1500 Team Rating. To leave or disband a team, you can type /teamdisband team_type or /teamquit team_type (where team_type is 2v2, 3v3, or 5v5).

**Comment by moonsado** [comment]
Yeah but isn't this server running on 3.3.5a patch?

**Comment by ujellyx** [comment]
Some people started at 1,500 personal rating today... and some at 0. What's the reasoning behind this? They gain an unfair advantage...

**Comment by moonsado** [comment]
3.3.5a patch a dev told me....

**Comment by ujellyx** [comment]
Even then, with the 3.1 Patchnotes (see 0vertime's post above), the teams and personal rating should start at 0...

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.

**Comment by ujellyx** [comment]
How about this:

"As of season 6 (Patch 3.1) newly formed teams have their Team Rating set to 0 that you must raise by fighting against other groups. Before patch 3.1 the first time the Arena Team is created, it starts with 1500 Team Rating. To leave or disband a team, you can type /teamdisband team_type or /teamquit team_type (where team_type is 2v2, 3v3, or 5v5)."
(http://wowwiki.wikia.com/wiki/Arena_team)
