### ISSUE TITLE
[Jewelcrafting] Icy Prism

### ISSUE THREAD

**Issue by Critthulu** [SunwellTracker/issues#451]
Decription: Unable to create Icy Prism despite having required materials in inventory.

How it works: Level Jewelcrafting to 425. Train Icy Prism. Collect Materials and attempt to create. Receive error message that you do not have one of the materials required.

How it should work: Creates an Icy Prism

Source (you should point out proofs of your report, please give us some source): 
![crittu](https://user-images.githubusercontent.com/36458723/36174847-bfa0d7e4-10ca-11e8-92c7-eedc3d02f7b1.png)

**Comment by CaillouZsn** [comment]
Mine also is having the same problem but with Chalcedony's ...

![wowscrnshot_021318_154010](https://user-images.githubusercontent.com/36458957/36175252-6d62c924-10d4-11e8-8f30-e70facee3fb9.jpg)

**Comment by Nadiirr** [comment]
Hey there. The bug is the tooltip. 
It says you need 1 of them but you really need 3.

**Comment by Kokaina** [comment]
Till ICC content there were needed 3x of each common gems - so do we need it here, but we can't change display of this spell because all of us have 3.3.5a client version.
