### ISSUE TITLE
Unreachable copper vein in Redridge mountains

### ISSUE THREAD

**Issue by Chelseakiko3** [SunwellTracker/issues#452]
Decription: 
There are  a bunch of copper veins that we cannot reach in Redridge mountains please do a review on them :) 

How it works: 

the mining veins are usually a top of a mountain or inside a rock and you cannot reach them :) 
How it should work: 
You should be able to mine them without having problems 
![Uploading WoWScrnShot_021418_002438.jpg…]()
here's an example
https://ibb.co/eyW1MS  -photo upload
https://ibb.co/kQnQgS

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
