### ISSUE TITLE
[Important][Loot] Wotlk heroics trash loot

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#454]
Decription: The trash loot table in wotlk herics is not correct or changed/mistaken with the trash loot in normals. 

How it works: I have been in all heroics today and found out in 5 of them that the trash doesnt drop the correct loot. Instead of trash loot table, the trash in heroics still drops items same as normal. As an example I remember UK, Nexus and HOS trash (just because I need items from them). Please fix this asap. 

How it should work: The trash in heroics should drop different items than those in normals with higher ilvl and stats. 

Source (you should point out proofs of your report, please give us some source): You can look up in loot tables, they differ.

**Comment by Dootz** [comment]
will be fixed with next server update
