### ISSUE TITLE
[Hunter] Feign Death - does not exit combat

### ISSUE THREAD

**Issue by djjurg1** [SunwellTracker/issues#455]
Decription: The skill: Feign Death does not work as intended. 

How it works: As of now, Feign Death does drop your aggro, but fails to put you out of combat.

How it should work: Feign Death has always been a reliable way for hunters to exit combat and drink (replenish mana). I've been playing WoW since its launch in 2004 and for as long as I can remember, Feign Death has always made you exit combat. The reason why it is so important is because of how exiting combat will reset the potion timer, allowing you to use multiple potions during an encounter. 
In the source I've provided it clearly states: Using feign death exits the hunter from combat, allowing for such things as eating, mounting, or other activities not possible while in combat.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Feign_Death

**Comment by Cwiercpasiec** [comment]
Feign Death makes you exit combat, unless you are in a boss fight, which is intended behaviour. From your own source: 
Patch 2.3.0 (13-Nov-2007): Fixed a bug in which Hunters were able to disengage from combat using Feign Death during boss encounters.

And here are some screenshots proving that you exit combat after  casting Feign Death: https://imgur.com/a/J4OJo
