### ISSUE TITLE
Wintergrasp rebuilding instantly

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#456]
Decription: 
Wintergrasp rebuilds every building instantly when winning/losing, instead of staying in the damaged state until the next battle restarts, which it then starts to rebuild

How it works: 
here it rebuilds instantly

How it should work: 
https://youtu.be/Wnphj1_s774?t=363
NOTE: you still cannot do VoA if your faction does not hold WG

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/Wnphj1_s774?t=363
retail vid, theres thousands of them

**Comment by Kokaina** [comment]
True do, building shoul repair when battle starts - not ends
after 3:48 https://www.youtube.com/watch?v=eWAdVixPyrc
