### ISSUE TITLE
[NPC] Azure Ley-Whelp - reputation

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#459]
Decription: The Azure Ley-Whelps in Oculus Heroic give way too much reputation than what they should. 

How it works: Each whelp gives 35 reputation.

How it should work: Each whelp should give 3 reputation (or even 2 according to other sources) with Wyrmrest Accord or with the selected reputation if you wear tabard.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Azure_Ley-Whelp

**Comment by Kokaina** [comment]
Will be set to 2.

**Comment by Dootz** [comment]
will be fixed with next update
