### ISSUE TITLE
Instantly dying when joining WG battle

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#460]
Decription: 
This bug happened to me so far on 3 previous wotlk srvs and now here too, sometimes when you join WG from dalaran you spawn there dead. It doesn't happen often so far it happened once here and I'm 100% it's not players that kill you on spawn point since it happened alot on other srvs. Maybe some other ppl can confirm this bug aswell.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by RandomXD** [comment]
Just happened again

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
