### ISSUE TITLE
[Feronis] [22062] Dr. Whitherlimb items no stamina visual

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#461]
Itemy dropiące z npca Dr. Whitherlimb (https://db.darkwizard.pl/?npc=22062):
1. Ghoul Hammer (https://db.darkwizard.pl/?item=31269)
2. Banshee Rod (https://db.darkwizard.pl/?item=31270)
3. Abomination Cleaver (https://db.darkwizard.pl/?item=31268)

w pozycji 'random enchantments' czyli suffixie mają zaznaczone 0 stamina (tooltip), co jest visual bugiem, bo gdy spojrzymy na character sheet lub po prostu zmianę hp postaci, to stamina faktycznie jest dodawana.

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
