### ISSUE TITLE
[Feronis] [Ashenvale Quests] Sentinel Care Packages (7863, 7864, 7865)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#463]
Problem dotyczy questów:
1. Sentinel Basic Care Package (https://db.darkwizard.pl/?quest=7863)
2. Sentinel Standard Care Package (https://db.darkwizard.pl/?quest=7864)
3. Sentinel Advanced Care Package (https://db.darkwizard.pl/?quest=7865)
Obecnie można przyjąć te questy posiadając reputację neutral, natomiast według wowwiki oraz komentarzy z wowhead powinno być to możliwe dopiero przy reputacji na poziomie friendly.

2.1.3
I did this quest when i got frendly with Silverwing Sentinels

2.3.0
You get this when you become friendly with the Silverwing Sentinels(Reputation of Warsong Gulch).

Wowwiki
Reach at least friendly with the Silverwing Sentinels by fighting within Warsong Gulch.
(http://wowwiki.wikia.com/wiki/Quest:Sentinel_Basic_Care_Package), (http://wowwiki.wikia.com/wiki/Quest:Sentinel_Standard_Care_Package), (http://wowwiki.wikia.com/wiki/Quest:Sentinel_Advanced_Care_Package).

1. Postacią z minimalnym poziomem 25/35/45 oraz reputacją Silverwing Sentinels na poziomie neutral podejść do npca Illiyana Moonblaze (https://db.darkwizard.pl/?npc=14753) w Ashenvale.
2. Przyjąć q mimo braku reputacji na poziomie friendly.

Przypuszczam, że analogiczna sytuacja może występować w przypadku hordowych odpowiedników (możliwość przyjęcia questów posiadając neutral reputation a nie friendly), aczkolwiek nie mam tego jak sprawdzić.
1. Outrider Basic Care Package (https://db.darkwizard.pl/?quest=7866)
2. Outrider Standard Care Package (https://db.darkwizard.pl/?quest=7867)
3. Outrider Advanced Care Package (https://db.darkwizard.pl/?quest=7868)
Npc Kelm Hargunth (https://db.darkwizard.pl/?npc=14754)

Wowhead 3.3.0
I'm Friendly and I just completed it

**Comment by Dootz** [comment]
will be fixed with next server update
