### ISSUE TITLE
[Feronis] [NPC] Fordragon Battle Steed (27761) oraz Fordragon Knight (27535)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#464]
Npcs Fordragon Knights (https://db.darkwizard.pl/?npc=27535#.) nie jeżdżą na Fordragon Battle Steeds (https://db.darkwizard.pl/?npc=27761#.) tylko są piechurami, co jest działaniem błędnym, gdyż powinno być odwrotnie, tzn powinni ich dosiadać (patrz zakładka 'Accessories' w drugim linku).

W konsekwencji tego błędu można wsiąść na Fordragon Battle Steeda i np eksplorować sobie Northrend, co oczywiście nie powinno być możliwe.

1. Dostać się do Dragonblight (mapa w linku).
2. Zaobserwować, że Fordragon Knights nie jeżdżą na Fordragon Battle Steeds.
3. Wejść na Fordragon Battle Steed.

Zrzut, na którym widać, że Knight znajduje się obok Steeda, a drugiego dosiada gracz (http://i.imgur.com/4p6o6Lz.jpg).

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
