### ISSUE TITLE
[Warlock] Pet UI

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#465]
Problem dotyczy UI minionów oraz korzystania z wszelkiej maści pojazdów. Polega on na tym, że po wejściu (i wyjściu) z takich vehicles jak maszyny na WG, smoki w the Oculus, wierzchowce w Trial of the Champion/Argent Grounds, etc UI minionów staje się niewidoczne (ale aktywne, tzn jeżeli mamy np Pettatack obindowany pod ctrl + 1 to po użyciu takiego skrótu komenda zadziała, mimo faktu, że nie widzimy Pet Action Bara).
Nie jest to gamebreaking issue, ale jednak bywa uciążliwy i prawdopodobnie występuje również u innych klas (chyba, że wina leży po stronie clienta).

1. Przywołać miniona.
2. Wejść do pojazdu.
3. Wyjść.
4. Zaobserwować zniknięcie PetActionBar.

**Comment by Valmere** [comment]
This happens on my hunter as well on Angrathar although it's usually triggered by reloading the UI. After a reload the pet bar goes blank but it can be restored by either

1) mounting and dismounting
2) dismissing and resummoning the pet

Both of these will restore the pet bar which makes it seem like a clientside issue. I have run Oculus many times as a hunter and have not had any issue with the pet bar going blank after getting on or off the drakes.

**Comment by Akha72** [comment]
Happened today in the Oculus after jumping of a dragon and in Wintergrasp after getting out of a Tower Cannon.

**Comment by M0dinstaller** [comment]
I have this and my 2 friends also have this. /reload causes pet bar to disappear and pet to stop reacting to orders. Can't use /petattack or /petdismiss or any other command, pet doesn't react to clicking spells in spellbook. Relogging fixes the issue. /script DismissPet() causes a lua error. Not sure about remounting since we don't have mounts yet.
