### ISSUE TITLE
The Conquest Pit: Final Showdown Bug

### ISSUE THREAD

**Issue by VAlandri** [SunwellTracker/issues#468]
Completed the last quest and killed the designated NPC but received no credit for doing so.

No one else in my party got credit for it also.  I've been told it has been bugged for a while so I'm probably not the only one to post.  Can we get this fixed for future questers?

**Comment by MrTide** [comment]
@Dootz Hello seems like whom ever that got the first tag and last hit gets the credit for it
its like that for whole arena quest line i believe

**Comment by Dootz** [comment]
should be fine starting from next update
