### ISSUE TITLE
[Feronis] [Alterac Valley Quest] The Battle of Alterac (7141)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#469]
NPC Prospector Stonehewer (https://db.darkwizard.pl/?npc=13816#starts) powinien oferować quest The Battle of Alterac (https://db.darkwizard.pl/?quest=7141) aliantom, którzy uzyskali min. 51 lvl. Obecnie się tak nie dzieje.

Wowwiki
http://wowwiki.wikia.com/wiki/Quest:The_Battle_of_Alterac

**Comment by Dootz** [comment]
will be fixed with next server update
