### ISSUE TITLE
Moonglade guards are passive

### ISSUE THREAD

**Issue by temenos7** [SunwellTracker/issues#47]
Decription: 
Moonglade guards (at least the ones I've seen) don't attack players for PvP in NPC populated areas

How it works: 
Open season in Moonglade, players can be killed while doing Druid quests, camped anywhere in the zone due to no mobs, etc.

How it should work: 
Should function like Booty Bay, Gadgetzan, etc.

Source (you should point out proofs of your report, please give us some source): 

Going to Moonglade, lol

**Comment by nimeral** [comment]
Can confirm.

**Comment by Riztazz** [comment]
Already fixed, thank you for the report
