### ISSUE TITLE
Oculus HC instance loot bug.

### ISSUE THREAD

**Issue by szkirox** [SunwellTracker/issues#470]
Decription: 
When you die mid-encounter during the last boss fight there is a high chance that you fall out of the instance and your spirit teleports to Dalaran for some reason. Due to this bug I was unable to loot the reward from the last boss.

How it works: 
Your spirit teleports to Dalaran and you are unable to loot the chest.

How it should work: 
Your spirit should be outside the instance and you should be able to loot the chest even if you die mid fight.

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Duplicate, im working on it
