### ISSUE TITLE
[Angrathar] Icy Prism consumes too many crystals!

### ISSUE THREAD

**Issue by Ridgep** [SunwellTracker/issues#472]
Decription: 
The issue is that Jewelcrafting recipy Icy Prism consumes too many crystals. 

How it works: 
As of right now, to be precise it consumes 1 Frozen Orb, 3 Chalcedony, 3 Shadow Crystals and 3 Dark Jade. When the recipy says 1 of each.

How it should work: 
Should consume 1 Frozen Orb, 1 Chalcedony, 1 Shadow Crystal, 1 Dark Jade and construct 1 Icy Prism.

Source (you should point out proofs of your report, please give us some source): 
Before construction: https://imgur.com/a/5jKFt
After construction: https://imgur.com/a/aj30K
Proof of system: http://wowwiki.wikia.com/wiki/Icy_Prism

**Comment by Afgann** [comment]
https://github.com/SunwellTracker/issues/issues/451
