### ISSUE TITLE
[Priest - Talent] "Borrowed Time" no haste for channeling spells

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#475]
Decription: 
The (disc-)talent buffs you for 5 seconds after using "Power Word: Shield" and provides 25% spell haste for the next cast.

How it works: 
It only grants spellhaste for non-channeling casts.

How it should work: 
Should grant spellhaste for all spells, even channeling spells such as Penance or Mind Sear.

Source (you should point out proofs of your report, please give us some source): 
Tooltip itself.

**Comment by Lizenable** [comment]
Don't know what you are talking about but it already gives haste for channeling spells like Penance

**Comment by ujellyx** [comment]
Hm, you're right. I tested it further and now it seems to work properly. Can't understand why it didn't when I first tried it.

Sorry for the confusion and the false bugreport.
