### ISSUE TITLE
[Achievement] Heroic achievements in normal dungeons

### ISSUE THREAD

**Issue by sonrakus** [SunwellTracker/issues#476]
Decription: 
Some time ago, i reported an issue where it was possible to get the heroic achievement (Hadronox denied) in a normal azjol-nerub. It seems as though this is not the only instance of this bug.

How it works: 
A guildie of mine got the heroic achievement "Volunteer work" in a normal old kingdom dungeon.

How it should work: 
It should not be possible to get heroic achievements in normal dungeons.

Source (you should point out proofs of your report, please give us some source): 
https://cdn.discordapp.com/attachments/408622313857220619/413446506734026763/unknown.png

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
