### ISSUE TITLE
Northrend Inscription Research

### ISSUE THREAD

**Issue by Squatbooty** [SunwellTracker/issues#478]
Decription: 
It gave me a minor glyph when it's 100% guaranteed a major glyph, however, not guaranteed a NEW recipe. It's not supposed to give you a minor glyph anywho, it did for me and now I am stuck with inscription with cooldown on the research..

How it works: 
Guarantees a major glyph

How it should work: 

Read Description.

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Northrend_Inscription_Research

https://wow.gamepedia.com/Northrend_Inscription_Research

**Comment by Dootz** [comment]
Will be fixed with next server update
