### ISSUE TITLE
[Feronis] [Temporary Armor Enchantments] Runes of Warding (23559, 25521)

### ISSUE THREAD

**Issue by Akha72** [SunwellTracker/issues#479]
Problem dotyczy consumablesów Lesser Rune of Warding (https://db.darkwizard.pl/?item=23559) oraz Greater Rune of Warding (https://db.darkwizard.pl/?item=25521), a mianowicie faktu, że ich obecne wymagania lvlowe odnoszą się tylko do poziomu zakładającego, a powinny również wymagać odpowiedniego poziomu od wybranego itemu, tzn Lesser Rune of Warding powinien wymagać do założenia postaci z poziomem 55 oraz itemu z takim samym ilvl, analogicznie Greater Rune of Warding - 60tego poziomu postaci, a także 60 ilvl. W tej chwili wymagane jest tylko pierwsze kryterium, czyli poziom gracza. W konsekwencji można postacią 55+/60+ założyć na chest z ilvl poniżej 55 lub 60 (np. na heirloom, który ma 1 ilvl) taki enchantment i będzie on działał.

1. Postacią z poziomem 55 lub 60 + użyć Lesser / Greater Rune of Warding na chest armorze z ilvl niższym niż 55 lub 60.
2. Zauważyć, że enchantmentsy faktycznie działają na itemkach niespełniających ich wymagań lvlowych.

Zasada działania temporary armor enchantments jest dokładnie taka sama jak temporary weapon enchantments - fraza 'requires level x' odnosi się zarówno do poziomu nakładającego, jak i itemu, na który enchantment jest nakładany.

**Comment by sitowsky** [comment]
Źródło nie zawiera konkretnych informacji. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
