### ISSUE TITLE
[Sunfury Researcher] [The Cyro-core - bloodmyst Isle] Spell locked mob will not move into Melee

### ISSUE THREAD

**Issue by Shaalth** [SunwellTracker/issues#48]
Decription: The sunfury Researchers will not move to melee when they are spell locked

How it works: Shield Bashed the mob mid cast to lock out the spell, moved back to adjust the mob, but it sits waiting for it's spells to unlock to cast again.

How it should work: When spell locked the mob should attempt to move in melee range, or follow target to get in melee range while unable to cast spells.

Source (you should point out proofs of your report, please give us some source):

**Comment by Afgann** [comment]
Are you sure that npc is correct? Sunfury Researcher (ID 20136) doesn't have any spells that require any casting.
