### ISSUE TITLE
Golem Suit quests in Howling Fjord (  with video )

### ISSUE THREAD

**Issue by napistyle** [SunwellTracker/issues#480]
Decription:  Totally bugged out when you use Golem

How it works: 
When u try to read crystalls u start flying around and stuff

How it should work: Should be able to read crystalls #1   And you should be able to #2 investigate the cave.

Source (you should point out proofs of your report, please give us some source):  I recorded what was happening as i dont know how to explain it :  https://www.youtube.com/watch?v=JcG6UWlR-To&feature=youtu.be

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/192
