### ISSUE TITLE
[Primal Might] recipe respawn

### ISSUE THREAD

**Issue by RandomDudoo** [SunwellTracker/issues#481]
Decription: 
Recipe [Primal Might](https://db.darkwizard.pl/?item=23574)  don't respawn.

How it works: 
Primal Might recipe respawn **only** after server restart. And offcourse people abusing it. And put it on AH for big money.

How it should work: 
He should respawn after some time, no clue how long.

Source (you should point out proofs of your report, please give us some source): 
This is how all recipe vendors work. no source actually since don't find any. I waiting that recipe like 2-3 hours and open/closing vendor trade window, every 1-2min. That is definitely nothing to do with my luck. And i know that you have more important stuff to fix. But please fix it ASAP. Its so dumb. If some users have some sources feel free to post them, thanks!

**Comment by Netherfrost** [comment]
I know some recipes first respawns after 8 and 16 hours, I have no idea if this is similar to the  case at hand, but I don't think it's fair to assume the 2-3 hour window suffices

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
