### ISSUE TITLE
[Quest] Duskbat and Young Scavenger quest items bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#483]
Decription: 
Duskbat and Young Scavenger in Tirisfal Glades drops quest items without any quest.

How it works: 
Duskbat and Young Scavenger drops Duskbat Wing and Scavenger Paw w/o a related quest.

How it should work: 
They shouldn't drop these without a quest.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021518_035735](https://user-images.githubusercontent.com/30598442/36236028-e8bc1d38-1204-11e8-9167-4870765b53f1.jpg)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
