### ISSUE TITLE
[Quest] Rattlecage Skeleton quest item bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#485]
Decription: 
Rattlecage Skeleton in Tirisfal Glades drops Rattlecage Skull without a related quest.

How it works: 
Rattlecage Skeleton drops Rattlecage Skull without a related quest.

How it should work: 
Rattlecage Skeleton shouldn't drop Rattlecage Skull without a related quest.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021518_052304](https://user-images.githubusercontent.com/30598442/36237985-8e36633a-1210-11e8-8a29-ecf54cad6b2f.jpg)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
