### ISSUE TITLE
Mage t7 2 piece bonus doesn't stack with on use trinkets correctly

### ISSUE THREAD

**Issue by redbrox** [SunwellTracker/issues#486]
Description: Mage t7 2 piece, of frostfire regalia, does not stack properly. You have to use your mana gem FIRST, and then use the trinket, which is stupid because you will be at full mana at the beginning of the fight when you pop your trinkets.

How it works: Mage t7 2 piece only stacks with trinkets if you use the gem first

How it should work: Mage t7 2 piece shoudl stack with trinkets, regardless of order used

Source (you should point out proofs of your report, please give us some source):  Try giving it a shot yourself and see if you can confirm.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
