### ISSUE TITLE
Everfrost

### ISSUE THREAD

**Issue by opelneca** [SunwellTracker/issues#487]
Decription:  Everfrost is magical never-melting ice found in a few places in The Storm Peaks. Calder from Sons of Hodir wants the Everfrost Chips for quest Neutral 15 [80] Everfrost (R). These items are used for the quest Neutral 15 [77] Everfrost to gain reputation with the Sons of Hodir. You can see them when you are neutral with the Sons of Hodir, but you may not loot them until at least FRIENDLY. 
Problem is that Everfrost doesnt drop Q and maybe respawn timer / spawn positions are wrong.

How it works: Opening Everfrost does not drop Q item [Everfrost Chip] instead it drops only [Everfrost Powder]

How it should work: After getting at least Friendly opening Everfrost should ALWAYS 100% droprate drop Q item [Everfrost Chip], quest rewards 300+ rep and its repeatable, very good source of  Sons Rep grinding.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Hello
Can confirm this

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
