### ISSUE TITLE
Taunt diminishing returns are not working properly

### ISSUE THREAD

**Issue by Zarant** [SunwellTracker/issues#488]
Taunt diminishing returns should work differently from crowd control diminishing returns. 

Patch 3.3.0 change log have a brief explanation on how it should behave:

> Taunt Diminishing Returns: We've revised the system for diminishing returns on Taunt so that creatures do not become immune to Taunt until after 5 Taunts have landed. The duration of the Taunt effect will be reduced by 35% instead of 50% for each taunt landed. In addition, most creatures in the world will not be affected by Taunt diminishing returns at all. Creatures will only have Taunt diminishing returns if they have been specifically flagged for that behavior based on the design of a given encounter. 
(http://wowwiki.wikia.com/wiki/Patch_3.3.0)

So the major 2 issues are:
- All creatures are subject to taunt diminishing returns, that should only be applicable to boss encounters
- Creatures become immune to taunt after 3 taunts have landed, instead of 5.

**Comment by Kokaina** [comment]
This will be changed with ICC content, just like on Feronis.
