### ISSUE TITLE
Mending Fences [Quest] [The Storm Peaks] Area is Phased

### ISSUE THREAD

**Issue by MrCuling** [SunwellTracker/issues#490]
## Decription: 
I'm phased out of completing the quest "Mending Fences" to continue the Sons of Hodir questline.
The game thinks i've already completed this quest. (Can't see Fjorn, the Stormforged Iron Giants or the boulders I'm supposed to pick up.
I noticed this issue when I picked up the quest "Forging an Alliance" also from Thorim while still having "Mending Fences" incomplete in my questlog. 
I have tried removing both quests and one after another. I'm still phased.

## How it works: 
Can't complete quest and can't continue to the part where the game has phased me. 

## How it should work: 
Should not be phased during this part of the quest chain.

## Source (you should point out proofs of your report, please give us some source): 
As you can see from these screenshots I have the quest active on my tracker (right side). The dead Iron giants in picture 1 indicate that the area has phased to where I should be had I completed the quest.

![wowscrnshot_021518_125520](https://user-images.githubusercontent.com/36504616/36256030-7bd0901c-1251-11e8-8065-5b1575a9a9b5.jpg)

The NPC "Snorri"in picture 2 is another player doing his Sons of Hodir dailes. I should not be in the same phase as this player.

![wowscrnshot_021518_125549](https://user-images.githubusercontent.com/36504616/36256037-7e4a7b3c-1251-11e8-8404-9d282c3d62be.jpg)

**Comment by Dootz** [comment]
In next update we'll introduce fix that will prevent this from happening. However since you're already in this position i recommend you to write in-game ticket and gm should manualy complete it for you.

**Comment by MrCuling** [comment]
perfect, thank you for the help!

**Comment by Kokaina** [comment]
Duplicate, we've already done it ;)
