### ISSUE TITLE
[Quest] Rescuing Evanor

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#491]
Decription: 
Quest [Rescuing Evanor](https://db.darkwizard.pl/?quest=11681#?ref=sunwell.pl) is not working correctly. After accepting this quest you can use dragon to fly and quest instantly becomes completed.

How it works: 
Quest [Rescuing Evanor](https://db.darkwizard.pl/?quest=11681#?ref=sunwell.pl) is not working correctly. After accepting this quest you can use dragon to fly and quest instantly becomes completed.

How it should work: 
You should resue Evanor and fight on dragon for her.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://www.youtube.com/watch?v=7M7nIq1Ye3Y

As you can clearly see in attached video, quest becomes completed after it is accepted. Roleplay with Evanor works fine.
