### ISSUE TITLE
Bixie Wrenchshanker wrong position

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#492]
Decription: 
[Bixie Wrenchshanker](https://db.darkwizard.pl/?npc=25705) is permanently running

How it works: 
[Bixie Wrenchshanker](https://db.darkwizard.pl/?npc=25705) is permanently running

How it should work: 
She must stand on one point invisible.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021518_150605](https://user-images.githubusercontent.com/35955516/36258321-40085000-126b-11e8-9857-0bd73a244bec.jpg)

**Comment by Dootz** [comment]
it doesn't happen in normal conditions, probably something highly unlikely caused this issue. New movement system will probably prevent this from happening
