### ISSUE TITLE
[warlock] Corruption haste/crit/%damage snapshot and refresh

### ISSUE THREAD

**Issue by ozzyian** [SunwellTracker/issues#495]
Decription: 
When hardcasting corruption it should snapshot character current haste/crit and keep those values until the dot expires. IF corruption is refreshed with shadowbolt/drainsoul/drainlife/haunt it should keep the values from when it was hardcasted.

How it works: 
Right now corruption seems to snapshot the correct values when being cast HOWEVER when corruption is refreshed with shadowbolt/drainsoul/drainlife/haunt it takes the characters CURRENT haste/crit values and applies them. Which it shouldnt.

How it should work: 
When corruption is refreshed by  shadowbolt/drainsoul/drainlife/haunt it should retain the same values from when it was hardcasted. For example; if I hardcast corruption with bloodlust/heroism corruption should get the characters current haste rating, which would be X+30%, and keep that value for corruption during the whole fight if refreshed with shadowbolt/drainsoul/drainlife/haunt until mob is dead or corruption is hardcasted again.

Furthermore, the same should be true for crit and %damage (tricks of the trade). But that is harder to test. For instance, with the talent death's embrace (https://wotlk.evowow.com/?spell=47198) you should need to recast corruption at 35% to get the extra damage bonus. Refreshing with just haunt/etc. should not give corruption that extra %damage from the talent.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/forums&topic=162195/rolling-corruption-an-overview

**Comment by Vraeldk** [comment]
First comment from your link says : 'The stats that do not roll are:
Spellpower
Haste' 
and that means your report is incorrect

**Comment by Cwiercpasiec** [comment]
From your own source: 
The stats that do roll are:

    Critical strike chance
    Percentage damage modifiers

The stats that do not roll are:

    Spellpower
    Haste

So your assumptions are partially wrong (haste and spell power are recalculated on every refresh with shadowbolt etc.). Crit chance and percentage damage modifiers shouldn't be recalculated.

You can easily test if crit chance stays the same using Nevermelting Ice Crystal (https://db.darkwizard.pl/?item=50259). Simply use the trinket, cast Corruption, cancel trinket and refresh the dot with shadowbolts, then do the same thing without this trinket. I personally use this trinket on my warlock and i can confirm that it works correctly (crit chance is recalculated only on hardcasts, not when Corruption is refreshed through Everlasting Affliction). I can provide some screenoshots to prove it works correctly.

Now about percent damage modifiers. You can notice it on Twin Val'kyr. Just take one essence colour, cast Corruption, switch the colour and refresh the DoT with Shadowbolts (or other spells... If you don't want to loose much dps, then go for Drain Life/Soul cast on focus and instantly interrupt channeling, this way you only loose one global cooldown per refresh). You will notice, that percent damage modifiers do not recalculate, unless you hardcast. Also another method to test it is to get a rogue to cast Tricks of the Trade on you, when you test it on dummy, just do everything the same way like when testing crit chance. Just get naked to test this, so spell power won't get in the way. If needed, I can provide proves it works correctly.

**Comment by ozzyian** [comment]
Yes, i remembered it wrong. Haste rolling was hotfixed later in 3.3.5. Hard to keep track after all these years, could've sworn it was never fixed before cata. Good to know that crit is working properly, i'll try to test TotT on a dummy later if I can.
