### ISSUE TITLE
[Death Knight] Pet Energy after Dismount

### ISSUE THREAD

**Issue by winNixz** [SunwellTracker/issues#496]
Description: 
When mounting with a pet as a death knight and dismounting after that, the pet will lose all of its energy. It's intended that the pet regenerates energy while mounted and that it doesn't start with 0 energy every time.

How it works: 
The pet will always have 0 energy after dismounting.
https://www.youtube.com/watch?v=CGyOabYYLnY

How it should work: 
The pet should keep it's current energy and regenerate it while mounted, it should spawn after dismounting with it's current amount.

at around 0:19 it's clearly visible how it's supposed to work 
https://www.youtube.com/watch?v=VOmuJyVbUk4

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
