### ISSUE TITLE
Druid's Nature's Grasp 's internal cooldown is not working.

### ISSUE THREAD

**Issue by Jiokko** [SunwellTracker/issues#497]
Decription: The spell Nature's Grasp from the druid does not have the 3 seconds (if i'm not mistaken it's 3 seconds) internal cooldown. 

How it works: 
When you 're buffed with Nature's Grasp and for example 2 mobs are hitting you, the proc for both can happen immediately and both mobs will be rooted together. Or even when 1 mob hits you with 2/3 hits fast, it will consume the 2/3 charges (depending on the number).

How it should work: 
If you have Nature's Grasp and 1,2 or more mobs hit you, when the 1st of the 3 charges of Nature's Grasp proc, then the 2nd charge will be procced after 3 seconds. (correct me if i'm wrong on the duration.

Source (you should point out proofs of your report, please give us some source):

**Comment by Jiokko** [comment]
ok i will upload pics tomorrow

**Comment by Avarishd** [comment]
There is no internal cooldown

**Comment by Jiokko** [comment]
Avarishd if you claim that, i really doubt that you have ever played retail. The problem is i can't find the info from so many years ago. The only thing i found is the bugtracker fix of some private servers that have their opinion and all of them say that there should be a 3 sec internal cooldown. (just think if a rogue open on you while he has you stunned and you had already pressed NG. The 3 charges gonna go off in like 2 seconds. I ask from players that have some experienced more on the thing to comment. Or search more on it. I just have found threads on forums from the past that say of that 3 secs ICD. I beg you don't even comment on bugtracker if you have no idea on how a skill is working and just have played on 2 private servers in your life. No offense meant. I'm trying to find out proofs from blizzard but it's hard in 2018...

**Comment by Jiokko** [comment]
<img width="727" alt="ns" src="https://user-images.githubusercontent.com/6665852/36344136-aee1b94e-141e-11e8-9015-47ccf6af75f2.png">

An update of a bugtracker of older server.

**Comment by Avarishd** [comment]
I beg you don't even comment on bugtracker if you have no idea on how a skill is working and just have played on 2 private servers in your life. No offense meant. @Jiokko Alright man, my bad didn't know you were a league player. Keep it clean.

**Comment by Avarishd** [comment]
Perhaps i wasn't correct, no need to be so toxic. It is hard to remember minor things from something that was relevant 10 years ago.

**Comment by Jiokko** [comment]
yea i apologize for that, sorry..

**Comment by Azathothh** [comment]
Nature's Grasp does have ICD already - it's set to 1,5sec

20:02:23> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:23> Rogalikx is afflicted by Azdru's Entangling Roots.
20:02:23> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:24> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:24> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:24> Azdru's Entangling Roots is refreshed on Rogalikx.
20:02:25> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:25> Rogalikx's attack misses Azdru.
20:02:26> Rogalikx's melee swing hits Azdru for 1 Physical.
20:02:26> Azdru's Nature's Grasp fades from Azdru.
20:02:26> Azdru's Entangling Roots is refreshed on Rogalikx.
