### ISSUE TITLE
los on destroyed gates

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#498]
Decription: 
In wintergrasp when you try to attack someone thats on the other side of a destroyed wall it will always say that the target is not in line of sight even if the wall is already down it counts as if it would be up, you can pass the wall but not attack other ppl through. I think same thing happens in sota too but i didnt check there yet.
http://prntscr.com/if6mg0
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
can confirm

**Comment by knasen88** [comment]
What more data could you possibly need? right now it's quite obvious what the problem is @sitowsky

**Comment by Sunite** [comment]
What more data you need? :D It is true if you need to see for yourself just join a WG. It is annoying as F and makes it so much easier for a defending team...Anyway, I won't bother to record it or so...If you wanna stay blind to this issue it is up to you...

**Comment by Nuy** [comment]
Bottom line is that your VMAP/MMAP system is broken and probably requires complete rewrite.

**Comment by Nuy** [comment]
Still bugged. Please fix it.

**Comment by Rosenkrantz** [comment]
Sorry, but bump. Can we get any update? Are you working on it, you'll start now/tomorrow/in a month or anything? :p It's really gamebreaking, playing SOTA is pure misery.
