### ISSUE TITLE
[Quest] A spirit guide.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#499]
Decription:  Wolf doesnt have his path way. He simply follow us instead of forcing us to follow him. Youtube's videos explain it all.

How it works:  https://youtu.be/KKkdTU3vm-o

How it should work: https://www.youtube.com/watch?v=4BGlnjGieUk

Source (you should point out proofs of your report, please give us some source):

**Comment by Avarishd** [comment]
Just did the quest a couple of minutes ago and it was working perfect, so i assume its fixed.

**Comment by Soufly** [comment]
Still doesnt work,however u can complete the quest ...
