### ISSUE TITLE
[Death Knight][Spell] Dancing rune weapon

### ISSUE THREAD

**Issue by danniellos94** [SunwellTracker/issues#5]
Decription: 
Dancing rune weapon działa nie prawidłowo.
Jest kilka błędów wymienie po kolei:
1.broń nie atakuje sama z siebie a powinna (powinna atakować bez ingerencji ataku dk przy czym ataki powinny wynosić 50% jego dmg w momencie odpalenia drw - biorąc pod uwagę istniejące wtedy proce itd.).
2.drw dmg nie zwiększa się jeśli odpalimy trinket/histerie/proc z broni dk fallen crusader,nastackujemy talent vengeance przed drw - krótko mowiąć proce najprawdopodobniej nie wpływaja na dmg drw.
3.skopiowane death coile wydają się bić za dużo. (normalny dc 900 skopiowany 700 - aktualnie na 72 lvlu),tutaj też dodam jakby co że proc sudden dooma powinien być skopiowany przez drw czy tak działa nie miałem jeszcze okazji sprawdzić.
How it works: 
zły attack speed,autoataki są zależne od dk (damage oczywiście powinien być zależny),nie snapshotuje statów - tutaj też warto dodać że wszystko powinno być brane pod uwagę - talenty,glyphy,buffy zwiększające dmg,setówki itd. w momencie przywołanie rune weapon,aktualnie nie ma debuffa na targecie.
arp powinien też wpływać na dmg rune weapon - ponieważ rune weapon robi 50% reduced dmg dk
nie kopiuje blood boila a powinno https://www.youtube.com/watch?v=_HPvfJ5xJMI
nie kopiuje bomb z inzynierii a powinno http://www.masterofwarcraft.net/2009/02/nuke-biggest-mob-groups-away-as-death.html
How it should work: 
1.DRW powinno działać bardzo podobnie do gargulca - haste powinien wpływać na attack speed broni(w tym buffy na haste,heroism,aura na haste,pot,haste z ekwipunku)
2.Dmg drw jest zależny od weapon dmg naszej broni - to działa
3.Dmg drw jest zależne od proców (naszych statystyk w momencie wezwania broni)
4.Po zabiciu targetu na, który przyzwaliśmy drw powinno ono zmienić target na najbliższy cel.Dodam,że nawet jeśli mamy 2 targety target A i target B,wezwaliśmy drw na target A a bijemy target B,to target A dostaje dmg z umiejetnosci których używamy na target B.
5.Drw pojawia się za targetem i bije go od tyłu zawsze nawet gdy odwrócimy cel pet powinien bić od tyłu.
6.Tutaj przedstawię problem melee petów w związku z expertisem i hitem (zalicza się do wszystkich petów)
All pets now receive 40% of their master’s resilience and 100% of their master’s spell penetration. In addition, if a player is at their appropriate spell hit chance or hit chance maximum, their pet will be at the maximum for spell hit chance, hit chance, and expertise. If they are below the maximum, their pet will be proportionately below those maximums.
http://us.battle.net/wow/en/game/patch-notes/3-2-0
7.drw krytuje kiedy chce niekoniecznie wtedy kiedy my krytujemy(bierze kryta z melee crit chance) - to działa.
Source (you should point out proofs of your report, please give us some source): 

    https://www.youtube.com/watch?v=FwR1HTrFAW4 3:18
    Patch 3.1.0 (14-Apr-2009): Damage done by, and duration of this pet is reduced by 50%, but the cooldown is reduced to 90 seconds. Attack speed of pet increased from 2.0 to 3.5. Fixed a bug making it trigger an unusual number of effects from the weapon equipped by the death knight. In addition, it will now only echo death knight spells whose primary purpose is dealing damage. This pet will no longer break stealth on nearby targets and attack them. Also corrected a bug making the effect last 8 seconds longer than intended.
    http://us.battle.net/wow/en/game/patch-notes/3-1-0

Linki WoWHead/OpenWoW:

    http://wotlk.openwow.com/spell=49028
tutaj jeszcze jeden filmik z globala (widać debuff drw na bossie)
https://www.youtube.com/watch?v=i7RRazukPq4&spfreload=5
a tu widać jak drw samo atakuje i nawet produkuje threat dla dk
https://www.youtube.com/watch?v=_ld_QsKa-gs
filmik z 3.3.3 patcha (od tego momentu zadnych zmian przy drw do 3.3.5)
https://www.youtube.com/watch?v=r11asc2Cd-0
1:51 death strike crit - 9684 player critical 2405 dancing rune weapon non critical
1:39 4538 dancing rune weapon autoattack critical
1:41 heart strike player critical 9681 pet 2438 non critical
jak widać praktycznie 50%, widać debuff na trainning dummy
opis pod filmikiem cytuje 👍 Keep your diseases up for maximum dps, and use hysteria and Dancing Rune Weapon for higher burst dps. remember, DRW inherits a copy of your stats, so it's bested used after CDs are blown and procs, etc.
https://www.youtube.com/watch?v=-CCXHeROUrs kolejny film z retaila
0:29 jego hs 8,5k crit drw 2,5 bez kryta
8,5:2=4,25 :2 =2,125 ale trzeba tez policzyc diseasy zwiekszajace dmg x 1.2=2,5k
0:33 death strike 4439 drw death strike 2353 nawet wiecej niz 50%
tutaj poradnik z elitist jerk http://www.mmo-champion.com/threads/671302-Blood-DK-Guide-Taken-from-Elitist-Jerks-for-new-DKs

DRW will gain buffs you have before casting it, but will not get things used after, i.e. Hysteria, potions, etc. Heart Strikes from DRW also are affected by its diseases, and the diseases will stay even after DRW has expired. For this reason it is proper to cast DRW before refreshing your diseases.

http://www.wowhead.com/forums&topic=124340

Dancing Rune Weapon?
Like Unholy's Gargolye, it will gain buffs pre-cast. However, it copies so you need to be more aware of your control over the ability, You should have
-4 deathrunes
-EPW
-Trinket Procs
-Potion
-Hysteria
At least aim for having those up, heroism/bloodlust and other procs will help too.
DRW does benefit from the disease multiplier so refresh your diseases after cast.

**Comment by Sunwellxd** [comment]
https://www.youtube.com/watch?v=YaJmhoiBvYQ
tutaj tez ladnie widac jak bije drw, duzo duzo mniej niz 50% co ma zapewne zwiazek wlasnie z braniem statystyk w momencie odpalenia.
ciekawe jak bloodwormsy u nas dzialaja...

bump!

**Comment by razarah** [comment]
bump, nie mogę grać DKjem jesli ten talent nie dziala dobrze :/

**Comment by luci1329** [comment]
When is this going to be merged? The blood spec becomes quite viable in terms of dps now that icc released
