### ISSUE TITLE
[Blade's Edge Mountain] Sons of Gruul quests completable by only one person at the same time

### ISSUE THREAD

**Issue by dreamingdust** [SunwellTracker/issues#500]
Decription: 
Grulloc Has Two Skulls
Maggoc's Treasure Chest
Even Gronn Have Standarts

How it works: 
The items that need to be looted in order to complete the quest despawn after the first person loots them.

How it should work:
After killing each of the sons of Gruul an item spawns on the ground and is lootable by everyone nearby.

Source (you should point out proofs of your report, please give us some source):
http://www.wowhead.com/item=32380/maggocs-treasure-chest#comments
http://www.wowhead.com/quest=10996/maggocs-treasure-chest

http://www.wowhead.com/item=32379/grullocs-dragon-skull#comments
http://www.wowhead.com/quest=10995/grulloc-has-two-skulls

http://www.wowhead.com/item=32382/slaags-standard#comments
http://www.wowhead.com/quest=10997/even-gronn-have-standards

**Comment by dreamingdust** [comment]
The next two quests of the chain have the exact same issue.
Grim(oire) Business
Into the Soulgrinder

http://www.wowhead.com/item=32358/vimgols-vile-grimoire#comments
http://www.wowhead.com/quest=10998/grim-oire-business

http://www.wowhead.com/quest=11000/into-the-soulgrinder

**Comment by Dootz** [comment]
will be fixed with next server update
