### ISSUE TITLE
Hunter Flare

### ISSUE THREAD

**Issue by AcidScytheZ** [SunwellTracker/issues#501]
Decription: 
1. When a hunter use flare at longer range, we don't even see where it will be active until the very slow animation fall down to show us, but its also instantly active which makes it unavoidable in most of the situations.

2. Also if you are inside of the flare spot and you exit it with sprint or nitro boosts and vanish, it still says immune.

How it works: 
1. I'm in stealth and i see hunter shoot flare, if I am at its max range and it is on me i get instantly out of stealth without even knowing that its shot to this direction or its shot to somewhere else.
You basically have to stay far far away and pray that u don't go through it before you can actually see where it is....

2. Even if you are like 10 yards+ out of it, it still says Immune and you don't get into stealth which is kinda broken, because you are not even in the effect of the flare.
You can try that.
Walk into flare and then sprint/nitro out of it, then vanish, even try vanish prep vanish, you will end up wasting 2 vanishes and just to see Immune text. Well this one is common in most of the private servers but the first thing that i describe is so frustrating and I am pretty sure that I'm not the only person who noticed it.

How it should work: 
1. Well animation should be either faster when its shot on long range so we can avoid it or the effect shouldn't be active before the animation arrives.

2. And about the second thing - the second u step out of the flare spot the debuff should go away and shouldn't say  IMMUNE to your vanish.

Source (you should point out proofs of your report, please give us some source): 
Just go ingame
Get hunter and rogue.
Tell rogue to go at max of the flare range and stealth.
Tell hunter to shoot flare at the rogue.
Result - rogue will be out of stealth without even being able to see that flare is shot yet.
You just get instantly out of stealth.....

And about the second thing.
Same just once the rogue is in the flare tell him to pop sprint/nitro to exit it's range fast.
Once out hit vanish. Result - immune text appears even if you are out of the effect.

Both things are game breaking.

In retail the animation comes instantly where the flare is shot and the small flying dot of light indicates when flare will be over. 
For example:
You shoot flare and the circle of light is instantly on the ground. But the flying dot slowly reaches the circle of light over 20 sec. Once its there the flare is over.
So by watching this you know exactly when the flare is over. And you also know where the flare is shot even on max range because it instantly appear on the ground and you can dodge it if its not exactly at your spot.
http://wowwiki.wikia.com/wiki/Flare

**Using Flare now leaves a bright light on the ground, possibly alerting stealthed units you are nearby.

There is a brief period of time after using the spell that a rogue, if properly positioned, can sneak in before the flare effect begins and get an opener off.**

As you can see the way Flare works hasn't been changed since The Burning Crusade.

**Comment by set-theorist** [comment]
This is untrue, flare effect should be instant even though the animation is slow. 

As for this
>There is a brief period of time after using the spell that a rogue, if properly positioned, can sneak in before the flare effect begins and get an opener off.**

This is true, but at any moment of the flare, not just the cast. At the moment the flare "ticks" too fast, which not only prevents this, but also doesn't allow shadowstepping and getting one opener off.

**Comment by AcidScytheZ** [comment]
In retail the effect is instant but so is the animation. The only thing moving is the little small ball of light which indicates when flare finishes. you can test that yourself.

**Comment by AcidScytheZ** [comment]
The problem here is that you see nothing on the ground for atleast 3-5 sec which is crucial .

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
