### ISSUE TITLE
Battleground graveyards work while they are grayed out

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#502]
Decription: 
Currently you get resurrected while graveyard is still contested, grayed out, the 1-minute period, no one actually owns it.

How it should work: 
You should get teleported to non-contested graveyard.

**Comment by knasen88** [comment]
are you sure about this in wg gy? it works like that in arathi etc iirc?

**Comment by 0vertime** [comment]
Not just WG, happens in EotS too at least.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
