### ISSUE TITLE
(quest) Timear Foresees Titanium Vanguards in your Future

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#503]
Decription: 
Killing 1 titanium vanguard for the quest counts as if killing 2.
http://prntscr.com/if9eff
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Valmere** [comment]
I noticed this happen too, thought I was just crazy so I brushed it off. Will it again next time that daily pops.

**Comment by bongobg** [comment]
Sometimes that happens, sometime not. I've never been able to find the reason.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/769
