### ISSUE TITLE
Drakkari Battle Rider (npc)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#504]
Decription: 
Visual bug on throw spell, it throws a cube at you.
http://prntscr.com/if9fej
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Fixed but forgot to close it

**Comment by Riztazz** [comment]
Fixed on feronis, Angrathar will be updated in following days, closing
