### ISSUE TITLE
Glyph of Eternal Water

### ISSUE THREAD

**Issue by Jurek-Kiler** [SunwellTracker/issues#507]
Decription: Water Elemental with glyph Eternal Water. 

How it works: Elemental doesnt attack at all. It is useless now with this glyph, 

How it should work: He szhould attack with everything besides casting freeze only!

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
Water Elemental with Glyph of Eternal Water attacks only with Waterbolts.
https://imgur.com/a/4z0jh This is how it works now. When you summon your elemental for the first time, waterbolt is not on auto cast, that's why your elemental does not attack.

**Comment by Jurek-Kiler** [comment]
It works indeed when i set it on autoattack. Sorry for trouble.
