### ISSUE TITLE
[NPC] Scarlet Missionary bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#508]
Decription: 
Scarlet Missionary in Tirisfal Glades doesn't attack most of the time if he isn't in range. I don't remember if he should cast something or not, maybe it's the cause.
Edit: The one on the screenshot is not evaded.

How it works: 
Scarlet Missionary doesn't attack most of the time if he isn't in range.

How it should work: 
Scarlet Missionary should move to the target and attack it.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021618_000912](https://user-images.githubusercontent.com/30598442/36281307-4bc35c4e-12ae-11e8-946d-beee9347f123.jpg)
![wowscrnshot_021618_000933](https://user-images.githubusercontent.com/30598442/36281308-4be9c140-12ae-11e8-9c6f-4b2e2dbdc661.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
