### ISSUE TITLE
[Dungeon - Violet Hold - Dehydration Achievement]

### ISSUE THREAD

**Issue by Corazzin** [SunwellTracker/issues#509]
Decription: Attempting the Dehydration achievement in the Violet Hold which involves killing all the water adds before they reach the boss, the crystals you can click on the walls in VH aren't doing any damage to the adds. Not saying they should one shot them, or it would be faceroll, but they dont seem to do any damage at all, making the achievement harder than it should be.

How it works: When the boss stacks reach 0, he splits into adds that you need to kill before they reach the boss. The crystals do 0 dmg to the adds and therefore they reach the boss and the achievement is hard.

How it should work: Using the crystals should help damage them / either 1 shotting or dmging them slightly, making it easier to kill ALL the adds for the achieve. We've attempted it without using the crystals at all and get close but because some spawn so close, its almost impossible to kill all, with the knockbacks etc.

Source (you should point out proofs of your report, please give us some source): Havent been able to record, but can upon revisiting VH

**Comment by Valmere** [comment]
I'm fairly certain the defense crystals should 1 shot the little water elementals, same as it does with the dragonspawn waves.

**Comment by Corazzin** [comment]
Yeah i thought it should one shot them, I could remember it did that on live, but yeah the crystals dont do any damage for my group at all.

**Comment by Valmere** [comment]
What more data do you need? I'm in a heroic VH right now and the crystals (https://db.darkwizard.pl/?object=193611) aren't even clickable.

They are supposed to 1 shot the Ichor Globules (https://db.darkwizard.pl/?npc=29321) during the boss fight with Ichoron (https://db.darkwizard.pl/?npc=29313).

When the crystals were enabled they were properly 1 shotting the waves of adds that spawn normally from portals. 

The only mobs that are not supposed to die from an activated crystal are the Portal Guardians, Portal Keepers and boss mobs.

**Comment by xethra89** [comment]
https://www.youtube.com/watch?v=x-9ZFUpj7Pw

Here's a video of the achievement being done in WOTLK. The video clearly shows the adds dying when the crystals are activated. However, on Sunwell the adds do not take damage.

**Comment by xethra89** [comment]
Any update??

**Comment by Riztazz** [comment]
poke @Afgann he rewrote the entire instance ;p

**Comment by Mortiiis** [comment]
we've been trying this yesterday, levers are clickables but they dont do anything to the blobs the boss spawns when he explodes
they should die instantly
can we have an update please? this is the last achievement we need for some in our group :P
thanks :)

**Comment by ihcTactics** [comment]
Any update? Obviously appreciate your hard work you put in to such a niche bug and all other problems the team has worked on. Just hoping we don't have to resort to respeccing and finding specific mob pushback comps.

**Comment by Dootz** [comment]
will be fixed with next server update (hopefully :) )

**Comment by Dootz** [comment]
I missed something and it's still not working. I found it and it will be working from next restart.
