### ISSUE TITLE
Hillsbrad Starving Mountain Lions just bugged in general

### ISSUE THREAD

**Issue by Mobane** [SunwellTracker/issues#51]
Decription: 
-Aggro range is too wide for yellow
-Attack speed is too fast, if you get 2 of them on you, even if you're a strong class, forget survival.

How it works: 
-You die trying to go anywhere

How it should work: 
-Normal attack speed, not 2 per second

Source (you should point out proofs of your report, please give us some source): 
-Make a level 20-22 toon, go to hillsbrad, and stand remotely near one of these little bastards

**Comment by Crackaw** [comment]
Can you give us some proof about it?

**Comment by Dootz** [comment]
http://www.wowhead.com/npc=2384/starving-mountain-lion#comments
> By nomm (2,077 – 4·12) on 2009/10/24 (Patch 3.2.2)
> very annoying if you're a caster, since they have a very high melee speed
