### ISSUE TITLE
Death Knight's permanent Ghoul does not spawn with 100 energy

### ISSUE THREAD

**Issue by set-theorist** [SunwellTracker/issues#510]
Decription: There are 2 parts to this bug. When you are specced into master of ghouls:
1. When you summon a ghoul it should spawn with 100 energy.
2. When you mount and dismount, your ghoul should spawn with whatever energy it had when you mounted up.

How it works: 
1. When you summon a ghoul it spawns with 0 energy.
2. When you mount and dismount, your ghoul spawns with 0 energy.

How it should work: 
1. When you summon a ghoul it should spawn with 100 energy.
2. When you mount and dismount, your ghoul should spawn with whatever energy it had when you mounted up.

Source (you should point out proofs of your report, please give us some source): 
1. https://youtu.be/teIODQeVjOI?t=8m15s
2. https://youtu.be/teIODQeVjOI?t=7m8s

**Comment by Cwiercpasiec** [comment]
I can confirm, ghoul always spawns with 0 energy.

**Comment by thanhtotti** [comment]
Confirmed!

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
