### ISSUE TITLE
Paladin's Sheath of Light healing should be able to roll

### ISSUE THREAD

**Issue by set-theorist** [SunwellTracker/issues#511]
Decription: 
The Sheath of Light talent causes a heal over time to be placed on the target whenever the ret paladin's heal critically hits.

This heal however can stack with itself or "roll," very much in the same fashion as warrior's deep wounds.
 
How it works: 
If you spec into Sheath of Light and cast 2 consecutive critical heals on the same target, the sheath of light buff from the second heal will override the first one, and the healing that had not yet been gained from the old sheath is lost.

How it should work: 
When you cast 2 consecutive critical heals on the same target, the old sheath's amount that has not yet beenhealed (which is equal to number of remaining ticks*heal per tick) is added to 30% of the new heal critical and then distributed evenly among the new 4 ticks over 12 seconds; very similar to how warrior's deep wounds works.

Source (you should point out proofs of your report, please give us some source): 
https://web.archive.org/web/20100724032013/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/#Special_Talents

http://lonedistrict.wowrpg.org/t556-retri-paladin-guide-by-razorblades 

http://retribution-paladins.blogspot.com.co/2009_09_01_archive.html

http://www.arenajunkies.com/topic/88595-paladin-32-viable-hybrid/

http://www.arenajunkies.com/topic/35853-holy-lvl-70-talents-when-content-patch-comes-out/page__st__40

**Comment by Cwiercpasiec** [comment]
Confirmed.
https://imgur.com/a/f9bw5
The second Sheath of Light just overrode the first one.

**Comment by Azathothh** [comment]
Fixed. Will be updated on Angrathar/Feronis soon.
