### ISSUE TITLE
Battle of Valhalas in Icecrown

### ISSUE THREAD

**Issue by Nexao** [SunwellTracker/issues#512]
Decription: 
The quest in north west of Icecrown that starts with "Final Challenge" 

How it works: 
It does not matter if you die and "fail" the quest, you will still complete it. Even if you just start the quest and run away, then when the mob despawns, you will complete it (This goes for all 6 quests)
"Battle of Valhalas Fallen heroes"
"Battle of Valhalas Khit'rix the dark master"
"Battle of Valhalas The return of Sigrid Iceborn"
"Battle of Valhalas Carnage"
"Battle of Valhalas Thane deathblow"
"Battle of Valhalas Final Challenge"

How it should work: 
It's like ring of blood in nagrand, where a group of 5 people go through x amount of challenges and get rewarded for each of them.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/632
