### ISSUE TITLE
Mage - Talent - Arcane Concentration

### ISSUE THREAD

**Issue by hugedude** [SunwellTracker/issues#513]
Decription: I have noticed 2 problems with Arcane Concentration.

1st - Blizzard will sometimes consume the clearcasting effect from Arcane Concentration but will STILL consume mana rather than costing 0 mana.

2nd - Using Frostfire Bolt with a Brain Freeze (talent) proc will also consume the clearcasting effect. It is already supposed to cost 0 mana and be instant cast (from Brain Freeze) so it should NOT consume the clearcasting effect from Arcane Concentration.

How it works: 

1st - Blizzard will sometimes consume the clearcasting effect from Arcane Concentration but will STILL consume mana rather than costing 0 mana.

2nd - Using Frostfire Bolt with a Brain Freeze (talent) proc will also consume the clearcasting effect. It is already supposed to cost 0 mana and be instant cast (from Brain Freeze) so it should NOT consume the clearcasting effect from Arcane Concentration.

How it should work: 

1st - If you have clear casting effect from Arcane Concentration, Blizzard should not cost mana to cast.

2nd - Casting Frostfire Bolt with a Brain Freeze proc should NOT consume clearcasting effect from Arcane Concentration.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
About Blizzard - it only costs mana with Clearcasting when it consumes the buff. So basically Blizzard now usually doesn't consume Clearcasting and costs no mana (if you have Clearcasting buff active) but when Clearcasting is consumed by Blizzard, it costs mana.

**Comment by hugedude** [comment]
I do not understand the point of your reply. 
It should not consume the buff AND cost mana. That is directly counter to the wording of the buff. And if it is the next damage spell to be cast it should consume the clearcasting buff and cost no mana. Simple as that.

"The clearcasting state reduces the mana cost of your next damage spell by 100%." - Talent screen description.

**Comment by Cwiercpasiec** [comment]
My point was, that not only Blizzard sometimes costs mana when it shouldn't, but it also doesn't consume Clearcasting. Also I'm not a developer, but i thought it might help to mention what I noticed.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
