### ISSUE TITLE
WINTERGRASP QUEUE

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#514]
Decription: 
it's totally botched, it allows everyone who presses it "in" instantly, only to later KICK THE OVERFLOWING PEOPLE TO ICECROWN

How it works: 
press queue, get "queued". Wintergrasp starts -> get ported to WG only to get kicked to shitcrown later.
It also doesnt even seem to be based on queue but rather how fast you press the button to accept battle.

So the queue is just a scam it does literally nothing but send you to WG and if its full it sends you away without queueing you so the only way to get a spot later is to spam fly in again

How it should work: 
There should be an actualy QUEUE in place, think like RBG or RDF, you should not be called into battle to get kicked out later that's fubar.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by knasen88** [comment]
How can I provide source when your 50 limit rule is a custom fix
