### ISSUE TITLE
Paladin hand of freedom does not remove confusion

### ISSUE THREAD

**Issue by IgnatBeresnev** [SunwellTracker/issues#515]
Decription: 
Paladin hand of freedom does not remove confusion

How it works: 
When you get debuff "confusion" (50% reduced running speed) (applied by mobs hitting you) and use hand of freedom on yourself, confusion does not get removed. 

How it should work: 
Hand of freedom should remove confusion

Source (you should point out proofs of your report, please give us some source): 
I can record a video but I think it'll be easier for you to try it out in game

**Comment by Cwiercpasiec** [comment]
I think you mean daze, not confusion.
http://wowwiki.wikia.com/wiki/Daze
"While it slows movement speed, daze is not considered a movement impairing effect. Thus it cannot be removed by the usual means such as druid shapeshifting, Vanish, Faction Insignia, or Hand of Freedom."

**Comment by Avarishd** [comment]
this is not a bug lol as @Cwiercpasiec said

**Comment by IgnatBeresnev** [comment]
@Cwiercpasiec it was confusion but it applies to both, I guess. Thanks
