### ISSUE TITLE
PROSPECTING SARONITE BROKEN

### ISSUE THREAD

**Issue by angryminer123** [SunwellTracker/issues#516]
Decription:  I just prospected 1000 saronite and got 10blue gems. This rng is seriously broken and should be looked at

How it works: 
broken as hell, the % chance is way to low to get blue gems

How it should work: 
It should get a boost for sure, 10 blue gems on 1k ores is not working as intendend, all my guildies are saying the same. the % chance is to LOW

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
Needs a source.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
