### ISSUE TITLE
[Paladin] Holy Wrath

### ISSUE THREAD

**Issue by Daford** [SunwellTracker/issues#517]
Decription: **Holy Wrath** - Sends bolts of power in all directions, causing X Holy damage divided among all enemies within 10 yards, stunning Demons and Undead for 3 sec.

How it works:  Works on Undead and Demons only.

How it should work: Should deal damage to everyone, but stun Demons and Undead only.

**Comment by Lidann1993** [comment]
dalaranwow/dalaran-wow#2857

**Comment by Valmere** [comment]
Might want to play your class a bit more or even read the tooltip.
https://db.darkwizard.pl/?spell=48817
"Sends bolts of holy power in all directions, causing (1050+0.07*HolP+0.07*AP) to (1234+0.07*HolP+0.07*AP) **Holy damage and stunning all Undead and Demon targets** within 10 yds for 3 sec."
