### ISSUE TITLE
[Death Knight] Corpse Explosion radius is too small when exploding pet ghoul

### ISSUE THREAD

**Issue by muusbolla** [SunwellTracker/issues#518]
Decription: When I explode a mob corpse, the radius is much bigger than when targeting my pet and having it cast Explode. I am using Glyph of Corpse Explosion to increase the range to 15 yards.

How it works: Corpse Explosion targeting a mob corpse seems to have the proper range of 15 yards. Corpse Explosion targeting my pet (causing it to cast Explode) seems to have a much shorter range (possibly even shorter than 10 yards).

How it should work: Ghoul Explode and mob-targeted Corpse Explosion should all have the same range of 15 yards when using Glyph of Corpse Explosion.

Source (you should point out proofs of your report, please give us some source): Tested for hours while doing AOE farming.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
