### ISSUE TITLE
Can't Summon a friend

### ISSUE THREAD

**Issue by teteudiniz** [SunwellTracker/issues#52]
Decription: Cant use the feature to summon a friend that I invited trough the RaF system. The spell doesnt cast.

How it works: It starts casting but doesnt complete.

How it should work: 
 Summon a Friend - it has 60 minutes of cooldown and allows linked accounts to summon each other, regardless of where they are.

Source (you should point out proofs of your report, please give us some source):

**Comment by nimeral** [comment]
RaF is disabled until all realm firsts happen. http://sunwell-community.com/index.php?/topic/19-couple-ideas/&do=findComment&comment=208
