### ISSUE TITLE
[Mage/Priest] Icy Veins and Power Infusion don't stack

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#520]
Decription: 
The two spells don't stack.
If Icy Veins is used first, one cannot buff the casting mage with Power Infusion.
If Power Infusion is used first, Icy Veins overwrites and removes the buff, when used by the mage.

How it works: 
See above.

How it should work: 
Those two buffs should stack.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=IWWVKndE_7g
starts at 4:52

**Comment by set-theorist** [comment]
This is an old video. Power infusion stacking with icy veins was removed around patch 3.2

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
