### ISSUE TITLE
Skittering Swarmer (npc)

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#522]
Decription: 
After killing the first boss in AN on the right side of the room in water the skittering swarmers will aggro us but they won't move unless we go near them. Might result in combat for whole duration of instance if ppl wont kill them.
http://prntscr.com/ifqoi7
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
