### ISSUE TITLE
Anub'arak in AN

### ISSUE THREAD

**Issue by RandomXD** [SunwellTracker/issues#523]
Decription: 
Anub'arak sometimes resets after 10-15 secs of starting the encounter in AN. He spawns back after few secs but no idea what makes him reset sometimes.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Valmere** [comment]
I've noticed this happen often as well when the boss is pulled the first time, usually during his first underground phase. Occasionally he'll target a unit other than the tank just before the submerge and I think this might be part of the issue. Reason being, if he targets say a totem or something and the totem dies or gets unsummoned by the shaman, this could be what triggers the boss to reset.

I have seen that happen during the first boss encounter in Azjol-Nerub during the first phase against the 3 Watchers. May or may not be the same thing that's happening on Anub, I'm unable to test it properly.

**Comment by Riztazz** [comment]
Imma give it a shot but i think i've tried everything that i could come up with including totems and destroying totems and so on and so forth and it never evaded :P

**Comment by Azathothh** [comment]
Couldn't reproduce - need more informations like combat log dump/video/ info about players classes inside /etc.
