### ISSUE TITLE
Pets dont bring you into combat state

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#524]
Description: I am a Warlock and whenever I send my pet on an enemy player or mob I do not enter combat state even if I use an ability on my target.

How it works: Send your pet on an enemy player and use abilities and still be out of combat.

How it should work: When you send your pet you should be in combat. The way its working now is if you send your pet on a rogue he can easily still sap you even if you are suppose to be in combat....

Source (you should point out proofs of your report, please give us some source): 
http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/
http://www.arenajunkies.com/topic/154952-pet-combat-sap-bug/
http://www.arenajunkies.com/topic/72876-pet-combat-bug/
https://github.com/dalaranwow/dalaran-wow/issues/1785

**Comment by Riztazz** [comment]
Works as intended, you wont be able to sap a player if a pet is going towards a victim but owner shouldnt be put in combat state
