### ISSUE TITLE
[Quest] Mythology of the Titans - never respawns

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#526]
Decription: the book for Mythology of the Titans never respawns

How it works: the book is lootable, but the respawn time is either very high or infinite

How it should work: the book should respawn instantly or almost instantly so everyone can loot it

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/PWnps unlootable

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
