### ISSUE TITLE
[Quest] Essential Artifacts - never respawn

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#527]
Decription: Essential Artifacts never respawn

How it works: Essential Artifacts for the same-named quest never respawn

How it should work: Essential Artifacts should respawn "eventually" (within some minutes is my guess)

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=2924/essential-artificials#comments:id=173038

**Comment by Dootz** [comment]
Wowhead comments(http://www.wowhead.com/quest=2924/essential-artificials) suggest that they shouldn't respawn. Most of ppl say that you might even do two runs to complete it.

**Comment by nimeral** [comment]
"Even if you have a full party with everyone on this quest you should all be able to complete it. There are enough in the instance, though some are hidden in seldom-visited nooks and crannies. **They also respawn eventually, so if you go back to areas you've already cleared you may find some more.**"

I misread for the first time too : )

**Comment by Dootz** [comment]
well, ok.

**Comment by Dootz** [comment]
Will be fixed with next update
