### ISSUE TITLE
Battered footlocker respawntime

### ISSUE THREAD

**Issue by Fibrile** [SunwellTracker/issues#528]
Decription: 
The respawn time 

How it works: 
The respawn time of battered lootboxes in Badlands, Angor Fortress have 2h respawn time.

How it should work: 
According to Wowhead comments, it should be much faster (either a few minutes, or a shared respawn of 1-is-always-spawned in one of the different spots).
It is also recommended in multiple lockpicking guides as a spot to level.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/object=179490/battered-footlocker#comments
"The respawn time can be as low as 5-6 minutes, but also significantly higher. 
It seems to me at least at the moment that there's always one footlocker somewhere, though that's only a guess."
"It spawns in several different places around the center room with tanks. Respawn time seems to be almost instant - the challenge is to find in what spot it happened. Just go around these places and it'll be there."

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by ecnu-zz** [comment]
Boxes still seem to be broken. I've been waiting over an hour for respawn.

**Comment by Dootz** [comment]
ok, i'll check that

**Comment by Dootz** [comment]
checked on angrathar. They should respawn every 15 minutes
