### ISSUE TITLE
[loottable] missing entries on Reinforced Junkbox

### ISSUE THREAD

**Issue by Gescht** [SunwellTracker/issues#529]
Decription: 
The item 43575 needs an update on its loottable.

How it works: 
current loot table
[https://db.darkwizard.pl/?item=43575#contains:0+1-2](https://db.darkwizard.pl/?item=43575#contains:0+1-2)

How it should work: 
what the loot table should look like
[http://web.archive.org/web/20110807091309/http://www.wowhead.com/item=43575#contains:0+1-15](http://web.archive.org/web/20110807091309/http://www.wowhead.com/item=43575#contains:0+1-15)

These epic items (43611, 43612, 43613) are missing on the loottable, thus unobtainable as of right now.
It's a small adjustment. Can be done by anybody with basic knowledge about the database.

Source (you should point out proofs of your report, please give us some source): 
Already given

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
