### ISSUE TITLE
 [Blueleaf Tubers]

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#53]
Decription: 
[[Blueleaf Tubers]](https://db.darkwizard.pl/?quest=1221) don't summon quest creature.

How it works: 
Quest item  [[Crate With Holes]](https://db.darkwizard.pl/?item=5880) don't summon ["Snufflenose Gopher"](https://db.darkwizard.pl/?npc=4781) no matter where i trying use that.

How it should work: 
https://www.youtube.com/watch?v=S9lrdq0AeoM

Source (you should point out proofs of your report, please give us some source): 
3-4 videos from YT

**Comment by siwy92** [comment]
still not work

**Comment by Sveron1** [comment]
It not working. I tried to use [](https://db.darkwizard.pl/?item=5880) in all places, and it always give you anserw "requires nearby tubers". You can read on wiki [](http://www.wowhead.com/quest=1221/blueleaf-tubers) that people had the same problem.

**Comment by Dootz** [comment]
Will be fixed with next server update
