### ISSUE TITLE
Amped for Revolt!

### ISSUE THREAD

**Issue by ivanlink** [SunwellTracker/issues#532]
Decription:  The quest works but it doesn't work as It should be working

How it works:  To many gargoyles spawn and destroy your machine before you get to do anything, which makes the quest a hell of a pain to complete.

How it should work:  Less gargoyles should be spawning at a time.

Source (you should point out proofs of your report, please give us some source):

**Comment by ivanlink** [comment]
The quest in general works pretty sloppy since the frostbloods that are around 2 shot you aswell. so you dont get any chance to complete the quest. I spent like 2 hours trying to do it and I gave up.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
