### ISSUE TITLE
[NPC Ability] Contagion of Rot

### ISSUE THREAD

**Issue by lipny** [SunwellTracker/issues#534]
**Decription:** 
Ability used by Zanzil Zombie in Stranglethorn Vale.
The disease is stacking instead of being refreshed. In attached SS, I have 4 different diseases on me, which results in being slowed down to 5.63 from 1.8. This is really annoying.

**How it works:** 
The disease is stacking and effect is cumulated. eg:
1.8 (starting speed) + 1.8 * 0,33 = 2,39
2,39 + 2,39 * 0,33 = 3,18
3,18 + 3,18 * 0,33 = 4,23
4,23 + 4,23 * 0,33 = 5,63 - total

**How it should work:** 
When effect is applied then current effect should be refreshed.

**Source (you should point out proofs of your report, please give us some s**ource): 
http://db.darkwizard.pl/?spell=7102#used-by-npc
![contagionofrot](https://user-images.githubusercontent.com/36561436/36339450-8bca6c60-13c6-11e8-9576-4f025e42022c.png)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
