### ISSUE TITLE
Trash mobs with no agro

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#535]
Decription: 
There are some trash mobs that we can't click or fight with

How it works: 
There are some trash mobs that we can't click or fight with

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021718_105914](https://user-images.githubusercontent.com/35955516/36339736-308977a8-13dd-11e8-9acf-bd52d628d2c3.jpg)
![wowscrnshot_021718_105922](https://user-images.githubusercontent.com/35955516/36339739-34de70b0-13dd-11e8-8da9-19101ccbea3c.jpg)

**Comment by Dootz** [comment]
Hi, in which area/zone i can find them? Or what's english name for that npc, or any npc nearby?

**Comment by artemmavrich** [comment]
![wowscrnshot_021718_124536](https://user-images.githubusercontent.com/35955516/36340193-e9da6676-13e8-11e8-9f06-88e3e3a2b8c4.jpg)

Shadowmoon Valley, where i am standing

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
