### ISSUE TITLE
Wrong script with vrykul ships

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#536]
Decription: 
There are some ships with vrykuls on the beach that are standing at one point. Please delete them 

How it works: 
There are some ships with vrykuls on the beach that are standing at one point. Please delete them 

How it should work: 
As i understand they must come to the beach and land there.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021218_204458](https://user-images.githubusercontent.com/35955516/36339763-ba6cc740-13dd-11e8-9649-a7340bbaefbd.jpg)
![wowscrnshot_021218_204316](https://user-images.githubusercontent.com/35955516/36339765-bebbfc26-13dd-11e8-9563-1182bf43cac5.jpg)
![wowscrnshot_021218_204305](https://user-images.githubusercontent.com/35955516/36339769-c48af292-13dd-11e8-8dcf-332729f929e9.jpg)

**Comment by Dootz** [comment]
Will be fixed with next update
