### ISSUE TITLE
NPS answering

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#537]
Decription: 
A lot of NPC answers like that. But instead of $c must be my name.

How it works: 
A lot of NPC answers like that. But instead of $c must be my name.

How it should work: 
A lot of NPC answers like that. But instead of $c must be my name.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021218_123643](https://user-images.githubusercontent.com/35955516/36339795-31fe0238-13de-11e8-8c30-3fd2ad55b96e.jpg)

**Comment by Dootz** [comment]
I'm aware of this issue, however each case must be approched individually so if you can please report them. Here are texts used by npcs in this quest: https://imgur.com/a/al8uP As you can see none of them include this symbol (this symbol is used to adjust displayed text to player's class). It might be connected to translation.
