### ISSUE TITLE
[Quest] Dissension Amongst the Ranks... unable to complete AT ALL

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#538]
Decription: 
Quest [Dissension Amongst the Ranks... ](https://db.darkwizard.pl/?quest=10776)unable to complete AT ALL.  The tabard is up, buff up and when i kill the mobs i have still 0/5.

How it works: 
Quest [Dissension Amongst the Ranks... ](https://db.darkwizard.pl/?quest=10776)unable to complete AT ALL.  The tabard is up, buff up and when i kill the mobs i have still 0/5.

How it should work: 
After killing mobs it must become 1/5, 2/5 etc ;D

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
