### ISSUE TITLE
[Quest] Battle of the Crimson Watch is not working at all

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#539]
Decription: 
[Battle of the Crimson Watch](https://db.darkwizard.pl/?quest=10781#?ref=sunwell.pl) is not working at all. 

How it works: 
[Battle of the Crimson Watch](https://db.darkwizard.pl/?quest=10781#?ref=sunwell.pl) is not working at all.  After accepting quest happen nothing. Mobs are not spawning at all.

How it should work: 
After accepting quest three waves one after another should spawn and then quest become completed

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021718_124046](https://user-images.githubusercontent.com/35955516/36340177-47acd9a6-13e8-11e8-80b5-fa7aa2ebdfbf.jpg)

**Comment by Dootz** [comment]
Tested locally. It's possible to start and complete quest. Then next player can start it aswell. It also works when previous player died and "failed" quest
