### ISSUE TITLE
Mobs wont agro correctly

### ISSUE THREAD

**Issue by hangak1** [SunwellTracker/issues#541]
Decription: 
When you attack a group of mobs with range attack!

How it works: 
Only the mob you attack will come fight you.

How it should work: 
All mobs that are near the mob you attack should attack you!

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
