### ISSUE TITLE
Zedd <Explorers' League> wrong position!

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#543]
Decription: 
[Zedd <Explorers' League>](https://db.darkwizard.pl/?npc=24145) wrong position, he must be on the hook. (look at pic and wowhead link)

How it works: 
[Zedd <Explorers' League>](https://db.darkwizard.pl/?npc=24145) wrong position, he must be on the hook. (look at pic and wowhead link)

How it should work: 
[Zedd <Explorers' League>](https://db.darkwizard.pl/?npc=24145) wrong position, he must be on the hook. (look at pic and wowhead link)

Source (you should point out proofs of your report, please give us some source): 
[wowhead photo](http://www.wowhead.com/npc=24145/zedd#screenshots)

And mine screenshot on Sunwell:

![wowscrnshot_021718_161209](https://user-images.githubusercontent.com/35955516/36342163-32dd2954-140b-11e8-85e3-a8e34d2f454d.jpg)

**Comment by Dootz** [comment]
http://www.wowhead.com/npc=24145/zedd#comments
> By Jibber (586 – 6·6) on 2009/10/05 (Patch 3.2.2)
> In another example of political correctedness gone wild, Zedd is no longer suspended from a meathook. He is now laying face down on the ground.
