### ISSUE TITLE
[Netherstorm - Ethereum Prison] 

### ISSUE THREAD

**Issue by tyk0s** [SunwellTracker/issues#544]
Decription: 
Too long respawn time on Ethereum Prison in Netherstorm. Should be around 1-2min instead of current 10-15min.

How it works: 
Farm Ethereum Prison Keys, open Ethereum Prisons in Netherstorm for random NPC spawn/Mob spawn.

How it should work: 
Faster respawns.

Source (you should point out proofs of your report, please give us some source): 
Didnt find anything in text form but found this youtube video.. https://www.youtube.com/watch?v=WQPBa2-jsrs

Been playing on other servers on the private server scene where it respawns much faster (1-2min)

**Comment by Akha72** [comment]
This point *Been playing on other servers on the private server scene where it respawns much faster (1-2min)* should not be raised.

**Comment by Dootz** [comment]
after some tests it seems that they never "respawn"

**Comment by Dootz** [comment]
Will be fixed with next server update
