### ISSUE TITLE
[Quest Borean Tundra] The Emissary - niepoprawny spawn Leviroth'a

### ISSUE THREAD

**Issue by Florkovsky** [SunwellTracker/issues#545]
Decription: Witam, wczorajszego dnia odkryłem problem z w/w misją The Emissary part 3, która ma na celu ubicie Leviroth'a. Będąc na miejscu wskazanym w misji, w pobliżu ruin Riplash w Borean Tundrze okazało się, że nigdzie ów mob się nie znajduje, czekałem również kilka godzin, ponieważ słyszałem o czasie jego respawnu, który ponoć wynosi godzinę, ustawiłem również makro na target by się upewnić czy nie znajduje się on gdzieś w teksturach lecz okazało się, że nigdzie go nie ma. Dziś postanowiłem napisać ticket do administracji by go odrespili czy coś w tym stylu, po chwili odpisał mi game master, który zauważył, że ów Leviroth zrespił się na drugim końcu mapy Borean Tundry a nie we wskazanym miejscu do którego prowadzi wątek misji. Po krótszej rozmowie z ów game masterem okazało się, że nie jestem pierwszą osobą, która wysyła ticket do administracji w związku z błędem misji. Poniżej załączam screen'a z aktualnym miejscem respawnu, wyciąłem jedynie swoje dane, które zawarte były w tickecie.

How it works: Misja prowadzi do miejsca gdzie nie aktualnie nie respi się Leviroth, znajduje się on na drugim końcu lokacji Borean Tundry, leży na plaży.

How it should work: Leviroth powinien respić się pod wodą we wskazanym miejscu obok ruin by zaoszczędzić administracji pracy z respawnowaniem go za każdym razem gdy ktoś wykonuje misję.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/LW8IMJh

**Comment by Dootz** [comment]
will be fixed with next server update
