### ISSUE TITLE
Drakkari Raptor Mount mobs

### ISSUE THREAD

**Issue by Ebeebe123** [SunwellTracker/issues#547]
Decription: 
Hi i'm the guy that noticed gundrak raptor skinning bug same thing happends with raptors in Drak'Tharon Keep

How it works: 
Drakkari Raptor Mount mobs drop nerubian hittin when skinned 

How it should work: 
They shouldn't drop it they are not nerubians

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=26824/drakkari-raptor-mount

**Comment by Dootz** [comment]
Will be fixed with next update
