### ISSUE TITLE
[RDF] No reward

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#55]
Decription: sometimes (?) RDF gives no reward - no money, no XP

How it works: at least two members of the group - Diana and Nimeralion - didn't get money/XP after killing Mutanus in WC. A GM said you don't do refunds (please let me know if it's possible to make an exception for mere 35 silvers), but I'm reporting it here so you can take a look and, hopefully, fix it for the future runs.

How it should work: RDF should give money and XP after killing the boss that gives a dungeon achievement.

Source (you should point out proofs of your report, please give us some source): one can see an achievement without a reward in chat on https://imgur.com/a/NN2ZS

Steps to Reproduce: this is purely a guess! I know it doesn't happen to everyone, so _maybe_ it's because we were grouped.
1) Create a group of two players
2) Queue for RDF
3) Complete the dungeon
4) Enjoy no reward (?)

**Comment by TheBigBallsOfFury** [comment]
This is intended. Rewards will be added with 3.3.0 content.

**Comment by nimeral** [comment]
Perhaps you misread, I don't mean a satchel with loot, I only mean bonus XP/money. Everyone I talked to (including a GM) say that you're meant to receive the rewards listed in the RDF UI after killing the main boss. Also, http://sunwell-community.com/index.php?/topic/34-rdf-experience/.

**Comment by fnm86** [comment]
Hello, we have LK but still we do not have Satchel of Helpful Goods :)
