### ISSUE TITLE
[Death Knight] Blade Barrier

### ISSUE THREAD

**Issue by Sensza** [SunwellTracker/issues#551]
Decription: 
"Whenever your Blood Runes are on cooldown, you gain the Blade Barrier effect" https://db.darkwizard.pl/?spell=55226

How it works: 
Blade Barrier nie jest aktywowane, gdy druga krwawa runa jest na cooldown po użyciu Vampiric Blood(https://db.darkwizard.pl/?spell=55233), Mark of Blood(https://db.darkwizard.pl/?spell=49005). 

How it should work: 
Blade Barrier powinno się aktywować za każdym razem, gdy obie krwawe runy są na cooldown niezależnie od użytych wcześniej umiejętności.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?spell=55226
http://www.wowhead.com/forums&topic=61031/death-runes-blade-barrier

**Comment by Sensza** [comment]
Tak, to wiem. I tak też być powinno, lecz dlaczego samo VB lub MoB nie nakłada Blade Barrier podczas combatu? Czy jest gdzieś jakiś haczyk, albo filmik na yt pokazujący inaczej niż jest to opisane przez talent? Blood Boil bez targetu i Pesti bez chorób jestem jeszcze w stanie zrozumieć ze względu na działanie tych spelli, choć to i tak trochę naciągane moim zdaniem. Nigdzie nie znalazłem wątku potwierdzającego, że powinno być TYLKO tak jak mówisz.

**Comment by Cwiercpasiec** [comment]
To co napisałem, to opis działania na sunwellu, dodałem tylko pare szczegółów o których nie wspomniałeś. Wydaje mi się, że Blood Barrier powinno odpalać się za każdym razem, kiedy mamy obie blood runy na cd. Bo dlaczego mielibyśmy odpalać ten talent np. icy touchem po użyciu przed pullem 2 blood boili (tak to teraz działa)?
