### ISSUE TITLE
AH buys/sells never reaching the mailbox.

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#552]
Over the last several days when I buy something from the AH it seems to be randomly not sending the bought items to the mailbox. I have logged out and everything. Happen with some herbs yesterday and arcane crystals today.

Also getting alot of mails saying the money is coming but the mail never changes to one with money or disappears. So not sure if not getting the money or it just not disappearing correctly.

**Comment by Cwiercpasiec** [comment]
Have you tried /reload after buying items from AH? Of course only if you don't see the items.

Mails telling you that gold is coming are a bit bugged, they do not dissapear, but the gold comes either way (in a second mail).

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
