### ISSUE TITLE
Death and Decay

### ISSUE THREAD

**Issue by Babbub** [SunwellTracker/issues#554]
Decription: 
Death and Decay circumference is to big in PvP. It also removes players with Shields (absorb effects on them) out of stealth.

How it works: 
Death and decay deals damage outside its circumference in PvP. It also removes players stealth no matter what buffs / effects they have active.
How it should work: 
The circumference should be smaller than what it is. Also should not remove players out of stealth if they have a Power word: Shield effect up and running.

Source (you should point out proofs of your report, please give us some source):

**Comment by knasen88** [comment]
are you immune to providing sources in your reports? they will just be thrown into the trashcan if you don't

**Comment by Snipergodx** [comment]
Stealth with absorb vs aoe was already reported, looks like just death and decay remained unfixed.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
