### ISSUE TITLE
Flare

### ISSUE THREAD

**Issue by Babbub** [SunwellTracker/issues#555]
Decription: 
Flare circumference is to big. Also works to shoot through pillars in Arena.

How it works: 
The hunter can shoot the flare through pillars, also the circumference is to big on flare in comparison to what it should be.

How it should work: 
It should not be castable through pillars. The target should be in line of sight. Also the circumference should be smaller.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
