### ISSUE TITLE
Holy Wrath - paladin skill

### ISSUE THREAD

**Issue by infatuationlol** [SunwellTracker/issues#558]
Decription:  The paladin skill - Holy Wrath is no longer doing damage to enemies.

How it works: 
Use the ability, no damage is done, ability goes on cooldown.

How it should work: 
Use the ability, damage is done, as well as undead and demon mobs getting stunned, ability goes on cooldown.

Source (you should point out proofs of your report, please give us some source):  I'm a level 54 paladin and the ability was working before the hotfix that went out today during Naxxramas, but the ability is no longer working after the hotfix.

**Comment by Cwiercpasiec** [comment]
Works as intended (should damage only demons and undead). #326 #517

**Comment by infatuationlol** [comment]
Based on the link you sent, you can understand that it is not working as intended for WotLK. The spell is supposed to damage all enemies, but add on a stun if the spell were to hit an enemy that is undead or a demon.
