### ISSUE TITLE
Shattered Halls - Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by Erzaskarlett** [SunwellTracker/issues#559]
Decription: Entered the boss room, he did not aggro 

How it works: 
Stuck in the room with a non active boss

How it should work: 
normal boss fight

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
He aggro after killing all Fel Orc Converts(4) in the room. Have you killed them?

**Comment by Erzaskarlett** [comment]
Hi Chris!
The party and I cleared the room and we tried multiple things. Consecrate, death and decay and taunting but he just stood there.
Thank you so much for checking it out though!

-Windy

**Comment by MrTide** [comment]
@Dootz I can confirm this happens from time to time you kill the adds and he just stays there i have to kill him and respawn him to get fixed
Regards

**Comment by samercyn** [comment]
Just tried this today with a group of friends and encountered the same issue. Tried multiple times with same result, i.e. dropped group and re-queued dungeon.

Got to boss room, killed the 4 orcs in front of the boss and the boss just stood there with us unable to attack him.

**Comment by Dootz** [comment]
will be fixed with next server update
