### ISSUE TITLE
[Loot] Bags don't drop

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#56]
Decription: bags don't drop.

How it works: http://db.darkwizard.pl/?item=4496#dropped-by claim they do, but they don't. Two chars on level 20, zero bag drops (a couple of 10+'s as well). In Global, people say that they buy bags or use tailoring.

How it should work: all/many mobs should drop a bag with a small probability, so people have some 6-slots by e.g. level 10, some 8-slots by e.g. level 25 and so on. I don't know the exact numbers, but 0.02 for each color (as in the database) seems reasonable. Probably you round the drop chance down at some point? : )

Source (you should point out proofs of your report, please give us some source): I've only found http://www.wowhead.com/item=828/small-blue-pouch#comments:id=180335 from TBC days

**Comment by dredd-sunwell** [comment]
They do, low drop rate.

**Comment by nimeral** [comment]
Indeed they drop! But on six 12-30 chars, I had one drop. 1864 creatures killed on lvl 30. It's definitely screwed and worth looking into.

Not that it's anyhow gamebreaking though : )
