### ISSUE TITLE
[Combat][Spell] Summon Gargoyle

### ISSUE THREAD

**Issue by Snipergodx** [SunwellTracker/issues#563]
Decription: 

How it works:  Dk wysyłając na gracza gargoyle (wystarczy wysłać i nic więcej) instantowo nabija mu combat, w dodatku przerywa jedzenie/picie.

How it should work: Gargoyle po wysłaniu na kogoś nie powinien nabijać mu combatu. Dopiero po wykonianiu ataku jak każdy inny pet itp.

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
Can confirm.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/553

**Comment by Snipergodx** [comment]
Its not related to #553, gargoyle is guardian too and behavior is different than normal pet like hunters or warlocks, are you installed wow yesterday?
