### ISSUE TITLE
Timear Foresees Infinite Agents in your Future!

### ISSUE THREAD

**Issue by Kokaina** [SunwellTracker/issues#565]
Decription: Quest works fine with one exception! We have to kill 4 of those infinite agents in CoS dung but sometimes one add doesnt spawn and people get 3/4 credit when this is daily Q.

How it works: Described above.

How it should work: There should always be 4x infinite agents in CoS dungeon run during arthas roleplay in this wooden house ;p

Source (you should point out proofs of your report, please give us some source):

**Comment by Sensza** [comment]
Isn't it a problem with Arthas? If he attacks infinite agent first (usually in the first group after they tranfsorm) then it's not counted as party's kill and quest can't be completed in a single run. That's what I heard but personally I've never missed any add for daily Q.

**Comment by 0vertime** [comment]
Sometimes the pack despawns instantly.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/574
