### ISSUE TITLE
[WARLOCK] Glyph of Felguard

### ISSUE THREAD

**Issue by grzybek** [SunwellTracker/issues#569]
Decription: Glyph don't improve total attack power, but green numbers.

How it works: Glyph don't improve total attack power, but green numbers.

How it should work: It should improve total attack power.

Source (you should point out proofs of your report, please give us some source): I just calculated it, same bug occured on feronis.

**Comment by Amarok-bt** [comment]
For me it works, there was a proper fix for that some time ago.
