### ISSUE TITLE
High droprates for white items

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#57]
Decription: 
Some monsters drops same white item almost everytime (like harpies in Durotar or Lighning Hide in the same zone). Bug confirmed by some other players, there is no possible way to count them all.

How it should work: 
Droprates should be extremely lowered.

Source (you should point out proofs of your report, please give us some source): 
Confirmed monsters:
Dustwind Savage (Durotar)
Dustwind Pillager (Durotar)
Lighning Hide (Durotar)
Greater Plainstrider (The Barrens)

*please, suggest others, if you encountered this

![wowscrnshot_012918_200223](https://user-images.githubusercontent.com/30598442/35527160-e48db00e-053a-11e8-8fe7-498efa21e719.jpg)

**Comment by Kokaina** [comment]
Already fixed.

**Comment by inscaped** [comment]
I've killed 10 Greater Plainstriders and it's not fixed.
