### ISSUE TITLE
[Shaman] Elemental Devastation proccing from weapon enchants

### ISSUE THREAD

**Issue by Amarok-bt** [SunwellTracker/issues#570]
Decription: 
Elemental Devastation talent should not proc from crits applied by weapon enchants e.g. Flametongue Weapon and Frostbrand Weapon. In result we can get almost 100% uptime with mediocre gear, where people in ICC BIS had a hard time to pass 90%.

How it works: 
Getting a crit from weapon enchants (Flametongue Weapon, Frostbrand Weapon) gives us a proc of Elemental Devastation.

How it should work: 
Crits from weapon enchants should not proc Elemental Devastation talent, they are not considered as regular spells which is the same case with proccing things like Reign of Dead trinket (right now it is possible to do so).

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/xoqFo
I've found no note about weapon enchants crits interacting with Elemental Devastation talent in over 200 pages long Elitist Jerks Shaman thread. Moreover i did my research comparing the combat logs from Method and Vision which shows that in a single target fight scenario BIS ICC shaman have a trouble getting above 90% of ED uptime where on Feronis it is easy to do so even with lesser gear. Screenshot also shows query log where there is combat log notification of Elemental Devastation proc after Flametongue Weapon crit which is not the case on a retail server.

**Comment by Kokaina** [comment]
Fixed, will be implemented with next update.
