### ISSUE TITLE
[Naxxramas] [NPC] Naxxramas Worshipper 25 man mode of Grand Widow Faerlina

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#573]
Decription: Together with Grand Widow Faerlina there are 6 adds, 4 Naxxramas Worshippers and 2 Naxxramas Followers. In 25 man mode the Worshipers can be Mind Controlled and they should have abbility called Widow's Embrace to prevent Faerlina's enrage. In 10 man mode they can't be controlled and you can prevent enrage on boss if you kill a worshipper close to boss. 

How it works: The 25 man version works same as 10 man. I controlled an NPC several times and the NPC didn't had the spell Widow's Embrace. After that we tried to kill one and it removed the enrage on boss. 

How it should work: There should be spell called Widow's Embrace on the taskbar when you mind control NPC Naxxramas Worshopper. And the enrage could be dispelled only if you use that spell, not if you kill the NPC close to boss. 

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Grand_Widow_Faerlina

**Comment by Azathothh** [comment]
Will be fixed at next server update.
