### ISSUE TITLE
[NPC] [Quest] Titanium Vanguard - Halls of Lightning and daily dungeon quest

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#575]
Decription: One of four daily dungeon quests is one in Halls of Lightning. The quest "Timear Foresees Titanium Vanguards in your Future!" requires you to kill seven Titanium Vanguards. The bug here is that you only need to kill 4 since every kill gives you 2x the objective. 

How it works: Every Titanium Vanguard kill completes 2xobjectives. Therefore you need to only kill 4 of them to finish the quest.

How it should work: Every NPC should count only as 1 kill, not as 2.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:Timear_Foresees_Titanium_Vanguards_in_your_Future!

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/503
