### ISSUE TITLE
[Quest] Sorlof's Booty - impossible to complete!

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#576]
Decription: 
[Sorlof's Booty](https://db.darkwizard.pl/?quest=11529) - impossible to complete solo. Elite giant  [Sorlof](https://db.darkwizard.pl/?npc=24914#sounds) 80 lvl must be killable by canon that is on the ship. BUT when you shot him by canon he take damage and instantly regen(evade) many times, so you can't kill him using cannon.  The only option is to kill him with 80 lvl character.

How it works: 
[Sorlof's Booty](https://db.darkwizard.pl/?quest=11529) - impossible to complete solo. Elite giant 80 lvl must be killable by canon that is on the ship. BUT when you shot him by canon he take damage and instantly regen(evade) many times, so you can't kill him using cannon.(Because he can't agro on us).  The only option is to kill him with 80 lvl character.

How it should work: 
You should kill him using cannon and then loot his treasure.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_021818_180726](https://user-images.githubusercontent.com/35955516/36353485-319f1368-14d8-11e8-851d-e9df121429a6.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/96
