### ISSUE TITLE
 [Reconnaissance Flight] quest bug , worked couple days ago

### ISSUE THREAD

**Issue by Szusterx** [SunwellTracker/issues#577]
Decription:  [Reconnaissance Flight] sholazar quest bug
How it works:  should kill some mobs when flying , then engine ll burn and u need 2 fly base  but u ddint recrive debuffs and cant land , happend to couple persons.

How it should work: should kill some mobs when flying , then engine ll burn and u need 2 fly base  with debuff then land.
Source (you should point out proofs of your report, please give us some source):  i cant finish this quest cuz cant get debuff when flying and killing mobs. Some ppls also

**Comment by Cwiercpasiec** [comment]
Duplicate. #136
