### ISSUE TITLE
[Quest] Death's Gaze

### ISSUE THREAD

**Issue by nmiller22390** [SunwellTracker/issues#578]
Decription: unable to turn quest in to the NPC, NPC name is Darkrider Arly

How it works: cant turn quest in, NPC doesn't have a grayed out "?" over her head either

How it should work: should be able to turn quest into the NPC

Source (you should point out proofs of your report, please give u
![wowscrnshot_021818_105226](https://user-images.githubusercontent.com/36602562/36353875-18bdf910-149a-11e8-9378-5143e8b313d5.jpg)
s some source):

**Comment by Dootz** [comment]
Hi, did you turn in http://www.wowhead.com/quest=13119/destroying-the-altars before Death's Gaze? Because that's what probably is causing this issue. I'll look into this.

**Comment by Talimar** [comment]
Yep. Same thing here. Turned in altar quest first and now can't turn in death's gaze.

**Comment by nmiller22390** [comment]
yes I'm pretty sure I turned in the altar quest first

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/302
