### ISSUE TITLE
[Westfall] The defias traitor is bugged

### ISSUE THREAD

**Issue by Etrusa** [SunwellTracker/issues#579]
Decription:  Defias traitor is bugged 

How it works: He is standing in Moonbrook but he does not move. He is stuck in Moonbrook

How it should work:Respawn in Sentinel Tower 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
