### ISSUE TITLE
Hammerfall Guard 

### ISSUE THREAD

**Issue by Doomwalkerr** [SunwellTracker/issues#58]
Decription: 

One of the guards in Hammerfall has a weird pathing, he is flying for a short time but it's really confusing for the eye
How it works: 
A guard is flying in the air

How it should work: 
make him not fly pls
![wowscrnshot_012818_224953](https://user-images.githubusercontent.com/35903205/35532100-5112cb3a-0539-11e8-8316-c3f76d4cae25.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
Will be fixed in a future update.
