### ISSUE TITLE
Felstalker Hoof

### ISSUE THREAD

**Issue by jinbojr** [SunwellTracker/issues#580]
Decription: 
Felstalker mobs in orc starting cave dropping their hooves without the quest and continually drops them after acquiring two hooves.

How it works:  Killing a Felstalker mob within the orc starting area drops nothing but it's hooves (if only the zhevra would do that!) despite not having the quest.

How it should work: 
Felstalker mobs should have its own loot table of Broken Fang, Ruined Pelt, Chipped Claw, all pouches, all ragged leather, all loose chain, all poor quality shields lvl 2 and lower, all frayed cloth, and grey weapons. The hooves should also not drop while on the quest.

Source (you should point out proofs of your report, please give us some source): 
![untitled](https://user-images.githubusercontent.com/36605391/36355155-8cde3470-149c-11e8-8c4d-a0775e3f6c13.png)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
