### ISSUE TITLE
[Urgent][Warrior] Slam resets swing timer rather than pausing it

### ISSUE THREAD

**Issue by set-theorist** [SunwellTracker/issues#582]
Decription: With the latest change to spells resetting weapon swing timer, warrior's Slam ability now resets the weapon swing timer whenever you successfully cast it.
This renders arms warriors rather useless in pve environments because they heavily depend on this ability.

How it works: 
When you sucessfully cast slam your weapon swing timer is reset, so at the end of the cast you must wait the full swing time for your next autoattack to go off, regardless of where your swingtimer was when you started casting slam.

Example with 3.00 weapon swing speed and 2/2 improved slam:
0.00: You swing your weapon
1.50: You begin casting slam. Your swing progress is 1.5/3 seconds but it is LOST.
2.00: You finish casting slam. Your swing was improperly reset and you are now at 0/3 seconds progress.
5.00: Your next swing goes off, 1.5 seconds later than expected.

How it should work: Slam should pause your swing timer, so that your current swingtime progress is stored and kept during the cast. At the end of the slam cast (or when it's canceled if you didn't manage to/canceled the cast) the swingtime continues from where it was stored.

Example with 3.00 weapon swing speed and 2/2 improved slam:
0.00: You swing your weapon
1.50: You begin casting slam. Your swing progress is 1.5/3 seconds.
2.00: You finish casting slam. Your swing progress is at 1.5/3 seconds.
3.50: Your next swing goes off.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Slam
"Bc icon/Wrath-Logo-Small Patch 3.0.2 (14-Oct-2008): Slam now suspends the weapon swing timer rather than resetting it."

**Comment by lowbur** [comment]
pls fix this

**Comment by sicknot1** [comment]
Holy shit

**Comment by Nadiirr** [comment]
Yes, a lot of reports about this bug.

**Comment by Yxt98** [comment]
Can you like fix this shit already?

**Comment by Sunaqt** [comment]
how is this not fixed yet ? its super crucial for pve arms!

**Comment by knasen88** [comment]
https://wow.gamepedia.com/Slam
Wrath of the Lich King Patch 3.0.2 (2008-10-14): Slam now suspends the weapon swing timer rather than resetting it. 

suspend = pause.
I mean it's nice and all now but it's broken in the other way now, you can see quartz trying to display it correctly but serverside the swing keeps on going.
https://streamable.com/bwxcf
