### ISSUE TITLE
[Quest] Uldaman quest items never respawn 

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#583]
Decription: Uldaman quest items never respawn 

How it works:  items for Find the Gems (item ID's 7669, 7670, 7671) and The Lost Tablets Of Will (item ID 5824) never respawn

How it should work: items for Find the Gems and The Lost Tablets Of Will should respawn instantly or almost

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/P4JGP is how it works half an hour after someone has looted the items; http://www.wowhead.com/quest=2201/find-the-gems, http://www.wowhead.com/quest=1139/the-lost-tablets-of-will do not indicate that the items are supposed to respawn, but I think it's a common sense - these quests can't only be completable by one person in a group

**Comment by Dootz** [comment]
Will be fixed with next update
