### ISSUE TITLE
[Druid] Innervate - generating too much threat

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#585]
Decription: The ability shouldn't have a any threat generation at all.

How it works: You generate immense amount of threat if it restores mana to a player in party/raid while in combat.

How it should work: You shouldn't gain any threat at all while the ability is restoring mana to a friendly player or to the caster itself.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/spell=29166/innervate#comments 
It is in the "generates no threat" group. Also there are no comments, no changelogs from retail and overall no information at all that indicates that this ability should generate ANY kind of threat.

**Comment by adamzimnyy** [comment]
I don't think legion spell description can be used as proof. It's a different spell than the wotlk one, and it doesn't even restore mana directly.

**Comment by Avarishd** [comment]
I mentioned wowhead for the coomments from patch 3.0 -3.3.5, there was no info that this spell did any kind of threat, also http://wowwiki.wikia.com/wiki/Innervate_(old) there is nothing that show any threat modifiers. http://wowwiki.wikia.com/wiki/Threat There is no threat modifier for Innervate.

**Comment by Riztazz** [comment]
@Kokaina @Shatterx

**Comment by Avarishd** [comment]
@Riztazz I provided more than enough information, which is relevant to the post.
Threat generated is 0,5 threat point per 1 mana gained. Which is 11799 threat no more, no less.
Currently as i mentioned in the bugreport you gain immense amounts of threat.

**Comment by akrom23** [comment]
http://web.archive.org/web/20100426234648/http://www.tankspot.com/showthread.php?47813-WOTLK-Bear-Threat-Values
Base is 5 per 1 mana, multiplied by 10.
