### ISSUE TITLE
[Level up/heirlooms] Not getting full health

### ISSUE THREAD

**Issue by Sasssyunicorn** [SunwellTracker/issues#586]
Decription: Whenever I level up I am not regening to full health/mana. Not sure if it's heirlooms or what

How it works:  ^ Not getting health/mana on lvl up.

How it should work: Should regen to full.

Source (you should point out proofs of your report, please give us some source):  Not much of a proof but should work.     https://imgur.com/a/Vsfaj

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
