### ISSUE TITLE
pet range

### ISSUE THREAD

**Issue by dathremar** [SunwellTracker/issues#587]
Decription: 
Bug pojawil sie niedawno(a przynajmniej na feronisie). Polega na istnieniu maxymalnego range dla komendy "pet attack". Napewno wystepuje u huntera, prawdopodobnie tez u warlocka i DK.

How it works: 
Jezeli cel jest oddalony od huntera o okolo 60yardow, to nie mozna wyslac na niego peta do ataku.  Jezeli pet juz atakuje, a cel oddali sie od huntera o w/w range, to pet przestaje atakowac.

How it should work: 
Range(inny niz "sight range") nie powinien miec zadnego wplywu na mozliwosc atakowania petem. Zawsze, kiedy mozna cos stargetowac, powinno sie tez moc wyslac na ow target peta.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
W tym raporcie nie ma źródła. Proszę znaleźć źródło (dowód) i zgłosić błąd poprawnie jeszcze raz.

Z góry dziękuję.
