### ISSUE TITLE
[Reputation] Kalu'ak reputation gain from quests is too low

### ISSUE THREAD

**Issue by Saveraa** [SunwellTracker/issues#590]
Decription: Po wykonaniu wszystkich nie powtarzalnych zadań dla frakcji Kalu'ak nie uzyskałem odpowiedniej ilości reputacji. 

How it works:  Po wykonaniu wszystkich nie powtarzalnych zadań moja reputacja z Kalu'ak wynosiła około 5000/12000. Za wykonanie zadania dostawałem 125/250 czasami 500 reputacji.

How it should work: Po wykonaniu wszystkich nie powtarzalnych zadań reputacja z Kalu'ak powinna wynosić około 2000/21000. Za wykonanie zadania powinno dostawać się 500+ reputacji.

Source (you should point out proofs of your report, please give us some source): Po kontakcie z GM polecono mi użycie jako dowodu tej strony http://wowwiki.wikia.com/wiki/Kalu%27ak . Żaden quest tutaj nie daje 250 reputacji tak jak było w moim przypadku.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.

**Comment by Dootz** [comment]
Will be fixed with next update
