### ISSUE TITLE
Random Lich king heroic

### ISSUE THREAD

**Issue by Cpburk** [SunwellTracker/issues#593]
Decription: 
You do not meet the requirements for the chosen dungeons. When i press random lich king heroic
3400gs been doing random all day
Something is broken in ur system

How it works: 
After you done all of them u get locked and cant play more.

How it should work: 
After you done all in **SPECIFIC SEARCH** you should be able to spamm **RANDOM LICH KING HEROIC**

Source (you should point out proofs of your report, please give us some source):

**Comment by 0vertime** [comment]
Think this is trinity core issue in both wotlk and cata. Although dungeon finder was added in 3.3

**Comment by RoyaxCH** [comment]
On Retail you were able to spamm Random Heroics 24/7 if you had the Stamina. You just got locked out for queuing a specific Dungeon.

**Comment by Riztazz** [comment]
You've done all the heroics on specific day and cannot do more, it will not be fixed on this patch - maybe later in the content ( 3.3 or so ) if higher-ups decide to do so, for now im closing this one since its intentional
