### ISSUE TITLE
Paladin bubble on encounters in naxx

### ISSUE THREAD

**Issue by Gasroil** [SunwellTracker/issues#594]
Decription: Pally bubble (the immune one) currently doesn't make you immune to certain things it should.

How it works: Divine Shield should block all damage/cc effects under its duration especially during Saph/Maexxna in Naxx (Saph frost damage aura and maexxnas aoe web stun should be nullified if bubble is used for the duration).

How it should work: 

Source (you should point out proofs of your report, please give us some source): https://cdn.discordapp.com/attachments/377217739384946699/415241588617379841/unknown.png

**Comment by dronebbq** [comment]
I think you should still get stunned, but not damaged by maexxna/sapphiron's spells

**Comment by Riztazz** [comment]
Both spells have attributes that allow them to hit targets with invulnerability, so it works fine
![image](https://user-images.githubusercontent.com/16348711/36431407-ce7407d6-1657-11e8-9ff3-76135731ad71.png)
![image](https://user-images.githubusercontent.com/16348711/36431431-da65a48c-1657-11e8-999f-16bda35011b5.png)
