### ISSUE TITLE
Sacred shield/beacon of light/Divine plea combat bug pvp

### ISSUE THREAD

**Issue by Gasroil** [SunwellTracker/issues#595]
Decription: As holy if you have sacred shield up you get combat locked briefly every 6 seconds or so if you applied it before combat has ended, i have had the same thing happen with beacon of light rarely and divine plea sometimes. IE I sacred shield myself just before combat ends and drop combat, then every 5-6 seconds get put into combat making it almost impossible to drink and impossible to mount.

How it works: Combat locked due to the buff ticks?

How it should work: Drop combat 

Source (you should point out proofs of your report, please give us some source):  Didn't get a video of it but it happens sporadically and not all the time usually I just click off buffs and it stops.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
