### ISSUE TITLE
[PvP] Ruins of Lordaeron Arena - line of sight issue with tombstone

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#596]
Decription: 
![lordaeron-tombstone](https://user-images.githubusercontent.com/17804807/36400594-1a8bf9c0-15d2-11e8-82bc-fa1d37c01827.jpg)

The tombstone shown in this picture ignores line of sight.

How it works: 
One can cast through it.

How it should work: 
One shouldn't be able to cast through it.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.

**Comment by ujellyx** [comment]
Source:
https://wow.gamepedia.com/Ruins_of_Lordaeron_(arena)
