### ISSUE TITLE
SPIRITUAL ATTUNEMENT

### ISSUE THREAD

**Issue by asq155** [SunwellTracker/issues#597]
Decription: 
A passive ability that gives the Paladin mana when healed by other friendly targets' spells. The amount of mana gained is equal to X% of the amount healed.

Protection paladin passive talent.
How it works: 
IT DOESN'T WORK

How it should work: 
A passive ability that gives the Paladin mana when healed by other friendly targets' spells. The amount of mana gained is equal to 10% of the amount healed.(2/2)

Source (you should point out proofs of your report, please give us some source): My friend asked, why he runs out of mana so fast - answer was very quick, healing done doesn't give mana %.

**Comment by Cwiercpasiec** [comment]
Logs from ToGC25, details for my guild's prot pal: 
http://www.worldoflogs.com/reports/5oguxwbmxga69jf0/details/0/?s=3245&e=3394
You can see, that Spiritual Attunement works: Spiritual Attunement | 11504 mana

**Comment by ujellyx** [comment]
On Angrathar i've noticed this aswell. Overhealed our tank-paladin with 10k+ greater heals and he doesn't gain any mana from it.

**Comment by Cwiercpasiec** [comment]
@ujellyx Spiritual Attunement shouldn't proc from overheals.
http://wowwiki.wikia.com/wiki/Spiritual_Attunement
"Mana will not be restored if the Paladin is at full health, regardless of the ability used (HoT or direct heal). Mana will also not be restored from an ability originating from the Paladin. "
