### ISSUE TITLE
[NPC] Witchwing Windcaller bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#598]
Decription: 
Witchwing Windcaller in The Barrens isn't using Enveloping Winds ability.

How it works: 
Witchwing Windcaller in The Barrens isn't using Enveloping Winds ability.

How it should work: 
Witchwing Windcaller should use the ability.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next update.
