### ISSUE TITLE
[NPC] Southsea Cannonneer bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#599]
Decription: 
Southsea Cannonneer does shoot now, but tries to run away when you close to melee range.

How it works: 
Southsea Cannonneer runs away when you're in melee range.

How it should work: 
Southsea Cannonneer should shoot until you're in melee range and shouldn't run away.

Source (you should point out proofs of your report, please give us some source): 

Edit: Seems like it doesn't appear 100% of a time, but with 3-4 pulls with my warlock I got 2 of them running away straight to the crowd.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
