### ISSUE TITLE
[Elwynn Forest] Kobolds high fire resistances

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#6]
Decription: 
Kobolds you face while doing "The Fargodeep Mine" and "The Jasperlode Mine" probably have very high fire resistances (compared to retail WotLK). 

How it works: 
For example rank 2 Fireball (31-45) deal far less damage than rank 1 Frostbolt (18-20). Fireball in this example hits for like 14 damage average.

How it should work: 
Fire spells in this zone always did tooltip damage.

Source (you should point out proofs of your report, please give us some source): 
Confirmed monsters:

Kobold Tunneler
Kobold Miner
Kobold Geomancer

Probably some others.

**Comment by Crackaw** [comment]
Can you give us some proof about it?

**Comment by inscaped** [comment]
Las time I checked it was in late beta, got to test again.
