### ISSUE TITLE
Didn't receive "Giddy Up!" achievement

### ISSUE THREAD

**Issue by lotsOfSnow** [SunwellTracker/issues#60]
Decription: I just learned the apprentice riding skill at Randal Hunter in Elwynn but didn't get "Giddy Up!" achievement.

How it works: I went to Randal Hunter in Elwynn and bought the Apprentice Riding at level 26 and didn't get rewarded with the achievement.

How it should work: After learning the skill I should get "Giddy Up!"
![source](https://user-images.githubusercontent.com/28030565/35532399-654f4046-053a-11e8-9f60-45b7944176af.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
Hello, I have checked this issue but I cannot re-create this bug.
