### ISSUE TITLE
[NPC] Theramore Preserver bug

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#600]
Decription: 
Theramore Preserver in The Barrens goes straight melee.

How it works: 
Theramore Preserver doesn't cast anything.

How it should work: 
Theramore Preserver should cast Renew, Heal and Holy Smite spells.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=3386/theramore-preserver#abilities

They were nerfed somewhere around Cataclysm I suppose (removed both healing spells)

https://vanilla-twinhead.twinstar.cz/?npc=3386#abilities

**Comment by Dootz** [comment]
Will be fixed with next update.
