### ISSUE TITLE
NPC invisible Argent Vanguard town in icecrown

### ISSUE THREAD

**Issue by Aragonbabyy1** [SunwellTracker/issues#603]
Decription: 
 
Every NPC is missing or invisible

How it works: 

Can't see any quest givers or NPC

How it should work: 

I should be able to see NPC and accept quest/use quartermaster

![npc missing](https://user-images.githubusercontent.com/36653963/36407309-6fb5ccca-15b2-11e8-95b4-a8296e7e5210.png)
![npc missing](https://user-images.githubusercontent.com/36653963/36407320-8c4700de-15b2-11e8-96c0-4b5f4c6146d9.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by adamzimnyy** [comment]
Are you sure this is not some quest chain that you haven't completed?

![image](https://user-images.githubusercontent.com/14812161/36424540-e74c9a7a-1643-11e8-87ce-a29d0d4347db.png)

**Comment by Avarishd** [comment]
You are in a phase, part from the short quest chain in the camp.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
