### ISSUE TITLE
Idol of Awakening Bugged

### ISSUE THREAD

**Issue by Jadefoxxx** [SunwellTracker/issues#604]
![wowscrnshot_021918_211119](https://user-images.githubusercontent.com/36654809/36408297-73d8a528-15b9-11e8-95cc-f0028bd92d07.jpg)
Decription: 

The Idol of Awakening from Gothik the Harvester is bugged and doesn't work correctly.
How it works: 

Broken and Reduces the Mana cost of Rejuvenation by 75
How it should work: 
It should be reducing the mana cost of Rejuvenation by 106 like it's listen on the item.
![broken1](https://user-images.githubusercontent.com/36654809/36408275-54ff9fda-15b9-11e8-9e52-e0b3934ad2cd.jpg)
![broken2](https://user-images.githubusercontent.com/36654809/36408277-57a95f50-15b9-11e8-9f48-96c427731024.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by Jadefoxxx** [comment]
No response about this at all? It's clearly bugged and not working as intended. Please look into this

**Comment by Crackaw** [comment]
I checked recently and its working
