### ISSUE TITLE
HELP! Quest in Nagrand Bugged

### ISSUE THREAD

**Issue by failinator72** [SunwellTracker/issues#605]
Description: 

Upon completion, the quest giver Corki has a typo in his completion text. Pretty sure it is a typo (likely a $ instead of a %)

How it works: 

Thanks $C for your help!

How it should work: 
Thanks "player name" for your help!

Source (you should point out proofs of your report, please give us some source): 
I submitted ticket and talked to Nadiir confirming it

**Comment by Dootz** [comment]
Will be fixed with next update.
