### ISSUE TITLE
Mature Lasher

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#606]
Decription:  Mature Lasher (https://db.darkwizard.pl/?npc=34300#?ref=sunwell.pl) is respawning every 10 minutes.

How it should work:   It should have the same respawn rate as the Brittle Revenant(https://db.darkwizard.pl/?npc=30873) since both are the WG controlled elementals.

**Comment by Dootz** [comment]
According to Wowhead comments their respawn time should be around 10 minutes. Issue marked as invalid, unless proven otherwise.
