### ISSUE TITLE
Gluth's zombies

### ISSUE THREAD

**Issue by Niknais** [SunwellTracker/issues#607]
Decription: Gluth zombies are bugged

How it works: When i, as Arcane mage cast spell ''Slow'' http://db.darkwizard.pl/?spell=31589
on thees zombies, my effect from this spell holds only 4-5secs.

How it should work: Slow spell must stay on them for full timer, 15secs.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
