### ISSUE TITLE
Problem with Lockbox/Duskwood chest

### ISSUE THREAD

**Issue by eldziubek** [SunwellTracker/issues#609]
Decription: Hello, I can't open any lockbox and Duskwood chest

How it works: I have lockpicking skill +100 but i can't open any lockbox even those from lvl 1 lockpicking. 
I can't skilling lockpicking use Duskwood chest (Westfall) I've completed all the rogue mission (Kleven's Tower and The Touch of Zanzil) 

How it should work: It just should work :D

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
