### ISSUE TITLE
Berserking no procc on offhand

### ISSUE THREAD

**Issue by Bisseleeten** [SunwellTracker/issues#611]
Decription: 
Berserking enchant (http://db.darkwizard.pl/?item=44492) doesnt procc on offhand.

How it works: 
Doesn't procc

How it should work: 
Chance to procc on attack

Source (you should point out proofs of your report, please give us some source): 
http://www.gnarlyguides.com/class-guides/wow-3-3-5a-assassination-rogue-pve/ claiming 2 berserkers is best enchants, wouldn't be that way if offhand can't procc
To recreate play rogue, enchant offhand with berserking, use only offhand, spam shiv and auto on mobs

**Comment by Cwiercpasiec** [comment]
Berserking procs both from offhand and main hand weapon, first tested with 2 daggers with berserking, then changed main hand to sword without berserking.
https://imgur.com/a/yvL1k

**Comment by Bisseleeten** [comment]
Sorry poorly worded. Try without mainhand weapon, or dissarmed

**Comment by Cwiercpasiec** [comment]
Without main hand weapon: https://imgur.com/a/38lS3
Still procs.

**Comment by RoyaxCH** [comment]
Is this maybe a Angrathar specific Problem? Cwiercpasiec is obviously playing on Feronis (Gearscore isnt reachable on Angrathar)
