### ISSUE TITLE
[DK] Death Grip bug.

### ISSUE THREAD

**Issue by Claritylols** [SunwellTracker/issues#612]
Decription: 
Death Grip doesnt grip.

How it works: 
When using Death Grip on a enemy player the grip doesnt actually work all the time,
It works 50% of the times and it hasnt to do with them being stuck or immobilized.
Sometimes the grip makes them "teleport" to your location instead of gripping. This is a graphical bug i think.

How it should work: 
They should be gripped without teleporting.

Source (you should point out proofs of your report, please give us some source): 
Playing DK right now.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
