### ISSUE TITLE
[Rogue] Vanish and Strangle Problem

### ISSUE THREAD

**Issue by nabermert** [SunwellTracker/issues#613]
Decription: 
Vanish: at the point where the rogue is vanishing, he dodge every spell but on Angratha he doesn't do that.
Strangle: the silence effect doesn't exist here, thats a big fail.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
