### ISSUE TITLE
Compendium of the fallen quest 

### ISSUE THREAD

**Issue by deiltis** [SunwellTracker/issues#614]
Decription: Quest item couldnt be found in the library.

How it works: Book cant be found  in library dungeon.

How it should work: Should be found in library.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
![wowscrnshot_022118_162810](https://user-images.githubusercontent.com/25490436/36488652-48a93a4a-1724-11e8-9898-825937d7c457.jpg)
![wowscrnshot_022118_162822](https://user-images.githubusercontent.com/25490436/36488653-48ce7c38-1724-11e8-915f-e4d7e93b5cca.jpg)

It's in hall before last boss.
