### ISSUE TITLE
Execute doing nothing 20% of the times.

### ISSUE THREAD

**Issue by Helltrix** [SunwellTracker/issues#615]
Decription: There is a bug that is occurring with execute casting, consuming rage, playing the animation and then doing nothing.

How it works: Execute is cast when the mob is under 20% hp but nothing happens, it just drains your rage, playing the animation and then doing nothing. It does not miss, does not get dodged etc.

How it should work: Execute should do damage every time you use it under 20% of the mobs health unless the mob is invulnerable.

Source (you should point out proofs of your report, please give us some source): It is hard to prove this with pictures but it is easily recreated if you play a warrior for 5 minutes.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
