### ISSUE TITLE
Northrend Alchemy Research does not work

### ISSUE THREAD

**Issue by Hadaa** [SunwellTracker/issues#617]
Description: Northrend Alchemy Research does not work, when I used it the first time

How it works: D. 21.02.2018 I was leveling my alchemy and got the spell "Northrend Alchemy Research" I used the spell and got the potion 1 x [Elixir of Expertise]. I should have learned the spell of my alchemy spell book but I cant. 

How it should work:  When I use Northrend Alchemy Research I should learn a spell, but that did not happen for me. It is my first time I have used the spell so you should be able to see this is a bug.

Source (you should point out proofs of your report, please give us some source): I do not have any proof other than as I mentioned above that I should have learned one spell from Northrend Alchemy Research but I haven't. You can check my alchemy spell book and see that I only know the trainer recipes.

**Comment by Hadaa** [comment]
I have added some screenshots as well so you can see CD and also that I have not learned anything;

https://gyazo.com/1dc84b95fb0de1af833d72ffcc08b603
https://gyazo.com/1d89ba97f9643f59dde85674cf1057c2
https://gyazo.com/02e282ffe235cb914fb68df0da94522f
https://gyazo.com/d1a497e3889716bada96842612d4baef

**Comment by Valmere** [comment]
Working as intended - the Northrend Alchemy Research has a chance at discovering a new recipe, it is not supposed to be a 100% thing.

http://www.wowhead.com/spell=60893/northrend-alchemy-research#comments:id=467349
