### ISSUE TITLE
[Vanilla Dungeons] Bosses body despawn short after kill

### ISSUE THREAD

**Issue by sicknot1** [SunwellTracker/issues#62]
Decription: Globally speaking, all mobs despawn fast, looted or not, but while on instances, bosses killed shouldn't despawn

How it works: Doing BFD with the quest http://wowwiki.wikia.com/wiki/Quest:Blackfathom_Villainy_(Horde) we defeated Twilight Lord Kelris whose quest drop is http://wowwiki.wikia.com/wiki/Head_of_Kelris, some of us including me forgot to loot the head, count 2 or 3 minutes after the kill and we went back, to our surpise the body was nowhere to be found therefore we couldn't complete the quest.

How it should work:
Dungeon Bosses shouldn't despawn after killed

Source (you should point out proofs of your report, please give us some source): 
Im sorry but for obvious reasons i cannot take a picture of something thats no longer there.
How to reproduce: Kill any dungeon boss and see their bodies despawn shortly after

**Comment by sicknot1** [comment]
No replies?

**Comment by Riztazz** [comment]
It was related to dynamic respawn, it is now disabled hence the issue shouldnt be present
