### ISSUE TITLE
[Angrathar][Mount/Elite/Rare] Time-Lost Proto Drake, blizzlike ?

### ISSUE THREAD

**Issue by davchichi4** [SunwellTracker/issues#620]
Decription: 

It's been more than 2 weeks since I farm the "Time-Lost Proto Drake" & to be honest with 4 account with the flying mount & 6-10hours per day. The problem is that I did not see either the proto or Vyragosa. And i'm not the only one, many players did the same and note the same problem. Only one ppl has been see with the proto on the server since the beginin.

How it works: 
I don't know. But after every restart, everyone is going to try to find one of the drakes (Vyragosa or Proto) cause everyone has noted that after every restart Dirkee respawned.

I see 20 spawn spots on your database : https://db.darkwizard.pl/?npc=32491#drops
Same for vyragosa..

And i'm not sure they follow the blizzlike path

How it should work:

There is only 4 spawn spots for Vyragosa & the proto normally.
And only Vyragosa & the proto share the spawn time. Dirkee & Skoll are alone. They don't share anything with both of the drakes. 

When vyragosa or proto is dead, there is 6hours before the next respawn between vyragosa & proto. Obivously vyragosa got a hightest spawn rate.

Vyragosa & the proto follow the same path.

The spawn spot coordinates are: [31, 69] - [51, 70] - [35, 76] - [52, 34] Each spawn spot can spawn either Time-Lost Proto-Drake or Vyragosa.

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Time-Lost_Proto-Drake all u need to know is there. Legion has only changed the total heatlh of the proto 18k wotlk then 8k en legion.
https://www.youtube.com/watch?v=eh2BE9emxXg (spawn spot 2010)
https://www.youtube.com/watch?v=SRbOssnGZ9s (the path video 2009)
https://www.youtube.com/watch?v=G4_HrCXXE4o&list=PL82E7111A4B926C46 (2011 spawn spots)
https://www.youtube.com/watch?v=-icGmm0eFUg (the path video 2009)

**Comment by davchichi4** [comment]
Today 24/02/2018 i saw the Lost in time Proto drake and i followed him to see if the path is blizzlike. And i note that the path is far, far from blizzlike. So there is the real fly path https://i.ytimg.com/vi/VOkGcPVFwOU/maxresdefault.jpg i mean the blizzlike fly path and there is 4 path. So i have the feel that i waste to much time... Unfortenuly i was with my 150% fly mount so i just lost the proto cause he was to fast for me..

**Comment by Sensza** [comment]
One day I had an opportunity to make the same observations(with 280% mount speed) and I noticed Vyragosa/TLPD uses only one long path merged from the 4 paths linked above by davchichi4. A little correction to the flight path itself would be nice as well, because there seems to be strange points in their point-to-point trajectory.

**Comment by Dootz** [comment]
So it's possible to find him now that we have confirmation from at least 3 ppl (@davchichi4 , @Sensza and https://github.com/SunwellTracker/issues/issues/681). I'll look into his paths tho.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
