### ISSUE TITLE
[Angrathar] Lockpicking gates

### ISSUE THREAD

**Issue by ghertruda** [SunwellTracker/issues#622]
Decription: Lockpicking gate in gnomeregan doesnt give skillup after you lockpick it once, will probably be the same for every gate in the game, this makes lockpicking significantly harder to level up

How it works: Gate doesnt give a skillup after first opening

How it should work: Gate should give a skillup whenever it resets back to its locked position or a chance for a skillup respective to the lockpicking skill

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
