### ISSUE TITLE
[Razorfen Kraul] Escort NPC disappearing at turn-in

### ISSUE THREAD

**Issue by Alex-Cas** [SunwellTracker/issues#624]
Decription: 
After doing the quest [Willix, the Importer], the NPC we escort (also the one we turn in the quest to) only seems to accept one turn-in.

How it works: 
We end the escort quest, and try to turn it in to the guy we just escorted. One guy turns the quest in, then the NPC flies back to his initial position and we cannot talk to him. 

How it should work: 
Everyone should be able to turn in the quest after we end it.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
