### ISSUE TITLE
Sethekk halls prophet fears

### ISSUE THREAD

**Issue by Buddik** [SunwellTracker/issues#629]
Decription: 
the prophets in sethekk halls are fearing way too often and it is making the second part of the dungeon unplayable, also it doesnt seem to be factoring in diminishing returns, i have played on multiple tbc servers and also the original tbc and i cant remember ever beeing feared for that long or that often, i realise that it is a tbc dungeon and not a priority but getting it in the dungeonfinder at this point means either dealing with more wipes than is necesary or just leaving.

otherwise great server thank you alot <3

How it works: 
fears too often and ignores diminishing returns

How it should work: 
longer time inbetween casts and factoring in diminishing returns to make doable. i do not know the exact numbers but i know the current ones just arent right

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
