### ISSUE TITLE
[Angrathar][Druid] Druids can need on Shields in Instances

### ISSUE THREAD

**Issue by TaKu007** [SunwellTracker/issues#630]
Decription: 
Druids can need on Shields in Instances, even tho they cant use them.

How it works: 
Druids can need on Shields in Instances, even tho they cant use them.

How it should work: 
Druids can`t need on Shields in Instances, as they cant use them.

Source (you should point out proofs of your report, please give us some source): 
can add screenshot at later rimes, but in general i could roll need on every shield i encountered.

**Comment by 0vertime** [comment]
Same with DK.

**Comment by RoyaxCH** [comment]
Same with Rogues
