### ISSUE TITLE
[Achievement] - Oh Novos!

### ISSUE THREAD

**Issue by Deamonik68** [SunwellTracker/issues#631]
"Defeat Novos the Summoner in Drak'Tharon Keep on Heroic Difficulty without allowing any undead minions to reach the floor." 

We have to cover stairs, and not let any undead to hit the floor coming from the top. We made sure that nobody passed I tried to achieve this many times. We killed every undead and followed instructions to get it, but we didn't. Nobody hit the floor, I saw people that they have this achievement, so it had to bug just recently. It is needed for Glory of the Hero achievement, which i can not get if this is bugged.

Simply, during the first phase when the boss is calling undead from the stairs, they can not hit the floor. And you have to stop them on the stairs. Then he spawn NPCs Crystal Handlers - which can not get close to the boss either. By following these steps you get achievement. I tried it multiple times but i didn't get it.

Please look at it, it is very important achievement, since he unlocks mount. Thank you.

**Comment by Azathothh** [comment]
Just checked that - it doesn't work when Novos use 59910 - [Summon Minions, rank 1 enUS] which spawns 4x Fetid Troll Corpse on floor near him (Entry: 27598.- same one as Fetid Troll Corpses in phase1)

**Comment by Panikx** [comment]
Tried it today without stun/root/snares : still not working

**Comment by Dootz** [comment]
Fixed.
