### ISSUE TITLE
Battle at Valhalas quests

### ISSUE THREAD

**Issue by Mysoopa** [SunwellTracker/issues#632]
Decription: 
Battle at Valhalas

How it works: 
Upon disengaging the quest mob summoned to the arena, the quest will autocomplete. 

How it should work: 
Upon killing the summoned mob to the arena, the quest should complete

Source (you should point out proofs of your report, please give us some source): 
Tide

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
