### ISSUE TITLE
[Class=Warlock] Conflagration

### ISSUE THREAD

**Issue by robpm** [SunwellTracker/issues#633]
Decription: 
There is a delay in the time you are able to use conflagration after you apply immolate to a target

How it works: 
It appears that the indicator of whether you can cast conflagrate on target after applying immolate is based in the distance, such as it was casted as a proyectile. After some tests, by casting immolate at melee range I could conflag almost instantly (still not instantly) but at range it takes almost 1,5s, 

How it should work: 
It should be instant (in the same global after casting immolate), so when you mash the conflag button while casting immolate, it should work.

Source (you should point out proofs of your report, please give us some source): Different tests on dummys, my laptop is a potato and I cannot record video.

Proof; https://www.youtube.com/watch?v=XXPFyAZZoNk here it shows multiple times how the conflagration is available as soon as immolate is applied Example: 10:31, he casts immolate, and as soon as cast is over conflag and rocket.

Spells: http://db.darkwizard.pl/?spell=47811, http://db.darkwizard.pl/?spell=17962

**Comment by Akha72** [comment]
What a load of rubbish. Delay between Immolate and Conflagrate was introduced back in Vanilla WoW. No source, nor proofs, pls close.

**Comment by robpm** [comment]
Akha, your comment is the only rubbish here, even on TBC this was on: https://www.youtube.com/watch?v=A4NL-GEoKEY min 3:36

**Comment by Akha72** [comment]
Do you realise you posted movie recorded on a private server? It's even stated in the description.

**Comment by Akha72** [comment]
In the second video in 3;36 Drakedog casts Immolate-Incinerate-Conflagrate. Are you serious or just trolling?
