### ISSUE TITLE
Aces High! [quest]

### ISSUE THREAD

**Issue by PowerKeeper666** [SunwellTracker/issues#636]
Decription: 
quest allows you to ride a drake similar to one from EoE raid.

How it works: 
you can target mobs and other players with drake's spell

How it should work: 
you should only be able to target the quest npcs, which are drakes flying high above coldarra
(where oculus last boss is)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next update
