### ISSUE TITLE
Heigan the unclean 25man ( hunter pets/warlock pets )

### ISSUE THREAD

**Issue by Vanggaard9300** [SunwellTracker/issues#638]
Decription: 
they are getting 1 or 2 shotted because the dmg is too high from the dance

How it works: 
they die

How it should work: 
they should not die cuz you guys buffed the content, you need to recode the dmg from the dance so combat pets takes less dmg

Source (you should point out proofs of your report, please give us some source): 
go test it and you will see

**Comment by CiriSunwell** [comment]
Its not bug, pets get -90% dmg from it but it not make them immortal. They raised damage so pets take more damage also.

**Comment by RoyaxCH** [comment]
What kind of Report is this?
"The announced Buffs to the Content makes it hard to play, thats a bug" ?

Pets aren't Immortal, thats why the Top-Hunters get praised for their Pet-Control, not how hard they press Aimed Shot.
