### ISSUE TITLE
The Four Horsemen 25man ( Combat pets )

### ISSUE THREAD

**Issue by Vanggaard9300** [SunwellTracker/issues#639]
Decription: 
Every combat pet are getting marks

How it works: 
pets get marks and blow up raid

How it should work: 
pets should not be counted as players 

Source (you should point out proofs of your report, please give us some source): 
go test it

**Comment by RoyaxCH** [comment]
Do you have any Source? I couldnt find anything describing that Pets don't get marked in my Research.
