### ISSUE TITLE
Quest: "Cluck" - Westfall

### ISSUE THREAD

**Issue by Goldelian** [SunwellTracker/issues#64]
Decription: The quest "Cluck" can be found at Saldean's Farm in Westfall while spamming "/chicken" while having in target one of the 2 chickens in front of the small house.

How it works: After spamming "/chicken" multiple times (as intended) on the chicken(yellow colour - unfriendly), the chicken turned green(friendly) and i was able to accept the quest. After that i went to buy the chicken food from the NPC next to me.
After i bought it got the completed notification on my screen and it showed up as "Completed" on my quest log as well.
**_After that i am suppose to go back to the same chicken and complete the quest._**

How it should work: 
After spamming "/chicken" multiple times (as intended) i was able to accept the quest. After that i went to buy the chicken food from the NPC next to me.
After i bought it got the completed notification on my screen and it showed up as "Completed" on my quest log as well.
Here is where the bug happens. When i went back to the chicken, she is already yellow colour unfriendly, which means if i am trying to do a right click to turn in the quest, the chicken will die.

Source (you should point out proofs of your report, please give us some source): I think i made it quite clear. If it's needed, i will go back or you can contact me at any time on discord or in-game.

**Comment by sitowsky** [comment]
It's working properly - you have to /cheer at the chicken (that is blizzlike).
