### ISSUE TITLE
Quest: Assault by Ground

### ISSUE THREAD

**Issue by Tangsus** [SunwellTracker/issues#640]
Decription: 3 of 5 Skybreaker Infantery stay at the top of the mountain, so you cant finish the Quest where you have to lead a least 4 Infantery to the City Yimirheim.
![wowscrnshot_022218_210122](https://user-images.githubusercontent.com/36744630/36561300-aa07460c-1813-11e8-949e-1e8e5bb83a20.jpg)
![wowscrnshot_022218_210140](https://user-images.githubusercontent.com/36744630/36561349-c5ea437e-1813-11e8-8242-2581db934280.jpg)

How it works:  IF you start the quest you start with just 2 Infantery at the ground, the other 3 are always on the top of the mountain, an stay there, even if you restart the Quest. So you always end up with 2/4

How it should work: Normally all 5 Stould hang around at the Startingpoint of the Quest and not anywere in the moutain

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/229
