### ISSUE TITLE
Shamman Talents:  (Improved Windfury Totem)

### ISSUE THREAD

**Issue by scv901025** [SunwellTracker/issues#646]
Decription: increase the meele haste granted by your windfury totem by 4%  2/2 points

How it works:  doesnt increse the meele haste

How it should work: he should increase the meele haste granted buy windfury totem like icy talons on dks

Source (you should point out proofs of your report, please give us some source):

**Comment by Deamonik68** [comment]
I can confirm that this talent doesn't work. It doesn't give extra 2%/4% melee haste.

**Comment by Crackaw** [comment]
Tooltip error. Works fine in stats
