### ISSUE TITLE
Frostworg

### ISSUE THREAD

**Issue by Cpburk** [SunwellTracker/issues#648]
Decription: 
Trying to farm Worg Haunch on Frostworg
I did record so here you go https://plays.tv/video/5a8ff427506a58baee/wolf-wont-drop-or-give-loot
Maybe not a prio 1 bugg but they have the highest drop chance on the item i want

How it works: 
They stand still and do nothing and drop nothing.

How it should work: 
They should attack you back and drop stuff.

Source (you should point out proofs of your report, please give us some source):

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
