### ISSUE TITLE
"You are not in Guild"

### ISSUE THREAD

**Issue by Magnetrans** [SunwellTracker/issues#650]
Decription: 
I was in a guild temporarily. Ever since i left i keep a message popping up "You are not in a guild:"

How it works: 
With the inconsitency of the message appearing i would assume that it is whenever someone in the guild writes something in guildchat and it is still trying to send the message to me.

How it should work: 
I am not trying to use any guild commands so the message shouldnt appear.

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/kZa4I

**Comment by TSSchoof** [comment]
Can confirm this also happened to me.

**Comment by Azathothh** [comment]
Looks like some addon issue, without addons it shouldn't happen.
