### ISSUE TITLE
[Quest - Howling Fjord] Parts of the job

### ISSUE THREAD

**Issue by sicknot1** [SunwellTracker/issues#653]
Decription: jenny wants you to obtain shoveltusk ligaments, you kill any of the 3 shoveltusk http://www.wowhead.com/quest=11309/parts-for-the-job#comments

How it works: shoveltusks won't drop the ligaments (killed more than 50 of them)

How it should work: Apply Blizzlike Drop rates

Source (you should point out proofs of your report, please give us some source): 
Need confirmation of other players or if a gm wants to try to reproduce it.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
