### ISSUE TITLE
Besieged! quest

### ISSUE THREAD

**Issue by Poltt** [SunwellTracker/issues#654]
Decription: 
Infernals in quest Besieged in SMV are not spawning

How it works: 
0 mobs in quest area

How it should work: 
Mobs should respawn immediately

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Can confirm .. only a GM can kill and respawn the way point summoners to fix the issue atm

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/985
