### ISSUE TITLE
WSG flag bug when joing on going battleground

### ISSUE THREAD

**Issue by Effimera** [SunwellTracker/issues#657]
Description: 
Whenever you join an on going WSG battleground top icons suggest the flags are being picked up (even though they are not). 

How it works: 
![wowscrnshot_022418_141300](https://user-images.githubusercontent.com/24449020/36630835-7c8a66a4-196d-11e8-9291-276550acd9eb.jpg)
![wowscrnshot_022418_141421](https://user-images.githubusercontent.com/24449020/36630836-7cab50e4-196d-11e8-88f2-22afbcd8b3f7.jpg)

How it should work: 
I bet you know! 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Resolved with next realm update
