### ISSUE TITLE
Mining ore us bigged

### ISSUE THREAD

**Issue by starblex** [SunwellTracker/issues#659]
Decription: 
A mining ore is bugged in Icecrown "rich saronite ore" at 74.64 , 62.09

How it works: 
after mining the ore disapears and you get no loot. then  i fly i away and after a couple of yeards the ore is back in the game

How it should work: 
You should be able to mine the ore, and then the ore should disapear

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next update.
