### ISSUE TITLE
[Discerning Eye of the Beast] heirloom 2% mana return not working.

### ISSUE THREAD

**Issue by Jestaro** [SunwellTracker/issues#662]
Decription: 
The Discerning Eye of the Beast Heirloom is not working properly by not giving the 2% returned mana on kill.

How it works: 
It does not return 2% of your maximum mana whenever you kill a target that yields experience or honor. Making the equip effect of this item pointless.

How it should work: 
Restores 2% of your maximum mana whenever you kill a target that yields experience or honor.

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
Works for me.

**Comment by Jestaro** [comment]
This does not work currently. https://streamable.com/410dz
