### ISSUE TITLE
Dragonblight Gryphon

### ISSUE THREAD

**Issue by Blueprnt** [SunwellTracker/issues#663]
Decription: 
The quest "Flight of the Wintergarde Defender" is bugged. When you accept the quest, if you don't turn it in, you can use the gryphon whistle to call and use the mount anywhere. In any zone, and you can dismount and remount it whenever, as well as call a new one. And it flies in caves etc.

How it works: 
Read above

How it should work: 
It's suppose to dismount you outside of the marked questing area.

Source (you should point out proofs of your report, please give us some source): 
It's obviously a broken bug, and I didn't look up the real proof other than I figured it out in game.

**Comment by Dootz** [comment]
Will be fixed with next update
