### ISSUE TITLE
Pet Range Max Distance

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#664]
Decription: I have noticed recently that my pet can't go as far as he could before. (also mentioned by dathremar in another report).

How it works: At the moment you can't send your pet too far.

How it should work: You should be able to send your pet a bit further, on all the other servers there was of course a capped distance BUT it was not as short as here ;(.

Source (you should point out proofs of your report, please give us some source): 
I am continuously searching for proof, if anything could be provided by anybody else that would be of great help.

**Comment by ujellyx** [comment]
Yeah, the range of being able to attack something with your pet is way too low. I tried to search for any videos or such where one can see this, but haven't had any success yet...

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
