### ISSUE TITLE
Blackrock Depths

### ISSUE THREAD

**Issue by Mysoopa** [SunwellTracker/issues#665]
Decription: 
The Lyceum door is closed and requires a key

How it works: 
After joining BRD trough RDF the door to The Lyceum is closed and requires a key

How it should work: 
Since its a RDF the door should automaticly open after killing the seven dwarfes

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I only found information that key requirement was removed in Cataclysm.
