### ISSUE TITLE
Angrathar Adversarial Blood quest

### ISSUE THREAD

**Issue by lippincott25** [SunwellTracker/issues#666]
Decription: 

Quest= Adversarial Blood

A mob named "Darkscreecher Akkarai" who is summoned and required to kill for this quest is suppose to cast a spell called "Flock Call".

How it works: Darkscreecher Akkarai only casts frostbolt and shadow bolt volley. I tested this with the GM Tide for a few minutes. 

How it should work: He's suppose to cast flock call about 10 seconds into the engagement. Flock call summons several Akkarai Hatchling to fight beside him.

Source (you should point out proofs of your report, please give us some source): 

http://www.wowhead.com/npc=23161/darkscreecher-akkarai#abilities

http://www.wowhead.com/npc=23206/akkarai-hatchling#comments

Notice the patch the comments were made above^ stating that they tamed the akkarai hatchlings prior to 3.3.5. Tide was telling me the spell Flock Call isn't in the database. But I believe it should be.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
