### ISSUE TITLE
Grizzly Hills Woodsman Drake quests

### ISSUE THREAD

**Issue by xrisus666** [SunwellTracker/issues#667]
Decription: There are missing quests from NPC Woodsman Drake at Amberpine Lodge in Grizzly Hills

How it works: in Amberpine (Grizzly) NPC Woodsman Drake (npc=27391) gives only one quest (Thane of Voldrune (quest=12255)

How it should work: after completing quest Local Support (quest=12292) NPC should give Thinning the ranks (quest=12223) followed by Secrets of the Flamebinders (quest=12222) and then by Thane of Voldrune

Source (you should point out proofs of your report, please give us some source): Wowhead DB

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
