### ISSUE TITLE
Dragonmaw Ork transformation Bug

### ISSUE THREAD

**Issue by Eserin** [SunwellTracker/issues#669]
Decription: There is a problem with Transformation into dragonmaw ork in Netherwing Ledge .

How it works: After i Completed last quest from NPC Mordenai (npc=22113) "Ally for Netherwing" (Shadowmoon Valley),  i got reputation on natural in Netherwing Ledge (Shadowmoon Valley) but  I can not transform into dragonmaw ork , so i can not continue quests there.

How it should work: The last quest in chain grants you sufficient reputation to become neutral with the Netherwing Faction (42,000), and giving transformation into dragonmaw raider to do quests in Netherwing Ledge (Shadowmoon Valley).

Source (you should point out proofs of your report, please give us some source): this is exactly what happend
![1](https://user-images.githubusercontent.com/36818382/36677859-91127a96-1b0f-11e8-9dc8-8fb40b29f30c.png)

**Comment by Dootz** [comment]
Hi, to get transformed you need to take this quest http://www.wowhead.com/quest=11013/in-service-of-the-illidari from http://www.wowhead.com/npc=22113/mordenai .  But first to get In service of the illidari you need to complete http://www.wowhead.com/quest=11012/blood-oath-of-the-netherwing . Now here's what's causing your issue: To get Blood Oath of the netherwing you need to have Flying level 300, as you can read in wowwiki comments.

I tested whole chain and it's working fine. So:
- check what's your current riding (aka flying )level, you need to have it at 300 to proceed with chain.

Hope that helps.

**Comment by Eserin** [comment]
So first i need this max ridding skill to start Blood Oath of the netherwing and then In Service of the Illidari ? I will see if he will have a quest for me then but ty very much for help :) have a nice day !
