### ISSUE TITLE
Server doesn't  show actual position of party members

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#67]
Decription: 
Server doesn't  show actual position of party members! even after re-invite. Asked different players - they have the same problems whith map and displaying players on map

How it works: 
Problem with displaying pary members on global map, i is not showing actual position of party members. For example : when i am in Redridge and my friend is in Stormwind he see my position like i am in Stormwind too, but  i was here 10 mins ago. Leaving and reinviting to the party making no progress. Both of us using no addons! 

How it should work: 
It should use actual position in real time and moving charater point on map

Source (you should point out proofs of your report, please give us some source): 
Asked different players - they have the same problem.

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
