### ISSUE TITLE
[NPC] Diseased Young / Timber Wolf drop

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#671]
Decription: 
Diseased Young / Timber Wolf drop chance of Ruined Pelt is extremely low.

How it works: 
Diseased Young / Timber Wolf in Elwynn Forest drop chance of Ruined Pelt is extremely low. I've killed like 30 of them and got none.

How it should work: 
Diseased Young / Timber Wolf drop chance of Ruined Pelt, Chipped Claw and Broken Fang should be around 40%.

Source (you should point out proofs of your report, please give us some source): 
Table removed from wowhead, was like that:
https://wotlk-twinhead.twinstar.cz/?npc=69

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
