### ISSUE TITLE
[NPC] Defias Thug quest item drop

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#672]
Decription: 
Defias Thug in Elwynn Forest drops Red Burlap Bandana without a proper quest.

How it works: 
Red Burlap Bandana drops without any quest related to it.

How it should work: 
Red Burlap Bandana should drop only with a quest related to it.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_022518_222212](https://user-images.githubusercontent.com/30598442/36645478-a4accad8-1a7a-11e8-96fd-9ee1e29f409d.jpg)

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
