### ISSUE TITLE
[Discerning Eye of the Beast] heirloom 2% mana return not working.

### ISSUE THREAD

**Issue by Jestaro** [SunwellTracker/issues#673]
Decription: 
The Discerning Eye of the Beast Heirloom is not working properly by not giving the 2% returned mana on kill.

How it works: 
It does not return 2% of your maximum mana whenever you kill a target that yields experience or honor. Making the equip effect of this item pointless.

How it should work: 
Restores 2% of your maximum mana whenever you kill a target that yields experience or honor.

Source (you should point out proofs of your report, please give us some source): 
https://streamable.com/410dz

**Comment by Akha72** [comment]
But you realise you have to be the one to land the killing blow?

**Comment by Akha72** [comment]
And in the video you posted hunter appears to be the one finishing this mob off.

**Comment by Jestaro** [comment]
I tested by myself as well getting the killing blow, normal regen happens I can do another video of the event if needed. I posted this issue once, and have talked to multiple people with the same issue,.
