### ISSUE TITLE
Corrupted Ashbringer and Naxxramas

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#68]
Decription: 
As i know, first raid on Angrathar will be Naxxramas and as i know Angrathar is progressive realm. SO Naxxramas TILL 3.0.2 version was ORIGINAL raid and there was a drop chance for Corrupted Ashbringer  and on version 3.0.2 there were Death Knights that could obtain Ashbringer, and here we can't obtain such a legendary item. I don't ask for leaving Old Naxxramas in Plaguelands, but maybe you should add this item to drop table to Four Horsemen chest for sometime? For moths or two? Whis will give players a challenge to obtain it and become more legendary player in future patches on Angrathar.

How it works: 
There is no Corrupted Ashbringer now on Angrathar  in droptable because Naxxramas is 80 lvl raid now.

How it should work: 
As for 3.0.2 version (like it should be now) players should have chance to obtain this item for 1 month (for example). It will give a challenge for server players.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Naxxramas_(original)

**Comment by nimeral** [comment]
First, it doesn't seem true, http://wowwiki.wikia.com/wiki/Patch_3.0.2_(undocumented_changes) - "Naxxramas has been removed from Eastern Plaguelands".

Second, it certainly doesn't belong to the bugtracker, you were right to post http://sunwell-community.com/index.php?/topic/290-epic-corrupted-ashbringer-must-live-d/ though.

Third, see there.
