### ISSUE TITLE
Quest:  [Bringing Down Heb'Jin] not working

### ISSUE THREAD

**Issue by asaphede** [SunwellTracker/issues#680]
Decription: 
When doing the quest  [Bringing Down Heb'Jin] in Zul'Drak, you are support to be able to get the rider down on his bat. When i press the quest item and get the bat down, the rider: "Heb'Jin" never spawns. I have done this 10 times to test it and have had a GM here also to look at the problem. 

How it works: 
I press the quest item, and only the bat gets down. Most of the time the bat will reset, before I can attack it. Heb'Jin (the rider) never spawns. 
<img width="1163" alt="skaermbillede 2018-02-26 kl 09 53 27" src="https://user-images.githubusercontent.com/36840735/36661178-e98e9d60-1ada-11e8-86d4-b0c89a2f563f.png">

How it should work: 
Press quest item, get bat + rider down from the roof. Net the bag with the quest item you have in your bags:  [Bat Net], and kill Heb'Jin.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/351
