### ISSUE TITLE
Time Lost Proto-Drake mount % confirmation

### ISSUE THREAD

**Issue by Adwean** [SunwellTracker/issues#681]
Decription:  It works simple,  Time Lost Proto-Drake is rare spawn supposed to drop blue rarity necklace , mount and bag full of gold/cloth/crystallized elements. 

How it works:  You find the rare and kill it :) 

How it should work: Works as intended , the drop on the items on other hand is what bothered me. After I found it , which was so rare on 5k populated project I couldn't belive when he only dropped the bag and not blue item or mount. So if possible I would like confirmation on the % drop of the items that were supposed to drop from the kill. 
![rip time lost](https://user-images.githubusercontent.com/22595427/36663708-1e580094-1aeb-11e8-9969-65eb68936595.jpg)  Here is the screenshot of my kill and the bag that receive from it.

Source (you should point out proofs of your report, please give us some source):  wowhead is not accurate site anymore since the difference of the patches so https://wow.gamepedia.com/Time-Lost_Proto_Drake. It is strange because I have it on the other realm - Feronis , farmed it for more than 5 different people and there was always Bag+Blue item+Mount on every single kill.

**Comment by Gescht** [comment]
In their database it states this:
https://db.darkwizard.pl/?npc=32491#drops

You may just got incredibly unlucky and lost the 99% dropchance.

**Comment by Adwean** [comment]
Was I extremely lucky on 2 out of 3 items even if the % is 99% chance to drop ? There was no blue item either. Also I am pretty sure this statistic cannot be tracked nowdays and be 100% accurate since most of the data bases are copied from wowhead and there have been tons of changes on the old content. I am still waiting for GM to handle the situation because this is so frustrating. The chance to see that rare on 5k pop server is so small , also you got to include that it shares CD spawn with another rare - Vyragosa which makes double less the chance to find it too.

**Comment by Gescht** [comment]
From my experience as a developer on another server, these online databases like the one I linked earlier are  directly linked to the actual database from the server which has all the numbers and values for every loottable.
These online databases are not just copies from wowhead, they are linked to the server you are playing on. 

Just compare these 2:
https://db.rising-gods.de/?npc=32491#drops
https://db.darkwizard.pl/?npc=32491#drops

The other server clearly made a change in their loottable (or sunwell did) by adding (removing) the BoE items from the list.

**Comment by Adwean** [comment]
I am not saying you are wrong , just want GM or Dev to confirm and explain the situation. How I never miss any blue item or mount on the other realm for 6 different kills , but having none of the 2 items drop on this realm.

**Comment by Nadiirr** [comment]
I believe it is less than a 99% chance. 
I think there's something wrong here.

**Comment by Adwean** [comment]
Okay so after browsing the forum I saw a post from a Blood elf warlock who killed TLPD on 20th of February and exactly the same thing happened to him -> Only bag , no mount or blue item in the corpse. This is extremely rare to happen if the drop rate is 99% like it is supposed to be , to a single player , what about 2 players ? Even lesser chance to happen.

**Comment by Dootz** [comment]
We'll look into this. It's definitely not fun to experience such thing.

**Comment by Adwean** [comment]
Had a friend killing him few minutes ago and obtaining all 3 items (bag,mount,blue rarity necklace) 
Screenshot : https://imgur.com/a/fv7Y9

My question is simple, when you find out what is causing the glitch in the loot table of the rare mob will me and the warlock who posted on forums about the same issue that happened for him on 20th of February (litteraly 6 days before me)  will receive the loot that we earned? 
I can think of another similar issue with the first boss in Karazhan (Attumen the Huntsman) who sometimes has his loot glitching and the players are unable to loot the corpse.  I would like to know the answer of my question , because answer such as "you are unlucky" is really not satisfiyng at all , and I expect more from your professional team rather than such excuse. You proved you can solve problems before please solve this one too. Will wait for the answer.

**Comment by Adwean** [comment]
Any update?

**Comment by Riztazz** [comment]
It is set at 99% but there could be a chance that some system lowered it a little bit, i made sure that it works correctly from now on, closing.
