### ISSUE TITLE
Vesperon's Twilight Torment (spell id=57988) appears to have no cooldown

### ISSUE THREAD

**Issue by Anselm123** [SunwellTracker/issues#682]
Decription: 
On our sarth 2D 10 man attempts last night when we'd get to the point where Vesperon's disciple appears it would near instantly kill 1-2 people (rogues and fury warriors who hit fast). After doing some research and watching many hours of kill videos to see if we were doing anything wrong it seems like this really wasn't an issue. On old retail kills with 2-3 drakes they would send dpsers and a healer into the portal to deal with the disciple to get rid of the debuff but people were instantly dying when they tried to dps. 

How it works: 
Will just reflect any damage you do with the debuff up on the raid.

How it should work: 
It should have a 1 second GCD, making it a hard portion of the fight but not near impossible as the death log below shows. This will allow us to go into the portal and kill the disciple and get rid of the debuff without killing ourselves trying to do it.

Source (you should point out proofs of your report, please give us some source): After doing some digging on wowhead the spell http://www.wowhead.com/spell=57988/twilight-torment#comments is shown to be having a 1 second internal cooldown per player with the damage reflect. This was the deathlog for our rogue in the final attempt last night https://i.imgur.com/oiadoXk.png Which shows him getting hit way more than once a second

**Comment by Anselm123** [comment]
We're going to look to try this again tonight. Is this wise since it's broken?

**Comment by Riztazz** [comment]
I will try to fix it without restarting, will let you know in a bit

**Comment by Anselm123** [comment]
awesome, so there was something wrong with the ICD?

**Comment by Riztazz** [comment]
yeah

**Comment by Anselm123** [comment]
Awesome thanks for your hard work!

**Comment by Riztazz** [comment]
Sadly i cannot fix this without restarting realm, fix will be live tomorrow morning after server update

**Comment by Anselm123** [comment]
No worries mate, i completely understand. Thanks again for your hard work, we'll just go kill it with 1 drake this week and smash it next week :)

**Comment by Riztazz** [comment]
Fixed with next update
