### ISSUE TITLE
Fix Discord invite link

### ISSUE THREAD

**Issue by Krrl** [SunwellTracker/issues#686]
Decription: 
Discord invite link is invalid or has expired.

How it works: 
Cannot get into discord server

How it should work: 
Should be able to get in discord server

Source (you should point out proofs of your report, please give us some source): 
![dcord](https://user-images.githubusercontent.com/14839617/36683889-a8917726-1ad3-11e8-8b25-f3199e69f18b.png)

**Comment by Dootz** [comment]
https://discord.gg/wmgNP6N

**Comment by Krrl** [comment]
works now.
