### ISSUE TITLE
[Paladin] Avenger's Shield

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#687]
Decription: 
Avenger's Shield bounce to critters after landing on main target.

How it works: 
Avenger's Shield choses the closest creature instead of the closest hostile target.

How it should work: 
Avenger's Shield should ignore critters.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Avenger%27s_Shield
@Riztazz

**Comment by Anselm123** [comment]
I can second this. Very frustrating.

**Comment by Riztazz** [comment]
Yeah yeah, i'll fix all aoe spells hitting critters in one go

**Comment by Riztazz** [comment]
Fixed on Feronis, angrathar will be updated in following days, closing
