### ISSUE TITLE
[Quest] Foolish Endeavors

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#688]
Decription: 
I was in middle of event, fighting with boss, and adds from cocoons, when sb clicked Deathstaler or sth. Im not sure, but adds disappeared, and boss got reseted. Unfortunately i wanted to pull it again when event end, he got aggro on me and killed me. and again when i respawned. and again. He was immune to all effect because of his bauble, and Saurfang, who stood near him was frozen solid to ground. When the second man got his event timer end, boss pulled to him with immune. Whole quests repaired itself when Saurfang dissappeared and cocooned mobs respawned, nearly 5 minutes later? Sth like that.

How it works: 
If somebody will start event, starting his own quest, it bugs whole event/quest.

How it should work: 
Other ppl cant disturb event, so they should be unable to talk to Deathstalker during event.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11705/foolish-endeavors
https://www.youtube.com/watch?v=_P5Lt4poVa4
@Dootz

**Comment by Dootz** [comment]
will be fixed with next update
