### ISSUE TITLE
[Death Knight] Acherus Deathcharger NPC's freely roaming and not phased in starting zone

### ISSUE THREAD

**Issue by phazedqt** [SunwellTracker/issues#69]
Decription: There are neutral, unphased Acherus Deathcharger NPC's wandering around the DK starting zone, and randomly aggroing without being attacked. 
(The mob attacks you if you attack a Scarlet Crusader/Citizen of Havenshire NPC near it)

How it works: Acherus Deathcharger NPC walking around aggroing players when you attack Scarlet NPC's and isn't phased.

How it should work: Acherus Deathcharger should be phased into the quest Into the Realm of Shadows, neutral, and not attacking players on sight. These NPC's are supposed to be phased into this quest, only when you're in the realm of shadows and have the realm of shadows buff. (youtube link of the quest: https://www.youtube.com/watch?v=ha_A2b79lTU )

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_013018_104835](https://user-images.githubusercontent.com/35966295/35575757-34743ece-05ab-11e8-933a-9d9a3675fd13.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/210
