### ISSUE TITLE
Vengeful Souls quest in outland

### ISSUE THREAD

**Issue by Stormcho** [SunwellTracker/issues#690]
Decription: The quest "Vengeful Spirits" in Terrokar Forest, Outland doesn't show properly the location of where you should do it and where to complete it

How it works: It doesn't show anything when you get it from the NPC and when you complete it it shows that you have to turn it in where it has to be the creatures for slaining.

How it should work: It has to work as a normal quest 

Source (you should point out proofs of your report, please give us some source): 
https://imgur.com/a/aq6dO
Screenshot of the map

**Comment by Dootz** [comment]
Will be fixed with next server update. It won't work if you have external addon for map & quests like Carbonite, but it will work with basic wow map. You'll need to delete cache folder.
