### ISSUE TITLE
[Angrathar] [Quest] [Howling Fjord] [It goes to 11.. ] 

### ISSUE THREAD

**Issue by Bearrman** [SunwellTracker/issues#691]
Decription: http://db.darkwizard.pl/?quest=11421
you have to shoot harpoons on 3 houses to put them on fire,
How it works: 
When you use the harpoon to burn the Longhouse ( The big one on the right) nothing happens. 
the other buildings do catch on fire.

How it should work: 
The objective  of the quest is to burn the buildings. When you shoot the longhouse you're supposed to get objective complete.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Have you tried to aim for roof? Around spot i marked on attached screenshot
![village](https://user-images.githubusercontent.com/25490436/36692749-3ae3a2f6-1b39-11e8-9e01-61c9f42e1027.png)

**Comment by Bearrman** [comment]
Yea i shot off about 30 rounds on the roof, and i watched a tutorial on youtube+ read about it on wowhead ^^ It didnt work. (btw its the house on the right of the one on the picture that is the problem)

**Comment by Dootz** [comment]
ok, after further tests; It is possible to hit roof and not get credit for it.  Sorry for screenshot of wrong house.

**Comment by Kokaina** [comment]
Fixed, will be updated soon.
