### ISSUE TITLE
[Priest] Improved Shadowform's Fade. (Added Proof)

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#693]
Decription:
While talented in Improved Shadowform, Fade should remove all movement impairing effects when used in Shadowform. Currently, it doesn't remove all, and some effects remain either visually (but no effect) or with both the effect and the debuff on the priest.

Talent description:
Your Fade ability now has a 50/100% chance to remove all movement impairing effects when used in Shadowform (...)

How it works:
Fade while in Shadowform removes some snares, while others are not removed.
Sometimes, snare effect is removed (player moves normally) but debuff remains.
Sometimes, snare is removed and debuff is removed aswell.
Other times, neither snare nor debuff are removed. 
This happens with NPC and player snares alike, but it's hard to pinpoint which do and which don't. For example, some frost mage snares are removed while others aren't.

Haven't been able to make a complete list, as some snares are from NPC and other for players and the application of the bug is irregular as stated above.

How it should work:
Fade while in Shadowform should remove **all snares with their respective debuffs**. Even if the snare has another components to it (DoT for example).

Source (you should point out proofs of your report, please give us some source):
http://www.wowhead.com/spell=586/fade#comments

By POINGjam (14,198 – 3·16·92) on 2008/09/30 (Patch 3.0.1) |   |  
Improved Shadowform has made Fade wonderful for PvP. Fade will lift all movement impairing effects when you use it, acting the same as the gnome racial Escape Artist, but usable every 30 seconds (or 24 with improved Fade).

http://wowwiki.wikia.com/wiki/Escape_Artist
"The best application for this is removing Boss debuffs that include a snare. If a debuff has "Slows movement speed AND does 65 damage ever 1 second", it will remove both the slow speed AND the damage over time spell from you, in one sweep. This will work as long as the spell roots you in place, or slows your movement speed."

The "remove" mechanic should bypass all sort of dispel resistances.

**Comment by ujellyx** [comment]
Any examples on where it doesn't remove something?

**Comment by Semper-Numquam** [comment]
I just dueled a mage: 
Frostbolt: removed effect (priest moves at normal speed) but debuff remains.
Cone of Cold: removed snare but debuff remained. 
Frostbite: When a chill procced Frostbite, Fade removed Frostbite but not the snare debuff (priest moved unhindered, though)
Frostfire Bolt: Removed snare but debuff remained. 
Mirror Image Frostbolt snare was removed, but debuff remained.

After Fade-ing these spells:
-The debuff remains in there and could be targeted by dispel (working as a trash debuff even when it should've been removed already)
-The priest took the 12% extra damage from Torment the Weak talent also, which requires a snare on the target.
-My healing spells were reduced (from 3.4k Flash Heals to 2.8k Flash Heals) because of Permafrost, which reduces healing by 20% on chilled targets.
-Frostfire Bolt debuff did DoT dmg.

I'm also pretty sure it has happened to me with other classes that even after Fade the snare remains. And not only the debuff stays visually, but movement speed also is reduced. I'm not talking about perma-ground effects like desecration, or recasts. Literally I use Fade and remain snared.

It's hard for me to pinpoint exactly all snares and which are effectively removed, and which are partially removed since I PvP as disc mainly and I'd have to test every single root and snare of every class and spec. However, with the above test you can see that the bug exists. This is really important because remaining debuffs work as trash debuffs vs dispel and because like TTW and FFB showed, you are still considered affected by the spell towards other spell mechanics + secondary effects of snares remain like DoTs.

**Comment by Semper-Numquam** [comment]
This is still a bug in Frosthold.
