### ISSUE TITLE
LAVA PIT (IRONFORGE)

### ISSUE THREAD

**Issue by fsink** [SunwellTracker/issues#694]
Decription: 
I fell into the lava in ironforge and died. Released and did not go to the graveyard. I ended up back at the location where my dead body was. Did this 2 more times and it kept repeating.

How it works: 
Released and did not go to the graveyard. I ended up back at the location where my dead body was.

How it should work: 
It should be taking my spirit to the graveyard outside Ironforge. 

Source (you should point out proofs of your report, please give us some source):  GM Tide had to Tele me out of the pit of lava.

**Comment by Dootz** [comment]
will be fixed with next server update
