### ISSUE TITLE
[Alchemy] Northrend Alchemy Research not saving discovered recipies

### ISSUE THREAD

**Issue by Shiibbaa** [SunwellTracker/issues#695]
Decription: 
After using the Northrend Alchemy Research, it will create the useable product (Potion, Elixir, ect) but will not save the recipe in the crafting tab for further use.

How it works: 
You channel Northrend Alchemy Research, and it will create a new product without giving you the recipe.

How it should work: 
You channel Northrend Alchemy Research and it discoveres a new Alchemy recipe for further use.

Source (you should point out proofs of your report, please give us some source): 
Below are pictures showing that I recieved the potions through Alchemy Research, thatmy Alchemy Research was indeed used and is on cooldown, and that neither of the recipes are now in my crafting.

![gm response](https://user-images.githubusercontent.com/36866803/36700844-168b0ada-1b1f-11e8-9a0a-6e20bb307f86.png)
![potion 1](https://user-images.githubusercontent.com/36866803/36700851-1a09eb68-1b1f-11e8-859d-691ecc40c5bf.png)
![potion 2](https://user-images.githubusercontent.com/36866803/36700853-1af5152a-1b1f-11e8-943f-9604a96c2cc8.png)
![research](https://user-images.githubusercontent.com/36866803/36700854-1c052e3c-1b1f-11e8-827c-37cf9fad1f69.png)
![search 1](https://user-images.githubusercontent.com/36866803/36700857-1e1501b6-1b1f-11e8-9b72-4a74a41a2667.png)
![search 2](https://user-images.githubusercontent.com/36866803/36700859-1f0181da-1b1f-11e8-8641-bfddcd394778.png)

**Comment by Hahecz** [comment]
There is no guarantee that you will learn recipe of the potion/elixir you create. Read this comment http://www.wowhead.com/spell=60893/northrend-alchemy-research#comments:id=838479
First example:
Researched: [Powerful Rejuvenation Potion]
Created: [Elixir of Mighty Thoughts] x2

In short: no bugs here.

**Comment by Shiibbaa** [comment]
Wait seriously wtf Blizzard thats such a stupid idea

Thanks for clearing that up. Time to figure out wtf it gave me then
