### ISSUE TITLE
Spell Crashing Wave ignores "freeze" modificator

### ISSUE THREAD

**Issue by Hahecz** [SunwellTracker/issues#696]
Decription: 
This spell is used when possesing NPC Water Terror (https://db.darkwizard.pl/?npc=30645) for quest (https://db.darkwizard.pl/?quest=13091)
First effect of the spell (dealing damage) works.
Second effect (Double damage to Frozen targets) does NOT work.  Targets are frozen by Water Terror's other ability (https://db.darkwizard.pl/?spell=57668).

How it works: 
1. Freeze enemies with Frost Nova
2.. Use Crashing Wave
3. Deal regular spell damage

How it should work: 
1. Freeze enemies with Frost Nova
2.. Use Crashing Wave
3. Deal double damage to enemies frozen by Frost Nova

Source (you should point out proofs of your report, please give us some source): 
Damage without freezing enemy:
https://imgur.com/a/RdCxY
Damage with freezing enemy:
https://imgur.com/a/4eM1N

**Comment by Azathothh** [comment]
Fixed, will be updated soon.
