### ISSUE TITLE
Critical Bug? npc and player invisibles in stormwind. RESOLVED!

### ISSUE THREAD

**Issue by gutzbr** [SunwellTracker/issues#697]
Hello sunwell I would like to report a bug, my character Hazard an ally 79 warrior with a bug that I can not see a npc or player (only appeared to see npc guards and one player most likely
 bugged too Nick name: Lee warrior 77 human) in stormwind. 
My other characters can see all the players and npcs in stormwind (I tested at the same time to see if it was some lag on the server) only the char Hazard can not, I tested elsewhere and got to see npcs and player across northrend and iron forge.

I could not see other maps from stormwind because the Gryphon npc did not show up either.

I do not know what that could be but I think it was because I deleted all the questlog quests, the quests that I deleted most were from the storm peaks K3 and dragonblight Wyrmrest Temple, and I finished all borean tundra quests...

Here are some bug prints:
stormwind bug: https://imgur.com/a/eIWpB
other cities is not bogged: https://imgur.com/a/Vprh3

sorry for bad english....

**Comment by MrTide** [comment]
Hello you are probably on battle for undercity event ... since you got the achievement for wrath gate .. go to the wrath gate and talk with lady alex ( big red dragon ) and get her quest to start the quest line

**Comment by gutzbr** [comment]
"problem" resolved thanks for the help!
