### ISSUE TITLE
Into hostile territory quest (dragonblight  wintergrade keep)

### ISSUE THREAD

**Issue by ivan4it** [SunwellTracker/issues#698]
Decription: 
quest not working

How it works: 

i mount the gryphon and i cant move
How it should work: 
https://www.youtube.com/watch?v=lI-h62eZlhM
![wowscrnshot_022718_081001](https://user-images.githubusercontent.com/36876157/36713523-c8dc0db6-1b96-11e8-8906-0aaf8d0e63fb.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by ivan4it** [comment]
i added link to video how need to work cuz my english is bad

**Comment by Dootz** [comment]
Will be fixed with next server update
