### ISSUE TITLE
[Quest] Dealing With Gjalerbron

### ISSUE THREAD

**Issue by xStiven** [SunwellTracker/issues#699]
Problem - quest giver isn't giving this quest.

This quest is part of the chain of quests:
1. The Conqueror of Skorn!
2. >Dealing With Gjalerbron
3. Necro Overlord Mezhen

NPC name - "Chieftain Ashtotem".

After dealing with Val'kyr village of Skorn (quest "The Conqueror of Skorn!"), the Chieftain Ashtotem, should give next quest "Dealing With Gjalerbron". But atm he just don't gives next quest "Dealing With Gjalerbron".

**Comment by xStiven** [comment]
Uhh-ohh... sssooo after doing a little digging i found a quest named "Stop the Ascension!" which started from random dropping quest item from the mobs in Skorn village. So after doing "Stop the Ascension!" , the quest "Dealing With Gjalerbron" has became available. So dunno false alarm or indeed a bug, since wowhead and comment on it, telling nothing about "Stop the Ascension!" being prerequisite to "Dealing With Gjalerbron".
![wowscrnshot_022718_103909](https://user-images.githubusercontent.com/10297700/36718434-7212d686-1baa-11e8-900e-b325195d9e10.jpg)

**Comment by Dootz** [comment]
Will be fixed with next update.
