### ISSUE TITLE
Winterfin Oracle - Mobs in Borean Tundra doesn't use abilities.

### ISSUE THREAD

**Issue by Vlnkaj** [SunwellTracker/issues#70]
Decription: 
Winterfin Oracle (murlock) in Borean Tundra just stay there and don't cast or run to you to autoattack.

How it works: 
Winterfin Oracle (murlock) in Borean Tundra just stay there and don't cast or run to you to autoattack.

How it should work: 
They should have spells to cast. Lighting bolt (ID:9532). Right now they only cast Unstable Magic (ID:50272) on themselves.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=0aRpJZ6X0AY (time 0:48 you can see two oracles casting)
http://www.wowhead.com/npc=25216/winterfin-oracle#abilities

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
