### ISSUE TITLE
[Item drop] Large Rope Net

### ISSUE THREAD

**Issue by PrivatePile** [SunwellTracker/issues#701]
Decription: 
Murlocks all along coast in Westfall suppost to drop item "Large Rope Net" with ~5-10% drop rate
killed around 200 and nothing

How it works: 

..
How it should work: 
https://classicdb.ch/?item=835 link to the item

Source (you should point out proofs of your report, please give us some source):

**Comment by Akha72** [comment]
Bullshit. This item was removed from drop before TBC.

**Comment by Akha72** [comment]
http://www.wowhead.com/item=835/large-rope-net#comments
