### ISSUE TITLE
[Stealth][Core] Looting does not break stealth

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#702]
Decription: 
Looting does not break stealth.

How it works: 
When in stealth, you can loot corpses without losing the Stealth buff.

How it should work: 
When looting corpses, you should lose the stealth buff.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Stealth#Notes

**Comment by TheBigBallsOfFury** [comment]
Hello, a fix went out for this:
"Stealth mode will be removed after looting corpse."

However this is not the complete fix, and does not completely solve the problem:

The rogue still does not lose stealth when searching (right-clicking) the corpse. He only breaks stealth upon **CLOSING the loot window**. Doesn't matter if loot is picked up, **_only_** closing the loot window by moving or clicking the [X] makes you lose stealth.

Negative gameplay effects:

1. Stealthed units can check the loot on a corpse without losing stealth. 
2. Stealth is not lost **even if** item is already successfully looted. It's only lost when you have looted ALL the items in the corpse.
3. After clicking the last item on loot window, and immediately pressing Stealth after that, you dip into stealth for a moment and then the closing of the loot window brings you out of stealth. Destroys smoothness of gameplay since you have to make sure loot window is closed on your client side before restealthing.

**Comment by TheBigBallsOfFury** [comment]
This is working as intended on Warmane, you can check how it is supposed to work there.

**Comment by TheBigBallsOfFury** [comment]
Could this fix please be reverted if the issue is not being worked on? The current fix does not work and it made the issue much worse.

**Comment by Kokaina** [comment]
Done, will be fixed with next update.
