### ISSUE TITLE
[Only Partly Forgotten] - Quest/NPC/Respawn and population

### ISSUE THREAD

**Issue by bongobg** [SunwellTracker/issues#703]
Decription: Quest Only Partly Forgotten (https://db.darkwizard.pl/?quest=12831) requires 1x Icetip Venom Sac (https://db.darkwizard.pl/?item=40944) which drops from Icetip Crawler (https://db.darkwizard.pl/?npc=29461). These NPCs spawns are exactly 3 with exactly 5 minutes respawn time and they should be at least 5 with with ~30 seconds respawn time. The drop rate is 39% percent and camping the respawn may take up to hour.

How it works: 
3 spawns of Icetip Crawler with precisely 5 minutes respawn time.

How it should work: 
At least 5 spawns with ~30 seconds respawn time.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=29461/icetip-crawler#map - 5 spawns on this map and a little down in the comments there is this:
   By Crevan (7,833 – 1·13·58) on 2009/09/17 (Patch 3.2.0)		
   These buggers have a very fast respawn rate, probably less than 30 seconds.
https://db.darkwizard.pl/?npc=29461 - According to your DB there should be a loooot more spawns.

**Comment by Dootz** [comment]
I'm not sold on idea to reduce their respawn time. Other spiders in this cave also have full respawn time. But new spawns will be added.

**Comment by Dootz** [comment]
Will be fixed with next update.
