### ISSUE TITLE
Lootbug with tier tokens in naxxramas 25

### ISSUE THREAD

**Issue by blodigejens** [SunwellTracker/issues#704]
Decription: During todays raid in ID 24470 (Naxxramas 25 man), the guild Simple downed 4 horsemen. However, the chest only contained 1 tier token ([Breastplate of the Lost Conqueror]) despite blizzlike clearly states 2 x tokens to be dropped. We were encouraged to make a ticket here, in order for you to reimburse the items not obtained. This happened during our Loatheb kill as well, where we were reimbursed shortly after our raid ended. Please make the token, if possible, tradeable for us to reward the player intended. Best regards, player Ivanovich of  Simple.

How it works: Only one tier7 token drops from bosses.

How it should work: Two tokens should drop per boss.

Source (you should point out proofs of your report, please give us some source): This is a forumpost from when wrath was current content discussing the drops;
https://www.mmo-champion.com/threads/625542-Simple-Question-How-many-items-per-Heoric-Naxx-Boss

**Comment by Dootz** [comment]
i belive that was fixed some time ago
