### ISSUE TITLE
Double Layered Herb and Mining Nodes

### ISSUE THREAD

**Issue by Jdavidlol** [SunwellTracker/issues#708]
Decription: 
Mining and Herb nodes will often have multiples of themselves spawned in one location. Though this isn't game breaking and a lot of people enjoy it, it is not how it should work, unfortunately.

How it works: You will mine some ore or grab some herbs and it will exhaust that node, but underneath it in the exact same spot is another node.

How it should work: One node per location.

Steps to Reproduce: Check nodes in the barrens and you will find this happens relatively often. I do not know if it occurs in further content.

**Comment by TSSchoof** [comment]
I can confirm. This happened a lot for me while leveling herbalism.
