### ISSUE TITLE
Mok'thardin's Enchantment Holy Spring Water Issue

### ISSUE THREAD

**Issue by Qua01** [SunwellTracker/issues#71]
Decription: 
Can't collect spring water out of the snakes head/well in the last quest of Mok'thardin's Enchantment

How it works: 
There's no way to interact with the snake to give you spring water

How it should work: 
There should be a gear letting you interact with the well

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
