### ISSUE TITLE
[Hunter]

### ISSUE THREAD

**Issue by Piechman** [SunwellTracker/issues#711]
Decription: 
[Hunter] ShadowMeld [Hunter] Scorping Sting+chimera shot [Hunter] Concussive Barrage

How it works: 
ShadowMeld po użyciu moby nie gubią targetu, stoja po czym atakuja nas natychmiasowo
SC+Chimera po uzyciu na danym celu nie disarmuje go
Concussive Barrage-talent która pozwala na 100% szanse "daze" targetu.. Niestety nie działa
How it should work: 
ShadowMeld-Moby powinny gubić target i odbiegać na swoje pozycje
SC+chimera- chyba logiczne ^^ powienien disarmować target

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
