### ISSUE TITLE
Warrior Intervene to Shaman Totems Bug

### ISSUE THREAD

**Issue by Tulkastor** [SunwellTracker/issues#712]
Decription: The warrior intervene works on normal friendly targets however not on friendly shaman's totems

How it works: When the warrior casts spell "intervene" to a shaman totem, the combat text says "immune" and hence the warrior does change position.

How it should work: It should work as it works with every friendly member in the party/raid. The game interprits the warrior spell cast as an exterior effect and due to the totem being immune to the intervene's buff, it cancels the warrior's ability all together. 

Source (you should point out proofs of your report, please give us some source): I unfortunately do not have a screenshot.

**Comment by set-theorist** [comment]
Proof: http://www.arenajunkies.com/topic/152169-macro-for-intervene-nearest-target/
"Thanks for the macro, but is there any way to make it so it only will intervene players? sometimes it intervenes totems and tries to intervene NPCs ><. "

**Comment by Tulkastor** [comment]
Edit; On "how it works" it should write "warrior does NOT change position" sorry for the missing word. I will provide a screenshot soon.
