### ISSUE TITLE
 [Brutal Gladiator's Libram of Justice]

### ISSUE THREAD

**Issue by vvezimir** [SunwellTracker/issues#713]
Decription:  [Brutal Gladiator's Libram of Justice] - Źle działa .

How it works: Libram pod Hpala pvp 70 lvl . Działa aktualnie w ten sposob,iż Target którego healam  ,  nie dodaje mu 39 Resilenca na 6 sekund , a jeszcze 2 tyg temu dodawał . Jedynym Targetem któremu dodaje Resi to jestem Ja . A jest wyraznie napisane : causes your flash of light to increase the target's resilience rating by 39 for 6 sec.

How it should work: Powinno dodawac każdemu graczowi 39 relisenca na 6 sekund po otrzymaniu Flash of Light ,a nie dodaje nikomu oprócz mojej postaci .

Source (you should point out proofs of your report, please give us some source):

**Comment by vvezimir** [comment]
Pozdrawiam

**Comment by Azathothh** [comment]
Working properly.
