### ISSUE TITLE
QUEST BUGGED: Waste Not,WANT NOT

### ISSUE THREAD

**Issue by angryminer123** [SunwellTracker/issues#717]
Decription: Following quest in hellfire is bugged.
you cant loot the Salvaged metal or salved wood.

How it works: 
The items are on the ground and glimmering but not lootable, i talked to GM tide and he said it seems to be some kind of visual bug. and told me to come here and do a post about it.

How it should work: 
Obviously you should be able to loot them in order to complete the quest and get 8 each of them

Source (you should point out proofs of your report, please give us some source): im posting a screenshot,
In the screenshot they arent glimmering, since gm tide completed the quest for me but told me to come here and explain the issue.
![wowscrnshot_022818_175425](https://user-images.githubusercontent.com/36540514/36800753-90d2e3b6-1cb0-11e8-8f31-96f3fb72c598.jpg)

**Comment by Dootz** [comment]
Apparently that's 100% blizzlike and intended. There are multiple reports on wowhead of this happening during tbc and wotlk. 
![k](https://user-images.githubusercontent.com/25490436/36812767-8c9727ea-1cd2-11e8-82dd-198803e4cbd4.png)
