### ISSUE TITLE
[Wolfshead Helm] - t7 cat bis item does not work

### ISSUE THREAD

**Issue by ntt1** [SunwellTracker/issues#719]
Decription: 
When equipped, Wolfshead Helm does not grant 20 energy upon shapeshifting while in cat form. Link to the item -https://db.darkwizard.pl/?item=8345

How it works: 
It doesn't grant any energy upon shapeshifting.

How it should work: 
Every time you shapeshift while wearing the helm you should be restored 20 additional energy. For example if I have 40 energy left in cat form then i quickly shapeshift into normal and then cat form again, i should have 60+ energy (20 additional energy from shapeshift, which is added to the energy restored over time, while being out of cat form).

Source: 
http://www.wowhead.com/item=8345/wolfshead-helm#comments
"still technically best in slot for feral dps at 80. powershifting adds a lot of complexity to fights though so results may vary."

Very important bug, it currently handicaps cats, as I see it as the only way of cat doing competitive dps currently.

**Comment by Dootz** [comment]
Will be fixed with next update.
