### ISSUE TITLE
[NPC] Stonetusk Boar

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#721]
Decription: 
Stonetusk Boar in Elwynn Forest doesn't use boar charge ability.

How it works: 
Stonetusk Boar in Elwynn Forest doesn't use boar charge ability.

How it should work: 
Stonetusk Boar in Elwynn Forest should use boar charge ability.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_022818_220648](https://user-images.githubusercontent.com/30598442/36807331-b9985100-1cd3-11e8-99fd-c39549bb4deb.jpg)
![wowscrnshot_022818_220652](https://user-images.githubusercontent.com/30598442/36807332-b9bbb2f8-1cd3-11e8-9308-40d6241bdb6f.jpg)

https://wotlk.evowow.com/?npc=113 it's like old wowhead mirror, linking this cause current version is cataclysm+ (http://wowhead.com/npc=113#abilities)

**Comment by Dootz** [comment]
Right now they have around 15% chance to use this ability on aggro. I'll tweak it.

**Comment by Dootz** [comment]
Will be fixed with next update.
