### ISSUE TITLE
[Quest] The Storm King's Vengeance 

### ISSUE THREAD

**Issue by Tragii** [SunwellTracker/issues#722]
Quest w Zul'Drak
Po wejdziu na olbrzyma nie mozna odnalezc elit do zabicia 
- Thyrm (pomimo ze inni gracze go widza)
- Prince Navarius (nie sprawdzalem z innym graczem czy go widzial jak bylem na olbrzymie)

**Comment by Ramirezzms** [comment]
Wczoraj zrobiłem normalnie tego questa. Bardzo możliwe że nie trafiłeś w respaw

**Comment by Tragii** [comment]
Wczoraj to inny gracz wisiał nad tyrmem A ja w tym samym miejscu byłem na olbrzymie, widział tyrma a mnie nie, ja ani jego ani tyrma nie widziałem. Resp nie powinien tu mieć nic wspólnego bo do tego questa tworzy się coś w rodzaju insty dla każdego gracza co go robi.

**Comment by Dootz** [comment]
will be fixed with next server update
