### ISSUE TITLE
[Quest] Leave no one behind

### ISSUE THREAD

**Issue by Tragii** [SunwellTracker/issues#723]
Decription: 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
please add some information about bug.

**Comment by Tragii** [comment]
I accidently pres "Enter" and it post... i was editing it when you close it....

**Comment by Dootz** [comment]
but check if it's not already reported https://github.com/SunwellTracker/issues/issues/103
