### ISSUE TITLE
jewelcrafting gems are currently too strong

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#725]
Decription: 
The current bonus JC has doesn't reflect like every other profession at this stage of the game, simply because of the prismatic change that was done during middle of wrath.

How it works: 
They all currently give +18x3 as raw bonus versus 3 regular gems (attribute str, agi etc)
that's currently 54 bonus, while BS for example would provide +32.

How it should work: 
The JC was buffed in 3.2 (or nerfed depending on how you put it) due to epic gems being added and that they lost their prismatic bonus.
If we go back the editing history of wiki we can see it was +27 prior to this change, giving a 33str bonus being more in-line with other professions. As the current dragon-eyes are balanced around epic gems.

You did this for proffession CD's being a thing again so I think this is a reasonable fix aswell.
>Until patch 3.3.3, Titansteel Bar had a 20 hour cooldown. 

as it WILL force all the tryhards to go for JC for min-maxing. Is that something you want?

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Bold_Dragon%27s_Eye?oldid=2085103

**Comment by bongobg** [comment]
Do you suggest we downgrade clients to patch 3.0.3 or they should remove the self gems entirely? You think it's possible to just like that edit stats on existing items in the DB?

**Comment by knasen88** [comment]
I'm  suggesting editing the stats of some gems, This does not require a downgrade in client version by any means. Just an update serverside and clients need to clean their cache and it's done.

I know it's possible because some servers have itemization patches that changes stats on items appropriate to the current content patch their server is on. All users have to do is delete their wdb(cache)

**Comment by Dootz** [comment]
Adjusting stats would probably confuse everyone.
