### ISSUE TITLE
Angermanagement Warrior Arms Talent Bugged

### ISSUE THREAD

**Issue by benshorty** [SunwellTracker/issues#726]
Decription: Generates 1 rage every 3 seconds

How it works: 
its not generating rage every 3 seconds in or out of combat it seems

How it should work
it should generate 1 rage every 3 seconds while in combat or out of combat passively

Source (you should point out proofs of your report, please give us some source):

**Comment by Valmere** [comment]
Best I could find article wise was here - http://wowwiki.wikia.com/wiki/Anger_Management_(old)

Might be able to find some old warrior tutorials on youtube, but basically what the above link says is that the Anger Management talent didn't give out of combat rage generation until Cataclysm and then a few patches later (same expansion) was removed again.

As far as in combat regen goes, it's 1 per 3 seconds so it's probably just hard to notice.
