### ISSUE TITLE
[Zangarmarsh - Quest] Watcher Leesa'oh uncompletable

### ISSUE THREAD

**Issue by KyleImrie** [SunwellTracker/issues#727]
Decription: 
The quest 'Watcher Leesa'oh' in the Zangarmarsh zone cannot be completed, as far as I can tell.

How it works: 
The NPC Watcher Leesa'oh ( NPC id=17831) cannot be talked to.
![untitled](https://user-images.githubusercontent.com/35434286/36821328-623340cc-1ca7-11e8-86c4-6a4ac97754d8.png)

How it should work: 
The quest (quest id=9697) should just be a simple turn-in to Watcher Leesa'oh ( NPC id=17831) to complete.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
There is event after turn-in of quest http://www.wowhead.com/quest=9709/stealing-back-the-mushrooms . While she takes part in scene she no longer act like questgiver. It seems that she's  stuck, despite that she should reset after 5 minutes, so if you visit her again there's a chance you'll be able to proceed with chain.

**Comment by TSSchoof** [comment]
I have the same issue trying to hand in the follow up quest (http://www.wowhead.com/quest=9708/familiar-fungi). The NPC is there, but you can not talk to it.

**Comment by Dootz** [comment]
Will be fixed with next update.
