### ISSUE TITLE
shamman loot

### ISSUE THREAD

**Issue by lenoravexx** [SunwellTracker/issues#728]
Decription: shammans cant roll need on loot thats not highest armor and no caster gear 

How it works:  something drops and shamman cant roll unless its melee

How it should work: shammans should be able to roll on everything they can use the system doesnt recognize how the player is playing i need a balance of stats to properly play the class

Source (you should point out proofs of your report, please give us some source):

**Comment by TSSchoof** [comment]
The behavior should be like this:

> At patch 3.3.0 the system was changed so Need Before Greed will now recognize gear appropriate for a class in three ways: the class must be able to equip the item, pure melee will be unable to roll on spell power items, and classes are limited to their dominant armor type (ex. paladins for plate). All items will still be available via Greed rolls as well as the new Disenchant option should no member be able to use the item. Also, players will be able to roll on items with a required minimum level higher than then player's current level.
> 
> The changes at patch 3.3.0 deliberately introduced a new complaint: classes may not roll on gear of lesser armor level even if it is an upgrade, such as a holy paladin wanting mail with spellpower and intellect. The only way for that player to be sure of getting that item is for either for all other players to pass, or for whoever wins that item to trade it afterwards provided it wasn't disenchanted. Despite the griping, this is important to ensure equality with other classes: mail wearers can't roll need on plate, so plate wearers can't roll need on mail. Blizzard expects people should be able to find all the gear they need in their own armor class without poaching from other armor classes. 

Source: http://wowwiki.wikia.com/wiki/Need_Before_Greed
