### ISSUE TITLE
Scarlet Converts and Initiates drop Scarlet Armbands after the quest is finished.

### ISSUE THREAD

**Issue by Jdavidlol** [SunwellTracker/issues#730]
Description: In the undead starting area of Deathknell there is a quest that asks you to get Scarlet Armbands from Scarlet Converts and Initiates that are camped nearby. They drop this quest item regardless of if you have finished the quest already.

How it works: You finish the quest, kill a Convert, and they drop an armband that you don't need.

How it should work: When you kill a Convert after finishing the quest they should only drop money and normal enemy loot.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_022818_203425](https://user-images.githubusercontent.com/24926558/36827282-7795557a-1cc7-11e8-87a5-caae57046365.jpg)

**Comment by Dootz** [comment]
Will be fixed with next update.
