### ISSUE TITLE
Strand of the Ancients Bug

### ISSUE THREAD

**Issue by Ambellyn** [SunwellTracker/issues#733]
Decription: 
I cannot properly cast while sitting in a demolisher in Strand of the ancients, casts doesn't go off while instant spells does

How it works: 
I think the character is forced to line of sight forward when the demolisher drives, making us unable to attack enemies behind the demolisher

How it should work: 
You should be able to cast in a 360' LoS Zone

Source (you should point out proofs of your report, please give us some source): 
Can't find any sort of proof

**Comment by Rosenkrantz** [comment]
Bump. Still present, still breaks the battleground.
