### ISSUE TITLE
Razormane Hunter's Pets do not attack

### ISSUE THREAD

**Issue by Jdavidlol** [SunwellTracker/issues#734]
Decription: In the Barrens the enemy Razormane Hunter has a wolf pet. It should go to the player and attack them when the player attacks the Razormane Hunter.. but it currently does not.

How it works: You attack the Razormane Hunter and the pet just stands there.

How it should work: The pet should go to the player and start attacking them.

Steps to reproduce: Attack a Razormane Hunter from range.

**Comment by Dootz** [comment]
Will be fixed with next update.
