### ISSUE TITLE
Gretta the Arbiter's dailies available without requirements

### ISSUE THREAD

**Issue by bongobg** [SunwellTracker/issues#736]
Decription: NPC Gretta the Arbiter (https://db.darkwizard.pl/?npc=29796) give 1 random daily out of list of 4. Each of these quests has a requirement first to unlock the quests. What exactly happened to me - I picked quest Back to the Pit (https://db.darkwizard.pl/?quest=13424) and I'm still not completed the required quest Into the Pit (https://db.darkwizard.pl/?quest=12997): https://prnt.sc/ilhc2i

How it works: Gretta the Arbiter gives dailies with no requirements.

How it should work: Each of the 4 quests has a requirement in order do be available

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?quest=13424

**Comment by Dootz** [comment]
Will be fixed with next update.
