### ISSUE TITLE
[Icecrown Citadel] Prof. Putricide - oozes and Immune State interactions

### ISSUE THREAD

**Issue by grottor** [SunwellTracker/issues#738]
Decription: 
We did a guild run on ICC25, and we encountered the problem that we are not sure if this is a bug or not. I coudn't find any sources that could help to confirm our worries so i decided to post this problem here. The problem occurs on prof. putricide, more specifically the oozes and their targeting interaction on players with Immune State (Ice block , Dvine Shield)

How it works: 
When an ooze targets a player who is in Immune State (Ice block, Dvine shield) the ooze just stops his movements and doesn't switch target or continue moving towards his target

How it should work: 
As I said earlier i'm not sure how it should work, i didn't find any intel about it, but all guides mentions only about invisibilty, feign death, and vanish for "tricks" about oozes targeting. I coudn't find single mention about Ice block or Dvine shield so i assume the ooze should continue moving towards his target regardless if he is in Immune State or not.

Source (you should point out proofs of your report, please give us some source):

**Comment by knasen88** [comment]
They should continue and blow up on the immune target

**Comment by Kokaina** [comment]
Anwsered on forum.
