### ISSUE TITLE
[ PVP ] PVP in city all the time ON

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#74]
Decription:  Bug with PVP mode ON/OFF

How it works: 
No difference PVP is on or off anyway in our lands or in our citis (orgrimmar, tb etc. ) enemy can attack us.

How it should work: 
When we have pvp off we should be not able to be attacked by opponent in our home city.

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
