### ISSUE TITLE
Sunder armor glyph not working with devastate

### ISSUE THREAD

**Issue by Mallekito** [SunwellTracker/issues#740]
Decription: 
The glyph os sunder armor, that apply sunder armor to a second target, is not working as intended with devastate.

How it works: 
The glyph is only applying sunder armor to a second target when the skill sunder armor is used, not devastate skill

How it should work: 
The glyph of sunder armor, should work as intended with the devastate skill of the warrior, when using devastate skill with the glyph of sunder armor, a secondary target should be affected by the sunder armor as the glyph says, because the devastate skill of the warrior apply sunder armor to the target

Source (you should point out proofs of your report, please give us some source): 

http://wowwiki.wikia.com/wiki/Glyph_of_Sunder_Armor
http://www.wowhead.com/forums&topic=44326/prot-glyphs
https://us.battle.net/forums/en/wow/topic/2649965481

**Comment by akrom23** [comment]
Works okay.
