### ISSUE TITLE
Elixir of Water Walking

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#741]
Decription: With the buff from Elixir of Water Walking, I will randomly and routinely fall down from the surface of the water. This happens on its own with no outside interaction. I'm not attacked or doing anything other than fishing or running on a mount. After I fall into the water, I can then jump back up and water walk again, without re-using an elixir.

How it works:  Random spell break of water walk, buff remains. Can water walk again under the same buff within 2-5 seconds of jumping.

How it should work: Water walking should only be broken on damage/combat. It should allow continual water walking otherwise.

Source (you should point out proofs of your report, please give us some source):

**Comment by set-theorist** [comment]
Are you facing down into the water using your right click by any chance?

**Comment by ihcTactics** [comment]
On some occasions, yes. There have also been moments when I'm not pressing any keys or moving my mouse, just waiting for the bobber to trigger and I'll fall in.

**Comment by set-theorist** [comment]
Can confirm the issue with fishing with water walking, sometimes you bop down and up and it interrupts your fishing.

**Comment by ivanlink** [comment]
I can confirm it aswell, it's so annoying since oyu get randomly dropped on water and it interrupts your fishing cast.
