### ISSUE TITLE
Gyrm the Storm Giant

### ISSUE THREAD

**Issue by fleshpeicer** [SunwellTracker/issues#742]
Decription: 
Issue with the process of completing the quest

How it works: 
us Gyrm the Storm Giant to kill scourge and other giants, his abilities randomly bug and essentialy cannot attack or dismount from him, but he can still move around

How it should work: 
attack normally throughout the whole duration.

Source (you should point out proofs of your report, please give us some source):

**Comment by winNixz** [comment]
This always happened to me when I moved gymer outside of his designated area.
