### ISSUE TITLE
Holy damage and Partial Resists

### ISSUE THREAD

**Issue by tsokushin** [SunwellTracker/issues#743]
Decription:  Holy damage is getting partial resists on this server.

How it works: Currently there's an upwards of 10% chance of getting partial resists 

How it should work: Holy damage in wotlk did not get partial resists. It was either hit or miss, no partial resistances.

Source (you should point out proofs of your report, please give us some source): https://imgur.com/ktvq2r1

**Comment by ujellyx** [comment]
To add a source:
http://et.worldofwarcraft.wikia.com/wiki/Magic_schools_(WoW)
"It is not possible to resist Holy magic, giving it a slight advantage over other schools, but it does have a basic miss chance like all spells, offset by Hit rating, and spells can be silenced."

**Comment by knasen88** [comment]
level based resistance does exist for holy aswell, which is why you will see it on bosses.

**Comment by Sunwellxd** [comment]
https://www.youtube.com/watch?v=bJxKUaKKmQE
3:42s SoV dmg (resist)

**Comment by Kokaina** [comment]
random boss from Method, every single holy damage spell has resist
![image](https://user-images.githubusercontent.com/22802214/36906709-ec7544f2-1e36-11e8-8dd5-0887666d4603.png)

**Comment by Heartbraker** [comment]
It's like knasen88 said - resistance from level differences apply for holy as well. If you have 80 lvl, you should never see any resist on 80lvl mobs/players, but there's chance for a resist on mobs with 81+lvl/bosses
