### ISSUE TITLE
Damaging Auras going through Iceblock

### ISSUE THREAD

**Issue by Gattious** [SunwellTracker/issues#745]
Decription: 
Damaging Aura spells are going through Ice Block invulnerability. 

How it works: 
https://clips.twitch.tv/ArtsyIntelligentPuppyM4xHeh
This is a core issue among all damaging auras.

How it should work: 
Proof shouldn't even needed for something like this... It's pretty self explanatory. Can look at the iceblock spell if you need. ID=45438

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Nope, not a bug. Some spells do have ability to pierce thru invulnerability, twilight shift is one of those.
![image](https://user-images.githubusercontent.com/16348711/36887356-1aaff312-1df1-11e8-9a1f-1bf83003ac3c.png)
