### ISSUE TITLE
Arena vendor prices wrong

### ISSUE THREAD

**Issue by reqiuem** [SunwellTracker/issues#746]
Decription: 
Pleased look at the arena deadly vendor, and review your item costs. The offhand weapons are the same as the main hand prices which is totally wrong. Buying the mainhand dagger and offhand dagger cost over 2k more Arena points then if i was to buy a 2h wep. i believe the offhand is like 1k points.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
We need a source.

**Comment by ozzyian** [comment]
http://www.wowhead.com/forums&topic=60347
<Veteran Arena Vendor>
Two-Hand, Ranged – 4,500
Main Hand, One-Hand – 3,150
Shield – 2,250
Off Hand, Held In Off-hand (Caster) – 1,350
Idol, Libram, Sigil, Totem – 1,200

**Comment by dinkmaster** [comment]
Off-hand weapons should definitely NOT cost the same as main hand

**Comment by Jdavidlol** [comment]
Off hand shouldn't be the same as mainhand.....

**Comment by reqiuem** [comment]
http://www.arenajunkies.com/topic/44468-pvp-gear-in-wotlk-where-to-get-it-and-how-much/

How many sources do you need, here is a POST from 2008 arena junkies that shows the same thing, there isnt much "sources" out there from a 2008 game season. Also you could take a poll or just ask yourself. why would a main hand cost 3150 and a offhand cost 3150 equaliing out to 6300 Arena points. And 1 2handed weapon you have priced at 4500 AP?
Fix please been 20 days.

**Comment by Dootz** [comment]
should be fine now.
