### ISSUE TITLE
Into The Wild Green Yonder

### ISSUE THREAD

**Issue by Reapsouls** [SunwellTracker/issues#747]
Decription: 
Into The Wild Green Yonder does not work as it should.

How it works: 
Well you fly on a proto drake and you cant pick up the captured crusaders. They just talk and nothing else happens.

How it should work: 
You fly on a proto drake to rescue 3 Crusaders that is captured and fly back with them to The Argen Vanguard.
Source (you should point out proofs of your report, please give us some source):

**Comment by frizzon** [comment]
For you to be able to rescue them they need to have a debuff called Nerubian Webs http://www.wowhead.com/spell=56726/nerubian-webs

Not all the captured crusaders have this debuff at the moment, so when you use the drake skill on them nothing happens. Can still be done if you find the ones that do have it though.

**Comment by bongobg** [comment]
^
As frizzon said, the crusaders have to have the debuff. Visually they look webbed. The others scattered around 'dont need rescuing'. I think it's not a bug to have non-webbed crusaders as well but i think they should be another ID npcs.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/989
