### ISSUE TITLE
[Warrior] Charge and Intercept not stunning instantly on cast

### ISSUE THREAD

**Issue by Kiljam** [SunwellTracker/issues#749]
Decription: 
Charge and Intercept currently are stunning when you have charged to the target so the interrupting is delayed. Hope you can fix this. It's gamebreaking for warrior pvp atm

How it works: 
Charge and Intercept currently are stunning when you have charged to the target so the interrupting is delayed.

How it should work: 
The stun should be received instantly when the charge is casted.

Source (you should point out proofs of your report, please give us some source): 
I couldn't find any official source to prove this. But I'm a multi glad warrior from retail and I have played warrior class for over 10 years. I am certain it should work the way I described. It works like this on all other private servers I played too.

**Comment by Akha72** [comment]
So it certainly wouldn't be a problem for optimus prime mega glad to provide a video of retail warrior using charge and intercept, would it?

**Comment by set-theorist** [comment]
https://www.youtube.com/watch?v=vFQl7JStwu4
4:50

There is a tiny delay but it's much much shorter than what is on sunwell, it's probably due to lag.

**Comment by Tulkastor** [comment]
I'm havint this issue aswell when engaging mobs in dungeons quite often. For example; Dragonflayer Overseers in Utgarde Keep (the ones which are around ghoul packs) have charge ability. But they can still charge you while you use spell "charge" to them. That should not happen. (I play with 70-80 ms)

**Comment by dinkmaster** [comment]
It shouldn't be instant, there's always been a delay

**Comment by Tulkastor** [comment]
I will not go further to say there is absolutely no delay. However in my experience as a warrior(from TBC patch 2.4.3 till end of WoD), I have never experienced a mob charging me back unless the mob itself was immune to stun effects. In pvp this would occur rarely where two players would cast charge to each other in a very close time frame. So it might not be a bug but rather the delay time of the charge's stun is too long and has to be changed.
