### ISSUE TITLE
[ RDF ] Satchel of Helpful Goods

### ISSUE THREAD

**Issue by fnm86** [SunwellTracker/issues#75]
Decription: When we make RDF we should receive also [ Satchel of Helpful Goods ] that was added in Patch 3.3.0 (08-Dec-2009): Added.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Satchel_of_Helpful_Goods

**Comment by nimeral** [comment]
Yea, but they're emulating pre-3.3.0 times. The report https://github.com/SunwellTracker/issues/issues/55 was closed when they thought it's about Satchel. So I guess this one will be closed too - until ICC.

**Comment by fnm86** [comment]
Right all is clear now thx pal.
