### ISSUE TITLE
Rejek in Frenzyheart Hill sometimes goes missing

### ISSUE THREAD

**Issue by set-theorist** [SunwellTracker/issues#751]
Decription: 
Sometimes the Frenzyheart quest giver Rejek (https://db.darkwizard.pl/?npc=29043) goes missing for no apparent reason. I highly doubt he's being killed, since the database says that his respawn time is 5 minutes, and this issue seems to be unique to him.

How it works: 
Sometimes, Rejek just disappears from his spot. I don't know exactly what causes it and it seems to be random

How it should work: 
He should not be disappearing from his spot.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next server update
