### ISSUE TITLE
Steamwheedle Cartel reputation not rewarded properly

### ISSUE THREAD

**Issue by Hoodeee** [SunwellTracker/issues#752]
Decription: 
I am currently:
Booty Bay: Friendly
Everlook: Neutral
Gadgetzan: Neutral
Rachet: Honored

When questing and killing pirates in Tanaris I am no longer receiving reputation with Rachet. However, I still receive max rep with Gadgetzan and reduced rep with the other 2 factions due to the location of the quests and npcs. If I quest and kill pirates in Barrens I receive max rep with Rachet and reduced rep with the 3 other factions. This leads me to believe there is a bug that prevents reputation gain past honored if you are not in the "priority" factions zone.

How it works: 
Reputation is not properly awarded past honored.

How it should work: 
Reputation should only be prevented past honored when handing in the cloth quests to reach neutral with that specific faction. Every other source of reputation should award rep until exalted with all 4 factions.

Source (you should point out proofs of your report, please give us some source): 

https://imgur.com/0vpnzjC

This first image shows me killing a pirate in Tanaris and not receiving rep with Rachet.

https://imgur.com/1iUEcGz

Second image shows me killing a pirate in Barrens and receiving rep with all 4 factions.

**Comment by set-theorist** [comment]
Just to add some clarification from http://wowwiki.wikia.com/wiki/Steamwheedle_Cartel

NPC grants full reputation for the "local" Steamwheedle faction to the end of honored and 50% reputation to the other three factions through to exalted. For specific information, see the list of Mobs which affect reputation with Steamwheedle Cartel.

That means that pirates and venture co. mobs should grant full reputation only up to 11999 honored and 50% of full reputation to the other 3 factions all the way to exalted.

**Comment by Tinytej** [comment]
I really would love it, if Devs would look into this. I am having the same issue, and it's really frustrating :P

**Comment by Hoodeee** [comment]
I am getting very close to the "Insane in the Membrane" achievement. I made this issue 26 days ago. The bug still exists and there hasn't been any comments by the dev. Please fix this issue.

**Comment by Hoodeee** [comment]
@Dootz 
http://wowwiki.wikia.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel
This link shows every mob and every quest that should award rep to the goblin factions, and at what point those quests and mobs should stop rewarding reputation.

**Comment by Dootz** [comment]
ok i'll check that today

**Comment by Dootz** [comment]
will be fixed with next server update
