### ISSUE TITLE
[NPC] School of Fish

### ISSUE THREAD

**Issue by inscaped** [SunwellTracker/issues#753]
Decription: 
Multiple School of Fish flies above the water in Eversong Woods.

How it works: 
Multiple School of Fish flies above the water in Eversong Woods.

How it should work: 
Multiple School of Fish should be under water.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030218_214024](https://user-images.githubusercontent.com/30598442/36915682-a941981c-1e62-11e8-878a-31635c8b988f.jpg)
![wowscrnshot_030218_214043](https://user-images.githubusercontent.com/30598442/36915683-a95fb590-1e62-11e8-9e03-b5e7f6c64959.jpg)
![wowscrnshot_030218_214146](https://user-images.githubusercontent.com/30598442/36915684-a9822bde-1e62-11e8-9626-fc51067f3a36.jpg)

**Comment by Dootz** [comment]
Will be fixed with next update.
