### ISSUE TITLE
Bug:Can not receive  request of succubus

### ISSUE THREAD

**Issue by MasterTreee** [SunwellTracker/issues#754]
Decription: 
I am a new player of this game. Succubus is a level 20 request that we can get this pet by completing this level 20 request. However, there is also a request which is a level 30 Fel Hunter. When I visit the  NPC in Stormwind city at the level of 36, he only gave me request of Fel Hunter. I thought I could get level 20request after getting Fel Hunter, I was wrong. 

I researched a lot and realized it is a common bug for many players, one of the solutions is to let GM deliver the request of succubus personally. I wish this bug can be fixed, or please tell me I am wrong if there is any other solution. My ID name is Bernuilli in Angrathar.

**Comment by Akha72** [comment]
Succubus quest chain starts in Ironforge, ask a guard where a warlock trainer is.
