### ISSUE TITLE
Alchemy Mastery quests bug

### ISSUE THREAD

**Issue by Iolwut** [SunwellTracker/issues#755]
Decription: Alchemy Master of Potion / Elixir / Transmute quests are unpickable after you choose one then abandon it.

How it works: 
When you hit 350 skill with your alchemy you are able to choose 3 different mastery namely Master of Potion / Elixir / Transmute. First i choose Master of Elixir since i want to proc my Flasks that i make. Then i read it its not a good idea since you can not complete it on this server, because the pre quest requires you to farm TBC Heroics to complete, wich is not possible since nobody have any heroic keys, or even you farm the reputation to get it, you cant solo it.
So the way to do is no matter what spec you want to choose, you always want to be Master of Transmute first, because the 4x Primal Might are solo farmable for the quest. Then you just unlearn the specialization at the trainer for 150 gold , and re-train one of the other 2 at the trainer for free. 
So i was like cool, i abandoned the Master of Elixir quest so i can pick up the Transmute one. However, after you pick up any of 3 path, then you delete the quest, you are not able to choose again, even if you dont have any of them in your questlog wich is a bug.

How it should work: 
Pick one of the 3 mastery quests. Abandon the quest you picked up wrongly. Talk to quest giver and pick one again.

Source (you should point out proofs of your report, please give us some source): 
Cant find any source because its a Sunwell bug. I already made tickets of this ingame as Lyz.

**Comment by Iolwut** [comment]
Well i cant proof that, its just common sense. Even if it would be as intentented it hurts the players since its impossible to do the quest on this server, and you have to throw away your proffession if you made this mistake. Im highly suggest to do a solution for this because its not the player fault. Its not like it was on retail, where 90% of the 80s had their heroic keys from back in then when they played TBC so you could find a group to help you out. At the moment if you choose the Elixir Master quest by mistake you can throw your Alchemy to the garbage.

**Comment by Azathothh** [comment]
By Coki (2,640 –  5·11)  on 2008/12/20 (Patch 3.0.3) |   |  
You can still change your mind on which mastery you want if you have completed this quest but not part two.
All you do is decline part two and take Master of Transmutation (part 2) to become Transmutation Master or Master of Potions (part 2) to become Potion Master from the relevant NPCs.

source: http://www.wowhead.com/quest=10906/master-of-elixirs

**Comment by Dootz** [comment]
will be fixed with next server update. You'll be able to pick different alchemy prof quest, without next prequest. Just go to different trainer after you abandon quest

**Comment by TheBigBallsOfFury** [comment]
Are you sure this is working? Changed from Transmute Master to Elixir Master and didnt get a proc in something like 30 flasks.
