### ISSUE TITLE
[death knight] Hysteria - not getting removed

### ISSUE THREAD

**Issue by ghost** [SunwellTracker/issues#756]
Decription: Hysteria is not getting removed from a friendly target after you respect. But it gets removed from yourself if you respec.

How it works: Giving hysteria to a friendly target and then respecing to other spec the buff doesn't get removed from your friendly target. It gets removed if you do it on yourself.

How it should work: The buff should instantly be removed from the player that you put it on, as it works when you do it on yourself.

Source (you should point out proofs of your report, please give us some source):

**Comment by Crackaw** [comment]
Proof?

**Comment by Avarishd** [comment]
proof? The same happens when you give Hysteria to yourself and then respec, it gets removed, this should happen to the friendly player as well.

**Comment by Jiokko** [comment]
are you saying you are able to give hysteria to yourself?

**Comment by akrom23** [comment]
Works okay. Hysteria is not getting removed on respec from yourself.
