### ISSUE TITLE
mining nodes

### ISSUE THREAD

**Issue by Wrecker80** [SunwellTracker/issues#758]
Decription: 
running around howling fjord and there are literally no cobalt nodes and there is noone here that would be mining

How it works: 
nodes spawn

How it should work: 
nodes get mined

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
There are around 30 spawns in hownling fjord, but with just flighing by it doesn't seem right. It'll be slightly increased.

**Comment by dinkmaster** [comment]
Could you also check storm peaks for flower nodes?
