### ISSUE TITLE
Toxic Tolerance 

### ISSUE THREAD

**Issue by ivanlink** [SunwellTracker/issues#759]
Decription:  Toxic tolerance is the 1st quest in order to obtain the Venomhide Raptor mount.

How it works:  The Venomhide Ravasaur are supposed to spit a venom on you but they never do it , so you never get credit for the quest. 

How it should work:  The Venomhide Ravasaur should spit a venom poison on you which gives you credit for the Toxic Tolerance quest.

https://imgur.com/iymZyYq

**Comment by Dootz** [comment]
Will be fixed with next update.
