### ISSUE TITLE
[Quest] Iron Rune Constructs and You: The Bluff (Howling Fjord)

### ISSUE THREAD

**Issue by jealousmuch** [SunwellTracker/issues#760]
Decription: Its part 3 of the chain. You transform into a golem and should bluff Lebronski, but there is no chance to bluff him.

How it works: You transform into a golem. Then stand on Lebronski's Rug but there wont be any reaction by Lebronski, therefore you cant bluff him.

How it should work: You transform into a golem. Then stand on Lebronski's Rug. Shortly after a speechbubble should appear (he says something) and you can bluff him with the golemskill. After it the quest is completed.

Source (you should point out proofs of your report, please give us some source): 
Watched a youtube video and couple of comments at some websites how it works. It works quite simple, but the interaction to bluff him (his speech) never comes.

**Comment by Dootz** [comment]
It can take him up to 1 minute to notice you, but he'll. It'll be slightly reduced.

**Comment by jealousmuch** [comment]
are you sure? stood there, im sure for at least 1min and nothing happened like in the videos of retail or w/e

**Comment by jealousmuch** [comment]
Tried it again with the /timer ingame, stood there in different positions on the rug, never happened anything.

**Comment by Dootz** [comment]
Will be fixed with next update.
