### ISSUE TITLE
Haalrun alchemy vendor npc bug

### ISSUE THREAD

**Issue by Iolwut** [SunwellTracker/issues#761]
Decription: Npc Haalrun in Zangamarsh doesnt sell Elixir of Major defense recipe.

How it works: He sell only 2 recipes, namely Recipe: Super Mana Potion; Recipe: Elixir of Major Frost Power

How it should work: He should sell 3 recipes, namely Recipe: Elixir of Major Defense; Recipe: Super Mana Potion; Recipe: Elixir of Major Frost Power

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/bKRYT

**Comment by Dootz** [comment]
He sells it, but this recipe is limited. It's restock time is around 12 h. Until proven otherwise, i would say it's intended behaviour.
