### ISSUE TITLE
[Steamwheedle Cartel Reputation.] Not giving rep as intended.

### ISSUE THREAD

**Issue by Tinytej** [SunwellTracker/issues#762]
Decription: 
The various Pirates that awards Steamwheedle Cartel, stops giving rep after Honored with the other Goblin cities.

How it works: 
If I am farming reputation in Rachet Pirates, they stop giving rep with the other factions at Honored

How it should work: 
They should continue giving rep all the way to exalted, only the Goblin faction where you are farming should stop at Revered, so from Revered with Rachet etc, you should farm either in Tanaris or Stranglethorn Vale to get the rest of the way.

Source (you should point out proofs of your report, please give us some source): I have actually been farming these reps for quite a bit, it's my 5th time doing Insane in the Membrane.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/752
