### ISSUE TITLE
Remastered Legion graphics problem

### ISSUE THREAD

**Issue by Jiokko** [SunwellTracker/issues#763]
Decription: 
I see some mounts (mostly dreadstead and charger totally white.

I don't know if i should post it here or at forums since its something "different"

I will explain what i mean with my pictures.

Problem seems to fade if the player dismounts and remounts again.

check mostly the 2nd screenshot to see it clearly.

reload doesn't work for it. Just dismount and remount.

![wowscrnshot_022418_095238](https://user-images.githubusercontent.com/6665852/36933188-93ddcf42-1edd-11e8-9870-e3e9c4e5db26.jpg)
![wowscrnshot_030318_121851](https://user-images.githubusercontent.com/6665852/36933189-983a8378-1edd-11e8-82b8-a9fadc9a9def.jpg)
![wowscrnshot_022218_131430](https://user-images.githubusercontent.com/6665852/36933191-9c21d0e0-1edd-11e8-8716-d43f306851bd.jpg)

**Comment by dinkmaster** [comment]
This is a client-side bug and has nothing to do with the server
