### ISSUE TITLE
[Dungeon] Nexus - Keristrasza aura not removed on pets when they're moving

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#764]
Decription: 
The damaging aura (ID: 48094) isn't removed when pets are moving, causing them to die early in the encounter.

How it works: 
Doesn't matter how much you move your pet, the aura doesn't fade and keeps stacking until your pet dies.

How it should work: 
The aura should be removed from the pet when it's moving.

Source (you should point out proofs of your report, please give us some source): 
See spell-tooltip.

**Comment by artemmavrich** [comment]
Confirm

**Comment by basvis** [comment]
Confirm
