### ISSUE TITLE
Kidney shot turns the mob around visually but server-side mob is still facing forward

### ISSUE THREAD

**Issue by dinkmaster** [SunwellTracker/issues#765]
Decription: 
When I kidney shot someone as a rogue the mob instantly turns it's back to me (visually) but Backstab/Ambush doesn't work because server-side the mob is still facing me

How it works: 
When I kidney shot someone as a rogue the mob instantly turns it's back to me (visually) but Backstab/Ambush doesn't work because server-side the mob is still facing me

How it should work: 
I'm not sure, either the mob should turn it's back to me server-side as well, letting me backstab them after the stun or they shouldn't turn at all.

Source (you should point out proofs of your report, please give us some source): 
https://gfycat.com/BarrenImpeccableBlowfish

**Comment by Semper-Numquam** [comment]
http://wowwiki.wikia.com/wiki/Backstab
"When soloing, use [Gouge] to move behind the mob and then Backstab. This earns two Combo points off the bat! At higher levels it also combines well with [Cheap Shot] and [Kidney Shot]."

Checked notes and sources and as far as I can see CCs shouldn't turn your opponent around and make you free to backstab. In fact, they promote MOVING behind the target while it's CCed to land a backstab. So this is a visual bug and not a mechanics bug.

Also applies to other stuns like Deep Freeze, so it's more of a visual thingie than a certain spell effects. From what I can observe, CCs like stuns cause the NPC to face the way it was facing before it was pulled, but I might be wrong.

**Comment by TheBigBallsOfFury** [comment]
Can confirm every time i Kidney Shot a mob it faces the way it was facing before aggro. Visual only since I still have to go around to Backstab.
