### ISSUE TITLE
[Quest/NPC] Fresh Remounts - Horses not spawning

### ISSUE THREAD

**Issue by ghettoniggu** [SunwellTracker/issues#766]
Decription: 
The horses of the quest fresh remounts are not spawning (venomspite)

How it works: 
it doesn't

How it should work: 
horses spawn, and you take them back

Source (you should point out proofs of your report, please give us some source): 
Tried to re-do this quest for 5 times various times, impossible

**Comment by Dootz** [comment]
Works fine for me. Maybe their respawn time is an issue. Will be reduced a bit.

**Comment by Dootz** [comment]
will be fixed with next server update
