### ISSUE TITLE
Quest Bug

### ISSUE THREAD

**Issue by ghettoniggu** [SunwellTracker/issues#767]
Description: 
Unable to talk to the priest in the quest: a fall from grace: I'm unable to talk to the priest for this quest.
(I am a SP)

How it works: 
You talk to priest and end the quest

How it should work: 
you are able to talk to the priest

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/235
