### ISSUE TITLE
[Quests] Counting objectives more than once

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#769]
Decription: 
A lot of quest objectives, like, for example to free prisoners from the cage , or destroy something by using quest item double count. For example quest : [A Tangled Skein](https://db.darkwizard.pl/?quest=12555) when you use quest item on flying machine it instantly count 2/5 from first machine.
It's not an quest issue because i met a lot of quest while lveling from 1 to 80 level, it is a problem in your  core, i think..

How it works: 
A lot of quest objectives, like, for example to free prisoners from the cage , or destroy something by using quest item double count. For example quest : [A Tangled Skein](https://db.darkwizard.pl/?quest=12555) when you use quest item on flying machine it instantly count 2/5 from first machine.
It's not an quest issue because i met a lot of quest while lveling from 1 to 80 level, it is a problem in your  core, i think..

How it should work: 
Obvious, when you use quest item to free some npc from cage  or smth else it should count 1/5, 2/5, 3/5 etc.

Source (you should point out proofs of your report, please give us some source):

**Comment by Semper-Numquam** [comment]
Depends on the objective, but this is true. There are some quests like "Oh Noes, the Tadpoles!" in Borean Tundra that have many NPCs freed per cage oppened, but on other quests a single (burn this) might trigger more than one credit.

**Comment by artemmavrich** [comment]
I met such types of quest all over the Azeroth. Like burning some corpses, free prisoners from cages, use quest items on mobs, etc.  so, possibly, it is core problem, not exact quest

**Comment by Dootz** [comment]
After investigating this issue i found that it's not necessarily core issue. At least bug in mentioned quest occurs due to specific order of quest completion actions. I'll try to find other quests that have this issue. Any help will be appreciated.

**Comment by artemmavrich** [comment]
[Doing Your Duty](https://db.darkwizard.pl/?quest=12227#?ref=sunwell.pl) during quest you "make" TWO [Partially Processed Amberseeds](https://db.darkwizard.pl/?item=37250) but to complete quest you need only one.

**Comment by Valmere** [comment]
#503 
#575

**Comment by artemmavrich** [comment]
[Timear Foresees Titanium Vanguards in your Future!](https://db.darkwizard.pl/?quest=13244#?ref=sunwell.pl)

![wowscrnshot_031118_100118](https://user-images.githubusercontent.com/35955516/37251948-dfcc5596-2521-11e8-9dd5-33a6721a5da3.jpg)
![wowscrnshot_031118_100119](https://user-images.githubusercontent.com/35955516/37251950-e544038e-2521-11e8-9859-6eeb300b95f5.jpg)

**Comment by Dootz** [comment]
found the issue with titanium vanguards, again different thing :( will be fixed with next server update.
