### ISSUE TITLE
[NPC] Matis the Cruel is passive

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#77]
Decription: Matis the Cruel is passive

How it works: Matis the Cruel (ID 17664) doesn't hit you, and doesn't even move when engaged. He only dismounts and then stays until you either kill him, capture him for the quest (ID 9711), or evade him. I charged to him, probably this is the reason, forgot to test without charge.

How it should work: Matis the Cruel should attack you as all the other mobs in game do : )

Source (you should point out proofs of your report, please give us some source): -

**Comment by TSSchoof** [comment]
Can confirm, exact the same happened to me. Was looking to report this too.

**Comment by Dootz** [comment]
will be fixed with next server update
