### ISSUE TITLE
Have They No Shame quest bug

### ISSUE THREAD

**Issue by whyhallothar** [SunwellTracker/issues#770]
Decription: The quest item "Bertrand's Research" for the quest [Have They No Shame?] in the Nexus seems to be only lootable by a single person.

How it works: The first person to reach the book on the ground loots it and it does not respawn.

How it should work:  After each member of the group loots the quest item it should respawn so that more than one person can complete the quest per run.

Source (you should point out proofs of your report, please give us some source): 
![havetheynoshame1](https://user-images.githubusercontent.com/36212388/36936260-dfb4ff9a-1efa-11e8-8ffd-9d2444b7911d.jpg)
![havetheynoshame2](https://user-images.githubusercontent.com/36212388/36936261-e14a97e8-1efa-11e8-9eaf-0d75fde4d251.jpg)

**Comment by Dootz** [comment]
Will be fixed with next update.
