### ISSUE TITLE
[Death Knight quest] An End To All Things

### ISSUE THREAD

**Issue by thanhtotti** [SunwellTracker/issues#771]
Description: 
- Respawn time of mobs is too slow

How it works: 
The respawn time of scarlet soldier is too slow, and DKs have to kill 150 of them

How it should work: 
It should respawn more frequently regarding number of new Death Knight this day.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next update.
