### ISSUE TITLE
[PvE] Partial Resist while full Hit capped

### ISSUE THREAD

**Issue by UFJ** [SunwellTracker/issues#773]
Decription:  It seems like mobs in PvE, bosses or any kinds of mob partially resist spells on a regular basis(around 5 to 10% of the base damage is resisted).

How it works:  Mobs in pve are partially resisting spells(around 5 to 10% of the base damage is resisted).

How it should work:  Mobs should not partially resist spells, they should not have resistances. 

Source (you should point out proofs of your report, please give us some source): https://imgur.com/a/eS4cE
This is a screenshot of a partially resisted spell(10% dmg resisted). My char is fully hit capped.

**Comment by Semper-Numquam** [comment]
Let's see:

This is not TBC where spell hit and spell resistances were linked. In Wrath of the Lich King, you can get hit capped and still get partial resists if mob is higher level or has an assigned stronger resistance to magic.

Spell Penetration doesn't work in PvE either. This means that as long as target has higher level it will have a chance to resist your spells partially. For each level above you, target gets more base resistance. 

Source: http://wowwiki.wikia.com/wiki/Resistance

Btw, resistances are indeed bugged in this server and I'm currently reporting how.
