### ISSUE TITLE
[Redridge Mountains][Herbalism] Peacebloom spawn 10 yards east from flight master is under tree and unobtainable

### ISSUE THREAD

**Issue by Brennan11** [SunwellTracker/issues#774]
Decription: 
[Redridge Mountains][Herbalism] Peacebloom spawn 10 yards east from flight master is under tree and unobtainable

How it works: 
[Redridge Mountains][Herbalism] Peacebloom spawn 10 yards east from flight master is under tree and unobtainable

How it should work: 
Peacebloom is obtainable

Source (you should point out proofs of your report, please give us some source): 
Fly to RedRidge mount and have herbalism skill. Attempt to obtain the peacebloom node 10 yards to the east.

**Comment by Dootz** [comment]
everything near flight master looks fine, except maybe amount of spawns.

**Comment by Brennan11** [comment]
@Dootz The peacebloom node in Redridge Mountain location 34,63 is under the tree and not obtainable.
![wowscrnshot_030418_103027](https://user-images.githubusercontent.com/22463850/36948993-5c4e0e2e-1f97-11e8-9b44-dd967940b732.jpg)
![wowscrnshot_030418_103040](https://user-images.githubusercontent.com/22463850/36948994-5c6b9c96-1f97-11e8-8e7b-27a83922a53a.jpg)
![wowscrnshot_030418_103020](https://user-images.githubusercontent.com/22463850/36948995-5c84aa56-1f97-11e8-9f5a-8ed036df1c5f.jpg)

**Comment by Dootz** [comment]
thanks for coord, i was looking at different tree.

**Comment by Dootz** [comment]
Will be fixed with next update.
