### ISSUE TITLE
[PvE][Resistances] NPC resistances are too high. Players getting aditional base resistances.

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#775]
**Decription:** 
NPCs currently have higher resistances than they should, allowing them to resist more damage and more frequently than they should.

Edit: Players are getting some sort of base resistance for no reason, allowing them to get partial resists even when their resistance is at 0 vs mobs of the same level or players of the same level.

**How it works:** 
NPCs have a higher base resistance than they should. Spell Penetration wasn't designed to work in PvE, so this bug reduces the casters DPS with no way to avoid it.

From what I can see, mobs with lvl 81 and 82 get pretty much the same amount of resists and % resisted than boss level characters, allowing them to get 10-20% partial resists from players casts and more often than not (about 30-50% of casts show a partial resist)

Edit: Players are also obtaining aditional resistances vs other players from the same level, and this base resistance is unaffected by spell penetration, so a player with 0 resistances still gets 10% or so partial resists even against a player of the same level with Spell Penetration gear.

**How it should work:** 

NPCs should have a base resistance (in general) that in endgame is only affected by the level difference between the player and the mob, going by the formula in the source.

effective resistance rating = Rb + max((Lt - Lc) * 5, 0) - min(P, Rb)
Rb - target base resistance (as advertised on the character sheet)
Lt - target level
Lc - caster level
P  - caster spell penetration

_"In PvE boss fights, the player level was usually equal to or less than the boss level, and no spell penetration was in effect."_

_"Note that this formula rendered level 83 bosses as having 15 magical resistance against level 80 player attacks."_

Of course, Player+1 and Player+2 lvl mobs (81-82 endgame mobs) should have 5 and 10 base magic resistances accordingly, clearly less than Player+3 level mobs (like bosses)

Then this formula:

Damage reduction percentage = 100% * effective resistance rating / ( K + effective resistance rating )

_[For level 80 mobs this constant K was 400. For level 83 boss mobs K was believed to be 510.]*_

100% * 15/(510+15) = 100 * 0.02857142857 = 2.8% damage reduction overall.

From my experience, this is reduced to around 10% chance of a 5% partial resist, and a 5% of a 10% partial resist which in average round up to about 2.8% damage mitigation.

Currently, the values are about 50% for a 10% damage mitigation and 10% for a 20% partial resist, way more than intended, specially since it double dips in effects like Ignite.

That's for NPCs. As for players. they should have 0 base resistances against others of the same level each  as shown in the character's stat tab. "Resistance against lvl 80: None" unless resistance gear/auras/buffs are equipped. Yet they are still getting resists.

**Source (you should point out proofs of your report, please give us some source):** 

http://wowwiki.wikia.com/wiki/Resistance

Here you can find the formulae, calculations and stuff for wotlk.

**Comment by ujellyx** [comment]
Holy non-binary spells can get partial resists due to the level-difference and therefore level-based resistance to holy which is the same as the other schools.

**Comment by Semper-Numquam** [comment]
After even further research I found info that agrees with you. There's no Holy Resistance but base resistance also includes Holy Damage. I'll edit post and remove it.

**Comment by Semper-Numquam** [comment]
Hell, even lvl 77 mobs are getting 10% partial resists against my spells (lvl 80 mage)

**Comment by moonsado** [comment]
++notice devs

**Comment by Saveraa** [comment]
Really no response so far from devs? Its getting ridiculous when mage can resist (immune) Shadowfury without any resist buffs.

**Comment by Semper-Numquam** [comment]
Well, a mage in PvP spec and Mage Armor has easily 120 resist at lvl 80, which is about 20-30% chance of a full resist.
