### ISSUE TITLE
Arathandris Silversky <Emerald Circle>npc=9528 Bugged

### ISSUE THREAD

**Issue by Mangonarango** [SunwellTracker/issues#777]
Decription: 
Arathandris Silversky npc=9528 is a female nightelve girl that lives in fellwood. This NPC doesnt give any follow Quests.

How it works: 
She npc=9528 gives the quest Cleansing Felwood quest=4101.
Then you get the option the get a Cenarion Beacon item=11511. 
But 0 follow quests. These quests are necessary to cleanse the flowers in fellwood. 
Cenarion Beacon is working i have this item in my inventory and i get Corrupted Soul Shard item=11515

How it should work: 
She npc=9528 gives the quest Cleansing Felwood quest=4101. 
Then you get the option the get a Cenarion Beacon item=11511. 
She should give now 5 quests. 

Salve via Hunting quest=4108
Salve via Mining quest=4104
Salve via Gathering quest=4105
Salve via Skinning quest=4106
Salve via Disenchanting quest=4107

Each Quest gives 2 Cenarion Plant Salve

Source (you should point out proofs of your report, please give us some source): 
This is a screenshot from the NPC:
https://i.imgur.com/GImWHUu.jpg

**Comment by Dootz** [comment]
To get these quests you need to know appropriate profession (Mining, Herbalism etc.). There are no requirements for "Salve via Hunting" and i was able to see it after Cleansing Felwood.

**Comment by Shirtrippa** [comment]
Just to add to this, I am facing the same issue on the Horde counterpart version of Arathandris (Maybess Riverbreeze). I am a miner and I am unable to choose any of the "Salve Via" options. They are not available to players for the purpose of completing the corrupted plants' quests.

**Comment by Dootz** [comment]
Ok, i'll check that again.

**Comment by Dootz** [comment]
Will be fixed with next server update
