### ISSUE TITLE
[Mage} Glyph of Ice Lance

### ISSUE THREAD

**Issue by Chillbringer** [SunwellTracker/issues#778]
Decription: Glyph of Ice Lance has no effect at all.

How it works: The glyph has no effect at all. Ice lance does triple dmg against frozen targets even with the glyph.

How it should work: Ice lance should deal quadruple dmg against frozen targets with the glyph.

Source (you should point out proofs of your report, please give us some source): I don't have any proof of this happening. But I've been testing this on mobs and the dmg of ice lance against frozen targets with or without glyph was the same.

**Comment by Dootz** [comment]
> Use: Your Ice Lance now causes 4 times damage against frozen targets **higher level than you** instead of `triple damage.`

On which mobs you've tested it? Because it's supposed to deal x4 damage to enemies with higher level than you, and that's how it works.
