### ISSUE TITLE
Quest: An End to the Suffering

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#779]
Decription: 
[An End to the Suffering](https://db.darkwizard.pl/?quest=12647) is not working properly. After you reach the temple you MUST use a quest item thet will wake up sleeping bear and ONLY THEN you can attack him BUT now you can hit him without using quest item

How it works: 
[An End to the Suffering](https://db.darkwizard.pl/?quest=12647) is not working properly. After you reach the temple you MUST use a quest item thet will wake up sleeping bear and ONLY THEN you can attack him BUT now you can hit him without using quest item

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030318_184707](https://user-images.githubusercontent.com/35955516/36942813-b2e8f3a6-1f84-11e8-88a2-74df64318363.jpg)
On the screenshot you can't see mouse pointer as it is a screenshot... but it it

**Comment by Dootz** [comment]
Will be fixed with next update.
