### ISSUE TITLE
[Priest] Improved Shadowform's Fade.

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#78]
Decription:
Talent description:
Your Fade ability now has a 50/100% chance to remove all movement impairing effects when used in Shadowform (...)

How it works: 
Fade while in Shadowform removes some snares, while others are not removed. 
Sometimes, snare effect is removed (player moves normally) but debuff remains.
Sometimes, snare is removed and debuff is removed aswell.
Other times, neither snare nor debuff are removed.

Haven't been able to make a complete list, as some snares are from NPC and other for players and the application of the bug is irregular as stated above.

How it should work: 
Fade while in Shadowform should remove all snares with their respective debuffs. Even if the snare has another components to it (DoT for example).

Source (you should point out proofs of your report, please give us some source): 
Tooltip should be clear enough

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof!) and report bug properly once again.

Thanks in advance.
