### ISSUE TITLE
Quest: The Emitter (Azuremyst Isle)

### ISSUE THREAD

**Issue by jubasek21** [SunwellTracker/issues#780]
**Decription**: Missing cutscene upon completion.

**How it works**: There is no cutsene at the moment. 

**How it should work**: Mage of Technician Dyvuun (http://www.wowhead.com/npc=16550/image-of-technician-dyvuun) should appear at the emitter and the following exchange should occur: 

**Image of Technician Dyvuun says**: _By the seven Ata'mal crystals! Others have survived the crash! Zhanaa, is that you? It is so good to see you again!_
**Image of Technician Dyvuun says**: _And who do we have here? No doubt th... crzzzk ...ade this communication I give you greetings fro... psshzzzk... Azure Watch._
**Image of Technician Dyvuun says**: _Judging by your signal, we put you... ust southeast of the larger part of the island we crashed onto. Cross the Crystalbrook River to ge... kshhhhk zzzt. Sorry, there's a lot of stat..._
**Technician Zhanaa says**: _This is great news! Your efforts have indeed saved us!_

The image should despawn shortly afterwards.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=5ztokpam98Q

**Comment by Dootz** [comment]
Will be fixed with next update.

**Comment by Dootz** [comment]
will be fixed with next server restart
