### ISSUE TITLE
Achievement: Damage Control

### ISSUE THREAD

**Issue by Effimera** [SunwellTracker/issues#781]
Decription: A player should get the achievement as soon as at least 300k damage or healing is done in a single battleground. 

How it works: 

A player got the achievement after 414k damage done.

How it should work: 

Source (you  should point out proofs of your report, please give us some source): 
screenshot: the moment player got the achievement
![wowscrnshot_030418_120404](https://user-images.githubusercontent.com/24449020/36945656-ce54e4ba-1fb1-11e8-8fbb-f80d1c4d511c.jpg)

**Comment by Semper-Numquam** [comment]
The damage/healing done must be counted towards players only. There's no way to know how much damage had he done on NPCs immo.

I got this achiv with a DPS and with a healer and both worked fine for me so I think it needs further testing?

**Comment by Dootz** [comment]
that's correct, it counts only damage dealt to players. So is it possible that player from screenshot dealt additional 118k damage to NPCs? Because it's AV i would say it is.

**Comment by Effimera** [comment]
Okay you guys are right
http://www.wowhead.com/achievement=227/damage-control
Check the comment "The achievement doesn't mention it, but it has to be 300,000 damage to players. Farming harpies or gnolls or whatever else until you hit 300,000 damage will not cut it. I confirmed this today with a GM."
