### ISSUE TITLE
Icy Prism bug 

### ISSUE THREAD

**Issue by Szusterx** [SunwellTracker/issues#784]
Decription:  Cant craft icy prism , missing regents but i already have all mats.

missing chalcedony all the time 👎 

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Szusterx** [comment]
srv : angrathar

**Comment by MrTide** [comment]
Hi its not bugged you need 3 of each gem like how it was in early wrath
its intended
