### ISSUE TITLE
[Global] Herb/mine (?) nodes

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#785]
Decription: there're too many herbs

How it works: a herb _always_ respawns in the same locations shortly after being gathered

How it should work: within _some time_ after a herb is gathered, it should respawn in a random location; there should be _more_ locations in a zone than herbs

Source (you should point out proofs of your report, please give us some source): https://us.battle.net/forums/en/wow/topic/8569107882#post-5

Disclaimer: 

0) What's arguable or unclear is in _italics_.

1) "How it works" part is just an impression (of myself and some guildies), after gathering a herb in the same place in a fairly empty (players-wise) zone. I admit I could be wrong and it works as how it should work in general (see below).

2) "How it should work" part is very incomplete. I feel that there're two possible issues: the respawn timer is too short, and the number of herbs is too close (or equal) to the number of possible locations.

3) Source isn't perfect either, but it is the best I could google.

Hope someone else can improve this report, or prove me wrong.

**Comment by Dootz** [comment]
yup, i'm already working on it.
