### ISSUE TITLE
The Egg of Mortal Essence

### ISSUE THREAD

**Issue by xblazze** [SunwellTracker/issues#788]
Decription: Your Direct heals and heals over time have a chance to proc 505 haste for 10 seconds.

How it works: This trinket does not proc from direct heal from affliction warlocks when using Drain Life or Siphon Life procs as a warlock or Vampiric Touch for shadow priests.
Reproduce this bug by using an affliction warlock's Siphon Life and Drain life with the trinket equiped.

How it should work: When the periodic heal from Siphon life or direct heal from Drain Life ticks it should have a chance to proc 505 haste even if you overheal.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/item=40685/the-egg-of-mortal-essence#comments

**Comment by Dootz** [comment]
I'm not sure if you've read comments in provided link, but i found in comment section this quote:

> By menion (214 –  2·2)  on 2009/03/11 (Patch 3.0.9) |   |  
> Does NOT proc off of: (damaged or full health)
> - **Drain Life**
> - The new **Siphon Life** talent with Corruption
> - Fel Armor
> - Deathcoil
> - Haunt

so it seems like it shouldn't proc from those two.
