### ISSUE TITLE
[Quest] You're Fired!

### ISSUE THREAD

**Issue by Platinumcoated** [SunwellTracker/issues#789]
quest in Blade's Edge Mountains:
You're Fired!
https://db.darkwizard.pl/?quest=10821
http://www.wowhead.com/quest=10821/youre-fired

how to supposedly complete quest:
-kill Anger Guards (mobs around the place)
-loot Camp Anger Key 5x (a key required for next step, Unique (5))
-use 5 Legion Obelisk objects around the place (key required and consumed)
-Doomcryer mob spawns
-kill Doomcryer
 
Bug:
3 out of 5 obelisks cannot be used. They say they are locked, even though I have the key in my keyring.

The 2 obelisks that can be used say "Requires Camp Anger Key" in their tooltip information box (to the right bottom of the screen). The 3 obelisks that cannot be used just say "Locked".

links to obelisks:
https://db.darkwizard.pl/?object=185193
https://db.darkwizard.pl/?object=185195
https://db.darkwizard.pl/?object=185196
https://db.darkwizard.pl/?object=185197
https://db.darkwizard.pl/?object=185198

comment from Wowhead:
"Collect 5 keys and quickly click all 5 obelisks. A green line will connect it to a nearby floating crystal to show it is activated. Once all 5 are connected, a level 68 elite demon will walk down from the floating crystal."

The quest cannot be completed as a result.

**Comment by Dootz** [comment]
After some tests. They reset in 2 minutes, so probably someone have done this quest right before you. If you don't mind, could you check it again?

**Comment by Platinumcoated** [comment]
Retried the quest today and was able to complete it without any problems. All obelisks were usable and none of them said "Locked".
I'm pretty sure that I stayed around for atleast 10 minutes yesterday and the "Locked" status didn't change.

**Comment by Dootz** [comment]
ok, thanks.

**Comment by ivanlink** [comment]
I can confirm it, It says locked for me aswell, I'm waiting at the moment and see if they can be used.
