### ISSUE TITLE
[Mage] Fingers of Frost consumes on hit and not on cast.

### ISSUE THREAD

**Issue by Semper-Numquam** [SunwellTracker/issues#79]
Decription: 
Talent description:
Gives your Chill effects a 7/15% chance to grant you the Fingers of Frost effect, which treats your next 2 **spell casts** as if the target were frozen.

How it works: 
Currently, Fingers of Frost is being consumed by spell hit and not by spell cast, which means that if a spell hits more than one target, both charges are spent.
With Blizzard, each blizzard tick on each mob will consume a charge.

How it should work: 
Fingers of Frost should be consumed per spellcast. This means that if a spell hits more than one target (AoE) they all get treated as frozen but only one charge is consumed. This also means that even if no target is hit, one charge should be spent.
As for Blizzard (talented into Improved Blizzard) it should consume one charge to benefit the whole duration. 

Source (you should point out proofs of your report, please give us some source): 
Wrath of the Lich King Patch 3.3.0 (2009-12-08): This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target.

**Comment by Semper-Numquam** [comment]
This bug extends to other procs like Clearcasting and Arcane Potency.

Clearcasting: It procs and consumes itself frequently on the same spell if it is a multistrike. For example, Blizzard ticks will proc it AND expend it constantly, while it should remain on you until NEXT cast.

Arcane Potency: gets constantly procced and consumed per spell hit, but it should be on cast. This causes one proc to be spent on a single missile of the arcane missile barrage for example, clearly wasting it's damage value

**Comment by Nuy** [comment]
There should be a delay though befor the FoF stack is consumed, otherwise it won't be possible to do combos with 1 FoF stack what wouldn't be correct.

**Comment by ShanKanis** [comment]
Still not working properly. :(

**Comment by Nuy** [comment]
Gona ever fix it Sunwello?
