### ISSUE TITLE
Quest The Delicate Sound of Thunder [Howling Fjord] Elevator stucking problem

### ISSUE THREAD

**Issue by rattleroneseven** [SunwellTracker/issues#790]
Decription: 
The quest is to equip a suit and enter a cave. Upon entering the cave the mobs in it are phasing (for a lack of a better word), like appearing and disappearing while i pass them by. At certain point, when i almost reach the tent inside, i get teleported to a wierd postion where elevator will be going thru me up and down (all the while remaining in the quest suit). Auto-unstuck feature doesnt work, in both cases i was unstuck my a GM.

How it works: 
The quest is to equip a suit and enter a cave. Upon entering the cave the mobs in it are phasing (for a lack of a better word), like appearing and disappearing while i pass them by. At certain point, when i almost reach the tent inside, i get teleported to a wierd postion where elevator will be going thru me up and down (all the while remaining in the quest suit). Auto-unstuck feature doesnt work, in both cases i was unstuck my a GM.

I think it will be easy to reproduce by just attempting to complete the quest. I had the exact same result in both cases.

How it should work: 
'Objective completed' should appear further down the cave.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/192
