### ISSUE TITLE
[NPC] Omor the Unscarred

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#791]
Decription: Omor doesn't always "summon" you back after throwing in the air

How it works: usually he does, but it's possible that you're thrown out of the platform instead. Then, you're out of the dungeon and cannot loot neither blues nor the quest item.

How it should work: Omor should always "summon" you back after throwing in the air

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/npc=17308/omor-the-unscarred#comments:id=20949

**Comment by Dootz** [comment]
Will be fixed with next server update
