### ISSUE TITLE
Warbringer

### ISSUE THREAD

**Issue by Kalysia** [SunwellTracker/issues#792]
Decription: 
Bug with The Protection Warrior Talent Warbringer

How it works: 
U cant use Intercept while in Defensive Stance

How it should work: 
Your Charge, Intercept and Intervene abilities are now usable while in combat and in any stance. In addition, your Intervene ability will remove all Movement impairing effects.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Warbringer_(warrior_talent)

**Comment by Azathothh** [comment]
Had no problems with using intercept while in defensive stance. Everything seem to work like it should
