### ISSUE TITLE
Mutanus the Devourer boss adds event not working properly

### ISSUE THREAD

**Issue by Jdavidlol** [SunwellTracker/issues#793]
Decription: The player works with Naralex to fight to Mutanus' lair and eventually defeat the boss. Waves of adds summon before mutanus and the group must fight them together. However, the spawn timer on the waves is actually too fast.

How it works: Waves spawn on top of eachother, with maybe 10 seconds before each wave.

How it should work: A wave shows up, you clear it, and then another wave spawns.

Source (you should point out proofs of your report, please give us some source): http://wowwiki.wikia.com/wiki/Mutanus_the_Devourer

The concept of "waves" is that that come one after another, not on top of one another.

**Comment by Hahecz** [comment]
proof: https://www.youtube.com/watch?v=l7EvpuSFCsU
waves in the video are released at much higher intervals than in sunwell

**Comment by Dootz** [comment]
should be fine now
