### ISSUE TITLE
[Warrior] Battle/ Commanding Shout

### ISSUE THREAD

**Issue by Ambertank** [SunwellTracker/issues#796]
Description: 
Podczas każdej bitwy o Wintergrasp, czy też któregokolwiek battleground'a  po śmierci postacie odradzają się na cmentarzu. Po odrodzeniu każda klasa otrzymuje 5 sekundowy buffy, który zmniejsza koszt wszystkich spelli o 100%. Dzięki temu każda klasa może rzucić buffy i dalej walczyć o chwałę swojej frakcji. Jednak żaden wojownik  w taki sposób tego nie uczyni. Do użycia Battle/Commanding Shout'a nadal potrzebna jest pewna ilość rage'u (w tym przypadku 10). Jest to dosyć denerwujący mankament grania BG, bo tracę cd generujący Rage na buffa.

How it works: 
Nie można użyć shout'ów  na bg po śmierci z buffem dającym 100-procentową redukcję kosztu spell'a. Przy posiadaniu odpowiedniej ilości RAGE jest to możliwe, ale nadal koszt jest ten sam.

How it should work: 
Po śmierci   na wg/bg   Battle shout/ comanding shout powinien być spellem darmowym, tj. nie powinien mieć żadnego kosztu przez pierwsze 5 sekund. Jest to sytuacja analogiczna do innych klas, które mają koszt spelli obniżony o 100%.
![wowscrnshot_030518_113623](https://user-images.githubusercontent.com/37082360/36991999-cd188d10-20a9-11e8-8b8b-6c7e7d14fa59.jpg)

Source (you should point out proofs of your report, please give us some source):

**Comment by knasen88** [comment]
since you conveniently left out sources, i'll provide some that say it infact is not bugged.

https://db.darkwizard.pl/?spell=44535

http://www.wowhead.com/spell=44535/spirit-heal#comments

Apply Aura: Mod Power Cost School Percent (Holy, Fire, Nature, Frost, Shadow, Arcane) [127]
Value: -100

physical spells do not apply, despite what the tooltip says

**Comment by set-theorist** [comment]
This report is invalid:
https://www.mmo-champion.com/threads/746862-Spirit-heal
