### ISSUE TITLE
Bugged patrol in Howling fjord

### ISSUE THREAD

**Issue by Chelseakiko3** [SunwellTracker/issues#797]
Decription: 

There's a few human patrolling the area here and they are just standing still and doing nothing! 
How it works: 

They  are standing still 
How it should work: 

They should be patroling the area around  Westguard keep! 
here is a screenshot https://ibb.co/dZpccn
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next server update
