### ISSUE TITLE
deterrence i komendy peta.

### ISSUE THREAD

**Issue by dathremar** [SunwellTracker/issues#799]
https://github.com/SunwellTracker/issues/issues/168
Decription:
Bug dotyczy mozliwosci sterowania petem w czasie deterrence. Ktos,kto to skryptowal zle zinterpretowal ". While Deterrence is active, you cannot attack. Lasts 5 sec.".

How it works:
W czasie deterrenca nie mozna uzywac komendy pet attack (zmienic targetu, zaczac atakowac petem). Jezeli pet zostal wyslany do ataku przez wlaczeniem deterrenca, to bedzie atakowal wybrany target (akurat to dziala dobrze).

How it should work:
Deterrence nie powinien miec absolutnie zadnego wplywu na sterowanie petem (rzucanie pulapek(w tym freezing arrow),uzywanie spelli nie zadajacych DMG powinno byc mozliwe,tylko kill command i shoty nie powinny byc uzywalne - co dziala dobrze). Komendy peta powinny byc mozliwe do uzycia przez caly czas. Powinno sie moc zmieniac target peta z wlaczonym deterrencem.

Source (you should point out proofs of your report, please give us some source):
https://db.darkwizard.pl/?spell=19263 - dowodem jest sam tooltip spella, nie ma tam nic o niemoznosci sterowania petem.
http://wowwiki.wikia.com/wiki/Deterrence
http://www.wowhead.com/spell=19263/deterrence#comments coment Magnatross z patcha 5.0.1 (nie ma zadnych informacji, by ta mechanika zmenila sie miedzy wotlkiem a mopem/cata)

http://www.warcraftmovies.com/movieview.php?id=121213
okolo 9:40 - widziemy, ze pet atakuje rogala, pozniej hunter uzywa deterrenca, nastepnie slychac jak mowie na team speaku "im gonna go mage" i zmienia target peta, pet zaczyna atakowac maga.

**Comment by ujellyx** [comment]
can confirm.
