### ISSUE TITLE
Feral Charge (Cat) - Speed to reach target issue

### ISSUE THREAD

**Issue by bitterra** [SunwellTracker/issues#80]
Decription: 
The current iteration in Sunwell.pl server on Angrathar is way too slow. Feral charge (cat) takes way too long to get the target.

How it works: 
It takes too long to get the target. It is too slow. The charge must be faster.

How it should work: 
It should be much faster. Watch the video below and test it in game. 

Source (you should point out proofs of your report, please give us some source): 
https://youtu.be/EqLPKtBlOmw?t=1m8s

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
