### ISSUE TITLE
[Quest] Heated Battle quest does not work properly

### ISSUE THREAD

**Issue by relinkosed** [SunwellTracker/issues#800]
Decription: 
http://www.wowhead.com/quest=12448/heated-battle#comments

How it works: 
On the server, the mobs spawn on random locations (mostly on cliff edges around the area where they should be charging uphill) in packs of up to 12 as well as Horde warriors that are not in the proper position, 

How it should work: 
The mobs should be coming in waves from the bottom of the hill/road and charging up and facing the stationed Horde warriors. Here is how it should work 
https://youtu.be/JrkBYuHV6uw 

Source (you should point out proofs of your report, please give us some source): 
https://i.imgur.com/qM3emK9.jpg
https://i.imgur.com/AzLaoAy.jpg

**Comment by Dootz** [comment]
Will be fixed with next server update

**Comment by jubasek21** [comment]
Quest should be rewritten. The same problems as above in description right now.
