### ISSUE TITLE
[Quest] No Mere Dream

### ISSUE THREAD

**Issue by Varilll** [SunwellTracker/issues#801]
Decription:  Assist Clintar in gathering the relics

How it works: Clintar is invisible

How it should work: Clintar should not be invisible.

Source (you should point out proofs of your report, please give us some source):  I don't really think it matters on taking a screenshot of someone invisible. Not going to make a video of it though.

**Comment by Dootz** [comment]
According to GM he's there. Maybe he wasn't there because someone else started quest.

**Comment by Varilll** [comment]
The quest giver lays back down and an invisible version of himself starts doing the escort portion...

**Comment by Dootz** [comment]
will be fixed with next server update
