### ISSUE TITLE
Nightmare Vine respawn timer non-existant.

### ISSUE THREAD

**Issue by AvatarRoku112** [SunwellTracker/issues#803]
Description: I've spent about 45 minutes, on different days attempting to gather Nightmare Vine in SMV and only collected 1, to 2 plants each time. I also found 1 spawn point  for Nightmare Vine under the ground, but it's only done it once, out of the twice I've been herbing. Coords of the "bugged" Nightmare Vine : 25.35

How it works: Currently I believe how Nightmare Vine is acting on this server, it's spawning whenever the server is reset and doesn't spawn afterwards.

How it should work: Nightmare Vine is a rarer herb, but the respawn should be somewhere inbetween 30 - 1 hour.

Source : https://jira.vengeancewow.com/browse/TBC-1124
On this website I saw a similar issue drawn by players that the herb simply isn't respawning.

[Nightmare Vine ](http://db.darkwizard.pl/?object=181280)

**Comment by Dootz** [comment]
One explanation could be that they are in spawn pool with Dreaming Glory, Felweed and other Outland herbs, So it's possible that everything else spawned except Nightmare Vine. But i'll investigate more.
