### ISSUE TITLE
[Dungeon] Oculus - Mage-Lord Urom bug

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#804]
Decription: 
At first phase when [Mage-Lord Urom](https://db.darkwizard.pl/?npc=27655) disapear and summon adds one of these adds [Phantasmal Water](https://db.darkwizard.pl/?npc=27653) is not fighting at all. Just standing and waiting for death. I suppose, he is ranged mob, and must cast  frost bolt?

How it works: 
At first phase when [Mage-Lord Urom](https://db.darkwizard.pl/?npc=27655) disapear and summon adds one of these adds [Phantasmal Water](https://db.darkwizard.pl/?npc=27653) is not fighting at all. Just standing and waiting for death. I suppose, he is ranged mob, and must cast  frost bolt?

How it should work: 
 I suppose, he is ranged mob, and must cast  frost bolt

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030518_151641](https://user-images.githubusercontent.com/35955516/37015875-47303ebe-2112-11e8-8696-9ed1cddee809.jpg)

**Comment by Dootz** [comment]
should be fine now
