### ISSUE TITLE
[Quest] Meet Lieutenant Icehammer (11427)

### ISSUE THREAD

**Issue by w0lf3h** [SunwellTracker/issues#809]
Description: Accepting the quest should put you on the back of a gryphon and fly you to the completion quest giver.

How it works: No gryphon summoned. No gossip option to talk to the quest giver to summon a gryphon.

How it should work: Accepting the quest should put you on the back of a gryphon and fly you to the completion quest giver.

Source (you should point out proofs of your report, please give us some source): The quest description reads, "When you're ready I'll place you on the back of one of our gryphons and zip you right to him!"

**Comment by Dootz** [comment]
Will be fixed with next server update
