### ISSUE TITLE
[Core][Minor] Campfire radius too big

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#81]
**Decription:** 
Fire sources (like in screenshot) like cooking fire and cozy fires in inns hit for damage in a circle. When a player walks into this circle he is periodically damaged by the fire object.

**How it works:** 
The radius for damage seems to be too high.

**How it should work:** 
Radius should be small enough so that you can stand near fire and not get burned. You should only get burned if you almost STEP ONTO the fire, not if you are standing few yards away.

**Source** (you should point out proofs of your report, please give us some source): 
Hard to find sources for fire burn for WotLK but it makes gameplay sense to lower the radius.
See : https://i.imgur.com/pL2v7V8.jpg (from Angrathar showing bug)

**Comment by Afgann** [comment]
Will be fixed with next update.

**Comment by TheBigBallsOfFury** [comment]
This is still bugged for many objects. And the cooking campfire no longer burns at all. Was a good game mechanic against stealth.

Not sure whether I should open a new report or post screenshots here...
