### ISSUE TITLE
[Dungeon] The Nexus - Keristrasza

### ISSUE THREAD

**Issue by Tedrude** [SunwellTracker/issues#810]
Decription: 
Her debuff called "Intense Cold" never goes away from pet's. I've tried calling it back and running it to different places but it never loses the debuff therefor my pet dies after some seconds.

How it works: 
Intense cold never goes away from pet's (i.e my hunter pet)

How it should work: 
When you move / jump you will lose the debuff.

Source (you should point out proofs of your report, please give us some source): 
Today at 7:49:42 local time (CEST+1) we engage her, at around 7:50:11 my pet is dead.
Can't give any other source unfortunately..

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/764
