### ISSUE TITLE
[NPC] Goramosh

### ISSUE THREAD

**Issue by AsgerCode** [SunwellTracker/issues#812]
Decription: Goramosh is an hostile NPC located in Moonrest Gardens - Dragonblight

How it works: Everything works perfectly except for the fact that this mob doesn't drop anything. Probably a problem with the loot table, a simple db fix.

How it should work: This NPC should drop AT LEAST the 100% drop chance item Goramosh's Strange Device (http://db.darkwizard.pl/?item=36746) which is key in getting Kirin Tor and Wyrmrest Accord rep.

Source (you should point out proofs of your report, please give us some source): http://db.darkwizard.pl/?npc=26349#drops

**Comment by Dootz** [comment]
To get this item you need to be on specific quest. 
http://www.wowhead.com/quest=12004/prevent-the-accord
http://www.wowhead.com/item=36746/goramoshs-strange-device#comments
> It's worth to note that this item only drops if you are on the quest Prevent the Accord.
