### ISSUE TITLE
[Rogue/Druid] Stealth breaks when looting.

### ISSUE THREAD

**Issue by YaboyJimmyrustle** [SunwellTracker/issues#814]
**Decription:** 
Stealth breaks when looting npcs.

**How it works:** 
When looting creatures/mobs, stealth breaks. This was working properly up until this last week when the server updated.

**How it should work:** 
Rogues and druids should be able to loot npcs while still in stealth without it breaking.

**Source (you should point out proofs of your report, please give us some source):** 
I will be attempting to find a video before 2012 to see if rogues/druids  break stealth if they loot anything while in stealth. This section will be anecdotal for now as I believe this is an unintentional bug. I remember having the ability to loot while stealthed in retail WotLK, but again, I will search for hard evidence.

**Conditions**:

- This was discovered on a rogue and tested to confirm for both rogues and druids.
- Level 30-36 when this was occurring. However, I had a level 80 rogue attempt this and get the same result.
- In and outside of dungeons.

A simple test of this is:
1. Kill an npc/enemy
2. Ensure there is loot through visual animation
3. Stealth
4. Right-click target to attempt to loot

**Comment by TheBigBallsOfFury** [comment]
Funny that you're writing this out just as I was updating my original report of it NOT breaking while looting.

http://wowwiki.wikia.com/wiki/Stealth?oldid=2365328
Stealth breaking on looting is intentional and blizzlike all the way back from vanilla. The current implementation of the mechanic here on Sunwell is not perfect as of now, but it shouldn't be much of a problem to refine it and get it working like the other wrath servers.

You can read more here: 
https://github.com/SunwellTracker/issues/issues/702

**Comment by YaboyJimmyrustle** [comment]
I remember stealth breaking in Vanilla and TBC vividly and remember it being quite blizzlike, but I also remember being able to stealth loot in WotLK as I mained a druid and had an alt rogue so I was in and out of dungeons, leveling, etc. while stealthed. I remember being able to loot multiple mobs while still remaining stealthed and then moving on.

I don't really trust wowwiki as a sole source for WotLK mechanics, so I'll be going over patch notes and videos from 7-9 years ago. Until then I'm inclined to believe you since I have nothing to hang my claim on and it sounds like that's the intended mechanic.

**Comment by bongobg** [comment]
Looting anything from NPC to object should break stealth. I've never seen otherwise on any patch.
