### ISSUE TITLE
Visit to the doctor

### ISSUE THREAD

**Issue by Thobias89** [SunwellTracker/issues#818]
Decription:  In the "A Visit to the Doctor" quest Patches can't kill Doctor Sabnok alone (for "Help Patches kill Doctor Sabnok"-part) because he dies before, and helping doesn't work either. Also, the metal pillar for the releasing part doesn't work after doing it once.

How it works:  Freeing Patches from his metal. And no possibility to help him kill the Doctor since its not possible to target the Doctor.

How it should work:  You should be able to get "Help Patches kill Doctor Sabnok"-part of the quest done by letting Patches kill the Doctor alone. You should also be able to respawn Patches with the metal pillar after the first time.

Source (you should point out proofs of your report, please give us some source): 
Patches is not able to kill him alone.. Been abandoning the quest 3 times and redo it.. still not working

**Comment by Dootz** [comment]
> part of the quest done by letting Patches kill the Doctor alone
I'm not sure about this part. As you can see for example here https://youtu.be/lFoYeNn_fpk?t=1m12s Patches is taking massive damage from doctor and will most likely die without help. So probably the most important thing here is report that Doctor is not targetable, and that you can't repawn Patches.

**Comment by Thobias89** [comment]
Well i am reporting that the doctor aint targetable...
"How it works: Freeing Patches from his metal. And no possibility to help him kill the Doctor since its not possible to target the Doctor."

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/829
