### ISSUE TITLE
[Quest] The Missing Diplomat (Part 11)

### ISSUE THREAD

**Issue by georgeapostolov** [SunwellTracker/issues#819]
Decription: 
The quest is in Menethil Harbor Inn (Wetlands).

How it works: 
I take the quest, NPC is in stealth mode near the inn. Can't be attacked.+

How it should work: 
After accepting the quest, Tapoke "Slim" Jahn should be in front of the Inn and be attackable, so I can finish the quest.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=1249/the-missing-diplomat

![wowscrnshot_030818_000001](https://user-images.githubusercontent.com/5627962/37120666-b1ff76cc-2263-11e8-9a8b-7e4f81e3b468.jpg)

**Comment by georgeapostolov** [comment]
There was a server restart and the quest is working now. He went outside with 1 bodyguard and i killed them.

**Comment by rouginek** [comment]
mind if i ask, what is your quest tracking addon?

**Comment by georgeapostolov** [comment]
Addon is called Carbonite
