### ISSUE TITLE
[Priest] Dispel Magic (Rank 2) only dispelling one debuff/buff

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#82]
Decription: 
As the title says, the Rank 2 Spell of Priest is currently bugged.

How it works: 
It only dispels one beneficiary buff from enemies and one debuff from friendly targets.

How it should work: 
As the tooltip says it should remove two of each.

Source (you should point out proofs of your report, please give us some source): 
See spell-tooltip.
Spell-ID should be 988.

**Comment by DemaciaMaggotPie** [comment]
I've seen that happening too, 100% reproduction rate.

**Comment by Semper-Numquam** [comment]
It is not 100%. It mainly happens when the target has many of the same kind of debuff (for example, many mobs casting SW:Pain on someone and when priest tries to dispel it only takes one off). When the debuffs are different, it does dispel two.

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
