### ISSUE TITLE
Mounting should not cancel Moonkin Form

### ISSUE THREAD

**Issue by strawburry12** [SunwellTracker/issues#821]
Decription: Title.

How it works: When you mount, it should not cancel Moonkin Form

How it should work: Mounting doesn't cancel Moonkin Form

Source (you should point out proofs of your report, please give us some source):

**Comment by Brennan11** [comment]
Moonkin cant mount in wotlk. Source: eyewitness and https://us.battle.net/forums/en/wow/topic/1127484616
