### ISSUE TITLE
Drops in heroic dungeons

### ISSUE THREAD

**Issue by sheerbits** [SunwellTracker/issues#823]
Decription: Heroic dungeons should be dropping higher level blues (rare drop)

How it works: Heroic dungeons offer better random drops specific to that dungeon. Normal dungeons offer loot for that level.

How it should work: Heroics will drop the lower level loot, and some of the higher level loot (dark runic mantle) is preposterously rare. Some are almost unheard of... dark runic mantle.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/454
