### ISSUE TITLE
Pattern: Fur Lining - Arcane Resist

### ISSUE THREAD

**Issue by iyasenai** [SunwellTracker/issues#824]
Decription: The item ID 44563 that belongs to the NPC 32297 is not available at this moment, the item is available to players since version 3.0.3.9183

How it works: The NPC 32297 must drop the item

How it should work: The NPC 32297 should have the probability of dropping the item

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=32297/cult-researcher#drops
http://wowwiki.wikia.com/wiki/Fur_Lining_-_Arcane_Resist
https://wow.gamepedia.com/Fur_Lining_-_Arcane_Resist

**Comment by Dootz** [comment]
Will be fixed with next server update
