### ISSUE TITLE
[NPC][Spell] Faerie Fire from mobs do not disable stealth

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#825]
Decription: 
Faerie Fire from mobs do not disable stealth. Rogue can still use stealth while affected by Faerie Fire debuff.

How it works: 
Faerie Fire from mobs do not disable stealth. Tested using Highvale Ranger (2694) in Hinterlands.

How it should work: 
Faerie Fire from mobs should remove the ability for Rogues and Druids to use Stealth or turn invisible using potions.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Faerie_Fire?oldid=1870824

**Comment by Azathothh** [comment]
Fixed. Will be updated on Angrathar/Feronis soon.
