### ISSUE TITLE
Spellpenetration not working.

### ISSUE THREAD

**Issue by tockerer** [SunwellTracker/issues#828]
Decription: 
Spell pen not working (at all?)  i see partial resists on me (i have 0 in all resistances) and on other targets that have way less resistance than my current spell pen. (for example if i have 95 spell pen and cast at targets with 50 resistances i should see 0 partial resists what so ever, but i do.) 

multiple tests have been done with multiple classes/spells.  got the same result every time.

How it works: 
Partial resists on 50%ish  spells recieved and cast. 
(not 50% of the dmg , but 50% frequency, the amount resisted if approx 10% of the dmging spell's dmg) 
This happens regardless of my current spell pen and/or the targets resistances.
 This for example  --> "300 dmg taken from Serpent Sting (30 resisted) "

How it should work: 
if my current spell penetration is higher than the target im casting at there should be no partial resists at all.
This for example --> "330 dmg taken from Serpent Sting"

Source (you should point out proofs of your report, please give us some source):

**Comment by Semper-Numquam** [comment]
Spell Penetration seems to work but there's a bug where players and NPCs get base resistances for no reason. Already explained and reported here #775
