### ISSUE TITLE
A visit to the doctor

### ISSUE THREAD

**Issue by Thobias89** [SunwellTracker/issues#829]
Decription: In the "A Visit to the Doctor" quest Patches can't kill Doctor Sabnok alone (for "Help Patches kill Doctor Sabnok"-part) because he dies before

How it works: The doctor is not targetable.

How it should work: You should be able to target the Doctor so u actually can help Patches kill him.

Source (you should point out proofs of your report, please give us some source):   https://youtu.be/lFoYeNn_fpk?t=1m12s here u can see the player switching targets.. Thats not possible on Angrathar.

**Comment by Dootz** [comment]
will be fixed with next server update
