### ISSUE TITLE
Herbing node spawns inside a tree, unlootable

### ISSUE THREAD

**Issue by dinkmaster** [SunwellTracker/issues#83]
Decription: 

Herbing node spawns inside a tree, unlootable
How it works: 
Herbing node spawns inside a tree, unlootable

How it should work: 
It should spawn next to the tree and be in looting range

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_013118_120955](https://user-images.githubusercontent.com/11167726/35622491-ecfafd1e-067f-11e8-9a64-e221abe2f08b.jpg)

**Comment by dinkmaster** [comment]
Location is at the Kurzen's Compound in stranglethorn vale, coords are 43.6, 11.5
![wowscrnshot_013118_121243](https://user-images.githubusercontent.com/11167726/35622558-28fc73c4-0680-11e8-9865-77582198562b.jpg)

**Comment by Dootz** [comment]
Will be fixed with next server update
