### ISSUE TITLE
[Warrior]Deep Wounds

### ISSUE THREAD

**Issue by splank96** [SunwellTracker/issues#830]
Decription: 
The damage from warriors talent "Deep Wounds" isnt affected by resilience or any other dmg reduce effect.
And the Base dmg is to High. 3,4k gs Warriors can stack that talent to 1300dmg per tick. On retail with Shadowmourne warrior i got that wounds on 1400dmg per tick in pve.
Quote:
PATCH 3.3.3: The damage from this talent is now affected by resilience as intended.
helping source:
http://wowwiki.wikia.com/wiki/Deep_Wounds

How it works: 
Deep wounds arent effected by resilience or for expample painsub, dispersion, shadowform, shieldwall and all other things. So in Dispersion (90% dmg reduce) it does every 1 sec 600 dmg+.

How it should work: 
That talent should do less dmg + should be affected by resilience and other dmg reduce effects.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Deep_Wounds
There you can see the fact that it should be affected by resilience. Cant find a source about that it should do less dmg but there is something wrong when warriors do the most dmg with deepwounds in a whole bossfight and if the wounds do the same dmg as a 6.8k gs warrior with shadowmourne.
 Pls analyse that talent with dev team 
:)

**Comment by Semper-Numquam** [comment]
Deep wounds is currently ignoring all damage modifiers. I tested with Resilence gear on/off and with Pain Supression and Dispersion. Every time the ticks were the same damage.

**Comment by dathremar** [comment]
Dunno about resilence, but other damage reduction modifiers should not affect deep wounds.
Proof:
https://www.youtube.com/watch?v=5TikZIvK2so
8:18 - deep wounds tick for 519, then enemy warrior pops shield wall, next deep wounds tick is 519 despite shield wall on. 

Hunter's piercing shots (same case with ret's righteous vengeance i think) are supposed to work the same way when it comes to damage reduction effect  - althought PS/RV are calculated from damage done by ability that has just landed on the target, so i guess resilence should not affect its damage (it would end up in doubled reduction). 
However, Deep wounds damage is calculated from melle damage (http://wowwiki.wikia.com/wiki/Weapon_damage) so resilence probably should affect it.

**Comment by splank96** [comment]
It should be affected by resilience. Look at the link i posted.
And that video you linked is from 2016. So its no quality source. Why should that wound do not be affected by dmg reduce effects if its not clearly explained in the Talent.

**Comment by dathremar** [comment]
I suppose u are right about the resilence (its literally stated in patch notes that it should be affected by resilence lel )
The video I linked was just a youtube mirror of retail wotlk video:
http://www.warcraftmovies.com/movieview.php?id=152529  
first comment was posted on 10-05-22 18:01
Other damage reduction effect should work only before warrior puts deep wounds on his target.
 e.g
priest uses PS, warrior crits him, deep wounds tick for 60% dmg
warrior crits priest, pri uses PS, deep wounds tick for full dmg
