### ISSUE TITLE
Deeprun Tram

### ISSUE THREAD

**Issue by psychazia** [SunwellTracker/issues#831]
Decription: 
https://db.darkwizard.pl/?quest=6661
The quest in the tram is bugged, 

How it works: 
all the rat are already enthralled (https://db.darkwizard.pl/?npc=13017)
Seems like they don't turn bag to their original form (https://db.darkwizard.pl/?npc=13016)
So the quest can't be complete because of invalid target

How it should work: 
The enthralled rat follow you and they disappear when you complete the quest or when you leave the instance, the original rat repop the others can complete the quest

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
