### ISSUE TITLE
[NPC Behavior] Mobs aggro instantly on respawn instead of waiting 5 seconds.

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#832]
Decription: 
When mobs spawn, or respawn after being killed, they instantly aggro an enemy in the aggro radius immediately after spawning.

How it works: 
Mobs instantly aggro after spawning.

How it should work: 
Mobs should wait around 5 seconds before aggroing player, allowing enough time to move out of aggro radius if spawn right on top of player.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Spawn?oldid=2244434

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
