### ISSUE TITLE
Weekly q

### ISSUE THREAD

**Issue by Sunwellxd** [SunwellTracker/issues#833]
Decription: 
W poprzednim tygodniu oraz obecnym po wykonaniu wq, nastepnego dnia pojawia sie kolejny.
W tym tyg zrobilem wczoraj q na Lorda w ToC,dzisiaj moge zrobic na  Notha w Naxxie

How it works: 
Od momentu otwarcia ICC kazdego tygodnia weekly q dubluja sie

How it should work: 
Powinien byc dostepny tylko jeden weekly q

Source (you should point out proofs of your report, please give us some source):

**Comment by neology95** [comment]
a to sprzedawczyk jeden :D

**Comment by Sunwellxd** [comment]
a to kogo sprzedalem? bug to bug
