### ISSUE TITLE
Pets Mana Before Arena Starts

### ISSUE THREAD

**Issue by moonsado** [SunwellTracker/issues#835]
Decription: Buffs on my pet (for example arcane brilliance) increases my pet's mana but she doesn't regenerate her mana before the arena starts So she will have something like 6000/7200 mana.

How it works: My pet has around 6000/6000 mana when she gets buffed by my mage friend before arena starts she has 6000/7200+ and does not regain her mana or does VERY SLOWLY. Before arena starts all pets and players should have their maximum possible stats.

How it should work: Before arena starts all pets and players should have their maximum possible stats.

Source (you should point out proofs of your report, please give us some source):

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
