### ISSUE TITLE
[Objects] [UI] Objects that end quests do not close quest info panel when clicking 'Complete Quest '.

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#838]
Decription: 
Objects like scrolls, crates, corpses that are part of quest chains and have a (?) on them **do not close** the quest info panel when clicking 'Complete Quest'.

How it works:
After clicking 'Complete Quest', quest credit is given, but next quest is not displayed. You have to manually press ESC or click the [X] on the quest window to close it and click the object again to accept the next quest.

How it should work: 
After clicking 'Complete', the quest info panel for the current quest should close and next quest in chain should automatically be displayed.

Source (you should point out proofs of your report, please give us some source):

**Comment by TSSchoof** [comment]
Can confirm. Happens every time.
