### ISSUE TITLE
[Quest] Among the champions

### ISSUE THREAD

**Issue by xxxkowal** [SunwellTracker/issues#839]
Decription: 
Quest w Argent Tournament, rozchodzi się o skill "Charge", dodatkowo "Exodar Champion" baaardzo wolno chodzi w przeciwieństwie do pozostałych championów

How it works: 
Będąc na wierzchowcu (obojętnie jakim) używając skill "Charge" na jakiekolwiek czepiona nie zawsze zadaje obrażenia co jest mega irytujące

How it should work: 
Każdy skill "Charge" powinien zadawać obrażenia

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=s7_vZJOmcOE

**Ps. Żeby nie zakładając drugiego tematu do questa "Battle before the Citadel" nie trzeba mieć założonej Lancy (np. Argent Lance) żeby wsiąść na wierzchowca.... a powinno się ją mieć założoną**

**Comment by Dootz** [comment]
Zgodzę się że Exodar champion chodzi wolno. O połowę wolniej niż inne. Zostanie to poprawione. Natomiast nie jestem w stanie odtworzyć sytuacji z brakiem obrażeń z Charge. Wydaje mi się że po prostu uderzasz szarżą w momencie gdy NPC ma 3 stacki tarczy. Wtedy obrażenia zadane nie są duże (ale są) i nie widać po pasku zdrowia żeby mu coś zeszło za bardzo.
