### ISSUE TITLE
Skining dosent work if im in group

### ISSUE THREAD

**Issue by aquila22** [SunwellTracker/issues#84]
Decription: Skining wont work if im in a group but works if i leave the group.
Even after i set loot free for all it still dosent work

How it works: 
It dose not alow me to skin it say the mob needs to be looted even after i loot the mob

How it should work: 
It should give me the option to skin after i loot the body

Source (you should point out proofs of your report, please give us some source):

**Comment by artemmavrich** [comment]
Maybe there was a quest items in mobs, that you can't see even if  free for all loot option.

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
