### ISSUE TITLE
Quest: A Bear of an Appetite

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#840]
Decription: 
[A Bear of an Appetite](https://db.darkwizard.pl/?quest=12279#?ref=sunwell.pl) can be completed using quest item in the same school a lot of times without cd

How it works: 
[A Bear of an Appetite](https://db.darkwizard.pl/?quest=12279#?ref=sunwell.pl) can be completed using quest item in the same school a lot of times without cd

How it should work: 
School must disapear after catching

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030918_154046](https://user-images.githubusercontent.com/35955516/37210287-d4eac490-23b0-11e8-9dd3-37ac62e3b701.jpg)
![wowscrnshot_030918_154050](https://user-images.githubusercontent.com/35955516/37210296-de581b68-23b0-11e8-9b88-c28df3db3bd2.jpg)

**Comment by Dootz** [comment]
Will be fixed with next server update

**Comment by rouginek** [comment]
now, it does not spawn at all, the schools

**Comment by Dootz** [comment]
there are 18 spawn points and they should respawn every 5 minutes. But I'll check that

**Comment by TariqPrst** [comment]
None of the spawn points are working, stood in 1 point for 15 minutes, nothing happened, and as I said, none is spawned.

**Comment by Dootz** [comment]
you're right. Sorry for that. It'll be fixed with next server update.

**Comment by wubadubwub** [comment]
still not fixed.

**Comment by artemmavrich** [comment]
Same problem with quest [The Way to His Heart...](https://db.darkwizard.pl/?quest=11472)

**Comment by rouginek** [comment]
Can't confirm with [https://db.darkwizard.pl/?quest=11472](url) did it today

**Comment by Dootz** [comment]
will be fixed with next server update
