### ISSUE TITLE
[Quest][PvP] Call to Arms-quests wrong rewards.

### ISSUE THREAD

**Issue by ujellyx** [SunwellTracker/issues#841]
Decription: 
The "Call to Arms" quests reward the wrong amount of Honor / Arena Points.
![calltoarms](https://user-images.githubusercontent.com/17804807/37211350-f2341178-23ab-11e8-9408-fe3af527a6ea.png)

How it works: 
Right now they reward 2482 Honor Points.

How it should work: 
They should reward 3720 Honor and 25 Arena Points - the same amount of a CTA win.

Source (you should point out proofs of your report, please give us some source): 
http://us.battle.net/wow/en/game/patch-notes/3-3-3
"Winning a Call to Arms Battleground for the first time in a day will award players with 30 Honorable Kills worth of additional Honor currency and 25 Arena points."
1 HK = 124 Honor Points

**Comment by Dootz** [comment]
will be fixed with next server update
