### ISSUE TITLE
NPC Surveyor Orlond

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#843]
Decription: 
[Surveyor Orlond](https://db.darkwizard.pl/?npc=26514#?ref=sunwell.pl) Must be dead and lie on the floor. Instead of it - he is standing but he is dead.

How it works: 
[Surveyor Orlond](https://db.darkwizard.pl/?npc=26514#?ref=sunwell.pl) Must be dead and lie on the floor. Instead of it - he is standing but he is dead.

How it should work: 
Corpse must lie on the floor

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030918_165454](https://user-images.githubusercontent.com/35955516/37213741-9ad11ec0-23bb-11e8-9f2b-c3cd5a2b7628.jpg)

**Comment by Dootz** [comment]
Will be fixed with next server update
