### ISSUE TITLE
[Quest] Warding the Walls.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#845]
Decription: Its Wintergrasp's Weekly Quest, rng choose one per week, but if you hold all of them, you can share and do all in week. I can share shadow, fire, nature, but i cant share water element quest.

How it works: Quest cant be shared to others.

How it should work: Quest should be able to share.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=13192/warding-the-walls

**Comment by Dootz** [comment]
That's intentional and won't be changed. Currently only active quest (1) can be shared from group of:
- Fueling the Demolishers
- Healing with Roses
- Bones and Arrows
- Warding the Walls
