### ISSUE TITLE
[Paladin] Can't use Hand of Freedom while in Freezing Trap

### ISSUE THREAD

**Issue by Nikespbb** [SunwellTracker/issues#846]
Decription: 
Found a bug, that you can't use Hand of Freedom (http://db.darkwizard.pl/?spell=1044) while affected the effect of Freezing Trap (http://db.darkwizard.pl/?spell=1499)

How it works: 
While you are in the Freezing Trap and trying to use Hand of Freedom on ally or even yourself, it says "Can't use while stunned"'' or something like that.

How it should work: 
You should be able to cast Hand of Freedom while You standing in Freezing Trap. It shoudn't remove freeze effect, when casting on yourself, but should able to cast. Before 3.2.2 you btw can cast BoF even in Cyclone.

Source (you should point out proofs of your report, please give us some source):   If it can be a proof - I find a post from May 2010 on ArenaJunkies about that - http://www.arenajunkies.com/topic/133296-freedombop-while-stunned/ Also, I'm posting this bug, because I played on retail wotlk, and was confused, when I step in Trap on Anghrathar and can't give freedom to my teammate lol. Thank you.

**Comment by Nikespbb** [comment]
Last WG shows me, that I can't use HoF even while standing in Repentance (http://db.darkwizard.pl/?spell=20066), I'm wondering, that it works fine with Sap, because Repentance and Sap debuffs has same mechanics (I think so).
How it should work: 
Paladin should be able to cast Hand of Freedom while affected by "sleepeng\frozen\stun effects": Freezing Trap, Repentance, Gouge, Sap, Wyvern Sting, etc
Paladin should not be able to cast Hand of Freedom while in Poly, Hex, Cyclone (after 3.3.0 patch), Fear, etc
I'm spending a lot of time now to find strong proofs of this, but it's too hard to find a video with moment when paladin using HoF under CC from 9 years ago =( I just "have a picture" in my mind, where I'm using HoF on myself after stepping, at Hunter's trap or when paladin using Repentance and "Paladins reflex" thinks that it's stun, trying to get out of this through Ret talent, and standing with that shiny effect, watching his ROFL face xD. When you are a new player (as I was in 2008), you trying to "Freedom with ret talent" any CC, that goes to you. 
But I find something useful:
-Here is discussion of the same issue from another wotlk project. There, HoF can't be used even in Sap, before it fixed : https://github.com/trinitycore/trinitycore/issues/7206 Also there you can find some minor proofs.
-Here in Patch changes section you can find a proof, that HoF was changed, and can't be used under druids Cyclone after 3.3.0: http://wowwiki.wikia.com/wiki/Hand_of_Freedom
I will try to find something more later. Hope, this bug take your attention. Thank you.

**Comment by Valmere** [comment]
Hand of Freedom is a cast-on-target spell, the same as any of the other Hand spells or spells in general. It, along with all the others, should not be usable while under the effects of a crowd control such as sap, sleep, or cyclone. Paladins may bubble out of those effects as bubble is a localized ability that targets only the paladin.

If Hand of Freedom worked during a crowd control spell in retail then it was an overlooked bug that only further made the paladin class overpowered.

**Comment by Nikespbb** [comment]
https://youtu.be/pS_1d7X2GHM?t=7m40s
7:42: our pala using Repentance on Holy pala
Now watch target (Warrior) buffs
7:44: Holy pal giving HoF to warrior
7:48: Repentance ends
Trying to find more proofs  HoF should be working under Gauge, Wywern Sting, Freeze trap, etc.

**Comment by Azathothh** [comment]
Fixed. Will be updated on Angrathar/Feronis soon.
