### ISSUE TITLE
Quest: Put on Your Best Face for Loken

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#847]
Decription: 
In quest [Put on Your Best Face for Loken](https://db.darkwizard.pl/?quest=12185#?ref=sunwell.pl) npc [Image of Loken](https://db.darkwizard.pl/?npc=27212) must not be hostile

How it works: 
In quest [Put on Your Best Face for Loken](https://db.darkwizard.pl/?quest=12185#?ref=sunwell.pl) npc [Image of Loken](https://db.darkwizard.pl/?npc=27212) must not be hostile

How it should work: 
In quest [Put on Your Best Face for Loken](https://db.darkwizard.pl/?quest=12185#?ref=sunwell.pl) npc [Image of Loken](https://db.darkwizard.pl/?npc=27212) must not be hostile

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_030918_184222](https://user-images.githubusercontent.com/35955516/37219051-f94bd6c0-23ca-11e8-9bd7-3c91970a5ee5.jpg)

**Comment by Dootz** [comment]
Will be fixed with next server update
