### ISSUE TITLE
 [Reflective Shield] causes threat it seems

### ISSUE THREAD

**Issue by Winterkorn** [SunwellTracker/issues#848]
Decription: 
The second I took the talent in the Disc tree, mobs startet to chaise me forever when I have the shield on. They did not do that before I took the the talent.

How it works: 
Causes threat

How it should work: 
Should not cause threat

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
I've conducted some tests and it feels the same with and without this talent.
