### ISSUE TITLE
Relentless Earthsiege Diamond not working

### ISSUE THREAD

**Issue by 1438902566** [SunwellTracker/issues#849]
Decription: 
   When a red, yellow and blue gemstone has been inserted，Relentless Earthsiege Diamond(http://db.darkwizard.pl/?item=41398) did not go into effect，21 agility and 3% crit damage not working

How it works: 
   When you are equipped with one each of red, yellow and blue gems, this colorful should have a bonus of 21 agility and 3% crit damage.

How it should work: 
    I already have erfect Delicate Bloodstone(http://db.darkwizard.pl/?item=41434), Balanced Twilight Opal(http://db.darkwizard.pl/?item=40029),Perfect Glinting Huge Citrine(http://db.darkwizard.pl/?item=41491),Relentless Earthsiege Diamond should give me 21 agility and 3% crit damage
    But through my uploaded picture，I have 734 agility before activating the effect，when I put on my feet(my feet are 49 agile, Druid talent has an 8% bonus, so it should be 53 Agility.)activate a colorful effect， I should have 734 plus 53 plus 21 Agility provided by Relentless Earthsiege Diamond, it should be 808 Agility，but I'm actually only 787 agile, 21 agility provided by Relentless Earthsiege Diamond did not work. as for 3% crit damage, I didn't verify it, but I guess it's also not working
    

![this is when the effect is not activated](https://user-images.githubusercontent.com/37223195/37224256-e37b4310-240d-11e8-9646-bd15f109e4e6.png)
![this is when the effect is not activated 2](https://user-images.githubusercontent.com/37223195/37224265-ebc45b6a-240d-11e8-8da7-31c24c183dcd.png)
![this is my feet](https://user-images.githubusercontent.com/37223195/37224281-f45d1e42-240d-11e8-911a-2dd32b1593ad.png)
![this is the time of activation](https://user-images.githubusercontent.com/37223195/37224290-f9763422-240d-11e8-8f26-ffdf35e96892.png)
![this is the time of activation 2](https://user-images.githubusercontent.com/37223195/37224295-fde5e106-240d-11e8-9c02-275097ba6a78.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by set-theorist** [comment]
Did you forget to equip your item with the balanced twilight opal? Don't see it anywhere in the screenshots.

**Comment by MrTide** [comment]
Hello i believe he had one purple .one orange and one red gem

**Comment by ujellyx** [comment]
For me this meta activates just fine.
