### ISSUE TITLE
[Quest]Feeding Arngrim

### ISSUE THREAD

**Issue by Avarishd** [SunwellTracker/issues#851]
Decription: Sometimes the turned NPCs despawn without any apparent reason.

How it works: After you use the quest item on Roaming Jormungar there is chance that it simply despawn without any reason.

How it should work: The only way the mobs can despawn is when they are forced to 15% hp (or whatever the threshold is).

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Will be fixed with next server update
