### ISSUE TITLE
[Quest-Take Five Bases] Brak tabarda za wykonanie tego questa

### ISSUE THREAD

**Issue by s00lar** [SunwellTracker/issues#852]
Decription: 
Jest to quest za przejęcie 5 baz na battlegroundzie Arathi Basin: https://db.darkwizard.pl/?quest=8122

How it works: 
Quest daje złe nagrody za jego wykonanie - brak tabardu.

How it should work: 
Powinno się otrzymywać tabard https://db.darkwizard.pl/?item=20131 którego nie otrzymałem.

Source (you should point out proofs of your report, please give us some source): 
Według strony darkwizard: https://db.darkwizard.pl/?quest=8122 tabard otrzymuje się za ten quest. Według wowwiki również: http://wowwiki.wikia.com/wiki/Battle_Tabard_of_the_Defilers . Gamepedia mówi to samo: https://wow.gamepedia.com/Battle_Tabard_of_the_Defilers .

Pozostałe linki z dowodem:
http://wow-mania.com/armory/?item=20131
http://wow.gamepressure.com/item.asp?ID=11299
https://db.linebr.com/woltlk/?item=20131

**Comment by Dootz** [comment]
Jesteś pewny że zrobiłeś quest na przejęcie 5 baz a nie 4? Quest na przejęcie 5 baz dostępny jest od poziomu Exalted reputacji z the Defilers i jak widać na dołączonych screen shotach za niego oferowany jest tabard.
![wowscrnshot_031018_145350](https://user-images.githubusercontent.com/25490436/37243029-33ce7304-2473-11e8-8f88-a25344cb4dda.jpg)
![wowscrnshot_031018_145421](https://user-images.githubusercontent.com/25490436/37243032-3a9e7d6e-2473-11e8-8729-a95d5a103947.jpg)

**Comment by s00lar** [comment]
Aaaaa, faktycznie :) Dzięki, mój błąd. Myślałem że nie trzeba do tego reputacji. Wybaczcie za kłopot.
