### ISSUE TITLE
Oh Novos! achievement not working

### ISSUE THREAD

**Issue by Vinklad** [SunwellTracker/issues#853]
Decription: 
We are attempting to do the achievement [Oh Novos!] and it is currently not working, the group is not getting awarded for completing the achievement.

How it works: 
We are killing all the zombies at the top of the stair to prevent them from ever coming close to the floor, if none of the adds touch the floor the group will get the achievement.

How it should work: 
Currently, stacking at the top of the stairs and killing all the zombies before they reach the stairs (including the summoners) does not grant the achievement [Oh Novos!]

Source (you should point out proofs of your report, please give us some source): 
I honestly don't know how I am supposed to provide a source on this, I have done it on my warrior and so I know how to do it and now it has not worked for my mages the last three tries.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/631

**Comment by Vinklad** [comment]
Sure, this might be a duplicate but the other one was 17 days ago and it has not been fixed and that one is "closed"
