### ISSUE TITLE
OUTLAND ponizej 58 lvlu

### ISSUE THREAD

**Issue by sobanejroo** [SunwellTracker/issues#854]
Decription:  Możliwość wejscia na Outland prawdopodobnie już od 1 lvla. Sprawdzone na 54 lvlu

How it works:  Portal maga do Shattrath City oraz Portal w dalaran nie mają wymogów lvl'owych co umozliwia dostania sie na outland nawet na 1 lvl.

How it should work: Wszystkie portale i przejścia do Outland powinny miec wymóg 58 lvl'a.

Source (you should point out proofs of your report, please give us some source):  https://prnt.sc/ipaeov  https://prnt.sc/ipaer3

**Comment by Riztazz** [comment]
To nie jest bug, tak ma byc
