### ISSUE TITLE
Constantly spam muted

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#856]
Decription: 
Sometimes I get constantly spam muted until i relog several times, I've made several tickets with responses saying it's my addons but since I've then tried replacing all addons and now even DISABLING all of them there must be an issue on your end.
No i don't use carbonite stop asking me to disable it.
And I'm not alone on this, most people in my guild experience it.
How it works: 
https://streamable.com/0z1qd

How it should work: 
I shouldn't get spam muted when doing absolutely NOTHING, i get this while AFKING Only solution is to relog, sometimes several times

Source (you should point out proofs of your report, please give us some source):

**Comment by ice-92** [comment]
Try downloading Fubar and Fubar_AddonSpamFu. It will show you which addons, and how much they communicate with other addons aka spam.

**Comment by knasen88** [comment]
Thank you, I will try it out
