### ISSUE TITLE
[Quest]Appeasing the Great Rain Stone

### ISSUE THREAD

**Issue by Avarishd** [SunwellTracker/issues#857]
Decription: The "spark" that represents the location of there Lafoo should dig takes too much time to respawn. I digged the same spot more than 3 times before the spark even spawned once.

How it works: The glowing area(spark) represents where the "diggable" spots are. But they take too much time (more than 15m for sure). While the average respawn time for a spot that can digged is like 4min.  (From personal test)

How it should work: After the 4min (or whatever the respawn time of the spots that can be digged) is met the glowing(spark) should respawn.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
they respawn every 5 minutes but they are not visible all the time.

**Comment by Avarishd** [comment]
Was pretty close then :D

**Comment by Dootz** [comment]
Will be fixed with next server update
