### ISSUE TITLE
Tidal Waves Resto shamana 45 talent

### ISSUE THREAD

**Issue by Rethik64** [SunwellTracker/issues#858]
Decription: Talent Tidal waves In the Resto tree (45 Talent points) is supposed to increase Healing effect scaling of your "Healing wave" and "Lesser healing wave" by 20% and 10% respectively, Is not increasing the scaling as it stands today. Tested it today and i Healed less with Tidal waves up in most cases. (Probably rng) But a 10% or 20% scaling increase should significantly increase the healing done not lower it.

How it works: Shaman 45 Point Talent. "Tidal Waves" Casting Riptide or Chail Heal has a chance (20, 40, 60, 80, 100%) to lower cast time of Healing wave by 30% and increase the Critical effect chance of Lesser healing wave by 20%. the additional effect its supposed to give is not working. 

How it should work: Shaman 45 Point Talent. "Tidal Waves" Casting Riptide or Chail Heal has a chance (20, 40, 60, 80, 100%) to lower cast time of Healing wave by 30% and increase the Critical effect chance of Lesser healing wave by 20%. In addition 20% increase to bonus healing effects of Healing wave and 10% of Lesser Healing wave.

Source (you should point out proofs of your report, please give us some source):  Dono how to prove it. Maybe some fellow Hardcore pve shaman can help me out with that. its borken anyway fix! :p

**Comment by Dootz** [comment]
"In addition, your Healing Wave gains an additional 20% **of your bonus healing effects** and your Lesser Healing Wave gains an additional 10% **of your bonus healing effects**."

http://wow.allakhazam.com/wiki/bonus_healing_(wow)
