### ISSUE TITLE
Zul'Farrak rare boss

### ISSUE THREAD

**Issue by Szelmon556** [SunwellTracker/issues#86]
Decription: 

Brakuje rare bossa w dungeonie Zul'Farrak.

How it works: 

Nie ma wariata.

How it should work: 

A powinien byc i patrolować wokolo fontanny w centralnej czesci instancji.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl?npc=10082

Resetowałem instancje ~50 razy i biegałem po całej spamujac /tar i niestety go nie znalazłem. Moze mialem pecha albo jest super duper ultra rare :p

**Comment by Szelmon556** [comment]
Jakies postepy?

**Comment by Dootz** [comment]
Witaj. Będzie zrobione na update w przyszłym tygodniu (poniedziałek/wtorek). Umknęło mi to. Dziękuję za przypomnienie.

**Comment by Dootz** [comment]
Będzie poprawione po update serwera. (20% na spawn rare bossa)

**Comment by Szelmon556** [comment]
Poprawione zostalo, owszem, z tym ze teraz spawni sie tylko jeden rare elita z trzech mozliwych (Sandarr Dunereaver) z zaskakujaco duza skutecznoscia :D @Dootz moglbys rzucic okiem? 

Brakujace elity: https://classicdb.ch/?npc=10082 /// https://db.darkwizard.pl/?npc=10081
