### ISSUE TITLE
[Quest] Unexpected Results

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#860]
https://db.darkwizard.pl/?quest=8488

If you kill the scourge before they get to her, she bugs out and the quest doesn't complete. Had to get GM to kill her to progress further.

**Comment by Dootz** [comment]
Will be fixed with next server update

**Comment by Nadiirr** [comment]
Had an issue today with this quest. 
Quest was not completing even with GM respawning mob quest was still showing as incomplete.
