### ISSUE TITLE
Mobs don't aggro

### ISSUE THREAD

**Issue by rseby99** [SunwellTracker/issues#862]
Decription: 
When I attack a mob with a ranged attack or spell, the mob or mobs near it don't aggro me, like they aren't linked.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):  https://www.youtube.com/watch?v=ueDem-fjVpE&feature=youtu.be

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/944
