### ISSUE TITLE
[Hunter] Snake Trap destroying Shaman's totems

### ISSUE THREAD

**Issue by a-krzysztofik** [SunwellTracker/issues#863]
Decription: 
Snakes from snake trap hit aoe and destroy newly placed totems.

How it works: 
When shaman triggers snake trap, snakes spawn and target a shaman. After that, when shaman places new totems, snakes instantly destroy them, focusing shaman all the time.

How it should work: 
Snakes after spawning should target nearest enemy and switch only when their target dies, attacking single-target.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Snake_Trap
"When the trap is activated, snakes start to attack the nearest targets. It is possible that some snakes will attack one target and some will attack other. After the target is dead, snakes attacks next target (in close range)." - which means that snakes shouldn't hit aoe or target new enemy before their current one is alive.

**Comment by a-krzysztofik** [comment]
Same thing applies to warrior sweeping strikes and rogue blade's flurry talents. While active, each hit destroys nearby totem, but it shouldn't:
http://wowwiki.wikia.com/wiki/Shaman_totem
"Totems are immune to AoEs and DoTs, and must be specifically attacked to be destroyed.".

**Comment by Azathothh** [comment]
Will be fixed at next server update.
