### ISSUE TITLE
[Druid] Feral Charge - Bear is in the wrong DR category

### ISSUE THREAD

**Issue by Evilpriest4** [SunwellTracker/issues#864]
**Description:** [Feral Charge - Bear](http://db.darkwizard.pl/?spell=16979)'s root effect currently shares DR with [Entangling Roots](url). It is not supposed to do so and should be listed in a different DR category.

**How it works:** Currently Feral Charge - Bear's root effect is sharing DR with Entangling Roots (i.e. If you do cast Entangling Roots you do have a 10 seconds root effect, if you do use Feral Charge - Bear you end up having a 2 seconds root effect and casting one more Entangling Roots will end up placing a 2.5 seconds root effect.)

**How it should work:** It should instead NOT share DR (i.e. after the first Entangling Roots cast, if you do use Feral Charge - Bear you should end up having a 4 seconds root effect. Casting one more Entangling Roots will result in a 5 seconds root effect.)

**Sources:** 
http://www.warcraftmovies.com/movieview.php?id=132563 at 19:10 minute mark. This is a footage from retail.

Edit: Added links to spells.

**Comment by Semper-Numquam** [comment]
From my research I find this to be true.

The addon "Diminishing Returns" at patch 3.3.5 doesn't show Feral Charge Bear on any DR category, agreeing with the report.

I also found a link (bug report on other server) which lists other sources like AJ and video footage.
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2938

**Comment by Avarishd** [comment]
bump, the video provides enough source. Hope we get a fix soonish :^)

**Comment by Azathothh** [comment]
Will be fixed at next server update.
