### ISSUE TITLE
Cultist Shard Watcher - lacking GCD for casting

### ISSUE THREAD

**Issue by ihcTactics** [SunwellTracker/issues#865]
Decription:  The [Cultist Shard Watchers](https://db.darkwizard.pl/?npc=32349) have 3 spell abilities, 2 of which are instant cast DoTs; Shadow Word Pain and Unstable Affliction. They are able to apply both spells with little to no GCD, effectively applying 2 DoTs instant.

How it works: Both spells are being applied in the spam of roughly 0.2 seconds, both instant cast dots.

How it should work: Mobs should follow the same GCD rules as players (AFAIK). If they have a separate ruleset, I'm unaware of it.

Example: https://youtu.be/oPT9apK3TkY
GM Tide watching + comment: https://puu.sh/zFMz1/50b620afd4.png

**Comment by Dootz** [comment]
Will be fixed with next server update
