### ISSUE TITLE
[Quest] The Cipher Of Damnation - final quest cannot be completed

### ISSUE THREAD

**Issue by TSSchoof** [SunwellTracker/issues#866]
**Decription:**  The quest works fine (except that the sons suddenly appear: they should fly in, they walk through a stone to get to the place where they fight Cyrukh, when walking back to their spawn place they stutter up and down). 

Until you have slain Cyrukh, then the quest doesn't update any more.

**How it works:** When you kill Cyrukh the Firelord the quest does not update that you have slain him thus the quest cannot be completed. I opened a ticket and the GM 'Vnu' came in, we did the fight again and then Vnu set the quest to completed for us.

**How it should work:**  Cyrukh the Firelord slain should update when you have killed the boss.

**Source (you should point out proofs of your report, please give us some source):** http://www.wowhead.com/quest=10588/the-cipher-of-damnation

**Comment by Dootz** [comment]
what probably happend is that friendly npcs dealt more damage to cyrukh than you. It'll fixed.

**Comment by TSSchoof** [comment]
That's possible because we 2 manned it. :)

**Comment by Dootz** [comment]
Will be fixed with next server update
