### ISSUE TITLE
[Quest] What Illidan Wants, Illidan Gets... - Npc's attack while disguised

### ISSUE THREAD

**Issue by TSSchoof** [SunwellTracker/issues#867]
**Decription:** In this quest you have to disguise as a blood elf, walk into Eclipse Point and talk to Ruusk. The blood elf NPC's shouldn't attack you when you are disguised.

**How it works:** Nearly all blood elf NPC's attack you, except for the 2 elites in front of Ruusk and Ruusk himself.

**How it should work:** None of the blood elf NPC's should attack you.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=10577/what-illidan-wants-illidan-gets

**Comment by Dootz** [comment]
Should be fixed with next server update
