### ISSUE TITLE
Arena Points

### ISSUE THREAD

**Issue by Palagay** [SunwellTracker/issues#868]
Decription: 
I played 10 match in 3v3 Sunday between 18:30pm and 19h30pm and me and my mates don't received  arena points.
The 10 match are in "last week" and this week i have 0 match.
How it works: 
I check it the monday and no arena point

How it should work: 
I have to receive my arena point the sunday at 23:00pm.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
This report does not containt enough information for us to help you. Unfortunately we're here to blame as our response should have come much eariler when it was first reported. I'm closing this issue as it's no longer relevant.
