### ISSUE TITLE
[Lightweave Embroidery] [Lightweave] nie odpala się prawidłowo

### ISSUE THREAD

**Issue by xantypa** [SunwellTracker/issues#869]
Decription: 
Jesteśmy shadow priestem. Ćwiczymy na kulke. Na sobie mamy założone następujące itemy miedzy innymi: 1. Ashen Band of Endless Destruction (finger, posiada odpałkę Frostforged Sage 285 sp), 2. Abyssal Rune (trinket, posiada odpałkę Elusive Power 590 sp) oraz Shawl of Fervent Crusader (back, posiada enchant z tailoringu Lightweave Embroidery, odpałka 295 sp). 

Odpałki nie działają poprawnie. 

How it works: 
Castujemy sobie Mind Flay, wielokrotnie, raz za razem. Widzimy, jak po kolei, w różnych odstępach czasu odpalają się nam odpałki z fingera (item1) oraz trinketu (item2). To nas najbardziej interesuje. Zastanawiające jest, dlaczego odpałka z itemu3 (back) praktycznie się nie odpala. 
Addon Need To Know, po odpowiednim ustawieniu nie wykazuje, aby w/w odpałka sie odpalała. 
Ponadto możemy to sprawdzić w buffach, które pojawiają się na bieżąco obok minimapy, że interesująca nas odpałka nie pojawia się, nie jest aktywna. 

How it should work: 

Niegdyś odpałka z itemu3 (back) była w stanie odpalić się nawet, gdy rzucamy na siebie Inner Fire, Power Word: Fortitute lub inny dowolny spell. Na każdym kroku towarzyszyła. Nie było praktycznie momentu, w której Lightweave się nie odpalał. Teraz nie sposób zauważyć, aby enchant z backa się odpalał. 

Source (you should point out proofs of your report, please give us some source):

**Comment by Nuy** [comment]
I can confirm it should be possible to get the proc from ANY spell cast.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/138
