### ISSUE TITLE
[Spell][Paladin] Seal of Corruption/Vengeance podwójny proc

### ISSUE THREAD

**Issue by Heartbraker** [SunwellTracker/issues#871]
Opis: 

Po wprowadzeniu poprawki : #989 "Seal of Corruption/Vengeance coefficient corrected." seal of corruption/vengeance często proca 2x, głównie po użyciu ds/cs, nie znalazłem żadnej zależności między pojedynczymi i podwójnymi procami (testowałem w eq i bez eq, nie sprawdzałem bez talentów).

Afgann już wie o tym błędzie - zgłaszam jakby komuś chciało się to sprawdzić bez talentów/zauważył coś co wywołuje drugi proc.

**Comment by Heartbraker** [comment]
dobra, znalazlem - jak melee ability critnie odpala się 2x - nawet jesli nie ma 5stackow blood corruption

**Comment by Afgann** [comment]
Poprawione.
