### ISSUE TITLE
[Quest Battling The Elements] Extremely slow respawn of Seething Revenants

### ISSUE THREAD

**Issue by Ordinayy** [SunwellTracker/issues#872]
Decription: 
The respawn rate of Seething Revenants at Fjorn's Anvil is incredibly low. Currently there are never any Revenants alive and 5 people standing there waiting for a respawn.

How it works: 
The current respawn of Seeting Revenants is extremely low.

How it should work: 
The respawn rate has to be increased as this currently makes the quest almost impossible.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
they should be fine now. Respawn time reduced to 2 minutes
