### ISSUE TITLE
[Warrior] Death Wish z Enrage

### ISSUE THREAD

**Issue by wolandu** [SunwellTracker/issues#873]
Decription: Death Wish nie stackuje się z Enrage do łącznie +30% dmg

How it works: odpalając Death Wish mając już efekt Enrage łączny bonus do dmg to 20% zamiast 30%

How it should work: powinno być razem 30%

Source (you should point out proofs of your report, please give us some source):

**Comment by Nuy** [comment]
Pretty it shouldn't stack with enrage.

Nie powinno się stackować.
