### ISSUE TITLE
[LOS][BG][PVP]Destroyed walls on SotA/IoC/WG still block LoS

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#874]
Decription: Even though a wall on SotA/IoC/WG is destroyed it still blocks range attacks by causing out of LoS errors.

How it works: Destroyed walls block LoS.

How it should work: Destroyed walls shouldn't block LoS.

Source (you should point out proofs of your report, please give us some source): -

**Comment by Riztazz** [comment]
duplicate https://github.com/SunwellTracker/issues/issues/498
