### ISSUE TITLE
[SPELL][TALENT]Fingers of Frost - 44544

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#875]
Decription: It's supposed to proc ON CAST, not when spell hits the target like it does now. There should be a delay befor FoF stack is consumed so you still should be able to do shatter combo with just one stack of FoF. The spell that is already in flight when you get the proc shouldn't get affected by FoF buff nor consume it.

How it works: FoF doesn't proc on spell release what's not correct.

How it should work: FoF should proc on spell release. 

Source (you should point out proofs of your report, please give us some source):  
Proof - http://wowwiki.wikia.com/wiki/Patch_3.3.0

"Fingers of Frost: This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target."

Proof that it should NOT get instantly consumed on cast - https://youtu.be/8ET2Ct9_Ma8?t=1m6s; https://www.youtube.com/watch?v=4X-GB9GB7Ic. In these videos you can see mages doing Frostbolt > DF with just one FoF stack.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/79
