### ISSUE TITLE
[Quest] Lightning Infused Relics - Constructor bugged

### ISSUE THREAD

**Issue by dstung610** [SunwellTracker/issues#876]
Description: The Iron Rune Construct not work normally. When I come to the Baelgun's Excavation Site. It just jumps around and cannot control probably after I try to "collect the data" from the crystal. I got stuck and need to open a ticket too, but the second attempt is the same.

How it works: After collecting the data in near the elevator, it's bugged and I got stuck.

How it should work: It's should collect data normally.
![screen shot 2018-03-12 at 9 15 40 pm](https://user-images.githubusercontent.com/16751174/37308474-6f6bd510-263e-11e8-82f1-04dc5d16f60c.png)

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/192
