### ISSUE TITLE
[Paladin] Exorcism / Seal of Command

### ISSUE THREAD

**Issue by kaytecc** [SunwellTracker/issues#878]
Decription: 
Seal of Command helps Paladins with AoE. In the SoC description it is stated that:
"When used with attacks or abilities that strike a single target, this additional Holy damage will strike up to 2 additional targets." The problem is, it doesn't work with Exorcism, which also is a single target, holy damage spell.

How it works: 
Explained it above. Exorcism doesn't proc the "strike 2 additional targets" with SoC.

How it should work: 
It should strike the additional targets after the usage of Exorcism.

Source (you should point out proofs of your report, please give us some source):  Just spawn 3 mobs, use Seal of Command and use Exorcism on one of them.

**Comment by MrTide** [comment]
Hello you can get more information about the procs here @kaytecc 
http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)
seems like Exorcism does not proc it

**Comment by Semper-Numquam** [comment]
Attacks and abilities don't include spells as a general rule. Seals only proc from melee attacks, in fact.
