### ISSUE TITLE
Quest: Honor is for the Weak

### ISSUE THREAD

**Issue by Thunderbuddy123** [SunwellTracker/issues#879]
Decription: 
Restless Lookouts assassinated

How it works: 
It says invalid target on quite a few of these mobs. 3 of which are located at 40.92, 37.62.

How it should work: 
I should be able to use the assassinate ability to get credit for this quest.

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031218_184754](https://user-images.githubusercontent.com/37314093/37313533-09f1d40e-2626-11e8-9176-86dffd419932.jpg)

**Comment by MrTide** [comment]
Hello can confirm only those three mobs are invalid target for some reason

**Comment by Dootz** [comment]
Will be fixed with next server update
