### ISSUE TITLE
Melle attack range 

### ISSUE THREAD

**Issue by Shaadya** [SunwellTracker/issues#88]
Decription: 
I encoutered some mobs (for example mammoths in Borean Tundra) staying out of my melee attack range and not coming any closer.

How it works: 
I encoutered some mobs (for example mammoths in Borean Tundra) staying out of my melee attack range and not coming any closer.

How it should work: 
I have seen something like this for the first time and I believe mobs should come to and always be in your melee attack range.

Source (you should point out proofs of your report, please give us some source):  
Mammoths in Borean Tundra. It doesn't always happen though, unless I wasn't focused on the issue. Maybe it's not an issue but maybe it will help you guys out.

**Comment by Azathothh** [comment]
Movement system rewriten, it shouldn't happen anymore.
