### ISSUE TITLE
Spirit wolf in dustwallow 

### ISSUE THREAD

**Issue by Nerysha** [SunwellTracker/issues#880]
Decription: Hi. I wanted to tame a spirit wolf in dustwallow marsh but it is untameable and dissapears in a few seconds. I wrote a ticket but Regards can't help and he said to wrote an issue. Thanks.

How it works: untameable and disappears.

How it should work: it must be there.

Source (you should point out proofs of your report, please give us some source): hunter pet

**Comment by Semper-Numquam** [comment]
Do you have the BM talent? The required level? What NPC was it?

**Comment by Dootz** [comment]
they shouldn't be tameable.
https://github.com/TrinityCore/TrinityCore/issues/13223
