### ISSUE TITLE
Goregek's Endurance - Spell ID [ 54179 ] 

### ISSUE THREAD

**Issue by seadix** [SunwellTracker/issues#881]
Decription: 
Frenzyheart npc you get doing quest chain when you summon him he buffs you

How it works: 
Sometimes heals Goregek for 406 to 644 health when damaging an enemy.
[ it heals your char every hit you do so you can farm 24/7 or do pvp without losing health while npc is near you ]
How it should work: 
Sometimes heals Goregek for 406 to 644 health when damaging an enemy.
[ it should heal only npc randomly as text says (sometimes)]
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
