### ISSUE TITLE
Loot: Heroic Occulus

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#883]
Just did Occulus on heroic, and there was no loot bag in the chest for the final boss.

**Comment by Heartbraker** [comment]
"#986
Core | Author: Riztazz
Core / General
Cache of Ley-Guardian Eregos only drops for player that are queued via LFG."
There should be added that it can be only obtained if player queued to **random heroic**

If you queued to Oculus or went there without Dungeon Finder you **shouldn't** get cache of the ley-guardian.




http://www.wowhead.com/item=52676/cache-of-the-ley-guardian#comments
"By Beltane (21,830 –  6·32·97)  on 2010/02/06 (Patch 3.3.2) | 
This only drops when you do the instance as the result of putting yourself in the queue for a random heroic: it will not drop if you choose to do the Oculus."
http://wowwiki.wikia.com/wiki/Cache_of_the_Ley-Guardian
"The Cache of the Ley-Guardian can be found in the Cache of Eregos after defeating Eregos in the Oculus on Heroic mode if and only if the player was selected to complete the dungeon randomly."

**Comment by Riztazz** [comment]
What @Heartbraker said, closing.

**Comment by TheRealYasri** [comment]
My mistake then was doing it for weeks as a single select or as a group of instances selected and was getting the bag, thought it was normal, so when I did not get one like I normally due, I was left confused.
