### ISSUE TITLE
[Paladin] Hand of Reckoning bug

### ISSUE THREAD

**Issue by Kenaowar** [SunwellTracker/issues#885]
Decription: Hand of Reckoning should work on totem and actually do the dmg on them.

How it works: On sunwell it doesn't work at all, Hand of reckoning do 0 dmg on totems

How it should work: Hand of reckoning should deal the damages on Totems,

Source (you should point out proofs of your report, please give us some source): http://www.arenajunkies.com/topic/52549-paladin-hand-of-reckoning-totem-killer/

**Comment by Heartbraker** [comment]
Topic you've posted was created before patch 3.2.0 when Hand of Reckoning was changed and sadly could no longer destroy totems (including grounding)

**Comment by Kenaowar** [comment]
http://www.arenajunkies.com/topic/64852-paladin-hand-of-reckoning-grounding-before-hoj-target/
You right, my bad, can delete that bug report. Ty
