### ISSUE TITLE
[Paladin] Beacon of light

### ISSUE THREAD

**Issue by Kenaowar** [SunwellTracker/issues#886]
Decription: Beacon of light is bugged here. It doesn't work properly

How it works: When you healing someone while having Beacon of light on yourself. If that target is near a wall or something similar, the heal success but the beacon of light don't work, so it only heal your target.

How it should work: If you are able to heal your target and beacon of light is on you, you should ALWAYS receive the heal on you. Here on sunwell if for example you running around pillar and using holy shock, most of the time you will not receive the heal from Beacon of Light.

Source (you should point out proofs of your report, please give us some source):

**Comment by Semper-Numquam** [comment]
http://www.wowhead.com/forums&topic=145887/beacon-of-light-and-line-of-sight

Beacon requires your heals' target to be on LoS of the Beacon Target even if it isn't on your LoS (Paladin. In the URL there's a nice image showing us how it should be.

My guess is that this is a lagg or delay issue, maybe even a check issue (that you manage to heal your target but LoS before server checks if you (beacon) are in LoS of your target.)

**Comment by Kenaowar** [comment]
I'm talking about beacon of light on the paladin, not a random target behind pillar. If you can heal your target, you SHOULD receive the heal, that's logical.

**Comment by Azathothh** [comment]
duplicate : https://github.com/SunwellTracker/issues/issues/19
