### ISSUE TITLE
Quest: The Eagle's Essence (class quest for 280% flying form - CAN'T COMPLETE!)

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#889]
Decription: 
[The Eagle's Essence](https://db.darkwizard.pl/?quest=10990#?ref=sunwell.pl) when you summon quest mob by using statue it summons quest mob INSIDE texture so you can't even hit it (even if you use your mass damage spells)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031318_191230](https://user-images.githubusercontent.com/35955516/37358335-7c7401c8-26f3-11e8-9242-77c698e070e8.jpg)

**Comment by Dootz** [comment]
should be fine now
