### ISSUE TITLE
Quest: The Hawk's Essence (class quest for 280% flying form - CAN'T COMPLETE!)

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#890]
Decription: 
[The Hawk's Essence](https://db.darkwizard.pl/?quest=10992#?ref=sunwell.pl) when you summon quest mob by using statue it summons quest mob INSIDE texture so you can't even hit it (even if you use your mass damage spells)

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031318_191230](https://user-images.githubusercontent.com/35955516/37358799-a42a2b38-26f4-11e8-8b6d-396c34dd3da1.jpg)

**Comment by Lyonsteel** [comment]
hello i would like to reassure this
You click on the statue this npc spawn
http://www.wowhead.com/npc=22992/guardian-of-the-hawk

and he's got an immune mask on it and cant be damage with spells/abilities than later he disappers

**Comment by Lyonsteel** [comment]
Quest is now working just done it at 10:34

**Comment by Dootz** [comment]
yup, i forgot to close this issue.
