### ISSUE TITLE
Quest: Chasing the Moonstone

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#891]
Decription: 
[Chasing the Moonstone](https://db.darkwizard.pl/?quest=10994#?ref=sunwell.pl) after using table  goblin must stun you and jump in the river and after that you must chase her in the river. You must evade bombs that she spawn etc.
This quest is not working as intended. After you use the table she apears near you and simply gives you your stone...

How it works: 
[Chasing the Moonstone](https://db.darkwizard.pl/?quest=10994#?ref=sunwell.pl) after using table  goblin must stun you and jump in the river and after that you must chase her in the river. You must evade bombs that she spawn etc.
This quest is not working as intended. After you use the table she apears near you and simply gives you your stone...

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
