### ISSUE TITLE
[Quest] Ghost-o-plasm Round Up (6134)

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#893]
Decription: 
Quest item cannot be activated at the required location.

How it works: 
Try to use [Crate of Ghost Magnets] in Desolace (64,90) and nearby area.
You will get "Requires Twin Goliaths" message.

How it should work: 
Quest item should activate at (64,90) instead of giving error message.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
![wowscrnshot_031418_000521](https://user-images.githubusercontent.com/25490436/37374487-ac6d9240-271b-11e8-9986-68d7e1521fb8.jpg)

I tried on 64, 93 as suggested by addon and it worked.

**Comment by TheBigBallsOfFury** [comment]
I had tried this a week ago and it didn't work. Maybe something had bugged it which solved itself after a restart. Don't know.

All I can say I thoroughly tested the whole area spamming the item at the time. Feel free to close this issue if it's working.

**Comment by Dootz** [comment]
ok, i'll test the rest of this area then.

**Comment by Dootz** [comment]
Will be fixed with next server update
