### ISSUE TITLE
[Quest] Aquementas (4005) - Incorrect Dialogue

### ISSUE THREAD

**Issue by TheBigBallsOfFury** [SunwellTracker/issues#894]
Decription: 
Aquementas says: That kodo sure is a beauty. Wait a minute, where are my bifocals? Perhaps you should inspect the beast for me.

How it works: 
Aquementas says: That kodo sure is a beauty. Wait a minute, where are my bifocals? Perhaps you should inspect the beast for me.

How it should work: 
Should not say dialogue of Kodo trainer from Desolace LUL

Source (you should point out proofs of your report, please give us some source): 
Can't find correct dialogue. But this should probably be removed :D

**Comment by Dootz** [comment]
Will be fixed with next server update
