### ISSUE TITLE
Quest: A Slow Death

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#895]
Decription: 
Drop rate of [Fel Gland](https://db.darkwizard.pl/?item=32502) in quest [A Slow Death](https://db.darkwizard.pl/?quest=11020) must be like 95%, but here it is like 5%.

How it works: 
Drop rate of [Fel Gland](https://db.darkwizard.pl/?item=32502) in quest [A Slow Death](https://db.darkwizard.pl/?quest=11020) must be like 95%, but here it is like 5%.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
Check it on wowhead.

**Comment by Dootz** [comment]
Will be fixed with next server update
