### ISSUE TITLE
Avenging Wrath and absorbs

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#896]
Decription: 
 Sanctified Wrath makes all Avenging Wrath damage go through absorbs.

How it works: 

How it should work: 
Sanctified Wrath should make 50% of the damage go through absorbs.

Source (you should point out proofs of your report, please give us some source): 
Tested ingame.

**Comment by MrTide** [comment]
Hello whats your proof ?

**Comment by Dootz** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.

**Comment by buugss** [comment]
Proof is in the tooltip

**Comment by MrTide** [comment]
Hello well it says 50% yes but you say its 100% how do you know its 100% also make the report again if you have any proof of this
