### ISSUE TITLE
Water Elemental doesn't stop casting

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#897]
Decription: 
When a /petpassive command is issued, the water elemental does not stop casting its waterbolt.

How it works: 

How it should work: 
The water elemental should stop casting when put to passive.

Source (you should point out proofs of your report, please give us some source): 
Tested ingame.

**Comment by Azathothh** [comment]
That's not true, he shouldn't stop his current cast.
Use /petfollow to get that effect.
