### ISSUE TITLE
Ice Barrier

### ISSUE THREAD

**Issue by buugss** [SunwellTracker/issues#898]
Decription: 
Ice Barrier cannot be refreshed if the current one has more spellpower on it than the one that is about to be casted.

How it works: 

How it should work: 
It should be able to be refreshed with less spellpower than the current Ice Barrier.

Source (you should point out proofs of your report, please give us some source): 
Tested ingame.

**Comment by Dootz** [comment]
That's most likely intended behaviour. Stronger buffs shouldn't be replaced with weaker. Unless you have any evidence that it should work as you described itt.

**Comment by buugss** [comment]
This is how it worked on arena-tournament
