### ISSUE TITLE
Naxx25 Loot Table mixups.

### ISSUE THREAD

**Issue by Doublespoons** [SunwellTracker/issues#900]
Decription: 
There are some loot table issues on certain bosses in Naxx25. Thaddius dropped Boots of Impetuous Ideals and that is NOT apart of his loot table. Also Thaddius, Four Horsemen, and Loatheb drop a total of 3 items each week. 

How it works: 
Thaddius, Four Horsemn, and Loatheb have a total of 2 Tier Pieces and 1 random drop from their table. Thaddius drops Boots of Impetuous Ideals.

How it should work: 
Thaddius, Loatheb, and Four Horsemen should drop a total of 4 items. Two tier pieces and 2 random pieces from the loot table. 

Source (you should point out proofs of your report, please give us some source): 
Boots of Impetuous Ideals drops from Loatheb and can be checked on Atlas Loot to confirm.

These images are from Retail currently. I checked with random videos that were dated 2009 on youtube by searching boss names, but i didnt think you wanted me to flood this part with videos so i just ran it and took screenshots.

https://clips.twitch.tv/HonestYawningSparrowRaccAttack clip from livestream where boots dropped off the wrong boss's loot table. WARNING: I cuss alot for no reason... i have a little bit of a potty mouth..,

https://imgur.com/a/e55qG Thaddius Kill
https://imgur.com/a/rkhkx Loatheb Kill
https://imgur.com/a/3PydM Four Horsemen Kill

**Comment by Dootz** [comment]
should be fine now
