### ISSUE TITLE
Hunter: Volley Bugs (2)

### ISSUE THREAD

**Issue by JohnNiemynski** [SunwellTracker/issues#901]
Decription: 
1) No Auto Shot during volley channel
2) No Mana return on damage tick while channeling Volley while in Aspect of the Viper

How it works: 
1) If you right click a mob to auto attack it and then channel volley, your next auto does not go off until the channel of volley completes
2) When in Aspect of the Viper, Mana gets refunded as if volley did damage when it is first cast, an not again

How it should work: 
1) If the Hunter Targets a mob and starts auto-ing, then throughout the duration of the channel of volley the hunter should continue auto-ing 
2) While in Aspect of the Viper, the Hunter should get mana back on each tick of damage from Volley, on each mob it hits (in retail this is how I would return a large amount of mana very quickly).

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment]
False report.

1: Autoshot should pause while casting Volley.
Proof:
https://youtu.be/OlkkQNRJfgo?t=2m41s
https://youtu.be/YMaNM3FQ7TM?t=1m10s
(blue bar over cast ba is the auto shot tracker)

2: Aspect of the Viper shouldn't generate mana on Volley.
Proof:
"Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, but not including the ticks of Serpent Sting or the damage of Volley) to generate a percentage of the Hunter's maximum mana."
http://wowwiki.wikia.com/wiki/Aspect_of_the_Viper

**Comment by Riztazz** [comment]
@ujellyx summed it up pretty well, closing
