### ISSUE TITLE
Quest-Suraku-the-Azure-Netherwing-Drake

### ISSUE THREAD

**Issue by sorenthore** [SunwellTracker/issues#902]
Decription: After you are exalted doing quests and picking up eggs from  Dragonmaw Fortress,  you are revealed not as part of their clan(Illidan sees it) but then a dragon saves you and takes you to shattra to pick a netherdrake amount 6 colors  1 of your choose.

How it works: once you fly from shadowmoon on the dragon you land in shattra amount 6 dragos and 
Barthamus to pick up a dragon.

How it should work:  Once you automatically dismount from the dragon you should be able to talk to a drake a get a mount.

Source (you should point out proofs of your report, please give us some source): http://www.wowhead.com/quest=11112/suraku-the-azure-netherwing-drake

**Comment by sorenthore** [comment]
![wowscrnshot_031418_065439](https://user-images.githubusercontent.com/37360412/37403501-ab583d5e-2754-11e8-9350-57fcfef36836.jpg)

**Comment by sorenthore** [comment]
![wowscrnshot_031418_065609](https://user-images.githubusercontent.com/37360412/37403575-dbc2a394-2754-11e8-9490-572643cd0a18.jpg)

**Comment by sorenthore** [comment]
![wowscrnshot_031418_071729](https://user-images.githubusercontent.com/37360412/37404538-c7902e84-2757-11e8-95ea-0cc51a372f83.jpg)

**Comment by sorenthore** [comment]
I just tried again and still nothing, i cannot interact with the drake i want nor the blood elf who sells other mounts( Barthamus)

**Comment by Dootz** [comment]
could you message me on discord? We'll figure it out.

**Comment by Dootz** [comment]
resolved
