### ISSUE TITLE
[Item - Formal Dangui]

### ISSUE THREAD

**Issue by zexwildbacon2** [SunwellTracker/issues#903]
Decription: Formal Dangui - chest,item level 60

How it works: it has 60 ilevel but you cant put enchants that requires ilevel at all.

How it should work: it should be fixed so you can put 60 ilevel enchants its a chest and has 60 ilevel should be working please fix its BiS item for 1 level twinks!

Source (you should point out proofs of your report, please give us some source): https://imgur.com/NwpHG0J > https://imgur.com/ud1O1YR > https://imgur.com/GFCEawb

**Comment by zexwildbacon2** [comment]
I though its a bug because i have that item in warmane and 60 level enchants work thats fucked up now cuz i wasted my gold for it + the enchant

**Comment by Akha72** [comment]
What Dootz posted is true, only Vanilla and TBC enchants work. Warmane is no proof of anything.
