### ISSUE TITLE
[Druid] Moonkin/Tree of life powershift does not work as intended

### ISSUE THREAD

**Issue by iamadog420** [SunwellTracker/issues#904]
Description: Powershifting is when druids make a macro to re-cast their form to remove a CC without leaving form

example macros:

/cast !travel form - works as intended (removes cc) 

/cast !moonkin form  - does not work as intended (does not remove cc)

same for tree of life 

/cast [stance:1] !Dire Bear Form; [stance:4] !Travel form; [stance:3] !Cat Form; [stance:5] !Tree of Life
/cast [stance:1] !Dire Bear Form; [stance:4] !Travel form; [stance:3] !Cat Form; [stance:5] !Moonkin Form

all forms except for moonkin/tree of life work properly.

How it works: 

for example you are affected by crippling poison you should be able to use the macro once to recast your current form to remove crippling poison. it does not remove if you are in tree of life form or moonkin form. you do recast the form (lose mana) but cc is not removed.

How it should work: 

it should remove the cc 

tooltip: "The act of shapeshifting frees the caster from polymorph and movement impairing effects"

Source (you should point out proofs of your report, please give us some source): 

very easily repeatable, just duel a rogue with crippling poison or a mage with frost nova, could post video if necessary.

**Comment by Dootz** [comment]
Will be fixed with next server update
