### ISSUE TITLE
[Quest] Patching Up  ID: 11894 [ Borean Tundra]

### ISSUE THREAD

**Issue by nab89** [SunwellTracker/issues#908]
Decription: http://www.wowhead.com/quest=11894/patching-up

How it works: 
After "collect 5 uncured caribou hide" we must go near Geyser Fields and use "uncured caribou hide" to creat "Steam Cured Hide" but we i am near Geyser Fields i see still communique: "Request Geyser Fields stream vent"
https://imgur.com/a/MdSnt

How it should work: 
https://www.youtube.com/watch?v=OAXV6u7stqE

Source (you should point out proofs of your report, please give us some source): I don't know.

**Comment by Dootz** [comment]
There are few places where it works. I'll fix that. If you want to complete this quest right now, please check following locations:

66.4, 27.4
68.5, 28.3

![Uploading WoWScrnShot_031418_180712.jpg…]()

**Comment by nab89** [comment]
Yes, its working in this localications. Good luck with fix all  localications near Geyser.
Thanks for helping.

**Comment by Dootz** [comment]
Will be fixed with next server update
