### ISSUE TITLE
There is no Check for inventory space when you equip a two-handed item

### ISSUE THREAD

**Issue by CsapiWasTaken** [SunwellTracker/issues#91]
Decription: 

There is no check if you have enough inventory space for main and off-hand when you equip a two handed item.  

How it works: 

As a result if you have an off-hand on you and you want to equip a  two handed the off-hand won't be placed into your bag. The "System" will send the item to you by mail so its not really gamebreaking but can be a pain if you accidentally destroy your off hand and you don't really have a mailbox nearby.

(I'm not sure but i suspect that means you have no check for inventory when items are unequipped so it may cause more problems with certain things that forces you to take off your items)
How it should work: 

It should make an inventory check if you have enough place for the items that are about to be unequipped.
Source (you should point out proofs of your report, please give us some source): 

Picture related
![proof1](https://user-images.githubusercontent.com/36010634/35641650-11876ba4-06c1-11e8-9c8a-989e49965051.PNG)

![proof2](https://user-images.githubusercontent.com/36010634/35641651-11aa1870-06c1-11e8-8651-eccb022627a8.PNG)

![proof3](https://user-images.githubusercontent.com/36010634/35641645-1119a628-06c1-11e8-82e7-f44b31c2d0c5.PNG)

![proof4](https://user-images.githubusercontent.com/36010634/35641647-113a05d0-06c1-11e8-8e92-e04a269d8c32.PNG)

![proof5](https://user-images.githubusercontent.com/36010634/35641648-1161101c-06c1-11e8-9f5f-06369a00a477.PNG)

**Comment by CsapiWasTaken** [comment]
Also note, that if i had a main hand it would have been placed in the empty slot, but it seems like the off-hand takes priority and is taken down before the two handed is even equiped

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
