### ISSUE TITLE
Hunter: Aspect of the Viper and Explosive Traps

### ISSUE THREAD

**Issue by kinghunterx** [SunwellTracker/issues#911]
Decription: when you use Explosive Trap with Aspect of the Viper the initial tick from the trap should restore mana, and the more targets it ticks from the initial proc the more mana you gain. 

How it works: currently it gives no mana back and its a huge bug on hunters atm.

How it should work: when you use explosive trap with viper aspect up you should get mana back.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/forums&topic=149577.72
 ( Volley does not return mana to you in Aspect of the Viper. That said, Explosive Trap does. By Rilgon on 2010/06/23 at 1:07 PM (Patch 3.3.5)

+ https://www.warmane.com/bugtracker/report/15744 best sources i could find.

**Comment by akrom23** [comment]
Works okay.
