### ISSUE TITLE
Cant tame beast on 11lvl hunter

### ISSUE THREAD

**Issue by braylay** [SunwellTracker/issues#912]
Decription: 
I dont have quest for tame 1st beast and even tame beast ability icon in spellbook.
Pet trainer can only tell me how tame beast, in hunter trainer i cant learn this spell...

How it works: 
I dont have quest for tame 1st beast and even tame beast ability icon in spellbook.
Pet trainer can only tell me how tame beast, in hunter trainer i cant learn this spell...

How it should work: 
I should have quest and tame beast ability. 

Source (you should point out proofs of your report, please give us some source): 
![zrzut ekranu 11](https://user-images.githubusercontent.com/37385723/37433315-b9581c08-27db-11e8-8db6-4c995dd4acb5.png)
![zrzut ekranu 12](https://user-images.githubusercontent.com/37385723/37433316-b9700f7a-27db-11e8-8401-ef2905ad9d24.png)
![zrzut ekranu 13](https://user-images.githubusercontent.com/37385723/37433317-b9888582-27db-11e8-8806-741f23099dd7.png)
![zrzut ekranu 14](https://user-images.githubusercontent.com/37385723/37433318-b9a78180-27db-11e8-9b10-84a54994170a.png)

**Comment by braylay** [comment]
![zrzut ekranu 11](https://user-images.githubusercontent.com/37385723/37433338-c9ae5216-27db-11e8-98d7-9ec9c55fd5f8.png)

**Comment by MrTide** [comment]
Hello i don't think its bugged make a ticket ingame we will check it out for you
