### ISSUE TITLE
Joining Arena in raid group [PvP] [Arena]

### ISSUE THREAD

**Issue by Sunite** [SunwellTracker/issues#913]
Description: 

**Joining arena in a raid group leads to disbanding a raid group after every arena...**

How it works:

**When you join arena 2v2 or 3v3 in a raid group, once you are finished and leave arena your raid is disbanded. So you need to invite your partners again every time which is annoying...This is very crucial as you are not only inviting your partners every time but you also have to mark your teammates...**

How it should work: 

**Simply your group is not supposed to disband after an arena match.**

Source (you should point out proofs of your report, please give us some source): 

**???Common sense???**

**Comment by Sunite** [comment]
Mandatory for arenas, any ETA when this going to get fixed?

**Comment by Sunite** [comment]
??????????????????????

**Comment by Danieloses** [comment]
Same for battlegrounds
