### ISSUE TITLE
Feral TigerFury+RIP DPS spec

### ISSUE THREAD

**Issue by oinin** [SunwellTracker/issues#919]
Decription: 

when use on feralDPS spec TigerFury Damage at bleeds dont BuFF? we tested it a lot of time with some addons. plz fixed it(if u use in rotationTiger Fury + bleed) ur bleed must up dmg. but on this server nothing
How it works: 
if u use in rotationTiger Fury + bleed) ur ur bleed Dmg dont buff

How it should work: 
[Блокнот.txt](https://github.com/SunwellTracker/issues/files/1815619/default.txt)
when u use TF+RIP ur RIP ability must do more DMG
https://db.darkwizard.pl/?spell=50213

**Comment by Avarishd** [comment]
I already reported that, literally 3min ago LOL @oinin
