### ISSUE TITLE
Enchant proc cooldown upon swapping weapons

### ISSUE THREAD

**Issue by vedude** [SunwellTracker/issues#92]
Decription: 

I seem to have noticed a problem that I've never seen on any wotlk server except Sunwell. I do not know if this is intentionally implemented, but when you have an enchant that does not have a iternal cooldown on two weapons, swapping to weapon number two triggers some sort of cooldown itself to not let the weapon number two's enchant proc within at least 30 seconds.

As an example is written below.

Weapon 1 has "Berserking" Refreshable proc
Weapon 2 has "Executioneer" Refreshable proc

How it should work: 

You equip weapon 1. You get berserking proc and it does not have a cooldown, which means it can refresh itself. You equip weapon 2 with executioneer and it procs instantly within it's proc chance. If you are lucky, you can have both these enchants up but still sacrifice 1.5 sec global cooldown.
How it works: 

You equip weapon 1. You get berserking proc and it does not have a cooldown, which means it can refresh itself. You equip weapon 2, however the executioneer enchant will not proc until at least 30 seconds have passed.

Source (you should point out proofs of your report, please give us some source): 

This works on all wotlk servers I have played on. I have not seen anywhere where weapon enchants should have 30 sec cooldown to proc. In fact, I have seen forum discussions where some people advices to swap weapons to have the possibility to use both the enchants within their proc rates.

http://www.arenajunkies.com/topic/133199-berserking-v-executioner/

There is some discussion here where they talk about which enchant is the best to use. However, there's been no discussion about cooldown, but rather use them both with weapon swap macros, including swapping to one hand and a shield.

Thank you very much for reading this. It would be great if you guys could take a look into this :)

Sincerely

Vedude

**Comment by vedude** [comment]
Hello,

Updating this issue. It has been confirmed by Afganek that there's a cooldown of 30 seconds before the swapped weapons enchant can proc. This is a big problem for warriors as in PvP, there's alot of weapon swapping to one-hand and shield, and back to Two-Hand weapons.

Warriors can't afford to have a big damage nerf because they need to play properly by swapping weapons. This can be tested easily by switching weapons with enchants.

Sincerely

Vedude

**Comment by vedude** [comment]
Update.

Weapons that have proc chance within themselves ALSO have internal cooldown.
As an example, weapon from Professor Putricide (25) drops One-Handed mace called "Last Word". Link to this weapon is here - http://wowwiki.wikia.com/wiki/Last_Word

This weapon, or any weapon enchants (except Spell Surge), are not supposed to have a 30 second cooldown.

Hopefully this helps :)

**Comment by vedude** [comment]
Update.

This cooldown also includes Shadowmourne. After changing weapons, you are forced to wait 30 seconds before the shard procs will start stacking up again.

**Comment by Vanquis** [comment]
What about this bug? It's really important for all weapon-switching classes. Is anything happening in here?
