### ISSUE TITLE
Iron rune construct rocket boots don't work as intented

### ISSUE THREAD

**Issue by Kaombo** [SunwellTracker/issues#920]
Decription: 
http://www.wowhead.com/quest=11494/lightning-infused-relics
On this quest I tried to use the rocket boots but ended up with full controll of the construct and a significant speed boost

How it works: 
https://plays.tv/video/5aa9848275bf66ff44/sunwell
Video recording of what happened

How it should work: 
It should jump into the air and land on a platform at the top of the mine

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=11494/lightning-infused-relics

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/192
