### ISSUE TITLE
[Hunter] pet wont attack target on mid/long range

### ISSUE THREAD

**Issue by blazetrooper** [SunwellTracker/issues#921]
Decription:  I am having some troubles with pet controling, he wont run to target at 50-60 yards from him. Its not good on some bosses and super bad on arena. You cant break drinking with pet, you cant keep rogue/feral in combat for preventing restelth and etc.

How it works: Pet just staying near hunter and ignoring all comands to attack target. 
https://www.youtube.com/watch?v=AZD6NrlGtNs world video
https://www.youtube.com/watch?v=AZD6NrlGtNs arena video, you can see how pet just stops chasing target at some range.

How it should work: Pet must run and attack any visible target.

Source (you should point out proofs of your report, please give us some source): Its kinda basic mechanic and its hard to find any proofs cuz nobody noticing this moment on videoss etc. I recorded video from retail wow for example: https://www.youtube.com/watch?v=9JFqHKIu1fc . i've played on retail wotlk and on many private servers and never seen same problems. And i believe any hunter (or dk/warlock probably) can approve this problem.

**Comment by dathremar** [comment]
https://github.com/SunwellTracker/issues/issues/587

proof: http://www.warcraftmovies.com/movieview.php?id=122825 - 3:20-4:00 - pet commands range on retail was way bigger then on sunwell, it worked fine couple of weeks ago it either got bugged or just fixed in a very wrong way.

**Comment by dispelx** [comment]
up ^ fix this  It is not at all possible to play for a hunter

**Comment by Kokaina** [comment]
Fixed.
