### ISSUE TITLE
Quest: Leave No One Behind. (ID=12512)

### ISSUE THREAD

**Issue by elhardy** [SunwellTracker/issues#923]
Description: 
The quest "Leave No One behind" in Zul'Drak (ID=12512) doesn't allow the first crusaders, you help to become creditable after you return them to the quest NPC. Did this with mounting up and not mounting up, so the mount shouldn't be the issue.

How it works: 
This results in them not dying, and they will follow you afterwards. Had to contact a GM to get them killed. 

How it should work: 
They should be creditable within the time limit, and if you exceed the time limit they should die. 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=lLOpUvAxjw0

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/103
