### ISSUE TITLE
[Quest] Into Hostile Territory - Gryphon not fly

### ISSUE THREAD

**Issue by dstung610** [SunwellTracker/issues#924]
Description: In Wintergarde Keep at Dragonblight, this quest lead you to the Gryphon Master and he tells you to jump on one 1 the Gryphon. But nothing happened at the stage when we jump in the Gryphon.

How it works: After we hopped in, it stays still like a children Gryphon ride, and the only solution is to get off the vehicle.

How it should work: After we hopped in, it takes a few seconds to set off and fly to the Thorson's Post as intended.

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=lI-h62eZlhM

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/698
It'll be fixed with next update
