### ISSUE TITLE
Auras

### ISSUE THREAD

**Issue by keepokappalul** [SunwellTracker/issues#925]
Decription: 
Retri paladin/Arcane mage/BM hunter auras,

How it works: 
Sanctified Retribution/Arcane Empowerment/Ferocious Inspiration are stacking and u can get 9% total damage(instead of 3%,only from 1 aura).

How it should work: 
They should never stack.

Source (you should point out proofs of your report, please give us some source):

**Comment by MrTide** [comment]
Hello i believe its just visual .. they are not actually stacking 
you can see the auras but damage is not stacking

**Comment by Riztazz** [comment]
@Kokaina @Shatterx

**Comment by Kokaina** [comment]
They don't stack for me as well, u may have displayed all of those buffs at the same but dmg is increased only once.
