### ISSUE TITLE
Drop Rate of Demolisher Parts

### ISSUE THREAD

**Issue by kasea** [SunwellTracker/issues#926]
Decription: 
After killing Scavenging Geist, they drop Demolisher Parts. This item is needed to finish quest Field Repairs. Retail drop rate is about 46%. On Angrathar, after killed more than 20 SG I've got any of this item.

How it works: 
Drop rate is significantly below 46%.

How it should work: 
Drop rate is 46%.

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=31847/scavenging-geist

**Comment by Semper-Numquam** [comment]
I did the quest on my priest and it took me like 12 kills to get all parts.

**Comment by Dootz** [comment]
Will be fixed with next server update
