### ISSUE TITLE
[Mob] Ymirjar Wrathbringer chain pull.

### ISSUE THREAD

**Issue by kovaq** [SunwellTracker/issues#927]
Decription:  Chain pull not working for mobs in Pit of Saron. Second group on road up to Tyrannus (they appear after 2 bosses death) More info which mob on screenshot in Source section.

How it works: Mob dont pull with others in chain.

How it should work: Mob should pull with others.

Source (you should point out proofs of your report, please give us some source): 
http://myprintscreen.com/s/rsn5/5da6baed5f

**Comment by Dootz** [comment]
will be fixed with next server update
