### ISSUE TITLE
Evocation 

### ISSUE THREAD

**Issue by Vessler** [SunwellTracker/issues#929]
Decription: If you have a loot table opened such as looting the mob for example, and you use evocation while the loot window is displayed, evocation will cancel its cast right away

How it works: Evocation will cancel its cast right away, providing no mana and have its full cd duration, now this doesnt seem like a something important but it's really annoying especially while leveling.

How it should work: It should close the loot table/window and do its proper evocation animation and cast.

Source (you should point out proofs of your report, please give us some source):  https://imgur.com/a/DLUKH   video proof here

**Comment by akrom23** [comment]
Cannot reproduce.
