### ISSUE TITLE
Dk's Blade Barrier bug

### ISSUE THREAD

**Issue by darray01** [SunwellTracker/issues#93]
Decription: Blade Barrier rank 3 is not working, i dont have tested another ranks.

How it works: dont get the buff

How it should work: 10 sec's buff , 3% less damage taken (rank 3) after using all blood runes.

Source (you should point out proofs of your report, please give us some source):

**Comment by Cwiercpasiec** [comment]
I've just tested it, Blade Barrier (rank 5 and rank 3, checked both) gives proper buff. 
https://imgur.com/a/teSZI - Proof.

The only problem is that when you use Blood Boil while 1 blood rune is already on cd and it doesn't hit anything (idk what about misses, i just moved away from any enemy targets) you won't get the buff. I'm not sure if this is a bug or not, someone has to check it.
