### ISSUE TITLE
[Warrior Bug] Trauma talent increases Deep Wounds damage by 69% instead of 30%

### ISSUE THREAD

**Issue by ntt1** [SunwellTracker/issues#930]
Decription: 
When you get the talent Trauma (increases bleed damage taken by the target by 30%), warrior's Deep Wounds does 69% more instead of 30% more (x1,69 instead of x1,30). This could be because deep wounds takes 30% from the talent twice into the formula, which results in 69% total increase. This bug does not affect other dots, like rend.
Link to trauma - https://db.darkwizard.pl/?spell=46855

How it works: 
Before specing into Trauma talent, Deep Wounds does blizzlike damage, after specing Trauma it does 69% more, instead of just 30% more, effectively increasing the damage of Deep Wounds by at least 39% more than blizzlike (without taking into account other buffs stacking).

How it should work: 
When Trauma is specced, Deep Wounds should do only 30% more damage. 

Proof: 
https://youtu.be/wY2w9cgbcPg

First without the trauma talent, deep wounds does 78 damage per tick.
After specing into trauma, deep wounds does 132 damage per tick (x1,69 more), when it should do 101 damage per tick (x1,3 more). Clearly not blizzlike.

Updated the video so there's no confusion.

**Comment by Kenaowar** [comment]
Deep wounds stack up, if you crit multiple times the damage goes up, you didn't show your character infos (we can't check if you changed gear or stuff like that) + combat log

**Comment by ntt1** [comment]
The damage per tick i showed was from a single crit, not from stacked up crits.

**Comment by ntt1** [comment]
I have made a video as proof - https://www.youtube.com/watch?v=OUe3ldjgi34

First without the trauma talent, deep wounds does 78 damage per tick.
After specing into trauma, deep wounds does 132 damage per tick (x1,69 more), when it should do 101 damage per tick (x1,3 more). Clearly not blizzlike.

**Comment by Kenaowar** [comment]
Thanks, your video prove that deep wounds is indeed bugged, it doesn't stack while it should stack up.
At 28 seconds you crit 2 times in a row and your deep wounds do 132 damage, at 41seconds you crit only 1 time and your deep wounds do 132 damage again.

So deep wounds doesn't stack while it should, it's actually nerfed

**Comment by ntt1** [comment]
I do not know if you're trolling, but you can see in the video that I applied a new deep wounds after the previous one expired.
I will assume you're trolling as even an average player will understand how this works.

**Comment by Kenaowar** [comment]
How am i trolling ? Deep wounds doesn't stack up with 2 crits. So it's obviously nerfed.
It does the same damage with 1 crit or 2 crits, you think this is "blizzlike"?

**Comment by ntt1** [comment]
Look at the combat log again, it's one crit. Also, if you think its wrong, make another report and submit your findings, this is a report about entirely different thing.

**Comment by Kenaowar** [comment]
28 seconds of your video, your crit the overpower and the white hit. At 41 seconds you crit the overpower and not the white hit. And in both case the deep wounds do the same damage, which is incorrect, it should've done more.

**Comment by ntt1** [comment]
"Your critical strikes cause the opponent to bleed, dealing 48% of your melee weapon's average damage over 6 sec." - deep wounds tooltip, meaning it does fixed damage depending on your melee average damage. If it depended on the critted amount, the tooltip would say "48% of the critted amount".

You're incompetent, please do not comment on serious reports.

Will a developer finally check and confirm this?

**Comment by Kenaowar** [comment]
[WDPS + AP/14*WSPD]x0.48 

This is the formula for deep wounds.

http://www.wowhead.com/forums&topic=146956/deep-wounds-quick-question

I'm incompetent, yeah sure :), keep writting bullshit to make spells fixed to bugged.

**Comment by ntt1** [comment]
And where in that formula is crit amount taken into account? Do you actually understand the formula or you just posted it here without knowing what it means? Why do you keep flooding this topic with irrelevant information? Also you're trying to steer the report away from the actual point. This report is about trauma incorrectly scaling Deep Wounds, increasing the damage x1,69 times instead of 1,3 times. Nowhere in this report did I say it shouldn't stack or anything like that.

**Comment by Kenaowar** [comment]
For the stack deep wounds, someone explained it on the wowhead link i provided. Sorry i assumed that you could check it yourself. But i was wrong, i'm trully sorry.

**Comment by Kenaowar** [comment]
Deep wounds is indeed bugged, it does x1.69 with warrior or feral Trauma talents instead of 1.3x.

**Comment by knasen88** [comment]
Yea this is so noticeable when top damage of warriors is their deep wounds

**Comment by ujellyx** [comment]
Any update on this? Bug was reported months ago and still no change...

**Comment by Kokaina** [comment]
Fixed.
