### ISSUE TITLE
[Warrior] If deep wounds is already applied on the target, damage reduction abilities do not affect it

### ISSUE THREAD

**Issue by ntt1** [SunwellTracker/issues#931]
Decription: 
The Warrior dot Deep Wounds is unaffected by damage reduction abilities if the damage reduction ability is used while deep wounds is already present on the target.
Link to the talent - https://db.darkwizard.pl/?spell=12867

How it works: 
If you're a shadow priest and a warrior has applied Deep Wounds on you, and then you use dispersion, the damage of deep wounds will not be decreased. The damage of deep wounds applied while dispersion is active will be reduced though.

How it should work: 
Damage reduction abilities should decrease the damage of deep wounds even if it was applied before the damage reduction ability was used.

Proof:

Damage of deep wounds before using dispersion (129 per tick):
https://i.imgur.com/undefined.jpg

Damage of deep wounds after using dispersion (129 per tick):
https://i.imgur.com/dgPFXJn.jpg

**Comment by Kenaowar** [comment]
Deep wounds isn't affected to reduction damage mechanics, it does damage about the critical damage you did. If you crit again on the dispersion for example the damage will be lower.

**Comment by Kenaowar** [comment]
Ok you are dumb. Idk if you ever played wotlk but deep wounds was never reduced by stuff like that, only by resilience. And ofc if you crit after a reduced damage buff it's reduced.

There is plenty videos on warcraftmovies of warrior so shouldn't be hard for you to find a proof for what you saying :)

**Comment by ntt1** [comment]
So you're saying that Deep Wounds is one of the few abilities in the game that are not affected by damage reduction abilities? Do you have any proof of that? If it was the case, it would say it in the tooltip, the way it is for spells that do ignore damage reduction abilities (Chaos Bolt, Avenging Wrath).

**Comment by Kenaowar** [comment]
Yes it's only about your weapon damage. Check warcraftmovies videos as i said. People even talking about it on wowhead lol. search a little bit please.

**Comment by ntt1** [comment]
Okay, let me try to explain this as if i'm explaining this to a 5 year old.
After 3.1 patch - http://wowwiki.wikia.com/wiki/Deep_Wounds - deep wounds is unaffected by damage increasing/reducing abilities that affect THE WARRIOR (for example if you have a buff that increases your damage or debuff that decreases your damage, it will only affect your average weapon damage, which will in turn affect deep wounds. Those damage increasing/reducing abilities do not directly affect the deep wounds, but indirectly by increasing/reducing the average weapon damage.)
Now this doesn't mean that when deep wounds is applied on a target, damage reducing abilities that affect THE TARGET should not affect the damage of deep wounds. Contrary, when deep wounds is applied on a target, it should work like any other dot, if you use any damage reducing abilities it should immediately reduce it.

**Comment by Kenaowar** [comment]
Then find a video that prove your statement. Mr. 5years old

**Comment by ntt1** [comment]
https://www.youtube.com/watch?v=BmhJihPPO-U - the first video i found when i searched for 3.3.5 warrior vs sp confirms my statement (look what happens to deep wounds after the sp disperses).

One more thing to note, the patch note clearly says "effects that increase or decrease damage done by a percentage" - DAMAGE DONE, not DAMAGE TAKEN, which clearly indicates that it means increasing/decreasing effects that affect the warrior, not the target.

Why don't you send a video to prove your statement, as all the patch notes and game tooltips are against it, i don't see a reason that i should be the one proving that you're wrong, prove that you're right.

**Comment by Kenaowar** [comment]
On the video, the priest use dispersion indeed, but the warrior use overpower right after, and refresh the deep wounds, which means it's reduced, if he didn't crited the overpower there the deep wounds would've still hit for 378.

It's actually sad that you can't watch a simple video rofl.
And this server isn't retail, it's a private server.
