### ISSUE TITLE
[Quest]Pearl diving - doesn't spawn quest objects

### ISSUE THREAD

**Issue by Lexofein** [SunwellTracker/issues#932]
Decription: 
Quest objects http://db.darkwizard.pl/?object=2744 doesn't exist

How it works: 
https://1drv.ms/u/s!AkiNZqz252mlh2wZRujWcHJ8p-oR
https://1drv.ms/u/s!AkiNZqz252mlh22cVNGYPzByXJCT
How it should work: 
http://wow.zamimg.com/uploads/screenshots/normal/146537-pearl-diving.jpg

Source (you should point out proofs of your report, please give us some source): 
http://db.darkwizard.pl/?quest=705
http://db.darkwizard.pl/?object=2744
http://www.wowhead.com/quest=705/pearl-diving

**Comment by Dootz** [comment]
There are 7 spawn points, one of them is at 26.1, 22.6. Because for this quest you need 9 i'll add few more.
![wowscrnshot_031618_161046](https://user-images.githubusercontent.com/25490436/37528352-ba12d9e4-2934-11e8-859a-21711c9ef533.jpg)
