### ISSUE TITLE
The way to his heart

### ISSUE THREAD

**Issue by bigdaddykain** [SunwellTracker/issues#935]
Decription: There is no spawns of tasty reef fish schools so quest can not be completed

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
There are nine spawn points for this school. One can be found at 36.6, 69.3
![wowscrnshot_031618_162229](https://user-images.githubusercontent.com/25490436/37529026-5879e306-2936-11e8-9239-7fa4c34e8b3e.jpg)
