### ISSUE TITLE
[Priest] Mass dispel can`t dispel Divine Shield 

### ISSUE THREAD

**Issue by Emew009** [SunwellTracker/issues#936]
Decription: 
Dispels magic in a 15 yard radius, removing all harmful Magic from 5 friendly targets and 1 beneficial Magic effects from 5 enemy targets. Potent enough to remove Magic that is normally undispellable.

How it works: 
Mass Dispel doesn`t dispel Divine Shield 

How it should work: 
It should can Dispelled Divine Shield

Source (you should point out proofs of your report, please give us some source): When i use Mass Dispel,divine shield don`t be dispelled

**Comment by Heartbraker** [comment]
Make a screenshot of combatlog where you try to dispell divine shield ~10times and it doesn't work (probably you'll notice in that process that it's working just fine)
https://db.darkwizard.pl/?spell=53519 - this talent is used in all paladin pvp builds

**Comment by Effimera** [comment]
Agree. Even with 5% hit cap on my priest it sometimes takes 3-4 mass dispells and the shield is still on until it finishes naturally. Don't believe the talent's 30% work THAT much!

**Comment by Danieloses** [comment]
True, on sunwell it sometimes takes 5 mass dispels to get bubble off which is a joke

**Comment by akrom23** [comment]
Works okay.
