### ISSUE TITLE
[Quest] The Valiant's Charge(Human)

### ISSUE THREAD

**Issue by disho** [SunwellTracker/issues#937]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Humany nie dostają automatycznie questa niezbędnego do wykonania Chaina z Argent Tournament

**Obecne działanie**: Po quescie A Valiant Of Stormwind nie dostaje się questa The Valiant's Charge. Bug znany administracji (wielokrotnie zgłaszany)

**Oczekiwane działanie**: Automatyczne otrzymywanie questu The Valiant's Charge po wykonaniu questa A Valiant Of Stormwind.
**Co należy zrobić, aby odtworzyć ten błąd**:

1. Spróbować wykonać chaina jako rasa Human
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://wowwiki.wikia.com/wiki/Quest:A_Valiant_Of_Stormwind
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: Argent Tournament - npc Marshal Jacob Alerius

**Comment by Dootz** [comment]
should be fine now
