### ISSUE TITLE
[Ironforge] All guards can detect stealth

### ISSUE THREAD

**Issue by ecnu-zz** [SunwellTracker/issues#943]
Decription: All guards can see stealth players. This is not how it should be. 

How it works:  All guards can detect stealth horde and have a blue circle above them

How it should work: Only some patrol guards can see stealth horde and have a blue circle above them.

Source (you should point out proofs of your report, please give us some source): am rogue, got seen by guards in front of the IF bank.

**Comment by Cwiercpasiec** [comment]
Same thing goes for Exodar (Exodar Peacekeepers can detect stealth), Darnassus (Darnassus Sentinel), Undercity (Kor'kron Overseer) and Thunder Bluff (Bluffwatcher).

**Comment by Dootz** [comment]
Which npcs in major cities should have stelath detection then? So far i found only this:
" Officer Jaxon, Brandy in SW, "Thief Catcher's" in Ironforge, "Scout's" in Orgrimmar "

**Comment by Dootz** [comment]
So for now elite mobs in major cities will have stealth detection

**Comment by Cwiercpasiec** [comment]
In Silvermoon there are Arcane Guardians instead of elites, they should detect stealthed units, and they did, hope you didn't change it. In other cities there are elites, like you mentioned.

**Comment by TheBigBallsOfFury** [comment]
Also, Gadgetzan guards should not have stealth detection (blue circle) on them:

https://www.youtube.com/watch?v=gLjHsH9Dz5w

**Comment by TheBigBallsOfFury** [comment]
Pretty sure that Gadgetzan guards should not have stealth detection. Found no evidence so far to suggest they have stealth detection so it should be disabled IMO. They are not even elites.

**Comment by Dootz** [comment]
will be fixed with next server update.
