### ISSUE TITLE
Priest - staying in combat

### ISSUE THREAD

**Issue by rouginek** [SunwellTracker/issues#947]
Decription: After every fight as shadow priest, i stay in combat for next 3-5 sec untill debuff from improved mind blast fall off, even if the mob is already dead. 

How it works: After every fight as shadow priest, i stay in combat for next 3-5 sec untill debuff from improved mind blast fall off, even if the mob is already dead. 

How it should work: I should get rid of the combat, at the point of the mob's death

Source (you should point out proofs of your report, please give us some source):

**Comment by bongobg** [comment]
First time I'm hearing this. oO

**Comment by rouginek** [comment]
so you dont have that problem?

**Comment by l2github** [comment]
I can confirm this. As priest I come out of combat consistently 3-5 seconds after everyone else in the same fight.

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/1429
