### ISSUE TITLE
Quest: The Hunter and the Prince - Missing/Phasing bugg

### ISSUE THREAD

**Issue by Moozart1337** [SunwellTracker/issues#950]
Decription: The quest in Icecrown called "The Hunter and the Prince" is not doable. 
You are supposed to click on a item on the ground called "BloodStained Stone" This item on the ground is not there.

How it works: The stone or the item to trigger the quest is NOT there.

How it should work: It SHOULD be there

Source (you should point out proofs of your report, please give us some source): 
Video of the quest, in the beginning you can see the rocks location: https://www.youtube.com/watch?v=FRFVDewnV1Y
Wowhead link to the quest, showing it's added in 3.3.0, not a later patch: http://www.wowhead.com/quest=13361/the-hunter-and-the-prince#comments

This is a fun and lore rich quest

**Comment by Dootz** [comment]
Bloodstone spawns after quest "The Hunter and the Prince is accepted. It despawns after some time ~1 minute. So if you can't find it, please try to abandon quest and take it again.
![wowscrnshot_031718_154133](https://user-images.githubusercontent.com/25490436/37556685-b0e9d53c-29f9-11e8-8899-aef5a59f6c13.jpg)

**Comment by MrTide** [comment]
Hello this happens if you accept the quest while mounted or shape shifted and if you abandon or fail and accept it again sometimes two illidan appears instead of one

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/394
