### ISSUE TITLE
Quest: "Crowleg" Dan (Howling Fjord)

### ISSUE THREAD

**Issue by jubasek21** [SunwellTracker/issues#951]
Decription: There's no dialog option with this NPC.

How it works: Cannot complete quest, because there's no dialog option simply.

How it should work: There should be a dialog option to make this NPC angry and complete the quest:
_**Umm... the frog says you're a traitor, "matey".**_

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?npc=24713#abilities
https://db.darkwizard.pl/?quest=11479
https://www.youtube.com/watch?v=jlBylQJg_2U

**Comment by MrTide** [comment]
Hello
Actually dialog pops out after you hit him but you are right you need to talk first

**Comment by Dootz** [comment]
will be fixed with next server update
