### ISSUE TITLE
Icy Prism crafting bugged

### ISSUE THREAD

**Issue by Eggburp** [SunwellTracker/issues#952]
Decription: 
[Jewelcrafting - Icy Prism] Cant craft Icy Prism due to missing reagent : chalcedony despite having chalcedony in my bags
![image](https://user-images.githubusercontent.com/37473912/37554878-edfb9f5a-29d6-11e8-9bb5-418c89a7ba89.png)

How it works: 
Unable to craft despite having all mats

How it should work: 
Should be able to craft

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
That might be visual bug, from what i've heard on currenct patch you need 3 instead of 1 chalcedony
