### ISSUE TITLE
Arcane Torrent - 28733, 25048, 50615

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#953]
Decription: Blank silence blocks player from using this racial. That is not correct.

How it works: Silence blocks player from using Arcane Torrent.

How it should work: You should be able to use Arcane Torrent even if you're silenced.

Source (you should point out proofs of your report, please give us some source): Never worked like that on retail, nothing to back it up that it did.

**Comment by Akha72** [comment]
Proof?

**Comment by Riztazz** [comment]
like akha72 said, proof

**Comment by Nuy** [comment]
Don't you think it's pretty weird not a single wowhead comment would mention that you can't use it while silenced? Can't find any mmo-champion post about it either. I know that it's not a proof by itself but still gives some direction.
