### ISSUE TITLE
Hodir's Horn

### ISSUE THREAD

**Issue by Elefant0n** [SunwellTracker/issues#954]
Decription: Unable to accept daily quest

How it works: Lets me interact with the Horn but can't accept the quest, Tried both yesterday 2-3 times and today 2-3 times.

How it should work: Should be interactable ?

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, 
can you see yellow quest indicator over it? If so try clicking on horn while standing in location from following screenshot
![wowscrnshot_031718_153548](https://user-images.githubusercontent.com/25490436/37556609-e8c4eef2-29f8-11e8-96b3-97c3543400bc.jpg)
