### ISSUE TITLE
(Enchanement) Fishing Derby Quest Turnin

### ISSUE THREAD

**Issue by TheRealYasri** [SunwellTracker/issues#955]
Hello, I just won the northrend derby and picked the wrong item in the rush to complete the quest. It would be nice if when you win you get a follow up quest to pick the reward instead of how it is now were you have to pick as your turning in and possible loss the derby if not quick enough.

Sidenote: Is there anyway I could get the boots replaced with the BoA ring ;P

**Comment by Dootz** [comment]
Sorry that's not possible :(
