### ISSUE TITLE
Players can loot containers while invulnerable

### ISSUE THREAD

**Issue by knasen88** [SunwellTracker/issues#957]
Decription: 
Players are able to loot containers while being invulnerable, while they shouldn't be able to.

How it works: 
They're completely immune as of now

How it should work: 
Patch 0.6
Players can no longer loot or use items while invulnerable.
http://wowwiki.wikia.com/wiki/Patch_0.6?oldid=26360
and it was NEVER patched back into the game, because it is un-counterable by 80% of the game.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Patch_0.6?oldid=26360

**Comment by Azathothh** [comment]
Will be fixed at next server update.
