### ISSUE TITLE
[Dalaran] Game crashes while in Dalaran

### ISSUE THREAD

**Issue by kaytecc** [SunwellTracker/issues#959]
Error I'm getting:
https://imgur.com/a/bH2Z0

Using WoD models and Ultra settings.

PC Specs:
i5-4460
GTX 970
8GB RAM CL9 1600Mhz

**Comment by Cwiercpasiec** [comment]
https://forum.sunwell.pl/index.php?/topic/6529-problem-wow-error-134/
Also this is client problem, no point in posting this kind of problems here.

**Comment by TheRealYasri** [comment]
I had crashing issues also in dalaran alot and used that application like three weeks ago and no crash sense then.

If people find this post in the future and the forum link above does not work anymore. The name of the app was Large Address Aware
https://www.techpowerup.com/forums/threads/large-address-aware.112556/

This is an application that assists in making applications large address aware. When a 32-bit application is large address aware, it can access up to 4 GiB on x64 operating systems and all memory that isn't used by the operating system and other applications on x86. 64-bit versions of Windows require no modifications to the operating system to benefit from this application; however, in 32-bit versions of Windows, you must increase the user memory setting. Instructions how to do this are in spoiler below. It is not advised to use this application if you have less than 3 GiB of RAM.
