### ISSUE TITLE
 [Daggercap Divin'] Quest in Howling Fjord (Crates cant be looted proberly)

### ISSUE THREAD

**Issue by Winterkorn** [SunwellTracker/issues#960]
Decription: 
 [Daggercap Divin'] Quest in Howling Fjord (Crates cant be looted proberly)

How it works: 

(Crates cant be looted proberly)
How it should work: 

Crates should be lootable
Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
what do you mean by "can't be looted properly". Could you  elaborate further on that? You tried to click on it and nothing happened? Were you by any chance in raid group?

**Comment by Winterkorn** [comment]
Hello,

It bugged for me and some other guys, When we had the diving helmet on. Wihtout it, we could loot.

Sendt fra min iPhone

Den 18. mar. 2018 kl. 21.38 skrev Chris <notifications@github.com<mailto:notifications@github.com>>:


what do you mean by "can't be looted properly". Could you elaborate further on that? You tried to click on it and nothing happened? Were you by any chance in raid group?

**Comment by Dootz** [comment]
Fixed.
