### ISSUE TITLE
Quest: Preying Upon the Weak (Howling Fjord)

### ISSUE THREAD

**Issue by jubasek21** [SunwellTracker/issues#961]
Decription: Trapped animals are not lootable, so quest cannot be completed.

How it works: Trapped animals are not lootable.

How it should work: Animals should be lootable.

Source (you should point out proofs of your report, please give us some source): 
https://db.darkwizard.pl/?quest=11292
https://db.darkwizard.pl/?npc=24196
https://db.darkwizard.pl/?item=33487

**Comment by Dootz** [comment]
quest can be complete. You get quest item sometimes when you open trap, and sometimes from killed wolf that spawns.

**Comment by Dootz** [comment]
https://www.youtube.com/watch?v=mtoucx1KQKc
