### ISSUE TITLE
[Item] Black Pearl drop chance

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#964]
Decription: Black Pearls are too rare

How it works: Black Pearl drops from Big-Mouth Clam with probability 1% http://db.darkwizard.pl/?item=7971#created-by

How it should work: probability should be 4%

Source (you should point out proofs of your report, please give us some source): http://web.archive.org/web/20090323094142/http://wow.allakhazam.com:80/db/item.html?witem=7971#Found_in_Items (scroll down to "Found in Items")

Comments like http://www.wowhead.com/item=7973/big-mouth-clam#comments:id=1002797 suggest even higher rate, but guess Allakhazam's estimate is better

**Comment by Dootz** [comment]
Probability displayed at http://db.darkwizard.pl is not always up-to date. That affects among others - Black pearl. So i can tell you that chance to get it is higher than 1%.

**Comment by nimeral** [comment]
>Probability displayed at http://db.darkwizard.pl is not always up-to date

Wow, okay, didn't know that. Hope the chance is 4% or higher as proofs indicate : P
