### ISSUE TITLE
lok`lira`s bergain 

### ISSUE THREAD

**Issue by dropperss** [SunwellTracker/issues#965]
Decription: 
At the pit of fang u get lok`lira`s bergain  so u looks like a blue big women

How it works: 
lok`lira`s bergain  removes from the area so i cant complete the quest from the sons of hodir questline

How it should work: 
The area should be bigger 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
Hi, which quest from sons of hodir questline you can't complete?

**Comment by dropperss** [comment]
Hello Chris! I fixed it, I had "at war" with sons of hodir thats why i
couldnt complete any quest with them. But i were honored with them, hehe.
Thanks for the answer anyway.
/ Droppers

2018-03-18 21:39 GMT+01:00 Chris <notifications@github.com>:
