### ISSUE TITLE
[Zul'Aman] [Timed Chest Rewards]

### ISSUE THREAD

**Issue by zexwildbacon2** [SunwellTracker/issues#966]
Decription: The loot from the event is dependent on the number of hostages you rescue. All loot is from the Zul'Aman timed event loot table (see below).

    First hostage will give a random piece of armor (iLvl 128).
    Second hostage will give a random weapon (iLvl 132).
    Third hostage will give a random ring (iLvl 141).
    Fourth hostage will give a random ring (iLvl 141). 

How it works: Basicly when you kill bosses chest spawn but they can't be opened! so you cant get timed chest rewards.

How it should work: should get  fixed so we can open the chests

Source (you should point out proofs of your report, please give us some source): https://imgur.com/Q0eLWfY (it was kinda late to ss the chest,but guys please look at them they are really bugged)

**Comment by AshhWoW** [comment]
Please fix this
