### ISSUE TITLE
[Transmogrification] No tmog throwing effect.

### ISSUE THREAD

**Issue by mchudy97** [SunwellTracker/issues#967]
Decription:  transmogrified thrown have no throwing effect from tmog thrown.

How it works: transmogrified  Crimson Star  by Sharpened Hyldnir Harpoon looks like that thrown but  have no "effect" of throwned harpoon- It's the same effect like throwing a normal thrown.

How it should work: When I throw that I should see a flying spear.

Source (you should point out proofs of your report, please give us some source): 
[https://db.darkwizard.pl/?item=42863#reward-from-quest](url)

**Comment by Cwiercpasiec** [comment]
Duplicate #827
