### ISSUE TITLE
Quest: A Visit to the Doctor

### ISSUE THREAD

**Issue by Thunderbuddy123** [SunwellTracker/issues#968]
Decription: You must release "Patches", then assist him in killing Doctor Sabnok.

How it works: You right click the post that "Patches" is linked to, which releases him. Then it starts an event that Doctor Sabnok walks down and after some time becomes attackable and "Patches" engages in combat. If you get aggro on Doctor Sabnok, "Patches" gets stuck in place and stops attacking the Doctor. If this happens, and you need to kite Doctor Sabnok and kill him out of "Patches" range, you do not get credit. 

How it should work: "Patches" should not get stuck in place, and killing Doctor Sabnok away from him should still give credit. 

Source (you should point out proofs of your report, please give us some source): GM Tide can confirm this is how it's working in-game.

**Comment by Dootz** [comment]
Starting with next server update, killing doctor will complete part of this quest
