### ISSUE TITLE
Quest: Destroying the Altars

### ISSUE THREAD

**Issue by Thunderbuddy123** [SunwellTracker/issues#969]
Decription: You must kill Master Summoner Zarod to retrieve his Staff to destroy the 4 altars.

How it works: I killed Master Summoner Zarod 4 times. The first 3 he did not drop the staff. The 4th time, he did. I believe there may be a bug with the loot table and it not being a 100% drop rate.

How it should work: When he is killed his staff should be a 100% drop rate.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
