### ISSUE TITLE
[Mage - frost nova/frostbite]

### ISSUE THREAD

**Issue by PaziMetak** [SunwellTracker/issues#97]
Decription: 
Sometimes(rarely) Mobs that are frozen attempt to run away and suddenly Teleport cca 40 yd away in the direction they were running away.
Seen in Scarlet monastery cathedral and Deadmines, and others ( can't remember which ones ) so we can assume its a general mob problem ( not dungeon related)

How it works: 
-

How it should work: 
They should walk away 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again. 

Thanks in advance.
