### ISSUE TITLE
[NPC] High Priestess Jeklik evades all the time

### ISSUE THREAD

**Issue by nimeral** [SunwellTracker/issues#970]
Decription: High Priestess Jeklik evades all the time and can't be pulled/killed

How it works: High Priestess Jeklik (Bat boss in Zul'Gurub) stays where she is and evades few seconds after a pull (unless you have a DK who can pull her down), so Zul'Gurub is impossible to complete

How it should work: High Priestess Jeklik should fly down when aggroed, starting the fight

P.S. A lazy quick solution would be to simply change the spawn location to downstairs.

**Comment by Dootz** [comment]
will be fixed with next server update
