### ISSUE TITLE
Hand of reckoning missing bosses even with glyph

### ISSUE THREAD

**Issue by Anselm123** [SunwellTracker/issues#971]
Decription: 
Hand of reckoning misses even with the glyph giving it 8% hit.

How it works: 
With the glyph it missed. Don't know if it's taking my actual hit chance

How it should work: 
It shouldn't miss ever with the glyph.

Source (you should point out proofs of your report, please give us some source): 
WOL: http://www.worldoflogs.com/reports/y4ba36o0omee1uno/details/21/ Shows 1 miss on Hand of Reckoning.

EJ paladin tank thread: http://sulfuron.warsforum.com/t16-elitistjerks-the-protection-paladin-field-manual-wotlk  "Note that unlike RD, HoR does have a small mana cost. As of the 3.2 patch, the Glyph of Righteous Defense affects HoR as well, making this glyph a great way to help make both your taunts foolproof (along with sufficient hit rating)."

**Comment by knasen88** [comment]
you still need 9% hit from gear to make the 8% glyph make it 17%= 100% chance to hit against bosses.

**Comment by Anselm123** [comment]
Do you have a source for that? I know thats the way that pally taunt worked in BC due to it needing melee hit but being regarded as a spell but iirc wrath they changed that to make it just work off of melee hit

**Comment by Azathothh** [comment]
I've got no idea what the hell BC got to do with hand of reckoning....
" Patch 3.0.8 (2009-01-20): Added." - http://wowwiki.wikia.com/wiki/Hand_of_Reckoning

> Do you have a source for that?

Well, you've linked source already - http://sulfuron.warsforum.com/t16-elitistjerks-the-protection-paladin-field-manual-wotlk - 

"Hit Rating
    32.79 hit rating = +1% chance to hit with melee or ranged attacks (-1% chance to miss).
        For our purposes, this applies to melee swings (white damage), Avenger's Shield, Hammer of the Righteous, Shield of Righteousness, Hammer of Wrath, and Judgements.
        Against a raid boss, melee and ranged attacks have a base 8% chance to miss (this is changed from 9% in TBC), so 263 hit rating is required to eliminate all melee misses if there are no other bonuses to hit.

    26.23 hit rating = +1% chance to hit with spells. For our purposes, this only applies to Righteous Defense, Hand of Reckoning, and Exorcism.
        Against a raid boss, spells have a base 17% chance to miss."

You need about 237hit rating to get ~9%spell hit + glyph for another 8% to get 17% spell hit and never miss with hand of reckoning.
