### ISSUE TITLE
armor, druid-feral

### ISSUE THREAD

**Issue by narcoshka** [SunwellTracker/issues#972]
Decription: 

Armor on the staff and jewelry is not scaled in armor, in feral (370%)
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
"Armor on the staff and jewelry is not scaled in armor, in feral (370%)"
Please, put some effort into explaining what's working wrong, so we can better understand it and fix it. In current form it's incomprehensible.
