### ISSUE TITLE
Issue with Grand warlock nethekurse 

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#973]
Decription: Hello there is a issue with this boss that causes him to stop attacking 

How it works: ATM its possible for him to stop and don't attack players .. and only way to fix this issue is to kill him and revive him with GM command

How it should work: He should not get stuck and start attacking once you killed his minions 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031918_031730](https://user-images.githubusercontent.com/36106057/37572784-791e5ca4-2b25-11e8-85f3-0bca1695d28f.jpg)
NPC ID and extra information included in screenshot

**Comment by dreamingdust** [comment]
It seems to happen if not everyone is in the room when the adds are engaged/killed. Got the bug mentioned above while there was someone staying around the position seen on this SS: http://i66.tinypic.com/20sx8nd.png
Furthermore, if you go out of the room after the Fel Orcs are dead, he does a soft reset in a strange way- starts channeling Shadow Sear (https://db.darkwizard.pl/?spell=30735) without a target, but it damages the Grand Warlock himself:
http://tinypic.com/view.php?pic=28ti1s6&s=9

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/559
