### ISSUE TITLE
Quest : Just following orders

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#974]
Decription: Hello there is an issue with this npc

How it works: Only one player can do it per quest

How it should work: it should be repeatable without an issue for other players 

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031718_003616](https://user-images.githubusercontent.com/36106057/37572807-f183122a-2b25-11e8-8e67-cf324b490085.jpg)
![wowscrnshot_031718_003610](https://user-images.githubusercontent.com/36106057/37572809-f1dcb528-2b25-11e8-9051-e8c71de1ab08.jpg)

**Comment by Dootz** [comment]
should be fine now
