### ISSUE TITLE
Quest  [Dun-da-Dun-tah!]

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#975]
Decription: Quest  [Dun-da-Dun-tah!] is not doable for most of the players also there is a credit issue at the end and happens when someone else starts the event with you

How it works: You can start the event in middle of someone else event so it resets 
he just walks backs and starts the event again

How it should work: You should not be able to start the event in middle of someone else event

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031918_033853](https://user-images.githubusercontent.com/36106057/37572885-19f6f39c-2b27-11e8-8b06-aa9c7c3c3de1.jpg)
![wowscrnshot_031918_033850](https://user-images.githubusercontent.com/36106057/37572886-1a5087c2-2b27-11e8-9e25-99624abc01ef.jpg)
![wowscrnshot_031918_033840](https://user-images.githubusercontent.com/36106057/37572888-1b29d252-2b27-11e8-8887-5fe5ec998cfd.jpg)
![wowscrnshot_031918_033830](https://user-images.githubusercontent.com/36106057/37572889-1ba62668-2b27-11e8-89f3-0b060ae7b267.jpg)
![wowscrnshot_031918_033812](https://user-images.githubusercontent.com/36106057/37572891-1c98ae10-2b27-11e8-8dea-dd241ae3e85c.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
