### ISSUE TITLE
Quest rallying-the-troops

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#976]
Decription: There is a issue with this quest that causes player only be able to do it once 

How it works: after using quest item once on these mobs ( Grizzly hills giant id : 26261 ) for somereason second person can't do the same on that mob again until server restart or GM reset ( kill and respawn)( i know about the debuff its not that )

How it should work: You should be able to do it again

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/quest=12070/rallying-the-troops

**Comment by Dootz** [comment]
will be fixed with next server update
