### ISSUE TITLE
Drakkari Colossus 

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#977]
Decription: Hi
Some times this boss bugs out after getting the living mojos 

How it works: He just stands there 
How it should work: he should not get stuck .. there is some scripting issue with it
Source (you should point out proofs of your report, please give us some source): 
The only way to fix it .. is to ask a GM to kill and respawn the boss to reset it

**Comment by Azathothh** [comment]
Will be fixed at next server update.
