### ISSUE TITLE
Scarlet monastery Cathedral last boss

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#979]
Decription: Hi
There is an issue with Scarlet commander mograine and follow up boss High inquisitor Whitemane

How it works: After starting the fight with the boss  Scarlet commander mograine if you pull the boss too far away from the door that High inquisitor Whitemane comes out event bugs out and mograine stays dead also  High inquisitor Whitemane sometimes goes through the walls since ppl can kite the mograine outside
Also this issue sometimes caused by mindcontrol / stuns too / multiple wipes by the group
How it should work: High inquisitor Whitemane should come out and ress the Scarlet commander mograine no matter what  

I recommend to make the door close up after starting the event so players can't kite him too far

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
will be fixed with next server update
