### ISSUE TITLE
Human starting zone wolves

### ISSUE THREAD

**Issue by Chelseakiko3** [SunwellTracker/issues#98]
Decription: 
Human Starting zone wolves attacking 

How it works: 

When u attack a wolf and get near another wolf without hitting ,it also attacks (they are yellow)
How it should work: 
when u attack a wolf and get near other wolves they should not attack since they are not red (hostile) 

Source (you should point out proofs of your report, please give us some source):

**Comment by sitowsky** [comment]
Done and dusted! Fix will be implemented in the next update.
