### ISSUE TITLE
Quest [Kaw the Mammoth Destroyer] ID 11879

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#980]
Decription: There is a issue with this quest which causes the mob bugs out sometimes 

How it works: The mammoth that you use keep casting the his third ability and fearing the mob all the time and causes a reset and in some cases going into the walls 
ability ID : 46316 Thundering Roar
seems like there is a hidden ability that mammoth does it by itself with no cooldown without player command 
which there should not be such ability

How it should work: mob should not cast auto fear all the time only you should be able to cast it
also this auto fear does not put the spell Thundering Roar on cooldown 

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=S9Amt8EJ8ZU

**Comment by Dootz** [comment]
will be fixed with next server update
