### ISSUE TITLE
Halls of stone Brann bronzebeard

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#981]
Decription: Hi
Brann stops and never opens the last boss door

How it works: when you talk to the brann to run and open the last boss door for you after previous events he sometimes just stops after fighting a mob or just without reason and only a GM can kill it and reset it or open the door

How it should work: He should always get to the door and open the last door to the boss

Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment]
This happens at different spots after Brann is in combat usually.
