### ISSUE TITLE
Issue with outland(hellfire) with a tub (FPS)

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#984]
Decription: 
This might crash the server (16 fps )
so many scarabs inside of this thing .. 
Object ID : 184715
How it works: it happens when so many ppl does this quest ( npc id included in pic ) .. they disappear after while ( the scarabs ) but fps issue is still there seems like they are there ... 

How it should work: they should not cause fps problems after disappearing 
Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031818_072830](https://user-images.githubusercontent.com/36106057/37575047-34e6b76a-2b3a-11e8-938b-2bd582c04ba5.jpg)

**Comment by Dootz** [comment]
will be fixed with next server update
