### ISSUE TITLE
Quest [Besieged!]

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#985]
Decription: 
Quest  [Besieged!] ..
Invis infernal caster got issues only killing one and respawning it fixes the issue atm which only a GM can do that
id's included in the screenshots 

How it works: NPC infernals that you are suppose to kill don't spawn because of a script bug 

How it should work: they should spawn and after dying another one should fall down ( one by one )

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031918_060101](https://user-images.githubusercontent.com/36106057/37575133-cf05d920-2b3a-11e8-9eeb-b8eff526cbf5.jpg)
![wowscrnshot_031918_060053](https://user-images.githubusercontent.com/36106057/37575134-cf63dcd2-2b3a-11e8-98c2-f553f75246a4.jpg)

**Comment by Kokaina** [comment]
Confirmed, it needs to be fixed.

**Comment by Warmanesucks** [comment]
Can confirm too.  Infernal doesnt rain from the sky. Theres no mob around to kill in order to complete the quest
![wowscrnshot_041618_220908](https://user-images.githubusercontent.com/38439998/38830013-9aaf9d4c-41c3-11e8-8747-ea9abb59a9cf.jpg)

**Comment by Dootz** [comment]
Should be fixed now.
