### ISSUE TITLE
Quest  [Reconnaissance Flight]

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#986]
Decription: If you start the quest shape shifted or mounted it bugs out

How it works: If you start the quest shape shifted or mounted it bugs out and you can't land the plane the ability that lands you wont work .. since plane is not on fire ( part of scripting i assume ).. 
and even if you start it in the right way its hard to gain control you need to hold left+right click mouse together then hit the space button once then move them mouse .. which is wrong

How it should work: you should be able to start the quest in any form or mounted also .. regaining control after getting hit easily 
Source (you should point out proofs of your report, please give us some source): 
i assume this problem caused because a npc which got the control of the plane before you
Recommendation : Quest asks/forces the player to dismount + remove the shape shifted form to fix the issue .. this solution can also resolve the issue related to this quest https://github.com/SunwellTracker/issues/issues/950

**Comment by Cwiercpasiec** [comment]
Duplicate: #136

**Comment by MrTide** [comment]
Had to add my own Recommendation which is related to another quest

**Comment by Dootz** [comment]
will be fixed with next server update
