### ISSUE TITLE
Quest [Foolish Endeavors] 11705

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#988]
Decription: Hello this quest is a benchmark quest which gets high overlord saurfang involved with a quest 

How it works: Some one else can start the quest in middle of your event which causes to multiple high overlord saurfang which causes multiple issues like not getting credit

How it should work: other ppl should not be able to start the quest in middle of your quest

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031918_074413](https://user-images.githubusercontent.com/36106057/37577740-3bb9a0c0-2b49-11e8-949f-2212dc019219.jpg)

**Comment by Dootz** [comment]
https://github.com/SunwellTracker/issues/issues/688
