### ISSUE TITLE
quest: Into The Wild Green Yonder - Id 13045

### ISSUE THREAD

**Issue by MrTide** [SunwellTracker/issues#989]
Decription: You need to grab crusaders for the quest 

How it works: crusaders most of the time respawn without the web on them so you can't grab them for rescue with the proto drake .. only way to fix it .. is to ask a GM to kill and respawn them

How it should work: They should alway have web on them so you can do the quest 
ability name included on screenshot

Source (you should point out proofs of your report, please give us some source): 
![wowscrnshot_031918_084656](https://user-images.githubusercontent.com/36106057/37579216-4a2cf82e-2b52-11e8-915e-042454c4e246.jpg)
![wowscrnshot_031918_084637](https://user-images.githubusercontent.com/36106057/37579217-4a5a1624-2b52-11e8-9e03-f15ccd331f1a.jpg)

**Comment by Dootz** [comment]
will be fixed with next update
