### ISSUE TITLE
Dire Maul shortcut huge pack of mobs 

### ISSUE THREAD

**Issue by milkman227** [SunwellTracker/issues#99]
Decription: Apparently there is a huge pack of mobs at the place where you are supposed to jump off at dire maul 

How it works: when you jump the ungoro flower mobs whatever they are called 1 hit you since you're at 20hp

How it should work: they should not be there

Source (you should point out proofs of your report, please give us some source): https://www.youtube.com/watch?v=Q-OOAXz1drs
around 1min the guy jumps down the shortcut, he walks a bit and there are the flower mobs, apparently here, the flower mobs are right at the place where you jump

**Comment by Afgann** [comment]
This video is from private server, you've got any other proof?

**Comment by sitowsky** [comment]
There is not enough data in the source to confirm this as a bug.
 
Thanks in advance.
