### ISSUE TITLE
vendor Frozo the Renowned

### ISSUE THREAD

**Issue by narcoshka** [SunwellTracker/issues#990]
Decription: 
I can not find a vendor, is it there?
http://www.wowhead.com/npc=40160/frozo-the-renowned
This NPC will be added in Patch 3.3.3
How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment]
yup, that intended.

**Comment by nimeral** [comment]
Bump, Frozo is announced to come with ToC while it shouldn't.

https://www.wowhead.com/item=45087/runed-orb#comments:id=982836

_In 3.3.3, a Gnome named "Frozo the Renowned" Will come to dalaran on his flying carpet, Camping himself at Dalaran Magus Commerce Exchange, Selling Runed Orbs for 4 Frozen Orbs each._

But I personally don't care that much if you keep this **bug** in game : )
