### ISSUE TITLE
[Flying Black Qiraji Battle Tank] cast time

### ISSUE THREAD

**Issue by Fellipe23** [SunwellTracker/issues#992]
Decription: 
Wcześniej działał poprawnie, czyli cast instant oraz 3s cooldown . Bug wystąpił prawdopodobnie po dzisiejszym update.
How it works: 
Flying Black Qiraji Battle Tank posiada obecnie 1,5s cast time

How it should work: 
Flying Black Qiraji Battle Tank powinien posiadać instant cast time oraz 3s cooldown

Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/spell=31700/black-qiraji-battle-tank
http://db.darkwizard.pl/?spell=25863
http://db.darkwizard.pl/?spell=26655

**Comment by Afgann** [comment]
Zmiana zamierzona.
