### ISSUE TITLE
[Druid] Insect Swarm doesn't reduce targets chance to hit with melee and ranged hits.

### ISSUE THREAD

**Issue by lorderheller** [SunwellTracker/issues#994]
**Decription:** 

At the moment insect swarm doesn't reduce targets chance to hit with melee and ranged hits (PVP).

Link to the spell: https://db.darkwizard.pl/?spell=48468 (Effect 2 | Apply Aura: Mod Hit ChanceValue: -3)

**How it works:** 

When debuff is applied to the target, it continues to hit all the attacks without any change.

**How it should work:** 

Should reduce targets chance to hit by melee and ranged attacks by 3%,

**Source:** 

NOTE: didn't test in PVE, might work in PVE - but at the moment at least doesnt work in PVP

https://imgur.com/a/mXOXX  

https://imgur.com/a/8OAW3

**Comment by kinglobster** [comment]
still broken, fix pliz

**Comment by MrTide** [comment]
@Kokaina Hi can you check this out please
Thanks

**Comment by set-theorist** [comment]
can you test with hitcap and see if you manage to make any spells miss

**Comment by Nadiirr** [comment]
Yeah I don't think this is working.

**Comment by akrom23** [comment]
W/o Insect Swarm:
![WoWScrnShot_090619_114607](https://user-images.githubusercontent.com/1035215/64420604-ef9e0980-d09f-11e9-8330-c078a87409ba.jpg)

With Insect Swarm:
![WoWScrnShot_090619_115733](https://user-images.githubusercontent.com/1035215/64420620-f75dae00-d09f-11e9-9dfe-fbadf6ecc077.jpg)

I think you forgot about defense skill.
