### ISSUE TITLE
Quest [Test of Strength] mob - Rok'Alim

### ISSUE THREAD

**Issue by zhanjor** [SunwellTracker/issues#995]
Decription: 
bugged mob spawn and mob pathing

How it works: 

Mob spawns in semi-random location in Thousand Needles and doesn't move
How it should work: 

Mob should spawn at 26 41 and move along the mountain towards Feralas
Source (you should point out proofs of your report, please give us some source): 
http://www.wowhead.com/npc=4499/rokalim-the-pounder#comments

**Comment by Dootz** [comment]
will be fixed with next server update
