### ISSUE TITLE
[Warrior] Charge/intercept focus, auto-attack issue

### ISSUE THREAD

**Issue by Kenaowar** [SunwellTracker/issues#996]
Decription: Charge/intercept your target as warrior

How it works: When you charge or intercept your focus (not your target) You will auto-attack your focus.
To solve this issue we need to remove our target and target again...

How it should work: When you charge or intercept your Focus, you will keep auto-attacking your current target.

Source (you should point out proofs of your report, please give us some source):

**Comment by set-theorist** [comment]
confirm

**Comment by ntt1** [comment]
This bug occurs with druid's bear charge as well.

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
