### ISSUE TITLE
[Druid] Berserk doesn't reset cooldown of Mangle (Bear)

### ISSUE THREAD

**Issue by ntt1** [SunwellTracker/issues#997]
How it works: 
If Mangle (Bear) is on cooldown and you cast Berserk, the cooldown of Mangle (Bear) is not reset.

How it should work: 
When you cast Berserk it should reset the cooldown of Mangle (Bear).

Source: 
http://wowwiki.wikia.com/wiki/Berserk
http://www.wowhead.com/patchnotes=3.0.3
(Spell #50334): Now clears the cooldown on (Spell #48564).

**Comment by Dootz** [comment]
will be fixed with next server update
