### ISSUE TITLE
Cheat Death - Subtlety Rogue

### ISSUE THREAD

**Issue by stabo** [SunwellTracker/issues#998]
**Decription:** 
Hi, talent in Subtlety tree Cheat Death doesn't work. Cheat Death proc, but all dmg after it has normal dmg, no 90% (modified by resilience) reduce for 3sec. 

**How it works:** 
It help with not dying, but not with reduce dmg after talent proc. 
It does left me on 10% of my HP, so this part it is fine.

**How it should work:** 
It should stop dying, and reduce dmg for 90% for 3 sec and left me on 10% of my health.

**Source** (you should point out proofs of your report, please give us some source): 
Description of talent.

**Comment by Cwiercpasiec** [comment]
How much resilience do you have?
http://wowwiki.wikia.com/wiki/Cheat_Death_(rogue_talent)
Patchnote says: The damage reduction will be four times the damage reduction resilience causes against critical strikes.
As far as I know Cheat Death works fine for PvP geared Rogues.

**Comment by Azathothh** [comment]
I've tested it with resilience items and without them, seems to work fine.
