### ISSUE TITLE
[Wintergrasp] Tenacity

### ISSUE THREAD

**Issue by 0vertime** [SunwellTracker/issues#999]
Tenacity seems to only work when the lower faction has under 40 players in raid. After multiple raids it seems to stop working.

I've been checking /who z-"Wintergrasp" on multiple games, for example when theres 130 vs 150, we should have 2 tenacity for every +10 being 1, never had.

**Comment by Cwiercpasiec** [comment]
Source? All I found is this: "The algorithm for how many stacks to apply is unknown, although a previous hotfix[1] has indicated that only characters level 70 and higher are counted.

There are proponents both for linear stacking (stacks = C * (x-y), for some value C) and exponential stacking (stacks = 10x/y). More research is needed."
http://wowwiki.wikia.com/wiki/Tenacity_(Wintergrasp)
Also there shouldn't be so much players, Wintergrasp should have limit of 120 players per faction.

**Comment by Piootrek** [comment]
There is no source in this report. Please find a source(proof) and report bug properly once again.

Thanks in advance.
